### ISSUE TITLE
Component: Accordion

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#10]
https://github.com/Esri/calcite-web/issues/1015

**Comment by paulcpederson** [comment]
adding myself to this as I'm going to give the ol' accordions a shot 🎹 🎶

**Comment by paulcpederson** [comment]
@julio8a no, haven't been able to go tackle this yet

**Comment by macandcheese** [comment]
I'll take a look at this today

**Comment by macandcheese** [comment]
Added in https://github.com/Esri/calcite-components/issues/10
