### ISSUE TITLE
Bug: Dropdown calciteDropdownClose event not triggering on button click

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#1003]
### Summary
The event `calciteDropdownClose` triggers when an item is selected or when the user clicks outside of the dropdown, but the event doesn't trigger when the button (slot: dropdown-trigger) is clicked.

### Code Example
<img width="657" alt="Screen Shot 2020-09-17 at 10 15 55 AM" src="https://user-images.githubusercontent.com/55154968/93501290-7bad5880-f8d2-11ea-9a82-a3687842a2e2.png">

**Comment by macandcheese** [comment]
@joeyHarig addressed in https://github.com/Esri/calcite-components/pull/1319 - assigned to you for verification after merge to master.
