### ISSUE TITLE
Tooling: @types cause Node context to leak into source

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1004]
### Background 

Node types are leaking into component source. For example:

```ts
    const foo: number = setTimeout(() => {}, 1000);
```

Will throw an error because of incompatible types (`NodeJS.Timeout` vs `number`).

### Desired Outcome 

No Node types in component source.

**Comment by jcfranco** [comment]
https://github.com/ionic-team/stencil/commit/1a907f784f58463cfe52f87518f1a1d38a2908e5 may fix this.

**Comment by julio8a** [comment]
Is this issue still valid?

**Comment by jcfranco** [comment]
Still valid.

**Comment by jcfranco** [comment]
Installed! Now, global interval and timeout methods resolve to the right type as they are called from their corresponding context object. The original issue will still arise whenever the global methods are called directly as TS will resolve them using Node's global declarations (pulled in by `jest` dependencies) (see https://github.com/microsoft/TypeScript/issues/842#issuecomment-301228428).

**Comment by benelan** [comment]
verified on master
