### ISSUE TITLE
chore(tooltip): Add unit test for triggering tooltip from combinations of hover/focus

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1006]
### Description

Enhancement: Tooltip - Add unit test for triggering tooltip from combinations of hover/focus

### Acceptance Criteria 

Unit tests

### Relevant Info 

https://github.com/Esri/calcite-components/pull/1005

#### Which Component

Tooltip

#### Example Use Case

Tooltip triggered from focus and then hover and vice versa

**Comment by jcfranco** [comment]
Verified!
