### ISSUE TITLE
Bug: calcite-button width=full not working inside calcite-dropdown

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1012]
### Summary
Upgraded from beta.38 to beta.39, now the `calcite-button` inside `calcite-dropdown` is not wide enough anymore. Using `calcite-button` outside of `calcite-dropdown` is fine.

<img src=https://user-images.githubusercontent.com/44481292/93641911-fbf6bb00-f9b1-11ea-906e-9a10add26fc9.png width=200/>

![image](https://user-images.githubusercontent.com/44481292/93640499-87bb1800-f9af-11ea-829b-f62972e70a50.png)

the dropdown seems to have the correct width
![image](https://user-images.githubusercontent.com/44481292/93641827-d1a4fd80-f9b1-11ea-9fcb-ec42d5cb063e.png)

button CSS
<img src=https://user-images.githubusercontent.com/44481292/93641848-dec1ec80-f9b1-11ea-89c8-51c9749ca4f3.png width=150/>

### Reproduction Steps

**beta 39**
https://codepen.io/jcfranco-the-scripter/pen/abNRJoK?editors=1000

**beta 38**
https://codepen.io/jcfranco-the-scripter/pen/ZEWqeEX?editors=1000

**Comment by jcfranco** [comment]
@AdelheidF I added repro cases to the description. 😄

**Comment by jcfranco** [comment]
@driskull Can you take a look? I think the dropdown + popper changes may have affected it.

**Comment by driskull** [comment]
@asangma or @macandcheese do you think you could take this one? I'm not sure the best way to update the css display. Seems like it might need to use some flexbox.

**Comment by macandcheese** [comment]
Yeah I can take a look and see what changed.

**Comment by driskull** [comment]
The only thing that changed is that now the button is put into another container. but having both containers as display:inline-block won't work

**Comment by macandcheese** [comment]
Ok, little bit of flexbox solved it... to confirm, a user will still need to wrap the dropdown in a 100% width container like in your above examples (would no longer need to set 100% width on the dropdown):

```
<style>
  .test-width-container {
    border: 1px dashed blue;
    display: flex;
    width: 100%;
  }
  .test-width-container calcite-dropdown {
    border: 1px dashed red;
  }
</style>

<div class="test-width-container">
  <calcite-dropdown>
    <calcite-button width="full" slot="dropdown-trigger">Scale S small</calcite-button>
    <calcite-dropdown-group group-title="View">
      <calcite-dropdown-item icon-start="list-bullet" active>List</calcite-dropdown-item>
      <calcite-dropdown-item icon-start="grid">Grid</calcite-dropdown-item>
      <calcite-dropdown-item icon-start="table">Table</calcite-dropdown-item>
    </calcite-dropdown-group>
  </calcite-dropdown>
</div>
<div class="test-width-container">
  <calcite-dropdown>
    <calcite-button slot="dropdown-trigger">Scale S small</calcite-button>
    <calcite-dropdown-group group-title="View">
      <calcite-dropdown-item icon-start="list-bullet" active>List</calcite-dropdown-item>
      <calcite-dropdown-item icon-start="grid">Grid</calcite-dropdown-item>
      <calcite-dropdown-item icon-start="table">Table</calcite-dropdown-item>
    </calcite-dropdown-group>
  </calcite-dropdown>
  some text
</div>
```

<img width="1124" alt="Screen Shot 2020-09-18 at 7 29 32 PM" src="https://user-images.githubusercontent.com/4733155/93657197-53624e80-f9e5-11ea-8903-2fb349368c1a.png">

**Comment by AdelheidF** [comment]
Is working again with `1.0.0-next.7`

<img src=https://user-images.githubusercontent.com/44481292/93819554-ba178000-fc10-11ea-8f5f-c93f8e4e5661.png width=200/>

**Comment by nwhittaker** [comment]
@driskull or @macandcheese, adding `flex-grow: 1`[1] for this issue caused a regression in the Field Maps web app with how some of our overflow buttons are positioned (see https://github.com/ArcGIS/field-apps-web/issues/1209).

These buttons are inside a `flex` layout, so they're now expanding to fill out the available space of the container instead of hugging their content. Since the default value for the `flex-grow` style is `0`, it's unexpected to see the buttons grow within a flex layout on their own.

Thoughts on if this should be considered a regression in Calcite? If so, should I create a new issue?

[1] https://github.com/Esri/calcite-components/pull/1013/files#diff-717513f97b6ede6d16b1ad91d26a20deb137955e0743cfebf03b776d4c46a789R4

**Comment by macandcheese** [comment]
@nwhittaker can you open a new issue so we can track this? And link this issue so if it's determined a change is needed on our end we don't undo this fix. Thanks!

**Comment by nwhittaker** [comment]
>@nwhittaker can you open a new issue so we can track this?

Added https://github.com/Esri/calcite-components/issues/1232 for this.
