### ISSUE TITLE
Enhancement: Notice - Add "gray" color option to notice

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1014]
### Description
Add "gray" as a color option for the notice component

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/93815450-9a398980-fc1b-11ea-8ad4-31a1b914e787.png)

**Comment by macandcheese** [comment]
Valid

**Comment by macandcheese** [comment]
Valid

**Comment by bstifle** [comment]
Valid

**Comment by macandcheese** [comment]
Valid
