### ISSUE TITLE
Bug: calcite-date / no change event when changing the year inside calendar title

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1017]
### Summary
When changing the number of the year here it won't call a change event (calciteDateChange). Even if I then click outside of that input box.

<img src=https://user-images.githubusercontent.com/44481292/93818323-14174600-fc0f-11ea-9c94-a5a6b01c50ed.png width=200/>

The change event is called when I change the year inside the input or when I click on a day number.

<img src=https://user-images.githubusercontent.com/44481292/93818421-33ae6e80-fc0f-11ea-926a-f800f5853ee3.png width=200/>

### Reproduction Steps

1.

**Comment by paulcpederson** [comment]
This should be in the latest release.

**Comment by AdelheidF** [comment]
verified it locally
