### ISSUE TITLE
Enhancement: Update shadow variables for level 1 and 2

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#1018]
![image](https://user-images.githubusercontent.com/14083530/93826550-15576b80-fc2d-11ea-9f7b-3b7942cf2fca.png)
![image](https://user-images.githubusercontent.com/14083530/93826585-2902d200-fc2d-11ea-80e7-1234f89d43c6.png)

**Comment by macandcheese** [comment]
Closing as this should be taken care of in the Tailwind PR
