### ISSUE TITLE
Enhancement: Tile Select Group Docs - show example of vertically stacked tiles

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1020]
### Description
The tile select group is capable of being displayed vertically / stacked - but browsing the component Storybook that's not apparent. 

### Acceptance Criteria 
Add a story that shows how that could work.

**Comment by kat10140** [comment]
close? @macandcheese

**Comment by paulcpederson** [comment]
@kat10140 no there is still no docs for this. I think it's still valid

**Comment by caripizza** [comment]
I just added the layout prop with vertical/horizontal options to calcite-tile-select-group's stories in [pr #2129](https://github.com/Esri/calcite-components/commit/6b11306795722992521380a585b23d3ca5bca270#diff-76fd18f9bc59ea94cb1a711630cc9dc1b58277b25fe4987a188a78db020daf9fR17). Can someone on check it out and close this one if the updated stories suffice?

**Comment by caripizza** [comment]
Closing this one. As of beta.56, Tile Select Group has both Light/Dark stories which allow the component to be viewed in vertical layout ([via knob](https://esri.github.io/calcite-components/?path=/story/components-tiles-tile-select-group--light)).
