### ISSUE TITLE
Enhancement: Tile Select - add a "spaced" variant

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1021]
### Description
Some WIP designs call for a spaced example for tile select :

### Acceptance Criteria 
Add an opt-in prop that allows for this. The above WIP screenshots show slightly different styling - our styling, border, etc., should be maintained. 
![Bitmap](https://user-images.githubusercontent.com/4733155/93913860-85f89980-fcba-11ea-8eb5-c38a0f706c7c.png)
![Bitmap2](https://user-images.githubusercontent.com/4733155/93913864-87c25d00-fcba-11ea-90c1-af74a5ee032d.png)

Use space-between to ensure the tile items fill 100% of the container and do not create gutters at far left / right for alignment.

Perhaps this necessitates a "horizontal" alignment? Not sure...

**Comment by kat10140** [comment]
@macandcheese can this be closed?

**Comment by macandcheese** [comment]
No, still valid, just low priority.

**Comment by julio8a** [comment]
Those designs look good!

**Comment by macandcheese** [comment]
Closing.
