### ISSUE TITLE
Enhancement: Add `valueAsNumber` to calcite-input

### ISSUE THREAD

**Issue by codylawson** [Esri/calcite-components#1025]
### Description
The `input` HTML spec shows a property called `valueAsNumber`, we should expose this prop on the `calcite-input`.

### Acceptance Criteria
Expose `valueAsNumber` from native `input` el in `calcite-input`.

### Relevant Info
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

#### Which Component
`calcite-input`

#### Example Use Case
A `calcite-input` with `type="number"` requires users to `parseInt()` the `value` prop to get a number.

**Comment by eriklharper** [comment]
@codylawson can you explain your use case for this a bit more?  It sounds like you just need to be able to read (not write) the `valueAsNumber` property, correct?

**Comment by codylawson** [comment]
@eriklharper That's correct, this would just be to store the value in local state. By default input `value` is a string, even if the input type is `number`, meaning you have to `parseFloat` or similar to get the proper value. My recommendations was to just follow the dom api standard and expose `valueAsNumber` as well.

**Comment by driskull** [comment]
Would we want to expose 'childEl' as something and let the user access things like `valueAsNumber` and `valueAsDate`?

**Comment by codylawson** [comment]
@driskull I think that would be acceptable as well.

**Comment by driskull** [comment]
I'm just trying to avoid having to duplicate native input logic for these things

**Comment by eriklharper** [comment]
> Would we want to expose 'childEl' as something and let the user access things like valueAsNumber and valueAsDate?

On board with this idea, because like you said we would have to duplicate all the native properties otherwise.

**Comment by driskull** [comment]
@eriklharper @jcfranco I'm not sure if we can add a readOnly property like this. Seems like we would have to use a method. Is that correct?

**Comment by eriklharper** [comment]
> @eriklharper @jcfranco I'm not sure if we can add a readOnly property like this. Seems like we would have to use a method. Is that correct?

When you say "readOnly" property, are you talking about the idea of exposing the `childEl` or the `valueAsNumber` property?

**Comment by driskull** [comment]
childEl prop

**Comment by eriklharper** [comment]
A method could work, which would return the input element, but I was thinking just a plain ol javascript getter (POJG? lol) which we could maybe call `input` perhaps since that _is_ the actual input?

**Comment by driskull** [comment]
I'm not sure it would get added unless it has the prop decorator though.

**Comment by eriklharper** [comment]
I'll look into if this is possible, and even consult the Stencil Slack peeps to see what they think.

**Comment by driskull** [comment]
Yeah I opened a support issue and didn't realize we had opened one before about this. :(

**Comment by julio8a** [comment]
This one still valid?

**Comment by eriklharper** [comment]
> This one still valid?

As long as the need still exists to have this, then this issue is still valid.  We are planning at some point deprecating calcite-input's `type` property in favor of individual components for each type, which would include number in this case, but it is still  being discussed and issues still need to be created and prioritized to make that happen.

We should include this ticket as a requirement on the new `calcite-input-number` component.  @jcfranco thoughts?
