### ISSUE TITLE
Tooling: Release notes commit links 404

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#1026]
## Summary 

https://github.com/Esri/calcite-components/releases/tag/v1.0.0-beta.40

Release notes have links to PRs (working) and commits (not working).

## Measure of Success 

Links to commits should go to a commit.

Or links to commits could be removed.

### Resources 

Bug might be in gh-release or in the calcite-components implementation of the library.

**Comment by jcfranco** [comment]
Thanks for reporting this. I suspect this is caused by our [changelog helper script](https://github.com/Esri/calcite-components/blob/master/support/ensureNonPrereleaseChangelog.ts).

**Comment by jcfranco** [comment]
Installed! @gpbmike Could you help verify?

**Comment by gpbmike** [comment]
@jcfranco can i reserve judgement until beta 41 is released? 😄

**Comment by jcfranco** [comment]
You sure can, thanks!

**Comment by jcfranco** [comment]
@gpbmike FYI, beta 41 was officially released a few moments ago. 🚀

**Comment by gpbmike** [comment]
Looks good to me!
