### ISSUE TITLE
Enhancement: ShellPanel - bring height-scale back.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1029]
### Description
`height-scale` in Panel can cause UI bugs if Panel uses that property and is in a non-detached ShellPanel.
Also "microapps" won't know if they're putting a Panel into a detached ShellPanel or not.

Adding `detached-height-scale` to ShellPanel would help this.
It was removed to simplify things conceptually by only having this property on Panel, but the reality of the "mirco apps" using calcite-components and then being rendered inside a "macro app" means that this simplification complicates things.

An adjacent benefit would be a reduced amount of app refactoring.

cc @driskull @jcfranco @macandcheese 

#### Which Component
ShellPanel

**Comment by asangma** [comment]
@kat10140 Please verfee when you have a minute.

**Comment by driskull** [comment]
@kat10140 can this be closed?
