### ISSUE TITLE
Enhancement: New slot for dialog in calcite-modal

### ISSUE THREAD

**Issue by nathan-barrett** [Esri/calcite-components#1033]
### Description

would be nice to have a specific slot to use when using a alert or dialog box within calcite-modal. Currently I have been using the `back` slot for a `calcite-alert`

#### Which Component
`calcite-modal`
#### Example Use Case

![usecase](https://user-images.githubusercontent.com/30009669/94212952-70d26500-fe8a-11ea-8df0-0dec7a6fe014.png)

**Comment by bstifle** [comment]
![2](https://user-images.githubusercontent.com/14083530/94308473-345f4180-ff3c-11ea-89c5-b7c1ef220582.png)

hi @nathan-barrett  we'll most likely be doing something more like this for the modals just so you know :)

**Comment by nathan-barrett** [comment]
@bstifle - looks good, thank you!

**Comment by nathan-barrett** [comment]
Also, sorry took me so long to take a look at this!

**Comment by bstifle** [comment]
no worries! we'll work on getting this in!

**Comment by evanmosby** [comment]
+1 ArcGIS Monitor team's looking forward to it

**Comment by macandcheese** [comment]
@evanmosby does this issue address this need? https://github.com/Esri/calcite-components/issues/2801

**Comment by evanmosby** [comment]
@macandcheese - Yes I believe so, especially as you described it here https://github.com/Esri/calcite-components/issues/2801#issuecomment-900441403

**Comment by macandcheese** [comment]
@evanmosby thanks, closing this one. Feel free to re-open or re-submit if the above feature doesn't end up working for you.
