### ISSUE TITLE
Bug: Calcite-input not accepting all time values for Start/End time

### ISSUE THREAD

**Issue by lau11123** [Esri/calcite-components#1035]
### Summary
When values within 12:00-12:59 AM are typed or keyed, using the arrow keys, into the Start/End time calcite-input in the Time slider options panel, the calcite-input goes blank and a format warning appears in the console. Eventually times within 12:00-12:59 AM are accepted, but it can sometimes take more than 5 tries. These are valid values and should be accepted in Map Viewer Beta's time animation.

Warning:
![image](https://user-images.githubusercontent.com/71884380/94272017-78d4e800-ff10-11ea-9c82-e1b499422ea4.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/71884380/94272420-0adcf080-ff11-11ea-9759-b3bf06822b4e.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/71884380/94272479-1cbe9380-ff11-11ea-96e9-bbf87f33c4c5.png)

### Reproduction Steps
1. Open the above map in Map Viewer Beta
2. Open the Time slider options panel
3. Open the browser debugger
4. Set the Start time to 12:00 AM - see that the time editor goes blank and that there's a format warning in the console
5. Set the End time to 12:00 AM - see that the time editor goes blank and that there's a format warning in the console
6. Keep entering values within 12:00-12:59 AM until it is accepted

### Relevant Info 
- Issue occurs in Chrome and Microsoft Edge
- Issue does not seem to occur in FireFox

**Comment by macandcheese** [comment]
Hi @lau11123  - I'm struggling to find how to "open the time slider options panel" - any tips?

**Comment by lau11123** [comment]
@macandcheese Click Map properties on the left toolbar then under Time click Time slider options. Should have made that clearer, sorry.

**Comment by macandcheese** [comment]
No problem, I am not sure I have permissions to view that unfortunately, all I see under Map Properties is a link to "item details". I have tried my devext login and a few others but I don't seem to be able to login.

**Comment by lau11123** [comment]
Interesting. The map and layer are public. Try my login: lauren_devtest/lauren_devtest1CT. Can you see Time slider options with my account?

**Comment by macandcheese** [comment]
Yes that worked, thank you (you can delete your comment if you want to hide credentials since this repo is not behind auth).

I see the issue inside of map viewer in the console and in the UI, where it takes a few tries to work, but I can't reproduce in isolation: https://jsbin.com/cokusecopi/edit?html,output

Is there another library interpreting the contents of the input?

**Comment by lau11123** [comment]
@macandcheese I reached out to Kevin Doshier to clarify if there was another library interpreting the contents of the input, and he actually found the problem. The formatter we use to format time returns 24:00 for midnight, but the Time component does not accept that it only accepts "00:00" for midnight, so he's put a fix in to convert 24:00 to 00:00. Thanks for you help.

Closing this.
