### ISSUE TITLE
Enhancement: PickListItem and ValueListitem. Add start slot. Deprecate secondary-actions

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1039]
### Description
* Add a slot to add content to the start side: `actions-start`
* Add a slot to add content to the end side. `actions-end`
* Route `secondary-actions` content to  `actions-end`?
* ~Deprecate~ Remove `secondary-actions`

cc @jcfranco @driskull 

#### Which Component
* ValueListItem
* PIckListItem

#### Example Use Case
In general, a way to have a lane on the start side would be useful.

**Comment by asangma** [comment]
@kat10140 Verfee!

**Comment by jcfranco** [comment]
Verified locally.
