### ISSUE TITLE
Research: Provide an event when calcite-popover has been added to the DOM

### ISSUE THREAD

**Issue by dhrumil83** [Esri/calcite-components#1060]
### Background 
Trying to focus does not work without timeout since the content isn’t on the DOM yet when popover is doing its initial setup.

![image](https://user-images.githubusercontent.com/14285436/94954892-966cf900-049e-11eb-8d16-20c6185cb724.png)

```
componentDidLoad(): void {
    this.closeButtonNode.setFocus();
}
```

Works with timeout:
```
componentDidLoad(): void {
    setTimeout(() => {
      this.closeButtonNode.setFocus();
    }, 100);
}

```

### Desired Outcome 

Maybe calcite-popover can hook into Popper’s lifecycle and provide an event or callback when its content has been positioned.

**Comment by AdelheidF** [comment]
@driskull I don't think this is completed... Praveen ran into the issue that he's faster than our (randomly selected) timeout to set the focus on the close button and so whatever he clicked on looses its focus.

**Comment by driskull** [comment]
@AdelheidF is there an issue with more information?

If you are rendering in stencil you can call its `forceUpdate` utility function to force rendering before calling setFocus

**Comment by AdelheidF** [comment]
related: https://github.com/Esri/calcite-components/issues/5369

**Comment by driskull** [comment]
Just for clarity here, `calcitePopoverOpen` can be listened to to know if the popover is opened.
