### ISSUE TITLE
Enhancement: Allow image in calcite-tile-select 

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#1062]
### Description
It would be useful to have a thumbnail/image slot for calcite-tile-select similar to the design in calcite-card.

### Acceptance Criteria 
The component can be set up to look similar to this calcite-card design https://esri.github.io/calcite-components/?path=/story/components-card--footer-links

#### Which Component
calcite-tile-select

#### Example Use Case
I'm using the calcite-tile-select in selectable mode and it would be good to have the same design you see in the above calcite-card design for a list of selectable AGOL items.

**Comment by macandcheese** [comment]
This is possible with https://developers.arcgis.com/calcite-design-system/components/tile/#component-api-slots - please follow up if that does not satisfy requirements @noahmulfinger.
