### ISSUE TITLE
Bug: A few problems with calcite-checkbox 

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#1064]
### Summary
I've found a few different problems with calcite-checkbox. I'm grouping them into this one issue but I can separate them out if needed.

### Actual Behavior

1) When you pass in a checkbox (as shown in the README example), the formatting is off and the checkbox is not clickable~
2) When wrapped in a label that has the `for` attribute, the checkbox is not clickable
3) When you hit Space, the checkbox flashes as selected, but the becomes deselected.

### Expected Behavior
In all cases the styling should be consistent and functionality should match the native checkbox.

### Reproduction Steps

See codepen: https://codepen.io/noahmulfinger/pen/KKzLLQp

**Comment by eriklharper** [comment]
~When you pass in a checkbox (as shown in the README example), the formatting is off and the checkbox is not clickable~
☝️ this is no longer supported, and the docs were just updated recently to remove instructions for this.

- [x] When wrapped in a label that has the `for` attribute, the checkbox is not clickable
- [x] When you hit Space, the checkbox flashes as selected, but the becomes deselected.

**Comment by noahmulfinger** [comment]
@eriklharper I'm still seeing the Space issue in beta.46. Still reproducible in my original Codepen.
