### ISSUE TITLE
Bug:  Safari -  calcite-date's focus out handler gets triggered when clicking the next/prev arrows

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#1069]
Found testing in Map Viewer Beta. 
In safari, calcite-date's focus out handler gets triggered when clicking the next/prev arrows and they don't work as expected. 
![image](https://user-images.githubusercontent.com/50747646/95238775-d98cdc00-07be-11eb-815f-de4cb0481895.png)

Calcite repo from @jcfranco 
https://esri.github.io/calcite-components/?path=/story/components-date--simple

cc @paulcpederson

**Comment by paulcpederson** [comment]
Looked into this a bit, seems like safari moves focus to the body as soon as you click these buttons? Which is fairly ridiculous, not totally sure the best workaround.

**Comment by paulcpederson** [comment]
@zaramatheson this should be fixed in beta.42

**Comment by jcfranco** [comment]
Closing, based on ☝.

@zaramatheson Please create a new issue if anything else comes up. Thanks!
