### ISSUE TITLE
Component: Inputs

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#107]
Opening a placeholder issue for inputs - we'd likely want to incorporate validation options, and associated messaging / error styles into this for consistency. Style wise, we'd likely have a default input field, similar to current ones, and a "minimal" option, and improvements to placeholder, label, spacing over current inputs.

**Comment by macandcheese** [comment]
@paulcpederson agreed, maybe even some option for displaying as "drag and drop well". 

What do we want this to look like? 
- How should labels be handled - prop, slot, etc...

```
<calcite-input 
    type="text/textarea/file" 
    status="idle/success/error/warning/general"
    status-message="message text"
    status-message-type="inline/floating"
    validation-status="idle/success/error/warning"
    required
/>
```

- required could come with some kind of styling / indication
- validation status could display in line, independently of a message shown - should accommodate for overlap with password browser extensions

Should we offer an optional wrapper for displaying aggregated formset level-messages, "Please complete the required fields" ?

**Comment by paulcpederson** [comment]
it may be worth looking at how the different platforms manage input validation, I know that Angular 2.0 has a specific syntax for how these attrs should be added.

**Comment by paulcpederson** [comment]
I don't think this component should be concerned with aggregate errors. The input should only be concerned about itsself.

**Comment by macandcheese** [comment]
I don't think we should validate anything, just allow updates to that prop for the purpose of displaying errors

**Comment by paulcpederson** [comment]
Yeah, I agree it's on app devs to validate their own inputs, for sure. For reference here is what angular calls this stuff: 

| State	| Class if true	| Class if false |
| ----- | ------------- | -------------- |
| The control has been visited. | `ng-touched` | `ng-untouched` |
| The control's value has changed. | `ng-dirty` | `ng-pristine` |
| The control's value is valid. | `ng-valid` | `ng-invalid` |

- Could be useful to add `loading` as well (show a loader in the input for things like searching for geocode results).
- We often need the ability to add a search icon (and semantically have the input be a search input).
- Status message as a prop means you can't have a link in there like, "this value could cause problems, [learn more]". 

We could add more control over messages by using a subcomponent maybe? Less eloquent but, IDK it might help:

```
<calcite-input value="cows" invalid>
  <calcite-input-message>You can't use the term "cows" here</calcite-input-message>
</calcite-input>
```

IDK that's kind of weird...

**Comment by paulcpederson** [comment]
Another nice-to-have would be to allow devs using the component programmatically to set a validator function so that when they return false we set the correct prop/show the message, etc for them:

```js
var input = document.createElement("calcite-input")
function checkInput (value) {
  return value && value.length > 3;
}
input.validator = checkInput;
```

**Comment by ajturner** [comment]
We're exploring calcite components for some uses in Hub. I ran into missing `<input/>` right away. While it's great Calcite has a lot of more advanced components like range sliders - there is a fundamental need for the basics for devs to start using. Inputs, Text, Lists, etc.

**Comment by macandcheese** [comment]
Hi @ajturner - there's currently an open draft PR for input, needs a little more work but should be ready to go soon. Feel free to check it out and provide feedback on design or functionality: https://github.com/Esri/calcite-components/pull/248

Re: lists and text - could you expand on that a little? We know there's a need for layout / text rhythm helpers for more editorial type of content but haven't decided the best place for that. We've been leaning towards a set of helper classes in 'Calcite-base', but would like to hear more about your use cases. Thanks!
