### ISSUE TITLE
Enhancement: Make Calcite-Value-List-Item fully draggable

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1073]
@Csmith246 commented on [Wed Sep 23 2020](https://github.com/Esri/calcite-app-components/issues/1064)

### Description

In configurable apps, we are using the Calcite Value List in a component in our configuration experience. We have received feedback through holistic testing that many users find the drag and drop functionality with the Value List Items confusing. They don't like that the Value List Items can only be moved by using the 6 dots icon on the left side of the element. They have instead expressed a desire for the entire Value List Item to be draggable. So no matter where you "click and hold" on the Value List Item, it starts the dragging behavior.

For context, here is what it looks like now. We think it would be best if the entire value list item were draggable.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/22039422/94075657-6f346e80-fdb0-11ea-96a7-6a978af0ce6b.png)

### Acceptance Criteria 
The entire Value List Item is made to be draggable, instead of just using the 6 dots.

#### Which Component
Calcite Value List, and Calcite Value List Item

**Comment by jcfranco** [comment]
Adding @asangma for his UXpertise™.

**Comment by asangma** [comment]
This was the original behavior.
It however causes issues with keyboard navigation and as such causes a11y issues.

**Comment by asangma** [comment]
I could see a simple draggable list component or version of this component which is focused on arranging stuff in a list or among lists.

**Comment by Csmith246** [comment]
@asangma I think that would fit in exactly with what we need. 

If you look at the "Position Manager" section in this [blog post](https://www.esri.com/arcgis-blog/products/arcgis-online/announcements/whats-new-in-configurable-apps-september-2020/) that is what we are using this component for. Specifically, arranging items, within and between lists, through dragging. The action of "drag and drop" should be central to how users interact with the interface.

**Comment by kellyhutchins** [comment]
@asangma  do you know what accessibility issues occurred when the item was fully draggable? Just curious because we may need to create our own component to handle this behavior if the calcite component stays as-is and just curious about issues we might face.

**Comment by Csmith246** [comment]
@jcfranco @asangma  Hey guys, Would you guys be able to tell me what the potential plan is for this going forward? Do you think that this use case warrants a brand new calcite component, or are we going to try to make new configurability options for the `Calcite-Value-List` to handle this? Either way, I have some availability in the coming weeks, and am willing to get involved in the development for this

cc @kellyhutchins

**Comment by julio8a** [comment]
Is this issue still valid?

**Comment by Csmith246** [comment]
I think this issue can be closed now

**Comment by jcfranco** [comment]
Thanks. Closing!
