### ISSUE TITLE
Bug: calcite-block-section and intlExpand/intlCollapse

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1074]
@AdelheidF commented on [Wed Sep 09 2020](https://github.com/Esri/calcite-app-components/issues/1062)

### Summary

The documentation has these `intlExpand` and `intlCollapse` properties for `calcite-block-section`, but the labels don't seem to appear.
https://github.com/Esri/calcite-app-components/tree/master/src/components/calcite-block-section

You can see this in the story book as well.
https://esri.github.io/calcite-app-components/?path=/story/components-calcite-block--basic

### Reproduction Steps

1.

**Comment by jcfranco** [comment]
Installed. 

@AdelheidF could you verify when you try out `@next`? 🙇‍♂️

**Comment by AdelheidF** [comment]
works fine now, tested locally
