### ISSUE TITLE
Enhancement: Ability to set orientation (vertical/horizontal) on calcite-action-bar

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1075]
@nel11211 commented on [Tue Aug 18 2020](https://github.com/Esri/calcite-app-components/issues/1057)

### Description
The [arcgis-charts-components](https://devtopia.esri.com/WebGIS/arcgis-charts/tree/master/packages/arcgis-charts-components) package implements the calcite-action-bar component as a UI for chart interaction. Each chart component in this package will allow the consumer to designate a position for the action bar to be displayed beside the chart. This looks fine with the current action bar for `start` and `end` positions, but `top` and `bottom` shouldn't have a vertical bar. e.g.

![image](https://user-images.githubusercontent.com/66378014/90557443-57355380-e14f-11ea-8414-99a5dd0a3963.png)

In order to display the calcite-action-bar neatly along the top or bottom of the chart component, something like an `orientation` property that can be set as `horizontal` or `vertical` on the calcite-action-bar would be helpful.

### Acceptance Criteria 
Added `orientation` property to calcite-action-bar to designate a vertical or horizontal render.

#### Which Component
[calcite-action-bar](https://github.com/Esri/calcite-app-components/tree/master/src/components/calcite-action-bar)

**Comment by driskull** [comment]
@asangma would we want to do this?
