### ISSUE TITLE
Research: Automatically create notes for component dependencies

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1078]
@jcfranco commented on [Fri Feb 14 2020](https://github.com/Esri/calcite-app-components/issues/829)

### Background 

Components from top-level stories should have their note sections automatically generated.

### Desired Outcome 

The `readme.md` for each component lists its component dependencies. Each one should have a corresponding section under the `Notes` tab.

**Comment by julio8a** [comment]
Still valid?
