### ISSUE TITLE
Bug: tip-manager spacing weird

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1081]
@kat10140 commented on [Fri Aug 23 2019](https://github.com/Esri/calcite-app-components/issues/218)

### Summary
Spacing looks different:

Chrome 👇
<img width="1669" alt="63472058-d3566780-c425-11e9-930d-e955b0351b04" src="https://user-images.githubusercontent.com/48069902/63624443-2f012c00-c5b1-11e9-879d-c0b1e83c58e0.png">

Edge 👇
<img width="1317" alt="63472059-d3566780-c425-11e9-9ec4-7e63b5f6a053" src="https://user-images.githubusercontent.com/48069902/63624454-3b858480-c5b1-11e9-9d0c-a5d7110766c6.png">

**VM Win 10 + FF (68)**
- No focus outlines
`calcite-tip-manager`
- Same spacing issue mentioned above.

**VM Win 10 + Chrome**
`calcite-tip-manager`
- Same spacing issue mentioned above.

### Reproduction Steps

1. go to https://esri.github.io/calcite-app-components/demos/calcite-tip-manager.html 

---

@kat10140 commented on [Fri Sep 20 2019](https://github.com/Esri/calcite-app-components/issues/218#issuecomment-533714955)

@asangma made any progress on this?

---

@asangma commented on [Wed Oct 02 2019](https://github.com/Esri/calcite-app-components/issues/218#issuecomment-537608484)

I need help understanding the issue. 

---

@kat10140 commented on [Wed Oct 02 2019](https://github.com/Esri/calcite-app-components/issues/218#issuecomment-537628405)

actually the spacing seems to be fine/consistent on my windows machine on all browsers. @jcfranco i believe you found this bug at the testing party, any comment?

---

@jcfranco commented on [Wed Oct 02 2019](https://github.com/Esri/calcite-app-components/issues/218#issuecomment-537662168)

Note the text alignment is off in Edge. There is a different font-family being used there, so I'm not sure if that's the culprit.

**FF/Chrome/Safari**

<img width="1659" alt="Screen Shot 2019-10-02 at 1 07 14 PM" src="https://user-images.githubusercontent.com/197440/66077957-ea54a300-e515-11e9-8eaa-9fcf562f6ee7.png">

**Edge**

<img width="1653" alt="Screen Shot 2019-10-02 at 1 07 31 PM" src="https://user-images.githubusercontent.com/197440/66078014-05271780-e516-11e9-893c-5401c9ad0abb.png">

---

@kat10140 commented on [Wed Oct 02 2019](https://github.com/Esri/calcite-app-components/issues/218#issuecomment-537669488)

OH i see what you mean now. I don't think it's a font thing bc Chrome/FF/Edge are all the same arial looking font on Windows, but Edge does have that different alignment.

---

@asangma commented on [Wed Oct 02 2019](https://github.com/Esri/calcite-app-components/issues/218#issuecomment-537676283)

Looks like Edge *is* getting the wrong font tho.

---

@kat10140 commented on [Wed Oct 02 2019](https://github.com/Esri/calcite-app-components/issues/218#issuecomment-537697784)

Ok, all windows browsers look like they're getting that same font as Edge is all i'm sayin, so we'll have to think about those as well

**Comment by bstifle** [comment]
@asangma do you have an eta on this?

**Comment by julio8a** [comment]
This component's spacing will be adjusted with the tip manager refactor. 
https://github.com/Esri/calcite-components/issues/2469

Should we close this one?

**Comment by bstifle** [comment]
yep let's close it in favor of #2469
