### ISSUE TITLE
Bug: calcite-action tapping behavior

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1082]
@kat10140 commented on [Fri Aug 23 2019](https://github.com/Esri/calcite-app-components/issues/216)

### Summary
Tapping text actions does not change color, white ones do.

(note: on hover on mac/chrome the white changes to off white, though not when clicked- not sure if this behavior is supposed to happen or not)

### Actual Behavior
Tapped blue action
![63472309-8030e480-c426-11e9-872a-37216832162f](https://user-images.githubusercontent.com/48069902/63623927-d2e9d800-c5af-11e9-94e6-8ed62c270abb.jpeg)

Tapping white action 
![63472307-8030e480-c426-11e9-80e6-140bbdc9189a (1)](https://user-images.githubusercontent.com/48069902/63623937-d67d5f00-c5af-11e9-8198-acf2a65e9a7a.jpeg)

### Expected Behavior
No changey color

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/demos/calcite-action.html on your mobile device. Click white action. 

### Relevant Info 

---

@asangma commented on [Tue May 19 2020](https://github.com/Esri/calcite-app-components/issues/216#issuecomment-630928914)

@kat10140 Assigning to you to try and reproduce.

**Comment by driskull** [comment]
@asangma does the styling just need an active state?

**Comment by bstifle** [comment]
@asangma this is assigned to you, is it still relevant?

Has there been any movement? Thank you.

_end comment_

**Comment by jcfranco** [comment]
I think this is still relevant. Any action with the `active` prop doesn't display the pressed state when clicked.

![clicking-actions](https://user-images.githubusercontent.com/197440/109182077-7be33700-7741-11eb-80f1-5e05b7e1b145.gif)

**Comment by jcfranco** [comment]
@Esri/calcite-design-representatives Any tips to distinguish the pressed state on ☝🏼 ?

**Comment by justinhough** [comment]
@caripizza @jcfranco Is this what you were both thinking for the active state click? Would you also want to flash the text color from dark to light in the same context?

![CleanShot 2021-08-17 at 12 25 28](https://user-images.githubusercontent.com/9469422/129780572-e4bf7cf6-81d3-48c5-bcdc-31786e375101.gif)

**Comment by bstifle** [comment]
i think the active foreground-3 should just press to fg-2 or fg-1

**Comment by justinhough** [comment]
@bstifle I think the fg-2 works, but here are both for comparison. 

fg-2
![CleanShot 2021-08-17 at 15 22 40](https://user-images.githubusercontent.com/9469422/129802544-a356dc4a-47ba-4979-9469-9a9868bc6014.gif)

fg-1
![CleanShot 2021-08-17 at 15 24 27](https://user-images.githubusercontent.com/9469422/129802692-d4c2ae75-7c19-4737-823b-169d1c797b3f.gif)

@caripizza @jcfranco

**Comment by caripizza** [comment]
@justinhough looking good! (`bg-brand` was just an example showing an obvious color change targeting that `:active` selector.)

Couple questions:
- Do we need to update the `:active` background color for **all** calcite-action appearances (`"clear" | "outline" | "solid"`), or only solid?
- Should we add designs for the `"outline"` appearance in Figma, or is that not a valid appearance? (Something like the "Button Colors" design in _Infastructures would be super helpful.)

**Comment by justinhough** [comment]
@caripizza Thanks! Are those questions for me or @bstifle?

**Comment by caripizza** [comment]
@justinhough those are questions for anyone who knows what calcite-action **_should_** look like with the Figma/Tailwind refactor. @bstifle or @asangma - do you guys have a preference on colors for calcite-action? cc @julio8a

**Comment by justinhough** [comment]
@asangma Any feedback on this one? I can proceed with the hover bg changes, but not sure if there was a consensus around these questions that @caripizza had asked prior.

- Do we need to update the :active background color for all calcite-action appearances ("clear" | "outline" | "solid"), or only solid?
- Should we add designs for the "outline" appearance in Figma, or is that not a valid appearance? (Something like the "Button Colors" design in _Infastructures would be super helpful.)

cc @julio8a

**Comment by julio8a** [comment]
Unless @macandcheese or @asangma have any objections, short term, let's go with the biggest visual difference with `:active` (all appearances), fg-1, we can have a follow-up issue/discussion to look at all the states and appearances for `action` holistically.

**Comment by julio8a** [comment]
verified on master, local build demo pages.
