### ISSUE TITLE
Research: Sharing radio logic with a functional component

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#1096]
### Background 

Problem: we have two types of radio components: `radio-group/group-item` and `radio-button-group/radio-button` that have the same exact functionality, but only truly differ in their appearance.  They both have vastly different internal implementations leading to bugs that happen in one and not the other (#1027,  #1058) which require redundant time and effort to resolve fixes that uniquely apply to each.

### Desired Outcome 

`radio-group/group-item` and `radio-button-group/radio-button` share internal logic whilst retaining their styling as independent elements without creating a base HTMLElement that could be used standalone.

**Comment by macandcheese** [comment]
Still valid.
