### ISSUE TITLE
Docs: Document CSS variables

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1097]
### Description 

Document the CSS variables we would like to expose for users to be be able to overwrite.

These could be documented in each component and the more global ones could be documented in a section on storybook using a markdown file and an `.mdx` file.

### Which Component

All components. Can start with variables that are common to all and more basic variables like color, font, etc and work toward styling

### Background

The ArcGIS JS API currently allows theming via Sass but is looking to use calcite components within their widget and allow styling without Sass using CSS variables.

### Resources 

N/A

**Comment by caripizza** [comment]
It looks like Stencil may be able to do this for us in the component .scss files:
https://stenciljs.com/docs/docs-json#css-variables

**Comment by driskull** [comment]
Nice, yes lets do that.

**Comment by jcfranco** [comment]
Moving to the 5/24-6/7 sprint. cc @caripizza

**Comment by jcfranco** [comment]
@asangma Is this on your radar for this sprint?

**Comment by asangma** [comment]
@jcfranco I won't be able to get to this for the 6/7 sprint.

**Comment by asangma** [comment]
@jcfranco I need to get up to speed on Storybook.js so I think this won't be done in this sprint.

**Comment by jcfranco** [comment]
@asangma I think for this one we need to first determine which ones are the global CSS vars. Those would get a Storybook MDX page (e.g. https://raw.githubusercontent.com/Esri/calcite-components/master/src/1-introduction.stories.mdx). We also need to decide what will be the best way to doc these. I guess the simplest would be a markdown table for each CSS var group where we list the vars and their purpose:

```md
### Global Category/Group

| CSS custom property    | Description    |
|------------------------|----------------|
| --calcite-some-prop    | what it do     |
| --calcite-another-prop | what it do too |
```

Secondly, any component-level CSS vars would only need a custom Stencil `@prop --calcite-some-var: what it do` JSDoc tag entry (see @caripizza's comment above https://github.com/Esri/calcite-components/issues/1097#issuecomment-841327765). On a related note, are these ready to be exposed or should we focus on the global ones for now?

**Comment by driskull** [comment]
Lets let this issue focus on the global ones and we can create individual issues for components.

**Comment by caripizza** [comment]
@jcfranco @driskull I can doc the CSS properties from each component stylesheet over in #2241 if that's helpful. I like the idea of using this issue to doc the global vars. (Adam and I are working on getting those added for our next developer docs update.)

**Comment by asangma** [comment]
LOL! I just saw the last couple comments here.
I started on [some tables](https://github.com/Esri/calcite-components/blob/asangma/doc-css-vars-1097/src/6-custom-theme-introduction.stories.mdx#available-css-varirables) similar to what you suggest @jcfranco.

**Comment by asangma** [comment]
I've also had a chat with @bstifle about _broadly_ documenting the font size usage in different scales.
Note: I am updating files for the Storybook but I'm guessing this info would likely go on Developers yeah?

**Comment by macandcheese** [comment]
Yep, I would suspect we eventually have a more comprehensive "theming" page on the Developers site that provided these css vars, and maybe some live updating components to see the result (similar to Storybook). We could even have a few custom themes we use as samples across our examples, something Material does a great job at in their usage examples.

**Comment by julio8a** [comment]
I think this is covered by the work @caripizza did for the doc site with the CSS vars, Cari can you confirm?

**Comment by caripizza** [comment]
@julio8a Not quite - I think Alan's working on doc'ing out the global CSS vars in this issue. (I only doc'ed the component stylesheet vars thus far.)

**Comment by julio8a** [comment]
@asangma, can you work on this in the 7/19 sprint?

**Comment by macandcheese** [comment]
Is this still something we need now that developer site will be source of truth for public documentation? The component-level variables are now available in the documented output. For the developer site documentation, we can just get the Calcite Color values from the repo.

**Comment by driskull** [comment]
I think we can close this one.
