### ISSUE TITLE
Research: better selection UX for large visual checkbox tile selects

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#1098]
so everything seems to be good except for these. maybe a future enhancement since it's a weird issue with the hover/focus

Really hard to tell when deselecting something

![image](https://user-images.githubusercontent.com/14083530/95371073-52636500-089f-11eb-82ad-9edf7a75f594.png)

_Originally posted by @bstifle in https://github.com/Esri/calcite-components/pull/1072#issuecomment-705110452_

**Comment by bstifle** [comment]
thanks Erik! it would be nice for the border to go back to 1px and gray. but the focus "ring" remain on deselect. like so:

![image](https://user-images.githubusercontent.com/14083530/95614795-b6676400-0a2c-11eb-97fe-25a05323d5f7.png)

it would apply to all these:
![image](https://user-images.githubusercontent.com/14083530/95614832-c7b07080-0a2c-11eb-8335-4a556407c058.png)
![image](https://user-images.githubusercontent.com/14083530/95614845-d26b0580-0a2c-11eb-9cb1-7e8a9af24b61.png)
![image](https://user-images.githubusercontent.com/14083530/95614858-d72fb980-0a2c-11eb-883b-2e793c77133a.png)
