### ISSUE TITLE
Component: Tree Navigation

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#11]
http://proto.esri.com/#/detail/Navigation/Tree%20Navigation/1

I'm adding this to the initial list from @paulcpederson because we have a pretty big need for it on both the Developers Site (the existing side nav pattern isn't working for us anymore) and the Vector Tile Style Editor (our existing Angular tree component has issues).

**Comment by patrickarlt** [comment]
@julio8a @macandcheese I'm going to have some time to spend on this since I want to use it for an upcoming release on the developers site. From a design perspective how we want to proceed? Should I forge ahead and just do a mix of http://proto.esri.com/#/detail/Navigation/Tree%20Navigation/1 and my own best judgement? I tried starting up https://github.com/ArcGIS/calcite-design-system to see if there was anything but I got a lot of errors in the process.

How do you want to proceed?

**Comment by macandcheese** [comment]
Here's designs, combines the style and function of VTSE, Online, Calcite Design Site so it can be used for all purposes.

Propose having props for:
border/lines: true/false (the alignment lines are useful for deeply nested trees, but should give the option of not having them for shallow trees)

scale: default/compact(dense?) - useful for dense implementations like VTSE - 1/2 y-padding.

States: 
Dropdowns:
- Closed / Inactive (no style) 
- Closed / Active (500 weight text, "thick stroke" blue caret) 
- Open / Inactive (no style, rotated caret) 
- Open / Active (rotated caret, 500 weight text, "thick stroke" blue caret


Children:
- Inactive (no style)
- Active (500 weight font, blue line, blue dot)
- Hover (darken text, darken line and dot to gray)

Original varying designs:
![Source](https://user-images.githubusercontent.com/4733155/62885207-19f0e700-bced-11e9-8eb5-888bfc4a467b.jpg)


Combined proposed design:
![Example](https://user-images.githubusercontent.com/4733155/62885215-2117f500-bced-11e9-9f62-0d240e177685.jpg)

Combined proposed design in VTSE (probably a good candidate for "dense / compact" display)
![VTSE example](https://user-images.githubusercontent.com/4733155/62885233-2f661100-bced-11e9-8ccb-4655ca97dbe2.jpg)

**Comment by paulcpederson** [comment]
✨ 👌

**Comment by patrickarlt** [comment]
@macandcheese this looks great. I'll get started on this this week.

**Comment by macandcheese** [comment]
Closing as this has been merged in, can open subsequent issues for any other tasks if needed ✨
