### ISSUE TITLE
calcite-date: placeholder changed from beta.40 to beta.41

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1104]
The placehoder for an empty calcite-date input has changed. Was this purpose? Because the year never appears with a length of 2, once it's selected, it seems wrong to me.

beta.40
<img src=https://user-images.githubusercontent.com/44481292/95627097-71ddc780-0a30-11eb-9b4f-96dbc94b98c8.png width=200/>

beta.41
<img src=https://user-images.githubusercontent.com/44481292/95627135-7f934d00-0a30-11eb-9ce9-2e4d50193203.png  width=200/>

once you pick a date
<img src=https://user-images.githubusercontent.com/44481292/95627169-8cb03c00-0a30-11eb-831d-97389a2021ab.png width=200/>

**Comment by AdelheidF** [comment]
You can still see this placeholder 'M/d/yy' when removing a valid date from the input. 
Then when I then type in this string '5/5/13' the dropdown shows this date below. 
So the placeholder string is definitely wrong.

<img src=https://user-images.githubusercontent.com/44481292/99749793-fc83fe80-2a93-11eb-9e47-fbfab21bc594.png width=200/>

**Comment by macandcheese** [comment]
Related https://github.com/Esri/calcite-components/issues/1265

**Comment by AdelheidF** [comment]
Still the same...

**Comment by paulcpederson** [comment]
Yes this was an intentional change. While technically correct per unicode CLDR spec, the previous format was "a bit weird" to users, so the format was updated to use `mm/dd/yyyy` but in the correct order and with the correct separator.

@julio8a could speak to this from a design perspective.

**Comment by paulcpederson** [comment]
Here's a link to the issue with discussion of this update: #1265

**Comment by paulcpederson** [comment]
I'm going to close this. If we want to update the placeholder more let's open a new issue to discuss as this one keeps getting marked as stale. AFAIK the current behavior represents accurately what was designed by the design team.
