### ISSUE TITLE
Bug: calcite-panel: add default width to calcite-panel

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#1107]
### Summary
Can you pls add a default width-scale on CalcitePanel.  When used in calcite-shell, it would be helpful if the width was set automatically

[alan] Also add width-scale to CalciteShellPanel.

### Reproduction Steps

1.

**Comment by kevindoshier** [comment]
@asangma - I can use both of these properties now, but it doesnt seem like setting width-scale="l" on the shell-panel in turn sets it on a calcite-panel within it?  should it do that?

**Comment by macandcheese** [comment]
Still valid.

**Comment by julio8a** [comment]
Following up on this issue, @asangma

**Comment by caripizza** [comment]
Hi @kevindoshier, are you asking for calcite-panel's `width-scale` property to be updated after the attribute is changed on a parent shell-panel? 

I can see `calcite-panel` is styled with a 100% width, so setting `width-scale="l"` on a parent shell-panel will constrain the child calcite-panel width per [these styles](https://github.com/Esri/calcite-components/blob/dd10e9c2e2035715b1b72b87f90c6b86ef7f56fd/src/components/calcite-shell-panel/calcite-shell-panel.scss#L34-L50), but it's not setting the width-scale property on calcite-panel.

**Comment by caripizza** [comment]
Just chatted with Kevin in Teams, he's good with current behavior so this one can now be closed.
