### ISSUE TITLE
Bug: Calcite Date changes automatically with certain time zone settings

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#1111]
Related Map Viewer Beta issue:
https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/1966

If your computer is set to certain time zones, interacting with the calcite-date component causes it to continuously scroll through the calendar.

This issue can be reproduced in any broswer if you set system time zone in UTC+(1 to 14).(eg:UTC+08:00 Beijing), and it is not reproduced if set system time zone in UTC+00:00 Dublin or UTC-8:00 Pacific Time

Reproducible here if you click on the highlighted arrow in Beijing time zone:

https://esri.github.io/calcite-components/?path=/story/components-date--simple

![image](https://user-images.githubusercontent.com/50747646/95780578-ff175b00-0c80-11eb-807b-dac8907f18db.png)

![image](https://user-images.githubusercontent.com/50747646/95780498-dabb7e80-0c80-11eb-92e0-f64c9c8158e5.png)

@jcfranco @paulcpederson

**Comment by paulcpederson** [comment]
I looked into this a bit, not entirely sure why this is happening, but I can reproduce.

Note to self (or if somebody else wants to take a look): the easiest way to set timezone (without changing your whole OS) is to launch a new chrome instance passing a `TZ` config:

```
mkdir ~/chrome-profile
TZ='Asia/Shanghai' open -na "Google Chrome" --args "--user-data-dir=$HOME/chrome-profile"
```

Will keep working on this one...

**Comment by macandcheese** [comment]
Still valid.

**Comment by zaramatheson** [comment]
@paulcpederson @macandcheese Any updates on a potential fix for this one? We've had some more people come across it in MVB.

**Comment by paulcpederson** [comment]
One fix is to remove proxy input support. @eriklharper @driskull @jcfranco is that something that's on the table?

Otherwise it's going to be a matter of debugging exactly where this render loop is being caused and tiptoeing our way around it, somehow.

**Comment by eriklharper** [comment]
> One fix is to remove proxy input support. @eriklharper @driskull @jcfranco is that something that's on the table?

I'm in favor of removing proxy input support here, but is this bug only reproduced when using a proxy input?

**Comment by paulcpederson** [comment]
It's been a while since I investigated but removing `syncProxyToThis` and the problem went away, IIRC. The proxy syncing introduces two way data binding inside what's meant to be a unidirectional state machine, so it's not super surprising that it causes infinite render calls.

**Comment by eriklharper** [comment]
That makes all the sense in the world, and removing proxy input simplifies the component to boot, so yeah I'd go all in on removing that.

**Comment by paulcpederson** [comment]
@zaramatheson have a pr open for a fix to this, should make the next release

**Comment by julio8a** [comment]
@paulcpederson, @zaramatheson 

Does this just need verification?

**Comment by paulcpederson** [comment]
@julio8a correct, it's installed

**Comment by julio8a** [comment]
I'm on a mac so the settings are different. However, I did set change my timezone to a Chinese city `Baiyin - China mainland`, and didn't get the issue. 

Verified fixed.
