### ISSUE TITLE
Enhancement: Add Small and Large props to Slider

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#1115]
![image](https://user-images.githubusercontent.com/14083530/95886006-9e9d2200-0d43-11eb-8fb4-214b7bfd4017.png)

![image](https://user-images.githubusercontent.com/14083530/95885826-5b42b380-0d43-11eb-8723-617a39ee21c0.png)

All of the other specs should be the same as Medium.

Though, we may need to fine tune how big/small histogram is

**Comment by macandcheese** [comment]
Still valid.

**Comment by macandcheese** [comment]
Valid
