### ISSUE TITLE
calcite-pick-list-item click on icon not working

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1116]
It used to be like this:

<img src=https://user-images.githubusercontent.com/44481292/95902488-bf687600-0d49-11eb-9c16-65e8503195a0.png width=200/><img src=https://user-images.githubusercontent.com/44481292/95902954-5f260400-0d4a-11eb-8d3a-3aa7a3ac1cf2.png width=200/>

![image](https://user-images.githubusercontent.com/44481292/95902576-dad38100-0d49-11eb-9d2b-6de95e426f83.png)

Now it's like this:

<img src=https://user-images.githubusercontent.com/44481292/95902635-ec1c8d80-0d49-11eb-9cc9-48b47f70e39d.png width=200/><img src=https://user-images.githubusercontent.com/44481292/95903013-71a03d80-0d4a-11eb-97d4-cfbfd0755df9.png width=200/>

![image](https://user-images.githubusercontent.com/44481292/95902728-07879880-0d4a-11eb-9487-8edd49dfc306.png)

I made this change

<img src=https://user-images.githubusercontent.com/44481292/95903107-90063900-0d4a-11eb-9f68-d383a310d405.png width=300/>

Also, when I click on the icon to unselect or click the area where it would show when currently unselected, it not longer does anything. I have to click on the text. In the past that worked. It's kind of weird now, because that's how typical check boxes work.

**Comment by AdelheidF** [comment]
> when I click on the icon to unselect or click the area where it would show when currently unselected, it not longer does anything. I have to click on the text. In the past that worked. It's kind of weird now, because that's how typical check boxes work.

I still think this should be changed.

**Comment by AdelheidF** [comment]
This is still an issue and it keeps annoying me when using the component in the UX.

<img src=https://user-images.githubusercontent.com/44481292/105225233-1fbe3f00-5b13-11eb-86e6-8f950c66720c.png width=200/>

If you click on the check nothing happens. You have to click on the title to uncheck it. Same for radio buttons. It should work on both the title and the checkbox.

The alignment of action-end text is also still an issue. 
<img src=https://user-images.githubusercontent.com/44481292/105228201-251d8880-5b17-11eb-886d-d035888c69c4.png width=200/>

**Comment by macandcheese** [comment]
Agree this needs to be fixed, that’s super annoying. @asangma do you still have bandwidth for this or need someone else to pick up? TIA

**Comment by AdelheidF** [comment]
How can I make this higher priority? Can we at least fix the alignment issue with action-end?

**Comment by AdelheidF** [comment]
I would still like someone to comment on this. It's still annoying to me.

**Comment by julio8a** [comment]
https://github.com/Esri/calcite-components/pull/1949

**Comment by ethanbdev** [comment]
This fix looks good in charts, thanks @driskull!

**Comment by AdelheidF** [comment]
Yes, works well for me too for multi-select and single-selection lists. Tested with next.156.
