### ISSUE TITLE
Bug: calcite-action-bar ('Collapse' string misaligned in action bar for RTL languages)

### ISSUE THREAD

**Issue by rslibed** [Esri/calcite-components#1118]
### Summary
I18N-RTL: String 'Collapse' is slightly misaligned with other tools in calcite-action-bar

![calcite-action-bar](https://user-images.githubusercontent.com/29421380/95909634-abc20d00-0d53-11eb-9fa6-c23cdf330ab0.png)

Actual result:
String 'Collapse' is slightly misaligned with other tools in Configuring page of app with Full Setup design.

Expected result:
String 'Collapse' should be aligned with other tools in Configuring page of app with Full Setup design.

Issue found in ArcGIS Online Instant Apps Config Panel reported by Olga.

**Comment by macandcheese** [comment]
Still valid.

**Comment by caripizza** [comment]
Verified resolved in the latest release of @esri/calcite-components@1.0.0-beta.50, closing.
