### ISSUE TITLE
calcite-input type=number: not much space left for actual number

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1119]
The shell panel has a min-width of 240px. 

This is how this looks now with that width
<img src=https://user-images.githubusercontent.com/44481292/96524874-46c45680-122e-11eb-96a9-2b1a8b023971.png width=300/>
There is barely enough space to see a 2 digit number.

With `beta.40` it looked better.
<img src=https://user-images.githubusercontent.com/44481292/95911804-cb0e6980-0d56-11eb-827a-ad19223a723f.png width=250/>

Could we reduce some padding in `calcite-input`?

**Comment by macandcheese** [comment]
We could probably reduce the -end padding to half its current value for these, although from the screenshots it looks like  maybe there's a bit more padding on the panel itself?

We could also make the increment / decrement buttons take up less width, there's no reason for them to be that wide, or, maybe in this example the number button type could be set to "none" if they aren't needed?

**Comment by AdelheidF** [comment]
> although from the screenshots it looks like maybe there's a bit more padding on the panel itself?

Yes, I see this now. Need to investigate because this must have happened from the calcite update.

> We could also make the increment / decrement buttons take up less width, there's no reason for them to be that wide

Yes, I'd like that option the most. 

>  in this example the number button type could be set to "none" if they aren't needed?

Might still be nice to have that, especially once holding the arrows down to increase the speed is implemented.

**Comment by AdelheidF** [comment]
> although from the screenshots it looks like maybe there's a bit more padding on the panel itself?

Padding used to be 8 all around for calcite-block content.
`padding: var(--calcite-app-cap-spacing-half) var(--calcite-app-side-spacing-half);`

Now it's 12px right/left and 8 top/bottom.
`padding: var(--calcite-spacing-half) var(--calcite-spacing-three-quarters);`

cc @asangma

**Comment by AdelheidF** [comment]
this is still a valid issue

**Comment by AdelheidF** [comment]
Would it be possible to hide the up and down arrows completely if the width of those calcite-inputs gets too small? So big screens would have it and small screens not, all automatically?

**Comment by macandcheese** [comment]
The app itself could set that to "none" at a certain width, I'm not sure if we want to have that in the component?

**Comment by AdelheidF** [comment]
oh, let me try that. I missed that feature...

**Comment by macandcheese** [comment]
Sorry, didn't mean to say the input has that capability as far as setting that prop at a certain width, but the "number-button-type:none" prop exists now: https://esri.github.io/calcite-components/?path=/story/components-input--without-label&knob-scale=m&knob-status=idle&knob-type=number&knob-alignment=start&knob-number-button-type=none&knob-min=0&knob-max=100&knob-step=1&knob-prefix-text=&knob-suffix-text=&knob-loading=&knob-clearable=&knob-disabled=&knob-value=&knob-placeholder=Placeholder text

**Comment by AdelheidF** [comment]
OK, that works. But now it has to listen to the browser resize event to know if it has to change.

Closing this issue.
