### ISSUE TITLE
calcite-date: intl-next-month and intl-prev-month not working

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1122]
`intl-next-month` and `intl-prev-month` are not working. I never see any text on hover. 
Reproducible with the storybook.

**Comment by paulcpederson** [comment]
It's not a hover text, it's an aria label. However I did find a bug in how we're reading it so it was never updating. Pr open.

**Comment by AdelheidF** [comment]
OK, could we update the doc them to make that clear? Thanks.

![image](https://user-images.githubusercontent.com/44481292/96320758-209d7d00-0fc8-11eb-962f-4f1110e2594b.png)

**Comment by AdelheidF** [comment]
doc is updated
