### ISSUE TITLE
calcite-panel: doc says undefined is width 100%

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1126]
Typo 'height' and it says default is 100%
![image](https://user-images.githubusercontent.com/44481292/96055834-f61db980-0e39-11eb-9810-967a92dd7a81.png)

but it's set to default to m
https://github.com/Esri/calcite-components/blob/master/src/components/calcite-panel/calcite-panel.tsx#L90
`@Prop({ reflect: true }) widthScale: CalciteScale = "m";`

Setting it to "l" makes it about 75% wide.

**Comment by AdelheidF** [comment]
looks good now, tested locally with next.23

**Comment by asangma** [comment]
Yew! Thanks @AdelheidF.
