### ISSUE TITLE
Bug: Storybook Input page freezes

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1127]
### Summary
The Input section on our Storybook freezes.

### Actual Behavior
![frozen](https://media.giphy.com/media/10vJoTT4oWZR84/giphy.gif)

### Expected Behavior
![not frozen](https://media.giphy.com/media/1sv8vtuj5vF2eV7K8W/giphy.gif)

### Reproduction Steps

1. Go to https://esri.github.io/calcite-components/?path=/story/components-input--with-label

**Comment by jcfranco** [comment]
Linking a comment about a condition that triggers an infinite loop in `calcite-input`: https://github.com/Esri/calcite-components/pull/1049#issuecomment-702275036
