### ISSUE TITLE
Bug: Block and Panel font sizes are wrong

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1131]
### Summary
* Block heading should be 0.875rem (currently it's 0.75rem)
* Block summary should be 0.75rem (currently it's 0.6875rem)
* Panel heading should be 1rem (currently it's 0.875rem)

cc @AdelheidF

**Comment by asangma** [comment]
@AdelheidF Would you mind checking this locally in order to verify?

**Comment by AdelheidF** [comment]
verified locally with `next.24`.
panel header is 16px, block and block-section header are 14px. 
panel header summary is 12px, 'normal' text is 14px, label scale=s is 12px, label scale=m is 16px.

**Comment by asangma** [comment]
Thanks for verifying @AdelheidF.
I'll close this one and leave the label size stuff to #1137.
