### ISSUE TITLE
Design Audit

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#114]
Ensure parity between Sketch library and implementation. Light and Dark theme. Calcite-component implementation might be further along than Sketch library, some components need to get updated in the Sketch library.

- [ ] Alerts (#15)
- [ ] Buttons (#71)
- [ ] loader (#7) 
- [ ] modals (#83)
- [ ] progress (#25)
- [ ] radio-group (#5)
- [ ] slider (#4) 
- [ ] switch (#33) 
- [ ] tabs (#8) 
- [ ] tree nav (#11)

**Comment by macandcheese** [comment]
Closing this, it's been addressed in other issues / repos.
