### ISSUE TITLE
Refactor: API/nomenclature review

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1145]
Initial review notes: https://github.com/Esri/calcite-components/wiki/calcite-components-API-review

## Action items

**Note**: PRs for each item must include an update to our conventions doc.

~* [ ] ensure consistent boolean names (@jcfranco)~
  ~* prefer adjectives (e.g., collapsible, moveable, etc), if an appropriate one does not exist, `-disabled`/`-enabled` suffixes can be used to describe the prop.~
~* avoid initializing booleans to true~
☝🏼  extracted to https://github.com/Esri/calcite-components/issues/2115
* [x] wherever applicable, update `value` prop types to accept the most flexible type allowed. (https://github.com/Esri/calcite-components/pull/1961
  * widening calcite-input's value was extracted to #758 
* [x] make sure that all public events have doc (@jcfranco) https://github.com/Esri/calcite-components/pull/1517
* [x] mark registration-related events (for parent-child components) as internal to be excluded from the doc (@jcfranco) https://github.com/Esri/calcite-components/pull/1517
* [x] for any component with focusable content, the `setFocus` method must be implemented (@jcfranco) https://github.com/Esri/calcite-components/pull/1522
* [x] remove outdated sections from readmes and move any examples to a usage folder (@jcfranco) https://github.com/Esri/calcite-components/pull/1521
* [x] prefer `calciteComponentChange` name for events that notify about component updates (@jcfranco) https://github.com/Esri/calcite-components/pull/1519
* [x] mark reflected props used for styling as internal to be excluded from the doc (@jcfranco) https://github.com/Esri/calcite-components/pull/1523

**Comment by julio8a** [comment]
Hey guys, checking in on this one since it's a required item for the 1.0

**Comment by paulcpederson** [comment]
Below is a summary of all the components and their props. This may help us spot inconsistencies.

---

#### calcite-accordion
appearance, iconPosition, iconType, scale, selectionMode, theme

#### calcite-accordion-item
active, icon, itemSubtitle, itemTitle

#### calcite-action
active, appearance, compact, disabled, icon, indicator, intlLoading, label, loading, scale, text, textEnabled, theme

#### calcite-action-bar
expand, expanded, intlCollapse, intlExpand, position, theme, tooltipExpand

#### calcite-action-pad
expand, expanded, intlCollapse, intlExpand, layout, position, theme, tooltipExpand

#### calcite-alert
active, autoDismiss, autoDismissDuration, color, icon, intlClose, label, scale, theme

#### calcite-avatar
fullName, scale, theme, thumbnail, userId, username

#### calcite-block
collapsible, disabled, dragHandle, heading, intlCollapse, intlExpand, intlLoading, loading, open, summary, theme

#### calcite-block-section
intlCollapse, intlExpand, open, text, toggleDisplay

#### calcite-button
alignment, appearance, color, disabled, href, iconEnd, iconFlipRtl, iconStart, intlLoading, loading, round, scale, splitChild, theme, width

#### calcite-card
intlDeselect, intlLoading, intlSelect, loading, selectable, selected, theme

#### calcite-checkbox
checked, disabled, focused, guid, hovered, indeterminate, name, scale, theme, value

#### calcite-chip
appearance, color, dismissLabel, dismissible, icon, iconFlipRtl, scale, theme, value

#### calcite-color
appearance, hideChannels, hideHex, hideSaved, intlB, intlBlue, intlDeleteColor, intlG, intlGreen, intlH, intlHex, intlHsv, intlHue, intlR, intlRed, intlRgb, intlS, intlSaturation, intlSaveColor, intlSaved, intlV, intlValue, scale, storageId, theme, value

#### calcite-color-hex-input
intlHex, scale, theme, value

#### calcite-color-swatch
active, color, scale, theme

#### calcite-combobox
active, allowCustomValues, disabled, label, maxItems, placeholder, scale, theme

#### calcite-date
active, end, endAsDate, intlNextMonth, intlPrevMonth, layout, locale, max, min, noCalendarInput, proximitySelection, range, scale, start, startAsDate, value, valueAsDate

#### calcite-dropdown
active, alignment, disableCloseOnSelect, disabled, maxItems, scale, selectedItems, theme, type, width

#### calcite-dropdown-group
groupTitle, selectionMode

#### calcite-dropdown-item
active, href, iconEnd, iconFlipRtl, iconStart

#### calcite-fab
appearance, color, disabled, icon, label, loading, scale, text, textEnabled, theme

#### calcite-filter
data, intlClear, intlLabel, placeholder

#### calcite-flow
theme

#### calcite-graph
data, height, highlightMax, highlightMin, width

#### calcite-handle
textTitle

#### calcite-icon
flipRtl, icon, scale, textLabel, theme

#### calcite-inline-editable
afterConfirm, controls, disabled, editingEnabled, intlCancelEditing, intlConfirmChanges, intlEnableEditing, loading, scale, theme

#### calcite-input
alignment, autofocus, clearable, disabled, icon, iconFlipRtl, loading, max, min, numberButtonType, placeholder, prefixText, required, scale, status, step, suffixText, theme, type, value

#### calcite-input-message
active, icon, scale, status, theme, type

#### calcite-label
disableSpacing, disabled, for, layout, scale, status, theme

#### calcite-link
disabled, href, iconEnd, iconFlipRtl, iconStart, theme, userSelect

#### calcite-loader
active, inline, label, noPadding, scale, text, type, value

#### calcite-modal
active, backgroundColor, beforeClose, color, disableCloseButton, disableEscape, docked, firstFocus, fullscreen, intlClose, noPadding, scale, theme, width

#### calcite-notice
active, color, dismissible, icon, intlClose, scale, theme, width

#### calcite-option
disabled, label, selected, value

#### calcite-option-group
disabled, label

#### calcite-pagination
num, scale, start, textLabelNext, textLabelPrevious, theme, total

#### calcite-panel
beforeBack, disabled, dismissed, dismissible, heading, heightScale, intlBack, intlClose, intlOpen, intlOptions, loading, menuOpen, showBackButton, summary, theme, widthScale

#### calcite-pick-list
disabled, filterEnabled, filterPlaceholder, loading, multiple

#### calcite-pick-list-group
groupTitle

#### calcite-pick-list-item
description, disableDeselect, disabled, icon, intlRemove, label, metadata, removable, selected, value

#### calcite-popover
closeButton, disableFlip, disablePointer, flipPlacements, intlClose, label, offsetDistance, offsetSkidding, open, placement, referenceElement, theme

#### calcite-popover-manager
autoClose, selector

#### calcite-progress
reversed, text, theme, type, value

#### calcite-radio
checked, disabled, focused, hidden, hovered, scale, theme

#### calcite-radio-button
checked, disabled, focused, guid, hidden, hovered, name, required, scale, theme, value

#### calcite-radio-button-group
disabled, hidden, layout, name, required, scale, theme

#### calcite-radio-group
appearance, disabled, layout, name, scale, selectedItem, theme, width

#### calcite-radio-group-item
checked, icon, iconFlipRtl, iconPosition, value

#### calcite-rating
average, count, disabled, displayValue, intlRating, intlStars, readOnly, scale, theme, value

#### calcite-scrim
intlLoading, loading, theme

#### calcite-select
disabled, label, scale, selectedOption, theme, width

#### calcite-shell
theme

#### calcite-shell-center-row
detached, heightScale, position

#### calcite-shell-panel
collapsed, detached, detachedHeightScale, position, widthScale

#### calcite-slider
disabled, hasHistogram, histogram, labelHandles, labelTicks, max, maxLabel, maxValue, min, minLabel, minValue, pageStep, precise, snap, step, theme, ticks, value

#### calcite-sortable-list
disabled, handleSelector, loading

#### calcite-split-button
appearance, color, disabled, dropdownIconType, dropdownLabel, loading, primaryIconEnd, primaryIconFlipRtl, primaryIconStart, primaryLabel, primaryText, scale, theme

#### calcite-stepper
icon, layout, numbered, scale, theme

#### calcite-stepper-item
active, complete, disabled, error, itemSubtitle, itemTitle

#### calcite-switch
disabled, name, scale, switched, theme, value

#### calcite-tab
active, tab

#### calcite-tab-nav
storageId, syncId

#### calcite-tab-title
active, disabled, iconEnd, iconFlipRtl, iconStart, tab

#### calcite-tabs
layout, position, theme

#### calcite-tile
active, description, embed, focused, heading, hidden, href, icon, theme

#### calcite-tile-select
checked, description, disabled, focused, heading, hidden, icon, name, showInput, theme, type, value, width

#### calcite-tile-select-group
layout

#### calcite-tip
dismissed, heading, intlClose, nonDismissible, selected, theme

#### calcite-tip-group
groupTitle

#### calcite-tip-manager
closed, intlClose, intlDefaultTitle, intlNext, intlPaginationLabel, intlPrevious, theme

#### calcite-tooltip
label, offsetDistance, offsetSkidding, open, placement, referenceElement, theme

#### calcite-tooltip-manager
selector

#### calcite-tree
lines, scale, selectionMode, theme

#### calcite-tree-item
expanded, selected

#### calcite-value-list
disabled, dragEnabled, filterEnabled, filterPlaceholder, group, loading, multiple

#### calcite-value-list-item
description, disabled, icon, label, metadata, removable, selected, value

**Comment by julio8a** [comment]
Where are we with this issue?

**Comment by jcfranco** [comment]
I'll have a few PRs for some items before the end of the week.

**Comment by julio8a** [comment]
Thanks for the update @jcfranco

**Comment by julio8a** [comment]
I can help with verification if I get some guidelines on how to verify. 

I know this is a big one, should we have a quick meet on how we can tackle it?

**Comment by julio8a** [comment]
Talked with Franco and closing this now. Open up follow-ups if anything else comes up.
