### ISSUE TITLE
Components: Phase 2 (VOTE)

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#115]
All,

After the v1.0 release in September, we're looking at adding more components. We need your help to identify which are the most important to you and prioritize our work. Please vote on which components you need sooner rather than later. We'll be taking the highest voted components into the next release. Also, if you have any suggestion please add in a comment for voting.

**Comment by julio8a** [comment]
Inputs, forms & validation

**Comment by julio8a** [comment]
Pagination

**Comment by julio8a** [comment]
super select

**Comment by julio8a** [comment]
Chips (labels)

**Comment by julio8a** [comment]
Stepper (including vertical orientation)

**Comment by julio8a** [comment]
Tooltips

**Comment by julio8a** [comment]
color-picker

**Comment by macandcheese** [comment]
An issue has been made for each of these and they've been added to "To Do" in ranked order in the Phase 2 project. Thanks all - feel free to use the breakout issues for further discussion / feedback!
