### ISSUE TITLE
Enhancement: A11y updates for Date

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1152]
### Description
Follow up from Teams chat:

- [ ] - Ensure label is able to be passed to input (render inside component based on passed string?)

- [ ] - Examine use of aria-hidden inside component.

@driskull feel free to tack more on here if found.

**Comment by macandcheese** [comment]
still valid

**Comment by caripizza** [comment]
Closing in favor of Level Access a11y audit results
