### ISSUE TITLE
Enhancement: Indicator for accordion-item

### ISSUE THREAD

**Issue by jgibson02** [Esri/calcite-components#1157]
### Description
I would like to be able to toggle an indicator on calcite-accordion-item that's similar to the one found on calcite-action to be able to notify the user to updates in that section without needing to programmatically open it which might interrupt the user.

### Acceptance Criteria 
- [ ] calcite-accordion-item accepts a boolean `indicator` prop that controls whether to display an indicator
- [ ] the indicator is completely controlled by the user of the library (i.e. it doesn't deactivate when the accordion-item is opened)

### Relevant Info 
Possibly might need to separate out the HTML/CSS for the calcite-action indicator to something reusable

#### Which Component
accordion-item

#### Example Use Case
For complex form steps it's nice to be able to make form sections into accordion items so that the user is able to focus on one section at a time. However, it's possible that a section of a form might trigger an update to another section of a form. (in the example below, choosing a particular authentication type might set a content-type header).
![image](https://user-images.githubusercontent.com/5069711/96760597-ce74a700-138d-11eb-81c3-14f8c8c7b34f.png)

It's necessary then to have some way of letting users know that an update happened, and currently it's possible to programmatically open the accordion-item but it would be less intrusive to have a similar indicator to calcite-action. 
![image](https://user-images.githubusercontent.com/5069711/96760007-a7b67080-138d-11eb-8d98-4390bf430f66.png)

**Comment by macandcheese** [comment]
still valid

**Comment by macandcheese** [comment]
Still valid - apologies for delay on this @jgibson02 - I run into the need occasionally as well. 

@bstifle anything here? The same indicator icon from action makes sense. We just need to make sure it is aligned and works with all combinations of indicator-icon positions and decorative icons!
