### ISSUE TITLE
Enhancement: [calcite-select] support native + styled rendering of options

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1161]
### Description

Breakout issue from https://github.com/Esri/calcite-components/issues/302#issuecomment-705267556 and https://github.com/Esri/calcite-components/pull/1112/

cc @macandcheese @eriklharper 

#### Which Component

`calcite-select`, `calcite-option`, `calcite-option-group`

#### Example Use Case

**Native UI**

```html
<calcite-select>
  <optgroup>
    <option value="1">one</option>
    <option value="2">two</option>
    <option value="3">three</option>
  </optgroup>
</calcite-select>
```

**Calcite UI**

```html
<calcite-select>
  <calcite-optgroup>
    <calcite-option value="1">one</calcite-option>
    <calcite-option value="2">two</calcite-option>
    <calcite-option value="3">three</calcite-option>
  </calcite-optgroup>
</calcite-select>
```

**Comment by jcfranco** [comment]
Did a quick comparison on popular design system components and found none that supported a mixed approach:

**Native**

- https://www.carbondesignsystem.com/components/select/usage
- https://polaris.shopify.com/components/forms/select#navigation
- https://clarity.design/documentation/select#top

**Styled**

- https://atlassian.design/components/select/examples
- https://material-components.github.io/material-components-web-catalog/#/component/select
- https://ant.design/components/select/
- https://liquid.emd.design/elements/dropdowns/ (dropdown)
- https://spectrum.adobe.com/page/picker/ (dropdown)
- https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown (dropdown)

**Comment by macandcheese** [comment]
Honestly it seems like maybe we should just render this as native always, to keep it simple. Dropdown can be used for a styled version (and perhaps we can add a "mobile docked" version of that to better simulate a spinner).

**Comment by jcfranco** [comment]
Simple is good. 😃

For me, all that matters is that the component sticks to one consistent experience.

**Comment by macandcheese** [comment]
Agreed. For datalist, browsers style the options very differently! I think we may (?) be able to style the non-mobile version while still getting the benefit of native spinner.

**Comment by eriklharper** [comment]
> Honestly it seems like maybe we should just render this as native always, to keep it simple. Dropdown can be used for a styled version (and perhaps we can add a "mobile docked" version of that to better simulate a spinner).

Agree 💯 %.  Does that mean this issue can be simplified to remove the `calcite-option` and `calcite-optgroup` components, or do you think there's still value in keeping them around?

**Comment by jcfranco** [comment]
I'm for keeping them. Mostly for future-proofing (feature & styling). It's nice that the markup looks consistent with other components. All of the listed design system components also have custom option/group elements.

**Comment by jcfranco** [comment]
Discussed w/ @macandcheese and decided we will not pursue this. cc @benelan
