### ISSUE TITLE
Enhancement: [calcite-select] allow specifying separator between options

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1163]
### Description

Breakout issue from https://github.com/Esri/calcite-components/issues/302#issuecomment-705668096

### Relevant Info 

Depends on #1160 

#### Which Component

`calcite-select`, `calcite-option`

**Comment by macandcheese** [comment]
Closing this as we don't want to address styling the natively rendered option / option groups. The dropdown supports separators between groups (works without passing the group-title prop), which better supports the screenshot / requested use case of two different interaction types ("select from existing values", "create new" map to existing dropdown types of single select, no selection).
