### ISSUE TITLE
Enhancement: [calcite-select] allow icons/images for rendered options

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1164]
### Description

Breakout issue from https://github.com/Esri/calcite-components/issues/302#issuecomment-705689362

### Relevant Info 

Depends on https://github.com/Esri/calcite-components/issues/1160

#### Which Component

`calcite-select`, `calcite-option`

**Comment by macandcheese** [comment]
Possible currently - improved by https://github.com/Esri/calcite-components/issues/3074 - out of scope for select component.

**Comment by macandcheese** [comment]
@jcfranco - closing this as we don't want to handle this in the select's natively rendered options. Request encompassed by Combobox current functionality / this issue https://github.com/Esri/calcite-components/issues/4334 (which is also likely better as a combobox enhancement, not select).
