### ISSUE TITLE
Enhancement: Refactor CSS variables

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1165]
### Description

Refactor CSS variables so that components can easily be themed by users. 

This will help support users and the JS API be able to theme the components easily. 

Currently, the CSS variables are named in a way that makes theming them not ideal. The names are referencing colors and ideally the names of the variables should reference how they are used instead.

### Acceptance Criteria 

Rename and refactor CSS variables so that theming them makes more sense

### Relevant Info 

Related to #1097

#### Which Component

All components

#### Example Use Case

N/A

**Comment by asangma** [comment]
I did the refactor.
Now the real work...

**Comment by driskull** [comment]
Is this one done @asangma ?

**Comment by julio8a** [comment]
This one is done, there might be modifications as we refactor the components, but we can create new issues in that case. Nice work @asangma!
