### ISSUE TITLE
Enhancement: Add transparent ui-blue variable

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#1166]
In need of a transparent blue variable, that can be replaced with a brand color theme in the future. Would be used on Date Range Component and can replace ArcGIS Online's `calcite-ui-foreground-current` as well.

rgba(0,122,194, 0.15) for light theme
rgba(0,160,255, 0.15) for dark theme

Suggested names for these variables:

`calcite-ui-blue-1-transparent`
`calcite-ui-blue-1-transparent-dark`

**Comment by kat10140** [comment]
Bryan- assigning you to this so it doesn't get deleted by duh bot

**Comment by bstifle** [comment]
hmm i think we actually resolved this issue in a design meeting a couple weeks ago. did you still have a need for this @kat10140 ?

**Comment by julio8a** [comment]
Closing, please reopen if still valid.
