### ISSUE TITLE
Enhancement: Consolidate FAB / Button functionality.

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1167]
### Description
We should clean up the stories around FAB / Button-that-acts-as-fab:

`calcite-button`:
- Remove `floating` prop
- Remove "FAB" examples under button component in Storybook.

`calcite-fab`:
- Apply the shadow from `floating` to this component, at all times.
- Move `FAB` stories to general list since they aren't really layout?

**Comment by driskull** [comment]
@macandcheese want me to take this one?

**Comment by macandcheese** [comment]
Yeah if you have some extra time, I think this would be good to get out of the way.

**Comment by macandcheese** [comment]
fab looks good, it looks like clear and outline buttons are referencing a `@mixin btn-outline-clear-floating` instead of `@mixin btn-outline-clear`... The former of which can probably be removed from the button css altogether:

![Screen Shot 2020-11-24 at 3 16 01 PM](https://user-images.githubusercontent.com/4733155/100162405-64599100-2e68-11eb-9560-f4ff9057f0c6.png)

**Comment by driskull** [comment]
Installed now. I forgot to merge. 🤦

**Comment by macandcheese** [comment]
Ha, yeah I was looking at the PR branch but it's still there post merge.

We can get rid of this mixin since the shadows are now just applied on the fab component yeah?: https://github.com/Esri/calcite-components/blob/139c9885df5cf6d1a2e77dd56863aff1c0339bbb/src/components/calcite-button/calcite-button.scss#L328

and use the `@include btn-outline-clear-floating` instead here : https://github.com/Esri/calcite-components/blob/139c9885df5cf6d1a2e77dd56863aff1c0339bbb/src/components/calcite-button/calcite-button.scss#L462

**Comment by driskull** [comment]
I'm not sure... that mixin is used a few time and doesn't seem to have to do with `floating` at all.

**Comment by macandcheese** [comment]
It looks like there was maybe a merge conflict? There are two declarations for the outline and clear button types now, one set is under this comment:

https://github.com/Esri/calcite-components/blob/139c9885df5cf6d1a2e77dd56863aff1c0339bbb/src/components/calcite-button/calcite-button.scss#L327 

And these are overriding the "non floating" styles above it.  It's only being used in those 8 outline / clear declarations, so it should be safe to remove those and the mixin.

**Comment by driskull** [comment]
Gotcha. makes sense, ill open PR>

**Comment by macandcheese** [comment]
Thanks!

Apologies for not catching these in PR review, couple other things... It seems like FAB defaults to scale "s" if no scale is provided which seems a little weird as I think all other components default to "m"... and there looks to be a weird RTL styling thing on the demo with alignment (although I don't see the same thing with buttons in RTL so not sure where that is coming from)


![Screen Shot 2020-11-24 at 4 27 30 PM](https://user-images.githubusercontent.com/4733155/100167014-e484f400-2e72-11eb-8d65-3fc9526efab4.png)

**Comment by driskull** [comment]
@asangma can you comment on the above? https://github.com/Esri/calcite-components/issues/1167#issuecomment-733368518

**Comment by jcfranco** [comment]
Created follow-up issue for ☝️ . Closing as verified.
