### ISSUE TITLE
Enhancement: Use popper.js for Date

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1168]

**Comment by driskull** [comment]
@macandcheese want me to take this one?

**Comment by driskull** [comment]
@macandcheese Combobox already uses Popper so updating title just for Date. Was there another component mistaken?

**Comment by macandcheese** [comment]
Hm, I think this was just a breakout issue from a meeting we had. Not sure what else would need it if Combobox already has been updated?

**Comment by macandcheese** [comment]
Verified on master!
