### ISSUE TITLE
Research: Research using different focus trap npm helper

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1169]
### Background 

Research: Research using different focus trap npm helper

https://www.npmjs.com/package/focus-trap

### Desired Outcome 

Using best focus trap helper

**Comment by driskull** [comment]
@jcfranco I tried using the other focus trap package without any luck. The problem is that I couldn't find a good way to start the focus trap after the modal becomes active but after DOM nodes were already created or updated.

Do you want to take a stab at it?

**Comment by driskull** [comment]
I think the issue is with the tubbable dependency not supporting shadow dom.

**Comment by driskull** [comment]
Going to close this until the focus helper supports shadow dom.

**Comment by geospatialem** [comment]
Works great! Verified in `beta.98` in Chrome, Firefox, and Edge browsers.
