### ISSUE TITLE
Bug: calcite-value-list: list incorrect after removing an item

### ISSUE THREAD

**Issue by pemberdom** [Esri/calcite-components#1171]
### Summary
Using a calcite-value-list with `removable` items, the list gets wrongly updated when we click on an item to remove it.

Here is an example of how the list is built:

```ts
      <calcite-value-list
        class={someClass}
        multiple={true}
        onCalciteListChange={someHandler}
      >
        <calcite-value-list-item
          removable={true}
          textLabel="F1"
          value={(Math.random() * 10000 * Math.random() * 10000).toString()}
        >
          <calcite-icon slot="secondary-action" icon="x" scale="s"></calcite-icon>
        </calcite-value-list-item>
        <calcite-value-list-item
          removable={true}
          textLabel="F2"
          value={(Math.random() * 10000 * Math.random() * 10000).toString()}
        >
          <calcite-icon slot="secondary-action" icon="x" scale="s"></calcite-icon>
        </calcite-value-list-item>
      </calcite-value-list>
```

<details><summary>HTML extract:</summary>

```html
<calcite-value-list class="field-list hydrated" role="menu" aria-disabled="false" aria-busy="false"
    text-filter-placeholder="Filter results">
    <calcite-value-list-item data-id="calcite-value-list-item-87ecb163-b160-e8a7-076b-1131ba197e74" removable=""
        text-label="X_Coordina" value="55479989.080689356" class="hydrated" tabindex="-1">
        <calcite-icon slot="secondary-action" icon="x" scale="s" calcite-hydrated=""></calcite-icon>
    </calcite-value-list-item>
    <calcite-value-list-item data-id="calcite-value-list-item-259274ac-9834-b462-d8d6-7a6b09820f50" removable=""
        text-label="Ward" value="878304.3884729694" class="hydrated" selected="">
        <calcite-icon slot="secondary-action" icon="x" scale="s" calcite-hydrated=""></calcite-icon>
    </calcite-value-list-item>
    <calcite-value-list-item tabindex="-1" data-id="calcite-value-list-item-3624ad3f-179b-fb2b-50b0-789425ad5c7c"
        removable="" text-label="Community" value="2013857.3126570457" class="hydrated">
        <calcite-icon slot="secondary-action" icon="x" scale="s" calcite-hydrated=""></calcite-icon>
    </calcite-value-list-item>
</calcite-value-list>
```

</details>

### Actual Behavior

When an item is clicked, it is sometimes removed, sometimes not. Sometimes it removes the other items.
In any case it seems to stop displaying the `textLabel` in favor of the `value` after an item has been clicked:

The values use a `Math.random()` for the example:

- Before click:

![image](https://user-images.githubusercontent.com/45367780/97051667-67ddbd80-1534-11eb-92b2-85cf6e88238d.png)

- After click:

![image](https://user-images.githubusercontent.com/45367780/97051643-5e545580-1534-11eb-9be6-af037fcb09f3.png)

### Expected Behavior

The clicked item should be removed from the list. The value property should not be displayed.

### Reproduction Steps

1. Build a list with multiple removable items
2. Click on an item

### Side note
The documentation mentions a `label` property:

![image](https://user-images.githubusercontent.com/45367780/97052793-7cbb5080-1536-11eb-896d-6437271418ed.png)

But when we try to set it we get a TSC error:

![image](https://user-images.githubusercontent.com/45367780/97052779-76c56f80-1536-11eb-89c0-f730c14af749.png)
![image](https://user-images.githubusercontent.com/45367780/97052987-df145100-1536-11eb-80d9-08f27e5e1f4d.png)

So we used `textLabel` instead.

### Relevant Info 
Using CC@next (`"@esri/calcite-components": "next"`)

**Comment by jcfranco** [comment]
@pemberdom I think the doc is misleading. `removable` will render the remove button, which emits `calciteListItemRemove` for the dev to listen and remove the item.

@driskull @asangma Do you remember why the list doesn't remove the item directly? I think the component should handle this instead of leaving it up to the dev.

---

> The documentation mentions a label property:

WRT ☝, could it be outdated types? I couldn't repro locally.

**Comment by driskull** [comment]
I don't remember 🤷

**Comment by jcfranco** [comment]
I'll create a separate issue to look at enhancing the lists to handle item removal.

> When an item is clicked, it is sometimes removed, sometimes not. Sometimes it removes the other items.
In any case it seems to stop displaying the textLabel in favor of the value after an item has been clicked:

Looked at this and the item removal issue is not coming from the component (clicking on the remove button only emits an event). Closing as invalid.
