### ISSUE TITLE
Bug: calcite-value-list-item: setting `removable` to true doesn't change the item

### ISSUE THREAD

**Issue by pemberdom** [Esri/calcite-components#1172]
### Summary

When we set a `removable` true on a `calcite-value-list-item`, it doesn't seen to change its visual. The doc says:

> Set this to true to display a remove action that removes the item from the list.

### Actual Behavior

We use a `calcite-value-list-item` in that way:

```ts
      <calcite-value-list-item
        removable={true}
        textLabel={field}
        value={(Math.random() * 10000 * Math.random() * 10000).toString()}
      ></calcite-value-list-item>
```

But it doesn't display anything 

![image](https://user-images.githubusercontent.com/45367780/97053802-7037f780-1538-11eb-955b-093a9865fe85.png)

Clicking on it does something though.

### Expected Behavior

A remove action is displayed when `removable` is set to true.

### Relevant Info 
Firefox
CC@next

**Comment by pemberdom** [comment]
If we can squeeze this addition in the issue (otherwise I'll create another one): setting `removable` to `false` (explicitly or by not adding the attribute at all) doesn't seem to make any difference with `removable` being `true`.
In both cases the item is clickable (hand cursor), and itms are removed from the list.
cc @jcfranco

**Comment by jcfranco** [comment]
Do you have an isolated test case? I can't reproduce this. 

> In both cases the item is clickable (hand cursor), and itms are removed from the list.

The component does not remove any items. This issue is coming from the consuming code.

**Comment by pemberdom** [comment]
After more discussion, the bug is not valid anymore. Thanks
Closing
