### ISSUE TITLE
Research: explore using the fieldset element in calcite-radio-button-group for a11y

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#1174]
### Background 

The `fieldset` element improves accessibility and is perfectly suited for grouping related radios.
https://www.w3.org/WAI/tutorials/forms/grouping/

### Desired Outcome 

Look at improving readability by wrapping radios with a fieldset rendered by calcite-radio-button-group.

**Comment by julio8a** [comment]
@eriklharper, is this still valid?

**Comment by eriklharper** [comment]
I would say yes, this is still valid and I would actually like to link up the results we get back from Level Access testing on this component to see if using a fieldset would improve the score too.

**Comment by jcfranco** [comment]
@eriklharper Can you provide more info on the results with and without fieldset?

**Comment by geospatialem** [comment]
We have more context on implementing with `<fieldset>` and `<legend>`in issue #4600, so will close this issue as a result.

Also includes additional components that could benefit from this approach.
