### ISSUE TITLE
Bug: Calcite-Combobox calciteComboboxChipDismiss event is not firing

### ISSUE THREAD

**Issue by joshtaylor0404** [Esri/calcite-components#1179]
### Summary
When using the calcite-combobox component, the `calciteComboboxChipDismiss` event does not seem to be firing.

![image](https://user-images.githubusercontent.com/3470614/97332202-6b748b80-1837-11eb-9857-720669ef85b8.png)

In the screenshot above, when I wire up my `handleRemoveTag` function to respond to the event, it never executes when the chip is removed.

CC @paulcpederson

**Comment by jcfranco** [comment]
This was installed a while back and should be in `@next`. @joshtaylor0404 Could you help verify?

**Comment by jcfranco** [comment]
Closing as verified, based on ☝.

@joshtaylor0404 Please create a new issue if anything else comes up. Thanks!
