### ISSUE TITLE
Bug: Calcite-Pagination next button greyed out when last page has 1 result.

### ISSUE THREAD

**Issue by joshtaylor0404** [Esri/calcite-components#1180]
### Summary
When using the calcite-pagination component, if the last page only has 1 result the page will display in the pagination however the next button is greyed out before reaching the last page.

![image](https://user-images.githubusercontent.com/3470614/97333125-6e23b080-1838-11eb-854f-786f2e0d821e.png)

CC @paulcpederson

**Comment by macandcheese** [comment]
Valid
