### ISSUE TITLE
Enhancement: Calcite-Combobox white chip option

### ISSUE THREAD

**Issue by joshtaylor0404** [Esri/calcite-components#1181]
### Description
When using the calcite-combobox component on Esri standard grey backgrounds, the chip blends in with the background. It would be nice if we could have an option for a chip with a white background in these scenarios.

#### Which Component
calcite-combobox

#### Example Use Case
![image](https://user-images.githubusercontent.com/3470614/97333754-205b7800-1839-11eb-82ac-d620a11341a6.png)

CC @paulcpederson

**Comment by paulcpederson** [comment]
@bstifle wondering if a white variant might solve this issue? Either that or integrating the chips into the input of the combobox. Valid use case, though, for sure.

**Comment by macandcheese** [comment]
Agreed @joshtaylor0404 - having a white variant would be great. We even sidestep it's absence in the storybook by placing it on a white background. In the meantime, using the "clear" appearance option will at least give you an outlin:

https://esri.github.io/calcite-components/?path=/story/components-chip--simple&knob-scale=m&knob-appearance=clear&knob-color=grey&knob-dismissible=true

**Comment by bstifle** [comment]
@paulcpederson @joshtaylor0404 

Hey guys!

we have a few variants of chips. for this scenario, i suggest using chip clear:

![image](https://user-images.githubusercontent.com/14083530/97335620-0b3c1480-184c-11eb-84d8-f2f1dbb1e63f.png)


But, fun fact, the styling is off. so i'll open an issue for it.
#1182

**Comment by joshtaylor0404** [comment]
@bstifle - I like that too. I don't think you can change the chip styling through the combobox component though, so we would need to allow for that.

**Comment by bstifle** [comment]
@joshtaylor0404 Oh good catch!! @macandcheese do you have any insight on how to do that?

**Comment by macandcheese** [comment]
Sure, we could add a pass-through prop to the combobox component to choose appearance type. We would want to limit it to that though, not expose all the options for a chip like color, etc.

I think there's some validity to somehow being able to pass content to the image / avatar slot in the chip from the combobox but, we can probably address that if it gets requested.

**Comment by capeoples** [comment]
I wanted to give this issue a bump as I agree that the chips need to be styled to be visible on the grey background. 

Also, I think that the input field should have:
- placeholder text to let you know you can search for tags
- a dropdown indicator to let you know you can browse a predefined list
