### ISSUE TITLE
Enhancement: font-scale updates

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#1186]
### Description
MPV has a release fairly soon and some components need the updated font-scale. 

### Acceptance Criteria 
Consume the typography scale. 

### Relevant Info 
A new type scale was merged in this PR
https://github.com/Esri/calcite-components/pull/897#issue-471136053

#### Which Component
- [ ] accordion
- [ ] button
- [ ] checkbox
- [ ] label
- [ ] input
- [ ] radio (and other radio things)
- [ ] dropdown
- [ ] ~link~ (inherited)
- [ ] select

**Comment by asangma** [comment]
Thanks @julio8a. Installed.

**Comment by julio8a** [comment]
Thanks, Alan!
