### ISSUE TITLE
`calcite-button` - add a disabled attribute

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#119]
Would be nice on `calcite-button` to have a way to disable it

**Comment by macandcheese** [comment]
@kevindoshier sure thing, I think we'll get requests for this pretty frequently. 

We should probably have some docs around *how* to use disabled buttons within an interface - ideally disabled buttons are used sparingly, and when used, they are presented in conjunction with a tooltip (coming soon as a component), or other UI messaging to let a user know user *why* it's disabled.
