### ISSUE TITLE
Enhancement: Add Line-hight values that match 4px scale and apply where necessary

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#1203]
This issue is regarding the alignment of our components to the new scale. We will need to determine where current line-heights should be assigned, and then where scale-based line-heights can be applied.

Scales and rules as follows:

![Spacing Scale](https://user-images.githubusercontent.com/14083530/97637740-3324a700-1a09-11eb-8e8c-362ce50a73f4.png)
![2 Set System](https://user-images.githubusercontent.com/14083530/97637748-37e95b00-1a09-11eb-9868-9bd94adf4534.png)
![Rules](https://user-images.githubusercontent.com/14083530/97637752-39b31e80-1a09-11eb-8a27-b0ae49b0737c.png)

**Comment by julio8a** [comment]
this is still needed.
