### ISSUE TITLE
Enhancement: [Alert / Notice] Add overrideable icon

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1204]
### Description

Copy the logic from input where we set defaults on each color, so when a user requests "icon" they get our recommended set, but they can still override it with a string for calcite ui icon in "icon" prop.

**Comment by layesdesign** [comment]
![Group overview - component option](https://user-images.githubusercontent.com/48816112/97642600-d3c39880-1a02-11eb-94b8-6c8728f8d86d.png)

**Comment by macandcheese** [comment]
Thanks @layesdesign - this one might actually necessitate the other component we were discussing with @mitc7862 - but I'll keep this issue open to allow icon overrides with calcite-ui-icons. Thanks for adding!
