### ISSUE TITLE
Enhancement: Light gray background notice

### ISSUE THREAD

**Issue by layesdesign** [Esri/calcite-components#1205]
Need a notice option to help visually distinguish new features messages from other elements on white background. 

### Example Use Case
<img width="805" alt="Screen Shot 2020-10-29 at 4 27 05 PM" src="https://user-images.githubusercontent.com/48816112/97642975-bd6a0c80-1a03-11eb-989c-20affa95caf5.png">

**Comment by macandcheese** [comment]
Still relevant

**Comment by macandcheese** [comment]
Leave open - could use the background-color prop nomenclature from Modal
