### ISSUE TITLE
Bug: calcite-date opening 2 calendars having 2 different styles

### ISSUE THREAD

**Issue by pemberdom** [Esri/calcite-components#1213]
### Summary

There is a bug while using an association calcite-label + calcite-date (unless they are misused), leading to opening 2 calendars in a row.

### Actual Behavior / Reproduction Steps

See [live example](https://codepen.io/pemberdom/pen/oNbxzVM):

```ts
<calcite-label>
  Pick a date:
  <calcite-date></calcite-date>
</calcite-label>
```

- **Click 1 on the date input: it opens the expected calendar**

![image](https://user-images.githubusercontent.com/45367780/97931318-34641580-1d22-11eb-94b2-a52bd1f3fe37.png)

- **Click 2 after picking a date: the first calendar closes, and this second one opens**

![image](https://user-images.githubusercontent.com/45367780/97931329-3af28d00-1d22-11eb-987c-7eb8d69cd7aa.png)

Note: that second calendar can also be directly open by clicking on the label.

### Expected Behavior

After picking a date on the first calendar to open, it closes and display the selected date in the input, without opening an extra calendar.
Side expectation: clicking on the label doesn't open a second calendar. Or at least they should a similar look

### Relevant Info 

Using Firefox and last version of CC.

**Comment by macandcheese** [comment]
Related FF Issues: 
https://github.com/Esri/calcite-components/issues/953
https://github.com/Esri/calcite-components/issues/931#issuecomment-689197320

**Comment by pemberdom** [comment]
> Related FF Issues:
> #953
> [#931 (comment)](https://github.com/Esri/calcite-components/issues/931#issuecomment-689197320)

Oh damn I didn't check. Thanks
Closing it as it doesn't bring more information, and we don't need to track it on our current project

**Comment by macandcheese** [comment]
It's a weird issue - FF has its own JS injected for date picking.
