### ISSUE TITLE
Boolean "scrollable" option on calcite-panel

### ISSUE THREAD

**Issue by nel11211** [Esri/calcite-components#1215]
The `content-container` element inside `calcite-panel` sets `overflow: auto` by default. It would be valuable (specifically for ArcGIS Charts) to have a `scrollable` prop on the `calcite-panel` to control this, similar to the existing `dismissible` prop. Setting this prop to `false` could set the CSS for the `content-container` to `overflow: hidden`. 

e.g. switching `overflow: auto` to `overflow: hidden`:
![calcite_panel_overflow](https://user-images.githubusercontent.com/66378014/98032553-084f9f80-1dc9-11eb-9f36-bdf7a7eb9987.gif)

**Comment by nel11211** [comment]
Use case is to address part 1 of [this issue](https://devtopia.esri.com/WebGIS/arcgis-charts/issues/2017) in the ArcGIS Charts repo.

**Comment by driskull** [comment]
@asangma what do you think about this? To me it seems nice to just have the scrolling work without a prop.

**Comment by nel11211** [comment]
Closing in favor of #1554, based on conversation with @asangma and Ganesh.
