### ISSUE TITLE
Bug: Calcite-dropdown: For a value list item, popover does not show for second list item.

### ISSUE THREAD

**Issue by kumarGayu** [Esri/calcite-components#1217]
### Summary
![image](https://user-images.githubusercontent.com/9862218/98040817-ca0cad00-1dd5-11eb-82a7-ddcacab321a4.png)

 Calcite-dropdown: For a value list item, popover does not show for second list item.

### Actual Behavior
For value list item, drop down menu is not visible with all the menu items.

### Expected Behavior
For value list item, drop down menu should open.

**Comment by macandcheese** [comment]
Is there a link to reproduce this? It looks like maybe the dropdown-trigger element is somehow positioned weirdly? When you say "popover" - you mean the dropdown container not the "popover" component yeah?

**Comment by kumarGayu** [comment]
Yes it is reproducible. the dropdown is located inside a calcite-value-list-item. and if the list has only one item. In mapviewer beta with chart list which has only oone chart this issue is reproducible.

**Comment by kumarGayu** [comment]
Also it adds a scroll bar because it does not place based on available space.

**Comment by macandcheese** [comment]
Could you add a quick codepen to repro?

**Comment by kumarGayu** [comment]
I think I am not able to repro it with new build.
