### ISSUE TITLE
Bug: Calcite-popover initial placement does not appear to the view portal

### ISSUE THREAD

**Issue by kumarGayu** [Esri/calcite-components#1218]
### Summary
![image](https://user-images.githubusercontent.com/9862218/98041480-d80efd80-1dd6-11eb-86a6-58d19341cf5b.png)

initial placement does not show up on the view screen.

### Actual Behavior
Popover is not visible.

### Expected Behavior
Popover initial placement should be visible.

### Reproduction Steps

1.

**Comment by driskull** [comment]
@kumarGayu This issue seems more specific to an app. Is there something reproducible you could share? It seems like configuration of the popover could fix this. The popover also depends on where it is placed in the DOM.

**Comment by caripizza** [comment]
Hi @kumarGayu, I'm closing this one per @driskull's comment above - please reopen if/when you have more details for us.
