### ISSUE TITLE
Enhancement: [calcite-value-list, calcite-pick-list] handle item removal

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1219]
### Description

Currently, the list components don't handle item removal and push that logic onto the developer. For ease of use, removable items should be removed by the parent list.

cc  @pemberdom

### Acceptance Criteria 

Parent list removes the list item that emits the `calciteListItemRemove` event.

#### Which Component

`calcite-pick-list`, `calcite-value-list`

#### Example Use Case

https://github.com/Esri/calcite-components/blob/a2ae67d1ad303b726e93f2b7e5d0208bada93160/src/demos/pick-list/basic.html#L21-L34 without the removal part (https://github.com/Esri/calcite-components/blob/a2ae67d1ad303b726e93f2b7e5d0208bada93160/src/demos/pick-list/basic.html#L40)

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
Closing as self-verified. 

@pemberdom Please create a new issue if this needs following up.

**Comment by pemberdom** [comment]
@jcfranco A question about the implementation: the event seems to be available on the `calcite-pick-list-item`, but not to the `calcite-value-list-item`:

![image](https://user-images.githubusercontent.com/45367780/100141771-c35ade00-2e47-11eb-8c22-63cbc950d319.png)

![image](https://user-images.githubusercontent.com/45367780/100141794-cbb31900-2e47-11eb-8e07-7d26cf10a64d.png)

Is there a way to listen to that event on the value list item?

**Comment by jcfranco** [comment]
Good catch. I'll create an issue and submit a PR for this.
