### ISSUE TITLE
Enhancement: Consolidate status colors across components

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1220]
### Description
Right now our "color" prop and what values it accepts is different across all components - it's used for styling an accent bar, and an icon if present / requested. The story around using that prop should be consistent where used. Note, it may change to a "status" or other name, but the resultant designs should not change

- Remove "red" as a color option for button, switch, link
- Input Message, Alert, Notice, Modal should all have the same 4 stateful colors (for now called by color name, potentially updated to intent-based nomenclature like info, success, warning, danger, in the future).
- Grey as option for the above (?)
- Update these instances to use the new "single" color css var.

cc @bstifle @asangma

**Comment by julio8a** [comment]
Closing this, as it should be covered here #1144 
re-open if needed.

**Comment by caripizza** [comment]
I'm re-opening this issue to collect feedback from the team. (For now I've left the issue title/description intact.)

For components that have a `color` property, the Calcite Design Team is currently considering the following change for v1:

| component | values | v1.0.0 proposed values |
|---|---|---|
| **colors for _status_** | |
| calcite-alert | `"blue" \| "green" \| "red" \| "yellow"` | `"info" \| "success" \| "danger" \| "warning" \| "brand"` |
| calcite-modal | `"blue" \| "red"` | `"info" \| "danger"` | `"info" \| "success" \| "danger" \| "warning"` |
| calcite-notice | `"blue" \| "green" \| "red" \| "yellow"` | `"info" \| "success" \| "danger" \| "warning" \| "brand"` |
| **colors for _buttons_** | |
| calcite-button | `"blue" \| "inverse" \| "neutral" \| "red"` | `"brand" \| "inverse" \| "neutral" \| "danger"` |
| calcite-chip | `"blue" \| "green" \| "grey" \| "red" \| "yellow"` | `"brand" \| "success" \| "neutral" \| "danger" \| "warning" \| "info"`  |
| calcite-fab | `"blue" \| "inverse" \| "neutral" \| "red"` | `"brand" \| "inverse" \| "neutral" \| "danger"` |
| calcite-split-button | `"blue" \| "inverse" \| "neutral" \| "red"` | `"brand" \| "inverse" \| "neutral" \| "danger"` |

@bstifle @julio8a @macandcheese please correct me if I'm wrong so we can fine-tune the changes needed.

**Comment by bstifle** [comment]
lookin good!!!!

**Comment by caripizza** [comment]
Self-assigning and adding to next sprint per conversation with @julio8a

**Comment by bstifle** [comment]
@caripizza  looks like we need to add one to notice as 'neutral'

![image](https://user-images.githubusercontent.com/14083530/128940372-153e4e3f-89c9-47c2-8bd5-494d443fe5e7.png)

**Comment by caripizza** [comment]
What icon should an alert have when its new color is "brand"?

This is the current list: https://github.com/Esri/calcite-components/blob/master/src/components/calcite-alert/interfaces.ts#L3

**Comment by julio8a** [comment]
If an icon is required, the `info` icon would be more fitting to a general use case.

**Comment by julio8a** [comment]
Moving this one to the next sprint will be a big change. 

CC'ing @jcfranco

**Comment by macandcheese** [comment]
We should also make sure to audit `calcite-input-message`, right now its using nomenclature tied to input validation state, but we could make that consistent with the above proposed values.

**Comment by driskull** [comment]
@macandcheese should the design team look at this issue and make sure the tokens sync up with the proposed values?

**Comment by macandcheese** [comment]
Yeah that would be great, this comment is a good start but should be verified: https://github.com/Esri/calcite-components/issues/1220#issuecomment-890162861

**Comment by ashetland** [comment]
Still need to verify that list. Are we also saying we'll rename the prop from `color` to `status` or is that still an open question?

**Comment by ashetland** [comment]
Okay we'll make sure to look at that as well when we verify the list. I like `status`, but we'll double check that it makes sense in each context. If not, `kind` also seems like a good bet.

**Comment by geospatialem** [comment]
> @geospatialem Just confirming that this is slated for v1.0, yes? If so, we'll prioritize verification.

@ashetland Great question, yes, this is slotted for next month's release.

**Comment by SkyeSeitz** [comment]
Awesome. Aaron and I went over the proposed values. `status` as a new prop name to replace `color` is preferable in our opinion and we can have these changes updated in Figma this week including adding the `neutral` status to `calcite-notice`.

**Comment by ashetland** [comment]
After yet more discussing, we will be adding variants for info or brand when one of them is missing.

**Comment by geospatialem** [comment]
Closing in favor of the #5947 epic
