### ISSUE TITLE
Bug: Accordion doesn't correctly apply transparent prop in FireFox

### ISSUE THREAD

**Issue by evanmosby** [Esri/calcite-components#1225]
### Summary
In FireFox, an Accordion component set to `appearance: transparent` appears white

### Actual Behavior
Component background is white

### Expected Behavior
Component background should be transparent

### Reproduction Steps

1. go to https://esri.github.io/calcite-components/?path=/story/components-accordion--simple
2. Set appearance to transparent
3. Observe background is still white

### Relevant Info 

Latest Firefox

**Comment by macandcheese** [comment]
Ah, looking at the css, there are styles set with `host-context` that are based on the parent `calcite-accordion`'s props - so we will also see this issue with the `appearance=minimal` setting, and in IE and Safari as well (I think they both also have trouble with `host-context`). Also might need to check out setting CSS `calcite-accordion` on the parent that pass through.

Looks like we'll need to grab those props and set them as attributes on the child `calcite-accordion-item` and then style that way.

**Comment by macandcheese** [comment]
Valid

**Comment by benelan** [comment]
verified using the doc sample https://developers.arcgis.com/calcite-design-system/components/accordion/#sample
