### ISSUE TITLE
Bug: calcite-input: doesn't always default to scale=m

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1228]
### Summary

Correct look
<img src=https://user-images.githubusercontent.com/44481292/98183657-7ffef680-1ebd-11eb-861e-77e4fe4bc721.png width=200/>

Wrong look
<img src=https://user-images.githubusercontent.com/44481292/98183673-8a20f500-1ebd-11eb-83e7-bd52080e817f.png width=200/>

The calcite-input components are inside a calcite-block-section. If I start the block-section collapsed and then open it to see these calcite-input boxes all is good. If I start the panel with the block-section open the look of those calcite-input boxes is not right and it's missing the value in it (it's not visible because there is no space).

I can see this issue with next.31, but also on production Map Viewer Beta from Oct 22 (probably beta.42).

I'm not setting a scale and it seems to default to `scale=s` sometimes and other times to `scale=m`. If I specifically tell it to use `scale=s` it's fine. The doc says it should default to m.

test case:
https://www.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0
Click on layer name to make layer active, click Styles tool on right side, click on 'Location' tile, click Transparency by attribute, toggle on -> input boxes look good. Now click Done and click on 'Location' tile and Transparency by attribute again -> now it looks wrong. If you toggle it off and start over it's good again.

### Reproduction Steps

1.

**Comment by macandcheese** [comment]
Is there another component wrapping it with a scale of "s"? Input component looks up the tree to find a scale. We could change how that works as well if desired.

**Comment by AdelheidF** [comment]
The `calcite-input` is inside a `calcite-tooltip-manager` and that's inside a `calcite-block-section` with a `scale=s`.

If that's the case that it would use the scale of the `calcite-block-section` it should always stay at `scale=s` then. But that's not what it does. Because when I open the panel with the block-section expanded, which still uses `scale=s`, the scale of the `calcite-input` switches to `m`.

<img src=https://user-images.githubusercontent.com/44481292/98288616-f5b99f80-1f5b-11eb-94df-648b56d4ce8f.png width=500/>

I'm fine with the behavior of taking on the scale of a parent component. But then it should always stay that way and we should mention that in the doc too.

<img src=https://user-images.githubusercontent.com/44481292/98288402-a70c0580-1f5b-11eb-8325-4e3a51f2423a.png width=500/>

**Comment by eriklharper** [comment]
@AdelheidF Just attempted to reproduce this locally on the latest `master` (see attached video).  Are you still seeing this occur on your end?
[1228 Erik attempted repro.mov.zip](https://github.com/Esri/calcite-components/files/5556459/1228.Erik.attempted.repro.mov.zip)

**Comment by AdelheidF** [comment]
In the smartMapping component I set to to `scale=s`, I no longer rely on the default setting.
I took it out locally and still see the issue.

https://devtopia.esri.com/WebGIS/arcgis-components/blob/master/src/smartMapping/support/Transparency/index.tsx#L572
https://devtopia.esri.com/WebGIS/arcgis-components/blob/master/src/smartMapping/support/Transparency/index.tsx#L592

**Comment by AdelheidF** [comment]
It's still an issue, the default value is wrong, but the work-around to set scale=s is ok.

**Comment by AdelheidF** [comment]
Still the same...

**Comment by macandcheese** [comment]
Valid

**Comment by AdelheidF** [comment]
Still an issue. I removed the `scale=s` prop from the first calcite-input here. The surrounding `calcite-block-section` has a `scale=s` prop.

![image](https://user-images.githubusercontent.com/44481292/120393198-648a8b80-c2e6-11eb-8b5d-692ccd18b8d8.png)

**Comment by AdelheidF** [comment]
Tested with next.237, still seeing the same thing. 
If the block-section (scale=s) is open at start the input box appears by default as scale=m, unless it's explicitly set as scale=s.

**Comment by macandcheese** [comment]
I can't reproduce this anymore - https://codepen.io/mac_and_cheese/pen/bGaYNZr?editors=100

@AdelheidF can you confirm?

**Comment by AdelheidF** [comment]
I can still reproduce this with beta.80 in my React component, maybe it's related to React.
I can't find a way to repro this in a codepen https://codepen.io/afreitag/pen/popdJeQ .

Doesn't matter, I'll close.
