### ISSUE TITLE
Bug: [calcite-dropdown] Inside a flex layout, component no longer hugs trigger content

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#1232]
### Summary
Previously, when placed inside a flex layout, the `calcite-dropdown` component hugged its trigger content. Since https://github.com/Esri/calcite-components/issues/1012, it now expands to fill the available space of its container.

### Actual Behavior
With the below snippet, the dropdown trigger is positioned flush with the container's leading edge.

### Expected Behavior
Because the container is specifying `justify-content: flex-end`, the dropdown trigger is expected to be positioned flush with the container's trailing edge.

### Reproduction Code

```html
<div style="width: 500px; display: flex; justify-content: flex-end;">
    <calcite-dropdown>
        <calcite-icon slot="dropdown-trigger" icon="ellipsis" />
    </calcite-dropdown>
</div>
```

### Relevant Info 
The new behavior stems from adding a `flex-grow: 1` property to the `calcite-dropdown` component[1].

Per web standards, the default value for `flex-grow` property is `0`[2]. As such, I'd posit it's reasonable to expect any calcite component to hug its content by default when placed within a flex layout -- just as any other block or inline level element would behave by default.

Issue discovered in Field Map web app: https://github.com/ArcGIS/field-apps-web/issues/1209.

---
[1] https://github.com/Esri/calcite-components/pull/1013/files#diff-717513f97b6ede6d16b1ad91d26a20deb137955e0743cfebf03b776d4c46a789R4

[2] https://www.w3.org/TR/css-flexbox-1/#flex-grow-property

**Comment by macandcheese** [comment]
Note : any fix here should maintain functionality that was fixed in linked issue.

**Comment by macandcheese** [comment]
Still valid
