### ISSUE TITLE
Bug: calcite-dropdown has broken styling in Firefox

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#1241]
### Summary

The calcite-dropdown seems to be missing some styling. You can see the issue in storybook:
<img width="330" alt="Screen Shot 2020-11-09 at 10 40 20 AM" src="https://user-images.githubusercontent.com/6539297/98582797-4bea5380-2278-11eb-9b95-887c4065b84a.png">

### Relevant Info 

Firefox 82.0.3
macOS 10.15.6

**Comment by macandcheese** [comment]
@asangma could this be a regression from https://github.com/Esri/calcite-components/pull/119?
