### ISSUE TITLE
Bug: calcite-select height issue

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1244]
### Summary

If I place a `calcite-input` right next to a `calcite-select` you can see that the `calcite-select` is higher than the `calcite-input`. It's weird because when I check the height of each they both say `32.6667px`.

![image](https://user-images.githubusercontent.com/44481292/98598950-1487a100-2290-11eb-87eb-0ae85a1e2cb6.png)

![image](https://user-images.githubusercontent.com/44481292/98599172-6d573980-2290-11eb-8f22-1919d70fee75.png)

![image](https://user-images.githubusercontent.com/44481292/98599081-4dc01100-2290-11eb-96b0-976074e63331.png)

### Reproduction Steps

1.

**Comment by AdelheidF** [comment]
Issue seems to have disappeared

<img src=https://user-images.githubusercontent.com/44481292/105616476-0a077e80-5d8c-11eb-9c15-ad3055b64df9.png width=400/>

**Comment by AdelheidF** [comment]
No, issue is still there. You can see it if you use the browser zoom.

<img src=https://user-images.githubusercontent.com/44481292/105616505-68346180-5d8c-11eb-93b7-f15b35782829.png width=400/>

**Comment by julio8a** [comment]
Thanks @AdelheidF

**Comment by AdelheidF** [comment]
Still there...

**Comment by AdelheidF** [comment]
That seems to be good now.

![image](https://user-images.githubusercontent.com/44481292/113026978-744aef80-913e-11eb-92c5-83dfab1b9337.png)
