### ISSUE TITLE
Bug: calcite-panel - section should not have tabindex=0

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1246]
### Summary
Not sure if this is a valid issue...

This is my component using calcite-panel. When the component starts I want it to focus on the close action.
<img src=https://user-images.githubusercontent.com/44481292/98605718-c330df00-229a-11eb-9f13-19608dd6bc9f.png width=200/>

Then on tab it should go directly to the Add expression fab button.
<img src=https://user-images.githubusercontent.com/44481292/98605786-db086300-229a-11eb-96e3-67f8ed410014.png width=200/>

But it doesn't go there directly because it sets the focus on the panel section first. 

![image](https://user-images.githubusercontent.com/44481292/98605941-19058700-229b-11eb-81d2-d6bade446516.png)

Should section have no tabIndex or a tabIndex of -1 instead?

### Reproduction Steps

1.

**Comment by driskull** [comment]
It goes to the section incase it needs to be scrolled. Panels that can scroll need to be able to be focused so the user can scroll them.

**Comment by AdelheidF** [comment]
OK, I guess it could not figure out if there are scrollbars first...

**Comment by driskull** [comment]
yeah it would be quite tricky to do that.
