### ISSUE TITLE
Enhancement: New Current States and visual story

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#1248]
@asangma 
per design meeting, we agreed on these for a new Current style:

![image](https://user-images.githubusercontent.com/14083530/98704227-05f9c200-2342-11eb-9f79-0b66bbbd85b0.png)

### Light theme

_idle_
icons: ui-text-3
bg: ui-foreground-1

_hover_
icons: ui-text-1
bg: ui-foreground-2

_current_
icons: ui-text-1
bg: ui-foreground-3

_indicator_
ui-blue-1

### Dark theme

_idle_
icons: ui-text-3-dark
bg: ui-foreground-1-dark

_hover_
icons: ui-text-1-dark
bg: ui-foreground-2-dark

_current_
icons: ui-text-1-dark
bg: ui-text-1 (#151515)

_indicator_
ui-blue-1-dark

**Comment by macandcheese** [comment]
@bstifle @asangma was this added already?

**Comment by bstifle** [comment]
i think so

**Comment by julio8a** [comment]
Closing, if still needed, please add to refactor for this component: https://github.com/Esri/calcite-components/issues/2452
