### ISSUE TITLE
Bug: calcite-stepper does not work with React DOM manipulation

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#1258]
### Summary

When using calcite-stepper (with layout="horizontal") in a React component, React will throw an error any time you add/remove DOM elements. I'm guessing this is because of the way calcite-stepper moves DOM elements around depending on the active step.

### Actual Behavior

React will throw the error `Node.insertBefore: Child to insert before is not a child of this node` whenever you update the DOM inside a calcite-stepper. Here's a repro case in this codesandbox: https://codesandbox.io/s/nifty-ardinghelli-28ry7?file=/src/App.js

### Expected Behavior

The calcite-stepper should work fine with React. It might require using making steps hidden instead of moving their contents into the active slot.

### Reproduction Steps

1. Open https://codesandbox.io/s/nifty-ardinghelli-28ry7?file=/src/App.js
2. Hit the `Toggle` button
3. You will see the `Node.insertBefore` error.

**Comment by macandcheese** [comment]
To confirm, this only happens in "horizontal" not "vertical" layout, correct?

**Comment by noahmulfinger** [comment]
@macandcheese Interesting, yeah only `horizontal`.

**Comment by macandcheese** [comment]
"vertical" doesn't do anything with slotted content, just shows and hides. "Horizontal" basically functions as tabs and moves slotted content from the stepper item "up" to a single container in the parent calcite-stepper. It seems like this causes more hassle than is needed, there's probably an easier way. We might be able to try and totally re-think that.

**Comment by driskull** [comment]
Looking at the stepper code, it could use quite a bit of cleanup. I see a lot of nodes being created without JSX and some IE specific testing going on.

**Comment by macandcheese** [comment]
Valid

**Comment by driskull** [comment]
@jcfranco @paulcpederson @macandcheese @julio8a  I think we need to revisit this component and it's API.

We could just have a property for `currentPosition` called `step` and get rid of the methods and internal events going on.

The `updateContent()` method seems pretty hacky.

Would we want to do this pre 1.0?

**Comment by macandcheese** [comment]
I think maybe @eriklharper had looked at this (?) - I know it works fine in vertical mode, the bug is in the "tab" functionality in horizontal mode for React since it's (I think?) doing what label does and creating / removing Nodes after it's mounted in React

**Comment by jcfranco** [comment]
> moves slotted content from the stepper item "up" to a single container in the parent calcite-stepper

We should not be manipulating nodes from the light DOM. This workflow will break in all VDOM libs since they assume their VDOM tree is the source of truth.

> We could just have a property for currentPosition called step and get rid of the methods and internal events going on.

Would we ever need to support running checks/code between steps (e.g., validation)? Having a prop might make that tricker to implement.

**Comment by eriklharper** [comment]
I addressed this issue related to stepper a while back https://github.com/Esri/calcite-components/issues/1245.  The way I resolved that was to refactor how I was rendering the `<input>` inside `calcite-radio-button`.  Basically I converted radio-button from a shadowed to a scoped component, which allowed me to render the `<input>` in JSX as opposed to doing it manually with the DOM API.  My guess is that [this line](https://github.com/Esri/calcite-components/blob/ba932e2040a1c6db4311863eeb1e07254d965306/src/components/calcite-stepper/calcite-stepper.tsx#L247) is party to the bug because this was the exact way I used to render the input in radio-button when I was seeing weird issues.

There are lots of funky things that happen when rendering calcite components with vdom libraries if the calcite components manually move DOM outside of the standard Stencil JSX rendering.  We should probably make an effort to deprecate any place where we're doing this kind of manual DOM manipulation in favor of alternate approaches.  My guess is that this issue might not just be specific to React, but possibly other react-like libraries like Preact as well.

**Comment by macandcheese** [comment]
Can we just use tabs internally for horizontal stepper content?

**Comment by driskull** [comment]
> Would we ever need to support running checks/code between steps (e.g., validation)? Having a prop might make that tricker to implement.

Good point.

**Comment by paulcpederson** [comment]
I don't think you need to move dom around to have both of these modes work the same with the same markup. Here's an example with CSS Grid:

https://codepen.io/paulcp/pen/OJbYEVq

Basically you can set the items to be pass through and position the title vs content where you need it on the grid without moving things around. Just show/hide the active step rather than ripping it out and dumping it somewhere else. Would this work?

**Comment by caripizza** [comment]
@driskull @jcfranco @julio8a should this one be assigned to a dev?

**Comment by julio8a** [comment]
This one might need to be added to the next sprint.

**Comment by driskull** [comment]
Should we have a wiki or readme file for 'areas of responsibility' with a table that has each component listed along side a lead dev, backup dev, PE and designer?

**Comment by julio8a** [comment]
Let's talk about this ^

**Comment by eriklharper** [comment]
Sounds like a good CC meeting agenda item.

**Comment by driskull** [comment]
To do this correctly, I think we'll have to introduce a breaking change that adds a slot for content to be below the actual stepper items. Does that sound doable?

Currently, it tries to do this by moving nodes around in light dom.

**Comment by driskull** [comment]
@jcfranco @julio8a I think we need to come up with a better architecture of `calcite-stepper` that doesn't have to move nodes around to display right.

A similar component to t his might be `calcite-tabs`. It has separate child components for the content and header whereas this tries to combine both the content and the header and so this odd logic of moving nodes has to happen.

Should we meet to discuss the options for this?

**Comment by driskull** [comment]
Maybe it should be more like this>

```html
<calcite-stepper icon numbered id="my-example-stepper">
  <calcite-stepper-steps>
    <calcite-stepper-step>Choose method</calcite-stepper-step>
    <calcite-stepper-step>Compile member list</calcite-stepper-step>
    <calcite-stepper-step>Set member properties</calcite-stepper-step>
    <calcite-stepper-step>Confirm and complete</calcite-stepper-step>
  </calcite-stepper-steps>
  <calcite-stepper-item> Step 1 Content Goes Here</calcite-stepper-item>
  <calcite-stepper-item>Step 2 Content Goes Here</calcite-stepper-item>
  <calcite-stepper-item>Step 3 Content Goes Here</calcite-stepper-item>
  <calcite-stepper-item>Step 4 Content Goes Here</calcite-stepper-item>
</calcite-stepper>
```

**Comment by driskull** [comment]
We could create a new steps component and just deprecate stepper?

**Comment by driskull** [comment]
The CSS grid method that @paulcpederson proposed above could work here but would need to be researched. I'm not sure how display:contents would work with shadowDom elements.

The other thing is that these two sets of components are very similar but architecturally different.

**Comment by jcfranco** [comment]
If possible, let's try to preserve the existing structure. We should explore the CSS grid approach before proposing another component.

Sidebar, I think `calcite-tabs` could be simplified as well:

```html
<calcite-tabs ...>
  <calcite-tab-nav slot="tab-nav">
    <calcite-tab-title>title</calcite-tab-title>
    <calcite-tab-title>title</calcite-tab-title>
    <calcite-tab-title>title</calcite-tab-title>
  </calcite-tab-nav>

  <calcite-tab>content</calcite-tab>
  <calcite-tab>content</calcite-tab>
  <calcite-tab>content</calcite-tab>
</calcite-tabs>
```

vs.

```html
<calcite-tabs ...>
  <calcite-tab heading=title ...>content</calcite-tab>
  <calcite-tab heading=title ...>content</calcite-tab>
  <calcite-tab heading=title ...>content</calcite-tab>
</calcite-tabs>
```

There's other web component libs that follow this structure:

https://ant.design/components/tabs/
https://react.carbondesignsystem.com/?path=/story/components-tabs--playground
https://material-ui.com/components/tabs/

The only one that doesn't is Ionic (similar structure): https://ionicframework.com/docs/api/tabs

I'll bring this up in our next meeting and see where we go from there.

**Comment by driskull** [comment]
Sounds good. I'll let someone else handle this issue with the CSS grid approach.

**Comment by macandcheese** [comment]
Still valid - ideally the css grid approach can work.

**Comment by noahmulfinger** [comment]
Is there a way to prevent this issue from getting marked as stale?

**Comment by macandcheese** [comment]
@benelan I think we should re-triage this.

**Comment by macandcheese** [comment]
Keep open

**Comment by macandcheese** [comment]
Note for this - it will likely involve a bit of css refactor - we should make sure we move the styling away from reflected props on the host and to internal container class modifiers. Mentioned here re: https://github.com/Esri/calcite-components/pull/4767

**Comment by jcfranco** [comment]
FYI, I revived https://github.com/Esri/calcite-components/pull/4367 and just need some help from @macandcheese or @asangma on reviewing/tweaking the styles. ⚡🧟 ⚡

**Comment by geospatialem** [comment]
Verified with the [codesandbox sample](https://codesandbox.io/s/nifty-ardinghelli-28ry7?file=/src/App.js) with `next.533` ✅ 

![verified-stepper-dom-manipulation](https://user-images.githubusercontent.com/5023024/179295009-5d7593c0-ed48-41fa-a245-541c072dc219.png)
