### ISSUE TITLE
Enhancement: active vs selected

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1261]
### Description
Our components seem to be inconsistently using `active` or `selected`.
Is this inconsistent? If so, seems like we'd wanna choose one.

Right now, seems like about 18 files use `active` and about 10 use `selected`.

<img src="https://media.giphy.com/media/XHVmD4RyXgSjd8aUMb/giphy-downsized.gif"/>

#### Which Component
Many...

**Comment by asangma** [comment]
@macandcheese @paulcpederson @driskull @bpatterson88 @driskull 

![anybody?](https://media.giphy.com/media/vHwGAMZfWj3mU/giphy.gif)

**Comment by driskull** [comment]
I think it's ok to have both as long as we are using them consistently.

IMO `selected` can be used for form controls or components where the purpose of them is to select item(s).

`active` can be used for toggling UI specific things. 

I think I would need to see where they are used to be able to comment on if we need to change any.

Thoughts?

**Comment by asangma** [comment]
Cool...I'll work on an audit.

**Comment by asangma** [comment]
Here's an audit. Feel free to correct.
| component | active | selected | when true | user concept |
|-------------|:------:|:--------:|-----------|--------------|
| accordion | X | | expanded and icon change | It's open. |
| action | X | | style change | It's "on". |
| alert | X | | displays | It's there or it's the top one in the list. |
| card | | X | checks box, style change | It's a selected one. |
| color-swatch | X | | style change | It's the selected one. |
| combobox | X | | focuses and displays | It's there and focused. |
| combobox-item | | X | style change (adds class) | It's a selected one. |
| date | X | | displays | It's there. |
| date-day | X | | focuses | It's focused. |
| date-day |  | X | style change | It's the selcted one. |
| dropdown | X | | expands | It's there. |
| dropdown-item | X | | style change | It's the selected one. |
| handle | `activated` | | style change & emits kb "up" and "down" | It's on. |
| input-message | X | | displays | It's there. |
| loader | X | | displays | It's there. |
| modal | X | | displays | It's there. |
| notice | X | | displays | It's there. |
| option | | X | style change | It's the selected one. |
| pick-list-item | | X | style change and icon added | It's a selected one. |
| stepper-item | X | | stle change and displays | It's the current step. |
| tab | X | | displays | It's the selected tab. |
| tab-title | X | | style change | It's the selected tab title. |
| tile | X | | stylce change | It's the selected tile. |
| tip | | X | displays | It's there. |
| tree-item | | X | style change and show children? | It's a selected one. |
| value-list-item | | X | style change and icon added | It's a selected one. |

**Comment by driskull** [comment]
From material design:

Selected
A selected state communicates a user choice.

Activated
An activated state communicates a highlighted destination, whether initiated by the user or by default.


Should we follow those? As a prop I do prefer `active` over `activated`

**Comment by asangma** [comment]
Agree. Prefer `active` over `activated`.

It's interesting because in the doc of some components, it says "selected" when describing the `active` property.

Selected being about user choice makes a heap o' sense to me. I think this could make queries more consistent. E.g. when the app needs to query for what the user changed.

Active being more flexible also makes sense, e.g. "it's showing", "it's focused", "it's the current one", etc.

note: I don't see the two as mutually exclusive.

**Comment by driskull** [comment]
Yep, I agree with your assessment about showing vs user choice. 👍

**Comment by macandcheese** [comment]
Thanks for putting that together. I agree, `activated` is weird - we should update `handle` to use active (or selected...).

From the list, it seems like `tip` should definitely be `active` based on other examples. Card makes sense for `selected`. 

Then it's kind of a grey area with tree / accordion for me since either one can be in both a single or multiple select workflow.

All said, I think it's kind of a toss-up, both are valid names and could be argued for - maybe there's something in "components that load without a user choice" - ie tabs have an active tab by default, pick list might not have a selected item by default (unless loaded from saved preference or something).

**Comment by asangma** [comment]
I think some of those gray areas might benefit from the ability to use both props?
E.g. a childless tree-item could be `selected` but wouldn't be able to be `active` where as a parent could do both. Eh?

In regards to the selected item by default, in the majority of cases, the user will still be able to _deselect_ and select that item again. And it might have been something that they'd selected yesterday. Point being, the concept is that it's _selectable_, yah?

To be clear, this goal here is not to choose between the two but rather to be more consistent in our usage of both.

**Comment by macandcheese** [comment]
> E.g. a childless tree-item could be `selected` but wouldn't be able to be `active` where as a parent could do both. Eh?

This seems really, really confusing, ha.

> In regards to the selected item by default, in the majority of cases, the user will still be able to deselect and select that item again.

I was really referring to tabs, and stepper (and single-persist example of accordion) here, where there shouldn't ever be a state when there *isn't* an active item.

Because of the available options for our components (tree, accordion, dropdown, etc., can all be either single or multiple select), I think the "selected for multiple" doesn't quite work.

**Comment by asangma** [comment]
>  I think the "selected for multiple" doesn't quite work.

Hmmm...I don't understand why `selected` wouldn't work for multiple.

re: tabs and stepper
That makes sense. I think those are closer to that "highlighted destination" concept. I think this might also apply to Action in ActionBar.

The more I think about it, the more it seems like `selected` could mostly be used for things that go in a list, e.g. pick-list-item, value-list-item, option, etc.

**Comment by macandcheese** [comment]
> Hmmm...I don't understand why `selected` wouldn't work for multiple.

Because in those examples multiple selection is only one "mode" - they also exist in "single" select modes (by default)

**Comment by asangma** [comment]
Hmmm...doesn't the multiple or single select mode go on the containing component?
E.g.

- each **pick-list-item** can have `selected`
- **pick-list** has single or multiple selection modes

**Comment by macandcheese** [comment]
The comment you quoted was about accordion, dropdown, tree.. Which are single select by default. Tree is currently using selected, the other two active. It feels weird to call an open accordion item "selected", but my point was none of those can be pinned to a "single select gets active, multi select gets selected" rule.

**Comment by asangma** [comment]
Ah...misunderstanding.
I agree that "selected" wouldn't apply to accordion. I think it's more similar to a tab or a step in a stepper.

**Comment by paulcpederson** [comment]
It should probably be noted that the date component has both of these concepts. The day you have actually clicked and selected is "selected" but if you use arrow keys to navigate you'll see an "active" day that will become selected once you actually select.

**Comment by julio8a** [comment]
From a meeting today, it seems that we are okay with selected and active throughout the library. We just need the documentation within the components as to which one is used. 

Closing, re-open if needed.
