### ISSUE TITLE
Bug [calcite-select]: calciteSelectChange event returns previous value as a result

### ISSUE THREAD

**Issue by svlesiv** [Esri/calcite-components#1262]
### Summary
Listener with `calciteSelectChange` event returns previous value as a result.

### Reproduction Steps
1. Attach event listener with`calciteSelectChange` event to `calcite-select` element.
2. Observe the values of the selected elements when changing options.
3. Every time the listener will return the previous value.

### Relevant Info 
https://codepen.io/svlesiv/pen/oNLQooV

**Comment by jcfranco** [comment]
Installed. 

@svlesiv Could you verify with `@esri/calcite-components@next`?

**Comment by svlesiv** [comment]
I've tested `calcite-select` component in the app, and I'm not getting that issue anymore. Thank you!

**Comment by jcfranco** [comment]
Awesome, thanks for verifying! 🙌
