### ISSUE TITLE
Bug: English placeholder text for date component is strange

### ISSUE THREAD

**Issue by capeoples** [Esri/calcite-components#1265]
### Summary
Currently, the placeholder text for the date component is a bit weird. 

### Actual Behavior
The current format is M/d/yy
<img width="365" alt="Screen Shot 2020-11-11 at 1 34 48 PM" src="https://user-images.githubusercontent.com/30473086/98867114-dff81e80-2422-11eb-9d50-2fef27a435ae.png">

### Expected Behavior
I think the casing should be consistent, and possibly follow a format like MM/DD/YYYY

cc @joshtaylor0404

**Comment by paulcpederson** [comment]
This is a CLDR unicode spec, but agree it's not friendly to end users. Wondering how it should be in all languages, though. Assuming we'd want to have the letter of the actual unit in that language? 

Maybe @raje9276 has ideas on how this should be handled?

**Comment by macandcheese** [comment]
It looks like in the definition .JSON there is a separate "placeholder" value, maybe we can for now update in en-* and update others as requests for change comes in? (currently all the palceholders from what I've seen just mirror the unitOrder"?

**Comment by paulcpederson** [comment]
Yeah when I spec'd this translations format the "placeholder" was meant to be an actual user-friendly translated value but I think it just got overlooked.

**Comment by macandcheese** [comment]
Is it valid to use the placeholder value, and for this particular issue just update en-* to the `MM/DD/YYYY` example Colleen provided until other language changes are requested? Was just pinged about this from Julio. cc @capeoples

**Comment by paulcpederson** [comment]
We could just update all of them and respect their ordering. Do you want me to take a crack at that?

**Comment by macandcheese** [comment]
It looks like placeholder is already set in the data... maybe just updating the "en" strings for now will be sufficient? Unless you meant you to handle passing a custom string instead as a prop.

**Comment by paulcpederson** [comment]
No I mean hand-editing the placeholder so it looks how we want it to look in each language (respect unit order). So in `ca`:

```diff
-  "placeholder": "d/M/yy",
+  "placeholder": "DD/MM/YYY",
```

but in `en`:

```diff
-  "placeholder": "M/d/yy",
+  "placeholder": "MM/DD/YYY",
```

**Comment by macandcheese** [comment]
Still valid

**Comment by julio8a** [comment]
@paulcpederson, Any updates on this one?

**Comment by paulcpederson** [comment]
I have not done this, but it shouldn't be too hard

**Comment by paulcpederson** [comment]
Verified in beta.49
