### ISSUE TITLE
Enhancement: Add alignment props for Button

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1267]
### Description
Allow users to define how the nodes in a Button align.

### Acceptance Criteria 
- center (default)
- start
- end
- space between

This will make it so users will not need to hand-roll their own buttons to achieve this in their interfaces.

cc @paulcpederson @macandcheese @AdelheidF 

#### Which Component
Button

**Comment by macandcheese** [comment]
Is the intent with this to only have this work for widths other than auto - half and full?

**Comment by asangma** [comment]
Good point. It would "work" with all of them, but effects would be more apparent in half & full.

**Comment by asangma** [comment]
Also....this should probz be a "justify" prop.

**Comment by AdelheidF** [comment]
Is this a duplicate of this one? https://github.com/Esri/calcite-components/issues/922

**Comment by macandcheese** [comment]
Yeah, nomenclature for this is tough. Other "alignment" props so far are ... "alignment". I don't know if the prop needs to be 1:1 with the css property it sets.

**Comment by asangma** [comment]
Ah! Thanks @AdelheidF.

**Comment by asangma** [comment]
Sorry @macandcheese. this is a dup. Moving over to #922
