### ISSUE TITLE
Bug: Disabling a button in Chrome/Edge while its tooltip is visible makes the tooltip sticky

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#1269]
### Summary
When a button is associated with a tooltip (in Chrome and Edge), disabling the button while the tooltip is visible causes the tooltip to never disappear.

Disabling a button when clicked is a typical pattern to enforce atomic event handling.

### Actual Behavior
Following the below reproduction steps, the tooltip never disappears until the web page is reloaded.

### Expected Behavior
The tooltip should either disappear in response to the button becoming disabled or the mouse leaving.

### Reproduction Steps
```html
<calcite-tooltip reference-element="tooltip-button">This is the message of the tooltip</calcite-tooltip>
<calcite-tooltip-manager>
  <p>
    Lorem <button id="tooltip-button" onclick="this.disabled = true">ipsum</button> dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  </p>
</calcite-tooltip-manager>
```
1. Hover the button until the tooltip appears.
2. Click the button.
3. Move the mouse off the button.

### Relevant Info 
Chrome and Edge (Firefox and Safari work as expected)
macOS 10.15.7

**Comment by nwhittaker** [comment]
Digging into this, it looks like the failure is occurring with this conditional in `CalciteTooltipManager.focusedToggle()`:
https://github.com/Esri/calcite-components/blob/f055e85659382ab75c69916789ac8fc6135542b0/src/components/calcite-tooltip-manager/calcite-tooltip-manager.tsx#L75-L77

For the test case `referenceEl` and `hoveredReferenceEl` are still equal because the `mouseleave` event hasn't triggered yet. When clicking the button in Chrome, the order of events is
1. `mouseenter`
2. `focus`
3. `blur`
4. `mouseleave`

If I switch `mouseleave` to fire before `blur`, I get the expected behavior of the the tooltip disappearing.

In Firefox and Safari, the `focus` and `blur` events are not fired when clicking on a button[1] which would explain why this is a Chrome-only issue.

---
[1] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus

**Comment by driskull** [comment]
Installed. should be in the next release. Could you test when that happens @nwhittaker ?

Thanks!

**Comment by nwhittaker** [comment]
Verified in `1.0.0-next.59` and this looks to be working. Thank you!
