### ISSUE TITLE
Enhancement: [calcite-input] background-color attribute

### ISSUE THREAD

**Issue by svlesiv** [Esri/calcite-components#1272]
### Description
The background color of `calcite-modal` is matching the background color of `calcite-input` component. It would be nice to distinguish the input field from the background.

<img width="788" alt="Screen Shot 2020-11-12 at 1 52 22 PM" src="https://user-images.githubusercontent.com/35533801/99002514-611de700-24f1-11eb-916c-c7de4d58843f.png">

### Acceptance Criteria 
The background color options for `calcite-input` component would be a great addition.

#### Which Component
calcite-input

#### Example Use Case
<img width="780" alt="Screen Shot 2020-11-12 at 1 59 45 PM" src="https://user-images.githubusercontent.com/35533801/99002593-827ed300-24f1-11eb-8402-c32f318b2368.png">

**Comment by macandcheese** [comment]
Yeah I think this is valid... Even in instances where it's on white background vs. grey background in light theme this comes into play. 

In the meantime, you could set "background-color" of modal to grey to get some contrast, not sure if that works for the rest of the design but its a currently available option until this gets added : https://esri.github.io/calcite-components/?path=/story/components-modal--dark-mode&knob-active=true&knob-color=&knob-background-color=grey&knob-scale=m&knob-width=s&knob-fullscreen=&knob-docked=&knob-disable-escape=&knob-no-padding=&knob-close-label=Close

**Comment by svlesiv** [comment]
Changing the modal background is not matching our designs. Thank you for looking into this issue.
