### ISSUE TITLE
Enhancement: update Input borders to be AA accessible based on agreed designs

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#1274]
![Standard Inputs](https://user-images.githubusercontent.com/14083530/99119954-adcff380-25bf-11eb-9bd7-3133b05e2e9c.png)

### Light Theme
Change borders to calcite-ui-border-input(#949494) as changed in this issue https://github.com/Esri/calcite-colors/pull/49

### Dark Theme
Change borders to calcite-ui-border-input-dark (#757575)
Change `read only` and `prefix` and `suffix` fills to ui-background-dark (#353535)

**Comment by julio8a** [comment]
@bstifle, we good to close this?

**Comment by bstifle** [comment]
Still valid. The borders have not been updated in code

**Comment by bstifle** [comment]
assigning @caripizza since it's related to https://github.com/Esri/calcite-components/issues/816#issuecomment-784397087

**Comment by bstifle** [comment]
valid and being addressed in refactor

**Comment by caripizza** [comment]
@bstifle is this issue work already included in the Tailwind/Figma refactor designs? If so can we close this one?

**Comment by bstifle** [comment]
Has not been addressed yet

**Comment by bstifle** [comment]
@caripizza 

affected components

input, select, combobox, checkbox, radio button, radio group, inline editable, switch
 
and consequently, time picker input, and color picker

**Comment by julio8a** [comment]
Some of these already have the input-border, input is one of the main outliers atm. Ben is working on input refactor
https://github.com/Esri/calcite-components/issues/2455#issue-939111957

**Comment by caripizza** [comment]
@bstifle this one looks complete to me now that the input refactor pr is merged. Can you confirm and close if so?

**Comment by bstifle** [comment]
correct!
