### ISSUE TITLE
Bug: calcite-panel loading=true doesn't align footer buttons correctly

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1275]
### Summary

In my smartMapping component when I load a MapService sublayer it might take a while before I have all info to load the UI. So I create the panel, pretty empty, with loading=true. Somehow the Done and Cancel buttons don't appear at the bottom of the panel though, even though the panel height is correctly set as 100%. Once I update the panel with loading=false it's fine.

<img src=https://user-images.githubusercontent.com/44481292/99120702-26c74f00-25b0-11eb-9ac9-c51c27590cd7.png width=200/>

### Reproduction Steps

1.

**Comment by driskull** [comment]
Hey @AdelheidF, can you not show the buttons until the panel is done loading?

The other option would be to set a 100% height div in the content until you have the actual content but it would probably be better to just not show the buttons until they can be used. What do you think?

**Comment by AdelheidF** [comment]
Yes, I can use this work-around. I originally wanted to show just the content part of the panel in a loading state.
