### ISSUE TITLE
Enhancement: calcite-panel setFocus also needs to focus flow back button

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1277]
### Description
Currently there is no way to set the focus on the back button of a flow panel.
`setFocus(focusId?: "dismiss-button")`

Also, would it make sense to automatically set the focus on the back button if the user travels through a flow?

<img src=https://user-images.githubusercontent.com/44481292/99287158-bfe3a900-27ee-11eb-8a2c-3e9b996ea19a.png width=200/>

cc @dhrumil83

**Comment by driskull** [comment]
@jcfranco I'm wondering if we should update all of our default setFocus methods to by default somehow find the first focusable element inside the shadow dom?

We would need some kind of utility for this.

For now, i'll create a way to focus to the back button. sound good?

**Comment by jcfranco** [comment]
Great idea! Can you create an issue for this util for me?

**Comment by driskull** [comment]
Created! maybe we can get the `tabbable` dependency working for shadow dom?

**Comment by driskull** [comment]
Installed

**Comment by AdelheidF** [comment]
Focus works well now but I don't see "back-button" in the doc. Had to look in the code.

**Comment by driskull** [comment]
Yeah release should get it in the doc.
