### ISSUE TITLE
Bug: Color - RGB / HSV values can extend past channel limit / below 0

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1283]
### Summary
It's possible to enter or increment / decrement values to less than zero or more than the channel limit.

### Actual Behavior

![Screencast 2020-11-19 at 12 39 44 PM (1)](https://user-images.githubusercontent.com/4733155/99721689-6dabbd80-2a64-11eb-9903-6935293a2f4a.gif)

### Expected Behavior
Incrementing / Decrementing these inputs should limit to the RGB / HSV value limit / 0
Entering explicit values should be validated on blur.

### Reproduction Steps
https://esri.github.io/calcite-components/?path=/story/components-color--simple

### Relevant Info 
@jcfranco I might try to take a stab at this along with the "shift key" portion of : https://github.com/Esri/calcite-components/issues/866

**Comment by jcfranco** [comment]
Weird, the color component [does clamp the value on input](https://github.com/Esri/calcite-components/blob/0482868d548f40f68ae02eb4a5e333fcd7d12443/src/components/calcite-color/calcite-color.tsx#L276-L278), but the underlying input doesn't seem to be updating.

**Comment by julio8a** [comment]
@jcfranco, still valid?

**Comment by jcfranco** [comment]
I think this got fixed by #866. @macandcheese Can you confirm?

**Comment by julio8a** [comment]
Verified! thx @jcfranco!
