### ISSUE TITLE
Bug: Popover placement 

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#1284]
## Summary
The `placement` property values of "top-end" and "bottom-end" aren't working in larger window / when there is horizontal space for "top-start" or "bottom-start" instead. 

#### When it does work
The "top-end" and "bottom-end" values work on smaller screens.

![popover-small-screen](https://user-images.githubusercontent.com/55154968/99726497-c9ca0e00-2a73-11eb-8c95-710c62693181.gif)
 
#### When it doesn't work
The "top-end" and "bottom-end" values don't work if there is enough horizontal screen space for the popover to be placed "top-start" or "bottom-start". In this case, the placement defaults to "[top or bottom]-start".

![popover-wide-screen](https://user-images.githubusercontent.com/55154968/99726336-9be4c980-2a73-11eb-855f-f8aea2a4a698.gif)

## Expected Behavior
The "top-end" and "bottom-end" values should take effect on all screen sizes

## Reproduction Steps

1. Open the popover component in the storybook
2. Increase your window size to > 1750px if it isn't already
3. Switch between placement values of "top-end", "top-start", "bottom-end", and "bottom-start"

## Relevant Info 
Browser: Chrome

**Comment by driskull** [comment]
@joeyHarig I believe the Popper.js dependency is doing it's best to try and place the popover in the best location it can. I think if it doesn't fit in a position, it falls back to another position.

There are some FAQ's here: https://popper.js.org/docs/v2/faq/
