### ISSUE TITLE
Enhancement: include group titles for triggering maxItems in a calcite-dropdown

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#1289]
### Description
The `maxItems` property specifies "the max items to display before showing the scroller". If the dropdown is composed of groups with titles, then those title lines are not included for triggering the maxItems scroller.

### Acceptance Criteria 
All lines of a dropdown are counted for triggering the maxItems scroller.

#### Which Component
calcite-dropdown

#### Example Use Case
6 lines are displayed when `maxItems`= 4 because of the two group titles:

![image](https://user-images.githubusercontent.com/2125181/99856816-acae4180-2b3e-11eb-901f-1efc2da8c99d.png)

```html
<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" href="https://esri.github.io/calcite-components/build/calcite.css" type="text/css" />
  <script src="https://requirejs.org/docs/release/2.3.6/minified/require.js"></script>
</head>
<body>
  <calcite-dropdown max-items="4">
    <calcite-button class="sort-control" slot="dropdown-trigger" icon-start="sortAscending"></calcite-button>
    <calcite-dropdown-group group-title="Sort by" selection-mode="single">
      <calcite-dropdown-item value="relevance" role="menuitem" selection-mode="single" tabindex="0">Relevance</calcite-dropdown-item>
      <calcite-dropdown-item value="modified" role="menuitem" selection-mode="single" tabindex="0">Date Modified</calcite-dropdown-item>
      <calcite-dropdown-item value="title" role="menuitem" selection-mode="single" tabindex="0">Title</calcite-dropdown-item>
    </calcite-dropdown-group>
    <calcite-dropdown-group group-title="Sort direction" selection-mode="single">
      <calcite-dropdown-item active="" value="asc" role="menuitem" selection-mode="single" tabindex="0">Alphabetical</calcite-dropdown-item>
      <calcite-dropdown-item value="desc" role="menuitem" selection-mode="single" tabindex="0">Reverse-Alphabetical</calcite-dropdown-item>
    </calcite-dropdown-group>
  </calcite-dropdown>

  <script>
    require.config({ paths: { "calcite-components": "https://esri.github.io/calcite-components/build/calcite" } });
    require(["calcite-components"], function () {});
  </script>
</body>
</html>
```

**Comment by macandcheese** [comment]
Hm, I wonder if this is a docs enhancement since the prop is technically working as expected, showing 4 items. 

The title height is included in the calculation of drop down container height and (like items) could also be comprised of multiple lines of text.

Is the intention to just show the first 3 items? Kind of hesitant to change how it works to make “items” include “titles” since the nomenclature is correct now, but I do think we can make the documentation clearer and specifically note the prop doesn’t include titles, and only items, in the count. Would that be acceptable here?

**Comment by driskull** [comment]
Yeah i'm not sure I like this prop at all. Can't we just have a heightScale prop to define the height of the menu as s,m,l,xl?

**Comment by macandcheese** [comment]
I think "max-items" is justified, if it were height scale you'd end up with partially visible items... I think a solution here is just to document that "max-items" refers only to calcite-dropdown-items and not group-titles included in calcite-dropdown-groups.

**Comment by macandcheese** [comment]
Updated docs in https://github.com/Esri/calcite-components/pull/1343
