### ISSUE TITLE
Enhancement: [calcite-color] Handle hue values of 0 and 360 as if they were separate values

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1297]
### Description

Although the behavior is correct (360 === 0), the immediate updating of the hue input and slider thumb to 0 may be jarring to users. 

cc @macandcheese 

### Acceptance Criteria 

Update the color picker to handle 0 and 360 as if they were different values. When 0, the hue input should show 0 and the hue slider thumb should render at the leftmost edge, and when 360, the input will show 360 and the hue slider thumb will render at the rightmost edge.

### Relevant Info 

Stems from https://github.com/Esri/calcite-components/pull/1295#issuecomment-732398371

#### Which Component

`calcite-color`

#### Example Use Case

N/A

**Comment by macandcheese** [comment]
Another option could be to let users cycle continuously forward or backward through all values...

**Comment by jcfranco** [comment]
@macandcheese I like your suggestion better. It would provide a consistent experience for all inputs. No special treatment of hue. #hueaintspecial😭

**Comment by jcfranco** [comment]
@macandcheese Sorry, I had misread your comment and thought it would be for all inputs. It was meant only for hue. 😅 Per our conversation, we will not allow values to cycle and instead update the color picker to handle 0 and 360 as if they were different values. When 0, the hue input should show 0 and the hue slider thumb should render at the leftmost edge, and when 360, the input will show 360 and the hue slider thumb will render at the rightmost edge.

I'll update the issue description.
