### ISSUE TITLE
Enhancement: Update outline and clear prop border colors to match input borders

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#1301]
![image](https://user-images.githubusercontent.com/14083530/100135801-c4900900-2e4f-11eb-9cb8-9f4817e82ddd.png)

### Light Theme
• UPDATE dark prop border color for outline and clear to use blk-100 (#949494)
matches input border color

### Dark Theme
• UPDATE light prop border color for outline and clear to use blk-130 (#757575)
matches input border color

**Comment by julio8a** [comment]
I'm' assuming this one is still valid? we should just add as an action item for input, buttons, etc., and close this one.

**Comment by caripizza** [comment]
@bstifle can we close this one? Input has the border-input color. However, Figma shows different border colors for buttons based on color so I don't think that part of the issue is valid anymore.

**Comment by bstifle** [comment]
Yep! oldie!
