### ISSUE TITLE
Bug: calcite-select should use inherited theme

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#1305]
### Summary

A theme set on a parent element (`<body theme="dark">`) does not set the calcite-select theme to dark.

### Actual Behavior

When theme is set on a parent element, calcite-select still uses the default (light) theme.

### Expected Behavior

calcite-select should inherit theme from parent.

### Reproduction Steps

```html
<div theme="dark">
  <calcite-select>
    <calcite-option>high</calcite-option>
  </calcite-select>
</div>
```

https://codepen.io/gpbmike/pen/OJRLbLr

**Comment by julio8a** [comment]
Is this still an issue?
On the latest storybook updating the prop updates the select theme
https://esri.github.io/calcite-components/?path=/story/components-select--basic

**Comment by gpbmike** [comment]
> Is this still an issue?
> On the latest storybook updating the prop updates the select theme
> https://esri.github.io/calcite-components/?path=/story/components-select--basic

Looks good in beta 48. Thanks!
