### ISSUE TITLE
Enhancement: [value-list-item] Expose `calciteListItemRemove` event

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1306]
### Description

Stems from https://github.com/Esri/calcite-components/issues/1219#issuecomment-733185191. `calcite-value-list-item` needs to expose the same event introduced by #1219 since it is wrapping a `calcite-pick-list-item`.

@pemberdom

### Acceptance Criteria 

`calciteListItemRemove` shows up in `calcite-value-list-item` typing.

#### Which Component

`calcite-value-list-item`

#### Example Use Case

See https://github.com/Esri/calcite-components/issues/1219#issuecomment-733185191.

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
@pemberdom could you help verify this one w/ @next?

**Comment by pemberdom** [comment]
> @pemberdom could you help verify this one w/ @next?

ya

**Comment by pemberdom** [comment]
> > @pemberdom could you help verify this one w/ @next?
> 
> ya

Made a simple [Codepen](https://codepen.io/pemberdom/pen/zYKvYZN?editors=1111), looks good to me 👍

**Comment by pemberdom** [comment]
> > @pemberdom could you help verify this one w/ @next?
> 
> ya

Works good @jcfranco  👍. Tested on this [Codepen](https://codepen.io/pemberdom/pen/zYKvYZN?editors=1111) (checking the event this time).

**Comment by jcfranco** [comment]
Awesome. Thanks! 🙌🏼
