### ISSUE TITLE
Enhancement: [calcite-select] multiple selection mode

### ISSUE THREAD

**Issue by svlesiv** [Esri/calcite-components#1312]
### Description
Multiple selection mode would be a nice addition to the `calcite-select` component.

#### Which Component
`calcite-select`

#### Example Use Case
Multiple items can be selected.
```js
<calcite-select selection-mode="multi">
  <calcite-option>1</calcite-option>
  <calcite-option>2</calcite-option>
  <calcite-option>3</calcite-option>
</calcite-select>
```

**Comment by driskull** [comment]
I think in this case, we may prefer users to use a PickList/ValueList or Combobox. @julio8a thoughts?

**Comment by julio8a** [comment]
Agreed, picklist or value list should work. @svlesiv can you try either of those components?

**Comment by svlesiv** [comment]
I will try it, thank you!

**Comment by svlesiv** [comment]
Among three options (PickList, ValueList, Combobox), Combobox seems more appropriate for us. In that case, we would need to switch from Select to Combobox everywhere to be consistent. Thank you for your response.

**Comment by driskull** [comment]
Awesome. i'll close this. Feel free to reopen if necessary.
