### ISSUE TITLE
A11y: Checkbox read twice from screen reader

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#1318]
### Summary

When interacting with a checkbox from a screenreader like NVDA, the checkbox is read twice.

### Actual Behavior

Screen reader reads:

> Checkbox not checked Checkbox not checked

### Expected Behavior

Screen reader should read:

> Checkbox not checked

### Reproduction Steps

1. turn on screen reader
2. move focus to any checkbox component

### Suggestion

Either hide the internal checkbox from the screen-reader or stop treating the component host as `role-checkbox`

**Comment by jcfranco** [comment]
I believe this is fixed in the latest version. Tested w/ NVDA + Chrome, Firefox and VO + Chrome. Closing!
