### ISSUE TITLE
Bug: Calcite File Input Padding

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#1323]
### Summary
The file input could use some padding in between the button and the text. 

<img width="340" alt="Screen Shot 2020-11-30 at 2 06 33 PM" src="https://user-images.githubusercontent.com/55154968/100663008-a92b6f00-3323-11eb-8945-dc1d9cb9bda8.png">

**Comment by macandcheese** [comment]
These are notoriously hard to style with overrides ... I know @bstifle had some ideas for a more “full replacement “

**Comment by caripizza** [comment]
@joeyHarig is this issue still relevant? If so, can you provide a code snippet for your example screenshot?
