### ISSUE TITLE
Enhancement: Input Message - Allow custom icon

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1330]
### Description

Similar to notice and alert, we should allow a custom icon to be passed in addition to the status-based default recommendation.

### Acceptance Criteria 
- update icon from boolean to boolean | string where a string of a valid calcite ui icon renders a custom icon instead of the recommended default (see logic in notice, alert)
- update stories
- update dev demo

**Comment by bstifle** [comment]
Verified
