### ISSUE TITLE
Issue with Edge browser

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#134]
We are seeing issues trying to load the new mapViewer into Edge, you can see the details of it here, it appears something with calcite-components but not positive.

https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/585

**Comment by paulcpederson** [comment]
Related to https://github.com/Esri/calcite-components/issues/100 ?

**Comment by kevindoshier** [comment]
Seems similiar, the errors are the same but just different property names

`[object Error]: {description: "Unable to get property 'O' of undefined or null reference", message: "Unable to get property 'O' of undefined or null reference", number: -2146823281, stack: "TypeError: Unable to get property 'O' of undefined or null reference at Anonymous function (http://local.arcgis.com:5555/node_modules/@esri/calcite-components/dist/calcite/p-aef71dcb.js:1:10874) at grouptitle.set (http://local.arcgis.com:5555/node_modules/@esri/calcite-components/dist/calcite/p-aef71dcb.js:1:10846) at h (http://local.arcgis.com:5555/node_modules/@esri/calcite-components/dist/calcite/p-k7ztosol.entry.js:1:159) at Anonymous function (http://local.arcgis.com:5555/node_modules/@esri/calcite-components/dist/calcite/p-aef71dcb.js:1:15494) at Generator.prototype.next (native code)"}`

**Comment by kevindoshier** [comment]
@paulcpederson - I cant change labels/etc in this repo, pls mark as duplicate if you feel its a duplicate of #100

**Comment by paulcpederson** [comment]
@macandcheese is looking into this, not sure if this is duplicate yet but I'll follow up

**Comment by macandcheese** [comment]
@driskull yeah it's weird, it's emitted for each `EventEmitter` for each and every component, only three of which seem to use componentDidUnload at all, so I think it's an indication of some more systematic structuring issue... 👀 still looking...

**Comment by macandcheese** [comment]
@kevindoshier Closing this as this has been broken into smaller issues for each.
