### ISSUE TITLE
Bug: pagination arrows point wrong way in RTL

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#1341]
### Summary

![Screen Shot 2020-12-02 at 9 42 40 AM](https://user-images.githubusercontent.com/1031758/100910368-bd39b280-3482-11eb-8022-6b6dca413da2.png)

### Actual Behavior

`> <`

### Expected Behavior

`< >`

### Reproduction Steps

1. Set `dir=rtl`
2. Observe

**Comment by bstifle** [comment]
Verified
