### ISSUE TITLE
Tooling: increase stale-to-closed duration

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1348]
## Summary 
I think 7 days feels a bit short, considering that’s only 5 working days to check in. I think we suffered a bit from having to go through a few hundred, but a lot of the ones that were just closed after 7 days were probably still valid.

14/21 days from marked stale -> close seems a bit more lenient? Too long ?

**Comment by driskull** [comment]
How about we bump the state from 30 to 45 and closed from 7 to 14? I think the default stale is 60 so we could maybe do that too.

What do you think @macandcheese?

**Comment by macandcheese** [comment]
Yeah happy with either. Just giving folks a little more time before it’s closed. I think this was mostly just an issue this first batch or two since we didn’t go through all couple hundred.

Proposed sounds gr8 to me.

**Comment by macandcheese** [comment]
Not sure how to verify this aside from looking at `stale.yml` file - but.. looks good 😅

**Comment by driskull** [comment]
I guess it's the wait and see approach :D
