### ISSUE TITLE
Enhancement: Date - Separate Date picker from input 

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1349]
### Description

Separate the built in input in the Date component from the DatePicker portion.

This will allow a developer to use the date picker without having to turn off the input and is more modular in nature.

### Acceptance Criteria 

The input is not tied to the Date component.

If a user wants the date input and date component combined, they would have one of the following:

- calcite-input with type of "date-picker"?
  - Would need to figure out how to apply date picker options.
- new calcite-input-date component?

#### Which Component

Date

**Comment by julio8a** [comment]
Does this one just need to be verified?

**Comment by julio8a** [comment]
verified.
