### ISSUE TITLE
Bug: Slovak calendar should start on Monday instead of Sunday

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#1355]
### Summary

The `sk.json` file is wrong. 

### Actual Behavior

Weeks when `locale="sk"` start on Sunday.

### Expected Behavior

Should start on Monday

### Reproduction Steps

1. Set Calendar locale to `sk` 
2. Observe!

**Comment by paulcpederson** [comment]
@caripizza this could be a good way to get to know the date's localization strategy, feel free to reassign 👍

**Comment by julio8a** [comment]
Unless I'm missing something, the week still shows starting on Sunday (ned.)

Storybook:
![image](https://user-images.githubusercontent.com/6144462/106029287-c78ebc00-6081-11eb-88ae-119c9fd059c0.png)

Local build:
![image](https://user-images.githubusercontent.com/6144462/106029369-dd03e600-6081-11eb-9581-740a3689dbd7.png)

**Comment by caripizza** [comment]
@julio8a did you select the "sk" locale in your screenshots?

**Comment by paulcpederson** [comment]
@julio8a clear your cache and try again, storybook caches pretty heavily

**Comment by paulcpederson** [comment]
I just verified this on docs site.

**Comment by julio8a** [comment]
ah, cache issue, thx @paulcpederson.
