### ISSUE TITLE
Bug: Tab highlight is incorrect in RTL

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#1356]
### Summary

When viewed in right to left languages (Hebrew, Arabic), the tabs component displays the highlight on the wrong side:

![Screen Shot 2020-12-04 at 9 34 31 AM](https://user-images.githubusercontent.com/1031758/101195308-1422c180-3614-11eb-8300-cb7631d3b939.png)

### Actual Behavior

Blue underline displays on left.

### Expected Behavior

Should display on right.

### Reproduction Steps

1. Set `dir="rtl"` on the `calcite-tabs` component.
2. Make sure one of the links is active
3. The links will be on the right, but the underline is on the left

**Comment by paulcpederson** [comment]
@caripizza this could be a good way to learn how right to left works 😄

**Comment by bstifle** [comment]
Verified
