### ISSUE TITLE
Enhancement: Y Axis value indication for Calcite slider-histogram

### ISSUE THREAD

**Issue by RSantosGIS** [Esri/calcite-components#1373]
### Description

I love the calcite-slider histogram except that there is no way to communicate to the user the y value at a particular point along the slider.  I am using a two thumb slider to represent a range of dates on the x-axis, with the y-axis histogram magnitude representing the feature count in a date-range increment.  An option to turn on a y-axis with a couple value labels to provide some kind of context, or perhaps have the value appear when the histogram is hovered is the kind of thing I'm looking for

### Acceptance Criteria 
Setting toggle to turn on y-axis with some number of label values, representing the range of possible magnitude values mapped by the histogram.
(Optional): ability to hover over a point of the histogram graph and see the exact y-value at that point.
![Y-axis histogram idea](https://user-images.githubusercontent.com/36513418/101395409-82bf8380-388f-11eb-8929-c71b23e2ccf1.png)
![Y-axis histogram idea](https://user-images.githubusercontent.com/36513418/101395435-8d7a1880-388f-11eb-9420-7907a2f33c52.png)

#### Which Component
slider-histogram

#### Example Use Case
Imagine you have several time-enabled objects and your x-axis of your time slider represents the date, and the two thumbs represent the minimum and maximum time currently in view.  Each x-increment on the slider would represent an increment "time-bucket", and the y-value would represent the number of objects with a date field that falls into that bucket.  The enhancement would be to provide a y axis with a few labels to provide context on what the magnitude of the y-value means to the user.  Optionally, the ability to hover over the graph and see the exact count of objects at that point on the graph would be fantastic

**Comment by macandcheese** [comment]
I think this is a valid use case.. although we are definitely getting into an “almost necessitates a separate graph/chart component that slider relies on” territory. 

I could see a couple small niceties like options for rounding, stepped / bracketed data, etc. being useful, both with a slider and as a standalone element to make those UI usages more consistent across apps.

More scoped discussion, we’d probably need to expose a “y-step” option to let users determine at what interval to show lines, if they want hover values as mentioned, etc. it might be reasonable to have “full height and width” graph lines as an option but this is kind of in wishlist territory and maybe out of immediate scope.

**Comment by paulcpederson** [comment]
@RSantosGIS  would this axis labeling need to support exponential values, or is this just purely a linear scale?

**Comment by RSantosGIS** [comment]
Purely linear.  Like I said, my overarching goal here is only to give the client that I'm building this custom widget for some kind of context so they can tell more easily what the histogram values mean.  If they can at least tell what value the bottom of the y-axis represents (the point array minimum), what the top represents (the point array maximum), and a few ticks in between, that that does the job without changing anything about how the histogram works or doing anything super complicated.

**Comment by macandcheese** [comment]
I think this is out of scope for the current component. cc @julio8a

**Comment by julio8a** [comment]
Yes, this is out of scope for this component and more related to charting. Closing, please reach out to me if there are questions on this one.
