### ISSUE TITLE
Storybook for calcite-shell-center-row

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/calcite-components#1378]
Hi,

Is there a storybook for **calcite-shell-center-row**?

I would like to show FeatureTable widget in a bottom panel (is this available?), any advises please.

**Comment by macandcheese** [comment]
@asangma is it possible to add an example of this with a container in there? Maybe to the "advanced" story?

**Comment by driskull** [comment]
@rangasatishkumar this story already uses center row. https://esri.github.io/calcite-components/?path=/story/app-components-shell--advanced

You can place anything inside the center row slot.

**Comment by driskull** [comment]
Let me know if this doesn't answer your question. :)
