### ISSUE TITLE
Bug: Dropdown on RTL page causes long horizontal scroll

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#1381]
### Summary
The Dropdown component introduces a long horizontal scroll bar when placed on a page where the `dir="rtl"` attribute is set on the root element.

<img width="1504" alt="Screen Shot 2020-12-08 at 1 56 07 PM" src="https://user-images.githubusercontent.com/421496/101530078-70147f80-395f-11eb-9d7b-594c5d281d92.png">

The `.calcite-dropdown-wrapper` element uses a `left: -999999px` style to position itself offscreen. In RTL layouts, this causes the horizontal scroll. One fix could be to replace this with a `right: -999999px` style when in an RTL layout.

### Actual Behavior
A long horizontal scrollbar is present on the viewport.

### Expected Behavior
No horizontal scrollbar is present.

### Reproduction Steps
1. Visit https://esri.github.io/calcite-components/?path=/story/components-dropdown--simple-rtl.
2. Use the browser's developer tools to find the `#storybook-preview-iframe` element.
3. Open the iframe and add the `dir="rtl"` attribute to the root node.
4. Notice the horizontal scrollbar appears. Some browsers may flash it, others may need the iframe focused before showing it.

### Relevant Info 
Observed in latest versions of Chrome, Firefox, and Safari on latest macOS.

**Comment by nwhittaker** [comment]
@driskull, we're seeing a regression with this fix when a dropdown trigger is aligned to the trailing/end edge of a scrollable container: https://github.com/ArcGIS/field-apps-web/issues/1336.

For a contrived example:

1. Visit https://esri.github.io/calcite-components/?path=/story/components-dropdown--simple.
2. If needed, give the `.calcite-dropdown-wrapper` element a `left: auto;` style to mimic the https://github.com/Esri/calcite-components/pull/1387 patch.
2. Give the `#root` element `width: 240px; height: 218px; text-align: right; overflow: scroll;` styles.

Before clicking the trigger, notice the #root element is horizontally scrollable. After clicking the trigger, the container is no longer horizontally scrollable.

Setting a `-999999px` `left`/`right` style on the `.calcite-dropdown-wrapper` element, depending on the `dir` value, does appear to be enough to fix the regression.

<img width="1284" alt="Screen Shot 2020-12-14 at 1 11 54 PM" src="https://user-images.githubusercontent.com/421496/102120133-16ed9580-3e10-11eb-9e66-c92fa2acaae8.png">

**Comment by driskull** [comment]
Thanks @nwhittaker. I'll take a look. I'll see if I can use something other than positioning it to the left or right.

**Comment by driskull** [comment]
@nwhittaker Installed a fix! Let me know if you're still seeing an issue.

**Comment by nwhittaker** [comment]
>@nwhittaker Installed a fix! Let me know if you're still seeing an issue.

Looking good in `1.0.0-next.62`, thanks
