### ISSUE TITLE
Bug: calcite-input returns console errors for text and number type

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1389]
### Summary

While using `calcite-input` type number/text I see these errors. (Map Viewer beta on production)

![image](https://user-images.githubusercontent.com/44481292/101600245-e2ad4b80-39af-11eb-869a-d16101aaf3dd.png)

![image](https://user-images.githubusercontent.com/44481292/101600275-efca3a80-39af-11eb-8ee3-bcb641b02f6a.png)

max is an optional prop, but the watcher assumes the value exists.

https://github.com/Esri/calcite-components/blob/873ee6c0225715bb1c1946a8f03e0532a2ed568a/src/components/calcite-input/calcite-input.tsx#L69-L76

If I add a random max value to all of them the error goes away, but this is not a good solution because I don't don't know what kind of data (and max value) layers contain.

### Reproduction Steps

1.

**Comment by driskull** [comment]
@AdelheidF I'll look into it. @macandcheese usually handles the `calcite-input` I think.

**Comment by jcfranco** [comment]
@AdelheidF Could you help verify this one?

**Comment by AdelheidF** [comment]
No longer seeing the issue on devext MVB.
