### ISSUE TITLE
Bug: Calcite Modal does not remove overflow-hidden class on HTML if it removed from the DOM.

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#1394]
### Summary

If a open `<calcite-modal>` is removed from the DOM without being closed the `overflow-hidden` class persists on the `<html>` element.

### Actual Behavior

The  `overflow-hidden`  class persists on the `<html>` element.

### Expected Behavior

Removing a `<calcite-modal>` from the DOM should clean up after itself by removing the `overflow-hidden` class.

### Reproduction Steps

1. Open https://codepen.io/patrickarlt/pen/eYddLMp?editors=0100
1. Notice you can scroll the page because of the really long div.
1. Open the modal
1. Click the remove buttom
1. You cannot scroll the page because `overflow-hidden` remains on the body.

### Relevant Info

This kind of cleanup behavior is probably needed across any component that modifies the DOM outside itself. I ran into this when doing somethign like this in React:

```jsx
{option ? <ModalThatTogglesOption /> : <OtherModalThatTogglesOption />}
```

`<ModalThatTogglesOption>` and `<OtherModalThatTogglesOption>`  both modify the value of `option` and close then selves but React is doing this:

1. `option=true` so React renders `<ModalThatTogglesOption />`
2. A user uses `<ModalThatTogglesOption />` to make `option=false`. This occurs in a function like:
   ```
   updateOptionTo(false); <-- React re-renders here
   closeModal(); <-- this doesn't get called because the modal no longer exists in React
   ```
3. Now `option=false` React starts to re-render because closing a modal is async it goes on the stack while React is re-rendering.
4. `option=false` so React renders  `<OtherModalThatTogglesOption>` and REMOVES `<ModalThatTogglesOption />` which makes it look like the modal closed (since it removes the open modal from the DOM) but since the modal didn't close properly the `overflow-hidden`  class persists on the `<html>` element.

**Comment by macandcheese** [comment]
Hm, yeah I'll look into trying to remove that class, this would still occur if used with `beforeClose` yeah? https://github.com/Esri/calcite-components/tree/master/src/components/calcite-modal#properties

Seems like this also prevents a modal from "animating out"... What does that experience look like for a user? A quick flash before another modal replaces it while animating in? Could the content of the modal / footer be swapped vs. replacing the entire thing?
