### ISSUE TITLE
Enhancement: Uneasy to get the selected option value from the calcite-select component on change

### ISSUE THREAD

**Issue by haoliangyu** [Esri/calcite-components#1401]
### Description

Currently, there is no easy way to get the selected option value from the `calcite-select` component on change. The component can emit a `calciteSelectChange` event but it is in the `CustomEvent<void>` type with NO data.

In order to get the selected value on change, I need to listen to the `calciteSelectChange` event and iterate its option children to find the one with a `selected` attribute. But this is hacky and touches the internal elements:

``` javascript
function handleChange (event) {
  // get a collection of child option elements
  const options = event.target.children;

  for (let i = 0; i < options.length; i++) {
    const option = options.item(i)
    // if the option has the "selected" attribute, return the option inner text
    if (option.hasAttribute('selected')) {
      const value = option.textContext;
      console.log('new value:', value);
    }
  }
}
```

### Acceptance Criteria 

There is an easy way to get the selected value on change. The expected way is to modify the change event to include the value, like `CustomEvent<string>`. It is the same pattern that many calcite components, like calcite-input, have

#### Which Component

calcite-select

#### Example Use Case

The change event handler should look like

``` javascript
function handleChange (event) {
   const value = event.detail;
   console.log('new value:', value);
}
```

**Comment by jcfranco** [comment]
Fixed by https://github.com/Esri/calcite-components/issues/1250 and will be available in the next beta release.
