### ISSUE TITLE
Bug: date picker's calendar size issue 

### ISSUE THREAD

**Issue by Rohtash2020** [Esri/calcite-components#1408]
### Summary
With date picker component, the calendar which pops up, sizing it's width same as the size of date picker input box width. Due to of which sometimes it appears to squeezed or stretched(image attached)

### Actual Behavior
Calendar width adjusted as per width of date picker input box

![Calendar](https://user-images.githubusercontent.com/64084089/102366525-c5473580-3fde-11eb-96fa-e20d9f9761cb.jpg)

### Expected Behavior
Calendar dimensions should should remain unchanged, as designed

**Comment by driskull** [comment]
I think this is fixed now that we use popper. @Rohtash2020 can you verify?

**Comment by julio8a** [comment]
verified.
