### ISSUE TITLE
Bug: Long modal header and action buttons cut off on Safari (Mobile)

### ISSUE THREAD

**Issue by cosbyr** [Esri/calcite-components#1412]
### Summary
- When a modal header is long it will leave the boundaries of the header div
- Buttons at the bottom of the modal are cut off

### Actual Behavior
![image](https://user-images.githubusercontent.com/11748268/102421698-e8132300-3fb9-11eb-8627-cd34467e288f.png)

### Expected Behavior
Chrome on Android mobile device shows the expected behavior:
![image](https://user-images.githubusercontent.com/11748268/102421955-8606ed80-3fba-11eb-8af5-6f38ac133565.png)

### Reproduction Steps

Open the following html content in safari on an iPhone
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script type="module" src="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.js"></script>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.css" />
</head>
<body>
    <calcite-modal active  scale="l" aria-labelledby="modal-title">
        <h3 slot="header" id="modal-title">Gas and Pipeline Data Management for ArcGIS Enterprise. Gas and Pipeline Data Management for ArcGIS Enterprise</h3>
        <div slot="content">The actual content of the modal</div>
        <calcite-button slot="back" color="light" appearance="outline" icon="chevron-left" width="full">
          Back
        </calcite-button>
        <calcite-button slot="secondary" width="full" appearance="outline"> Cancel </calcite-button>
        <calcite-button slot="primary" width="full"> Save </calcite-button>
    </calcite-modal>
</body>
</html>
```

### Relevant Info 
iPhone XS Max Safari 12

**Comment by bstifle** [comment]
@paulcpederson hi fren, do you have an eta on this?

**Comment by paulcpederson** [comment]
yeah, ETA: Jan 4, 2021, 2:49 PM PST

**Comment by julio8a** [comment]
@bstifle, Looks like this just needs verification

**Comment by bstifle** [comment]
@paulcpederson  thanks but can you do it sooner

**Comment by bstifle** [comment]
Verified

**Comment by paulcpederson** [comment]
![doc from back to the future saying "ready"](https://user-images.githubusercontent.com/1031758/106067488-9d55f200-60b3-11eb-8e97-da8476365628.gif)
