### ISSUE TITLE
Enhancement: Improve styling of calcite-select disabled state

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#1416]
### Description
When disabled, the calcite-select component continues to appear enabled and responds to the `:hover` state with cursor and background style changes. Any non-explicit style changes are inherited from the browser's built-in styling of disabled `<select>` elements.

### Acceptance Criteria 
When disabled, the calcite-select component is given a distinct appearance indicative of its state. Styling for other pseudo-classes (e.g. `:hover`) should also be considered.

### Relevant Info 
In Chrome, the border around the chevron icon is currently slightly darker in color when the component is disabled:
<img width="200" alt="Screen Shot 2020-12-17 at 5 49 54 PM" src="https://user-images.githubusercontent.com/421496/102554238-5fb48100-4092-11eb-9bba-e5f140099057.png">

#### Which Component
Calcite-select

#### Example Use Case
Confusing to the end-user if disabled calcite-select components do not maintain visual consistency with other disabled calcite components and form inputs.

**Comment by macandcheese** [comment]
@nwhittaker can you verify ? Thanks

**Comment by nwhittaker** [comment]
Looks good on latest macOS versions of Chrome, Firefox, and Safari -- thanks!
