### ISSUE TITLE
Enhancement: calcite-color - setting explicitely the output format

### ISSUE THREAD

**Issue by pemberdom** [Esri/calcite-components#1423]
### Description

The `calcite-color` doc says about the `value` property:

> The type will be preserved as the color is updated

Which can lead to deal with extra tests and conversions if ever the calcite-color is used in a context where the input color format can vary.

Also, if the first input color is `null` (when `allowEmpty` is `true`), the format is defaulted to RGB.

Ideally the `calcite-color` could be instructed to dispatch its selected value through always the same specific format (RGB / hex...=> new `outputFormat` property?)).

### Acceptance Criteria 

The `calcite-color` has a property allowing the user to set the ouput color format, independently from the input color format.
Independently from the input color format (and whether it's `null`), the output value carried by the `calciteColorChange` event is always formatted according to the defined output format.

#### Which Component

calcite-color

#### Example Use Case

```jsx
<calcite-color
  value="#123456"
  outputFormat="RGB"
  >
</calcite-color>
```

**Comment by jcfranco** [comment]
This is already supported via the `format` property (https://github.com/Esri/calcite-components/pull/1439).
