### ISSUE TITLE
Tooling: Shadow DOM Test Helper

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#1426]
## Summary 

A test helper for reducing boilerplate when testing components inside a shadowRoot.

## Measure of Success 

A reusable function in `commonTests` that can be used to test components in shadowRoot environments.

### Resources 

https://github.com/Esri/calcite-components/pull/1422#pullrequestreview-556536476

**Comment by julio8a** [comment]
Is this issue still valid?

**Comment by eriklharper** [comment]
Yep, I'd leave this open, as it will come in handy in multiple places.
