### ISSUE TITLE
Bug: [FAB] defaults to small scale instead of medium

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1427]
### Summary

Stems from https://github.com/Esri/calcite-components/issues/1167#issuecomment-733368518

via @macandcheese 

> It seems like FAB defaults to scale "s" if no scale is provided which seems a little weird as I think all other components default to "m"... and there looks to be a weird RTL styling thing on the demo with alignment (although I don't see the same thing with buttons in RTL so not sure where that is coming from)
> 
> ![Screen Shot 2020-11-24 at 4 27 30 PM](https://user-images.githubusercontent.com/4733155/100167014-e484f400-2e72-11eb-8d65-3fc9526efab4.png)

### Actual Behavior

FAB defaults to small scale when not provided.

### Expected Behavior

FAB defaults to medium scale when not provided.

### Reproduction Steps

1. Create FAB w/o `scale` attribute/prop.

**Comment by driskull** [comment]
Assigning to @asangma. Its just a simple change but we need his approval.

**Comment by macandcheese** [comment]
We could break the mentioned rtl bug into another issue if needed but seems simple enough to be addressed here as well.

**Comment by driskull** [comment]
Yeah I think the RTL is also a small styling issue probably best addressed by one of the designers.

**Comment by jcfranco** [comment]
Verified locally!
