### ISSUE TITLE
Question: Table component 

### ISSUE THREAD

**Issue by mateuspontesmoraes** [Esri/calcite-components#1430]
### Question
Hello, I didn't found the table component within the component list.
Could you help me?

[https://esri.github.io/calcite-components/?path=/story/overview-home--page](url)

**Comment by macandcheese** [comment]
Hi @mateuspontesmoraes - at this time we don’t have a table / datagrid component in the library. 

We hope to add one in the future but don’t have a timeline for this.

**Comment by mateuspontesmoraes** [comment]
Hi @macandcheese, thank you to answer.
