### ISSUE TITLE
Component: Radio Button

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#144]

**Comment by AdelheidF** [comment]
Any news on when we can expect this?

my design

<img src=https://user-images.githubusercontent.com/44481292/77128192-6da67a00-6a0c-11ea-933b-606c43c8ef68.png width=200/>

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/77209373-596d8600-6abb-11ea-997b-e411ae2861ec.png)

@AdelheidF this is the latest design
@julio8a how would you like to move forward?

**Comment by julio8a** [comment]
We've had the design for a while, we just need this built-out by a dev. Moving this back into the WIP phase 2. @Esri/calcite-components, anyone has some cycles to start this one?

**Comment by macandcheese** [comment]
We need to decide if we are going to continue to build components in this manner - some discussion was at the end of this issue: https://github.com/Esri/calcite-components/pull/391 - but we should make have that chat before we begin another component in this manner.

**Comment by julio8a** [comment]
We have a meeting scheduled for this Thur at 3 pm. We can discuss this then. I'll add you @AdelheidF

**Comment by AdelheidF** [comment]
I'm using the standard radio button right now and it works fine, just doesn't look so nice. It's not a showstopper for me. 

<img src=https://user-images.githubusercontent.com/44481292/77362061-8ca75380-6d0d-11ea-94f4-3e107e56d4de.png width=200/>

**Comment by macandcheese** [comment]
@AdelheidF - we will definitely be adding a Radio Button component! Currently, we just do some over the top stuff to support passed inputs in our other similar components and want to decide if we want to continue that :)

**Comment by AdelheidF** [comment]
Using Beta 26 with radio buttons now.
None of the sizes work for me, the text is either too big or too small. How can I modify the text size?

before:
<img src=https://user-images.githubusercontent.com/44481292/82486573-ee780580-9a91-11ea-902c-350d166cba74.png width=200/>

Beta 26 with scale=m
<img src=https://user-images.githubusercontent.com/44481292/82486221-61cd4780-9a91-11ea-8875-8a78eca79bd7.png width=200/>

Beta 26 with scale=s
<img src=https://user-images.githubusercontent.com/44481292/82486659-11a2b500-9a92-11ea-86da-79cc67c9a1ce.png width=200/>

Also the doc could use some more explanation for radio-button and radio-button-group and it needs to fill the missing pieces.

<img src=https://user-images.githubusercontent.com/44481292/82487579-65fa6480-9a93-11ea-8bc9-ed50611aadd3.png width=300/>

**Comment by eriklharper** [comment]
I'll defer to @bstifle with regards to the sizes.

That doc screenshot you included: where are you accessing that?  On the Notes tab in Storybook it shows the docs correctly https://esri.github.io/calcite-components/?path=/story/radio-button--light-theme
![image](https://user-images.githubusercontent.com/821864/82488552-ed94a300-9a94-11ea-9de4-32ad64799c39.png)

**Comment by AdelheidF** [comment]
https://github.com/Esri/calcite-components/tree/master/src/components/calcite-radio-button

**Comment by paulcpederson** [comment]
@eriklharper may just need to run a build so the `README` rebuilds and commit the result?

**Comment by eriklharper** [comment]
I think I just need to remove the `<>` from within the code blocks.  `name` is rendering fine on the readme and it doesn't have the angle brackets.

**Comment by AdelheidF** [comment]
A comment about the focus state. 
I guess it's related to this issue here: https://github.com/Esri/calcite-components/issues/555

Initially
<img src=https://user-images.githubusercontent.com/44481292/82495751-7107c180-9aa0-11ea-96b5-a16335b4c8a7.png width=200/>

After clicking on the first radio button. It becomes this huge blue icon in my panel (where everything else is mostly gray) which makes the radio button really important, but it shouldn't be.
<img src=https://user-images.githubusercontent.com/44481292/82495802-87158200-9aa0-11ea-8ea8-1660b5902846.png width=200/>

I guess it's expected with the overall focus width of 2px but that radio button really draws your attention to it.

cc @asangma

**Comment by eriklharper** [comment]
FWIW, the font sizes are standard `calcite-label` font sizes.  Are the rest of your form field labels using the `calcite-label` component?  If so, any of the three scales should look fine as long as all the form fields needing labels are consistently using the same scale on their calcite-labels.
