### ISSUE TITLE
Enhancement: showInput on calcite-tile-select refactoring

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1445]
### Summary

The `showInput` property has values of "left" | "right" | "none" but I think it should probably use `start/end` instead of left and right for RTL support.

It may also be a good time to do the following for it as well:

- reconsider property name
- Use interface for `"start" | "end" | "none"`

This would be a breaking change.

**Comment by macandcheese** [comment]
Are we ok with `inputDisplay` as the new name for this?

**Comment by driskull** [comment]
What about `inputPosition`? I'm ok with inputDisplay though.

**Comment by macandcheese** [comment]
-position does make sense (or -alignment) but since there's a "none" option that seems weird whereas with -display it's... slightly less weird? I don't feel super strongly 🤷‍♂️

**Comment by driskull** [comment]
I agree with those feelings. It's like it maybe should be split into two properties. Once to deal with disabling the feature and one to do with positioning. What do you think?

**Comment by macandcheese** [comment]
`showInput` (boolean) + 
`inputAlignment` as new prop.. then we could Extract start / end from the Alignment interface instead having to create a unique one for start / end / none

**Comment by eriklharper** [comment]
> showInput (boolean) +
inputAlignment as new prop.. then we could Extract start / end from the Alignment interface instead having to create a unique one for start / end / none

I like that idea, let's go with that!

**Comment by julio8a** [comment]
Great collaboration on this guys. What's the status of this? has the naming been updated?

**Comment by julio8a** [comment]
@macandcheese, is this is the issue you mentioned in our meeting that we can close?

Want to confirm.

**Comment by macandcheese** [comment]
Keep open until the linked pr is merged

**Comment by julio8a** [comment]
Linked PR was merged, can we close/?
