### ISSUE TITLE
CalciteButton exceeds its defined height

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#146]
![image](https://user-images.githubusercontent.com/1231455/65061399-b16dd900-d92e-11e9-87d1-3e422b0880e1.png)

The CalciteButton visually exceeds its defined height. I noticed the issue using the Popover component.

@julio8a not sure who to assign this to.

**Comment by macandcheese** [comment]
Is this causing issues?

That's just the interpreted height of the slotted text - the entire button is clickable and the shadow-root has the correctly rendered height:

 
![Screen Shot 2019-09-17 at 9 41 54 AM](https://user-images.githubusercontent.com/4733155/65061854-a10a2e00-d92f-11e9-99f1-e467921d22ca.png)

If it's a problem (maybe with dynamically setting container height based on button height?) I can take a look.

**Comment by driskull** [comment]
If you wanted to get the height of the button you would have to go into the shadow dom to get it which doesn't seem right.

**Comment by macandcheese** [comment]
Yeah roger that, will take a look.

**Comment by macandcheese** [comment]
Addressed in https://github.com/Esri/calcite-components/pull/147 :)

**Comment by driskull** [comment]
thanks @macandcheese !!
