### ISSUE TITLE
Bug: [checkbox] internal input can be styled externally

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1467]
### Summary

A specific enough style can override the checkbox's hidden input.

cc @AdelheidF 

### Actual Behavior

The internal hidden input is exposed to external styling. 

### Expected Behavior

Internals to remain encapsulated.

### Reproduction Steps

Open the following pen to see the issue in action: https://codepen.io/jcfranco-the-scripter/pen/poEmRMr?editors=1000

**Comment by bstifle** [comment]
@eriklharper do you have an eta on this?

**Comment by eriklharper** [comment]
@bstifle glad you asked!  Just put up a PR for it: #1467
