### ISSUE TITLE
Bug: calciteColorChange event does not emit when setting the format property to "rgb"

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1468]
### Summary
At next.76, trying to set the format prop of the color component to rgb to ensure it is in that format when the value is retrieved. When the format is set to "rgb", the calciteColorChange event does not emit and there is a warning in the console:

![image](https://user-images.githubusercontent.com/52869490/105553307-fb509700-5cb9-11eb-831a-9a0780ae61a5.png)

### Actual Behavior
Event does not emit when changing the color.
### Expected Behavior
Color component should work as usual but have the RGB format as its value I think.
### Reproduction Steps

Codepen: https://codepen.io/eborgen/pen/OJRmmPO?editors=1001

**Comment by jcfranco** [comment]
Installed! Note that the change event will not be emitted as it's considered the initial value and therefore unchanged.

@ethanbdev Could you help verify on @next (updating soon)?

**Comment by ethanbdev** [comment]
Looks great, thanks @jcfranco! 💯

**Comment by ethanbdev** [comment]
Hey @jcfranco, it looks like this one could be back? It seems to now emit an event, but the value is null instead of the color the picker shows. See:
https://codepen.io/eborgen/pen/LYRwjEm?editors=1001

**Comment by jcfranco** [comment]
Confirmed with beta.62. Can you open a new issue for this?

**Comment by ethanbdev** [comment]
> Confirmed with beta.62. Can you open a new issue for this?

https://github.com/Esri/calcite-components/issues/2853

Thank you!
