### ISSUE TITLE
Bug: Accordion should by default have 100% width

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1469]
### Summary
By default an accordion should take up the entire width of the parent container. Right now it's set to max-width: 100%, which means that if content within the accordion's open items is not being displayed, the longest piece of text will set the extent of the component. 

Setting the component to 100% width will make it more predictable when placing within containers that have flex settings on them. Currently you must set a workaround like so (in Storybook: https://github.com/Esri/calcite-components/blob/f0716bbc35cddd7a962d7f507c12186625e15690/.storybook/preview-head.html#L26) to achieve a "controlled" width as accordion items open or close.

### Reproduction Steps

1.

**Comment by julio8a** [comment]
Still valid?

**Comment by jcfranco** [comment]
@macandcheese Is this still applicable with the most recent changes?

**Comment by macandcheese** [comment]
@jcfranco nope - looks like https://github.com/Esri/calcite-components/pull/2669 resolved this. Closing 👍
