### ISSUE TITLE
Question: FAB inconsistencies / updates

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1470]
### Question
While building out component previews for the new docs sites, I found some oddities in the FAB button that I'd like to get updated:

It seems weird to me that FAB doesn't default to the same visual settings as button. A button defaults to blue / solid, whereas a FAB defaults to outline / light. 

I know we just fixed FAB so the default is scale M to match other components, so I propose updating the default color and appearance to match that of button to a similar end.

It's also strange to me (although slightly less so) that there is a default icon set at all (plus). Even the calcite-icon component doesn't have a default icon. I understand the intent there but it precludes the component from being used with just text and text-enabled (like the extended fab here: https://material.io/components/buttons-floating-action-button#interactive-demo with no leading-icon).

Thoughts @Esri/calcite-components

**Comment by paulcpederson** [comment]
I agree with both points. API/nomenclature should match button, IMO

**Comment by bstifle** [comment]
1% agree 99% agreed

**Comment by driskull** [comment]
> A button defaults to blue / solid, whereas a FAB defaults to outline / light.

IMO, I don't really see this as an issue. The FAB Is there to present the button in the way the FAB should have it so I would expect some inconsistencies here. If they are both the same then there may not be a need for the FAB at all.

**Comment by bstifle** [comment]
It's just for consistency in defaults. FAB is a unicorn right now. We dont believe in unicorns matt!!!

**Comment by driskull** [comment]
> It's just for consistency in defaults. FAB is a unicorn right now. We dont believe in unicorns matt!!!

🦄 THEY EXIST. :)

But honestly, if the FAB should be solid by default then that is okay. If they are consistent then there isn't a need for the FAB. The point of the FAB is to configure the button in the ideal state for a FAB.

**Comment by driskull** [comment]
The point of the FAB component is for users to not have to think about how to configure the button a specific way every time for a FAB. We want to promote consistency.

So by its design, it shouldn't be consistent with the button component.

**Comment by macandcheese** [comment]
I think that argument works for the “default to plus icon”, so that to me is.. more understandable .. but it does prevent it from being used with just text, right?

I still think a fab should be blue and solid by default as a more actionable appearing FAB that could still be overridden if apps want to make them light like the above MVB example (IMO)

**Comment by driskull** [comment]
> I still think a fab should be blue and solid by default 

I'll leave this up to the design gurus. If that's how we want it to appear by default, that change can be made.

**Comment by driskull** [comment]
I think we can close this issue and open a new issue if we need to change the defaults for the FAB.
