### ISSUE TITLE
Enhancement: CalciteButton cleanup

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1473]
### Description

CalciteButton applies a prop that doesn't exist to the host of the component.
https://github.com/Esri/calcite-components/blob/master/src/components/calcite-button/calcite-button.tsx#L141

It should probably apply a css class inside of the component instead if it needs to adjust styling.

Also, the getAttributes internal method seems to apply both attributes and properties. Some are dashed and some are camel cased. This seems like it should do either props or attributes.

https://github.com/Esri/calcite-components/blob/master/src/components/calcite-button/calcite-button.tsx#L210-L213

### Acceptance Criteria 

hasText is removed from host.

#### Which Component

CalciteButton

#### Example Use Case

N/A

**Comment by macandcheese** [comment]
Yeah let’s just make sure it works with both “icon-start” and “iconStart” placed in dom and doesn’t place either on the child. Maybe both need to be there in the “don’t spread” list.

**Comment by driskull** [comment]
Seems its fixed now. Closing :)
