### ISSUE TITLE
Bug: Color component slider does not work with some initial color values

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1474]
### Summary
It looks like when an initial color value is set that has both the canvas and slider color pickers all the way to the left, the slider does not activate with clicking or dragging. Tested a few different default values that this occurs with.
### Actual Behavior
If a value is set on the color component that pushes the slider and canvas pickers to the left, the slider will not work
![C54453E8-51C9-47FB-97ED-97BD5DCCF5B6](https://user-images.githubusercontent.com/52869490/105885507-12470000-5fbe-11eb-82de-a95f89c0264b.GIF)
### Expected Behavior
The color slider should work with an initial value of black (#00000) or similar colors set.
### Reproduction Steps

https://codepen.io/eborgen/pen/LYRwjEm?editors=1000

### Relevant Info 
Does not appear to be browser specific.

**Comment by jcfranco** [comment]
Installed!

@ethanbdev Could you help verify w/ @next once it updates?

**Comment by ethanbdev** [comment]
> Installed!
> 
> @ethanbdev Could you help verify w/ @next once it updates?

👍 Thank you!
