### ISSUE TITLE
Docs: Simple modal documentation doesn't scroll if page loaded in Canvas view

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#1476]
### Description 

Go to https://esri.github.io/calcite-components/?path=/docs/components-modal--simple and select the Canvas tab if not already selected. Refresh the page, and then select the Docs tab; the page is not scrollable (the iframe's html is set to class "override-hidden"). If you refresh the page while the Docs tab is active, however, the page is scrollable.

### Which Component

Simple modal

### Resources 

Chrome 88, Firefox 84 & 85

**Comment by jcfranco** [comment]
Verified!
