### ISSUE TITLE
Bug: calcite-pick-list - should not focus or fire event (space bar) on disabled pick-list-item

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1478]
### Summary
(1) When tabbing through a pick-list it sets the focus on the title and then the end-action of an active pick-list-item, this is fine. If a pick-list-item is disabled it still sets the focus on the title. It should not do this, correct? It skips over the end-action of the disabled pick-list-item.

![image](https://user-images.githubusercontent.com/44481292/105921906-6b2e8c80-5fee-11eb-8ed9-5a29503371e9.png)

### Reproduction Steps

1.

**Comment by AdelheidF** [comment]
Actually it's more than just the focus. If I click with the mouse on a disabled pick-list-item nothing happens, this is good. If I hit the space bar on a disabled pick-list-item it gets selected. It calls the "calciteListChange" event handler.

**Comment by jcfranco** [comment]
Fixed via #2655.

**Comment by AdelheidF** [comment]
Looks good, I can no longer focus the disabled list items. Tested with 1.0.0-next.415
