### ISSUE TITLE
Bug: certain `dependencies` are listed as `devDependencies` 

### ISSUE THREAD

**Issue by subgan82** [Esri/calcite-components#1479]
### Summary

When Calcite-Components is used in an application , there are couple of dependencies listed as `devDependencies` throwing runtime errors as follows

### Actual Behavior

Throws runtime errors for react, angualar, ember based apps using calcite-components
/node_modules/arcgis-charts-components/dist/esm/calcite-modal.entry.js
Cannot find module: '@a11y/focus-trap/focusable'. Make sure this package is installed.

### Expected Behavior

The App works without doing [these](https://devtopia.esri.com/WebGIS/arcgis-charts/blob/ganesh/update-samples-latest/samples/arcgis-charts-sample-react/package.json#L13-L14) workarounds as shown [here](https://devtopia.esri.com/WebGIS/arcgis-charts/blob/ganesh/update-samples-latest/samples/arcgis-charts-sample-react/package.json#L21-L23)

### Reproduction Steps

1. Download this app https://devtopia.esri.com/WebGIS/arcgis-charts/tree/ganesh/update-samples-latest/samples/arcgis-charts-sample-react 
2. remove these lines 
     - https://devtopia.esri.com/WebGIS/arcgis-charts/blob/ganesh/update-samples-latest/samples/arcgis-charts-sample-react/package.json#L13-L14
     - https://devtopia.esri.com/WebGIS/arcgis-charts/blob/ganesh/update-samples-latest/samples/arcgis-charts-sample-react/package.json#L21-L23
 3. do `yarn`, `yarn start` the runtime errors can be seen

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
I missed one dependency. Fix coming up...

**Comment by jcfranco** [comment]
@subgan82 Can you help verify this one? Thanks! 🙇‍♂️

**Comment by subgan82** [comment]
Thanks @jcfranco looks good will verify in the sample app and confirm.

**Comment by subgan82** [comment]
tested using 1.0.0-next.83. this issue is resolved. No additional dependencies are needed.

![2021-02-11_11-33-17](https://user-images.githubusercontent.com/1017712/107674815-fe0d2f00-6c5c-11eb-9c9f-78f4c9850645.png)

**Comment by jcfranco** [comment]
Thanks! Closing as verified.
