### ISSUE TITLE
calcite-button label not aligned

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#148]
In the image below all 3 rows have a calcite-button in the center with the same width.
The button labels do not align. It would be good to have the text centered inside the calcite-button.

<img src=https://user-images.githubusercontent.com/44481292/65099791-8f9b4300-d97c-11e9-86af-71133751ec05.png width=300/>

![image](https://user-images.githubusercontent.com/44481292/65100676-fc164200-d97c-11e9-97a0-5dd307f21201.png)

**Comment by macandcheese** [comment]
Hi @AdelheidF - you can try using `width="full"` to set the width to 100%, although without knowing the exact structure of the entire row it may not work out of the box (it's still `inline-block` so, you may need to use flexbox on the surrounding and containing elements). Does the button include the "grab handle" or is that a separately clickable areas with different functionality?

**Comment by AdelheidF** [comment]
`width=full` solved it. Thanks.
