### ISSUE TITLE
Bug: Date range unexpectedly calls calciteDateRangeChange

### ISSUE THREAD

**Issue by codylawson** [Esri/calcite-components#1484]
### Summary
In some cases a controlled `calcite-date`, configured with `range`, will call `calciteDateRangeChange` when the `start` and `end` properties are changed via another control in the UI. 

### Actual Behavior
In Vue if you store a `start` and `end` date as a data and pass these values to the `calcite-date` component, changes to the state from any other component on the UI will cause the calcite-date component to call `calciteDateRangeChange`.

Another issue I'm seeing is that the `startAsDate` and `endAsDate` properties don't seem to be working, the component just shows the placeholder text.

### Expected Behavior
`calciteDateRangeChange` should only be called if the user selects values from the component or calendar dropdown.

### Reproduction Steps
Created a repro case here:
https://github.com/codylawson/calcite-components-examples/tree/vue-date-test/vue

1. Select "Last 2 hours"
  a. Console only shows one update to state called from `setPreset`
  b. `calcite-date` component represents the dates properly
2. Select "Last December"
  a. Console shows two updates to state `setPreset` and `setFilterDate` (called from `calciteDateRangeChange`)
  b. `calcite-date` shows incorrect date values

### Relevant Info 
Example is in Vue, haven't tested in React or other libraries

**Comment by codylawson** [comment]
@paulcpederson

**Comment by paulcpederson** [comment]
Have a pr open that I _think_ will fix this.
