### ISSUE TITLE
Enhancement: Add ability to set "any" on the step property of calcite-input

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1485]
### Description
Currently, the step property can only be set to a number. The native HTML input has an option for "any" to be set. This option would leave the ability to use the arrows to increment by 1 but remove the step being considered during validation, removing tooltips like this:
![image](https://user-images.githubusercontent.com/52869490/106213892-86320580-6182-11eb-86e6-764fdc4412fa.png)

### Acceptance Criteria 
Can set the step property to "any" as well as a number without changing any other behavior.
### Relevant Info 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#htmlattrdefstep
#### Which Component
calcite-input
#### Example Use Case
There is a minimum/max value calculated that the use can also change. The calculated value cannot be rounded to match the `step` precision as this would be inaccurate. Setting to "any" removes this extra validation that is not needed.

**Comment by eriklharper** [comment]
Looks like this issue has been resolved.  Will go ahead and close it.
