### ISSUE TITLE
Research: Bookmarklet that highlights components on a webpage

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#1490]
### Background 
Create a bookmarklet to detect where components are being used on a page. This can help us identify what components are being used in different apps to understand adoption and how many components are being used. 

Here's an example bookmarklet I put together that highlights anchor tags. I couldn't figure out how to do components since they use shadow dom. 
```
javascript: (function () {    var a = document.createElement('style'),        b;    document.head.appendChild(a);    b = a.sheet;    b.insertRule("a{background: rgba(255, 0, 0, .5) !important;", 0);})()
```

### Desired Outcome 

JS code for a bookmarklet that anyone can add to their bookmark bar to highlight the calcite-components on a webpage. 

How to create bookmarklet: https://gist.github.com/caseywatts/c0cec1f89ccdb8b469b1

**Comment by caripizza** [comment]
I gave Julio the bookmarklet code I came up with; it worked somewhat but could only find calcite-components in light DOM, wasn't able to pierce shadow DOM to find all the other components. I'm not sure this is something that can be prioritized at this time so I'm closing for now.
