### ISSUE TITLE
Enhancement: calcite-select value should be captured in FormData

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#1496]
### Description

It would make calcite components much easier to work with if their value could be captured with `FormData` without extra steps.

### Acceptance Criteria 

`FormData` should contain `<calcite-select>` value if `<calcite-select>` has the `name` attribute and its parent `<form>` is passed to `FormData`.

https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData

### Relevant Info 

This would improve form data handling by not needing a special case for handling `<calcite-select>` values.

#### Which Component

`<calcite-select>`

#### Example Use Case

https://codepen.io/gpbmike/pen/dypLKLm

```html
<form>
  <calcite-select name="fish-taco">
    <calcite-option selected>fish</calcite-option>
    <calcite-option>turtle</calcite-option>
  </calcite-select>

  <button>Submit!</button>
</form>
```

```js
form.addEventListener("submit", (event) => {
  event.preventDefault();
  const data = new FormData(event.target);
  
  // data should include select value!
});
```

**Comment by jcfranco** [comment]
This is already supported via #2570. 🎉
