### ISSUE TITLE
Bug: Slider value should move on MouseDown instead of MouseUp

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1497]
### Summary

Bug: Slider value should move on MouseDown instead of MouseUp

### Actual Behavior

Slider value changes on mouse up. 🐁 

### Expected Behavior

Slider value changes on mouse down. 🐭 

### Reproduction Steps

1. View  a calcite-slider
2. Click on a spot on the range
3. Notice it won't change if you press and hold on a location.
4. The native input slider will change immediately.

**Comment by driskull** [comment]
Also, if I press and drag and then unpress outside of the slider the mouse still moves the slider

![Uploading Feb-01-2021 11-06-33.gif…]()

**Comment by driskull** [comment]
Another nice improvement would be to multiply the step value if the user is holding the shift key while using arrow keys.

**Comment by driskull** [comment]
@eriklharper do you think you can address this one?

**Comment by eriklharper** [comment]
My pleasure!
