### ISSUE TITLE
Question: Why does switch have both switched and value

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1498]
### Question

Question: Why does switch have both switched and value?

Shouldn't it just have one source of truth for whether or not the switch is toggled in the on state?

**Comment by macandcheese** [comment]
Not sure on this, I think @eriklharper did that one?

**Comment by driskull** [comment]
Never mind, It is to support native form submission

**Comment by eriklharper** [comment]
> Never mind, It is to support native form submission

Correct.

`switched` communicates whether the switch is on or off (just like `checked`). 
`value` is just a label that overrides the default "on" text that is reported to the form when the switch is turned on.
