### ISSUE TITLE
Bug: Unintentional padding in the calcite-shell footer slot

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#1502]
There is padding being set for the calcite-shell footer slot that I spoke to Alan about and it should not be there, can you pls remove it?

Here is the code

https://github.com/Esri/calcite-components/blob/dd10e9c2e2035715b1b72b87f90c6b86ef7f56fd/src/components/calcite-shell/calcite-shell.scss#L70

### Reproduction Steps

1.

**Comment by kevindoshier** [comment]
PR here:
https://github.com/Esri/calcite-components/pull/1503

**Comment by driskull** [comment]
Needs verification
