### ISSUE TITLE
Enhancement: Make option for icon-only buttons responsive to container width

### ISSUE THREAD

**Issue by mitc7862** [Esri/calcite-components#1506]
### Description
I was able to make a grid of action buttons that fill the width of a panel, but the icon's doesn't appear centered because the calcite icon button width is restricted. 

What we want it to look like:
![image](https://user-images.githubusercontent.com/12564905/106818060-9d626e80-662c-11eb-9e09-01dd4aa47fea.png)

As close as we could get:
![image](https://user-images.githubusercontent.com/12564905/106817890-5d02f080-662c-11eb-9e7a-e10ff0eed519.png)

### Acceptance Criteria 

- [ ] Icon-only buttons no longer restrict max width.

#### Which Component

- Calcite Icon button
- Calcite Action

#### Example Use Case

See screenshot above.

**Comment by macandcheese** [comment]
I think restricting to a square (or a rectangle when icon-start and icon-end are populated), should still be available somehow.

**Comment by mitc7862** [comment]
Agree, I would suggest that still be the default behavior… but I think all components should have a responsive state for varying-width containers.

**Comment by asangma** [comment]
I think you could use Action as a starting place.

That being said, I think this could be handled by using a layout attribute or some layout attributes.

If we wanted to start small to get a feel for it, we could add a layout attribute to ActionGroup to help accomplish that design. I have a couple other designs that would benefit from that.

Also, Action already has a `text-enabled` attribute that can be set to `false` for the icon only option.

**Comment by asangma** [comment]
Also, this would allow users to have an ActionPad with a grid layout.

**Comment by asangma** [comment]
Looks like Action might also need a layout property.

**Comment by asangma** [comment]
@mitc7862 Do you mind if I rename this and update the first comment to be more about making layout options specific to the ActionGroup (with a note about this having the potential of becoming a broader pattern)?

**Comment by macandcheese** [comment]
I think a regular button still needs to have this option, since it’s basically styling users might want to just update a prop on a button. 

Not that it would preclude action bar from also having a layout like “grid” in addition to horizontal or vertical that could be used like this.

**Comment by asangma** [comment]
@macandcheese Seems like the Button should be a bit more prescriptive considering it's usage, but perhaps I'm missing something. Let's connect on this.

**Comment by asangma** [comment]
I'll make a new issue specific to Action and ActionGroup so if we wanna do something similar in Button, we can do that too.

**Comment by AdelheidF** [comment]
@dhrumil83 verified this.

**Comment by macandcheese** [comment]
Valid
