### ISSUE TITLE
Bug: calcite-input form reset behavior doesn't match native input

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#1507]
### Summary

When you call reset on a form containing a calcite-input, it clears the value regardless of what the initial value was.

### Actual Behavior

I've created a codepen where you can see the reset behavior: https://codepen.io/noahmulfinger/pen/GRNpBgb. Click the Reset button and the calcite-input will go blank, but the native input will not

### Expected Behavior

Behavior should match the native input.

### Reproduction Steps

1. Open codepen
2. Add text to both inputs
3. Hit the Reset button
4. The native input will still be "one", but the calcite input will be "".

### Relevant Info 
Tested on Chrome 88 and Firefox 87 with macOS 10.15.7

**Comment by driskull** [comment]
@noahmulfinger can you verify this fix?

**Comment by jcfranco** [comment]
Verified using the description's test case.
