### ISSUE TITLE
Component: Button - width="full" seems like its "half" now

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#151]
We use calcite-button, and set width to half, but now button text is wrapping, it seems like the half width became quarter

**Comment by kevindoshier** [comment]
![image](https://user-images.githubusercontent.com/11093161/65265331-8b2e7180-dac5-11e9-8707-c354dc7d42f7.png)

**Comment by macandcheese** [comment]
Hey @kevindoshier - thanks for the report. do you have a link to see a repro or a code snippet? It shouldn't be wrapping like that in isolation. We do have a couple of updates to buttons in the latest (unreleased) beta version, I'll see about cutting a new release.

**Comment by kevindoshier** [comment]
Hey, sorry I meant that when we set it to half it looks really small, somethign changed, you can see it here

https://devext.arcgis.com/apps/mapviewer/index.html

**Comment by macandcheese** [comment]
@kevindoshier Weird if you are pinned to a prior release it could have changed! This was fixed independently in a recent PR https://github.com/Esri/calcite-components/pull/150/files - it should go out in next release. Let's see if that resolves it when that release gets cut :)

**Comment by macandcheese** [comment]
@kevindoshier can you try pinning to the new release and see if that fixes it? Still worrisome that an old pinned release could change like that?

**Comment by kevindoshier** [comment]
@macandcheese - i pinned beta10 and it looks fine there, not sure why we saw this for that one time, thanks for your help
