### ISSUE TITLE
Enhancement: Deprecate CalciteAction and achieve feature parity with CalciteButton

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1511]
### Description

Deprecate CalciteAction and achieve feature parity with CalciteButton

### Acceptance Criteria 

- CalciteButton should be able to disable text without having to remove the text
- Indicator support
- Active support (highlighted) // would this be appearance on button?
- All components that expect a CalciteAction can use a CalciteButton instead
- Slot names may change from 'action'(s) to 'button'(s) on components throughout the project.
- compact mode? @asangma would we need this?

#### Which Component

- CalciteAction
- All

**Comment by driskull** [comment]
cc @jcfranco @asangma @paulcpederson @macandcheese

**Comment by driskull** [comment]
Let me know if this is something we would want to do for V1.

**Comment by julio8a** [comment]
If yes, please add to the 1.0 project.

**Comment by driskull** [comment]
closing: decided to keep calcite-action
