### ISSUE TITLE
Enhancement: Add layout options for Action and ActionGroup

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1514]
### Description
re: #1506

Allow Actions to be displayed in a grid.
![image](https://user-images.githubusercontent.com/12564905/106818060-9d626e80-662c-11eb-9e09-01dd4aa47fea.png)

### Acceptance Criteria 
* works with text-enabled on/off
* works inside a panel
* works inside ActionPad
* probs doesn't need to work with ActionBar
* pattern could be generalized and used more broadly
* doesn't break stuff

#### Which Component
* Action
* ActionGroup

#### Example Use Case
Sketching on map.

cc @mitc7862

**Comment by macandcheese** [comment]
@asangma Action Group now has a layout property - can this be closed?

**Comment by macandcheese** [comment]
@asangma can you confirm if this is still needed?

**Comment by benelan** [comment]
Closing based on ☝️ (Action Group)
