### ISSUE TITLE
Add support for resize style on inputs of type textarea

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#1528]
### Description
The ability to fine-tune a `<textarea>` element's resize behavior is controlled via the `resize` style[1]. When dealing with a `<calcite-input type="textarea">` element, there's currently no way to set this style on the underlying `<textarea>` element.

### Acceptance Criteria 
An interface is provided at the `calcite-input` level to set the `<textarea>` element's `resize` style.

#### Which Component
`<calcite-input>` elements of type `"textarea"`.

#### Example Use Case
Depending on the design or data constraints, it may be necessary to limit the user's ability to resize a `<textarea>` element in both directions, or at all. E.g. the element appears in a modal, or has a `maxlength`.

---
[1] https://esri.github.io/calcite-components/?path=/story/components-input--textarea

**Comment by macandcheese** [comment]
As a note, I think we want to break input type text area into its own calcite-textarea component, but we haven’t gotten around to that quite yet.

**Comment by julio8a** [comment]
Added as a criteria in description for new component issue #863

closing this one.
