### ISSUE TITLE
Add styling for popover

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#153]
Add shadow, background, perhaps invocation animations based on directionality.

**Comment by asangma** [comment]
@macandcheese Would these be props?

**Comment by macandcheese** [comment]
I would imagine it just providing default styling on the popover component - vs. just providing a functional popover. I'd imagine "doesAnimate" could be a prop, perhaps for animation? It could also just default to the same easing styles we use for Modals, Dropdowns, etc.

**Comment by asangma** [comment]
![cool](http://giphygifs.s3.amazonaws.com/media/HaC3m9r4JFjPi/giphy.gif)

**Comment by macandcheese** [comment]
Closing this, addressed in other issues.
