### ISSUE TITLE
Docs: Toggling `input-message-active` appears to do nothing

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#1532]
### Description 
On the [With Label](https://esri.github.io/calcite-components/?path=/story/components-input--with-label), [With Slotted Action](https://esri.github.io/calcite-components/?path=/story/components-input--with-slotted-action), [Textarea](https://esri.github.io/calcite-components/?path=/story/components-input--textarea), and [Simple - Dark mode](https://esri.github.io/calcite-components/?path=/story/components-input--simple-dark-mode) pages, toggling the `input-message-active` checkbox doesn't appear to do anything.

My inferred expectation is that it would toggle the appearance of the assoc. `calcite-input-message` component.

### Which Component
`calcite-input`

**Comment by macandcheese** [comment]
Storybook issue, I’ll get this sorted..

**Comment by macandcheese** [comment]
@nwhittaker closing in favor of : https://github.com/Esri/calcite-components/issues/2007 - there seems to be a bug in the actual input component floating variant, it does appear in Storybook but it's not anchored to the component.
