### ISSUE TITLE
Enhancement: ShellPanel add header slot

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1540]
### Description
Add header slot for ShellPanel.
This will add a container above the main content container (which receives default slot content).

cc @driskull @kevindoshier 

#### Which Component
ShellPanel

**Comment by asangma** [comment]
@kevindoshier Mind giving this a verify?

**Comment by kevindoshier** [comment]
I cant I dont have access here to do that

**Comment by asangma** [comment]
@kevindoshier No worries.

I'll close this having verified it on your build. :)
