### ISSUE TITLE
Enhancement: Shell. Add prop for "overlay content" (name TBD) and update default content to be a column between ShellPanels

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1541]
### Description
Currently, default slot content is placed behind any content in ShellPanels.
Update Shell to treat default content as a column that fits between ShellPanel content.

Default for this prop will be false.
Behavior like for the MVB will need to set this to true. cc @kevindoshier 

#### Which Component
Shell & ShellPanel.
Maybe also CenterRow.

**Comment by driskull** [comment]
Installed.
