### ISSUE TITLE
Bug: calcite-block - missing 'closed' state sign

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1542]
### Summary

People mistake a block header for a popover title and never click on it. Could we add a down caret or something back in?

<img src=https://user-images.githubusercontent.com/44481292/107702288-e2ab1f80-6c6e-11eb-9a15-fcb7eacbed8f.png width=300/>

### Reproduction Steps

1.

**Comment by pspraveenkr** [comment]
> People mistake a block header for a popover title and never click on it

I'm one of those people

**Comment by AdelheidF** [comment]
John Nelson ran into it as well: https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/2981

**Comment by julio8a** [comment]
ready to verify

**Comment by jcfranco** [comment]
The latest next should have it (it was added in `1.0.0-next.186`).
