### ISSUE TITLE
Bug: Calendar component's month steppers do the opposite of expected

### ISSUE THREAD

**Issue by joshtaylor0404** [Esri/calcite-components#1546]
### Summary
The month steppers on calendar component do the opposite of what is expected.

### Actual Behavior
When clicking the right stepper, the previous month is displayed. When clicking left toggle, the next month is displayed.

### Expected Behavior
When clicking the right stepper, the next month should be displayed. When clicking the left stepper, the previous month should be displayed.

### Reproduction Steps
See above.

### Relevant Info 

CC @paulcpederson

**Comment by paulcpederson** [comment]
@joshtaylor0404 This should be fixed in beta.50 , feel free to reopen if it's still not working.
