### ISSUE TITLE
Enhancement: New styling for filterEnabled prop on Pick List/Value List

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#1549]
New style update for `filterEnabled` prop in order to differentiate the element more from the items beneath it.

Reports of users missing the filter altogether since it was styled too similarly.

Here is the current vs proposed design:

![image](https://user-images.githubusercontent.com/14083530/107825221-5d943900-6d48-11eb-884d-90628b39353b.png)

**Comment by bstifle** [comment]
@asangma  for 👀

**Comment by bstifle** [comment]
ok after talking with @macandcheese it probably is better to just use calcite-input

![image](https://user-images.githubusercontent.com/14083530/107826942-6df9e300-6d4b-11eb-9693-dc1398a13f15.png)

**Comment by julio8a** [comment]
Still valid?

**Comment by bstifle** [comment]
Yes, keep open, needs development

**Comment by julio8a** [comment]
This is needed for accessibility on the input. The underline doesn't meet A11y requirements

**Comment by caripizza** [comment]
> This is needed for accessibility on the input. The underline doesn't meet A11y requirements

@julio8a what does this mean exactly? Can you clarify?

**Comment by julio8a** [comment]
It has to do with the tappable appearance, example:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/6144462/134038257-e41e3454-f181-4191-89ed-546af9c8ffd3.png">

@arjavbadjatiya had brought this up before. Anything to add @arjavbadjatiya for accessibility other than the tappable appearance?

**Comment by arjavbadjatiya** [comment]
@julio8a Yes, the main thing reiterated by Level Access as well was the ability to understand the interactive area for any input. The minimal style is a concern for someone with vision issues that uses a magnifying tool to interact with a page. They would either have trouble recognizing a decorative line vs input or knowing where to click/tap to get started.

**Comment by benelan** [comment]
verified in storybook
https://esri.github.io/calcite-components/?path=/story/components-pick-list--basic
