### ISSUE TITLE
Enhancement: Remove resize animation from calcite-shell-center-row

### ISSUE THREAD

**Issue by nel11211** [Esri/calcite-components#1554]
### Description
There have been issues with the center-row resize animation on the ArcGIS Charts side causing scrollbar flashing. [Here is the issue](https://devtopia.esri.com/WebGIS/arcgis-charts/issues/2052) in charts repo. As per discussion with @asangma, the recommended solution at this time is to remove the resize animation on the center-row.
### Acceptance Criteria 
Center-row resize animation removed.
### Relevant Info 
Charts issue: [2052](https://devtopia.esri.com/WebGIS/arcgis-charts/issues/2052)
Previously proposed solution: #1215
#### Which Component
[calcite-shell-center-row](https://github.com/Esri/calcite-components/tree/master/src/components/calcite-shell-center-row)
#### Example Use Case
See [charts issue 2052](https://devtopia.esri.com/WebGIS/arcgis-charts/issues/2052)

**Comment by driskull** [comment]
Maybe a better option to just disable the scrolling on the center row via a prop.

**Comment by asangma** [comment]
@driskull I had considered that, but thought it might be better to simplify.

**Comment by asangma** [comment]
@nel11211 Would you mind verifying this? If you don't have perms to do so, leave a comment, and I'll hit the button.

**Comment by nel11211** [comment]
This change seems to improve the "flickery" issue [described here](https://devtopia.esri.com/WebGIS/arcgis-charts/issues/2385), and moderately improves the scrollbar flashing, but does not completely resolve it. Looking into a fix that @asangma suggested for that on the charts side Charts via AmCharts styles. 

It would probably be fine to keep this change. As mentioned, it improves the visual quality of chart resizing, especially for charts with many data points. But if you would prefer to revert it since it does not totally resolve the initial concern, that's fine as well.

**Comment by nel11211** [comment]
Closing
