### ISSUE TITLE
Bug: calcite-input-date-picker ignores width:100%

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1555]
### Summary
This started with beta.49 when switching from `calcite-date` to `calcite-input-date-picker`.

<img src=https://user-images.githubusercontent.com/44481292/108103691-24591300-703f-11eb-8bdd-1b0410b68874.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/108109125-58840200-7046-11eb-8687-36c73854ae30.png width=300/>

It no longer reacts to my `width:100%` setting.

It seems the max-width setting messes it up
<img src=https://user-images.githubusercontent.com/44481292/108103505-e360fe80-703e-11eb-9e73-895d5f13c383.png width=150/>

### Reproduction Steps

1.

**Comment by paulcpederson** [comment]
I don't see this happening anymore.

**Comment by AdelheidF** [comment]
yes, this is fixed. Actually this is a (partial) duplicate of https://github.com/Esri/calcite-components/issues/1689.
