### ISSUE TITLE
Bug: calcite-input-date-picker switches to 1/1/1000 when trying to edit date via input box

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1556]
### Summary
(1) I'm trying to type in a new date into the input box and this is what I see in the calendar while typing: January 1000...
<img src=https://user-images.githubusercontent.com/44481292/108105122-10aeac00-7041-11eb-90c5-3f71d29a1b11.png width=200/>

(2) If I start with a valid date 7/7/2017 and just remove the last '7', the date in the input box switches to 1/1/1000.
<img src=https://user-images.githubusercontent.com/44481292/108105325-55d2de00-7041-11eb-9e17-9400726ec9db.png width=200/>

(3) If I remove the date string inside the input box and then try and type 7/7/2017, it will jump to '1/1/1000' once I reach the '2' for the year. It only works if I paste the whole string of '7/7/2017' into the input box. Typing doesn't work.

It could either keep the old date in the calendar while I type or it could disable the calendar. But switching to 1/1/1000 is weird.

This happens with beta.48 and beta.49.

### Reproduction Steps

1.

**Comment by paulcpederson** [comment]
Related to https://github.com/Esri/calcite-components/issues/905

**Comment by paulcpederson** [comment]
I don't think this bug repros any more either.

**Comment by AdelheidF** [comment]
No, still the same.

https://devext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0

click layer name to select it, click on Filter on the tools at the right, add expression, change field to 'Date of crash'. Now type into the date input field, e.g. remove the 7 in 2017 to type in a 6.

**Comment by AdelheidF** [comment]
The onCalciteDatePickerChange event fires with this. I guess this is the date in the input box at that time. But since I'm in the middle of typing, maybe it should wait until I take a small break from typing?
![image](https://user-images.githubusercontent.com/44481292/114227957-8e4cb500-992a-11eb-8c91-c56faa23cf5a.png)

**Comment by AdelheidF** [comment]
The onCalciteDatePickerChange event fires with this. I guess this is the date in the input box at that time. But since I'm in the middle of typing, maybe it should wait until I take a small break from typing?

![image](https://user-images.githubusercontent.com/44481292/114227957-8e4cb500-992a-11eb-8c91-c56faa23cf5a.png)

It seems to round that date to 1/1/1000 because that is my min prop. If I remove min and max it's much better.

I guess it's user error. Sorry!
