### ISSUE TITLE
Bug: calcite-input-date-picker editing year in calendar has no effect in input box

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1557]
### Summary
When I edit the year inside the calendar header from e.g. 2021 to 2018 nothing happens inside the input box.

![image](https://user-images.githubusercontent.com/44481292/108108962-2c688100-7046-11eb-9265-c05d864981c5.png)

This worked fine with beta.48. It now longer works with beta.50.

### Reproduction Steps

1.

**Comment by paulcpederson** [comment]
I think this is maybe working as intended. When you edit the year, you're not selecting a new day, you're just moving the calendar. So I've selected at date in 2018, if I type in 2020 and hit enter, the calendar is showing 2020, but I haven't selected a new day yet, if that makes sense.

/cc @bstifle for confirmation that this is the intended interaction model.

**Comment by AdelheidF** [comment]
> but I haven't selected a new day yet

Then why does it still show the blue dot?

**Comment by paulcpederson** [comment]
Let me look at this a bit more.

**Comment by paulcpederson** [comment]
It does not seem to show the blue dot at least on the current storybook: https://esri.github.io/calcite-components/?path=/story/components-controls-inputdatepicker--simple 

1. click to open
2. tab to year
3. hit up arrow to increase year
4. date is gray not blue

I _think_ it's meant to work like this (ie changing the active date but not the selected date).

**Comment by AdelheidF** [comment]
> I think it's meant to work like this

OK, I'll close this issue. We can come back to it if other people report it.

I can still reproduce it with the storybook.

click to open calendar
click on year number and increase number by one via typing
date stays blue 
if I close and re-open the calendar I still see the same thing

<img src=https://user-images.githubusercontent.com/44481292/115306652-01b9a800-a11d-11eb-9121-ece0a7ca87e1.png width=300/>

**Comment by paulcpederson** [comment]
@AdelheidF I think you would have to hit "Enter" to see the year change reflected in the calendar below.
