### ISSUE TITLE
calcite-modal: would like to hide header and footer

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#156]
I want to show the Arcade editor in a fullpage modal, but don't need the header and footer because the editor comes with its own close and save buttons.

![image](https://user-images.githubusercontent.com/44481292/65342000-a3b29080-db86-11e9-87ca-e9ec0f69a0dd.png)

**Comment by macandcheese** [comment]
Hmmm, I feel like having a consistent header and footer is a large benefit of using the `<calcite-modal>` - just providing a container feels like it will lead to pretty inconsistent usage. Maybe we can look at adding an "edit title" UI to modals - would that help here?

**Comment by AdelheidF** [comment]
I would still end up with 2 closing X and too much space below the Arcade editor's OK/Cancel buttons.

I guess because Arcade editor is what it is right now I will not use calcite-modal. We can change that once we have a new Arcade editor version.

**Comment by macandcheese** [comment]
Gotcha - I'm not familiar with Arcade but it should be possible to attach those "OK / Cancel" and "close" events to the ones in calcite-modal. Should we explore the "edit modal title" UI for the future?

**Comment by AdelheidF** [comment]
> Should we explore the "edit modal title" UI for the future?

Currently the Arcade editor displays the expression title in the header and when you click on that title or the edit icon it becomes an input box. I guess I could not do this in the header of an calcite-modal.

**Comment by macandcheese** [comment]
Going to close this for now, maybe we can look at an "Editable Field" component down the road that could solve for this use case.
