### ISSUE TITLE
Docs: Add additional storybook sections for grouping components

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1573]
### Description 

Docs: Add additional storybook sections for grouping components

### Which Component

All

### Resources 

Group similar components such as the "form" components similarly to how app components are grouped.

**Comment by driskull** [comment]
I will take an initial stab at this.

@julio8a @asangma @juliepowell maybe you could help with grouping the components into sections.

**Comment by driskull** [comment]
Installed storybook organization changes. Needs verification.

**Comment by julio8a** [comment]
Nice! Thanks for the work on this.
