### ISSUE TITLE
refactor: Remove getAttributes() utility helper and no longer spread attributes.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1579]
### Description

Remove getAttributes() utility helper and no longer spread attributes. #1579

### Acceptance Criteria 

We only set defined properties on internal elements

#### Which Component

All components using getAttributes() helper utility:

- [x] `calcite-button` #2410
- [x] `calcite-dropdown-item` #2427
- [x] `calcite-input` #2443 
- [x] `calcite-label` #2503 
- [x] `calcite-link` #2509

PR info: https://github.com/Esri/calcite-components/pull/1567

Related to #1538

**Comment by driskull** [comment]
This isn't pre 1.0 but is something we want to refactor soon since it allows a user to affect the shadow dom from the host element.

**Comment by eriklharper** [comment]
Resolved by #2410, #2427, #2443, #2503, #2509
