### ISSUE TITLE
Question: tabs/tab overflow in shell panel how to?

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#1582]
No amount of height or overflow styles will make tabs in a shell panel scroll on y overflow. It would be great if just the tab content scrolled and not the tab navs. But the shell panel scrolling the entire tabs component would be better than nothing.

Or maybe tabs are not suitable for a shell panel?

Here's a couple examples with no height or overflow and shell panel scrolls overflow just fine. And tabs with the containing `div`, `calcite-tab` and an inner content `div` all with `height: 100%` and `overflow: auto`.

![image](https://user-images.githubusercontent.com/14297903/108444348-4dc89900-720f-11eb-9905-df5f943c48a3.png)

![image](https://user-images.githubusercontent.com/14297903/108444362-55883d80-720f-11eb-93b6-8779fccc3cd3.png)

![image](https://user-images.githubusercontent.com/14297903/108444399-69cc3a80-720f-11eb-89be-600ae68d9cd0.png)

Thank you.

(And sorry for not making the browser height less for the screenshots.)

**Comment by driskull** [comment]
Yeah, it sounds like an update to the tabs so that their content scrolls when necessary. Does that sound correct?

**Comment by COV-GIS** [comment]
Correct.

I played around some more with overflows and heights. Any kind of overflow scrolling other than the top level element in the shell panel causes odd behavior. For example scrollbars on both sides of the action bar and in the nested element itself.

The way I'm displaying widgets in or using the shell panel might be an issue to.  I'm adding all widgets to the shell panel with `display: none;` and displaying appropriate widget when it's action is clicked. Is there an example of switching between content in a shell panel based on action click? Is there a proper calcite pattern for that or up to the dev?

Thanks.

**Comment by driskull** [comment]
@julio8a do you know who should work on this one?

**Comment by julio8a** [comment]
@caripizza is taking this one.

**Comment by justingreco** [comment]
I am able to achieve this by defining the height of the calcite-tabs component, which works fine in Chrome and Firefox, however makes it no usable in Safari.

calcite-tabs {
    height: calc(100% - 40px);
}

**Comment by caripizza** [comment]
@COV-GIS can you provide your snippet of code for me? I played with `calcite-shell-panel` inside of `calcite-tabs` in this pen here, and didn't run into any issues like you described yet (so I'm guessing your setup is a bit different): https://codepen.io/caripizza-the-animator/pen/mdRRwbK

**Comment by COV-GIS** [comment]
Here you go @caripizza https://codepen.io/COV-GIS/pen/BapJogR

The use case is a map view and a shell panel with action bar to toggle between widgets. It's a widget with tabs inside the shell panel which has a height greater than the height of the shell panel which has issues. I've tried several ways of adding heights and overflows to various elements but cannot achieve normal overflow scrolling as would be expected with an auto overflow div inside a 100% height div.

Ideally the tab content would scroll and the tab navs would remain fixed at top.

**Comment by caripizza** [comment]
@COV-GIS have you tried styling `calcite-tabs` with an actual height, like `height: 100vh;`? If you do this, adding `overflow-y: scroll;` to your existing `calcite-tab` styles in the pen seems to fix the issue for me.

**Comment by COV-GIS** [comment]
Thanks for looking into this @caripizza. The `100hv` height and scrolling leaves a portion inaccessible (height of the tabs) and the scrollbars are always visible in desktop browsers regardless of the widget's height. The issue can be overcome by accessing the shadow dom via JS and applying styles which is kind of hacky.

I previewed a shell panel and action bar for switching widgets with my users and they prefer the "floating" widget opposed to the shell panel taking up map real-estate. The component classes included in the JSAPI handle all the height and scrolling automagically.
