### ISSUE TITLE
Stories/Demos: use svg placeholder utility/abandon network calls to fetch images

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#1584]
### Demos
Our component demos include a few dynamic placeholder image links, which make Screener tests fail when the images change. Instead, we should use fixed images that don't change so Screener tests are less brittle. 

### Details 
Update the offending placeholder image links in the demos/ folder with static image links or svg data URIs
(Teams discussion is [here](https://teams.microsoft.com/l/message/19:fd15b51dacd24e70895ec1218a54ae06@thread.skype/1613755252847?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1613755252847&teamName=Calcite%20Design%20System&channelName=Calcite%20Components&createdTime=1613755252847))

UPDATE: Use the svg component Matt whipped up for this work (from #1587)

**Comment by julio8a** [comment]
Verified!
