### ISSUE TITLE
Enhancement: Add event emitter to combobox filter input

### ISSUE THREAD

**Issue by stevenalbers** [Esri/calcite-components#1585]
My current use case depends on adding a fallback option if no items in the combobox's list match the provided filter:

<img width="500" alt="Screen Shot 2021-02-19 at 10 34 44 AM" src="https://user-images.githubusercontent.com/5317415/108546815-806da280-729e-11eb-9078-d46acf4d5cf7.png">
<img width="463" alt="Screen Shot 2021-02-19 at 10 37 18 AM" src="https://user-images.githubusercontent.com/5317415/108546820-819ecf80-729e-11eb-843f-d7f63db9887d.png">

My thought is that the event `detail` would contain the current filter input, as well as the list of matching `visibleItems`, though that can be up for interpretation. This enhancement could also be beneficial in enabling async behavior based on the user's filter input.

**Comment by driskull** [comment]
I think we already have an event `calciteFilterChange`, it's just not documented.

**Comment by paulcpederson** [comment]
@stevenalbers this will be in the next release
