### ISSUE TITLE
Enhancement: Add combobox config option to highlight ancestry on child select

### ISSUE THREAD

**Issue by stevenalbers** [Esri/calcite-components#1590]
Some workflows only store the deepest value selected, so I'm looking for a mode where when you click on a child, every parent is also checked. I'll try to highlight most possible scenarios here, but can go into more detail if needed.

### Long example

Clicking on `Grandchild` should show `Grandchild`, `Child`, and `Parent` as selected, but only show the chip for `Grandchild`:

```
[Grandchild]
* Parent
  * Child
    * Grandchild
```

Clicking on a deeper element simply selects it, and updates the chip:

```
[Great-grandchild]
* Parent
  * Child
    * Grandchild
      * Great-grandchild
```

Clicking on a parent deselects all of its children:

```
[Child]
* Parent
  * Child
    Grandchild
      Great-grandchild
```

Clicking the selected element deselects the whole tree:

```
Parent
  Child
    Grandchild
      Great-grandchild
```

If multiple children are selected, they are all removed when a common ancestor is clicked. Before:

```
[Grandchild] [Child2]
* Parent
  * Child1
    * Grandchild
      Great-grandchild
  * Child2
```

After:

```
[Parent]
* Parent
   Child1
    Grandchild
      Great-grandchild
   Child2
```
cc @paulcpederson

**Comment by paulcpederson** [comment]
PR under review
