### ISSUE TITLE
Research: Investigate removal of host-context SCSS use in components

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1601]
### Background 

https://github.com/Esri/calcite-components/pull/1510#discussion_r580636342

### Desired Outcome 

Research: Investigate removal of host-context SCSS use in components

**Comment by paulcpederson** [comment]
`host-context` styles were a shim to get dark mode working in IE11 I believe. 

I think we could note under our browser support section that dark mode and theming don't work in IE11 and remove it. I would need to actually crack them open and be sure that light mode still works without it.

**Comment by driskull** [comment]
Can we just use both host and host-context for now? Or should we replace them?

**Comment by paulcpederson** [comment]
Basically if you want to support dark mode in IE11, you need to add the dark theme vars to the `:host-context` selector. If you don't do this, IE11 will get the light theme variables. For example, stepper items have it declared and they look good in dark on ie11:

<img width="1546" alt="Screen Shot 2021-02-23 at 12 46 10 PM" src="https://user-images.githubusercontent.com/1031758/108905912-20943600-75d5-11eb-92e3-55fa9033c866.png">

But when you remove it, they revert back:

<img width="1505" alt="Screen Shot 2021-02-23 at 12 41 25 PM" src="https://user-images.githubusercontent.com/1031758/108905941-2a1d9e00-75d5-11eb-88b5-3d7adc60efdd.png">

Basically most modern browsers don't support `:host-context`, so they ignore it. But stencil tries to polyfill it in IE11, so it's a way to bootleg the correct variables into the pseudo shadow dom in IE11. That said the story for dark theme support in IE11 is already... spotty:

<img width="1521" alt="Screen Shot 2021-02-23 at 12 49 15 PM" src="https://user-images.githubusercontent.com/1031758/108906276-8ed8f880-75d5-11eb-929d-dd1196db46f2.png">

My thought was to just remove all these `:host-context` sections, add a note that dark theme is not available in IE11 and move on with our lives. I'm not aware of any teams that want ie11 support + dark mode support but I could be wrong. Modern browsers get the dark vars via inheritance from the global style sheet, so it's only ie11 where we have this issue. They also bloat the final styles transferred across the wire significantly.

**Comment by driskull** [comment]
> add a note that dark theme is not available in IE11 and move on with our lives

<img src="https://media.giphy.com/media/zKsfeEYZI4Ku4/giphy.gif" />

**Comment by driskull** [comment]
Installed. Only `accordion` has host-context being used. We could possibly remove that in the future if someone wants to make an issue.
