### ISSUE TITLE
Research: How to best handle notification of animation complete

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1602]
### Background 

https://github.com/Esri/calcite-components/pull/1510#discussion_r580651509

A lot of our components are using setTimeout to wait for animations to end and then calling setFocus(). This is quite brittle. We should expose the animationend/transitionend event to notify when internal animations are completed.

We need to do some prototype work.

https://github.com/Esri/calcite-components/search?l=TSX&q=setTimeout%28

### Desired Outcome 

setTimeout isn't used to focus on nodes.

**Comment by paulcpederson** [comment]
This is a cool idea!

**Comment by jcfranco** [comment]
What's the priority of this one?

**Comment by driskull** [comment]
I'd say medium to low. I think all of these things work now with the timeouts but they are subject to breaking.

**Comment by driskull** [comment]
I'm wondering if we should use the existing events or add additional events for the transitionEnd?

One issue is that it doesn't seem the `.e2e` tests get notified of transitionEnd.

**Comment by jcfranco** [comment]
Verified via https://codepen.io/jcfranco/pen/gOWzapR?editors=1010
