### ISSUE TITLE
Enhancement: Add Small and Large Tabs

### ISSUE THREAD

**Issue by bpatterson88** [Esri/calcite-components#1610]
### Description

Current tabs component comes in one size, which looks like medium. Dashboards would like to use tabs in the side panel in the future, and the medium size would be a bit a large for that.

### Acceptance Criteria 

Tabs can be rendered small

#### Which Component

Tabs

#### Example Use Case

Mockup for how we're planning to use tabs:
![Screen Shot 2021-02-23 at 4 52 25 PM](https://user-images.githubusercontent.com/15875886/108928751-8e515980-75f7-11eb-8f15-b747c85c515f.png)

**Comment by macandcheese** [comment]
Related - https://github.com/Esri/calcite-components/issues/803 - should just have S, M, L cc @bstifle

**Comment by bstifle** [comment]
yep! designs are done, just need to implement

![image](https://user-images.githubusercontent.com/14083530/109025394-4fb5b080-7684-11eb-9877-5096dfea0a1f.png)

**Comment by julio8a** [comment]
I can give this a try!
![](https://media3.giphy.com/media/y9X0F8VgTkmU8/giphy.gif)

**Comment by bstifle** [comment]
hahahaha love stimpy

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/116442582-45489c00-a818-11eb-9359-425a054b39a1.png)
specs

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/116614572-b616b380-a8ff-11eb-8b13-6a147dc172f8.png)

**Comment by caripizza** [comment]
Hi @bpatterson88! Would you mind if I close this one in favor of #803? (@bstifle is looking to add an additional prop to the component in that issue, along with adding the SML scales.)

**Comment by caripizza** [comment]
Closing in favor of #803
