### ISSUE TITLE
Enhancement: Combobox non-selectable headings

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1617]
### Description
Add ability to have non-selectable headings for groups of items.

#### Which Component
ComboBox

#### Example Use Case

https://w3c.github.io/aria-practices/examples/listbox/listbox-grouped.html

**Comment by driskull** [comment]
Installed

**Comment by asangma** [comment]
Looks grood!

**Comment by asangma** [comment]
Reopening...

Seems like we'd want the label to wrap and keep the chevron to the right.
![image](https://user-images.githubusercontent.com/12503298/110518212-b0031400-80c0-11eb-8e30-df377a0841e1.png)

I can add styles for this.

**Comment by driskull** [comment]
Yeah that sounds right. Its kind of unrelated though right?

**Comment by jcfranco** [comment]
Closing. 

> Seems like we'd want the label to wrap and keep the chevron to the right.

@asangma If this is still valid, can you open another issue? Thanks!
