### ISSUE TITLE
Bug: calcite-action: appearance=outline doesn't work

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1630]
### Summary

appearance=outline doesn't work

![image](https://user-images.githubusercontent.com/44481292/109341727-ac999e00-781f-11eb-9b7e-88296b7aefc7.png)

I'd like to have this look for an input with an action

![image](https://user-images.githubusercontent.com/44481292/109341673-95f34700-781f-11eb-8e05-48616f079ece.png)

---------------------

When I don't use a border the focus box looks like this.
<img src=https://user-images.githubusercontent.com/44481292/109535882-ea8e0080-7a71-11eb-94a6-102e2d642437.png width=250/>
<img src=https://user-images.githubusercontent.com/44481292/109535908-f5e12c00-7a71-11eb-8ce1-0fd3f7ca6482.png width=250/>

When I use a border on the top, right, and bottom the focus box looks a bit weird. Maybe we should keep the outline option.
<img src=https://user-images.githubusercontent.com/44481292/109535775-ca5e4180-7a71-11eb-9f99-9fa06d135f1f.png width=250/>
<img src=https://user-images.githubusercontent.com/44481292/109535828-d944f400-7a71-11eb-9422-67160a9ed4bf.png width=250/>

### Reproduction Steps

1.

**Comment by AdelheidF** [comment]
from @driskull 

@alan0002 do you know if action is supposed to support "outline" or do we need to update that doc/interface?

**Comment by macandcheese** [comment]
Closing this - the unused value is no longer documented: https://github.com/Esri/calcite-components/tree/master/src/components/action#properties
