### ISSUE TITLE
Bug: Active tab event fired before tab title is hydrated

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#1641]
### Summary
While the `calcite-tab-title` component renders, it fires off a `calciteTabsActivate` event before the component is fully hydrated. As a result, listeners interested in the `calcite-tab-title` element (maybe to get its `id` property for accessibility purposes) are unable to do so. The event is not fired again until the user changes tabs.

The `calcite-tab-nav` component's `calciteTabChange` event exhibits the same behavior.

### Actual Behavior
A `calciteTabsActivate` listener is triggered with an event target object containing an empty `calcite-tab-title` element.

### Expected Behavior
The listener's event target references the fully populated/hydrated `calcite-tab-title` element.

### Relevant Info 
Chrome, macOS

**Comment by benelan** [comment]
Tested on `next`. The event no longer emits on initial load, and it also doesn't emit twice per tab change. @nwhittaker can you verify that this is what you're looking for: https://codepen.io/benesri/pen/abEGRXa

**Comment by nwhittaker** [comment]
>The event no longer emits on initial load...

Thanks for the work on this. It does address the problem of handling the event before the tab title element is hydrated. However, for my particular use-case, it was important that the event was also emitted for the initially active tab too so I could get its Calcite-generated `id`.

I can think of a workaround or alternative approach for my code, but I suspect omitting the event for the initial tab could be a fairly major BC break, in general.

**Comment by jcfranco** [comment]
@nwhittaker You can set the ID on the tab title component and it will get set accordingly. The ID is auto-generated only when `id` is missing.

**Comment by benelan** [comment]
Closing as verified on `next` based on ☝️
