### ISSUE TITLE
Enhancement: PickList remove margin-top from description

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1650]
### Description
There's a heap of space in there that gets multiplied where there are a lot of items.
cc @bstifle 

### Acceptance Criteria 
Tighter UI.

#### Which Component
PickList
Change here should also appear in ValueList

#### Example Use Case
Any PickList or ValueList with more than a few items.

![Screen Shot 2021-03-03 at 9 46 03 AM](https://user-images.githubusercontent.com/12503298/109848586-4a68e080-7c05-11eb-8a4b-626bc39ec74f.png)

**Comment by asangma** [comment]
@julio8a @bstifle Would one of y'all mind verifying?

**Comment by bstifle** [comment]
Verification Complete ✅
