### ISSUE TITLE
CalcitePopover: Enhance Popover

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#166]
We should move the interaction versions (click, close X, image, button, etc) to the popover.

- Add property to automatically setup the click handler. (false by default)
- Add property to enable the close button (false by default)
- Add slot to accept image

![image](https://user-images.githubusercontent.com/1231455/66502228-b4fe0700-ea79-11e9-8d61-69d5844230f5.png)

**Comment by driskull** [comment]
Installed.

**Comment by julio8a** [comment]
Looks good. Closing this out.
