### ISSUE TITLE
Question: Do we need the image node in Popover?

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1671]
### Question
Propose removing the image slot from Popover.

Right now we have an [image node](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-popover/calcite-popover.tsx#L346-L352) in Popover.

The image slot seems like an unnecessary and unused feature.
Supporting it also causes unnecessary nesting of nodes when there's just content.

### Helpful Details 
Divs with single divs inside them have a tendency to cause unforeseen UI bugs.

**Comment by julio8a** [comment]
This sounds good to me

**Comment by asangma** [comment]
Thanks @julio8a!

**Comment by asangma** [comment]
@julio8a Mind if I assign this one to you?
