### ISSUE TITLE
Enhancement: Tip Manager spacing and design improvements

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#1672]
![image](https://user-images.githubusercontent.com/14083530/109991312-d5161200-7ccf-11eb-93f1-3ad9c6078c9c.png)

Let's bring tip manager into the future!

Figma link
https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1183%3A20943

**Comment by caripizza** [comment]
closing in favor of #2471 and #2469
