### ISSUE TITLE
Enhancement: Get buttons up to design spec

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#1674]
Many buttons have improper colors for idle/hover/press states.

This issue is to take care of that once and for all!!!

Figma link:
https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1706%3A0

![buttons](https://user-images.githubusercontent.com/14083530/110050148-ee8f7c00-7d18-11eb-8aa0-efea01b1461b.png)

**Comment by caripizza** [comment]
Closing in favor of #2456
