### ISSUE TITLE
Bug: calcite-button - make padding fit other components

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1679]
### Description
Could we add an option to align the icon at the very end of the button instead of after the text?
When clicking on the button a popover opens. The component below is a calcite-select.

I could work around this issue by using a button and an action but then I have two pieces doing the same thing and a visible separator.

![image](https://user-images.githubusercontent.com/44481292/110158818-b468bd80-7d9e-11eb-992f-dade141d0da6.png)

**Comment by macandcheese** [comment]
@AdelheidF already in there with `alignment="icon-end-space-between"` -

https://jsbin.com/neguharora/

However, the button doesn't really align with the select below it:

![Screen Shot 2021-03-05 at 10 50 43 AM](https://user-images.githubusercontent.com/4733155/110160301-af0c7280-7da0-11eb-90df-bb486c009d71.png)

I think the upcoming Tailwind pass will solve that? (@asangma @bstifle )

**Comment by AdelheidF** [comment]
Oh, sorry that I missed that.

But yes, would be great if they'd align. The third line uses a calcite-action.
![image](https://user-images.githubusercontent.com/44481292/110162156-31963180-7da3-11eb-8b68-68d7a5340a97.png)

**Comment by AdelheidF** [comment]
this is fine now
