### ISSUE TITLE
Bug: calciteDropdownOpen is fired when dropdown is open

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#1688]
### Summary

An extraneous `calciteDropdownOpen` event is fired.

### Actual Behavior

Clicking on the dropdown button to close the dropdown fires `calciteDropdownOpen` followed by `calciteDropdownClose`.

### Expected Behavior

Only `calciteDropdownClose` should fire.

### Reproduction Steps

1. Click on dropdown button to open dropdown.
2. Click on dropdown button again to close dropdown.

https://codepen.io/gpbmike/pen/gOLdaaV?editors=1011

Take a look at the console log.

### Relevant Info 

Chrome 88.0.4324.192
MacOS 10.15.7

**Comment by Elijbet** [comment]
@gpbmike Does the issue still exist? Clicking on the dropdown button to close the dropdown seems to be firing calciteDropdownClose twice instead.

**Comment by gpbmike** [comment]
@Elijbet You're right. I should have pinned the calcite-components version when I created the issue. 

Still a bug I would think, just the opposite bug now. 😄

**Comment by benelan** [comment]
verified on `beta.71`
