### ISSUE TITLE
Bug: calcite-input-date-picker - width issues

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1689]
### Summary

I display the `calcite-input-date-picker` next to a `calcite-action`. The action opens a popover with unique values.

perfect look:
<img src=https://user-images.githubusercontent.com/44481292/110185483-4dabca00-7dc7-11eb-99cc-8e2bec0475a3.png width=250/>

narrow panel, if I remove the padding it's fine:
<img src=https://user-images.githubusercontent.com/44481292/110185517-67e5a800-7dc7-11eb-998a-fbb088c86e3e.png width=200/><img src=https://user-images.githubusercontent.com/44481292/110185541-7c29a500-7dc7-11eb-8bb6-eb8bebf46082.png width=300/>

wide panel:
<img src=https://user-images.githubusercontent.com/44481292/110185613-a713f900-7dc7-11eb-8f0b-42582060aa0b.png width=250/><img src=https://user-images.githubusercontent.com/44481292/110185652-c27f0400-7dc7-11eb-86dc-f4d5dc285e18.png width=200/>

If I overwrite `max-width` with `initial` I see this, why can't the calendar be as wide as I need it? Or, if my input is wider than we allow for the calendar, just align the calendar on the right or left side of the input.
<img src=https://user-images.githubusercontent.com/44481292/110185715-eb06fe00-7dc7-11eb-9927-aa1c58de13f9.png width=200/>

cc @asangma @driskull

**Comment by driskull** [comment]
@asangma this seems like only style changes, right?

**Comment by asangma** [comment]
@driskull Yeah.

**Comment by asangma** [comment]
@AdelheidF Ping me if need be, and I can close.

**Comment by AdelheidF** [comment]
The issue with a wide panel is fixed. Thanks!

<img src=https://user-images.githubusercontent.com/44481292/112067131-cda29580-8b24-11eb-899f-b45ac57e7469.png width=300/>

The issue with a narrow panel is not.

<img src=https://user-images.githubusercontent.com/44481292/112067313-18bca880-8b25-11eb-9ef7-940280852106.png width=200/>

test case:
Open Chrome debugging tools and make them very wide, so the viewer is pretty narrow.
https://devext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0
select layer, click filter, add expression. Change field to 'Date of crash', observe.

**Comment by AdelheidF** [comment]
The calendar is always left aligned, even in RTL. Is this purpose?

<img src=https://user-images.githubusercontent.com/44481292/112067566-836de400-8b25-11eb-87f1-7705b8676064.png width=250/><img src=https://user-images.githubusercontent.com/44481292/112067615-954f8700-8b25-11eb-8cca-462e86b28d20.png width=250/>

**Comment by driskull** [comment]
@AdelheidF can you create an issue for the calendar alignment? We need to update to use those new placements added.

**Comment by AdelheidF** [comment]
https://github.com/Esri/calcite-components/issues/1826

**Comment by AdelheidF** [comment]
Issue is still happening with a narrow shell panel when the picker is part of a calcite-block and has a calcite-action after.
![image](https://user-images.githubusercontent.com/44481292/116900109-36cdfc00-abed-11eb-8d51-85688056e291.png)

I noticed that it's caused by the calcite-action. If I take that away I can make the panel as narrow as I want and the picker adjusts correctly.

**Comment by AdelheidF** [comment]
can no longer repro it
