### ISSUE TITLE
Add global variables to includes.scss

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#169]
We have a lot of duplicate css variables at the top of component .scss files, we could probably offload some of the more common ones like background, background-hover/-press, shadows,  state colors to our includes file - https://github.com/Esri/calcite-components/blob/master/src/assets/styles/includes.scss

Could probably organize and separate out mixins, etc.

**Comment by paulcpederson** [comment]
I think since @julio8a added https://github.com/Esri/calcite-components/blob/master/src/assets/styles/_colors.scss we are good on this one?
