### ISSUE TITLE
Disabled param does not work for calcite-button

### ISSUE THREAD

**Issue by ehusaint** [Esri/calcite-components#170]
`<calcite-button scale="xl" disabled="true"> </calcite-button> `does not disabled the button.

**Comment by macandcheese** [comment]
Hi @ehusaint, make sure you are using an updated version of the calcite-components beta, support for disabled buttons was only added a few releases ago - https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#v100-beta5---aug-21th-2019. Let me know if that clears it up or if there is still an issue. Thanks!

**Comment by macandcheese** [comment]
I think this was resolved with the version bump - feel free to re-open if that's not the case.
