### ISSUE TITLE
Docs: Review internal events

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1705]
### Description 

https://github.com/Esri/calcite-components/pull/1517 added doc to all public events and made pending ones internal to be reviewed in this issue.

Please review the internal events of each component and determine whether they should be made public. Please add doc for any that will be exposed.

### Which Component

- [x] `calcite-inline-editable` (@alexabreu)
- [x] `calcite-stepper` (@macandcheese)
- [x] `calcite-stepper-item` (@macandcheese)
- [x] `calcite-input` (@macandcheese)
  Note: focus/blur events were made internal to allow for more general calciteFocus/calciteBlur events.
- [x] `calcite-switch` (@macandcheese )
- [x] `calcite-accordion` (@macandcheese)
- [x] `calcite-accordion-item` (@macandcheese 
  Note: the close event doesn't seem to be not emitted

**Comment by macandcheese** [comment]
Switch, input public events look good, I'll make some updates to accordion/stepper 🚀

**Comment by jcfranco** [comment]
Addressed by https://github.com/Esri/calcite-components/pull/4496. Closing! cc @geospatialem
