### ISSUE TITLE
Enhancement: Auto-adjust headingLevel of child elements

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#1710]
### Description

https://github.com/Esri/calcite-components/pull/1639/ added `headingLevel` to the block, panel, pick-list-group and tip-manager components. The level prop needs to be set on the parent and child elements (except for tip & tip-manager). As an enhancement, the remaining components should follow this pattern to make it easier for users.

### Acceptance Criteria 

Root elements with a `headingLevel` prop should automatically adjust for child elements (similar to tip-manager & tip).

#### Which Component

- `calcite-block`
- `calcite-pick-list`
- `calcite-panel`

**Comment by driskull** [comment]
@jcfranco how does this affect block or panel? I think it's just the `pick-list` and `value-list` that need to modify the `pick-list-group`.

**Comment by jcfranco** [comment]
> how does this affect block or panel? I think it's just the pick-list and value-list that need to modify the pick-list-group.

Sorry for the delay. I can't remember why I added block or panel. For panel, maybe because I was thinking about having it adjust the heading level of any child content, but that may be too complex/intrusive.

**Comment by jcfranco** [comment]
Verified locally!
