### ISSUE TITLE
Bug: Icon for the calcite link does not flip in RTL

### ISSUE THREAD

**Issue by ajoshipuraGH** [Esri/calcite-components#1712]
### Summary
the icon on the end does not flip in position to the start neither does it rotate when we view the page in RTL mode:
https://aem-author-dev.esri.com/content/esri-sites/language-masters/en/sandbox/c3p0/modular-content-strip.html?wcmmode=disabled

### Reproduction Steps

1.

**Comment by ajoshipuraGH** [comment]
Hi Adam, Need it to work with AEM,  Tim mentioned that that dir attr is
being added by the calcite js and not AEM code

**Comment by paulcpederson** [comment]
This must be for some other component which uses an icon internally? Icons inside links work correctly in terms of their position within the link flow:

https://codepen.io/paulcp/pen/bGggKNa

The icon doesn't flip itself. We'd need to add  `icon-start-mirror` `icon-end-mirror` for that. 

@ajoshipuraGH what would be really helpful would just be a copy + paste of the source elements that display this?

**Comment by macandcheese** [comment]
We do have that prop, icon-flip-rtl which can accept start, end, or both:

https://github.com/Esri/calcite-components/tree/master/src/components/calcite-link#properties

**Comment by paulcpederson** [comment]
OK, yeah we should add that to the storybook. Works great https://codepen.io/paulcp/pen/bGggKNa . I'm going to close this. 

@ajoshipuraGH feel free to reopen with a code sample and we can look into it more.
