### ISSUE TITLE
Bug: Panel heading should be Medium

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1715]
### Summary
It got set to Bold.

Panel > .header > .header-content > .heading

### Reproduction Steps

1.

**Comment by asangma** [comment]
I suggest not making UI changes as part of a refactor.

**Comment by paulcpederson** [comment]
Figma designs had demi, not medium, right?

@asangma you need to pull in calcite fonts from the CDN onto the app-components demo pages. They will currently render a true bold because they use the system default avenir.

**Comment by asangma** [comment]
@paulcpederson Copy that. I will update this issue.

**Comment by asangma** [comment]
Hmm...our Tailwind font-weights might be out of sync.

**Comment by julio8a** [comment]
PR merged that reverts this to the previous font-weight. Panel heading is back to Medium.
