### ISSUE TITLE
Component: update Sliders style

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#172]
Need to update implementation based on latest Sketch designs. 

- Handle colors
- track colors
- hover state changes
- keep focused state same as hover
- notch breaks: down to 1px instead of 2px
- etc

![image](https://user-images.githubusercontent.com/14083530/66685791-50d27300-ec32-11e9-9798-a17227235907.png)

**Comment by macandcheese** [comment]
I think @julio8a updated these!

**Comment by julio8a** [comment]
Yeah, these should be good.
