### ISSUE TITLE
Bug: calcite-shell-panel hiding content when it overflows the panel height

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1733]
### Summary
I think this has been reported already in the viewer, but I did not see an issue for it here, so wanted to put one in for tracking.

When content in a shell panel, such as a long value list, overflows the height of the panel, the items are hidden rather than scrollable. Seems to happen in a shell panel but not in a calcite-panel - still trying to work out exact case.
![image](https://user-images.githubusercontent.com/52869490/110713846-75c86e00-81b7-11eb-81e3-9514af90e70c.png)

### Expected Behavior
It should scroll so the items that overflow are visible and not cut off.
### Reproduction Steps

https://codepen.io/eborgen/pen/dypMyON?editors=1000

**Comment by ethanbdev** [comment]
Just adding, after looking some more it seems like any panel that gets this selector added has the issue:
![image](https://user-images.githubusercontent.com/52869490/110816814-88d35080-8240-11eb-85fd-6b1c0a1c4ec8.png)

So even if I use a panel not _directly_ inside a calcite shell panel (but still a child of), it gets this css and has the issue.

**Comment by ethanbdev** [comment]
It is a bit messy, but I have added my popover repro case to the codepen.
![Uploading image.png…]()

**Comment by driskull** [comment]
@asangma I think you recently added that CSS that might be causing the issue.

**Comment by driskull** [comment]
I'm not sure the shell panel is supposed to scroll by default. I'm not seeing any overflow defined for it to do so. @asangma do you know?

Same thing with the popover, the user needs to define a scrollable area.

**Comment by driskull** [comment]
If you add a height to the `<calcite-panel>` inside the popover it scrolls fine.

Maybe we need better doc for components where they need their height set to be scrollable?

**Comment by asangma** [comment]
If you would prefer to put your own stuff in there, you'll be responsible for handling scroll behavior.
Try putting your content inside a CalcitePanel. It will give you a lot of that stuff for free.

**Comment by asangma** [comment]
> Maybe we need better doc for components where they need their height set to be scrollable?

Or we can do like we do in ShellPanel where we do :slotted styles for our own components, yeah?

In the case of the popover, you can set your max-height class on Panel, but you'd also need to add an overflow rule.

We don't set that because we don't know what needs to happen in various cases.

**Comment by ethanbdev** [comment]
@driskull, the panel has a height (of 100%), it is coming slotted from the shell panel. If I set `height: auto` on the panel then it does fix the issue. Doing this was not needed pre-beta.51 and there was no documented change on it. Going forward is this what we should do?

@asangma It is hard to explain, I do not want to post a screenshot of the UI here, but the UI is in a panel, and that panel has a scroll correctly. The bottom is still cut off slightly in the viewer.
![BCF91785-C47E-44F9-804F-48F9A1B670A0](https://user-images.githubusercontent.com/52869490/111693480-e8f06680-87ed-11eb-9367-0fb867a8736d.GIF)

I missed the beginning of the meeting, sorry if any of this has been answered.

**Comment by asangma** [comment]
Just merged an update.
Once that's on @next, try it by setting the `height-scale` prop on Panel.
It will also work to write a height style onto Popover...but the Panel prop would be the suggested approach.

**Comment by ethanbdev** [comment]
Looks good @asangma 🚀, so we should use `height-scale` instead of our own `max-height`. Makes sense to me!

Thank you for taking a look!

**Comment by asangma** [comment]
Yew!
