### ISSUE TITLE
Enhancement: Improve cut off text display in panel headers

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#1739]
In Map Viewer, long layer names get cut-off on the panel headers:

![image](https://user-images.githubusercontent.com/50747646/110839986-0b680a00-8259-11eb-8e61-02564562ed7a.png)

Would be nice to improve this so the entire layer name is visible. 

cc @asangma

**Comment by macandcheese** [comment]
related: https://github.com/Esri/calcite-components/issues/1643

**Comment by macandcheese** [comment]
Closing - this was addressed in https://github.com/Esri/calcite-components/pull/3736

@zaramatheson - example of current functionality here: https://codepen.io/mac_and_cheese/pen/XWEmMPo?editors=100

cc @benelan
