### ISSUE TITLE
Component: Pagination

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#174]

**Comment by julio8a** [comment]
![image](https://user-images.githubusercontent.com/6144462/68345405-1d0a3200-00a6-11ea-8d2b-c2e848059425.png)

**Comment by paulcpederson** [comment]
Here is a stab at a quick spec for this. Using the above design example.

# calcite-pagination

Calcite pagination allows you to create a set of links for navigating between pages in longer API responses. 

```html
<calcite-pagination 
  start="1"
  total="230" 
  num="12"
  next-label="next page" 
  previous-label="previous page"
  theme="dark"
  dir="rtl"
/>
```

When a link is clicked we should emit an event with the desired state. Imagine we clicked the `4` above:

```js
const pagination = document.querySelector("calcite-pagination");
pagination.addEventListener("calcitePaginationUpdate", function (e) {
  console.log(e.detail) // => { start: 49, total: 230, num: 12 }
});
```

---

The reason for structuring and naming the props and event detail like this is that it's a 1-to-1 with how most paginated APIs at Esri name their response properties , so will be extremely easy for devs to plug and play.

**Comment by pr3tori4n** [comment]
https://github.com/Esri/calcite-components/tree/master/src/assets/styles
type and shadow mixins.

**Comment by pr3tori4n** [comment]
@julio8a could you provide additional technical specifications for how the ellipses should work?

**Comment by paulcpederson** [comment]
Current behavior is as follows: 

```
// Less than 5 pages
Prev  [1]   2   3   Next
Prev   1   [2]  3   Next
Prev   1    2  [3]  Next

// Exactly 5 pages
Prev  [1]   2   3   4   5   Next
Prev   1   [2]  3   4   5   Next
Prev   1    2  [3]  4   5   Next
Prev   1    2   3  [4]  5   Next
Prev   1    2   3   4  [5]  Next

// High number of pages
Prev  [1]  2   3   4   5   ... 22  Next
Prev   1  [2]  3   4   5   ... 22  Next
Prev   1   2  [3]  4   5   ... 22  Next
Prev   1   2   3  [4]  5   ... 22  Next
Prev   1  ...  4  [5]  6   ... 22  Next
Prev   1  ...  5  [6]  7   ... 22  Next
...
Prev   1  ...  17 [18] 19  ... 22  Next
Prev   1  ...  18  19 [20] 21  22  Next
Prev   1  ...  18  19  20 [21] 22  Next
Prev   1  ...  18  19  20  21 [22] Next
```

Screenshots of this progression:

![Screen Shot 2019-12-19 at 5 30 12 PM](https://user-images.githubusercontent.com/1031758/71222667-42ce4d80-2286-11ea-9623-c9ddd15226e9.png)
![Screen Shot 2019-12-19 at 5 30 20 PM](https://user-images.githubusercontent.com/1031758/71222668-4366e400-2286-11ea-960d-978d8f5ba450.png)
![Screen Shot 2019-12-19 at 5 30 27 PM](https://user-images.githubusercontent.com/1031758/71222669-4366e400-2286-11ea-9c25-c937b0ed0459.png)
![Screen Shot 2019-12-19 at 5 30 35 PM](https://user-images.githubusercontent.com/1031758/71222670-4366e400-2286-11ea-820f-7a798051bf5c.png)
![Screen Shot 2019-12-19 at 5 30 42 PM](https://user-images.githubusercontent.com/1031758/71222671-4366e400-2286-11ea-9653-a811f7508634.png)
![Screen Shot 2019-12-19 at 5 30 50 PM](https://user-images.githubusercontent.com/1031758/71222672-4366e400-2286-11ea-8d14-5a5d489fcff8.png)
![Screen Shot 2019-12-19 at 5 30 58 PM](https://user-images.githubusercontent.com/1031758/71222673-4366e400-2286-11ea-817b-45e5b57512a2.png)
![Screen Shot 2019-12-19 at 5 31 13 PM](https://user-images.githubusercontent.com/1031758/71222675-43ff7a80-2286-11ea-8bf6-dbd35fca7d3e.png)
![Screen Shot 2019-12-19 at 5 31 18 PM](https://user-images.githubusercontent.com/1031758/71222676-43ff7a80-2286-11ea-9890-ad4f3dfb5a80.png)
![Screen Shot 2019-12-19 at 5 31 07 PM](https://user-images.githubusercontent.com/1031758/71222674-43ff7a80-2286-11ea-99b9-9e1c34890e3f.png)


It's a lot of math, but doing it this way keeps the next/prev buttons in the same place and makes the component roughly the same width regardless of page set size.

**Comment by pr3tori4n** [comment]
@paulcpederson I think I have this logic as desired. Would you mind pulling down my branch and taking a look?
` hrobbins/pagination-component-174`

**Comment by paulcpederson** [comment]
@pr3tori4n behavior looks correct. We should work with @bstifle once this goes in to get the design matching the spec, though, I see a couple things that are off (hover states, etc) that will be quick things to address. I've put up static sites at temporary urls for design review before, and that seems to work fairly well.

**Comment by pr3tori4n** [comment]
@bstifle http://localhost:3333/demos/calcite-pagination.html

This is my local dev server. It may come up or down depending on what i'm doing so hit me up if you can't get to this.

**Comment by julio8a** [comment]
@pr3tori4n, I think you need to replace `localhost` with your computer name or Esri internal IP address

**Comment by pr3tori4n** [comment]
whoops. Fixed :).

**Comment by pr3tori4n** [comment]
@julio8a What's the process for moving an issue forward after its been merged. Do you have a verification process?

**Comment by julio8a** [comment]
Once we merge the PR handles quite a bit of review. If it needs any more work we'll create new issues. Closing this guy!
