### ISSUE TITLE
Bug: remove calcite-label from internals of checkbox and radio

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1740]
### Summary

Bug: remove calcite-label from internals of checkbox and radio

### Actual Behavior

these two components automatically add a calcite-label internally

### Expected Behavior

User is expected to add their own calcite-label externally

**Comment by driskull** [comment]
@julio8a should this be a pre-1.0 breaking change?

**Comment by julio8a** [comment]
Yes, likely. I want to spend some time reviewing all the `p-high` labels to see what else we have that might be breaking needed for 1.0
