### ISSUE TITLE
Bug: calcite-switch - alignment issues in RTL

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1747]
### Summary

It shows two calcite-block-section and one calcite-switch, surrounded by calcite-label.

<img src=https://user-images.githubusercontent.com/44481292/110873798-64e72d80-8287-11eb-9d39-b259d02517ec.png width=200/>

LTR:
<img src=https://user-images.githubusercontent.com/44481292/110874184-2c941f00-8288-11eb-8bb1-ada66e3da715.png width=200/>

### Reproduction Steps

1.

**Comment by Olga8614** [comment]
https://github.com/ArcGIS/I18N-BYS-Bugs/issues/6389 - reported by BYS

**Comment by AdelheidF** [comment]
This must have gotten fixed before `beta.54`, because production is fine too.

![image](https://user-images.githubusercontent.com/44481292/118573440-6aee0480-b737-11eb-81e3-5cc546288837.png)

**Comment by Olga8614** [comment]
We verified this defect on AGOL 9.2 Devext site (6/9/2021) in Arabic and Hebrew language on FF/Chrome/Edge(Chromium)/Safari browsers. On/Off switcher of Include in legend is left aligned now but is still flipped. So this defect is partly fixed. Thanks!
