### ISSUE TITLE
Bug: calcite-panel - disabled:true makes panel scroll to top

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1749]
### Summary
We want to disable the panel if the user opens a popover overlapping it. 
If you disable the panel while you're scrolled to the bottom it will automatically scroll up. So the user has to scroll back down after closing the popover.

### Reproduction Steps

1.

**Comment by AdelheidF** [comment]
I noticed a second thing.

On the left is my panel without the popover. On the right is the panel in disabled state (I'm hiding the popover to show the issue better). Notice where the footer buttons are.

<img src=https://user-images.githubusercontent.com/44481292/111010740-37b08300-834c-11eb-8ff1-c52fba9309f7.png width=210/><img src=https://user-images.githubusercontent.com/44481292/111010786-63336d80-834c-11eb-8c4f-031a91d1e34b.png width=200/>

**Comment by driskull** [comment]
Installed.

**Comment by AdelheidF** [comment]
looks good with next.123
