### ISSUE TITLE
Bug:  calcite-shell-panel - header slot messes up fab button

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1750]
### Summary

Might have started with beta.51.

The "header" in the calcite-shell-panel that the layerSwitcher is in, it pushes everything down.
<img src=https://user-images.githubusercontent.com/44481292/111005284-607e4b80-833f-11eb-977a-6f9c8c572b05.png width=250/>

### Reproduction Steps

1.

**Comment by asangma** [comment]
@AdelheidF A simple fix I found was to set `overflow:hidden` on your component, e.g. on `arcgis-filter`.

I can add a style for a slotted `calcite-panel` or `calcite-flow`, but I would be reluctant to do a wildcard `*` selector.
I could maybe do a `[class^="arcgis-"]` to target our micro apps...?

cc @driskull @jcfranco @paulcpederson

**Comment by driskull** [comment]
> I could maybe do a [class^="arcgis-"] to target our micro apps...?

Probably not a good idea.

**Comment by AdelheidF** [comment]
So, we should add `overflow:hidden` to all panel-components that show a fab button and could be used with a layer switcher?

**Comment by asangma** [comment]
I think apply `overflow:hidden` to any of the `arcgis-[your component name]` elements.
This would apply to Popup config, etc. as well. (Can't seem to get Dhrumil's handle to appear here).

Charts would need to do something similar, but there seems to be other things happening with that mico-app.

**Comment by asangma** [comment]
I'll keep trying other things in the meantime.

**Comment by asangma** [comment]
Update: hold off on adding the overflow:hidden. I'll try to find another way that doesn't require that. If I can't soon, you'll have to add it.

**Comment by asangma** [comment]
@AdelheidF Installed.

You can ignore the overflow suggestion earlier.
If you see a lack of a scrollbar where there should be one, try setting `height:100%` on things.

If a Panel or Flow is placed directly into the default slot, it should work as-is.
For anything else, you'll probably need to put `height: 100%` on it. 
This includes a Panel inside something else, e.g. `arcgis-[some thing]` > `calcite-panel`.

**Comment by AdelheidF** [comment]
looks good with next.123
