### ISSUE TITLE
Bug: calcite-shell-panel with button in header slot with weird focus box

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1753]
### Summary

Is there something we could do?

<img src=https://user-images.githubusercontent.com/44481292/111007980-f2d51e00-8344-11eb-94a4-0e66a1b5a405.png width=300/>

<img src=https://user-images.githubusercontent.com/44481292/111008053-1ef09f00-8345-11eb-8cda-82b57bd79706.png width=400/>

### Reproduction Steps

1.

**Comment by driskull** [comment]
@AdelheidF this UI actually needs to be updated to use the `calcite-combobox` instead of a button/popover combination.

**Comment by AdelheidF** [comment]
cc @kevindoshier
