### ISSUE TITLE
Enhancement: calcite-dropdown - more alignment options for RTL

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1758]
### Description

I use a `calcite-dropdown` (`alignment:end`) with a `calcite-action` that opens a menu below the action. This works well with LTR.

<img src=https://user-images.githubusercontent.com/44481292/111213969-949b7b80-858e-11eb-8c58-49d8644d5acc.png width=250/>

In RTL though this opens the menu on top of the action.

<img src=https://user-images.githubusercontent.com/44481292/111213912-84839c00-858e-11eb-80b2-e2a886fe20d6.png width=250/>

To work around it I have to switch to `alignment:start` for RTL.

It would be great if this could be handled similarly to `calcite-popover` with `leading-end` and `trailing-end`.
popover doesn't seem to have a solution for "bottom-end" either.

**Comment by driskull** [comment]
@macandcheese do we need alignment options for the dropdown? I'm wondering if we can just remove it and handle the positioning internally?

We don't offer positioning for combobox, input-date-picker either.

**Comment by driskull** [comment]
The other option is to automatically do the switch for users in RTL?

```tsx
const dir = getElementDir(this.el);

    if (alignment === "end") {
      return dir === "rtl" ? "bottom-start" : "bottom-end";
    }

    return dir === "rtl" ? "bottom-end" : "bottom-start";
```

**Comment by driskull** [comment]
Installed breaking change.

dropdown now has a placement property consistent with popover.

popover also gains additional options to handle RTL for start/end.

**Comment by AdelheidF** [comment]
Using `bottom-trailing` in this case places the dropdown above the action.

![image](https://user-images.githubusercontent.com/44481292/112066569-d6469c00-8b23-11eb-813a-35523bb2f10c.png)
![image](https://user-images.githubusercontent.com/44481292/112066600-e5c5e500-8b23-11eb-897e-76a481f93226.png)

If I change it to `bottom-start` it's fine. 

test case:
https://devext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0
Edit HTML dir attribute to "rtl"
Select layer, click Filter, click Add expression, open menu. You'll see the dropdown open to the bottom because it's using `bottom-start'. Now change it to `bottom-trailing` and open menu again.

**Comment by driskull** [comment]
I'm not seeing that:

![image](https://user-images.githubusercontent.com/1231455/112071562-44dc2780-8b2d-11eb-80c0-65d6187339ef.png)

**Comment by AdelheidF** [comment]
That is not really flipped for RTL. Not sure how you got into that state Did you flip to rtl before opening the filter panel?

It should look like this.
<img src=https://user-images.githubusercontent.com/44481292/112071837-dcda1100-8b2d-11eb-8ba0-6a4123c34764.png width=400/>

**Comment by driskull** [comment]
![image](https://user-images.githubusercontent.com/1231455/112072130-6b4e9280-8b2e-11eb-8be2-c7e60fea6f5c.png)

**Comment by AdelheidF** [comment]
You're using `bottom-leading`. I want `bottom-trailing`. Does this work for you?

I used `bottom-end` before, so I thought the corresponding universal version is `bottom-trailing`.
In LTR I want the bottom right corner of the action align with the top right corner of the dropdown.

**Comment by driskull** [comment]
hmm toggling rtl/ltr on that element doesn't seem to do anything. Are you sure it's using latest code?

Maybe try having RTL before page loads?

**Comment by driskull** [comment]
I think the issue might be because we're setting `dir=` on the host and some state is getting lost here. I'll need to investigate more.

**Comment by jcfranco** [comment]
@driskull Can this be verified or does it need a follow-up issue?

**Comment by driskull** [comment]
I think this was fixed. @AdelheidF ?

**Comment by AdelheidF** [comment]
Just tried it again with next.142 and it seems to work correctly now with `bottom-trailing`.
