### ISSUE TITLE
Enhancement: add valueAsDateTime support to time-picker components

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#1760]
### Description

Adds support for passing in a `Date` object for the value via the `valueAsDateTime` property.

#### Which Components

`calcite-input-time-picker`
`calcite-time-picker`

#### Requested by:

Future: Is there another type we could additionally support? Not sure if `Date` would work since it includes the non-time components.

_Originally posted by @jcfranco in https://github.com/Esri/calcite-components/pull/1736#discussion_r593322447_

**Comment by jcfranco** [comment]
Superseded by https://github.com/Esri/calcite-components/issues/4277.
