### ISSUE TITLE
Bug: calcite-radio-button forcing the panel to shift upward

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1775]
### Summary
I bit of a tricky repro, still looking into it, but when a radio button is selected it can cause the UI to shift with the right use case. In particular using it at the bottom of a calcite flow -> calcite-panel. See the codepen, selecting one of the radio buttons on a smallish screen will make it happen. It will only happen when there is a scroll bar present.

It seems like the input elements in the shadow root are not positioned correctly, and are too far down. The issue showed up at the beta.50 release. I think it may be something from this PR (https://github.com/Esri/calcite-components/pull/1551) , not exactly sure.

cc: @eriklharper 

### Reproduction Steps

https://codepen.io/eborgen/pen/rNWogjQ

**Comment by eriklharper** [comment]
Thanks for reporting this @ethanbdev !  I have a fix already to go :)

**Comment by ethanbdev** [comment]
> Thanks for reporting this @ethanbdev ! I have a fix already to go :)

Thank you for taking a look so quick!

**Comment by eriklharper** [comment]
My pleasure!  I had a hunch I knew what was causing it, and I was correct.  Gotta love one-liners!

**Comment by ethanbdev** [comment]
This looks good - I can't add labels but verified it

**Comment by eriklharper** [comment]
> This looks good - I can't add labels but verified it

Ah yes, we removed built-in label support as part of #2148 .   Same for checkbox: #2161.

Usage looks like this now for both radio and checkbox:

```
<calcite-label layout="inline">
  <calcite-radio-button></calcite-radio-button>
  Label
</calcite-label>

<calcite-label for="radio">Label</calcite-label>
<calcite-radio-button id="radio"></calcite-radio-button>
```

```
<calcite-label layout="inline">
  <calcite-checkbox></calcite-checkbox>
  Label
</calcite-label>

<calcite-label for="checkbox">Label</calcite-label>
<calcite-checkbox id="checkbox"></calcite-checkbox>
```

**Comment by ethanbdev** [comment]
> > This looks good - I can't add labels but verified it
> 
> Ah yes, we removed built-in label support as part of #2148 . Same for checkbox: #2161.
> 
> Supported usage looks like this now for both radio and checkbox:
> 
> ```
> <calcite-label layout="inline">
>   <calcite-radio-button></calcite-radio-button>
>   Label
> </calcite-label>
> 
> <calcite-label for="radio">Label</calcite-label>
> <calcite-radio-button id="radio"></calcite-radio-button>
> ```
> 
> ```
> <calcite-label layout="inline">
>   <calcite-checkbox></calcite-checkbox>
>   Label
> </calcite-label>
> 
> <calcite-label for="checkbox">Label</calcite-label>
> <calcite-checkbox id="checkbox"></calcite-checkbox>
> ```

Sorry, I mean I cannot add the "verified" label to the issue itself :)

**Comment by eriklharper** [comment]
😆 wrong label, lol!
