### ISSUE TITLE
Progress: Add dark theme

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#178]
match styles to Sketch library:

![image](https://user-images.githubusercontent.com/6144462/67031441-65958780-f0c6-11e9-9295-f53f70b90d79.png)

**Comment by macandcheese** [comment]
These feel a little chunky in height yeah? Dark mode looks good!

**Comment by bstifle** [comment]
they are 2 px @macandcheese  hahahaha

**Comment by macandcheese** [comment]
Ah just the scaling in GH I guess 🤷‍♂️

**Comment by julio8a** [comment]
#194
