### ISSUE TITLE
Enhancement: add actions-end and actions-start slots to calcite-accordion-item's header

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#1786]
### Description
Ability to add a button to the header of `calcite-acccordion`. There are props for title and subtitle, but no option to include any button or action in the accordion header. 

#### Which Component
calcite-accordion

#### Example Use Case
<img width="375" alt="Screen Shot 2021-03-17 at 7 26 13 PM" src="https://user-images.githubusercontent.com/55154968/111559842-e2fb7680-8756-11eb-8b8b-97113672be44.png">

**Comment by macandcheese** [comment]
Hey @joeyHarig - do you have a screenshot of a more macro view of that UI? 

Right now accordion items don’t really have facility for being dismissed or deleted (you can obviously just remove from DOM, but if the trash can in the screenshot above deletes the accordion item it is contained within, that may be a weird UI moment).

We have action slots in block and other components so there is precedent, but I would be worried about conflating the accordion component with some others if it becomes more of a sub-in for a line-item, if that makes sense!

**Comment by joeyHarig** [comment]
@macandcheese Thank you for taking a look at this. 

We are building a UI that allows users to configure notifications and subscribe to custom events. There could be several events and each event may have several expressions. We are using accordions to collapse the events the user isn't currently working on. 

The user needs to be able to delete events and it seems like a better use of space to place that action in the accordion title as opposed to inside the accordion body.


<img width="615" alt="Screen Shot 2021-03-30 at 12 07 13 PM" src="https://user-images.githubusercontent.com/55154968/113035549-90578c80-9150-11eb-814a-10122a1487c4.png">

**Comment by kellyhutchins** [comment]
On the instant app team we've run into a few cases where it would be nice to be able to add slotted content to the accordion item header. One use case is the Nearby app where we add the count of items inside the accordion to the header. Here's an example:

https://www.arcgis.com/apps/instant/nearby/index.html?find=Calle%2520Emilio%2520Carranza%2520Poniente%2520442%252C%2520Obrera%252C%2520Ju%25C3%25A1rez%252C%2520Chihuahua%252C%252032050&sliderDistance=1.2

**Comment by rslibed** [comment]
In the Instant Apps configuration experience, we use `calcite-accordion-item` to show/hide the `calcite-color-picker`. However, there isn't a simple way to display a color that is currently selected. 

![image](https://user-images.githubusercontent.com/29421380/123463792-d0d47400-d5a0-11eb-8697-c93c60f94e9e.png)

It would be great if there was a slot to pass in an element like `calcite-color-picker-swatch` to display the selected color. Another thing that can be useful is to pass in/specify an icon via slot or attribute.

**Comment by macandcheese** [comment]
Having the actions-end and actions-start slots that block does would be useful here.

**Comment by paulcpederson** [comment]
@benelan @macandcheese any chance we could get these actions-start/actions-end slots for accordion in an upcoming release? We have a design that calls for these coming up in Online soon.

**Comment by macandcheese** [comment]
@paulcpederson could you post a picture of design?

**Comment by macandcheese** [comment]
@paulcpederson - could you attach a screenshot of the design? Thanks.

**Comment by driskull** [comment]
Currently, clicking anywhere on the header will collapse/expand an accordion. I think this would need to be refactored so that the slotted actions wouldn't collapse/expand the accordion.

We want the click area to remain the same so the padding/margins would need to be refactored here...

![image](https://user-images.githubusercontent.com/1231455/169421569-e3b22ce5-b20a-4bb2-99c9-9ca2298b8913.png)

**Comment by driskull** [comment]
In actuality,  we may need to add 4 slots. `actions-start`,  `actions-end`,  `content-start` and `content-end`. That way, content can still be clickable to toggle the accordion whereas actions will not toggle the accordion. Is this correct? @macandcheese @jcfranco

**Comment by geospatialem** [comment]
Verified on beta.90
![verify-accordion-actions](https://user-images.githubusercontent.com/5023024/182233856-f2422b09-733b-48ea-8822-ed0e6f160cd5.gif)
