### ISSUE TITLE
multi-word attribute names should use dashes as separators

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#179]
I was looking at the attributes in different calcite-app-components and calcite-components and most of the multi-word names use a dash as the separator, like `filter-enabled`. But some of them don’t. E.g.:
 
iconposition:
https://github.com/Esri/calcite-components/tree/master/src/components/calcite-button
 
grouptitle:
https://github.com/Esri/calcite-components/tree/master/src/components/calcite-dropdown-group
 
linktitle:
https://github.com/Esri/calcite-components/tree/master/src/components/calcite-dropdown-item

This is not a complete list.

Do we want to change them all to use dashes?

**Comment by macandcheese** [comment]
Yeah, good catch. This is a result of how camelCase attributes are handled - these instances in Calcite Components should be updated to use camelCase vs. lower case (IMO) - in practice this lets attributes to be written as `filter-enabled`. This coincides with attribute naming convention issue: https://github.com/Esri/calcite-components/issues/36

**Comment by macandcheese** [comment]
Addressed in https://github.com/Esri/calcite-components/issues/179
