### ISSUE TITLE
First alpha release

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#18]
@paulcpederson @julio8a @macandcheese I would like to be able to present Calcite Components at the brown bag session in ~2 weeks. By then do you think we could cut an initial alpha release so I can start to integrate this into the ArcGIS for Developers and Vector Tile Style Editor. IT would be great to have:
  * `<calcite-tabs>` - can replace out current tabs in a few places on ArcGIS for Developers
  * `<calcite-alerts>` - can replace our current alerts in VTSE
  * `<calcite-modal>` - can replace our current modals in both ArcGIS for Developers and VTSE.
   * `<calcite-accordion>` - can replace out current accordion in a few places on ArcGIS for Developers

Would everyone be ok with me standing up some initial build tooling?

**Comment by macandcheese** [comment]
Closing this :)
