### ISSUE TITLE
Bug: calcite-input (number) has no locale support

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1810]
### Summary
In French e.g. the decimal separator needs to be a comma and date separator needs to be a dot. I can't find a way to make this happen. 

![image](https://user-images.githubusercontent.com/44481292/111825089-49da7600-88a4-11eb-934b-48ff4044925e.png)

<img src=https://user-images.githubusercontent.com/44481292/111824707-c751b680-88a3-11eb-9837-8f9e5ae44a8f.png width=200/>

Outside of those input boxes...
<img src=https://user-images.githubusercontent.com/44481292/111824582-a2f5da00-88a3-11eb-89b7-f52bbe24ab2f.png width=200/>

Also, where does that (English) text come from when I hover over the input? I'm not adding a step property and what it says is not true.

![image](https://user-images.githubusercontent.com/44481292/111826211-a5593380-88a5-11eb-89ff-2a7c2536651b.png)
![image](https://user-images.githubusercontent.com/44481292/111825502-c2d9cd80-88a4-11eb-97bf-97719e244b47.png)

cc @jcfranco @macandcheese 

### Reproduction Steps

1.

**Comment by ethanbdev** [comment]
You can set step to "any" to get rid of that hover tip @AdelheidF , if it is not set it defaults to 1.

**Comment by AdelheidF** [comment]
> You can set step to "any" 

Thanks, that works.

**Comment by AdelheidF** [comment]
What is the plan for a French UI that uses calcite-input with step:1 when the user enters a decimal value? I assume the message won't be translated.

**Comment by AdelheidF** [comment]
@paulcpederson @macandcheese is this doable for beta.52?

**Comment by paulcpederson** [comment]
@AdelheidF date picker can already do this. For example, try `fr-CH` as lang. Not sure why the `fr` locale doesn't use the dot separator, but would be easy to just remove fr and replace it with `fr-CH`. Maybe @raje9276 can comment on the distinction between these two regions.

**Comment by AdelheidF** [comment]
fr-CH is French spoken in Switzerland. 

de or es is not any better:

<img src=https://user-images.githubusercontent.com/44481292/112067995-40f8d700-8b26-11eb-811d-56ea982f33a0.png width=250/><img src=https://user-images.githubusercontent.com/44481292/112068063-6554b380-8b26-11eb-90a8-a10c6b15cca8.png width=250/>


> would be easy to just remove fr and replace it with fr-CH

Who would do this?

**Comment by paulcpederson** [comment]
`de` seems to render `.` correctly. Set locale to `de` on the storybook docs: https://esri.github.io/calcite-components/?path=/story/components-controls-inputdatepicker--simple

**Comment by AdelheidF** [comment]
Oh, I see now. 

![image](https://user-images.githubusercontent.com/44481292/112068809-e791a780-8b27-11eb-8f27-eb336cd1acc2.png)

It says it's using `document.documentElement.lang` which is set correctly to those languages in my case but it has no effect. If I pass in a `locale` prop then it works correctly, at least for the codes it supports.

**Comment by AdelheidF** [comment]
Never mind, fixing the date issue on my side.

**Comment by paulcpederson** [comment]
Playing around with the demo pages, setting lang on the html tag works. Wondering if this is a race condition or something? The lang must be set prior to the component being initialized or rendered in the DOM. This is a one-time lookup at initialization (it's not "live" and won't re-render the component if the lang changes later).

**Comment by eriklharper** [comment]
Looks like it should be easy to update the display number in the input with `Intl.NumberFormat`, but as far as restricting invalid characters based on locale, that would be a bit more involved, and would likely need to be tackled in maybe a second pass.  I'll update once I have more information.

**Comment by AdelheidF** [comment]
I'll close it once it's verified. Testing now with next.161

**Comment by AdelheidF** [comment]
It no longer shows the initial value that I set when creating the component. I can reproduce this with my Stencil and Maquette components. If I then hit up/down the value shows up.

**Comment by AdelheidF** [comment]
It's kind of nice that if I type 1 and then a bunch of 0s the thousand commas show up automatically. But this feature needs to be optional, because for some numbers a thousander comma doesn't make any sense, e.g. a year value. I don't see a property to hide it in the doc.

**Comment by ethanbdev** [comment]
> * [ ]  2. Also, if a value shows up or it's empty and I then change the value through another way, e.g. by picking a unique value or clicking on the histogram, the value that shows or doesn't show in the input doesn't change. This worked before so I'm pretty sure my component sets it correctly.

Seeing this one too. Have a case where the value of a number input can be "reset". After it is changed with user interaction -> changed programmatically to a different value -> it is not reflected in the input. If the user nudges the number, it uses the set value to base the increase off. It seems to just be visual, maybe the component not re-rendering properly?

Could be related, but also after the `calciteInputInput` event, the input changes visually but `fontSizeInputElement.value` has the old value. The event details looks right.

**Comment by eriklharper** [comment]
> * [ ]  3. It's kind of nice that if I type 1 and then a bunch of 0s the thousand commas show up automatically. But this feature needs to be optional, because for some numbers a thousander comma doesn't make any sense, e.g. a year value. I don't see a property to hide it in the doc. So it might be better to not do this for now and add it later.

Should be able to set `format-locale="false"` in the cases where you need to set something like a year.

**Comment by macandcheese** [comment]
Can we update that to be opt-in so we don't have a `"false"` ? Something like `enable-locale-formatting` ?

**Comment by eriklharper** [comment]
What do people think of these prop names?

1. `locale-format`
2. `format-locale`
3. `enable-locale-formatting`
4. `number-localized`
5. `localized`

**Comment by AdelheidF** [comment]
> What do people think of these prop names for opting into locale number formatting? 

Just to clarify. Number formatting should never be optional. With a French UI we always want to see a decimal comma. The part that should be optional is automatically displaying thousandth separators.

**Comment by eriklharper** [comment]
Sounds like we should just not automatically format the input as the user types, or are you saying there should be a way to opt-out of thousandth separators, but keep decimal separators, even when the user is not actively typing?

**Comment by eriklharper** [comment]
I noticed that some locales when using `Intl.NumberFormat.prototype.formatToParts` will omit the thousandth separator on a 4-digit number, but then include it when the number increases to 5 digits and beyond.

**Comment by AdelheidF** [comment]
> Sounds like we should just not automatically format the input as the user types, or are you saying there should be a way to opt-out of thousandth separators entirely while retaining decimal separators, even when the user is not actively typing?

Not automatically add thousandth separators as the user types. The user might still copy/paste a number with a thousandth separator, then just leave it there (or remove it if it's easier).

**Comment by AdelheidF** [comment]
Created separate issues 
1 . https://github.com/Esri/calcite-components/issues/1972
2 . https://github.com/Esri/calcite-components/issues/1982
4 . https://github.com/Esri/calcite-components/issues/1983

**Comment by AdelheidF** [comment]
If I set `localFormat` to `false` then I see dot decimals for a French UX, so I can't do that. On a side note: with `localeFormat` set to `false` all problems go away.

**Comment by AdelheidF** [comment]
`localFormat = false`, decimal sign is wrong
![image](https://user-images.githubusercontent.com/44481292/114801841-62c63200-9d51-11eb-991c-e6a7be68654a.png)

`localeFormat = true`, decimal sign is correct, but value doesn't update
![image](https://user-images.githubusercontent.com/44481292/114802106-f8fa5800-9d51-11eb-8980-46e29469b27b.png)

`localeFormat` should have no effect on the decimal sign of the input value. For French is needs to always be a comma.

**Comment by eriklharper** [comment]
> Can we update that to be opt-in so we don't have a `"false"` ? Something like `enable-locale-formatting` ?

Made this prop opt-in in #1969

**Comment by AdelheidF** [comment]
related issue about decimal and group separators https://github.com/Esri/calcite-components/issues/1988

**Comment by AdelheidF** [comment]
copy/paste issue: https://github.com/Esri/calcite-components/issues/1999

**Comment by AdelheidF** [comment]
This is installed and working. Very nice! 
We'll track little issues separately.

**Comment by paulcpederson** [comment]
🎉 🎉 🎉 🎉 🎉
