### ISSUE TITLE
Enhancement: Disable spinner and horizontal spinners for Read Only Inputs

### ISSUE THREAD

**Issue by rmstinson** [Esri/calcite-components#1813]
### Description
Current spinner inputs keep their spinner enabled when input is read-only. Proposing that we disable the spinner buttons along with the input field.
### Acceptance Criteria 
If those spinners are disabled, we got a stew goin'.
### Relevant Info 
NA
#### Which Component
Input
#### Example Use Case
![Read Only Disabled Spinners](https://user-images.githubusercontent.com/12650705/111851891-38a85e00-88d2-11eb-9238-83a71119c21f.png)

**Comment by macandcheese** [comment]
For input of type number, should we hide the number increment / decrement buttons (either in horizontal or vertical) altogether when in readonly?

**Comment by bstifle** [comment]
yeah that makes sense to just hide them if we can!!

**Comment by asangma** [comment]
@Elijbet Hopefully [this codepen](https://codepen.io/mtb-alan/pen/QWMYxMp) will help.

When the input is set to `read-only`, the increment buttons and input remain interact-able.

I believe @rmstinson is suggesting that `read-only` should respond to mouse and keyboard the same way as `disabled`.

@rmstinson I think we should also update the `disabled` appearance no?

**Comment by Elijbet** [comment]
@rmstinson If you could also provide styles suggestions for disabled vs read-only, that'd be awesome. Thanks!

**Comment by rmstinson** [comment]
So as far as the visual design goes, I'm proposing we follow this design, with the disabled inputs set to .5 opacity, following the disabled state of the calcite button's example.

In addition, we need to add the appropriate aria tag so that even is a component is disabled, screen readers & keyboard navigators will still be able to focus on the component and communicate the info and status of the component:

![Input_states](https://user-images.githubusercontent.com/12650705/142936782-48a54f1f-fd76-4af9-9ea2-19d93df259b8.png)

Link to the design doc: https://www.figma.com/file/eN2aaw0QPZCfLHA3lErhae/input_states?node-id=0%3A1

The application of the aria tag is pending further review, but the visual design should be pretty close to set if the team agrees.

**Comment by asangma** [comment]
@rmstinson @Elijbet If they're not already there, we may need to add an `intlDisabled` property to allow users to localize that string for that aria tag.

Mike, I'm assuming that that aria tag would default to "disabled"?

**Comment by rmstinson** [comment]
@asangma Yep, the string would default to "disabled," as long as it's preceded with some description of the component w/ the screenreader, ie, "input, Contact Name, disabled," like so: https://youtu.be/bUeqVNX3oLE?t=58

**Comment by driskull** [comment]
I think a disabled component shouldn't receive focus. https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

> The Boolean disabled attribute, when present, makes the element not mutable, focusable, or even submitted with the form. The user can neither edit nor focus on the control, nor its form control descendants.

@jcfranco do you think it would be helpful to add another step to the triage process to vet the issue and try to catch/edit some of the details of the issue before a dev is assigned? Otherwise, we have to rely on all devs to vet details like this. Just trying to improve efficiency.

**Comment by benelan** [comment]
verified on next
