### ISSUE TITLE
Bug: Incorrect font weight syntax. "Normal" should be "Regular"

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#1817]
```
   🦠 --calcite-font-weight-normal: 400; 🦠
```

should be

```
  ✨  --calcite-font-weight-regular: 400;✨
```

**Comment by caripizza** [comment]
Related: #2728

**Comment by julio8a** [comment]
Since this is not publicly documented, we can change this anytime and not wait for a big rename sprint.

**Comment by jcfranco** [comment]
@macandcheese Is this still valid? `normal` seems to be the norm... (badumtss 🥁: 😅 ). If so, do you agree [renaming this](https://github.com/Esri/calcite-components/blob/master/src/assets/styles/_type.scss#L20) is still a safe change or do we need to hold on to the previous one? It doesn't look like this is used by our components at the moment.

**Comment by macandcheese** [comment]
I think we can leave this as is (`normal`), unless @paulcpederson or @asangma have other thoughts.

`normal` is already the css value for 400 weight. `regular` is usually just used in the font names themselves.
