### ISSUE TITLE
Enhancement: improve calcite-action-bar overflow menu handling

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1819]
### Description
There was a new slot added to action-group for the overflow-menu.

```html
           <calcite-action-group>
                <calcite-action text="Save" icon="save" indicator>
                </calcite-action>
                <calcite-action text-enabled icon="map" text="New" slot="menu-actions">
                </calcite-action>
                <calcite-action text-enabled icon="collection" text="Open" slot="menu-actions">
                </calcite-action>
            </calcite-action-group>
```

But it requires the app to count all actions and groups in the action bar and guess their height to know how many actions need to be added to the slot in order to avoid scrollbars. Instead this logic should be handled by calcite, especially since it knows the height of action items and groups.

Maybe each action item in a group could have a property that indicates that this item could be moved into the overflow if there is not enough space for all. E.g. bottom most action item with that property goes first into the overflow list. If there are several groups with those action items, it could start with the bottom most group first.
Or just the group has a new property and it would automatically move action items into the overflow starting with the bottom one. 

Adding Alan here since I'm not clear what the expected order of things moving into the overflow should be, especially since the left action bar in map viewer beta has 4 groups.

https://github.com/Esri/calcite-components/pull/1510
https://github.com/Esri/calcite-components/issues/1466

cc @asangma

**Comment by asangma** [comment]
This seems like it could be a generalized utility or something like that.

**OverflowManager**
* wraps the main list of things
* has a limit property : [ n | "auto" ]*

**OverflowContainer**
* container that receives the overflowing items
* maybe this is a wrapper for Popover?
* probably also needs to be able to insert items into a nested component
  *  e.g. if Actions need to get added to an ActionGroup inside of the OverflowContainer


Maybe it's something like this?
```
<calcite-overflow-manager limit="auto" overflow-target="overflow-thing">
  <calcite-action-group>
    <calcite-action text="cool"></calcite-action>
    <calcite-action text="cool"></calcite-action>
    <calcite-action text="cool"></calcite-action>
    <calcite-action text="cool" overflow-me></calcite-action>
    <calcite-action text="cool" overflow-me></calcite-action>
  </calcite-action-group>
</calcite-overflow-manager>
```

Elsewhere

```
<calcite-overflow-container id="overflow-thing" target-child="target-list">
  <calcite-action-group id="target-list">
  </calcite-action-group>
</calcite-overflow-container>
```

*Not really sure how "auto" would work.

**Comment by driskull** [comment]
I have a PR that will use resizeObserver to handle this dynamic slotting scenario. It needs some more logic to it though.

**Comment by driskull** [comment]
Installed.

**Comment by AdelheidF** [comment]
cc @kevindoshier

**Comment by kevindoshier** [comment]
It works but there needs to be either an option or have the default behaviour to hide the popover once the action within the popover is clicked, otherwise its 2 clicks to open something, one to active the action, and another to close the overflow menu.

Also in the app we use the popover with the pointer when we show popover menus off of the actionBar, this one does not use that and doesnt look consistent so either we need to change the app, or have an option here to use the pointer

![image](https://user-images.githubusercontent.com/11093161/113325615-8909bd80-92cd-11eb-9f2a-7aad10ef5d7d.png)

![image](https://user-images.githubusercontent.com/11093161/113325720-a63e8c00-92cd-11eb-8d46-7849faa4a0da.png)

**Comment by driskull** [comment]
> It works but there needs to be either an option or have the default behaviour to hide the popover once the action within the popover is clicked, otherwise its 2 clicks to open something, one to active the action, and another to close the overflow menu.

@kevindoshier the `calcite-action-group` has a `menuOpen` property which you can set to false to close any open menus on action click.

We can create an event on `calcite-action` like `calciteActionClick` that you could listen on the action-bar? Would that help to know if one is clicked?

> Also in the app we use the popover with the pointer when we show popover menus off of the actionBar, this one does not use that and doesnt look consistent so either we need to change the app, or have an option here to use the pointer

I'll add the pointer arrow for this thanks.

---

@kevindoshier can you open an issue for @asangma and @caripizza to address the styling part? I know that the popover added rounded corners but maybe that was a bad call since the action buttons are not rounded.

**Comment by driskull** [comment]
> Also in the app we use the popover with the pointer when we show popover menus off of the actionBar, this one does not use that and doesnt look consistent so either we need to change the app, or have an option here to use the pointer

@asangma @julio8a When should the popover have a pointer? It seems with `calcite-panel`, we don't use a pointer right now and I'd like this to be consistent. For the action menu, should we always have a pointer?

Is this ok? 

![image](https://user-images.githubusercontent.com/1231455/113329634-a9884680-92d2-11eb-9069-3a66bc536acc.png)

**Comment by kevindoshier** [comment]
> @kevindoshier the calcite-action-group has a menuOpen property which you can set to false to close any open menus on action click.

This will be perfect, but I tried it and setting menuOpen to false on the action-group didnt hide the menu, im doing something like this

`const groups = container.querySelectorAll("calcite-action-group");
            groups.forEach(function (element) { return element.menuOpen = false; });
        };
`

**Comment by kevindoshier** [comment]
One other thing I noticed is the menus only get put into the overflow actions if the page is resized, if the page starts off at a height where they should be in the overflow I have to resize the page to trigger it,  is there something the app should do to just resize after the page loads?

**Comment by driskull** [comment]
> One other thing I noticed is the menus only get put into the overflow actions if the page is resized, if the page starts off at a height where they should be in the overflow I have to resize the page to trigger it, is there something the app should do to just resize after the page loads?

@kevindoshier do you have an app I could look at?

**Comment by kevindoshier** [comment]
Its non-minified, will take a bit to load

http://kdoshier.esri.com/mapviewer/dist/index.html

**Comment by driskull** [comment]
Thanks for sharing @kevindoshier. I see the issues. 👍

**Comment by kevindoshier** [comment]
This is an awesome improvement,  I really like that its all just automatic, will be very helpful for any clients using this

**Comment by driskull** [comment]
Yeah, using the `resizeObserver` makes it possible. You should look into using the resizeObserver anywhere you need to know where the width or height of something changes. Such as panel widths,etc.

**Comment by driskull** [comment]
@kevindoshier I think all those issues have been addressed. Can you test with the latest `next` version once it's deployed?

**Comment by kevindoshier** [comment]
@driskull - Awesome!  Thanks, I will test as soon as the `next` version is available

**Comment by kevindoshier** [comment]
@driskull - looks good!  The only issue I see remaining is initally at load time the actions arent put into the overflow until I resize the window, everything else looks great though

**Comment by driskull** [comment]
Cool. I'll get that fixed.

**Comment by driskull** [comment]
@kevindoshier I'm going to close this one out. If it's still broken after 'next.143' release then we can create another issue.

**Comment by kevindoshier** [comment]
Sounds good, thanks!
