### ISSUE TITLE
calcite-popover : offset is reversed if placement is vertical

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#182]
If I use a calcite-popover with `placement="vertical"` then `xOffset` modifies really the y placement and `yOffset` modifies the x placement.

Also, it would be nice if negative offset values would work. It currently seems to have an issue when displaying the popover above the reference element in that case. I would like the popover to overlap the reference element.

**Comment by driskull** [comment]
According to the [Popper doc](https://popper.js.org/popper-documentation.html#modifiers..offset) it is flipped depending on whether or not it is horizontal or vertical.

> For length is intended the main axis relative to the placement of the popper.
This means that if the placement is top or bottom, the length will be the width. In case of left or right, it will be the height.

So we would have to flip them internally or we can change to accept a single string like the documentation accepts. example: `10px, 10px` and then we don't have to flip them but would need to document the same information that Popper does.

@AdelheidF @julio8a do you have a preference?

**Comment by driskull** [comment]
Another option is to just take a single value for offset and it will apply to either length or height depending on the position.

**Comment by AdelheidF** [comment]
> Another option is to just take a single value for offset and it will apply to either length or height depending on the position.

That won't work. I currently use both at the same time in the FeatureFilter actionPad popover.

> do you have a preference?

Either way will work for me, but I lean towards two properties in case you have to modify one after creation.

**Comment by julio8a** [comment]
I'm good with either.

**Comment by driskull** [comment]
Installed.

**Comment by AdelheidF** [comment]
Looks good.
