### ISSUE TITLE
Bug: calcite-shell-center-row cut off at top if height-scale is large

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1821]
### Summary
The center shell panel at full height is being cut off at the top.

![image](https://user-images.githubusercontent.com/44481292/112055052-9b3c6c80-8b13-11eb-8f44-20404f6f08af.png)

### Reproduction Steps

1.

**Comment by asangma** [comment]
Installed.

**Comment by AdelheidF** [comment]
verified with next.127

![image](https://user-images.githubusercontent.com/44481292/112394214-944f5e80-8cb9-11eb-880f-c46b8638c99e.png)
