### ISSUE TITLE
Bug: calcite-fab with native hover text

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1842]
### Summary

calcite-fab displays the native style hover text. Is this purpose?

<img src=https://user-images.githubusercontent.com/44481292/112399456-78e95100-8cc3-11eb-950b-72741729814f.png width=550/>

Also, this is from the doc:
<img src=https://user-images.githubusercontent.com/44481292/112399364-51928400-8cc3-11eb-9932-68d9269cda62.png width=550/>

But if I don’t provide a label and my text is “Add expression” I see this:
<img src=https://user-images.githubusercontent.com/44481292/112399305-3fb0e100-8cc3-11eb-895a-720a71e62eaa.png width=250/>

### Reproduction Steps

1.

**Comment by driskull** [comment]
We also have these:

9 results - 9 files

src/components/calcite-block/calcite-block.tsx:
  173              onClick={this.onHeaderClick}
  174:             title={toggleLabel}
  175            >

src/components/calcite-block-section/calcite-block-section.tsx:
  121            tabIndex={0}
  122:           title={toggleLabel}
  123          >

src/components/calcite-card/calcite-card.tsx:
  147          onKeyDown={this.cardSelectKeyDown}
  148:         title={checkboxLabel}
  149        >

src/components/calcite-color-picker-swatch/calcite-color-picker-swatch.tsx:
  81      return (
  82:       <Host aria-label={hex} title={hex}>
  83          <svg class={CSS.swatch} xmlns="http://www.w3.org/2000/svg">

src/components/calcite-dropdown-group/calcite-dropdown-group.tsx:
  106      return (
  107:       <Host dir={dir} role="menu" scale={scale} title={this.groupTitle}>
  108          {dropdownSeparator}

src/components/calcite-fab/calcite-fab.tsx:
  130            theme={theme}
  131:           title={title}
  132            width="auto"

src/components/calcite-handle/calcite-handle.tsx:
  102          tabindex="0"
  103:         title={this.textTitle}
  104        >

src/components/calcite-modal/calcite-modal.tsx:
  159          ref={(el) => (this.closeButtonEl = el)}
  160:         title={this.intlClose}
  161        >

src/components/calcite-popover/calcite-popover.tsx:
  353          ref={(closeButtonEl) => (this.closeButtonEl = closeButtonEl)}
  354:         title={intlClose}
  355        >

**Comment by driskull** [comment]
> calcite-fab displays the native style hover text. Is this purpose?

This is on purpose for now. We may opt to change it to the `calcite-tooltip` at some point.

> But if I don’t provide a label and my text is “Add expression” I see this:

I'll get that fixed.

In the future, we can decide which components we should change `title` attributes to be `calcite-tooltip`.

**Comment by AdelheidF** [comment]
sorry never mind....

**Comment by AdelheidF** [comment]
Tested this now with next.134.

I have textEnabled=true, text="Add expression", and no label.

Now I see nothing on hover. This is fine with me, but now the doc doesn't fit anymore.

**Comment by driskull** [comment]
It will only show the native tooltip when not textEnabled. We can update the doc for that.

**Comment by driskull** [comment]
https://github.com/Esri/calcite-components/pull/1875
