### ISSUE TITLE
Enhancement: calcite-popover-manager not working through shadow dom

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1844]
### Description

I tried this (1)
![image](https://user-images.githubusercontent.com/44481292/112526777-8ce29080-8d5f-11eb-9188-3c9bca74061e.png)

and this (2)
![image](https://user-images.githubusercontent.com/44481292/112526896-af74a980-8d5f-11eb-93e4-3755832b31fe.png)

and around the action that opens the popover (3)
![image](https://user-images.githubusercontent.com/44481292/112528795-ccaa7780-8d61-11eb-9cb7-0593c334bc07.png)

and neither version closes the popover if I click outside.

**Comment by driskull** [comment]
The problem is querying all the popovers that need to be closed. If they cross shadow DOM boundaries I cant query them to close them. So a popover manager needs to be in each shadow DOM that exists for it to work.

**Comment by driskull** [comment]
Sorry adelheid :(
