### ISSUE TITLE
Bug: Date picker:  Range, end date selected hover style

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#1845]
### Summary
When hovering over the active range end date there is a gray bg that should not show up.
![image](https://user-images.githubusercontent.com/6144462/112526985-c87d5a80-8d5f-11eb-86c8-9cd4f8c1cbd5.png)

### Actual Behavior
No gray background behind the selected date hover.

### Expected Behavior
No gray background when hovering over end date selected range 

### Reproduction Steps
Hover over range end date selection.

**Comment by bstifle** [comment]
this seems to have been resolved. @julio8a  can you verify on master?

**Comment by julio8a** [comment]
Verified on master. closing.
