### ISSUE TITLE
Expose a CSS var for Panel a base width.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1849]
### Question
Currently the CSS vars for Panel widths are defined in the shadow.
It could be useful to users to be able to adjust these for their purposes.

I propose we expose these and allow users to overwrite them.
It would probably mean having a var for each width-scale.

Currently it looks like this inside of Panel
```
:host([width-scale="s"]) {
  --calcite-panel-width: 12vw;
  --calcite-panel-max-width: 300px;
  --calcite-panel-min-width: 150px;
}

:host([width-scale="m"]) {
  --calcite-panel-width: 20vw;
  --calcite-panel-max-width: 420px;
  --calcite-panel-min-width: 240px;
}

:host([width-scale="l"]) {
  --calcite-panel-width: 45vw;
  --calcite-panel-max-width: 680px;
  --calcite-panel-min-width: 340px;
}
```

We will offer a base panel-width var at the global level.

```
:root {
  --calcite-panel-width-base: 12vw;
}
```

Existing vars in Panel (width-scale width, max-width, and min-width) for each scale will be be calculated (`calc`) based on that base var to produce the same value that are currently being used.

**Comment by asangma** [comment]
cc @kevindoshier

**Comment by macandcheese** [comment]
I've run up to this frequently recently. 

I'd also encourage allowing override of `flex-direction` in some way for the `.main` div in the shadow root of `calcite-shell`.

Allowing this to be user-configured would mean that I can stack my panels for certain screen sizes as I need to. Currently I need to access that `.main` div via JS and manually change that `flex-direction` property:

![Screen Shot 2021-03-26 at 11 34 31 AM](https://user-images.githubusercontent.com/4733155/112677831-6f78f980-8e27-11eb-94af-dbc4c765352d.png)
![Screen Shot 2021-03-26 at 11 34 20 AM](https://user-images.githubusercontent.com/4733155/112677835-70119000-8e27-11eb-9eb3-1eb9f4e486dd.png)


Combined with setting 100% width for `shell-panel` and `panel`, this allows me to "fake" mobile pretty well, but allowing it as in the example you provide would be way better.

**Comment by asangma** [comment]
@macandcheese I could see that.

I would suggest utilizing our Layout interface and call the property `layout`.

That being said, I think with your mobile stuff, there's the additional complexity of `content-behind` in Shell.

**Comment by driskull** [comment]
I'm ok with exposing them. Maybe we don't document them for a while though incase we need to refactor them?

**Comment by asangma** [comment]
@driskull That makes sense to me. That says to me that we should leave this out of the Tailwind config for now too.

**Comment by driskull** [comment]
My only concern about this is that by exposing this, we are intentionally allowing inconsistencies between our apps. There should be a good reason for it :)

**Comment by macandcheese** [comment]
> I would suggest utilizing our Layout interface and call the property `layout`.

I was thinking it could just be a css var to not clutter with a prop, and avoid doccing it unless needed: `--calcite-shell-flex-direction`. Not sure about content-behind but just changing the flex direction works for my few use cases that don't use content-behind. So that might just not be applicable for those types of layouts. Simple stacking works like this though.

**Comment by asangma** [comment]
@macandcheese Sounds like we need a new issue. :)

**Comment by asangma** [comment]
@driskull I see your concern. In this case, it's the sizing of the panel which I think can vary between apps without negatively affecting the cross-app experience.

I am also thinking that selecting the perfect panel sizes for all apps is a hard ask, so adding in some flexibility might be nice.

A middle ground would be to only expose a single CSS var that the other width-scale values would be based on.
I'd have to do some math to calculate max and min px sizes from a `vw`, but it's doable.

**Comment by CodeBarker** [comment]
If we are worried about consistency I think we could solve the preplanned issue slightly differently too.

Preplanned only has the left panel
![image](https://user-images.githubusercontent.com/3944714/112835618-8312a300-9067-11eb-9945-238bae714d79.png) 

I think an equally valid option to consider is that if there is no right actionbar/panel in the app that the left panel doesnt scale width down as quickly

Either works for solving the preplanned app concern from our stand point.

**Comment by asangma** [comment]
Thanks @CodeBarker!

@driskull I think I will take a whack at exposing a base panel width CSS variable that will set the `s` size. `m` and `l` will be calculated off of that.

I can make the current values stay approximately the same.
