### ISSUE TITLE
Bug: Cannot type in `color-picker` hex input in Firefox

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1852]
### Summary
Cannot type in the hex input in the color picker component if the user highlights the text and types, and if the user backspaces then types, it works.

Happens in Firefox, not chrome, have not tested other browsers.

### Reproduction Steps
**update**
1. Highlight all of the text in the hex input, then try to type
2. Typing will not input any values, you have to use the backspace and enter.

https://codepen.io/eborgen/pen/OJRmmPO?editors=1000

### Relevant Info 
Firefox 78.9.0esr (64-bit)

**Comment by bstifle** [comment]
getting the same bugs in Brave

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
@ethanbdev could you help verify this w/ `@next`? Thanks! 🙇🏼‍♂️

**Comment by ethanbdev** [comment]
Looks good, thanks @jcfranco for the quick fix 👏
