### ISSUE TITLE
Bug: native change event target value is not reset on calcite-input clear button click until clear button is released 

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#1856]
### Summary

`calcite-input` clear button click can be captured via `change` event and checking event target value for empty string. The component clears and event fires immediately on clicking the clear button, however the event target value does not change until the user releases the clear button and the input refocuses. Initially suspected a race condition, but upon further testing determined the timeout had to be longer than the clear button was focused/active to properly evaluate the target's value.

The `calciteInputInput` event does not have this behavior, and its event target value is the expected empty string.

### Actual Behavior

As stated.

### Expected Behavior

Native `change` event target's value should be an empty string when clicking the clear button.

### Relevant Info 

Browser (chrome and edge) same behavior.

**Comment by COV-GIS** [comment]
Here's an pen: https://codepen.io/COV-GIS/pen/dyzpMbL

I was converting tsx widgets from html to calcite and in the case of calcite input `oninput` was not capturing the clear button click. `onchange` does but as per this issue the value returned was value before clear.

This is technically an issue, however wiring up two events is the incorrect pattern since `calciteInputInput` works including when clearing. I'd be inclined to close this. But I'll leave that to you in case you're working on this.

As for documentation I was suggesting a page maybe under Foundations explaining custom events and that they should be used for their purpose over native events when they exist. Actually a section in FAQ would probably be more appropriate and sufficient.

**Comment by jcfranco** [comment]
This should be fixed via https://github.com/Esri/calcite-components/issues/3474 in the next release: https://codepen.io/jcfranco/pen/VwzRdwB

Note that when the text is cleared, it will be `null` vs `""`. This will be addressed by https://github.com/Esri/calcite-components/issues/3381.

**Comment by benelan** [comment]
verified on `next`
