### ISSUE TITLE
Tab UI disappears when used with text content

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#186]
I've been working on some UI mockups inside Sketch and I've noticed that the tab component UI tends to disappear when used inline with text content for example a tabbed code block.

This screenshot is from the Sketch components but in a real implementation it is worse since the tab UI is the same size (and color) as the text leading to it getting lost.

![image](https://user-images.githubusercontent.com/378557/67303230-fee9e280-f4a6-11e9-9afc-be1e89e6762c.png)

In the old tabs UI I think it was pretty clear that these are interactive elements:

![image](https://user-images.githubusercontent.com/378557/67308925-dca89280-f4af-11e9-98c3-632691277550.png)

**Comment by macandcheese** [comment]
Agreed - I think we can add an "appearance" variant, I also think we need a slightly stronger hover state in general, we can look at that too cc @bstifle

**Comment by bstifle** [comment]
@macandcheese  do you think adding a "contained" traditional tab style would be a good prop?
