### ISSUE TITLE
Unstable Test:  FAIL src/components/calcite-combobox/calcite-combobox.e2e.ts (74.343 s)

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1876]
## Summary

This test seems unstable. Fails every once and a while.

**Which component?:**

calcite-combobox

**Which test(s)?:** 

FAIL src/components/calcite-combobox/calcite-combobox.e2e.ts (74.343 s)

**Test error:**

FAIL src/components/calcite-combobox/calcite-combobox.e2e.ts (74.343 s)
  ● calcite-combobox › should filter the items in listbox when typing into the input
    expected event "calciteComboboxFilterChange" to have been called 1 times, but was called 2 times
      57 |     expect(item1Visible).toBe(true);
      58 |     expect(item2Visible).toBe(false);
    > 59 |     expect(eventSpy).toHaveReceivedEventTimes(1);
         |                      ^
      60 |     expect(await eventSpy.lastEvent.detail.visibleItems.length).toBe(1);
      61 |     expect(await eventSpy.lastEvent.detail.text).toBe("one");
      62 |   });
      at Object.<anonymous> (src/components/calcite-combobox/calcite-combobox.e2e.ts:59:22)
          at runMicrotasks (<anonymous>)

**PR that skipped the test:** #1877

**Comment by jcfranco** [comment]
@driskull can you assign someone to this, so we don't lose track of it?

**Comment by jcfranco** [comment]
Closing as self-verified based on latest successful Travis builds. cc @benelan
