### ISSUE TITLE
calcite-date-picker not working with Maquette

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#188]
I’m trying to use calcite-date-picker in the FeatureFilter component, but I can’t get it to work. This is how it looks like when I click on it. The calcite-date-month shadow-root stays empty.
It’s using Maquette.
 
<img src=https://user-images.githubusercontent.com/44481292/67364501-86c20200-f524-11e9-94ce-ba67c5ac73f5.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/67364498-832e7b00-f524-11e9-90f3-b8e15f9d5907.png width=400/>

I re-installed everything in case there is a version mix up and then tried it again.
At that point the date-picker opened. But when I tried it again a few times it didn’t open. So it’s definitely something related to timing.

When it didn’t open I got these errors:
 
<img src=https://user-images.githubusercontent.com/44481292/67364581-afe29280-f524-11e9-96ad-7a34aefa0a35.png width=350/>

<img src=https://user-images.githubusercontent.com/44481292/67364586-b244ec80-f524-11e9-8ca3-7ab69ed74990.png width=300/>

I tried with and without min/max properties, but I got the same result.
According to the demo page my date string of “09/13/2000” should be correct.

```
<calcite-date-picker 
class="component-condition__date-picker hydrated" 
next-month-label="Next month" 
prev-month-mabel="Previous month" 
start-of-week="0" 
locale="en-US" 
tabindex="0" 
aria-label="Value" 
role="application" 
value="09/13/2000" 
min="" 
max="" 
expanded=""
>
</calcite-date-picker>
```
Or with 
```
min="01/01/1970" 
max="12/31/2030" 
```
Once the calcite picker is on the panel I do re-create it whenever the user changes the operator on the filter. In that case I get it working. See below.

There is also a styling issue. I need to shrink down the component to 200px wide when the right panel in the map viewer is at its smallest. In that case the bottom part of the component doesn’t shrink with its top.

<img src=https://user-images.githubusercontent.com/44481292/67364526-92adc400-f524-11e9-8e59-357c5176a21a.png width=200/><img src=https://user-images.githubusercontent.com/44481292/67364572-a9ecb180-f524-11e9-80ad-b78e4f81ee12.png width=220/>

**Comment by macandcheese** [comment]
Thanks for report - assigning to @kumarGayu as original author

**Comment by AdelheidF** [comment]
Kumar is out until Nov 11. Is there someone else who could look at this?

**Comment by AdelheidF** [comment]
test app with repro case:

https://devtopia.esri.com/WebGIS/arcgis-components/tree/adel2697/date-picker

Under /test-apps/FeatureFilter/index.html is the test app. 
Click 'Filter layer' and then choose a date field.

This is a layer with date fields (pick field DAY):
../test-apps/FeatureFilter/index.html?url=https://sampleserver6.arcgisonline.com/arcgis/rest/services/Hurricanes/MapServer/0

**Comment by macandcheese** [comment]
Was this resolved in https://github.com/Esri/calcite-components/pull/257?

**Comment by AdelheidF** [comment]
I tried it again with 1.0.0-beta.15.

The calendar now opens, it is very large and the date numbers don't align with the days of the week if I make it fit in the panel with `width: 100%;`. This also causes the horizontal scroll bars.
Would be nice if there was an option to have a smaller version with less padding around the numbers.

![image](https://user-images.githubusercontent.com/44481292/71195574-0decd700-2243-11ea-8300-c3de0b38f3ca.png)

Look on a large screen and look on a Windows Surface screen (I pretty much always need to scroll to see the full calendar):
<img src=https://user-images.githubusercontent.com/44481292/71195389-af275d80-2242-11ea-98be-3cdc077ee843.png width=250/><img src=https://user-images.githubusercontent.com/44481292/71195482-dc740b80-2242-11ea-8e04-cf0e2288f401.png width=250/>

I'm a bit confused about the name. When I use `<calcite-date-picker>` it works fine, but when I look at the doc it says `<calcite-date>`,  but that doesn't work. https://github.com/Esri/calcite-components/blob/master/src/components/calcite-date/readme.md

**Comment by mitc7862** [comment]
@AdelheidF I think the calendar component will need to be opened in a popover or floating panel. I suspect the alignment issues are due to the narrow width.

**Comment by AdelheidF** [comment]
@mitc7862 not sure how to add the calendar to a popover and leave the selected date in the panel to be clicked on. It seems to be one piece right now.
If I make the selected date a simple action that opens a popover the popover will initally just display that one line with the selected date, no calendar. The calendar only opens when you click on that selected date.

![image](https://user-images.githubusercontent.com/44481292/71208536-08e95100-225e-11ea-8c3a-c4a25a3d01dd.png)

**Comment by mitc7862** [comment]
@macandcheese I think this may be a use case where we need the calendar and the date to be separate pieces. ☝️

**Comment by macandcheese** [comment]
Yep! I think that is the intention - currently we just don't have a `calcite-input` component of `type=date` to leverage for that (open PR - wip). 

Once we have that added I would imagine we want to break the two apart - allowing the calendar to be placed "on page" independent of an input - with no shadow or, wrapped in a calcite-accordion, calcite-popover, etc.

**Comment by kumarGayu** [comment]
Added the correction. and is available with latest release.

**Comment by AdelheidF** [comment]
Is it part of 1.0.0-beta.16? This seems to be the latest release.

**Comment by julio8a** [comment]
Closing this out. re-open if needed.

**Comment by AdelheidF** [comment]
Did someone verify it?

**Comment by AdelheidF** [comment]
Not working. Using 1.0.0-beta.17.

![image](https://user-images.githubusercontent.com/44481292/73210357-f38a0100-40fe-11ea-9fb4-79d334605151.png)

Would it be possible that someone other than me could verify this, because I have to wait for another release to test it again.

**Comment by macandcheese** [comment]
@AdelheidF - is this happening exclusively with Maquette? If the original issue with Maquette throwing errors was resolved, and this is separate issue about incorrect display of dates in narrow containers, can we open as a separate issue?

Just want to make sure @kumarGayu or whoever picks it up knows what the current issue is. Thanks!

**Comment by AdelheidF** [comment]
new issue: https://github.com/Esri/calcite-components/issues/308

**Comment by macandcheese** [comment]
Thanks @AdelheidF ! Closing this one.
