### ISSUE TITLE
Enhancement: 

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#1888]
### Description
@kevindoshier can you open an issue for @asangma and @caripizza to address the styling part? I know that the popover added rounded corners but maybe that was a bad call since the action buttons are not rounded.

![action_bar](https://user-images.githubusercontent.com/11093161/113328868-b193b680-92d1-11eb-9c53-923393882c5e.png)

![rounded_cornders](https://user-images.githubusercontent.com/11093161/113328876-b3f61080-92d1-11eb-8f9d-0e35940e7067.png)

cc: @driskull

**Comment by driskull** [comment]
Being addressed during ongoing refactoring
