### ISSUE TITLE
calcite-action-menu: when opening menu set focus on first action

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1896]
### Summary
If the popover opens the focus is not inside the popover. 

### Reproduction Steps

1.

**Comment by AdelheidF** [comment]
Tested locally with next.142.

It now sets the focus on the first action in the menu after opening the menu, but when using the up and down arrows the focus doesn't move, unlike calcite-dropdown. Also, hitting space doesn't execute the action. As a keyboard only user it's impossible to select the focused action or move down to another one.

**Comment by driskull** [comment]
Ah, forgot this was using activedescendent. This will need some more work then 👍

**Comment by AdelheidF** [comment]
Using next.146...

When I open the menu I now can move up and down using the arrow keys and hitting enter/space selects the grey action. But when I open the menu I no longer see the typical blue focus box.

![image](https://user-images.githubusercontent.com/44481292/113637844-6ad3f280-962a-11eb-961b-bd78d07f1441.png)

**Comment by driskull** [comment]
@AdelheidF yes that's by design. It's using `activedescendant` so that the button doesn't lose focus.

https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-actions-active-descendant.html
