### ISSUE TITLE
calcite-popover placement issues when popover is too high

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#190]
If I place a calcite-popover with “bottom” but it ends up being too high to fit properly I end up with something like below (popover has Add button). My reference element is the 'Visualization attributes' text.

This can happen with smaller devices. It won’t happen anymore in my component because I’m calculating the height of the popover dynamically based on the height of the app, but I’m sure other people will run into it.

I understand that the component is trying to find the best spot, but that one is definitely not it. I rather have it placed at the bottom being cut off.

Incorrect placement
<img src=https://user-images.githubusercontent.com/44481292/67440868-8884d780-f5af-11e9-85c4-96e82980d4e9.png width=200/>

Correct placement:
<img src=https://user-images.githubusercontent.com/44481292/67440855-71de8080-f5af-11e9-99e1-6c2fac4021e3.png width=200/>

```
<calcite-popover 
id="gallery-popover" 
open="" 
role="dialog" 
aria-hidden="false" 
placement="bottom" 
theme="light" 
x-offset="0" 
y-offset="5" 
class="hydrated" 
x-placement="bottom" 
style="position: absolute; transform: translate3d(577px, 73px, 0px); top: 0px; left: 0px; will-change: transform;">...</calcite-popover>
```

Side note, the look of the triangle in the incorrect placement is weird.

**Comment by driskull** [comment]
The recent fixes I checked in for popover may fix this. The only thing I can think of is to be able to disable the "flip" feature on occasion if you don't want it to figure out where to go.

**Comment by AdelheidF** [comment]
Here is another case. The placement is "bottom" and the popover doesn't fit, but there is more space below the referenceElement than above. But it still shows "top".

<img src=https://user-images.githubusercontent.com/44481292/67626971-836e9500-f808-11e9-875e-dd8a1332ce56.png width=200/>

**Comment by driskull** [comment]
Added a property to disable flipping the popover.

**Comment by macandcheese** [comment]
released 🚀

**Comment by AdelheidF** [comment]
If I use the new `disableFlip` property the dropdown _always_ opens to where I set it, e.g bottom, even if there is plenty of space above it. This is not working for my case below. 
Without making calculations I won't know if I need the popover above or below the reference element.

I need a 'dropdown' for the 'Natural Breaks' box in the UI. The box can be near the top or the bottom of the panel, depending on the panel's scroll state.

closed state&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;box is near the top of the panel
<img src=https://user-images.githubusercontent.com/44481292/68051832-97514580-fca5-11e9-9fbf-34d537121bc0.png width=200/><img src=https://user-images.githubusercontent.com/44481292/68051187-1180ca80-fca4-11e9-94dc-ae19a8faa7aa.png width=230/>


box is near the bottom of the panel&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;box is in the middle, but farther towards the top, of the panel 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(I use bottom without displableFlip here)
<img src=https://user-images.githubusercontent.com/44481292/68051250-36753d80-fca4-11e9-8bec-b03af25acce3.png width=220/><img src=https://user-images.githubusercontent.com/44481292/68051314-5c9add80-fca4-11e9-9107-4dd7dc977759.png width=220/>


I do not set a height for the popover or the content of the popover. Could it get scroll bars if it doesn't fit vertically?

I assume I will need to figure out where the box is placed on the page and if there is more space above or below it. Then I need to calculate the max-height that I need to set. I'm not sure yet though how I get the height of the popover before it displays to make these calculations. The height of the popover depends on the width of the popover and that depends on the width of the shell-panel.

cc @asangma

**Comment by driskull** [comment]
> Without making calculations I won't know if I need the popover above or below the reference element.

I think you need to use "auto" in this case. That's when it will figure out where to put the popup.

> I do not set a height for the popover or the content of the popover. Could it get scroll bars if it doesn't fit vertically?

You can add scrollbars to the content inside it. We don't have any heights set for the popover so a user can define them.

---

It seems like you are using the Popover for a `<select>` menu use case which it wasn't designed for. I'm not sure this is the correct use case. A native select menu or a calcite dropdown may be more appropriate here. It seems like this should be a form element and not a popover. @asangma ???

**Comment by AdelheidF** [comment]
> You can add scrollbars to the content inside it. We don't have any heights set for the popover so a user can define them.

Tried that, they don't seem to make a difference if I don't give the content also a fixed height that would always fit. I was hoping I don't have to.

**Comment by driskull** [comment]
> Tried that, they don't seem to make a difference if I don't give the content also a fixed height that would always fit. I was hoping I don't have to.

Did you give it a height and an `overflow:auto`? That should work

**Comment by macandcheese** [comment]
It does kind of seem like a use case for a dropdown or native select - the dropdown can look like this:
<img width="225" alt="Screen Shot 2019-11-01 at 1 44 53 PM" src="https://user-images.githubusercontent.com/4733155/68055425-d388a400-fcad-11e9-9051-ea2228dd8f24.png">


If needed, we can add a "selected left" vs. dot indicator of active item to dropdown

**Comment by driskull** [comment]
We may need to have a good guide on which components are for certain use cases. We don't want the `calcite-popover` to be a hammer & nail for everything. 🔨

**Comment by AdelheidF** [comment]
Tried the overflow suggestion:

![image](https://user-images.githubusercontent.com/44481292/68055732-95d84b00-fcae-11e9-8cde-337979e7c522.png)

**Comment by driskull** [comment]
@AdelheidF if you are setting `overflow-y:auto` you also need to have a height defined for when it should start overflowing with a scrollbar. `height:200px`?

**Comment by AdelheidF** [comment]
OK, seems like the answer to my question is that I have to do some calculations myself to make it work with `calcite-popover` for all screen sizes or use `calcite-dropdown` with a bit of a different look.

This is another version of the same idea:
<img src=https://user-images.githubusercontent.com/44481292/68057151-4c89fa80-fcb2-11e9-980d-685888b6c8e5.png width=200/>
