### ISSUE TITLE
Bug: calcite-action-menu styling

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1906]
### Summary
In the filter component I switched from a calcite-dropdown to a calcite-action-menu.

dropdown:
<img src=https://user-images.githubusercontent.com/44481292/113449318-6ac9bd80-93b2-11eb-81b6-edf763eea4f5.png width=200/><img src=https://user-images.githubusercontent.com/44481292/113449425-a82e4b00-93b2-11eb-9ad4-57597b09cf1a.png width=200/>

action-menu:
<img src=https://user-images.githubusercontent.com/44481292/113449220-35bd6b00-93b2-11eb-812c-18e54531d40d.png
 width=200/><img src=https://user-images.githubusercontent.com/44481292/113449601-09561e80-93b3-11eb-9ca3-6c0255f992ee.png width=200/>

(1)
To me the new action menu now looks more like a tooltip/more info than a dropdown menu with actions, especially in regards to the triangle pointer. Also, this seems to be the only component that I use that has round corners. Everything else that I use has sharp corners.

(2)
With `1.0.0-beta.54` the blue focus box went missing
![image](https://user-images.githubusercontent.com/44481292/116929706-a9ea6900-ac13-11eb-9fe8-35636dd9fe99.png)

If this is all purpose, please close this issue.

cc @driskull 

### Reproduction Steps

1.

**Comment by driskull** [comment]
@asangma we should decide if the action menu should have a pointer or not.

Since both the `panel` and `action-bar` use the `calcite-action-menu`, we should probably be consistent right?

**Comment by TheBlueDog** [comment]
Following. Agreed. The mix of radius and non-radius seems odd.

**Comment by macandcheese** [comment]
Could those actions just render as dropdown-items of "selection-mode:none" in a dropdown which would still not have a tail but have the correct 4px border radius?

**Comment by AdelheidF** [comment]
With 1.0.0-beta.54 the blue focus box went missing
![image](https://user-images.githubusercontent.com/44481292/116929706-a9ea6900-ac13-11eb-9fe8-35636dd9fe99.png)

**Comment by asangma** [comment]
@driskull Started this but could use your help on the keyboard event handling See related PR.

**Comment by jcfranco** [comment]
@AdelheidF This is installed. Can you help verify this one? 🙇🏼‍♂️

**Comment by AdelheidF** [comment]
tested with beta.56

![image](https://user-images.githubusercontent.com/44481292/121240493-41fcf300-c84f-11eb-8dcf-7413f1747557.png)

The focus box is back, pointer is gone, but corners are still round.
