### ISSUE TITLE
Bug: Tooltip "beak" shadow is on top

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1911]
### Summary
The pointy beak part is casting a shadow on the main square part.

### Actual Behavior
![image](https://user-images.githubusercontent.com/12503298/113599398-6a6c3500-95f3-11eb-9697-090a86c76fb4.png)

### Expected Behavior
A unified shadow.

### Reproduction Steps

1.

**Comment by caripizza** [comment]
@asangma how can I reproduce the issue?

**Comment by bstifle** [comment]
@caripizza its clear in the documentation of the issue:

![image](https://user-images.githubusercontent.com/14083530/113602374-259ec900-9608-11eb-83f1-f9a90b0617ae.png)

**Comment by asangma** [comment]
Weirdly, it looks like it's only happening in the devext environment.
Let me know if you need access to that @caripizza.

**Comment by caripizza** [comment]
@asangma that would rule!

**Comment by driskull** [comment]
I think this was fixed already

**Comment by asangma** [comment]
Thanks @driskull.
