### ISSUE TITLE
Enhancement: Append to body prop

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#1913]
### Description
Introduce an append-to-body prop to components that use popper.js (dropdown, popover, input-date-picker etc). These types of components may be used within modals, drawers, or other wrappers that make it difficult to show the full popover. 

`append-to-body` would determine if the popover would be added as a direct child to the `<body>` tag. 

### Acceptance Criteria
- Will need to calculate position of reference element in order to place the popover in the correct spot
- Will need to recalculate position on scroll / window resize

#### Which Component
- input-date-picker
- combobox
- color-picker
- popover
- tooltip
- dropdown
- any others that use popper.js

#### Example Use Case
<img width="465" alt="Screen Shot 2021-04-05 at 11 04 13 AM" src="https://user-images.githubusercontent.com/55154968/113610165-fc7f3800-9609-11eb-8d55-271ff140d6f1.png">
<img width="1538" alt="Screen Shot 2021-04-05 at 12 27 22 PM" src="https://user-images.githubusercontent.com/55154968/113610404-4ec05900-960a-11eb-9324-015b4cccb1ef.png">

**Comment by driskull** [comment]
@joeyHarig I'm guessing that they are getting cut off because you have an `overflow:hidden` on the modal content. Is that correct?

I don't think the `popover` would apply here since you can position that wherever in the DOM. However, the others may.

**Comment by joeyHarig** [comment]
@driskull The overflow of the CC modal body is set to `auto` (we didn't apply any additional styles). They're not being cut off, but rather actually making the modal scrollable (on mac so that isn't visible). 

In our app, we're using a custom dropdown component based on vue-select (https://vue-select.org/). Vue-select is appending the dropdown menu to the html `<body>` in order for it to appear on top of all other content as shown below. 

<img width="548" alt="Screen Shot 2021-04-07 at 11 04 29 AM" src="https://user-images.githubusercontent.com/55154968/113906078-15662580-9791-11eb-9438-c47c6f4e1c3c.png">



As you can see, the result is much more usable than if the menu is rendered within the modal body. 

![append-to-body](https://user-images.githubusercontent.com/55154968/113905619-940e9300-9790-11eb-9219-b0ac7510de16.gif)

**Comment by driskull** [comment]
@joeyHarig I think we'll have to do some research on this.

We can't just move it into the body since it's encapsulated in shadowDOM and we don't want to move it to light DOM and expose it to user styles.

**Comment by joeyHarig** [comment]
@driskull Could you use the body as the shadow host and then use `body.shadowRoot.appendChild` to add the menu nodes to the shadow tree?

**Comment by paulcpederson** [comment]
https://github.com/Esri/calcite-components/pull/1940 addresses a similar issue in combobox. Basically popper was computing the wrong direction for the combobox dropdown so it would open _down_ all the time. We may be able to apply a similar fix to other components. For example, in the gif above, the date picker would open _up_ rather than down, making it less important to overflow the container.

**Comment by alexabreu** [comment]
We're running into the same issue on Field Maps. While I agree that opening `up` rather than `down` would address our current specific issue, I do think it makes sense for component consumers to have more granular control over a given popper's placement. Building on @joeyHarig's idea, it seems we could allow specifying a target selector for appending to the `shadowRoot` of the resulting element.

**Comment by paulcpederson** [comment]
I think `appendToBody` could be a boolean and get passed directly into popper

**Comment by driskull** [comment]
popper.js doesn't do any appending, neither does `calcite-popover`. 

This would need to be handled in the components that internally use `popper.js` or `calcite-popover`. It would need to append to `getRootNode()` and not body incase used within a shadow dom. It would also then expose some internals of the component outside of it so I'm not sure this is the right approach.

**Comment by driskull** [comment]
Closing. reopen if still an issue.
