### ISSUE TITLE
Bug: Combobox max-items being ignored

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#1916]
### Behavior
When `allow-custom-values` is true and `max-items` is greater than 0, the input of a custom value causes the `max-items` prop to be ignored (showing the full list).

### Expected Behavior
Custom values should not influence the application of `max-items` to the combobox dropdown.

### Reproduction Steps

1. Go to the combobox in the storybook
2. Set `max-items` to 4
3. Set `allow-custom-values` to true
3. Enter a custom value 
4. Notice that the dropdown no longer obeys the `max-items` rule

<img width="1700" alt="Screen Shot 2021-04-05 at 3 04 01 PM" src="https://user-images.githubusercontent.com/55154968/113627333-981ba300-9620-11eb-955d-6377f1ae0eb9.png">

**Comment by driskull** [comment]
@paulcpederson can you take this one? I think you did some work on this so it may be fixed already.

**Comment by paulcpederson** [comment]
@joeyHarig so I just tried this out on the current docs and looks like it was fixed, can you confirm?

**Comment by joeyHarig** [comment]
@paulcpederson It still seems to be broken. 

![Jun-09-2021 14-08-30](https://user-images.githubusercontent.com/55154968/121422271-4ba85880-c92c-11eb-9708-c402f8759611.gif)

**Comment by paulcpederson** [comment]
so the repro steps are just type in custom tag and hit enter?

**Comment by joeyHarig** [comment]
1. Go to the combobox in the storybook
2. Set max-items to 4
3. Set allow-custom-values to true
4. Enter a custom value
5. Notice that the dropdown no longer obeys the max-items rule

If you click away and click back, the list is limited to 4 again, but immediately after entering a custom value, the list doesn't recognize `max-items`

Browser: Chrome Version 91.0.4472.77

**Comment by paulcpederson** [comment]
OK, thanks @joeyHarig

**Comment by julio8a** [comment]
verified on storybook. closing.
