### ISSUE TITLE
Bug: Dropdown styling issues post-refactor

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1921]
### Summary
There are some regressions since the Tailwind refactor to the styling of dropdown:

- selection-mode:none should not have padding for a selector

Current:
![Slice1](https://user-images.githubusercontent.com/4733155/113900250-7afee580-9782-11eb-841c-5bc90174ab6c.png)

Desired:

![Screen Shot 2021-05-05 at 10 08 51 AM](https://user-images.githubusercontent.com/4733155/117181306-ee981080-ad89-11eb-8c34-68fcff0118ed.png)

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/113904194-6d078f80-9797-11eb-9a6f-78a9dd7708e5.png)
figma^

yes these things should be lined up

**Comment by bstifle** [comment]
selection-mode:none should not have padding for a selector ✅


borders below group-titles should NOT be full width. **(design change, disregard)**

**Comment by caripizza** [comment]
@macandcheese when was the last time you recall it looking that "previous" way? Do you have a version number?

**Comment by macandcheese** [comment]
It looks like we just stopped styling non-anchors of selection-mode:none - just need to update to match:

![Screen Shot 2021-05-05 at 10 04 57 AM](https://user-images.githubusercontent.com/4733155/117181222-d9bb7d00-ad89-11eb-8f3f-5c9acfbed8d3.png)

**Comment by macandcheese** [comment]
cc @TheBlueDog

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/117328357-2e79f900-ae59-11eb-9da1-83e024c0795b.png)
Yep! left spacing should match the same as the headers for `none`

**Comment by julio8a** [comment]
@justinhough, can you change this one to installed

**Comment by justinhough** [comment]
@julio8a Updated.

**Comment by julio8a** [comment]
verified on master
