### ISSUE TITLE
Docs: Update the doc section for how to add a tooltip to `calcite-action-bar` expand action

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1925]
### Description 
with beta.52, this section of the doc no longer works:
```html
<calcite-action-bar id="action-bar-test">
  <calcite-action text="Add" icon="plus"></calcite-action>
</calcite-action-bar>
<calcite-tooltip id="tooltip">Expand</calcite-tooltip>
<script>
  var actionBar = document.getElementById("action-bar-test");
  var tooltip = document.getElementById("tooltip");
  actionBar.tooltipExpand = tooltip;
</script>
```
It would be helpful to show the proper way to do this to help making the update to the new version, it was confusing to me.

### Which Component
calcite-action-bar

cc: @driskull

**Comment by kevindoshier** [comment]
@ethanbdev - I had to make this change as well, its not a slot for the expand tooltip, from the .53 changes list

action-bar, action-pad: Replace 'tooltipExpand' properties with 'expand-tooltip' slots (#1841) (38787d4)

**Comment by ethanbdev** [comment]
> @ethanbdev - I had to make this change as well, its a slot for the expand tooltip, from the .52 changes list
> 
> action-bar, action-pad: Replace 'tooltipExpand' properties with 'expand-tooltip' slots (#1841) ([38787d4](https://github.com/Esri/calcite-components/commit/38787d4e9e8eb6a62a8c09289b291c62866600be))

Thanks @kevindoshier, so the tooltip needs to be appended to the action bar now instead of the document body?

**Comment by kevindoshier** [comment]
I think this should work

```
<calcite-action-bar id="action-bar-test">
  <calcite-tooltip slot="expand-tooltip">Expand</calcite-tooltip>
  <calcite-action text="Add" icon="plus"></calcite-action>
</calcite-action-bar>
```

**Comment by driskull** [comment]
Yes, that' is correct.

**Comment by ethanbdev** [comment]
> I think this should work
> 
> ```
> <calcite-action-bar id="action-bar-test">
>   <calcite-tooltip slot="expand-tooltip">Expand</calcite-tooltip>
>   <calcite-action text="Add" icon="plus"></calcite-action>
> </calcite-action-bar>
> ```

Thanks 😃

**Comment by ethanbdev** [comment]
Thanks @driskull 👍
