### ISSUE TITLE
Enhancement: Add border for Action Bars

### ISSUE THREAD

**Issue by TheBlueDog** [Esri/calcite-components#1926]
### Description

Currently when an action bar is used, there is no separation between it and the rest of the content on the page without adding customization.

Example:

![Action-Bar Default](https://user-images.githubusercontent.com/5419306/113941125-91ca2a00-97cc-11eb-9a96-b78814c7d30a.png)

![Screen Shot 2021-04-07 at 4 43 19 PM](https://user-images.githubusercontent.com/5419306/113932572-c4225a00-97c1-11eb-8f54-f8c0e39af2fe.png)

Since there is configuration for `start` and `end` positions, the appropriate border can be added as part of the component.

Example:

![Action-Bar Borders](https://user-images.githubusercontent.com/5419306/113941214-b0302580-97cc-11eb-97d5-512d71c717d9.png)

![Screen Shot 2021-04-07 at 4 55 21 PM](https://user-images.githubusercontent.com/5419306/113933426-8ffb6900-97c2-11eb-9c60-96c73cad8076.png)

### Acceptance Criteria 

- [ ] If an action-bar is used in the `start` position, add `border-right` with `ui-border-1`.
- [ ] If an action-bar is used in the `end` position, add `border-left` with `ui-border-1`.

#### Which Component
Calcite Action Bar

#### Example Use Case
Map View Beta and Field Maps are currently using the actionbars with added local customizations to apply a border and border-color.

**Comment by bstifle** [comment]
i think border-1 is too much. suggest using border-2 #dfdfdf to match whats already used in action bar and action pad

**Comment by justinhough** [comment]
@TheBlueDog Do you have a working example of this that I can take a look at? 

I don't have access to the "Map View Beta and Field Maps" and not sure if this would be a local project fix or something in relation to action bar within calcite. 

Let me know. Thanks.

cc @julio8a @caripizza

**Comment by justinhough** [comment]
@TheBlueDog I added a demo for action bar to show when position is used and used the color recommendation from @bstifle

**Comment by justinhough** [comment]
cc @julio8a

**Comment by TheBlueDog** [comment]
@justinhough You might want to check with @asangma to see what the relationship of this is when used inside vs outside the app-shell.

**Comment by TheBlueDog** [comment]
@julio8a This Figma library needs to be update to use a boarder left/right

**Comment by julio8a** [comment]
One of the things we want to improve is when a design change or addition get added to Figma/code. This update wouldn't be officially out until the beta 64 release on the 9/13. This is when the Figma library will reflect the change.

**Comment by TheBlueDog** [comment]
Well... the lack of border in the Figma library is where I initially found the issue, which spurred creating this issue to hopefully get it fixed and my designs accurate by the time it got to our devs for implementation. Something to consider.

**Comment by asangma** [comment]
The ActionBar shouldn't need to add borders.
If a dev needs a border on it, they can add that in the app.

That being said, ShellPanel should already be [adding borders](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-shell-panel/calcite-shell-panel.scss#L102-L110) when an ActionBar is placed in an `action-bar` slot.

**Comment by TheBlueDog** [comment]
Thanks @asangma ... So this may only be a Figma change that's needed.

**Comment by julio8a** [comment]
Thanks for the info guys, I will create issues to update Figma (ui kit repo) and link to this issue. Closing.
