### ISSUE TITLE
Enhancement: Add CSS utility class to ShellPanel to help match flex container heights

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1927]
### Description
Add a class that helps users correctly size their own elements when putting them inside of a container component (e.g. ShellPanel).

### Acceptance Criteria 
* works with ShellPanel
* works with non component tags, e.g. `div` or a custom element.
* works with nested tags, e.g. 
```
<div>
  <some-custom-element>
    <calcite-panel>
      ...
    </calcite-panel>
  </some-custom-element>
</div>
``` 
cc @AdelheidF @kevindoshier @driskull

**Comment by asangma** [comment]
Would someone mind verifying this.
I can provide details.

**Comment by driskull** [comment]
Closing. reopen if still an issue.
