### ISSUE TITLE
Enhancement: drop IE11 support by refactoring input to use HTMLInputElement's stepup and stepdown

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#1928]
### Description

See TODO comment here: https://github.com/Esri/calcite-components/blob/master/src/components/calcite-input/calcite-input.tsx#L479-L480

### Acceptance Criteria 

`calcite-input` uses the stepdown and stepup API to increment and decrement number values.

#### Which Component
`calcite-input`

**Comment by caripizza** [comment]
@eriklharper is this one still relevant?

**Comment by eriklharper** [comment]
Yes, I would think this would be a good enhancement still.

**Comment by jcfranco** [comment]
FYI: At the time of writing, Firefox's implementation doesn't align with the HTML spec: 

https://caniuse.com/?search=stepdown
https://caniuse.com/?search=stepup

**Comment by jcfranco** [comment]
Closing in favor of https://github.com/Esri/calcite-components/issues/3676.
