### ISSUE TITLE
<calcite-button> type="submit"

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#193]
I just noticed this but if I have a button in a form thats type="button" instead of type="submit" for instance a cancel button, the click event is still submitting the form, and calling the click handler I have bound to it

**Comment by paulcpederson** [comment]
@macandcheese for you?

**Comment by macandcheese** [comment]
Yep taking a look

**Comment by macandcheese** [comment]
addressed in https://github.com/Esri/calcite-components/pull/197

**Comment by paulcpederson** [comment]
🥇

**Comment by macandcheese** [comment]
@kevindoshier this should go out next beta version bump.

**Comment by kevindoshier** [comment]
@macandcheese - thanks, do you know when that beta will be available?

https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/803

**Comment by macandcheese** [comment]
I'll try and cut a release today, tomorrow at latest. 🚢

**Comment by kevindoshier** [comment]
@macandcheese - I pulled the latest and now the submit button does not call into the onsubmit function set on the form element, it calls the default form behaviour which refreshes the page now

**Comment by macandcheese** [comment]
Looked at again - https://github.com/Esri/calcite-components/pull/212, will keep this open until it's actually solved for you ;)

**Comment by svlesiv** [comment]
I'm having an issue with the submit button refreshes the page without submitting a form. Did that issue has been fixed?
