### ISSUE TITLE
Bug: `calcite-action-bar` expand tooltip not opening on hover when used inside web component

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1930]
Using the new slot, the tooltip does not open on hover. The action bar is being used inside a web component, that could be related to the issue. I cannot reproduce in a code pen. Sent @driskull a url where it is reproducible.
![98781FEF-2192-40EB-AC1F-4999C16B4EE8](https://user-images.githubusercontent.com/52869490/114039413-8fe98080-9837-11eb-90f5-6af01afe8923.GIF)

**Comment by driskull** [comment]
Yeah, it's because it's put into another shadowDom element and it's trying to find the tooltip with `docoment.getElementById()`. 

We will have to introduce some logic to query the shadow dom instead.

**Comment by ethanbdev** [comment]
This looks good, thanks @driskull 👍
