### ISSUE TITLE
Enhancement: Calcite-Block leading and trailing variants

### ISSUE THREAD

**Issue by TheBlueDog** [Esri/calcite-components#1931]
### Description

Using the block component inside a panel to create sections, it appears that it only has a border on the left. This border is visible when the block is used in a trailing panel.

When a block is used in a leading panel, the border appears missing as it is still on the left.

Example:

![Block Default](https://user-images.githubusercontent.com/5419306/114041408-8883a080-9852-11eb-8f46-00b3e83eaa78.png)

### Acceptance Criteria 

- [ ] calcite-block can be configured for its use in a leading panel, which would place the border on the right
- [ ] calcite-block can be configured for its use in a trailing panel, which would place the border on the left.

### Relevant Info 

The component is used frequently in MVB to group content in panels. Field Maps is intending to follow the similar pattern, but has need to use this in both left and right panels.

Example:

![Block Variants 2](https://user-images.githubusercontent.com/5419306/114041295-6a1da500-9852-11eb-8980-5a8717acd1f8.png)

#### Which Component

Calcite Block

**Comment by bstifle** [comment]
also thinking about how important those lines are. can we remove them completely? @asangma are there cases where that side border is used outside of a panel?

**Comment by TheBlueDog** [comment]
I could see adding the border to the entire leading/trailing panel instead and then removing them from block.

**Comment by macandcheese** [comment]
Yeah the border on just the side of block seems weird. I’ve had to manually add a border to solve for the above layout, it should be in the component OOTB IMO

**Comment by TheBlueDog** [comment]
In the example here it appears to be only on the bottom? https://next.sites.afd.arcgis.com/calcite-design-system/components/layout/block/

**Comment by asangma** [comment]
Once we have the expand/collapse chevrons back in, we should remove the border.

**Comment by asangma** [comment]
Wait...is this about Figma?

**Comment by TheBlueDog** [comment]
> Wait...is this about Figma?

No. It appears that Figma is accurately representing the component code as built.

**Comment by asangma** [comment]
Strange that the border is showing up when the Block is collapsed.
It should only be there when it's expanded.

That being said, I think it's fine if we remove it.

**Comment by asangma** [comment]
> I could see adding the border to the entire leading/trailing panel 

Not sure why you're not getting those borders.
ActionBar should have the borders already.

![Screen Shot 2021-04-08 at 10 52 07 AM](https://user-images.githubusercontent.com/12503298/114073795-88869f00-9858-11eb-898b-dfaaa188ca49.png)

**Comment by TheBlueDog** [comment]
@asangma Did you mean to post that in the issue about the borders on actionbars? :)

**Comment by macandcheese** [comment]
I can see those borders in the map viewer now.

Kind of related to this... I find myself needing to override the "duplication" of spacing between two consecutively open blocks. Is that intentional? Was this changed in the latest version used in MV since I don't see it there?

**Comment by asangma** [comment]
It's intentional. But it could be tightened up a bit.
Let's sync up on a bunch of this stuff. There are good reasons for the design decisions but we could def adjust the UI.

**Comment by asangma** [comment]
@TheBlueDog Maybe this isn't an issue anymore?

**Comment by asangma** [comment]
@TheBlueDog The settled design was to get rid of the left/right border.

**Comment by TheBlueDog** [comment]
@asangma sounds good. It's still present in the code. Is there an issue for updating the component?

**Comment by bstifle** [comment]
@TheBlueDog @asangma  can we close this since we are removing that border?
