### ISSUE TITLE
New Component: chip-group and selection modes

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#1933]
### Description

We need a workflow for single or multi selection of chips. 

Material refers to these as “choice” / “filter” chips - https://material.io/components/chips#types

Our options could match other components in our system like dropdown, accordion, etc., with a single/ multi / single-persist / none selection mode prop.

#### User Stories

Single select cc @asangma 

Multi select:
Category search on : https://developers.arcgis.com/calcite-design-system/icons/

![Screen Shot 2021-08-23 at 8 53 56 AM](https://user-images.githubusercontent.com/4733155/130478482-0bd8ba55-3d88-472a-be04-39db92a58d8e.png)

That functionally works as "multi select choice chips" would (missing some keyboard affordances)

```
<calcite-chip-group selection-mode="single/multi/single-persist">
    <calcite-chip></calcite-chip>
    <calcite-chip></calcite-chip>
<calcite-chip-group>
```
- To improve keyboard navigability, it needs to work with arrow / home / end - Do we need to render a hidden semantic analog here like in `calcite-rating`?
- A `calcite-chip` would need an `active` prop to determine styling.
- A wrapping `calcite-chip-group` would set the selection-mode, similar to a dropdown group or accordion component.
- In addition to selection modes - `calcite-chip-group` would be able to space consistently chips used in static display, or dismissible chip grid. Need to evaluate keyboard behavior for chips in chip group without selection - do they need focus? only when dismissible?

High priority for Online (analysis/home app)

**Comment by macandcheese** [comment]
Here's a demo, kind of a choppy gif recording... These navigate with arrow keys as well. The "selection modes" of `single`, `single-persist`, and `multi` are borrowed from dropdown, and accordion, so they should be familiar and flexible enough for most use cases.

In this example these are enforcing a "check icon when selected" - but that obviously prevents these from being used with icons set directly on the chip. Not sure if we should offer this as an option or otherwise find a distinct style, but something to think about ... 

@asangma @bstifle - any other use cases or thoughts there?

![Screencast 2021-04-29 at 9 21 02 AM (1)](https://user-images.githubusercontent.com/4733155/116584959-c06b8a00-a8cc-11eb-90b5-462de2ee4ce6.gif)

**Comment by macandcheese** [comment]
Can we bump the priority of this? We are still using a hand-rolled solution using Calcite Chips on the icon search linked above.

**Comment by ethanbdev** [comment]
+1, have a need for this as well!

**Comment by macandcheese** [comment]
@julio8a @benelan - can we take a look at adding some priority to this?

**Comment by mitc7862** [comment]
This looks great!
We really need this in Map Viewer and Analysis Studio.

**Comment by macandcheese** [comment]
@benelan let's look at re-prioritizing this one if possible next triage.

**Comment by ethanbdev** [comment]
@jay-bis ended up implementing something similar for a different project, I am not sure if some if it could be reused / moved to this repository

**Comment by macandcheese** [comment]
I wonder if this could be encompassed within a chip-group component instead of one specific to selection.

We could have have a “none” selection mode in addition to those listed in OP to provide spacing to chips elsewhere, which has been requested separately in the past. A single chip would be able to exist on its own without the parent as it currently does.

**Comment by ellenupp** [comment]
We could also use something like this in Dashboards. We're currently implementing something similar using calcite-buttons:

![image](https://user-images.githubusercontent.com/14304581/219524809-3d4d4fdd-c067-4a17-a1f6-5c831e209e85.png)

But we also have an "edit" mode where items can be reordered and renamed.

![image](https://user-images.githubusercontent.com/14304581/219524921-2d22405c-5aec-4cd0-a6f8-03d5759e1f4d.png)

**Comment by geospatialem** [comment]
Verified in `master` with mouse, keyboard, and AT - JAWS and NVDA.

Referencing issue https://github.com/Esri/calcite-components/issues/6825 for additional keyboard support down the line.
