### ISSUE TITLE
Enhancement: add scale to calcite-action-menu

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#1939]
### Description

`calcite-action-menu` doesn't have `scale` property. And the action button only "fits" with medium `calcite-action-bar` and `calcite-action-pad` actions.

#### Which Component

`calcite-action-menu`

#### Example Use Case

Any `calcite-action-bar` or `calcite-action-pad` with small or large scale actions.

**Comment by COV-GIS** [comment]
Awesome! Thanks @driskull.

**Comment by COV-GIS** [comment]
This is seems to have regressed in v1.0.0-beta.59 @driskull.

**Comment by driskull** [comment]
@COV-GIS calcite-action-menu now has a slot "trigger" where you can supply your action with all its props.

**Comment by COV-GIS** [comment]
Thanks @driskull.

FYI...The slotted action has a small margin which adds a "gutter" to one side of the action pad.

**Comment by driskull** [comment]
Thanks, i'll create an issue for that one unless you want to handle it. I think i saw that as well. We need to probably add a slotted style for the action-menu in that component.

**Comment by driskull** [comment]
https://github.com/Esri/calcite-components/issues/2459

**Comment by driskull** [comment]
Thanks created issue!
