### ISSUE TITLE
Bug: with the action-bar overflow changes, a window size of 1440 x 655 will clip the expand action

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#1942]
### Summary

A window size of 1440 x 655 will clip the expand action

![image](https://user-images.githubusercontent.com/11093161/114207097-da8afb80-9910-11eb-894b-cbe9d3b89791.png)

### Reproduction Steps

1.

**Comment by driskull** [comment]
Thanks @kevindoshier. I'll get this logic working better.

**Comment by driskull** [comment]
Closing. reopen if still an issue @kevindoshier
