### ISSUE TITLE
Bug:  Overflow Menu doesn't work in certain scenario

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#1945]
Clicking to open the overflow menu does not open the menu in New Map viewer when add layer item browser pane is open. 
To reproduce:

![menuissue](https://user-images.githubusercontent.com/50747646/114251596-712ddb80-9956-11eb-94f8-ffb72111394b.gif)

cc @kevindoshier @driskull

**Comment by kevindoshier** [comment]
The popover is there but it gets hidden by the properties panel of the itemBrowser

![image](https://user-images.githubusercontent.com/11093161/114251929-b56dab80-9957-11eb-99ff-de3616933c57.png)

**Comment by driskull** [comment]
@kevindoshier this just sounds like a zindex issue. Can you adjust it on that specific panel so that it isn't over everything?
