### ISSUE TITLE
calcite-popover going offscreen

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#195]
Dhrumil is having issues with the popup popovers going offscreen, and not being able to scroll to the end.  He also mentioned that there is "no fixed location from where the popover will launch". I'll forward y'all the email thread for reference. 

![image001](https://user-images.githubusercontent.com/48069902/67532975-30b4a200-f67d-11e9-850b-fdbac8dd2d97.png)

**Comment by AdelheidF** [comment]
Same issue with "top" placement (and probably "bottom"). The popover causes horizontal scrolling of the entire page.
In this case it should not center the caret.

<img src=https://user-images.githubusercontent.com/44481292/67630872-68714480-f84b-11e9-9483-2671494ffb01.png width=300/>

**Comment by driskull** [comment]
Added a property to disable flipping the popover.

**Comment by macandcheese** [comment]
released 🚀
