### ISSUE TITLE
Bug: pick list retains a pick list item in its `selectedItems` when it is removed while selected

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1954]
### Summary
When a pick list item is selected, then removed while selected, calling `getSelectedItems` after a new selection will return a map containing the **old, removed** selected item _and_ the new one.

### Reproduction Steps

1. Create a pick list with a few items
2. Select a pick list item
3. Remove the above selected item
4. Select a new item
5. Observe the result from both the `calciteListChange` event and `getSelectedItems()` method.

https://codepen.io/eborgen/pen/gOxJpey?editors=1011

**Comment by benelan** [comment]
@ethanbdev Can you provide a codepen to repro this issue?

**Comment by ethanbdev** [comment]
> @ethanbdev Can you provide a codepen to repro this issue?

Yeah, let me work on one.. Maybe I am missing something easy but how does the `getSelectedItems` method work in the codepen? https://codepen.io/eborgen/pen/gOxJpey?editors=1011

**Comment by benelan** [comment]
`getSelectedItems()` returns a Promise that is resolved with a Map, so log something like `console.log(...selectedItems.entries());`

**Comment by ethanbdev** [comment]
> `getSelectedItems()` returns a Promise that is resolved with a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), so log something like `console.log([...selectedItems.entries()]);`

Right 🤦 

Here you go on a repro, let me know if it makes sense:
https://codepen.io/eborgen/pen/gOxJpey?editors=1011

**Comment by benelan** [comment]
Makes sense to me, thanks for the repro sample!

**Comment by ethanbdev** [comment]
Looks good in my repro!
