### ISSUE TITLE
Refactor: [calcite-slider] remove drag interaction listeners when the component is removed from the DOM

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#1955]
### Summary

Event listeners added to the document are not disconnected when calcite-slider is removed from the DOM.

### Actual Behavior

Several event listeners are added to the document but are never cleaned up.

### Expected Behavior

All event listeners should be disconnected when the component disconnects from the DOM.

**Comment by jcfranco** [comment]
@eriklharper Could you details on which event listeners remain? The pointer events are removed at the end of a drag interaction, but we can also remove them on `disconnectedCallback`.

**Comment by eriklharper** [comment]
> @eriklharper Could you details on which event listeners remain? The pointer event listeners are removed at the end of a drag interaction, but we can also remove them on `disconnectedCallback`.

Ah, this looks to be resolved now, probably can close this issue then.

**Comment by jcfranco** [comment]
I'll change this to a refactor ticket instead to ensure manually-added event listeners are removed when the component is disconnected.

**Comment by benelan** [comment]
verified on next
