### ISSUE TITLE
Bug: Label - Remove use of document.getElementById()

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1957]
### Summary

Remove use of document.getElementById since it won't work if the component is within another shadow dom component. It seems like other teams are wrapping our components in their shadow dom components so we need to be mindful of this.

The solution is to use this.el.getRootNode() and then query either the rootNode (document) or rootNode.host (shadow dom) element.

### Actual Behavior

```jsx
// 2. htmlFor matches a calcite component
const inputForThisLabel = document.getElementById(this.for);
```

### Expected Behavior

```jsx
import { getElementById, getRootNode } from "../../utils/dom";

// 2. htmlFor matches a calcite component
    const rootNode = getRootNode(this.el);
    const inputForThisLabel = getElementById(rootNode, this.for);
```

### Reproduction Steps

1. Use a `calcite-label` inside the shadow dom of another component
2. Notice that the `for` property is not working as expected.

### Relevant Info 

https://github.com/Esri/calcite-components/pull/1956

**Comment by jcfranco** [comment]
@eriklharper Was this closed intentionally?

**Comment by eriklharper** [comment]
Yes, it was closed as per the linked PR, is that not correct?

**Comment by jcfranco** [comment]
We shouldn't be closing via PR/commits, since we want someone to verify an issue is fixed before closing it and to set the appropriate labels. cc @caripizza

**Comment by eriklharper** [comment]
Makes sense, I guess I did actually close it, since I assume its not getting closed automatically anymore on merged linked PRs?
