### ISSUE TITLE
Bug: Button - Remove use of document.getElementsByName()

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#1958]
### Summary

Remove use of document.getElementById since it won't work if the component is within another shadow dom component. It seems like other teams are wrapping our components in their shadow dom components so we need to be mindful of this.

The solution is to use this.el.getRootNode() and then query either the rootNode (document) or rootNode.host (shadow dom) element.

### Actual Behavior

```jsx
const targetForm = requestedForm
        ? (document.getElementsByName(`${requestedForm}`)[0] as HTMLFormElement)
        : (this.el.closest("form") as HTMLFormElement);
```

### Expected Behavior

```jsx
import { getElementById, getRootNode } from "../../utils/dom";

const targetForm =  rootNode instanceof ShadowRoot
          ? rootNode.host.querySelector(`[name=${requestedForm}]`)
          : document.getElementsByName(`${requestedForm}`)[0] as HTMLFormElement
```

### Reproduction Steps

1. Use a `calcite-button` with a form inside the shadow dom of another component
2. Notice that the `form` functionality is not working as expected.

### Relevant Info 

https://github.com/Esri/calcite-components/pull/1956

**Comment by driskull** [comment]
Can we get this issue elevated so that we use the `queryElementsRoots` in dom utils?

What do you think @jcfranco Should this be a priority since it uses document and would fail inside a shadowRoot.

**Comment by jcfranco** [comment]
Added to the next sprint. Will move to this one if the queue clears up.

**Comment by driskull** [comment]
Think this should be pre 1.0

**Comment by caripizza** [comment]
I can verify this one - @driskull can you suggest a code snippet for me to confirm the fix?

**Comment by driskull** [comment]
@caripizza you will have to setup a page with a shadowed component that uses the button.

```html
<script>
      class DemoShadow extends HTMLElement {
        constructor() {
          super();
          this.attachShadow({ mode: "open" });
          this.shadowRoot.innerHTML = `
          <form id="myform">
            <calcite-button form="myform"></calcite-button>
          </form>
        `;
        }
      }
      customElements.define("demo-shadow", DemoShadow);
    </script>
```

```html
<demo-shadow></demo-shadow>
```

**Comment by caripizza** [comment]
Verified the fix locally with this code on master branch (closest prior release is 1.0.0.next-259):
```html
    <script>
      class DemoShadow extends HTMLElement {
        constructor() {
          super();
          this.attachShadow({ mode: "open" });
          this.shadowRoot.innerHTML = `
          <form name="sign-up">
            <calcite-label>
              First name
              <calcite-input name="first-name" required></calcite-input>
            </calcite-label>
            <calcite-button type="reset">I should reset the form (type reset)</calcite-button>
            <calcite-button type="button">I should not submit the form (type button)</calcite-button>
            <calcite-button>Submit</calcite-button>
          </form>
        `;
        }
      }
      customElements.define("demo-shadow", DemoShadow);
    </script>
    <demo-shadow></demo-shadow>
```

Form submit/reset behavior works as expected, closing.
