### ISSUE TITLE
Enhancement: Accordion add open/expand property

### ISSUE THREAD

**Issue by previnWong** [Esri/calcite-components#1959]
### Description
Right now, there is no property to set whether the accordion can be open/expanded by default.  So user has to always click to expand.

### Acceptance Criteria 
Add a boolean property so that the accordion can be open by default

### Relevant Info 
![image](https://user-images.githubusercontent.com/11183838/114618595-6036e000-9c5e-11eb-9c65-9ce42aba7bff.png)

#### Which Component
Accordion

#### Example Use Case
![image](https://user-images.githubusercontent.com/11183838/114618290-09310b00-9c5e-11eb-9d99-49a338eb2662.png)

**Comment by macandcheese** [comment]
Hi @previnWong - You can use `active` on a `calcite-accordion-item` to set it to open by default without user interaction: https://codesandbox.io/s/tender-spence-vludx

**Comment by previnWong** [comment]
That worked!  thank you!  Maybe add accordion item as a sub bullet under accordion in story book with it's properties.
