### ISSUE TITLE
Enhancement : Switch. Allow slot to be positioned leading/trailing

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#196]
Currently, `<slot />` is always placed after `track`. Might be nice to have a prop for placing the default slot in front of or after.

Need it for cases where switches are in calcite-app-components panels and blocks.
![image](https://user-images.githubusercontent.com/12503298/67591100-791d9f80-f711-11e9-9632-141204e4a969.png)

**Comment by macandcheese** [comment]
This will be included in the `calcite-label` component - the ability to position inline or inline-with-space-between, so you can wrap checkbox, radio button, or switch in this manner.

**Comment by macandcheese** [comment]
Closing this as it'll be addressed in https://github.com/Esri/calcite-components/pull/248
