### ISSUE TITLE
Enhancement: Add ability to disable selection in ValueList

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#1964]
### Description
ValueList and by extension ValueListIem always has selection enabled.
Sometimes it shouldn't be.

#### Which Component
ValueList & ValueListItem

**Comment by asangma** [comment]
@driskull Any thoughts on this?

**Comment by driskull** [comment]
@asangma I think we need a generic list component that doesn't have to do with selection. Then the value/pick list can use it internally.

**Comment by asangma** [comment]
Closing as this is a ghost of duplicate past re #2040.
