### ISSUE TITLE
Enhancement: Event on Dropdown Item when SelectionMode is None

### ISSUE THREAD

**Issue by tyanthony** [Esri/calcite-components#1967]
### Description
When the dropdown list has the `selectionMode` set to `none`, the item that is selected is unknown. The `calciteDropdownSelect` event is fired, but we are unable to determine _which_ item was selected. 

### Acceptance Criteria 
Ability to determine _which_ item in the dropdown list was selected when the `selectionMode` is `none`.
Desired Behavior (1 of the following):
- exposed event on the dropdown-item
- detail on the parent event to include the element that was selected
- other?

#### Which Component
[Dropdown](https://esri.github.io/calcite-components/?path=/story/components-buttons-dropdown--groups-and-selection-modes)

**Comment by macandcheese** [comment]
Follow up from Teams - likely have the parent detail include the selected item AND expose the child event as well. Likely applies to other components with parent/child events like this (accordion, tree, stepper, etc...)

**Comment by geospatialem** [comment]
Verified on next.551 with [Codepen](https://codepen.io/geospatialem/pen/RwMQNjM).

![verify-selectnone-dropdown-items](https://user-images.githubusercontent.com/5023024/182239749-f421dc2a-aaf8-4306-8915-69f64808591f.gif)
