### ISSUE TITLE
Button Styling Updates

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#199]
**Overall**
Solid buttons...
- [ ] Remove borders from hover and pressed states

![image](https://user-images.githubusercontent.com/14083530/67610352-f3b4e200-f746-11e9-8c7e-db964e3bf808.png)

-----

**Light theme**
- [ ] dark solid button styling to
idle  blk-190
hover  blk-180
press  blk-200

![image](https://user-images.githubusercontent.com/14083530/67610383-37a7e700-f747-11e9-9e6a-6b6019ce8330.png)

-----

**Dark theme**
- [ ] dark solid button styling to
idle  blk-190
hover  blk-200
press  blk-180

- [ ] light solid button styling to
idle  blk-010
hover  blk-020
press  blk-000

![image](https://user-images.githubusercontent.com/14083530/67610424-9c634180-f747-11e9-8642-819e6c3d3c30.png)

**Comment by julio8a** [comment]
#200
