### ISSUE TITLE
Question: Webpack Missing Module

### ISSUE THREAD

**Issue by previnWong** [Esri/calcite-components#1993]
### Question
Using Calcite in a Stencil web component.  After building the component, and using the web component in an Experience Builder application, there is an error that it there is a webpackmissingmodule.
![image](https://user-images.githubusercontent.com/11183838/115095654-e65d5b80-9ed6-11eb-9ca6-feeefe7bb47f.png)

Is there step missing when building the web component?
### Helpful Details 

Here is the file it is looking at
![image](https://user-images.githubusercontent.com/11183838/115095671-f412e100-9ed6-11eb-80e2-9a2037656b3f.png)

package.json file
![image](https://user-images.githubusercontent.com/11183838/115095728-2a506080-9ed7-11eb-80be-fd164559d5db.png)

Loading the custom elements
![image](https://user-images.githubusercontent.com/11183838/115095776-5370f100-9ed7-11eb-8a3b-818a32a526ed.png)
![image](https://user-images.githubusercontent.com/11183838/115095783-5ec41c80-9ed7-11eb-9c08-ffd0f18187c2.png)

**Comment by macandcheese** [comment]
@previnWong can you verify if this is still an issue with the latest version?

**Comment by previnWong** [comment]
I think Accordion is now there.  Although I switch to use js api instead of web component.  Closing for now.
