### ISSUE TITLE
Bug: Add Preact types to next builds

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#1994]
### Summary

Currently next builds don't include the preact types for some reason. They seem to be generated by the build and they live in the `dist/types` folder, and other files are included in that folder, so not sure what is preventing them from being included. 

I looked through the tooling for a while, but can't find anything obvious...

### Actual Behavior

Missing `dist/types/preact.d.ts`

### Expected Behavior

`dist/types/preact.d.ts` included

### Reproduction Steps

1. install latest next version: `1.0.0-next.164`
2. Observe

**Comment by jcfranco** [comment]
Installed and self-verified w/ the latest `@next` deployment: https://unpkg.com/browse/@esri/calcite-components@1.0.0-next.171/dist/types/
