### ISSUE TITLE
Search Widget Inside of calcite-panel on Safari

### ISSUE THREAD

**Issue by justingreco** [Esri/calcite-components#1996]
### Summary
There appears to be an issue when the ArcGIS JS API 4.x search widget is placed inside of a Calcite panel on Safari on macOS, it is not an issue on iOS or in other browsers (tested in Chrome).  I am thinking this is an issue with Safari and the shadow DOM.

The issue is demonstrated in this code pen:
https://codepen.io/justingreco/pen/qBRMwmm

It works in Chrome on macOS, but not in Safari on macOS.

### Actual Behavior
After selecting from the suggestions menu of the search widget nothing happens.

### Expected Behavior
After selecting from the suggestions menu, the text of the input box should be replaced by the value selected, the map should zoom to the feature, the map should display a popup.

### Reproduction Steps

1. Place the search widget's container inside of the body of a Calcite panel.
2. Enter a search term.
3. Select from the suggestions menu.

### Relevant Info 
Safari on desktop (works on mobile)

**Comment by justingreco** [comment]
Tested search widget inside of Material Web Components mwc-drawer and can't replicate the issue in Safari.  Believe it might be more of a calcite-components issue than a JS API issue.

**Comment by macandcheese** [comment]
This seems to have been resolved in the JSAPI in version 4.20: https://codepen.io/mac_and_cheese/pen/LYeOEwY


@justingreco can you confirm?

**Comment by jcfranco** [comment]
Closing per ☝️.
