### ISSUE TITLE
Bug: calcite-input type=number - can enter weird numbers

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2005]
### Summary

- calciteInputInput returns 000000, should probably not display this
![image](https://user-images.githubusercontent.com/44481292/115477956-eec8d580-a1f9-11eb-9bec-f394e57dd3a8.png)

- calciteInputInput returns valid numbers 1 and 5, but it should not allow a display like this
![image](https://user-images.githubusercontent.com/44481292/115478060-1f107400-a1fa-11eb-8c3c-4be73c4c8f2a.png)

- calciteInputInput returns 03
Start with a value of 0. Then type in a 3 after the 0. The input box correctly updates to just 3.
![image](https://user-images.githubusercontent.com/44481292/115478140-567f2080-a1fa-11eb-8f8e-775e37aa5cf8.png)

### Reproduction Steps

1.

**Comment by eriklharper** [comment]
@AdelheidF @jcfranco Should we diverge from how the native `<input type="number">` element works by truncating `00000` to just `0`?  In a native number input, it allows multiple zeros, both in the display and the stored value at form submission time:

![image](https://user-images.githubusercontent.com/821864/122275598-be6b8380-ce98-11eb-946b-05087c94f3c8.png)

**Comment by AdelheidF** [comment]
I don't see where this would ever be useful for an input field of type number.

**Comment by AdelheidF** [comment]
Tested with the latest next.226 (from 11 days ago!)

I can no longer enter 1.... or 1,,,,, so that part is good.
Waiting on a newer next release to test 0000.

**Comment by AdelheidF** [comment]
Tested now with next.227 and 0000 is good too.
