### ISSUE TITLE
Bug: calcite-popover pointer placement 

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#201]
From Adelheid:

### Summary

The placement of the triangle pointer doesn't seem correct. I assume there should be no grey shadow looking through between the popover box and the triangle.

![image](https://user-images.githubusercontent.com/44481292/67626872-79e42d80-f806-11e9-8814-24fafbe7d782.png)

![image](https://user-images.githubusercontent.com/44481292/67626875-8799b300-f806-11e9-9170-c6a23fec9d72.png)

### Relevant Info 

http://devext.arcgis.com/apps/mapviewer/index.html

**Comment by driskull** [comment]
@kat10140 this may be a map viewer specific issue. Can you verify the shadow is from the popover?

**Comment by kat10140** [comment]
@driskull yeah this shadow isn't present for me

**Comment by kat10140** [comment]
![Screen Shot 2019-10-30 at 2 43 47 PM](https://user-images.githubusercontent.com/48069902/67901287-b32cde00-fb23-11e9-8f04-4aef257f3a6b.png)

**Comment by driskull** [comment]
@AdelheidF can you comment on this?

**Comment by AdelheidF** [comment]
Yes, user error. I had added a temporary shadow while popover didn't have one. Removed it now.

**Comment by kat10140** [comment]
Ok, closing this issue
