### ISSUE TITLE
Enhancement: Add `Don't show this again` option on the Alert component

### ISSUE THREAD

**Issue by ade10176** [Esri/calcite-components#2012]
### Description
As a user, I'd like to have the option to select `Don't show this again` on an alert. 

### Acceptance Criteria 
- [ ] As a user, I can see and select a check box next to the `Don't show this again` on the alert
- [ ] The message can be updated/translated and support RTL

### Relevant Info 
Some users would save continuously throughout their workflow and don't find the need to see `changes successfully saved` appears after each save. Some other ones prefer to see the save confirmation. We believe including `Don't show this again` option will support both use cases.

#### Which Component
Alert

#### Example Use Case
![Saving confirmation - 1](https://user-images.githubusercontent.com/49533268/115622235-6eaf7800-a2ac-11eb-9e38-647f8810f05c.png)

**Comment by macandcheese** [comment]
Thanks for submitting @ade10176 - I agree having that functionality as a user would be nice to have, but I'm not sure if this component should contain that. It seems a little heavy to have an interactive control inside of a component as "fleeting" as alert - actions contained inside should be lightweight and not require multiple steps to complete.

Technically, the requested design could already be achieved by a dev-user using slots... inside of which they could have a control with an interaction event they use to keep track of user preference however that may be stored (and, hopefully, some way to reset this choice as a user).

After chatting with @bstifle - this could (?) be a use-case for an "action icon" / required "tooltip" that emitted an event when interacted with. That way, a dev-user could use it for "don't show again", "snooze for x hours", "dismiss but send to notification panel", "try that action again" or anything else.

![Screen Shot 2021-04-27 at 10 36 02 AM](https://user-images.githubusercontent.com/4733155/116286953-ad2db280-a744-11eb-8a9c-c408dbb08ae6.png)


Not sure if this overbuilds our alert into something more like... a Dialog, something that's half modal and half alert for more conversational interactions with a "do this" or "do that instead" type of experience.

**Comment by TheBlueDog** [comment]
How would this work with queued alerts as well? There might be three in the stack, but not all would have the capability of "don't show this again".

**Comment by macandcheese** [comment]
Yeah, that would ultimately be up to what the app puts as far as text / action there. If they decide it's "don't show again", they would need to handle which of their queued alerts that would apply to, and remove from queue if that happened? We could certainly improve the "queued" functionality too. Above is just a suggestion for that, I'd imagine if we went forward we would want to more strictly document how / what to do there.

**Comment by ade10176** [comment]
Thanks @macandcheese for this feedback!

**Comment by macandcheese** [comment]
I'm going to close this since it should be achievable with this issue that updates the alert to accept slotted actions like Notice: https://github.com/Esri/calcite-components/issues/2382.
