### ISSUE TITLE
Question: Is it possible to minimize bundle size to only what I need?

### ISSUE THREAD

**Issue by joelcoxokc** [Esri/calcite-components#2018]
### Question

I am using Angular, with the Angular CLI latest version. 

When I pull calcite-components in, my bundled application exceeds 4000 files. 
I am only using 3 or 4 of the calcite components. 

Most typescript libraries will only bundle the modules that are used. 

Is there a way to only bundle the modules that I need. 
This will help me exclude the massive list of icon/json files and date-picker languages that I do not need.

**Comment by paulcpederson** [comment]
@joelcoxokc are those being loaded in the browser or just included in your built files? These files should be fetched dynamically on the client and not included in any bundles...

**Comment by joelcoxokc** [comment]
@paulcpederson they are not being concatenated in the bundle, but everything is included in the final dist output. 
Which exceeds 4000 files. 
I am trying to deploy this to Azure-Static Webapps and they have a max file limit of 4000. 

Ide like to just not include the entire library in the dist directory when I run my build.

**Comment by paulcpederson** [comment]
@joelcoxokc so I was just playing with this and you can leverage the angular cli config's `assets` section to serve assets from `node_modules` by adding the following to `angular.json` in `architect.build`:

```json
{
  "glob": "**/*",
  "input": "./node_modules/@esri/calcite-components/dist/calcite/assets/",
  "output": "./assets/"
}
```

Theoretically you could make that glob whatever you want and serve only the icons you need. For example, the following would only copy over icons dealing with bananas:

```json
{
  "glob": "calcite-icon/banana*.json",
  "input": "./node_modules/@esri/calcite-components/dist/calcite/assets/",
  "output": "./assets/"
}
```

The static resources used by Calcite Components are not required, and we will fail gracefully if it's not there. So you are free to make your set of assets as small as you need it to be. I pushed up a demo repo here: https://github.com/paulcpederson/calcite-components-angular-example 

Hope that helps!

**Comment by joelcoxokc** [comment]
@paulcpederson  we are already using the asset globs to ignore all the date-piker and icon assets. 

However, I would also like to ignore the rest of the Javascript modules that we are not using.

My dist folder looks like this now, and I am not using 99% of this code, and we do not want out server serving all this code up. 

![image](https://user-images.githubusercontent.com/4668188/116265666-eebc5e80-a740-11eb-9872-32ce63ec02ef.png)
![image](https://user-images.githubusercontent.com/4668188/116265708-f67c0300-a740-11eb-9855-2f312f60e534.png)
![image](https://user-images.githubusercontent.com/4668188/116265755-ff6cd480-a740-11eb-8cf9-ebeb9f237703.png)

**Comment by joelcoxokc** [comment]
@paulcpederson  I noticed that the `defineCustomElements(window);` has an `exclude: []` option. Will excluding elements prevent them from being included in the output folder?

**Comment by paulcpederson** [comment]
> Which exceeds 4000 files.

You're seeing over 4000 js bundles? That doesn't seem right. Can you tell me what release that is?

I'm not totally sure what `exclude` does, the stencil docs are... nonexistent. If I had to guess I would say that probably just skips defining those tags and won't help with the bundles being moved over. 

Another path here would be to use the custom elements bundles and define them yourself:

```ts
import { CalciteButton } from '@esri/calcite-components/dist/custom-elements/';

customElements.define('calcite-button', CalciteButton);
```

Theoretically you could then copy literally the files you wanted as those custom elements bundles are named by component rather than by autogenerated hash. This is going to end up being pretty annoying, though, as you add more components. It also requires that you define the whole dependency tree for a component (ie, button would also require defining `calcite-icon`).

**Comment by joelcoxokc** [comment]
@paulcpederson  No it is only 236 js bundles. 

With the assets, it exceeded 4000, But we already solved the 4000 issue.

I am using `"@esri/calcite-components": "^1.0.0-beta.50"`

I that output by simply running `ng build`

**Comment by paulcpederson** [comment]
Oh, thank goodness I was really concerned. 

I'm not familiar enough with the internals of angular to know how it's managing the dependency tree, but have a play with the custom elements bundle and let me know if anything clicks, I can try to help when I have some cycles.

**Comment by joelcoxokc** [comment]
Great!.. That seemed to do the trick. Thank you soo much for you quick response and help on this.

**Comment by jcfranco** [comment]
Closing based on the above comment. @joelcoxokc Please submit a new issue if anything else is needed.

@paulcpederson Thanks for the support! 💪🏼
