### ISSUE TITLE
Research: explore using additional Screener APIs to improve screenshot testing

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#2019]
### Background 

Screener provides additional tools to perform visual testing on more complicated components, such as dropdowns or modals that require interaction to display additional UI.  

### Desired Outcome 

- [x] Explore how the Screener steps API would change our current testing (https://github.com/Esri/calcite-components/pull/3141, https://github.com/Esri/calcite-components/pull/3140)
- [x] If we do incorporate the steps API, 
  - [x] add documentation for usage guidelines:
    - background usage guidelines
    - when to use it (pros and cons)
    - how to use it
  - [x] if applicable, create component-specific issues to use the steps API

**Comment by driskull** [comment]
I merged storybook changes for popover/tooltip

**Comment by eriklharper** [comment]
Wiki Doc Page created here: https://github.com/Esri/calcite-components/wiki/Screenshot-Testing
