### ISSUE TITLE
Build: remove demo html's _assets from dist/collection folder

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2024]
## Summary
I'm not sure if this is more of a bug or not, so just starting with a blank issue template. This is a follow-up to my CC Dev Sync meeting's wiki bullet point ([4/22/21](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.wiki/tab::2bc3cae1-7547-41b0-a1cf-72bd303a0b1a?context=%7B%22subEntityId%22%3A%22%7B%5C%22pageId%5C%22%3A34%2C%5C%22sectionId%5C%22%3A46%2C%5C%22origin%5C%22%3A2%7D%22%2C%22channelId%22%3A%2219%3Afd15b51dacd24e70895ec1218a54ae06%40thread.skype%22%7D&tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d)), where I suggested we utilize this folder but we decided nope we should remove this from the build output.

Our build includes the js helper functions that we use in the component demos/ html pages:
https://unpkg.com/browse/@esri/calcite-components@1.0.0-beta.54/dist/collection/demos/_assets/

## Measure of Success 
The src/demos/_assets/ folder is no longer included in the dist/collection output from the build.

**Comment by jcfranco** [comment]
Installed and self-verified w/ latest `@next` deployment: https://unpkg.com/browse/@esri/calcite-components@1.0.0-next.172/dist/collection/
