### ISSUE TITLE
Bug:  `calcite-dropdown` error with Rollup

### ISSUE THREAD

**Issue by gavinr** [Esri/calcite-components#2026]
### Summary

Error `Uncaught TypeError: Cannot read property 'isLink' of undefined` when clicking on a `calcite-dropdown` when using with Rollup.

### Actual Behavior

Error:
![image](https://user-images.githubusercontent.com/209355/115819444-5ba4c100-a3ee-11eb-88a5-7fe3c3156c6e.png)

### Expected Behavior

No error.

### Reproduction Steps

1. Open https://gavinr.github.io/calcite-components-svelte-example/
2. In browser, click on the "Open Dropdown" dropdown.

OR:

1. Clone https://github.com/gavinr/calcite-components-svelte-example
2. `npm install`
3. `npm run dev`
4. In browser, click on the "Open Dropdown" dropdown.

### Relevant Info

- Error above is in Chrome. In Firefox, I get a similar but different error: `Uncaught TypeError: item.attributes is undefined`

- calcite-components v1.0.0-beta.54

Originally mentioned [here](https://github.com/Esri/calcite-components-examples/pull/7#issuecomment-666069317).

**Comment by julio8a** [comment]
Thanks for opening this issue. We'll review and prioritize.

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
Closing as self-verified. Please submit a new issue if something else needs to be addressed.
