### ISSUE TITLE
Bug: Date picker styles

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2039]
### Actual Behavior
**1. bad range hovers when hovering inside existing range:**
<img width="365" alt="Screen Shot 2021-04-26 at 11 00 33 AM" src="https://user-images.githubusercontent.com/14083530/116114618-24990e80-a67f-11eb-8e04-64a8abc0820b.png">
<img width="284" alt="Screen Shot 2021-04-26 at 11 00 41 AM" src="https://user-images.githubusercontent.com/14083530/116114625-25ca3b80-a67f-11eb-9dc2-5232450f86d5.png">

### Expected Behavior
**good range hovers:**
![image](https://user-images.githubusercontent.com/14083530/116116083-5d85b300-a680-11eb-820b-e6bf1be9a20c.png)

### Actual Behavior

**2. wrap issue on small heading:**
<img width="201" alt="Screen Shot 2021-04-26 at 11 01 05 AM" src="https://user-images.githubusercontent.com/14083530/116114729-3f6b8300-a67f-11eb-9f5e-56864c351b45.png">

### Expected Behavior

**good small heading:**
<img width="204" alt="Screen Shot 2021-04-26 at 11 01 15 AM" src="https://user-images.githubusercontent.com/14083530/116114881-64f88c80-a67f-11eb-86a1-170b87f471d8.png">

**Comment by caripizza** [comment]
Related issue: #1845

**Comment by caripizza** [comment]
@bstifle how can I reproduce issue 2 from your description?

**Comment by bstifle** [comment]
@caripizza 
idk if its only on september, but its on the "inside small container" variant on the demo page

![image](https://user-images.githubusercontent.com/14083530/118561160-3dea2380-b730-11eb-99fd-ee345c8a53bc.png)

**Comment by caripizza** [comment]
Got it @bstifle, in that case maybe we can just add `width: 100%;` to the .text class [here](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-date-picker-month-header/calcite-date-picker-month-header.scss#L76) to prevent the header text from wrapping in smaller-width containers.

**Comment by bpatterson88** [comment]
@caripizza Added that fix to https://github.com/Esri/calcite-components/pull/2132

**Comment by bstifle** [comment]
looks good ben! merge it in!

**Comment by bpatterson88** [comment]
Closed by #2132
