### ISSUE TITLE
Enhancement: pick/value-list and pick/value-list-item add nonInteractive prop

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2040]
### Description
Add a disableSelect property which disables select.
There are cases where value-list-items benefit from the ability to sort and quickly remove but where the UX suffers from an irrelevant selected state.

#### Which Component
ValueList and ValueListItem

cc @driskull

**Comment by TheBlueDog** [comment]
Field Maps has a use for this. We have a list of fields in the layer that will never need a selected state.

**Comment by asangma** [comment]
@jcfranco not sure who to assign to for verfee since I created the issue. :)

**Comment by jcfranco** [comment]
No prob. I can help verify. 😄

**Comment by jcfranco** [comment]
Verified!
