### ISSUE TITLE
Remove border conflicts with backgrounds — Update border vars

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2042]
<img width="1402" alt="NEW BORDERS LIGHT" src="https://user-images.githubusercontent.com/14083530/116129546-d93b2c00-a68f-11eb-87c5-f210266f2fe6.png">
<img width="1402" alt="NEW BORDERS DARK" src="https://user-images.githubusercontent.com/14083530/116129552-da6c5900-a68f-11eb-9f74-722dc96a028a.png">

**Comment by macandcheese** [comment]
Is this a calcite-colors level or tailwind-level change?

**Comment by bstifle** [comment]
i think tailwind. the colors used for the new ones are existing in calcite colors

**Comment by macandcheese** [comment]
OK, I think we actually need to update this in calcite-colors repo - the values are there: https://github.com/Esri/calcite-colors/blob/ba782b1a87deb3ef6b5e98662220f24c0e40703c/dist/colors.scss#L528

**Comment by caripizza** [comment]
@bstifle does this need to land with v1.0.0?

**Comment by bstifle** [comment]
Ideally yes. Im not sure if it would be a breaking change or not

**Comment by caripizza** [comment]
@driskull @jcfranco @paulcpederson looks like we're going to need to update the Sass variables' hex values in the table above over in calcite-colors. Then, cut a new release and consume that version here in cc.

Should all issues tied to this effort (ie., in both repos) have a "breaking change" label?

**Comment by driskull** [comment]
> Should all issues tied to this effort (ie., in both repos) have a "breaking change" label?

Yes, if they are breaking changes. I'm not sure the calcite-components would be breaking though.

**Comment by paulcpederson** [comment]
yeah we'd have to update the theme mixins in calcite-colors to change these. Theoretically no updates on the calcite components side should be required other than updating the calcite colors lib?

**Comment by caripizza** [comment]
https://github.com/Esri/calcite-colors/pull/71 has been installed, just need to cut a new release. I'll work with Paul on this after next week. (Then we can use this issue to track consuming the updated version.)

**Comment by macandcheese** [comment]
What's the status of this? Would be great to get the correct values in there, it's a little weird now when switching between dark and light theme in a UI: https://jmp.sh/k0OOfHQ

**Comment by caripizza** [comment]
@macandcheese just waiting on a new release of calcite-colors [per my comment in the linked issue](https://github.com/Esri/calcite-colors/issues/68#issuecomment-880827606)  cc @paulcpederson

**Comment by julio8a** [comment]
I can help publish. I'm looking at the latest for calcite-colors and it's [6.0.0](https://github.com/Esri/calcite-colors/blob/master/package.json#L3), same as on NPM. Does that need to be updated before publishing a new version?

**Comment by driskull** [comment]
> I can help publish. I'm looking at the latest for calcite-colors and it's 6.0.0, same as on NPM. Does that need to be updated before publishing a new version?

Yes.

**Comment by driskull** [comment]
https://github.com/Esri/calcite-colors/blob/master/CONTRIBUTE.md#releasing-a-version

**Comment by caripizza** [comment]
Verified on [`1.0.0-next.266`](https://unpkg.com/@esri/calcite-components@1.0.0-next.266/dist/calcite/calcite.css), the new border var values appear as:

```scss
.calcite-theme-light {
  ...
  --calcite-ui-border-2: #d4d4d4; /* (was #dfdfdf) */
  --calcite-ui-border-3: #dfdfdf; /* (was #eaeaea) */
  ...
}
  
.calcite-theme-dark {
  ...
  --calcite-ui-border-1: #555555; /* (was #4a4a4a) */
  --calcite-ui-border-2: #4a4a4a; /* (was #404040) */
  --calcite-ui-border-3: #404040; /* (was #353535) */
  ...
}  
```
