### ISSUE TITLE
Bug: [calcite-input] inconsistent value when setting ""

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2060]
### Actual Behavior

`<calcite-input>` behaves inconsistently depending on when value is set to "".

### Expected Behavior

When initially set to "", value will be null. Later on, if you set the value prop to "", value will be "" instead of null (as it was in the beginning).

### Reproduction Steps or Sample

https://codepen.io/jcfranco/pen/rNjRKPO?editors=1000

### Relevant Info

_Version_: `@esri/calcite-components@next.175`

- [x] CDN
- [ ] NPM package

**Comment by eriklharper** [comment]
@jcfranco should a falsy value always be `""` or `null'?

**Comment by jcfranco** [comment]
IMO, it should be `null` meaning there's no number set.

**Comment by jcfranco** [comment]
Verified with issue test case.
