### ISSUE TITLE
Bug: calcite-block - gray border is on left for both LTR and RTL

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2062]
LTR:
![image](https://user-images.githubusercontent.com/44481292/116283174-6d64cc00-a740-11eb-8a7d-a28bc943555c.png)

RTL, border should be on the right
![image](https://user-images.githubusercontent.com/44481292/116283246-82d9f600-a740-11eb-8181-5c4f7c7ce26a.png)

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by macandcheese** [comment]
Related - can we just remove that border entirely from block edges and have it set on panel? https://github.com/Esri/calcite-components/issues/1931

**Comment by asangma** [comment]
The border is now removed and shouldn't be an issue anymore.
Please reopen if this persists.

**Comment by AdelheidF** [comment]
Yes, no more border.

![image](https://user-images.githubusercontent.com/44481292/118189323-79b27f80-b3f6-11eb-8ca1-2c6fe20e0e55.png)
