### ISSUE TITLE
Tailwind: update to v3

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2078]
**Summary**
Update TailwindCSS in calcite-components from v1.9.6 to v3.0:

**Relevant Info**
- upgrade guide: https://tailwindcss.com/docs/upgrading-to-v2
- https://github.com/tailwindlabs/tailwindcss/blob/v2.0.0/CHANGELOG.md
- https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.0.0

**Comment by benelan** [comment]
This has been installed for a week there have not been any reports of build or visual issues. I'm closing this as verified, thanks for doing this Matt!
