### ISSUE TITLE
Enhancement: Add Large size for Tree

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2080]
**Summary**
Add Large size option to the Tree component's [`scale`](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-tree/calcite-tree.tsx#L50) property.

**Design mockups:**
![image](https://user-images.githubusercontent.com/14083530/116614898-245b7600-a900-11eb-8635-361aac1ea52f.png)

**Comment by bstifle** [comment]
![Tree-specs](https://user-images.githubusercontent.com/14083530/116724825-bd44cc80-a9a6-11eb-9028-fb2dbdb128e3.png)


Tree Specs!

**Comment by julio8a** [comment]
Verified on master demo pages.
