### ISSUE TITLE
Enhancement: Selection visuals for Tree

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2082]
Remove left-hand bar single selection active state style:
![image](https://user-images.githubusercontent.com/14083530/116617741-d183bd80-a903-11eb-82ac-d0fbaa14df23.png)

- Replace with circle (radio) visual
- Have ability to have multi select with checkmarks
- have ability to style multi select using `calcite-checkbox` including all available states such as idle, hover, selected, and indeterminate. Checkbox should give the ability to select an entire parent/group and its children
![image](https://user-images.githubusercontent.com/14083530/116618761-19571480-a905-11eb-8894-a9f52817488d.png)

**Comment by bstifle** [comment]
![Uploading Tree Specs.png…]()

**Comment by bstifle** [comment]
![Tree Specs](https://user-images.githubusercontent.com/14083530/116725789-0b0e0480-a9a8-11eb-83ca-5b2e06e5d479.png)

**Comment by macandcheese** [comment]
Comps look good, great alignment

🔲🔲
🔲🔲


It seems like the "checkbox" design functions differently than "check icon" - are parent-level items not selectable in that mode?

**Comment by bstifle** [comment]
to my understanding no, which is kind of a neat differentiator imo

**Comment by macandcheese** [comment]
Ok, it might be worth looking how these three layouts map to all 5 of the selection-modes, and how it interacts with the show-input prop (if they need to both still remain)?

If we can make that decision for them based on mode, we'll have less of a tree-mode-potpourri across our apps. Just props for theme, lines, scale is nice.

**Comment by evanmosby** [comment]
Looking forward to these options with ArcGIS Monitor! Especially the center option (checks w/o box) for facet filter multi-select!

**Comment by caripizza** [comment]
Tree scales were installed in pr #2803.

Next I'll fine-tune the selection visuals with Bryan in Figma. We'll need to support all 5 of tree's selection-modes, which were implemented according to the specs here:
- https://www.w3.org/TR/wai-aria-practices-1.1/#:~:text=Selection%20in%20multi-select%20trees
- https://www.w3.org/TR/wai-aria-practices-1.1/#:~:text=Alternative%20selection%20model%20--%20Moving%20focus%20without%20holding%20the%20Shift%20or%20Control%20modifier%20unselects

(Descriptions and screenshot examples for our current tree behavior in each selection-mode can be found [in the markdown table here](https://github.com/Esri/calcite-components/pull/2803#issue-711740128).)

**Comment by caripizza** [comment]
@bstifle I'm blocked on this one until I know what tree should look like in all 5 selection modes. Can you please clarify?

**Comment by bstifle** [comment]
@caripizza 

![image](https://user-images.githubusercontent.com/14083530/129976991-0cb0a541-6715-430b-9bfa-c4214226309d.png)
https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1183%3A21400

**Comment by benelan** [comment]
Verified on storybook after beta.64 release. Awesome stuff!
https://esri.github.io/calcite-components/?path=/story/components-tree--simple
