### ISSUE TITLE
Bug: Check for `ResizeObserver` existence before using it

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#2086]
### Actual Behavior

Check that `ResizeObserver` exists before trying to use it, this is to support an issue that came in from a customer that still uses Firefox 68 where `ResizeObserver` is not supported

cc: @driskull 

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by caripizza** [comment]
Since we only support [the last 2 versions of Firefox](https://github.com/Esri/calcite-components#browser-support), can you clarify why this was opened?

**Comment by kevindoshier** [comment]
https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/35135

**Comment by driskull** [comment]
I'm actually kind of torn on this issue. I'm leaning toward the solution that MapViewer needs to use a polyfill to get this supported. We won't be able to get it to work without a polyfill. I'm thinking we don't want to do anything and continue to show the error so that the app is aware that they should provide a polyfill here.

**Comment by driskull** [comment]
@kevindoshier assigning back to you for now. Our support says we only support the last two versions so if an app needs to support an earlier version then a polyfill needs to be provided.

@jcfranco @paulcpederson @macandcheese let me know your thoughts here.

I could do the following, but then it would just break functionality.

```tsx
resizeObserver =
    "resizeObserver" in window
      ? new ResizeObserver((entries) => this.resizeHandlerEntries(entries))
      : null;
```

**Comment by driskull** [comment]
What we can do, is document some of the browser functionalities that components need. Like resizeObserver, mutationObserver.

**Comment by kevindoshier** [comment]
The only polyfill I've found is this one

https://www.npmjs.com/package/resize-observer-polyfill#usage-example

**Comment by kevindoshier** [comment]
Using the polyfill in the app appears to work fine,  Ill close this
