### ISSUE TITLE
Final Design Review for Refactored Components

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2088]
Design Audit of refactored components related to #1500 

WIll be doing in-depth visual review of each component.

Final signoff of Design for refactor.

Goal is for implementation to match Figma

- [ ]  Accordion
- [ ]  Alert
- [ ]  Avatar
- [ ]  Button
- [ ]  Card
- [ ]  Checkbox
- [ ]  Chip
- [ ]  Color Picker
- [ ]  Combobox
- [ ]  Date Picker
- [ ]  Dropdown
- [ ]  FAB
- [ ]  Icon
- [ ]  Inline Editable
- [ ]  Input
- [ ]  Label
- [ ]  Link
- [ ]  Loader
- [ ]  Modal
- [ ]  Notice
- [ ]  Pagination
- [ ]  Popover
- [ ]  Progress
- [ ]  Radio Button
- [ ]  Radio Button Group
- [ ]  Radio Group
- [ ]  Rating
- [ ]  Scrim
- [ ]  Select
- [ ]  Slider
- [ ]  Split Button
- [ ]  Stepper
- [ ]  Switch
- [ ]  Tabs
- [ ]  Tile Select Group
- [ ]  Tile Select
- [ ]  Tile
- [ ]  Tooltip
- [ ]  Tree
- [ ]  Action Bar
- [ ]  Action Pad
- [ ]  Action
- [ ]  Block
- [ ]  Flow
- [ ]  Panel
- [ ]  Pick List
- [ ]  Shell
- [ ]  Tip Manager
- [ ]  Tip
- [ ]  Value List

**Comment by julio8a** [comment]
Can we use #1500 instead since that's the epic for the refactor?
We also have the Figma project.  https://github.com/Esri/calcite-components/projects/14

**Comment by bstifle** [comment]
yeah this is redundant
