### ISSUE TITLE
Refactor: calcite-input tests show 'The state/prop "value" changed during rendering' warnings 

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2091]
## Summary

Test runs show the following warnings:

```
PASS src/components/calcite-input/calcite-input.e2e.ts (329.206 s)
376 ● Console
377
378 console.warn
379 STENCIL: The state/prop "value" changed during rendering. This can potentially lead to infinite-loops and other bugs. 
380 Element JSHandle@node 
381 New value 
382 Old value 
383 Location: http://localhost:3333/build/index-09c7248a.js:2710:70
384
394 console.warn
395 STENCIL: The state/prop "localizedValue" changed during rendering. This can potentially lead to infinite-loops and other bugs. 
396 Element JSHandle@node 
397 New value 
398 Old value 
399 Location: http://localhost:3333/build/index-09c7248a.js:2710:70
```

## Additional Info 

probably related to this? https://github.com/Esri/calcite-components/pull/2036/files#diff-d4e9e38d573f92a6608141863d1a3ce63b4cc9c7bc0b97585e8a91c48ac9a705R286

**Comment by eriklharper** [comment]
This is caused anytime a number input's `.value` is set on the input programmatically to an invalid number, which resets the number back to the previous value, which one of the tests is doing.  I don't know why Stencil complains about this and if there is another way to implement this without triggering the warning, but I can look into it.

**Comment by jcfranco** [comment]
Changed the title, milestone and priority of this one since it's not an unstable test.

**Comment by jcfranco** [comment]
Warnings are no longer observed with the latest codebase. Closing!
