### ISSUE TITLE
Bug: Calcite label spacing bug in Safari

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#2092]
In Safari, grid spacing does not seem to be applied to elements wrapped in a calcite-label.

Seems to not have x or y spacing, across the three label layouts (inline, inline-space-between, default)

### Actual Behavior

Screenshots from Storybook:
Chrome left, Safari center, Firefox right

![Screen Shot 2021-05-04 at 10 32 14 AM](https://user-images.githubusercontent.com/4733155/117045580-83383b00-acc4-11eb-9aa9-cbc69d99e932.png)
![Screen Shot 2021-05-04 at 10 20 50 AM](https://user-images.githubusercontent.com/4733155/117045592-86332b80-acc4-11eb-8515-500f2b6048cf.png)
![Screen Shot 2021-05-04 at 10 21 38 AM](https://user-images.githubusercontent.com/4733155/117045593-87645880-acc4-11eb-83b4-2ef0955677d4.png)
![Screen Shot 2021-05-04 at 10 22 04 AM](https://user-images.githubusercontent.com/4733155/117045595-87645880-acc4-11eb-906a-f8c889e60325.png)

### Reproduction Steps or Sample

Storybook exhibits behavior above.

### Relevant Info
Experienced in Safari Version 14.0 (14610.1.28.1.10)

_Version_: `@esri/calcite-components@<version>`

Not sure what Storybook is referencing.
- We should display the version Storybook references on the sidebar / header / somewhere.

**Comment by bpatterson88** [comment]
Updating to Safari 14.1 fixes this issue. Apparently earlier versions of Safari do not support `gap` when used with `flex`, despite supporting it when used with `grid`. Interesting blog post on the issue: https://www.falldowngoboone.com/blog/the-curious-case-of-flexbox-gap-and-safari/

<img width="388" alt="Screen Shot 2021-05-11 at 3 53 07 PM" src="https://user-images.githubusercontent.com/15875886/117894339-ffa4be00-b270-11eb-8ecf-c5d06237afea.png">

**Comment by macandcheese** [comment]
@bpatterson88 nice diggin’

**Comment by macandcheese** [comment]
Tested in latest Safari and this is no longer an issue.
