### ISSUE TITLE
Bug: calcite-combobox:  long strings arent formatted correctly

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#2096]
### Actual Behavior

calcite-combobox:  long strings arent formatted correctly

![image](https://user-images.githubusercontent.com/11093161/117064249-c8fffe00-acda-11eb-8a4a-b1dc2c9dce05.png)

### Expected Behavior

Shouldnt mess up the formatting of the combobox

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by driskull** [comment]
@julio8a who would this be for?

**Comment by julio8a** [comment]
Does this look like this might be part of refactoring? @caripizza 

If it is, we should add it to that refactor epic.

**Comment by driskull** [comment]
I think we should elevate this, mapviewer can't use this for layer selector until this is fixed. @julio8a @jcfranco @caripizza

**Comment by jcfranco** [comment]
@driskull @kevindoshier Does this codepen represent the issue? https://codepen.io/jcfranco/pen/YzZOXNp?editors=1000

**Comment by driskull** [comment]
@jcfranco yes but also when the selection mode is single

**Comment by jcfranco** [comment]
Got it. Thanks for the info. Adding it to this sprint as `help wanted`. cc @caripizza

**Comment by driskull** [comment]
I think a designer needs to take this issue since it's mostly a design decision on what to do and then updating the SCSS.

**Comment by caripizza** [comment]
@kevindoshier @driskull Can you please add the code snippet that shows the issue? I'm having trouble replicating

**Comment by kevindoshier** [comment]
Doesnt this one reproduce it?

https://github.com/Esri/calcite-components/issues/2096#issuecomment-858050015

**Comment by caripizza** [comment]
Thanks @kevindoshier, I missed that comment. Can you add repro steps to the Description to help make it more clear? Or is this just a question of what it should look like when it's refactored to wrap?

**Comment by kevindoshier** [comment]
Its just about needing it to be styled correctly

**Comment by bstifle** [comment]
Couple of options for this:

![image](https://user-images.githubusercontent.com/14083530/122080636-09679700-cdc4-11eb-81ad-bbcb2943e58e.png)

**Comment by caripizza** [comment]
@driskull - I chatted with @bstifle about this just now. What if we just truncate the selected item's text label with ellipses ("...") if it's over 25 characters long?

```js
private trimLabels = (textLabel, chars = 25) => {
  return textLabel.length > chars ? textLabel.substring(0, chars) + "..." : textLabel;
};
```

Here's what that looks like on master without any extra styles:
![image](https://user-images.githubusercontent.com/42423180/122084364-9c99d000-cdb6-11eb-80ca-3f7d6c5bdde5.png)


The list item would still show the full label text like so:

![image](https://user-images.githubusercontent.com/42423180/122084397-a4597480-cdb6-11eb-99a2-6ee1564e7c45.png)

![image](https://user-images.githubusercontent.com/42423180/122084426-aa4f5580-cdb6-11eb-845f-c37bb8360bf5.png)

![image](https://user-images.githubusercontent.com/42423180/122084448-b0453680-cdb6-11eb-81d8-794e3f1ff66d.png)

Here's the markup I used for these screenshots:
```html
    <div style="width:350px;margin-left:1rem;">
      <h3>Multi</h3>
      <calcite-combobox
        label="demo combobox 1"
        selection-mode="multi"
        allow-custom-values
      >
        <calcite-combobox-item value="Trees" text-label="Trees">
          <calcite-combobox-item
            value="CommercialDamageAssessment - Damage to Commercial Buildings & Damage to Commercial Buildings"
            text-label="CommercialDamageAssessment - Damage to Commercial Buildings & Damage to Commercial Buildings"
            selected
          ></calcite-combobox-item>
          <calcite-combobox-item
            value="Sequoia"
            disabled
            text-label="Sequoia"
          ></calcite-combobox-item>
          <calcite-combobox-item
            value="Douglas Fir"
            text-label="Douglas Fir"
          ></calcite-combobox-item>
        </calcite-combobox-item>
      </calcite-combobox>
    </div>

    <div style="width:350px;margin-left:1rem;">
      <h3>Ancestors</h3>
      <calcite-combobox
        label="demo combobox 2"
        selection-mode="ancestors"
        allow-custom-values
      >
        <calcite-combobox-item value="Trees" text-label="Trees">
          <calcite-combobox-item
            value="CommercialDamageAssessment - Damage to Commercial Buildings & Damage to Commercial Buildings"
            text-label="CommercialDamageAssessment - Damage to Commercial Buildings & Damage to Commercial Buildings"
            selected
          ></calcite-combobox-item>
          <calcite-combobox-item
            value="Sequoia"
            disabled
            text-label="Sequoia"
          ></calcite-combobox-item>
          <calcite-combobox-item
            value="Douglas Fir"
            text-label="Douglas Fir"
          ></calcite-combobox-item>
        </calcite-combobox-item>
      </calcite-combobox>
    </div>

    <div style="width:350px;margin-left:1rem;">
      <h3>Single</h3>
      <calcite-combobox
        label="demo combobox 3"
        selection-mode="single"
        allow-custom-values
      >
        <calcite-combobox-item value="Trees" text-label="Trees">
          <calcite-combobox-item
            value="CommercialDamageAssessment - Damage to Commercial Buildings"
            text-label="CommercialDamageAssessment - Damage to Commercial Buildings"
            selected
          ></calcite-combobox-item>
          <calcite-combobox-item
            value="Sequoia"
            disabled
            text-label="Sequoia"
          ></calcite-combobox-item>
          <calcite-combobox-item
            value="Douglas Fir"
            text-label="Douglas Fir"
          ></calcite-combobox-item>
        </calcite-combobox-item>
        <calcite-combobox-item
          value="Rivers"
          text-label="Rivers"
        ></calcite-combobox-item>
      </calcite-combobox>
    </div>
```

cc @macandcheese @bpatterson88

**Comment by driskull** [comment]
That sounds reasonable to me.

**Comment by driskull** [comment]
Maybe make this a domUtil as well?

```
export const truncate = (text: string, chars = 25) => {
  return text.length > chars ? text.substring(0, chars) + "&hellip;" : text;
};
```

**Comment by driskull** [comment]
@caripizza actually, can we just use CSS to do this? Seems like we can just use the `truncate` tailwind class and set a max-width on the tags and selected item?

**Comment by caripizza** [comment]
@driskull I think with just CSS, we'd have to make sure the chip's close button stays visible too. I prefer the domUtil approach, since many components could opt into this trim pattern.

**Comment by driskull** [comment]
I think we can do that with css still. The text already has a container inside the chip.

**Comment by caripizza** [comment]
@driskull can I assign this to you then? It sounds like you got it working

**Comment by driskull** [comment]
Installed.

**Comment by julio8a** [comment]
Verified on master.
