### ISSUE TITLE
Question: calcite-combobox programatically select a item

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#2097]
### Question

I have a use case where I need to change the selection of the clacite-combobox from outside of the combobox, is there a way to do this?

**Comment by driskull** [comment]
@kevindoshier if you create the combobox with the items marked as selected does that work? The way it should work is like any select element, the item elements should be able to be toggled via their selected property.

**Comment by kevindoshier** [comment]
@driskull - yeah that works fine, but I have the case where Im switching the layerSwitcher to use the combobox and I need to keep the selection in the combobox in sync with the layerList, so if a layer is selected in the layerList I need to update the selection in the combobox

**Comment by driskull** [comment]
@kevindoshier does it not work when modifying an item's selected property at that time?

**Comment by kevindoshier** [comment]
@driskull - yeah that will update the selection (the blue dot) but not this part of the combobox

![image](https://user-images.githubusercontent.com/11093161/117082533-6701c180-acf7-11eb-801f-575c1e2e79f1.png)

**Comment by driskull** [comment]
Ok makes sense. Seems like a bug :)

**Comment by kevindoshier** [comment]
@driskull - thanks, ill add an issue for that one

**Comment by driskull** [comment]
addressed in https://github.com/Esri/calcite-components/issues/2102
