### ISSUE TITLE
Bug: ValueListItem drag-handle is the wrong color

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2098]
### Actual Behavior
The icon in a value-list-item is incorrect.

### Expected Behavior
The icon should be 

| state | color |
|-----|-------|
| idle | border-color-3 |
| hover | text-color-1 |
| activated | text-color-1 |

cc @bstifle 

### Reproduction Steps or Sample

1. view `demos/value-list/advanced.html`

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by asangma** [comment]
Mind verifying this one?

**Comment by asangma** [comment]
@julio8a Mind verifying this one?

**Comment by bstifle** [comment]
@asangma should be border-1 #CACACA on idle 😇

**Comment by julio8a** [comment]
Based on Bryan's comment, should I wait to verify then?

**Comment by asangma** [comment]
See new PR.

**Comment by asangma** [comment]
Updated with border-1

**Comment by asangma** [comment]
Thanks for catching that @bstifle!

**Comment by julio8a** [comment]
Nice! thank @asangma. Verified on master.
