### ISSUE TITLE
Bug: calcite-combobox- updating the selected item doesnt update the "title" of the combobox

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#2102]
If I update the selected item for the combobox, the title of the combobox doesnt seem to reflect the change, it remains to be the previously selected item

https://github.com/Esri/calcite-components/issues/2097

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by driskull** [comment]
@paulcpederson this is because the 'calciteComboboxItemChange' doesn't fire unless a combobox item is clicked. Do you know why?

**Comment by driskull** [comment]
Related to the discussion in #2033

In the components i've worked on i've just had a watcher that emits so that its always 1:1 (all prop changes are emitted no matter how they changed).

So we need a pattern defined I guess.

**Comment by paulcpederson** [comment]
Is this in a particular selection mode? https://codepen.io/paulcp/pen/xxqxqOG?editors=1010 changing selected on an item should update the displayed chips, etc

**Comment by driskull** [comment]
Like this:
https://codepen.io/driskull/pen/NWpWpZm?editors=1010

**Comment by driskull** [comment]
If you try the codepen I provided you see it's all messed up :\

**Comment by paulcpederson** [comment]
Oh of course, right. Yeah I think the combobox item's change event is not propagated outside the tree, so it's probably safe to  emit that on changes to the property.

**Comment by julio8a** [comment]
Verified with latest on Codepen.
