### ISSUE TITLE
Bug: calcite-action-group - using menu-tooltip slot doesnt show the tooltip on hover of the overflow action

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#2103]
Im placing a calcite-tooltip into the "menu-tooltip" slot of a calcite-action-group, but when hovering on the overflow action the tooltip is not being shown

![image](https://user-images.githubusercontent.com/11093161/117165685-8f7ecf80-ad7a-11eb-9756-2203b0d56da5.png)

### Expected Behavior

A tooltip for the overflow action should show up when hovering similiar to how the expand action works

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by driskull** [comment]
@AdelheidF @kevindoshier installed. Can you let me know once 'next' is built?

**Comment by AdelheidF** [comment]
I'm using `next.194` and I still see no tooltips, in all 3 different ways I tried before.

**Comment by driskull** [comment]
@AdelheidF do you have a sample I can look up? Maybe this is a separate issue to open.

**Comment by AdelheidF** [comment]
```
  private renderTest() {
    return (
      <div
        id="content"
        ref={
          () => {
            console.log(
              this.hostElement.shadowRoot.getElementById("program-button"),
              this.hostElement.shadowRoot.getElementById("body-button")
            );
            // -> null, null

            const tooltip2: HTMLCalciteTooltipElement = document.createElement("calcite-tooltip");
            tooltip2.placement = "auto";
            tooltip2.label = "body";
            tooltip2.referenceElement = document.getElementById("body-button");
            tooltip2.innerHTML = "body";
            document.body.appendChild(tooltip2);
          }
        }
      >
        <calcite-tooltip-manager>
          <calcite-button
            id="program-button"
            ref={(node: HTMLElement) => {
              console.log("button created", this.hostElement.shadowRoot.getElementById("content"));
              // -> null

              setTimeout(() => {
                console.log("waited", this.hostElement.shadowRoot.getElementById("content"));
                // -> returns node

                const tooltip: HTMLCalciteTooltipElement = document.createElement(
                  "calcite-tooltip"
                );
                tooltip.placement = "auto";
                tooltip.label = "program";
                tooltip.referenceElement = node;
                tooltip.innerHTML = "program";
                this.hostElement.shadowRoot.getElementById("content")?.appendChild(tooltip);
                // -> tooltip node has a valid size, but it never opens when I hover
              }, 2000);
            }}
          >
            program button
          </calcite-button>
          <calcite-button id="body-button">body button</calcite-button>
          <calcite-button id="inline-button">inline button</calcite-button>
        </calcite-tooltip-manager>
        <calcite-tooltip placement="auto" referenceElement="inline-button" label="inline">
          inline
        </calcite-tooltip>
      </div>
    );
  }
```

**Comment by driskull** [comment]
@AdelheidF can you verify that this line is actually finding the element? `tooltip2.referenceElement = document.getElementById("body-button");`

**Comment by AdelheidF** [comment]
I added a timeout now with the same result. I updated the code above for the test case.

**Comment by AdelheidF** [comment]
I fixed that mistake and the tooltip on the document body is working now. The other 2 ways don't work. This means if the reference button gets removed I have to make sure the tooltip gets removed as well.

**Comment by driskull** [comment]
Ok I have a fix for that I think @AdelheidF. I'll have another PR coming.

**Comment by driskull** [comment]
@AdelheidF installed. Let me know once next 196 is available.

**Comment by AdelheidF** [comment]
Nice, all 3 ways are working with next.197.

**Comment by driskull** [comment]
Awesome. I'll let @kevindoshier verify as well.

**Comment by julio8a** [comment]
Verified on master. Closing.
