### ISSUE TITLE
Tooling: add Eslint rule to check for `dir=` attribute set directly on Host

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2109]
## Summary 
When the `dir` attribute is applied directly onto Host components, it causes issues when the component needs to inherit the attributes from further up the DOM tree (ie., overriding it becomes difficult).

## Measure of Success 
A new Eslint rule will catch when the `dir=` attribute is set directly on Host components in .tsx files.

### Background
This is a follow-on that we're hoping will help us verify all changes from Epic #1831.

**Comment by driskull** [comment]
After looking into this, i think maybe the commonTest will be enough. We would have to create a custom ESLint plugin to handle this and it doesn't seem to be worth the effort. Thoughts?

**Comment by caripizza** [comment]
@driskull that works for me, I'll close this one.
