### ISSUE TITLE
Bug: calcite-tree ancestry mode - setting `selected` on nested `calcite-tree-item`s does not update lineage

### ISSUE THREAD

**Issue by stevenalbers** [Esri/calcite-components#2112]
Clicking on a nested tree item correctly manages the selected/indeterminate state of its parents:

<img width="400" alt="Screen Shot 2021-05-05 at 5 20 25 PM" src="https://user-images.githubusercontent.com/5317415/117369993-8f65f900-ae7a-11eb-90c3-1064ea54abb0.png">

But if you're generating a `calcite-tree` and you initialize it by setting `selected` on a nested item, its ancestry isn't being updated (In this case `Regional Deterministic Prediction System (RDPS) [10 km]` should be shown as indeterminate:

<img width="625" alt="Screen Shot 2021-05-05 at 4 51 49 PM" src="https://user-images.githubusercontent.com/5317415/117370001-90972600-ae7a-11eb-9f24-c6692b3bd3fc.png">

What's interesting is that `Regional Deterministic Prediction System (RDPS) [10 km]` knows it has selected children (the text is bold), but the checkbox didn't get the memo.

@paulcpederson

**Comment by jcfranco** [comment]
@paulcpederson @caripizza Can either of you look at this for the incoming sprint?

**Comment by caripizza** [comment]
@jcfranco yep I can!

**Comment by benelan** [comment]
verified locally on master in the `calcite-tree-scales` demo page. @caripizza, should that page be added to the demo `index` file? If so I can do that.

**Comment by benelan** [comment]
Or at least linked to in the tree demo page?

**Comment by caripizza** [comment]
> should that page be added to the demo index file?

@benelan yep we can handle that in #2622 if that sounds good to you?

**Comment by benelan** [comment]
@caripizza sounds great, thanks!
