### ISSUE TITLE
Enhancement: Allow icon size and position customizations for Tiles

### ISSUE THREAD

**Issue by mitc7862** [Esri/calcite-components#2113]
### Description
In order to launch the item details page/REST endpoint of a layer from within Map Viewer, I need the ability to add a launch indicator at the end of the tile

Existing component design:
![image](https://user-images.githubusercontent.com/12564905/117382911-60f51780-ae94-11eb-9c14-490492904306.png)

Proposed variant:
![image](https://user-images.githubusercontent.com/12564905/117382835-3f942b80-ae94-11eb-8ea1-f94db3e9f4ba.png)

Two possible resolutions could be:
- Add a slot at the end of the tile where we can add an indicator
- Allow resizing or repositioning of the existing tile icon (currently it always shows with size L)

### Acceptance Criteria 
- Ability to add an indicator (icon) at the end of a tile
- Allow an icon to be added inline within the description body

#### Which Component
Tile

#### Example Use Case
![image](https://user-images.githubusercontent.com/12564905/117382808-2c815b80-ae94-11eb-8c35-5623d22f9bd8.png)

**Comment by bstifle** [comment]
Cool! propose calling this variant `icon-end` and the original layout 'icon-start`

**Comment by jcfranco** [comment]
I find `icon-start`/`icon-end` a bit misleading, since `start` is more of on top. Would there be cases where you'd need both the top and end icons?

**Comment by jcfranco** [comment]
@bstifle @mitc7862 Could you confirm whether ☝🏼  is possible with the proposed changes?

**Comment by bstifle** [comment]
> I find `icon-start`/`icon-end` a bit misleading, since `start` is more of on top. Would there be cases where you'd need both the top and end icons?

No just one or the other. 

> Could you confirm whether ☝🏼 is possible with the proposed changes?

Just icon-top or icon-end, not at the same time :)

**Comment by jcfranco** [comment]
Moving to next sprint. Draft PR should be up today.

**Comment by jcfranco** [comment]
> Draft PR should be up today.

![starting-starting-now](https://user-images.githubusercontent.com/197440/129816084-b8216af8-c42f-43bc-b764-2b311b3ed0a2.gif)

**Comment by jcfranco** [comment]
Actually, going to put this on hold until we decide on the rules for when to use slots vs props for icons. cc @asangma @macandcheese

**Comment by asangma** [comment]
Per our recent sync, the proposal is to add a slot that can be used for that icon.
@mitc7862 This should enable your proposed design.

**Comment by jcfranco** [comment]
Installed.

**Comment by benelan** [comment]
Doesn't look quite right, I'm assigning it back to you @jcfranco.
```css
<script
  type="module"
  src="https://unpkg.com/@esri/calcite-components@1.0.0-next.280/dist/calcite/calcite.esm.js"
></script>
<link
  rel="stylesheet"
  type="text/css"
  href="https://unpkg.com/@esri/calcite-components@1.0.0-next.280/dist/calcite/calcite.css"
/>
```

**Comment by benelan** [comment]
[Verified](https://codepen.io/benesri/pen/RwgrjEx) on `1.0.0-beta.63`

**Comment by AdelheidF** [comment]
@mitc7862 do you still want the icon for the polygon layer? There is no good place for it yet.

![image](https://user-images.githubusercontent.com/44481292/134228293-4c6ec0df-a4ae-4dc5-97bc-8803b537e569.png)
