### ISSUE TITLE
New Component: CalciteList & CalciteListItem - general purpose list and list-item

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2117]
### Description
A general purpose list that enables users to construct list items that conform to Calcite styling.
The list will also replace the currently used functional component and act as a base for several other lists, e.g.

* ValueList
* ValueListItem
* PickList
* PickListItem
* Proposed FlowMenu & FlowMenuItem

#### User Stories
Any developer for whom our pre-baked list-item doesn't work.

### Acceptance Criteria 
* Allow non-breaking refactoring of ValueList, ValueListItem, PickList and PickListItem.
* Act as a base for building the proposed FlowMenu and FlowMenuItem

### Questions
* Should it include `filterEnabled`?
* Should it include `dragEnabled`?

### Helpful Details
Things like selected states can be handled at the app level (or internally) by utilizing the "content-start" and/or "content-end" slots. See below.

**Item structure**
```
<calcite-list-item label="candy" description="kingdom">

  <calcite-action icon="some-icon" label="finn" slot="actions-start" />
  <calcite-icon icon="some-icon" slot="content-start"  />
  <img src="http://www.fillmurray.com/g/140/100" slot="content-start" />

  <calcite-icon icon="some-icon" slot="content-end" />  
  <calcite-action icon="some-icon" label="jake" slot="actions-end" />

</calcite-list-item>
```

RENDERS THIS LAYOUT

![image](https://user-images.githubusercontent.com/12503298/117511922-7412f080-af43-11eb-97fd-13185f2ff6ec.png)

### Additional thoughts on UI and scale
We may want to add a **scale** property and adjust internal spacing and font size according to our existing scales. Maybe this is a later enhancement as it will probably require additional UI design cycles.

At least for V1, we can mimic what we currently have in PickList and ValueList.

**Comment by asangma** [comment]
@driskull Leaving the milestone up to you.

**Comment by driskull** [comment]
Moving this to next milestone

**Comment by asangma** [comment]
@julio8a @caripizza Could use this sooner rather than later. :)

**Comment by julio8a** [comment]
@jcfranco and I will be triaging issues tomorrow.

**Comment by driskull** [comment]
@asangma I'll start prioritizing it! Should start on it end of this week or early next week. Sorry for the delays.

**Comment by asangma** [comment]
Yeet!

**Comment by driskull** [comment]
@asangma about the "hit area". What should hitting the hit area do? Should each list item automatically have a hit area (button)? or should it depend on a property?

Should hitting the hit area toggle a property or just emit an event?

**Comment by asangma** [comment]
re: hit area.
Good questions.

I def think ListItem should have a hit area by default. It's primarily an interactive component. For read-only content, a user can use 

Here are my thoughts:
- ListItem should have a hit area by default as it should primarily enable _interaction_.
  - we should add a prop to disable that hit area
  - not sure whether prop should be something like `hit-area-enabled` defaulting to true or whether we should have an optional `hit-area-disabled` property. I am leaning toward the latter.
    - wrapping components can toggle this prop based on their needs, e.g. if they are disabled.
- Hit area should only emit an event (since this is a generic list item)

Regarding toggling a property when the hit area is triggered, I think we wouldn't do this.
A wrapping component (e.g. when we refactor PickListItem or ValueListItem to use ListItem) could listen for the click event and update accordingly:
- PickListItem could use "content-start" to add a check or bullet based on a `selected` property
- ValueListItem could add its own border based on a `selected` property
- Dev users can control if they want to do something else.

If this resonates, I will update the first comment.

**Comment by driskull** [comment]
> we should add a prop to disable that hit area

I'm hearing that we need a selectable prop? It would be better to add the functionality rather than remove it. What do you think?

**Comment by asangma** [comment]
> It would be better to add the functionality rather than remove it. What do you think?

To be clear, I am thinking more about having a **clickable area**. And the only behavior would be to emit an event upon click.

If "selectable" means having a selected state, it's probably something we'd not include here.

In cases like a list of items that let the user drill into a flow, the item should be clickable but not have a **selected state**.
In cases where there needs to be a selected state (i.e. value-list-item versus pick-list-item), the appearance of that state is gonna be case by case and probz better handled by a wrapping component.

In regards to whether the item is clickable by default, it seems like the majority of cases when we have lists in our interfaces, they're clickable (whether to trigger something or be selected).

That being if we're calling it a generic CalciteListItem, I guess it parallels a `<li>`. If that's the mental model, maybe you're right.

So, I could go either way as to whether it's "clickable" by default. I'm not sure if it's confusing or not to call it "selectable" though.

**Comment by driskull** [comment]
> To be clear, I am thinking more about having a clickable area. And the only behavior would be to emit an event upon click.

Yes, but to do that I need to either render a button or a div. We need a good prop to explain what this button is for.

**Comment by asangma** [comment]
I agree there should be a prop.

As far as the name of the prop, I honestly don't know if something like "selectable" is confusing if we're not also including a selected state. 

As far as whether it's on by default, seems like most uses of this thing will have it on, but I will defer to your judgement.

**Comment by driskull** [comment]
> As far as whether it's on by default, seems like most uses of this thing will have it on, but I will defer to your judgement.

It's just better to add functionality than to disable it.

> As far as the name of the prop, I honestly don't know if something like "selectable" is confusing if we're not also including a selected state.

What if we also included a selected state? Is there any use case where clicking the content should not toggle a selected state?

**Comment by TheBlueDog** [comment]
Here's an example of where we would use this...

Sorry if the context is cropped out, but this is a block in a trailing panel to show all of the arcade expression in your form. Clicking the expression applied/removes that expression from the selected form input (Note, this is a hack we had to do in order to make it selectable, but limit it to one and provide the ability to unselect it.) The chip inside the action shows the number of fields that use this expression. Clicking the action opens the list. HERE, you can easily remove this action from those other fields by clicking the action, however, clicking on the field name doesn't do anything.

![list-items](https://user-images.githubusercontent.com/5419306/121360643-98773980-c902-11eb-8b19-3735c8ae7199.gif)

**Comment by bstifle** [comment]
ooh thats fun @TheBlueDog love it

**Comment by ade10176** [comment]
<img width="347" alt="Screen Shot 2021-06-14 at 2 23 44 PM" src="https://user-images.githubusercontent.com/49533268/121961361-32345180-cd1c-11eb-8494-26c529de23df.png">
Hoping this is the right issue to add this use case. When the user hovers over an item, is it possible to support hover state on both label and action areas as one item vs separate?

**Comment by asangma** [comment]
@ade10176 Thanks for the comment.

For that use case, the icon would go into the content-end slot of this component.
If you need it for ValueListItem, you can put CalciteIcon (not CalciteAction) into the actions-end slot. You will need to add some styles to center and pad it though. Have a look at the Configure Fields in Map Viewer. :)

**Comment by asangma** [comment]
Assigning to myself for styling.

**Comment by julio8a** [comment]
Verified

**Comment by bstifle** [comment]
looking good @asangma !!!! ✅
