### ISSUE TITLE
Enhancement:   Allowing Calcite themes to be imported with class in addition to theme=""

### ISSUE THREAD

**Issue by ajoshipuraGH** [Esri/calcite-components#2121]
### Description
As of now we are importing themes with the attr theme="dark/light". This works for majority of the AEM components but when we use a style system we run into issues.  The style system can only be applied with a class:

eg:  if we need to add a dark style system: we would need to class="dark-mode" on the component.  

Would it possible to add this functionality?  At present we have to rewrite the css with the var()  instead of just adding the dark or light class

**Comment by caripizza** [comment]
Hi @ajoshipuraGH! Just posting an update here that @eriklharper brought up a similar issue up today in Teams. We'll be discussing this theme topic in our Thursday dev sync meeting agenda. Teams discussion is [here](https://teams.microsoft.com/l/message/19:e19ba3a68aa644f4a58f21e345228a61@thread.skype/1621377542616?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1621363130994&teamName=Calcite%20Design%20System&channelName=Pattern%20Discussion&createdTime=1621377542616).

**Comment by jcfranco** [comment]
@ajoshipuraGH I believe this landed in the [previous release](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#100-beta55-2021-05-24). Could you test using the updated `.calcite-theme--light` & `.calcite-theme--dark` classes?

**Comment by jcfranco** [comment]
I'm going to go ahead and close this one based on ☝🏼 . @ajoshipuraGH Please reopen if this needs following-up.
