### ISSUE TITLE
Enhancement: Improve color picker's thumb interaction

### ISSUE THREAD

**Issue by jul11557** [Esri/calcite-components#2122]
### Description
Update the color picker to keep track of movements outside of the color field and color ramp while the user's mouse is down. While holding down the selection control, accidentally dragging outside of the color field causes the selection within the color field to be lost. 

### Acceptance Criteria 
1. While holding down the selection control, no matter where the user's mouse is on screen, the selection should remain within the color ramp.
2. When the user moves their cursor in and out of the color field (while still holding down to grab) the picker should retain its selection.

### Relevant Info 
Current Behavior:
https://user-images.githubusercontent.com/83983300/117719737-bc344c00-b1ab-11eb-8755-a8c3c73556fc.mov

Example from Figma's color picker:
https://user-images.githubusercontent.com/83983300/117720066-31a01c80-b1ac-11eb-850a-152e77366ca9.mov

#### Which Component
Calcite Color Picker
https://developers.arcgis.com/calcite-design-system/components/color-picker/

#### Example Use Case
In ArcGIS Mission, people will use the color picker to change the color of a symbol or icon. They may choose to use a color at the edge of the color gradient (ex: white, #FFFFFF) and should be able to easily select a color from the color field or ramp without entering in an RGB or HSV value.

**Comment by jcfranco** [comment]
Installed. 

@jul11557 Could you help verify w/ `next` (should deploy in a little bit)?

**Comment by jcfranco** [comment]
Actually, we have a release coming out today, so you could also verify w/ the updated docs page. I'll let you know when it rolls out. Thanks!

**Comment by jul11557** [comment]
Awesome, thanks! Yes, I'll help verify when it's ready.

**Comment by jcfranco** [comment]
@jul11557 Docs page are updated now. Here's the color-picker story for verification: https://esri.github.io/calcite-components/?path=/story/components-controls-colorpicker--simple

**Comment by jul11557** [comment]
@jcfranco Verified — exactly what I was looking for. Works great!

**Comment by jcfranco** [comment]
Awesome, thanks!
