### ISSUE TITLE
Bug: calcite-tile has a max-width too small for max shell-panel width

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2123]
### Actual Behavior

Using `calcite-tile` in a `calcite-block` that's inside a `calcite-shell-panel` or when `calcite-tile` is inside a `calcite-popover` on a wide screen does not look correct because of a `max-width` that's too small.

![image](https://user-images.githubusercontent.com/44481292/118052787-3265b980-b338-11eb-9660-96fca75cc4e4.png)

![image](https://user-images.githubusercontent.com/44481292/117741854-3d91db80-b1b8-11eb-92e1-1f15add7f778.png)

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by asangma** [comment]
cc @AdelheidF Installed. :)

**Comment by AdelheidF** [comment]
Looks good. Thank you.

![image](https://user-images.githubusercontent.com/44481292/119911205-afcf2380-bf0d-11eb-8502-5cc84c000062.png)
