### ISSUE TITLE
Research: Should events be emitted by programmatic and/or user changes

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2125]
### Background 

Should events be emitted by programmatic and/or user changes.

Research how we should be emitting events for components. Should it be only for user interaction or when a property watcher is fired.

Come up with use cases for both if we can and decide on an approach for when we do one vs the other or if we only do one of them.

#2033 #2102 https://github.com/Esri/calcite-components/pull/2118/files

Our current Events readme is here for reference: https://github.com/Esri/calcite-components/blob/master/conventions/README.md#events

### Desired Outcome 

Update the developer guidelines for how and when to emit events.

https://github.com/Esri/calcite-components/blob/master/conventions/README.md#events

cc @jcfranco @paulcpederson @eriklharper @caripizza

**Comment by jcfranco** [comment]
FWIW, emitting input/change on user interaction follows [the HTML spec on input/change events](https://html.spec.whatwg.org/multipage/input.html#common-input-element-events):

> When the input and change events apply (which is the case for all input controls other than buttons and those with the type attribute in the Hidden state), the events are fired to indicate that the user has interacted with the control. The input event fires whenever the user has modified the data of the control. The change event fires when the value is committed, if that makes sense for the control, or else when the control loses focus. In all cases, the input event comes before the corresponding change event (if any).

#2033 has been updated accordingly.
