### ISSUE TITLE
Bug: <calcute-input type="number"> does not use native number input

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#2126]
### Actual Behavior

`<calcite type="number">` does not show the native numeric keypad on mobile devices.

### Expected Behavior

`<calcite type="number">` should show the native numeric keypad on mobile devices for better accessibility by using `<input type"number">` internally.

### Reproduction Steps or Sample

https://codepen.io/patrickarlt/pen/XWMmwPb

![Screenshot_20210511-143819](https://user-images.githubusercontent.com/378557/117888620-34137c80-b267-11eb-9092-3c7ed34e3bf6.png)
![Screenshot_20210511-143826](https://user-images.githubusercontent.com/378557/117888623-34ac1300-b267-11eb-8426-ca9a468a727b.png)

### Relevant Info

There are techniques for hiding the native controls here https://stackoverflow.com/a/4298216 and https://stackoverflow.com/questions/45396280/customizing-increment-arrows-on-input-of-type-number-using-css

Happens on all mobile devices.

_Version_: `@esri/calcite-components@v1.0.0-beta.54`

- [x] CDN
- [x] NPM package

**Comment by macandcheese** [comment]
> There are techniques for hiding the native controls here https://stackoverflow.com/a/4298216 and https://stackoverflow.com/questions/45396280/customizing-increment-arrows-on-input-of-type-number-using-css

The screenshot of the `calcite-input` above does have custom increment buttons - we already override the native ones.

As far as the "showing the number pad"... I think this is, partly, a mobile OS / browser-specific thing, although I discovered an oddity on the CC input.

AFAIK an input of type `number` doesn't bring up the "numpad" in Safari... BUT - it does seem like it _should_ bring up the "number and punctuation keyboard" vs. the "text keyboard" on iOS - Safari _doesn't_ use the "numpad" with input type of `number`, either with native input or our `calcite-input` component:

<img src="https://user-images.githubusercontent.com/4733155/117906882-9af65d00-b28a-11eb-939e-edbdd659c2ea.PNG" width="25%">
<img src="https://user-images.githubusercontent.com/4733155/117906886-9d58b700-b28a-11eb-8d0a-80d2fdbb9620.PNG" width="25%">

So, above, on Safari it does seem like the `calcite-input` brings up a different keyboard state than the native one, but neither bring up the "numpad".

To add, Safari _does_ use the "numpad" with input type of `tel` (both native and `calcite-input` work the same here, so it seems like we do pass the type correctly):
<img src="https://user-images.githubusercontent.com/4733155/117906990-d42ecd00-b28a-11eb-85c7-d0a4428771b7.PNG" width="25%">
<img src="https://user-images.githubusercontent.com/4733155/117906999-d5f89080-b28a-11eb-97b8-16e6d4ca41d2.PNG" width="25%">

Maybe there is something (pattern attribute ?) that on iOS allows Safari to render the "number and punctuation keyboard" and on Android, the "numpad"?
