### ISSUE TITLE
Bug: <calcite-input type="number"> allows non-numeric characters

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#2127]
### Actual Behavior

`<calcite type="number">` allows all non-numeric non-alphabet characters.

### Expected Behavior

`<calcite type="number">` should not even allow you to enter non numeric characters potential related to https://github.com/Esri/calcite-components/issues/2009

### Reproduction Steps or Sample

![2021-05-11_14-32-54 (1)](https://user-images.githubusercontent.com/378557/117889070-cae03900-b267-11eb-8f53-2813cd1341b2.png)

1. Configure a numeric input on https://esri.github.io/calcite-components/?path=/story/components-controls-input--with-label
2. Enter any combination of non `1-9a-zA-Z` characters.

### Relevant Info

Any

_Version_: `@esri/calcite-components@v1.0.0-beta.54`

- [x] CDN
- [x] NPM package

**Comment by macandcheese** [comment]
What browser was the above screenshot from? 

AFAIK each browser treats the number input field differently: only Chrome limits it to numbers (and "e") - calcite-input behaves this way in Chrome. 

In Safari and Firefox, native inputs are NOT limited to just numbers - you can enter anything, and calcite-input behaves this way too.

Related: https://github.com/Esri/calcite-components/issues/961#issuecomment-736720527

@eriklharper I see the addition in the above PR  - it could be a "feature" of our calcite-input in type="number" to behave in that way - but this is a departure from (bespoke) browser functionality.

**Comment by eriklharper** [comment]
Thanks for that added context @macandcheese .  I didn't realize the breadth of differences between browsers and this behavior.  Sounds like there is a big difference in opinion too when it comes to what a number input UI/UX _should_ be.  Honestly, I would love to remove all this keydown validation to prevent users from typing anything but valid number characters, but I might be in the minority on a decision like that.  It looks like Firefox's number input doesn't restrict you to typing a just single decimal, nor does it restrict typing a comma like Chromium does, and we have that kind of validation in there from my recent locale changes.

I'm super curious what others think about this issue?  @Esri/calcite-components-reviewers

**Comment by bstifle** [comment]
what about copy/pasting numbers into that field? if it has a comma, will it jack it up?

**Comment by eriklharper** [comment]
In Firefox the number `1,234.56` pastes verbatim in a number input.  In Chromium it strips the comma out, resulting in `1234.56`.

**Comment by eriklharper** [comment]
For locales, we support typing `,`, `.`, ` ` in addition to all the numbers of course, and there is extra validation put in there to ensure that the decimal separator can only be typed once, so in french you can only type `,` once in the number.

**Comment by eriklharper** [comment]
![image](https://user-images.githubusercontent.com/821864/118006987-979db880-b300-11eb-9854-a742561584cd.png)

Here's what a bunch of locale formats look like, with and without the `group-separator` option (thousandths character).

**Comment by raje9276** [comment]
@eriklharper what is the behavior with native numbers like Arabic? 

Does input accept native numbers like these
<html>
<body>


١ | ٢ | ٣ | ٤ | ٥ | ٦ | ٧ | ٨ | ٩
-- | -- | -- | -- | -- | -- | -- | -- | --



</body>
</html>

**Comment by eriklharper** [comment]
> @eriklharper what is the behavior with native numbers like Arabic?
> 
> Does input accept native numbers like these
> 
> ١	٢	٣	٤	٥	٦	٧	٨	٩

Doesn't look like it currently.  I see a brief flash of the arabic numerals on initial load, but it looks like one of our number validator functions ignores them so we'll have to convert the localized number characters back to english numbers to do the validation instead of validating the locale characters. Thanks for testing this!  I'll create a new issue that adds locale numeral support, and this will apply to all other languages that use different number characters as well.
