### ISSUE TITLE
Bug : dropdown. Items take DOM space when hidden

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#213]
When dropdown is not active, the items still take up space. This is 

Could be solved by setting height on `calcite-dropdown-wrapper` when `visibility:hidden`?
Note: no wrapper is added when there is only a single group.

![image](https://user-images.githubusercontent.com/12503298/68149938-9ca3cf80-fef3-11e9-9286-9acf25531868.png)
Note the scrollbar.

**Comment by macandcheese** [comment]
Can you provide a link to where this is happening? I can't reproduce the "parent scrollbar" behavior.
Also, can could you clarify what "Note: no wrapper is added when there is only a single group." means here?

@asangma

**Comment by macandcheese** [comment]
Fixed in https://github.com/Esri/calcite-components/pull/226, I tested this with a quick example div, let me know if the update doesn't solve for your use case when this next release goes out... @asangma
