### ISSUE TITLE
Bug: calcite-popover - close button in weird position

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2130]
It sounds like the current location of the close icon of a popover is by design. But it does look weird if the popover is a bit longer. 
If you still think the current behavior is how it should be, please close this issue...

This is a popover containing a div

![image](https://user-images.githubusercontent.com/44481292/117897152-ff0f2600-b276-11eb-89ca-96d0be884353.png)

This is a popover containing a panel

![image](https://user-images.githubusercontent.com/44481292/117896981-988a0800-b276-11eb-834b-54844b0f0b5f.png)

This is a popover containing a tile

<img src=https://user-images.githubusercontent.com/44481292/118016509-55797480-b30a-11eb-901a-02c5b23d3b58.png width=350/>

It would be nice if it were closer to the top-right like this design.

![image](https://user-images.githubusercontent.com/44481292/117897248-3b428680-b277-11eb-9750-bcfa7d101047.png)

To get this look currently I have to add a flow and a panel inside the popover, even for this small case here. E.g. similar to this one.

<img src=https://user-images.githubusercontent.com/44481292/118010858-4263a600-b304-11eb-9c0e-64065b5f670a.png width=450/>

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by bstifle** [comment]
Oh weird, yeah that close button should always be in the right-top corner

**Comment by asangma** [comment]
Thanks for the correction @bstifle.
Should take much to fix it.

**Comment by bstifle** [comment]
ok so after talking with julio and adam, i think we did that deliberately........ so maybe its not a mistake. just cant remember when we did that with the X haha.

**Comment by mitc7862** [comment]
@bstifle @julio8a @macandcheese 

This looks bad when the popover has more than one or two lines of text in it. Having an X in the corner of a dialog is a convention that's been around since GUI computers have existed… seems odd to decide to do it differently for this, doesn't _look_ very deliberate to me. 

Seems like the popover is used more like a dialog (modal, panel etc) and less like an alert or an in-line notice. Maybe it needs its own little header element to constrain the X, that way it can be consistent and not look bad when there's more text or images in the popover.

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/118186977-fa2bad00-b403-11eb-87ba-aac3c681f960.png)

u mean like this? we'd need to require a header at that point

**Comment by bstifle** [comment]
and if the header wrapped, youd get this, which to me is just fine

![image](https://user-images.githubusercontent.com/14083530/118187230-4c6cce00-b404-11eb-987a-b219875924e4.png)

**Comment by mitc7862** [comment]
Yeah, that's how header have behaved, so I'd be happy with something that

**Comment by bstifle** [comment]
ok then next problem, what if no header?

**Comment by mitc7862** [comment]
Maybe it could revert to what it's currently doing…

Also, not sure what should happen if the image slot id filled.
would the header be above the image or below?
![image](https://user-images.githubusercontent.com/12564905/118187763-42db6a00-b3f4-11eb-886b-b3bbd4e972cd.png)

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/118188344-d9fced80-b405-11eb-9cc3-7e582e34705b.png)
would be fine with this

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/118188667-5bed1680-b406-11eb-800d-3807a7eec890.png)
this fine too. no reservations

**Comment by asangma** [comment]
> ok then next problem, what if no header?

I set it up to do what it currently does when there's no heading (and thus no header).
I think the header-less design still works with the close button mimicking what Notice does.

re: image.
There's no image slot.

**Comment by asangma** [comment]
re: image.
There's no image slot.
That being said, a user can an image into the default slot and set its width to 100%, and it works nicely.

*ignore the heading size and weight here and the lack of border*
<img src="https://user-images.githubusercontent.com/12503298/119746932-77b0dd80-be46-11eb-8f64-c22b3395fcda.png" width="400" />

**Comment by asangma** [comment]
@bstifle Mind verifying this one?

**Comment by AdelheidF** [comment]
Tested with next.209

Now it doesn't set the focus anymore on the close button. This worked before this update.

calcite-tile
![image](https://user-images.githubusercontent.com/44481292/119911321-f6bd1900-bf0d-11eb-9a91-06e4b95d816e.png)

div
![image](https://user-images.githubusercontent.com/44481292/119911463-308e1f80-bf0e-11eb-8d01-2cc1b51d19b9.png)

**Comment by asangma** [comment]
@AdelheidF Thanks for catching the focus issue. I may need some help from @jcfranco or @driskull on that one.

**Comment by AdelheidF** [comment]
I tried `popover.heading` and wrapped the content text in a `calcite-label`. This did not work correctly because `calcite-label` didn't add the `<label>` element and so the styling is off. Is this expected?

<img src=https://user-images.githubusercontent.com/44481292/120027238-f96c4c80-bfa7-11eb-9466-5dcbbb325b33.png
 width=750/>

If I use a `div` as the content of the popover and copy the styles from `calcite-label` then it looks OK. But I'd rather use `calcite-label` directly.

![image](https://user-images.githubusercontent.com/44481292/120026298-b9f13080-bfa6-11eb-801d-1d57212ca901.png)

**Comment by asangma** [comment]
@AdelheidF This might need to be a different issue. Right now, the default slot of Popover is left unstyled to avoid conflict. A general solution for this might be a utility class or content component, but it's probably outside the scope of this issue.

**Comment by asangma** [comment]
@driskull Could use some help with the close button focus.

**Comment by macandcheese** [comment]
`calcite-label` isn't really meant to be used for displaying just text, instead it should be used when wrapping a control. Agree with Alan this could probably just be handled by styling a div or p tag with utility classes.

**Comment by driskull** [comment]
@asangma you probably need to call setFocus instead of focus here now that is an action. https://github.com/Esri/calcite-components/blob/3c2d9a4f2e85548fc34f23ccc1bc51c2b26e6594/src/components/calcite-popover/calcite-popover.tsx#L220

**Comment by asangma** [comment]
Thanks @driskull!

**Comment by asangma** [comment]
@driskull Still having some trouble here. Let me know if you have time Monday to look at it.

**Comment by driskull** [comment]
Yeah sounds good

**Comment by asangma** [comment]
setFocus for "close-button" should be working now.
@driskull Added you as an assignee if you feel like verfeeing.

**Comment by AdelheidF** [comment]
Focus is working again, thanks.
