### ISSUE TITLE
Enhancement: Add Tabs slot in Panel

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2131]
Idea to have Panels have Tabs built in via @TheBlueDog .

With the available props here are some quick mockups with tabs and how they can display within Panel:

![tabs panel](https://user-images.githubusercontent.com/14083530/118024597-7bac0e00-b324-11eb-858f-d29e83d9d57a.png)
![with actions](https://user-images.githubusercontent.com/14083530/118024589-7a7ae100-b324-11eb-8dcc-334e2a6007d2.png)

**Comment by mitc7862** [comment]
@bstifle Can we have the option to use icon-tabs too?

**Comment by TheBlueDog** [comment]
This feature would be useful in Field Maps!

**Comment by macandcheese** [comment]
Yeah this is nice, visual feedback for now is limited to spacing - it would be nice for the space between title / summary text and top of tabs, to match the space from the top of the panel to the top of title / summary area.

Would be curious to see how tabs with long titles (or more than 3) work with scrolling in panels, especially the smaller width instances.

This reminds me of this old request for a slotted calcite-stepper in the header of a modal, to use the bottom border similarly: https://github.com/Esri/calcite-components/issues/734

**Comment by bstifle** [comment]
![Frame 6](https://user-images.githubusercontent.com/14083530/118348397-9abac380-b50f-11eb-9e28-cc532bd320e0.png)


@macandcheese some ideas for tab overflow. I prefer the bottom one with the dropdown

**Comment by macandcheese** [comment]
Hrm… could it just scroll horizontally? Not ideal but neither is having a ton of tabbed content in a small space. That’s also how tabs currently work - in my mind having an ellipsis w overflow items potentially beneath another overflow menu could get dense.

Maybe we can just make a slight update to the current tabs to have some kind of visual indicator there are more w/in a horizontally scrollable container?

**Comment by bstifle** [comment]
sure that could work. just slap a scrolly on there

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/118532553-b212d000-b70c-11eb-9f31-18090381798f.png)

**Comment by macandcheese** [comment]
Yeah, not sure we need comps or anything in figma / sketch since scrolling is already a part of tabs? 

In the above, only the tab area would scroll - having the scroll bar under the back button insinuates the whole area is overflow-x.

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/118536250-1c2d7400-b711-11eb-91a6-bcc0ac8d4624.png)
better closer warmer

**Comment by bpatterson88** [comment]
Placing tabs in the panel header is a requirement for the new Arcade editor. It looks like the "Tabs only" option would work for our needs, but we would probably want the option to use medium tabs rather than large.

Current UI:
![Screen Shot 2021-06-01 at 3 48 30 PM](https://user-images.githubusercontent.com/15875886/120400437-ba653080-c2f2-11eb-84de-1569c4676f33.png)

What we'd like:
![Screen Shot 2021-06-01 at 3 50 52 PM](https://user-images.githubusercontent.com/15875886/120400452-c18c3e80-c2f2-11eb-83f0-da4180fe7d1e.png)

**Comment by TheBlueDog** [comment]
After doing some experimenting with adding tabs to existing panel header patters, got talking with @bpatterson88 and his need is for scale. Neither of our use cases have a need for Heading/Summary in addition to the tabs.

Proposing a simpler solution to implement... this would include the options for back button, actions, and dismiss-able.  There would be a new scale property for the header component that changes the scale of the tab set.

![Screen Shot 2021-06-04 at 7 43 43 AM](https://user-images.githubusercontent.com/5419306/120822802-c89a9300-c524-11eb-8fa2-391c5b441787.png)

**Comment by bstifle** [comment]
The horizontal misalignment of the text and icons is painful. If we are gonna build these into the component, let's increase the margin between the active line and the tab text to be centered

**Comment by asangma** [comment]
Not sure that Panel needs a specific slot for Tabs.
Seems like you could put Tabs in the default slot of Panel.
![image](https://user-images.githubusercontent.com/12503298/120835187-d64a1b80-c518-11eb-8ec0-39060482e8b5.png)

**Comment by asangma** [comment]
Also, if you don't add a `heading` or `summary`, the Header node doesn't render, so you build the tabs inside the default slot.
![image](https://user-images.githubusercontent.com/12503298/120835578-5c666200-c519-11eb-9c1d-f3fe1c37bd01.png)

**Comment by asangma** [comment]
I also think that the Panel would probably need to manage the tab navigation.
Or Tabs would need to be reworked to be able to let the tab nav manage tab content that is in a different node.
This is because Panel's header is one node, and Panel's content is another node.

**Comment by TheBlueDog** [comment]
@asangma You thinking that a tabbed would need to be its own standalone component?

**Comment by TheBlueDog** [comment]
Examples of how the scaled versions would look. This would require a change in the spacing of tabs, such that the label centers itself vertically in the space.

![Screen Shot 2021-06-04 at 2 49 24 PM](https://user-images.githubusercontent.com/5419306/120853145-39ec3d00-c549-11eb-9267-853b0c01c117.png)
![Screen Shot 2021-06-04 at 2 49 33 PM](https://user-images.githubusercontent.com/5419306/120853151-3a84d380-c549-11eb-9daf-300d8c452211.png)
![Screen Shot 2021-06-04 at 2 51 00 PM](https://user-images.githubusercontent.com/5419306/120853153-3a84d380-c549-11eb-9d7b-b32773061e46.png)

**Comment by macandcheese** [comment]
Tabs already scroll horizontally when the space is too small to accommodate all the items. 

Because this is utilizing an existing back button in the header I think the designs should solve for also having a header text lockup, since that is already present, even if unneeded from these two use cases. Seems weird to not make that available imo

**Comment by bstifle** [comment]
agreed. we should have all the possible variations accounted for

**Comment by bstifle** [comment]
the alternative would be making this it's own component. but not sure that's necessary

**Comment by TheBlueDog** [comment]
I'm wondering if there's a true use case for Header + Summary + Tabs. Would there be scaled versions of those?

**Comment by macandcheese** [comment]
A use case the docs site has is for the tabs to represent knob groups, with a title on top as in the comps. 

Currently we are using blocks but tabs will help us save verticals space if this enhancement becomes available with a title and description area.

**Comment by asangma** [comment]
The main issue at hand (as I understand it) is an alignment issue.
Seems like we could solve this by matching spacing, font-size, and font-weight between CalciteTabTitle and CalcitePanel's header contents.

As far as the actions, seems like we can leverage our existing "actions-end" (and if need be "actions-start") slot pattern that we're using in a number of other components.

We can also add an appearance property to CalciteTabNav for the background color, e.g. `appearance="solid"`.

This would keep a consistent DOM for CalciteTabs, e.g. everything lives inside the CalciteTabs element. As such, it can continue to handle behavior without needing to crawl the DOM for related elements.

Enhancing Panel to deal with tab navigation that will have tab content in a different node would introduce a number of new and different implementation patterns and also encourage what seems to be me to be non-ideal UX, e.g. tabbed navigation inside a drill-in.

**Comment by TheBlueDog** [comment]
After discussion with @asangma, I'm going to explore using tabs without a header or panel. As mentioned above, this may result in an enhancement to the tabs component instead.

**Comment by macandcheese** [comment]
@TheBlueDog can you provide visual examples of the intended workflow? Tough to see what the result of that discussion is without some visuals for everyone to see.

**Comment by TheBlueDog** [comment]
@macandcheese Here's our current production app. When the user selects a layer in the leading panel, the center panel is updated to show the form and templates canvas. The tabs are used to switch between those two views.

![Screen Shot 2021-06-09 at 8 44 39 AM](https://user-images.githubusercontent.com/5419306/121356911-539dd380-c8ff-11eb-9ba9-c83b6b8423c0.png)

What I'm exploring is removing the canvas from using a panel and applying the tabs in a way that is more in line with the way they are designed to be used. This does pose a design problem in that we have a set of actions that were in the panel header that no longer fit anywhere.

![Screen Shot 2021-06-09 at 8 47 10 AM](https://user-images.githubusercontent.com/5419306/121357380-c4dd8680-c8ff-11eb-9231-c8253fac3615.png)

**Comment by bstifle** [comment]
Going to leave this design discussion open until next Tuesday 6/22

**Comment by bstifle** [comment]
All here, we don't have a final design for this and we need to move forward. @TheBlueDog @asangma @macandcheese

**Comment by TheBlueDog** [comment]
We are going to. look at a whole different approach, moving the canvas area out of a panel and the existing tabs float above the content area.  Just reviewed this design with our PO yesterday. We won't be needing this any longer.

![Screen Shot 2021-06-23 at 10 03 19 AM](https://user-images.githubusercontent.com/5419306/123110606-3fcb9480-d40a-11eb-8351-e8db1c05520d.png)

**Comment by bstifle** [comment]
Sounds good, thanks for the follow up!

**Comment by macandcheese** [comment]
For posterity... we will be adopting a tab-inside-panel approach on the docs site component preview. It requires a bit of spacing and border fudging to bring into alignment with the panel heading, but using it OOTB inside the panel content isn't that bad.

**Comment by bstifle** [comment]
@mitc7862 in case u wanted it reopen

**Comment by macandcheese** [comment]
@asangma @bpatterson88 this seems like it's still relevant after seeing the Dashboard designs. This is our implementation in the developer site - we have to fudge a bit of padding, margin, border color... so perhaps a slot as originally proposed (without any of the action slot or flow stuff, just placing tabs inside a single panel item), is a simple solution:

![Screen Shot 2021-08-31 at 9 52 11 AM](https://user-images.githubusercontent.com/4733155/131544191-da582666-4f98-4b22-aee6-29f2d12a84d7.png)
