### ISSUE TITLE
Bug: Disabled labels toggle switches assoc. by `for` attribute

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2135]
### Actual Behavior
Given a disabled `<calcite-label>` element associated with a `<calcite-switch>` by its `for` attribute, clicking the label both focuses and toggles the value of the switch.

### Expected Behavior
Clicking the disabled label has no effect.

### Reproduction Steps or Sample

```html
<calcite-label for="switch" disabled>Label</calcite-label>
<calcite-switch id="switch" disabled />
```

### Relevant Info
_Version_: `@esri/calcite-components@v1.0.0-next.191`

**Comment by jcfranco** [comment]
Confirmed this is no longer an issue with the latest release: https://codepen.io/jcfranco/pen/MWvByGa?editors=1000
