### ISSUE TITLE
Enhancement: refactor Alert to match Figma design

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2136]
### Description
Calcite-alert needs to match its new design in Figma.

### Acceptance Criteria 
The component appears as it does in Figma.

### Relevant Info 
#1500, Figma refactor project: https://github.com/Esri/calcite-components/projects/14

#### Which Component
Alert

**Comment by caripizza** [comment]
@jrowlingson would you be able to take on this one?

**Comment by julio8a** [comment]
assigning to @bstifle for verification.

**Comment by bstifle** [comment]
verified!
