### ISSUE TITLE
Enhancement: Place Action Bar Horizontally 

### ISSUE THREAD

**Issue by mitc7862** [Esri/calcite-components#2137]
### Description
- I'd like to be able to place an action bar horizontally.
![image](https://user-images.githubusercontent.com/12564905/118153311-9b960d00-b3ca-11eb-82bb-b0000841cf49.png)
![image](https://user-images.githubusercontent.com/12564905/118156242-fb41e780-b3cd-11eb-9c11-f90d163db56d.png)

### Acceptance Criteria 
- action bar can be used within a panel and other dialogs
- action bar can be placed horizontally
- horizontal action bar can be fully expanded or collapsed
- horizontal action bar can contain a mix of expanded and collapsed actions
- horizontal action bar can 'overflow' when there's not enough space to show all actions (same behavior as vertical)
- optionally, an action's width can expand to fill available space. (similar to how flex-grow or css grid can work to 'best fit' elements within a layout.)

#### Which Component
- Action Bar
- Action

#### Example Use Case
![image](https://user-images.githubusercontent.com/12564905/118153201-7acdb780-b3ca-11eb-848e-f16a29565c62.png)
![image](https://user-images.githubusercontent.com/12564905/118153450-c54f3400-b3ca-11eb-9531-4769fc7943f0.png)

**Comment by bstifle** [comment]
very dope

**Comment by tyanthony** [comment]
What's the status of this enhancement request? This would definitely be a welcome enhancement as we could use a horizontal Action Bar and would love to see this be available

**Comment by macandcheese** [comment]
cc @benelan can we prioritize this?

**Comment by driskull** [comment]
The overflowing part is a bit tricky. With the "vertical" layout, the height of each action never changes when expanded. However, with "horizontal" layout the width of the actions are all different because of their text length when expanded.

**Comment by driskull** [comment]
@macandcheese can you test out this pr: https://github.com/Esri/calcite-components/pull/4838 ?

**Comment by macandcheese** [comment]
> @macandcheese can you test out this pr: #4838 ?

I'm having trouble replicating Mitch's designs on that PR - all actions after the first seem to aggregate into an overflow, and the expand / collapse appears underneath, vs. on the end. You can see them pop in initially on load then move to the overflow - I tried in containers of various width / display type:

```    
<calcite-action-bar layout="horizontal">
      <calcite-action-group layout="horizontal">
        <calcite-action text="Add" icon="plus"> </calcite-action>
        <calcite-action text="Save" icon="save"> </calcite-action>
        <calcite-action text="Layers" icon="layers"> </calcite-action>
        <calcite-action text="Add" icon="plus"> </calcite-action>
        <calcite-action text="Save" icon="save"> </calcite-action>
        <calcite-action text="Layers" icon="layers"> </calcite-action>
     </calcite-action-group>
</calcite-action-bar>
```
Does a user need to set `layout="horizontal"` on both the parent action bar and all child action groups?
<img width="315" alt="Screen Shot 2022-07-01 at 9 55 28 AM" src="https://user-images.githubusercontent.com/4733155/176937975-04a80b36-b86f-41f7-a4d7-465bfccf9587.png">

For the overflow items - the action bar could likely be "bottom or top" w/r/t its orientation related to content. Is that automatically positioned by popper to adjust if it is adjacent to viewport end?

**Comment by driskull** [comment]
@macandcheese Should we disable the Expand/Collapse functionality when in horizontal layout? It shifts the hit areas in some cases.

![1](https://user-images.githubusercontent.com/1231455/177428922-53b0bb2e-0671-4425-b686-bce91918e4c5.gif)

![fit](https://user-images.githubusercontent.com/1231455/177428934-d5946930-0999-4b5e-a880-c94fa775bb7f.gif)

Another solution would be to maybe make the text read vertically? That would solve the width issue when expanding.

When in vertical mode, there is no issue because the height of an action doesn't change. However, when in horizontal mode the expanding functionality changes the width.

**Comment by driskull** [comment]
ping @mitc7862 @yelenakreyndel for the above design questions. https://github.com/Esri/calcite-components/issues/2137#issuecomment-1175573283

**Comment by macandcheese** [comment]
Yeah, I see what you mean, could the overflowing actions be appended to an overflow if that occurred on expand (in addition to viewport adjustment)

That’s still not ideal, as potentially an “active” action could be unexpectedly appended to the overflow, but I guess that’s the same as vertical resizing.

I think having expand / collapse disabled could prevent some valid use cases like times when you have a large center area to work with for a horizontal action bar, but we could warn against its use in tight / cramped spots where that many actions probably isn’t a great idea anyway - incentivize disabling expand / collapse in those cases?

**Comment by driskull** [comment]
> I think having expand / collapse disabled could prevent some valid use cases like times when you have a large center area to work with for a horizontal action bar, but we could warn against its use in tight / cramped spots where that many actions probably isn’t a great idea anyway - incentivize disabling expand / collapse in those cases?

I think that's fine, I just wanted to demonstrate that the overflow with expandable actions isn't ideal. It will produce a lot of undesired behavior.

I just want us to understand the issue and have a solution before we merge and install.

**Comment by macandcheese** [comment]
Suggest we append the overflowing / colliding items to a menu the same way we do in vertical layout when the viewport height changes.

**Comment by driskull** [comment]
> Suggest we append the overflowing / colliding items to a menu the same way we do in vertical layout when the viewport height changes.

Thats how it is currently working. However, there are rules where a group must have at least 2 items shown at all times (first action and overflow menu) so it isn't enough when there are many groups and long text.

**Comment by driskull** [comment]
@macandcheese anything I need to do to move this along?

**Comment by yelenakreyndel** [comment]
@driskull @macandcheese Just looked at this issue for the first time. Has it been addressed? If not, do Calcite designers need to define a solution? @jcfranco does this need to be prioritized for 1.0? Adding @ashetland for visibility.

**Comment by driskull** [comment]
I think I just need testing and approval from @macandcheese.

**Comment by geospatialem** [comment]
Verified on next.551
![verify-horizontal-action-group](https://user-images.githubusercontent.com/5023024/182244905-70e80838-4eec-4c6d-81b5-1d39c6d63039.gif)
