### ISSUE TITLE
Enhancement: calcite-notice - add option to change the close icon to a different action

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2144]
### Description

From the story book
![image](https://user-images.githubusercontent.com/44481292/118171050-b58e1a80-b3df-11eb-86e9-e501e734ac37.png)

Design
![image](https://user-images.githubusercontent.com/44481292/118171495-203f5600-b3e0-11eb-98a5-4707893274ca.png)

**Comment by macandcheese** [comment]
There was a similar request for alert - in my mind a good addition to both notice and alert : https://github.com/Esri/calcite-components/issues/2012#issuecomment-827792704

**Comment by jcfranco** [comment]
@macandcheese Would users expect the info icon to close it?

**Comment by AdelheidF** [comment]
The info icon opens a popover. It will never be closed in this use case.

**Comment by macandcheese** [comment]
I don't think so... it would also likely be any Calcite UI Icon so somewhat up to the implementer?

**Comment by jcfranco** [comment]
@AdelheidF Thanks for clarifying. 

@macandcheese Would there be a use case for a trailing icon next to the close button? If so, we could add an icon-end slot and still allow it to be dismissed if necessary.

**Comment by macandcheese** [comment]
That was the ask in the issue linked above https://github.com/Esri/calcite-components/issues/2012#issuecomment-827792704 - slot makes sense for having a tooltip, if we can style the border to and limit size of slotted icon to match that of the appened "x"

**Comment by jcfranco** [comment]
Awesome. I think that will work. To recap, this should:

* add an icon-end slot for `calcite-action`s
  * placed before the close icon
  * close icon can be independently toggled via `dismissed`
  * styling should match the designs from the comment you linked above.

Does the above seem correct? Did I miss anything?

**Comment by macandcheese** [comment]
Seems good to me!

**Comment by bstifle** [comment]
![Uploading shia best part.png…]()
do it

**Comment by bstifle** [comment]
<img width="432" alt="shia best part" src="https://user-images.githubusercontent.com/14083530/120852403-c691fd80-c53f-11eb-9377-57fd2726923e.png">
do it

**Comment by jcfranco** [comment]
Installed. 

@AdelheidF Can you help verify once you use the latest next or the next beta release (beta 58)? 🙇🏼‍♂️

**Comment by AdelheidF** [comment]
I'm using next.231.

Do we really need these vertical lines?

Without adjusting the position of the icon...

![image](https://user-images.githubusercontent.com/44481292/123138613-17439a80-d40a-11eb-8c93-3c4e0d36f1e4.png)![image](https://user-images.githubusercontent.com/44481292/123138711-35a99600-d40a-11eb-9804-c438448b3ef0.png)

now with aligment...

![image](https://user-images.githubusercontent.com/44481292/123139058-a05ad180-d40a-11eb-87f9-85a9c7eb967a.png)![image](https://user-images.githubusercontent.com/44481292/123138958-81f4d600-d40a-11eb-8de1-12a3b7b2dd3a.png)

**Comment by jcfranco** [comment]
> Do we really need these vertical lines?

I think we can remove the divider if there's only one icon displayed. @macandcheese WDYT?

Weird how the action is not aligned. Can you confirm if that is a slotted icon or an action? If it's an action, can you share a snippet for the above?

**Comment by AdelheidF** [comment]
I'm now adding a vertical-align...

```
          <calcite-notice
            class={CSS.properties}
            width="full"
            scale="s"
            active={true}
            onClick={this.openStatus}
            ref={this.afterCreateStatusNotice}
          >
            <div slot="title">
              {strings.propsFromSource}
            </div>
            <calcite-icon
              slot="icon-end"
              icon="information"
              scale="s"
              class={CSS.propertiesIcon}
            ></calcite-icon>
          </calcite-notice>
```

**Comment by macandcheese** [comment]
The vertical lines denote hit / touch area, this action should be treated the same as the dismiss button. It also visually matches an alert displaying a queue length and a dismiss button, so I don’t think we should change that design, although I agree it looks weird when not spaced consistently.

Re: The question of alignment - this is the drawback to suggesting content with slots vs. being more prescriptive ie accepting an icon string and tooltip text string. 

It’s advantageous in many ways to use slots but it adds a lot of risk around design fragmentation.

**Comment by jcfranco** [comment]
> Slot "action-end" didn't work for me.

I renamed the class but not the slot. 🤦🏼  Fixing...

**Comment by jcfranco** [comment]
The slot is for a calcite-action to help with layout and button interactions.

![Screen Shot 2021-06-23 at 10 23 11 AM](https://user-images.githubusercontent.com/197440/123141232-08aab280-d40d-11eb-857f-7559deffe62b.png)

> It also visually matches an alert displaying a queue length and a dismiss button, so I don’t think we should change that design, although I agree it looks weird when not spaced consistently.

@macandcheese The dismiss button by itself doesn't have the vertical line (https://esri.github.io/calcite-components/?path=/story/components-notice--simple). Do we only show vertical lines when we have an action and the close button? Or do we show it always?

**Comment by macandcheese** [comment]
Let’s use alert when queue and dismiss are present as the example to follow. When slotted action and dismiss are present, use vertical lines on either side of the slotted action.

If it’s just the single item (action or dismiss), treat it as we do the dismiss now (no border).

cc @bstifle to confirm the designs in Storybook are up to date / have parity with Figma.

**Comment by AdelheidF** [comment]
So the correct slot name should be "action-end"? I use a similar slot name in other components and there it's called "actions-end" (with an s). Are you sure you want to go with "action-end"?

**Comment by jcfranco** [comment]
I used single because all of the designs had only one action at the most, but I do see that in my list of requirements I used plural. @macandcheese, @bstifle can you confirm if notice would support multiple actions? If so, I can update accordingly.

**Comment by bstifle** [comment]
well. We dont add the verical lines in block/panel/value list etc. not sure we should add those here

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/123144979-ea9b7d00-d421-11eb-826f-a938cdd5925b.png)

**Comment by jcfranco** [comment]
@bstifle Noice! One more question: if there's only one action, show it directly and skip the `...` menu (w/o vertical lines as well)?

**Comment by AdelheidF** [comment]
My wanted design is this one.
![image](https://user-images.githubusercontent.com/44481292/118171495-203f5600-b3e0-11eb-98a5-4707893274ca.png)
You click on the icon to get more info about it.

The design above https://github.com/Esri/calcite-components/issues/2144#issuecomment-867041115 says to me the notice is the info. This is different.

**Comment by macandcheese** [comment]
Alert is a more analogous component than any of block, panel, or value list, and this is how we treat two trailing "things":

![Screen Shot 2021-06-23 at 10 54 33 AM](https://user-images.githubusercontent.com/4733155/123145313-8d97cb00-d411-11eb-8838-03cbede21f73.png)

Let's make sure these are all visually consistent. I don't have a strong preference to what end. Maybe make the "queued" value a chip with no lines ever.

**Comment by bstifle** [comment]
@jcfranco 
> @bstifle Noice! One more question: if there's only one action, show it directly and skip the `...` menu (w/o vertical lines as well)?

sorry that was confusing. the dots were not meant to be an overflow. just an action next to X. would just stack em to the side like this if more than one:

![image](https://user-images.githubusercontent.com/14083530/123145783-cc824c80-d422-11eb-9210-77688355f21c.png)

**Comment by bstifle** [comment]
>Let's make sure these are all visually consistent. I don't have a strong preference to what end. Maybe make the "queued" value a chip with no lines ever.

Chip for queue would be dope

![image](https://user-images.githubusercontent.com/14083530/123146098-2420b800-d423-11eb-8229-3f7c29f56534.png)

**Comment by jcfranco** [comment]
@bstifle Got it. 👍🏼  

Should we doc a recommended amount of notice actions? We could tackle this later if we need a mechanism to deal with the notice title/message overflowing into the actions area.

**Comment by bstifle** [comment]
no more than 2 would be best. that screen shot up there would be worst case in my opinion

**Comment by jcfranco** [comment]
I'll have a PR for this today that will:

* remove vertical delimiters
* rename `action-end` slot to `actions-end`
* support multiple actions
* update action slot doc with recommended number of actions to use

**Comment by jcfranco** [comment]
Thanks everyone!

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
@AdelheidF Slot names should be fixed (now `actions-end`). Can you help verify?

**Comment by AdelheidF** [comment]
Tested with next.234. Looks good, thank you.

Without any styling
![image](https://user-images.githubusercontent.com/44481292/124038669-5c417100-d9b6-11eb-955a-85262cc08fbe.png)

With styling
![image](https://user-images.githubusercontent.com/44481292/124038777-8eeb6980-d9b6-11eb-903e-ce96364de0c5.png)

With close icon
![image](https://user-images.githubusercontent.com/44481292/124039054-09b48480-d9b7-11eb-8626-d5891c3b4089.png)
