### ISSUE TITLE
Docs: `calcite-input` slot name is incorrect

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2150]
### Description 
The doc shows the `calcite-input` element's slot name as `"calcite-action"`[1]:
<img width="530" alt="Screen Shot 2021-05-14 at 10 43 56 AM" src="https://user-images.githubusercontent.com/421496/118293895-2862c880-b4a8-11eb-9af9-1f5d246479af.png">

However, the code snippets show the slot as `"action"`:
https://github.com/Esri/calcite-components/blob/d8e931421d5d661bf83b32f8396d0b227f531923/src/demos/calcite-input.html#L209-L211

And indeed, naming the slot `"action"` in code works while using `"calcite-action"` results in no button showing.

I also noticed the [popup-config-example.html](https://github.com/Esri/calcite-components/blob/d8e931421d5d661bf83b32f8396d0b227f531923/src/demos/shell/popup-config-example.html) demo page makes use of the same slot but names it `"input-action"`. Those slotted buttons are also absent until retargeted towards the `"action"` slot.

### Which Component
`calcite-input`

### Resources 
```html
<calcite-input>
  <calcite-button slot="action">Go</calcite-button>
</calcite-input>
```

---
[1] https://esri.github.io/calcite-components/?path=/docs/components-controls-input--with-label#slots

**Comment by jcfranco** [comment]
Installed. @nwhittaker Can you help verify this? The [input's readme](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-input/readme.md#slots) should be updated by tomorrow. 🙇🏼‍♂️

**Comment by nwhittaker** [comment]
Thanks @jcfranco, I'll keep an eye out for it.

How do you want to handle fixing the code samples on [popup-config-example.html](https://github.com/Esri/calcite-components/blob/d8e931421d5d661bf83b32f8396d0b227f531923/src/demos/shell/popup-config-example.html) to use the `action` slot name?

**Comment by jcfranco** [comment]
@nwhittaker Ah, I missed that. I'll submit a follow-up PR in a few.

**Comment by jcfranco** [comment]
☝🏼  💥

**Comment by nwhittaker** [comment]
I see the doc and demos updated -- thanks!
