### ISSUE TITLE
Enhancement: Single util to allow us to call DOM APIs across shadow boundary

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2154]
### Acceptance Criteria 

Maybe something like (very rough):

```ts
domQuery<T extends HTMLElement>(
  method, // `selector`, `closest`, others?
  options // `all`, others?
): Element | Elements | null; // we can fine tune results based on input arguments
```

### Relevant Info 

We need to be able to do the following queries:

- querySelector
- querySelectorAll
- closest
- Potentially `getElementById` if we feel the slight performance increase is worth it over using `querySelector(#id)`

All of these will query the shadowDom first then go up the chain using `getRootNode()`

For `querySelectorAll`, we may want an option to just return the first set of results or return all of the results from each shadowDom and document.

https://github.com/Esri/calcite-components/pull/2107#discussion_r629752065

#### Which Component

All

#### Example Use Case

See above

**Comment by driskull** [comment]
@jcfranco what about...

```
domQuery<T extends HTMLElement>(
  element: T;
  method: "selector" | "selectorAll" | "closest" | "id";
): (T | null) | T[];
```

**Comment by jcfranco** [comment]
This isn't valid anymore. Closing.
