### ISSUE TITLE
Bug: Expand/Collapse chevrons are wrong in <calcite-action-bar> when position=end

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#2159]
### Actual Behavior

When <calcite-action-bar position="end"> is set the chevrons point the wrong direction.

### Expected Behavior

Expand chevrons should point right and Collapse chevrons should point left. The chevron alignment should be controlled by `dir` not `position`.

### Reproduction Steps or Sample

1. Go to https://esri.github.io/calcite-components/?path=/story/components-action-bar--basic
2. Set `position="end"` notice the "Expand" action points left even though `dir="ltr"

**Comment by driskull** [comment]
@patrickarlt the position property is for when the action-bar is placed on the right or left of the map.

So if it is positioned left, it should point left.
