### ISSUE TITLE
Deprecate "floating" input-message variant

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2172]
### Question
Per [this Teams conversation](https://teams.microsoft.com/l/message/19:fd15b51dacd24e70895ec1218a54ae06@thread.skype/1620320832990?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1620320832990&teamName=Calcite%20Design%20System&channelName=Calcite%20Components&createdTime=1620320832990), the Calcite design team is proposing that we remove the "floating" input-message variant.

### Helpful Details 
Does not seem to be used very much right now, and would simplify the use cases input-message needs to support.

Related bug tied to this variant: https://github.com/Esri/calcite-components/issues/2007

**Comment by caripizza** [comment]
Moving to current sprint per Calcite Design Team request (prerequisite for the Figma calcite-input refactor work)

**Comment by jcfranco** [comment]
@caripizza Can you help verify this one? Thanks! 🙇🏼‍♂️

**Comment by caripizza** [comment]
Verified on master branch (currently at `1.0.0-next.259`), calcite-input-message no longer supports a `type` property. (Its previous `type="default"` variant styles are now standard.)

Here's a screenshot showing the new active message styles in each scale:

![image](https://user-images.githubusercontent.com/42423180/127693745-b11100a0-8644-4900-911d-818f10439c8f.png)
```html
        <h3>With message</h3>
        <calcite-label scale="s" for='s-message-input'>
          My great label
          <calcite-input id='s-message-input' placeholder="Enter your information"></calcite-input>
          <calcite-input-message icon="3d-glasses" active status="idle">
            Here's something you should know about this input
          </calcite-input-message>
        </calcite-label>
        <calcite-label for='m-message-input'>
          My great label
          <calcite-input id='m-message-input' placeholder="Enter your information"></calcite-input>
          <calcite-input-message icon="3d-glasses" active status="valid">
            Here's something you should know about this input
          </calcite-input-message>
        </calcite-label>
        <calcite-label scale="l" for='l-message-input'>
          My great label
          <calcite-input id='l-message-input' placeholder="Enter your information"></calcite-input>
          <calcite-input-message icon="3d-glasses" active status="invalid">
            Here's something you should know about this input
          </calcite-input-message>
        </calcite-label>
```
