### ISSUE TITLE
Epic: Introduce comprehensive/testable pattern for demo pages

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2174]
### Background 

The idea is to have a somewhat repeatable set of layouts so that Screener can read more iterations, and also for better manual auditing since it (should be) easier to scan. 

cc @bstifle 

### Desired Outcome 

For all demo pages to have a consistent layout that will allow Screener and ourselves to visually scan all possible states from components.

### Components that need updated demo pages in alphabetical order:
- Accordion #2616
- Action #2686 
- Alert #2436 
- Avatar #2526 
- Block #2687 
- Button #2482 
- Card #2626 
- Checkbox #2508 
- Chip #2549 
- Color-picker #2576 
- Combobox #2561 
- Date-picker #2580 
- Dropdown #2628 
- Fab #2629 
- Flow #2688 
- Icon #2529 
- Inline-editable #2630 
- Input #2483 
- Label #2631 
- Link #2632 
- List #2703 
- Loader #2633 
- Modal #2505 
- Notice #2611 
- Pagination #2634 
- Panel #2689 
- Pick-list #2690 
- Popover #2635 
- Progress #2636 
- Radio Button #2769 
- Radio Button Group #2789 
- Radio Group #2791 
- Rating #2536 
- Scrim #2605 
- Select #2637 
- Slider #2638 
- Sortable-list #2691 
- Stepper #2639 
- Switch #2365
- Tabs #2640 
- Tile #2641 
- Tip-manager #2692 
- Tooltip #2642 
- Tree #2643 
- Value-list #2693

**Comment by bstifle** [comment]
Initial design direction. The idea for that top bar section is for it to stick, so theme/etc can be changed whenever

![Input](https://user-images.githubusercontent.com/14083530/118865473-97745e80-b8a6-11eb-97d5-c9baca13fb99.png)
![Button](https://user-images.githubusercontent.com/14083530/118865478-98a58b80-b8a6-11eb-8283-e70f78d6fab2.png)
![Alert](https://user-images.githubusercontent.com/14083530/118865480-993e2200-b8a6-11eb-926f-ed70b82f2a8f.png)
![Switch](https://user-images.githubusercontent.com/14083530/118865467-96433180-b8a6-11eb-8eee-994424a1640d.png)

**Comment by julio8a** [comment]
Still valid and being worked on.

**Comment by jcfranco** [comment]
Closing as verified based on linked issues from the description. 

@julio8a please reopen if further action is needed.
