### ISSUE TITLE
Bug: Date-Picker range hover visuals

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2175]
1. When hovering for a new range day, and then hovering outside of the "day area" the gray selection becomes square.
- Expected: should be round

<img width="279" alt="Screen Shot 2021-05-19 at 2 32 33 PM" src="https://user-images.githubusercontent.com/14083530/118873330-3e5cf880-b8af-11eb-9e35-53c559f2f98c.png">

2. When hovering for the second click of the range, blue bleeds through the hover state which is incorrect and should not happen very sad very not good
- Expected: no blue bleed (see screenshot below)
<img width="282" alt="Screen Shot 2021-05-19 at 2 32 40 PM" src="https://user-images.githubusercontent.com/14083530/118873446-651b2f00-b8af-11eb-870d-2ced51237109.png">

**Comment by caripizza** [comment]
@bstifle can you clarify if this one is different than behavior from #1845?

**Comment by caripizza** [comment]
Description should use the Bug issue template:
https://raw.githubusercontent.com/Esri/calcite-components/master/.github/ISSUE_TEMPLATE/bug.md

**Comment by bstifle** [comment]
similar behavior. but that #1845 issue isn't an issue anymore on master. ill close it

**Comment by bstifle** [comment]
This was fixed in a past issue and I just verified
