### ISSUE TITLE
Bug: Modal loses buttons on re-render

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2178]
A common pattern in Ember is to dynamically add and remove templates as needed. Applying this pattern to the `calcite-modal` component exposes an issue where the slotted button elements visually disappear on subsequent re-renders.

### Actual Behavior
| First render | Second render |
| - | - |
| <img width="866" alt="Screen Shot 2021-05-19 at 5 31 22 PM" src="https://user-images.githubusercontent.com/421496/118887265-1d54d180-b8c8-11eb-9370-5075f1e39c64.png"> | <img width="906" alt="Screen Shot 2021-05-19 at 5 30 50 PM" src="https://user-images.githubusercontent.com/421496/118887170-fa2a2200-b8c7-11eb-84d2-329519422de8.png"> |

### Expected Behavior
Slotted buttons continue to be visually present and clickable.

### Reproduction Steps or Sample
```hbs
<button {{action 'openModal'}}>Open modal</button>

{{#if isOpen}}
  <calcite-modal active>
    <h3 slot="header">Title of the modal</h3>
    <p slot="content">The actual content of the modal</p>
    <calcite-button slot="primary">Primary</calcite-button>
  </calcite-modal>
{{/if}}
```

1. Visit https://jsbin.com/xutonogoya/1/edit?html,js,output for working repro case.
2. Click the _Open modal_ button and notice the button at the bottom.
3. Close the modal and click the _Open modal_ button again to reopen it. Notice the button is gone.

#### Alternative repro
```hbs
<calcite-modal>
  <h3 slot="header">Title of the modal</h3>
  <p slot="content">The actual content of the modal</p>
  <calcite-button slot="primary">Primary</calcite-button>
</calcite-modal>

<button {{action 'openModal'}}>Open modal</button>

{{#if isOpen}}
  <calcite-modal active>
    <h3 slot="header">Title of the modal</h3>
     <p slot="content">The actual content of the modal</p>
     <calcite-button slot="primary">Primary</calcite-button>
  </calcite-modal>
{{/if}}
```

1. Visit https://jsbin.com/jegebifuse/1/edit?html,js,output for working repro.
2. Click the _Open modal_ button and notice the slotted button is not shown.

### Relevant Info
Observed in latest versions of Safari 14.1 and Chrome 90. Symptoms are similar to those observed in https://github.com/Esri/calcite-components/issues/1409. Possibly related to a similar underlying issue?

_Version_: `@esri/calcite-components@1.0.0-next.201`

**Comment by caripizza** [comment]
@nwhittaker thank you for this really well documented bug report.

**Comment by Csmith246** [comment]
I've also noticed this behavior of the footer buttons disappearing. If you need another repro example, you can setup and run this project locally: https://github.com/Csmith246/calcite-4x-widget-sandbox

**Comment by jcfranco** [comment]
Installed.

@nwhittaker @Csmith246 Could you help verify this one? Thanks!

**Comment by nwhittaker** [comment]
Looks good to me in the jsbin -- thanks for swift fix!
