### ISSUE TITLE
Docs: Modal events fire when animations ends

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2179]
### Description 
Both the `calciteModalClose` and `calciteModalOpen` events are documented as firing when their respective animations begin. However, in code, they both fire when their respective animations end.

### Which Component
`<calcite-modal>`

### Resources 
https://github.com/Esri/calcite-components/blob/52045a8229c4b26c6ccde5497fd3546b2bbb7d25/src/components/calcite-modal/calcite-modal.tsx#L330

https://github.com/Esri/calcite-components/blob/52045a8229c4b26c6ccde5497fd3546b2bbb7d25/src/components/calcite-modal/calcite-modal.tsx#L317-L320

https://github.com/Esri/calcite-components/blob/52045a8229c4b26c6ccde5497fd3546b2bbb7d25/src/components/calcite-modal/calcite-modal.scss#L5

**Comment by driskull** [comment]
related to #2074

**Comment by jcfranco** [comment]
Verified w/ latest readme contents.
