### ISSUE TITLE
Enhancement: Popover border-radius

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#218]
Since Popover is a floating element, seems like it could benefit from some border-radius.

@paulcpederson @macandcheese @julio8a Ya?

**Comment by asangma** [comment]
![image](https://user-images.githubusercontent.com/12503298/68343245-32c92880-00a1-11ea-8c15-adadc15ca640.png)

**Comment by macandcheese** [comment]
That makes sense - modals, alerts, popovers, tooltips, dropdowns - read: floaty-things, should have border-radius.

**Comment by asangma** [comment]
Cool...I'll submit a PR.

**Comment by macandcheese** [comment]
Sounds good, I think we just need to account for the possibility of the close button abutting a corner, and applying the border-radius to the button in that case to prevent it from clipping above the border-radius of the container.

**Comment by asangma** [comment]
Was thinking `overflow: hidden`.
