### ISSUE TITLE
Enhancement: calcite-flow should detect calcite-panels within custom components

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2180]
### Description + Relevant Info + Example Use Case
Currently the custom `arcgis-filter` Stencil component includes a `calcite-panel`. This works fine if the filter component is used directly from inside a `calcite-shell-panel`.
![image](https://user-images.githubusercontent.com/44481292/118897150-8f281d80-b8be-11eb-9c35-bc44174393d4.png)

Sometimes though we want to use the filter component as part of a flow, e.g. when creating labels for a layer and then adding a filter to not show labels for all features of the layer. This would look something like this:
```
<calcite-shell-panel>
  <calcite-flow>
    <calcite-panel>
      ... some label settings
    </calcite-panel>
    <arcgis-filter>
      <calcite-panel>
         some filter settings
      </calcite-panel>
    </arcgis-filter>
  </calcite-flow>
</calcite-shell-panel>
```
We tried that but it doesn't work because the flow doesn't detect the second panel wrapped inside the custom element. In the past we also had issues with the styles, but that might be working now (I didn't try recently).

If I take the panel out of the custom component and ask the calling component to add the panel instead then I run into an issue with the fab button, because `slot=fab` no longer works.
![image](https://user-images.githubusercontent.com/44481292/118896891-1d4fd400-b8be-11eb-8fa0-d1d70454de23.png)

Since this is a common requirement when we want to reuse certain custom components in multiple places I would like to have this solved in `calcite-flow`. Would it be possible that the flow not only looks for children that are `calcite-panel` components, but also looks for elements that contain a `calcite-panel`, at least one level farther down the dom tree?

This might be the related issue for styles https://github.com/Esri/calcite-components/issues/1927

#### Which Component

calcite-flow

**Comment by driskull** [comment]
@AdelheidF do you have a sample?

Looking at the code, it should work fine as long as the panels are not within the filter's shadowRoot.

**Comment by AdelheidF** [comment]
No sample right now, but I will need this again in a little bit. Will report back then. Last time we tried it we didn't get it to work, but that's already a bit time ago.

**Comment by AdelheidF** [comment]
This is working fine now. Closing.

**Comment by asangma** [comment]
@driskull Revisiting this one. Do you think it would be weird to let Flow grab whatever the last child is and remove it when the back button is clicked?

**Comment by driskull** [comment]
Yeah I think that could be bad.

**Comment by asangma** [comment]
Seems like you'd only wanna put elements in there that would be part of a flow though, no?

**Comment by driskull** [comment]
Yes, but removing any last node seems like it could go badly.

**Comment by asangma** [comment]
True.
I'm thinking that custom elements are gonna continue to be a thing we see regularly.
True, users can hook into the "calcitePanelBackClick" event, but there may be some unintended behaviors there too. 

What if the user could register a partial tag (i.e. the prefix of a tag) with Flow.

```html
<calcite-flow node-prefix="vuvuzela">
  <vuvuzela-noise>
    <calcite-panel>
    <!-- stuff -->
    </calcite-panel>
  </vuvuzela-noise>
  
  <vuvuzela-sound>
    <calcite-panel>
    <!-- stuff -->
    </calcite-panel>
  </vuvuzela-sound>
<calcite-flow>

And Flow would add that to its query.

**Comment by asangma** [comment]
note: I don't know what a good name for that prop would be.

**Comment by driskull** [comment]
Yeah, we could add a `selector` prop that by default has `calcite-panel` but the user could change it to whatever.

**Comment by asangma** [comment]
Got it.
Will work out details with you offline.

**Comment by asangma** [comment]
cc @AdelheidF ⬆️ 
Thoughts?

**Comment by AdelheidF** [comment]
That sounds great. My custom elements though don't always start with the same `vuvuzela-`. Could it be instead a prop or class on the custom tag?

![image](https://user-images.githubusercontent.com/44481292/128400734-cd0a1bfb-00d9-4edc-b665-9dc445a41fd2.png)

**Comment by asangma** [comment]
A class makes sense to me.
Thoughts @driskull ?

**Comment by driskull** [comment]
@asangma no, we call the prop `selector` and it can be any HTML selector but defaults to `calcite-panel`

**Comment by AdelheidF** [comment]
How would this selector work in my case above? https://github.com/Esri/calcite-components/issues/2180#issuecomment-893679671

**Comment by driskull** [comment]
You could set the selector to a class. eg: `.arcgis-layer-view`

**Comment by asangma** [comment]
Oooohhhh.... @driskull I get it now.

**Comment by AdelheidF** [comment]
closing this issue as it's being dealt with via https://github.com/Esri/calcite-components/issues/4817
