### ISSUE TITLE
Bug: Allow updating tab programatically

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#2185]
### Actual Behavior

Setting `.active` on a tab title doesn't update the blue active underline position

### Expected Behavior

Setting active to a new tab should mark that tab as active and move the underline. 

### Reproduction Steps or Sample

https://codepen.io/paulcp/pen/WNpoJdW 

### Relevant Info

I think a watcher on the active prop of a tab should update location of underline.

_Version_: all versions

- [ ] CDN
- [ ] NPM package

**Comment by caripizza** [comment]
I'm going to take a stab at this one alongside #803

**Comment by julio8a** [comment]
verified on master. closing.
