### ISSUE TITLE
Enhancement: change calcite-label's layout="inline" to use layout="horizontal"

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#2188]
### Description

To keep terminology consistent with other components, `calcite-label` should use the term "horizontal" to describe laying out slotted content as opposed to "inline".  This probably should also apply to `inline-space-between`, so the correct wording should be `horizontal-space-between`.

### Acceptance Criteria 

`calcite-label`'s `layout` property should support the values `horizontal` and `horizontal-space-between`.

#### Which Component

`calcite-label`

#### Example Use Case

```
<calcite-label layout="horizontal">
   <calcite-radio-button></calcite-radio-button>
   Label
</calcite-label>
```
☝️ renders a radio and the label to the right of the radio (in LTR mode).

**Comment by asangma** [comment]
Hi. Sorry to do this late, but seems like the "inline" terminology is something we should keep since it's more inline (no pun intended) with CSS terminology and stuff.

OK, maybe the pun was intended.

**Comment by macandcheese** [comment]
@eriklharper is this safe to close? It could be brought back up at a later time as a Discussion, if needed.

**Comment by eriklharper** [comment]
> @eriklharper is this safe to close? It could be brought back up at a later time as a Discussion, if needed.

Yeah, we can let this go for now.  If the need to reconsider comes up again, we can create a discussion.
