### ISSUE TITLE
Enhancement: color picker swatch theme lookup

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2193]
### Description

It seems this is the only component that looks up the theme to do something. Is it possible to refactor this logic to grab a CSS variable instead of looking up the theme?

```tsx
const theme = getElementProp(el, "theme", "light", true);
    const borderColor = theme === "light" ? COLORS.borderLight : COLORS.borderDark;
```

### Acceptance Criteria 

Instead of storing the colors in TS, the colors are just stored as a theme variable in CSS and grabbed to be set onto the svg?

### Relevant Info 

```tsx
  render(): VNode {
    const { active, el, internalColor } = this;
    const borderRadius = active ? "100%" : "0";
    const hex = internalColor.hex();
    const theme = getElementProp(el, "theme", "light", true);
    const borderColor = theme === "light" ? COLORS.borderLight : COLORS.borderDark;
```

#### Which Component

color picker swatch

#### Example Use Case

These color resources would be removed...

```ts
export const COLORS = {
  borderLight: "rgba(0, 0, 0, 0.15)",
  borderDark: "rgba(255, 255, 255, 0.15)"
};
```

**Comment by driskull** [comment]
There may even be an existing css variable for border we can just use

**Comment by caripizza** [comment]
Good question @driskull seems doable to me. This also plays into @paulcpederson's [comment](https://github.com/Esri/calcite-components/pull/2114/files#r633891806) from #1737, and other thoughts I had about what semi-transparent background colors we want to offer.

Right now, we're using a bunch of alpha colors as CSS variables in the global stylesheet for theming. Should we just add a new alpha color set to our Tailwind theme's `colors` properties? (ie., from the `blk-` and `ui-light`/`ui-dark` Sass vars from calcite-colors)

I think if we had colors like this in the theme:
```scss
      blk: {
        // ...
        240: "#000000",
      },
      "ui-light": {
        // ...
        "brand-hover": "#00619b",
      },
      "ui-dark": {
        // ...
        "brand-hover": "#007AC2",
      },
```
We'd be able to use Tailwind's `bg-opacity-#` utility, for even more customization with background color opacity:
https://v1.tailwindcss.com/docs/background-opacity

I think we just want to do this instead in the config:
```scss
    backgroundColor: theme => ({
      ...theme("colors"),
      // ...
```

And then we can reference these styles in component .scss files like this:

```scss
@apply bg-blk-240 bg-opacity-75;
```

Which produces the following styles:
![image](https://user-images.githubusercontent.com/42423180/119179254-90bf2600-ba23-11eb-844a-bdca99536a3f.png)

**Comment by driskull** [comment]
Actually, there is one more component doing something similar. Avatar uses theme to render a background.

https://github.com/Esri/calcite-components/blob/master/src/components/calcite-avatar/calcite-avatar.tsx#L112

**Comment by paulcpederson** [comment]
Avatar could probably look up closest element based on the new class as well and use that in it's logic?

**Comment by caripizza** [comment]
Yeah, maybe just reference the existing color properties from: `calcite-colors/dist/colors.d.ts`

The way this file does: .storybook/utils.tsx
```js
import { colors } from "../node_modules/@esri/calcite-colors/dist/colors";
//..
const lightValue = {
  name: "Light",
  value: colors["blk-005"]
};
```

**Comment by driskull** [comment]
> Avatar could probably look up closest element based on the new class as well and use that in it's logic?

Yeah. I'll create a dom util for lookup. Closest isn't' great if there is no class at all and it has to go through shadow root.

**Comment by paulcpederson** [comment]
Isn't closest how `getElementDir` works? Pretty sure we do that for most components...

**Comment by driskull** [comment]
Yeah. I wonder if its more performant to get the computed style of the component instead of going up the DOM? closest also has to cross shadow boundaries.

**Comment by paulcpederson** [comment]
IIRC `getComputedStyle` forces a reflow which is a super costly operation for the browser, but I think we'd have to benchmark it to really know.

**Comment by caripizza** [comment]
Adding an update that this one was resolved via Matt's `getThemeName` addition in pr #2194, marking this installed.

**Comment by julio8a** [comment]
Verified on lastest storybook
