### ISSUE TITLE
Bug: Calcite Tree in input-enabled mode fires select twice when label is clicked

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#2196]
### Actual Behavior

calciteTreeSelect event is fired twice

### Expected Behavior

calciteTreeSelect event should be fired once

### Reproduction Steps or Sample

1. go to https://codepen.io/paulcp/pen/GRWWoLx?editors=1111
2. click the _text_ of the first tree option to select it
3. notice the console has two logs that are identical

**Comment by jcfranco** [comment]
Installed!

**Comment by julio8a** [comment]
verified
