### ISSUE TITLE
Research: Usage of CSS custom prop to define the theme

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2199]
### Background 

Currently, developers have to explicitly set a class to specify the theme. It would be useful to support theme selection via a CSS prop. This would allow specifying the theme within another stylesheet. 

cc @driskull 

### Desired Outcome 

Theming via CSS prop.

**Comment by asangma** [comment]
#### Naming suggestion
I suggest if we use BEM here, that we don't use "dark" and "light" as modifiers.
e.g. we should not do this: `calcite-theme--dark` and `calcite-theme--light`.

My thought here is that this assumes a `calcite-theme` which is modified to be dark or light. We could consider one of the themes to be the default so `calcite-theme` would be e.g. "dark" and the `--light` modifier would be added to switch to light.

I suggest we instead place each theme at the "block" level and make them:

```
calcite-theme-dark
calcite-theme-light
```

**Comment by driskull** [comment]
Sounds good Alan.

**Comment by driskull** [comment]
> Currently, developers have to explicitly set a class to specify the theme. It would be useful to support theme selection via a CSS prop.

Using a class seems like the right way.

How would a css variable adjust the selectors? I'm not sure how that would work but doesn't sound right

**Comment by driskull** [comment]
@asangma can you create an issue to rename the theme classes?

**Comment by driskull** [comment]
> Currently, developers have to explicitly set a class to specify the theme. 

I think this is how the HTML gods intended things to be.

going to close, feel free to reopen if there are some ideas on how this would work.
