### ISSUE TITLE
Bug: Select component arrow right-aligned in RTL

### ISSUE THREAD

**Issue by andreasulmer** [Esri/calcite-components#2203]
### Actual Behavior
With `document.dir= "rtl"`, the triangle button to open the select options appears on the right.
![image](https://user-images.githubusercontent.com/25357523/119506729-7ad89a80-bd6e-11eb-9d87-d07f2a9ec531.png)

### Expected Behavior

The triangle should appear on the left

### Reproduction Steps or Sample

https://zrh-app-sd-2.esri.com/arcgis-play/f/yEV-

### Relevant Info

* Reproducable with Chome on Windows, Brave on Windows
* Works as expected in Windows Firefox, MacOS Chrome

_Version_: `"@esri/calcite-components": "^1.0.0-beta.52"`

- [ ] CDN
- [x] NPM package

**Comment by caripizza** [comment]
Closing in favor of #2147
