### ISSUE TITLE
Enhancement: Expose calcite-filter or equivalent with improvements

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#2208]
### Description

value-list implies that the data to be filtered are the value-list-items.
My issue is that my collection of value-list-items are coming from a service.
As the user types a word in the value-list filter component (calcite-filter), I would like to use the word and query the service and then update the value-list-items based on the result.

In that sense, it is not really about 'filtering' but rather about 're-fetching' data for the value-list.
This is why, my solution was to simply disable the filter on the value list and provide my own UI above the value-list and control myself the whole workflow.
I can achieve this by using calcite-input. However, the look and feel of calcite-input is not matching the look and feel and animations of the calcite-filter.

### Acceptance Criteria 

A control that expose the same UX as calcite-filter (animations, etc) and an event when the text changed.

**Comment by jcfranco** [comment]
Installed! 

Recap:

* `calcite-filter` is now public
* added `items` and `filteredItems` props
* `data` and event payload is deprecated and will be removed in the next sprint
* I will create follow-up issues for
  * dropping deprecated props in the next sprint 
  * adding support for custom filter function

**Comment by jcfranco** [comment]
[Belated] Installed!

**Comment by benelan** [comment]
verified on `next`! https://codepen.io/benesri/pen/wvrMRyE?editors=0010
