### ISSUE TITLE
Bug: X icons in close buttons should hover/press to ui-text-1 color

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2216]
When hovering over close buttons in CC, the X icon should change color to ui-text-1

Popover, Modal, Alert, Notice, Input (clear X) ((would affect inline-editable))

![image](https://user-images.githubusercontent.com/14083530/119736508-6b775100-be43-11eb-8080-7e33d90ccbe5.png)

**Comment by julio8a** [comment]
assigning to @bstifle for verification.

**Comment by bstifle** [comment]
Modal X is not ui-text-3 on idle

Input close X and other controls (spinners, chevrons, etc)  are not ui-text-3 on idle

Popover, Alert, Notice are good ✅

**Comment by julio8a** [comment]
@bstifle, can you verify this one on master?

**Comment by bstifle** [comment]
dang it. input and inline editable dont have this fix

**Comment by bstifle** [comment]
I mentioned this in the comment above, before merge

https://github.com/Esri/calcite-components/issues/2216#issuecomment-873238055

**Comment by julio8a** [comment]
Thanks, Bryan! Bringing this back to in dev

**Comment by jcfranco** [comment]
Moving to the next sprint. @julio8a Feel free to adjust the sprint if needed.

**Comment by julio8a** [comment]
Self-verified input buttons idle/hover
I'm going to close this one and add notes to the inline editable issue: #2468
