### ISSUE TITLE
Question: Is Popover's max-width needed?

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#222]
Can we do without the max-width on Popover?
Seems like the content should define this.

**Comment by paulcpederson** [comment]
We should have a set of props that help determine width, sort of like modal has. Default could be an auto?

**Comment by driskull** [comment]
@asangma this is getting stale. Do we want to do anything?

**Comment by macandcheese** [comment]
Going to close this, feel free to re-open if anything needs to be changed.
