### ISSUE TITLE
Enhancement: Popover "close-button" property should be "dismissible"

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2223]
### Description
Popover uses the property `close-button` to turn on its close button. 
Notice and Panel use `dismissible`.

Suggest deprecating `close-button` on Popover and using `dismissible`.

### Acceptance Criteria 
Don't break stuff.

#### Which Component
Popover

#### Example Use Case
"I want to use Calcite Components and use the same prop to do the same thing in different components."

**Comment by julio8a** [comment]
Verified in master

**Comment by AdelheidF** [comment]
`setFocus("close-button")` still uses the old name. Is this expected?

https://github.com/Esri/calcite-components/blob/master/src/components/calcite-popover/calcite-popover.tsx#L228

**Comment by driskull** [comment]
Yes, that wasn't changed.

**Comment by AdelheidF** [comment]
How can I find out what focusIds are supported without looking at the code?

**Comment by driskull** [comment]
Right now the code is the best way. The interface isn't being generated into doc. I think we would need to get stencil to fix it.

**Comment by driskull** [comment]
Can you open a doc issue? We can probably just doc it in the method.
