### ISSUE TITLE
Enhancement: Slider needs Small and Large scales

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2224]
Slider needs small and large scales!

Figma designs:
https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=0%3A15235

**Comment by jcfranco** [comment]
I believe this is also related to #1500. Assigned to 7/5 milestone. cc @caripizza @julio8a

**Comment by julio8a** [comment]
closing this one, this is already documented in the refactor issue:
https://github.com/Esri/calcite-components/issues/2457
