### ISSUE TITLE
A11y: [calcite-color-picker] - "ghost" focus ring when hue is set to 0 or 360

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-components#2230]
### Actual Behavior

When setting the hue to 0 or 360, the component ends up with a focus ring in the middle, as shown in the following image:
![Screen Shot 2021-05-28 at 14 44 15](https://user-images.githubusercontent.com/3759114/119993868-5974ea00-bfcc-11eb-93c2-2d6305a79253.jpg)

Could be related to https://github.com/Esri/calcite-components/issues/1297

### Expected Behavior

The focus ring should stay over the hue thumb.

### Reproduction Steps

1. Add a `<calcite-color-picker>` to an app.
2. Drag the hue thumb all the way to the left.
3. Tab into the component and notice that there is a ghost focus ring in the middle of the hue gradient.

**Comment by hccampos** [comment]
@jcfranco this now works 👍  However, noticed a slightly different but related issue:
1. Initialize the `calcite-color-picker` with pure white.
2. Tab to the hue handle - notice you can't move the handle with the keyboard ⚠️  
4. Tab to the color handle and move to a different color - works 👍 
5. Tab back to the hue handle and try to move it with the keyboard - color gets reset to pure white.

This may be related to https://github.com/Esri/calcite-components/issues/1297

**Comment by jcfranco** [comment]
Awesome, thanks for the breakdown! I see the above issues in the previous release, so I'll create a follow-up issue.

**Comment by jcfranco** [comment]
Closing as verified based on the above.

**Comment by jcfranco** [comment]
Created issue: https://github.com/Esri/calcite-components/issues/2357
