### ISSUE TITLE
Enhancement: Option to make Modal closable by clicking outside the dialog

### ISSUE THREAD

**Issue by andreasulmer** [Esri/calcite-components#2234]
### Description

Most modal web dialogs have the option to be closed by clicking outside the dialog, with the same behavior as clicking ✖, or pressing Esc. Calcite Modal does not provide this functionality.
It would ideally be configurable, the boolean could be called `disable-outside-close` (similar to `disable-escape`).

### Acceptance Criteria 
Dialog closes when user clicks (or touches) outside the dialog.

#### Which Component
Modal

#### Example Use Case
No specific use case, but following common web UX patterns.

**Comment by bstifle** [comment]
**100% yes**

**Comment by andreasulmer** [comment]
Tested locally w/ npm @1.0.0-next.237
Tested on Win 11 Chrome, Firefox, Edge, Chrome w/ mobile touch emulation, Android Chrome.

✔ by default, modal now closes on outside click
✔ `<calcite-modal disable-outside-close...>` disables the outside close
✔ behaves as expected on drag-clicks, reliably triggers close on outside mouse-up
❌ One minor inconsistency with drag-release: 
  * Mouse (non-touch) device: click-drag-release_in_outside_area triggers close ✔
  * Touch device: tapAndHold-drag-release_in_outside_area does not trigger close ❌
-> Sloppy taps prevent modal from being closed

IMHO can still be closed as done if ❌ is considered too minor.
