### ISSUE TITLE
Bug: Calcite Popover positions itself off the modal rather than the screen when using with Calcite Modal on Firefox and Safari

### ISSUE THREAD

**Issue by ptmdmusique** [Esri/calcite-components#2242]
### Actual Behavior

Calcite Popover has an additional offset based on the modal position if it's created inside the modal. 
This happens on FIrefox and Safari but works on Chrome

### Expected Behavior

Calcite Popover should be positioned based on the screen on Firefox and Safari

### Reproduction Steps or Sample

1. Go to https://codepen.io/ptmdmusique/pen/QWbQNjN
2. Notice how the popover has an offset from the `referenceElement` (blue button), which equals to the position of the modal relative to the screen

### Relevant Info

Browser: Firefox, Safari

**Comment by ptmdmusique** [comment]
cc @paulcpederson

**Comment by driskull** [comment]
If you give that test div a position of relative it fixes it.

```css
.test {
  min-height: 1000px;
  position: relative;
}
```

I'm not sure if 'modal' needs to do some slotted selector to do that but that fixes the issue.

**Comment by ptmdmusique** [comment]
> If you give that test div a position of relative it fixes it.
> 
> ```css
> .test {
>   min-height: 1000px;
>   position: relative;
> }
> ```
> 
> I'm not sure if 'modal' needs to do some slotted selector to do that but that fixes the issue.

That fixes it! But there is still an overflow issue 
![image](https://user-images.githubusercontent.com/37349324/121239580-4379eb80-c84e-11eb-9222-d7d80d2f5e98.png)

I'm checking the popper js doc and wondering if it's possible to expose `preventOverflow` mentioned [here](https://popper.js.org/docs/v2/modifiers/prevent-overflow/) ❓

**Comment by driskull** [comment]
We can potentially do that later down the road. 👍  I'm hesitant to do it right now because it opens a lot of options for that and makes the API more complex.

For now, can you just size the content inside the popover so that its not so wide?

```css
    padding: 12px 16px;
    width: 400px;
```

**Comment by ptmdmusique** [comment]
I think we can try doing that `preventOverflow` as a boolean and see if it works

Also, I'm wondering if we can make the popover children of `body` instead because it escapes all the context problems overall (I _think_)

**Comment by ptmdmusique** [comment]
Ah that would works!

What do you think about this case

**Comment by driskull** [comment]
For that, the easiest solution would be to place the popover outside of the modal.

**Comment by ptmdmusique** [comment]
I see. Well I'll stick to the `relative` and `auto`. Closing! Thanks a bunch 👋
