### ISSUE TITLE
Docs: Use correct button order in Storybook

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#2243]
### Description 

Currently we are not using the correct button order in a few of our component examples in Storybook. We should update these to match the correct button order based on our placement documentation : https://developers.arcgis.com/calcite-design-system/components/button/

Correct example:
Modal : https://esri.github.io/calcite-components/?path=/story/components-modal--simple

### Which Component
Panel, Flow (maybe others?)

cc @julio8a @bstifle

**Comment by caripizza** [comment]
Taking this one as a part of pr #2251, since I'm already modifying these components' RTL stories.
