### ISSUE TITLE
Enhancement: Add support for tabs in panel header

### ISSUE THREAD

**Issue by bpatterson88** [Esri/calcite-components#2245]
### Description

Currently, placing tabs inside a panel header disrupts the padding and overall layout. The panel header should be updated to better support tabs and, potentially, other similar components.

Example of current UI:
![Screen Shot 2021-06-01 at 3 48 30 PM](https://user-images.githubusercontent.com/15875886/120399418-d5cf3c00-c2f0-11eb-8a6f-0f4f7dcf34a6.png)

### Acceptance Criteria 

Update the panel header so that tabs, and other components, can be placed inside without disrupting spacing.

Example:
![Screen Shot 2021-06-01 at 3 50 52 PM](https://user-images.githubusercontent.com/15875886/120399578-28a8f380-c2f1-11eb-9d58-46820ab92b86.png)

### Relevant Info 

This is a requirement for the new Arcade editor.

#### Which Component

`calcite-panel`

#### Example Use Case

The arcade editor uses panel headers as a surface for tabs.

cc @ffaubry

**Comment by macandcheese** [comment]
Related? https://github.com/Esri/calcite-components/issues/2131

**Comment by bpatterson88** [comment]
Yep closing in favor of that one. Thanks!
