### ISSUE TITLE
Enhancement: calcite-value-list + filter more events?

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2254]
### Description

From @dhrumil83

![image](https://user-images.githubusercontent.com/44481292/120675020-8bad9e00-c449-11eb-9306-78783ee62892.png)

Updated design for multi select on attributes, has the regular filter + additional filter via numbers, integers, strings and date.
https://www.figma.com/file/jqVQ2vzkumTI7wVf3eQMv1/Multiple-fields-formatting
 
Here is the issue:
Workflow attached.
Once user clears the 2nd filter(Numbers filter in this example), I somehow need to know if user had typed anything and apply that filter. (even better if calcite can figure it out on its own with the new values provided, or I can call a function and tell it something changed and to reapply the search filter)
I don’t see anything that can help with this in the docs for calcite-value-list, calcite-value-list-item and calcite-filter.
 
So far I think we have used the options via calcite-value-list only for sorting, and not applying filters on top of the search filter.

![attr](https://user-images.githubusercontent.com/44481292/120675100-a1bb5e80-c449-11eb-8df6-078ff3a4f51b.gif)

Any suggestions?

**Comment by driskull** [comment]
I think we can either:

- Expose an event for when a filter is done so a user can further filter items
- Allow for a function to be called to filter more items.

**Comment by AdelheidF** [comment]
duplicate of https://github.com/Esri/calcite-components/issues/2209
