### ISSUE TITLE
Bug: `mouseover` listener fired twice on buttons with tooltips

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2255]
### Actual Behavior
If a button has a tooltip, any user-land `mouseover` listener/handler on a `<calcite-button>` element is triggered twice when mousing onto the button.

The events passed to the listeners are almost identical except for differing `composedPath()` values:

|  | First event | Second event |
| - | - | - |
| **composedPath()** | `[calcite-button, ...]` | `[button, document-fragment, calcite-button, ...]` |

### Expected Behavior
The user-land listener is triggered once per `mouseover` event.

### Reproduction Steps or Sample
```html
<calcite-tooltip reference-element="button">tooltip</calcite-tooltip>

<calcite-tooltip-manager>
  <calcite-button id="button">button</calcite-button>
</calcite-tooltip-manager>

<script>
  document.getElementById('button').addEventListener('mouseover', event => {
    console.log('mouseover');
  });
</script>
```

1. Mouse on to the button
2. Notice `"mouseover"` appears twice in the dev console.

### Relevant Info
Possibly related to how `<calcite-tooltip-manager>` (or Stencil) attaches the `mouseEnterShow`. Temporarily removing it produces the expected behavior with regards to how many times the user-land listeners are fired.

_Version_: `@esri/calcite-components@1.0.0-next.214`

**Comment by driskull** [comment]
@nwhittaker no events are added to the buttons, only to the `calcite-tooltip-manager` gets events. It doesn't seem like this is related. Maybe something related to the calcite-button itself?

**Comment by driskull** [comment]
@nwhittaker I think this is as expected because the tooltip manager uses capture events.

**Comment by nwhittaker** [comment]
>Maybe something related to the calcite-button itself?

I would agree there's something special about the interplay between `calcite-tooltip-manager` and a `calcite-button`. If I replace the button w/ something else, like a link, I don't see the handlers fired twice.

>I think this is as expected because the tooltip manager uses capture events.

If it was expected, wouldn't the handlers fire twice for non-button elements too?

**Comment by driskull** [comment]
Its probably the way calcite-button is spreading attributes to the internal tag. Probably happening on the host and the internal button.

**Comment by driskull** [comment]
#2187

**Comment by nwhittaker** [comment]
Now that https://github.com/Esri/calcite-components/issues/2310 is merged and released, I updated the issue to reflect its behavior as of `1.0.0-next.227`.

In summary, I see the `mouseover` event fired twice. I'm not seeing the `mouseout` event fired twice. However, when it fires, I'm seeing it's target is the `<button>` element instead of the `<calcite-button>` element -- don't know if that's expected, though.

**Comment by driskull** [comment]
Yes, that is expected because mouseover fires on entering each new element, even child elements. This is to keep a popover open when hovering child elements.

**Comment by nwhittaker** [comment]
>Yes, that is expected because mouseover fires on entering each new element, even child elements.

The two events I was seeing had the same targets and composed paths -- so thought it might be the same issue. That being said, I'm unable to reproduce the issue anymore w/ the reduced test case. What I observed in https://github.com/Esri/calcite-components/issues/2255#issuecomment-867897481 was in-app, so there may be other factors going on -- I'll close this issue. Thanks for looking!

**Comment by driskull** [comment]
No problem. thanks for testing again and reporting it!
