### ISSUE TITLE
Enhancement: Value list and Pick list, change summary font to Avenir

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2258]
### Description
Change Summary font in Value list and Pick list from monospace to avenir-regular (400)

#### Which Component
Value list and Pick list

![image](https://user-images.githubusercontent.com/14083530/120709661-bd8f2680-c482-11eb-8b19-75adbcefd6ed.png)

**Comment by julio8a** [comment]
This should be connected to the refactor project. I think @mike9959 might be working on these for the refactor.

**Comment by asangma** [comment]
Installed and ready for you to review again. lol

**Comment by bstifle** [comment]
Done and done
