### ISSUE TITLE
Enhancement: Block (and maybe BlockSection) - add status property and appropriate icon to header

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2261]
### Description
Add a property to Block that aligns with the Notice and Input status states.
Use the icon property/slot to show appropriate icons for states.

### Acceptance Criteria 
* use existing statuses
* use existing same icons

#### Which Component
Block and BlockSection

#### Example Use Case
An input or something inside a Block is in an error or warning state...it needs attention otherwise the workflow is obstructed. The thing needing attention is inside a Block that is collapsed and there's not clear way to route the user to the error.

### Designs
These design show something like `status="danger"`.
Would also have "warning".
I'm not sure if we need "success", but it wouldn't hurt.
I don't think we need "info".

Also, this could also just be `status="invalid"` to be more like Label and Input, but having "warning" and "success" might be nice. I'm open to suggestions on that.

**Collapsed.**
I'm not sure how I feel about the border, but it matches Alert.

![Frame 2](https://user-images.githubusercontent.com/12503298/120832088-1c9d7b80-c515-11eb-9c46-7a4fe84ed438.png)

**Expanded**
This shows error states for Block section.
Note: the input error state is not part of this issue.

![Frame 1](https://user-images.githubusercontent.com/12503298/120832191-39d24a00-c515-11eb-8a2c-5b57c9d2bf78.png)

### Bubbling status?
Possibly a v2. 
Might be nice if Block could inspect its contents for Calcite Components that are in invalid/danger/warning states and bubble that status up to the header. Based on that, it could update its status to the most severe status.

**Comment by asangma** [comment]
Could use this in time for 9.3.
cc @CodeBarker

**Comment by bstifle** [comment]
@asangma  suggest making the red line 2px to be cohesive with notice and alert

**Comment by asangma** [comment]
Updated UI.
![image](https://user-images.githubusercontent.com/12503298/122448728-ed95f980-cf59-11eb-9ed7-279c09647c3a.png)

**Comment by asangma** [comment]
> the red line 2px to be cohesive with notice and alert

Hmmm...I had the impression we were nixing the border.

**Comment by bstifle** [comment]
YEAH kill it. that comment was from last night

**Comment by asangma** [comment]
@caripizza Would you mind assigning this one to someone to verify? :)

**Comment by caripizza** [comment]
@asangma yep I'll verify it

**Comment by asangma** [comment]
🙏🏾

**Comment by asangma** [comment]
See `demos/shell/block-configurations.html`

**Comment by caripizza** [comment]
Verified the new UI and behavior on master: now block and block-section can each have their own unique `status` properties. And when `status` is set to `valid` or `invalid`, the elements render with a status icon which matches the valid/invalid input-message status icons.
