### ISSUE TITLE
Bug: calcite-dropdown throws errors on open (bad items array)

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-components#2268]
### Actual Behavior

When opening a dropdown, an error is thrown:
```
utils.js:12293 Uncaught TypeError: Cannot read property 'isLink' of undefined
```
As a consequence, no item is focused and other things like the `max-items` attribute fail.

### Expected Behavior

No errors should be thrown when opening the dropdown. Furthermore, the list of items should be rebuilt when needed, rather than only when the component gets loaded.

### Reproduction Steps or Sample

Could not reproduce this in the Storybook demos but this is happening in one of our JS API widgets, using Maquette.

Digging in I noticed this happens because the `calcite-dropdown` component tries to access `item.attributes.isLink` but the item doesn't exist. This is because `componentDidLoad` runs before any of the calls to `registerCalciteDropdownGroup`, which means that when the dropdown is opened, the `items` array isn't correct.

### Relevant Info

- Happens when using Calcite Components through Maquette.js in an ArcGIS JS API widget.
- Issue exists in both `1.0.0-beta.55` and `1.0.0-next.215`.

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [x] NPM package

**Comment by caripizza** [comment]
Related: #2026

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
@hccampos @gavinr Can either of you help verify this one? FYI, this will be in today's release. Thanks!

**Comment by jcfranco** [comment]
Closing as self-verified. Please submit a new issue if something else needs to be addressed.
