### ISSUE TITLE
Bug: Calcite Flow not found in dist of calcite in JS API

### ISSUE THREAD

**Issue by previnWong** [Esri/calcite-components#2269]
### Actual Behavior

In the calcite distributable in node modules in JS API, calcite flow is missing.  See screenshot below
![image](https://user-images.githubusercontent.com/11183838/121062509-ff1d1b80-c779-11eb-9c2e-775ce65072b7.png)

### Expected Behavior

A js file should exists in this folder for FLOW.

### Reproduction Steps or Sample

1.  Look under this directory and Calcite Flow is missing.
<webroot>\arcgis-js-api\node_modules\@esri\calcite-components\dist\custom-elements\bundles

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [x] NPM package

**Comment by jcfranco** [comment]
Installed. This will be available in `@next` and today's (later) release.

**Comment by jcfranco** [comment]
Closing as verified based on https://unpkg.com/browse/@esri/calcite-components@1.0.0-next.219/dist/custom-elements/bundles/.
