### ISSUE TITLE
Enhancement: ActionMenu - close menu when item is selected

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2273]
### Description
From a [previous PR](https://github.com/Esri/calcite-components/pull/2157#issuecomment-853999405):
By default, close the ActionMenu when an item is selected.
We probably don't need a property to override this default.

### Acceptance Criteria 
Keyboard accessibility.

#### Which Component
ActionMenu

#### Example Use Case
Selecting an item from the menu.

**Comment by jcfranco** [comment]
@driskull Can you update the issue fields? This is still marked as new and awaiting triage.

**Comment by julio8a** [comment]
Verified on master.
