### ISSUE TITLE
Bug: calcite-radio-button-group with calcite-radio-button

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2286]
Alignment is wrong now with beta.55. Was working correctly with beta.54.

beta.55
![image](https://user-images.githubusercontent.com/44481292/121274299-0e39c180-c87f-11eb-8945-d9b684383ae1.png)

![image](https://user-images.githubusercontent.com/44481292/121274075-8bb10200-c87e-11eb-9540-5515f95f2625.png)

beta.54 (Map Viewer production)
![image](https://user-images.githubusercontent.com/44481292/121274266-fe21e200-c87e-11eb-9184-f2218d4ee764.png)

![image](https://user-images.githubusercontent.com/44481292/121274129-abe0c100-c87e-11eb-8101-e33e40bc9263.png)

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by kevindoshier** [comment]
@AdelheidF - I ran into this too, and this fixed it for my case

`<calcite-label layout="inline">
   <calcite-radio-button />
    My Radio Label
</calcite-label>`

**Comment by AdelheidF** [comment]
No, that didn't do anything. Maybe because it's inside a block-section?

<img src=https://user-images.githubusercontent.com/44481292/121397621-5b627580-c909-11eb-851f-e990f96064dc.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/121397407-235b3280-c909-11eb-8baa-cfb94140388b.png width=400/>

**Comment by AdelheidF** [comment]
I figured it out. The text now needs to be outside of the radio-button as well.
