### ISSUE TITLE
Bug: calciteTreeSelect event doesn't fire on spacebar keypress

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#2290]
### Actual Behavior
The event `calciteTreeSelect` fires when the user clicks on a tree item or presses enter while focused on the tree-item. When the user is focused on the `calcite-tree-item` and presses the spacebar key, the `calcite-tree-item` appears to be selected, but the event doesn't fire.

### Expected Behavior
The event `calciteTreeSelect` should fire on click, enter keypress and spacebar keypress.

### Reproduction Steps or Sample

1. console.log the event returned from `calciteTreeSelect` 
2. Press the enter key while focussed on a `calcite-tree-item`
3. Notice that the event is logged
2. Press the spacebar while focussed on a `calcite-tree-item`
3. Notice that the event is not logged despite the tree item appearing selected

### Relevant Info

_Browser_: Chrome, Firefox
_Tree Accessibility Guides_: https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView
_Version_: `@esri/calcite-components@1.0.0-beta.51`

- [ ] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
@joeyHarig Can you confirm if this is still an issue? The following codepen uses the latest and the event seems to fire on click and Enter/Space keydown: https://codepen.io/jcfranco/pen/gOmNByj

Sidebar, I did notice that when a nested item is selected, two events are fired. @paulcpederson Do you know if this is the expected behavior? If not, I'll create a separate issue for this.

**Comment by paulcpederson** [comment]
@jcfranco it's the multiple trees, each one emits a change event, so when you select one of the nested ones you get n events based on your depth.

**Comment by paulcpederson** [comment]
I don't know if it's _expected_, though...

**Comment by joeyHarig** [comment]
@paulcpederson Let me update our CC dependency and I'll get back to you.

**Comment by jcfranco** [comment]
@joeyHarig Did you get a chance to test this with the latest?

**Comment by joeyHarig** [comment]
@jcfranco I have not yet, but I will have time tomorrow and I'll get back to you by EOBD

**Comment by jcfranco** [comment]
Thanks! I truly appreciate it. 😄

**Comment by joeyHarig** [comment]
@jcfranco I created a code pen where I have reproduced the bug: https://codepen.io/joeyHarig/pen/eYWmpbm?editors=1111

It looks like `selection-mode="children"` is the difference. I changed selection mode to equal "single" on our end and it resolved the issue.

**Comment by jcfranco** [comment]
@joeyHarig Awesome. Thanks for the additional info. I see the issue now. Will submit a PR soon.

**Comment by jcfranco** [comment]
Installed! 

@joeyHarig Can you help verify this one?

**Comment by joeyHarig** [comment]
@jcfranco Can confirm works great!

**Comment by jcfranco** [comment]
Thanks for verifying! 🎉
