### ISSUE TITLE
Bug: Date Picker - First Day of the week is not localized 

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#2291]
Reported in the Map Viewer Time Slider Date Picker:

In Russian, the calendar is localized, by the first day of the week is Sunday which is incorrect:

![image](https://user-images.githubusercontent.com/50747646/121410862-dcc10480-c917-11eb-87ff-06afad211be6.png)

https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/1913

cc @paulcpederson @jcfranco

**Comment by caripizza** [comment]
Related: #1355

**Comment by jcfranco** [comment]
Installed. @zaramatheson You can use the following codepen after `@next` deploys (in ~10 mins) to verify. https://codepen.io/jcfranco/pen/vYxqWVM?editors=1000

**Comment by zaramatheson** [comment]
@jcfranco It looks like this is an issue still for other languages https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/3522

**Comment by julio8a** [comment]
To avoid having individual language issues created, it seems we need a list of the languages that need Mon as the first day of the week and tackles them all. @jcfranco, is this something the i18n team can help us identify?

**Comment by babakbolour** [comment]
@julio8a  we will get the list to you @raje9276

**Comment by julio8a** [comment]
Thanks @babakbolour!

**Comment by babakbolour** [comment]
@julio8a  pls access this web tool we created for the info: [here](http://i18nsrv1/localelookup/GroupFormats) 
this is reading from CLDR.
Also, I hope you don's hard-code the first day of the month, by  UI language! has to be by locale/region (i.e. for Switzerland, we should show Monday, regardless of the languages spoke there: German, Italian, French, other). if you need coding help, @raje9276 can help.

**Comment by jcfranco** [comment]
@zaramatheson Can you help verify? Otherwise, we'll close as self-verified. 

@babakbolour Thanks for the great resource! The date picker has its own resources to build its UI: https://github.com/Esri/calcite-components/tree/master/src/components/calcite-date-picker/assets/calcite-date-picker/nls

**Comment by jcfranco** [comment]
Closing as self-verified. 

@zaramatheson Please open a new issue if anything new comes up. Thanks!

**Comment by zaramatheson** [comment]
@jcfranco It looks like this is still an issue for some languages: https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/3522
