### ISSUE TITLE
Bug: ActionMenu - fix offsetDistance & focus ring

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2295]
### Actual Behavior
1. Since ActionMenu no longer has a pointer, there is now too much space between the menu and its trigger.
2. Focus ring is sometimes cut off

### Expected Behavior
1. offsetDistance of zero
2. unclipped focus outline

### Reproduction Steps or Sample

<img width="604" alt="Screen Shot 2021-06-09 at 2 59 13 PM" src="https://user-images.githubusercontent.com/12503298/121435176-4e5a7c00-c933-11eb-99d0-aea3eff463d2.png">

1. view demo app

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by julio8a** [comment]
verified on master.
