### ISSUE TITLE
Question: border-radius - Seems like we should use Tailwind or add it to our config

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2297]
### Question
Right now, there's a [CSS var for border radius](https://github.com/Esri/calcite-components/blob/master/src/assets/styles/global.scss#L45). 
Seems like we should either use Tailwind's default border-radius (which is 0.25rem/4px) or store our custom one in the config, yeah?

### Helpful Details 
Tailwind's border radius: https://tailwindcss.com/docs/border-radius

**Comment by asangma** [comment]
cc @bstifle

**Comment by bstifle** [comment]
as long as we have 4px border radius im a happy boi

**Comment by caripizza** [comment]
Our current config includes the following values ([mostly defaults](https://github.com/tailwindlabs/tailwindcss/blob/v1.9.6/stubs/defaultConfig.stub.js)):
```
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      default: "0.25rem",
      md: "0.375rem",
      lg: "0.5rem",
      xl: "0.75rem",
      "2xl": "1rem",
      "3xl": "1.5rem",
      full: "9999px",
      half: "50%"
    },
```
What new values are you proposing?

**Comment by asangma** [comment]
@caripizza I think `default` is 4px.

I'm not so much proposing a new value. :)
I just noticed that we're defining a 3px radius in our [global.scss](https://github.com/Esri/calcite-components/blob/master/src/assets/styles/global.scss#L45).

**Comment by caripizza** [comment]
@asangma Got it, it looks like the `--calcite-border-radius` var was added long ago in pr #235, so it's a super old value. As far as I know, we can refactor it out at this point and go with your `default` 4px suggestion.

Do you want to take a crack at that work, as a part of this issue? (Thinking we can also remove that `px` 1px borderWidth addition in the config, since that's already included in Tailwind's defaults too.)

**Comment by asangma** [comment]
@caripizza I might be able to get to it this sprint or next. It'll include refactoring a couple stylesheets I think.

**Comment by caripizza** [comment]
@asangma what if we do this in global.scss instead? (Might require less stylesheet changes.)
```scss
--calcite-border-radius: theme("borderRadius.default");
```

**Comment by caripizza** [comment]
@julio8a can you add this one to your alert refactor? I think we should keep using this `--calcite-border-radius` global CSS var if we can (just needs the update from my above comment).

**Comment by caripizza** [comment]
Self-assigning this one per conversation with Julio

**Comment by caripizza** [comment]
@asangma  I jumped the gun on this one, calcite-alert really wants that 3px border-radius. I was hoping to refactor it to only have a 2px top border width, but now that its corners are rounded (pr #2339), it shows a wonky curved top border with anything other than the 3px border-radius. I'm leaving this value in place for now and we can revisit down the road if needed.

**Comment by bstifle** [comment]
@caripizza the only corner radius in CC should be 4px :)

**Comment by caripizza** [comment]
Got it @bstifle

**Comment by caripizza** [comment]
Assigning to @asangma for verification.

**Comment by julio8a** [comment]
Verified in master
