### ISSUE TITLE
New Component: Card

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#230]
### Description
Cards contain content and actions about a single subject.
See [Material card](https://material.io/components/cards/#anatomy).

#### User Stories
Developer wants to add a highly visual entry point to more content or a larger set of configurations.

### Acceptance Criteria 
![image](https://user-images.githubusercontent.com/12503298/66436320-95b09c80-e9db-11e9-8ce7-d2e99e3c1b25.png)

_stolen from https://material.io/components/cards/_

1. Container
Card containers hold all card elements, and their size is determined by the space those elements occupy. Card elevation is expressed by the container.

2. Thumbnail [required]
Cards can include thumbnails to display an avatar, logo, or icon.

3. Heading text [required]
Header text can include things like the name of a photo album or article.

4. Footer with leading and trailing slots

5. Icons [optional]
Cards can include icons for actions.

6. Prop for prioritizing height of image for crop (default will prio width)

7. Image-scale s | m | l (for dealing with thumbnail)

#### Desired Behavior
States
- idle
- hover/focus
- selected
- disabled
- loading

#### Desired Look & Feel
How @mitc7862 wants it.

### Helpful Details
- https://github.com/Esri/calcite-components/issues/52
- https://esri.github.io/calcite-web/documentation/components/#card

### Designs
![image](https://user-images.githubusercontent.com/12564905/68063321-3e95a300-fccd-11e9-895e-5be0e7770d56.png)

### API Design
```
 @Prop({ reflect: true }) disabled = false;

 @Prop({ reflect: true }) loading = false;

 @Prop({ reflect: true }) selected = false;

 @Prop({ reflect: true }) respectImageHeight = false;

 @Prop({ reflect: true }) theme: "light" | "dark" = "light";

```

```
<slot name="thumbnail">  
<slot name="header">  //can put icons in too
<slot name="button-action">
<slot name="footer-leading">
<slot name="footer-trailing">
```

**Comment by kat10140** [comment]
added theme prop above. removing scale. don't need scale but will need layout options in v2

**Comment by kat10140** [comment]
@mitc7862 i can't assign you for some reason

**Comment by kat10140** [comment]
@asangma styling? 😬

**Comment by macandcheese** [comment]
@asangma can you give feedback on the currently open PR? Thanks!
