### ISSUE TITLE
Enhancement: Trigger `calciteLookupChange` event when the comobox is in single select mode

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#2305]
### Description
Currently, the `calciteLookupChange` event does not emit when the combobox is in single select mode. It would be a nice convenience to have it emit on single select the same it does for multi. 
### Acceptance Criteria 
An event is emitted when the selected item changes in single select mode on the combobox
### Relevant Info 
Right now it checks specifically for multi select: https://github.com/Esri/calcite-components/blob/master/src/components/calcite-combobox/calcite-combobox.tsx#L529
#### Which Component
`calcite-combobox`
#### Example Use Case
I am creating a component that uses the combobox and can operate in either single or multi select mode. Having a single unified event would simplify the event handling.

**Comment by mhogeweg** [comment]
is anyone actively working on this? we are using this widget and are being affected by this issue.

**Comment by driskull** [comment]
`calciteLookupChange` is documented as emitting when 'selectedItems' have changed. However, we don't have any event for when 'selectedItem' has changed.

I'm wondering if we should add a separate event for when a 'selectedItem' has changed or if we should reuse the same event and document it differently.

Internally, there's no reason why we can't just use 'selectedItems' when the mode is "single" as well as "multiple".

@julio8a @jcfranco what do you think?

**Comment by ethanbdev** [comment]
Closing due to https://github.com/Esri/calcite-components/issues/2499
