### ISSUE TITLE
Bug: calcite-slider - in Firefox, clicking the slider track doesn't trigger a change

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-components#2309]
### Actual Behavior

- In Firefox, clicking on the slider track doesn't trigger a change whereas in Chrome it does.
- When dragging, changes fire normally.

### Expected Behavior

Clicking the track should trigger a change just like in Chrome.

### Reproduction Steps or Sample

1. Open an app with a <calcite-slider> in Firefox
2. Click on the track.
3. Note that changes don't get triggered.

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.55`
_Browser_: Firefox (tested in Firefox Developer Edition 90.0b6, for example)

- [ ] CDN
- [x] NPM package

**Comment by jcfranco** [comment]
Installed! @hccampos can you help verify this one too?

**Comment by hccampos** [comment]
Tested with Firefox 91 and clicking the track works fine now.

**Comment by jcfranco** [comment]
@hccampos Thanks for verifying!
