### ISSUE TITLE
Bug: Tooltip can close prematurely for non-leaf nodes

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2310]
### Actual Behavior
If a tooltip is associated with a reference element that contains child nodes, mousing off a child node (but not off the reference element) causes the tooltip to close.

![Screen Recording 2021-06-11 at 12 48 30 PM](https://user-images.githubusercontent.com/421496/121723702-d916b480-cab4-11eb-95a5-286abdf37c15.gif)

### Expected Behavior
Tooltip is open as long as the mouse is within the reference element.

### Reproduction Steps or Sample

```
<calcite-tooltip-manager>
  Ut enim ad minim veniam, quis <calcite-button id="reference-element">nostrud <b>exercitation</b></calcite-button> ullamco laboris nisi ut aliquip ex ea commodo consequat.
</calcite-tooltip-manager>

<calcite-tooltip reference-element="reference-element">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
</calcite-tooltip>
```

1. Mouse on the bolded text in the button.
2. Mouse off the bolded text, but not off the button.
3. Wait for the tooltip to disappear.

### Relevant Info
Can the tooltip manager filter out `mouseleave` events not targeting a reference element?

_Version_: `@esri/calcite-components@bfadb3d3`

**Comment by julio8a** [comment]
Verified.
