### ISSUE TITLE
Question: Slot cleanup questions

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2313]
### Question

- calcite-input
  - should 'calcite-action' be documented as just 'action'? I think its wrong now. bug?
- calcite-dropdown
  - Should 'dropdown-trigger' just be 'trigger'?
-  calcite-tab
  - Should 'tab-nav' just be 'nav'?

### Helpful Details 

Slot cleanup questions

**Comment by driskull** [comment]
cc @julio8a

**Comment by julio8a** [comment]
Thx @driskull, these updates would match up consistency with nomenclature across components?

**Comment by driskull** [comment]
I think so. the first one might be a doc bug but someone needs to confirm.

**Comment by jcfranco** [comment]
1. This is a doc issue: https://github.com/Esri/calcite-components/issues/2150. 
2. I think we could simplify and have a consistent name for trigger slots (similar to another PR that @driskull recently submitted). 
3. Similar to ☝🏼 , but no strong preference. Sidebar, is `nav` commonly used or do we need `navigation`? I know there's a `<nav>` element, but it has different semantics.

**Comment by macandcheese** [comment]
> Sidebar, is `nav` commonly used or do we need `navigation`? I know there's a `<nav>` element, but it has different semantics.

We hope to tackle a true “app navigation” story this year, for which we probably (?) want to use ‘calcite-nav’ (and ‘calcite-nav-*’ for child components).

Using “nav” in tabs is a little misleading IMO, it’s really a wrapper for only ‘calcite-tab-title’ children. 

Maybe ‘calcite-tab-title-group’? To me it’s a more literal name, and more closely matches other instances of parent-child component nomenclature in the library (option, pick list, dropdown, tile, etc.)

**Comment by driskull** [comment]
We don't prefix any slots elsewhere with `calcite-` or `component-` so we should be consistent.

**Comment by macandcheese** [comment]
I meant a slot names ‘title-group’ based on a component of ‘calcite-tab-title-group’, but obviously that’s a much larger change to rename the ‘calcite-tab-nav’ component.

**Comment by driskull** [comment]
I searched for any more slot inconsistencies and things look good.

**Comment by geospatialem** [comment]
Verified slot renames for:

1. `input`:
  - `action` slot
2. `dropdown`
  - `trigger` slot
3. `tabs`
  -  `title-group` slot
