### ISSUE TITLE
Bug: Boolean props work incorrectly in react output target

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#2315]
### Actual Behavior

boolean props render with `true` or `false` strings. So:

```jsx
<CalciteSlider labelTicks={false} />
```

becomes:

```html
<calcite-slider label-ticks="false" />
```

### Expected Behavior

`false` values for booleans should be ommited, like:

```html
<calcite-slider />
```

According to this: https://github.com/ionic-team/stencil-ds-output-targets/issues/123 we could use the following to update the boolean behavior:

```ts
// attachProps.ts
if (propType === 'boolean') {
  if (newProps[name] === true) {
    node.setAttribute(camelToDashCase(name), camelToDashCase(name));
  } else {
    node.removeAttribute(camelToDashCase(name));
  }
}
```

We should investigate if we can just patch and fix this on our side or we need updates to the actual ds library.

**Comment by driskull** [comment]
We shouldn't have any boolean properties that are true by default, so can you just leave the attribute off in this scenario? `<CalciteSlider labelTicks={false} />`

**Comment by paulcpederson** [comment]
@driskull yeah I mean I think people can code around it, but it's a little time bomb for every react user. I should clarify that you wouldn't just be doing `<CalciteSlider labelTicks={false} />` it would be more like `<CalciteSlider labelTicks={someStatefulVariableThatChanges} />`

**Comment by driskull** [comment]
Agreed. It's just a JSX workaround that we need to solve so to me it seems like it should be fixed in the ds library.

**Comment by paulcpederson** [comment]
Yeah, that would be ideal, for sure.

**Comment by jcfranco** [comment]
Closing as this is outside of this project's scope. Let's see if that Stencil issue picks up traction, otherwise, we'll have to patch on the output-target side.
