### ISSUE TITLE
Bug: Mousing over non-reference elements keeps tooltip open

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2318]
### Actual Behavior
Mousing off a tooltip's reference element and then continuously mousing over other elements within the same `<calcite-tooltip-manager>` prevents the tooltip from closing.

![ezgif-3-14eaa7d2909c](https://user-images.githubusercontent.com/421496/122106279-b7d10380-cde7-11eb-9260-1d375b56c52a.gif)

### Expected Behavior
The tooltip closes after mousing off the reference element.

### Reproduction Steps or Sample
```
<calcite-tooltip-manager>
  <calcite-button id="reference-element">with tooltip</calcite-button>
  <calcite-button">without tooltip</calcite-button>
</calcite-tooltip-manager>

<calcite-tooltip reference-element="reference-element">tooltip</calcite-tooltip>
```

1. Mouse on to the "with tooltip" element.
2. Mouse off the "with tooltip" element.
3. Mouse on/off the "without tooltip" element.
4. Stop moving the mouse to allow the tooltip to close.

### Relevant Info
Related to, but not introduced by, the work for https://github.com/Esri/calcite-components/issues/2255.

_Version_: `@esri/calcite-components@1.0.0-next.226`

**Comment by bstifle** [comment]
Nice catch!

**Comment by driskull** [comment]
Installed.

**Comment by julio8a** [comment]
verified on master.
