### ISSUE TITLE
Bug: calcite-input-time-picker - clicking arrows should keep popup open

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2328]
### Actual Behavior

When I click the arrows above and below the seconds the little popup stays open, which is very convenient when I want to click it a bunch of times. When I click the arrows once for hour, minute, and meridiem the popup closes, which is annoying if you want to click it several times. You’re basically forced to enter a new number value instead of using the arrows.

![image](https://user-images.githubusercontent.com/44481292/122467464-66538080-cf6f-11eb-9844-e54b153e0bcc.png)

### Expected Behavior

popup stays open when clicking all arrows and closes on enter or clicking outside.

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by driskull** [comment]
@AdelheidF Can you verify that this is still happening in the latest version?

**Comment by AdelheidF** [comment]
still the same with next.237

**Comment by driskull** [comment]
@AdelheidF can you create a codepen with steps? I'm unable to reproduce it on our test apps.

**Comment by driskull** [comment]
cc @eriklharper if he can reproduce

**Comment by driskull** [comment]
Seems like this component also needs a story in storybook. cc @eriklharper

**Comment by driskull** [comment]
@AdelheidF I'm not seeing it here: https://esri.github.io/calcite-components/?path=/story/components-controls-time-input-time-picker--light-theme

**Comment by AdelheidF** [comment]
Sorry, my bad. A re-render causes this.
