### ISSUE TITLE
Bug: calcite-input-time-picker - unexpected behavior when typing in a number

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2330]
### Actual Behavior

When entering a new number value I don’t get a cursor. It’s a bit weird if I wanted to change the ‘2’ in 12 to a ‘0’, e.g.

![image](https://user-images.githubusercontent.com/44481292/122467826-d8c46080-cf6f-11eb-8738-2eed6b9e2297.png)

If I use a backspace to delete the number, to enter a new one, it closes the popup and changes the time to an empty input box.

![image](https://user-images.githubusercontent.com/44481292/122467898-e7ab1300-cf6f-11eb-8325-8746dddc6892.png)

I guess you have to just start typing the new value and then it works, but that is not what I expected.

### Expected Behavior

works like a typical input box

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by eriklharper** [comment]
> If I use a backspace to delete the number, to enter a new one, it closes the popup and changes the time to an empty input box.

@AdelheidF  which browser/OS are you seeing this behavior?  I've tested this on Brave (Chromium), Chrome, Safari and Firefox on MacOS and it doesn't do this.

**Comment by AdelheidF** [comment]
With a more recent next version I see this when I use backspace.

first backspace on the hour
![image](https://user-images.githubusercontent.com/44481292/126243130-649d83f8-99bb-48fb-b270-9504c938eaac.png)

second backspace on the hour
![image](https://user-images.githubusercontent.com/44481292/126242920-6c4fcf9b-5266-4a3c-a8fe-d447f92bc24e.png)

first backspace on the second
![image](https://user-images.githubusercontent.com/44481292/126243023-0dcd58d9-ee0f-4cfa-8859-27974cf7f791.png)

second backspace on the second
![image](https://user-images.githubusercontent.com/44481292/126243059-da90870f-3045-4b14-8919-cf4c96de721f.png)

I guess it's OK now.
