### ISSUE TITLE
Question: calcite-input-time-picker - calciteInputTimePickerChange does not return event.detail

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2332]
### Question

The calciteInputTtimePickerChange event returns a CustomEvent without a detail property. Is this expected? I have to use event.target.value to get the value. I thought CustomEvent always returns significant info via details.

**Comment by jcfranco** [comment]
This is behaving as expected. Using the event's `target`/`currentTarget` to access info available on the component is the recommended way. The detail object from custom events will only have a value if there's data that can't be obtained from a component attribute/property.
