### ISSUE TITLE
Bug: calcite-color-picker - color indicator doesn't follow pointer in Safari

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-components#2335]
### Actual Behavior

![color-picker-safari](https://user-images.githubusercontent.com/3759114/122550528-125e9f80-d034-11eb-9c87-7565bf5e3336.gif)

As can be seen above, when moving the mouse pointer in Safari, the color indicator doesn't match the pointer, like it does in Chrome and Firefox.

### Expected Behavior

The color indicator should always match the pointer like it does in Chrome and Firefox.

### Reproduction Steps or Sample

1. Open the [color picker sample](https://esri.github.io/calcite-components/?path=/story/components-controls-colorpicker--simple) in Safari.
2. Drag the color indicator at the top of the component.
3. Note that the color indicator starts "lagging" behind the mouse pointer.

### Relevant Info

_Browser_: Safari 14.1.1
_OS_: MacOS Catalina
_Version_: `@esri/calcite-components@1.0.0-beta.56`

- [ ] CDN
- [x] NPM package

CC @RalucaNicola

**Comment by jcfranco** [comment]
Installed! 

@hccampos Can you help verify this one?

**Comment by hccampos** [comment]
Now works in Safari, Chrome and Firefox. Looking good 👍

**Comment by jcfranco** [comment]
@hccampos Thanks for verifying! 💪🏼
