### ISSUE TITLE
create types for using calcite components with react + typescript

### ISSUE THREAD

**Issue by esride-nik** [Esri/calcite-components#2336]
## Summary
Setting up React with TypeScript and Calcite Components I'm experiencing the same issues described by @paulcpederson [in relation to preact here](https://github.com/Esri/calcite-components/pull/693#issue-441717917), the main symptom being the error message "Property 'calcite-<thing>' does not exist on type 'JSX.IntrinsicElements'.". The components are working, but I obviously get no type checking. Furthermore I need to hook up events via DOM (look for node and addEventListener), but I imagine that this should be possible via arguments in the JSX tags.
The issues seem to be resolved for preact and I see the working preact example in your [examples repo.](https://github.com/Esri/calcite-components-examples).

I wrote this[ description of my observations on the Esri Community ](https://community.esri.com/t5/arcgis-api-for-javascript/calcite-design-system-with-react-and-typescript/m-p/1069340#M73526)yesterday. Now I became aware of the above mention Github issue, that's why I'm opening this one. 

## Measure of Success
Using React with TypeScript and Calcite Components should give me intellisense / type checking.
Events should be usable as arguments in the JSX tags.

### Resources 
It's all in [here](https://github.com/Esri/calcite-components/pull/693) and the linked issues and the examples repo. I tried to create something similar to your preact.d.ts (without all the Omits, that you only need to swap out the events spelling, right?), but it seems like I'm on the wrong track:
![image](https://user-images.githubusercontent.com/1322415/122556774-31f9c600-d03c-11eb-8186-c3f063cf9cab.png)

**Comment by paulcpederson** [comment]
@esride-nik this is exactly what the [@esri/calcite-components-react](https://www.npmjs.com/package/@esri/calcite-components-react) package was meant to provide. It's essentially a wrapper around calcite components to make events more ergonomic, etc. 

Here is an example of how to use it in a react project: https://github.com/Esri/calcite-components-examples/tree/master/react

This is a pretty new package, so please send feedback about anything that didn't make sense/didn't work as you're setting it up!

**Comment by esride-nik** [comment]
Thanks a ton @paulcpederson! I didn't realize this was released a week ago. My clone of the examples repo was older and it never came to my mind to pull any updates. Squiggly lines are gone, events are working as attributes in general. Maybe you could enhance the [React guide](https://developers.arcgis.com/calcite-design-system/framework-examples/react/).

Intellisense for tag attributes is not correct though. Your components.d.ts has the same long list of standard attributes for every tag, but none of the Calcite-specific events etc. These would be great to have. Are you still working on this?

Follow-up question: Which one is the right API documentation to use? My starting point is usually the [components page](https://developers.arcgis.com/calcite-design-system/components/), and from a specific component I'd follow the [link under "implementation"](https://developers.arcgis.com/calcite-design-system/components/layout/action-bar/#implementation) to the Github doc. There I find props and [events](https://github.com/Esri/calcite-components/tree/v1.0.0-beta.52/src/components/calcite-action-bar#events). Using this I have to know some conventions, like adding an "on" prefix to use the event in React. Is this the way for now?

All in all, this in great and I'm super happy. I guess I'm ready to use this in a "real" project now. Anything I can do to help? Thanks again!

**Comment by paulcpederson** [comment]
> but none of the Calcite-specific events etc

Hmmm, are you seeing props but no events or just no real info about components at all?

> Which one is the right API documentation to use?

They are both "right" but I think the one on developers.arcgis.com will continue to improve and evolve. @julio8a could comment on that more.

> Anything I can do to help?

I'd say just opening issues as you find stuff would be a huge help. Thinking we could break off the Intellisense into its own issue and close this one?

**Comment by esride-nik** [comment]
Sure! Here it is: https://github.com/Esri/calcite-components/issues/2391
Thanks!
