### ISSUE TITLE
Enhancement: Allow for greater nesting of calcite-combobox-items within calcite-combobox

### ISSUE THREAD

**Issue by phenderson00** [Esri/calcite-components#2337]
### Description
Per Paul Pederson, there is currently a depth limit of 3 for nesting calcite-combobox-items within a calcite-combobox.  My use case requires a depth of 4, so while functionally everything is working correctly, visually it does not appear as it should.

### Acceptance Criteria 
Ability to nest calcite-combobox-items within a calcite-combobox to a depth of at least 4.

#### Which Component
calcite-combobox/calcite-combobox-item

#### Example Use Case
```
<calcite-combobox selection-mode="ancestors" placeholder="Select Map Theme">
    <calcite-combobox-item text-label="Biodiversity" value="">

        <calcite-combobox-item text-label="Species Biodiversity" value="SpBioRnkEco">

            <calcite-combobox-item text-label="Terrestrial Biodiversity" value="BioRankEco">
                <calcite-combobox-item text-label="Native Species Richness" value="NtvRankEco"></calcite-combobox-item>
                <calcite-combobox-item text-label="Rarity Richness" value="RarRankEco"></calcite-combobox-item>
                <calcite-combobox-item text-label="Irreplaceability" value="RwiRankEco"></calcite-combobox-item>
            </calcite-combobox-item>

            <calcite-combobox-item text-label="Aquatic Biodiversity" value="BioAqRankSW"></calcite-combobox-item>

        </calcite-combobox-item>

    </calcite-combobox-item>
</calcite-combobox>
```

Renders as shown in the screenshot below

![image](https://user-images.githubusercontent.com/48392427/122571811-bd5e6180-d012-11eb-8ac7-a124eadab647.png)

The expected output is that the three items with red arrows next to them would nested under Terrestrial Biodiversity (screenshot below).

![image](https://user-images.githubusercontent.com/48392427/122571984-ee3e9680-d012-11eb-9652-a7a1a72e49b3.png)

**Comment by julio8a** [comment]
verified on beta.59
