### ISSUE TITLE
calcite-checkbox - Multiple checkbox and onChange event

### ISSUE THREAD

**Issue by ehusaint** [Esri/calcite-components#234]
Two issues:
1. Multiple checkbox are been displayed for the below code. 
2. No onChange event is been triggered on check. 
3. listening on the calciteCheckboxChange is also not working. 

<calcite-checkbox>
  <input name="myCheckbox" type="checkbox" onChange={this.handleInputChange} />
</calcite-checkbox>

**Comment by ehusaint** [comment]
![Screen Shot 2019-11-14 at 3 02 00 PM](https://user-images.githubusercontent.com/23363475/68904160-2290f900-06f2-11ea-8dfb-12d127126a33.png)
 multiple checkbox image.

**Comment by macandcheese** [comment]
I think we should remove the proxy inputs that cause this - @patrickarlt have you tried out the stencil-ds-binding option for angular? I think if that works, we can remove the proxy inputs from CC?

**Comment by eriklharper** [comment]
Is this issue still valid?  Also, can the code that reproduces this be posted here so we can attempt to verify it?

**Comment by eriklharper** [comment]
Closing this as this does not occur anymore.
