### ISSUE TITLE
Unstable Test:  calcite-input › number type › typing zero and then a non-zero number sets and emits the non-zero numbe

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2349]
## Summary

**Which component?:**

input

**Which test(s)?:** 

**Test error:**

Summary of all failing tests
FAIL src/components/calcite-input/calcite-input.e2e.ts (334.899 s)
  ● calcite-input › number type › typing zero and then a non-zero number sets and emits the non-zero number
    expect(received).toBe(expected) // Object.is equality
    Expected: "0"
    Received: null
      767 |       await page.waitForChanges();
      768 | 
    > 769 |       expect(await calciteInput.getProperty("value")).toBe("0");
          |                                                       ^
      770 |       expect(calciteInputInput).toHaveReceivedEventTimes(1);
      771 | 
      772 |       await page.keyboard.press("1");
      at Object.<anonymous> (src/components/calcite-input/calcite-input.e2e.ts:769:55)
          at runMicrotasks (<anonymous>)
Test Suites: 1 failed, 1 skipped, 94 passed, 95 of 96 total
Tests:       1 failed, 6 skipped, 1360 passed, 1367 total

**PR that skipped the test:** https://github.com/Esri/calcite-components/pull/2351

**Comment by driskull** [comment]
This one also seems to be unstable.

```
Summary of all failing tests
FAIL src/components/calcite-input/calcite-input.e2e.ts (379.139 s)
  ● calcite-input › number type › disallows typing redundant zeros
    expect(received).toBe(expected) // Object.is equality
    Expected: "0"
    Received: undefined
      809 |       await page.waitForChanges();
      810 | 
    > 811 |       expect(await calciteInput.getProperty("value")).toBe("0");
          |                                                       ^
      812 |     });
      813 | 
      814 |     it.skip("typing zero and then a non-zero number sets and emits the non-zero number", async () => {
      at Object.<anonymous> (src/components/calcite-input/calcite-input.e2e.ts:811:55)
          at runMicrotasks (<anonymous>)

```

**Comment by jcfranco** [comment]
Stabilized via https://github.com/Esri/calcite-components/pull/3566. 🐴 🤠 💨

**Comment by benelan** [comment]
I have not seen this test fail since the fix, verified.
