### ISSUE TITLE
Enhancement: Add groups to lists

### ISSUE THREAD

**Issue by TheBlueDog** [Esri/calcite-components#2350]
### Description

Field Maps has an immediate need for being able to use groups in a `value-list`.  Add `calcite-*-list-group` to the value list and the calcite list components

### Acceptance Criteria 

Would expect these to work the same way groups do in the current `pick-list`

#### Which Component

calcite-value-list
calcite-list (Current PR #2274)

**Comment by driskull** [comment]
@asangma we need to decide if we want to allow groups for lists. The grouping shown [here](https://esri.github.io/calcite-components/?path=/story/components-pick-list--grouped) always seemed weird because in the example they would be best as two different lists.

**Comment by TheBlueDog** [comment]
One of two use cases in Field Maps is that we have this same list of field in the layer (shown here in MV), but we group them into REQUIRED and OPTIONAL fields.  Pick-list doesn't work for our workflow, but Value-list does. The base calcite-list would probably be even better, but not having the groups means we will need to either hack the component or build our own.

![Screen Shot 2021-06-21 at 6 13 20 PM](https://user-images.githubusercontent.com/5419306/122834322-5f54a700-d2bc-11eb-8877-8837b9ae301a.png)

**Comment by TheBlueDog** [comment]
Our current fully custom implementation
![Screen Shot 2021-06-21 at 6 16 18 PM](https://user-images.githubusercontent.com/5419306/122834574-d38f4a80-d2bc-11eb-8451-3f0aac28f471.png)

**Comment by driskull** [comment]
Gotcha. those use cases make sense.

**Comment by driskull** [comment]
@julio8a @jcfranco should this issue be designed first before being implemented?

**Comment by julio8a** [comment]
If a dev is ready, I think this is small enough of an update that we can get started on it. We can have @bstifle review at the PR state for UI feedback.

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/124660611-0c5a2280-de6c-11eb-9d56-394049b44303.png)

quick design for this. @TheBlueDog what do you think?

**Comment by TheBlueDog** [comment]
Does the group title have a background color? Or is it transparent?

**Comment by driskull** [comment]
@asangma I think we need to enhance the `calcite-list-item` to support nesting. Do we want to do that? Seems like currently, its restricted to a flat list.

**Comment by driskull** [comment]
@asangma I'll take a stab at the nesting styling. lord help us.

Can I get some assistance? Maybe one of the designers can take over?

![image](https://user-images.githubusercontent.com/1231455/125869222-6eec3e71-8d06-484e-8a00-737919ad5a04.png)

**Comment by julio8a** [comment]
I can create an issue to update the styling for this one.

**Comment by julio8a** [comment]
verified on master demo pages
