### ISSUE TITLE
Bug: color-picker hue thumb cannot be nudged via keyboard when color is #000 or #fff

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2357]
### Actual Behavior

When the color value is #fff or #000, tabbing to the hue handle will not move when the arrow keys are pressed. This works as expected when the color is another value.

### Expected Behavior

The hue handle can be nudged regardless of color value.

### Reproduction Steps or Sample

1. Initialize the calcite-color-picker with pure white.
2. Tab to the hue handle 
3. Press left/right or up/down and notice you can't move the handle

### Relevant Info

Stems from https://github.com/Esri/calcite-components/issues/2230#issuecomment-860439982

_Version_: `@esri/calcite-components@1.0.0-beta.56`

- [ ] CDN
- [x] NPM package

**Comment by jcfranco** [comment]
Installed!

**Comment by jcfranco** [comment]
@julio8a Can you help verify this one? You can use https://codepen.io/jcfranco/pen/poPPwQq?editors=1000

**Comment by julio8a** [comment]
verified!
