### ISSUE TITLE
Enhancement: calcite-switch - update demo html to match Figma designs

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2365]
### Description
The goal of this issue is to achieve parity between the calcite-switch ~Figma design~(nixed this requirement on 7/9) demo HTML page, and any usage snippets we provide.

### Acceptance Criteria 
1. ~Variants illustrated in the Figma designs match the variants illustrated on the demo HTML page.~
1. The component's usage example is updated to match (src/components/calcite-switch/usage/basic.md needs a calcite-label instead of native label)
2. The html page includes all major variants ("flavors") for the component

### Relevant Info 
- ~Figma: calcite-switch needs designs for its disabled property, and the page needs some sort of headings to illustrate the properties for each variant~
- Switch demo html: needs semantic markup, a11y cleanup (ex: wrapping calcite-labels should have a `for` attribute that matches the `id` attribute on the corresponding calcite-switch)

#### Which Component
calcite-switch

**Comment by ManahariDahal** [comment]
I have updated the Figma design we had for Switch, will create a PR soon.
