### ISSUE TITLE
Bug: calcite-input type="number disabled buttons are clickable/keyboard navigable

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2377]
### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by macandcheese** [comment]
Should these be tab-to-able at all, even when not disabled? Native input spinners, and clear buttons, are not navigable with keyboard. 

Those actions can be done with the esc, or arrow keys, so having them be tab-to-able is actually extra steps for keyboard users and not in alignment with native functionality.

**Comment by caripizza** [comment]
Created this one on accident, closing in favor of #2378

**Comment by macandcheese** [comment]
@caripizza sounds good.
