### ISSUE TITLE
Bug: when calcite-input is `disabled` and `clearable`, the clear button is still clickable/keyboard navigable

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2378]
### Actual Behavior
When input type is number, and the input includes a value with `clearable` and `disabled` properties:
- the clearable button is still clickable and keyboard navigable, and is able to update the input's value
- the Up/Down arrow buttons are still clickable, and are able to update the input's value

Reproducible via Storybook iframe link:
https://esri.github.io/calcite-components/iframe.html?id=components-controls-input--without-label&args=&knob-status=idle&knob-scale=m&knob-label%20text=My%20great%20label&knob-type=number&knob-alignment=start&knob-number-button-type=horizontal&knob-min=0&knob-max=100&knob-step=1&knob-prefix-text=&knob-suffix-text=&knob-disabled=true&knob-value=2&knob-placeholder=Placeholder%20text&knob-input%20message%20type=default&knob-input%20message%20status=idle&knob-input%20message%20text=My%20great%20input%20message&knob-clearable=true&viewMode=story

This screenshot shows how the clearable button can still be pressed:
![image](https://user-images.githubusercontent.com/42423180/123133152-4c4cee80-d404-11eb-9ac6-fe2d048a9e6b.png)

### Expected Behavior
- The clearable button should not be clickable or keyboard navigable
- The up/down arrows should not be clickable

My thoughts on addressing the issue:
- The buttons will likely need `tabindex` set when disabled is truthy
- Input's stylesheet may need added disabled styles for the buttons

### Reproduction Steps or Sample

1. Go to Storybook
2. View one of calcite-input's stories, change `type` knob to `number`
3. Ensure the input has a value
4. Set `disabled` property knob
5. Set `clearable` property knob
6. Notice the issue

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.57`

- [x] CDN
- [x] NPM package

**Comment by caripizza** [comment]
I just tested and the clearable button is clickable/keyboard navigable on all input types that have the `disabled` attribute set. I'll update the issue title.

**Comment by driskull** [comment]
Looked into this issue and I see a few things that are causing issues here:

- Why are we using `mousedown` events instead of click events here?
- Why are we using `div`s for buttons instead of `button` elements here?
- Why are `pointer-events` being used in a nested fashion? It's causing issues when the component host sets `pointer-events: none` and an internal node has `pointer-events: initial`.
- Why are we throwing focus back to the input when a button is clicked? Shouldn't the focus remain on the button?

Seems like all the components can still be focused when disabled by tabbing through the dom.

We need to apply `tabindex` of `-1` to internal focusable elements when disabled. If we don't want elements to be tabbed to, we should use `tabindex="-1"` as well.

**Comment by driskull** [comment]
I have a starting point for this but I think its a bit more complicated so maybe @eriklharper can tackle it.

https://github.com/Esri/calcite-components/pull/2495/files

**Comment by driskull** [comment]
This might be more of an epic to handle disabled components correctly.

We could setup a global test to make sure when a component is disabled and the tab key is hit, nothing inside the component is focused.

And add a global test utility to click an element and test that it hasn't changed something.

**Comment by driskull** [comment]
@caripizza this should be fixed with #2582.

I think we should have an epic about disabled states and making sure that no child components are still operational or focusable. cc @jcfranco @julio8a

**Comment by jcfranco** [comment]
@driskull Yep, as we had discussed, I'll create an epic for this. I have a draft in the works. 😄

**Comment by caripizza** [comment]
Verified by running docs locally from master branch and attempting to interact with a clearable, disabled input that includes a value; no input buttons are clickable/keyboard navigable.
