### ISSUE TITLE
Bug: Action pad expanded on mobile device size doesn't work correctly

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2380]
### Actual Behavior

I have a Calcite Action Pad defined as a sibling to a Calcite Shell component which contains a header and my mapView div like this:

```html
<calcite-action-pad style="position:absolute;margin-top:4px;margin-left:4px;visibility:hidden;" expanded layout="vertical" id="hamburgerMenu">
      <calcite-action id="menu1" onclick="window.open('aURL','_blank')" text="Frequently Asked Questions" icon="question-mark"></calcite-action>
      <calcite-action id="menu2" onclick="window.open('aURL','_blank')" text="FWP Buy and Apply" icon="shopping-cart"></calcite-action>
      <calcite-action id="menu3" onclick="window.open('aURL','_blank')" text="TIP-MONT" icon="star-circle"></calcite-action>
      <calcite-action id="menu4" onclick="window.open('aURL','_blank')" text="Submit Feedback" icon="edit-attributes"></calcite-action>
      <calcite-action id="menu5" onclick="document.getElementById('myModal-disclaimer').style.display = 'block'" text="Show Disclaimer" icon="exclamation-mark-circle"></calcite-action>
  </calcite-action-pad>
```

It is not visible by default but is triggered by a click event on an icon. On desktop the labels show up as expected but on mobile they do not show up at all. When expanded the action pad expands by a few pixels but no text appears. Is this a known issue, or something I'm doing wrong here?

### Expected Behavior

action pad expands correctly on mobile device sized screens

### Reproduction Steps or Sample

see above

### Relevant Info

https://community.esri.com/t5/calcite-design-system-questions/action-pad-labels/m-p/1069514#M18

**Comment by caripizza** [comment]
This looks to me like it's from the action-pad's .container class, that has `max-width: 15vw;` style (I think even when expanded):
https://github.com/Esri/calcite-components/blob/master/src/components/calcite-action-pad/calcite-action-pad.scss#L25

Should the width match action-bar and instead be `20vw;` to show more of the truncated text labels?

**Comment by samMatenaer** [comment]
Should the width of this component really change based on screen width? If anything, rather than resizing the entire action pad, it might be better to just auto collapse the pad? For example, in the image below, the text should not be cut off.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/50883428/128533549-d996e5a7-2e00-4aa5-ae91-8a156513fd69.png">

When you reduce the width of the screen even more, the pad looks like it is not even expanded although it actually is.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/50883428/128533898-d8067dca-fd00-476d-ac3f-b165edb3a3d5.png">


https://codesandbox.io/s/jolly-faraday-q6i2b?file=/index.html

**Comment by macandcheese** [comment]
Depending on screen size this will happen on sizes greater than mobile : https://jsbin.com/xowipikasa/edit?html,output

It may be worth not making the action bar / pad proportionally scale and instead expand to the width of the longest text string...

**Comment by macandcheese** [comment]
cc @asangma - maybe we can look at not proportionally scaling this component, I think it would resolve https://github.com/Esri/calcite-components/issues/3337 as well. Thoughts?

**Comment by tannerjt** [comment]
@macandcheese - I like the idea of expanding to longest text string.  It also might be desirable to allow a `max-width` prop on the component (action-pad / action-bar) for the expanded state on mobile.  We're observing this as in issue in Hub:

![9fa319f8-3801-4f4f-a1c6-006e9ea7f1f2](https://user-images.githubusercontent.com/3883995/178010202-e8cde305-06e5-4635-b3d7-5221cf3682e0.jpeg)

**Comment by brollison** [comment]
Agree with @tannerjt's perspective [above](https://github.com/Esri/calcite-components/issues/2380#issuecomment-1179044375). @macandcheese we have this issue in production today for all ArcGIS Hub sties, so interested to know what the priority + timeline to resolution of this fix may be.

At worst we can pass in `expand-disabled` prop when on smaller screens to circumvent users experiencing the bug for the time-being.

**Comment by macandcheese** [comment]
Cc @benelan / @jcfranco for prioritization.

@asangma are there instances where expanding to longest string as default behavior and offering a css var for max width would cause issues in MV?

**Comment by jcfranco** [comment]
Added to the upcoming milestone with bumped priority.

**Comment by driskull** [comment]
Can we just remove these max widths and let users set their own max width on the action-bar,action-pad,action-group?

**Comment by driskull** [comment]
If we do want a set max-width by default, we can add a CSS variable that users could override?

**Comment by driskull** [comment]
Another option would be to have a prop like `widthScale` similar to what is on the panel. We could have sizes for s/m/l and also have a CSS var if a user wants to customize it.

**Comment by driskull** [comment]
Ping. cc @jcfranco

**Comment by macandcheese** [comment]
> Can we just remove these max widths and let users set their own max width on the action-bar,action-pad,action-group?

This would be my preference - provide a `component-max-width` css var, and expand to the longest string in the slotted actions by default.

**Comment by driskull** [comment]
Ok. I'll proceed with that. Thanks

**Comment by geospatialem** [comment]
Verified on next.551. 

If a smaller width is desired users can set the max width using the `--calcite-action-pad-expanded-max-width` var.

![verified-action-pad-width](https://user-images.githubusercontent.com/5023024/182247277-9fa78e14-3eac-4a10-85f1-e07c70d1ff50.png)
