### ISSUE TITLE
Enhancement: Alert supporting actions-end

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2382]
### Description
alert needs to support up to 2 actions in the end slot next to the X

![image](https://user-images.githubusercontent.com/14083530/123152019-b7f58280-d429-11eb-8498-f5c600c1cd48.png)

**Comment by bstifle** [comment]
hover and hit space to match X

**Comment by ashetland** [comment]
Design complete in Figma. Updated design also addresses issues #5254 and #3338. cc: @geospatialem

**Comment by geospatialem** [comment]
@Elijbet Is the alert with `actions-end` ready for verification, and/or should we move this into the January release milestone?

**Comment by geospatialem** [comment]
Verified on `next.658` when slotting a `calcite-action`.

```html
<calcite-alert open>
    <div slot="title">Alert title</div>
    <div slot="message">Message lorem ipsum</div><a slot="link" href="#">Link slot</a>
  <calcite-action slot="actions-end" text="Settings" icon="gear"></calcite-action>
  <calcite-action slot="actions-end" text="Information" icon="information"></calcite-action>
</calcite-alert>
```

![image](https://user-images.githubusercontent.com/5023024/205771777-c894aa77-ed22-423d-bcb3-c2c23d914180.png)
