### ISSUE TITLE
Enhancement: Update Alert queue to use chips

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2383]
### Description
Alert queue change to chips, and get rid of the vertical lines.

Small chips for small alert, medium chips for medium alert, large chips for large alert

Design:
![image](https://user-images.githubusercontent.com/14083530/123153991-ef652e80-d42b-11eb-9638-97564979a0dc.png)

**Comment by julio8a** [comment]
I was doing refactor for Alert and this was an easy add #2339

**Comment by caripizza** [comment]
Assigning to @bstifle for verification

**Comment by bstifle** [comment]
yep verified julio added it
