### ISSUE TITLE
Bug: Fix use of invalid tailwind variables.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2385]
### Actual Behavior

- calcite-combobox-item.scss 'colors.border.1' does not exist in your theme config.
- calcite-accordion.scss - 'borderColor.2' does not exist in your theme config. 

### Expected Behavior

There are no references to tailwind variables that do not exist

### Reproduction Steps or Sample

Using this VSCode plugin can display the error

https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss

### Relevant Info

![image](https://user-images.githubusercontent.com/1231455/123158751-081c1700-d421-11eb-81f5-fd27f1f625d1.png)

**Comment by driskull** [comment]
If we can prevent these errors in the future that would be ideal too :)

**Comment by driskull** [comment]
https://github.com/tailwindlabs/tailwindcss-intellisense/issues/346

**Comment by caripizza** [comment]
Installed. @driskull can you please verify?

**Comment by driskull** [comment]
Looks good. no more tailwind errors in these files.
