### ISSUE TITLE
Additional Modal size between Med and Large

### ISSUE THREAD

**Issue by evanmosby** [Esri/calcite-components#239]
We have a use case where its desirable to have a modal size in between the large and medium sizes. Medium is just too constraining and large feels quite empty. Any opportunity to add an additional size? Thanks for considering!

**Comment by macandcheese** [comment]
Couple options off the top of my head...

Add an optional "max-width" attribute that, if defined, overrides the 'size' attribute value with a user-defined number, but it's also nice to enforce a little consistency between modals like our current scale does

We could reconfigure our current scale to accommodate xs -> xl - we'd probably always encounter "in betweens" that wouldn't work for folks but we'd cover a lot more bases OOTB and still have a consistent, predefined set of widths.

Some kind of "auto width" where the modal expands to fit it's content while still controlling mobile styling, letting users add a child modal content item with its own set max-width.

Thoughts as "code owner" @paulcpederson ?

**Comment by paulcpederson** [comment]
The problem with child max-width is that you actually want to make the modal fullscreen at the determined breakpoint.

An additional prop for exact size is most likely the solution here.

**Comment by paulcpederson** [comment]
@evanmosby in `v1.0.0-beta.32` the API for calcite-modal allows for this. Basically you can set the `width` prop to standard sizes ("s", "m", "l") _or_ you can pass in a number for a custom max width, allowing you to select the exact size that works best for your design:

```
<calcite-modal width="500">
  ...
</calcite-modal>
```

Head up there are several other API changes in beta.32 as well, so you may want to peruse the [release notes](https://github.com/Esri/calcite-components/releases/tag/v1.0.0-beta.32)

**Comment by evanmosby** [comment]
Thanks Paul - much appreciated! We'll check it out and the other API changes.
