### ISSUE TITLE
Intellisense with React + TypeScript

### ISSUE THREAD

**Issue by esride-nik** [Esri/calcite-components#2391]
## Summary 
As requested by @paulcpederson, I'm opening this issue:
Using the NPM package "@esri/calcite-components-react" in a project with React and TypeScript, intellisense for tag attributes is not correct. _components.d.ts_ has the same long list of standard attributes for every tag, but none of the Calcite-specific events etc. These would be great to have. 

## Measure of Success 
Intellisense is working in a project with React and TypeScript.

### Resources 
Here's what I see:
![image](https://user-images.githubusercontent.com/1322415/123272867-6e2c9b00-d502-11eb-81e0-6d3b928e1004.png)

The suggestions are probably coming from components.d.ts:
![image](https://user-images.githubusercontent.com/1322415/123273259-c95e8d80-d502-11eb-898a-1b92d98c50de.png)

The list of attributes is the same for all listed components. No "onCalcite..." events are listed here.

**Comment by jcfranco** [comment]
@esride-nik Can you share your project setup? Intellisense is working fine for me: 

![Screen Shot 2021-07-22 at 2 48 14 PM](https://user-images.githubusercontent.com/197440/126713792-a1368748-6100-422d-85e8-22852ab765b1.png)

**Comment by jcfranco** [comment]
@esride-nik I submitted a [PR](https://github.com/Esri/calcite-components-examples/pull/42) to update the React example to TypeScript on the `calcite-components-examples` repo. Hope that helps.

Closing as this is outside this project's scope.
