### ISSUE TITLE
Bug: ColorPicker display is inline by default which makes the height only 19px.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2412]
### Actual Behavior

Bug: ColorPicker display is inline by default which makes the height only 19px.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1231455/123864430-9be95980-d8df-11eb-88e2-1e537f93dc93.png)

### Expected Behavior

```
:host {
 display: inline-block;
}
```

### Reproduction Steps or Sample

Can be seen on storybook as well. https://esri.github.io/calcite-components/?path=/story/components-controls-colorpicker--simple

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [x] NPM package

**Comment by driskull** [comment]
cc @julio8a @caripizza We should make sure that all components have the correct display type by default so that their dimensions are correct.

**Comment by caripizza** [comment]
@driskull sorry can you clarify? Was a defect introduced on one of our related refactor prs?

**Comment by driskull** [comment]
@caripizza nope I don't think so, it seems like it was always like this.

I just wanted to make an announcement to the peeps who work on the SCSS files.

We might need to do an audit to make sure that the host has the correct display type for all components.

**Comment by jcfranco** [comment]
Installed!
