### ISSUE TITLE
Enhancement: Update icon sizes within Notice and Alert medium sizes

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2417]
### Description
Update icon sizes within Notice and Alert to match the global consistency of medium components

### Acceptance Criteria 
- Medium Scale  alert/notice should use small scale for the X and start icon. 
- Large scale alert/notice should use medium scale the X and start icon

#### Which Component
notice and alert

**Comment by bstifle** [comment]
Design

![image](https://user-images.githubusercontent.com/14083530/124022079-f652ea80-d9b1-11eb-9775-4cdec605261d.png)

**Comment by jcfranco** [comment]
@bstifle Updated description based on our conversation.

**Comment by jcfranco** [comment]
Installed.

**Comment by bstifle** [comment]
verified  ✅✨💰
