### ISSUE TITLE
Enhancement: button loading indication with text

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#2420]
### Description

Button able to be in the loading state but also shows the text, i.e. loading indicator in the button icon location.

Or better yet a `loadingText` property or the like so the loading and button text could be different.

#### Example Use Case

Waiting for a geoprocessing task to complete and the button with just the loading indicator for 10-30 seconds without text isn't intuitive to the user as to what's happening.

**Comment by driskull** [comment]
@jcfranco @julio8a this needs a design first right?

**Comment by bstifle** [comment]
@driskull loading button is already in... so i imagine this would look like this:

![image](https://user-images.githubusercontent.com/14083530/124661811-a40c4080-de6d-11eb-8320-cb547e91ede6.png)


Same 16px size and same space between as a button with icon

**Comment by jcfranco** [comment]
Thank you both for bringing this up and for the spec design! 💪🏼

**Comment by bstifle** [comment]
@jcfranco @driskull julio had a good idea to make these also have the disabled property:

![image](https://user-images.githubusercontent.com/14083530/124663074-3a8d3180-de6f-11eb-83b2-d0f69d2dcb73.png)

**Comment by macandcheese** [comment]
If `loadingText` as requested is introduced, let's just make sure we handle potential width changes with a transition of some sort, changing the size and text of a button at the same time can be jarring.

**Comment by driskull** [comment]
@asangma or @julio8a can you handle adding the transition for this?

**Comment by julio8a** [comment]
Not sure I have the technical chops, but I can give it a try

**Comment by driskull** [comment]
Assigning to @bstifle and @julio8a for the following:

```
I think this looks good - couple things, both shown in screen cap of demo page:

Maybe try a width transition for when the loader is appended to the button cc @bstifle
A "just icon" button should expand with adequate x padding, it's a little squished right now
```

**Comment by driskull** [comment]
https://github.com/Esri/calcite-components/pull/2441#pullrequestreview-700425347

**Comment by caripizza** [comment]
This one can be verified once we cut a new beta release today

**Comment by jcfranco** [comment]
Verified via https://esri.github.io/calcite-components/?path=/story/components-buttons-button--simple

**Comment by COV-GIS** [comment]
Thanks. It works and looks great.
