### ISSUE TITLE
Enhancement: Alert - queue length number should be localized.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2424]
### Description

Enhancement: Alert - queue length number should be localized.

https://github.com/Esri/calcite-components/pull/2339#discussion_r661769180

The number displayed for queue length should be localized so that it appears correct in different languages.

### Acceptance Criteria 

Number appears correct in different languages.

#### Which Component

Alert

**Comment by geospatialem** [comment]
Closing in favor of #4893.
