### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#243]
This is based on the Intl discussion with @subgan82. 

> we recently worked with esri's i18n/l10n team and have come with a design for Date Format Picker which will use INTL ( JS native Intl) we would like to build this in calcite-components so all teams can reuse, I see this related issue https://github.com/Esri/calcite-components/issues/58 , recommend using Intl over Moment and leverage intl.dateformatoptions, JSAPI 4x already supports Intl, Charts project is also using Intl. Proposed Design: https://devtopia.esri.com/WebGIS/Online-Charts/issues/225, https://esri.invisionapp.com/share/GPULURV4D6F#/screens

Related issues:
Inputs component: #107 
date-picker (calendar): #58 

I'm assuming this work will be tied into the input/selects and communication between the calendar (date+range) and inputs/selects.

**Comment by macandcheese** [comment]
@julio8a can you expand on this a bit?
 It seems more like a pattern comprised things like accordion, inputs / select, label, etc. than a standalone component.

**Comment by julio8a** [comment]
I don't think this issue is for a new standalone component. My understanding of this is the logic for internationalization for date formating. Since every user of date-picker whether that be through input/select or calendar, they all need internationalization due to our global product exposure. Therefore, everyone who uses these specific calcite-components (date-picker/inputs with dates and time) will need the date formating for internationalization. 

The inputs/selects that @subgan82 worked on with Mike already have this logic. They are looking to adding it to our input/forms and to the calendar component. 

@subgan82, does this sound right? Please correct or give some more info.

**Comment by subgan82** [comment]
Hi @julio8a 

The request is for a DateTimeFormat Picker component, it has usages in Charts, Popups , Ops Dashboard. This component standardizes this Date formatting across our platform. This component uses native Intl to provide the format. 

![Screen Shot 2019-11-21 at 8 19 29 AM](https://user-images.githubusercontent.com/1017712/69346175-f9afbd00-0c37-11ea-8971-65c8255fa912.png)

![Screen Shot 2019-11-21 at 8 23 11 AM](https://user-images.githubusercontent.com/1017712/69346308-2f54a600-0c38-11ea-9500-4956cefd08d5.png)

**Comment by subgan82** [comment]
Coming to https://github.com/Esri/calcite-components/issues/58

On these questions 

Questions include:

how to integrate moment into the build without bloating people's apps
how to do locale-specific date formatting

Here also for the Date picker to use [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) to set the date picker displayValue instead of using momentjs or another i18n library. As Intl now widely used in most web apps.

Using intl here also would not necessitate bringing a 3rd party library.

**Comment by kumarGayu** [comment]
@julio8a do you have any comments on UX? and I feel only the first image component should go in calcite-components. also, if you agree, then can you and mike discuss on what should edit-custom should look like?

**Comment by julio8a** [comment]
@macandcheese, would this be part of the `select` component?

**Comment by macandcheese** [comment]
I think this can be handled with some combination of the upcoming input / label / select components.

We haven't chatted about where a "normal" native select fits in, which is what it looks like the above screenshots would require... I think we should handle both a "normal" select that can utilize native spinners as well as our more complex "super select". 

Maybe we need a "Calcite-select" and  separately the more complex "Calcite-super-select" that includes filter, multi select etc. They would share an underlying "Calcite-input" field style but other than that had different functions.

Thoughts?

**Comment by subgan82** [comment]
> Maybe we need a "Calcite-select" and separately the more complex "Calcite-super-select" that includes filter, multi select etc. 

@macandcheese that sounds good,Can we able to do one unified component something like this 
 
``` javascript
//default maps to native select
<calcite-select>
...
</calcite-select>
// calcite super select as mentioned above with multiple, filter props
<calcite-select multiple=true filter=true>
...
</calcite-select>

```

**Comment by macandcheese** [comment]
I think that makes sense, there's a proposed API for that component here: https://github.com/Esri/calcite-components/issues/61 - feel free to leave feedback there!

**Comment by subgan82** [comment]
Thanks @macandcheese The proposed API looks good

**Comment by macandcheese** [comment]
Can this be closed? @subgan82 want to add any needed requirements to that issue?

**Comment by kumarGayu** [comment]
@macandcheese don't you think this component is needed in calcite-components? user or consumer should do this by themselves in the consuming app using all those calcite-components?

**Comment by subgan82** [comment]
@macandcheese Initial the plan was to build the DateFormat Picker in Calcite components but if it is more App level we can implement it in `arcgis-app-components`, we  plan to develop this component in this sprint cycle for charts project. Ops-dashboard, Popup UX also needed this component.

Will calcite-select and other form based inputs be available sooner, any time line for this ?

**Comment by macandcheese** [comment]
I do think it's a better candidate for app-components, whether that's arcgis-app-components or the map maker. There is an input component PR currently open and the "select" component discussion is open here - https://github.com/Esri/calcite-components/issues/61

Either way those would need to be built before this one 😄.

**Comment by subgan82** [comment]
Thanks. we will discuss with the teams that need this component where we can build it most likely it will be [here](https://devtopia.esri.com/WebGIS/arcgis-app-components)

**Comment by macandcheese** [comment]
Closing as it seems like this functionality will be built into a consuming library :)
