### ISSUE TITLE
Enhancement: calcite-alert - update demo html to match Figma designs

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2436]
### Description
This issue aims to achieve parity between the calcite-alert Figma design, its demo HTML page, and any usage snippets we provide.

### Acceptance Criteria 

- Variants illustrated in the Figma designs match the variants illustrated on the demo HTML page.

### Relevant Info 

- Figma: calcite-alert needs to match the design in Figma and the usage of either flex/grid to achieve it

#### Which Component
calcite-alert

**Comment by ManahariDahal** [comment]
Ready to verify!

**Comment by julio8a** [comment]
The PR is not `installed` yet.

**Comment by julio8a** [comment]
Verified on master, very nice work!
