### ISSUE TITLE
Bug: Calcite-Input content is not left-align in Firefox

### ISSUE THREAD

**Issue by tyanthony** [Esri/calcite-components#2439]
### Actual Behavior
In Firefox, the Calcite Input content is center-aligned. It is correct in Chrome and Safari.

### Expected Behavior
In Firefox, the content (Browse, etc.) should be left-aligned

### Reproduction Steps or Sample

Firefox (incorrect):
![image](https://user-images.githubusercontent.com/17069279/124605866-59bd9c00-de3a-11eb-9f08-ad6b08e79955.png)

Chrome/Safari (correct):
![image](https://user-images.githubusercontent.com/17069279/124605941-6b06a880-de3a-11eb-9747-957a75170365.png)

### Relevant Info

Browser: Firefox
OS: Found on all - OSX, Windows, Linux

_Version_: `@esri/calcite-components@1.0.0-beta.58`

**Comment by macandcheese** [comment]
To confirm, this is only for input of type “file”?

**Comment by jcfranco** [comment]
@tyanthony Can you help answer the above and possibly provide a test case instead of screenshots?
