### ISSUE TITLE
Bug: Calcite-panel does not account for long text

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#2445]
Related Map Viewer issue: https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/3463

The string ends in an elipsis and there is no tooltip over it:

![image](https://user-images.githubusercontent.com/50747646/124674585-e33b9100-de6f-11eb-901d-bd967e9e8803.png)

cc @jcfranco

**Comment by AdelheidF** [comment]
I think it's OK that it displays ellipses if the text does not fit in one line, but if it would display the full text on hover somehow that would be great.

**Comment by macandcheese** [comment]
I think removing truncation is the way to go here - simply letting the text wrap prevents this from being an issue and teams can choose to truncate on their own if they really want to. cc @asangma

**Comment by macandcheese** [comment]
Seems like this is the current behavior, to allow the heading to display at any length: https://codepen.io/mac_and_cheese/pen/wvpPaGp?editors=100

@zaramatheson can you confirm?

**Comment by zaramatheson** [comment]
@macandcheese Hi, yes it looks like that is what is happening in MV now:
![image](https://user-images.githubusercontent.com/50747646/161347286-858cd90f-ff48-4505-8252-bf7e4bfb9190.png)

**Comment by driskull** [comment]
Is this still an issue?

**Comment by driskull** [comment]
Seems like we should just allow it to span multiple lines. Does that sound correct?

**Comment by AdelheidF** [comment]
I think this got resolved already, @zaramatheson ?

**Comment by zaramatheson** [comment]
Yes, it seems fine to me! If you make the screen smaller, the text will span multiple lines and it looks ok.
