### ISSUE TITLE
Bug: Updating calcite-tooltip reference-element fails in specific case

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#2446]
### Actual Behavior

When updating the `id` and `reference-element` for a calcite-tooltip simultaneously (like via React state), the tooltip stops working if the tooltip is before the reference element. The reason this fails does make some sense. When the `calcite-tooltip` renders first, it can't find the matching reference element because the element has not been rendered with the new ID yet. This seems like a bug, but could also be addressed through documenting this potential pitfall.

### Expected Behavior

I would expect the order of the calcite-tooltip and the reference element to not matter.

### Reproduction Steps or Sample

1. Open this code sandbox https://codesandbox.io/s/calcite-tooltip-updating-id-1ewjn
2. Hover over `BUTTON WITH TOOLTIP` and you should see the tooltip appear
3. Click `UPDATE ID` (which updates the id stored in React state)
4. Hover over `BUTTON WITH TOOLTIP` again and the tooltip will not appear
5. Move the `<calcite-tooltip...` code below the `<calcite-tooltip-manager>`
6. Now the tooltip will work again

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.58`

- [ ] CDN
- [x] NPM package

**Comment by driskull** [comment]
I think this is kind of expected. If it can't find the ID it's not going to work and it can't wait for that ID to start existing. It uses `.getElementById()` so if its not there it can't assign it.

In this case, I would recommend to not use a string for the reference element but a HTMLElement. The HTML element is always preferred if possible. The string ID is just a convenience.

**Comment by noahmulfinger** [comment]
@driskull Thanks. That makes sense. One thing that could address this is having the tooltip query for the reference-element right when the tooltip gets activated. That way it will always have the latest information about the DOM when trying to display the tooltip

If that's not feasible, I think adding some documentation about recommended/best practices would be helpful, like:
- use html element instead of string for reference-element when possible
- if using a string, best to add the tooltip after the tooltip-manager

This was pretty difficult to track this down without knowing the internals of calcite-tooltip, so hopefully adding doc would help others.

**Comment by driskull** [comment]
> One thing that could address this is having the tooltip query for the reference-element right when the tooltip gets activated. That way it will always have the latest information about the DOM when trying to display the tooltip

Yeah we might be able to do that. I'll investigate and leave this issue open.

**Comment by driskull** [comment]
@jcfranco @julio8a  can we triage this one and put it in current milestone?

**Comment by jcfranco** [comment]
Added to the current milestone.

**Comment by jcfranco** [comment]
@noahmulfinger Can you help verify this one?

**Comment by noahmulfinger** [comment]
I updated the codesandbox I linked to beta.60, and looks like I am still seeing the same behavior after following the repro steps.

**Comment by jcfranco** [comment]
@noahmulfinger Thanks for testing. Moving this to the current sprint based on ☝🏼 . 

@driskull Can you take another look at this one? 🔍 👀

**Comment by driskull** [comment]
Yeah i'll take another crack at this one

**Comment by driskull** [comment]
I think we may just need to log a warning for this.

**Comment by driskull** [comment]
@noahmulfinger we now log a warning when this happens and we will put the issue in the backburner and discuss if we want to refactor this further.

**Comment by noahmulfinger** [comment]
@driskull Thanks, I can see the console warning in my codesandbox now.

**Comment by macandcheese** [comment]
@driskull does this PR resolve this issue? https://github.com/Esri/calcite-components/pull/4280

**Comment by driskull** [comment]
Nope, that PR Is not related to this issue.
