### ISSUE TITLE
refactor(Value List): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2453]
Description
This component needs to match Figma designs.

Acceptance Criteria
The component appears as it does in Figma.

Related prs:
- pr #1730
- pr #1731

Design:
- Needs full refactor, see Figma spacing
- https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1183%3A21916

6/24: Mike Stinson is working on this refactor - CP

**Comment by rmstinson** [comment]
Should be resolved with the Pick List issue: https://github.com/Esri/calcite-components/pull/2502

**Comment by julio8a** [comment]
verified on master, local build demo pages.
