### ISSUE TITLE
refactor(Input): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2455]
Description
This component needs to match Figma designs.

Acceptance Criteria
The component appears as it does in Figma.

Linked issue:
- #2139
- #2216

Related issues:
- #2041
- #1228

Related prs:
- pr #1653

Design:
- [ ] Needs Small Medium and Large scales for everything, cant fully QA
- [ ] needs full refactor (color, type no wrap line height, spacing)
- [ ] borders need to be updated to border-input
- [ ] It is missing the warning status color
- https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=0%3A9270

**Comment by caripizza** [comment]
Verified by running Storybook docs locally on master branch and comparing with Figma designs for Input, Color Picker (hex input), Date Picker Input, and Time Picker. (The most recent cc release I used for comparison is 1.0.0-next.259.)
