### ISSUE TITLE
refactor(Button): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2456]
Description
This component needs to match Figma designs.

Acceptance Criteria
The component appears as it does in Figma.

Linked issue:
- #2140

Related issues:
- #2041

Design:
- Issues above^
- full refactor (spacing, color, and non-wrapping text classes)
- https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=0%3A2053

**Comment by caripizza** [comment]
I'm not seeing what calcite-button should look like with text + 1 icon, or with 2 icons. Can you help me understand what that's supposed to look like @bstifle? (Is it supposed to appear like the FAB designs and have 12px margin between?)

**Comment by caripizza** [comment]
^ I'll go with the above margins for now

**Comment by bstifle** [comment]
@caripizza yep just like fab and split button

![image](https://user-images.githubusercontent.com/14083530/125703546-8e0700ba-b748-4e05-811b-772a9de7ea37.png)

https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=0%3A2053

**Comment by caripizza** [comment]
Scales are installed. Next item to-do: update button colors to match Figma

**Comment by julio8a** [comment]
Verified on master demo pages
