### ISSUE TITLE
refactor(Slider): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2457]
Description
This component needs to match Figma designs.

Acceptance Criteria
The component appears as it does in Figma.

Linked issue:
-#2224

Related issues:
- #720

Design:
- Medium is good. Small and Large need to be added
- https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=0%3A15235

**Comment by caripizza** [comment]
Self-assigning and adding to next sprint, per conversation with @julio8a.

**Comment by caripizza** [comment]
@bstifle There are no histogram variants in Figma for slider, does it need to look the same as it does now?

**Comment by bstifle** [comment]
@caripizza 
![image](https://user-images.githubusercontent.com/14083530/129968702-d7064038-7c43-44b1-b996-6dde0d20419a.png)

**Comment by caripizza** [comment]
@bstifle thanks, should it look like that with the color stops in action too? (ie., solid b-bb-30 for the highlighted range?)

**Comment by caripizza** [comment]
@julio8a should we create an issue in the ui-kits repo to add Slider's histogram variant(s) to Figma?

**Comment by julio8a** [comment]
Good catch, yes, I'll create and link to this issue.

**Comment by benelan** [comment]
@macandcheese can you please help me verify this design issue?

**Comment by macandcheese** [comment]
@benelan done - thanks!
