### ISSUE TITLE
refactor(Action): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2458]
Description
This component needs to match Figma designs.

Acceptance Criteria
The component appears as it does in Figma.

5/19 QA: Work that needs to be addressed: 
-  add Clear variant to Figma (Bryan)

Related prs:
- pr #1501

Design:
- needs small and large variants
- https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1184%3A3828

**Comment by julio8a** [comment]
@bstifle, this one already has s, m, and l. 

Does it need anything else?

**Comment by bstifle** [comment]
i believe the Large size type is wrong, and the spacing between the type and icons are off on small and large

**Comment by bstifle** [comment]
also, there are no examples of action pad or action bar in small or large sizes, would be dope to update the demo there

**Comment by bstifle** [comment]
@asangma @julio8a @macandcheese yo guys. Action type. Currently Small text size is text--2h, Medium is text--2h, and Large is text-0h.

Would like to stay consistent with the global font scaling and get medium to use text--1h

**Comment by caripizza** [comment]
Blocked by #2736

**Comment by asangma** [comment]
I'll have a look at how that affects things.
@bstifle Per your comment, it looks like you're suggesting

| text size | scale |
|:-------:|:-----:|
| --2h? | s |
| --1h | m |
| -0h | l |

Is that correct?

**Comment by asangma** [comment]
@bstifle 
Here's how it would look in an interface.
Thoughts?

![image](https://user-images.githubusercontent.com/12503298/129425822-cfe8aa49-645a-4ed5-ad62-9d65bf450161.png)

**Comment by asangma** [comment]
Broke out the font-size stuff into it's own issue.

**Comment by julio8a** [comment]
https://github.com/Esri/calcite-components/issues/2864

**Comment by julio8a** [comment]
Closing this one.
