### ISSUE TITLE
refactor(Dropdown): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2466]
Description
This component needs to match Figma designs.

Acceptance Criteria
The component appears as it does in Figma.

Related issues:
- #2041
- #1921
- #1431

Related prs:
- pr #1857

Design:
- Needs refactor stuff. Spacing, sizes of radio selection
- https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=0%3A7828

**Comment by bstifle** [comment]
i think this was completed in https://github.com/Esri/calcite-components/pull/2360

**Comment by bstifle** [comment]
verified
