### ISSUE TITLE
refactor(Inline Editable): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2468]
Description
This component needs to match Figma designs.

Acceptance Criteria
The component appears as it does in Figma.

Related issues:
- #2041

Design:
- Issues above^
- full refactor (spacing, color, and non-wrapping text classes)
- close `X` idle (ui-text-3) and hover (ui-text-1) need to be updated
- https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1183%3A22445

**Comment by julio8a** [comment]
- The heights for S (24px), M (32px), and L(48px) should already be taken care of from the input refactor.
- the close `X`. Currently, this is using calcite-button, but will need to be switches to a native button. Similar to Alert: https://github.com/Esri/calcite-components/blob/master/src/components/calcite-alert/calcite-alert.tsx#L118
- Spacing and general color will need a review against what's in Figma

**Comment by bstifle** [comment]
only thing there is L should be 44px total height

**Comment by julio8a** [comment]
Verified on master demo pages.
