### ISSUE TITLE
refactor(Tile and Tile Select): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2470]
Description
This component needs to match Figma designs.

Acceptance Criteria
The component appears as it does in Figma.

Related issues:
- #1230

Related prs:
- pr #1769
- pr #1770
- pr #1771

Design:
- https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1183%3A19780

**Comment by julio8a** [comment]
@bstifle, merged the PR for this one. Can you verify it on master?

**Comment by bstifle** [comment]
lookin good!
