### ISSUE TITLE
refactor(Panel): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2473]
Description
This component needs to match Figma designs.

Acceptance Criteria
The component appears as it does in Figma.

Related prs:
- pr #1678

Design:
- Panel and Flow spacing needs work:
    - Top and bottom should be 20px
    - Left and Right of header and summary should be 16px
    - https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1183%3A7662

**Comment by benelan** [comment]
Same with this one @julio8a, LGTM but if I can get a designer to look at this one for verification that would be great. Thanks!

**Comment by macandcheese** [comment]
LGTM @benelan

**Comment by benelan** [comment]
Thanks, verified and closing
