### ISSUE TITLE
Bug: I18N-Arabic only: Mixture of Indic and European numerals for RGB values in Color Picker

### ISSUE THREAD

**Issue by nel11211** [Esri/calcite-components#2476]
### Actual Behavior

RGB values in the color picker display as Indic numerals when user profile language is set to AR and FF browser is used.

### Expected Behavior
RGB values should display as European numerals.

### Reproduction Steps or Sample

1. Open "My Settings" on an Devext test user and set language to Arabic.
<img width=500px src="https://user-images.githubusercontent.com/66378014/124812717-d32bbc00-df18-11eb-844f-634a2341abe2.png"></img>
2. Login to that user in a Firefox session. 
3. Open any layer in Map Viewer.
4. Navigate to "Styles" and open the color picker to change the color of features on the map.
5. Notice the RGB values are shown with Indic numerals instead of European numerals.
![RGB_indic](https://user-images.githubusercontent.com/66378014/124813315-94e2cc80-df19-11eb-8a33-d1dcf255d3e0.PNG)

**Note:** This only happens when the language is set via user profile settings. It does not happen when simply adding the URL parameter `locale=ar`.

### Relevant Info

Originally observed in ArcGIS Charts issue https://devtopia.esri.com/WebGIS/arcgis-charts/issues/2928.

_Version_: `@esri/calcite-components@1.0.0-beta.58`

_Browser_: Mozilla Firefox 89.0.2 (64-bit)
**Issue is not present on Chrome**

**Comment by AdelheidF** [comment]
this is the related issue for calcite-input https://github.com/Esri/calcite-components/issues/3079

**Comment by anveshmekala** [comment]
fix is installed with [4195](https://github.com/Esri/calcite-components/pull/4195) . @benelan  can we close this one?

**Comment by geospatialem** [comment]
Verified on `beta.86`

### Default
![verify-colorpicker-firefox-default](https://user-images.githubusercontent.com/5023024/179313535-ff80cd29-d039-48e4-b9ed-6c453cfe3def.png)


### `numberingSystem` prop set to arab
![verify-colorpicker-firefox-numberingsystem-prop](https://user-images.githubusercontent.com/5023024/179313762-b03de321-faca-47d1-a34f-213049c6f560.png)
