### ISSUE TITLE
Bug: calcite-input type=number allows value entered outside of min/max range

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2477]
### Actual Behavior

When using the arrows it blocks the user to go past the min-max range, but it allows users to enter a value outside of that range. 
I'd expect the value to return back to the previous valid value.

### Expected Behavior

return back to the previous valid value or stay at the range max or min value.

### Reproduction Steps or Sample

```
<calcite-input type="number" min="1" max="10" value=".5"></calcite-input>
```

1. Enter `22`
2. Value `22` stays in input box

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by eriklharper** [comment]
Closing in favor of https://github.com/Esri/calcite-components/issues/1592
