### ISSUE TITLE
Bug: ActionBar and ActionMenu unnecessary margin

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2479]
### Actual Behavior
When the action-menu is present, the trigger gets an additional margin which causes a visual gap.
![Screen Shot 2021-07-07 at 2 13 18 PM](https://user-images.githubusercontent.com/12503298/124829665-bbaafe00-df2d-11eb-964f-cf3b6a6ad914.png)

### Expected Behavior
No margin. No gap.
![Screen Shot 2021-07-07 at 2 16 21 PM](https://user-images.githubusercontent.com/12503298/124829823-fa40b880-df2d-11eb-910b-85995471007f.png)

### Reproduction Steps or Sample

1. View one of the Shell demo apps
2. Make browser window small enough to trigger the action-menu

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by driskull** [comment]
duplicate of #2459

**Comment by asangma** [comment]
Closing
