### ISSUE TITLE
Bug: slider's min value thumb not placed correctly when range is -100 – 0 and both min and max are 0

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2480]
### Actual Behavior

For a range of -100 – 0, sliders are placed at opposite ends when both min-value/max-value are 0

### Expected Behavior

Both thumbs to overlap at 0

### Reproduction Steps or Sample

https://codepen.io/jcfranco/pen/LYyNqmj?editors=1000

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [x] CDN
- [ ] NPM package

**Comment by caripizza** [comment]
Happened upon this one while looking into slider issues with #2457. 

Beyond the thumb button placement issue mentioned here, the `min` label handle also displays `0` when it should show `-100`:

![image](https://user-images.githubusercontent.com/42423180/132380560-31b397bf-1940-4be7-9276-6d4ab504328e.png)

**Comment by caripizza** [comment]
I'm stuck on this issue. The main problem to me seems to be that when slider has a negative `min` value in its range, it disallows a `minValue` of `0`; the handle get's `left: 0%` positioning added to it, which forces it to appear to the far left of the track.

It's like slider's range was designed to assume that the minimum value would be 0, not a negative number.

**Comment by caripizza** [comment]
Installed via pr #3083

**Comment by caripizza** [comment]
@benelan it looks like this also happens in a histogram range - I'll open a pr for that edge case fix today since I missed that before.

**Comment by caripizza** [comment]
Additional histogram fix installed via pr #3092.

**Comment by benelan** [comment]
verified on beta.66
