### ISSUE TITLE
Bug: slider's max value thumb can't be moved via pointer if thumbs overlap at min edge

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2481]
### Actual Behavior

The max thumb can't be grabbed when thumbs overlap at the min edge. Users can tab into the thumb and move it via the keyboard, but this seems broken.

### Expected Behavior

When both thumbs overlap at the edge, click/tap should grab the max value thumb

### Reproduction Steps or Sample

https://codepen.io/jcfranco/pen/eYWZxxz?editors=1000

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [x] CDN
- [ ] NPM package

**Comment by caripizza** [comment]
Installed via pr #3078

**Comment by benelan** [comment]
verified on beta.66
