### ISSUE TITLE
Enhancement: calcite-button - update demo html to match Figma designs

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2482]
### Description
This issue aims to achieve parity between the calcite-button Figma design, its demo HTML page, and any usage snippets we provide.

### Acceptance Criteria 
- Variants illustrated in the Figma designs match the variants illustrated on the demo HTML page.

### Relevant Info 
- Figma: calcite-button needs to match the design in Figma.

#### Which Component
calcite-button

**Comment by julio8a** [comment]
verified on master
