### ISSUE TITLE
Enhancement: calcite-input - update demo html to match Figma designs

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2483]
### Description
This issue aims to achieve parity between the calcite-input Figma design, its demo HTML page, and any usage snippets we provide.

### Acceptance Criteria 
- Variants illustrated in the Figma designs match the variants illustrated on the demo HTML page.

### Relevant Info 
- Figma: calcite-input needs to match the design in Figma.

#### Which Component
calcite-input

**Comment by julio8a** [comment]
verified on demo pages
