### ISSUE TITLE
Create shared repository & NPM project for shared utilities & assets

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#249]
Should we create a github repository where we can share code and assets across projects that are building stencil components? Something like `calcite-component-resources`?

Both `calcite-components` and `calcite-app-components` could use it as a dependency and we see other teams building components using stencil that could benefit from these shared resources.

For example, these could be shared:

- [Utilities](https://github.com/Esri/calcite-components/tree/master/src/utils)
  - Functional components (if any)
  - [Common tests](https://github.com/Esri/calcite-components/blob/master/src/tests/commonTests.ts)
- [SCSS mixins](https://github.com/Esri/calcite-components/blob/master/src/assets/styles/_mixins.scss)

Thoughts?

@patrickarlt @paulcpederson @macandcheese

**Comment by macandcheese** [comment]
Agreed - we already have calcite-base that contains some mixins (for font-size, for example https://github.com/Esri/calcite-base/blob/master/dist/_type.scss) - would be good to leverage that if possible for things that may be applicable to others outside Stencil-land. calcite-component-resources/helpers could work as well.

**Comment by driskull** [comment]
We could add another folder for `components` inside `calcite-base` if that is the easier solution.

**Comment by macandcheese** [comment]
`calcite-stencil-base` / `calcite-stencil-helpers` ?

**Comment by driskull** [comment]
I like `calcite-stencil-base` better than helpers

**Comment by julio8a** [comment]
Let's go with `calcite-stencil-base`. I'll reach out to the Github admins and get this repo started.

**Comment by macandcheese** [comment]
Thanks for setting this up @julio8a !
