### ISSUE TITLE
Bug: calcite-combobox incorrect indentations for second level calcite-combobox-items

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/calcite-components#2490]
### Actual Behavior

second level combobox-items are not being indented

### Expected Behavior

second level combobox-items should be indented

### Reproduction Steps or Sample

See combobox storybook:
[https://esri.github.io/calcite-components/?path=/story/components-controls-combobox--simple](https://esri.github.io/calcite-components/?path=/story/components-controls-combobox--simple)

See in CodePen:
[https://codepen.io/john-grayson/pen/QWvEdzG](https://codepen.io/john-grayson/pen/QWvEdzG)

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.59`

- [x] CDN
- [ ] NPM package

**Comment by driskull** [comment]
@jcfranco @julio8a can we move this to current milestone?

**Comment by jcfranco** [comment]
Can you provide an effort estimate on this one (1, 2, 3, 5, 8, 13, 21, 40)? Seems like a 1 or 2 to me.

**Comment by driskull** [comment]
dos

**Comment by jgrayson-apl** [comment]
The indentations look correct when tested with **v1.0.0-next.239**:
[https://codepen.io/john-grayson/pen/QWvEdzG](https://codepen.io/john-grayson/pen/QWvEdzG)
