### ISSUE TITLE
Bug: calcite-combobox only visually highlights the selected item on every other time

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/calcite-components#2491]
### Actual Behavior

calcite-combobox only visually highlights (blue dot and bold text) the selected item on every _other_ selection

### Expected Behavior

calcite-combobox should visually highlight (blue dot and bold text) the selected item _every_ time there's a selection

### Reproduction Steps or Sample

See calcite-combobox Storybook:
[https://esri.github.io/calcite-components/?path=/story/components-controls-combobox--simple](https://esri.github.io/calcite-components/?path=/story/components-controls-combobox--simple)

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.59`

- [x] CDN
- [ ] NPM package

**Comment by jgrayson-apl** [comment]
https://user-images.githubusercontent.com/5324720/124979340-c3c77400-dfe7-11eb-958b-1afce03dd8c0.mp4

**Comment by driskull** [comment]
Thanks @jgrayson-apl! This one seems a bit trickier. what do you think @jcfranco @julio8a ?

**Comment by driskull** [comment]
Seems the issue only shows when mode is single selection. I'm guessing an event issue here.

**Comment by jgrayson-apl** [comment]
@driskull: verified with **@v1.0.0-next.250** that using selection-mode="single" will now correctly highlight the selected option.

[test codepen](https://codepen.io/john-grayson/pen/zYwBVBZ)

Thank you!
