### ISSUE TITLE
Docs: ColorPicker missing Usage section

### ISSUE THREAD

**Issue by dasa** [Esri/calcite-components#2492]
### Description 

Most controls seem to have a Usage section, like [here](https://esri.github.io/calcite-components/?path=/docs/components-controls-checkbox--simple), but ColorPicker [does not](https://esri.github.io/calcite-components/?path=/docs/components-controls-colorpicker--simple).

### Which Component

ColorPicker

**Comment by benelan** [comment]
Hi @dasa, I added Color Picker [usage examples](https://github.com/Esri/calcite-components/tree/master/src/components/calcite-color-picker/usage), do you want to verify before I close the issue? I also created #2860 to add usage examples to the rest of the components that don't have any.

**Comment by jcfranco** [comment]
Verified locally!
