### ISSUE TITLE
Enhancement: Add 2px margin between heading and summary for Block and CalciteListItem

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2494]
### Description
Add 2px margin between heading and summary for Block and Calcite-List to match what picklist and valuelist are doing. currently no margin and the text is butted up with the line-heights

### Acceptance Criteria 
2px margin between heading and summary 

#### Which Component
Block and CalciteListIem

**Comment by asangma** [comment]
Updated to focus on CalciteListItem. :)

**Comment by benelan** [comment]
Installed! @asangma, @bstifle, can one of you verify? Thanks!

**Comment by asangma** [comment]
yup

**Comment by asangma** [comment]
Verfee!
