### ISSUE TITLE
Bug: calcite-combobox - calciteLookupChange event not fired when selection-mode is 'single'

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/calcite-components#2499]
### Actual Behavior

The calcite-combobox 'calciteLookupChange' event is not fired when selection-mode is 'single'.

Reported by user in [GeoNet](https://community.esri.com/t5/calcite-design-system-questions/calcitelookupchange-event-when-combobox-selectionmode-is-single/m-p/1077037#M26)

### Expected Behavior

The calcite-combobox 'calciteLookupChange' event should fire regardless of selection-mode.

### Reproduction Steps or Sample

See CodePen:
[https://codepen.io/john-grayson/pen/zYwBVBZ](https://codepen.io/john-grayson/pen/zYwBVBZ)

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.59`

- [x] CDN
- [ ] NPM package

**Comment by jgrayson-apl** [comment]
oops!  Just found workaround using 'calciteComboboxItemChange'...

**Comment by driskull** [comment]
@jcfranco @julio8a should this be for this sprint?

Looking at the docs, the calciteLookupChange says its just for when the 'selectedItems' change.

It seems like we have internal state for selectedItems and selectedItem. I'm wondering if we should use the same event and refactor selectedItem to just use selectedItems?

**Comment by driskull** [comment]
From meeting. We will deprecate `calciteLookupChange` and create `calciteComboboxChange` to handle both single and multiple selection. cc @jcfranco

**Comment by jgrayson-apl** [comment]
Confirmed that the new 'calciteComboboxChange' event fires for both 'single' and 'multi' using **@v1.0.0-next.254**
[Test CodePen](https://codepen.io/john-grayson/pen/zYwBVBZ)

**Comment by jcfranco** [comment]
@jgrayson-apl Thanks for verifying!
