### ISSUE TITLE
New Component:  `calcite-icon`

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#250]
### Description

Convert the `CalciteIcon` functional component into a web component

#### User Stories

Currently, users have to get the path from `calcite-icons` project and then create an SVG with the path to that icon. There's a lot of boilerplate in that process and we want to ensure consistency for displaying icons. This component will promote that and eliminate boilerplate

### Acceptance Criteria 

Component should have properties for:

- "calcite-icons" name,
- size
- label of the icon

### Helpful Details

https://github.com/Esri/calcite-app-components/blob/master/src/components/utils/CalciteIcon.tsx
https://github.com/ionic-team/ionicons
https://github.com/Esri/calcite-components/tree/jcfranco/proto-calcite-ui-icon

**Comment by macandcheese** [comment]
I like the functionality of: https://github.com/jpeterson/calcite-ui-icons-react (supplying one of three sizes "closest" to the requested size)

We should also figure out how this will work with existing components (ie as a consumer I want to pass the chevronDown24 icon to a calcite-button - it'd be nice to scale that icon proportionally to the scale attribute of the calcite-button)

**Comment by driskull** [comment]
Ideally, they would tell the component to use `size:32` and "chevron-down"or similar and it would load the path for the correct size.

**Comment by macandcheese** [comment]
Yeah, makes sense. I think some components would want to control the size of icon, only accepting the string for name... IMO if a button is scale="s", we should size the icon a user requests for them within the component.

**Comment by jcfranco** [comment]
Added in #256.
