### ISSUE TITLE
Enhancement: calcite-modal - update demo html to achieve parity with Figma designs

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2505]
### Description
This issue aims to achieve parity between the calcite-checkbox following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- Modal design should encompass the Figma HTML demo page

### Relevant Info
- The calcite-modal demo page should have all the variants

#### Which Component
calcite-modal

**Comment by ManahariDahal** [comment]
Ready to verify!

**Comment by julio8a** [comment]
verified on master
