### ISSUE TITLE
Enhancement: CalciteChip

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2506]
### Description
Align Chip a bit more (but not totally) with Button.
One immediate benefit would be to provide a chip style that works well on our background color (`--calcite-ui-background`).

Add
* `neutral` option to color
* `inverse` option to color
* `outline` option to appearance

Deprecate
* `color="grey"` 
  * yes, "grey" with an "e".

### Acceptance Criteria 

* Avoid breaking changes.
* Align styles to matching properties in Button

#### Which Component
CalciteChip

#### Example Use Case
Field Formatting in Map Viewer

**Comment by asangma** [comment]
cc @mitc7862

**Comment by macandcheese** [comment]
This was added in https://github.com/Esri/calcite-components/pull/6058 and is slated for inclusion in our upcoming release.

**Comment by geospatialem** [comment]
Verified on `next.695`
