### ISSUE TITLE
Enhancement: calcite-checkbox - update demo html to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2508]
### Description
This issue aims to achieve parity between the calcite-checkbox following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- Checkbox design should encompass the Figma HTML demo page to achieve parity

### Relevant Info 
- The calcite-checkbox demo page should have all the variants

#### Which Component
calcite-checkbox

**Comment by ManahariDahal** [comment]
Ready to verify!

**Comment by julio8a** [comment]
verified on master
