### ISSUE TITLE
Docs: Add additional information for using attributes related to labels i.e used with aria-labels or tooltips.

### ISSUE THREAD

**Issue by ankitagupta820** [Esri/calcite-components#2517]
### Description 
Component attributes related to labels do not have sufficient information on usage. For instance Calcite-slider ->“max-label”, “min-label” , weather used as tooltip or aria label. Information about how these labels are rendered on UI etc.

### Which Component
-	Calcite-slider: “max-label”, “min-label”
-	Calcite-pagination: “text-label-next”, “text-label-previous”
-	Calcite-pick-list-item: “intlRemove”

### Resources 
Calcite - slider
![image](https://user-images.githubusercontent.com/65870621/125367938-06fa4d80-e32e-11eb-9107-6cf403832d0f.png)

Calcite-Pagination
![image](https://user-images.githubusercontent.com/65870621/125367973-1c6f7780-e32e-11eb-90ea-1b2883bd4491.png)

Calcite-Picklist-item
![image](https://user-images.githubusercontent.com/65870621/125368003-26917600-e32e-11eb-9059-473503e6d329.png)

**Comment by benelan** [comment]
verified on storybook
