### ISSUE TITLE
Enhancement: Calcite-pagination: Support for locale numerals for page numbers.

### ISSUE THREAD

**Issue by ankitagupta820** [Esri/calcite-components#2519]
### Description
The pagination component must locale numbers for page numbers. For instance arabic, hebrew do not support latin numerals.

### Acceptance Criteria 
Component UI shows numbers in locale specific to the language used in browser settings.

#### Which Component
calcite-pagination

#### Example Use Case
For instance calcite-datepicker shows locale specific numerals as below. Similar support should be provided for calcite-pagination.
![image](https://user-images.githubusercontent.com/65870621/125368981-3611be80-e330-11eb-9d26-9de5940c6136.png)

**Comment by jcfranco** [comment]
@annierm18 Can you look at this one and confirm if it's still valid? 🙇‍♂️

**Comment by annierm18** [comment]
@jcfranco This issue is still valid https://jsbin.com/sudacej/edit?html,output.

**Comment by geospatialem** [comment]
Closing in favor of #4893.
