### ISSUE TITLE
New Component: Calcite-scrim

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#252]
We want a more widespread component for loading and disabled states. Gonna make our calcite-app functional component into a calcite "component component" that can be used in this repo and brought into arcgis-components (for Dhrumil).

#### Acceptance Criteria
Props for:
- loading
- ~disabled~

Div styling that matches our spinning science of where icon for loading state and changed opacity for disabled states.

**Comment by macandcheese** [comment]
Maybe related to loading / skeleton states? https://github.com/Esri/calcite-components/issues/163

**Comment by kat10140** [comment]
sorry im editing the description i pushed enter and it submitted a blank issue @macandcheese 😄

**Comment by macandcheese** [comment]
Do we still need this component? It could also probably be some shared css mixin vs. a component...

**Comment by kat10140** [comment]
@macandcheese I started on it, but don't have to finish it. We can talk about it in the meeting tomorrow

**Comment by driskull** [comment]
@kat10140 is there a status update?

**Comment by kat10140** [comment]
moving this to backlog. still need to collaborate with alan

**Comment by driskull** [comment]
@kat10140 does Dhrumil still need this? What is the priority for him?

What part of this needs collaboration? Could we just port the existing logic and styles at this time?

**Comment by asangma** [comment]
> Could we just port the existing logic and styles at this time?

If you mean porting the functional component from calcite-app-components and making it a component, then yeah...that would be neat!

**Comment by macandcheese** [comment]
Is the intention to make this available to folks to use in their own apps, or just for our own components to consume?

**Comment by driskull** [comment]
I think we want to make it available for folks to use

**Comment by driskull** [comment]
Installed.
