### ISSUE TITLE
Enhancement: For type=”tel”, the input must be restricted to numbers (0-9), hyphens (-) and parenthesis ().

### ISSUE THREAD

**Issue by ankitagupta820** [Esri/calcite-components#2521]
### Description
Calcite-input , type="tel" (telephone) is not input restricted. A user can enter all possible characters.
Instead, the input must be restricted to numbers (0-9), hyphens (-) and parenthesis ().

### Acceptance Criteria 
input characters are restricted to numbers (0-9), hyphens (-) and parenthesis ().

#### Which Component
calcite-input , type="tel"

#### Example Use Case

![image](https://user-images.githubusercontent.com/65870621/125369890-1380a500-e332-11eb-95a3-892d3ec36672.png)

**Comment by driskull** [comment]
@eriklharper we should probably just get rid of these.

**Comment by driskull** [comment]
@julio8a @jcfranco should we get rid of `calcite-input` type for 1.0?

**Comment by eriklharper** [comment]
> @eriklharper we should probably just get rid of these.

Get rid of what exactly?  The illegal telephone characters or the `type="tel"` altogether?

I think we should move towards supporting each `type` of input as separate components, so it would become `calcite-input-tel` if we decide to support that.

**Comment by driskull** [comment]
the `type="tel"`.

> I think we should move towards supporting each type of input as separate components, so it would become calcite-input-tel if we decide to support that.

👍

**Comment by eriklharper** [comment]
We'll probably need an Epic to capture deprecating the `type` property from `calcite-input` and make separate tickets that break out all the existing supported types into separate components.

**Comment by macandcheese** [comment]
As far as I know this matches the native implementation - which provides no masking or character limitations: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel

Managing masking ourselves for type tel based on locale seems.... possible but complex and out of scope. Can this be closed?

**Comment by eriklharper** [comment]
We do currently restrict the number input to only valid numbers, including `e`, `-`, `+`, `.` for entering exponential format, negative and positive values and decimals so I can see how it could be relevant to do the same for telephone formats, and it would be easier to restrict input than implement input masks, which will vary based on locale.

However, if `type="tel"` is part of a broader effort to implement consistent form field validation, then we'll have to implement locale-specific validation for telephone numbers anyway, so it could be worth it to roll this up into the broader epic of form validation as well.

**Comment by benelan** [comment]
We discussed this internally, and we are going to continue using the [native input's `type="tel"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel) functionality for the time being. We will reconsider if we recieve a lot more requests to customize the telephone input.
