### ISSUE TITLE
Enhancement: calcite-input type=”time” does not support different locales. 

### ISSUE THREAD

**Issue by ankitagupta820** [Esri/calcite-components#2522]
### Description
calcite-input, type=”time” does not support different locales. 
Existing support only for 12 & 24 hour clocks.

### Acceptance Criteria 
calcite-input of type="time" should support localization of time formats. (AM/PM strings), default clock formats in different locales (12/24 hour clocks) etc.

#### Which Component
calcite-input, type="time"

#### Example Use Case
For instance, in korean "AM"/"PM" are translated.
![image](https://user-images.githubusercontent.com/65870621/125370382-32336b80-e333-11eb-94a2-668cb0215c5d.png)

**Comment by driskull** [comment]
This component just displays a native input element. I don't think the native browser supports this formatting so we likely won't be able to do anything here.

For example this does nothing different, even if you set your browser locale differently.

```html
<input lang="ko" type="time">
```

**Comment by benelan** [comment]
We discussed this internally, and we are going to continue using the [native input's `type="time"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time) functionality. You can use [`calcite-input-time-picker`](https://developers.arcgis.com/calcite-design-system/components/input-time-picker/) as an alternative.
