### ISSUE TITLE
Bug: Panel header/heading x-spacing doesn't match Block header/heading x-spacing

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2524]
### Actual Behavior
Alignment between Panel header and Block header is off.
Note this will not apply when
- Panel has a back button
- Block has any content (icon, drag handle) in the start position of its header

### Expected Behavior
* suggested x-padding for Block is 0.75rem (`px-3`)
* This would also mean that Panel `.header-content` should also get x and y padding to match (`p-3`)
* Because Panel's .header-content is `display: block`, it also needs:
  - `display: flex`
  - `flex-direction: column`
  - ~align-items: center~
  - might also benefit from `flex: 1 0 auto` (not sure)

### Reproduction Steps or Sample

1. view `demos/shell/nesting-testing.html`.

![Screen Shot 2021-07-13 at 7 40 18 AM](https://user-images.githubusercontent.com/12503298/125472352-5181c29d-1912-4411-a1fa-3349f4370d37.png)

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by asangma** [comment]
cc @TheBlueDog spoke with Ade about this.

**Comment by bstifle** [comment]
this is good. ill update in figma/sketch

**Comment by asangma** [comment]
@bstifle

> this will mean the back button for panel will need to be updated to have parity with the horizontal spacing.

I propose we use the Panel 0.75rem spacing. It's also what Block uses for its content area. Thoughts?

Also, that back button is a CalciteAction with `scale="s"`. We'd need to update that component.

**Comment by bstifle** [comment]
@asangma i deleted that comment cuz it was innacurate

**Comment by bstifle** [comment]
@asangma that being said.. i think using 1 rem in both cases would be stronger. panel with a 12px left is pretty tight

**Comment by asangma** [comment]
@bstifle Let's have a look at the two options together in a demo app yeah?

**Comment by jcfranco** [comment]
@bstifle @asangma Would this be handled by the ongoing styling refactor?

**Comment by asangma** [comment]
@jcfranco The stylesheet update might be. But we need to make a call on which amount of spacing to use.

**Comment by anveshmekala** [comment]
@asangma @bstifle I assume we are going ahead with 1rem for panel header x-space .Correct me if I am wrong. Thanks.

**Comment by asangma** [comment]
![image](https://user-images.githubusercontent.com/12503298/139963355-299dc251-af64-45ed-b2d2-81a4e5df5246.png)

So clean!
