### ISSUE TITLE
Enhancement: Modal width property values are misleading. Change to Narrow, Moderate, Wide

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2525]
### Description
Modal width property values are misleading because the they are the same as Scale which uses S M L.

Change S M L width values to -> Narrow, Moderate, Wide

![image](https://user-images.githubusercontent.com/14083530/125495402-cf3ef38d-7d06-4f25-99a3-d913aef1a797.png)

**Comment by macandcheese** [comment]
Moderate seems a little weird to be a width value… I don’t think there’s anything wrong with it also being medium (or matching s,m,l). FWIW I think dropdown also has this width property.

**Comment by bstifle** [comment]
Narrow, Default, Wide would prob be better

**Comment by driskull** [comment]
I would prefer to keep it s,m,l if possible for consistency

**Comment by jcfranco** [comment]
Closing in the name of consistency.
