### ISSUE TITLE
Enhancement: calcite-icon demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2529]
### Description
This issue aims to achieve parity between the calcite-icon following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- Icon design should encompass the Figma HTML demo page

### Relevant Info 
- The calcite-icon demo page should have all the variants

#### Which Component
calcite-icon

**Comment by ManahariDahal** [comment]
Ready to verify!

**Comment by julio8a** [comment]
verified on master.
