### ISSUE TITLE
Research: Inactive Dropdown Options Mistaken For Disabled

### ISSUE THREAD

**Issue by drewdaemon** [Esri/calcite-components#2530]
### Background

We recently used dropdown Calcite components in the Hub application and got feedback from users that the lighter, inactive text color that shows on the `calcite-dropdown-item` sometimes led to dropdown options being mistaken for being disabled when they were really just not _active_.

### Desired Outcome

See if it might be worth denoting inactive options in a way that isn't easily confused with a disabled state.

**Comment by samanthahunter** [comment]
An example of our first implementation and some customer feedback (loudoun.gov):
<img width="295" alt="Screen Shot 2021-07-13 at 5 47 51 PM" src="https://user-images.githubusercontent.com/33425289/125529768-38cf8578-b7a5-421f-877b-2713e88d4a3c.png">

> From working with customers trying to download data, our front counter has provided this feedback: When you click the Download Options button, it appears that 'Download available file' is grayed out and not selectable.; When the mouse is over Download available file, the text turns black and you are able to click it, but the second option to 'Request a new file' is not obvious that downloading is an option and the blue selection remains on the 'download available file'

**Comment by julio8a** [comment]
@bstifle can you take a look at this one

**Comment by bstifle** [comment]
This is tricky since there are only two options.

Here are a few solutions:
![image](https://user-images.githubusercontent.com/14083530/127567118-c570e7e4-157a-4553-83ef-74d8ac077512.png)

1.  Adding support icons to your dropdown.

2. Remove the dropdown and have two buttons: Request new file, and Download available file

3.  Use a native select and dropdown



I recommend #2 since it is the most clear and requires less clicks

**Comment by bstifle** [comment]
@andrewctate were you able to take a look at those  solutions?

**Comment by andrewctate** [comment]
Hi @bstifle. Thanks for your solutions comment. I did see it, but assumed it was directed at the Calcite Components team.

We fixed the problem on our end by overriding the text color. I opened this issue just to share the feedback we received in case your team found it useful in considering any changes to this styling in `calcite-components` itself.

Thanks for your time in researching this for me, and I apologize that I wasn't more clear.

**Comment by bstifle** [comment]
@andrewctate can you share a screenshot on your solution?

Thanks!

**Comment by andrewctate** [comment]
<img width="455" alt="download options" src="https://user-images.githubusercontent.com/315764/128928418-b4d2575a-aaff-4713-91cc-9a78999db5d3.png">

**Comment by geospatialem** [comment]
Closing in favor of a similar request on `combobox`: #6245
