### ISSUE TITLE
Docs: calcite-block - description for slot=icon is wrong

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2531]
### Description 

![image](https://user-images.githubusercontent.com/44481292/125530132-179b0c25-e73f-4cb6-91ff-02f5d9c9c199.png)

Though icon seems to appear at the leading side.
![image](https://user-images.githubusercontent.com/44481292/125530192-ed44cf92-b6b9-475b-8f40-4188376d172c.png)

**Comment by julio8a** [comment]
installed. @AdelheidF, would you mind verifying this one?

**Comment by julio8a** [comment]
self-verified on master

**Comment by AdelheidF** [comment]
looks good, thanks

![image](https://user-images.githubusercontent.com/44481292/128051766-45ed908c-a82c-4dfa-b650-7e9bb0d54bfb.png)
