### ISSUE TITLE
Bug: calcite-radio-button-group events only fire when clicking the labels and not radio buttons

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#2535]
### Actual Behavior

In a radio button group when clicking on a radio button wrapped in a label events only fire when clicking the label and not the button.

### Expected Behavior

When a radio button is clicked and/or the check state of the group has changed events should fire.

### Reproduction Steps or Sample

https://codepen.io/COV-GIS/pen/BapJogR

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.59`

- [x] CDN
- [x] NPM package

**Comment by driskull** [comment]
@COV-GIS I'm not seeing any event in the codepen unless I change the event to `calciteRadioButtonGroupChange`. Then it seems to work fine.

**Comment by COV-GIS** [comment]
Guess you have to use the right event. Thanks @driskull.
