### ISSUE TITLE
Bug: Number input event not fired when removing remaining decimal value

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#2538]
### Actual Behavior

When I type "1.2" into a number input then delete "2", the component only emits events for "1" and "1.2" not "1", but the final input displays "1".

### Expected Behavior
The component emits an event for the final "1" as well.

### Reproduction Steps or Sample

Codepen: https://codepen.io/mpayson/pen/BaRpXvy

Type "1.2" into the input then delete "2" and check the console logs, there should only be two events
### Relevant Info

Firefox, latest (89)

_Version_

- [x] CDN (1.0.0-beta.59) 
- [x] NPM package (1.0.0-beta.57)

**Comment by benelan** [comment]
Relevant code
https://github.com/Esri/calcite-components/blob/14a8f75f99750e0c0f6d9ca7d39a3b641d46757e/src/components/calcite-input/calcite-input.tsx#L613-L621

**Comment by jcfranco** [comment]
Verified with repro case!
