### ISSUE TITLE
Tree: Click / keypress function and selection mode bug

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#254]
Currently it seems as if you can enter "multi" select mode when using the `SPACE` key to select items in a `<calcite-tree>`, even with explicitly set "single" `selection-mode`.

Reproduction:

- go to: https://esri.github.io/calcite-components/?path=/story/tree--simple
- in `selection-mode:single` - clicking sibling items or using `ENTER` to select them should abide by "single select" mode and NOT select more than one item.
- using the `SPACE` key to select items should cause both siblings to be selected even though the select-mode is set to `single`

Perhaps this is intended and I am misinterpreting the way these modes work :)

**Comment by julio8a** [comment]
is this one still an issue?

**Comment by macandcheese** [comment]
yes

**Comment by julio8a** [comment]
@patrickarlt, is this something you can work on?

**Comment by jcfranco** [comment]
@macandcheese I'm confused. The following 

> using the SPACE key to select items should cause both siblings to be selected even though the select-mode is set to single

seems to contradict 

> in selection-mode:single - clicking sibling items or using ENTER to select them should abide by "single select" mode and NOT select more than one item.

In single-selection, shouldn't there be at the most one node item selected? Maybe I'm missing something.

**Comment by macandcheese** [comment]
Probably should have read as "using the SPACE key to select items should **NOT** cause both siblings ...".

This is old enough to be closed, the storybook doesn't behave like this anymore so it can probably be closed.

**Comment by jcfranco** [comment]
@macandcheese Thanks for clarifying. Closing!
