### ISSUE TITLE
Bug: calcite-list not looking the same as calcite-pick-list

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2541]
### Actual Behavior

The 2 lists don't match on the vertical padding and on the  definition between items.

calcite-list&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;calcite-pick-list
![image](https://user-images.githubusercontent.com/44481292/125705128-853ad4aa-9ca7-4d47-a83a-974914163e16.png)![image](https://user-images.githubusercontent.com/44481292/125705145-22836ae2-0fb0-404e-beb1-d8360ad179c1.png)

calcite-list padding:
`.content { padding: 0.75rem;`

calcite-pick-list padding:
`.label { padding: 0.5rem 0.75rem`

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by asangma** [comment]
@caripizza @jcfranco Would be nice to get this in soon since CalciteList is starting to get used.

**Comment by jcfranco** [comment]
@asangma Can you estimate the level of effort for this? If simple, do you have some cycles to wrap this up this week?

**Comment by asangma** [comment]
LOE is very low.
I could make it happen today.

**Comment by jcfranco** [comment]
@asangma Up for grabs for this milestone. 💪🏼

**Comment by AdelheidF** [comment]
Good now, thank you. Tested with next.243

![image](https://user-images.githubusercontent.com/44481292/125982389-be8fe672-9a56-4e09-b1db-3d34f113588f.png)

**Comment by asangma** [comment]
Woot!
