### ISSUE TITLE
Enhancement: calcite-chip demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2549]
### Description
This issue aims to achieve parity between the calcite-chip following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- Chip design should encompass the Figma HTML demo page

### Relevant Info 
- The calcite-chip demo page should have all the variants

#### Which Component
calcite-chip

**Comment by julio8a** [comment]
verified on master.
