### ISSUE TITLE
Docs: List storybook is misleading

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2553]
### Description 
The first list-item uses all the slots and the following items don't making it seem like the first item is a header.

![image](https://user-images.githubusercontent.com/12503298/125977185-b8f2b40a-5f51-49f6-b7df-e8dc20c55106.png)

### Which Component
CalciteList

**Comment by asangma** [comment]
Suggest doing something more akin to what's in the demo.

**Comment by driskull** [comment]
@asangma I can update them here: https://github.com/Esri/calcite-components/pull/2550

**Comment by asangma** [comment]
Thanks @driskull!
