### ISSUE TITLE
Unstable Test: dropdown-item - item selection should work when placed inside shadow DOM

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2554]
## Summary

Investigate why the following change is necessary. 

https://github.com/Esri/calcite-components/pull/2485#pullrequestreview-708562921

https://github.com/Esri/calcite-components/blob/deb41815531c0d1282a7357b0e3f6667b8a9fd74/src/components/calcite-dropdown/calcite-dropdown.e2e.ts#L951

**Which component?:** dropdown-item

**Which test(s)?:** 

https://github.com/Esri/calcite-components/pull/2485#pullrequestreview-708562921

**Test error:**

Test requires another request for animation frame change.

**PR that skipped the test:** N/A

**Comment by benelan** [comment]
verified on master
