### ISSUE TITLE
Enhancement: calcite-combobox demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2561]
### Description
This issue aims to achieve parity between the calcite-combobox following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- Combobox design should encompass the Figma HTML demo page

### Relevant Info 
- The calcite-combobox demo page should have all the variants

#### Which Component
calcite-combobox

**Comment by ManahariDahal** [comment]
ready to verify @julio8a

**Comment by julio8a** [comment]
Verified on master
