### ISSUE TITLE
Bug: selected and hover dropdown no longer have an ellipse visible

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2566]
### Actual Behavior
No longer a visible ellipse. The icon update in #2485 must have caused a bug

![image](https://user-images.githubusercontent.com/14083530/126183653-e9e7d69e-61aa-4dc3-96fa-44b0a84d2637.png)

### Expected Behavior

Hover and selected need to have an ellipse:
![image](https://user-images.githubusercontent.com/14083530/126183865-0a896cfc-e166-4a3c-84ae-8df5671f702b.png)

hover color: ui-border-1
active color: ui-brand

### Reproduction Steps or Sample

Open dropdown

### Relevant Info

on master

**Comment by julio8a** [comment]
Since it's a new version of the icon library, you need to run 'npm i' so it downloads the latest icons.

**Comment by caripizza** [comment]
I can't replicate this issue, I see the bullet just fine on master:

![image](https://user-images.githubusercontent.com/42423180/126207908-9ac9d07a-f99b-48eb-911e-c40c3b254ca3.png)

@bstifle let me know if I'm missing something here!

**Comment by julio8a** [comment]
@bstifle since it is a new icon from a new release you need to run￼ npm i

**Comment by bstifle** [comment]
WHOOPSIE

i see it now, thanks Julio
