### ISSUE TITLE
Bug: calcite-slider histogram does not line up with slider

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#2569]
### Actual Behavior

![image](https://user-images.githubusercontent.com/8754/126213954-bfd94407-0303-4533-bcd1-c37700a9521b.png)

https://esri.github.io/calcite-components/?path=/story/components-controls-slider--histogram

The histogram extends beyond the slider. The range indicators on the histogram do not line up with the slider.

### Expected Behavior

Histogram and range indicators should line up with the slider and handles.
 The vertical white lines should follow with the handles (like they are connected to them)
![image](https://user-images.githubusercontent.com/14083530/128289783-bfd29f27-e94e-4d96-bbc3-c80dc669433e.png)

### Reproduction Steps or Sample

1. go to https://esri.github.io/calcite-components/?path=/story/components-controls-slider--histogram

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

It's not clear what version is currently deployed to storybook, I assume https://github.com/Esri/calcite-components/releases/tag/v1.0.0-beta.59.

**Comment by jcfranco** [comment]
Closing in favor of #2706
