### ISSUE TITLE
Enhancement: calcite-color-picker demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2576]
### Description
This issue aims to achieve parity between the calcite-color-picker following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- Color-picker design should encompass the Figma HTML demo page

### Relevant Info 
- The calcite-color-picker demo page should have all the variants

#### Which Component
_calcite-color-picker_

**Comment by ManahariDahal** [comment]
ready to be verified @julio8a

**Comment by julio8a** [comment]
verified on master
