### ISSUE TITLE
Bug: calcite-block-section and calcite-label+calcite-switch toggle buttons not aligned vertically

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2577]
### Actual Behavior

Beta.60

![image](https://user-images.githubusercontent.com/44481292/126394532-5342c347-0677-452e-9726-dbeff84d5075.png)

Top and bottom elements are `calcite-block-section`. Center is a `calcite-label` with a `calcite-switch`.

1. if you look at the three toggle buttons they're not aligned vertically
2. if you look at the very first toggle button it's not horizontally aligned with the text.

I can add a margin to the center element. Not sure if this is expected though.

The switch inside the block-section uses a margin:
![image](https://user-images.githubusercontent.com/44481292/126394982-d048e26f-2f92-4db6-bb32-4e45605e2fa1.png)

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.60`

- [ ] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
Looks like label or block-section needs to tweak the trailing space. @Esri/calcite-design-representatives Do you think this is the case or are there other things to consider?

**Comment by caripizza** [comment]
Which version? This might be fixed in latest `next` [per my comment in Justin's pr](https://github.com/Esri/calcite-components/pull/2681#issuecomment-892215276)

**Comment by jcfranco** [comment]
@caripizza Thanks for the update! 

@AdelheidF Can you update the description with the version and also check if this is fixed in `next`?

**Comment by AdelheidF** [comment]
Tested with next.265.

Horizontal alignment is correct now. Vertical is not.

![image](https://user-images.githubusercontent.com/44481292/128778991-9e746dda-13d3-418d-8b1b-f0990489c729.png)

**Comment by caripizza** [comment]
Where is the code snippet so we can reproduce the issue?

**Comment by AdelheidF** [comment]
The test case is part of Map Viewer.

Can you not reproduce it with a `calcite-block-section` and a `calcite-label` with a `calcite-switch`?

**Comment by caripizza** [comment]
@AdelheidF we have various devs working on style issues like this, and some don't have access to what you're looking at. Any code you can give us will help us fix the issue faster, thanks.

**Comment by julio8a** [comment]
CodePen example:
https://codepen.io/julio8a/pen/gOWJwvQ

**Comment by justinhough** [comment]
@caripizza The easiest solution might be to add the following to check for `inline-space-between`, which would add the necessary margin based on the codepen example from @julio8a. I can't see we would want to add the margin in any other case to the switch unless it is using that specific flex layout.

```[layout=inline-space-between] calcite-switch {
    margin-right: 0.25rem;
}```

**Comment by caripizza** [comment]
@justinhough sorry for my delay. Looking at this closer, it seems like the issue stems from the fact that calcite-block-section uses a [native label](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-block-section/calcite-block-section.tsx#L128) with its own padding/margins alongside its calcite-switch (ie., it doesn't use a calcite-label right now).

It looks like adding some external styles like this will align the switches vertically/make the label look like the other block-sections:

```css
calcite-block {
  width: 33vw;
}
calcite-label {
  display: block;
  margin-top: 12px;
  border-bottom: 1px solid var(--calcite-ui-border-3);
}
calcite-switch {
  margin-inline-end: 4px;
}
.calcite--rtl calcite-switch {
  margin-inline-end: 0;
}
```

On beta.62, the above styles render like so:
![image](https://user-images.githubusercontent.com/42423180/130529398-3eb47665-75c9-456d-863f-bba917aec4b7.png)

CodePen: https://codepen.io/caripizza-the-animator/pen/wvevqZy

@AdelheidF can you take a look at my pen and let me know if this is an option?

**Comment by AdelheidF** [comment]
> I can add a margin to the center element. Not sure if this is expected though.

This was my original question. I can add the margin on my side to fix this. Wasn't sure if you wanted to have it all aligned out of the box.

**Comment by asangma** [comment]
@julio8a I think we can just remove the margins on the switch inside BlockSection.

Unless I'm missing something @caripizza ?

**Comment by AdelheidF** [comment]
these orange ones here...

![image](https://user-images.githubusercontent.com/44481292/131382487-b3a086b5-cc33-4267-ba7a-da40f8cda680.png)

I'll look like this if I remove the margins:
![image](https://user-images.githubusercontent.com/44481292/131382217-de98abf2-cf85-4419-9b11-2ff471b24f2b.png)

**Comment by caripizza** [comment]
@julio8a it sounds like this issue is needed, who should work on it?

**Comment by asangma** [comment]
I can do it.

**Comment by julio8a** [comment]
Thanks, @asangma, Do you just want to update this PR or create a new one?
https://github.com/Esri/calcite-components/pull/2839

**Comment by asangma** [comment]
@julio8a I'll create a new one.

**Comment by asangma** [comment]
@julio8a this fix has been installed. Not sure who should verfee.

cc @AdelheidF

**Comment by julio8a** [comment]
@AdelheidF, can you help verify this one?

**Comment by asangma** [comment]
@benelan Do you think you could have a verify? Let me know if you have questions.

**Comment by AdelheidF** [comment]
Using beta.64 it looks good now.

![image](https://user-images.githubusercontent.com/44481292/133289021-d76eabc3-0dd2-49ce-b483-c0e364c340f9.png)

**Comment by benelan** [comment]
Ah beat me to it, I was just looking at Julio's sample. Thanks!
