### ISSUE TITLE
Document that global css file is needed for color variables

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#258]
In order for a lot of the color styling to work in the components, the calcite.css style file (found at `@esri/calcite-components/dist/calcite/calcite.css`) needs to be imported globally. If this isn't documented anywhere, there should be some documentation stating that this file is required and why it's needed in addition to things like `calcite-colors` and `calcite-base`.

cc @oknoway @paulcpederson

**Comment by macandcheese** [comment]
Yeah, I think this became a dependency when the root-level included css vars were added. It'd be a cleaner story without the need to add the built css obviously, but not sure if there's a way to pass css var without that?

**Comment by noahmulfinger** [comment]
@macandcheese Do you think those css vars could go in `calcite-colors` or `calcite-base`? Maybe making the additional calcite.css file necessary if you don't already include `calcite-colors`?

**Comment by paulcpederson** [comment]
@noahmulfinger do you already pull in calcite-base as css vars?

**Comment by noahmulfinger** [comment]
We're just importing `calcite-base/dist/_index.scss` and `calcite-colors/colors.scss` at the moment. So we're not importing `calcite-base/dist/variables.css` if that's what you mean.

**Comment by macandcheese** [comment]
Added in https://github.com/Esri/calcite-components/pull/262 🎈
