### ISSUE TITLE
Enhancement: calcite-date-picker demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2580]
### Description
This issue aims to achieve parity between the calcite-date-picker following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- Date-picker design should encompass the Figma HTML demo page

### Relevant Info 
- The calcite-date-picker demo page should have all the variants

#### Which Component
_calcite-date-picker_

**Comment by ManahariDahal** [comment]
Ready to verify!

**Comment by julio8a** [comment]
verified on master
