### ISSUE TITLE
Bug: disabled calcite-input + type=number allows interaction with the up/down buttons. 

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2582]
### Actual Behavior

The up/down buttons can be still be clicked when the input component is disabled. 

### Expected Behavior

Value cannot be adjusted when clicking up/down buttons.

### Reproduction Steps or Sample

1. Open https://codepen.io/jcfranco/pen/XWRaqYW
2. Click on up/down buttons

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [x] CDN
- [ ] NPM package

**Comment by caripizza** [comment]
Related: #2378

**Comment by julio8a** [comment]
verified on Codepen.
