### ISSUE TITLE
Bug: Accordion chevron direction doesn't match Block

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2597]
### Actual Behavior
Note: this only applies when Accordion is `icon-position`: `end` and `icon-type`: `chevron` or `caret`.

**Block**
In Block the chevron indicates the direction of the resultant action. Down when collapsed...
![image](https://user-images.githubusercontent.com/12503298/126569967-f39827bc-30ea-4f15-a95c-53043fd707f6.png)

...up when opened.
![image](https://user-images.githubusercontent.com/12503298/126570020-7176aae4-81b0-4bb0-bd2b-9f2b796d9cf7.png)

**Accordion**
Accordion uses the chevron to indicated state. Up when collapsed...
![image](https://user-images.githubusercontent.com/12503298/126570081-9f13edbb-fd30-4640-825f-76afbc0c0305.png)

...down when open.
![image](https://user-images.githubusercontent.com/12503298/126570117-de07de1c-d4a5-4ccb-be6d-b402305bdbd5.png)\

### Expected Behavior
Align with Block chevron direction: down when closed & up when open.

### Reproduction Steps or Sample

1. See Accordion demo and Block demo.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

cc @bstifle

**Comment by bstifle** [comment]
yes! this is the way it was intended. thanks alan

**Comment by asangma** [comment]
Note, this reverts the changes discussed [here](https://github.com/Esri/calcite-components/issues/289#issuecomment-630419597).

But we have an established pattern in Block which is being used a fair amount.

**Comment by bstifle** [comment]
Yeah, the chevron direction paradigm should be different depending on start/end placement.

Start closed: pointing right
Start open: pointing down

End closed: pointing down
End open: pointing up

**Comment by asangma** [comment]
Agreed.
This is currently what we use in Block (right/end) and BlockSection (left/start).

**Comment by benelan** [comment]
This has been installed, @asangma can you please verify?

**Comment by asangma** [comment]
@anveshmekala Sorry. Looks like we missed the `icon-position--start` case. With the update, the open icon should be pointing down.
![Screen Shot 2021-09-03 at 4 34 31 PM](https://user-images.githubusercontent.com/12503298/132074462-bdd31089-0bb5-4bd3-843f-843eb71ce8de.png)

The animation should also go the other way. Right now, the icon spins the wrong way.

**Comment by anveshmekala** [comment]
Will fix it. Thanks @asangma .

**Comment by anveshmekala** [comment]
@asangma can you please attach the expected icon spin direction when `icon-position` set to start . Thanks.

**Comment by asangma** [comment]
### LTR icon in start position
* closed to open, rotate clockwise from `>` to `v`
* open to closed, rotate counterclockwise from `v` to `>`

### RTL icon in start position
* closed to open, rotate counterclockwise from `<` to `v`
* open to closed, rotate clockwise from `v` to `<`

Does that help @anveshmekala? :)

**Comment by anveshmekala** [comment]
Yup. Exactly what I am looking for. Thanks @asangma

**Comment by anveshmekala** [comment]
@benelan can you please verify this issue. Thanks

**Comment by benelan** [comment]
Hi @anveshmekala, It looks like the closed icon is still pointing down in beta.64

https://codepen.io/benesri/pen/PojJeyL?editors=1000

Can you take another look?

**Comment by anveshmekala** [comment]
@benelan That's the expected behavior. Icon when positioned at end will point down when closed and up when open.

**Comment by benelan** [comment]
Oh maybe I misunderstood the instructions, @asangma can you verify this one for me please?

**Comment by benelan** [comment]
Alan verified

**Comment by asangma** [comment]
![yay](https://media.giphy.com/media/j6NbehBiL808NVgDY5/giphy.gif)
