### ISSUE TITLE
Enhancement: [Color Picker] Fix hue bar click and drag interaction

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#2602]
### Description
Currently, dragging past the extent of the hue bar will cause an abrupt "snap" back to the opposite side of the hue bar.

### Acceptance Criteria 
While using a mouse to click and drag past the component boundary, prevent the selector from snapping.

### Relevant Info 
https://user-images.githubusercontent.com/4733155/126690043-888c038f-384f-499f-b545-b11ef5a49bee.mp4

https://esri.github.io/calcite-components/?path=/story/components-controls-colorpicker--simple

#### Which Component

Color Picker

**Comment by geospatialem** [comment]
Verified in Storybook

https://user-images.githubusercontent.com/5023024/175564500-7ba07af9-e826-4a21-8594-73cf97a90257.mp4
