### ISSUE TITLE
Enhancement: calcite-scrim demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2605]
### Description
This issue aims to achieve parity between the calcite-date-picker following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-scrim design should encompass the Figma HTML demo page

### Relevant Info 
- It should have all the variants

#### Which Component
_calcite-scrim_

**Comment by julio8a** [comment]
verified on master
