### ISSUE TITLE
Enhancement: calcite-accordion demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2616]
### Description
This issue aims to achieve parity between the calcite-accordion following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-accordion design should encompass the Figma HTML demo page

### Relevant Info 
- It should have all the variants

#### Which Component
_calcite-accordion_

**Comment by ManahariDahal** [comment]
ready to verify @julio8a

**Comment by julio8a** [comment]
Verified on master
