### ISSUE TITLE
Enhancement: Add `closable` functionality to calcite-tabs-title

### ISSUE THREAD

**Issue by am-maneaters** [Esri/calcite-components#2620]
### Description
Add action button to the calcite-tab-title component to allow for closing tabs

*Obviously very rough implementation below
<img width="552" alt="image" src="https://user-images.githubusercontent.com/50883428/126845046-2e9caf15-c592-4e11-850b-d80995b035d3.png">

### Acceptance Criteria 
Include action button in tabs with custom icons and custom onClick event

#### Which Component

calcite-tab-title

#### Example Use Case

Allow users to close opened tabs using the action button in the tab titles

**Comment by AdamWMoqrane** [comment]
Hello! XI Design would definitely have a need for this issue with the Knowledge Studio project we are working on. Prioritizing this would help many out!

**Comment by RSantosGIS** [comment]
Just wanted to bump this requirement from the ArcGIS Knowledge Studio team again following our conversation with Adam T. yesterday.

**Comment by macandcheese** [comment]
This was mentioned in a Community post as well: https://community.esri.com/t5/calcite-design-system-questions/calcite-tab-dismissible-closable/m-p/1238589#M278

**Comment by lkoumis** [comment]
Similar to the attribute table in web appbuilder, it would be a great feature to be able to add a tab containing the  feature table of a loaded layer and then be able to remove the tab when the layer is removed from the map.

**Comment by macandcheese** [comment]
@geospatialem @jcfranco - this is high-impact for Knowledge Studio and other teams.

**Comment by geospatialem** [comment]
Should consider with the efforts of https://github.com/Esri/calcite-components/issues/2721, anticipated for the May 2023 milestone.

**Comment by ashetland** [comment]
Quick question about behavior on this as we work out details. I would expect [closable] to be globally set, e.i. all tabs are closable or not-closable. This way we would avoid a confusing possible state of mixed closable and non-closable tabs. Does this thinking jive with expectations?

**Comment by macandcheese** [comment]
I’d imagine it would be more flexible to set per tab. 

Perhaps the tabs represent tables or sheets, and the app has a minimum number to display, or for the same workflow, some tabs are locked due to permission (and denoted as such with icon-start/end).

Those are just two use cases that come to mind but I’d expect some other similar needs. 

Some related questions:
Should we allow the last tab to be closed?

Should we consider allowing tabs to be re-ordered (log as separate enhancement). If tabs can be closed, we can imagine they may be used in workflows where users could reorder the representative tabs.

**Comment by lkoumis** [comment]
Like I mentioned in an earlier post, ideally it should work like the Attribute table in ArcGIS web appBuilder.
First tab does not have a closable option but the rest of the tabs. 
![image](https://user-images.githubusercontent.com/3720337/226071250-ede7cdd1-7e12-4542-9c01-c3b09e89b3be.png)

**Comment by AdamWMoqrane** [comment]
This is going to be implemented one way or another by the Knowledge team for this Summer so would love to have it in Calcite. Here is a use case below (being able to have different content item opens in Knowledge Studio and closing them accordingly using their tabs...): 

![image](https://user-images.githubusercontent.com/83651264/226076086-0feae801-448f-4876-8df0-b6a8bd412d0a.png)

**Comment by AdamWMoqrane** [comment]
Also @macandcheese  having tabs reordered maybe by a drag interaction... that would be amazing

**Comment by ashetland** [comment]
Thanks all, setting closable on a per-tab basis looks like the way to go. Agree we should consider adding the ability to reorder tabs (separate enhancement issue). @AdamWMoqrane, I'm finishing up the details in Figma this week so development can begin on this.

**Comment by AdamWMoqrane** [comment]
@ashetland Amazing, thank you!

**Comment by geospatialem** [comment]
Reallocating to the April milestone.

**Comment by ashetland** [comment]
@geospatialem, final designs are ready in the Figma enhancements folder and had a walkthrough chat today with Eliza. The Figma branch should get merged this week so designers can start playing with it.

**Comment by AdamWMoqrane** [comment]
Yay! Thanks Aaron, we are looking forward to using this!

**Comment by RSantosGIS** [comment]
Thanks for working on this!  We are definitely glad to not have to custom roll this as an extended capability in Studio

**Comment by Elijbet** [comment]
I have a lingering question regarding what happens when we close a tab. As in does closing tab 3 mean we get tab 4 selected (tab 4 contents displayed) after tab 3 and its contents are gone?

Or do we let it refocus to default: tab 1 with its contents displayed?

@SkyeSeitz @ashetland @macandcheese

**Comment by macandcheese** [comment]
I'd expect the previous tab to be focused and open, similar to how closing a Sheet in Excel opens the previous Sheet and makes that Tab active (they don't have a close button, but you can right click to select from menu).

This also follows how it is set up in upcoming Chip Group - if you close a chip, the previous chip gains focus.

**Comment by SkyeSeitz** [comment]
My expectation was for the next tab to be focused and opened rather than the previous, but I could see either way as long as we are consistent 👍🏽

**Comment by Elijbet** [comment]
> My expectation was for the next tab to be focused and opened rather than the previous, but I could see either way as long as we are consistent 👍🏽

I think this is problematic when the closed tab is the last tab. And since we decided that the first tab cannot be closed if it's the last remaining one, the previous tab being focused makes more sense.

**Comment by ashetland** [comment]
> Like how it was implemented on the Attribute table of the Web AppBuilder, if tab3 closes, then tab4 will be selected and show its contents. If tab 4 then tab3 will be selected. So, the tab to be closed, the tab to its right will get focus, if the rightmost tab closes then the tab to its left will be focused, and if the leftmost tab closes, the tab to its right will be focused,

This feels like the correct approach. See this video of Chrome tabs as a demonstration. 
Using our 4-tabs model:
- Closing a background tab does not change my current tab or focus
- If tab 1 is active and closed, tab 2 becomes active
- If tab 3 is active and closed, tab 4 becomes active
- If tab 4 is active and closed, tab 3 becomes active

https://user-images.githubusercontent.com/108549080/228880345-e0a2a7a9-a2b4-4599-a042-9f27a9f9861d.mp4

**Comment by ashetland** [comment]
Adding link to the final spec in Figma for reference. 
https://www.figma.com/file/xly5vekrCnx7AH0e4D4ueM/Closable-Tabs-%5Bissue-2620%5D?node-id=1-2

**Comment by geospatialem** [comment]
Migrating to the May release for implementation.
