### ISSUE TITLE
Docs: update demos/ index page to include links to all pages, remove old styles

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2622]
### Description
Right now we have some pages linked to on the main index.html page, but there are many other pages you can only get to by manually typing demos/ path into the browser.

### Acceptance Criteria 
1. All demos/ html pages appear as clickable links on the main index.html file.
2. All demos pages source from the same updated styles (ie., no more gray background color pages with "Courier New" font).

**Comment by caripizza** [comment]
@julio8a should this one be worked on in the current sprint or next sprint?

**Comment by julio8a** [comment]
Not this sprint. Will look at the next sprint.

**Comment by benelan** [comment]
There are a couple more demos that are missing from the landing page:
- graph
- input-date-picker
- theme
- animation
- handle
- shell (pick whichever you think is best)

**Comment by benelan** [comment]
verified on master
