### ISSUE TITLE
Docs: Installation CDN

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#2623]
### Description 

The [installation instructions](https://github.com/Esri/calcite-components#installation) use the unpkg CDN. *.arcgis.com should probably be the recommendation like [ArcGIS for JavaScript](https://developers.arcgis.com/javascript/latest/get-started/)

```html
<script type="module" src="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.esm.js"></script>
<link rel="stylesheet" type="text/css" href="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.css" />
```

**Comment by driskull** [comment]
@jcfranco do you think we could have a URL on the CDN that redirects to the latest version like unpgk does?

Otherwise, we probably need to have some kind of instruction changes like this:

**Replace `<VERSION>` with the correct version tag before adding to your document.** eg. 1.0.0-beta.60

```html
<script type="module" src="https://js.arcgis.com/calcite-components/<VERSION>/calcite.esm.js"></script>
<script nomodule="" src="https://js.arcgis.com/calcite-components/<VERSION>/calcite.js"></script>
```

**Comment by jcfranco** [comment]
> do you think we could have a URL on the CDN that redirects to the latest version like unpgk does?

I'll see if we can do the redirect option.

**Comment by driskull** [comment]
I'm second guessing that actually. As a best practice, we wouldn't want users to use the redirect since it could automatically break their apps. Maybe its best we have something that automatically updates the readme's?

**Comment by jcfranco** [comment]
True. Would there be any other case where we want the redirect-to-latest behavior from unpkg? 

Going back to the original request, I'll look at automating this on each release.

**Comment by driskull** [comment]
> Would there be any other case where we want the redirect-to-latest behavior from unpkg?

I'm not sure. I would say probably not.

**Comment by benelan** [comment]
Doesn't look quite right, I'm assigning it back to you @jcfranco
```css
<script
  type="module"
  src="https://unpkg.com/@esri/calcite-components@1.0.0-next.280/dist/calcite/calcite.esm.js"
></script>
<link
  rel="stylesheet"
  type="text/css"
  href="https://unpkg.com/@esri/calcite-components@1.0.0-next.280/dist/calcite/calcite.css"
/>
```

**Comment by jcfranco** [comment]
Installed!

**Comment by benelan** [comment]
verified in the readme after beta.64 released
