### ISSUE TITLE
Enhancement: match combobox w/o chip height to single selection-mode height

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2624]
### Description
When there is no chip selected in a combobox with selection-mode set to "multi" or "ancestors", the height should match its "single" selection-mode height (24px / 32px / 44px high per Figma designs).

~Additionally, a CSS transition of some sort should be added to accommodate the height change when an item is selected and the chip appears, and when the chip disappears after the selected item is removed from the combobox.~

### Acceptance Criteria 
1. The height of a "multi" or "ancestors" selection-mode combobox that has no item selected matches the height of a "single" selection-mode combobox.
2. ~When an item is selected and a calcite-chip either appears in (or is removed from) the combobox, a CSS transition makes the height change in a smooth fashion.~ (update 9/28: this will be re-evaluated down the road in a subsequent issue, if desired.)

### Relevant Info 
See #2359 for background discussion on this issue.

#### Which Component
calcite-combobox "multi" and "ancestors" selection-modes

#### Example Use Case
Current:
![image](https://user-images.githubusercontent.com/42423180/127032458-33fdb79e-680e-4877-913a-31bd11589a96.png)

New:
![image](https://user-images.githubusercontent.com/42423180/127032828-c50deeb2-f3b7-4550-a0cd-8d499ada3eb7.png)

**Comment by macandcheese** [comment]
@benelan @julio8a can we bump the priority of this? Should be an easy change.

**Comment by benelan** [comment]
@macandcheese moved to the backburner, which means you can grab it during any sprint that you have time

**Comment by macandcheese** [comment]
For posterity - I spoke with @anveshmekala regarding the `a CSS transition makes the height change in a smooth fashion.` portion of the OP - that can be re-examined if needed in a follow up issue.

**Comment by caripizza** [comment]
@macandcheese why not add a transition like this to the `.wrapper` class to accommodate the height change?

```scss
--calcite-animation-timing: 150ms;
  transition: padding var(--calcite-animation-timing) ease-in;
```

**Comment by macandcheese** [comment]
When the chips are appended they are placed without a transition so there's still a jump in height. I'm not sure if we'd want to delay that since the immediacy is nice.

I think the visual "jaggedness" (for lack of a better term, ha) is actually due to the "x" icon inside the chip appearing in slightly after the chip text - at least to my eyes.

**Comment by caripizza** [comment]
@macandcheese got it, thank you. I'll go ahead and nix the CSS portion from this issue.

**Comment by benelan** [comment]
verified locally on master
