### ISSUE TITLE
Bug: Add width property for dropdown button

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#2625]
When MV updated to Beta 60, the width of the dropdown shrunk. Beta.58 was fine.
![image](https://user-images.githubusercontent.com/50747646/127033418-a2d63562-3ddd-4d13-a237-4bc885d4e5c3.png)

Talked to @asangma and the change that caused this is here:
https://github.com/Esri/calcite-components/commit/cc8d424903a134227f40ecb91ce5ae5032ee5717#diff-717513f97b6ede6d16b1ad91d26a20deb137955e0743cfebf03b776d4c46a789L34

DropDown has a width property like Button does, but it applies to the actual dropdown part (not the button).

It could be fixed with a width property that controls the dropdown-trigger in the same way that Button's width does.

Button's width takes "auto" | "half" | "full".

or by reverting that change. 

cc @AdelheidF

**Comment by asangma** [comment]
I'm thinking we revert the change and make `calcite-dropdown-trigger-container` width: 100%.
This may still require the user to put something like `width:100%` on Dropdown but it will allow the user to accurately set the width on whatever is inserted into the `dropdown-trigger` slot.

Do you see an issue with that @driskull ?

**Comment by asangma** [comment]
On a separate note, it seems like the `width` property on Dropdown seems to be more inline with how we're using Scale in other components. Seems like we may want to rework this property here. 

In addition, the `width` property affects the content. Perhaps we should offload the content width control to the dropdown-item or dropdown-group?

**Comment by driskull** [comment]
I agree that it seems like the dropdown should just fill its space and let the user decide the max available width.

**Comment by asangma** [comment]
@zaramatheson Instead of adding a width property, I updated the component to better respect its container. User will still need to put something like a "width: 100%" style on CalciteDropdown, but once that is done, the user should be able to set the width on whatever is passed into the `dropdown-trigger` slot and that should work, e.g.

```html
<calcite-dropdown>
  <!-- note the width property on CalciteButton -->
  <calcite-button slot="dropdown-trigger" width="full">Selection mode example</calcite-button>
  <!-- DROPDOWN CONTENT -->
</calcite-dropdown>

**Comment by AdelheidF** [comment]
Looks good. Tested locally with next.262

![image](https://user-images.githubusercontent.com/44481292/128413243-90c38f9a-96ea-4970-bc76-e1d46b94ce5e.png)
