### ISSUE TITLE
Enhancement: calcite-card demo html update to achieve parity with Figma 

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2626]
### Description
This issue aims to achieve parity between the calcite-card following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-card design should encompass the Figma HTML demo page

### Relevant Info 
- It should have all the variants

#### Which Component
_calcite-card_

**Comment by ManahariDahal** [comment]
ready to verify @julio8a

**Comment by julio8a** [comment]
verified on master
