### ISSUE TITLE
Slider: Drag the bar

### ISSUE THREAD

**Issue by gavinr** [Esri/calcite-components#263]
In the [slider component](https://github.com/Esri/calcite-components/issues/4), it would be useful in many of my use cases to have the ability for the user to drag the entire slider (so the min/max endpoints move in parallel) like this:

![rangeslider](https://user-images.githubusercontent.com/209355/70826582-eb733d80-1dac-11ea-96b5-b3c8ddc1c6d0.gif)

**Comment by jwasilgeo** [comment]
👍 nice suggestion! Here's another sample out in the wild to draw inspiration from: https://refreshless.com/nouislider/behaviour-option/#section-drag

**Comment by jwasilgeo** [comment]
Another example: https://observablehq.com/@mootari/range-slider

**Comment by macandcheese** [comment]
An example of this in the new Map Viewer Beta (cursor becomes `ew-resize`, I believe): 

<img width="294" alt="Screen Shot 2020-01-23 at 3 09 12 PM" src="https://user-images.githubusercontent.com/4733155/73031938-6c811400-3df2-11ea-821c-af4cb0f124f0.png">
