### ISSUE TITLE
Enhancement: calcite-label demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2631]
### Description
This issue aims to achieve parity between the calcite-label following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-label design should encompass the Figma HTML demo page

### Relevant Info 
- It should have all the variants

#### Which Component
_calcite-label_

**Comment by julio8a** [comment]
verified on demo pages
