### ISSUE TITLE
Enhancement: calcite-link demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2632]
### Description
This issue aims to achieve parity between the calcite-link following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-link design should encompass the Figma HTML demo page

### Relevant Info 
- It should have all the variants

#### Which Component
_calcite-link_

**Comment by ManahariDahal** [comment]
@julio8a ready to verify!

**Comment by julio8a** [comment]
verified on master
