### ISSUE TITLE
Enhancement: calcite-popover demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2635]
### Description
This issue aims to achieve parity between the calcite-popover following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-popover design should encompass the Figma HTML demo page

### Relevant Info 
- It should have all the variants

#### Which Component
_calcite-popover_

**Comment by ManahariDahal** [comment]
Ready to verify!

**Comment by julio8a** [comment]
verified on master
