### ISSUE TITLE
Enhancement: calcite-tabs demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by maxdahal** [Esri/calcite-components#2640]
### Description
This issue aims to achieve parity between the calcite-tabs following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-tabs design should encompass the Figma HTML demo page

### Relevant Info 
- It should have all the variants

#### Which Component
_calcite-tabs_

**Comment by ManahariDahal** [comment]
ready to verify!
