### ISSUE TITLE
Enhancement: calcite-tooltip demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2642]
### Description
This issue aims to achieve parity between the calcite-tooltip following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-tooltip design should encompass the Figma HTML demo page

### Relevant Info 
- It should have all the variants

#### Which Component
_calcite-tooltip_

**Comment by ManahariDahal** [comment]
Ready to be verified!

**Comment by julio8a** [comment]
verified on master
