### ISSUE TITLE
Enhancement: radio button white background when unchecked

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#2659]
### Description

Unchecked radio buttons would have better contrast and IMHO look better with a white (or corresponding in dark theme) background like checkbox does.

![image](https://user-images.githubusercontent.com/14297903/127220040-3062b361-312d-4dfc-a210-fdbfc3fbf2c9.png)

Visually doesn't seem to match other controls.

#### Which Component

radio button

**Comment by jcfranco** [comment]
@Esri/calcite-design-representatives Can you chime in on this one? Seems like a low-effort one for this sprint.

**Comment by caripizza** [comment]
Agreed. I think we just need to add `bg-foreground-1` to the radio [on this line](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-radio/calcite-radio.scss#L4). Should we assign this one to Justin @julio8a?

**Comment by benelan** [comment]
I can't tell if the unchecked colors are the same in this sample:
https://codepen.io/benesri/pen/PojJbpw?editors=1000

@julio8a can you take a quick look? It may just be my eyes playing tricks on me due to the different outlines.

**Comment by julio8a** [comment]
I can verify this one, thanks Ben.

**Comment by julio8a** [comment]
Verified on master, demo pages.
