### ISSUE TITLE
Enhancement: Format total pagination count

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#2664]
### Description
Add commas to the total pagination count when pages exceed 1,000 to make the count more readable.

#### Which Component
`calcite-pagination`

#### Example Use Case
Representing thousands of items in a table view. The page count below should read "10,752".

<img width="1177" alt="Screen Shot 2021-07-28 at 12 10 26 PM" src="https://user-images.githubusercontent.com/55154968/127374471-e950a5bf-809b-4f74-8fba-5683bca11058.png">

**Comment by driskull** [comment]
I think we need to render all pages using Intl number formatting. That should solve this issue. 👍

**Comment by geospatialem** [comment]
Verified on next ✔️ 
![pagination with commas where thousand separators are used](https://user-images.githubusercontent.com/5023024/170135701-3b91c7a7-7025-49c8-b2c7-b95abb3b8d6a.png)
