### ISSUE TITLE
Bug: calcite-input with clearable + "enter" key = no value

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#2675]
### Actual Behavior

- Using the `clearable` attribute (or `type="search"`) will result in no value when using the "enter" key to submit a form.
- Input is cleared

### Expected Behavior

- Input value is submitted
- Input not cleared

### Reproduction Steps or Sample

Examples: https://codepen.io/gpbmike/pen/gOWzMOW

```html
<form>
  <calcite-input clearable />
  <button>Submit</button>
</form>
```

1. Add `clearable` or `type="search"` to `calcite-input`.
2. Submit form with "enter" key
3. Input value will be "".

### Relevant Info

I think the enter key is triggering the clearable button.

_Version_: `@esri/calcite-components@1.0.0-beta.60`

Example uses https://unpkg.com/@esri/calcite-components... which is both CDN and NPM package...

- [x] CDN
- [x] NPM package

**Comment by driskull** [comment]
This seems to be because the clear button is submitting the form. Adding `type="button"` to it fixes it. Probably need to do that for all buttons in this component.

Wouldn't be an issue if it were a shadowed component :)

**Comment by gpbmike** [comment]
This looks fixed to me on the codepen example (points to beta 61). I don't know what the process is for closing out issues.
