### ISSUE TITLE
Enhancement: calcite-action demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2686]
### Description
This issue aims to achieve parity between the calcite-action following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-action design should encompass the Figma HTML demo page

#### Which Component
_calcite-action_

**Comment by julio8a** [comment]
verified on demo pages
