### ISSUE TITLE
Enhancement: calcite-flow demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2688]
### Description
This issue aims to achieve parity between the calcite-flow following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-flow design should encompass the Figma HTML demo page

#### Which Component
_calcite-flow_

**Comment by julio8a** [comment]
verified on master
