### ISSUE TITLE
Enhancement: calcite-pick-list demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2690]
### Description
This issue aims to achieve parity between the calcite-pick-list following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-pick-list design should encompass the Figma HTML demo page

#### Which Component
_calcite-pick-list_

**Comment by julio8a** [comment]
verified on master
