### ISSUE TITLE
Tooling: error on fresh repo clone

### ISSUE THREAD

**Issue by ptmdmusique** [Esri/calcite-components#2697]
### Actual Behavior

I cloned the repo, then got error about `Plugin` after `npm install` then `npm start`. 
![image](https://user-images.githubusercontent.com/37349324/127921442-07f605bd-d089-4593-b0b4-e667af13410b.png)

I tried `npm run build` then it starts throwing Tailwind `@apply` error
![image](https://user-images.githubusercontent.com/37349324/127921465-2bb05ff8-b55c-48fe-9d99-17566e918eb4.png)

### Expected Behavior

No error, `npm start` should run correctly after `npm install` 

### Relevant Info

I'm using Windows

cc @paulcpederson

**Comment by caripizza** [comment]
Related: #1941

@ptmdmusique can you provide a) your system details and b) the version of node you used when you attempted the installs?

**Comment by ptmdmusique** [comment]
Hey @caripizza 

Here is my spec:
- Windows 10
- Node v14.17.0
- npm 6.14.13

**Comment by driskull** [comment]
Autoprefixer has its own types here: https://unpkg.com/browse/autoprefixer@10.3.1/lib/autoprefixer.d.ts

However, we still have a npm package for `@types/autoprefixer` which is deprecated. 

https://www.npmjs.com/package/@types/autoprefixer

Seems like we also need to update `postcss` or lock it to a version that works with `autoprefixer`. Currently, we just have `@stencil/postcss` installed. Ill submit a PR.

@jcfranco can I take this one? AKA triage this thang

**Comment by jcfranco** [comment]
@driskull Thang triaged, thanks!

**Comment by driskull** [comment]
I'm also seeing this on build:

```
[WARNING] calcite-filter is not referenced in stencil.config.ts and will not have a bundle generated
[WARNING] calcite-handle is not referenced in stencil.config.ts and will not have a bundle generated
```

Do we want to do these bundles @jcfranco ?

**Comment by jcfranco** [comment]
No, those aren't standalone components, so no bundle. 🚫 📦

**Comment by caripizza** [comment]
Thanks @jcfranco and @driskull! @ptmdmusique can you test drive beta.61 to see if this issue still occurs?

**Comment by caripizza** [comment]
Oops - I just noticed Matt's pr was merged after we released beta.61 last night, so this one will need to wait for 1.0.0-next.262 to test the fix.

**Comment by caripizza** [comment]
@ptmdmusique I'd like to close this one if we can - did the fix work for you? (Yesterday we released 1.0.0-next.266 so this one is ready to be verified.)

**Comment by ptmdmusique** [comment]
Hmmm, I think I still have the same error

**Comment by caripizza** [comment]
Bummer @ptmdmusique, thanks for the update. I'm not sure re: cache cleaning, however that error matches the one @ethanbdev reported in #1941 exactly. We'll keep this issue open while we continue to look into it.

**Comment by ethanbdev** [comment]
Yes, this is the same issue it looks like, thanks!

**Comment by benelan** [comment]
I have the same issue on Windows. I was able to get it working on WSL2 with Ubuntu 20.04 as a temporary workaround.

**Comment by driskull** [comment]
Is this still an issue with the bump to stencil 2.7.0?

**Comment by ethanbdev** [comment]
> Is this still an issue with the bump to stencil 2.7.0?

Not for me

**Comment by benelan** [comment]
Still an issue for me even with a fresh clone :( 
![image](https://user-images.githubusercontent.com/10986395/130832587-6d4fea2e-6415-404b-b911-0d015c56c7e6.png)

**Comment by ethanbdev** [comment]
Thanks for fixing this @paulcpederson! 🍻
