### ISSUE TITLE
Enhancement: calcite-list demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2703]
### Description
This issue aims to achieve parity between the calcite-list following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-list design should encompass the Figma HTML demo page

#### Which Component
_calcite-list_

**Comment by ManahariDahal** [comment]
ready to verify!

**Comment by julio8a** [comment]
verified on master
