### ISSUE TITLE
Enhancement: calcite-split-button demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2712]
### Description
This issue aims to achieve parity between the calcite-split-button following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- calcite-split-button design should encompass the Figma HTML demo page

### Relevant Info 
- should have all the variants

#### Which Component
_calcite-split-button_

**Comment by ManahariDahal** [comment]
@julio8a ready to verify!

**Comment by julio8a** [comment]
verified on master
