### ISSUE TITLE
Bug: calcite-select with long string is cut off

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2714]
### Actual Behavior

If a selected string inside a `calcite-select` is very long the string is just cut off. Could it add ellipses?

![image](https://user-images.githubusercontent.com/44481292/128094483-b77caadd-a649-4f97-bb6b-7496c2aa3dbb.png)

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by driskull** [comment]
@jcfranco can we triage this for this milestone?

**Comment by jcfranco** [comment]
Added to this sprint. I assigned to you since you're already working on it.

**Comment by AdelheidF** [comment]
I don't see a change with next.262

![image](https://user-images.githubusercontent.com/44481292/128414473-e2f6047a-191a-47d1-ad97-57f4ee1d8d50.png)

**Comment by driskull** [comment]
Did you update the CSS?

**Comment by AdelheidF** [comment]
It was merged around 4pm, and next.262 is from 11am. There is no next.263 yet

**Comment by AdelheidF** [comment]
Good with next.263

![image](https://user-images.githubusercontent.com/44481292/128422766-8db529d0-fb8d-4ac0-be97-acf0af3c4815.png)
