### ISSUE TITLE
Bug: calcite-stepper-item container margin

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#2715]
### Actual Behavior
The `<div/>` with class `container` within the `calcite-stepper-item` component has margin-bottom. Because the margin is being applied to an element within the `calcite-stepper-item` and not to the item itself, the hight of the item is being messed up. 

This isn't a big issue other than its effects of the focus-border of the `calcite-stepper-item`. As you can see from the screenshot below, the focus-border of the item overlaps the other items. 
<img width="1169" alt="Screen Shot 2021-08-03 at 4 03 27 PM" src="https://user-images.githubusercontent.com/55154968/128095015-cbed07f7-36ad-4c4b-a75b-acdf315a684c.png">

### Expected Behavior
The margin-bottom should be applied to the `calcite-stepper-item`. This change will prevent the focus-border from overlapping the other items. 

<img width="1173" alt="Screen Shot 2021-08-03 at 4 38 04 PM" src="https://user-images.githubusercontent.com/55154968/128095265-f2605593-d14c-45d3-9f90-56f247a8f8ea.png">

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.58`

- [ ] CDN
- [x] NPM package

**Comment by benelan** [comment]
verified on master
