### ISSUE TITLE
Bug: calcite-popover close-button partially hidden

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2720]
### Actual Behavior

wrong:
![image](https://user-images.githubusercontent.com/44481292/128097680-edaccb5c-f38a-4378-8725-92d2a915ebc8.png)

correct:
![image](https://user-images.githubusercontent.com/44481292/128097707-b16f7c84-8e90-49ff-ac8d-276878112ed8.png)

![image](https://user-images.githubusercontent.com/44481292/128097912-a55a4ad8-26df-4b1a-9fac-602a6d2dbaae.png)

![image](https://user-images.githubusercontent.com/44481292/128097950-ef180682-6221-47b8-b4c8-868c230f56b8.png)

I think it has something to do with the exact length of the title string 'Verwendung von A mit B vergleichen'.

Reproducible in Chrome, FF, Safari, Edge Chromium

------------------
from @driskull 
putting an overflow:hidden on the shadowRoot .content div seems to fix it

### Reproduction Steps or Sample

https://codepen.io/afreitag/pen/RwLrvKe?editors=1000

### Relevant Info

_Version_: `@esri/calcite-components@next.261`

- [ ] CDN
- [ ] NPM package

**Comment by driskull** [comment]
Note:

[4:11 PM] Matt Driscoll
    putting an overflow:hidden on the shadowRoot .content div seems to fix it
​[4:11 PM] Matt Driscoll
    Seems like a component issue. Its missing some styles to handle a bunch of text content I think

**Comment by benelan** [comment]
Hi @AdelheidF, I have been [unable to repro](https://codepen.io/benesri/pen/GRMoYgY?editors=1000) this issue in codepen, can you give it a try? It may be related to something else in your code besides the `heading` length.

**Comment by AdelheidF** [comment]
https://codepen.io/afreitag/pen/RwLrvKe?editors=1000

**Comment by jcfranco** [comment]
Verified with [updated codepen](https://codepen.io/jcfranco/pen/MWEVygX?editors=1000)!
