### ISSUE TITLE
Tooling: "Unchanged files with check annotations" failures on pr builds prevents merge

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2724]
### Background 
Our current pr build checks include an "Unchanged files with check annotations" beta GitHub feature that will show a security warning tied to a file that wasn't changed in the pr. Here's an example from pr #2502, showing a build check failure due to a "Shell command built from environment values" issue in support/prepReleaseCommit.ts:

![image](https://user-images.githubusercontent.com/42423180/128213437-a8e9d0b0-24cc-4bba-90b9-8dbd02da55a6.png)

Admins on the team can click "Dismiss" to get rid of the message, or "Show paths" to see code tied to the error:

![image](https://user-images.githubusercontent.com/42423180/128215398-2020e32d-2c51-40d2-b215-37ce5cc0109f.png)

### Desired Outcome 
Not sure what is best. I think ideally the check would only appear for GitHub admins, and not run on prs with unrelated file changes.

**Comment by jcfranco** [comment]
Installed! 

If this shows up again, I can try something similar to [this](0e60ba9195c63b98d46b26264f3e99058617b7c9) where arguments are passed individually to the command runner.

**Comment by jcfranco** [comment]
Before that, another option would be to quote all commands, like this blog post suggests: https://auth0.com/blog/preventing-command-injection-attacks-in-node-js-apps/

**Comment by caripizza** [comment]
Verified, the [security alert](https://github.com/Esri/calcite-components/security/code-scanning/5?query=ref%3Arefs%2Fheads%2Fmaster) shows it was fixed in Franco's commit here: https://github.com/Esri/calcite-components/commit/a69e2783a33d0506cde5a3d7a2f86904db89ddcd
