### ISSUE TITLE
Unstable Test: combobox

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2727]
## Summary

**Which component?:**
`Combobox`

**Which test(s)?:** 
`src/components/calcite-combobox/calcite-combobox.e2e.ts`

**Test error:**
```
 FAIL  src/components/calcite-combobox/calcite-combobox.e2e.ts (31.788 s)
  ● calcite-combobox › single select › should allow selection of single item
    TypeError: Cannot read property 'isVisible' of null
      666 |       const label = await page.find("calcite-combobox >>> .label");
      667 |       await page.waitForChanges();
    > 668 |       const labelVisible = await label.isVisible();
          |                                        ^
      669 |       expect(labelVisible).toBe(true);
      670 |       expect(label.textContent).toBe("One");
```

**PR that skipped the test:** #2710 
PR still pending design and code review

## Additional Info 
Inline changed to block

**Comment by driskull** [comment]
@julio8a i'm not seeing any skipped test from that PR

**Comment by caripizza** [comment]
^ agree with @driskull  - @julio8a I'm going to close this one but please re-open if I missed something here.
