### ISSUE TITLE
Bug: calcite-list no longer as wide as panel

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2729]
calcite 2 weeks ago:

![image](https://user-images.githubusercontent.com/44481292/128258186-39d38b86-5d01-4e2d-8783-77c6cad70816.png)

calcite next.261:

![image](https://user-images.githubusercontent.com/44481292/128258256-56545284-7941-4b44-854e-ae69663339b5.png)

If I uncheck `display:flex` here it's fine.

![image](https://user-images.githubusercontent.com/44481292/128258529-1b51887a-9a15-4c1a-b680-3eee3b487e5d.png)

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by asangma** [comment]
@caripizza Gonna punch this one out.

**Comment by driskull** [comment]
👊

**Comment by AdelheidF** [comment]
Looks good. Tested locally with next.263.
