### ISSUE TITLE
Bug: Block heading color is wrong on idle

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2735]
### Actual Behavior
heading text is ui-text-3 at idle
![image](https://user-images.githubusercontent.com/14083530/128267384-17c586c5-51a4-4f74-8849-4506fa6cf2cd.png)

### Expected Behavior
heading text should be ui-text-1 at all times
![image](https://user-images.githubusercontent.com/14083530/128267334-818f069a-7cba-4c6f-acc5-925a062c651b.png)

**Comment by julio8a** [comment]
Verified on master
