### ISSUE TITLE
Bug: calcite-input no longer has the same height as calcite-action

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2736]
With next.261. It was fine with beta.60.

`calcite-input` and `calcite-action` have both `scale=s`.

![image](https://user-images.githubusercontent.com/44481292/128270046-9c3f2712-6b03-4e3e-8444-72c68753673e.png)

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by bstifle** [comment]
@asangma currently the actions are at 32px, 48px, 64px.

Would you be down with getting actions down to 24, 32, 44 like buttons, inputs, selects, etc?

**Comment by julio8a** [comment]
Why would they not follow the height scale from all other components?

**Comment by julio8a** [comment]
If there are no objections with updating the heights of `calcite-action`: S (24px) , M (32px), and L (44px) we can have this one updated this sprint by prioritizing `calcite-action` Figma/tailwind refactor. Will wait until 8/9 for feedback/comments on this.

**Comment by asangma** [comment]
@bstifle will need to see how that affects..kinda everything.

It would have broad effects in existing implementations.

As a note, when Action is not showing text and is just the icon, medium would be 32x32 which I believe is smaller than suggested mobile touch size.

It's also pretty small hit areas for widely separated interfaces like left and right action-bars.

**Comment by bstifle** [comment]
@asangma agreed. pretty much all the layout components utilize action.

another way around this would be to not use actions in tandem with inputs, per the OG issue. use a native button and style accordingly

**Comment by AdelheidF** [comment]
> another way around this would be to not use actions in tandem with inputs, per the OG issue. use a native button and style accordingly

This is a breaking change for a bunch of our components.

**Comment by AdelheidF** [comment]
What about adding a size XS for `calcite-action` that would then match calcite-input? Still a breaking change, but at least it's easy to fix.

**Comment by macandcheese** [comment]
Couldn't actions that are slotted in those locations just use scale="l", just a 4px change from current?

**Comment by asangma** [comment]
I see two things going on here.

1. We could add styles in Input to target a slotted Action or Button.
  - we do this is other places effectively
2. Input currently sets heights based on scale. We should consider letting the height be defined by the font sizes and padding.
3. We can also update Input styling to be more responsive to its slotted content.

**Comment by asangma** [comment]
Note that 1. is probably the  simplest approach though I think 2. should be considered at some point as a separate discussion. And 3. is probably a broader philosophical suggestion toward more flexible componentry.

**Comment by AdelheidF** [comment]
Solving this issue now by applying a height of 24px to the action to make it match the input.
