### ISSUE TITLE
Bug: histogram vertical lines are disconnected from slider handles

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2739]
### Actual Behavior

the verticle white lines are way off from the handle
![image](https://user-images.githubusercontent.com/14083530/128290131-ef570858-e782-4144-b203-56f93580d35d.png)

![image](https://user-images.githubusercontent.com/14083530/128289664-191b4d54-d8cd-42b7-b120-1b3d4c2c0357.png)

### Expected Behavior

 The vertical white lines should follow with the handles (like they are connected to them)
![image](https://user-images.githubusercontent.com/14083530/128289783-bfd29f27-e94e-4d96-bbc3-c80dc669433e.png)

**Comment by julio8a** [comment]
closing in favor of #2569
