### ISSUE TITLE
Bug: missing vertical scroll bars in panel with use of custom elements, calcite-match-height not working

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2741]
-> Make `calcite-match-height` work inside of Flow. 

Missing vertical scroll bars
![image](https://user-images.githubusercontent.com/44481292/128368679-5f747e2c-46b8-4bac-8ddf-2881ade1999c.png)

![image](https://user-images.githubusercontent.com/44481292/128368757-77fa400d-2f7e-4d4e-932d-b5a6dfb678ce.png)

If I add this to the custom element it's fine
```
display: flex;
overflow: hidden;
flex: 1 1 auto;
```
### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by asangma** [comment]
@AdelheidF I made it so `calcite-match-class` is now available in CalciteFlow. Let me know this helps.

**Comment by AdelheidF** [comment]
`calcite-match-height` works great now. Thanks.
