### ISSUE TITLE
Enhancement: remove clear and transparent appearances from FAB

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2744]
### Description
remove clear and transparent appearances from FAB. They don't belong on the Depth level that FAB lives on. The level 2 shadow interferes with the design of those appearances as well.

### Acceptance Criteria 

remove clear and transparent appearances 

#### Which Component
FAB

**Comment by caripizza** [comment]
Adding this one to the button refactor per team conversation

**Comment by julio8a** [comment]
verified on master
