### ISSUE TITLE
Bug: Calcite-popover content resize causes incorrect popover positioning

### ISSUE THREAD

**Issue by samMatenaer** [Esri/calcite-components#2751]
￼
### Actual Behavior
Before:
![image](https://user-images.githubusercontent.com/50883428/128427006-5e0cafe9-f7ee-4298-9f58-5bf348cad602.png)

After:
![image](https://user-images.githubusercontent.com/50883428/128427030-7f4d2a17-4d64-449e-8e30-1317c4bc8205.png)

When popover-placement is centered below the reference element and the size of the popover content changes, the popover position is not updated to center below the ref element
### Expected Behavior
![image](https://user-images.githubusercontent.com/50883428/128427209-6f6c1dda-ba61-4fbc-971b-fa4580e4ed0d.png)

### Reproduction Steps or Sample

Codesandbox example:
https://codesandbox.io/s/wonderful-hellman-yi33t?file=/index.html

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.61`

- [x] CDN
- [x] NPM package

**Comment by driskull** [comment]
We can setup a mutation observer and call resize. @jcfranco should we prioritize this for this sprint or not?

**Comment by driskull** [comment]
On the other hand, the user that modified the popover can just call resize on it as well. So just a matter of if we want to automatically do it for them using mutation observer

**Comment by driskull** [comment]
@samMatenaer this fixes it. 

```js
document.getElementById('displayText').innerHTML = 'uh oh';
document.querySelector('calcite-popover').reposition();"
```

**Comment by samMatenaer** [comment]
@driskull thanks, that's actually what i have been using to get around this problem; my code is a little more complicated than the example so it ends up just feeling a little messy.

**Comment by driskull** [comment]
I don't think we should do anything here. Any objections to closing?
