### ISSUE TITLE
Change color of calcite-icon

### ISSUE THREAD

**Issue by rslibed** [Esri/calcite-components#276]
Is there a way to change the color of the icon other than using the `theme` property? i.e. Update the icon color by using a hexadecimal or RGBa value?

**Comment by macandcheese** [comment]
Hi @rslibed - Adding a custom class and associated style should work:

`<calcite-icon class="my-icon-color-class" icon="arrowBoldLeft"></calcite-icon>`

```
.my-icon-color-class {
  color: red;
}
```

We can do a better job of documenting that - and are open to suggestions if you have a more elegant solution in mind!

**Comment by rslibed** [comment]
Ah yes that works. I was previously using SVGs instead of the `calcite-icon` component. And I was updating the color of the SVG with the css fill property so I was assuming that the fill property had to be used with the `calcite-icon` component. Closing the issue.

**Comment by macandcheese** [comment]
Yeah the svg here is rendered as a child element with 'fill : currentColor' that inherits from the styles set on the parent 'calcite-icon' - as you mentioned, that's a little unexpected so I added a quick doc in a PR for others who run into this. Thanks!

**Comment by AmroOsama** [comment]
is this possible with calcite-action?

**Comment by AmroOsama** [comment]
To do the same with calcite-action that has an icon property
<calcite-action class='my-icon-color-class' icon='arrowBoldLeft'></calcite-action>

.my-icon-color-class{
  --calcite-ui-icon-color: red;
}
