### ISSUE TITLE
Bug: calcite-input type="number" step="any" doesn't support decimals

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#2764]
### Actual Behavior

Decimals cannot be entered when a number calcite-input's step is set to "any".

### Expected Behavior

Decimals are supported with the "any" step in the native number input, so calcite-input support the same.

### Reproduction Steps or Sample

```
<calcite-input type="number" step="any"></calcite-input>
```
1. Type `123.45`
2. Result: decimal is ignored

### Relevant Info

@eriklharper I am seeing that with `step="any"` a decimal also cannot be inputted. This doesn't seem right, what is intended?

https://codepen.io/mpayson/pen/XWRxXBr

_Originally posted by @ethanbdev in https://github.com/Esri/calcite-components/issues/2009#issuecomment-893678716_

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by AdelheidF** [comment]
In what sprint will this be? Map Viewer is waiting on it because we can't upgrade from beta.60 without it.

cc @jcfranco @julio8a

**Comment by jcfranco** [comment]
@eriklharper What's your estimated level of effort for this?

**Comment by eriklharper** [comment]
> @eriklharper What's your estimated level of effort for this?

That should be a fairly quick turnaround, maybe a day or two?

**Comment by jcfranco** [comment]
@eriklharper Thanks! Added to the current sprint, although it may roll over to the next one. Can you update the issue title and description to match our templates?

**Comment by ethanbdev** [comment]
LGTM on next, https://codepen.io/mpayson/pen/XWRxXBr

**Comment by jcfranco** [comment]
@eriklharper Thanks for tackling this and thanks to @ethanbdev for verifying!
