### ISSUE TITLE
Enhancement: make calcite-tooltip delay customizable

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-components#2778]
### Description

In certain cases the tooltips can be very easy to miss due to the long delay of 500ms. It would be nice to be able to customize the delay.

If we don't want to allow specifying the delay in milliseconds, we could support `fast`, `slow`, `none` or something similar.

Thoughts?

<sub>SVCH</sub>

**Comment by julio8a** [comment]
Yes, this will be a good enhancement. I've noticed this too when hovering over elements with tooltips. Sometime I look somewhere else and notice that the tooltip shows up. Franco and I will triage this.

**Comment by hccampos** [comment]
Great! Then I can probably contribute a PR for this, if you don’t get to it before. Just let me know once it’s ready for development/triaged.

**Comment by driskull** [comment]
If you can create a PR that would be great!

**Comment by yannikmesserli** [comment]
Part of the same integration that triggers this feature request, SV also used to hide certain tooltips when the mouse was over. E.g. in this situation, the tooltip goes over the close button, so the user would be annoyed to move away to get to the button:
![2021-08-13 12 20 31](https://user-images.githubusercontent.com/1910449/129343052-8be0e287-6f20-436a-bb68-34405594d5b3.gif)

Can we also add a new option in the tooltip to hide on mouse over? e.g. `hideOnOver={true}` or something similar?

**Comment by driskull** [comment]
Yeah could we get a separate issue for that?

**Comment by hccampos** [comment]
@yannikmesserli that one isn't really an issue. It is happening because we're placing the tooltip inside of the menu item. If the tooltip is placed outside (e.g. as a sibling) then the tooltip does get hidden when moving the mouse away from the menu item.

**Comment by geospatialem** [comment]
Closing in favor of https://github.com/Esri/calcite-components/issues/6396
