### ISSUE TITLE
refactor(Action Pad): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2781]
5/19 QA: visual design looks good based on what Cari and Bryan see in Figma

8/10: Needs S and L scale

Related prs:
- pr #1816

Figma designs: https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/?node-id=1184%3A6690

**Comment by asangma** [comment]
ActionPad doesn't support scale.

**Comment by asangma** [comment]
I don't think it needs scale.
It's a container for Actions and/or ActionGroup, and Action has scale. ActionPad is responsive to its content.

**Comment by asangma** [comment]
> breaking behaviour due to the attached/included action for expand/expand.

Got it. This is a much more specific issue. It probably shouldn't be considered a scale setting for ActionBar.
We might consider something like an `expand-button-scale` property.

@driskull thoughts on that naming?

**Comment by driskull** [comment]
Yeah this is tricky because `action`s can be child elements as well as stand alone elements. 

So, we could have a scale on the action-bar/pad but then it would override the scale on action. The `action-bar` expanded property does this for `text-enabled`.

**Comment by asangma** [comment]
Thinking the property would just affect the expand button that ActionPad is responsible for inserting.

**Comment by driskull** [comment]
We could go either way but we should decide if scale should be a thing a user sets on a parent or child component. It would be more convenient to just set it on the parent once and not have to set it on every child.

**Comment by julio8a** [comment]
I think it's best to set it at the parent. Seems like it can be a hassle to set it to all the children. It's easier with one and done.

**Comment by asangma** [comment]
Have we established a pattern/philosophy on cascading properties in our components?

**Comment by asangma** [comment]
> we should decide if scale should be a thing a user sets on a parent or child component.

My though on this is that if the parent is rendering the children and can set the `scale` properties on each of those children (e.g. DatePicker), then the property should cascade.

If the children are being written in by the app, each `scale` prop should be set during that process.

Seems like the `scale` property should affect the scale of the thing the property is being set on.

As far as convenience, setting/updating props across multiple actions, this seems like something that would be handled expertly at the user-level and/or by the convenience features in an editing app.

_As a note, I did a quick unofficial audit of how `scale` is being loosely cascaded in some of our components, and at the moment there are a few different approaches with varying results. The most consistent and easily understandable approach appears to be the one used in DatePicker (and its child DatePickerMonth)._

**Comment by driskull** [comment]
What we want to avoid is having an action-bar with actions that have different scales. So to me it seems like the action-bar should enforce that.

**Comment by asangma** [comment]
Seems like an educational approach should help with that.

If anything though, seems like ActionGroup would be the appropriate place to implement a cascading `scale` property.

**Comment by julio8a** [comment]
verified on demo pages
