### ISSUE TITLE
Enhancement: calcite-radio-button-group demo html update to achieve parity with Figma

### ISSUE THREAD

**Issue by ManahariDahal** [Esri/calcite-components#2789]
### Description
This issue aims to achieve parity between the `calcite-radio-button-group` following the similar layout on the Figma HTML Demo page and any usage snippets we provide.

### Acceptance Criteria 
- `calcite-radio-button-group` should be isolated from other radio component to make it easier to test

#### Which Component
`calcite-radio-button-group`

**Comment by julio8a** [comment]
verified on demo pages
