### ISSUE TITLE
Enhancement: Scrim - render default slot

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2801]
### Description
Render default slot in Scrim.
This will allow users more flexibility for loading, success, error, etc. states and messages.

```
<calcite-scrim>
  <calcite-notice color="red">
    <h4 slot="title">Something went wrong.</h4>
    <p slot="message">The vuvuzella did not honk to the required volume.</p>
    <a href="vuvuzella-technique.com" slot="link">Learn how to make it loud.</a>
  </calcite-notice>
</calcite-scrim>
```

### Acceptance Criteria 
* Render the default slot.
* Add CSS to retain some padding around anything that is added to the default slot
* Possibly also add some CSS for some reasonable/expected content, e.g. Notice or "modal" like use-cases

### Relevant Info 
Sometimes the Alert is not the right solution. Especially since it has a pre-defined (and appropriate) app-level message.

#### Which Component
Scrim

#### Example Use Case
Using a determinate loader in a scrim.

![image](https://user-images.githubusercontent.com/12503298/129755441-7b0938c3-7e95-4f25-bffd-74b54c723633.png)

**Comment by asangma** [comment]
Another example use case would be

1. either set `loading` to a Panel or manually add Scrim to the Panel
2. when the process is done, show status (error or success), remove `loading` prop from Panel or Scrim
3. add Notice to Scrim
4. based on timing set in app, remove Scrim.

**Comment by asangma** [comment]
@jcfranco @caripizza This might be needed/helpful relatively soon and the update is low effort and low risk.

**Comment by jcfranco** [comment]
Added to the following sprint.

**Comment by asangma** [comment]
Thanks @jcfranco!

**Comment by asangma** [comment]
Do you want me to handle the PR?

**Comment by jcfranco** [comment]
That'd be awesome. Feel free to grab it and remove the `help wanted` label. :)

**Comment by asangma** [comment]
Will do.

**Comment by julio8a** [comment]
Before moving forward, we should have a design discussion around this.

**Comment by jcfranco** [comment]
@julio8a Sounds good. Sorry for overlooking that step. 😅

**Comment by asangma** [comment]
@julio8a There's not really a design since it's an empty slot.

But for a design review, I would dig syncing with @bstifle on default padding for when a user drops in a known component.

**Comment by julio8a** [comment]
Can a user drop anything in there? Seems like we're opening up some bad UX practices on this. Can they drop an accordion in there with content or any other component?

Wondering if there's something more controlled for messaging in this environment. 

@macandcheese @bstifle what do you guys think about this one?

**Comment by asangma** [comment]
It's a default slot, so they can drop "anything" in there.
It definitely seems weird if we come up with weird examples.
But consider useful examples like the updated one above.

Keep in mind that 

- we want to avoid property bloat
- best practices are less about limitation and more about education
- healthy flexibility is key to componentry success

**Comment by macandcheese** [comment]
Some thoughts...

Having a "loading" prop on calcite-scrim and then still needing to have a way to slot a calcite-loader component seems like a fractured story. One or the other yeah?

The screenshot originally shown in the OP was (IMO) an example of something we would never want people to do - have a user leave a non-interactive loading state, only to present them with blocked interactive controls behind a non-dismissible slotted-in-scrim notice. 

That said, I think there are some useful opportunities for this type of display... in the past we've seen requests for the ability to place a "Confirmation icon, helper text, and "return to workflow CTA"" over top of a popover, modal, etc., and in those cases it seems reasonable to use scrim in this way. 

I think it's a large risk but if it's an absolute requirement for MVB perhaps we could add and lightly document some guardrails.

**Comment by asangma** [comment]
Thanks for the feedback @macandcheese.
While I have a different opinion on the scale of the risk, I do agree it's a risk. 

And as you said, we have requests for this and rendering the default slot will address those requests.

And indeed, some documentation is called for.

Discussed the general UX of this and aligned on some light styling with @bstifle and will demonstrate in an upcoming PR.

cc @AdelheidF

**Comment by bstifle** [comment]
Mr. @asangma and I chatted through some design specs with scrim. The idea is to get a simple cushion of padding (1 rem) all around so anything that gets slotted in has some breathing room. The other change would be to up the opacity on the scrim itself, since right now the opacity on top of a busy panel makes things like determinate loader pretty hard to read

**Comment by bstifle** [comment]
FWIW IDT the risk is a big one either. Some interesting concepts can be achieved with a "locked" content area or things like that... not tied to loading only

**Comment by AdelheidF** [comment]
> The screenshot originally shown in the OP was (IMO) an example of something we would never want people to do - have a user leave a non-interactive loading state, only to present them with blocked interactive controls behind a non-dismissible slotted-in-scrim notice.

There are cases where we need to block interaction when loading a panel. We currently can't stop the process (e.g. generating SmartMapping renderers) that's going on in the background.

**Comment by macandcheese** [comment]
> There are cases where we need to block interaction when loading a panel. E.g. we currently can't stop the process of generating SmartMapping renderers that's going on in the background.

That is totally fine... The original screenshot (no longer there) showed a scrim with a notice inside with no way to dismiss it.

**Comment by asangma** [comment]
> The original screenshot (no longer there) showed a scrim with a notice inside with no way to dismiss it.

It's like there was a reason I deleted it. 😆

**Comment by asangma** [comment]
@jcfranco @caripizza May I pass this to you to assign a verifier?

**Comment by jcfranco** [comment]
@asangma I'll verfee!

**Comment by jcfranco** [comment]
Verified w/ https://codepen.io/jcfranco/pen/abwZwLr?editors=1000

@asangma Sidebar, the scrim's default slot should used specifically for the overlay, but not to place the main content, right?

```html
<!-- container --> 
<div>
  <!-- overlay -->
  <calcite-scrim></calcite-scrim>

  <!-- underlay -->
  <div>content</div>
</div>
```

```html
<!-- container --> 
<div>
  <!-- overlay -->
  <calcite-scrim>
    <div>overlay content</div>
  </calcite-scrim>

  <!-- underlay/content -->
  <div>content</div>
</div>
```

If so, I think it'd be useful to add the content nodes in the usage examples to make it a bit clearer: https://esri.github.io/calcite-components/?path=/docs/components-scrim--simple cc @benelan
