### ISSUE TITLE
Bug: z-index is leaking out and causing conflicts

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2806]
From https://github.com/Esri/calcite-components/pull/2650#issuecomment-898580756

cc @bstifle 

### Actual Behavior
Some components have z-index conflicts.

- [ ] DatePicker
- [ ] Slider
- [ ] ColorPicker
- [ ] ComboBox
- [ ] Dropdown
- [ ] Input
- [ ] InputDatePicker
- [ ] Popover
- [ ] Scrim

@bstifle Please ensure that these are all the places you're seeing the issues. 

### Expected Behavior
No z-index conflicts.

Also add z-index tests
- [ ] add DatePicker z-index test
- [ ] add Slider z-index test
- [ ] add ColorPicker z-index test
- [ ] add ComboBox z-index test
- [ ] add Dropdown z-index test
- [ ] add Input z-index test
- [ ] add InputDatePicker z-index test
- [ ] add Popover z-index test
- [ ] add Scrim z-index test

### Reproduction Steps or Sample

1. View listed demo pages above.
2. Scroll until a component overlaps with demo header which is `sticky`

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by asangma** [comment]
@driskull 

> The components that are going over the header need to have a position:relative on their host most likely. Their zIndex shouldn't be leaking out.

The work that @ManahariDahal is doing presents some consistent DOM and CSS classes that can be used to help with this. 🤞🏾

**Comment by driskull** [comment]
@asangma but these aren't issues with the demo pages, they are issues with the components themselves. A user could run into this as well.

**Comment by asangma** [comment]
@driskull Ah. Understood. I'll update the issue.

**Comment by driskull** [comment]
We may need to setup some kind of test for this.

For example, having a div with a `z-index:2` and a component where they are both absolutely positioned at `top:0; left:0;`. The component should never be on top of the div.

This would test that any internal z-index used within the component is constrained within the component using `position:relative`. 

No more leaky z-index issues.

@jcfranco what do you think?

**Comment by driskull** [comment]
For example, if you add a `z-index:1` on the `.conatiner` of `calcite-slider` it is fixed.

**Comment by jcfranco** [comment]
Agreed, making sure that the root container (not host) creates a stacking-context is the way to go. I'll see if there's a way we can add a lint rule for this and avoid checking at test time.

Apologies for the delay.

**Comment by driskull** [comment]
Not sure if this one should be pre 1.0 @jcfranco @benelan

**Comment by jcfranco** [comment]
I stumbled on this one after working on #5058 and I think the proposed solution won't work as expected because of our `floating-ui` usage. Creating a stacking context per component means that all z-layer ordering is contained and makes it trickier to fix cases where you need to escape (see https://codepen.io/jcfranco/pen/gOeXVLB?editors=1010). I now think that the way to go is to define and use z-index layers across components and document these for devs to layer accordingly.

**Comment by benelan** [comment]
linking to #4372

**Comment by jcfranco** [comment]
Closing as this was addressed by #4372.
