### ISSUE TITLE
Docs: Consistent slot documentation

### ISSUE THREAD

**Issue by samMatenaer** [Esri/calcite-components#2807]
### Description 
All the available slots in the Panel component are documented in a Slots list in the [documentation](https://esri.github.io/calcite-components/?path=/docs/components-panel--basic).

However, for components like Card [don't have a similar list](https://esri.github.io/calcite-components/?path=/docs/components-card--simple), making it difficult to find available slots

List of components with slots documentation:
- [Alert](https://esri.github.io/calcite-components/?path=/docs/components-alert--title-message-link)
- [Flow](https://esri.github.io/calcite-components/?path=/docs/components-flow--basic)
- [Shell](https://esri.github.io/calcite-components/?path=/docs/components-shell--basic)
- [Tip](https://esri.github.io/calcite-components/?path=/docs/components-tips-tip--basic)
- [Popover](https://esri.github.io/calcite-components/?path=/docs/components-popover--simple)
- [Notice](https://esri.github.io/calcite-components/?path=/docs/components-notice--simple)

List of components without (complete) slots documentation
- [Card](https://esri.github.io/calcite-components/?path=/docs/components-card--simple)
- [Modal](https://esri.github.io/calcite-components/?path=/docs/components-modal--simple)
- [List Item](https://esri.github.io/calcite-components/?path=/docs/components-list--simple)
- [Pick List Item](https://esri.github.io/calcite-components/?path=/docs/components-pick-list--basic)
- [Value List Item](https://esri.github.io/calcite-components/?path=/docs/components-value-list--basic)
- [Tree](https://esri.github.io/calcite-components/?path=/docs/components-tree--simple)
- [Tabs](https://esri.github.io/calcite-components/?path=/docs/components-tabs--simple)

**Comment by benelan** [comment]
List Item, Pick List Item, and Value List Item all have the proper jsdoc slot tags in the code. The issue with those components is that they are not documented at all in storybook under their parents. I created a different issue to fix that: #2887. The rest of the missing slots are added in #2888.

**Comment by jcfranco** [comment]
@benelan Aside from `calcite-tree` and `calcite-tree-item`, everything looks good!

* `calcite-tree` – has a default slot, but doc has `children` slot
* `calcite-tree-item` – has default and `children` slot, but doc has none

**Comment by benelan** [comment]
Thanks @jcfranco, should I be documenting default slots by the way? Mat was wondering that too cc @driskull

**Comment by jcfranco** [comment]
I think it makes sense to do so. Otherwise, there's no way to find out if any user-content will be displayed or not.

**Comment by driskull** [comment]
Also, I think in the future we could have a custom JSDoc tag for whether a component allows slotting elements inside and maybe a link to see the usage doc.

**Comment by benelan** [comment]
@jcfranco, @julio8a, ready for verification!

**Comment by jcfranco** [comment]
Verified locally!

**Comment by caripizza** [comment]
Can we add documentation for stepper/stepper-item's slots too?
