### ISSUE TITLE
 refactor(Rating): match Figma and utilize Tailwind

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#2810]
Related issues:
- #2041

Related prs:
- pr #1638
- or #2220

Design:
- 24, 32, ~~48~~ 44 height without chips

**Comment by justinhough** [comment]
@julio8a I thought large was `44px`.

**Comment by julio8a** [comment]
Whoops, Yes, typo on my part, I'll update description.

**Comment by julio8a** [comment]
Verified on master demo pages
