### ISSUE TITLE
Bug: calcite-action-menu does not seem to honor its `expanded` attribute

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#2813]
### Actual Behavior

When using a `calcite-action-menu` within a `calcite-action-bar` it should honor the `expanded` attribute, but it instead mirrors what the expand attribute is on the `calcite-action-bar`.  If the actionBar is not expanded the actionMenu will not be expanded even though the `expanded` attribute is set on the `calcite-action-menu`.

### Expected Behavior

`calcite-action-menu` should honor the expanded attribute

### Reproduction Steps or Sample

https://codepen.io/kevindoshier/pen/yLbwWpj

![image](https://user-images.githubusercontent.com/11093161/129422159-3dbfd9e0-ba89-429b-8b97-cec73d3c5626.png)

![image](https://user-images.githubusercontent.com/11093161/129422247-133c7809-9bbd-4fd1-9aa4-6a2561df375e.png)

### Relevant Info

_Version_: `@esri/calcite-components@60`

- [x ] CDN
- [ ] NPM package

**Comment by driskull** [comment]
@jcfranco @julio8a can we triage this for this milestone? I can take it.

**Comment by jcfranco** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/calcite-components-5f7d10460071bf0024e66277/issues/Esri/calcite-components/2813?planning-poker) with ZenHub @driskull

**Comment by jcfranco** [comment]
Verified w/ https://codepen.io/jcfranco/pen/eYRvrPL?editors=1000
