### ISSUE TITLE
Enhancement: Expose property for fallback placements in calcite-dropdown

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#2814]
### Description
Similar to `calcite-popover`, it would be great if `calcite-dropdown` exposed a property to set fallback (flip) placements. I am using placement "bottom" but when it flips it goes to "top-start" because that's hardcoded as the first fallback. I'd want it to be mirrored and fallback to "top" (centered over dropdown trigger).

### Acceptance Criteria 
Able to configure fallback/flip placement for dropdown

#### Which Component
`calcite-dropdown`

**Comment by benelan** [comment]
verified on next
https://codepen.io/benesri/pen/popwvWG
