### ISSUE TITLE
Question: Tooltip `start`/`end` placement and RTL

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2815]
### Question
The `<calcite-tooltip>` component supports a `placement` attribute ​that has the following effects:

| Edge | Alignment | Result |
| - | - | - |
| `top` | `start` |  Tooltip placed _above_ ref. element and flush with the _left_ edge. |
| `top` | `end` | Tooltip placed _above_ ref. element and flush with the _right_ edge. |
| `bottom` | `start` | Tooltip placed _below_ ref. element and flush with the _left_ edge. |
| `bottom` | `end` | Tooltip placed _below_ ref. element and flush with the _right_ edge. |

In RTL layouts, the results are the same instead of reversed. The question is, are `start` and `end` intended to be synonymous with "leading" and "trailing" (in which case there's a bug) or "left" and "right" (in which case there's not)?

### Helpful Details 
The `placement` attribute's type includes the `VariationRtl` type which adds additional placement options not shown in [the documentation](https://esri.github.io/calcite-components/?path=/story/components-tooltip--simple). Specifically it adds placement options for `top-leading`, `top-trailing`, `bottom-leading` and `bottom-trailing`. Choosing one of these does result in a layout that respects the RTL direction.

I suppose a couple follow-on questions are, is the `VariationRtl` type safe to use? Should it be added to the documentation?

**Comment by driskull** [comment]
The `VariationRtl` are the correct ones to use. The others do not respect RTL

**Comment by benelan** [comment]
Closing this case since the question was answered. If there are follow up questions I can reopen it.
