### ISSUE TITLE
Bug: Tooltip with `auto-end` placement behaves like `auto-start`

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2817]
### Actual Behavior
A `<calcite-tooltip>` component with `auto-end` placement aligns itself flush with the reference element's top or left(/leading?) edges. Here's it's flush with the left edge:

<img width="881" alt="Screen Shot 2021-08-13 at 9 01 54 PM" src="https://user-images.githubusercontent.com/421496/129430096-c78e4d6b-cfba-493a-b074-ec1fca27b8e5.png">

### Expected Behavior
The tooltip should align itself flush with the reference element's bottom or right(/trailing?) edges. If placed below, it'd look the same as if it had `bottom-end` placement (flush with the right edge):

<img width="727" alt="Screen Shot 2021-08-13 at 9 02 51 PM" src="https://user-images.githubusercontent.com/421496/129430108-5413c2a4-6a71-496d-a9d2-154dde195298.png">

### Reproduction Steps or Sample

```html
<calcite-button appearance="outline" id="tooltip-auto-end-ref">auto-end</calcite-button>

<calcite-tooltip label="tooltip - auto-end" placement="auto-end" reference-element="tooltip-auto-end-ref">
  tooltip
</calcite-tooltip>
```

### Relevant Info
Also have an open question about whether or not `start`/`end` terms are supposed to be direction-dependent: https://github.com/Esri/calcite-components/issues/2815.

_Version_: `@esri/calcite-components@v1.0.0-next.269`

**Comment by driskull** [comment]
I think this is because...

> The "auto" placements will choose the side with most space.

https://popper.js.org/docs/v2/constructors/#placement

We're not modifying anything with the positioning here.

**Comment by nwhittaker** [comment]
>The "auto" placements will choose the side with most space.

I think my issue is with what happens after popper chooses the side with the most space. For `auto-start` and `auto-end` placements, I would expect the tooltip to then try to align itself with the reference element along the cross axis.

>We're not modifying anything with the positioning here.

Maybe there's an upstream bug here? I have yet to find a scenario where `auto-start` and `auto-end` actually end up with different placements of the tooltip.

**Comment by jcfranco** [comment]
@nwhittaker Is this issue still valid? Looks like placements do differ based on the available space:

<img width="418" alt="Screen Shot 2022-11-09 at 7 07 44 PM" src="https://user-images.githubusercontent.com/197440/200991518-3f0e7c4d-88ea-4205-8920-b37a33bebb98.png">

<img width="956" alt="Screen Shot 2022-11-09 at 7 07 11 PM" src="https://user-images.githubusercontent.com/197440/200991544-8162342b-9a79-486f-935b-f64ad86a68b3.png">

https://codepen.io/jcfranco/pen/MWXpgpR

**Comment by nwhittaker** [comment]
Looking at the test page, `auto-end` positions as expected now. It's been awhile since this issue was reported, so I imagine some upstream library change/fix resolved it in the mean time.
