### ISSUE TITLE
Bug: Tooltip offset-skidding not reversed in RTL layout

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2818]
### Actual Behavior
Tooltips with `top` or `bottom` placement and non-zero `offset-skidding` are offset in the same direction regardless if layout is LTR or RTL.

| Baseline | LTR | RTL |
| - | - | - |
| <img width="1286" alt="Screen Shot 2021-08-13 at 9 53 59 PM" src="https://user-images.githubusercontent.com/421496/129431032-74c647f7-12ab-4724-bb0a-2718f47c507f.png"> | <img width="1286" alt="Screen Shot 2021-08-13 at 9 53 50 PM" src="https://user-images.githubusercontent.com/421496/129431038-c5581271-6805-423e-aac5-2d5498d16a66.png"> | <img width="1286" alt="Screen Shot 2021-08-13 at 9 54 07 PM" src="https://user-images.githubusercontent.com/421496/129431043-e3ea53d6-ef3b-43f8-85db-f8814c43cc6d.png"> |
| Tooltip centered | Tooltip shifted right | Tooltip shifted right instead of left |

### Expected Behavior
The tooltip is offset in opposing directions depending on if the layout is LTR or RTL.

In the context of the above actual behavior, the expected behavior would be to see the tooltip shifted to the left in RTL layouts (achieved here by manually inverting the `offset-skidding` value):
<img width="1286" alt="Screen Shot 2021-08-13 at 9 58 37 PM" src="https://user-images.githubusercontent.com/421496/129431107-7c9c631e-38db-44e4-9558-090e616686a7.png">

### Reproduction Steps or Sample
```html
<div dir="rtl">
  <calcite-button appearance="outline" id="tooltip-bottom-ref">tooltip bottom</calcite-button>

  <calcite-tooltip label="tooltip - bottom" offset-skidding="15" placement="bottom" reference-element="tooltip-bottom-ref">
    tooltip
  </calcite-tooltip>
</div>
```

### Relevant Info

_Version_: `@esri/calcite-components@v1.0.0-next.269`

**Comment by driskull** [comment]
Offset skidding is not `dir` dependent at this time. Maybe in the future but Popper itself doesn't do anything depending on RTL/LTR

**Comment by nwhittaker** [comment]
A couple possibly related upstream issues:
* https://github.com/popperjs/popper-core/issues/695
* https://github.com/popperjs/popper-core/issues/1170

Looks like the current recommendation is to add a [custom modifier](https://popper.js.org/docs/v2/modifiers/#custom-modifiers) for it.

**Comment by nwhittaker** [comment]
>Offset skidding is not dir dependent at this time. Maybe in the future but Popper itself doesn't do anything depending on RTL/LTR

The `CalciteTooltip.placement` attribute has logic to support RTL layouts, so my thinking is it'd be natural to expect the same of the offset-related properties.

**Comment by nwhittaker** [comment]
This issue appears to have been resolved somewhere in the [`next.539`][1] release. Possibly by https://github.com/Esri/calcite-components/pull/3836.

[1]: https://github.com/Esri/calcite-components/releases/tag/v1.0.0-next.539
