### ISSUE TITLE
Bug: header/h4 element still rendered in calcite block without setting a heading

### ISSUE THREAD

**Issue by JonUihlein** [Esri/calcite-components#2824]
### Actual Behavior

header/h4 element still rendered in `<calcite block>` without setting a `heading` property.

### Expected Behavior

no header/h4 element should be displayed if not providing a `heading` property

### Reproduction Steps or Sample

Create a `<calcite-block>` without a `heading`

### Relevant Info

![calcite-block-header](https://user-images.githubusercontent.com/2378615/129595654-855658c9-223a-4e01-a164-262f615c3db5.PNG)

```ts
      <calcite-block class={CSS.toggleBlock} open>
        {this.renderSnappingToggle()}
      </calcite-block>

**Comment by jcfranco** [comment]
This is by design. @asangma can correct me if I'm wrong, but block should always have a heading. It is not documented as such, so we should mark it as required.

cc @benelan

**Comment by benelan** [comment]
I changed block's heading to required in the doc, @jcfranco can you please please verify?

**Comment by julio8a** [comment]
verified on master
