### ISSUE TITLE
Bug: calcite-tile's "large visual" variant doesn't center the content

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#2826]
### Actual Behavior

The large icon in `calcite-tile`'s "large visual" option displays on the left in LTR and on the right in RTL modes.

![image](https://user-images.githubusercontent.com/821864/129614965-8de60fc3-9ba8-4a88-9125-5929bbf9110a.png)

![image](https://user-images.githubusercontent.com/821864/129615038-caa3d1c5-82e9-4d86-aac7-b2f4096ffa86.png)

### Expected Behavior

The icon and description should always be displayed in the center in either reading mode.

### Reproduction Steps or Sample

```
<calcite-tile icon="layers" heading="Tile title lorem ipsum"></calcite-tile>
```

### Relevant Info

All browsers/OS

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by benelan** [comment]
Verified on beta.66
https://codepen.io/benesri/pen/KKqJPod
