### ISSUE TITLE
Additional checkbox rendering in Webpack app

### ISSUE THREAD

**Issue by rslibed** [Esri/calcite-components#283]
Additional checkbox rendering in Webpack app when using either `calcite-switch` or `calcite-checkbox`. 

<img width="205" alt="Screen Shot 2020-01-07 at 9 59 52 AM" src="https://user-images.githubusercontent.com/29421380/71918692-a803b900-3137-11ea-8072-c360841a692f.png">

cc: @macandcheese

**Comment by macandcheese** [comment]
I believe these components were built to support users placing their own inputs inside the component, right @patrickarlt ?

Stencil now has an "unreleased" library that generates bindings for angular and react, perhaps that would allow us to strip out all the proxy input logic that causes this?

I think we could probably find a more short term fix to hide the duplicate checkbox with css in the meantime?

**Comment by rslibed** [comment]
Any updates on this issue? @macandcheese @patrickarlt

**Comment by macandcheese** [comment]
Related: https://github.com/Esri/calcite-components/issues/234

@patrickarlt have you been able to experiment with https://github.com/ionic-team/stencil-ds-plugins for Angular? That would allow us to strip out all the "proxy input" stuff that (I believe) causes these, and simplify the switch, checkbox components a bit to prevent this.

@rslibed not a great solution but as a stopgap can you set `display: none` to hide the checkbox with a class on the `<calcite-checkbox>` ?

**Comment by rslibed** [comment]
Sure, that can work for now. Thanks

**Comment by julio8a** [comment]
what's the status of this one?

**Comment by paulcpederson** [comment]
@eriklharper did your recent changes to hidden checkboxes help fix this issue? Thinking this may be taken care of now.

**Comment by eriklharper** [comment]
Proxy input support is gone from `calcite-checkbox` and yes, [this fix](https://github.com/Esri/calcite-components/pull/1483/files) should resolve this issue but the only way that I can imagine it occurs is when `!important` styles are being applied to `input` tags in the CSS that affect the rules hiding the checkbox from view.  Not sure if this webpack app is doing that kind of thing, but that fix should ensure that those styles can't be overriden.

**Comment by paulcpederson** [comment]
@rslibed feel free to reopen if this can still be reproduced but at least locally I'm not seeing this anymore in the webpack example
