### ISSUE TITLE
A11y: Tab navigation through a single-select value list skips items after the first one

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#2834]
### Summary
Tab navigation with a single select value list seems a bit odd. The items that come after the first do not get a focus indication and are skipped when navigating the list using `tab`.

### Actual Behavior

The value list items after the first one are skipped. In single select mode, the value list items have a tab-index of -1 applied it seems.
![B9A62729-D7EC-451B-BBED-D93F10D35FB6](https://user-images.githubusercontent.com/52869490/129644809-f95ea271-c623-4109-a67b-a8e6081dee25.GIF)

### Expected Behavior
Should the interactive `value-list-item` element have a focus indicator? Or is this correct?

cc: @julio8a 

https://codepen.io/eborgen/pen/qBmGmOK?editors=1010

**Comment by jcfranco** [comment]
This is by design. Keyboard focus is only allowed within the active item. The up/down arrows can be used to navigate between items when the item content has focus.

**Comment by jcfranco** [comment]
cc @benelan

**Comment by ethanbdev** [comment]
> This is by design. Keyboard focus is only allowed within the active item. The up/down arrows can be used to navigate between items when the item content has focus.

Thanks @jcfranco , I will pass that along
