### ISSUE TITLE
calcite-button: If icon is present, text in the button is now right justified instead of centered 

### ISSUE THREAD

**Issue by dhrumil83** [Esri/calcite-components#284]
Was working fine with v1.0.0-beta.15. Broke with v1.0.0-beta.16

With icon:
`<calcite-button
        appearance="transparent"
        icon={plus32}
        scale="m"
        width="full"
      >
        "Add Content"
      </calcite-button>`

![image](https://user-images.githubusercontent.com/14285436/72093938-31e38b80-32ca-11ea-9ca5-2c52e7af3368.png)

Without icon:
`<calcite-button
        appearance="transparent"
        scale="m"
        width="full"
      >
        "Add Content"
      </calcite-button>`

![image](https://user-images.githubusercontent.com/14285436/72093971-44f65b80-32ca-11ea-8e75-e5876f042a0e.png)

**Comment by macandcheese** [comment]
Should be fixed by https://github.com/Esri/calcite-components/pull/285

**Comment by CodeBarker** [comment]
@macandcheese  any idea when the next release is ?

**Comment by macandcheese** [comment]
Will put one out today 🤙

**Comment by macandcheese** [comment]
@CodeBarker released!
