### ISSUE TITLE
Bug: calcite-input: using type="url" the placeholder string in rtl languages does not render correctly

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#2840]
### Actual Behavior

Using a `calcite-input` of type="url", the placeholder string doesnt seem to render correcty, was reported by BeyondSoft to the mapViewer repo.

![calcite-input](https://user-images.githubusercontent.com/11093161/129779143-0150d972-be7d-4ad8-a824-58371c83340d.png)

### Expected Behavior

See above screenshot of the expected behaviour

### Reproduction Steps or Sample

codepen link:
https://codepen.io/kevindoshier/pen/zYwWZRp

### Relevant Info

_Version_: `@esri/calcite-components@61`

- [ ] CDN
- [ ] NPM package

**Comment by driskull** [comment]
@kevindoshier `<input type="url" placeholder="https://<أدخل عنوان URL>"/>` does the same thing. This is just a browser thing.

**Comment by kevindoshier** [comment]
Ok ill mark the one in the mapViewer repo with this info, thanks

**Comment by jcfranco** [comment]
Closing based on ☝🏼 .

I think the translation text can use the LTR/RTL mark characters to enforce direction. Without that, the browser doesn't know how how to properly place the URL characters: https://www.w3.org/International/articles/inline-bidi-markup/#where

**Comment by Olga8614** [comment]
@driskull @jcfranco - can you please wrap the URL placeholder into _span dir="ltr"_ ? I don't think translation team can do it on their own.
