### ISSUE TITLE
Bug: calcite-action-menu and overflow action on calcite-toolbar, the menu floats behind any detached panels

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#2847]
### Actual Behavior

When using either `calcite-action-menu` or the overflow menu in an action bar, the menu that is displayed will be beneath any detached `calcite-panels` in the app

### Expected Behavior

The menu should appear on top of any panels to make it more useable

### Reproduction Steps or Sample

1.  Using the new mapviewer compress the window height until the "..."  overflow menus appear
2. Add a sketch layer to the map using the `+` action in the left hand toolbar
3. The sketch layers widget will appear on the right hand side of the app,  click one of the overflow menus in the right hand toolbar observe the menu is beneath the sketch tools detached panel.

![image](https://user-images.githubusercontent.com/11093161/129809203-b91f2a8a-9e84-4e5b-8665-e3f207c65390.png)

### Relevant Info

_Version_: `@esri/calcite-components@61`

- [ ] CDN
- [x] NPM package

**Comment by jcfranco** [comment]
@kevindoshier I couldn't reproduce this issue with the latest release. 

![Screen Shot 2022-07-01 at 1 45 05 PM](https://user-images.githubusercontent.com/197440/176965762-68a9f103-3456-4b2a-ad48-935f2ae561de.png)

I couldn't quite reproduce the screenshot you shared with the provided steps, so I could have missed a step, but can you confirm this is still an issue?

**Comment by kevindoshier** [comment]
Yes its ok now, we fixed it in the app by adjusting the z-index of some things, I will close
