### ISSUE TITLE
Enhancement: Clearer/better to see checkboxes

### ISSUE THREAD

**Issue by janett-baresel** [Esri/calcite-components#2848]
### Description
calcite-checkbox is hard to see when the small size is used. The line for the check is so thin, that even in normal size it is pretty subtle. 
Here a comparison of calcite-checkbox in small and checkbox icons we used in the past:
![image](https://user-images.githubusercontent.com/11048042/129920125-f7159c04-f551-473d-a6de-11c9fbd2be3e.png)

The line looks pretty blurry and is hard to see.

### Acceptance Criteria 
Clearer, thicker line for the check mark.

#### Which Component
calcite-checkbox (especially in `size="small"`)

#### Example Use Case
see above screenshot. We use checkboxes for a layer list where layers are turned on and off (visibility).

<sub>SVCH</sub>

**Comment by KatelynSeitz** [comment]
Does the Calcite checkbox have to use this icon: https://esri.github.io/calcite-ui-icons/#check
or are there components that are designed outside the icon library perhaps with HTML? I am thinking of other UI elements that are small, but not Calcite UI icons such as toggles, radio button, etc.

**Comment by KatelynSeitz** [comment]
Request submitted for new check icon to live in this component. Thanks for the suggestion, @janett-baresel

**Comment by KatelynSeitz** [comment]
The follow SVG code can now live in the checkbox component to replace the Calcite UI check icon: 
`<svg id="icons" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14"><path d="M5.5 10.38L2.56 7.44l.88-.88L5.5 8.62l5.06-5.06.88.88z"/><path fill="none" d="M0 0h14v14H0z"/></svg>`

Reach out if there are any follow up questions.

**Comment by caripizza** [comment]
@KatelynSeitz I don't think that svg isn't going to scale properly unfortunately. 

It looks to me like we just need to revert the path changes back to what they were before this pr change: 
https://github.com/Esri/calcite-components/pull/2205/files#diff-652d8517a10478f41cf540118f5d3246cd42490b69fd1a164933515f47f35c0dL91

Before (current)
![image](https://user-images.githubusercontent.com/42423180/137366008-d16afd72-2eeb-4f5f-a699-cfb63d9e29db.png)

After (the previous svg paths before Julio's pr):
![image](https://user-images.githubusercontent.com/42423180/137365917-e259bd8d-7c4b-4718-bad7-9dc4fc4aa0a8.png)

**Comment by caripizza** [comment]
@macandcheese AFAIK, checkbox has to support indeterminate state, so it's using `getPath` to apply the proper [`d` attribute values](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-checkbox/calcite-checkbox.tsx#L99-L101) to the conditionally rendered svg's path. Then for each scale, it sets the height/width of the checkbox to a font-size (ie., 12px sm/ 14px m / 16px l).

It really looks to me like we just need to revert that pr change Julio added, refactoring checkbox for each icon scale seems like more work than is required here to me.

Screenshots for comparison, all 100 x 30 px.

| Master (ie., current behavior) | Reverted paths (ie., my suggestion) |
|--|--|
| checked + focused | |
| ![image](https://user-images.githubusercontent.com/42423180/137374170-e5916855-5d1c-4244-952b-f504ebb34929.png) | ![image](https://user-images.githubusercontent.com/42423180/137374354-04837a43-ad8b-47fc-bffa-f789d29b6967.png) |
| indeterminate + focused | |
|![image](https://user-images.githubusercontent.com/42423180/137374283-75d569d9-a381-4944-bce9-b24066430c78.png) | ![image](https://user-images.githubusercontent.com/42423180/137374390-bccebde9-94d7-45a4-853a-ec2e626626db.png) |

**Comment by caripizza** [comment]
I'd like to add an additional to-do to this issue - let's remove the [`test` class](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-checkbox/calcite-checkbox.tsx#L265) that got added to the svg's containing div (Matt confirmed was added [on accident](https://github.com/Esri/calcite-components/pull/3161#discussion_r729221746)).

**Comment by benelan** [comment]
verified on next
