### ISSUE TITLE
Enhancement: Readonly for input box

### ISSUE THREAD

**Issue by janett-baresel** [Esri/calcite-components#2849]
### Description
We would like a readonly mode for input boxes. Main driver is a control for showing a url or code and allowing the user to copy it. They can do that by selecting the text (and copy/paste) or by pressing an additional button next to the input. 

### Acceptance Criteria 
- the content of the input box cannot be changed (same as when disabled)
- the content of the input box can be viewed even when it exceeds the maximum width of the input box (same as when it is enabled)
- the content of the input box can be selected and copied (same as when it is enabled)

#### Which Component
calcite-input

#### Example Use Case
arcgisonline item details page: 
![image](https://user-images.githubusercontent.com/11048042/129922951-7aebaec6-dd8c-408f-b869-76091ce94cc2.png)
(I think this is currently implemented with a native input)

<sub>SVCH</sub>

**Comment by caripizza** [comment]
@janett-baresel `readOnly` was added to calcite-input in #2726, so it's available for use in beta.62 if you can install this version.

**Comment by janett-baresel** [comment]
great news. thanks.
