### ISSUE TITLE
Bug: Dynamically created dropdown items are not keyboard navigable

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#2852]
### Actual Behavior

After `calcite-dropdown` is rendered, any `calcite-dropdown-items` (or group with items) that are added dynamically cannot be accessed by keyboard (using arrow keys or tab).

### Expected Behavior

It should be possible to navigate to all dropdown items using the keyboard.

### Reproduction Steps or Sample

See sample: https://codepen.io/ellupp/pen/MWmMGyd?editors=1010
1. open menu, 3 items can be cycled through using arrow keys or tabbed through
2. click button to add new item
3. open menu again, arrow keys continue to cycle through initial 3 items and tab skips over new item

### Relevant Info

_Version_: `@esri/calcite-components@beta61` NPM package

**Comment by driskull** [comment]
Seems like dropdown needs to setup a mutation observer so it can update it's state.

**Comment by macandcheese** [comment]
@ellenupp - this seems to have been resolved at some point, as it seems to work on beta 77 - https://codepen.io/mac_and_cheese/pen/abEOPNo?editors=1010.

Going to close this, feel free to re-open if this isn't resolved.
