### ISSUE TITLE
Bug: Add types to public events EventEmitter

### ISSUE THREAD

**Issue by samMatenaer** [Esri/calcite-components#2854]
Many components are either missing or have incomplete event types which makes causes a headache with handling events in typescript. 

For example, here is an excerpt from my code using the calcite-components-react package
```ts
onCalciteInputInput={(evt) => {
    // evt currently typed as CustomEvent<any>
    const typedEvent = evt as CustomEvent<{ value: string }>;
    const newValue = typedEvent.detail.value;
}}
```
You can see the return type on calciteInputInput is currently `any`, when it should have a specific type.

This is because the [EventEmitter has no type provided](https://github.com/Esri/calcite-components/blob/c87f343651f55dc4ab0031b9f35af74da70dca49/src/components/calcite-input/calcite-input.tsx#L336), so it auto-casts to `any`

### Actual Behavior
Current calciteInputInput definition:
```ts
 @Event({ cancelable: true }) calciteInputInput: EventEmitter;
```

### Expected Behavior

Proposed definition:
```ts
  @Event({ cancelable: true }) calciteInputInput: EventEmitter<{
    element: HTMLInputElement | HTMLTextAreaElement;
    value: string;
    nativeEvent: any;
  }>;
```

I'd like to take this task on if it's something others think would be worth doing

**Comment by jcfranco** [comment]
Thanks for bringing this up. We need to do an audit of our custom events as we will be removing any custom event payload that is not already on the component itself. 

For the `calciteInputInput` case, you can to through the event's `target`/`currentTarget` to get the value: https://codepen.io/jcfranco/pen/eYRmJej?editors=0010

cc @benelan

**Comment by driskull** [comment]
It seems all events have types now. @geospatialem can you confirm?

**Comment by geospatialem** [comment]
Verified on the `master` branch. 👍🏻
