### ISSUE TITLE
Bug: close icon wrong size in tip manager

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2856]
### Actual Behavior

cant change icon to correct size because of this: https://github.com/Esri/calcite-components/blob/master/src/components/calcite-action/calcite-action.tsx#L171

### Expected Behavior

Need to use a 24px X close icon for tip manager

maybe not use action, and just use a styled native button.

### Relevant Info
![image](https://user-images.githubusercontent.com/14083530/130014210-3bcf0afa-1f12-417e-b463-74900709432d.png)

**Comment by bstifle** [comment]
@justinhough

**Comment by justinhough** [comment]
@asangma @julio8a  For this issue, do you have any insight into the line that was referenced for this issue: https://github.com/Esri/calcite-components/blob/master/src/components/calcite-action/calcite-action.tsx#L171.

That one change could resolve this issue since it appears to be overriding the action size to be "M" if set to large.

**Comment by julio8a** [comment]
@asangma, would be the best person to answer this ^

**Comment by asangma** [comment]
👀

**Comment by asangma** [comment]
@justinhough If you want Action to show an icon of a scale other than the one it prescribes, inside TipManager

1. don't use Action's `icon` property
2. put a CalciteIcon inside [Action used for the close button](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-tip-manager/calcite-tip-manager.tsx#L283-L289) and set scale to taste.
3. profit.

```js
/**
* Inside TipManager
*/
<calcite-action scale="m">
  <calcite-icon icon="x" scale="you're-not-the-boss-of-me" />
</calcite-action>

**Comment by asangma** [comment]
>  it appears to be overriding the action size to be "M" if set to large.

This is setting the icon's scale based on Action's scale.
Per design: S and M Actions use small icons and only use large icons when scale is L.

**Comment by asangma** [comment]
To be clear, that could be a new issue we probably want to be consistent when a parent renders a child component, and make sure the child component uses the same scale.

**Comment by justinhough** [comment]
@asangma So the code would change to this then in `calcite-tip-manager.tsx` to get the desired effect. It seems that would be the only real change besides disabling the icon rendering from `calcite-action`.

![CleanShot 2021-09-02 at 18 33 44](https://user-images.githubusercontent.com/9469422/131932916-a81d49d3-8db6-4c93-9ba8-8839dc953399.png)

**Comment by asangma** [comment]
Yup! That looks about right.

**Comment by justinhough** [comment]
👍🏻 Cool. That works for me.

**Comment by asangma** [comment]
Although you should still be able to use the `ICONS.close` value.

**Comment by justinhough** [comment]
For sure. I just did that real quick.

**Comment by asangma** [comment]
@julio8a Do you want me to verfee?

**Comment by julio8a** [comment]
That would be very helpful, thank you.

**Comment by asangma** [comment]
Dang that icon looks good 24px a day!
