### ISSUE TITLE
Bug: Action - align font sizes

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2864]
Breaking this off from #2458 to address just the font sizes.
@justinhough can then move on #2786.

### Actual Behavior

Action font sizes are

| text size | scale |
|:-------:|:-----:|
| --2h | s |
| --2h | m |
| --1h | l |

### Expected Behavior

Font sizes should be

| text size | scale |
|:-------:|:-----:|
| --2h | s |
| --1h | m |
| -0h | l |

so that it aligns with other components.

### Reproduction Steps or Sample

1. review Action font sizes.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

cc @bstifle @julio8a

**Comment by julio8a** [comment]
Thanks Alan

**Comment by julio8a** [comment]
@justinhough, this is what we should move forward with the refactor on Action for now. 
From this PR: https://github.com/Esri/calcite-components/issues/2458

**Comment by justinhough** [comment]
@asangma and @julio8a Pushed the updates for this issue into the following PR -> https://github.com/Esri/calcite-components/pull/2786. Have a look and let me know.

**Comment by julio8a** [comment]
verified on master, local build demo pages.
