### ISSUE TITLE
Bug: @stencil/core/internal/client not found from custom-elements with Webpack 5

### ISSUE THREAD

**Issue by ssylvia** [Esri/calcite-components#2865]
### Actual Behavior
I receive the following error when trying to include this package in a Webpack 5 bundle with StorybookJS

```
ModuleNotFoundError: Module not found: Error: Can't resolve '@stencil/core/internal/client' in '.../node_modules/@esri/calcite-components/dist/custom-elements'
Did you mean 'index.js'?
BREAKING CHANGE: The request '@stencil/core/internal/client' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
   at...

...

resolve '@stencil/core/internal/client' in '.../node_modules/@esri/calcite-components/dist/custom-elements'
  Parsed request is a module
  using description file: /.../node_modules/@esri/calcite-components/package.json (relative path: ./dist/custom-elements)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
```

### Expected Behavior

Bundle without error

### Relevant Info

It looks like it is related to this PR: https://github.com/Esri/calcite-components/pull/781 where the `dist/custom-elements/index.js` is copied to `dist/custom-elements/index.mjs` for rollup support.

If I remove `dist/custom-elements/index.mjs` from my `node_modules` folder, everything resolves correctly

Adding a [browser ignore](https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module) to the package.json also seems to work:

```json
  "browser": {
    "dist/custom-elements/index.mjs": "dist/custom-elements/index.js"
  },
```

**Comment by jcfranco** [comment]
@ssylvia https://github.com/Esri/calcite-components/pull/3224 got rid of `index.mjs`, so this may no longer be an issue. Could you try testing with `@next`?

**Comment by Biboba** [comment]
> Oops! Note, this is not an ArcGIS JS API issue. Try adding this new rule to `webpack.config.js` as a potential fix.
> 
> ```
>  module: {
>     rules: [
>         // add this new rule
>         {
>             test: /\.m?js/,
>             resolve: {
>                 fullySpecified: false
>             }
>         },
> ```
> 
> The `ERROR: Module note found...can't resolve...did you mean index.js` message is commonly related to babel + Webpack 5. Something in your set up is triggering these errors. Here is a discussion thread with more information: [webpack/webpack#11467](https://github.com/webpack/webpack/issues/11467)

Thanks @andygup ! I confirm your fix works.

**Comment by jcfranco** [comment]
[belated] closing as verified based on ☝🏼.
