### ISSUE TITLE
Enhancement: Allow disabling resize on a `calcite-input` of type textarea

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#2866]
### Description
There is not a way now to disable the resizing of a textarea input. The only way now is to use nested css like so:
```css
> div.calcite-input__resize-icon-wrapper {
    display: none;
}
```
but this is prone to breaking with new releases and is hard to maintain

### Acceptance Criteria 
Have a property that hides the resize icon, maybe `disable-resize`, that can be used to hide it and not allow the user to change the height/width.

#### Which Component
`calcite-input`
#### Example Use Case
![image](https://user-images.githubusercontent.com/52869490/130158496-04696812-c9d2-44ed-bb8e-8025aa49e8e6.png)

**Comment by macandcheese** [comment]
@ethanbdev - going to close this - it should be addressed by https://github.com/Esri/calcite-components/issues/3312 / https://github.com/Esri/calcite-components/issues/863.
