### ISSUE TITLE
Research:  Set goals for and discuss cascading scale

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#2868]
### Background 
Continuing the Teams discussion on #2781 about how we want to handle cascading scale. One of the options was to use a -- var for scale and remove the prop. Another option was not cascading and having the user set the prop on all of the components that they want to change.

### Desired Outcome
- Create pros/cons for the options above as well as any other ways to handle cascading scale
- Make sure the solution is consistent for the end user

**Comment by driskull** [comment]
By their nature, props aren't supposed to cascade. I think if we want scale to cascade, we should look into using a CSS class for it.

If we're ok with a prop scale not cascading then we just don't have it cascade.

**Comment by patrickarlt** [comment]
In looking into https://github.com/Esri/calcite-components/issues/3624 it might be nice to split scale into 2 parts:

1. text scale
2. "size" scale

In the case of https://github.com/Esri/calcite-components/issues/3624 I could then set the "size" scale so the components are the same height and the text scale to the same level to ensure the text stays the same size.

**Comment by jcfranco** [comment]
Discussed with the team and we will not pursue cascading scale via props outside of parent/child structures (e.g., `accordion`/`accordion-item`). Doing so introduces opportunities for unintentional scale overrides across subtrees. I'll submit a separate issue to drop any scale lookups outside of this (looks like it's just the input components).

**Comment by jcfranco** [comment]
@patrickarlt Apologies for the belated reply. Could you provide additional info about the use case? + @macandcheese @SkyeSeitz @ashetland for design considerations regarding separate text/size scale. We can also move this to a separate discussion.
