### ISSUE TITLE
Test: Revisit calcite-date-picker.e2e.ts > "when the locale is set to Slovak calendar"

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2872]
## Summary

**Which component?:** `calcite-date-picker.e2e.ts`

**Which test(s)?:** 

`calcite-date-picker.e2e.ts > "when the locale is set to Slovak calendar"`

https://github.com/Esri/calcite-components/blob/27531d525df5a8fa1dd6d8b61e51cbf95869543c/src/components/calcite-date-picker/calcite-date-picker.e2e.ts#L123

**Test error:**

N/A

**PR that skipped the test:** N/A

## Additional Info 

Stems from https://github.com/Esri/calcite-components/pull/2870/files#r693140986

The following lines should be refactored to be deterministic since the HTML structure should not vary between runs (i.e. remove the optional chaining): https://github.com/Esri/calcite-components/blob/27531d525df5a8fa1dd6d8b61e51cbf95869543c/src/components/calcite-date-picker/calcite-date-picker.e2e.ts#L132-L133

Marking this as a low-priority since the test would still fail when needed.

**Comment by anveshmekala** [comment]
this test is passing locally. Ref  [#2902](https://github.com/Esri/calcite-components/pull/2902/files#diff-75d874aa637026098d9dd3e76b98b711ec569b2262c0629f0d3efb63aea00e0aR133)

**Comment by benelan** [comment]
Verified on master. This test passed locally for me and has been passing in PR checks too.
