### ISSUE TITLE
Enhancement: Link styles cannot be overridden inline

### ISSUE THREAD

**Issue by dulldrums** [Esri/calcite-components#2876]
### Description

`<calcite-link>` styles cannot be overridden inline. Attempting to provide a `style` attribute inline does nothing to the text inside the link.

This is particularly an issue when dealing with the `text-decoration` css property.

Attempting to override Link styles inline is not following best practices and is probably discouraged. Ran into this behavior when rewriting a page and wanted to reach visual parity with the previous implementation.

### Acceptance Criteria 

Be able to override Link styles inline. Alternatively, provide a way to remove the underline from a link. Additional documentation on `text-decoration` default behavior in the docs might help as well (although may be superfluous). Mentioning this in the Link component doc might also be helpful. Examples of overriding themeing of `--calcite-link-blue-underline:` could help as well.

### Relevant Info 

version: `1.0.0-beta.62`

#### Which Component

`Link` https://developers.arcgis.com/calcite-design-system/components/link/

#### Example Use Case

Here is a demo in codepen: https://codepen.io/dulldrums/pen/BaZBBLv

**Comment by tjameswhite** [comment]
We have a similar problem -- there instances in components where we need to change the link color (see screen shot). For buttons we can use the `color=inverse` property. 

I suggest adding the same property to calcite-links. 

![blue-link](https://user-images.githubusercontent.com/2693135/133311927-15152e2b-8103-4236-9734-5ea781f9c5ef.png)

**Comment by geospatialem** [comment]
Assigned to the April milestone to determine next steps via research.

**Comment by paulcpederson** [comment]
Ran into this issue randomly, and we've had to handle stuff like this before, so thought I'd offer some work arounds until this gets looked at.

@dulldrums you can kind of clear the underline by setting the underline color to transparent. 
@tjameswhite you can set the color with a CSS var

codepen with both of those https://codepen.io/paulcp/pen/ZEMxbdB?editors=1100

**Comment by geospatialem** [comment]
Reallocating to the May release for design considerations.

**Comment by ashetland** [comment]
@paulcpederson @tjameswhite @dulldrums @jcfranco 

Hey folks! We wanted to get everyone thoughts on possibly adding an `underline-disabled` prop to Link. The behavior would be identical to Paul's [codepen](https://codepen.io/paulcp/pen/ZEMxbdB?editors=1100): the underline would be hidden when idle, but would still appear on hover. Custom colors would still use the var `--calcite-ui-text-link`.

That said, we have a concern about fragmentation. If we add this, it will make it much easier for links to have less consistent styling, thus making them less obvious to users. 

**Is this use case common enough to warrant adding a new prop to disable the underline or does the existing workflow of using `--calcite-ui-text-link` and `--calcite-link-blue-underline` suffice for a customization story?**

**Comment by paulcpederson** [comment]
It's not a huge deal with our team, really. But I know Tim has different requirements due to the Adobe CMS.

**Comment by ashetland** [comment]
Closing as `--calcite-ui-text-link` and `--calcite-link-blue-underline` provide a suitable customization story.
