### ISSUE TITLE
Enhancement: Add ability to add tooltip to Icon in List component

### ISSUE THREAD

**Issue by dulldrums** [Esri/calcite-components#2878]
### Description

Cannot add a tooltip to an Icon placed inside a List Item component. 

Adding a tooltip to an icon in a List component item row could be useful in certain cases. In this specific case, there were multiple icons in the row, and adding a tooltip could clarify their behavior. 

Currently, we can only add a tooltip to the List Item component or components using `slot="actions-start"`, but not to icons within the List Item component using `slot="content-start"`.

### Acceptance Criteria 

The ability to use a tooltip for an icon in a List Item.

### Relevant Info 

version: `1.0.0-beta.62`

workaround: Use `slot="actions-start"` on the icon

#### Which Component

List: https://developers.arcgis.com/calcite-design-system/components/list/
Icon: https://developers.arcgis.com/calcite-design-system/components/icon/

#### Example Use Case

Here is a codepen: https://codepen.io/dulldrums/pen/XWgrrqM

**Comment by driskull** [comment]
@asangma this is because the pointer events for the content is set to `none`. https://github.com/Esri/calcite-components/blob/master/src/components/calcite-list-item/calcite-list-item.scss#L74-L77

Do we need that set?

Here's a temporary workaround...

```html
<calcite-icon
                        style="pointer-events:auto;"
```

**Comment by jcfranco** [comment]
I think content slots are not interactive by design, but I could be wrong. @asangma Can you chime on this one?

**Comment by macandcheese** [comment]
> I think content slots are not interactive by design, but I could be wrong.

Agreed - In this case the recommendation would be to use the actions-end (or start) slot to house a trigger for the tooltip: https://codepen.io/mac_and_cheese/pen/ExEajNN?editors=1000
