### ISSUE TITLE
Bug: calcite-slider component calls emitChange function on page load

### ISSUE THREAD

**Issue by shubhamsoengg** [Esri/calcite-components#2881]
### Actual Behavior

The calcite-slider component calls the "emitChange" function in the "componentWillLoad" lifecycle method. This is causing a bug in the arcgis-charts-config-histogram component. 
https://github.com/Esri/calcite-components/blob/2b4f41be2f51704f1f2ec2f1e8026b719ee69084/src/components/calcite-slider/calcite-slider.tsx#L124

### Expected Behavior

The emitChange function should be called only if the slider value changes. Please do mention if there is a specific reason why emitChange is called in the componentWillLoad method.

**Comment by jcfranco** [comment]
@shubhamsoengg Thanks for reporting this issue. Can you update the title and description to follow our issue templates? https://github.com/Esri/calcite-components/issues/new?assignees=&labels=bug%2C+0+-+new%2C+needs+triage&template=bug.md&title=Bug%3A+

Also, issue assignment is managed by the team, so no need to assign.

**Comment by benelan** [comment]
> This issue is installed, assigning to @benelan for verification

Whoops I'll fix that. @jcfranco or @julio8a can I get a verification on this issue?

**Comment by jcfranco** [comment]
I'll verify.

**Comment by jcfranco** [comment]
Verified with https://codepen.io/jcfranco/pen/vYZPWZb?editors=1000
