### ISSUE TITLE
Bug: active tab "underline" not visible when when tabs contained in initially hidden panel

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#2885]
### Actual Behavior

As stated and shown here: https://codepen.io/COV-GIS/pen/ExXxzWj

### Expected Behavior

Active tab should be underlined when panel is shown.

Switching tabs or resizing the window causes the underline to appear.

### Relevant Info

_Version_: `@esri/calcite-components@v1.0.0-beta.62`

- [ ] CDN
- [ ] NPM package

**Comment by ellenupp** [comment]
Encountering this as well. Put together a sample before I noticed this was already logged: https://codepen.io/ellupp/pen/ZEaYeMV?editors=1010

**Comment by jcfranco** [comment]
Installed. 

Simplified repro case: https://codepen.io/jcfranco/pen/jOYGyBb

**Comment by COV-GIS** [comment]
Thanks for working on this @jcfranco and fixing https://github.com/Esri/calcite-components/pull/4351 too.

**Comment by geospatialem** [comment]
Closing this issue, verification provided by @jcfranco 👍🏻
