### ISSUE TITLE
Docs: Add child components that are not included in the parent storybook page

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#2887]
### Description 
Most of the components with direct children have those children documented on the same storybook page, e.g. [Tabs](https://esri.github.io/calcite-components/?path=/docs/components-tabs--simple), [Flow](https://esri.github.io/calcite-components/?path=/docs/components-flow--basic), [Shell](https://esri.github.io/calcite-components/?path=/docs/components-shell--basic). etc. 

The components listed below do not have their child components documented in storybook and should have them added.

### Which Component
[List](https://esri.github.io/calcite-components/?path=/docs/components-list--simple)
[Pick List](https://esri.github.io/calcite-components/?path=/docs/components-pick-list--basic)
[Value List](https://esri.github.io/calcite-components/?path=/docs/components-value-list--basic)
[Radio Button](https://esri.github.io/calcite-components/?path=/docs/components-controls-radio-radio-button--light-theme)

**Comment by benelan** [comment]
Installed, can one of you please verify @jcfranco @julio8a?

**Comment by jcfranco** [comment]
I'll verify.

**Comment by benelan** [comment]
@jcfranco can you verify this one?

**Comment by jcfranco** [comment]
Reopening to verify.

**Comment by jcfranco** [comment]
Verified via internal storybook! 🎉
