### ISSUE TITLE
Bug: calcite-sortable-list around calcite-block changes block layout

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2889]
When I add `calcite-sortable-list` around `calcite-block` elements that I want to sort they suddenly appear all in one line.
I have to add `flex-flow: column nowrap;` to `calcite-sortable-list` to make them appear properly.

<img src=https://user-images.githubusercontent.com/44481292/130658923-d3c1af07-99a3-46f3-bf78-85b39068412f.png width=250/>

![image](https://user-images.githubusercontent.com/44481292/130658962-d9fa7201-34a2-4906-b3ca-1661372aab41.png)

@asangma suggested to add a layout property to SortableList;

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by asangma** [comment]
Simple solution for this would be to add a default style that lays content out in a column.

A more involve (though not much more involved) solution would be to add a `layout` property that defaults to "vertical".

**Comment by asangma** [comment]
I can do either.

**Comment by AdelheidF** [comment]
not yet fixed with beta.65 https://codepen.io/afreitag/pen/jOwKGmK?editors=1010

**Comment by benelan** [comment]
verified in beta.66 using the sample above
