### ISSUE TITLE
Use up/down chevrons in accordions

### ISSUE THREAD

**Issue by TheBlueDog** [Esri/calcite-components#289]
The use or left/right pointing chevron icons can be confusing when used in accordions. It can be unclear that the icon would point opposite directions to mean the same action, depending on which side of an accordion header its place. Left/right navigation is also used when navigating sliding panels.

The request is to change the accordion design to use up/down chevrons to separate it from panel navigation and have the same convention that wouldn't change based on the placement of the icon.

`chevron-up` would indicate the content will be hidden. `chevron-down` would indicate the content will expand.

Some examples in other design systems:

[Carbon Design System](https://www.carbondesignsystem.com/components/accordion/usage/)
[Spark Design System](https://sparkdesignsystem.com/patterns/components/accordions)

**Comment by macandcheese** [comment]
@asangma @mitc7862 

currently Online uses a right-facing arrow to the left of the title, would the above be acceptable for your use cases?

**Comment by macandcheese** [comment]
@TheBlueDog Sorry for letting this lag - I propose doing the above suggestion but only when the icon is positioned with `icon-position=end` - as in the examples provided. When `icon-position=start`, I think it should remain as is. Thoughts?

**Comment by TheBlueDog** [comment]
I think changing the behavior from left to right would feel inconsistent.

**Comment by macandcheese** [comment]
I guess the difference (IMO), is in `icon-position=start`, the title is directly adjacent to the chevron (GitLab example: https://design.gitlab.com/components/accordion/, Ant example: https://ant.design/components/collapse/ Lightning: https://www.lightningdesignsystem.com/components/accordion/)

While when it's positioned to the right, it's far enough away from the title that having it facing up makes sense like in the examples you provided.

**Comment by bstifle** [comment]
✅ when the icon is next to the header, i prefer this:

![image](https://user-images.githubusercontent.com/14083530/82254174-3ae30a00-9907-11ea-82af-0f6bd449956c.png)



✅ when the icon is on the other side of the header, i much prefer this:

![image](https://user-images.githubusercontent.com/14083530/82254280-69f97b80-9907-11ea-96fe-b091140b4f60.png)

**Comment by TheBlueDog** [comment]
What about flipping them in the second example? That way, in either use case, `chevron-down` means its expanded.

**Comment by macandcheese** [comment]
Agree ^ the carbon "down facing is closed" is weird IMO. Then we can be consistent between icon start / end but still have the arrow facing title in icon start

**Comment by TheBlueDog** [comment]
Suggest maybe for accordions the icon only on the right, and for trees they are on the left.

**Comment by macandcheese** [comment]
I think we should keep both - there are a lot of UIs where there's an accordion as the left-most element on a page that aren't replicable as tree navs, in Online especially (not currently using the `calcite-accordion` component) - that house elements besides tree navs: 

<img width="346" alt="Screen Shot 2020-05-18 at 2 48 07 PM" src="https://user-images.githubusercontent.com/4733155/82262893-a1235900-9916-11ea-8a9f-c8dcdc49156b.png">

But I'd definitely be up for updating the `icon-position=end` to appear as up / down items as initially requested.

**Comment by bstifle** [comment]
i agree with keeping both. and letting the user decide.
