### ISSUE TITLE
Bug: Combobox single select filled text using wrong weight

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2901]
### Actual Behavior

Filled weight in combobox single select text is using avenir-medium 500
![image](https://user-images.githubusercontent.com/14083530/130825272-23aa069e-bff2-47fc-bd16-79251d958b8e.png)

### Expected Behavior

Filled weight in combobox single select text should use avenir-regular 400
![image](https://user-images.githubusercontent.com/14083530/130825470-12dc3ae8-c7bf-4f5f-9a23-f828cb5a5615.png)

### Relevant Info
Same weight as inputs and selects

**Comment by julio8a** [comment]
Verified on master demo pages.
