### ISSUE TITLE
Refactor: remove calcite prefix from component filenames

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#2913]
### Description
Remove ``calcite-`` from the component directories and filenames. It is unnecessarily verbose, and removing it would make our naming convention similar to that of ionic: https://github.com/ionic-team/ionic-framework/tree/main/core/src/components/select

### Acceptance Criteria 
All of the ``calcite-`` prefixes are removed from the component directories and filenames.

**Comment by driskull** [comment]
This is a nice thing we could do prior to 1.0 release.

**Comment by jcfranco** [comment]
Closing as verified! 🎉
