### ISSUE TITLE
Bug: Default display for calcite-label should be defined.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#2921]
### Actual Behavior

calcite-label is displayed as inline by default. Should it be? Should the 'layout' property change the default display?

### Expected Behavior

At very least, a test is setup to test the default display and if any layout prop changes should affect that.

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
> calcite-label is displayed as inline by default. Should it be? Should the 'layout' property change the default display?

I think your suggestion makes sense. Based on the [following codepen](https://codepen.io/jcfranco/pen/BarNKeE?editors=1000), maybe the host display should use `flex` and `inline-flex`. WDYT? cc @macandcheese @asangma

**Comment by macandcheese** [comment]
Yes, as long as it maintains the same visual functionality that makes sense. It seems to work with the `inline-space-between` layout type as well in your example.

**Comment by driskull** [comment]
https://github.com/Esri/calcite-components/pull/6014

Tested that changing to `flex`doesn't render differently. `inline-flex` did render diifferently.

**Comment by geospatialem** [comment]
Verified on `next.675`.

![image](https://user-images.githubusercontent.com/5023024/207639774-7d9002b2-4b1e-4707-868e-626df768c5a8.png)
