### ISSUE TITLE
Enhancement: Tile. Add styles for Icon in actions-end slot

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2937]
### Description
Add a convenience styles for CalciteIcon in Tile's "actions-end" slot.

~Blocked until #2890 is merged.~

### Acceptance Criteria 
* Use layout styles only.

### Relevant Info 
Suggested style for CalciteIcon
```
align-self: center;
padding: 0 0.75;
```

#### Which Component
Tile

#### Example Use Case
Adding a CalciteIcon ~or CalciteAction~ to a the "actions-end" slot.
(CalciteActions already seems to be responding according to designs.)

cc @jcfranco

**Comment by asangma** [comment]
@jcfranco Updated.

**Comment by y0n4** [comment]
For `calcite-tile`, there is the slot name: `content-start` and `content-end` but not under the name actions-end. The padding styling is at least fulfilled https://github.com/Esri/calcite-components/blob/master/src/components/calcite-tile/calcite-tile.scss#L72

Were you referring to the `content-end` slot or something else? @asangma

**Comment by jcfranco** [comment]
> Were you referring to the content-end slot or something else?

@asangma can you help clarify this?

**Comment by asangma** [comment]
Ah...looks like this is no longer a valid issue.
