### ISSUE TITLE
Bug: calcite-color-picker calls calciteColorPickerInput on initial setup

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2938]
I noticed that the initial setup of `calcite-color-picker` already calls the `calciteColorPickerInput` event. 
That's an issue because by just creating this popover it sets an effect on the layer.

```
          <calcite-color-picker
            dir="ltr"
            scale="m"
            value="#000000"
            format="hex"
            appearance="default"
            intlBlue={blue}
            intlGreen={green}
            intlHex={hex}
            intlRed={red}
            intlSaved={saved}
            hideSaved={true}
            onCalciteColorPickerInput={this.onPropChange}
          ></calcite-color-picker>
```

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by AdelheidF** [comment]
FYI, the other day I noticed that `calcite-radio-group` has the same issue.

**Comment by benelan** [comment]
verified on next
