### ISSUE TITLE
Bug [calcite-tooltip]: partially visible tooltip inside a small container

### ISSUE THREAD

**Issue by svlesiv** [Esri/calcite-components#2942]
### Actual Behavior
A tooltip might not fit inside a small container (for example, inside a dropdown with a few items).

<img width="249" alt="Screen Shot 2021-08-27 at 5 37 05 PM" src="https://user-images.githubusercontent.com/35533801/131200607-35a5c406-1bad-4684-b952-66884f756add.png">

### Expected Behavior
A tooltip will be shown outside of a small container.

### Reproduction Steps or Sample
1. Create a dropdown with only 2 items.
2. Wrap one of the items inside a tooltip with a long text.
3. Hover over that item.
4. The tooltip will be partially visible.

### Relevant Info
https://codepen.io/svlesiv/pen/rNLQvaQ

_Version_: `@esri/calcite-components/1.0.0-beta.62`
Chrome:  version 92.0.4515.159

**Comment by driskull** [comment]
@svlesiv you can move the tooltip outside of the dropdown and it works fine.

**Comment by svlesiv** [comment]
Thank you for your response, but I'm not sure how it can fix the problem.
The task is to display tooltips for dropdown items.

**Comment by driskull** [comment]
```html
 <calcite-tooltip placement="auto" reference-element="tooltip-id"
      >Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</calcite-tooltip
    >
<calcite-dropdown>
  <calcite-button slot="dropdown-trigger">Open Dropdown</calcite-button>
  <calcite-dropdown-group>
    <calcite-tooltip-manager>
      <p id="tooltip-id">
        <calcite-dropdown-item>Option 1</calcite-dropdown-item>
      </p>
    </calcite-tooltip-manager>

    <calcite-dropdown-item active>Option 2</calcite-dropdown-item>
   
  </calcite-dropdown-group>
</calcite-dropdown>
```

**Comment by macandcheese** [comment]
From a UX perspective, having a tooltip invoked by hovering over individual dropdown items, already inside a floating window, probably isn't the best choice. 

Is it possible to display supplementary text within the dropdown item?

**Comment by svlesiv** [comment]
Thank you for the quick response.

The use case is to disable certain menu items depending on permission level and explain why they are disabled when hovering over them.

<img width="572" alt="131202431-19c3ad0d-9459-42e3-975f-17d0793f9801" src="https://user-images.githubusercontent.com/35533801/131542952-231702f4-8183-4408-b49c-d629b9c80eb8.png">

But if that issue is tricky to fix, we will try to find another solution how to accomplish that when we will have a tooltip with longer text. With our current tooltip, the issue is almost not visible.

**Comment by driskull** [comment]
It works with the snippet I provided

Can we close this issue?

**Comment by svlesiv** [comment]
Yes, thank you for your help :grinning:

**Comment by driskull** [comment]
Thanks! closed
