### ISSUE TITLE
Unstable Test: calcite-input › number type › allows decimals when step is any

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2946]
## Summary

**Which component?:** `calcite-input`

**Which test(s)?:**  `calcite-input › number type › allows decimals when step is any`

**Test error:**

```
FAIL src/components/calcite-input/calcite-input.e2e.ts (380.725 s)
  ● calcite-input › number type › allows decimals when step is any
    expect(received).toBe(expected) // Object.is equality
    Expected: "1.5"
    Received: "15"
      920 |       await page.waitForChanges();
      921 | 
    > 922 |       expect(await input.getProperty("value")).toBe("1.5");
          |                                                ^
      923 |     });
      924 |   });
      925 | 
```

**PR that skipped the test:** https://github.com/Esri/calcite-components/pull/2945

## Additional Info 

N/A

**Comment by jcfranco** [comment]
Stabilized via https://github.com/Esri/calcite-components/pull/3566. 🐴 🤠 💨

**Comment by benelan** [comment]
Its been two weeks and I haven't seen this test fail, verified!
