### ISSUE TITLE
Research: revisit calcite-graph's default SVG width

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2948]
### Background 
I'm opening up this issue [per Franco's request](https://github.com/Esri/calcite-components/pull/2867#issuecomment-908473509) in my slider style update pr:

> Is there a use case where the SVG wouldn't need to fill the whole width? If not, shouldn't it always be full width and up to the host component to modify its width?

### Desired Outcome 
Answer the above questions and determine path forward with calcite-graph (and calcite-slider's histogram).

**Comment by jcfranco** [comment]
Discussed with @benelan and @macandcheese during triage and decided we should refactor `calcite-graph`'s styling so that it is full-width by default.

**Comment by benelan** [comment]
verified on `beta.75` https://codepen.io/benesri/pen/GROgvRJ
