### ISSUE TITLE
Enhancement: Input - support "inputmode"

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#2949]
### Description
As a follow up to https://github.com/Esri/calcite-components/issues/2726, we should add support for inputmode: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

### Acceptance Criteria 
inputmode is a usable attribute on the input component

#### Which Component
Input

#### Example Use Case
Implementer should have control over the type of inputmode 

#### Related

#2949

**Comment by jcfranco** [comment]
Verified with https://codepen.io/jcfranco/pen/wvqXrrb?editors=1000 on an iOS device.
