### ISSUE TITLE
Bug: Input type submit should not be supported

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#2952]
### Actual Behavior

Setting type="submit" breaks the calcite-input component. [Submit](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit) should not be supported at this time. There is no submit value option in our [input doc](https://developers.arcgis.com/calcite-design-system/components/input/#component-api-properties-type).

### Expected Behavior
If type="submit", don't try to use the native submit functionality

### Reproduction Steps or Sample
https://jsbin.com/fuyiyewiji/edit?html,output

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.63`

- [x] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
Closing. The `submit` type is not supported in the doc, we have no plans for it and type-wise it's not a valid value.
