### ISSUE TITLE
Bug: calcite-tip heading displaying past tip border

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2961]
![image](https://user-images.githubusercontent.com/44481292/131756537-779797d4-f2bb-427d-bcc3-13353cfe731c.png)

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by asangma** [comment]
This should be straightforward fix.

**Comment by asangma** [comment]
@benelan I can knock this out real quick if you want me to take it.

**Comment by benelan** [comment]
@asangma All yours!

**Comment by asangma** [comment]
@benelan Assigning to you if you wanna verfee or pass it to someone else to do so.

**Comment by AdelheidF** [comment]
Using beta.64 it looks good now. Thanks

![image](https://user-images.githubusercontent.com/44481292/133291208-97ebae00-85b2-4d95-9f81-79185fd56860.png)
