### ISSUE TITLE
Tooling: create GitHub Action to make sure new bug issues have samples

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#2962]
## Summary 
We will now be requiring sample code to reproduce bug issues. The issue template will say this, but I will make a GH Action just in case. The action should: 
1. check for no link to sample code (codepen/jsbin/jsfiddle/etc)
2. automate comment / add needs more info label if there is no sample
3. if no new comment with URL after 5 days, close issue with comment
4. if follow up comment has url meeting criteria, remove needs more info, don't close.

## Measure of Success 
A working GH action for the workflow above

**Comment by benelan** [comment]
Installed! @julio8a or @jcfranco, can I get a verifier

**Comment by julio8a** [comment]
🔥 verified on master
