### ISSUE TITLE
Tooling: create GH Action to automatically add the current milestone to PRs

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#2964]
## Summary 
We now (#2954) have an action to add the proper labels to PRs. Next up is the current milestone. I'll likely need to write something that uses [date-fns](https://date-fns.org/) to check which date range of the milestone titles we are currently in.

## Measure of Success 
A working GH Action that adds the current milestone to PRs

### Resources 
[This action](https://github.com/Code-Hex/auto-milestone-binder) adds milestones based on the [smallest semver](https://github.com/Code-Hex/auto-milestone-binder/blob/master/src/main.ts#L39-L46). I can probably steal most of that code and switch out the [version comparing](https://www.npmjs.com/package/compare-versions) to [date checking](https://date-fns.org/v2.23.0/docs/isWithinInterval).

**Comment by benelan** [comment]
Installed. @jcfranco or @julio8a, next time one of you makes a PR, can you verify by making sure the current milestone is added?

**Comment by julio8a** [comment]
verified on latest created PR
