### ISSUE TITLE
Research: Review spacing and scale through components

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#2972]
### Background 
Our components have some spacing, alignment, and font size discrepancies.
And those discrepancies also appear across different scales.

As discussed by the team, we need to review our components.

Primary tasks per component would be
* review spacing values and look for divergent values
* look for inconsistencies in scale properties that are rendered internally (e.g. Action rendering Icon)
* note where components are setting fixed widths or heights and not relying on content and spacing

### Desired Outcome 
Have a simple spacing and font-size pattern that changes in a predicable way across scales.

The components to be reviewed
(will add as missing ones are discovered)

### A
- [x] accordion
  - [x] accordion-item
- [x] action
- [x] action-group
- [x] action-menu
- [x] action-pad
- [x] action-bar
- [x] alert
- [x] avatar

### B
- [x] block
- [x] block-section
- [x] button

### C
- [x] card
- [x] checkbox
- [x] chip
- [x] color-picker
  - [x] color-picker-hex-input
  - [x] color-picker-swatch
- [x] combobox
  - [x] combobox-item

### D
- [x] date-picker
  - [x] date-picker-day
  - [x] date-picker-month
  - [x] date-picker-month-header
- [x] dropdown
  - [x] dropdown-group
  - [x] dropdown-item

### F-H
- [x] fab
- [x] filter
- [x] flow
- [x] graph
- [x] handle

### I
- [x] icon
- [x] inline-editable
- [x] input (including all the types)
- [ ] input-date-picker
- [x] input-message
- [ ] input-time-picker

### L
- [x] label
- [x] link
- [x] list
  - [x] list-item
  - [x] list-item-group
- [x] loader

### M-O
- [x] modal
- [x] notice
- [x] option
- [x] option-group

### P
- [x] pagination
- [x] panel
- [x] pick-list
  - [x] pick-list-item
  - [x] pick-list-item-group
- [x] popover (and popover-manager?)
- [x] progress

### R
- [x] radio
- [x] radio-button
- [x] radio-button-group
- [x] radio-group
- [x] radio-group-item
- [x] rating

### S
- [x] scrim
- [x] select
- [x] shell
- [x] shell-center-row
- [x] shell-panel
- [x] slider
- [x] sortable-list
- [x] split-button
- [x] stepper
  - [x] stepper-item
- [x] switch

### T1
- [x] tabs
  - [x] tab-nav
  - [x] tab-title
  - [x] tab
- [x] tile
- [x] tile-select
- [x] tile-select-group
- [x] time-picker

### T-V
- [x] tip
- [x] tip-group
- [x] tip-manager
- [x] tooltip (and tooltip-manager?)
- [x] tree
  - [x] tree-item
- [x] value-list
  - [x] value-list-item

### Functional components
Not sure if we need to look at these, but ¯\_(ツ)_/¯.

- [ ] ExpandToggle
- [ ] Heading

**Comment by asangma** [comment]
cc @macandcheese

**Comment by asangma** [comment]
This is somewhat related to the research project for [cascading styles](#2868) (e.g. scale).
It will help that project if we have highly consistent (particularly mathematically consistent) pattern for how spacing changes across scales.

**Comment by asangma** [comment]
@benelan Updated the list with all the things. I think it's a complete list.

**Comment by benelan** [comment]
@asangma once you figure out what the spacing should be I can go make the manual changes for you.

**Comment by asangma** [comment]
@macandcheese I chunked up the list some. If you wanna take a chunk, put your name next to the heading.

**Comment by benelan** [comment]
@macandcheese and @asangma, I put together a table to keep track of the components' spacing/scale once you start working on this issue.

https://github.com/Esri/calcite-components/wiki/Scale-Spacing-Table

**Comment by asangma** [comment]
Yew! Done (enough).

**Comment by geospatialem** [comment]
Completed, and will be tracked via the above 6558 for inclusion.
