### ISSUE TITLE
Docs: add missing default slots

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#2974]
### Description 
The following components have undocumented default slots that need to be documented. We decided that the default slot should be the first one so I will go through all of the components to fix that in this issue as well.

### Which Component
```
calcite-accordion
calcite-accordion-item
calcite-button
calcite-checkbox
calcite-chip
calcite-combobox
calcite-combobox-item
calcite-combobox-item-group
calcite-dropdown
calcite-dropdown-group
calcite-dropdown-item
calcite-input-message
calcite-label
calcite-option-group
calcite-panel
calcite-popover
calcite-radio-button-group
calcite-radio-group
calcite-scrim
calcite-select
calcite-split-button
calcite-stepper
calcite-stepper-item
calcite-tab
calcite-tav-nav
calcite-tab-title
calcite-tabs
calcite-tile-select
calcite-tile-select-group
calcite-tip
calcite-tip-group
calcite-tooltip
```

### Resources 
**Related Issue:**: #2807

**Comment by macandcheese** [comment]
Following up re: Teams chat about ‘action’ - we should also make sure the verbiage used for default slot documentation across the all components is generalized and made consistent.

**Comment by benelan** [comment]
@macandcheese yeah this issue is part of an upcoming epic already planned out for syntax/verbiage consistency throughout usage, prop, and slot doc

**Comment by jcfranco** [comment]
`calcite-checkbox` is missing its default slot. The rest look good! I'll create a follow-up issue for checkbox.

**Comment by jcfranco** [comment]
Actually, after looking at the implementation and stories, checkbox's slot appears to be internal and should not be doc'd.

**Comment by jcfranco** [comment]
@benelan Can you confirm? ☝🏼

**Comment by benelan** [comment]
@jcfranco yeah I saw the slot but I don't think we want users putting anything in there so I left it out of the doc.
