### ISSUE TITLE
Enhancement: Alert - remove bespoke mobile styles

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#2979]
### Description
Let’s remove our subtle mobile styling change for Alerts. Currently they dock at the bottom which can cause them to be missed, or placed too close to the bottom of phones where swipes for OS functions may be used.

### Acceptance Criteria 
Remove the media query styles.

### Relevant Info 
Came up as part of larger discussion re/mobile. Certain components justify mobile styling (a docked modal, for instance), but this adjustment seems superfluous and makes alerts harder to see.

#### Which Component
Alert

**Comment by benelan** [comment]
verified on `beta.68`
