### ISSUE TITLE
calcite-button: icon disappears when the label has not enough space

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#299]
I'm adding 2 calcite-buttons in the smartMapping gallery.

If the panel is wide enough I get this
![image](https://user-images.githubusercontent.com/44481292/72846775-19725a00-3c56-11ea-9e0f-fdf4fbdb3079.png)

If the panel is smaller (on a smaller screen) I get this
![image](https://user-images.githubusercontent.com/44481292/72848177-e1b8e180-3c58-11ea-96f8-2d1a120ef7f3.png)
and eventually this (Surface like screen size)
![image](https://user-images.githubusercontent.com/44481292/72846748-09f31100-3c56-11ea-93df-fbc80e790f8f.png)

And if the label is even longer I get this
![image](https://user-images.githubusercontent.com/44481292/72846570-b254a580-3c55-11ea-99bb-f0234e8781b1.png)
and this
![image](https://user-images.githubusercontent.com/44481292/72848306-2a709a80-3c59-11ea-9ff4-ca08c847a5b5.png)

![image](https://user-images.githubusercontent.com/44481292/72846938-69512100-3c56-11ea-9158-baf79195546b.png)

Changing them to scale=s shows it like this
![image](https://user-images.githubusercontent.com/44481292/72847138-cb118b00-3c56-11ea-9ad3-34a90de0e19f.png)
![image](https://user-images.githubusercontent.com/44481292/72847200-e7adc300-3c56-11ea-808f-a6120b764751.png)
Should the label of the pretty high Field button move to the middle?
![image](https://user-images.githubusercontent.com/44481292/72847754-082a4d00-3c58-11ea-912f-3db69a16520a.png)

Using 1.0.0-beta.16

cc @asangma

**Comment by macandcheese** [comment]
Thanks for reporting - I'll add some fallbacks to vertically align side-by-side button text and maintain the size of the icon - eventually the icon will get a bit of a refactor to use the new `calcite-icon` component that should help as well: https://github.com/Esri/calcite-components/issues/297

**Comment by AdelheidF** [comment]
Looks good now. Thanks.

![image](https://user-images.githubusercontent.com/44481292/73293441-c1d57080-41b8-11ea-84fb-e42e1b97fac3.png)

![image](https://user-images.githubusercontent.com/44481292/73293345-918dd200-41b8-11ea-939f-5448f851563f.png)

![image](https://user-images.githubusercontent.com/44481292/73293376-a5d1cf00-41b8-11ea-8fc1-9feb0ecedae0.png)
