### ISSUE TITLE
Enhancement: Ability to customize borders on calcite-shell contents

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#2992]
### Description
We would like a way to remove the borders from the main content slot in calcite-shell. At the moment there is a 1px top and bottom border on the "main" div and a 1px left and right border on the "content” div within that. A few reasons we don't want these borders:
- Our header has its own border style, so the content doesn’t need a top border
- The primary shell panel can be hidden, but when it is there is a still a border on the left of the content. Using the shell in light theme, this can look pretty bad when the content is dark because the border is light gray. It would be better to have a right border on the panel instead so it’s only visible when the panel is visible
- It would look better without the border below the action bar 
![image](https://user-images.githubusercontent.com/14304581/132568611-f38908c9-0481-4eac-9b97-e8f439a9579a.png)

### Acceptance Criteria 
Ability to toggle off the borders on the content or override style without needing to manipulate the styles in the shadow DOM.

#### Which Component
calcite-shell

**Comment by benelan** [comment]
Hi @ellenupp, you can set the color of the border to transparent, which effectively removes the border. Here is a sample:
https://codepen.io/benesri/pen/ZEyLZJj

Here is some information about the calcite color css vars:
https://developers.arcgis.com/calcite-design-system/foundations/colors/#themes

**Comment by ellenupp** [comment]
Thanks @benelan, I had explored this option before but it's not an ideal solution. When the color is set to transparent, there is still 1px space there so for example you still get the gap below the action bar. Also I wouldn't want to override the border color for the whole shell (since I do need borders elsewhere), only on those shadow divs- but I can't target those with CSS unless I'm missing something here.

**Comment by benelan** [comment]
Some components have a prop to remove the border, like `appearance='minimal'` for [color picker](https://developers.arcgis.com/calcite-design-system/components/color-picker/#component-api-properties-appearance). Is that what you are looking for, except only the top and bottom border?

**Comment by ellenupp** [comment]
Something like that would be great, but for all the borders around the content not just top/bottom.

**Comment by benelan** [comment]
@ellenupp, can you please provide some more information about your use case, and if possible a codepen that demonstrates the issue?

**Comment by ellenupp** [comment]
[Example 1](https://nickelbuilder.esri.com/buildStore/PR-5357/dashboards/76f961fb0eea4cdbaa5f2b13ba3cd496#mode=edit)
We are always using the shell in light mode but the contents (i.e. a dashboard) could be in light or dark mode. The problem is easier to see when the contents is in dark mode as in this sample. Hit shift+S to switch from edit to view mode. In view mode, the content is still in the shell but we are hiding the panel and header. The light grey border from the shell is still visible. This is not desirable. In view mode we don't need borders at all and in edit mode we can achieve the desired look by putting a bottom border on the header and a right border on the primary (left) shell panel. 

[Example 2](https://codepen.io/ellupp/pen/JjJwbJM?editors=1000)
We are using a shell in a modal. The modal header/footer have borders as does the shell content, which results in double horizontal borders above/below the shell contents.

**Comment by asangma** [comment]
@benelan I realized that the update assumes that
- a ShellPanel in `slot="primary-panel"` has `position="start"`
- a ShellPanel in `slot="contextual-panel"` has `position="end"`

But I need to think I need to think through how to target those styles since the `slot` names are defined in Shell.

**Comment by asangma** [comment]
For the time being though, I'm not sure how many users are flipping those slots and positions.

**Comment by benelan** [comment]
Thanks Alan! @ellenupp can you test with your repro case using `@next` to make sure its working the way you want?

**Comment by ellenupp** [comment]
Yeah this works great, thank you! I notice there is a border around the action bar now though I can easily target that to remove it.

**Comment by benelan** [comment]
Thanks for testing! @asangma is the border around the action bar by design or a side effect?

**Comment by asangma** [comment]
@ellenupp I believe you should be able to add a block to your app's stylesheet and do something like this. Let me know if that works.

```scss
.no-border {
  border: none;
}
```

```html
<calcite-action-bar slot="action-bar" class="no-border">
  <!-- actions -->
</calcite-action-bar>
```

**Comment by benelan** [comment]
Thanks for the confirmation Alan! This is verified on next.
