### ISSUE TITLE
Bug: calcite-color-picker ignores initial value

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2994]
beta.63

```
<calcite-color-picker
            scale="m"
            value="#FF0000"
            format="hex"
            appearance="default"
            hideSaved="true"
          ></calcite-color-picker>
```

any hex color value displays blue swatch
<img src=https://user-images.githubusercontent.com/44481292/132595662-a213ad95-5635-4999-a581-d46231a49545.png width=300/>

I tried to 're-set' the value again in ref, but this doesn't help.

If I remove `format` it works fine.

Repro case: https://codepen.io/jcfranco/pen/dyRvVpX?editors=1000

**Comment by jcfranco** [comment]
Installed.

**Comment by AdelheidF** [comment]
Tested with beta.64, all good now. Thanks.
