### ISSUE TITLE
Introduce Autoprefixer into the build process

### ISSUE THREAD

**Issue by pr3tori4n** [Esri/calcite-components#30]
This has 2 major benefits.
1) It eliminates developers needing to intentionally read/write (while deving and code reviewing) vendor prefixes for CSS properties. Less work!
2) It prevents browser-specific bugs from a vendor prefix being accidentally omitted or typo'd.

https://github.com/postcss/autoprefixer

**Comment by paulcpederson** [comment]
In the generated dist files, the styles are prefixed, so marking this as closed.
