### ISSUE TITLE
Bug: calcite-input type=number not always updating value in box

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3003]
beta.63

When updating a input box value programmatically the value inside the input box does not always update.
In the test case below I use it for the valid range of values, but it is not specific to that case.

I can reproduce it with SymbolStyler and I built a simple codepen.

The value of that input box should never be greater than 5. If the user types in a number that's bigger I want to set it back to 5. That works the first time, but not after. E.g. enter value 6, you can see the value changing back to 5 and below the input box I display what I then get from the input node as a value. Now enter 6 again or another number greater than 5 and you can see the value in the box stays at 6, but the node.value displayed below is correctly 5.

https://codepen.io/afreitag/pen/vYZxrmx?editors=1010

**Comment by driskull** [comment]
I think we discussed this previously... We need better error states for components where users can input data.

I don't think we want to "reset" values input by a user but display that the component has an invalid value.

**Comment by AdelheidF** [comment]
> We need better error states for components where users can input data.

Yes, this is another issue. The issue here is just that when I programmatically update values in the input they don't show.
I happen to use them for the min/max range because that's not implemented yet.

This other issue here got closed even though it's still valid too: https://github.com/Esri/calcite-components/issues/2477

**Comment by AdelheidF** [comment]
Looks good to me.

**Comment by benelan** [comment]
Thanks for checking, looks good to me as well. verified on next
