### ISSUE TITLE
New component: Calcite-avatar

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#301]
We should standardize the use and design of avatars across our apps and products. Hopefully this can provide multiple scale options, a consistent fallback "no photo" icon, "Initials with BG color" as an option, "avatar stack", etc.

https://uniform.hudl.com/components/avatars/user/design#Style

**Comment by TheBlueDog** [comment]
In Tracker and Workforce, its important that users who don't have a photo, we need to use the initials. We have UIs where many users are either on a map, in a list or both.

**Comment by paulcpederson** [comment]
@TheBlueDog yeah I think the plan is to dynamically generate a thumbnail with user initials/unique+consistent background color generated off their id. This is a requirement for Online as well.

**Comment by paulcpederson** [comment]
Hey, this is a thing now!
