### ISSUE TITLE
Enhancement: Improve hover transition style of icon / text in Radio Group

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#3028]
### Description
Currently the icon has a transition but the color property of the text does not. It's more obvious in dark theme:

https://user-images.githubusercontent.com/4733155/133157270-3bd8b791-4227-46b4-a3ea-6cd97cd10b0d.mp4

These should ideally be the same, so there isn't a choppy appearance when the icon transitions to the hover state color more slowly.

### Acceptance Criteria 
The icon and the text color transition in lockstep.

#### Which Component
Radio Group

**Comment by benelan** [comment]
verified on `beta,68` in the doc
https://developers.arcgis.com/calcite-design-system/components/radio-group/#sample
