### ISSUE TITLE
Enhancement: Add a slot in List Item for specialized content or a slot for label and a slot for description

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#3032]
### Description

Currently, the only way to have content is by providing label and/or description.
It would be useful to also support a slot 'content' for specialized content.
In my particular case, we would like a second line for the description:

Label
Description 1
Description 2

#### Which Component

calcire-list-item

#### Example Use Case

Support more specialized content for list item

**Comment by geospatialem** [comment]
Verified on `next.664` with the [following Codepen](https://codepen.io/geospatialem/pen/zYaXovV), where the `content` slot will override the `label` and `description` props.
