### ISSUE TITLE
Enhancement: Alert - provide various placement options

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-components#3033]
### Description

We would like to be able to place alerts in different locations. 

### Acceptance Criteria 

- `<calcite-alert>` should have a property/attribute to specify its placement.
- Valid options could be similar to what we have to tooltips.

#### Which Component

`<calcite-alert>`

#### Example Use Case
- An app with a sidebar on the left side would like to place the alerts on the bottom-right corner.
- An app with a bottom drawer would like to display the alerts on the top of the screen.

<sub>SVCH</sub>

**Comment by macandcheese** [comment]
I think this is reasonable. 

I wonder if a slot within the shell makes sense for this, so the positioning could be controlled absolutely. Currently, it's a fixed position item which prevents the alert from staying affixed to a shell that is not full-screen (which, may be good in some cases, and not in others, so some affordance to choose this?)

I feel like we'd probably want to limit the options to top center/start/end, bottom center/start/end.

Another thing to consider would be what happens on mobile - currently we constrain max width and start / end positioned alerts at small scale may just need to become full-width.

**Comment by macandcheese** [comment]
I mentioned #2835 above - while this issue may inform that one, this one can proceed - that's not a blocker and this is a reasonably simple add.

**Comment by macandcheese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Alert positioning Issue](https://trello.com/c/tGxUFyLG/37-alert-positioning-issue)

**Comment by benelan** [comment]
verified on beta.74 in the doc sample https://developers.arcgis.com/calcite-design-system/components/alert/#sample
