### ISSUE TITLE
Bug: [color-picker] dragging the color field thumb gets offset by content above when placed in a component's shadow DOM

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3035]
### Actual Behavior

When the color-picker is placed in a shadow DOM, any content above will mess up the positioning used when dragging the color field around.

### Expected Behavior

The color-picker's color field drag interaction should behave consistently regardless of where it is placed (light or shadow DOM).

### Reproduction Steps or Sample

1. Open https://codepen.io/jcfranco/pen/xxrXEPr?editors=0010
2. Click on the color field, press and move the pointer around
3. Notice how the position is offset by the container above

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.61`

- [x] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
Installed

**Comment by benelan** [comment]
Verified in beta.65 using the codepen in the issue.
