### ISSUE TITLE
Slider enhancement: Explicit value entry

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#304]
It'd be nice to include the ability to enter a value as part of this component, it's something that causes apps to need to build their own interpretations...

Example from MVB cc @asangma :

<img width="294" alt="Screen Shot 2020-01-23 at 3 08 46 PM" src="https://user-images.githubusercontent.com/4733155/73032088-e0232100-3df2-11ea-8d79-b1270224a27a.png">
<img width="294" alt="Screen Shot 2020-01-23 at 3 08 58 PM" src="https://user-images.githubusercontent.com/4733155/73032089-e0232100-3df2-11ea-8465-9d4cfc07cb93.png">

**Comment by bstifle** [comment]
this was a design we chatted on too

![image](https://user-images.githubusercontent.com/14083530/82708521-4a2dc480-9c33-11ea-880a-ed7de541a784.png)

**Comment by macandcheese** [comment]
@patrickarlt could you post a screenshot of the requirement in the new pricing selector you mentioned?
