### ISSUE TITLE
Enhancement: [Rating] Add ability to clear a user-set rating

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#3043]
### Description
Currently there is no built-in functionality to allow a user to clear the rating.

### Acceptance Criteria 
A user is able to clear their rating. 

### Relevant Info 
The suggestion is to allow a click, space, or enter interaction on the current value star to "reset" the value.
If this is the new default behavior, should a "disable this" prop be available?

#### Which Component
Rating

--
Follow up issue from Teams chat: https://teams.microsoft.com/l/message/19:646421511c3c4f2090210d9f493856cf@thread.skype/1631648728148?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1631648728148&teamName=Calcite%20Design%20System&channelName=Calcite%20Design&createdTime=1631648728148

cc @driskull @benelan

**Comment by benelan** [comment]
"indelible" is a prop name that comes to mind but we might need a more common word.

**Comment by driskull** [comment]
It might be better to add a prop `required` in which case unset is disabled.

**Comment by geospatialem** [comment]
Verified on `beta.84` ✔️ 
![verify-rating-clear](https://user-images.githubusercontent.com/5023024/178603120-5377717d-496d-4a44-b762-74f647f49c90.gif)
