### ISSUE TITLE
Bug: Dropdown wrapper causes UI bug when combined with a Panel in a PickList

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3048]
### Actual Behavior
Because the `calcite-dropdown-wrapper` node still has a height when its hidden, it can cause height calculation issues in small containers.

### Expected Behavior
Dropdown item container shouldn't have a height when hidden.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/mtb-alan/pen/wvePErY

1. Use filter to search for "lisa"
2. Observe as the items disappear.
3. Note that a scrollbar appears but there doesn't appear to be content.
4. Inspect the sorting action and search in the browser's inspector for "calcite-dropdown-wrapper"

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by asangma** [comment]
@jcfranco @julio8a  @benelan This could use some priority. The combo of PickList in a Panel (often in a Popover) with actions is a regular occurrence in existing and upcoming interfaces.

**Comment by benelan** [comment]
@asangma This sprint is already quite hefty, I'll put it in the next one

**Comment by asangma** [comment]
Thanks @benelan!

**Comment by anveshmekala** [comment]
issue  #3071  resolved this bug.

**Comment by benelan** [comment]
verified on beta.75
