### ISSUE TITLE
Calcite Tree Item: Every item has a large inline style tag

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#305]
If you inspect the shadow root for `calcite-tree-item` in the demo (https://esri.github.io/calcite-components/?path=/story/tree--simple), you'll see that every `calcite-tree-item` has a `<style>` tag with a lot of css. I'm not super familiar with shadow DOM and web components, but that seems like it adds a lot of duplication and increases the size of the DOM significantly.

Considering that `calcite-tree-item` is a sub-component of `calcite-tree` and is not intended to be used outside of it, is there a need for the tree item to have its own encapsulated css? Maybe its css could be moved up to the `calcite-tree` css. That way it would appear only once per tree instead of once per item.

cc @patrickarlt @oknoway

**Comment by julio8a** [comment]
@patrickarlt, assigning to you since you built calcite-tree.

**Comment by paulcpederson** [comment]
This should be fixed on the `master` branch now. Basically we were injecting all of the `calcite-` css variables into every component. Now we are declaring them once globally, this greatly reduces the amount of css within each component.
