### ISSUE TITLE
Docs: List the allowed values for the placement attribute for `calcite-popover` and `calcite-tooltip`

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#3051]
### Description 
In the developers doc, the allowed placement values for a calcite popover/tooltip are not listed. It is difficult to tell what the placements are without going to popperjs and looking.

https://developers.arcgis.com/calcite-design-system/components/popover/#component-api-properties-placement
![image](https://user-images.githubusercontent.com/52869490/133527378-9eb4080a-3ef7-4bf0-8157-90c484845693.png)

### Which Component
calcite-popover, calcite-tooltip
### Resources 

This also occurs in the storybook.

**Comment by macandcheese** [comment]
cc @caripizza - related to our previous documentation site issues.

**Comment by benelan** [comment]
@ethanbdev, It's in storybook, you can get the options there for now: https://esri.github.io/calcite-components/?path=/story/components-popover--simple

**Comment by macandcheese** [comment]
For the documentation site, we looked at using the @see tag in the docs-json output, but that would just send people off the documentation site anyway. 

If there's a way to get the values into that output file, we can then pull them into the docs site.

**Comment by benelan** [comment]
I'll look into that @macandcheese

**Comment by ethanbdev** [comment]
> @ethanbdev, It's in storybook, you can get the options there for now: https://esri.github.io/calcite-components/?path=/story/components-popover--simple
> ![image](https://user-images.githubusercontent.com/10986395/133528529-a4e204fe-04b4-47a8-bfc8-03f11db08a77.png)
> 

Ah thanks, I didn't see them in the readme and just assumed. I'll pass it along!

**Comment by macandcheese** [comment]
@ethanbdev I've opened a tracking issue for this on the developer site side of things: https://github.com/ArcGIS/afd-calcite-documentation/issues/203. 

This should help clean up other instances of properties (and some event detail items) like this across components besides the ones shown here.

**Comment by macandcheese** [comment]
@ethanbdev This PR https://github.com/ArcGIS/afd-calcite-documentation/pull/204 should resolve the documentation site side of things - we should be able to verify the changes after next week's Developer site deployment.

**Comment by macandcheese** [comment]
@ethanbdev This PR https://github.com/ArcGIS/afd-calcite-documentation/pull/204 should resolve the documentation site side of things - we should be able to verify the changes after next week's Developer site deployment.

@benelan feel free to adjust tags and labels as needed based on the above.

**Comment by benelan** [comment]
verified in next sites afd
