### ISSUE TITLE
Enhancement: [Combobox] - Always display chevron, regardless of selection-mode

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#3055]
### Description
Currently, the chevron affordance is only displayed for `selection-mode="single"`. It strikes me as a little strange to have it for one selection mode, but not others. I understand that when a chip is in a combobox, that affordance may become superfluous, but at idle, the selection mode dropdowns behave the same, - I'd like to update them all to have the chevron at idle.
 
This is consistent with how Spectrum, Material UI, etc., function

### Acceptance Criteria 
Chevron is used consistently across all combobox types.
Ensure there is internal padding to prevent chips or text strings from overlapping the chevron.

### Relevant Info 
Original Teams chat : https://teams.microsoft.com/l/message/19:646421511c3c4f2090210d9f493856cf@thread.skype/1631727331889?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1631727331889&teamName=Calcite%20Design%20System&channelName=Calcite%20Design&createdTime=1631727331889

#### Which Component
Combobox

**Comment by benelan** [comment]
@macandcheese can you please verify this one for me?

**Comment by caripizza** [comment]
Adding an update for posterity that @macandcheese clarified my question [above](https://github.com/Esri/calcite-components/issues/3055#issuecomment-940386487) isn't necessary for this one (the chevron will point downwards for now).

**Comment by benelan** [comment]
@macandcheese can you please verify this one for me?

**Comment by macandcheese** [comment]
@benelan lgtm
