### ISSUE TITLE
Bug: calcite-combobox should close with dropdown open when clicking on box

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3058]
Click twice on the yellow highlighted area of the combobox. It should close the dropdown on the second click.
If you do this to the also highlighted calcite-select box for overlay-positioning then this is how it works there.

https://developers.arcgis.com/calcite-design-system/components/combobox/
![image](https://user-images.githubusercontent.com/44481292/133695041-56692161-6326-4e83-8395-e1edfbc165b2.png)

### Reproduction Steps and Sample

_Sample_:

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by AdelheidF** [comment]
from @kevindoshier 

https://codepen.io/kevindoshier/pen/YzQYRZm

**Comment by macandcheese** [comment]
This is a reasonable enhancement (not sure if it's a bug - just never addressed in design or implementation). This change would match how `calcite-dropdown` works in regards to the trigger being a toggle (as well as anywhere else on the page).

Regarding `calcite-select`, it looks like our "cursor: pointer" that is set for an open `calcite-select` persists across other elements on the page. It should probably revert to "cursor:normal" like a native select while not hovering over the element's container. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by macandcheese** [comment]
We should match the behavior requested in the OP - example of "click on input to close" : https://mui.com/components/autocomplete/

**Comment by jcfranco** [comment]
I believe this got fixed in beta.81 (via https://github.com/Esri/calcite-components/pull/4218): https://codepen.io/jcfranco/pen/zYpbbKX.

The doc example now behaves as this issue expected.

**Comment by AdelheidF** [comment]
looks good, closing
