### ISSUE TITLE
Bug: calcite-block-section long header text does not wrap

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3069]
https://esri.github.io/calcite-components/?path=/story/components-block--basic

- add `width: 400px;` to the `calcite-block` element
- Change `Animals` text and make it longer, make sure not to add spaces

![image](https://user-images.githubusercontent.com/44481292/133864862-5f708f92-cee5-4ba3-be33-b59beb669702.png)

`calcite-block` handles this fine.

### Actual Behavior

header does not wrap

### Expected Behavior

header should wrap

### Reproduction Steps and Sample

https://esri.github.io/calcite-components/?path=/story/components-block--basic

- add `width: 400px;` to the `calcite-block` element
- Change `Animals` text and make it longer, make sure not to add spaces

### Relevant Info

_Version_: `@esri/calcite-components@beta.65`

- [ ] CDN
- [ ] NPM package

**Comment by benelan** [comment]
verified on `beta.68`
https://codepen.io/benesri/pen/bGrYVvJ?editors=1000
