### ISSUE TITLE
Enhancement: calcite-date-picker - easy way to change year

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#307]
If you start e.g. with a date like this:

![image](https://user-images.githubusercontent.com/44481292/73210832-ecafbe00-40ff-11ea-9dd9-1250229c1106.png)

And you want to change the year to 1900, there is no easy way to do this.

I can click on this arrow button through 100 years and 12 months until I reach 1900.
![image](https://user-images.githubusercontent.com/44481292/73211268-c4748f00-4100-11ea-8fb4-107ef77fba65.png)

If I backspace once in the text box I get this
![image](https://user-images.githubusercontent.com/44481292/73211021-4617ed00-4100-11ea-93bb-0bed0ff2117b.png)

If I backspace twice or more times I get this
![image](https://user-images.githubusercontent.com/44481292/73211073-621b8e80-4100-11ea-8cb8-f2b85e086b7c.png)

If I highlight the year to erase it to replace it with 1900 I get this:
![image](https://user-images.githubusercontent.com/44481292/73211169-9000d300-4100-11ea-9ebe-c93c271eeead.png)
![image](https://user-images.githubusercontent.com/44481292/73211195-a1e27600-4100-11ea-8dfd-fbe6fdf18a52.png)

The only way I can make it work right now is if I place my cursor in the front of the year 2000 text and insert 1900 there to get the long number 19002000 and then I place my cursor 4 places to the right and hit delete 4 times.
![image](https://user-images.githubusercontent.com/44481292/73211461-2634f900-4101-11ea-9308-581baeaac73d.png)

**Comment by macandcheese** [comment]
@kumarGayu - I think the input used be of `type="date"` right?

**Comment by kumarGayu** [comment]
@macandcheese There was lot of features were not required and it was adding more pan for styling and it had diffrent behaviors in different browsers. o I prefered this but in this input i can put a pattern though.

**Comment by kumarGayu** [comment]
I will work on it this week or next week.

**Comment by paulcpederson** [comment]
This is going to be part of my date component updates / ie11 fixes

**Comment by paulcpederson** [comment]
In next release the parsing of the input has been improved

**Comment by AdelheidF** [comment]
(1)
I start with this:
<img src=https://user-images.githubusercontent.com/44481292/78846058-6cd78700-79bf-11ea-952c-4cc858a169de.png width=200/>

Then I hit backspace once:
<img src=https://user-images.githubusercontent.com/44481292/78846086-8ed10980-79bf-11ea-88f5-e021a381bdfc.png width=200/>

Then I enter a 0:
<img src=https://user-images.githubusercontent.com/44481292/78846123-a8725100-79bf-11ea-8bac-896acfd4bda1.png width=200/>

(2)
I start with this:
<img src=https://user-images.githubusercontent.com/44481292/78846302-2afb1080-79c0-11ea-9117-8bec71c19829.png width=200/>

Then I click on '31':
<img src=https://user-images.githubusercontent.com/44481292/78846326-3d754a00-79c0-11ea-9db6-31c893536a7f.png width=200/>

**Comment by AdelheidF** [comment]
Never mind, missed the change to event.detail.

**Comment by AdelheidF** [comment]
I can't figure out where where the 5 year difference comes from. 
This is the value that's being entered in the value property: `2017-07-07`, no min or max.

<img src=https://user-images.githubusercontent.com/44481292/78847406-88449100-79c3-11ea-91e2-e1ff7d4b08d6.png width=200/>

**Comment by paulcpederson** [comment]
what browser, locale, etc?

**Comment by AdelheidF** [comment]
Sorry, used the wrong format for min/max.

**Comment by paulcpederson** [comment]
OK, cool, yeah the examples were all using `MM/DD/YYYY` in the docs as well 🤦‍♂

**Comment by AdelheidF** [comment]
If I erase the complete date string I see this text: mm/dd/yyyy, 2 characters for day.

(1)
I started with a date like `11/20/2000` and tried to replace the '11' with '09', but as soon as I entered the '0' the date jumped to this `10/31/2000`. 

(2)
I started with `11/20/2000`, then removed the '11' and entered 0, which made the date jump to `1/20/2000`, then I removed the 1 and entered 0 again.
<img src=https://user-images.githubusercontent.com/44481292/78848617-284fe980-79c7-11ea-8b73-3573388cfb33.png width=150/>

**Comment by AdelheidF** [comment]
I'm not sure if this is an issue in RangeSlider or the date component.

<img src=https://user-images.githubusercontent.com/44481292/78849028-36ead080-79c8-11ea-8b26-90b6abddf0fc.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/78849046-45d18300-79c8-11ea-87c6-19b33690acbf.png width=170/>

The slider handle has a z-value of 7.

**Comment by paulcpederson** [comment]
I think all of these should also be in the next release as well.

**Comment by AdelheidF** [comment]
verified with MapViewer
