### ISSUE TITLE
Enhancement: Block loading state when not open

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3075]
### Description
Add a way to see if Block is `loading` when its not `open`.

### Acceptance Criteria 
* Design should use existing slots

#### Which Component
Block

#### Example Use Case
Have a consistent design for a Block that is in a loading state but is not open.

#### Proposed design
![image](https://user-images.githubusercontent.com/12503298/134081542-8a48c08d-03db-491a-b853-942c51e93fe6.png)

* Use the same slot that other statuses use.
* Loading indicator rotates
* If Block has `loading` prop, `status` is ignored.

**Comment by benelan** [comment]
verified on `beta.68` in the doc
https://developers.arcgis.com/calcite-design-system/components/block/#sample
