### ISSUE TITLE
Bug: calcite-date-picker not displaying days in correct columns

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#308]
The date numbers don't align with the days of the week if I make it fit in the panel with `width: 100%;`. 
Would be nice if there was an option to have a smaller version with less padding around the numbers.

I'm using calcite-shell and calcite-shell-panel on a Surface like screen. It handles the min width of the panel.

![image](https://user-images.githubusercontent.com/44481292/73212225-a019b200-4102-11ea-82b3-ec15056ee685.png)

**Comment by kumarGayu** [comment]
@julio8a do you want to take a look at this stylling?

**Comment by macandcheese** [comment]
@kumarGayu I think we just need to make sure the dates shrink in an appropriate way to stay aligned with the date labels on top...

**Comment by AdelheidF** [comment]
This is how it looks with a small screen, Now it's cut off at the right side. That was the original issue that there is not enough width in the calcite-shell-panel on small screens.

<img src=https://user-images.githubusercontent.com/44481292/78845825-9643e300-79be-11ea-93ad-c8a789f8b7ba.png width=250/>

**Comment by paulcpederson** [comment]
I'd like to solve this with a `scale` prop as I think what you really want is a more compact UI.

Will also look at adding a max-width as well.

**Comment by AdelheidF** [comment]
On many screens there is enough space for the big calendar. Could it go off the width of the main date input box and make it not wider? Minimum width could be the smallest shell panel width.

**Comment by paulcpederson** [comment]
Yeah we can give the wrapper for the calendar a `max-width` of `100%`

**Comment by paulcpederson** [comment]
@AdelheidF so next release will have a `scale` prop which will make the whole ui more compact if you use `scale="s"`. The calendar width will be sized on the input, and should shrink down acceptably to very tight widths (~200px). After we release feel free to reopen if it doesn't work out for you :+1:

**Comment by AdelheidF** [comment]
verified in MapViewer
