### ISSUE TITLE
Discussion: Use specific named vars for tree functionality

### ISSUE THREAD

**Issue by oknoway** [Esri/calcite-components#310]
I'd like to propose undoing cd61aa071e3fb2014791015d7a6c37a0cddeb4f0

The new Developers site had been using the old vars (specifically `-calcite-tree-indicator-active` and `--calcite-tree-line-active` to style specific parts of the tree. We'd really like that option back.

Re: #298

**Comment by macandcheese** [comment]
Cc @julio8a for now can you revert the advice? Thanks... Moving forward in general we need a better story for overriding spot colors.

**Comment by julio8a** [comment]
I can add those CSS vars back and just have the value be `--calcite-ui-blue` does that work for you @oknoway?

**Comment by oknoway** [comment]
@julio8a That would be perfect. 👏

We're not currently changing `--calcite-tree-chevron-active`…

**Comment by macandcheese** [comment]
Resolved in https://github.com/Esri/calcite-components/pull/311
