### ISSUE TITLE
Bug: a range slider's minValue thumb should appear on bottom near max edge when handles collide

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#3101]
### Actual Behavior
In a `mirrored` range slider with `label-handles` ~

#### A.
When the minValue thumb is moved via keyboard or mouse towards the max edge, it's positioned **above** the maxValue thumb on the range with the maxValue thumb below (bug):

![image](https://user-images.githubusercontent.com/42423180/134575979-bb03d780-3789-409e-9405-f3962b3d0e7c.png)

#### B.
The `.hyphen` class gets added to the value handle label, instead of the minValue handle label.
The hyphenation that appears when the labeled handles collide on max edge currently targets the [`:after`](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-slider/calcite-slider.scss#L88) pseudo-element.

Here's how both the non-mirrored (left) and mirrored (right) range sliders appear which shows the UI bug:

![image](https://user-images.githubusercontent.com/42423180/134576694-ac018415-ce6d-4d11-ac74-b68f22c8713e.png)

(The above screenshots have a semi-transparent red color to articulate the minValue thumb.)

### Expected Behavior

In a `mirrored` range slider with `label-handles` ~

#### A.
When the minValue thumb is moved via keyboard or mouse towards the max edge, it's positioned **below** the maxValue thumb on the range with the maxValue thumb above (correct, ie., match non-mirrored behavior).

#### B.
The `.hyphen` class gets added to the minValue handle label.
The hyphenation that appears when the labeled handle thumbs collide on max edge targets the `:before` pseudo-element.

### Reproduction Steps and Sample

_Sample_:

1. https://codepen.io/caripizza-the-animator/pen/eYRLEXG

### Relevant Info

_Version_: `@esri/calcite-components@beta.65`

- [x] CDN
- [ ] NPM package

**Comment by caripizza** [comment]
I think I might have found an easy fix for this while working on #2457, so I'm going to take a stab at it.

**Comment by anveshmekala** [comment]
Currently, the hyphenation in slider is aligned vertically below the `minHandle` label which looks like a regression bug. Correct me if am wrong @asangma & @macandcheese 

Guessing it should look like below attached hyphenation for both mirrored and non-mirrored slider. Correct me if am wrong. 

![4E565FCB-B3F1-4AF8-9C72-A5571529BDD8_4_5005_c](https://user-images.githubusercontent.com/88453586/149043890-c227d15a-8788-4b41-929e-ceeab3c975f2.jpeg)

**Comment by jcfranco** [comment]
>  hyphenation in slider is aligned vertically below the minHandle label which looks like a regression bug.

I think this is indeed a regression. I believe the hyphenated parts always stayed aligned on the same level. @eriklharper Can you confirm?

**Comment by anveshmekala** [comment]
Screener run in PR #3813  bring ups an interesting edge case where the thumbs are aligned horizontally and overlapped in previous runs.  The description of this issue showcase thumb handles when overlapped align vertically.  Did the design changed  since the issue is created or we must be dealing with a regression bug .

**Comment by asangma** [comment]
Am I mistaken in thinking that the vertical stacking of the thumbs is an unintended result of the hyphen wrapping?
That is to say, when the two values are very close, should the thumbs have the same behavior that they have elsewhere on the slider, i.e. on top of each other?

**Comment by asangma** [comment]
As @jcfranco suggests

> I believe the hyphenated parts always stayed aligned on the same level.

The visual bug, i.e. the vertical stacking appears to be resulting from the hyphen in the `:after` wrapping.

I suggest updating the `.thumb .handle__label` display to be `flex` or some other solution to keep the `:after` from wrapping.

**Comment by anveshmekala** [comment]
Update on the issue:

When the thumbs are overlapped or colliding, they should be aligned horizontally(see screenshot below) rather than vertically as mentioned in the OG description and `hyphen` should be wrapped in between the handles rather than below the `minLabel`.
![D4A586B8-C13F-4F50-8C6A-9004CAB5B12D_4_5005_c](https://user-images.githubusercontent.com/88453586/149584232-ece8a0d9-1cdf-4cf5-ba8c-8faee25901c0.jpeg)


cc: @benelan

**Comment by benelan** [comment]
The functionality described in Anvesh's comment above is verified on `next`
