### ISSUE TITLE
Bug: Multiselect dropdown reverts to single select when remounted

### ISSUE THREAD

**Issue by jgibson02** [Esri/calcite-components#3102]
This may be specific to calcite-components-react

### Actual Behavior
When a multiselect dropdown is unmounted and remounted to the DOM, the calcite-dropdown-items seem to revert to single selection mode.

Before unmount:
![image](https://user-images.githubusercontent.com/5069711/134588856-197086c2-7649-4d31-9df8-14edbf77ff62.png)

After remount:
![image](https://user-images.githubusercontent.com/5069711/134588889-4dbc501a-eb27-4c58-9623-3ea5bf1a3a4e.png)

### Expected Behavior
calcite-dropdown-items remain in multiselect mode

### Reproduction Steps and Sample

_Sample_: https://codesandbox.io/s/calcite-components-dropdown-multiselect-revert-ykjul

1. Toggle the checkbox off then on to remount the component

### Relevant Info

Chrome

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [x] NPM package

**Comment by jcfranco** [comment]
This got fixed by https://github.com/Esri/calcite-components/issues/4215 (beta.80): https://codesandbox.io/s/calcite-components-dropdown-multiselect-revert-forked-qnvdg2?file=/src/App.js

Closing!
