### ISSUE TITLE
Bug: [Combobox] - Do not open dropdown when clicking on chip dismiss button.

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#3103]
### Description
Currently, if a user interacts with the dismiss button on a chip inside a combobox, the dropdown menu opens. 

### Acceptance Criteria 
The dropdown state should not be affected by interactions with the dismiss button of a chip.

#### Which Component
Combobox

**Comment by benelan** [comment]
The issue is reproducible in the doc:
https://developers.arcgis.com/calcite-design-system/components/combobox/#sample

1) Select a couple combobox items
2) Unfocus the dropdown
3) Close one of the chips and the dropdown will open

**Comment by macandcheese** [comment]
@benelan - Sorry for not having the example -  I had added a video, realized I uploaded the wrong video, edited the video out, had an issue with screen recording software, and forgot to re-add the example 😄 . Thanks for linking.

**Comment by benelan** [comment]
@macandcheese no worries, enhancements don't need samples. We just decided it was more of a bug so it asked for one when I changed it.

**Comment by benelan** [comment]
verified on beta.69
