### ISSUE TITLE
Bug: Can't type multiple zeros to create decimals when input < 1 for CalciteInput type=number

### ISSUE THREAD

**Issue by annelfitz** [Esri/calcite-components#3107]
### Actual Behavior

I am not able to type 0s after a decimal point if the input is less than 1. For instance, `0.01` or `0.505` is not a possible input, the 0s after the decimal place simply cannot be typed. I can access these numbers if I use the up/down arrows, but not by typing. This only occurs when the input is less than 1.

### Expected Behavior

I expect that I would be able to type zeros into the input box after a decimal place.

### Reproduction Steps and Sample

_Sample_:

1. https://codepen.io/annefitz/pen/RwgeKqZ
2. Try to type 0.01 -> the zero after the decimal will not type, instead you will get 0.1 in the input box
3. Try to type 0.505 -> you will only be able to type 0.55
4. When the input is greater than 1, there is no problem. For example, typing `1.01` gives me no problems

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.65`

- [x] CDN
- [ ] NPM package

**Comment by benelan** [comment]
Whoever works on this should also do #3053. It looks like the number validation methods need some love.

**Comment by annelfitz** [comment]
also https://github.com/Esri/calcite-components/issues/3017
I was surprised I had to set the `step` property just to be able to type in decimals in the first place

**Comment by jcfranco** [comment]
Verified with https://codepen.io/jcfranco/pen/abyPJJV?editors=1010
