### ISSUE TITLE
Bug: [slider] clicks on a range slider cause the max-value thumb to be focused

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3109]
### Actual Behavior

Clicking on the min-value thumb or the track always focuses the max-value thumb.

![max-value-thumb-always-focused](https://user-images.githubusercontent.com/197440/134750123-c4aeaad0-82f3-4070-ab54-a97d37c9abcc.gif)

### Expected Behavior

1. Clicking on min-value thumb, should focus the corresponding thumb 
2. When clicking outside the track, the closest thumb should be focused (after its value is updated)
3. When clicking within the track, the closest thumb should be focused 

@Esri/calcite-design-representatives does 3. ☝🏼 make sense? 

### Reproduction Steps and Sample

_Sample_: https://esri.github.io/calcite-components/?path=/story/components-controls-slider--range

1. Click on the min-value thumb, notice max-value thumb is focused
1. Click on the track (either inside or outside the range), notice max-value thumb is focused

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.65`

- [x] CDN
- [ ] NPM package

Reported by @anveshmekala

**Comment by caripizza** [comment]
The Expected Behavior sounds correct to me 👍

**Comment by benelan** [comment]
verified on storybook
