### ISSUE TITLE
Bug: calcite-tree selection-mode of multi

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#3117]
### Actual Behavior
When `selection-mode` for `calcite-tree` is set to `multi` or `multi-children`, the user is still unable to select multiple `calcite-tree-items`.

### Expected Behavior
A `selection-mode` of `multi` or `multi-children` should allow the user to select multiple `calcite-tree-items`. The event `calciteTreeSelect` should also return an array of all selected items, not just the most recently selected item. 

### Reproduction Steps and Sample
Here is a code pen that uses a `multi` select `calcite-tree`. Notice that only one item can be selected and that the event only returns an array of 1 selected items (this is being console logged). 
https://codepen.io/joeyHarig/pen/BaZqWRM?editors=1111

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.65`

**Comment by caripizza** [comment]
@joeyHarig as far as I know, the "shift" key is required when selecting multiple tree-items with either "multi" or "multi-children" selection-modes. (I made a run-down of the behavior I noticed [here](https://github.com/Esri/calcite-components/pull/2803#issue-969712281) for reference.)

**Comment by caripizza** [comment]
I had the same thought myself @joeyHarig. AFAIK, tree's multi-select behavior was added via these specs (which mention the Shift key to select multiple list items design pattern):
-  https://www.w3.org/TR/wai-aria-practices-1.1/#:~:text=Selection%20in%20multi-select%20trees
- https://www.w3.org/TR/wai-aria-practices-1.1/#:~:text=Alternative%20selection%20model%20--%20Moving%20focus%20without%20holding%20the%20Shift%20or%20Control%20modifier%20unselects

That said, myself and @macandcheese agree -  it seems like at the very least, selection-mode "multi" shouldn't require the Shift key. It should allow you to click to select multiple items (but also support the shift key selection when used).

I'll keep this issue open so we can gather feedback from the team on potentially changing the Shift key requirement.

**Comment by macandcheese** [comment]
Agree with above - having the shift key there seems a little unexpected, even if it's technically within spec. We should allow click / key interaction to select multiple. At which point I'm not sure there would be any support needed for the shift key at all?

**Comment by macandcheese** [comment]
Here are some examples of multi-select trees that allow users to select with mouse / keyboard (not shift):

SAP: https://sap.github.io/ui5-webcomponents/playground/components/Tree/
Infor: https://design.infor.com/code/ids-enterprise/latest/demo/components/tree/example-select-multiple

I guess the application for "shift" could be for selecting more than one (select one, then shift-click to select four or five consecutive options), but I'm not sure that's a requirement.

**Comment by joeyHarig** [comment]
@macandcheese @caripizza Thank you both for looking into this

**Comment by benelan** [comment]
verified on beta.76 with the issue's repro sample
