### ISSUE TITLE
Bug: calcite-radio-group emits multiple calciteRadioGroupChange events

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#3120]
### Actual Behavior
The calcite-radio-group emits multiple calciteRadioGroupChange events, with the event's detail alternating between the previous and the selected value. Note that this bug was originally found in EmberJs.

### Expected Behavior
Only one calciteRadioGroupChange should be fired when making a selection to be consistent with how this event is usually emitted.

### Reproduction Steps and Sample

_Setup:_
1. Create a scenario where a calcite-radio-group is conditionally rendered.
2. Add two calcite-radio-group-items.

_Repro steps:_
1. Select the second calcite-radio-group-item. For example, if your options are [1, 2] then select 2.
2. Toggle the calcite-radio-group off then on again by conditionally rendering it.
3. Select the first calcite-radio-group-item. For example, if your options are [1, 2] then select 1.
4. Observe the calciteRadioGroupChange event fires multiple times.

The [codepen](https://codepen.io/jmanke/pen/zYzyxXK) contains a more detailed set of repro steps specific to that sample. 

_Sample_:

1.  EmberJs - [codepen](https://codepen.io/jmanke/pen/zYzyxXK)

### Relevant Info

_Browser_: Chrome, Firefox, Safari
_Version_: @esri/calcite-components@<1.0.0-beta.65>
_Framework_: EmberJs v3.28.0
- [x] CDN
- [x] NPM package

cc @vijayendranj @julio8a

**Comment by jgrayson-apl** [comment]
+1

**Comment by anveshmekala** [comment]
> I was able to repro in vanilla JS, triaging to next sprint https://codepen.io/benesri/pen/eYENJBX?editors=0010
> 
> cc @jcfranco

Couldn't reproduce this in local on master thought its repro in codepen & jsfiddle

**Comment by benelan** [comment]
I can repro locally
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="initial-scale=1, maximum-scale=1, user-scalable=no"
    />
    <script
      type="module"
      src="https://unpkg.com/@esri/calcite-components@1.0.0-beta.69/dist/calcite/calcite.esm.js"
    ></script>
    <link
      rel="stylesheet"
      type="text/css"
      href="https://unpkg.com/@esri/calcite-components@1.0.0-beta.69/dist/calcite/calcite.css"
    />
  </head>
  <style>
    calcite-button {
      margin: 0.5rem;
    }
    calcite-radio-group {
      margin: 0.5rem;
    }
  </style>
  <body>
    <h3>Repro Steps</h3>
    <ol>
      <li>Select a different <code>calcite-radio-group-item</code></li>
      <li>Click the "Toggle Radio Group" button twice</li>
      <li>Open and clear the console</li>
      <li>
        Select the "Layers" item (or any item before the currently selected one)
      </li>
      <li>
        Notice that the <code>calciteRadioGroupChange</code> fires multiple
        times
      </li>
    </ol>
    <calcite-button id="toggleRadioGroup">Toggle Radio Group</calcite-button>
  </body>
  <script type="module">
    /**
     * https://github.com/Esri/calcite-components/issues/3120
     * reproducible when radio-group is conditionally rendered
     * not reproducible when only changing the display style:
     * document.querySelector(...).style.display = isRadioVisible ? "" : "none";
     **/

    let isRadioVisible = false;
    let checkedValue = "layers";
    const radioGroupString = `<calcite-radio-group id="radioGroup">
     <calcite-radio-group-item value="layers">Layers</calcite-radio-group-item>
     <calcite-radio-group-item value="data">Data</calcite-radio-group-item>
     <calcite-radio-group-item value="geography">Geography</calcite-radio-group-item>
     <calcite-radio-group-item value="maps">Maps</calcite-radio-group-item>
   </calcite-radio-group>`;

    const onRadioToggle = () => {
      isRadioVisible = !isRadioVisible;
      if (isRadioVisible) {
        const radioGroup = document
          .createRange()
          .createContextualFragment(radioGroupString);

        document.body.appendChild(radioGroup);

        // re-check the previously checked item
        document.querySelector(
          `calcite-radio-group-item[value="${checkedValue}"]`
        ).checked = true;
      } else {
        document.querySelector("#radioGroup").remove();
      }
    };

    // button click event listener
    document
      .querySelector("#toggleRadioGroup")
      .addEventListener("click", onRadioToggle);

    // radio-group change event listener
    document.addEventListener("calciteRadioGroupChange", (e) => {
      checkedValue = e.detail;
      console.log(`calciteRadioGroupChange, value: ${checkedValue}`);
    });

    onRadioToggle();
  </script>
</html>
```

**Comment by benelan** [comment]
Hmm, `next` also repros for me. Does the code above repro for you @anveshmekala?

**Comment by anveshmekala** [comment]
> Hmm, `next` also repros for me. Does the code above repro for you @anveshmekala?

Yup. Able to reproduce with above snippet. I believe the only diff is the version of cc, in the snippet attached in PR [3565](https://github.com/Esri/calcite-components/pull/3565/files#diff-6b7035fc97879b561336e007c1f24527d7bd2334fe72ca1ec610c2c183a4d104R41) it is referring to head.js . Thanks @benelan

**Comment by benelan** [comment]
`head.js` is the code that is built locally when running the demos, so if it repros on `next` but not on `head.js` maybe you successfully fixed it?

**Comment by anveshmekala** [comment]
There are no code changes in PR 3565 . It has do with the version I guess.

**Comment by benelan** [comment]
If there are no code changes then in terms of functionality it should be the same as `next`. @jcfranco any thoughts?

**Comment by jcfranco** [comment]
I remember [a difference in behavior with `MutationObserver` when running on the dev server vs a local build](https://github.com/Esri/calcite-components/issues/1409#issuecomment-760364275).

**Comment by benelan** [comment]
It repros for me locally. Are you looking in the console like the repro steps mention?

**Comment by anveshmekala** [comment]
> I remember [a difference in behavior with `MutationObserver` when running on the dev server vs a local build](https://github.com/Esri/calcite-components/issues/1409#issuecomment-760364275). Not sure if that's causing this issue though. Worth checking if `calcite-radio-group-item` emitting the change event when the `checked` prop changes (vs emitting only when the user interacts with it) is the culprit.

 mouse click is emitting `calciteRadioGroupChange event`

**Comment by anveshmekala** [comment]
Able to repro this on prod build.

**Comment by jmanke** [comment]
@benelan Yes it's working great, thank you!

**Comment by benelan** [comment]
Awesome, thanks for checking! Verified on `next`.
