### ISSUE TITLE
Enhancement: [calcite-tree] Support actions/menu in tree items

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#3127]
### Description
We would like to include a menu of actions in each tree item, ex: 
![image](https://user-images.githubusercontent.com/14304581/135178348-7963846b-a815-4f82-9fa9-341b39caa7f1.png)

Including a calcite-dropdown within a calcite-tree-item does not render in a usable way as the dropdown is constrained to the current tree level. It would be great to have a slot in the tree item to accommodate such a menu.
https://codepen.io/ellupp/pen/PojWvmR?editors=1100
![image](https://user-images.githubusercontent.com/14304581/135178285-633c6843-d2a1-47db-851f-1b45dee4eeb2.png)

### Acceptance Criteria 
Tree items can include a menu of actions/dropdown. When opened, the menu should render on top of all tree items such that it is entirely visible.

### Relevant Info 
Supporting a menu is the key enhancement needed but we also need to support multiple actions in some tree items. Slotting a calcite-button into the tree item works for this at the moment. Also, in our use case we only want the actions to be visible on hover or when focus is on/within the tree item. 
![image](https://user-images.githubusercontent.com/14304581/135178820-98de4acb-4a7a-449b-80bb-56bbb6f5e033.png)

#### Which Component
calcite-tree/calcite-tree-item

#### Example Use Case
Please contact me for link to a custom tree implementation in dashboards that has the desired functionality. 

cc @vijayendranj @julio8a

**Comment by macandcheese** [comment]
Seems like this could adopt the action / content start / end slot paradigm to allow for these customizations, similar to a list item.

**Comment by Elijbet** [comment]
@ellenupp 
Just noticed that all `tree-items` from the example I had from you earlier today have an `icon-start`. Is it needed for your use case, I could plan to add that as well if it is.

**Comment by ellenupp** [comment]
Yeah that would be great, thanks.

**Comment by geospatialem** [comment]
Verified in `1.0.3` with the [following Codepen](https://codepen.io/geospatialem/pen/rNrrLew) with the `iconStart` prop and `actions-end` slot.

<img width="403" alt="Screenshot 2023-01-28 at 9 59 41 PM" src="https://user-images.githubusercontent.com/5023024/215304161-710d2152-956c-403d-8560-33f88d93fe09.png">

**Comment by ellenupp** [comment]
Getting around to trying this out- it looks great, thanks!
