### ISSUE TITLE
Component: Single & Multiple Selection Toggle Buttons

### ISSUE THREAD

**Issue by rmstinson** [Esri/calcite-components#313]
We need multiple selection toggle buttons for behavior around font styling within calcite web, [like so.](https://material-ui.com/components/toggle-button/)

<img width="606" alt="Screen Shot 2020-01-30 at 2 03 28 PM" src="https://user-images.githubusercontent.com/12650705/73496546-ac557780-436d-11ea-97a0-bd92beb21b46.png">

**Comment by macandcheese** [comment]
Thanks, I wonder how much of this could be accomplished by the radio group - it's basically the "exclusive selection" from the link you provided. 

Could we repurpose that to also allow multiple selections - could that potentially be confusing and we should have a distinct component?

The item on the right seems more like the "radio card" type component that had been discussed on Teams. Something we'll definitely want but perhaps distinct from the above? Thoughts @bstifle @rmstinson ?

**Comment by julio8a** [comment]
checking back in on this one.

**Comment by macandcheese** [comment]
leave open as feature request
