### ISSUE TITLE
Bug: color-picker selection area isolated in Safari

### ISSUE THREAD

**Issue by jul11557** [Esri/calcite-components#3131]
### Actual Behavior
While testing in Safari, the color-picker component has a limited drag area. In the gif below, you can see that the knob is restricting movement to a small area in the center of the gradient selector. This has been tested in ArcGIS Mission Manager and the new map viewer. In codepen it appears to be fine.

![2021-09-28 16 46 09](https://user-images.githubusercontent.com/83983300/135266602-e7befcfd-8a46-40c2-be91-9901cab5ff11.gif)

### Expected Behavior
When dragging to select a color, I should be able to drag the selection knob to any area of the available colors.

### Reproduction Steps and Sample
1. Open color picker
2. Drag to select in the main color selection area
3. Notice that you cannot drag your cursor all the way to the boundaries of the color area

_Sample_:

Note: I don't know how to use codepen, codesandbox, or jsbin so have not included those as samples. It appears that the component works correctly in codepen on Safari, but is incorrect in two different ArcGIS apps, leading us to believe this is a calcite bug.

The sample in calcite-components documentation does not appear to be visible in safari:

<img width="1743" alt="Screen Shot 2021-09-29 at 8 28 01 AM" src="https://user-images.githubusercontent.com/83983300/135270803-02e87fd7-d713-4db7-b1c0-a414f8cf16db.png">

### Relevant Info
Browser: Safari

_Version_: `@esri/calcite-components@<v1.0.0-beta.58>`

- [ ] CDN
- [ ] NPM package

**Comment by benelan** [comment]
Hi @jul11557, this issue should be resolved in the newest version. See:

#3035
#2335

**Comment by jul11557** [comment]
Thanks @benelan I noticed that this morning. I didn't see the issues when I first looked through the repo (I was searching open issues, not closed). Appreciate it!

**Comment by benelan** [comment]
No problem! When using older versions it can be helpful to check the [changelog](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#bug-fixes-1) for any fixes.
