### ISSUE TITLE
Question: Add overlay positioning to split button

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#3132]
### Description

Add `overlayPositioning` property to split button.

### Acceptance Criteria 

Be able to have a split button in fixed container.

### Relevant Info 

I tried wrapping the dropdown group in a dropdown to use its overlay positioning but this causes split button to not work.

#### Which Component

Split button.

**Comment by caripizza** [comment]
@COV-GIS can you add your code?

**Comment by COV-GIS** [comment]
Sorry for the delay @caripizza. I was out.

I tried to reproduce the issue but was unable. It was similar to https://github.com/Esri/calcite-components/pull/3182. I believe it was two versions back. I should have put the version in the initial issue.

**Comment by benelan** [comment]
verified on next
