### ISSUE TITLE
Bug: [calcite-tree] Visibility of child elements can be out of sync with parent's expanded state

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#3134]
### Actual Behavior

In some scenarios the visibility of a child element can be out of sync with its parent's expanded state, i.e. the parent is set to expanded but the child is hidden. I've encountered this is in two scenarios:
1. When a tree item is set to expanded by default and the tree is hidden and re-rendered
2. When an item is dynamically added to the tree while it is in an expanded state

This was first encountered in EmberJS but the second scenario can easily be reproduced in vanilla JS. 

### Expected Behavior

Whenever a tree item is expanded, all its children should be visible. 

### Reproduction Steps and Sample

_Sample_: Conditionally rendered tree in EmberJS: https://codepen.io/ellupp/pen/LYLqXao?editors=1010

1. Click "Hide tree" to hide the tree
2. Click "Show tree" to render the tree again. Notice that the first item is expanded but its children are not visible. 

![image](https://user-images.githubusercontent.com/14304581/135325799-8e4b35be-f2ff-4851-9551-dd58f2a7eaca.png)
Initial state

![image](https://user-images.githubusercontent.com/14304581/135325837-a601c4ef-cb7e-4c2d-afe9-79cedd452b80.png)
After re-render

_Sample 2_: Dynamically adding item to tree: https://codepen.io/ellupp/pen/powGqOq?editors=1010

1. Click "Add item to tree". Note that the tree item is created but is not visible. It has the attribute `calcite-hydrated-hidden`. When collapsing and re-expanding "Element 1" all children will show up as expected. 

![image](https://user-images.githubusercontent.com/14304581/135326284-81357a3a-1a4e-4fa8-b64c-301cb13a3c45.png)

### Relevant Info

_Version_: `@esri/calcite-components@beta.65`

- [x] CDN
- [x] NPM package

cc @vijayendranj @julio8a

**Comment by caripizza** [comment]
@ellenupp can you help me replicate Sample 1 in vanilla js? I can see the issue clearly in Sample 2, but it's less clear to me in that first sample you provided.

**Comment by ellenupp** [comment]
Hi @caripizza, I'm not sure how to accomplish that in vanilla js since you can't do conditional rendering like that. The closest thing I could think to try is removing the tree from the dom then creating and adding it back again but that works fine...

**Comment by caripizza** [comment]
Gotcha, yep I noticed the same behavior as well. Thanks @ellenupp

**Comment by benelan** [comment]
Idk if this helps but I was able to repro an ember issue in vanilla js with a hacky conditional rendering sample:
https://codepen.io/benesri/pen/eYENJBX?editors=1010

**Comment by benelan** [comment]
verified on beta.69
