### ISSUE TITLE
Calcite Filter Enhancement: 

### ISSUE THREAD

**Issue by sam11927** [Esri/calcite-components#3138]
### Description
Should have some way of knowing if the calcite-filter has text currently typed into the input, or knowing what the text is. 

### Acceptance Criteria 
When text is entered into the input element of the calcite-filter, an outside component should be able to read the entered text and know if it is empty or not.

### Relevant Info 
It would be nice to have both a public `isEmpty` and a `Prop` for the input elements current text value.

#### Which Component
`calcite-filter`

#### Example Use Case
Say someone wants to render different elements based on whether or not the calcite-filter has any text entered. They should be able to read the value or check if it is empty.

**Comment by driskull** [comment]
@jcfranco Seems like combobox should also have this ability, right? I think we should add a value prop to both of these components.

**Comment by driskull** [comment]
I wonder if we should also add a property for filtered items? Like "selectedItems" or "filteredItems".

**Comment by driskull** [comment]
Will be addressed by making the component public via #2208.

**Comment by benelan** [comment]
verified on `next`! https://codepen.io/benesri/pen/wvrMRyE?editors=0010
