### ISSUE TITLE
Bug: first radio button always selected when clicking other buttons in a radio-button-group

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3146]
### Actual Behavior

Clicking a `calcite-radio-button` in a `calcite-radio-button-group` results in the first one always being selected.

### Expected Behavior

The clicked `calcite-radio-button` should be selected.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/jcfranco/pen/RwgORaY

1. Click on any radio button except the first
2. Notice how the first option is always selected

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.66`

- [x] CDN
- [ ] NPM package

**Workaround**: use the `for` attribute in label (see codepen for example)

**Comment by driskull** [comment]
@jcfranco this might be the problem. I had this previously...

<img width="515" alt="Screen Shot 2021-10-01 at 9 48 51 AM" src="https://user-images.githubusercontent.com/1231455/135658311-2d8e4d5f-99b1-4c87-a910-5e761ff42841.png">

**Comment by driskull** [comment]
Seems like it should be querying within the label instead of the rootNode.

**Comment by jcfranco** [comment]
Installed.
