### ISSUE TITLE
Enhancement: Calcite-Card style options for Rounded corners & shadow

### ISSUE THREAD

**Issue by amandathomas-90** [Esri/calcite-components#3152]
### Description
On the Hub team, we're exploring a redesign of our components - several of which utilize calcite cards. I specifically wanted to alter the appearance of the `<calcite-card-container>` but it seems that we do not have that ability. Is this something that could potentially be doable in the future?

I'm happy to clarify this further if needed.

### Acceptance Criteria 
Ability to edit appearance of `<calcite-card>`

- Optional Rounded corner (boolean or radius)
- Optional Drop Shadow (boolean or enumeration like low,medium,high)

#### Which Component

`<calcite-card>`

#### Example Use Case

![calcite-comp-request](https://user-images.githubusercontent.com/49413021/135888300-4670d69c-f5dd-46e8-9f11-0d76871f3cb3.png)

**Comment by benelan** [comment]
@macandcheese / @asangma - thoughts on the shadow half of this issue?

**Comment by ajturner** [comment]
@benelan can you clarified what _installed_ means in this project context? Is there a PR or documentation we can refer to for starting to use this great enhancement?

**Comment by benelan** [comment]
Installed means that it is available on `next` and will be released in `beta.77` next week! There is no documentation yet, but here is a small sample: https://codepen.io/benesri/pen/JjOJMRB?editors=1100

Please note that this should not be used in Esri products. It is for end users who need to customize the component to meet their own design system's criteria.

**Comment by eriklharper** [comment]
Verified on next

**Comment by mjuniper** [comment]
Thanks for this - it's working great. Have you given any thought to the box-shadow part?

**Comment by macandcheese** [comment]
> Thanks for this - it's working great. Have you given any thought to the box-shadow part?

I think it's something we'll eventually want to support as part of the general theming story but not at this time. cc @asangma
