### ISSUE TITLE
Bug: calcite-color-picker-swatch border does not respect class="calcite-theme-light"

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#3160]
### Actual Behavior

The calcite-color-picker-swatch's border is transparent when a parent element has class="calcite-theme-dark" and the calcite-color-picker-swatch has class="calcite-theme-light".

### Expected Behavior

The calcite-color-picker-swatch's border should be the visible when class="calcite-theme-light", regardless if there is a class="calcite-theme-dark" in a parent element. Otherwise, other calcite components will be light themed while the calcite-color-picker-swatch will have no border (colors close to white will just blend into the background).

### Reproduction Steps and Sample

1. Create a `<div class="calcite-theme-dark">`
2. Create a `<calcite-color-picker-swatch class="calcite-theme-light" color="#ffffff" >` as a child of the div created in step 1
3. Observe a transparent border for the calcite-color-picker-swatch

_Sample_:

1. [codepen sample](https://codepen.io/jmanke/pen/PojrLRB?editors=1010)

### Relevant Info

Browsers: Chrome, Firefox, Safari

_Version_: `@esri/calcite-components@<1.0.0-beta.66>`

- [x] CDN
- [x] NPM package

**Comment by benelan** [comment]
For this one either double the alpha value or use the same as disabled for `borderLight`

https://github.com/Esri/calcite-components/blob/master/src/components/calcite-color-picker-swatch/resources.ts#L7-L8

**Comment by jcfranco** [comment]
@Elijbet Looks like this got fixed a while back. Can you confirm if anything else is pending?

**Comment by Elijbet** [comment]
> @Elijbet Looks like this got fixed a while back. Can you confirm if anything else is pending?

I believe it was finalized and merged.

**Comment by jcfranco** [comment]
Thanks, updating labels!

**Comment by jcfranco** [comment]
Never mind, you had already done so. 😅

**Comment by benelan** [comment]
verified on beta.76
