### ISSUE TITLE
Refactor: CalciteSwitch - modify calciteSwitchChange event payload before 1.0 release

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#3163]
We should modify `modify calciteSwitchChange` event payload to not emit redundant props before 1.0 release.

As part of https://github.com/Esri/calcite-components/pull/3162, we deprecated the `switched` property in favor of `checked` but the event payload still has a switched property on it.

**Comment by geospatialem** [comment]
`calciteSwitchChange` event payload has been modified to `event.target.checked` via https://github.com/Esri/calcite-components/pull/5921.
