### ISSUE TITLE
Enhancement: calcite-input type="file" to accept only specified file types

### ISSUE THREAD

**Issue by tyanthony** [Esri/calcite-components#3168]
### Description
Enhancement to the `Input` component, of `type="file"`, to specify types of files to accept.

### Acceptance Criteria 
- [ ] Add a property to allow files of the accepted type(s)
- [ ] Prevent files from being added that are not in the "accepted files"

### Relevant Info 
This can be done currently in the default html `<input>` element, using the `accept` property which takes a string of comma-separated file types (see below). [File Input documentatioin found here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file)

Ex: 
```js
<input
  type="file"
  accept=".pdf, .doc, .docx, .xls, .xlsx, .ppt, .pptx, .csv"
/>
```

#### Which Component
Calcite Input

#### Example Use Case
- Allow the file Input to accept any file type
- Allow the file Input to accept only image files
  - `accept=".png, .jpg, .jpeg, .tif, .tiff"` etc.
- Allow the file Input to accept documents
  - `accept=".pdf, .doc, .docx, .xls, .xlsx, .ppt, .pptx"` etc.

**Comment by jgrayson-apl** [comment]
+1

**Comment by benelan** [comment]
This is available on `next` along with the native input's `multiple` attribute:
https://codepen.io/benesri/pen/gOKEKGe

**Comment by yelenakreyndel** [comment]
@benelan did this get implemented? This issue was added by @macandcheese on Confluence (see Next section here: https://confluencewikidev.esri.com/display/Calcite/New+Web+Components). Adam, please provide more info about the status of this issue.

**Comment by macandcheese** [comment]
@yelenakreyndel opened a new issue for tracking, will update Confluence: https://github.com/Esri/calcite-components/issues/6545
