### ISSUE TITLE
Bug: calcite-tooltip doesn't dismiss after hovering over it

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#3171]
### Actual Behavior

If you mouse over the tooltip, it doesn't dismiss until you hover over the reference element again. 
![2021-10-06_17-25-11 (1)](https://user-images.githubusercontent.com/14304581/136301655-fa509be3-c179-491f-933a-c1fdc297543e.gif)

### Expected Behavior

Tooltip should dismiss after mousing off the reference element and/or tooltip itself. 

### Reproduction Steps and Sample

_Sample_: https://developers.arcgis.com/calcite-design-system/components/tooltip/

1. Issue is reproducible in the developer doc sample. Hover over reference element to show tooltip, then move mouse over tooltip. Mouse off. Tooltip remains visible. 

### Relevant Info

_Version_: `@esri/calcite-components@beta.65`

**Comment by jcfranco** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/calcite-5f7d10460071bf0024e66277/issues/Esri/calcite-components/3171?planning-poker) with ZenHub @driskull
