### ISSUE TITLE
Bug: calcite-input-time-picker does not reset correctly with a form

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#3174]
### Actual Behavior

When a form is reset, the input-time-picker is set to an empty string when it should reset to the default behavior.

### Expected Behavior

When a form is reset, the input-time-picker should be set to the default value

### Reproduction Steps and Sample

1. https://codepen.io/driskull/pen/PoKYoGK?editors=1000
2. Click the native reset button
3. Notice that the input is cleared
4. It should be set to the original value

### Relevant Info

N/A

- [x] CDN
- [ ] NPM package

**Comment by driskull** [comment]
@jcfranco @benelan  I triaged this, hope thats ok.

**Comment by jcfranco** [comment]
This should be fixed in the following release: https://codepen.io/jcfranco/pen/VwzRxwp?editors=1000

**Comment by jcfranco** [comment]
Installed via #2777.

**Comment by benelan** [comment]
verified on next
