### ISSUE TITLE
Enhancement: calcite-card has horizontal layout mode

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-components#3181]
### Description
Horizontal layout mode of calcite card so you can get a layout with the thumbnail adjacent to the main content like this:

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/942837/136593141-e0b93e96-91b6-42de-b8d3-d703418a3786.png)

### Relevant Info 

Maybe it takes a `layout` attribute with a value of `horizontal` or something.

#### Which Component

calcite-card

**Comment by mjuniper** [comment]
I took a quick stab at this and came up with this:

![image](https://user-images.githubusercontent.com/942837/137557015-52cb058c-1467-407d-aa10-f1a87d2d8fdf.png)

I don't have push access to this repo and it sounds like we will want to go through a design process for this but the branch is [here](https://github.com/mjuniper/calcite-components/pull/1);

**Comment by macandcheese** [comment]
I almost wonder if a `thumbnail-position:inline-start,inline-end,block-start,block-end` property (defaulting to the current `block-start`) would be the way to go here. 
It would allow for the above, along with other alignments that might be needed?

**Comment by macandcheese** [comment]
@benelan see above for a potential update to the issue framing.

**Comment by macandcheese** [comment]
This should be simple to update with a ‘thumbnail-position’ (or substitute of a prop name) option with the values listed above (defaulting to current behavior) to provide solution for multiple use cases.

Thoughts @asangma @mitc7862 ?

**Comment by macandcheese** [comment]
Sure, I think the card content and slot alignment itself can stay as is: just positioning the thumbnail at the values mentioned above (top, bottom, start, end)  would let folks achieve “horizontal” cards as well as some other layouts.

**Comment by asangma** [comment]
Ehyo!
Here are some designs.

### Thumbnail in the start position
![image](https://user-images.githubusercontent.com/12503298/152401057-1a23871f-f612-4617-934e-35bd488db089.png)

### Thumbnail in the end position
![image](https://user-images.githubusercontent.com/12503298/152401197-92a42a4e-590e-4ffd-b1ef-ebbad400c9db.png)

### Thumbnail in the bottom position
![image](https://user-images.githubusercontent.com/12503298/152401269-d03d0c76-eac0-4b1e-b93b-eb5cd6198e04.png)

## Checkbox position
As you can see, in the bottom position, the checkbox for `selectable` probably needs to be moved. That might mean an adjustment to something like this.

### Checkbox paired with heading
![image](https://user-images.githubusercontent.com/12503298/152401852-6d47acb4-fd03-444d-997e-61d7393749c4.png)

### No title or subtitle
Maybe at least `title` is required and made into a prop?
![image](https://user-images.githubusercontent.com/12503298/152402087-58a6e78f-094d-4f26-b525-04bdc5b4d373.png)

**Comment by macandcheese** [comment]
Looks good - I think we'll need to validate the chosen width (40%). For the `thumbnail-position:bottom` - I think it should go beneath the footer as that is more consistent with the prop naming / other displays.

I am happy to make the title required. If we do that I'd like to have a summary / description as well, as optional, to encourage consistent lockups.

**Comment by asangma** [comment]
Copy that.
I'm cool with tweaking the thumbnail percentage. Open to suggestions.

**Comment by asangma** [comment]
Updated bottom position design. ⬆️

**Comment by asangma** [comment]
> If we do that I'd like to have a summary / description as well, as optional, to encourage consistent lockups.

Should I take this to mean that title is required and summary/description is optional?

**Comment by macandcheese** [comment]
Users often use the subtitle slot for a rich lockup like [icon][text][link] so maybe we can keep that as slot. A title has little justification for having content besides text content aside from being used as a link (which might be the only use case we would lose by turning title into a required string).

**Comment by mjuniper** [comment]
FWIW we currently use the title slot so we can make it a link.

**Comment by asangma** [comment]
Update. Add the `background-color` to the thumbnail container so that if the content is taller than the thumbnail, it looks like this.
![card-tall-content-short-image](https://user-images.githubusercontent.com/12503298/154590143-09312c25-7372-4a29-8fe6-13cf337403dd.png)

**Comment by asangma** [comment]
@macandcheese 
Thinking more on the designs and discussing with @eriklharper, this design seemed better and more robust. How you feel?

<img width="669" alt="image" src="https://user-images.githubusercontent.com/12503298/158474074-948ceabf-712c-46e1-915d-0991fa0641c2.png">

**Comment by macandcheese** [comment]
Agree

**Comment by FelFly** [comment]
Hello - This issue was shared with me because we're redoing our cards and currently wrestling with image thumbnails aspect ratios. Glancing at the mocks above, which mostly seem to feature a square image similar to the 1:1 group thumbnail, is the pattern for the 3:2 item thumbnail what I see on Alan's post, where underneath the image is essentially white space?

**Comment by geospatialem** [comment]
Verified in `beta.83` using the `thumbnail-position` attribute. 

Values include: `block-end`, `block-start` (**default**), `inline-end`, and `inline-start`.

Example with `inline-start`:
![verified layout enhancement with thumbnail](https://user-images.githubusercontent.com/5023024/173409571-cffa1de2-2975-433f-9251-4c9851bc2bb0.png)
