### ISSUE TITLE
Enhancement: allow unrestricted typing of numbers in input type="number" 

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#3184]
### Description
Currently, in input type="number", there is validation that restricts valid numbers from being entered. For example:
- If step is 1, you can't enter decimals
- #3107  

Our component should not be so restrictive based on number validation. Validation can be handled by the form. This change is in line with the [HTML spec](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement).

### Acceptance Criteria 
- Should be allowed to input any valid number. 
- Step only increments using the + - buttons, it does not effect the numbers you can enter

#### Which Component
`calcite-input`
#### Example Use Case
`<calcite-input type="number" step=1>`
1. User is allowed to enter 0.5
2. User clicks the + button which changes the value to 1.5

cc @jcfranco @eriklharper

**Comment by jcfranco** [comment]
Verified with https://codepen.io/jcfranco/pen/ExvGWmw?editors=1010
