### ISSUE TITLE
Enhancement: allow exponential numbers for input type="number"

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#3185]
### Description
We should allow exponential numbers to be entered in `calcite-input` type="number". For example: `2e25` or `5e-4`

### Acceptance Criteria 
- Exponential numbers can be entered into the number input
- The exponential number string is converted into an actual number, which is used for the value

#### Which Component
`calcite-input`
#### Example Use Case
Inputting numbers with a lot of zeros gives me a headache

cc @jcfranco @eriklharper

**Comment by jcfranco** [comment]
Verified via https://codepen.io/jcfranco/pen/zYELrbd?editors=1000
