### ISSUE TITLE
Bug: block header and block content x-spacing don't match

### ISSUE THREAD

**Issue by bpatterson88** [Esri/calcite-components#3186]
### Actual Behavior
![Screen Shot 2021-10-08 at 2 39 32 PM](https://user-images.githubusercontent.com/15875886/136628175-7f3684d7-e7ec-4159-a46d-b4c70c5b3386.png)

### Expected Behavior

The left edge of the header label should align with the left edge of the labels below

### Reproduction Steps and Sample

Codepen: https://codepen.io/benpatterson/pen/abyoNrx

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.63`

- [ ] CDN
- [ ] NPM package

**Comment by lejara** [comment]
hello,
Its cool if i can work on this?

**Comment by benelan** [comment]
Sure, we appreciate the help! Can you quickly read through the [contributing documentation](https://github.com/Esri/calcite-components/blob/master/CONTRIBUTING.md) first? For now you can fork the repo and create a PR. The checks on the PR won't pass unless you use conventional commits as [mentioned here](https://github.com/Esri/calcite-components/blob/master/CONTRIBUTING.md#commit-message-format) Thanks!
