### ISSUE TITLE
Bug: Nested Calcite Accordions incorrectly toggle parent

### ISSUE THREAD

**Issue by Soreon** [Esri/calcite-components#3212]
### Actual Behavior

When you nest two accordion components with the parent being in `selection-mode="single"`, clicking on one of the items of the child accordion toggle the parent `<calcite-accordion-item>` instead of toggling the child.

If you remove `selection-mode="single"` on the parent accordion, this issue dissapear but the child accordion is not clickable.

### Expected Behavior

Clicking on the child accordion should not toggle the parent.

### Reproduction Steps and Sample
https://codepen.io/jcfranco/pen/KKvRbYO?editors=1000

### Relevant Info

This issue seems to have been fixed at some point : https://github.com/Esri/calcite-components/issues/330

_Version_: `@esri/calcite-components@1.0.0-beta.66`

- [x] CDN
- [ ] NPM package

**Comment by Elijbet** [comment]
@Soreon Could you please provide steps on how to reproduce the issue? Eg which accordion-item do I need to click to observe the unwanted behavior?

**Comment by jcfranco** [comment]
@Elijbet I updated the repro case to make it clearer to see. If you expand one accordion group and then expand the other one, the first one closes.

**Comment by benelan** [comment]
verified on next
