### ISSUE TITLE
Bug: [label + input-date-picker(range)] clicking on start date input focuses end date input

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3214]
### Actual Behavior

When you have a labeled input-date-picker (range), clicking on start date input focuses end date input.

### Expected Behavior

Clicking on either start or end input should end up owning the focus.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/jcfranco/pen/LYjVYxq

1. Click on the first input field
2. Note how the 2nd input field gets focused

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.67`

- [x] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
[Belated] Installed!l

**Comment by benelan** [comment]
verified on beta.69
