### ISSUE TITLE
Bug: calcite-tile doesn't handle long heading correctly

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3215]
![image](https://user-images.githubusercontent.com/44481292/137012689-2f84b52b-05fa-41a8-b8e5-14c8b2bf50d5.png)

### Actual Behavior

text moves beyond tile

### Expected Behavior

text ends with ellipses

### Reproduction Steps and Sample

https://codepen.io/afreitag/pen/qBXdEoN?editors=1000

_Sample_:

1.

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.65`

- [ ] CDN
- [ ] NPM package

**Comment by caripizza** [comment]
Can we remove the [`10%` width](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-tile/calcite-tile.scss#L50) I see set on the .content class? It's ignored since that element already has `flex-auto` set on it (which includes flex-basis for width).

**Comment by benelan** [comment]
Assigning back to @y0n4 based on Cari's comment

**Comment by benelan** [comment]
verified on next
