### ISSUE TITLE
Dropdown enhancement: ability to add icon to item

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#322]
Pretty common use case is for there to be an icon next to the item text: 

![Screen Shot 2020-02-05 at 2 16 45 PM](https://user-images.githubusercontent.com/4733155/73888321-4875f780-4822-11ea-87ff-5f690bc8c5e0.png)

Currently users can add an icon in the slot but there's no way of ensuring consistent placement or scale without users needing a ton of custom CSS.

We should allow an icon={iconName} to be set, which would render a `<calcite-icon>` of the appropriate scale. Also a good test for updating the button component to use `<calcite-icon>` component and render only a provided Calcite UI Icon name vs. just accepting any path data like it currently does.

cc @bpatterson88

**Comment by bpatterson88** [comment]
Dashboards uses this pattern a few times

![Screen Shot 2020-02-05 at 2 31 36 PM](https://user-images.githubusercontent.com/15875886/73889361-575da980-4824-11ea-9231-11fd8a88c5ed.png)
![Screen Shot 2020-02-05 at 2 31 49 PM](https://user-images.githubusercontent.com/15875886/73889363-59276d00-4824-11ea-9ea1-dc3ae73de56d.png)
![Screen Shot 2020-02-05 at 2 32 15 PM](https://user-images.githubusercontent.com/15875886/73889368-5af13080-4824-11ea-9f3b-276125b348e0.png)

**Comment by macandcheese** [comment]
Based on above an "icon-position=start/end" is probably warranted as well.

**Comment by macandcheese** [comment]
@bpatterson88  as a note,  for the "add something" use case where there might not be a need for an item to have an active state, you can use `selection-mode="none"` to prevent items from appearing as selected or active in a `calcite-dropdown-group` 🎈.
