### ISSUE TITLE
Bug: calcite-input-time-picker disabled not being applied correclty

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#3225]
### Actual Behavior
When `disabled` is set on `calcite-input-time-picker` the component still functions as if it were not disabled. The time-picker popover still opens and the controls still work.

### Expected Behavior
The `calcite-input-time-picker` should meet the following criteria when set to disabled.
- The cursor should be the default cursor, not pointer or text (just like `calcite-input` when it is disabled)
- The input should not be able to receive focus
- The date-picker popover should not open when the input is clicked

### Reproduction Steps and Sample

_Sample_: https://codepen.io/joeyHarig/pen/MWvwqJz?editors=1011

Notice how the enabled and disabled `calcite-input-time-picker` components behave very similarly. 

### Relevant Info
_Version_: `@esri/calcite-components@ v1.0.0-beta.67`

I noticed there is an epic for disabled states. This issue and issue #1947 could be added to that epic.

**Comment by jcfranco** [comment]
Fixed via #2655.

**Comment by benelan** [comment]
verified on beta.79
