### ISSUE TITLE
Bug: calcite-fab: click event fires even when its disabled

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#3226]
calcite-fab will fire the click event even when its disabled, a calcite-button correctly does not

### Expected Behavior

It should not fire the click event, in the sample below I place both the fab and a button, disable both, and the button does not fire the event

### Reproduction Steps and Sample

_Sample_:

1.https://codepen.io/kevindoshier/pen/bGrdQrp

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by CodeBarker** [comment]
This is need for the December update in Online

**Comment by jcfranco** [comment]
This should be addressed by https://github.com/Esri/calcite-components/issues/2655

**Comment by jcfranco** [comment]
Fixed via #2655. 

BTW, the original codepen seems to have been modified for another bug, so I created this one for testing: https://codepen.io/jcfranco/pen/XWVrZqy

**Comment by benelan** [comment]
verified in beta.79
