### ISSUE TITLE
Bug: selected property of CalcitePickListItem incorrectly rendering all items as selected

### ISSUE THREAD

**Issue by apfister** [Esri/calcite-components#3230]
### Actual Behavior
There are two issues happening that this issue can address:

1. When using a `CalcitePickList`, the `CalcitePickListItem`s are all showing as selected regardless of their selected property value. 
2. A blue circle icon is displaying instead of a check mark icon

![image](https://user-images.githubusercontent.com/5233042/137188607-9939d174-9a8b-426a-b9fb-81746e6c11e1.png)

### Expected Behavior
1. Only the item with `selected: true` should show as selected.
2. A check mark icon should be rendered rather than the blue circle icon

### Reproduction Steps and Sample
https://codesandbox.io/s/eloquent-sutherland-z8wgwv

### Relevant Info

_Version_: `@esri/calcite-components-react@0.7.0`

- [ ] CDN
- [x] NPM package

**Comment by benelan** [comment]
I doc'd the problem/workaround: https://developers.arcgis.com/calcite-design-system/frameworks/#gotchas

Moving this issue to the freezer until stencil fixes it on their end.
