### ISSUE TITLE
Bug: calcite-fab in calcite-panel slot overlaps content in Firefox

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#3236]
### Actual Behavior

When a calcite-fab is used in the `fab` slot of a calcite-panel, and the content takes up the entire vertical height of the panel, the fab overlaps the panel even when scrolling to the bottom (in firefox). 
![image](https://user-images.githubusercontent.com/14304581/137018297-d0b93f2a-b43b-4734-838f-783fa8f629f7.png)

### Expected Behavior

The fab should be sticky'd to the bottom of the panel, but once the scroll reaches the bottom it should no longer overlap.
In chrome, if you scroll to the bottom of the panel, all content is visible with the fab positioned below it. 
![image](https://user-images.githubusercontent.com/14304581/137018549-cf045cc7-a6fa-4606-9144-9fb97d2beb0a.png)

### Reproduction Steps and Sample

_Sample_: https://codepen.io/ellupp/pen/qBXdEdB?editors=1000

1. Open sample in firefox, scroll to bottom of panel. 

### Relevant Info

Browser: Firefox (not reproducible in Chrome)

_Version_: `@esri/calcite-components@beta.65`

**Comment by benelan** [comment]
reproducible in beta.67 too using the sample ^
