### ISSUE TITLE
Bug: `<calcite-option>` value attribute missing when set via handlebars

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#3240]
### Actual Behavior
The `<calcite-option>` component's `value` attribute is absent. Interestingly, the component's `value` property is set correctly.

### Expected Behavior
The `<calcite-option>` component's `value` attribute is present in the DOM and accessible via `Element.getAttribute()`.

### Reproduction Steps and Sample

```hbs
<calcite-select>
  <calcite-option value="one">one</calcite-option>
  <calcite-option value={{twoValue}}>two</calcite-option>
</calcite-select>
```

_Sample_: https://jsbin.com/boxakokado/1/edit?html,js,output

1. Visit the provided jsbin.
2. Inspect the `<calcite-select>` element in the browser's dev tools. Notice the first `<calcite-option>` element has a `value` attribute and the second one does not.

### Relevant Info
This bug has implications for being able to craft CSS selectors based off the `value` attribute. This can be useful when writing tests that assert certain select options are present.

_Version_: `@esri/calcite-components@1.0.0-beta.67`

- [ ] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
This is working as expected. `value` can take any value type and is therefore not reflected (following https://developers.google.com/web/fundamentals/web-components/best-practices#do-not-reflect-rich-data-properties-to-attributes.).
