### ISSUE TITLE
Bug: `CalciteSelect.selectedOption` is briefly `undefined` post hydration on re-render

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#3241]
### Actual Behavior
When re-rendering a `<calcite-select>` component, there is a brief period of time after its `calcite-hydrated` attribute is set but its `selectedOption` property is `undefined`.

### Expected Behavior
On re-render, the `selectedOption` property is populated before hydration completes.

### Reproduction Steps and Sample

_Sample_: https://jsbin.com/xixamuwupa/1/edit?html,js,output

1. Visit the jsbin sample.
2. Click the "hide" button, then click it again to force a re-render of the `<calcite-select>` element. When the element is detected to be hydrated, the `selectedOption.value` output is updated to show the `value` of its selected option. Notice the output shows `"undefined"` instead of the expected value of "one".
3. Click the "sync output" button to re-poll for the `value` of the selected option. The output updates to show "one", indicating the `selectedOption` property has since become re-populated.

### Relevant Info
This bug largely has implications for test writing where assertions can occur immediately after a component becomes hydrated.

_Version_: `@esri/calcite-components@1.0.0-beta.67`

- [ ] CDN
- [ ] NPM package

**Comment by benelan** [comment]
verified on `next`
