### ISSUE TITLE
Bug: Changes to `<calcite-option>` text content not propagated to shadow DOM

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#3242]
### Actual Behavior
Changes to the text content of a `<calcite-option>` element are not reflected in the select menu.

### Expected Behavior
Changes to the text content of a `<calcite-option>` element are reflected in the select menu.

### Reproduction Steps and Sample

_Sample_: https://ember-twiddle.com/d6f427deeec2a6ae2c9dcf62ecedb61f/db6e00bf0ce2799502ac73f9f730ec3bcae2d66e

1. Visit the twiddle sample.
2. Click the "Update options" button. Inspecting the DOM, see the text content of the `<calcite-option>` elements are updated, however the options in the shadow DOM are not.

### Relevant Info
There is a viable workaround in that changes to the element's `label` and/or `value` attributes are propagated as expected -- but could be overlooked/missed as these are not required attributes.

_Version_: `@esri/calcite-components@1.0.0-beta.67`

- [ ] CDN
- [ ] NPM package

**Comment by benelan** [comment]
@nwhittaker can you please help me verify this one on `next` when you get a chance? I don't see an "update options" button in the repro sample.

**Comment by nwhittaker** [comment]
>@nwhittaker can you please help me verify this one on next when you get a chance? I don't see an "update options" button in the repro sample.

Looks like I may have overwritten the head revision. I'll update the issue description with the older revision meant for this issue: https://ember-twiddle.com/d6f427deeec2a6ae2c9dcf62ecedb61f/db6e00bf0ce2799502ac73f9f730ec3bcae2d66e.

**Comment by benelan** [comment]
Thanks for the repro sample, this issue is verified on next.
