### ISSUE TITLE
Bug: Changes to `checked` and `indeterminate` attributes not reflected in wrapped checkbox input

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#3246]
### Actual Behavior
Changes to the `checked` and `indeterminate` attributes on a `<calcite-checkbox>` element are not reflected in the checkbox input that the component wraps.

### Expected Behavior
When set on the `<calcite-checkbox>` element, the `checked` and `indeterminate` attributes are also set on the wrapped checkbox.

Maintaining an accurate state on the wrapped checkbox is helpful in test writing with Typescript. The wrapped checkbox can be passed to assertion helpers that require the element be typed to the `HTMLInputElement` interface.

### Reproduction Steps and Sample

1. Visit https://developers.arcgis.com/calcite-design-system/components/checkbox/
2. Inspect the `<calcite-checkbox>` element in the browser's dev tools.
3. Click on the element in the browser window and notice the `checked` attribute is added to it but not to the wrapped checkbox.
4. Uncheck the element and add the `indeterminate` attribute manually. Notice it's also not propagated.

### Relevant Info
A partial workaround is to re-render the entire `<calcite-checkbox>` element whenever one of these attributes changes, but that can lead to a lot of duplicated template code:

```hbs
{{#if this.checked}}
  <input checked ...
{{else if this.indeterminate}}
  <input indeterminate ...
{{else}}
  <input ...
{{/if}}
```

However, there's a potentially related bug where if `indeterminate` is initially set, it's still not reflected in the wrapped checkbox -- unlike the `checked` attribute which is initially reflected.

_Version_: `@esri/calcite-components@1.0.0-beta.67`

- [ ] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
I believe this is no longer an issue since `calcite-checkbox` was refactored this sprint. @nwhittaker Can you confirm? https://codepen.io/jcfranco/pen/mdMoKJv?editors=1000

**Comment by nwhittaker** [comment]
@jcfranco, verifying the issue is no longer possible in https://codepen.io/jcfranco/pen/mdMoKJv, thanks.

**Comment by jcfranco** [comment]
Thanks for verifying! cc @benelan
