### ISSUE TITLE
Refactor - Consider using Popper v2 for Popover/Tooltip positioning

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#326]
Refactor - Consider using Popper v2 for Popover/Tooltip positioning

https://popper.js.org/

https://www.npmjs.com/package/@popperjs/core

---

This will likely result in breaking changes since some of the options/positioning have changed. Hopefully nothing too bad. We can probably also do away with some of the properties on the Popover/Tooltip.

**Comment by driskull** [comment]
cc @AdelheidF @kevindoshier

**Comment by driskull** [comment]
Installed. @AdelheidF when would you like to begin using this? When should we have a release?

**Comment by AdelheidF** [comment]
> When should we have a release?

I'm fine with whenever. We keep using beta 18 for the patch this week.

**Comment by driskull** [comment]
Going to close!
