### ISSUE TITLE
Enhancement: Disable/remove drag handle when there is only one calcite-value-list-item in a calcite-value-list

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#3272]
### Description
The `<calcite-value-list drag-enabled>` currently lets the user drag a `<calcite-value-list-item>` even when there is only one item in the list. Since there is no where the user can drag the item, it would make sense to either disable or remove the drag handle.

### Acceptance Criteria 
Either disable or remove the drag handle when there is only one item in `<calcite-value-list drag-enabled>`.

#### Which Component
calcite-value-list

#### Example Use Case

A reorder-able list where users can add or remove items. When there is only one item in the list, it doesn't make sense to let the user drag it.

**Comment by asangma** [comment]
@jmanke Would it work if you were to toggle the `drag-enabled` property when there's only one item?

**Comment by jmanke** [comment]
@asangma Yep, that works perfectly! Don't know why I didn't think to do that, thank you.
