### ISSUE TITLE
Bug: calcite-list is missing setFocus()

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3275]
`calcite-value-list` and `calcite-pick-list` both have a `setFocus` method. `calcite-list` doesn't even though I can tab through each list-item and focus it this way.

### Actual Behavior

no setFocus method

### Expected Behavior

add setFocus method

### Reproduction Steps and Sample

https://codepen.io/afreitag/pen/zYdrogo
_Sample_:

1.

### Relevant Info

_Version_: `@esri/calcite-components@1.0.0-beta.65`

- [ ] CDN
- [ ] NPM package

**Comment by benelan** [comment]
yessir @driskull

**Comment by benelan** [comment]
verified on next
