### ISSUE TITLE
Bug: TabNav causes scrolling issue when container has set width

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3279]
### Actual Behavior
When in a container with a set width, TabNav causes a horizontal scrollbar.
It seems to be related to the combo of [the padding and negative margin](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-tab-nav/calcite-tab-nav.scss#L23-L24).

### Expected Behavior
Not have horizontal scrollbars.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/mtb-alan/pen/GRvorRY

1. In demo, change tabs
2. observe the horizontal scrollbar.
3. note that it doesn't matter how wide the container is.

### Relevant Info
Fixed width container are common in the JS API.

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by benelan** [comment]
verified on beta.72
