### ISSUE TITLE
Refactor: remove 'childElType' from button and link components.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#3284]
### Description 

Refactor: remove 'childElType' from button and link components.

### Proposed Advantages 

Calculate the child element type during rendering.

### Relevant Info 

https://github.com/Esri/calcite-components/pull/3248#discussion_r730255124
https://github.com/Esri/calcite-components/pull/3222#discussion_r730255535

#### Which Component

- calcite-button
- calcite-link

**Comment by benelan** [comment]
verified on master
