### ISSUE TITLE
Bug: calcite-dropdown max-items not respected when dynamically adding calcite-dropdown-items

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#3295]
### Actual Behavior

`calcite-dropdown` will not update its height according to the `max-items` attribute when dynamically adding `calcite-dropdown-items`.

### Expected Behavior

`calcite-dropdown` should update its height according to the `max-items` attribute when dynamically adding `calcite-dropdown-items`. Regardless of when items are added to the dropdown, max-items should be respected.

### Reproduction Steps and Sample

1. Set `max-items` to some number greater than 0.
2. Add less `calcite-dropdown-items` than the max number of items set in `max-items`. For example, if `max-items=4` add three `calcite-dropdown-items`.
3. Dynamically add another `calcite-dropdown-item`.
4. Open the dropdown and observe that the number of items visible is the number of items the `calcite-dropdown` initially started with. For example, if `max-items=4` and there were three `calcite-dropdown-items` before adding another item, then only three items will be visible.

_Sample_:

1. JS [codepen](https://codepen.io/jmanke/pen/QWMNRzZ)
2. EmberJS [codepen](https://codepen.io/jmanke/pen/dyzMELN)

### Relevant Info

It would be nice to have a css variable to set max-height instead of having max-items.

[Issue 2882](https://github.com/Esri/calcite-components/issues/2882) might be related.

_Version_: `@esri/calcite-components@<1.0.0-beta.67>`

- [x] CDN
- [ ] NPM package

**Comment by benelan** [comment]
verified on next
