### ISSUE TITLE
Bug: calcite-input-date-picker min and max not updating

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#3317]
### Actual Behavior

When the properties `min` or `max` are  updated on a `calcite-input-date-picker`, the min and max values within the date picker are not updated.

### Expected Behavior

The date picker update min and max values when they are updated on the `calcite-input-date-picker`

### Reproduction Steps and Sample
The following code pen includes steps to reproduce this bug.
https://codepen.io/joeyHarig/pen/oNezexE?editors=1001

### Relevant Info

_Reproducible version_: `@esri/calcite-components@v1.0.0-beta.67`

**Comment by Elijbet** [comment]
I think there might be a misunderstanding of how the date-picker works. These are 2 independent fields, one with min attribute and one without. I wouldn’t expect picking a date on the one without to set the minimum attribute on the other. Am I misunderstanding the issue?

**Comment by joeyHarig** [comment]
@Elijbet In the codepen I'm setting the min for input-2 after a date select form input-1. 

The issue is that the 'min' value being passed to the date-picker from the input isn't being updated when the 'min' value on the input is updated.

**Comment by jcfranco** [comment]
@Elijbet It looks like the issue is that the date-picker isn't updating internally when `min` is updated after initialization.

**Comment by benelan** [comment]
verified on next
