### ISSUE TITLE
New Component: Radio Cards

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#333]
Not sure if there's a better name for this, but... some kind of containers that function as radio buttons. Follow up from discussion on Teams with @TheBlueDog @rmstinson @asangma @mcox @bstifle 

"Live use case":

![Screen Shot 2020-02-10 at 3 39 13 PM](https://user-images.githubusercontent.com/4733155/74200508-fc5cf580-4c1b-11ea-83ff-8c3be7137c83.png)

Pseudo design - allowing for horizontal and vertical layouts: 
![horizontal](https://user-images.githubusercontent.com/4733155/74200628-5362ca80-4c1c-11ea-8d87-fa72cf58699e.png)
![vertical](https://user-images.githubusercontent.com/4733155/74200868-f4ea1c00-4c1c-11ea-89c1-5049d104ed42.png)

I'm not sure we would need to use radio buttons - in the "live use case" example those are the only clickable areas which is pretty frustrating as a use - the whole card should be clickable. Ideally we'd always default to having one active item, and disallow "non selected state" with no active items (for a true radio use.. if we allow multiple selection then obviously you'd need to allow unselected items...)

Entire contents would be a slot... We should have an optional `icon`, `item-title` or `item-subtitle` attributes for standardizing simple icon use and text like in the provided example, but we'd need the slot because these could easily accommodate more complex items. Should support our usual scale, theme options.

Salesforce has the concept of "visual picker" which allows for multiple to be selected, not sure if that would be a separate component or not, perhaps we can borrow from their terminology. https://www.lightningdesignsystem.com/components/visual-picker/

**Comment by bstifle** [comment]
**_Radio Tiles_**

**Comment by rmstinson** [comment]
I call the ones in the Share Dialog, _**Super Radio Buttons**_. 

<img width="556" alt="Screen Shot 2020-02-10 at 4 49 33 PM" src="https://user-images.githubusercontent.com/12650705/74203691-5a420b00-4c25-11ea-933a-85ce6f0051fb.png">

**Comment by driskull** [comment]
@asangma this is getting pretty similar to the pick-list. Could it use this internally or something?

https://esri.github.io/calcite-app-components/?path=/story/components-calcite-pick-list--basic

**Comment by julio8a** [comment]
new issue for this coming soon
