### ISSUE TITLE
Enhancement: [pick-list-item] meld the icon's selection states with item's label when it has no `actions-start` slot content

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#3334]
### Description
When hovering over or selecting a pick-list-item that includes an `icon`, it currently shows as 2 separate selection hit states:

#### Current
(hover)
![image](https://user-images.githubusercontent.com/42423180/138507190-76f83035-1076-4469-8309-8639fb6628bd.png)

(focused)
![image](https://user-images.githubusercontent.com/42423180/138505977-ec19c631-ed75-4ac9-a606-d43773c3edf0.png)
([Storybook iframe url](https://esri.github.io/calcite-components/iframe.html?id=components-pick-list--basic&args=&viewMode=story))

This issue should meld the two areas so that hovering over or selecting a pick list item shows the entire label as hovered/focused:

#### TO-DO
(hover)
![pick-list-item-to-do-hover](https://user-images.githubusercontent.com/42423180/138507483-afcab349-fe01-4351-9ba5-e10d9598826d.png)

(focus)
![pick-list-item-to-do-focused](https://user-images.githubusercontent.com/42423180/138507123-1935afbe-94d3-459f-b56a-fae9a7b0bf68.png)

### Acceptance Criteria 
Hovering over or selecting a pick-list-item with icon (and without `actions-start` slotted content) shows the entire `label` as hovered/focused, per the above TO-DO screenshots.

### Relevant Info 
Related issues: 

* #1547 (Specifically [this comment](https://github.com/Esri/calcite-components/pull/2502#issuecomment-883433102))
* https://github.com/Esri/calcite-components/issues/3373

#### Which Component
calcite-pick-list-item

#### Example Use Case
From the Storybook iframe markup/screenshots above:

```html
<calcite-pick-list>
  <calcite-pick-list-item label="T. Rex" description="arm strength impaired" value="trex" icon="circle">
    <calcite-action slot="actions-end" label="click-me" appearance="clear" icon="information"></calcite-action>
  </calcite-pick-list-item>
  <calcite-pick-list-item label="Triceratops" description="3 horn" value="triceratops" icon="circle">
    <calcite-action slot="actions-end" label="click-me" appearance="clear" icon="information"></calcite-action>
  </calcite-pick-list-item>
  <calcite-pick-list-item label="hi" description="there" value="helloWorld" icon="circle">
    <calcite-action slot="actions-end" label="click-me" appearance="clear" icon="information"></calcite-action>
  </calcite-pick-list-item>
</calcite-pick-list>
```

**Comment by geospatialem** [comment]
With the deprecation of `pick-list` and the new functionality support of `list` closing out this issue.
