### ISSUE TITLE
Enhancement: ActionPad. Remove max-width.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3337]
### Description
ActionPad's max-width is probably unnecessary and is likely to cause issues in smaller window sizes.

### Acceptance Criteria 
Remove max-width.

#### Which Component
ActionPad

#### Example Use Case
ActionPad in a small browser window.
<img width="341" alt="Screen Shot 2021-10-22 at 2 19 42 PM" src="https://user-images.githubusercontent.com/12503298/138524236-da8b9355-daa3-4ad1-b0b8-9f4e7478c3a8.png">

**Comment by macandcheese** [comment]
@asangma this should be fixed, you can now opt-in to the max-width with `--calcite-action-pad-expanded-max-width` : https://codepen.io/mac_and_cheese/pen/poZGazE?editors=1000
