### ISSUE TITLE
Bug: [combobox] longer strings aren't truncated anymore when in fixed-width container

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#3341]
### Actual Behavior
Starting at next.290, longer combobox strings are no longer truncated when the combobox is nested in a smaller fixed-width container:

![image](https://user-images.githubusercontent.com/42423180/138535494-6bd55a35-8d68-46f5-8026-c03695326a1b.png)

### Expected Behavior
Longer combobox strings should be truncated when the combobox is nested in a smaller fixed-width container. The ellipsis should appear when the combobox has selection-mode "multi" or "ancestors" as well.

next.289:
![image](https://user-images.githubusercontent.com/42423180/138535469-d5d83733-a466-44d6-973b-91c739b99330.png)

### Reproduction Steps and Sample
https://codepen.io/caripizza-the-animator/pen/qBXRBpd

_Sample_:

1. Open the CodePen
2. notice the combobox item text isn't truncated

### Relevant Info
We added the ellipsis effect back in #2096.

It looks to me like maybe a regression from the chevron icon we added in pr #3143.

AFAIK, the ellipsis should appear in multi/ancestors selection-modes - single I think we removed the ellipsis from appearing in #3059.

_Reproducible version_: `@esri/calcite-components@1.0.0-next.290`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-next.289`

**Comment by caripizza** [comment]
(Self-assigning this per Teams conversation with @macandcheese)

**Comment by benelan** [comment]
verified on `beta.68` in repro sample
