### ISSUE TITLE
Bug: Can't type in input with slotted action

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#3344]
### Actual Behavior

When clicking on an input with a slotted action to type a value, the focus automatically goes to the action, preventing text from being entered.

### Expected Behavior

The focus stays on the input so the user can type.

### Reproduction Steps and Sample

[Current documentation](https://developers.arcgis.com/calcite-design-system/components/input/) under "With slotted action".

### Relevant Info

_Browser_: Firefox
_Reproducible version_: `@esri/calcite-components@1.0.0-beta.67`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-beta.66`

**Comment by jcfranco** [comment]
Installed.

**Comment by benelan** [comment]
verified on beta.69
