### ISSUE TITLE
Bug: Block heading and summary don't seem to align correctly in RTL

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3346]
### Actual Behavior
In RTL, Block heading and summary don't seem to align correctly.
This seems to only happen when the Block is `collapsible`

![Screen Shot 2021-10-25 at 10 47 30 AM](https://user-images.githubusercontent.com/12503298/138744958-8f08db15-404f-4910-a6e8-de29600cf91e.png)

### Expected Behavior
Align correctly in RTL.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/mtb-alan/pen/porepam?editors=1000

1. View the difference between the collapsible and not collapsible Blocks.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by benelan** [comment]
verified on next
