### ISSUE TITLE
Bug: Styling inconsistencies in dropdown items (link vs non-link, RTL)

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#3349]
### Actual Behavior

There are some inconsistencies in the styling of dropdown items:
- horizontal padding is different in RTL vs LTR
- vertical padding is different between links and non-links (extra padding on links makes them 40px in height while non-links are 32px at medium scale)
- focus and hover states are different between links and non-links (text color does not change for links)

![image](https://user-images.githubusercontent.com/14304581/138755281-71872876-50f2-4f86-8690-5924b47ea419.png)

### Expected Behavior

Padding should be consistent between LTR and RTL. Not sure if it is by design that there should be differences between links and non-links but I would expect them to have the same height at least. 

### Reproduction Steps and Sample

_Sample_: https://codepen.io/ellupp/pen/YzxZaQz?editors=1000

1. Create a calcite-dropdown that includes both link (has href attribute) and non-link calcite-dropdown-items. Observe the differences. View same dropdown in RTL and observe differences.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta67`

- [x] CDN
- [x] NPM package

**Comment by benelan** [comment]
verified on `beta.69`
