### ISSUE TITLE
Enhancement: add new events for Calcite Inline Editable

### ISSUE THREAD

**Issue by alexanderela** [Esri/calcite-components#3357]
### Description
Request to add following events to Calcite Inline Editable component:
* calciteInlineEditableConfirmEdit
* calciteInlineEditableCancelEdit

### Acceptance Criteria 
* Allow users to listen for above events to facilitate integrating Calcite Input component with custom state management.

![Screen Shot 2021-10-26 at 3 26 11 PM](https://user-images.githubusercontent.com/30238776/138963351-dc0d68a6-eb4f-458e-b2c0-5ac5eeddf152.png)

#### Which Component
[Calcite Inline Editable with controls active](https://developers.arcgis.com/calcite-design-system/components/inline-editable/)

#### Example Use Case
* User uses Calcite Input wrapped in Calcite Inline Editable to create new folder.  User types new folder name, reconsiders, and clicks the `X` to cancel/clear input.  This would emit the above described `calciteInlineEditableConfirmEdit` event, which would then be used to clear state managing the value contained in the input.  Then, user would type new folder name in input and click checkbox to confirm. This would emit the above described `calciteInlineEditableConfirmEdit` event, which would then be used to update state managing the value contained in the input.

**Comment by driskull** [comment]
@benelan @jcfranco 

We have some internal events on this class that would handle this issue. Do we want to rename them and document them?

https://github.com/Esri/calcite-components/blob/master/src/components/calcite-inline-editable/calcite-inline-editable.tsx#L173-L186

**Comment by driskull** [comment]
Awaiting response from above

**Comment by benelan** [comment]
Sorry, for the delay Matt. I would defer to Franco's input but that sounds like a good plan to me.

**Comment by jcfranco** [comment]
Yes, exposing the internal `calciteInlineEditableChangesConfirm` & `calciteInlineEditableEditingCancel` events is the goal. Aside from making these public, we should:

* review the names - IMO they read a bit disconnected currently
* type the emitters as `void`

@y0n4 Can you pick this one up?

**Comment by benelan** [comment]
verified on beta.75 https://codepen.io/benesri/pen/oNobyqg
