### ISSUE TITLE
Enhancement: ListItem - add padding when no description

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3362]
### Description
When there is no description, list items are very small.
In order to retain good hit area, we should add some additional padding when there is no description.

### Acceptance Criteria 
Add 0.25rem top and bottom padding to `.content` or `.label` when `.label` is the only child.

### Relevant Info 
See demo example here: https://codepen.io/mtb-alan/pen/XWagXRG

#### Which Component
CalciteListItem

#### Example Use Case
Any time a list-item is used with only the label.

**Comment by asangma** [comment]
@benelan I'd like to bust this one out in this sprint. Low risk, better UI.

**Comment by benelan** [comment]
@asangma sure, I'm adding it to this sprint

**Comment by asangma** [comment]
Whoop!

**Comment by benelan** [comment]
verified on next
