### ISSUE TITLE
Docs: [value-list] remove erroneous Label-editing-and-single-select usage example

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#3364]
### Description 
The following doc shows a `label-editing-enabled` attribute that doesn't seem to do anything in the corresponding usage snippet:
https://github.com/Esri/calcite-components/blob/master/src/components/value-list/readme.md#label-editing-and-single-select

We should remove this example from value-list docs.

### Which Component
calcite-value-list

### Resources 
n/a

**Comment by jcfranco** [comment]
@benelan Triaged this simple doc fix.

**Comment by geospatialem** [comment]
Verified on master.
