### ISSUE TITLE
Bug: [calcite-switch] the switched property is not picked up when initialized

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3371]
### Actual Behavior

The `switched` property of calcite-switch no longer picked up initially.

### Expected Behavior

Changes to the `switched` property are only picked up after initialization

### Reproduction Steps and Sample

_Sample_: https://codepen.io/jcfranco/pen/PoKjgPN

1. Observe how the first example works with `checked` and the second one does not with `switched`

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.67`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-beta.66`

Beta.67 deprecated `switched` in favor of `checked`, but it looks like it is missing initializing the value as [watchers are not triggered when a component is initialized](https://stenciljs.com/docs/reactive-data#watch-decorator).

**Comment by AdelheidF** [comment]
I just ran into this too and I don't see any updates for `calcite-switch` as part of beta.67. Is there some doc missing? I would have thought there would be something about `switched` being deprecated.

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
@AdelheidF You are right, it is missing. I'll update the changelog. It got skipped by the changelog-generating script because it was typed as a [refactor](https://github.com/Esri/calcite-components/commit/6876686ac9ce30fae6f866403ec9373713617889) (vs feat for adding a prop?). cc @driskull

**Comment by jcfranco** [comment]
https://github.com/Esri/calcite-components/pull/3464

**Comment by benelan** [comment]
verified on `beta.69`
