### ISSUE TITLE
Bug: calcite-popover causes notice not to be full width

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3372]
If there is a notice with width=full inside a popover it's not as wide as the popover.

![image](https://user-images.githubusercontent.com/44481292/139304579-0100095f-4d27-45d3-a80d-36cf65fcc7f0.png)

From Alan: popover's content node needs to have something like `flex: 1 0 auto` defined on it.

### Actual Behavior

notice with width=full is not taking full width of popover

### Expected Behavior

notice takes full width of popover

### Reproduction Steps and Sample

https://codepen.io/afreitag/pen/oNewOXR?editors=1000

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-68`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by benelan** [comment]
verified on `next`
