### ISSUE TITLE
Bug: calcite-value-list-item's label takes up space even if there is no content specified

### ISSUE THREAD

**Issue by ptmdmusique** [Esri/calcite-components#3373]
### Actual Behavior

calcite-value-list-item's label (which is inside calcite-pick-list-item) takes up space even if no label is passed as prop

### Expected Behavior

the label should not take up space and we can stretch the `actions-end` or `actions-start`

### Reproduction Steps and Sample

https://codepen.io/ptmdmusique/pen/YzxZaZK

cc @paulcpederson @abi11500

### Relevant Info

---

**Comment by driskull** [comment]
We might just need to improve documentation and make `label` required.  Label is like a title and description is like a subtitle in this case. You can't have just a subtitle without a title.

@benelan @jcfranco Any suggestions on how we can catch these things before assignment? I don't want to waste dev time. Or we can communicate that issues require further investigation before proceeding with development.

**Comment by jcfranco** [comment]
`calcite-value-list-item#label` [is marked as required](https://developers.arcgis.com/calcite-design-system/components/value-list/#component-api-properties-label). Sidebar, `calcite-pick-list-item#label` [is not](https://developers.arcgis.com/calcite-design-system/components/value-list/#component-api-properties-label). cc @benelan 

@driskull Let me assure you that nobody wants to waste dev time, this just slipped through the cracks during triaging.

**Comment by benelan** [comment]
Woops the mention must have gotten buried in my emails, thanks for taking care of this Matt. [Verified on master](https://github.com/Esri/calcite-components/blob/master/src/components/pick-list-item/readme.md)
