### ISSUE TITLE
Enhancement: calcite-chip allow for custom colors

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#3374]
### Description
Allow for custom hex colors to be passed into the `calcite-chip` component. 

Consider revising the style of chips when using dark theme. Full color chips can be too contrasting on dark backgrounds. Under 'Relevant Info' is an example of how GitHub alters their chip styles on dark backgrounds. 

### Acceptance Criteria 
- Allow hex values to be passed as the color to `calcite-chip`
- Evaluate the luminosity of a color in order to determine the text color of the chip. This will ensure that the contrast is always accessible. Consider the JSFiddle color evaluator example under 'Relevant Info'. 

### Relevant Info 
- GitHub light vs dark filled chip styles:
<img width="270" alt="Screen Shot 2021-10-28 at 12 40 45 PM" src="https://user-images.githubusercontent.com/55154968/139316788-2ebbe728-519d-4f5d-bcc3-d63d1bf6395b.png">
<img width="330" alt="Screen Shot 2021-10-28 at 12 53 03 PM" src="https://user-images.githubusercontent.com/55154968/139317776-5996d9b9-58f2-498f-b0bb-a6a8fdcde50d.png">

- Color evaluator: http://jsfiddle.net/alex_ball/PXJ2C/

#### Which Component
`calcite-chip`

#### Example Use Case
ArcGIS Monitor uses labels to categorize and express actions on items. The colors of these labels allow users to customize their label management and differentiate labels. 

<img width="809" alt="Screen Shot 2021-10-28 at 12 47 27 PM" src="https://user-images.githubusercontent.com/55154968/139316980-77f28b5e-03a1-4686-adf3-b042034a1071.png">

**Comment by macandcheese** [comment]
@joeyHarig FWIW - you can currently use the existing css variables to achieve this: https://codepen.io/mac_and_cheese/pen/dymbEzj?editors=1000

However we should probably have some local-to-component css variable alias so folks don't need to guess which border / text / foreground variable to override. @benelan generally these "local override alias" could be useful in a lot of cases.

**Comment by macandcheese** [comment]
@joeyHarig is this still valid? The css variables can be used to theme the chips to achieve the designs in the screenshots.

I do think the "generate valid color combination from a single hex" could be a valid story for any components, not just chip, but I think it's a larger story and not specific to this component.

@benelan thoughts on closing this / opening a more representative issue for adaptive theming if needed?

**Comment by macandcheese** [comment]
Closing as Chips can be themed - if we want to explore generative color pairs down the road (a good idea) it should probably be done across the library and not specific to Chip.

Chip has example of custom theming in the "Chip with theming" Sample on doc site: https://developers.arcgis.com/calcite-design-system/components/chip/
