### ISSUE TITLE
Bug: Inconsistent event detail returned from `calciteInputInput` when using `clearable`

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#3381]
### Actual Behavior
Using the `clearable` affordances (`esc` key, "x button") on an input causes inconsistent value to be set: `null` instead of `""`.

### Expected Behavior

Consistently value - `""` for both use cases.

### Reproduction Steps and Sample

_Sample_:

JSBIN: https://jsbin.com/puwuvuxofa/1/edit?html,js,console,output
Step 1: enter text into input
Step 2: delete text with "delete" key.
Step 3: notice that upon removal of all text, `""` is the input's value.
Step 4: enter text into input.
Step 5: clear text with `esc` key or by clicking the "x" affordance
Step 6: notice that the input value is now `null` - different than `""` above.
### Relevant Info

_Reproducible version_: `1.0.0-beta.68`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

Related issue: #2060

**Comment by jcfranco** [comment]
Possibly related to https://github.com/Esri/calcite-components/issues/1856
