### ISSUE TITLE
Enhancement: Input - add `enterkeyhint`

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#3383]
### Description
Similar to the recently added `inputmode` - this is a useful native attribute that can help devs provide a better UX to end users: 

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint#values

### Acceptance Criteria 
`enterkeyhint` is available as an attribute.

### Relevant Info 

Should we just audit all native attributes and add them - there are others we don't support, `pattern`, etc., that may be useful (or, wait until we "break apart" and add them to their related input types?)

**Comment by jcfranco** [comment]
@benelan Can we refactor the prop this sprint to follow prop-naming conventions (`enterKeyHint`)? For consistency, we want to avoid having mixed casing in our APIs. This should also apply to https://github.com/Esri/calcite-components/issues/2949 cc @macandcheese

**Comment by jcfranco** [comment]
Verified with https://codepen.io/jcfranco/pen/wvqXrrb?editors=1000 on an iOS device.
