### ISSUE TITLE
Bug: calcite-tab will not show horizontal scroll if the content width gets too large

### ISSUE THREAD

**Issue by y0n4** [Esri/calcite-components#3389]
### Actual Behavior
When the width is already set and wrapped around the tabs component, and the tab content becomes larger than the width length, there is no scroll to view the rest of the content

### Expected Behavior
Have a scroll shown when the content gets larger than the given height/width

### Reproduction Steps and Sample

_Sample_: https://codepen.io/yonachos/pen/GRvvGwd
1. view content at first tab "tab one"
2. observe that you cannot view the full image since it is cut off

### Relevant Info
May have to add an overflow styling in the tab component

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by benelan** [comment]
verified on `next`
