### ISSUE TITLE
Enhancement: Focus outline inset

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#3392]
### Description
Allow specification of focus outline on components to be inset. Components like `calcite-action` and `calcite-input` utilize inset outlines when focused on while `calcite-button` and `calcite-dropdown` utilize an outset outline. When the surrounding elements prevent overflow, outset outlines can be covered hidden.

### Acceptance Criteria 
- add prop to components with outset focus outlines to allow them to be inset

#### Which Component
- `calcite-button`
- `calcite-stepper`
- `calcite-tabs`

_possibly_
- `calcite-switch`

#### Example Use Case
<img width="750" alt="Screen Shot 2021-10-29 at 3 52 02 PM" src="https://user-images.githubusercontent.com/55154968/139505987-1a74efa5-8763-4551-a794-7325ac0f61bf.png">

**Comment by macandcheese** [comment]
We will need to examine how to allow this while ensuring focus is visible, for example a focus outline that is inset on a filled blue button is not perceivable.

**Comment by geospatialem** [comment]
Reallocating this issue to tackle in February's priorities.

**Comment by geospatialem** [comment]
Re-adjusting the timeline to accommodate upcoming Esri events and will tackle as part of the March priorities in coordination with #4633.

**Comment by ashetland** [comment]
### Proposal to make this a system-wide customization


Add two CSS variables for customization at the root or component level (actual text TBD):
- `--calcite-ui-focus-offset` (default to what is currently most common (-2px?))
- `--calcite-ui-focus-color` (defaults to ui-brand)

cc: @jcfranco @macandcheese @geospatialem

**Comment by ashetland** [comment]
Also related: https://github.com/Esri/calcite-components/issues/6588

**Comment by geospatialem** [comment]
Further research is needed to carry out the [above proposal of two exposed CSS vars](https://github.com/Esri/calcite-components/issues/3392#issuecomment-1481920535).

In April we'll research further to assess a time estimate and priority prior to assigning to a future milestone for implementation.

**Comment by geospatialem** [comment]
Verified on `master`:

```css
--calcite-ui-focus-color: var(--calcite-ui-danger);
```

![button focus var verify](https://user-images.githubusercontent.com/5023024/234133922-2eb51652-2b09-474f-b289-2ec58cbb4882.png)
![switch focus var verify](https://user-images.githubusercontent.com/5023024/234134201-ce74f23c-8716-47f0-ad68-04fffd7903a8.png)



```css
--calcite-ui-focus-color: var(--calcite-ui-danger);
--calcite-ui-focus-offset-invert: 1;
```
![button focus var verify with offset invert](https://user-images.githubusercontent.com/5023024/234133997-7d3acc0c-79c1-414c-9e8c-82864a611b72.png)
