### ISSUE TITLE
Bug: setting the selected prop changes the size of Tip component

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#3398]
### Actual Behavior
Setting the `selected` property on the `calcite-tip` component changes the size/margins of the component and makes everything look strange.

### Expected Behavior
Setting the `selected` property doesn't make things look weird

### Reproduction Steps and Sample

_Sample_: https://developers.arcgis.com/calcite-design-system/components/tip/#sample

1. Add the `selected` property

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.68`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by benelan** [comment]
@asangma what is the `selected` prop used for?

**Comment by asangma** [comment]
The `selected` prop is used by TipManager to track which Tip is active.
It also allows Tip to style the `.container` in its shadow DOM in a way that works in TipManager.

My suggestion is to add a note in the doc about how the `selected` prop is used...?

**Comment by benelan** [comment]
Looks like this is [already documented](https://developers.arcgis.com/calcite-design-system/components/tip/#component-api-properties-selected). Closing the issue.
