### ISSUE TITLE
Bug:[calcite-panel] Dropdown items are hidden when combined with picklist in a panel 

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#3423]
### Actual Behavior

When we click on dropdown action icon , dropdown menu is hidden when the container width is `<225px` and the no of `dropdown-items` are <= 2

### Expected Behavior

when the dropdown is active, the items should be visible.

### Reproduction Steps and Sample

1. Click on the dropdown action icon 
2. Observe the dropdown menu wont pop-up.
3. Now change the width of the container to `225px` and the menu is visible

_Sample_:

1.https://codepen.io/ANVESHMEKALA/pen/RwZxeNX

### Relevant Info

Related to  #3048 
cc : @asangma 

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.68

**Comment by anveshmekala** [comment]
Related to #404 .

**Comment by jcfranco** [comment]
After https://github.com/Esri/calcite-components/pull/4182, this is [no longer an issue (`overlay-positioning="fixed` to escape the scrolling container)](https://codepen.io/jcfranco/pen/GRyewLy). @benelan @geospatialem Should we close this one?

**Comment by jcfranco** [comment]
> Quick ❓ on design implementation - is the intent to have the menu reside above the dropdown trigger? Looks like prior to the fix, the menu was displayed below the dropdown trigger. If so, then we can close.

I think so. Before, it was placing it within the scrolling container, so it had the extra space on the right. With `'fixed'`, it doesn't have enough space on the left for the bottom-trailing position, so it changes placement. It would be placed as expected If there were extra space on the left of the panel 

![Screen Shot 2022-04-22 at 9 12 14 AM](https://user-images.githubusercontent.com/197440/164753909-8bed1eb2-9022-49b7-9d47-3afb3c2bb55c.png)

or if the items were smaller.

![Screen Shot 2022-04-22 at 9 12 53 AM](https://user-images.githubusercontent.com/197440/164753927-bac53e56-0693-4011-a53b-bfe1c8a3a386.png)

cc @driskull

**Comment by driskull** [comment]
Yeah the positioning logic depends on space limitations

**Comment by benelan** [comment]
Thanks, closing issue based on ☝️
