### ISSUE TITLE
Dropdown group is displayed as inline but should be a block or flex displayed element

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#3427]
### Actual Behavior

Dropdown group is displayed as inline

### Expected Behavior

Dropdown group should be a block or flex displayed element

### Reproduction Steps and Sample

N/A

_Sample_:

1. https://codepen.io/driskull/pen/WNEMGgv

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by benelan** [comment]
reproducible in the doc sample: https://developers.arcgis.com/calcite-design-system/components/dropdown/#sample

**Comment by benelan** [comment]
verified on `beta.74`
