### ISSUE TITLE
calcite-tab: remove host color styles

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#3437]
### Actual Behavior

The `calcite-tab` content text color is being set to calcite-ui-text-3.

### Expected Behavior

The color of the content should not be set. This should be up to the developer to set if they choose to.

### Reproduction Steps and Sample
_Sample_:
https://developers.arcgis.com/calcite-design-system/components/tabs/
1. Go to the tabs example in docs
2. Inspect element on the text of the tab ('tab 1 content')
3. Notice that the color is being set to `var(--calcite-ui-text-3)`

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.68`

**Comment by benelan** [comment]
@joeyHarig, for future reference, it just asked for more info because the `Relevant Info` header is missing. No worries on this issue it won't be closed.

**Comment by benelan** [comment]
verified on next
