### ISSUE TITLE
Bug: [global CSS Vars] - font-family generic names should not have surrounding quotes 

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#3438]
### Actual Behavior

Remove surrounding quotes around global CSS vars for font-families: https://github.com/Esri/calcite-components/blob/master/src/assets/styles/_type.scss#L2-L3

Current (incorrect, bug):
```scss
--calcite-code-family: "Consolas", "Andale Mono", "Lucida Console", "Monaco", "monospace";
--calcite-sans-family: "Avenir Next", "Avenir", "Helvetica Neue", "sans-serif";
```

With the sans-family var, this causes Times New Roman to render instead of a sans-serif font in Windows:

![image](https://user-images.githubusercontent.com/42423180/140543808-d50f1450-0c17-44e7-8bfa-adda9e493539.png)

### Expected Behavior

In Windows, a sans-serif font displays by default:

![image](https://user-images.githubusercontent.com/42423180/140543964-23b48fff-5fa0-4fab-af62-4fff92c62e11.png)

### Reproduction Steps and Sample

_Sample_:

1. Open the following CodePen in Windows, notice a serif font displays (TNR): https://codepen.io/pen?template=RwgrjEx

### Relevant Info
MDN docs: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#values

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.68`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>` (no, been this way a while)

**Comment by benelan** [comment]
verified on `next`
