### ISSUE TITLE
Action Bar: add onHover text when expand-disabled or when text is cut off

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#3442]
### Description
If the width of the Action Bar is small the text gets cut off
![image](https://user-images.githubusercontent.com/10986395/140571652-093938d7-e9a3-41c6-8121-dfe0680720a6.png)
Additionally, when using the `expand-disabled` there is no text. 
![image](https://user-images.githubusercontent.com/10986395/140571855-ad3a3ae3-3e62-472c-9d1f-5621b8545281.png)

The user would like to display the text in a tooltip when hovering over an Action

### Acceptance Criteria 
Tooltip displaying the text when it is not visible
### Relevant Info 
From holistic feedback

#### Which Component
Action Bar

**Comment by macandcheese** [comment]
Related ... https://github.com/Esri/calcite-components/issues/4414

We could also look at not proportionally scaling the action-bar when expanded.

**Comment by macandcheese** [comment]
Looking at this again, I don't see a reason to limit the width of the action bar or try and scale it. Users can decide to set the collapse / expand display options if needed. As it stands almost all text is truncated even with small screen width adjustments. Thoughts @asangma ?

**Comment by geospatialem** [comment]
It appears like the `action-bar` no longer truncates. cc @benelan in case you still experience, we can re-open.
