### ISSUE TITLE
calcite-radio-group calls calciteRadioGroupChange on initial setup

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3453]
I noticed that the initial setup of calcite-radio-group already calls the calciteRadioGroupChange event.
See also https://github.com/Esri/calcite-components/issues/2938

### Actual Behavior

calls event on initial setup

### Expected Behavior

only calls event if the user clicks on radio button

### Reproduction Steps and Sample

https://codepen.io/afreitag/pen/XWaqwaM?editors=1000

_Sample_:

1.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.68`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by jcfranco** [comment]
This is no longer reproducible with the latest release: https://codepen.io/jcfranco/pen/dyVXrQL?editors=1000. Probably fixed via #3120.
