### ISSUE TITLE
Handle color should be darker.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3466]
### Description
The handle icon is currently a bit too subtle and can easily be missed especially if an end user's display contrast is cranked up.

### Acceptance Criteria 
More visible icon. Suggest text-color-3.

#### Which Component
CalciteHandle

#### Example Use Case
Low vision users or not perfect display setups...or just complex interfaces.

**Comment by geospatialem** [comment]
Current color values are meeting accessibility requirements within the design across `block` and `value-list` components - closing this issue out.
