### ISSUE TITLE
Component: ComboBox input

### ISSUE THREAD

**Issue by mitc7862** [Esri/calcite-components#349]
We need ComboBox inputs that allow users to manually type single-values (string, number, date or time) **OR** open and select from a dropdown (or date picker) to populate the input. 

Example:
![image](https://user-images.githubusercontent.com/12564905/75278068-11aa5600-57be-11ea-8261-243cd4f1b918.png)

**Comment by mitc7862** [comment]
As I briefly discussed with @macandcheese, the expected behavior here wouldn't open the date picker or drop down on focus as it would in a "super select". User's who type the value manually know exactly what value they want.

**Comment by macandcheese** [comment]
Thinking of the best way to add this to our roster... We currently have 3 components in progress that are somewhat similar to this:

- Calcite-input 
- Calcite-select
- Calcite-combobox 

I think this could be possible if using the "input action" slot with a dropdown that wrapped a button, or with an instance of date picker... But that would require users to style a button with a chevron / caret themselves... Use case makes sense just need to find a good way to make it fit with an existing component or think more prescriptive and make it it's own... 

Thoughts @driskull @jcfranco?

**Comment by paulcpederson** [comment]
New select component should just handle keyboard input. Date use case here is already complete and you can enter dates via keyboard as well. I think we can close this. Feel free to reopen if I've jumped the gun!
