### ISSUE TITLE
Enhacement: Match animation timing global variable value with calcite base transition  & add scales for animation timing variable

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#3491]
### Description

Global transition variable is added in #2607  which allows to customize the duration time for animation/transitions which is currently set to `300ms` . Match `--calcite-animation-timing` global variable value with `calcite-base` [transition](https://github.com/Esri/calcite-base/blob/master/dist/_variables.scss#L2) value which is `150ms` . With the [audit](https://github.com/Esri/calcite-components/wiki/Animation-&-Transition-duration-Audit) of animation duration, it is clear that component have different values and we need to have different levels of animation duration variables.

### Acceptance Criteria 

1. `--calcite-animation-timing` value should be set to `150ms`
2. Make sure any existing components utilizing this var should be updated
3.  Add multiple levels of animation timing variable to support component across CC repo.
4.  List of tailwind UtilClasses using `--calcite-animation-timing`  :
- animate-in
- animate-in-down
- animate-in-up
- animate-in-scale
5. Update components utilizing above mentioned tail wind classes

### Relevant Info 
Refer to #3081 

#### Which Component
List of components utilizing tailwind util classes with `--calcite-animation-timing`:

- [ ]  [calcite-action-pad](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-action-pad/calcite-action-pad.scss#L3)
- [ ] [calcite-block](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-block/calcite-block.scss#L144)
- [ ] [calcite-shell](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-shell/calcite-shell.scss#L91)
- [ ] [calcite-shell-center-row](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-shell-center-row/calcite-shell-center-row.scss#L27)

**Comment by benelan** [comment]
@macandcheese can you please help verify this installed design issue?

**Comment by macandcheese** [comment]
Looks great - thanks for the work on this @anveshmekala. cc @asangma for reference.

**Comment by benelan** [comment]
verified on next!
