### ISSUE TITLE
calcite-action-bar inside shell-center-row expand tooltip doesn't work at first

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3495]
When adding the action-bar programmatically the expand tooltip doesn't work initially. Once you expand and collapse the action-bar the expand tooltip starts working.

![image](https://user-images.githubusercontent.com/44481292/141387420-4f57b38f-26b1-47cc-b7da-0ced1c35dace.png)

cc @driskull 

### Actual Behavior

expand tooltip doesn't work initially

### Expected Behavior

expand tooltip should work from the start

### Reproduction Steps and Sample

https://codepen.io/afreitag/pen/RwZBxKa

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.69`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by driskull** [comment]
This is due to the use of the getSlotted utility...

The utility dom.getSlotted() is great, but one problem is that if a user slots an element after initialization using JS, the getSlotted() method doesn't know about the newly slotted element until a re-render occurs. 
 
We might want to setup a mutation listener to re-render for those scenarios.

>>> Yeah, that makes sense. There is also a slot event when its content changes that we could listen for to rerender.

**Comment by driskull** [comment]
@benelan @jcfranco Can you triage this? I think we need a utility refactor first.

**Comment by benelan** [comment]
This issue is currently in the next sprint starting 12/20. Do you think it needs to be in the current sprint starting today?

**Comment by driskull** [comment]
I think that's fine.

**Comment by driskull** [comment]
@jcfranco Is this the approach we want to take?

```tsx
<slot name={SLOTS.expandTooltip} onSlotchange={() => forceUpdate(this)} />
```

It would look something like this...

```tsx
<calcite-action-group class={CSS.actionGroupBottom} scale={scale}>
        <slot name={SLOTS.bottomActions} />
        <slot name={SLOTS.expandTooltip} onSlotchange={this.slotChanged} />
        {expandToggleNode}
      </calcite-action-group>
```

```tsx
slotChanged = (): void => {
    forceUpdate(this);
  };
```

**Comment by driskull** [comment]
This would also involve going through any component that uses `getSlotted` and adding an `onSlotchange` listener to call forceUpdate.

**Comment by jcfranco** [comment]
According to MDN, [`onslotchange`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event) bubbles, so we could look at adding a util for any components using slots (`SlottedComponent`).

**Comment by driskull** [comment]
@jcfranco There's no JSX listener defined for anything other than the slot tag it seems. So we would have to manage the listener I think.

**Comment by jcfranco** [comment]
If we add a utility similar to our other ones we can manage the listeners.

**Comment by driskull** [comment]
This doesn't seem to work for me. Not sure why...

```
<Host
        onCalciteActionMenuOpenChange={this.actionMenuOpenChangeHandler}
        ref={(el) => {
          el.addEventListener("slotchange", this.slotChanged);

Doesn't seem like it does bubble.
        }}
      >
```

**Comment by jcfranco** [comment]
You have to attach it to the shadow root. `onslotchange` bubbles, but isn't composed, so it won't reach the host.

**Comment by driskull** [comment]
Ok, yep that works. cool

**Comment by benelan** [comment]
verified on `beta.71`, cool stuff!
