### ISSUE TITLE
Panel is dismissed on escape keyup rather than keydown

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#3500]
### Actual Behavior

A dismissible panel is closed with 'escape' on keyup, while other components like dropdown and combobox are closed on escape keydown. 

### Expected Behavior

Panel should also be dismissed on escape keydown for consistency. Using the same event would make it simpler to stop propagation of that event in the case you have for example a dropdown inside a dismissible panel, where closing the dropdown using escape should not also close the panel. 

### Reproduction Steps and Sample

_Sample_: https://codepen.io/ellupp/pen/vYJzQWQ?editors=1000

1. Open dropdown. Press and hold escape key. Dropdown closes on keydown. Release escape key. Panel is dismissed on keyup.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.69`

**Comment by benelan** [comment]
verified on next
