### ISSUE TITLE
popover inside stepper-item only works in vertical layout

### ISSUE THREAD

**Issue by jgrew** [Esri/calcite-components#3513]
Popover inside stepper-item only displays when stepper is set to layout="vertical"

### Actual Behavior

Popover only displays in vertical stepper layout

### Expected Behavior

Popover should display in horizontal stepper layout

### Reproduction Steps and Sample

https://codepen.io/jgre/pen/jOLQLaV?editors=1010

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.69`

- [x] CDN
- [x] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by jcfranco** [comment]
This could be related to https://github.com/Esri/calcite-components/issues/1258.

**Comment by driskull** [comment]
Yep, seems to be related.

**Comment by jcfranco** [comment]
Fixed via https://codepen.io/jcfranco/pen/LYdbBLw?editors=1010.

**Comment by geospatialem** [comment]
Verified on `next.533` ✔️ 

![verify-popover-stepper-horizontal](https://user-images.githubusercontent.com/5023024/179317328-731fdf66-1116-4c60-bacf-a8c8c1833a8f.png)
