### ISSUE TITLE
Calcite-button: when having empty icon-end or icon-start, it adds padding

### ISSUE THREAD

**Issue by yannikmesserli** [Esri/calcite-components#3529]
### Actual Behavior

```typescript
<calcite-button icon-end>Test</calcite-button>
```

Has extra padding at the end. 

### Expected Behavior

No padding

### Reproduction Steps and Sample

A sample code: https://codepen.io/yannikm/pen/VwzqEzZ?editors=100

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [x] CDN
- [x] NPM package

Not a regression

**Comment by benelan** [comment]
verified on next
