### ISSUE TITLE
Design: Tooltip and ActionPad in a Popover look similar

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#353]
## Tooltip
![image](https://user-images.githubusercontent.com/12503298/75489067-6f79a200-5966-11ea-8eca-91c16a71aa32.png)

## ActionPad in a Popover
![image](https://user-images.githubusercontent.com/12503298/75489120-83250880-5966-11ea-922c-29c0425e97eb.png)

Is this good or bad?
Should I stay or should I go now?

cc @driskull @jcfranco @paulcpederson

**Comment by driskull** [comment]
🤷‍♂

**Comment by asangma** [comment]
Thanks for the discussion y'all. Closing this and applying some app level changes.
