### ISSUE TITLE
CalciteButton - incorrect layout with space-between

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3533]
### Actual Behavior
When Button has `alignment="space-between"` and `width=[ "half" | "full" ]`, the layout has extra space in the start area.
This seems to be caused by the loader still taking up space.

This may also cause issues with `icon-start-space-between` and `icon-end-space-between`.

### Expected Behavior
The loader shouldn't take up space if it's not visible.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/mtb-alan/pen/oNemXBO

1. Set CalciteButton width to "half"
2. Set Calcite Button alignment to "space-between"
3. observe

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by benelan** [comment]
verified on next
