### ISSUE TITLE
Suggestion: add browser support by platform to README

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#3536]
### Description 

README lists four supported browsers. It would be helpful to know on what operating systems these browsers are supported. Or should we assume that if you can get the browser flavor on your platform, calcite-components will be supported?

The browsers are widely available across platforms:
* Windows: Brave, Chrome, Firefox, & Edge
* MacOS: Brave, Chrome, Firefox, Safari, & Edge
* iOS: Brave, Chrome, Firefox, Safari, & Edge
* Android: Brave, Chrome, Firefox, & Edge

### Which Component

all

**Comment by benelan** [comment]
Hi @MikeTschudi, we appreciate the suggestion, however we are going to keep the supported browsers information the same for now. Just FYI, we don't have a mobile story at the moment, but if you run into issues on any of the platforms feel free to log an issue and we will investigate!
