### ISSUE TITLE
New component: Splitter

### ISSUE THREAD

**Issue by rslibed** [Esri/calcite-components#3537]
### Description
A component that allows users to easily resize the dimensions of a panel(s) by dragging an element on the page. 

Example: https://www.telerik.com/kendo-angular-ui/components/layout/splitter/

### Acceptance Criteria 
- Provide the ability to slot this into existing components like `calcite-shell-panel` or expose an attribute/property to enable/disable this behavior
- Ability to use this component with plain HTML elements i.e. `div`
- A property on limiting how wide or narrow a user can resize a panel would be useful

### Helpful details
In the Instant Apps configuration experience, the UI elements within the side panel can appear to be limited in space or "squished" at times. Allowing users to easily resize the panel with a draggable element can help with this.

**Comment by rslibed** [comment]
cc: @kellyhutchins @bcree11 @csmith246

**Comment by benelan** [comment]
This seems like a duplicate of #2770, can you confirm @rslibed ?

**Comment by rslibed** [comment]
Yep! Looks like a duplicate. Thanks for referencing that issue. Closing.
