### ISSUE TITLE
calcite-alert: Automatically generate "id" attribute on creation

### ISSUE THREAD

**Issue by cosbyr** [Esri/calcite-components#354]
Alert Queue functionality requires that each calcite-alert element has a unique "id" attribute. 

Rather than requiring users to generate this id and assign it to each alert, can we have a new guid id automatically generated on creation?

FYI, @macandcheese

**Comment by macandcheese** [comment]
Thanks for submitting @cosbyr - this will be a good addition. If a user doesn't provide an id themselves, we can fall back to a generated guid.

Just to confirm, you are using a custom data attribute to target an alert to open, correct? `document.querySelector('[data-custom-id=myalert]').open()`

**Comment by cosbyr** [comment]
@macandcheese, we are doing this:
```ts
const alert = document.createElement("calcite-alert");
alert.id = // assign it a random id here <-- it would be nice to skip this part
//..... giving the alert some more attributes here... appending alert-message and alert-link divs
alert.open()
```
we then listen to the calciteAlertClose event and remove them from the DOM when finished by using the event.target property.

**Comment by macandcheese** [comment]
Gotcha - yeah that makes sense. 👍 

You'd lose the ability to explicitly call `close()` on an open or queued alert as we probably won't make the GUID a public prop... currently you can call close() on an alert to close or remove it from the queue if you know its id / data-custom id... but that's kind of a weird use case anyway.

This update will make queue "just work" for your use case and it's still something folks can achieve by just using id / data-custom-id if they wish to have that kind of control over opened alerts.
