### ISSUE TITLE
Unstable Test: calcite-input › number type › tests related to output of increment/decrement on long hold 

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#3540]
## Summary

**Input of type number**

**Which test(s)?:**

correctly increments and decrements on long hold on mousedown and step is set to a decimal
should emit an event every 100ms on keyboard down ArrowUp/ArrowDown and stop on keyboard up

**Test error:**

 FAIL  src/components/calcite-input/calcite-input.e2e.ts (169.812 s)
  ● calcite-input › correctly increments and decrements on long hold on mousedown and step is set to a decimal

    expect(received).toBe(expected) // Object.is equality

    Expected: "0.12"
    Received: "0.11"

      307 |     await page.mouse.up();
      308 |     await page.waitForChanges();
    > 309 |     expect(await input.getProperty("value")).toBe("0.12");
          |                                              ^
      310 |
      311 |     await page.mouse.move(buttonDownLocationX, buttonDownLocationY);
      312 |     await page.mouse.down();

PR that skipped the test: #3542

## Additional Info

The 2 tests I added last are sometimes off by one step and need to be rerun. Maybe these are too detailed: expecting a certain number of steps per interval. Need to make it less specific and just check if the long press results in multiple increments for decimal or integer steps.  

Reason is that "the specified amount of time (or the delay) is not the guaranteed time to execution, but rather the minimum time to execution. The callbacks you pass to these functions cannot run until the stack on the main thread is empty".

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Timeouts_and_intervals

**Comment by benelan** [comment]
Hi @Elijbet, unstable test issues are marked as installed after the test is no longer unstable. The PR to fix the test and un-skip it would be the one to resolve this issue. Setting this back to assigned (these issues are low priority for the most part).

**Comment by jcfranco** [comment]
Stabilized via https://github.com/Esri/calcite-components/pull/3566. 🐴 🤠 💨

**Comment by benelan** [comment]
Its been two weeks and I haven't seen this test fail, verified!
