### ISSUE TITLE
DropDownItem is missing flex definition

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3541]
### Actual Behavior
The `.dropdown-item-content` does not have a flex definition. This means that content layout inside the default slot is inconsistent due to the inability to accurately calculate the width of the container.

### Expected Behavior
`.dropdown-item-content` should have flex defined, e.g. `flex: 1 1 auto`.

### Reproduction Steps and Sample
View the sample below.

_Sample_: https://codepen.io/mtb-alan/pen/abyXxwJ

1. click the dropdown trigger
2. observe how the image and text are right next to each other.
3. inspect the code
4. add the above style (via browser) to `.dropdown-item-content`.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by asangma** [comment]
@benelan This is probably a one-line fix if someone wants to add it to their PR.

**Comment by macandcheese** [comment]
We should probably add the content start / end slots to dropdown item as well when that larger refactor takes place, which could solve for this long term.

**Comment by asangma** [comment]
@macandcheese Totes agree. It's probably still good for a default container to use the full width so that if something is `width: 100%` inside there, the resulting width calculation makes sense, yeah?

**Comment by asangma** [comment]
Woot!
