### ISSUE TITLE
Deprecate calcite-radio by moving markup and styles into calcite-radio-button

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#3543]
### Description 

Now that `calcite-radio-button` is shadowed, the `calcite-radio` component, which originally existed purely to encapsulate the Esri radio branding behind a shadow root so that `calcite-radio-button` could expose its child native input as a scoped component (for native form integration), is no longer needed.

### Proposed Advantages 

This ticket will deprecate the separate internal `calcite-radio` component, removing an unnecessary separate element, and add the markup and styling for the UI it produces into `calcite-radio-button`.

### Relevant Info 

During this process would also be a good opportunity to refactor the CSS to move away from attribute selectors into CSS classes, since `calcite-radio` relies heavily on these.

#### Which Component

`calcite-radio`, `calcite-radio-button`

**Comment by benelan** [comment]
verified on next. `calcite-radio-button` doesn't look or behave differently than before
