### ISSUE TITLE
Enhancement: Calcite-panel sticky header

### ISSUE THREAD

**Issue by sam11927** [Esri/calcite-components#3544]
### Description
There should be an option to make the header of a `calcite-panel` sticky to the top (`position: fixed`).
### Acceptance Criteria 
The header can stick to the top of a panel
#### Which Component
`calcite-panel`
#### Example Use Case
A panel header has a scroll to top button and it is useless unless the user can always see the header.

**Comment by macandcheese** [comment]
@sam11927 Could you clarify this a bit or provide a Codepen? Is this a request to have `calcite-blocks` sticky to the top of a panel?

**Comment by macandcheese** [comment]
Closing as stale - feel free to re-open with a reproduction case or further information.
