### ISSUE TITLE
Consider substituting input type="hidden" for CSS in form component utility

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#3545]
### Description 

The hidden input that is created by the `defaultSyncHiddenFormInput` helper in components that implement the `FormComponent` (and other derivatives like `CheckableComponent`) could be updated to make the input's `type` set to `"hidden"` so that implementing components don't have to employ the `hidden-form-input()` Sass mixin just to visually hide it in the UI.  

Ionic does exactly this in their similar implementation for hidden form inputs: https://github.com/ionic-team/ionic-framework/blob/e4bf052794af9aac07f887013b9250d2a045eba3/core/src/utils/helpers.ts#L203

### Proposed Advantages 

This would eliminate the need for a Sass mixin while taking advantage of native support for hidden inputs.  It would also reduce the complexity and potential bugs in implementing the `FormComponent` interface in form components.

#### Which Component

Any form-associated component.

**Comment by jcfranco** [comment]
[Belated] Validation will break if we change the form inputs to use the "hidden" type or the hidden attribute, so we would still need the mixin.

**Comment by jcfranco** [comment]
Closing based on ☝🏼 .
