### ISSUE TITLE
color-picker not initializing values properly when set early while using the custom-elements bundle

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3552]
### Actual Behavior

Creating a color-picker instance programmatically and setting its `value` property should get picked up properly.

### Expected Behavior

The initial value gets process properly regardless of the output target being used.

### Reproduction Steps and Sample

_Sample_: https://codesandbox.io/s/calcite-components-color-picker-initial-value-setting-in-custom-elements-bundle-t3seb?file=/src/main.js

1. Notice how the initial value gets set, but the color picker does not display it.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.69`

- [ ] CDN
- [x] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by benelan** [comment]
verified on next
