### ISSUE TITLE
Enhancement: calciteCheckboxChange event should include state

### ISSUE THREAD

**Issue by ajturner** [Esri/calcite-components#3567]
### Description

currently `calciteCheckboxChange` [emits an empty event](https://github.com/Esri/calcite-components/blob/555594ea03d79a54e443210b176fbc5bad8e88bb/src/components/calcite-checkbox/calcite-checkbox.tsx#L126)

It would be useful for listeners to include the current checkbox state in the event.

### Acceptance Criteria 

`event.detail.value` is the new state of the checkbox

### Relevant Info 

Without this event consuming components need a handle to the element to request state, or cast the target `(event.target as HTMLCalciteCheckboxElement).checked`

#### Which Component

`calcite-checkbox`

#### Example Use Case

```ts
@Listen('calciteCheckboxChange')
  mapUpdateControlChanged(event: CustomEvent) {
    this.mapUpdate = event.detail.checked;
  }
```

**Comment by jcfranco** [comment]
> Without this event consuming components need a handle to the element to request state, or cast the target (event.target as HTMLCalciteCheckboxElement).checked

This is by design and is the preferred choice to get the component's value (going through the event's `target`/`currentTarget`). cc @benelan
