### ISSUE TITLE
calcite-combobox: overlay-positioning='fixed' causes menu to become width of viewport

### ISSUE THREAD

**Issue by kstinson14** [Esri/calcite-components#3578]
### Actual Behavior
When `overlay-positioning='fixed'` is set on a `calcite-combobox`, the menu becomes the width of the viewport rather than being constrained to the width of the combobox itself:
![Screen Shot 2021-11-29 at 2 10 43 PM](https://user-images.githubusercontent.com/17748358/143928153-6a07859d-dbdd-4fa3-b7c8-47c5e9dc987e.png)

### Expected Behavior
I would expect that changing the `overlay-positioning` value would not affect the menu's width.  In Field Maps, we currently have a combobox inside an element with `overflow: hidden` on it.  We'd like to allow the menu to overflow the container while still being constrained to the width of the combobox itself (which can have a variable width).

### Reproduction Steps and Sample
I believe any combobox with `overlay-positioning='fixed'` that is smaller than the width of the viewport should show this issue.

Codepen: https://codepen.io/kstinson/pen/KKXKMQK

### Relevant Info

This is related to https://github.com/Esri/calcite-components/issues/1913 and https://github.com/Esri/calcite-components/issues/2069.  I found this issue while trying to fix the menu positioning on a `calcite-combobox` in a container with `overflow: hidden` on it.  While searching this repo, I found the two issues above, for which `overlay-positioning` was added as a solution.

Unfortunately, the property doesn't seem to have the desired effect for the combobox component.  I think making the menu `fixed` removes its constraints to the parent `combobox` element, and it instead uses its `width: 100%` styling to inherit the width of the viewport rather than the `combobox`.

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.70`

- [ ] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/calcite-5f7d10460071bf0024e66277/issues/Esri/calcite-components/3578?planning-poker) with ZenHub @driskull

**Comment by driskull** [comment]
> Do you know if Popper requires all parent containers to have visible overflow? 

Yes, I think so. That's why the element needs to be placed in the body sometimes.

**Comment by jgrayson-apl** [comment]
Not sure if this helps, but changing the _display_ style property of the _.popper-container_ to _'contents'_ fixed this issue in may app.

https://codepen.io/john-grayson/pen/MWVOvme

**Comment by jcfranco** [comment]
@jgrayson-apl Thanks for sharing that workaround! @benelan Maybe we could add a note about this to https://github.com/Esri/calcite-components/issues/4355. 

Perfect timing though, as the fix for this [landed today](https://github.com/Esri/calcite-components/pull/5045): https://codepen.io/jcfranco/pen/VwXrzdE

**Comment by jgrayson-apl** [comment]
wow... you guys jumped on that quickly!  Sorry, after further testing I realized it only _seemed_ like it was working... unfortunately that display setting invalidates the 'fixed' positioning, which I didn't realize until I tried the fix on a combobox that was not the last item in my block.  ...apologies...

**Comment by jcfranco** [comment]
No worries. Thanks for following up! 🏆

**Comment by benelan** [comment]
> Perfect timing though, as the fix for this https://github.com/Esri/calcite-components/pull/5045: https://codepen.io/jcfranco/pen/VwXrzdE

Verified on next using Franco's sample
