### ISSUE TITLE
Conventions: Naming conventions for attributes

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#36]
@driskull @ycabon Agreed we should document naming conventions https://github.com/ArcGIS/calcite-components/pull/32#discussion_r290522166.

Examples:

* `active` not `isActive`
* `disabled` not `isDisabled`

Some components will have to change to accommodate this.

**Comment by macandcheese** [comment]
We still need to do a pass on this...
scale, size (xs vs extraSmall), appearance, etc.

**Comment by macandcheese** [comment]
As mentioned in https://github.com/Esri/calcite-components/pull/232#discussion_r346942353 - we should also look at updating and standardizing "color" attribute when it is in effect used to convey status / meaning of component (ie alert is currently red, green, yellow, blue -> warning, success, caution, information)...

**Comment by julio8a** [comment]
What's the status of this issue? can we close for now?

**Comment by macandcheese** [comment]
Opened: https://github.com/Esri/calcite-components/issues/359

We still need to clarify guidelines around active/selected. I think color is good as is....

**Comment by julio8a** [comment]
Okay, closing this one out. re-open if needed.
