### ISSUE TITLE
Bug: can't pan a jsapi map behind a detached shell-panel

### ISSUE THREAD

**Issue by MukeZ** [Esri/calcite-components#3604]
### Actual Behavior

The issue is that you cannot drag the "map" under a `calcite-panel` when the panel is displaying.

### Expected Behavior

You should be able to drag the "map" under a `calcite-panel` when the panel is displaying.

### Reproduction Steps and Sample

It worked in the version 1.0.0-beta.69, but not working since 1.0.0-next.295.

It can be easily reproduced by switch the version of script.

_Sample_:

1. [link](https://codepen.io/mukez/pen/PoJwNwZ)

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-beta.69-<version>`

**Comment by benelan** [comment]
Something is funky with the provided sample, it looks like you didn't include the Calcite Components CSS? I was not able to reproduce it here: https://codepen.io/benesri/pen/JjroXgd

**Comment by MukeZ** [comment]
> Something is funky with the provided sample, it looks like you didn't include the Calcite Components CSS? I was not able to reproduce it here: https://codepen.io/benesri/pen/JjroXgd

Sorry, I just updated CSS, but it already reproduced in your sample.

For example, you cannot drag the map in this area 
![image](https://user-images.githubusercontent.com/9669996/144149289-e218779f-8f58-4b7d-82ef-4949d6353d50.png)

**Comment by benelan** [comment]
Ah I got it, thanks for reporting this issue! `1.0.0-next.295` was released for [this feat](https://github.com/Esri/calcite-components/commit/2c5fdcc2dd39a3941d22b787fc13e25d0080ebdb), @asangma can you take a look? It actually looks like an issue with `calcite-shell-panel`. Here is a [simplified repro sample](https://codepen.io/benesri/pen/OJxPybZ?editors=1000).

### Steps
1. Click on the map view (a black border around the map should appear, is this a side effect or design choice? cc @macandcheese)
2. Click somewhere near the left edge of the map (where the detached panel is) and drag. Doing so will not pan. Click/drag from the right side works fine
3. Change the version to `beta.69` and repeat the two steps above; it pans correctly

**Comment by jcfranco** [comment]
Verified via https://codepen.io/jcfranco/pen/BawKxaZ?editors=1000.
