### ISSUE TITLE
pointer cursor shown by calcite-label can be misleading if it has no interactive content

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3609]
### Actual Behavior

Any content wrapped in a calcite-label will cause the pointer cursor to be shown on hover.

### Expected Behavior

Label should not modify the cursor. This should be handled individually by components. 

### Reproduction Steps and Sample

_Sample_: https://codepen.io/jcfranco/pen/abLzWZP?editors=1000

1. Note the cursor change when hovering over a label-wrapped, non-interactive div.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by anveshmekala** [comment]
@jcfranco Is it expected from label component to delegate the pointer cursor for slotted labelable components ?

**Comment by jcfranco** [comment]
I updated the description. In short, label should not modify the mouse cursor since it doesn't know about its children.

**Comment by benelan** [comment]
verified on next
