### ISSUE TITLE
Calcite-button enhancement: change transition configuration

### ISSUE THREAD

**Issue by kstinson14** [Esri/calcite-components#362]
Right now I'm working on making a split button/dropdown menu component, and I'd like to make it change dimensions / text on screen resize.  However, the process is a bit awkward-looking due to the `calcite-button`'s transition configuration. 
 
![resize](https://user-images.githubusercontent.com/17748358/76105143-6611ba80-5fa2-11ea-865b-913883587e26.gif)

Currently, the button (and the button's icon) transition on changes to all properties.  However, I'd rather not have them transition on things like width, height, padding, margin, etc. in this case.  Could we change buttons to only transition on a few properties (background-color, opacity, color, might be missing some others).  Or better yet, could we maybe have those as a default, but configure on the consuming side what we'd like to transition on?

**Comment by macandcheese** [comment]
Looks like this was addressed in the `split-button` PR - safe to close @kstinson14 ?

**Comment by macandcheese** [comment]
I believe this was added in the PR for `split-button`.
