### ISSUE TITLE
Radio group and button do not match at same scale.

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#3624]
### Actual Behavior

Sometimes component scales don't always match up. For example on https://developers.arcgis.com/net/uwp/sample-code/ we have a `<calcite-radio-group>` next to a `<calcite-button>` both are "medium" scale:

![2021-12-03_13-03-59](https://user-images.githubusercontent.com/378557/144672632-5d87a5b4-c6d1-4150-b98c-968780e34cd4.png)

If I want the heights to match I either need to set the radio buttons to large or the button to small to match the heights be then the text looks either to small or too large.

### Expected Behavior

I generally would expect components like these to share a similar height. They previously matched but now do now match.

### Reproduction Steps and Sample

https://developers.arcgis.com/net/uwp/sample-code/

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.55`

- [ ] CDN
- [x] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by benelan** [comment]
You can disregard the bot, the sample provided is reproducible

**Comment by patrickarlt** [comment]
It is worth noting that I did fix this by simply setting `height`  on the `<calcite-radio-group>` but I think the issue still stands that there might be a need for some way to sync sizes across components.

**Comment by y0n4** [comment]
Hi. I tried to reproduce with the html source including the class styling used just for those components (`calcite-radio-group`, `calcite-label`, `calcite-button`). I think it seems like this issue is not present in the latest version

@1.0.0-beta.55
https://codepen.io/yonacorn/pen/PoJeMqX

@1.0.0-beta.73 (latest)
https://codepen.io/yonacorn/pen/ExwRLWW

**Comment by benelan** [comment]
@macandcheese can we get your input on this one? It does look like they are pretty close, maybe a couple pixels off. Here it is without all of the custom classes:
https://codepen.io/benesri/pen/poWKVqE?editors=1000

**Comment by macandcheese** [comment]
Just to confirm - these components both have a height of 32px at the link above, so I think this is safe to close.
