### ISSUE TITLE
calcite-popover does not work properly when inside a component's shadow-dom

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-components#3625]
[This](https://github.com/Esri/calcite-components/issues/1844) issue is similar but I don't think it's exactly the same.

### Actual Behavior

If I create a stencil component with a `calcite-popover` in it, the popover will not work properly **if the component has `shadow: true`**. Specifically:

1. The popover will not open  when you click the toggle button (unless I explicitly open it with a click handler on the button or an `open` attribute`).
2. The `auto-close` attribute causes the popover to auto close when you click _inside_ the popover.

### Expected Behavior

I expect the popover to open when I click the toggle button and `auto-close` to  close the popover when you click _outside_ of it but _not inside_. I expect it to work like [this codepen](https://codepen.io/mjuniper/pen/MWvdjYP) which has almost identical markup to my test case stencil component.

### Reproduction Steps and Sample

Everything works as expected in my codepen: https://codepen.io/mjuniper/pen/MWvdjYP

And it works as expected in my [test case PR/branch](https://github.com/mjuniper/calcite-components/pull/3) **if I turn off shadow DOM.**
But it does not work in the test branch with `shadow: true`.

### Relevant Info

Reproducible version: @esri/calcite-components@1.0.0-next.312

**Comment by driskull** [comment]
@mjuniper I have a PR with a fix. Do you think you could test it out in your app? https://github.com/Esri/calcite-components/pull/4014

**Comment by benelan** [comment]
@mjuniper this should be fixed in `beta.76`, can you please try testing it in your app?

**Comment by mjuniper** [comment]
Shoot, sorry i missed those comments. Yes, it is fixed! Thanks a bunch!
