### ISSUE TITLE
Bug: calcite-date-picker min and max not updating

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#3645]
### Actual Behavior

Date-picker doesn’t update internally when min/max attributes are updated after initialization.

### Expected Behavior

Should be able to change the min/max props and have it update internally.

### Reproduction Steps and Sample

The following code pen includes steps to reproduce this bug.
https://codepen.io/elijbet/pen/ZEXWyPM?editors=1001

### Relevant Info

Reproducible version: @esri/calcite-components@v1.0.0-beta.71

**Comment by jcfranco** [comment]
Moving to current milestone. cc @benelan

**Comment by benelan** [comment]
verified on next
