### ISSUE TITLE
Closing and Opening of Calcite Tree Children does not work as expected

### ISSUE THREAD

**Issue by moosetraveller** [Esri/calcite-components#3646]
### Description

I was not sure if that would be a bug or an enhancement. In my opinion it's a bug. However, I was not sure if the behaviour is as intended by design. Therefore, I submit an enhancement issue. Please change labels if applicable/needed.

Click on the expand/collapse icon, checkbox or label of the 'group' item does not work as expected when `selectionMode="ancestors"`:

![Example Tree 2](https://user-images.githubusercontent.com/3456293/145121516-5f3b0580-1ea9-44e1-b928-681b7173844d.gif)

### Acceptance Criteria 

- click on the checkbox should only select/deselect all items within the 'group' and not close the 'group' (if open) 
    - reason: a user may want to deselect some children (if there are 10 children and 9 of them should be selected, a user is faster to select the whole group and deselect one child)
- click on label of a 'group' should not change the value of a the checkbox
    - reason: if clicked by accident (not expecting the behaviour like me) then it can be a lot of work to re-select the desired children
    - it may be another matter in case of a child (personally I think, even then, it should not change the checkbox' value (if within a tree))
- click on 'expand/collapse' icon should only open and close the 'group' (it can be finicky not to hit the margin/padding of the label)
    - reason: a user wants to explore the children

### Relevant Info 
see description

#### Which Component
Tree

**Comment by benelan** [comment]
verified on `beta.74` using the doc sample with `selection-mode="ancestors"` https://developers.arcgis.com/calcite-design-system/components/tree/#sample
