### ISSUE TITLE
Document officially supported locale list

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#3660]
### Description 

This ticket will address documenting the official list of supported locales in calcite components and updating demo pages like the one used for time picker.

### Which Component

All

### Resources 

ArcGIS API for Javascript official locale support page: https://developers.arcgis.com/javascript/latest/localization/#locale-support

**Comment by eriklharper** [comment]
cc @benelan @jcfranco

**Comment by benelan** [comment]
Assigning this to Kitty since she already has a PR open for it: https://github.com/ArcGIS/afd-calcite-documentation/pull/417

**Comment by geospatialem** [comment]
Merged to dev - go live anticipated next Wednesday, 5/11. Can get a sneak peak via the next preview: `/localization/#locale-support`.

**Comment by benelan** [comment]
verified on next (in a different repo)
