### ISSUE TITLE
Calcite Dropdown - Dropdown positioning is incorrect when nested in shadow DOM - Only in Browsers other than Chrome (confirmed in Firefox & Safari)

### ISSUE THREAD

**Issue by Csmith246** [Esri/calcite-components#3667]
### Actual Behavior

Issue can be seen in following codepen, when using FF or safari (it behaves properly in Chrome)(https://codepen.io/csmith55/pen/NWardEd?editors=1000)

Dropdown opens further to the right than it should. This appears to be a cumulative effect

![image](https://user-images.githubusercontent.com/22039422/145312230-17f7b4fc-6351-42a3-bd14-cd59b378f21c.png)

### Expected Behavior

Dropdowns to open attached to button, as usual

### Reproduction Steps and Sample

Open Codepen with FF, and press dropdown button

_Sample_:

1. provided

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>` - all

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>` - all

**Comment by driskull** [comment]
Seems to be fixed if the `calcite-dropdown` is positioned as relative within the shadowDom.

**Comment by jcfranco** [comment]
This is blocked by https://github.com/Esri/calcite-components/issues/3815.

**Comment by jcfranco** [comment]
Local testing w/ latest version of `floating-ui` (see https://github.com/Esri/calcite-components/issues/3815#issuecomment-1201698447 for more info) seems to work as expected. Marking as installed!

**Comment by geospatialem** [comment]
Verified placement in Firefox with next.557 via https://codepen.io/geospatialem/pen/VwXBGNv.

![verified dropdown positioning](https://user-images.githubusercontent.com/5023024/183940467-4776652a-0d7a-476f-8fea-a1385cd1e166.png)
