### ISSUE TITLE
[IE11] Date Picker - Functionality and styling are broken

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#368]
Seems like there are some issues with the Date Picker in IE11 - haven't dived in to look. Also seems like dark theme vars aren't being applied to the child components that do render:

<img width="363" alt="Screen Shot 2020-03-06 at 3 37 41 PM" src="https://user-images.githubusercontent.com/4733155/76131165-3ffc1280-5fc2-11ea-8f97-99c95d5264a3.png">

**Comment by paulcpederson** [comment]
I'm going to look into this today.
