### ISSUE TITLE
setAssetPath() and a hard-coded `/assets` path

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/calcite-components#3681]
### Actual Behavior

When consuming calcite-components via NPM while using assets locally, if I specify my own unique destination folder name when copying assets from `node_modules` and call `setAssetPath()`, icon resources cannot resolve the correct URL and break in my live web application.

Caveat: if I ensure that `/assets` is present in the destination folder path and that `/assets` is present in my call to `setAssetPath()`, things work as expected and I am able to use assets locally without relying on the CDN.

### Expected Behavior

I would expect to be able to specify my own folder name that differs from `/assets` when copying and using your assets myself.

As an alternative expected behavior, local asset management guiding docs and examples should state that `/assets` must be present in the destination folder structure and used appropriately with `setAssetPath()`.

### Reproduction Steps and Sample

Similarly to your Vite example repo that uses `rollup-plugin-copy` (<https://github.com/Esri/calcite-components-examples/tree/master/vite>), instead try out `ncp` to copy assets, for example in `package.json`.

_Side comment: Why `ncp`? Because I am using it already in a similar situation after following the ArcGIS API for JavaScript suggestion here: <https://developers.arcgis.com/javascript/latest/es-modules/#managing-assets-locally>_

1. This does work because `/assets` is simply used as the destination. Run `npm install` or `npm run postinstall` or `npm run copy-calcite-components-assets`.
    ```json
    "postinstall": "npm run copy-calcite-components-assets",
    "copy-calcite-components-assets": "ncp ./node_modules/@esri/calcite-components/dist/calcite/assets ./public/assets"
    ```

2. This does **not** work because `/calcite-components-assets` is used as the destination, and `/assets` is subsequently not present within that destination path. Run `npm install` or `npm run postinstall` or `npm run copy-calcite-components-assets`.
    ```json
    "postinstall": "npm run copy-calcite-components-assets",
    "copy-calcite-components-assets": "ncp ./node_modules/@esri/calcite-components/dist/calcite/assets ./public/calcite-components-assets"
    ```

### Relevant Info

I suspect these lines as the culprits since `/assets` is present in the usage of `getAssetPath()`

- https://github.com/Esri/calcite-components/blob/v1.0.0-beta.71/src/components/calcite-icon/utils.ts#L41
- https://github.com/Esri/calcite-components/blob/v1.0.0-beta.71/src/components/calcite-date-picker/utils.ts#L69

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.71`

- [ ] CDN
- [x] NPM package

Regression? No, I don't think so. It appears for both of these files this has always been present when I checked their full commit history.

**Comment by benelan** [comment]
@jwasilgeo a github repo may be better for a repro sample in this scenario. Do you think you can put one together?

**Comment by jwasilgeo** [comment]
Sure @benelan, I've fired up some stackblitzes.

Case 1 in my original repro steps which includes an `/assets` folder in my custom destination directory: https://stackblitz.com/edit/vite-fdnumn?file=package.json

Case 2 in my original repro steps which neglects to include `/assets` anywhere in my custom destination directory: https://stackblitz.com/edit/vite-re8cnw

Please note the `package.json` and `main.js` for each.

**Comment by jcfranco** [comment]
> local asset management guiding docs and examples should state that /assets must be present in the destination folder structure and used appropriately with setAssetPath().

We'll need to add this to the doc. Stencil moves each component's assets directory to the root of the build output. As a way to make it easier for users to copy all assets, we unify everything under `/assets`, which is why we need to hardcode at the moment (see https://github.com/Esri/calcite-components/pull/1457).

**Comment by jcfranco** [comment]
@benelan Can you take a stab at the doc for this? 🙇🏼‍♂️

**Comment by benelan** [comment]
I added a couple sentences to the [readme](https://github.com/Esri/calcite-components#2-assets) and the get started page, which will be updated next week.

>  The directory for the local assets must be named `assets`, which eases the copying process. For example, `/public/calcite/assets` will work, however `/public/calcite-assets` will not.

Closing this issue as self verified.

**Comment by jwasilgeo** [comment]
Thanks for taking care of this!

**Comment by rbrundritt** [comment]
Please update this doc https://developers.arcgis.com/javascript/latest/working-with-assets/ with the same information for clarity. I spent two days trying to figure out why the document methods for overriding these paths where only worked with half of the asset files. This closed issue was the only thing I came across that mentioned that the paths were hardcoded in some parts of ArcGIS. I came so close to writing a script to scan and overwrite all the paths in the JS files to resolve this issue. 

In my case the assets folder is virtual as I'm self-hosting the SDK within an app as an embedded resource and have a local proxy service setup to intercept the requests and grab the files locally. The one caveat this hardcoded "assets" path has for my scenario is that I've done this in a cross-platform Avalonia app and one of those platforms is web assembly. So, I have to make sure that my client knows not to create an Assets folder on their server, otherwise my proxy will intercept and try to fulfill that request locally.

**Comment by geospatialem** [comment]
> Please update this doc https://developers.arcgis.com/javascript/latest/working-with-assets/ with the same information for clarity. I spent two days trying to figure out why the document methods for overriding these paths where only worked with half of the asset files. This closed issue was the only thing I came across that mentioned that the paths were hardcoded in some parts of ArcGIS. I came so close to writing a script to scan and overwrite all the paths in the JS files to resolve this issue.
> 
> In my case the assets folder is virtual as I'm self-hosting the SDK within an app as an embedded resource and have a local proxy service setup to intercept the requests and grab the files locally. The one caveat this hardcoded "assets" path has for my scenario is that I've done this in a cross-platform Avalonia app and one of those platforms is web assembly. So, I have to make sure that my client knows not to create an Assets folder on their server, otherwise my proxy will intercept and try to fulfill that request locally.

@rbrundritt Thanks for letting us know! The documentation has been updated on the [working with assets page](https://developers.arcgis.com/javascript/latest/working-with-assets/) with JS' `5.0` release this week.
