### ISSUE TITLE
calcite-value-list doesn't emit the calciteListOrderChange event when using a keyboard

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#3685]
### Actual Behavior

When sorting a `calcite-value-list` with a keyboard, no `calciteListOrderChange` event is emitted.

### Expected Behavior

When sorting a `calcite-value-list` with a keyboard, the `calciteListOrderChange` event should be emitted since the list is being re-ordered.

### Reproduction Steps and Sample

_Sample_: [codepen](https://codepen.io/jmanke/pen/YzrGeqZ?editors=1111)

1. Create a `calcite-value-list` with `drag-enabled` attribute and at least two `calcite-value-list-item`s
2. Listen for the `calciteListOrderChange` event on the `calcite-value-list`
3. Use a keyboard to sort the list
4. Observe no `calciteListOrderChange` event is emitted

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.71`

- [x] CDN
- [ ] NPM package

Regression? No

**Comment by jmanke** [comment]
Noticed on @next that the event detail is different when using a keyboard. When using a keyboard the event detail is the element itself. When using a mouse the event detail is the value assigned to the `calcite-value-list-item`.

**Comment by jcfranco** [comment]
My bad. I'll submit a fix in a few.

**Comment by benelan** [comment]
verified on `beta.74`
