### ISSUE TITLE
CSS selector syntax in `id` attribute breaks `<calcite-tooltip>`

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#3687]
### Actual Behavior
If the tooltip's `reference-element` is an element `id` string that includes certain characters (e.g. periods, commas, etc...), the reference element is not found and a warning appears in the console.

### Expected Behavior
All valid `id` strings are supported and the reference element is found because the `reference-element` attribute is documented to support `id` strings, not a CSS selector string.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/nwhittaker/pen/bGowLdM?editors=1000

1. Hover linked text and notice tooltip does not appear.

### Relevant Info
Consider passing the `id` string through `document.getElementById()` instead of `document.querySelector()`.

_Reproducible version_: `@esri/calcite-components@1.0.0-<next.322>`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by benelan** [comment]
verified on `beta.74`
