### ISSUE TITLE
Bug: browser-specific switch focus border regressions

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#3694]
### Actual Behavior

~~There is a black border around a calcite-switch when clicking on the text of a parent calcite-label.~~
> Anvesh fixed the black border on Chrome, thanks!

Even with the black border fix, `calcite-switch`'s focus border still has regressions. It looks different in FF and Chrome, but both of them are not correct. 

-  In Chrome there is no focus border when clicking on the switch itself. When clicking on the label the border is rounded.
- In FF there is a dotted border inside of the expected border when clicking on the label. Clicking on the switch works as expected in FF.
- I don't have Safari but it should be tested as well.

The correct focus border is the one in `beta.69`, which works on both browsers.

### Expected Behavior
The focus border should look like it does in `beta.69` on all browsers.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/benesri/pen/ZEXLYqx?editors=1100

1. In all the browsers, use the switch (clicking both on the label and on the switch itself).
2. Repeat in `beta.69`, which is the expected behavior in both browsers

### Relevant Info
[Screenshots](#issuecomment-996211600)

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.71`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-beta.69`

**Comment by macandcheese** [comment]
Yeah it looks like the focus outline is no longer being applied - previously:
<img width="347" alt="Screen Shot 2021-12-13 at 12 48 56 PM" src="https://user-images.githubusercontent.com/4733155/145886600-b467cacb-0240-4623-951c-46b9513cfb70.png">

**Comment by benelan** [comment]
Yup the focus outline is present in `beta.69`. I didn't know if removing that was by design but I assumed that ugly black border was not.

**Comment by anveshmekala** [comment]
@benelan I don't see a black border while toggling the switch with label. Visual difference i see between `beta.69` and `.71` is the shrinked `focus-outline`.

**Comment by benelan** [comment]
you don't see this?
![image](https://user-images.githubusercontent.com/10986395/146091518-5886b073-1f01-47a2-84f6-f468c888325a.png)

**Comment by anveshmekala** [comment]
nope. i am using chrome. The black border is visible in edge though.

**Comment by benelan** [comment]
That screenshot is from Chrome, looks like it's not as obvious in FF

**Comment by benelan** [comment]
Strange, are you able to repro enough to work on this issue? If not someone else may have to do it

**Comment by anveshmekala** [comment]
Yup. I can use edge to fix the issue. Thanks @benelan

**Comment by benelan** [comment]
Nice, on `next` the black is blue in Chrome, but it still looks different than before (`beta.69`).

On `beta.69` both Chrome and FF:
![image](https://user-images.githubusercontent.com/10986395/146452199-fac24a6a-4365-41f9-a941-f7b15100f672.png)

on `next` in FF:
![image](https://user-images.githubusercontent.com/10986395/146451293-c542b6b0-b4f4-4d14-99f9-1a0ee6fffe56.png)
There is a dotted border inside of the normal focus border

on `next` in Chrome:
![image](https://user-images.githubusercontent.com/10986395/146451428-237b2b3e-2ee8-4e9d-a441-385a10fba7de.png)
The border is rounded and hugs the switch pretty tightly

@macandcheese were these design changes on purpose or are they regressions?

**Comment by macandcheese** [comment]
Not on purpose - the screenshot from beta.69 is the expected design across all browsers.

**Comment by benelan** [comment]
Thanks for the confirmation Adam. @anveshmekala I'm assigning back to you, with the goal of getting the focus border to look like it does in `beta.69` on all browsers.

**Comment by anveshmekala** [comment]
@benelan  sounds good. Please update the description and expected behavior as well. Thanks.

**Comment by benelan** [comment]
Updated, thanks!

**Comment by benelan** [comment]
verified on `beta.74`
