### ISSUE TITLE
Bug: black focus border around shell content

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#3697]
### Actual Behavior
When clicking on the jsapi map, a black focus border appears. It seems like the border is coming from #2992

### Expected Behavior
No black focus border

### Reproduction Steps and Sample

_Sample_: https://codepen.io/benesri/pen/poWRjYy?editors=1000

1. Click on the map

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.71`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-beta.69`

**Comment by asangma** [comment]
I don't think this is a Calcite thing.
It is default behavior in the api.
If you remove all the Calcite stuff from the codepen, you'll see the same behavior.

**Comment by benelan** [comment]
Oh, my mistake. I'll bring it up with the JSAPI team, closing this issue.

**Comment by asangma** [comment]
@driskull will be able to address it.

**Comment by benelan** [comment]
Might not be related, but there was a black focus border around `calcite-switch` on Chrome as well, which is fixed in `next`. https://github.com/Esri/calcite-components/issues/3694
