### ISSUE TITLE
Bug: action-bar and panel don't line up when nested side by side. 

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#3699]
### Actual Behavior

Action-bar and panel don't line up when nested side by side. 

### Expected Behavior

Feedback from @macandcheese:
On one hand it would be hard to ensure they are always the same height (since you can slot anything into header-actions of a panel), but it would be nice for the simple case of title + action bar to line up (you can see this same issue live in Map Viewer).

### Reproduction Steps and Sample

<img width="462" alt="action-bar-border" src="https://user-images.githubusercontent.com/19231036/145911779-f544f6a7-d43e-407f-8618-5f6bc120534f.png">

### Relevant Info

Reproducible version: @Esri/calcite-components@v1.0.0-beta.71

**Comment by AdelheidF** [comment]
The padding probably needs to be fixed first (https://github.com/Esri/calcite-components/issues/3494). 
https://codepen.io/afreitag/pen/ZEJjaRa

**Comment by asangma** [comment]
I think this would be a low-risk easy adjustment, i.e. reducing the top/bottom padding to 0.75rem.

**Comment by AdelheidF** [comment]
this looks good since beta.73
