### ISSUE TITLE
[IE11] Icon - Icons do not render

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#370]
<img width="415" alt="Screen Shot 2020-03-06 at 3 39 08 PM" src="https://user-images.githubusercontent.com/4733155/76131290-c6185900-5fc2-11ea-8e63-40fc6e6af724.png">
<img width="463" alt="Screen Shot 2020-03-06 at 3 55 34 PM" src="https://user-images.githubusercontent.com/4733155/76131349-f233da00-5fc2-11ea-92c7-75267f32df40.png">

**Comment by paulcpederson** [comment]
fixed by https://github.com/Esri/calcite-components/pull/387
