### ISSUE TITLE
calcite-popover-manager closes popovers outside its node or not matching the selector

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3701]
Closes popovers not inside popover-manager or popovers that do not match the selector

cc @driskull 

### Actual Behavior

Closes all popovers on page

### Expected Behavior

only closes popovers that are inside the popover-manager node or inside the popover-manager node and match the selector

### Reproduction Steps and Sample

https://codepen.io/afreitag/pen/JjrEGax?editors=1000

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-beta.71`

**Comment by driskull** [comment]
cc @jcfranco 

I think we're working towards deprecating the "manager" components for tooltip/popover. So we could introduce a "group" property on the tooltip/popover that handles when tooltips/popovers can be closed.

**Comment by AdelheidF** [comment]
> popovers aren't required to be inside a popover-manager so only closing ones inside might not make sense.

OK, I didn't know this and there is no doc.

> What if the popover had a property like prevent-auto-close or something that would prevent autoClose from closing it? Would that solve your issue?

I feel like the default should be `auto-close: false`, just like `calcite-popover-manager` has it. But I guess that would work.

> We may be deprecating the manager in the future.

`selector` is not working either.

**Comment by jcfranco** [comment]
@AdelheidF I believe the upcoming release [should fix this](https://codepen.io/jcfranco/pen/WNdWRwX). Thanks to https://github.com/Esri/calcite-components/pull/4423 and https://github.com/Esri/calcite-components/pull/4422,  tooltip/popover managers are no longer needed and tooltips/popovers can be set up on their own.
