### ISSUE TITLE
Slotted button enabled in disabled input

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#3711]
### Description

Allow a slotted button to be enabled with the input disabled.

### Acceptance Criteria 

As stated.

#### Which Component

`calcite-button`

#### Example Use Case

The user does not update the value of the input but rather uses the slotted button to populate the value of the input via a geoprocessing task.

The input can be set to `read-only` but the input is focusable, focused via tabbing, and the medium font weight looks odd (to me at least).

This is really an edge case and not sure it's even possible with the button wrapped in the input but I'm putting it out there.

**Comment by jcfranco** [comment]
Closing as won't fix. I think it'd be confusing and complex to allow parts of a disabled component be interactive.

**Comment by jcfranco** [comment]
Is it possible for you to share some screenshots or mockups of the desired UI/UX? Maybe there's an alternative way to set this up. cc @macandcheese

**Comment by COV-GIS** [comment]
Thanks for consideration @jcfranco. I ended up going a different direction with the workflow and agree with your assessment of complexity.
