### ISSUE TITLE
calcite-input-date-picker not changing after pasting new date string

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3722]
Instructions:
- copy string that's inside the input box
- change date to 10/15/2021 via calendar popover
- paste copied string into input box (it's 12/10/2021 again)
- open calender, it correctly highlights 12/10
- click on 12/15, nothing happens now, input box won't change to 12/15

### Actual Behavior

input box doesn't change to 12/15/2021

### Expected Behavior

input box should change to 12/15/2021

### Reproduction Steps and Sample

https://codepen.io/afreitag/pen/OJxWGpL

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.71`

- [ ] CDN
- [ ] NPM package

**Comment by driskull** [comment]
This seems to be fine in beta 74. @AdelheidF can you confirm?

**Comment by AdelheidF** [comment]
yes, looks good with beta.74
