### ISSUE TITLE
calcite-input-date-picker partially hidden by panel header

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3724]
Instructions:
- open calendar popover
- notice that the top of the calendar will not show on top of the panel header
- if I add more space above the input box it's fine
- if I remove some space above the input box it's fine too and the calendar shows below

<img src=https://user-images.githubusercontent.com/44481292/146238457-b8d1d42c-146a-48b2-be51-21ea6328b5a7.png width=300/>

Reported by Beyondsoft

### Actual Behavior

calendar partially hidden by panel header

### Expected Behavior

calendar should show on top of panel header

### Reproduction Steps and Sample

https://codepen.io/afreitag/pen/gOGmWeg?editors=1000

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.71`

- [ ] CDN
- [ ] NPM package

**Comment by macandcheese** [comment]
I've encountered this with the internally rendered `.header` div `z-index` declaration when other components are positioned over it like dropdown, etc. Unless there's a reason seems like we shouldn't be setting that internally as it causes users to have to use JS to unset that `z-index`.

**Comment by driskull** [comment]
I don't recall about the zindex. Was that added by me?

**Comment by jcfranco** [comment]
[Added way back in the early days](https://github.com/Esri/calcite-app-components/blame/master/src/components/calcite-panel/calcite-panel.scss#L64). 

The demo pages and screenshot tests should help catch any issues from dropping z-index, right?

**Comment by driskull** [comment]
Yeah it should. It might have been from when the header was over the panel?

**Comment by jcfranco** [comment]
FYI, I've submitted a PR for the z-indexing issues.

**Comment by driskull** [comment]
Just to add some clarity to this issue...

The header needs a higher z-index because a menu within the header should go over the content below it.

Any content within the scrolling panel should go under the header.

We will need to figure out floating menus within the scrolling area of the panel.

**Comment by depken** [comment]
We are having a similar issue with calcite-input-date-picker within calcite-modal.
https://codepen.io/jonasdepelsmaeker/pen/XWZLoJd?editors=100

**Comment by jcfranco** [comment]
> We are having a similar issue with calcite-input-date-picker within calcite-modal.

This was recently fixed via https://github.com/Esri/calcite-components/issues/3099. You'll need to [set `overlay-positioning=fixed` on the input-date-picker though](https://codepen.io/jcfranco/pen/vYRdLxW?editors=1000).

Regarding the original use case, the same fix applies. The only outstanding issue is proper placement of nested Floating UI elements, which I hope [this](https://github.com/Esri/calcite-components/issues/3815#issuecomment-1201698447) will address.

**Comment by jcfranco** [comment]
Floating UI fixes landed, shipped and our deps were bumped. This seems to work as expected locally. Marking as installed! 🎉

**Comment by geospatialem** [comment]
Verified both Codepen examples where `input-date-picker` has an `overlay-positioning="fixed"` (https://codepen.io/afreitag/pen/gOGmWeg and https://codepen.io/jonasdepelsmaeker/pen/XWZLoJd) in `next.557`. 

![verify calcite-input-date-picker in panel](https://user-images.githubusercontent.com/5023024/183948962-db2e7324-a299-4326-b1bb-c73c8d58c983.png)

![verify calcite-input-date-picker in modal](https://user-images.githubusercontent.com/5023024/183949072-b7cd6627-4f9b-4c2a-a7e3-412877926a69.png)

**Comment by AdelheidF** [comment]
looks good with beta.93
