### ISSUE TITLE
`overlay-position="fixed"` broken when used within a modal

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#3734]
### Actual Behavior

When a component that has `overlay-position="fixed"` is rendered within a `calcite-modal`, the position of the popover element is offset. The distance that the popover is offset by seems to be directly correlated to the x and y position of the modal itself.

#### `overlay-position="fixed"` used outside of modal works well
<img width="1450" alt="Screen Shot 2021-12-17 at 11 14 56 AM" src="https://user-images.githubusercontent.com/55154968/146589655-436dfc39-3fb1-481a-97df-7b76f881f508.png">

#### `overlay-position="fixed"` used inside of modal has incorrect positioning
<img width="1450" alt="Screen Shot 2021-12-17 at 11 14 38 AM" src="https://user-images.githubusercontent.com/55154968/146589744-11ec3e49-957d-4936-97b5-f1e2b38605e1.png">

### Expected Behavior

The positioning of `overlay-position="fixed"` should not be effected by the modal that the elements are rendered within. 

### Reproduction Steps and Sample

_Sample_: https://codepen.io/joeyHarig/pen/abLWKqQ?editors=1000

1. Open the codepen link and interact with the elements within the modal. Notice that the popover elements are not positioned correctly.
2. Close the modal and interact with the same element outside of the modal and notice that the popover elements are positioned correctly.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@ v1.0.0-beta.71`

- [x] CDN
- [x] NPM package

**Comment by benelan** [comment]
We have an [existing issue](https://github.com/Esri/calcite-components/issues/3815#event-5826423437) to rework how we handle popovers. However, for now you will need to use the default `absolute` value for `overlay-position`. If that does not work in your use case we can reopen this issue.
