### ISSUE TITLE
[IE11] Radio Group - Functionality and styling are broken

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#374]
Kind of a weird one - the "value" seems to be displayed alongside the slotted text if both are present. Additionally the dark theme vars don't seem to be working:

<img width="394" alt="Screen Shot 2020-03-06 at 3 41 36 PM" src="https://user-images.githubusercontent.com/4733155/76131657-35427d00-5fc4-11ea-8691-59383f7d0cc4.png">
. Additionally the dark theme vars don't seem to be working:

<img width="404" alt="Screen Shot 2020-03-06 at 3 41 22 PM" src="https://user-images.githubusercontent.com/4733155/76131656-34115000-5fc4-11ea-9e13-e7c991db7596.png">

**Comment by paulcpederson** [comment]
I got this pretty much figured out
