### ISSUE TITLE
Calcite Flow: showBackButton configurable

### ISSUE THREAD

**Issue by yannikmesserli** [Esri/calcite-components#3740]
### Description

- ~When setting `showBackButton` on a `calcite-panel`, the back button does not show up.~
- When putting a `calcite-panel` inside a `calcite-flow`, a back button shows up in the header.

### Acceptance Criteria 

A configuration to avoid the calcite-flow setting the back button on the calcite-panel

### Relevant Info 

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.71`

- [x] CDN
- [x] NPM package

#### Which Component

- `calcite-flow`
- `calcite-panel`

#### Example Use Case

- Two calcite-panels in a calcite-flow: https://codepen.io/yannikm/pen/KKXqrQB?editors=100

**Comment by driskull** [comment]
@yannikmesserli 

In the first example, the attribute should be `show-back-button` without any value assigned. Boolean attributes should not be set like `show-back-button="true"`.

In the second example, the flow is what is setting the `showBackButton` property. https://github.com/Esri/calcite-components/blob/master/src/components/calcite-flow/calcite-flow.tsx#L111

You can't do the following as it will be interpreted as true. `show-back-button="false"`. ("false" is a truthy value).

**Comment by yannikmesserli** [comment]
>  Boolean attributes should not be set like show-back-button="true".

Oh, right. Sorry about that.

> In the second example, the flow is what is setting the showBackButton property

We would like to remove it. Especially because when using a tsx render, going back does not remove the nodes inside the calcite-flow, where other navigation actions add or remove some calcite-panel within the calcite-flow. How can we achieve that?

**Comment by driskull** [comment]
@yannikmesserli you can just not have the flow and only have the panel. That would be the way to not have the back button.

**Comment by yannikmesserli** [comment]
> you can just not have the flow 

Since Calcite-components is the official web UI, Scene Viewer is using the flow to animate panel as the user drill-in configuration, as it should be. It would be sad not to use it because the back buttons is forced to appear when a calcite panel is inside a calcite flow.

Moreover, a calcite panel may not have a header - it's well supported. However, when within the calcite flow, the panel suddenly gets a  header because of the back button, which seems also odd.

Let's turn this issue into a feature request then, to support Scene Viewer own UX. I'll modify the ticket to reflect this.

**Comment by driskull** [comment]
Hey @yannikmesserli,

If there are 2 or more panels inside of the flow, it will show the back button. That's how it works. This can be verified by removing one of the panels inside of your codepen.

So, if you don't want the back button you can either...

- Remove one of the panels inside the flow
- Remove the flow (parent) and just use a panel

**Comment by yannikmesserli** [comment]
@driskull in Scene Viewer, the panels inside the flows are set or remove depending on the user's navigation. If he drills in one of the panels, then there is one more calcite-panel added to the calcite-flow.

> That's how it works.

Hence why I changed this issue to be a feature request - to change how it works. I can't change the labels, though. Please, help me by changing the labels.

**Comment by driskull** [comment]
@yannikmesserli I'm a little confused about the UX you are proposing. You would like the user to be able to drill in but not be able to go back?

**Comment by yannikmesserli** [comment]
>  You would like the user to be able to drill in but not be able to go back?

The component provide a `back` method, which clearly allow users to build different UI using the same functionality, so I think there is room for adding the back button being an opt-out option.

**Comment by gmiele** [comment]
> I'm a little confused about the UX you are proposing. You would like the user to be able to drill in but not be able to go back?

In addition to what @yannikmesserli already started to point out above:
- Scene Viewer offers several ways for the user to get back in the flow
   - The 2 buttons are present in the footer (confirmation/done and cancel)
   - The icon button in the action bar/toolbar can be used to go back to the first view
- This is a well-established UX in Scene Viewer and we should not break it. Forcing the back button to be there would break this, though.

Screen recording showing drill down and up in Scene Viewer's `Layer` configuration tool:

https://user-images.githubusercontent.com/5888662/148397226-abaddf80-9820-4bb5-9689-a9b9c66971e4.mp4

@driskull, I hope this clarifies things and dissolves your concerns reg. our request to have an opt-out option for the back button. Looking forward to integrating `Calcite Flow` in Scene Viewer.

**Comment by driskull** [comment]
Thanks @gmiele, I'll defer to our design team and wait for them to chime in.

**Comment by gmiele** [comment]
Thanks, @driskull. Any updates on the topic?

**Comment by driskull** [comment]
Hi @gmiele. Not yet, the issue still needs to be triaged.

**Comment by gmiele** [comment]
thanks, @driskull.

> the issue still needs to be triaged.

As I'm not familiar with your process and timelines:
- What does this mean in terms of timeline?
- What does the triage process include for such issues? 
- When will the next triage happen?

/cc @jcfranco

**Comment by jcfranco** [comment]
> What does this mean in terms of timeline?
> What does the triage process include for such issues?

We triage every 2 weeks, focusing on bug fixes, and high-priority items (for 1.0.0 release and stakeholders). You'll need to sync up w/ @benelan on this. 

FWIW, we release every 2 weeks.

> When will the next triage happen?

Tomorrow.

**Comment by gmiele** [comment]
Thanks, @jcfranco.

@benelan - I'll set up a call for next week. The requested improvement, reg. the `back-button` being an opt-out option, is crucial for us, and depending on its availability we would need to go different paths on Scene Viewer.

**Comment by macandcheese** [comment]
@asangma can you (or @mitc7862) provide an example of a similar configuration pattern in MV? It seems like the "options" flow might be better suited to a popover vs. a third flow panel as its its non-linear.

Small implementation nitpick - those footer buttons should really each take up half the width of the footer as shown here: https://developers.arcgis.com/calcite-design-system/components/flow/#sample

**Comment by macandcheese** [comment]
@mitc7862 @asangma - in the Map Viewer, this would be equivalent to the "symbol style popover" UX? It would be great to align across Scene / Map viewer on that pattern.

**Comment by benelan** [comment]
Closing this issue - when we met with @gmiele and @yannikmesserli we suggested working with MV to align their UX with the intended drill in/out of `calcite-flow`.
