### ISSUE TITLE
[IE11] Slider - Functionality and styling are broken

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#375]
These don't work in IE11 ☹️  - can't drag handles with mouse or move with keyboard. Styling also doesn't seem to be working for spacing the ticks but, could just be a result of something else since the rest of the styling seems ok.

<img width="394" alt="Screen Shot 2020-03-06 at 3 42 07 PM" src="https://user-images.githubusercontent.com/4733155/76131711-6e7aed00-5fc4-11ea-9960-90c15c1c4419.png">

**Comment by paulcpederson** [comment]
Will be in next release
