### ISSUE TITLE
[Combobox] - Internally rendered input has incorrect id assigned

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#3754]
### Actual Behavior
`calcite-combobox` is assigning the `guid` *function* as a string, not the result of the function, to the internal input.

<img width="1528" alt="Screen Shot 2021-12-21 at 11 27 47 AM" src="https://user-images.githubusercontent.com/4733155/146986703-0a5db498-cb88-4f7a-927d-279cd9f578e7.png">

https://github.com/Esri/calcite-components/blob/c24ae4e242ab6da7a516b96ea29554ec8c411b33/src/components/calcite-combobox/calcite-combobox.tsx#L950

### Expected Behavior
A guid is correctly assigned and associated with label. Perhaps this could use a calcite-input or calcite-label?

### Reproduction Steps and Sample
Inspect shadow DOM of combobox

_Sample_:

1.

### Relevant Info

_Reproducible version_: `71`

https://developers.arcgis.com/calcite-design-system/components/combobox/

- [ ] CDN
- [ ] NPM package

**Comment by benelan** [comment]
verified in the documentation sample
