### ISSUE TITLE
[Input Message / Input] Remove usage of `getElementProp` to set `status`

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#3755]
### Description 
`calcite-input-message` and `calcite-input` should not use `getElementProp` to set `status`.

### Proposed Advantages 
This is not a great pattern for inheriting properties - as of now it only detects and sets on load. Users should manage `status`  on each component individually.

### Relevant Info 
The verbiage on `calcite-label` here: (https://github.com/Esri/calcite-components/tree/master/src/components/calcite-label#basic) should also be removed.

#### Which Component
`calcite-input-message`
`calcite-input`
`calcite-label`

cc @driskull

**Comment by macandcheese** [comment]
To clarify (I think), this property should be kept on `calcite-input-message` and `calcite-input`, but their use of `getElementProp` to get and set the prop from `calcite-label` should be stopped.

The verbiage on `calcite-label` here: (https://github.com/Esri/calcite-components/tree/master/src/components/calcite-label#basic) should also be removed.

**Comment by y0n4** [comment]
Is it also recommended to remove the verbiage or change the code demo by adding additional status prop in the components for [calcite-input ](https://github.com/Esri/calcite-components/tree/master/src/components/calcite-input#with-label) and [calcite-input-mesage](https://github.com/Esri/calcite-components/tree/master/src/components/calcite-input-message#basic)?

**Comment by y0n4** [comment]
Does `calcite-label` still need the `status` property other then the purpose of having it propagate to `calcite-input`/`calcite-input-message`?

**Comment by driskull** [comment]
No, we should deprecate it or remove it.

**Comment by benelan** [comment]
verified on beta.76
