### ISSUE TITLE
Emit calciteAlertClose after animation

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#3760]
### Description
Similar to `calcite-modal`, it'd be helpful to receive the close event from an alert after its animation has completed so that it's not preemptively removed from the DOM when integrating with a framework like React.

### Acceptance Criteria 
`calcite-alert` emits an event after its animation completes (or has some other mechanism to notify a parent when it's done animating).

### Relevant Info 
NA

#### Which Component
`calcite-alert`

#### Example Use Case
```javascript
import { useState } from 'react';
import { CalciteAlert } from '@esri/calcite-components-react';

function Alert() {
  [message, setMessage] = useState('This is a message');
  return message
    ? <CalciteAlert
        active
        label="label"
        // Ideally setMessage('') is called after the animation
        onCalciteAlertClose={() => setMessage('')}>
          <div slot="message">{message}</div>
      </CalciteAlert>
    : null;
}

**Comment by macandcheese** [comment]
This would be a good addition

**Comment by jcfranco** [comment]
Implementer hint: https://github.com/Esri/calcite-components/pull/2074/files can be used as an example on how to accomplish this.

**Comment by mpayson** [comment]
Thanks all for working on this! I verified the fix in my app, should I close the issue? cc @benelan

**Comment by benelan** [comment]
Thanks for verifying @mpayson!
