### ISSUE TITLE
Race condition setting `for` click handler for labelable components

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#3761]
### Actual Behavior
If the rendering of a `<calcite-label>` element (or its `for` attribute) occurs after the assoc. input component is rendered, clicking the label does not focus or otherwise affect a "click" event on the input.

### Expected Behavior
Clicking the label should always affect a "click" event on whatever input is referenced via the label's `for` attribute, because it's consistent with native browser behavior.

### Reproduction Steps and Sample

_Sample_: https://ember-twiddle.com/ba0427f707a2227959a2406f1acb5f16

1. Visit the twiddle.
2. Wait for the `<calcite-switch>` element to render.
2. Click the "Show/Hide labels" button.
3. Click the "Calcite label" label and notice the switch is not toggled.

### Relevant Info
In practice, this bug is more likely to occur when using a dynamic templating system (e.g. Ember) where it's harder to control when a given element or attribute might get pushed to the DOM.

_Reproducible version_: `@esri/calcite-components@1.0.0-next.338`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by Elijbet** [comment]
Did some additional testing and confirmed it also occurs outside of Ember.

https://user-images.githubusercontent.com/19231036/150437490-0d591a7f-6c37-42d5-ad43-cfe20316a5a6.mov

**Comment by benelan** [comment]
@Elijbet can you post a codepen for that repro sample please?

**Comment by Elijbet** [comment]
> @Elijbet can you post a codepen for that repro sample please?

https://codepen.io/elijbet/pen/XWeLvWW?editors=1010

**Comment by jcfranco** [comment]
Verified with repro case. Great job, @Elijbet!
