### ISSUE TITLE
Bug: the first hyphen entered into number input is removed

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#3766]
### Actual Behavior
When typing `-` in number input, you have to type it twice in order for the hyphen to appear

### Expected Behavior
Only have to type a hyphen once

### Reproduction Steps and Sample

_Sample_: https://codepen.io/benesri/pen/bGorQYW

1. Type `-` and it won't add the character. Type it again and it will
2. Switch to `beta.70` and it works fine

Also reproducible in the doc: https://developers.arcgis.com/calcite-design-system/components/input/#sample
### Relevant Info
The only `input` PRs in the `beta.71` release notes are #3582 and #3627 

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.72`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-beta.70`

---
#### Edits
This is [the commit](https://github.com/Esri/calcite-components/commit/6ef5d4f338cdc29a4096f7f92efa48ebca8107cc#diff-d4e9e38d573f92a6608141863d1a3ce63b4cc9c7bc0b97585e8a91c48ac9a705L197-L244) that causes the regression

**Comment by jcfranco** [comment]
Verified via repro case!
