### ISSUE TITLE
Bug: hyphen is removed when typing negative decimals in number input

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#3767]
### Actual Behavior
You can't type negative decimal numbers, eg `-0.5`. The hyphen is removed when typing the `0`. If you type `0.5` then go back and add the hyphen it works fine. 

### Expected Behavior
Typing negative decimal values does not remove the hyphen

### Reproduction Steps and Sample

_Sample_: https://codepen.io/benesri/pen/bGorQYW

1. Type `-0.5` and notice the hyphen is removed after entering the zero
   - You have to type the hyphen twice due to #3766)
2. Switch to `beta.56` and it works fine

Also reproducible in the doc: https://developers.arcgis.com/calcite-design-system/components/input/#sample
### Relevant Info
Looks related to #2325

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.72`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-beta.56`

**Comment by jcfranco** [comment]
Verified via repro case!
