### ISSUE TITLE
[IE11] Tabs - Functionality is broken

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#377]
Tab nav items do not seem to render in IE:
<img width="394" alt="Screen Shot 2020-03-06 at 3 42 36 PM" src="https://user-images.githubusercontent.com/4733155/76131896-21e3e180-5fc5-11ea-8e63-f021fff5b3ac.png">

**Comment by driskull** [comment]
dis for me? or @jcfranco ?

**Comment by macandcheese** [comment]
Ah thought you did this one... carry on 🚶 ...

**Comment by jcfranco** [comment]
lol I didn't do this one either, but I can take it. 😄

**Comment by macandcheese** [comment]
🤷‍♂🤷‍♂🤷‍♂🤷‍♂ ha, must have been @patrickarlt ?

**Comment by paulcpederson** [comment]
I have this pretty much done locally, FYI. Will pr today

**Comment by macandcheese** [comment]
Looks like this was fixed, closing.
