### ISSUE TITLE
[Tree Item] Add support for disabled tree-item

### ISSUE THREAD

**Issue by ptmdmusique** [Esri/calcite-components#3772]
### Question

Is there any way to disable a single `tree-item` on a list, e.g.: make it not focusable/clickable 

I tried with `pointer-events: none` and it works, but it seems like if the `tree-item` is in the first layer of the tree, it's still focusable
Also, notice if a disabled `tree-item` is clicked first, the tree automatically select the first item in the list

https://codepen.io/ptmdmusique/pen/poWrxvJ

I can put `pointer-events: none` to the whole tree, but that wouldn't be ideal in a lot of cases

**Comment by macandcheese** [comment]
Currently this isn't possible - a valid enhancement request though. Updating title.

**Comment by geospatialem** [comment]
Verified on `next.597`

![tree item disabled verification](https://user-images.githubusercontent.com/5023024/196204144-43f8cb9c-6cc9-4027-bdf5-4a6d7234bf52.png)
