### ISSUE TITLE
Remove deprecated props/attrs, events, etc. before 1.0.0

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3781]
### Description 

We've been deprecating props in favor of breaking changes whenever possible during the beta phase. Before 1.0.0 rolls out, these will need to be removed. This issue should help keep track of the items that need to be removed to tackle everything in a single sprint before release.

We should also work on a migration document that encompasses all changes.

cc @benelan 

### Proposed Advantages 

Cleaner and 'lighter' codebase.

### Relevant Info 

N/A

#### Which Component

**Note**: this section should list action items per component or issues with relevant changes.

🚧 Coming soon 🚧

* https://github.com/Esri/calcite-components/issues/5099
* https://github.com/Esri/calcite-components/issues/4676
* https://github.com/Esri/calcite-components/issues/2115
* https://github.com/Esri/calcite-components/issues/2313
* https://github.com/Esri/calcite-components/issues/2512
* https://github.com/Esri/calcite-components/issues/2925
* https://github.com/Esri/calcite-components/issues/3163
* https://github.com/Esri/calcite-components/search?q=%22%40deprecated%22&type=code (search results to `@deprecated` usage)
* [Drop legacy ES5 build output](https://github.com/Esri/calcite-components/pull/5412)
* https://github.com/Esri/calcite-components/wiki/Consistency-Audit
* https://github.com/Esri/calcite-components/issues/3821
* https://github.com/Esri/calcite-components/issues/3755
* https://github.com/Esri/calcite-components/pull/4422
* https://github.com/Esri/calcite-components/pull/4423
* input inheriting `scale` and `status` should be removed as we are not cascading scale (see https://github.com/Esri/calcite-components/issues/2868)
  *  https://github.com/Esri/calcite-components/blob/640cece3ce15f221d075f11321c152ec2cba07b9/src/components/input/input.tsx#L384-L385
  * https://github.com/Esri/calcite-components/blob/c0973b4013dd2d91b40e9ad8a7187dc13c58d617/src/components/input-text/input-text.tsx#L232-L233
  * https://github.com/Esri/calcite-components/blob/640cece3ce15f221d075f11321c152ec2cba07b9/src/components/input-number/input-number.tsx#L340-L341

**Comment by driskull** [comment]
Lets bring this out of the Freezer 🥶 and start creating a checklist or sub-issues for each component that needs to have deprecated props/methods/events removed.

**Comment by geospatialem** [comment]
With the exception of `flow` (reallocated for a future milestone), the remaining above items have been tackled. Marking as installed.

**Comment by geospatialem** [comment]
All epic issues have been verified. 🏁
