### ISSUE TITLE
ComboBox icon should be a caret

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3807]
### Actual Behavior
Combobox currently uses a chevron icon.

### Expected Behavior
Seems like it should use a caret no?

### Reproduction Steps and Sample

_Sample_: https://codepen.io/mtb-alan/pen/KKXQmrY

1. View icon.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by macandcheese** [comment]
I don't really see a reason to change this to be honest - Caret icon just appear slightly heavier.
