### ISSUE TITLE
Calcite Button doesn't take onSubmit as a function in React

### ISSUE THREAD

**Issue by marcysilverman** [Esri/calcite-components#381]
When using calcite button in react in regards to a form, onSubmit is the standard function that you pass in the form html element, however, at the moment the calcite component does not recognize onSubmit as a target value.

Discussed with @macandcheese about this.

**Comment by macandcheese** [comment]
Buttons currently look for an "onsubmit" in the DOM and then run that function when type=submit (default)... I'm not sure if we could even look for a React "onSubmit" event in the DOM 🤷‍♂.

The workaround for React for now as @marcysilverman found was to use type=button and run the form "onSubmit" function in "onClick" on the button instead. Certainly not ideal.

**Comment by svlesiv** [comment]
Hi, I have the same issue with the submit button in React.
Currently, we start moving towards using Calcite Components in Site Scan. The workaround described above is working well. However, without a button with type="submit", users are not able to submit a form when pressing enter/return key as an alternative way of submitting forms.

**Comment by macandcheese** [comment]
Still relevant

**Comment by paulcpederson** [comment]
Old issue, but wanted to answer @svlesiv  's question in case others run into this. 

To enable <kbd>enter</kbd> to submit in a form, you can add a hidden submit button. Save a ref to it, and then simply call `click()`. The button doesn't have to be visible for this to work. Here is a little snippet:

```jsx
<button type="submit" ref={submitButton} style={{ display: "none" }}></button>
<calcite-button type="button" onClick={() => submitButton.current.click()}>Save</calcite-button>
```

This assumes you're using hooks and `useRef`. You could do the same thing with class components, though.

**Comment by stdavis** [comment]
Is there any interest in using something like this to output React components? https://github.com/ionic-team/stencil-ds-output-targets

**Comment by paulcpederson** [comment]
@stdavis yes, I opened a pr about this the other day: https://github.com/Esri/calcite-components/pull/1829 

One or two things left to work through, but it is planned at some point in the future.
