### ISSUE TITLE
Research: nested popper is contained within the component instead of overflowing

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#3815]
**Related Issues** 
#3099
#3724
#3725 
#3667 

### Background 

We have an issue with components using nested popper.js. Instead of overflowing, these are contained within the component.

eg. if placed inside a modal, a combobox is contained within that modal by default.

### Desired Outcome 

In this example the calcite-combobox list container needs to overflow like it does with calcite-select.

Sample: 
calcite-select: https://codepen.io/benesri/pen/NWgLgJJ
 calcite-combobox: https://codepen.io/benesri/pen/eYRLWej

It was suggested that we look at other component libs and how they handle nested popovers. That would require looking into libs that have some sort of custom modal, dropdown, or similar component using popper.

Also need to look into accessibility issues around the solution.

Please let me know if I'm missing anything from the issue.

**Comment by driskull** [comment]
It seems like carbon does it the same way. An issue I found says that its just up to the container to overflow: visible.
https://github.com/carbon-design-system/carbon/issues/2573

Spectrum components have the same issue It appears.
https://webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/EYQn9T6wOnieZbv4xnPj/src/index.stories.js?p=stories

Paper has same issue:
https://www.webcomponents.org/element/@polymer/paper-dropdown-menu/demo/demo/index.html

Looks like vaadin appends an overlay to the body.
https://vaadin.com/docs/latest/ds/components/combo-box

It seems like the easiest thing to do is to add an option to modal to either scroll or overflow-visible for these things.

**Comment by jcfranco** [comment]
https://github.com/floating-ui/floating-ui/pull/1827 should help address some issues related to using the `fixed` positioning strategy. Tested locally on some of our reported issues and floating-UI placement seems to work as expected.

If additional testing looks good, I believe we can consider this fixed once ☝️, #4372 and #4355 land.

**Comment by jcfranco** [comment]
The floating UI PRs were installed and are included in the latest release. Local testing of referenced issues looks good! @benelan Per our convo, assigning to you for follow up once the doc is done.

**Comment by geospatialem** [comment]
Verified with the `overlay-positioning` attribute when the value is set to "fixed". 👍🏻
