### ISSUE TITLE
tooling: remove @esri/eslint-plugin-calcite-components dependency

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#3822]
## Summary 

One cannot install this dependency because of its outdated dependencies:
```
>npm install @esri/eslint-plugin-calcite-components@latest --save-dev
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @esri/solutions-components@0.0.10
npm ERR! Found: @typescript-eslint/eslint-plugin@5.8.1
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   dev @typescript-eslint/eslint-plugin@"^5.3.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/eslint-plugin@"^2.23.0" from @esri/eslint-plugin-calcite-components@0.1.1
npm ERR! node_modules/@esri/eslint-plugin-calcite-components
npm ERR!   dev @esri/eslint-plugin-calcite-components@"0.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See \AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     \AppData\Local\npm-cache\_logs\2021-12-30T20_26_26_691Z-debug.log
```

## Measure of Success 

Successful fresh install of calcite-components dependencies.

### Resources 

Alternate is to update upstream dependency https://github.com/jcfranco/stencil-eslint-core/pull/1 followed by an update to eslint-plugin-calcite-components

**Comment by jcfranco** [comment]
Our `@esri/eslint-plugin-calcite-components` dependency got updated to the latest version. 

@MikeTschudi could you share your repro steps for our verification process? Thanks and Happy New Year! 🍾 🎉

**Comment by MikeTschudi** [comment]
1. Check out commit a961f4a0d31a7254aec8b67cb6beca55599e4434 ("test(input): stabilize e2e tests (#3566)")
2. Delete node_modules and package-lock.json
3. `npm install`: gets above error
4. Check out commit e469c7952b50e41982727932e8c0a8deb060adeb ("build(deps): bump @esri/eslint-plugin-calcite-components (#3830)")
5. `npm install`: success!

**Comment by benelan** [comment]
verified on `master`
