### ISSUE TITLE
Enhancement: allow customizing motion for components utilizing base transition variables

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#3827]
### Description

Allowing users to customize the animation/transition duration for components using `$transition` variable from `calcite-base` repo
cc @jcfranco 

### Acceptance Criteria 

All component animations/transitions which are utilizing `$transition` use `--calcite-animation-timing` instead to determine duration.

### Relevant Info 
Refer to #3081 

#### Which Component
All components in calcite-components repo

#### Example Use Case

`calcite-alert `container has[ transition](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-panel/calcite-panel.scss#L31) on `max-height` and `width`  with duration referring `$transition` variable from `calcite-base`. Currently user's can't customize/disable the transition .

**Comment by benelan** [comment]
verified on `beta.74`
