### ISSUE TITLE
Refactor: replace popper.js with floating-ui

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#3835]
### Description 

Refactor: replace popper.js with floating-ui

### Proposed Advantages 

Future support

### Relevant Info 

https://github.com/floating-ui/floating-ui
https://floating-ui.com/
https://floating-ui.com/docs/getting-started

#### Which Component

All that use popper.js

**Comment by benelan** [comment]
This has been installed for two weeks and I've been using/testing/verifying floating-ui related components with no issues. I'm marking this as verified, awesome work Matt!! :trophy:
