### ISSUE TITLE
[Chip] Remove "status" colors

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#3838]
### Description
The chip being used to convey state with associated colors has always seemed a bit strange to me. I am proposing we remove these. This also aligns with the goals of https://github.com/Esri/calcite-components/issues/2506.

cc @asangma 
### Acceptance Criteria 
The chip component removes yellow, green, blue, red status colors. Blue should be `brand` to match button nomenclature and allow for simpler overriding.

### Relevant Info 
Related: 
Should support need for users to be able to override : https://github.com/Esri/calcite-components/issues/3374
Makes it easier to supports the styling of "active" use case here: https://github.com/Esri/calcite-components/issues/1933

#### Which Component
Calcite Chip

**Comment by geospatialem** [comment]
Verified on `next.695`.
