### ISSUE TITLE
Calcite switch: Spacebar does not trigger onchange event

### ISSUE THREAD

**Issue by rslibed** [Esri/calcite-components#385]
Tested keyboard accessibility in an app which uses `calcite-switch` and noticed that the spacebar does not trigger the `onchange` event.

**Comment by macandcheese** [comment]
It looks like there's a handler for SPACE  / ENTER to handle this... @vcolavin any idea?

**Comment by rslibed** [comment]
Sample app: https://codepen.io/rslibed/pen/JjdveWe

Steps to repro:
1. Open the console
2. Click the switch
3. Observe the message logged into the console
4. Tab into the switch
5. Press the spacebar
6. Observe that the message is not logged into the console

**Comment by macandcheese** [comment]
Fixed in https://github.com/Esri/calcite-components/pull/391
