### ISSUE TITLE
calcite-panel should have an onscroll event

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3861]
### Description

I have a calcite-panel that contains a calcite-button that opens a small popover with the button as the reference element. I want to close the popover if the user clicks outside of the popover. This works fine with a click handler on the document unless the user clicks on the scroll bars or scrolls the panel. In that case the click event doesn't fire. If the user e.g. scrolls the scrollbar all the way down the popover moves all the way up with the button. At some point the button is hidden and the popover hangs at the very top.

![image](https://user-images.githubusercontent.com/44481292/148140806-0dbe47d9-e964-4178-958a-bab8fede51dc.png)![image](https://user-images.githubusercontent.com/44481292/148141267-7079bb73-3ea9-4fe7-92f1-81adf509973d.png)

To prevent this I want to close the popover if the user scrolls the panel. But to do this I need an onscroll event.

https://codepen.io/afreitag/pen/eYGKYEq

**Comment by driskull** [comment]
@jcfranco @benelan can we discuss how we can do scroll events for scrollable elements within a component?

**Comment by benelan** [comment]
Sure, I added it as an agenda item for our next meeting.

**Comment by driskull** [comment]
Proposal:

```
@Event onCalciteContentScroll: CustomEvent<ScrollEvent>;
```

**Comment by driskull** [comment]
@AdelheidF we already have an event for this, can you confirm this works already? https://github.com/Esri/calcite-components/blob/master/src/components/calcite-panel/calcite-panel.tsx#L168

**Comment by driskull** [comment]
Tested on your codepen...

```
document.addEventListener("calcitePanelScroll", console.log)
```

Going to close this one!
