### ISSUE TITLE
Add Hub related svgs to `calcite-icons`

### ISSUE THREAD

**Issue by vivzhang** [Esri/calcite-components#3864]
### Description
There are a few SVGs we would like to use in Hub and could not find substitutes for in `calcite-icons`.

### Acceptance Criteria 
Add below SVGs to `calcite-icons` -

survey:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 20.2" xml:space="preserve"><path d="M5.8,10.9H0v-2h5.8V10.9z M5.8,3.5H0v2h5.8V3.5z M5.8,13.6v-2.1H4v2.1H5.8z M5.8,8.2V6.1H4 v2.1H5.8z M5.8,14.3H0v2h5.8V14.3z M12.7,6.5l-1.4,1.3l4.1,4.1l1.4-1.3l0,0L24,3.4l-1.3-1.4l-7.3,7.2L12.7,6.5z M5.8,2H20V0H4v2.8 h1.8V2z M20.3,18.1H5.8v-1.2H4v3.2h18.2V8.4h-1.8V18.1z"/></svg>`
![image](https://user-images.githubusercontent.com/16672774/148295782-1174331b-d1d6-4df7-b84d-4afd336b2ce8.png)

mountain-summit-nocap:
`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" xml:space="preserve"><path d="M11.6,11L8.5,7.2V4C9.1,3.9,9.7,4,10.1,4.4c0.7,0.4,1.5,0.4,2.2,0v-3c-1.5,1.6-3.3-1.7-4.7-0.2v3l0,0v3L4.4,11l-3.6,4.3 h14.5L11.6,11z M11.6,2.5v1.2c-0.9,0.5-1.9-1-3-0.7V1.8C9.7,1.5,10.6,3,11.6,2.5z M8,8.4l5,5.9l-10.1,0L8,8.4z"/></svg>`
![image](https://user-images.githubusercontent.com/16672774/148295753-d6e50596-33ee-4d70-a7ab-2a8774eda8bb.png)

initiative-template-outlines-thick:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17,19h3.51V20H17Zm0-2.55h3.51v-.92H17Zm7-2.62v7.79a2.21,2.21,0,0,1-2.2,2.21H15.68a2.21,2.21,0,0,1-2.21-2.21V13.87a2.21,2.21,0,0,1,2.21-2.21H21.8A2.21,2.21,0,0,1,24,13.87Zm-1.78,0a.42.42,0,0,0-.42-.43H15.68a.43.43,0,0,0-.43.43v7.79a.43.43,0,0,0,.43.43H21.8a.42.42,0,0,0,.42-.43ZM9.84,7.93l3.07,3.64-.09.12a2.67,2.67,0,0,0-.49,1.22l-.05.41L9.18,9.73,3.57,16.34H12.3v1.58H0l4.71-5.48L8.39,7.93V4.82a2.49,2.49,0,0,0-1.64.48,2.76,2.76,0,0,1-2.83,0l-.1,0V.56l.33.35c.81.87,1.72.38,2.69-.14s2-1.09,2.95-.1l.05,0ZM8.36,1.66a2.6,2.6,0,0,0-1.55.49A2.49,2.49,0,0,1,5,2.63V4.18c.44.17,1-.1,1.53-.41a3.31,3.31,0,0,1,1.79-.55Z"/></svg>`
![image](https://user-images.githubusercontent.com/16672774/148295680-4c75bd12-335e-44d9-a0be-a4390895ec93.png)

solutions:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48.76 48.26"><path d="M31.31,48.26,29.69,48,17.32,40.87,19,38l.54-.18A2.45,2.45,0,0,0,20.72,37a2.29,2.29,0,0,0,.35-1.75,3.79,3.79,0,0,0-1.67-2.37c-1.62-1.08-3.65-1-4.53.3A2.27,2.27,0,0,0,14.53,35l.11.56L13,38.37,0,30.87l5.76-10A5.2,5.2,0,0,1,3.14,20c-2.56-1.8-3-5.69-1.06-8.65a6.77,6.77,0,0,1,4.31-3,5.21,5.21,0,0,1,5.34,2.19L17.82,0,30.69,7.43,29,10.29l-.54.18a2.27,2.27,0,0,0-1.39,1.19c-.65,1.39.25,3.22,2,4.09A3.76,3.76,0,0,0,32,16a2.24,2.24,0,0,0,1.35-1.18,2.47,2.47,0,0,0,.15-1.48l-.12-.55L35,9.93l12.61,7.32,1.13.79-5.71,9.87a5.19,5.19,0,0,1,2.63.93c2.56,1.81,3,5.69,1.06,8.66a6.76,6.76,0,0,1-4.31,2.94,5.25,5.25,0,0,1-4-.85,5.56,5.56,0,0,1-1.31-1.34ZM21.82,40l8.09,4.66,6.31-10.92,2.86,1.65.18.54a2.42,2.42,0,0,0,.87,1.2,2.29,2.29,0,0,0,1.75.35,3.77,3.77,0,0,0,2.37-1.66c1.08-1.62,1-3.66-.3-4.54A2.34,2.34,0,0,0,42.14,31l-.56.11-2.86-1.64,6-10.42-8.2-4.74a5.44,5.44,0,0,1-.47,1.81A5.24,5.24,0,0,1,33,18.83a6.75,6.75,0,0,1-5.21-.39c-3.19-1.58-4.72-5.18-3.4-8a5.1,5.1,0,0,1,1.81-2.12L18.92,4.1l-6.32,11L9.74,13.4l-.18-.54a2.45,2.45,0,0,0-.87-1.21,2.29,2.29,0,0,0-1.75-.35A3.81,3.81,0,0,0,4.57,13c-1.08,1.63-1,3.66.3,4.54a2.26,2.26,0,0,0,1.81.34l.56-.11,2.86,1.65-6,10.39L11.48,34a5.2,5.2,0,0,1,.94-2.62c1.8-2.56,5.69-3,8.65-1.06A6.77,6.77,0,0,1,24,34.66a5.29,5.29,0,0,1-.86,4A5.56,5.56,0,0,1,21.82,40Z"/></svg>`
![image](https://user-images.githubusercontent.com/16672774/148295590-5a0003f7-33d2-4860-bca2-9f46783239d7.png)

#### Which Component
`calcite-icons`

#### Example Use Case
`<calcite-icon icon="initiative-template-outlines-thick" />`

**Comment by benelan** [comment]
Yes that is correct. I can make sure the icons bump before the next release.
