### ISSUE TITLE
Bug: Action size is wrong when loading

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3866]
### Actual Behavior
When `scale="l"`, the loading state of Action is wrong.

### Expected Behavior
Should be the same size.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/mtb-alan/pen/NWazzLg

1. view the difference between the two actions.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by benelan** [comment]
Looks like the actions are now 100% width since `beta.75`, is that by design or a regression @asangma / @macandcheese ?
https://codepen.io/benesri/pen/mdpeQLd

**Comment by benelan** [comment]
@macandcheese mentioned 100% width makes sense for expanded action bars. verified on `beta.80`
