### ISSUE TITLE
Refactor combobox max-items to align with dropdown's max-items.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#3868]
### Description 

Apply the resize observer logic done in this PR to the combobox so that they are similarly structured. 

https://github.com/Esri/calcite-components/pull/3378

### Proposed Advantages 

Consistency

### Relevant Info 

https://github.com/Esri/calcite-components/issues/3048

#### Which Component

Combobox

**Comment by benelan** [comment]
verified on next https://codepen.io/benesri/pen/JjOEOKZ
