### ISSUE TITLE
Missing declaration files in dist/types/components.d.ts

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#3869]
The following errors occur when compiling TS using component types. I versioned back thru to `beta-70` from `beta-73` and it's an issue with all those versions. `// @ts-ignore` can be used to suppress the errors as a temporary fix.

```shell
node_modules/@esri/calcite-components/dist/types/components.d.ts:19:61 - error TS2307: Cannot find module './components/calcite-combobox/interfaces' or its corresponding type declarations.

19 import { ComboboxChildElement, ComboboxSelectionMode } from "./components/calcite-combobox/interfaces";

node_modules/@esri/calcite-components/dist/types/components.d.ts:28:41 - error TS2307: Cannot find module './components/calcite-pagination/calcite-pagination' or its corresponding type declarations.

28 import { CalcitePaginationDetail } from "./components/calcite-pagination/calcite-pagination";

node_modules/@esri/calcite-components/dist/types/components.d.ts:29:29 - error TS2307: Cannot find module './components/calcite-pick-list/shared-list-logic' or its corresponding type declarations.

29 import { ListFocusId } from "./components/calcite-pick-list/shared-list-logic";

node_modules/@esri/calcite-components/dist/types/components.d.ts:37:53 - error TS2307: Cannot find module './components/calcite-tree/interfaces' or its corresponding type declarations.

37 import { TreeSelectDetail, TreeSelectionMode } from "./components/calcite-tree/interfaces";
```

**Comment by benelan** [comment]
You can disregard the bot, this bug report does not require a sample. We are aware of the issue and currently investigating. The issue is not reproducible on `next`, so you can use that for development purposes until this is resolved.

**Comment by benelan** [comment]
@COV-GIS this issue is fixed in the `beta.74` patch we just released tonight. Do you want to make sure it works on your end before I close this issue?

**Comment by COV-GIS** [comment]
The above errors are resolved @benelan. Thanks.

However `calcite-value-list.d.ts` errors saying there is no declaration file for `sortablejs`. Which is odd as it is a dependency of the package. Easy enough for me to add `@types/sortablejs`.

**Comment by jcfranco** [comment]
> However calcite-value-list.d.ts errors saying there is no declaration file for sortablejs. Which is odd as it is a dependency of the package. Easy enough for me to add @types/sortablejs.

Interesting. Are you explicitly importing `calcite-value-list.d.ts` or is this type error coming up when you run your build? Do you have a repro case we could look at?

**Comment by COV-GIS** [comment]
When building. Only using "@esri/calcite-components" for element types. https://github.com/CityOfVernonia/Widget.PhotoAttachments
