### ISSUE TITLE
UX Improvements: Selecting a range on the calcite-date-picker

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#3874]
### Description
Currently, the calcite-date-picker is a bit unintuitive when selecting a date range. It would be nice if the range UX was similar to other range date pickers. 

Examples:

- [daterangepicker](http://www.daterangepicker.com/)
- [jquery-date-range-picker](https://longbill.github.io/jquery-date-range-picker/)
- [hoteldatepicker](http://lopezb.com/hoteldatepicker/)

### Acceptance Criteria 

Change the UX to align with other date pickers (linked above). In particular, after a range is set, the next click should clear the current range and set the new start date. Currently, the next click will just modify the start or end date without clearing the range.

#### Which Component

`<calcite-date-picker range>`

#### Example Use Case

A new user who has never used the calcite-date-picker attempts to select a date range. Since the UX is different than most other date pickers, there is a learning curve to using the date picker. If the UX was similar to other date pickers, then this learning curve could be avoided and the user would have a better experience.

**Comment by geospatialem** [comment]
Closing in favor of https://github.com/Esri/calcite-components/issues/6714
