### ISSUE TITLE
calcite-value-list no longer displays selection outline on items

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3877]
### Actual Behavior

Selected items have no outline.

#### Before
![Screen Shot 2022-01-07 at 9 06 58 AM](https://user-images.githubusercontent.com/197440/148580420-a7469289-72d6-4594-bf44-9ce57687fe89.png)

#### After
![Screen Shot 2022-01-07 at 9 08 26 AM](https://user-images.githubusercontent.com/197440/148580423-9e35d91b-6ea4-40b2-ae72-6a20370dd9dd.png)

### Expected Behavior

Selected items should have a visual indicator.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/jcfranco/pen/bGojjPj?editors=1000

For single:

1. Click on an item
2. Click outside of the list
3. Notice there is no indicator on the selected item

For multiple:

1. Click on an item
2. Click on another item
3. Note there is no indicator on the two selected items
2. Click outside of the list
3. Notice there is no indicator on any selected item

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-73`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-72`

**Comment by benelan** [comment]
verified on next
