### ISSUE TITLE
Number input: Value changes by itself indefinitely

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#3878]
### Actual Behavior

In certain situations the `<calcite-input type='number'>` will auto increment/decrement by itself indefinitely.

![chrome-capture](https://user-images.githubusercontent.com/19629809/148585073-df518eb7-6b09-4feb-ab2b-b83c7b02a8fd.gif)

### Expected Behavior

The number input should not change its value in unexpected ways.

### Reproduction Steps and Sample

_Sample_: [codepen](https://codepen.io/jmanke/pen/mdBjOEY?editors=1010)

1. Press the 'Up Arrow' and 'Down Arrow' keys in quick succession (or at the same time). If that doesn't work, try alternating between the 'Up Arrow' and 'Down Arrow' keys very quickly.
2. Observe the number input starts incrementing or decrementing the value by itself

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.73`

- [x] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
Yikes, this is a gnarly one. Thanks for reporting this.

This regression got introduced in beta 69. Probably from https://github.com/Esri/calcite-components/pull/3340. 

@Elijbet Do you think you can take a look at this one for this sprint?

**Comment by Elijbet** [comment]
> Yikes, this is a gnarly one. Thanks for reporting this.
> 
> This regression got introduced in beta 69. Probably from #3340.
> 
> @Elijbet Do you think you can take a look at this one for this sprint?

Yeah, I'll look at it. Sorry, missed that somehow.

**Comment by benelan** [comment]
verified on beta.75
