### ISSUE TITLE
New component : calcite-link

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#388]
I'd like to break "inline" type of "Calcite-button" into its own component. It's different in style and intended use than all other appearance types and there are many cases where it'd make more sense to have a "Calcite-link" components than rely on folks setting appearance="inline" on a button, like alert / notice action links. 

I'd imagine both components could retain functionality of rendering as an anchor with a href attribute present and a button / span (Calcite-link) without.

Thoughts @Esri/calcite-components?

https://www.carbondesignsystem.com/components/button/code

https://www.carbondesignsystem.com/components/link/code/

**Comment by paulcpederson** [comment]
I'm good with that. Definitely should still render as an anchor or a button, I agree.

This could be a good opportunity to standardize how we display "external" links or links that open in a new tab if that is something we want to do.

**Comment by julio8a** [comment]
Awesome!
