### ISSUE TITLE
Refactor(dropdown): nodeType checking for elements used in the dropdown-trigger slot of calcite-dropdown

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#3880]
### Description

We shouldn't have to keep blacklisting elements in the keyDownHandler when a different button type of element is slotted. Need to refactor nodeType checking or create a document for which node types are allowed in dropdown trigger. That way we can maintain this list of exclusion nodes.

Related PR: #3857

**Comment by benelan** [comment]
Closing this issue in favor of bug #4066, which should take this refactor into account when implementing the fix. The fix will show up on the changelog unlike this refactor issue.
