### ISSUE TITLE
Audit components for compatibility with high-contrast mode

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3887]
### Background 

Stems from #3875. To improve a11y, we should audit all components to make sure they are usable under high-contrast mode.

### Desired Outcome 

All components are compliant with high-contrast mode. Updating the conventions doc with common patterns is a plus.

**Comment by jcfranco** [comment]
@mpriour has volunteered some cycles to work on this. Thanks! 🙇

**Comment by mpriour** [comment]
@jcfranco @benelan Here is the high contrast audit I did.
https://github.com/Esri/calcite-components/wiki/High-Contrast-Audit

I'm happy to make any edits for clarification or consistency.

**Comment by geospatialem** [comment]
@mpriour Are there other components we should consider for inclusion in the 1.0 release next month, within the scope of the [audit](https://github.com/Esri/calcite-components/wiki/High-Contrast-Audit) or others you've come across aside from the `time-picker` PR?

**Comment by mpriour** [comment]
@geospatialem I don't think so.

**Comment by geospatialem** [comment]
Awesome, going to mark this issue as `installed` then. Thanks again for all of your expertise and help across the components. 🎉

**Comment by benelan** [comment]
Awesome work with these @mpriour, we really appreciate the help! 🎉

**Comment by geospatialem** [comment]
Verified on the `master` branch on Windows with high contrast enabled across components using Chrome. 👍🏻
