### ISSUE TITLE
Combobox: chip overflows border when 1 row is visible.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#3890]
### Actual Behavior

Combobox: chip overflows border when 1 row is visible.

<img width="469" alt="Screen Shot 2022-01-10 at 1 52 33 PM" src="https://user-images.githubusercontent.com/1231455/148847417-899ea79f-a682-4160-abaf-05f7884b14ed.png">

### Expected Behavior

Chip should not overflow border

### Reproduction Steps and Sample

_Sample_:

1.https://codepen.io/pen?editors=1000
2. Look

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by driskull** [comment]
Plz add a screener test for this as well.

**Comment by TheBlueDog** [comment]
We are seeing this behavior in Field Maps as well.

![Screen Shot 2022-01-21 at 1 26 59 PM](https://user-images.githubusercontent.com/5419306/150581600-7037bb86-e055-4a59-8b28-9587e4fcb8aa.png)

**Comment by benelan** [comment]
Triaging this to the next sprint cc @jcfranco @macandcheese

**Comment by y0n4** [comment]
Hi, the codepen link takes me to a blank editor. Is it alright if you can update with another codepen link please? Thanks!

**Comment by jgibson02** [comment]
I can file this as a new item, but I thought it might be relevant here due to the adjustments to chip margin: should there be margin between the last chip and the combobox placeholder?

**Comment by y0n4** [comment]
The merged pr #4068 also includes the spacing fix from @jgibson02 suggestion

**Comment by benelan** [comment]
verified on next
