### ISSUE TITLE
Combobox: Icon moves when opening menu

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#3891]
### Actual Behavior

Combobox: Icon moves when opening menu

![bug-combobox gif](https://user-images.githubusercontent.com/1231455/148847865-9caa2f8b-e321-4d7c-a53b-62cb5c6b3aaf.gif)

### Expected Behavior

Icon should stay in place

### Reproduction Steps and Sample

_Sample_:

1. https://codepen.io/driskull/pen/ZEXqebw?editors=1000
2. Click to open the combobox
3. 👀 

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by driskull** [comment]
Also add a storybook screener test for this.

**Comment by benelan** [comment]
Triaging this to the next sprint since it may be related to #3890 cc @jcfranco @macandcheese

**Comment by moosetraveller** [comment]
It happens as well when the menu is closed:

![image](https://user-images.githubusercontent.com/3456293/151384705-07456641-1034-449c-b677-ebb6dd317b51.png)

`1.0.0-beta.75`

**Comment by jcfranco** [comment]
FWIW, this landed in beta.76. 

Verified via repro case.
