### ISSUE TITLE
Tabbing between pick-list item content can prevent slotted actions from being tabbed into

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3894]
### Actual Behavior

Tabbing between pick-list item content can prevent slotted actions from being tabbed into.

### Expected Behavior

Consistent tabbing through pick list item content.

cc @asangma 

### Reproduction Steps and Sample

_Sample_: https://codepen.io/jcfranco/pen/eYGPRRr

1. Click first item
2. Press Tab (focus shifts to action)
3. Press Shift + Tab (focus shifts back to item content)
4. Press Tab (focus skips action and moves to the next focusable element)

After 4, clicking on the item and tabbing always skips the action

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-73`

- [x] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-73`

**Comment by benelan** [comment]
verified on next
