### ISSUE TITLE
Disscussion: Global configuration

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#39]
Breakout from https://github.com/ArcGIS/calcite-components/pull/32#issuecomment-498954866, https://github.com/ArcGIS/calcite-components/pull/32#issuecomment-498940293.

Discuss. I'll flesh this out later. 😄

**Comment by macandcheese** [comment]
I think this has been tabled for now, closing, can reference prior PR for ideas if we tackle this down the road.
