### ISSUE TITLE
Misalignment of tooltips in calcite-blocks in FireFox

### ISSUE THREAD

**Issue by 4andy** [Esri/calcite-components#3900]
### Actual Behavior

Calcite-tooltips display misaligned in Firefox when located within a calcite-block.  I was unable to reproduce the issue in Chrome or Edge browsers.

![image](https://user-images.githubusercontent.com/41160084/148974335-5da172a8-a21d-48c9-8664-f6da1b5e2b0c.png)

### Expected Behavior

Tooltips aligned with reference element. 

### Reproduction Steps and Sample

[https://jsbin.com/fularerofi/edit?html,output](https://jsbin.com/fularerofi/edit?html,output)

### Relevant Info
tested Firefox 96.0, 97.0b1

_Reproducible version_: `@esri/calcite-components@1.0.0-73`

- [x] CDN
- [ ] NPM package

**Comment by driskull** [comment]
Setting the `calcite-tooltip-manager` to have `position:relative;` fixes it. We might want to do that by default?

**Comment by jcfranco** [comment]
Separate discussion, but is there a way we can test this across components? We'll need to audit for other components that may need `position: relative`?

**Comment by benelan** [comment]
verified on next
