### ISSUE TITLE
calcite-panel: Ability to scroll to top

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#3924]
### Description

I am using a calcite-panel that needs its scroll position reset to the top when a certain action happens. 

### Acceptance Criteria

Having the ability to set the scroll position of the calcite-panel. In my case, I only need to set the scroll position to (0, 0).

### Relevant Info

In the absence of the shadow-dom, I would use [element.scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) to set the scroll position.

### Which Component

calcite-panel

**Comment by driskull** [comment]
@benelan @jcfranco we should discuss this along with if we want to emit scroll events.

**Comment by driskull** [comment]
Proposal...

```
@Method() scrollContent(value?: number): () => Promise<void>;
```

**Comment by jmanke** [comment]
Tried this on next, works great for me, thank you!

**Comment by benelan** [comment]
verified by Jeff!
