### ISSUE TITLE
[Combobox] - Unable to use icon to close dropdown while open

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#3931]
### Actual Behavior

If the dropdown is open, interaction with the chevron is disabled

https://user-images.githubusercontent.com/4733155/149390361-e9a8269f-1c07-4422-a13c-4a460855b696.mov

.

### Expected Behavior

I would expect to be able to toggle the dropdown by using the icon affordance at all times. It uses `cursor:pointer` which indicates interactivity.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/combobox/#sample

### Reproduction Steps

1. Open the dropdown. 
2. Try to close the dropdown by clicking on the chevron icon.

### Reproduction Version

beta 74

### Relevant Info

Regression? Last working version: `@esri/calcite-components@1.0.0-VERSION`

### Source

- [ ] CDN
- [ ] NPM package

**Comment by avezina** [comment]
We have also observed this issue in the new [Utility Network Trace widget](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-UtilityNetworkTrace.html) which is using this component. It is difficult to "get out" of the Combobox right now. Thank you!
![image](https://user-images.githubusercontent.com/50338557/149427288-2eb744e9-47d3-4e5e-ba95-471a5712d0e0.png)

**Comment by y0n4** [comment]
I noticed that the chevron icon is not focusable/tabbable (this can be addressed by wrapping it in a calcite-button).

Right now when the dropdown is opened, the whole combobox gets focused. In the case when the chevron icon gets clicked and the dropdown opens/closes, which in element gets focused? The whole combobox or the chevron icon button or does it depend on which element gets clicked?

**Comment by macandcheese** [comment]
My vote would be to not make the element itself focusable at all - just keep the visual as an affordance (and change the cursor to the same as the input). Clicks anywhere on the input would focus and open / close and focus. That behavior is replicable with a keyboard Esc press.

Thoughts @asangma ?

**Comment by asangma** [comment]
Basically, the behavior should be the same as CalciteSelect.

**Comment by geospatialem** [comment]
Verified chevron icon 🔼 behavior when dropdown is open in next 👍🏻

**Comment by avezina** [comment]
Is the new behavior available to test here?: https://next.sites.afd.arcgis.com/calcite-design-system/components/combobox/
I'm trying to see it in Next also in our sample https://next.sites.afd.arcgis.com/javascript/latest/sample-code/widgets-untrace/

**Comment by macandcheese** [comment]
@avezina - There isn't a deployed preview of our documentation site for next releases - the `next.sites` in those paths refers to the documentation site preview build ... slightly confusing 😅.

You can use the `unpkg` assets to test `next` releases in Codepen: https://codepen.io/mac_and_cheese/pen/abEERje?editors=100
