### ISSUE TITLE
Use new global attribute watch utility for Time Picker's lang attribute

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#3939]
### Description

The time picking components are using the `attribute` option of the `@Prop` decorator that Stencil provides for customizing which attribute should be watched for changes in the case where it needs to differ from the internal property name, in this case the global `lang` attribute is being watched to update the internal `locale` property.  The new utility for watching global attributes introduced by #3596 should be able to replace this usage while accomplishing the desired functionality.

### Proposed Advantages

This will allow us to remove an unnecessary `@Prop` declaration for the global lang attribute.

### Which Component

`input-time-picker` and `time-picker`

**Comment by jcfranco** [comment]
Closing in favor of https://github.com/Esri/calcite-components/issues/4213.
