### ISSUE TITLE
Enhancement: Set `action` to brand color

### ISSUE THREAD

**Issue by bpatterson88** [Esri/calcite-components#3950]
### Description

Allow `action` component to be set in brand color (blue). This would allow for a primary action in an action bar, similar to how button lockups have a primary button.

### Acceptance Criteria

`action` component has a property that renders it with a brand color background, such as `color="brand|neutral"`.

### Relevant Info

n/a

### Which Component

`action`

### Example Use Case

Dashboards will be implementing a UI that has an action bar with an action to add visualizations to a dashboard. This action is far and away the most important action, and we want it to be highly visible. A built in way to render that action with a blue background would be relatively simple way to increase visibility.

![Screen Shot 2022-01-18 at 11 19 44 AM](https://user-images.githubusercontent.com/15875886/150005357-ecb1fd6a-35c2-4043-8d08-25a18006dbfb.png)

**Comment by macandcheese** [comment]
This seems reasonable to me, thoughts @asangma ?

**Comment by geospatialem** [comment]
Closing with alternative methods to achieve the goal.

**Comment by macandcheese** [comment]
@asangma we had closed this during Triage, as this can currently be set with css vars - do you think this would be useful? We'd need to make extra considerations from the Button use case as that does not have the "active" state Action does. cc @ashetland @SkyeSeitz
