### ISSUE TITLE
calcite-input type="number": Incorrect negative values in some locales

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#3956]
### Actual Behavior

When typing a negative number in certain locales (et, ar), the `calciteInputInput` event always has the value set as `-1`. Additionally, when focusing off of the input, the value is reset to `-1`.

### Expected Behavior

The value emitted should reflect the value typed into the `calcite-input` since this would be consistent with other locales such as `en`.

### Reproduction Sample

https://codepen.io/jmanke/pen/mdBgawv

### Reproduction Steps

1. Use Estonian "et" locale
2. Type a negative number such as '-123'
3. Click off of the input (cause input to lose focus)
4. Notice value resets to "-1". The input also only outputs a value of "-1" on emitted events.

### Reproduction Version

@esri/calcite-components@next

### Relevant Info

I didn't try every locale, but 'et' and 'ar' exhibit this behavior.

Last working version: `@esri/calcite-components@1.0.0-beta.72`

### Source

- [X] CDN
- [ ] NPM package

**Comment by benelan** [comment]
In `beta.72` when typing `-123` you can see in the console that the value is `NaN`.  Since then, I made changes to invalid number sanitation, which is a little funky in this case due to an existing bug. I'll look into why `-123` is `NaN` in those locales.

**Comment by benelan** [comment]
- `In beta.55`, `calciteInputChange` started emitting `-1` instead of `-123`. [`beta.54`](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#100-beta54-2021-04-22) correctly emits `-123`.
- `In beta.72`, `calciteInputInput` started emitting `NaN` instead of `-123`. [`beta.71`](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#100-beta71-2021-12-07) correctly emits `-123`.

**Comment by jmanke** [comment]
@benelan It looks like the specific issue I logged above is fixed; however, there are some other issues with negative numbers with the same locales. Please see this [codepen](https://codepen.io/jmanke/pen/gOXPQZd?editors=1011). I can make another issue if it's not related to this one.

**Comment by benelan** [comment]
This is a different problem, it looks like the number isn't being delocalized correctly before being set as the value.  `e.target.value` should be delocalized to `1.5`. Right now it is `1,5` which is causing issues when converting it to a number. Can you please create a new issue, and I'll take a look?

**Comment by jmanke** [comment]
Sounds good, thanks @benelan 🙂

**Comment by geospatialem** [comment]
Verified in next for `lang='et'` ✔️ , but seeing the value reset to `-1` for the `lang='ar'`. 
cc/ @benelan

**Comment by benelan** [comment]
Hi @zaramatheson and @Olga8614! I could use some help with a locale question again. Do either of you know why `-123` is `NaN` in Arabic? Here is a codepen: https://codepen.io/benesri/pen/RwxYKWv?editors=0012

**Comment by geospatialem** [comment]
Verified in next, looks great!🎉
