### ISSUE TITLE
input-date-picker/date-picker no longer looks up the base language file if the specific locale code is not supported

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3965]
### Actual Behavior

Setting `pt-BR` (no matching locale file) as the date-picker's `locale` no longer loads the `pt` locale.

### Expected Behavior

When an unsupported locale value with language and region is provided (e.g., `pt-BR`), the language file should be used as the locale before falling back to English.

### Reproduction Sample

https://codepen.io/jcfranco/pen/NWaZbbN?editors=1000

### Reproduction Steps

1. Click on the input and notice the date-picker shows in `pt` (since `pt-BR` is not found)
2. Change the version to beta.75 
3. Repeat step 1 and notice how the date-picker displays in English.

### Reproduction Version

@esri/calcite-components@1.0.0-beta.75

### Relevant Info

Regression? Last working version: `@esri/calcite-components@1.0.0-beta.74`

This was introduced by https://github.com/Esri/calcite-components/issues/3925

### Source

- [X] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
Triaged to this milestone. cc @benelan 

@y0n4 Can you look at this one?

**Comment by AdelheidF** [comment]
Works with beta.74, doesn't work with beta.75, works with next.

**Comment by benelan** [comment]
verified by Adelheid on next
