### ISSUE TITLE
All custom events are marked as cancelable

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3967]
### Description

The automatically-generated [`docs-json.json`](https://unpkg.com/@esri/calcite-components@1.0.0-beta.75/dist/extras/docs-json.json) shows all custom events as cancelable. This file is used to power the SDK and in its current state will be misleading since [Stencil makes all custom events cancelable by default](https://github.com/ionic-team/stencil/issues/1023#issuecomment-420022412), but only a handful of our components support canceling events. We should update the `EventEmitter` decorator metadata to mark them as non-cancellable.

### Which Component

Any component with a public custom event.

### Resources

The following events **are** cancelable:

* `calciteInputNumberInput`
* `calciteInputTextInput`
* `calciteInputInput`
* `calciteListItemRemove` (for both pick/value list items)
* `calciteInputTimePickerChange`

**Comment by benelan** [comment]
verified on master
