### ISSUE TITLE
Enhancement: Introduce avatar stacking. 

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#3971]
### Description

Update: The description attached below has been covered in #1933, and this issue is being repurposed to introduce Avatar Stack. Something along this concept: https://developer.atlassian.com/platform/forge/ui-kit-components/avatar-stack/

Putting this here as a consideration for the design backlog @SkyeSeitz @ashetland @alisonailea.
@macandcheese suggested this as something that has been asked before, though not often. Eg, maybe Hub could use it in the Community feature.

Previously:

Follow up issue to #3430. To summarize the overall discussion and solution suggestion from @asangma: 

Avatars containing icons don’t align with those that do not. This occurs when using the calcite-icon component inside chip as well. 

The alignment issue isn't a Calcite issue but resulting from default browser behavior: the misalignment is coming from the default behavior of the containing element, e.g. a div whose default display is block.

A simple fix is to add display: flex to the parent div, but doing so seems outside of our components and something that should be handled at the app level.

The way to do something like that in the scope of Calcite would be to introduce something like a "ChipGroup”, for example. It would have appropriate styles applied for alignment, spacing between chips, spacing between groups, etc.

### Acceptance Criteria

Avatars/chips containing text/icon/image to have consistent alignment and spacing regardless of content. 

### Which Component

Avatar, chip, and any similar component that can have icon for content.

**Comment by macandcheese** [comment]
Specifically for chips, this could potentially be encompassed by https://github.com/Esri/calcite-components/issues/1933.

**Comment by geospatialem** [comment]
`chip-group` is being handled in #1933, a new issue has been created in favor of the above, https://github.com/Esri/calcite-components/issues/6804. Closing out the above for a refreshed Avatar stacking new component request.
