### ISSUE TITLE
Add `select` method to calcite-input

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#3976]
### Description

Similar to the `setFocus` method, we would like a `select` method on the calcite-input to wrap the [input select method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select).

As a workaround we can do something like `calciteInput.shadowRoot.querySelector('input').select()`, but it would be preferable for the api to expose this so we don't need to go into the shadow dom. 

### Acceptance Criteria

Be able to select text in a calcite-input without going through shadow dom, i.e. `calciteInput.select()`

### Which Component

calcite-input

### Example Use Case

A use case for select is when renaming an element. Clicking the "rename" option exposes a text input with the text selected. 
1. ![image](https://user-images.githubusercontent.com/14304581/150585383-e5119f36-3833-438f-a07e-a77a7d43c0f4.png)
2. ![image](https://user-images.githubusercontent.com/14304581/150585400-1b9eabd6-b9e7-4084-a093-76cebd3b0129.png)

**Comment by macandcheese** [comment]
This would also be nice to add to the `input-editable` functionality - when a user enters `editing-enabled`, have the text selected as shown above.

**Comment by nwhittaker** [comment]
The field maps web app has some autofocus logic that could use this `select` method.

**Comment by geospatialem** [comment]
Verified for `calcite-input` in `beta.86`.

![verify-input-selectText-method](https://user-images.githubusercontent.com/5023024/179029328-13db10af-a82c-45af-9c81-2376d82f9c32.gif)
