### ISSUE TITLE
Error when expanding action bar with expand tooltip

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#3978]
### Actual Behavior

For an expandable action bar with a tooltip in the `expand-tooltip` slot, expanding the action bar results in a console error: 

![image](https://user-images.githubusercontent.com/14304581/150593321-8da5ac49-679d-4b9e-b1c1-7ec921860020.png)

### Expected Behavior

Action bar expands and collapses with no error

### Reproduction Sample

https://codepen.io/ellupp/pen/xxXovPg?editors=1001

### Reproduction Steps

1. Hover over expand button and tooltip appears. Click button to expand.
2. See resulting error in console. 

### Reproduction Version

@esri/calcite-components@1.0.0-beta.74

### Relevant Info

Regression? Last working version: `@esri/calcite-components@1.0.0-VERSION`

### Source

- [X] CDN
- [ ] NPM package

**Comment by benelan** [comment]
verified on next
