### ISSUE TITLE
Progress component is fully invisible in high contrast mode

### ISSUE THREAD

**Issue by mpriour** [Esri/calcite-components#3986]
### Summary

The progress component is fully invisible in high contrast mode. Both the track and the bar use `background-color` values to make the elements show. The values used are changed to `none` by the forced colors rendering process that occurs in high contrast, making them not show at all.

This issue was discovered as part of #3887 - [High contrast audit](https://github.com/Esri/calcite-components/wiki/High-Contrast-Audit#progress) and identified as a severity level 4 out of 4 issue.

### Actual Behavior

Totally invisible (from the development demos page)
<img alt="progress, high contrast" height="240" src="https://user-images.githubusercontent.com/142636/149631329-0876ba46-a08a-4c58-b5eb-b28cceaf9c1a.png" />

### Expected Behavior

Something like this, but with high contrast system colors

<img alt="progress, normal" height="240" src="https://user-images.githubusercontent.com/142636/149631319-06384595-789c-45a0-872f-b48489d8bf45.png" />

### Reproduction Sample

https://esri.github.io/calcite-components/?path=/story/components-progress--indeterminate

### Reproduction Steps

1.  Set the theme on a Windows machine or vm instance to high contrast accessibility
2. View the above sample. Nothing is shown.

### Reproduction Version

@esri/calcite-components@1.0.0-75

### Relevant Info

Windows 7, 10, 11 with a high contrast theme enabled.
Any browser (Edge, Chrome, or Firefox)

### Source

- [X] CDN
- [X] NPM package

**Comment by benelan** [comment]
verified on beta.77
