### ISSUE TITLE
Tabs: optional tab-nav slot position

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/calcite-components#399]
Enhancement request/discussion.

When using `<calcite-tabs>` it would be an added bonus to be able to specify the position of the tab-nav slot to be either above or below the series of `<calcite-tab>`s.

The visual goal could be something in this direction:

![image](https://user-images.githubusercontent.com/4933392/77094737-ebea2880-69da-11ea-87e2-476f2654c1ec.png)

As a user-developer, is this possible to do now by placing the `<calcite-tab-nav>` below the series of `<calcite-tab>`s without specifying the slot?  Anything else I am missing and haven't seen in the docs?

Relevant lines? https://github.com/Esri/calcite-components/blob/958ad3acc4ba8fd37030b353663c204144043fc6/src/components/calcite-tabs/calcite-tabs.tsx#L57-L60

**Comment by jwasilgeo** [comment]
For what it's worth, I spoke to soon and answered my own question:

> As a user-developer, is this possible to do now by placing the `<calcite-tab-nav>` below the series of `<calcite-tab>`s without specifying the slot?

Yes; however, the active tab accent color is below the `<calcite-tab-title>` which is totally understandable.

I'll leave it up to the maintainers if you want to close this or leave it open for discussion. Thanks!

**Comment by macandcheese** [comment]
Hi @jwasilgeo - thanks for submitting. I agree, this would be a good configuration option to have - perhaps in an update combined with adding another `appearance` style as requested here - https://github.com/Esri/calcite-components/issues/186. 

I'll try and take a look like this after we work through some other open new component items; PRs are always welcome too :)

**Comment by macandcheese** [comment]
@paulcpederson want me to grab this? I'm doing a bunch of other tab updates today.

**Comment by paulcpederson** [comment]
Yeah go for it, dude
