### ISSUE TITLE
[Bug] - Slotted Dropdown no longer displays correctly on load

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4003]
### Actual Behavior

As of beta 75, slotted dropdowns in a panel no longer display. Even when `placement="bottom"` is used, the element displays off screen.

### Expected Behavior

The dropdown (slotted in panel in center row) behaves as it did in beta 74 and correctly displays.

74 repro (working):
https://jsbin.com/samedesaxo/1/edit?html,output

### Reproduction Sample
75 repro (not working):
https://jsbin.com/calalidome/1/edit?html,js,output

### Reproduction Steps

1. Navigate to each sample - click the action in panel slot.
2. Note that the prior version correctly displays, the 75 example displays off screen
3. While dropdown is active, change viewport width
4. See dropdown shift as position is calculated.

You can see it positioned "off screen" - if you move the view it will render correctly so maybe the mutation observer needs to fire at a different time to work at load.

### Reproduction Version

beta.75

### Relevant Info

Regression? Last working version: `beta.74`

This may occur elsewhere aside from panel slots, but I just ran into the example shared while updating an app to beta 75. Would be good to ensure it works with other slot / component examples.

### Source

- [X] CDN
- [ ] NPM package

**Comment by benelan** [comment]
triaging this to next sprint since it is preventing the afd doc from being updated cc @macandcheese @jcfranco

**Comment by benelan** [comment]
verified on next
