### ISSUE TITLE
popover's internal hiding of overflow trips up positioning when nested

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#4009]
### Actual Behavior

Nesting popovers will demonstrate issues with positioning. See the repro case for more details.

### Expected Behavior

Nested popovers to be placed properly.

### Reproduction Sample

https://codepen.io/jcfranco/pen/mdqdKzz?editors=1000

### Reproduction Steps

1. Click on the buttons from the already open parent popover
2. Notice the behavior (each configuration has a description)
3. Once all tested, click on the bottom button that will hack the popover's internal styling (fix suggested by @driskull 🎉)
4. Retest
5. Notice how all configurations work now

### Reproduction Version

@esri/calcite-components@1.0.0-beta.75

### Relevant Info

Regression? Last working version: `@esri/calcite-components@1.0.0-VERSION`

The `overflow: hidden` styles were introduced by the following installs, so we we need to make sure we don't introduce regressions:

https://github.com/Esri/calcite-components/commit/bebd22e41a49e1d29c2bfbc15e9d11f93e6cefc9
https://github.com/Esri/calcite-components/commit/6e4c81de6e560094ca7ff2a5cf68aed78ca2a32c

### Source

- [ ] CDN
- [X] NPM package

**Comment by driskull** [comment]
I can get this to work by using the word break mixin instead of overflow:hidden.

However, the action button used for the close button doesn't support rounded corners. So we would likely have to find some way to support that.

![image](https://user-images.githubusercontent.com/1231455/151459348-89178839-6149-4e58-8b8b-359827bff186.png)

**Comment by benelan** [comment]
I'll be working on #3152 which will create a global css var for border radius. So we will have precedent and the ability to use it here if design approves

**Comment by driskull** [comment]
@jcfranco @benelan @asangma do we even want to allow nested popovers? That seems like not the best UX.

**Comment by benelan** [comment]
Yeah I agree it's a bit weird. @jcfranco do you have a valid use case for it?

**Comment by AdelheidF** [comment]
There are plenty of use cases in the map viewer and they are not weird.
E.g. shell right panel opens a popover for some more complicated setting like symbol styler, filter, .... Then a small popover opens from the first popover for selecting a color, a field, some other single values.

**Comment by macandcheese** [comment]
> @jcfranco @benelan @asangma do we even want to allow nested popovers? That seems like not the best UX.

We certainly don’t want to incentivize it -“chasing” popover placement can be annoying as - but it should functionally work if a design team determines it is unavoidable.

**Comment by benelan** [comment]
verified on next
