### ISSUE TITLE
Disabled state may not be significant different enough

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#4015]
### Actual Behavior

Sometimes when all Actions are disabled, the disabled state may have too much contrast to be seen as disabled especially when there are not other not-disables Actions in the UI.

### Expected Behavior

More disabled-y disabled lack of contrast.

### Reproduction Sample

https://codepen.io/mtb-alan/pen/bGYdGeP

### Reproduction Steps

1. View the sample

### Reproduction Version

@esri/calcite-components@1.0.0-VERSION

### Relevant Info

Regression? Last working version: `@esri/calcite-components@1.0.0-VERSION`

### Source

- [ ] CDN
- [ ] NPM package

**Comment by jcfranco** [comment]
> More disabled-y disabled lack of contrast.

@asangma Do you have a suggestion for improving the disabled look?

**Comment by asangma** [comment]
I believe some styles got updated. This is no longer needed.
