### ISSUE TITLE
Popover - make pointer off by default

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#403]
What do we think about making the pointy pointer thing on Popover off by default?

Use case: most times we're using it MVB, the pointy bit is not needed. Also the thing it's pointing to is often in a scrolling panel, so if scrolling happens, Pointy-Pete is now lying.

Pointy-Pete of course still works nicely for Tooltip.

@macandcheese @paulcpederson @bstifle

**Comment by asangma** [comment]
![pointy pete](https://user-images.githubusercontent.com/12503298/77191391-249c0780-6a98-11ea-8ada-d80efea4c50a.gif)

**Comment by paulcpederson** [comment]
I'm good with that. IMO the indicator is superfluous and could be completely removed.

**Comment by macandcheese** [comment]
Makes sense, only comment would be the functionality should IMO be the same between the popover and tooltip, just make both off by default and opt-in with the same attribute.

**Comment by macandcheese** [comment]
Or, like Paul said, just remove altogether...

**Comment by asangma** [comment]
I will trust y'all. I do think it's nice for tooltips tho...especially with cats.
![image](https://user-images.githubusercontent.com/12503298/77191830-ca4f7680-6a98-11ea-84ca-d970d1b38e12.png)

**Comment by julio8a** [comment]
I’m good with hiding it by default.

**Comment by bstifle** [comment]
im fine with hiding it. i think we should keep it in tho

**Comment by macandcheese** [comment]
Works for me. Can we just make them the same though? Feels weird to have to opt in in one place and opt out in another for two similar components IMO.

**Comment by asangma** [comment]
@macandcheese 👍

**Comment by asangma** [comment]
Thanks y'all.

**Comment by bstifle** [comment]
yeah lets default them out @macandcheese fine with me

**Comment by driskull** [comment]
IMO it should be optional for Popovers and mandatory for tooltips. Its more important for tooltips to point to a reference for what they are offering a tooltip for.

**Comment by bstifle** [comment]
i also am fine with that.... i guess i dont mind either way. ill back away slowly...

**Comment by macandcheese** [comment]
OK, yeah I guess I don't really have a strong preference other than making whatever we do consistent 😅. Seems like both on by default is how we have it now?

**Comment by asangma** [comment]
I'm not sure that it's a problem to have Popover pointer off by default and Tooltip on by default. They're two different UXs and one of them benefits from having the pointer (Tooltip) and the other benefits from not having it.

**Comment by macandcheese** [comment]
Could we just them as they are now and turn off the pointer if desired in MVB? Seems easiest and wouldn't require any changes...

**Comment by asangma** [comment]
Making the change here will set a standard. And having three developers go through all their popovers and turn off the pointer...might be more work. And we'd have to manage that each time a new popover is created in MVB.

That being said, I was just looking at an interface that doesn't use pointers for the Tooltips, and it seems to work fine (contrary to what I was saying earlier).
![tooltips-dimension](https://user-images.githubusercontent.com/12503298/77206766-01338580-6ab5-11ea-945d-040ac4e87295.gif)

**Comment by asangma** [comment]
So...I think turning the pointer off by default in both tooltip and popover would be good.

**Comment by driskull** [comment]
So we want to just remove it for both? Breaking change? :)

**Comment by bstifle** [comment]
just default off, leave the points in if needed

**Comment by driskull** [comment]
I think you guys should test this before we do anything. It's really odd using the tooltip test page without pointers.  The tooltips are off centered from what they should be pointing at and it looks odd.

What do we gain by turning them off? It seems like a UX disadvantage for the user.

I pushed a branch `dris0000/no-arrows` for testing.

![image](https://user-images.githubusercontent.com/1231455/77210325-efa2ab80-6abd-11ea-98fc-5fc11ccc60c3.png)

**Comment by driskull** [comment]
Can you tell what the above tooltip is referencing? Its the bold text but you can't tell without an arrow.

**Comment by asangma** [comment]
The static example makes it weird.
In practice the user will have either set the pointer on the thing of interest or focused the element.
See the example above.

As a note, I'm not against keeping the pointer on the tooltip. I don't have a strong feeling about that.

I do however think that our Popover should have it off by default.

I also think it's fine to have it on by default for Tooltips and off by default for Popovers.

**Comment by pspraveenkr** [comment]
It looks like the popover position is already dynamic based on the parent element location (as much as the vertical space allows) when that element is clicked.

Given the above, this may be worth considering...
- Keep the pointer initially.
- When scrolling happens, let the popover follow the parent element until that element goes off screen? When the element goes off-screen, then remove the pointer from the popover?

Con: it may be distracting to the user if the popover moves while scrolling happens.

I'm suggesting this alternative since I feel it is good to have the pointer as much as possible as long as the parent element is in-view.

**Comment by asangma** [comment]
Thanks @pspraveenkr !
I agree that the moving popover can be distracting. And as for now, if the user scrolls, any pointer will no longer be accurate.

As such, we are generally showing a selected state or some sort of highlight on the thing that is selected especially if the popover is to the side. This makes the connection between the selected thing and its popover. Granted this is a UX that is implemented at the app level, but (as seen in the **Configure attributes** UX, the parent to popover relation is pretty clear.

![image](https://user-images.githubusercontent.com/12503298/77445166-f9702b80-6da9-11ea-9677-535e7b006618.png)


We're also already turning off the pointer in **Smart Mapping**. I don't know of any issues with users losing the connection between parent and popover.

![image](https://user-images.githubusercontent.com/12503298/77445295-23295280-6daa-11ea-90ea-cf92ed66f4ac.png)

**Comment by driskull** [comment]
I think we should leave the pointer on by default. 

The issues brought up are all issues specific to the map viewer usage. They are using a reference element that isn't what was clicked.

**Comment by macandcheese** [comment]
Yeah this seems like a simple solution, leave as-in and just turn it off if you want to 😆

**Comment by pspraveenkr** [comment]
> I think we should leave the pointer on by default.

👍 

> The issues brought up are all issues specific to the map viewer usage. 

Yes - depends on usage. If the parent element is not in a scrollable container, then feels like pointer is ok to have most of the times. Otherwise, user has a choice of removing it.

> They are using a reference element that isn't what was clicked.

What do you mean @driskull? I thought the reference element was the field node that was clicked.

**Comment by driskull** [comment]
> I thought the reference element was the field node that was clicked.

I don't think Adelheid set it up like that. For some of these she sets the reference element to the whole panel because she doesn't want it to scroll with the element.

**Comment by macandcheese** [comment]
This seems to be resolved per last discussion... Closing for now, re-open if need be.
