### ISSUE TITLE
[Design] Remove transition from focus style

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4036]
### Description

This is a currently a bullet point in https://github.com/Esri/calcite-components/issues/3345 - but it can be accomplished independently. 

Our transition for focus outline can cause components to appear slow, or laggy. It can also cause a situation where quickly tabbing through a set of components leads to a situation where the focus ring can't keep up.

### Acceptance Criteria

Remove the focus outline transition. I do not think this needs to be customizable.

### Relevant Info

cc @asangma @mitc7862 @TheBlueDog @rmstinson

### Which Component

All the components. Rating, Dropdown, are some that appear visibly sluggish.

### Example Use Case

As a user, sometimes the transition of focus ring can cause the application to appear slow, or if as a keyboard user I quickly tab, the currently focused element may not appear in focus.

**Comment by geospatialem** [comment]
Verified on next

https://user-images.githubusercontent.com/5023024/170577788-7e9aaea0-8334-49e6-baac-e0ff42d4a8bf.mov
