### ISSUE TITLE
Expose `scale` attribute of calcite-filter to enable using different size inputs

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#4038]
### Description

The underlying `calcite-input` and `calcite-icon` both have a scale prop to control the size/height of the control. Exposing these props up through the `calcite-filter` would allow aligning the size of the filter with other components in a layout.

### Acceptance Criteria

A `scale` prop exists on `calcite-filter` that takes `"s" | "m" | "l"`, with "m" as the default.

### Which Component

calcite-filter

**Comment by jcfranco** [comment]
@ethanbdev Thanks for submitting this. Next time, can you ping @benelan or myself to triage accordingly?

Adding @macandcheese for design review.

**Comment by ethanbdev** [comment]
> @ethanbdev Thanks for submitting this. Next time, can you ping @benelan or myself to triage accordingly?
> 
> Adding @macandcheese for design review.

Yes, sorry, apologies. I figured it was a small change but will wait next time.

**Comment by benelan** [comment]
verified on next https://codepen.io/benesri/pen/JjOENQL
