### ISSUE TITLE
calcite-input: emits invalid number

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#4063]
### Actual Behavior

This is new with beta.76, beta.75 didn't do this.

https://codepen.io/afreitag/pen/rNGreWY

Type in '5--' and watch what the component emits. It's 3 times the valid value 5. This is good.

Now start over and type in '-'. The component emits '-' which is not a valid value.
Instead it should not emit anything, just like if I had just cleared a number like 100 via select+backspace.

It also allows you to enter '--' and it emits '--' as a value.

### Expected Behavior

It should not emit anything for '-'.

### Reproduction Sample

https://codepen.io/afreitag/pen/rNGreWY

### Reproduction Steps

Type in '-'. The component emits '-' which is not a valid value.

### Reproduction Version

@esri/calcite-components@1.0.0-beta.76

### Relevant Info

Regression? Last working version: `@esri/calcite-components@1.0.0-beta.75`

### Source

- [ ] CDN
- [ ] NPM package

**Comment by AdelheidF** [comment]
Could this be please assigned to a milestone? It broke with beta.76 and causes issues for us. Thanks!

**Comment by benelan** [comment]
Yeah I'm going to revert #4020 before the next release. This regression effects `en` locale (which is most of our customers). I will reopen #3956 and find a different solution that does not create this regression.

**Comment by AdelheidF** [comment]
looks good with next
