### ISSUE TITLE
[Dropdown] When clicking focusable element outside dropdown to close, don't return focus to trigger

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4064]
### Description

There's a bit of a weird interaction (imo) when you click outside a dropdown to close it and that click occurs on a focusable element. 

The component returns focus to the trigger element:

https://user-images.githubusercontent.com/4733155/152656500-9f495ccd-d213-4d93-869c-bf7457e00b75.mov

This makes sense when the click occurs on a non-focusable element (or 'esc' key hit). But currently it doesn't allow focus to be set on the intended element. In the above, I'd expect focus to remain on the "share" action or the input when interacted with while the dropdown is open)

cc @asangma @driskull @jcfranco  - thoughts on this interaction?

### Acceptance Criteria

When clicking outside a dropdown to close, if the click occurs on a focusable element, do not return focus to the dropdown trigger, and instead allow focus on the interacted with element. Retain current functionality when the click occurs on a non-focusable element.

### Which Component

Dropdown

**Comment by jcfranco** [comment]
https://github.com/Esri/calcite-components/pull/4010 should fix this (specifically https://github.com/Esri/calcite-components/pull/4010/commits/915cc2757725fd36742a50ce886b4a77174a84ad). I had to change it since it was failing expectations from the test helper.

**Comment by jcfranco** [comment]
Fixed by #2655: https://codepen.io/jcfranco/pen/MWrYVwV?editors=1010.

**Comment by benelan** [comment]
Verified using Franco's sample!
