### ISSUE TITLE
Fab: When used as dropdown trigger, can't activate dropdown with space key

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#4066]
### Actual Behavior

Same issue as #3720 for `calcite-fab`

### Expected Behavior

The dropdown should stay open when pressing space (same resolution as #3720)

### Reproduction Sample

https://codepen.io/ellupp/pen/LYyKQwq

### Reproduction Steps

1. Focus the fab and press space, notice the dropdown does not stay open
2. Do the same with button/action, and notice that the dropdown stays open

### Reproduction Version

@esri/calcite-components@1.0.0-76

### Relevant Info

First reported by @ellenupp
___
> We shouldn't have to keep blacklisting elements in the keyDownHandler when a different button type of element is slotted. Need to refactor nodeType checking or create a document for which node types are allowed in dropdown trigger. That way we can maintain this list of exclusion nodes.
Related PR: https://github.com/Esri/calcite-components/pull/3857

-- Eliza in #3880

The refactor Eliza described above and this fix can be done together.

**Comment by driskull** [comment]
@benelan I think this should be handled via https://github.com/Esri/calcite-components/issues/3880

We can't keep adding components to the code inside dropdown. This "blocklist" isn't maintainable.

**Comment by geospatialem** [comment]
Verified in next ✔️ 

![screenshot with dropdown open using space bar](https://user-images.githubusercontent.com/5023024/161615855-9d50c263-66ad-4089-9439-d68149cf9563.png)
