### ISSUE TITLE
Component: time picking

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#407]
design for smartMapping Age renderer

<img src=https://user-images.githubusercontent.com/44481292/77340002-e5fd8b80-6ce9-11ea-8618-4f9e5ba5a228.png width=200/>

dojo component that we used in the past

<img src=https://user-images.githubusercontent.com/44481292/77340053-f9a8f200-6ce9-11ea-8f42-65eb196d7990.png width=300/>

Note: This must also work for 24 hour time format (00:00–23:59) and different languages (e.g. 05:37 chiều)

Native component (no support in Safari and IE): 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

**Comment by macandcheese** [comment]
@Esri/calcite-components are there other use cases for this? 

Curious if this would best be served as a dropdown, part of a date, some combination of a time input and dropdown (I think input + dropdown has come up before in dicussions), want to get a discussion about best way to handle this.

**Comment by paulcpederson** [comment]
This is actually already designed by @julio8a https://github.com/Esri/calcite-components/issues/58#issuecomment-514809436 basically to the right of date optional time.

**Comment by paulcpederson** [comment]
In my mind these are two separate inputs you can tab to independently. Possibly time picker has a dropdown as well, though not sure what that would look like.

**Comment by bstifle** [comment]
design for time picker

![image](https://user-images.githubusercontent.com/14083530/80749219-fa982500-8ada-11ea-9e77-e3a3397a7dab.png)

**Comment by paulcpederson** [comment]
1. Many countries don't use AM/PM but rather state everything in 24 hour time, assuming we would only show selector for locales that use it?
2. When paired with calendar, if I'm on 12PM and hit up, we wrap to 1 and I go to the next day? Or does time picker only impact time, or do we not allow wrapping? 
3. Interested to see a range selection that needs to allow for time on both start and end (or maybe we don't allow that?

**Comment by bstifle** [comment]
1. yeah that makes sense
2. i would vote yes on wrap, but no to affecting the date
3. 

![Date-time](https://user-images.githubusercontent.com/14083530/80757214-a3994c80-8ae8-11ea-9db5-8056a998f6ac.png)

**Comment by bstifle** [comment]
updated screen with localization and TZ

![image](https://user-images.githubusercontent.com/14083530/80760253-78fdc280-8aed-11ea-9420-1d8e5352ede5.png)

**Comment by AdelheidF** [comment]
We still need this. Currently we use a plain text input box.

**Comment by macandcheese** [comment]
I think @eriklharper has this cooking in the oven !

**Comment by eriklharper** [comment]
That is indeed correct!  I've been working on this but haven't had time to get back on it in a while because of other high priority issues.  Hope to resume this again very soon!

**Comment by joshtaylor0404** [comment]
We also have a need for this in Enterprise. Would this be built into the `calcite-date` component or would it be its own component?

**Comment by eriklharper** [comment]
It's currently being developed as its own standalone component `calcite-time`.

**Comment by eriklharper** [comment]
I'm wondering in light of #1404 if we want to have separate components for time as well.  I'm thinking if we follow those conventions in #1404 then we would end up with these two components:

`calcite-time-picker`
This component shows just this time picking UI:
![image](https://user-images.githubusercontent.com/821864/103376346-439ce080-4a91-11eb-96ec-01efd778fa0d.png)

`calcite-input-time-picker`
This component shows the input and when clicked displays the `calcite-time-picker` which is used internally.
![image](https://user-images.githubusercontent.com/821864/103376439-79da6000-4a91-11eb-8f7c-11e7d4254e76.png)

Thoughts? @bstifle @driskull

**Comment by bstifle** [comment]
I think thats a great idea

**Comment by driskull** [comment]
I agree. We should do that.

**Comment by eriklharper** [comment]
Did some research on the `step` attribute on `<input type="time">` and came to find out that it only supports `1-6, 10, 12, 15, 20, 30, 60` (the default), as well as these same numbers multiplied by 60: `60, 120, 180, 240, 300, 360, 600, 720, 900, 1200, 1800, 3600` which increment the minutes and disable the seconds, as well as 60 multiplied by the second set of numbers which increment just the hours and disable minutes and seconds, which makes sense.

Curious what people think of this behavior and should we replicate this for the Esri time picker?  Also, I think it begs the question how we document this, since it could throw some for a loop when they find out they can't just put any arbitrary number in there and expect it to behave like `<input type="number">`.

I also noticed that when using a step value such as 20, and then typing in a value like 13, it won't add 20 to 13 to make 33, it simply increments up to 20, and decrements down to 0.  Something else to keep in mind.

**Comment by bstifle** [comment]
thanks for researching this! are there any links to examples of these behaviors your have on hand?

**Comment by eriklharper** [comment]
> thanks for researching this! are there any links to examples of these behaviors you have on hand?

Good question.  I can whip up a codepen real quick and send you a link that will allow you to switch between these different step modes to see the result in the browser.

**Comment by eriklharper** [comment]
@bstifle check this out: https://codepen.io/eriklharper/pen/abBmOGz?editors=1111  I made it so that you can pick the values that work from a dropdown, but there's also a text number input that you can edit freely to put in any number you want as well.

**Comment by bstifle** [comment]
this is awesome, thanks erik. would be awesome to use this as documentation for time

**Comment by jcfranco** [comment]
FYI: moved to the next milestone.
