### ISSUE TITLE
calcite-popover-manager: undesirable auto-close behavior

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#4071]
### Actual Behavior

A calcite-popover-manager with the auto-close property will auto-close in an undesirable way. Starting your click (mouse down) inside the popover and ending (mouse up) outside the popover will cause the popover to close. 

### Expected Behavior

The popover should only close when both the mouse down and mouse up occur within the popover. This is because some frustrations can occur when using inputs (copy + paste). It's easy for a user to use the mouse to highlight some input text to copy (starts dragging inside the input and ending outside the popover) and inadvertently close the popover (see reproduction sample for an example). 

### Reproduction Sample

https://codepen.io/jmanke/pen/mdqrzgb?editors=1010

### Reproduction Steps

Steps for reproduction sample.

1. Press button to open popover
2. Hold down left mouse button inside of the hex input
3. While holding down the mouse, move it outside of the popover
4. Release mouse button. Notice the popover closes.

### Reproduction Version

@esri/calcite-components@latest

### Source

- [X] CDN
- [X] NPM package

**Comment by driskull** [comment]
fixed via https://github.com/Esri/calcite-components/pull/4423

**Comment by geospatialem** [comment]
Verified on next 👍🏻
