### ISSUE TITLE
calcite-input: Fails to update number programmatically after blur event

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#4076]
### Actual Behavior

When the input is type `number` and you trigger a blur event, the next time you update the value via JavaScript, it doesn't display the correct new value (it looks like it does update the internal state, just not the displayed value).

cc @MonikaKanduri4525 

### Expected Behavior

I would expect the displayed value to always match the value passed in via JavaScript.

### Reproduction Sample

https://codepen.io/noahmulfinger/pen/dyZvGdY

### Reproduction Steps

1. In the codepen, click `Increment value` a few times. Things should work as expected
2. Click on the input to focus and click away to trigger the blur event.
3. Click `Increment value` again. The input will not update.
4. Click `Increment value` once again. The input should now increment by two.

In the code, it looks like the variable `this.internalValueChange` is set to true during the blur event (because `origin` defaults to "internal" during [the `setValue` call](https://github.com/Esri/calcite-components/blob/master/src/components/input/input.tsx#L427) , so the next time the [`valueWatcher` updates](https://github.com/Esri/calcite-components/blob/master/src/components/input/input.tsx#L202-L203), it doesn't call `setValue`.

### Reproduction Version

@esri/calcite-components@1.0.0-beta.76

### Relevant Info

Regression? Last working version: `@esri/calcite-components@1.0.0-beta.74`. I believe it was introduced in this commit: https://github.com/Esri/calcite-components/commit/7d9e545dc841f476e1bbf8c0010e2ef98f122fb2

### Source

- [X] CDN
- [X] NPM package

**Comment by benelan** [comment]
verified on `next`
