### ISSUE TITLE
calcite-input: pass through native input attributes

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#4079]
### Description

The `accept` attribute restricts the type of files that can be selected when an input has the type `file`. It would be useful to have this attribute available on calcite-input.

### Acceptance Criteria

The `accept` property is passed down from the `calcite-input` into the internal `input`.

### Relevant Info

MDN docs for this attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept

### Which Component

calcite-input

### Example Use Case

Profile image upload:
```html
<calcite-label>
  Upload profile image (must be png or jpg)
  <calcite-input type="file" accept="image/png, image/jpeg"></calcite-input>
</calcite-label>


```

**Comment by benelan** [comment]
@macandcheese @jcfranco can we triage this to the next sprint?

**Comment by geospatialem** [comment]
Verified `accept` and `multiple` props. ✔️ 

@benelan Seeking your expertise 🧠 for verifying the `autocomplete` and `pattern` props are coming in as-expected with the [following Codepen](https://codepen.io/geospatialem/pen/zYaJyzN), where:

1. [`autocomplete`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete):
Unable to reproduce similar behavior to the native input where information is populated, such as email address.

2. [`pattern`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern):
Unable to discern how to use the new prop similar to the native input without using JavaScript to interpret.

**Comment by benelan** [comment]
My understanding is we have a post v1 epic to improve form validation, and for now users will still need JS like you mentioned. Here's an example:
https://codepen.io/benesri/pen/xxzaNKW?editors=1010

cc @driskull in case I'm wrong about that. I can another stab at it if so.

For autocomplete you have to have it turned on in your browser and have saved info. This works for me:
https://codepen.io/benesri/pen/LYrJozq?editors=1010

![image](https://user-images.githubusercontent.com/10986395/204962769-c002ea5b-cece-4ad5-b33c-08d695f53c9e.png)

**Comment by yelenakreyndel** [comment]
@macandcheese  why do we have this issue listed on confluence in the Next section here: https://confluencewikidev.esri.com/display/Calcite/New+Web+Components

**Comment by macandcheese** [comment]
@yelenakreyndel opened a new issue for tracking, will update Confluence: https://github.com/Esri/calcite-components/issues/6545
