### ISSUE TITLE
calcite-input-message: contained link does not work

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#4082]
### Actual Behavior

The doc for `calcite-input-message` says:
"Allows the passing of content, links, etc."

but when I try to add a `calcite-link` or `a` tag the link does not work. It does nothing when I hover or click on it.

### Expected Behavior

the link works like a link

### Reproduction Sample

https://codepen.io/afreitag/pen/rNYmOBL

### Reproduction Steps

see the codepen

### Reproduction Version

@esri/calcite-components@1.0.0-beta.76

### Relevant Info

Regression? Last working version: `@esri/calcite-components@1.0.0-VERSION`

### Source

- [ ] CDN
- [ ] NPM package

**Comment by paulcpederson** [comment]
the `pointer-events: none` that is causing this is actually on `host`, so until this gets fixed in calcite you can work around by setting `pointer-events: auto` on the element: https://codepen.io/paulcp/pen/WNXjQxe

**Comment by jcfranco** [comment]
Verified with the repro case + beta.77. 🎉

**Comment by AdelheidF** [comment]
looks good to me too, thanks
