### ISSUE TITLE
Bump calcite-ui-icons to beta6

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#409]
Are we able to bump calcite-ui-icons to `3.0.0-beta.6` or will explosions happen?

cc @driskull @jcfranco @macandcheese @paulcpederson

**Comment by paulcpederson** [comment]
Already bumped to 5 a while back, 6 i think just has some new paths so should be fine.

**Comment by asangma** [comment]
@paulcpederson Cool!

**Comment by macandcheese** [comment]
@asangma want to open a PR to bump this (I think they are on .7 now)?

**Comment by macandcheese** [comment]
Looks like this was updated in the last version bump, closing.
