### ISSUE TITLE
Docs: Incorrect prop description for calcite-tip-manager

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4106]
### Description

The generated doc for the `closed` prop of `calcite-tip-manager` reads "Alternate text for closing the `calcite-tip-manager`", which seems like a mistake.

We should update this to accurately describe the prop, which is probably more along the lines of "is the tip manager hidden" (... separately seems like that could be "active" to match other components, but ... for another time). 

### Which Component

Tip manager

### Which Page
https://github.com/Esri/calcite-components/blob/master/src/components/tip-manager/tip-manager.tsx#L32

### Resources 
Generated and displayed - https://developers.arcgis.com/calcite-design-system/components/tip-manager/#component-api-properties-closed

**Comment by benelan** [comment]
[Verified on storybook!](https://esri.github.io/calcite-components/?path=/docs/components-tips-tip-manager--basic#properties)
