### ISSUE TITLE
[calcite-filter] Initial property setup does not run filter method

### ISSUE THREAD

**Issue by ReidPritchard** [Esri/calcite-components#4111]
### Actual Behavior

Rendering a calcite filter with a pre-defined search value. The filteredItems property is an empty array even though there are matching results. The filter method is not called initially so the filteredItems property is misleading (an empty array even though some items match).

### Expected Behavior

I would expect on first prop set / (render in stencil) the filter method would be called and so accessing the filteredItems property would return the correct values.

### Reproduction Sample

https://codepen.io/reidpritchard/pen/WNXZwzZ?editors=1011

### Reproduction Steps

1. In console check out the filter's properties (value, items, and filteredItems)

### Reproduction Version

beta.76

### Relevant Info

Seems pretty agnostic, but I am using chrome.  

### Regression?

I don't believe there has been a regression. I have not tested with previous versions though.

**Comment by jcfranco** [comment]
@ReidPritchard Thanks for reporting this.

[Fixit note] Filtering needs to happen on `componentWillLoad`. Later updates to the component properly trigger filtering.

**Comment by benelan** [comment]
@ReidPritchard can you please verify that the fix is what you are looking for? You can get the filtered items by adding this line of code:

```js
filter.addEventListener("calciteFilterChange", ({target}) => console.log(target.filteredItems))
```

Unfortunately `filteredItems` is still `undefined` on the initial load, unless I'm missing something.

**Comment by benelan** [comment]
Looks like the component wasn't hydrated yet. Franco provided a working example:
https://codepen.io/jcfranco/pen/eYyZgmz?editors=1011

Verified on beta.80
