### ISSUE TITLE
Transparent accordion now has a border

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#4120]
### Actual Behavior

Transparent accordions (since beta 76) have a border around three sides.

### Expected Behavior

Transparent accordions should be transparent. 

### Reproduction Sample

https://codepen.io/paulcp/pen/zYPProK?editors=1000

### Reproduction Steps

1. apply the `appearance="transparent"` prop

### Reproduction Version

1.0.0-beta.76

### Regression?

 1.0.0-beta.75

**Comment by geospatialem** [comment]
Verified on next ✅ 
![screenshot with no borders when leveraging the transparency appearance prop](https://user-images.githubusercontent.com/5023024/161612875-1034668a-9d01-4393-9266-22d9c9ea5541.png)
