### ISSUE TITLE
Allow warning color property for Tab Icons

### ISSUE THREAD

**Issue by mitc7862** [Esri/calcite-components#4121]
### Description

We need to show a warning state for particular sections of analysis details. The easiest way would be to allow a color property to be passed to the tab's icon or to allow danger/warning/success properties to be set on the tab itself. 

### Acceptance Criteria

- Tabs can have an icon to indicate warning, danger, or success.
- Tab statuses can be set independently from other tabs in the group.

### Which Component

- Tabs
- Tab Title

### Example Use Case

Examples:
![image](https://user-images.githubusercontent.com/12564905/154307226-cc5abcf2-0995-4b76-b874-be2d35565485.png)

![image](https://user-images.githubusercontent.com/12564905/154307316-bedb15e7-f47b-4cfc-a801-bdebcc2ea539.png)

**Comment by macandcheese** [comment]
@mitc7862 good news - this is already possible with the `--calcite-ui-icon-color` css variable : 

https://jsbin.com/boxexaheye/1/edit?html,output

**Comment by macandcheese** [comment]
@mitc7862 good news - this is already possible with the `--calcite-ui-icon-color` css variable : 

https://jsbin.com/kuguqivuna/1/edit?html,output
