### ISSUE TITLE
calcite-slider labels appearing vertical inside calcite-popover

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#4126]
### Actual Behavior

Caused by upgrade from beta.76 to beta.77

![image](https://user-images.githubusercontent.com/44481292/154394412-1624edbc-e4cb-4c6e-85fb-cc728198aa42.png)

![image](https://user-images.githubusercontent.com/44481292/154397555-5e0b776a-0cfb-4379-ad48-9ce6e8e80f10.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/44481292/154394468-7707208d-4bbf-4cd6-9f72-6b7f9b4d949b.png)

### Reproduction Sample

https://codepen.io/afreitag/pen/OJOzLBM

### Reproduction Steps

Just open codepen.

### Reproduction Version

@esri/calcite-components@1.0.0-beta.77

### Regression?

@esri/calcite-components@1.0.0-beta.76

**Comment by AdelheidF** [comment]
I think this install for popover broke it: 
https://github.com/Esri/calcite-components/commit/31b7d8ff72a8673d6bb7a1b5bcfe52a7443c56f3#diff-2c88956271241eaf8204f4d12134f4fff58f10aeac5dc0dd8e18ad9e21f37607R69

Because I see this:
![image](https://user-images.githubusercontent.com/44481292/154399821-ad6d1ec4-c7d4-416a-8182-294e79a53154.png)
If I switch word-break off it's fine.

cc @driskull

**Comment by driskull** [comment]
I think we can solve this by either setting word break back to normal on any child of the popover content or set word break to normal within that slider element.

**Comment by driskull** [comment]
@AdelheidF as a temporary workaround, just set the following styles on the slider...

```css
overflow-wrap: normal;
word-break: normal;
```

**Comment by driskull** [comment]
@jcfranco @asangma should this be fixed on slider to set word-break to normal?

This could pop up if any other component or user styles applies word-break.

The alternative would be to try to target slotted elements in popover and set the word break but that might not be good.

**Comment by jcfranco** [comment]
> should this be fixed on slider to set word-break to normal?

I think so. @asangma Any objections to this?

**Comment by jcfranco** [comment]
Looking at the proposal from #4179, I like the idea of updating slider labels to not go beyond the slider track bounds. This would keep the labels within the slider container and we wouldn't need to worry about label positions modifying the slider's dimensions.

**Comment by jcfranco** [comment]
Follow-up on ☝️, the slider already behaves this way. I think the labels could be slightly tucked inward a bit, but adjusting the word-break for the slider, as suggested above, should work for now. 

> This could pop up if any other component or user styles applies word-break.

@asangma @driskull I think we should look at setting word-break for all components to avoid the scenario you brought up. Would  setting break-normal on our shared host styles and override on a case-per-case basis work?

**Comment by AdelheidF** [comment]
looks good, tested with next
