### ISSUE TITLE
calcite-combobox-items not aligning when added dynamically to calcite-combobox

### ISSUE THREAD

**Issue by RalucaNicola** [Esri/calcite-components#4127]
### Actual Behavior

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/8091967/154433075-c292bc2f-8e2c-41a4-8aa6-aea45b92639b.png)
This is just a silly app I made to repro the bug, in reality I have a service with a lot of diseases that I query as the user types in to offer them disease suggestions. As new suggestions come in, I remove the old calcite-combobox-items and add the new ones. As you can see in the screenshot above, the items don't align correctly anymore.

### Expected Behavior

I would expect that the items align

### Reproduction Sample

https://codepen.io/ralucanicola/pen/dyZVxLg?editors=1010

### Reproduction Steps

1. Open the sample
2. Start typing a word in the combobox (at least three letters)
3. Notice how the items that get added as suggestions don't align to the left.

### Reproduction Version

v1.0.0-beta.77

### Relevant Info

MacOS, Chrome

**Comment by benelan** [comment]
verified on next
![image](https://user-images.githubusercontent.com/10986395/160503991-a14fecf3-5dbc-4ea5-a4b0-5d40e8454f50.png)
