### ISSUE TITLE
calcite-combobox with single row of chips is missing margin or should be on new line

### ISSUE THREAD

**Issue by jgibson02** [Esri/calcite-components#4143]
### Actual Behavior

From the Storybook:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/5069711/154562624-d4001a88-6fbb-4ffd-ade7-447e61c0ff55.png">

The placeholder does wrap to a new line if there is not enough space remaining to be inline with chips, so I think it's just a matter of adding margin
<img width="423" alt="image" src="https://user-images.githubusercontent.com/5069711/154562752-8b9e1c14-8894-486a-a3b3-f67057c6e591.png">

### Expected Behavior

Margin is added between the last chip and the placeholder.
A case for this seems to not be captured in the Sketch UI kit since they all show the placeholder being wrapped to a newline.
<img width="679" alt="image" src="https://user-images.githubusercontent.com/5069711/154562367-9b231403-e374-42ce-b7b6-d310a7bf4299.png">

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/combobox/

### Reproduction Steps

1. Add some text for the placeholder
2. Select one or more items from the combobox

### Reproduction Version

beta.76

**Comment by macandcheese** [comment]
This should be addressed in https://github.com/Esri/calcite-components/pull/4068

**Comment by benelan** [comment]
verified on storybook https://esri.github.io/calcite-components/?path=/story/components-controls-combobox--simple
