### ISSUE TITLE
calcite-filter stop escape key propagation to prevent closing parent panels

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#4144]
### Description

Currently if a user presses "escape" within `calcite-filter` that event will propagate which can have unintended consequences like closing a dismissible parent panel. Here's an [example codepen](https://codepen.io/mpayson/pen/NWwXBey) -- type a value into the filter then hit escape, notice the whole panel will close

### Acceptance Criteria

In the above example, pressing the escape key just clears the filter, it does not close the panel

### Relevant Info

NA

### Which Component

`calcite-filter` and consuming components like `calcite-pick-list`, although our use case is just using the calcite filter.

### Example Use Case

See above

**Comment by geospatialem** [comment]
Verified on `next`

https://user-images.githubusercontent.com/5023024/184908850-c59c8461-e630-422c-b44d-5e05cf09a3a5.mov
