### ISSUE TITLE
Calcite Checkbox emit the name or value

### ISSUE THREAD

**Issue by ajturner** [Esri/calcite-components#415]
I'm building a stencil component array of checkboxes for a filter group. I'd like to have a single watch for any checkbox change and then emit the specific checkbox. However, the current Checkbox emit is empty of detail.

Would it be possible for [`checkedWatcher`](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-checkbox/calcite-checkbox.tsx#L79) to instead be `this.calciteCheckboxChange.emit(this.value ? this.value : this.name);` or similar?

@paulcpederson

**Comment by ajturner** [comment]
For more context, here is the example component

```javascript
import { Component, Host, h, Prop, Event, EventEmitter, Listen } from '@stencil/core';
import '@esri/calcite-components';

@Component({
  tag: 'hub-filter-category',
  styleUrl: 'hub-filter-category.css',
  shadow: true
})
export class HubFilterCategory {

  @Prop() name: string = "Tree Type";
  @Prop() categories: Array<string> = ['Ash', 'Birch', 'Maple'];
  @Event() filterChanged: EventEmitter;

  @Listen("calciteCheckboxChange")
  handleFilterChange(event) {
    console.debug("filterChanged", event)
    this.filterChanged.emit(event.detail)
  }

  render() {
    let output = []

    this.categories.map((category) => {

      output.push(<label>
        <calcite-checkbox
          name={category}
          value={category}
        >
        </calcite-checkbox>
        {category}
      </label>)
    })

    return (
      <Host>
        <h3>{this.name}</h3>
        {output}
      </Host>
    );
  }
}
```

**Comment by paulcpederson** [comment]
@ajturner these are DOM events, so I believe the "web-component-y" way to do this is to use the `target` of the event and glean the information from that. 

Can you try looking at `e.target` to see if that has what you need? If not we can for sure pass along a more robust payload in `detail`.

**Comment by paulcpederson** [comment]
Honestly it may make sense for use to treat the `detail` prop as a developer API in all of our component events and provide useful, focused info over events regardless.

**Comment by paulcpederson** [comment]
So I just played around with this and I think using the target is the "web-component-y" way to do this. In your example, this would mean changing your listener to something like:

```
@Listen("calciteCheckboxChange") handleFilterChange(event) {
  // can get this info from the instance of calciteCheckbox passed as target
  const { checked, value, name } = event.target; 
  this.filterChanged.emit({ checked, value, name });
}
```

Feel free to re-open and we can consider changing this (or improving docs?).
