### ISSUE TITLE
Button: 100 percent height in some environments

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#4151]
### Actual Behavior

In jsbin ***and a local html file*** `calcite-button` is 100% height. The height is normal in codepen, codesandbox, our dev site doc sandbox, storybook, etc.

### Expected Behavior

Button is the same height regardless of environment. Especially on a local HTML file, if it was just jsbin then it would probably be something weird they do.

### Reproduction Sample

https://jsbin.com/xadaluruju/edit?html,output

### Reproduction Steps

1. Look at the button size (its yuuge)
2. Copy/pasting the HTML from jsbin to a local HTML file also repros

### Reproduction Version

beta.77

**Comment by bsvensson** [comment]
The difference seems to be `<!DOCTYPE html>`. Codepen etc seem to add that. When you don't have it, you'll get the wrong height.

Firefox console (without DOCTYPE) says: `This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.`

cc: @benelan

**Comment by benelan** [comment]
Thanks for the follow up. After reading a bit about [Quirks Mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode) it sounds like this isn't a problem on our end, so I'm closing this issue.
