### ISSUE TITLE
[Shell / Shell-Panel] Allow a single detached shell-panel at the end of the shell in content-behind mode

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4156]
### Actual Behavior

Currently you cannot have a single detached `shell-panel` positioned at the right/end of the `shell` when `content-behind` is set (this works as expected with when not in `content-behind`).  A user needs to "fake" an empty `shell-panel` in the `primary` slot in order for one in the `contextual` slot to appear at the right/end.

### Expected Behavior

I would expect to be able to have a single `shell-panel` detached and positioned at the right/end. I might also expect the slots to be named `start-, end-` instead of `primary-, contextual-` since that may not be applicable to my design. cc @asangma 

### Reproduction Sample

https://codepen.io/mtb-alan/pen/NWwzrex?editors=1000

### Reproduction Steps

View codepen above, see "faked" slotted `shell-panel`. Remove that and observe the `contextual-panel` shift to the `primary-panel` position

### Reproduction Version

all

**Comment by asangma** [comment]
I think this calls for deprecating the primary and contextual panel slot names.
I am seeing enough examples of designs that have a single panel on the end side.

@benelan @jcfranco cool?

**Comment by geospatialem** [comment]
Verified on next
