### ISSUE TITLE
calcite-tree: Allow all keydown events to propagate

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#4158]
### Description

Currently `keydown` events are suppressed inside `tree-item`'s keydown handlers in order to avoid ancestor tree-items from receiving a bubbled keydown event that do not apply to them.  We need to instead allow keydown events to propagate outside the root calcite-tree component, so we'll need to refactor how the keydown behavior is applied.

### Proposed Advantages

The existing keyboard behavior will stay exactly the same, and improve on the accessibility by fixing the bugs outlined in #3123 while also allowing the native keydown events to bubble outside the root tree for developer usage, and to be consistent with other components and our goals to stop preventing native events from bubbling outside our components.

### Which Component

`calcite-tree`, `calcite-tree-item`

### Relevant Info

This refactor stems from #3123

**Comment by benelan** [comment]
verified on beta.80!
https://codepen.io/benesri/pen/XWVXBjg?editors=1010
