### ISSUE TITLE
value list should only leave the selected item as tabbable

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#4168]
### Actual Behavior

Navigating with the keyboard will leave navigated elements as tabbable.

### Expected Behavior

Only the selected item should be tabbable after the list loses focus.

### Reproduction Sample

https://codepen.io/jcfranco/pen/jOavwbX?editors=1000

### Reproduction Steps

1. tab or click the selected item
2. press ⬆️/⬇️ to go to the last item (don't select)
3. press Tab to move focus to the next element
4. press Shift + Tab to tab back in

### Reproduction Version

beta.78

### Relevant Info

N/A

### Regression?

No

**Comment by jcfranco** [comment]
@y0n4 Can you take a look at this one?

**Comment by benelan** [comment]
verified on beta.79
