### ISSUE TITLE
calcite-input-date-picker: minAsDate/maxAsDate not respected

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#4187]
### Actual Behavior

When setting the `minAsDate` and `maxAsDate`, the min/max is not respected and the user can change the date to something before/after the defined min and max.

### Expected Behavior

The user should not be able to select a date outside the bounds of the min/max.

### Reproduction Sample

https://codepen.io/eborgen/pen/xxPmvBq

### Reproduction Steps

1. Open the date picker
2. Observe the year can be changed to before 1950 / after 2050

### Reproduction Version

beta.77

### Regression?

unknown

**Comment by ethanbdev** [comment]
Possibly related to #4186

**Comment by benelan** [comment]
verified on next
