### ISSUE TITLE
calcite-combobox: choosing the selected option in a single select emits [undefined]

### ISSUE THREAD

**Issue by stevenalbers** [Esri/calcite-components#4196]
### Actual Behavior

Previously the single select mode on `calcite-combobox` would re-select the option if you chose it while it's already selected. From beta.70 onward though the same action now emits `[undefined]` instead.

### Expected Behavior

It could go one of two ways:

* Maintain the behavior from beta.69 and previous, where the chosen option is emitted, and the component's state remains the same
* Deselect the option, and emit an empty array `[]` instead of `[undefined]`

### Reproduction Sample

beta.69 - maintains select
https://codepen.io/stevenalbers/pen/LYOqVym 

beta.70 - deselects
https://codepen.io/stevenalbers/pen/RwjvPgE

### Reproduction Steps

1. Render a `calcite-combobox` with `selection-mode="single"`
2. Choose an option, then choose it again

The combobox deselects that option, and emits `[undefined]` to `calciteComboboxChange`

### Reproduction Version

beta.78

### Relevant Info

Not sure what the solution should be here. My use case involves a scenario where the combobox must always have an option selected, but there may be cases where a single select combobox does want to support having an empty value. If the latter is true, it may be worth considering adding something like a `required` prop that supports the previous behavior.

### Regression?

beta.69

**Comment by paulcpederson** [comment]
@benelan would be good to up-level this and prioritize it for a future sprint.

**Comment by driskull** [comment]
@paulcpederson @benelan this seems to be fine in beta 77+. Last reproduction was in beta 76.

> Deselect the option, and emit an empty array [] instead of [undefined]

This is already what happens now.

Do we want to do anything else?

Should we be able to unselect a value in single select mode?

**Comment by benelan** [comment]
Spoke with Paul and this is good to close, thanks Matt
