### ISSUE TITLE
[calcite-components-react] Support React 17+

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#4199]
### Description

With React 18 on the horizon, it'd be great if the React output target can support React 17+, and the Stencil docs suggest this is supported ([doc](https://stenciljs.com/docs/react)):
> Support: React v17+ • TypeScript 3.7+ • Stencil v2.9.0+

### Acceptance Criteria

React 17+ supported

### Which Component

React output target

**Comment by benelan** [comment]
My understanding is that we would need to change the output target's react peer dep version, which would cause issues for everyone using 16x

cc @jcfranco

**Comment by gavinr** [comment]
I worked around this by adding `--legacy-peer-deps` when installing, like this:

```
npm install --save @esri/calcite-components-react --legacy-peer-deps
```

but that workaround is not ideal. 

Would it be possible to set the output peer dep to `>=16`?

**Comment by benelan** [comment]
@gavinr I'm checking with stencil to see if that would break anything. We followed their example:

https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/example-project/component-library-react/package.json#L41-L44

**Comment by benelan** [comment]
I heard back from stencil and was able to set the react peerDep range to `>=16.7 <18`, which will be in the release early next week.

**Comment by benelan** [comment]
@gavinr or @mpayson can you please verify that you no longer get the peerDep install error in react 17x?

**Comment by gavinr** [comment]
## React v17 - fixed

Yes, for react v17 it does work. Here are my steps:

```
npx create-react-app my-app
cd my-app
```

Create react app is now defaulting to react v18, so need to downgrade to react v17:
```
npm install react-scripts@4 @testing-library/react@12 react@17 react-dom@17
```

Finally, install `calcite-components-react`
```
npm install --save @esri/calcite-components-react
```

The above works as expected! ✅

---

## React v18 - error
As I mentioned above, React 18 is now released (and standard with create-react-app) and when using it with that I get the same issue:

```
npx create-react-app my-app
cd my-app
npm install --save @esri/calcite-components-react
```

- Expected: no error
- Actual: error:
```
npm install --save @esri/calcite-components-react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=16.7 <18" from @esri/calcite-components-react@0.22.0
npm ERR! node_modules/@esri/calcite-components-react
npm ERR!   @esri/calcite-components-react@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See .....n\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!    ....\AppData\Local\npm-cache\_logs\2022-04-12T20_00_07_093Z-debug.log
```

---

Moving targets are so fun, right? 😜

**Comment by benelan** [comment]
Stencil said they haven't had a chance to make sure things work in react v18. I am going to do some testing on my end and then include 18 in the semver range if all goes well. I guess we can just use this same issue for that.

**Comment by benelan** [comment]
@mpayson @gavinr Can on of you please verify that React 18x works in the recent `calcite-components-react` release?

**Comment by gavinr** [comment]
I tested with the [above steps](https://github.com/Esri/calcite-components/issues/4199#issuecomment-1097160754). It looks good - no errors! Thanks! Please close this issue.
