### ISSUE TITLE
Update "isActive" prop to "active" 

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#420]
We have a few components using `isActive` prop whereas all others are using `active`.

- `calcite-loader`
- `calcite-modal`
- `calcite-tabs`

It's a breaking change, but we should have consistency between these prop / attribute names.

**Comment by jcfranco** [comment]
IMO, this doesn't have to be an immediate breaking change. `isActive` could be deprecated and add `active` with a higher precedence if both are present. The breaking change release could happen at a later time, possibly with other breaking changes.

**Comment by macandcheese** [comment]
Makes sense, just wanted to add an issue to track it. We could deprecate for short term and remove for 1.0 release 🎈

**Comment by macandcheese** [comment]
Closing this in favor of some upcoming breakout issues.
