### ISSUE TITLE
Audit components for `HTMLElement#click` behavior

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#4212]
### Background

Stems from https://github.com/Esri/calcite-components/issues/4211

Components similar to switch (e.g., checkbox) with single-click behavior should be updated to work with `HTMLElement.click`.

This issue will focus on identifying these components and which ones are not handling the expected `myElement.click()` behavior.

### Desired Outcome

A list of components that need to handle `click()`. We will create a follow-up issue/epic to tackle each.

- [x] checkbox
- [x] switch
- [x] radio-button

**Comment by benelan** [comment]
verified on beta.94
https://codepen.io/benesri/pen/MWGJPrV?editors=0010
