### ISSUE TITLE
Radio Button Group item does not stay checked after navigating away and back in

### ISSUE THREAD

**Issue by BennyBaruba** [Esri/calcite-components#4214]
### Actual Behavior

Using the CC Radio Button Group with two Radio Buttons.  When the user first accesses the page with the Radio Buttons, the "Off" Radio Button is correctly selected.  If the user navigates to a different view or clicks the browser back button and then back in to the view with the Radio Button component.  Neither the "Off" or "On"  Radio buttons are selected.  If I log out the Radio Button to the console.  The checked is set to true.  Even though `checked = true` is correct for the "Off" Radio Button and `checked = false` is correct for the "On" button.

<img width="673" alt="Screen Shot 2022-03-08 at 4 21 50 PM" src="https://user-images.githubusercontent.com/5122225/157328031-e43478be-cf6f-45b0-8544-cd909dd56f47.png">

Here is the code used for the Radio Button Group:
```
//Workflow with Radio Button Group
  private _renderNotificationSettings = (): JSX.Element => {
    const radioGroup = RadioButtonGroup({
      onChange: e => {
        const value = e.detail === "none" ? null : e.detail;
        this._setFormProperty("notifications", value === "on", "manager");
      },
      useLabels: true,
      items: [
        {
          checked: !this.formProperties.notifications.manager,
          value: "off",
          label: this._t9n.off
        },
        {
          checked: this.formProperties.notifications.manager,
          value: "on",
          label: this._t9n.on
        }
      ],
      layout: "vertical",
      name: "notifications-radio-group",
      scale: "m"
    });

    return (
      <div class={this.classes(flex.boxCFsFs, fontSizes.fontSizeMinus1)}>
        <div class={this.classes(CSS.fontGray, trailers.trailerHalf)}>
          {this._t9n.notification.description}
        </div>
        {radioGroup}
      </div>
    );
  };
```

The following is a screen recording of the experience.

https://user-images.githubusercontent.com/5122225/157324107-470fb967-5b2c-4a7d-b36e-3a5477aa60d0.mov

I was not able to reproduce the issue in the codepen environment.  I'm thinking the issue may only show itself when working with .tsx and a virtual DOM.  

I was however able to swap out the Radio Button Group for a Radio Group.  While keeping all the other code the same.  With the Radio Group, the issue does not exist.  

Here is the code used for the Radio Group:
```
//Workflow with Radio Group
private _renderNotificationSettings = (): JSX.Element => {
    const radioGroup = RadioGroup({
      onChange: e => {
        const value = e.detail === "none" ? null : e.detail;
        this._setFormProperty("notifications", value === "on", "manager");
      },
      //useLabels: true,
      items: [
        {
          checked: !this.formProperties.notifications.manager,
          value: "off",
          //label: this._t9n.off
        },
        {
          checked: this.formProperties.notifications.manager,
          value: "on",
          //label: this._t9n.on
        }
      ],
      layout: "vertical",
      name: "notifications-radio-group",
      scale: "m"
    });

    return (
      <div class={this.classes(flex.boxCFsFs, fontSizes.fontSizeMinus1)}>
        <div class={this.classes(CSS.fontGray, trailers.trailerHalf)}>
          {this._t9n.notification.description}
        </div>
        {radioGroup}
      </div>
    );
  };
```

The following is a screen recording of the experience.

https://user-images.githubusercontent.com/5122225/157324959-cb4c40c3-2e13-4d17-a4fa-33fcc18aa48d.mov

### Expected Behavior

The Radio Button should remain selected after the user navigates away from the view and back in.  Similar to the experience that happens with the Radio Group.

### Reproduction Sample

(https://codepen.io/NebHtesmar/pen/BamEJdR)

### Reproduction Steps

1. Setup a CC Radio Button Group with two Radio Buttons in a TSX virtual DOM environment. 
2. Set  the first button to checked and the second button not checked
3. Access the page with the Radio Buttons, the first Radio Button is correctly selected.  
4. Navigate to a different view or click the browser back button and then back in to the view with the Radio Button component. 
5. Neither the "Off" or "On"  Radio buttons are selected. 
6. Log out the component in the console and notice that the checked is set to true for the first button

### Reproduction Version

1.0.0-beta.77

**Comment by jcfranco** [comment]
Thanks for reporting this. I have a few questions:

1. Would it be possible to submit a repro case with your TSX + VDOM setup? 
2. What is your VDOM environment? I see `vnodeSelector` in one of the screenshots, so I'm guessing it's either maquette (standalone or from the JS API).
3. Where are `RadioButtonGroup`/`RadioButton` coming from? They seem to be external since neither our components have an `items`, `useLabels` props nor an `onChange` event.

**Comment by jcfranco** [comment]
I'm going to go ahead and close this. Based on ☝️, I have a hunch that it is not related to the components. Please reopen if there's additional info on this.
