### ISSUE TITLE
No `change` event if input cleared after setting value programmatically with focus

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#4232]
### Actual Behavior

If an empty `calcite-input` element has focus and its value is set programmatically, it will not dispatch a `calciteInputChange` event if it's manually cleared and blurred.

### Expected Behavior

A `calciteInputChange` event is dispatched because the value was changed due to a user interaction.

### Reproduction Sample

https://ember-twiddle.com/84ec2591fdac5ae61ae10e6dc804d632/3e2cba5bcd55a0fb71c82258be68d252a4fea18e

### Reproduction Steps

1. Visit the sample and open the browser's dev tools console
2. Click the "Seed value with focus shift" button
3. After focus shifts to the input, clear the contents of the input, and then blur the input in some way
4. Observe that "didChangeSeededInput" does not appear in the console indicating that the input's `calciteInputChange` handler was not run

### Reproduction Version

1.0.0-next.415

### Relevant Info

A follow-on to https://github.com/Esri/calcite-components/issues/4229.

**Comment by jcfranco** [comment]
Non-Ember repro case: https://codepen.io/jcfranco/pen/yLqrPMp

**Comment by geospatialem** [comment]
Migrating to the upcoming February milestone for the fix to land later this month.

**Comment by geospatialem** [comment]
Verified in `1.0.5`

![image](https://user-images.githubusercontent.com/5023024/217850846-2e928f95-d50a-439b-8616-16cf2902dc8b.png)
