### ISSUE TITLE
Popover stopped working between beta.77 and beta78

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/calcite-components#4242]
### Actual Behavior

calcite-popover stopped working between beta.77 and beta.78

### Expected Behavior

expected popover to keep working between beta.77 and beta.78

### Reproduction Sample

https://codepen.io/john-grayson/pen/gOopqEV

### Reproduction Steps

1.click on the information icon to the right of of 'Recent Weather' and notice how the popover appears.
2. change calcite-component version to beta.78
3. repeat step #1 and notice how the popover does NOT appear any more

### Reproduction Version

beta.79

### Regression?

beta.77

**Comment by macandcheese** [comment]
@jgrayson-apl - I verified this works on v80 - could you give that a try and close if you can confirm?

**Comment by jcfranco** [comment]
Closing based on ☝️ ([test app](https://codepen.io/jcfranco/pen/abEwaZg?editors=1010)).
