### ISSUE TITLE
Enhancement: calciteCheckboxChange event should include modifiers or underlying click or keyboard event

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-components#4248]
### Description

When toggling a checkbox, some apps may want to perform special logic depending on the state of modifier keys.

It would be great to have a way of looking at the state of the modifier keys when handling the `calciteCheckboxChange` event (but potentially others as well). Alternatively, the original `KeyboardEvent` or `MouseEvent` that triggered the `calciteCheckboxChange` could be included, just like we include the `target`.

### Acceptance Criteria

- Modifier keys should be available in the `calciteCheckboxChange`, or the original `KeyboardEvent` or `MouseEvent`.

### Which Component

`<calcite-checkbox>`

### Example Use Case

A concrete example is the SceneViewer team which needs to be able to toggle the visibility of all the sibling layers if the `meta`/`ctrl` is down when toggling the visibility of one of the layers. Currently there is a workaround in place by using keyboard events and storing the state of the modifier keys locally in the component and then using it to inform the behavior triggered `calciteCheckboxChange`. It would be great to simplify the event handling there and avoid local state management of the keyboard.

<sub>svch</sub>

**Comment by jcfranco** [comment]
I'd like to avoid adding click/keyboard events to the component events as they are not related to the component itself. Your current approach (separately tracking mouse/keyboard state) seems solid.

Closing this one for now. cc @benelan
