### ISSUE TITLE
Bug: [combobox] Mac Fn + right/left (home / end) should toggle corresponding first/last item into focus & scroll into view after opening listbox

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#4265]
### Actual Behavior

Mac Fn+left (home) initially focuses on the first item in the open listbox, but won't scroll to the last when hitting Fn+right (end). And after you scroll down to it manually, it won't scroll back to home. 

### Expected Behavior

Mac Fn + right/left (home / end) should toggle corresponding first/last item into focus & scroll into view if open or after opening the listbox.

### Reproduction Sample

https://codepen.io/elijbet/pen/jOYWwbW

### Reproduction Steps

1. Click on Combobox to open.
2. Click home/fn+leftArrow and see it focus on the first item.
3. Click end/fn+righArrow and notice it won't scroll to last item.</p>
4. Scroll to last item manually and see that it is highlighted.
5. Click home/fn+leftArrow and notice that it won't scroll back to the highlighted first item.

### Reproduction Version

v1.0.0-beta.80

### Relevant Info

Follow up on PR #4218

Once the last item in focus scrolls into view, update the combobox.e2e.tx test with: 
```
    it(`End opens dropdown and puts focus on last item`, async () => {
      const inputEl = await page.find(`#parentOne >>> input`);
      await inputEl.focus();
      await page.waitForChanges();
      expect(await page.evaluate(() => document.activeElement.id)).toBe("parentOne");

      await page.keyboard.press("End");
      await page.waitForChanges();
      const lastFocusedGroupItem = await page.find("#three >>> .label--active");
      expect(lastFocusedGroupItem).toBeTruthy();
      const visible = await lastFocusedGroupItem.isVisible();
      expect(visible).toBe(true);
    });
```

**Comment by benelan** [comment]
@jcfranco / @macandcheese can one of you verify this one? Kitty and I don't have a Mac

**Comment by geospatialem** [comment]
Was able to test on my personal Mac - verified on next. ✅ Also helps create a better experience for Windows users as well! 👍🏻
