### ISSUE TITLE
Enhancement: dropdown placement when not enough space in parent component

### ISSUE THREAD

**Issue by sam11927** [Esri/calcite-components#4272]
This is regarding the `calcite-dropdown`. When there is not enough space in the parent component, the dropdown will now autofill to where it thinks there is space. Instead, we should be able to specify where to place it. For example, if there is a small component in the top right corner of the screen that creates a dropdown, it will autofill the placement to be `top` when it makes far more sense for it to be `bottom`. We should be able to still use placement when there is not enough space in the component (perhaps with an override).

**Comment by amring1** [comment]
Was this fixed by the above PR?

**Comment by ethanbdev** [comment]
Did you have a repro / can you close this @sam11927

**Comment by sam11927** [comment]
I am pretty sure this is fixed, I think we can close it.
