### ISSUE TITLE
Calcite-tooltip sometimes throws browser console error

### ISSUE THREAD

**Issue by arxit-nis** [Esri/calcite-components#4279]
### Actual Behavior

Using calcite-tooltip components is sometimes producing a console error (Chrome browser).
The error is : `o.getElementById is not a function` at https://js.arcgis.com/calcite-components/1.0.0-beta.77/p-2e29554c.js

### Expected Behavior

Even if the behavior of the component seems to be still OK, the error should not appear in the console.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/tooltip/

### Reproduction Steps

1. Open a new tab in your Chrome browser with the devtools opened.
2. Open the official calcite-tooltip documentation page
3.  Update the component properties and / or refresh configuration from the sample section.
4.  The error in the console should appear.
![calcite-tooltip-error](https://user-images.githubusercontent.com/95091581/159251673-194fd3bd-cf2a-4fbd-9ddc-d775536de05f.png)
 

### Reproduction Version

1.0.0-beta.80

### Relevant Info

Chrome : 99.0.4844.74

**Comment by geospatialem** [comment]
Verified on [tooltip documentation site](https://developers.arcgis.com/calcite-design-system/components/tooltip) 👍🏻
