### ISSUE TITLE
Inconsistent list item height when there's a mix with and without description

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#4281]
### Actual Behavior

List item heights are not consistent if there's a mix of them with and without `description` set.

### Expected Behavior

List item heights are consistent.

### Reproduction Sample

https://codepen.io/jcfranco/pen/YzYGPYb?editors=1010

### Reproduction Steps

Set up list with items where some use `description` and other don't.

### Reproduction Version

beta.80

**Comment by macandcheese** [comment]
I don’t know if this is a problem. Lists should be presenting sibling items that display the same content, maybe something we could suggest in the documentation. 

But as it stands if a summary or description wrapped, you would end up with different heights as well, and I don’t know if we want to get into adjusting that, imo.

**Comment by macandcheese** [comment]
Documentation site follow up for guidance on using these consistently:  https://github.com/ArcGIS/afd-calcite-documentation/issues/311
