### ISSUE TITLE
calcite-input-date-picker: hidden date-picker takes up space and affect layout on first render

### ISSUE THREAD

**Issue by rpanichakit9541** [Esri/calcite-components#4282]
### Actual Behavior

When `calcite-input-date-picker` is first rendered the hidden date-picker takes up space in the layout while it's not visible.

![input_date_picker_scroll](https://user-images.githubusercontent.com/44479773/159368420-c5a79781-0a78-4cb9-b0e0-3e4e8b38cb0a.PNG)

### Expected Behavior

The component should not take up the space for the date-picker until it is active and visible.

### Reproduction Sample

https://codepen.io/rpanichakit/pen/GRyjpoQ?editors=1000

### Reproduction Steps

1. Render a `calcite-input-date-picker` inside a container with a smaller height/width than the hidden date-picker and `overflow: auto`.
2. Observe the vertical/horizontal scroll bar

### Reproduction Version

beta.79

### Relevant Info

Windows 10, Chrome 99.0.4844.74

### Regression?

Unknown

**Comment by jcfranco** [comment]
You can use `overlay-positioning="fixed"` to escape the calendar popper from the scrolling container. https://codepen.io/jcfranco/pen/eYyvWzW?editors=1000

**Comment by rpanichakit9541** [comment]
@jcfranco - Thank you for the workaround.  For some reason when I try to apply this to the actual usage in the Home app I'm seeing a weird result where the popover is positioned incorrectly far from the input. Do you know why this would be happening?

![date_picker_position_fixed](https://user-images.githubusercontent.com/44479773/160434525-0e2cdfb5-406a-46de-9eb1-7848d105d762.gif)

**Comment by jcfranco** [comment]
@rpanichakit9541 Oh, I _think_ this is a Popper issue where if an ancestor applies certain styles (e.g. `transform`) it messes up the positioning. This can happen with nested poppers or if a parent element applies these styles itself. It looks like modal applies `transform`. We can check if modal styles can be tweaked to avoid this. Can you share the hierarchy of components used in your GIF?

**Comment by rpanichakit9541** [comment]
@jcfranco - Thanks for the info.  I believe the implementation in my GIF is actually using a Home app specific `Overlay` component that we created before we started using `calcite-components` and it does have `transform: translate3D(0, 0, 0) scale(1);` styling.  

I'll try switching to using `calcite-modal` and let you know if that fixes it.

**Comment by jcfranco** [comment]
I think you'll encounter the same issue as `modal` uses `transform` at the moment. If possible, could you test removing the `Overlay` component's transform and see if that fixes positioning?

**Comment by rpanichakit9541** [comment]
@jcfranco - I just tried removing `transform` from `Overlay` and that fixed it as you suspected.

**Comment by jcfranco** [comment]
@rpanichakit9541 Awesome. Thanks for testing. I'm going to close this issue since `overlay-positioning` is the way to go. 

I will create issues for the following:

* refactor modal styles to avoid using transforms
* updating the doc for popper-owning components on when to use `overlay-positioning`
