### ISSUE TITLE
Calcite range slider not working properly on touch laptop

### ISSUE THREAD

**Issue by daniellaumer** [Esri/calcite-components#4290]
### Actual Behavior

When trying to drag a calcite slider on a laptop with touch screen, the dragging of the slider does not work. The slider thumb keeps stopping and you have to re-drag it. See attached screenshot: 
![CalciteSliderDrag](https://user-images.githubusercontent.com/93542103/159752574-ea3fbdef-eb82-4660-b158-4fb5a0c2ee0a.gif)

Note: A common html range slider works fine. 

### Expected Behavior

The expected behaviour is that the slider thumb follows the touch gesture and does not stop. 

### Reproduction Sample

Just any calcite slider

### Reproduction Steps

Open any example of a calcite slider on a laptop with touchscreen, for example this one: https://developers.arcgis.com/calcite-design-system/components/slider/

Not sure though if it happens for all touch laptops, the problem occured on a Dell Precision 5560

### Reproduction Version

beta.2

### Relevant Info

Windows 10, Chrome and Edge, Hardware: Dell Precision 5560

### Regression?

Probably never worked

**Comment by jcfranco** [comment]
@daniellaumer Thanks for reporting this. 

Additional testing on Windows 10 (thanks @bsvensson!) revealed issues with the following:

* Chrome version 99.0.4844.82 (Official Build) (64-bit)
* Chrome Version 100.0.4896.46 (Official Build) beta (64-bit)
* Chrome Version 100.0.4896.56 (Official Build) beta (64-bit) 
* Edge 99
* Firefox 99 (probably the worse, similar to Edge 99)
* Firefox Beta 100 (behaves like Chrome)

**Comment by benelan** [comment]
@bsvensson @daniellaumer can I have some help verifying that this issue is resolved? I don't have a touch laptop. Thanks!

**Comment by bsvensson** [comment]
I can help test @benelan - do you have a codepen or similar to test before/after?

**Comment by benelan** [comment]
Before:
https://codepen.io/benesri/pen/wvmmLJW

After:
https://codepen.io/benesri/pen/NWYYZpb

**Comment by daniellaumer** [comment]
I tested both links on my touch laptop and the bug still exists on both. Not sure if the bug was not fixed correctly or something goes wrong with loading the new version of calcite in the second app?

**Comment by bsvensson** [comment]
No improvement on my Dell Latitude 7320 touch laptop -- running Windows 10 Enterprise (10.0.1042 Build 19042)
* Edge Version 104.0.1293.63 (Official build) (64-bit)
* Chrome Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by benelan** [comment]
Thank you both for testing, I'm assigning this issue back to dev.

**Comment by geospatialem** [comment]
@daniellaumer `1.1.0` has been released and includes a fix to the above issue. however I don't have access to a touch laptop to verify the fix.

Would you be able to verify if the fix is working with `1.1.0` in the [following Codepen](https://codepen.io/geospatialem/pen/RwYyBEQ)?

**Comment by geospatialem** [comment]
@bsvensson Would you be able to verify if the above fix is working with `1.1.0` in the [following Codepen](https://codepen.io/geospatialem/pen/RwYyBEQ) with your touch laptop?

**Comment by bsvensson** [comment]
@geospatialem Yes, 1.1.0 works great on my Dell touch laptop using both Chrome Beta 112.0.5615.49 and Chrome 111.0.5563.147 (while 1.0.8 does not).

**Comment by geospatialem** [comment]
Thanks much! Closing out and marking as verified per Bjorn's verification above.
