### ISSUE TITLE
[Input Message] Fix overzealous animation

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4291]
### Actual Behavior

When making an input-message active by adding the attribute, currently the animation is rather ... in your face. I think we should tone this down a bit. 

https://user-images.githubusercontent.com/4733155/159779399-1a3c561b-3537-40f4-8964-d46e90f244eb.mov

![bam-cooking-show](https://user-images.githubusercontent.com/4733155/159779330-d38e9a9c-e07c-4648-9c95-06c24b0f8322.gif)

### Expected Behavior

Don't use a scale-in effect to display the input message. 

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/ExoPEBe?editors=1111

### Reproduction Steps

In codepen:
Click "add" in the slotted input button without entering anything in the input. See the wild and wacky animation.

### Reproduction Version

80

### Relevant Info

cc @mitc7862 @asangma

**Comment by geospatialem** [comment]
Verified on next

https://user-images.githubusercontent.com/5023024/170574419-3edff617-cf06-4493-bf10-88ecb10fa716.mov
