### ISSUE TITLE
Stepper in custom element - next/previous methods have no visual effect

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#4305]
### Actual Behavior

When stepper is in a custom element, the `nextStep` and `prevStep` methods do not visually change position. However, the `calciteStepperItemChange` event does trigger and the position is changed internally.

### Expected Behavior

Stepper works like it does when it is not inside a custom element.

### Reproduction Sample

https://codepen.io/benesri/pen/MWrJqzj

### Reproduction Steps

1. Open the repro sample
2. Open the dev tools console
3. Click the "Previous Step" and "Next Step" buttons
4. Notice that there are no visual changes to the stepper. 
5. In the console the `calciteStepperItemChange` is logged and the `position` is changed internally
6. Repeat in [this codepen](https://codepen.io/benesri/pen/PoEWKXv), which works correctly

### Reproduction Version

beta.80

### Relevant Info

In the repro sample, the `calciteStepperItemChange` event target is `custom-element`. It looks like it isn't visually changing position because the [target element needs to be the parent `calcite-stepper`](https://github.com/Esri/calcite-components/blob/master/src/components/stepper-item/stepper-item.tsx#L185-L188).

**Comment by geospatialem** [comment]
verified in next. 🎉
