### ISSUE TITLE
It is not possible to override the Icon color in the Chip component

### ISSUE THREAD

**Issue by BennyBaruba** [Esri/calcite-components#4306]
### Actual Behavior

When overriding the Icon color using `--calcite-ui-icon-color` for the Chip component, the icon color does not change.  However the text color changes.

### Expected Behavior

 Using `--calcite-ui-icon-color` to override the Icon color for the Chip component, should change the color for the icon and not the color of the text in the Chip.  The workflow should be the same as seen in the Button or Tab component.

### Reproduction Sample

https://codepen.io/NebHtesmar/pen/vYpgWVZ

### Reproduction Steps

1. Add a Chip component to an application
2. Override the Icon color by using `--calcite-ui-icon-color`
3. Notice the color of the Icon does not change, however the text does.

### Reproduction Version

https://codepen.io/NebHtesmar/pen/vYpgWVZ

**Comment by BennyBaruba** [comment]
@macandcheese

**Comment by geospatialem** [comment]
Verified in next

![icon color change in calcite-chip with CSS verified](https://user-images.githubusercontent.com/5023024/167164861-c4bbbc3d-d7b7-4143-9d73-7a939810604d.png)
