### ISSUE TITLE
Dropdown contents should not be dependent on the parent element

### ISSUE THREAD

**Issue by dhrumil83** [Esri/calcite-components#431]
Enhancement to this fix: https://github.com/Esri/calcite-components/issues/396
Codepen: https://codepen.io/dhrumil83/pen/poJBbEW

Can end up with 2 scrollbars when parent element to the dropdown has a height specified.

![image](https://user-images.githubusercontent.com/14285436/78198450-7dc34e00-743d-11ea-99a3-eb077f2058fe.png)

Behavior should be like the regular select, where the scrolling is independent of the parent element.
![image](https://user-images.githubusercontent.com/14285436/78198599-ead6e380-743d-11ea-9176-d78a1bbc93f0.png)

Potential fix can be to open the dropdown contents in a popover/popper?
Short term fix can be to let the client specify the max allowed height.

**Comment by jcfranco** [comment]
I submitted a PR to allow users to specify the max items to show before we show the scroller.
