### ISSUE TITLE
calcite-pick-list needs an event specific to its filter to get filtered items

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#4333]
### Description

When using `calcite-pick-list` with `filterEnabled:true` the only way to get to the filtered items is by listening to `calciteFilterChange` and using `event.path[0].filteredItems`.

Before November 2021 we could get the filtered items via `calciteFilterChange` and `event.detail`.
See: https://github.com/Esri/calcite-components/pull/3449

cc @dhrumil83

### Acceptance Criteria

There should be an event on `calcite-pick-list` specific to the filter to get the filtered items.

### Which Component

calcite-pick-list

### Example Use Case

```
<calcite-pick-list filter-enabled>
  <calcite-pick-list-item label="Chocolate" value="chocolate">
    <calcite-action slot="actions-end" icon="ellipsis-circle"></calcite-action>
  </calcite-pick-list-item>
  <calcite-pick-list-item label="Vanilla" description="Oldie but goodie" value="vanilla">
    <calcite-action slot="actions-end" icon="ellipsis-circle"></calcite-action>
  </calcite-pick-list-item>
  <calcite-pick-list-item label="Strawberry" description="no metadata on this one" value="strawberry">
    <calcite-action slot="actions-end" icon="ellipsis-circle"></calcite-action>
  </calcite-pick-list-item>
</calcite-pick-list>
```

**Comment by jcfranco** [comment]
[Implementor's note] Both `calcite-value-list` and `calcite-pick-list` need to be updated. 

#### Proposal

```ts
interface List {
  calciteListFilter: EventEmitter<void>;
  filterText: string;
}
```

#### Question

* Should filtering affect the selected values (not the items)? Both components have methods to get the selected items, but we may need an additional convenience prop for filtered ones if filtering is independent of selection.

@driskull @eriklharper @Elijbet WDYT about ☝️? Any name suggestions?

**Comment by driskull** [comment]
It depends on the purpose of the filter. If the filter is just to help the end user narrow results to select, it might not need to affect the value.

Maybe we shouldn't filter out selected values if we always want to show them?

**Comment by driskull** [comment]
The way the combobox gets away with this is that it is always showing the selected items as chips.

**Comment by AdelheidF** [comment]
Use case in table component.

User can filter a certain subset of fields then either hit select all or deselect all on that subset of fields. So it needs to know the subset of fields to make the adjustments in the table.

![image](https://user-images.githubusercontent.com/44481292/161174124-025fea01-73f3-4d7a-9708-47fd04c8f5a7.png)

**Comment by AdelheidF** [comment]
Could I also somehow 're-apply' the filter after the list changes order?

E.g. my list has 100 items and they're sorted A-Z. Now I enter a filter string "SOMETHING" and the list 'shrinks' to 20 items. Now the user clicks on a menu option (next to the filter input) to sort the list via Z-A. Now it re-renders the list items. The list now displays all 100 items sorted Z-A and the filter still shows "SOMETHING". There is no way to remove the filter string, or preferably apply the same filter to the new list.

I could re-create the pick-lists from scratch when re-sorting, but this takes a while if the list is long and the user looses the filter.

**Comment by driskull** [comment]
> Should filtering affect the selected values (not the items)? Both components have methods to get the selected items, but we may need an additional convenience prop for filtered ones if filtering is independent of selection.

I lean towards filter being independent of selection. So, filter will not treat selected values any different than non selected values. If we want to introduce a prop later to configure this we can.

**Comment by geospatialem** [comment]
Verified in `next.639` with [sample](https://codepen.io/geospatialem/pen/BaVrmwB).

Adds:
- `calciteListFilter` event
- `filteredItems`, `filterText` and `filteredData`  props
