### ISSUE TITLE
ListItem - Let content-start and content-end slot occupy full width

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#4336]
### Description

When only the `content-start` or `content-end` is used, let it take up the full width of the content area.

Currently the content slots are set to `flex: 0 1 auto`.
This works great for most cases.

In some cases, it is helpful to use one slot for custom content. This is especially helpful if the content needs to have a dynamic width and would benefit from getting an calculation on percentage-based widths, e.g. `width: 100%`

cc @macandcheese 

### Acceptance Criteria

When either content slot is use and is the only-child, it takes up the full width.
Existing behaviors remain the same.

### Relevant Info

This codepen shows that `width: 100%` gives us a non-useful value.
https://codepen.io/mtb-alan/pen/yLpoxjx

Ideally, the result would look like:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/12503298/160947117-a40476d6-2af3-4150-8f46-df02772b215b.png">

The red is the `.demo` div.

### Which Component

CalciteListItem

### Example Use Case

When a more customized UI is requested, e.g.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/12503298/161310567-82f63272-1e6c-49ea-a51d-13394f830d96.png">

**Comment by asangma** [comment]
@benelan I have a branch pretty much ready to go if we wanna up the priority on this one.

**Comment by benelan** [comment]
@asangma I assigned you and triaged it to the next sprint

**Comment by asangma** [comment]
Thanks!

**Comment by benelan** [comment]
Verified on next
