### ISSUE TITLE
calcite-inline-editable keeps emitting events after editing was cancelled or confirmed

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#4350]
### Actual Behavior

The calcite-inline-editable element will emit events after the editing has been cancelled or confirmed.
The event is emitted on mouse hovering on the edit button.

![image](https://user-images.githubusercontent.com/3506166/161120844-eba4ca10-2100-4db2-a814-3448c480e325.png)

### Expected Behavior

After editing the events should not be emitted.

### Reproduction Sample

https://codepen.io/ffaubry/pen/qBpPRvJ?editors=1001

### Reproduction Steps

1. Open the console view
2. Click on the edit button
3. Click in the cancel button
4. Hover on the edit button
5. You should see events being fired

### Reproduction Version

beta.80

**Comment by jcfranco** [comment]
[For implementor]: https://github.com/Esri/calcite-components/blob/083d283caf719eed91cb1f5bd71b4584864b5e61/src/components/inline-editable/inline-editable.tsx#L278 may be firing because of bubbling transition events.

**Comment by geospatialem** [comment]
verified on next ✔️
