### ISSUE TITLE
Improve `overlay-positioning` doc for popper-owning components

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#4355]
### Description

Stems from https://github.com/Esri/calcite-components/issues/4282

We should add more info on when to use the `absolute` vs `fixed` positioning strategies. 

### `absolute`

- should work for most cases
- when parent container is scroller
  - it will not escape it (positioned inside the scrolling container)
  - popper content affects the scrolling container's layout

### `fixed` 

- should be used when parent container is positioned with `fixed`
- can help escape a popper from a parent scrolling container

### Which Component

* `dropdown`
* `combobox`
* `input-date-picker`
* `input-time-picker`
* `popover`
* `tooltip`

### Resources

https://floating-ui.com/docs/misc#z-index-stacking-and-clipping
https://github.com/floating-ui/floating-ui/issues/1527#issuecomment-1029520798 (most recent suggestion)
https://github.com/floating-ui/floating-ui/issues/1035#issuecomment-603227037
https://popper.js.org/docs/v2/faq/#why-is-my-popper-jittering-while-scrolling
https://popper.js.org/docs/v2/constructors/#strategy

**Comment by jcfranco** [comment]
@benelan Can we prioritize this doc? I think it's necessary since popper/floating-ui-owner components can be used in different contexts. cc @driskull

**Comment by geospatialem** [comment]
Verified on `master.sites`.
