### ISSUE TITLE
Ensure flipPlacements are computed placements

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#4361]
### Discussed in https://github.com/Esri/calcite-components/discussions/4328

<div type='discussions-op-text'>

<sup>Originally posted by **benelan** March 29, 2022</sup>
Following up on our Teams discussion today.

Now that popper has start/end, we should consider removing the leading/trailing positions we added. I know @driskull needs to look into this a bit first. 

Not a high priority change, I just [ran into an error](https://codepen.io/benesri/pen/OJzgYWB) when clicking on a dropdown trigger while using trailing/leading positions for `flipPlacements`. 
![image](https://user-images.githubusercontent.com/10986395/160720786-c0f28e93-4189-4fde-97b1-ae81003443a3.png)

If anyone has a dissenting opinion, speak up!</div>

### Expected Behavior

Filter out invalid flipPlacements values, and/or log valid placement options to the console

### Reproduction Sample

https://codepen.io/benesri/pen/OJzgYWB

### Reproduction Steps

1. Click on the dropdown trigger
2. Check the console for an error

### Reproduction Version

beta.80

**Comment by geospatialem** [comment]
Verified on next 👍🏻
