### ISSUE TITLE
The calciteDatePickerChange event is not triggered when the value of input date picker is cleared

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-components#4363]
### Actual Behavior

The calciteDatePickerChange event of the input date picker does not get triggered when the value is cleared.

### Expected Behavior

The calciteDatePickerChange event of the input date picker should be triggered when the value is cleared.

### Reproduction Sample

https://codepen.io/nan9266/pen/GRyOZLx?editors=1111

### Reproduction Steps

1. Open the console of the sample above
2. Change the value of the input date picker, observe that the calciteDatePickerChange is triggered, and "Test picker changed" appears in the console.
3. Clear the value of the input date picker, observe that the calciteDatePickerChange is not triggered.

### Reproduction Version

beta.80

**Comment by fendiaoxiaoshuazi** [comment]
This is a crucial issue for Survey123. 
1. For a required date question, we are not able to prevent submission when the input value gets cleared.
2. When the value gets cleared, we are not able to change the actual submission value since we don't know the value has been changed.

**Comment by geospatialem** [comment]
verified in next ✅
