### ISSUE TITLE
The time picker of the input time picker appears in different positions

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-components#4364]
### Actual Behavior

The time picker of the input time picker appears in different positions when the value gets cleared.

### Expected Behavior

The time picker should appear on the same position.

### Reproduction Sample
https://codepen.io/nan9266/pen/KKZymWx

### Reproduction Steps

1. Click on the input time picker, observe the position of the time picker
2. Clear the value of the input time picker, observe the position of the time picker changes
3. Click outside, and click the input time picker again, observe the position of the time picker changes

### Reproduction Version

beta.80

**Comment by benelan** [comment]
Hi @fendiaoxiaoshuazi, can you please provide a sample that reproduces the issue?

**Comment by fendiaoxiaoshuazi** [comment]
Hi @benelan , the sample and screen shot has been included in the description.

**Comment by jcfranco** [comment]
[Implementor's note]: The input time picker needs a `reposition` method (similar to [other](https://github.com/Esri/calcite-components/blob/master/src/components/tooltip/tooltip.tsx#L131) [popper](https://github.com/Esri/calcite-components/blob/master/src/components/input-date-picker/input-date-picker.tsx#L293)-[owner](https://github.com/Esri/calcite-components/blob/master/src/components/dropdown/dropdown.tsx#L213) [components](https://github.com/Esri/calcite-components/blob/master/src/components/combobox/combobox.tsx#L205)).

**Comment by jcfranco** [comment]
@fendiaoxiaoshuazi Here's one workaround in the meantime: https://codepen.io/jcfranco/pen/jOYxxNQ?editors=1010

**Comment by benelan** [comment]
verified on `next`
