### ISSUE TITLE
Closable Tab

### ISSUE THREAD

**Issue by ranga-tolapi** [Esri/calcite-components#4365]
Possible to introduce **closable/dismissible** feature to Tab (calcite-tab)?

**Comment by macandcheese** [comment]
Hi @ranga-tolapi - do you have a use case or intended design for this request? More context could help determine if this is an enhancement we'd like to pursue. Thanks!

**Comment by ranga-tolapi** [comment]
Hi @macandcheese - our application allows users to search and add layers dynamically on to the map.

Would like to give below options for users...
- to open/view the attribute tables of their interested layer(s) in multiple tabs (This is possible with calcite-tabs)
- to close the attribute tables/tabs which they don't want to see anymore (This is currently **NOT** possible with calcite-tabs)

Hope this helps! Thank you.

**Comment by benelan** [comment]
closing as duplicate of #2620
