### ISSUE TITLE
Introduce tokens for z-index management (overlay layers)

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#4372]
### Description

Stems from https://github.com/Esri/calcite-components/pull/4182#discussion_r840900777

It would be beneficial to introduce a set of tokens to represent different levels of z-indices used in the design system. This could help our components use the same index depending on the context and better inform users on how to override these values. 

### Acceptance Criteria

1. A new set of tokens for z-indices is added (Tailwind for now)
2. These z-index tokens should provide context for their intended use
3. Components that require z-index should use these for consistency instead of hardcoded values

### Relevant Info

https://www.lightningdesignsystem.com/design-tokens/#category-z-index
https://designsystem.morningstar.com/legacy/v/2.4.0/visual-language/layering.html
https://www.duetds.com/tokens/#z-index
https://github.com/dojo/widgets#z-index-layering
https://www.smashingmagazine.com/2021/02/css-z-index-large-projects/

### Which Component

Any component that makes use of overlays.

**Comment by jcfranco** [comment]
All components should now use the [contextual tailwind z-index utils](https://github.com/Esri/calcite-components/blob/master/tailwind.config.ts#L213-L221) when layering is needed. If developers need to tweak layering, they can reference our z-index layers and set z-indices in their apps accordingly.

**Comment by geospatialem** [comment]
Verified on master ✨
