### ISSUE TITLE
Suggest avoiding setting height on components

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#4383]
### Description

Suggest not setting heights on components and instead leaning on prescribed font-size or content height and prescribed padding.

Some of our components have height set while others rely on content height (normally text with prescribed size) and padding.

The two approaches can result in different calculated heights.

In order to see how the two approaches differ, see [this demo](https://codepen.io/mtb-alan/pen/MWrVzwB?editors=1000).

### Acceptance Criteria

Consistent styling approach and consistent heights.

### Which Component

Ones which set their height.

### Example Use Case

When multiple components need to live together and look consistent...so kind of all of the use cases...?

**Comment by geospatialem** [comment]
@asangma Do you have a use case we can use to illustrate the above ask? We have an issue for combobox via https://github.com/Esri/calcite-components/issues/6421. Want to verify if additional use cases should apply to the ask.

**Comment by geospatialem** [comment]
@asangma - do ya have use case or proposal for the the request above? [Some additional context regarding an open combobox issue](https://github.com/Esri/calcite-components/issues/4383#issuecomment-1572648414) is above.

**Comment by geospatialem** [comment]
Closing the above, @asangma feel free to reopen if we have additional info.
