### ISSUE TITLE
Expose the version of CC within an app's dev files

### ISSUE THREAD

**Issue by shawnmgoulet** [Esri/calcite-components#4386]
### Description

Much like you added the version [to the built dist file](https://github.com/Esri/calcite-components/pull/4303), maybe there's somewhere to add the version the app is using to the files generated on `npm run dev`.

### Acceptance Criteria

![67ef8912-894f-4d25-9046-6c5228fe7ff6](https://user-images.githubusercontent.com/3179974/162486832-78f2650b-f0fd-4bb7-a458-360439605139.jpg)

the CC version the app is using mentioned somewhere in a dev file and indicated in the docs

### Which Component

n/a

### Example Use Case

Sorting out why the footer was appearing in the Modal component without slotted content. Was indicated by @macandcheese that it was removed around beta-76, but wasn't apparent looking at the dev files in the sources what version the app was using. This would help when researching.

**Comment by jcfranco** [comment]
The installed version info is available in `package.json` or `package-lock.json` (if using a range in `package-lock.json`). Will that address your use case?

**Comment by benelan** [comment]
I actually installed a PR for this a couple weeks ago (#4303). The version number is [already included in `next` releases](https://unpkg.com/@esri/calcite-components@1.0.0-next.438/dist/calcite/calcite.esm.js).

**Comment by benelan** [comment]
Woops, I'm sorry I didn't original issue close enough. Yeah Franco's comment should cover local development. If it doesn't, then we can reopen this issue.

**Comment by shawnmgoulet** [comment]
Awesome, will take a look when then next release goes out - thanks all.
