### ISSUE TITLE
Tile description overflows

### ISSUE THREAD

**Issue by tyanthony** [Esri/calcite-components#4390]
### Actual Behavior

In the `Tile` component, the `description` property overflows outside of the tile boundaries.

Ex: 
![unknown](https://user-images.githubusercontent.com/17069279/162818148-b2ef834f-d2b7-400a-9c69-b81d3124f779.jpg)

### Expected Behavior

The description should wrap (similar to the `heading`).

### Reproduction Sample

https://codepen.io/tyleranthony/pen/dyJjWeK?editors=100

### Reproduction Steps

1. Implement a Calcite Tile with a set width
2. Add the `description` property with a long description (the example uses a single long "word" without spaces)
3. Observe text overflow

### Reproduction Version

1.0.0-beta.80

**Comment by geospatialem** [comment]
verified in next ✔️ 

![screenshot of calcite tile description in next](https://user-images.githubusercontent.com/5023024/164768325-43f5b4db-c40d-4590-b2fc-1c4363d96b13.png)
