### ISSUE TITLE
[Map Viewer] [Charts] I18N-TXT-VI[Edge Chromium/FF/Chrome]: Inconsistent fonts displays on “Select chart type” menu of Configure charts tool.

### ISSUE THREAD

**Issue by Olga8614** [Esri/calcite-components#4392]
<div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;">Steps:<br style="box-sizing:border-box;"></span><div style="box-sizing:border-box;">1. Prepare a clean VI browser.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">2. Sign in Qaext site (https://qaext.arcgis.com) successfully.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">3. Open Map Viewer app and add some layers.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">4. Select Configure charts tool and click +Add chart button.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">5. Observe.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;"><br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">Actual result:<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">Inconsistent fonts displays on “Select chart type” menu of Configure charts tool.<br style="box-sizing:border-box;"> </div><span style="box-sizing:border-box;">Please refer to the screenshot “fonts.jpg&quot; for details.</span><br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;"><img src="https://github.com/ArcGIS/I18N-BYS-Bugs/blob/master/issues/13624_font.jpg?raw=true" alt = "13624_font.jpg" alt=font.jpg><br style="box-sizing:border-box;"></span> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;"><span style="box-sizing:border-box;">Expected Result:<br style="box-sizing:border-box;"></span><div style="box-sizing:border-box;">Font of each character should be consistent on “Select chart type” menu of Configure charts tool.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;"><br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">Additional information:<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">1. This behavior does not occur in TR language.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">2. This behavior also occurs in Chrome/FF browsers.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">3. This behavior does not occur with Safari browser.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">4. This behavior also occurs on Devext site.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">5. This behavior does not occur on 9.4 Production site.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;"><br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">Test case: https://github.com/ArcGIS/I18N-BYS-TestCases/issues/8081<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;"><br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">Configuration:<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">1. Build Version: AGOL 10.1 Qaext site<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">2. OS: ENU win10 64bit and change system language and locale to VI.<br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">3. Browser: Edge Chromium<br style="box-sizing:border-box;"> </div><span style="box-sizing:border-box;">4. Found by date: 3/7/2022</span></span> </div><br> </div><br/> Build Number : 3/7/2022

**Comment by Olga8614** [comment]
https://github.com/ArcGIS/I18N-BYS-Bugs/issues/10331

**Comment by Olga8614** [comment]
QV-B-Medium,CR-BY-Beyondsoft_I18N,QV-A-Bug,QV-C-I18N,QV-S-ToVerify,QV-S-DevAssigned,QV-C-VI,QV-P-Chrome;Edge;Firefox

**Comment by Olga8614** [comment]
![image](https://user-images.githubusercontent.com/29614798/162853272-64e2a14d-4aa6-43a1-a3cb-9a26bb11dc1f.png)

**Comment by Olga8614** [comment]
@paulcpederson

**Comment by paulcpederson** [comment]
after a bit of investigation, I've found this is not a calcite issue. Closing and will work with Olga to triage
