### ISSUE TITLE
Enhancement : Accordions. Add expand and collapse animations

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#440]
Make them animate all cool like.

Probably want the ability to turn off animations?

Ideally, this would rely mostly on CSS animation or transition and not get too script-y.

cc @macandcheese

**Comment by bstifle** [comment]
on by default woot!

**Comment by macandcheese** [comment]
I meant I don't think we should offer the option to turn it off, once added. Seems like a granular configuration that's unique to a specific component.

**Comment by bstifle** [comment]
leave it on woot!

**Comment by asangma** [comment]
@macandcheese Sounds good.
