### ISSUE TITLE
The abbreviation of the weekday on the date picker calendar of RU is not correct

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-components#4401]
### Actual Behavior

The abbreviation of the weekday on the date picker calendar of RU is not correct.

The abbreviation of the weekday of the RU calendar from left to right is Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, and Monday. However, the first column on the calendar are Mondays, e.g April 4th, April 11th, etc.
![image](https://user-images.githubusercontent.com/26078106/163120305-9dbd9a9d-86d2-45ca-a6dd-7e4035622994.png)

### Expected Behavior

Use the correct abbreviation for the weekday of RUH

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/date-picker/

### Reproduction Steps

1. Change the locale to RU
2. Observe that the weekday and date are not correlated

### Reproduction Version

beta.80

**Comment by benelan** [comment]
verified on next
