### ISSUE TITLE
The typed-in value on the input date picker is not honored by the component

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-components#4402]
### Actual Behavior

When I try typing in a value in the input date picker, the typed-in value will be changed while typing or after losing focus.
![date picker](https://user-images.githubusercontent.com/26078106/163167054-6e541a75-8cc3-4523-a834-ee2e5c75c1ec.gif)

### Expected Behavior

The value that already exists should not be changed while typing or after losing focus.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-date-picker/

### Reproduction Steps

1. Try type in a date value in the input date picker
2. Close the picker using `Esc`, and then click outside

### Reproduction Version

beta.80

**Comment by eriklharper** [comment]
@geospatialem this one has also been resolved by #5459.  Note: I changed this issue to only refer to the Input Date Picker bug.  I created a new issue for the Input Time Picker, which is still valid: #5847

**Comment by geospatialem** [comment]
Verified in `beta.97`

![verify-input-date-picker-esc](https://user-images.githubusercontent.com/5023024/205972075-f2dec630-a3d3-45d0-8ee1-af00d382338c.gif)
