### ISSUE TITLE
calcite-action with built-in tooltip

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#4414]
### Description

Most calcite-action need a tooltip. It would be great if the component could take care of this instead of every action having to use calcite-tooltip-manager and managing a tooltip itself. 

### Acceptance Criteria

Just using calcite-action with a tooltip label would create the calcite-tooltip component with the manager.

### Which Component

calcite-action

### Example Use Case

![image](https://user-images.githubusercontent.com/44481292/163439148-82214137-83ea-491e-8489-a5ca80979e6a.png)

![image](https://user-images.githubusercontent.com/44481292/163440354-7b300896-21d6-4201-9a8f-3933099b4d1b.png)

Maybe this could then also be used internally for better looking tooltips everywhere.

![image](https://user-images.githubusercontent.com/44481292/163440156-e0fa66b7-47db-492e-b965-5e91100d8679.png)

**Comment by driskull** [comment]
Would be nice to do once we deprecate the tooltip/popover manager components.

**Comment by macandcheese** [comment]
This would probably allow us to get rid of the [`expand-tooltip`](https://developers.arcgis.com/calcite-design-system/components/action-bar/#component-api-slots-expand-tooltip) slot on `action-bar`, which has always been a bit weird IMO.

**Comment by mjuniper** [comment]
I have a similar request for calcite-fab. In order to be accessible, I need to give it a text/label attribute but I am also giving it a tooltip and the two collide; see: https://codepen.io/mjuniper/pen/XWZNdNJ?editors=1000

@macandcheese suggested in a teams DM:

> where the fab's required text / label field could automatically create a tooltip (that you could opt in to with "showTooltip" or something like that).

**Comment by macandcheese** [comment]
@jcfranco @benelan could we give this another look now that the manager components have been deprecated?

**Comment by AdelheidF** [comment]
looks good, tested with beta.93
