### ISSUE TITLE
Define style guide and proof read component API reference

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#4442]
### Current Style Guide
So far we have the following conventions for API ref descriptions:

- Use complete sentences with proper grammar, capitalization, and punctuation.  
- No abbreviations, e.g. use "property" instead of "prop".  
- Verbs must be in present tense.  
- When referring to the component that the property/slot/method/css variable belongs to, call it "the component".  
- Use the full tag name when referencing other Calcite Components (prefix with `calcite-`), e.g. `calcite-button` instead of `button`.  
- For plural context, use `calcite-button`s instead of `calcite-button` elements.  
- Use backticks (``` ` ```) for the names of slots, events, properties, CSS variables, and component names.  
    - In line with the JSAPI docs [example](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-View.html#ready)  
    - Docs will incorporate styling with [afd-calcite-documentation issue #490](https://github.com/ArcGIS/afd-calcite-documentation/issues/490)  
- Use double quotes (`"`) for the values of properties/attributes and event details.  
- Only use single quotes (`'`) as apostrophes.  
- No links or URLs allowed in descriptions. If a link is necessary, a [custom JSDoc tag](https://stenciljs.com/docs/docs-json#custom-jsdocs-tags) should be added and parsed in the SDK site.  
- Refrain from using "e.g." or "i.e." references. Leverage "such as" (or similar) where examples are referenced.  
- Use "Accessible" instead of "Aria" language  
- Verify slots don't use the text "optional" in their descriptions  
- Remove optional JSDoc tags for props (`?`)

#### Common slots
- `header` - A slot for adding header text.
 - `content` - A slot for adding the component's content.

#### Events
- For click events, use descriptors such as "Fires", as opposed to "Emits", in line with MDN [mousedown](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event) and [mouseup](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseup_event) events.
    - For example: "Fires when the back button has been clicked." 

#### Common properties
- `active` - When true, the component is active.
- `appearance` - Specifies the appearance style of the component.
- `checked` - When true, the component is checked.
- `disabled` -  When true, interaction is prevented and the component is displayed with lower opacity.
- `dismissible` - When true, a close button is added to the component.
- `flipPlacements` - Defines the available placements that can be used when a flip occurs.
- `groupSeparator` - When true, number values are displayed with the locale's group separator.
- `heading` - The component header text.
- `headingLevel` - Specifies the number at which section headings should start.
- `height` - Specifies the height of the component.
- `icon` - Specifies an icon to display.
    - `iconStart` - Specifies an icon to display at the start of the component.
    - `iconEnd` - Specifies an icon to display at the end of the component.
    - `iconPosition` - When used with "icon", specifies its position.
    - `flipRtl` / `iconFlipRtl` - When true, the icon will be flipped when the element direction is right-to-left ("rtl").
- `label` /  `intlLabel` / `textLabel` (repeated below) - Accessible name for the component.
    - `intlClose` / `dismissLabel` - Accessible name for the component's close button.
    - `intlCollapse`  - Accessible name for the component's collapse button.
    - `intlExpand` -Accessible name for the component's expand button.
    - `intlLoading` - Accessible name when the component is loading.
    - `intlOptions` -Accessible name for the component's options button.
    - `intlClear` - Accessible name for the component's clear button.
- `layout` - Defines the layout of the component. 
- `loading` - When true, a busy indicator is displayed.
- `locale` - Specifies the BCP 47 language tag for the desired language and country format.
- `name` - Specifies the name of the component on form submission.
- `open` - When true, displays and positions the component.
- `placement` 
- `referenceElement` - The `referenceElement` used to position the component according to its "placement" value. Setting to an `HTMLElement` is preferred so the component does not need to query the DOM. However, a string `id` of the reference element can also be used.
- `required` - When true, the component must have a value in order for the form to submit.
- `scale` - Specifies the size of the component.
- `selected` - When true, the component is selected.
- `text` / `textLabel` (repeated above) 
- `value` - The component's value.
- `width` - Specifies the width of the component.

### Original Issue Description
Our property/slot/method descriptions are all over the place right now. We need to decide on some conventions, and then audit and proofread to make sure they are consistent. Some things to consider:

- Should they be sentences with proper case/punctuation/grammar, or should they be more like bullet points?
- Which verb tense should we use?
- Which quotation marks should be used (single vs double vs tick) in the descriptions? Should different quotation marks be used for different purposes (`calcite-xyz` vs "value")? e.g. [`disableCloseOnSelect`](https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-disableCloseOnSelect) uses double and [`overlayPositioning`](https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-overlayPositioning) uses single
- How should components be named when mentioned in the description? Should they be the full tag name? Should they be in quotes? - [here](https://developers.arcgis.com/calcite-design-system/components/button/#component-api-properties-splitChild) [here](https://developers.arcgis.com/calcite-design-system/components/combobox-item/#component-api-properties-ancestors) [here](https://developers.arcgis.com/calcite-design-system/components/combobox-item/#component-api-properties-icon) [here](https://developers.arcgis.com/calcite-design-system/components/flow/#component-api-methods-back)
- Should links be allowed in the description? If so, how should they be formatted? e.g. [`indeterminate`](https://developers.arcgis.com/calcite-design-system/components/checkbox/#component-api-properties-indeterminate), [`download`](https://developers.arcgis.com/calcite-design-system/components/link/#component-api-properties-download), [`value`](https://developers.arcgis.com/calcite-design-system/components/color-picker/#component-api-properties-value)

In addition to the consistency conventions, there is a lot of clean up that needs to happen. For example, 
- The description does not need to mention the default, since it is specified in the table - [here](https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-width) 
  - This also applies to documentation that is linked out, and contains many properties. 
- The description does not need to specify that it is read-only, since it displays a chip based on a jsdoc tag [here](https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-selectedItems)
- Product names should be capitalized, e.g. "Calcite UI Icons" vs [this](https://developers.arcgis.com/calcite-design-system/components/button/#component-api-properties-iconStart)

This is not an exhaustive list, but it is a start. If anyone else has something to add please feel free. @geospatialem and I will decide on and document the conventions, and then start updating the jsdoc.

cc @macandcheese and @jcfranco if you have any preferences on the conventions.

### Which Component
All components

<details>
  <summary><h2>Progress checklist (all done!)</h2></summary>

- [x] `accordion` (Ben)
- [x] `accordion-item` (Ben)
- [x] `action` (Ben)
- [x] `action-bar` (Ben)
- [x] `action-group` (Ben)
- [x] `action-menu` (Ben)
- [x] `action-pad` (Ben)
- [x] `alert` (Ben)
- [x] `avatar` (Ben)
- [x] `block` (Kitty)
- [x] `block-section` (Kitty)
- [x] `button` (Kitty)
- [x] `card` (Kitty)
- [x] `checkbox` (Kitty)
- [x] `chip` (Kitty)
- [x] `color-picker` (Kitty)
- [x] `combobox` (Kitty)
- [x] `combobox-item` (Kitty)
- [x] `combobox-item-group` (Kitty)
- [x] `date-picker` (Kitty)
- [x] `dropdown` (Kitty)
- [x] `dropdown-group` (Kitty)
- [x] `dropdown-item` (Kitty)
- [x] `fab` (Kitty)
- [x] `filter` (Kitty)
- [x] `flow` (Kitty)
- [x] `flow-item` (Kitty)
- [x] `icon` (Kitty)
- [x] `inline-editable` (Kitty)
- [x] `input` (Kitty)
- [x] `input-date-picker` (Kitty)
- [x] `input-message` (Kitty)
- [x] `input-time-picker` (Kitty)
- [x] `label` (Kitty)
- [x] `link` (Kitty)
- [x] `list` (Kitty)
- [x] `list-item` (Kitty)
- [x] `list-item-group` (Kitty)
- [x] `loader` (Kitty)
- [x] `modal` (Kitty)
- [x] `notice` (Kitty)
- [x] `option` (Kitty)
- [x] `option-group` (Kitty)
- [x] `pagination` (Kitty)
- [x] `panel` (Kitty)
- [x] `pick-list` (Kitty)
- [x] `pick-list-group` (Kitty)
- [x] `pick-list-item` (Kitty)
- [x] `popover` (Kitty)
- [x] ~~`popover-manager`~~ (Kitty) **deprecated**
- [x] `progress` (Kitty)
- [x] `radio-button` (Kitty)
- [x] `radio-button-group` (Kitty)
- [x] `radio-group` (Kitty)
- [x] `radio-group-item` (Kitty)
- [x] `rating` (Kitty)
- [x] `scrim` (Kitty)
- [x] `select` (Kitty)
- [x] `shell` (Kitty)
- [x] `shell-center-row` (Kitty)
- [x] `shell-panel` (Kitty)
- [x] `slider` (Kitty)
- [x] `split-button` (Kitty)
- [x] `stepper` (Kitty)
- [x] `stepper-item` (Kitty)
- [x] `switch` (Kitty)
- [x] `tab` (Kitty)
- [x] `tab-nav` (Kitty)
- [x] `tab-title` (Kitty)
- [x] `tabs` (Kitty)
- [x] `tile` (Kitty)
- [x] `tile-select` (Kitty)
- [x] `tile-select-group` (Kitty)
- [x] `time-picker` (Kitty)
- [x] `tip` (Kitty)
- [x] `tip-group` (Kitty)
- [x] `tip-manager` (Kitty)
- [x] `tooltip` (Kitty)
- [x] ~`tooltip-manager`~ (Kitty) **deprecated**
- [x] `tree` (Kitty)
- [x] `tree-item` (Kitty)
- [x] `value-list` (Kitty)
- [x] `value-list-item` (Kitty)

</details>

**Comment by macandcheese** [comment]
Thanks for putting this together! 

I have no preference on content structure or verbiage as long as it is consistent, and anything that can be turned into metadata items, can be - like in the examples you mention above for read-only, and default values.

**Comment by driskull** [comment]
Did we discuss back-ticks? I see single and double quotes mentioned. 

We use these to highlight code in descriptions. It's nice to see them highlighted in markdown.

**Comment by geospatialem** [comment]
We did have some inclusions with the component names above. 

> * Components should not be in quotes, e.g. calcite-button instead of `calcite-button` (ticks do not render as inline code in the doc)

So they would be recognized as calcite-list-item over ``` `calcite-list-item` ``` or "calcite-list-item". 

The back-ticks were recommended for removal since they don't register in the docs. For instance on the [list item](https://developers.arcgis.com/calcite-design-system/components/list-item/#component-api-slots) doc page.

![screenshot of calcite-list-item with back-ticks in current dogs](https://user-images.githubusercontent.com/5023024/168169017-767a8b85-f1e2-4cf5-89ea-eb4c039a90b2.png)

**Comment by driskull** [comment]
Makes perfect sense. thanks for clarifying!

**Comment by benelan** [comment]
Kitty beat me to it. @macandcheese is there any way you can highlight backticks in the doc? If so then I agree using backticks would be nice

**Comment by driskull** [comment]
I'm wondering if the docs could just find/replace all backticks? Maybe use them to apply their own highlighting.

**Comment by benelan** [comment]
[Looks possible to me](https://github.com/ArcGIS/afd-calcite-documentation/blob/dev/src/components/component-readme/component-readme.tsx#L288). Maybe we could switch backticks with `code` tags. But I'll defer to @macandcheese on this.

**Comment by benelan** [comment]
If it is possible, should we switch from only `"` to only backticks? Or Use both depending on the situation, e.g. `"` for property values and backticks for property names and calcite-component tags?

**Comment by geospatialem** [comment]
> If it is possible, should we switch from only `"` to only backticks? Or Use both depending on the situation, e.g. `"` for property values and backticks for property names and calcite-component tags?

So far I've only seen one instance of need for the double quotes (`""`), and it was related to a deprecation. 

With the rarity (granted it's rare **so far**), leaning towards all refs using back-ticks (``` `` ```) if supported.

**Comment by macandcheese** [comment]
That would be a good identifier for us to place inside a code block on the docs site.

**Comment by macandcheese** [comment]
In the future we could think about allowing markdown and parsing it on the documentation site side

**Comment by benelan** [comment]
We could do it pretty easily with this https://github.com/remarkjs/react-markdown

**Comment by macandcheese** [comment]
Adding a note here to review slot descriptions for "(optional)" and ensure it's removed - all slots are optional (and if we want to put this, it would be better as metadata item): https://developers.arcgis.com/calcite-design-system/components/alert/#component-api-slots-title

**Comment by geospatialem** [comment]
@benelan Could you verify this issue related to our API style guide across components?

**Comment by benelan** [comment]
Sure! I'm putting another checklist here that I'll use as I go through the component docs

<details>
  <summary><h2>Verification progress</h2></summary>

- [ ] `accordion` 
- [ ] `accordion-item` 
- [ ] `action` 
- [ ] `action-bar` 
- [ ] `action-group` 
- [ ] `action-menu` 
- [ ] `action-pad` 
- [ ] `alert` 
- [ ] `avatar` 
- [ ] `block` 
- [ ] `block-section` 
- [ ] `button` 
- [ ] `card` 
- [ ] `checkbox` 
- [ ] `chip` 
- [ ] `color-picker` 
- [ ] `combobox` 
- [ ] `combobox-item` 
- [ ] `combobox-item-group` 
- [ ] `date-picker` 
- [ ] `dropdown` 
- [ ] `dropdown-group` 
- [ ] `dropdown-item` 
- [ ] `fab` 
- [ ] `filter` 
- [ ] `flow` 
- [ ] `flow-item` 
- [ ] `icon` 
- [ ] `inline-editable` 
- [ ] `input` 
- [ ] `input-date-picker` 
- [ ] `input-message` 
- [ ] `input-time-picker` 
- [ ] `label` 
- [ ] `link` 
- [ ] `list` 
- [ ] `list-item` 
- [ ] `list-item-group` 
- [ ] `loader` 
- [ ] `modal` 
- [ ] `notice` 
- [ ] `option` 
- [ ] `option-group` 
- [ ] `pagination` 
- [ ] `panel` 
- [ ] `pick-list` 
- [ ] `pick-list-group` 
- [ ] `pick-list-item` 
- [ ] `popover` 
- [ ] ~~`popover-manager`~~  **deprecated**
- [ ] `progress` 
- [ ] `radio-button` 
- [ ] `radio-button-group` 
- [ ] `radio-group` 
- [ ] `radio-group-item` 
- [ ] `rating` 
- [ ] `scrim` 
- [ ] `select` 
- [ ] `shell` 
- [ ] `shell-center-row` 
- [ ] `shell-panel` 
- [ ] `slider` 
- [ ] `split-button` 
- [ ] `stepper` 
- [ ] `stepper-item` 
- [ ] `switch` 
- [ ] `tab` 
- [ ] `tab-nav` 
- [ ] `tab-title` 
- [ ] `tabs` 
- [ ] `tile` 
- [ ] `tile-select` 
- [ ] `tile-select-group` 
- [ ] `time-picker` 
- [ ] `tip` 
- [ ] `tip-group` 
- [ ] `tip-manager` 
- [ ] `tooltip` 
- [ ] ~`tooltip-manager`~  **deprecated**
- [ ] `tree` 
- [ ] `tree-item` 
- [ ] `value-list` 
- [ ] `value-list-item` 

</details>

**Comment by geospatialem** [comment]
Closing in favor of #7071.
