### ISSUE TITLE
calcite-pick-list-item:  icon renders even though its value is set to null

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#4444]
### Actual Behavior

When using the calcite-pick-list-item with default values, the doc specifies the icon attribute is null, and that it wont render the icon slot, but Im seeing the slot still being rendered empty

### Expected Behavior

The icon slot should not be rendered

### Reproduction Sample

https://codepen.io/kevindoshier/pen/yLpdLeo

### Reproduction Steps

1. Load the link above
2. See the empty space before the label where the icon slot is being rendered

### Reproduction Version

beta.77

**Comment by macandcheese** [comment]
Related hit box issue: https://github.com/Esri/calcite-components/issues/3334

**Comment by benelan** [comment]
Closing as duplicate based on ☝️
