### ISSUE TITLE
Enhancement: Add Empty State slot to calcite-pick-list

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#4446]
### Description

Add a slot for developers to implement an empty state when a filter enabled `calcite-pick-list` returns no results. 

### Acceptance Criteria

- Add slot for an empty state to `calcite-pick-list`

### Which Component

`calcite-pick-list`

### Example Use Case

Developers may want to add info such as 'no items found' or actions to create additional options when no options match the search string.

**Comment by macandcheese** [comment]
Can you conditionally display an element when there are no results? 
It's confusing to use since the event comes from the internal filter, and you need to infer what items are displayed

Something like this: https://codesandbox.io/s/green-wave-bgulis?file=/src/App.js

**Comment by geospatialem** [comment]
With the `calcite-list` component refactor, we won't be adding additional enhancements to the `calcite-pick-list` at this time. The component refactor includes a filter which can listen for results.

The workaround from @macandcheese above has [a workaround](https://codesandbox.io/s/green-wave-bgulis?file=/src/App.js). 

Closing the issue for the above refactor for next month's release and workaround prior to the release.
