### ISSUE TITLE
Console error + rendering bug when `calcite-radio-button` does not have `checked` attr

### ISSUE THREAD

**Issue by jgibson02** [Esri/calcite-components#4462]
### Actual Behavior

This error is observed when using a `calcite-radio-button` without a `checked` attribute. I believe this line might be the cause since `this.checked` may be `undefined`.
https://github.com/Esri/calcite-components/blob/083d283caf719eed91cb1f5bd71b4584864b5e61/src/components/radio-button/radio-button.tsx#L409

![image](https://user-images.githubusercontent.com/5069711/165609789-be74980a-6010-424c-ad83-556b2ed98564.png)

### Expected Behavior

No call to `toString()` when undefined, perhaps `aria-checked` can fallback to `"false"`?

### Reproduction Sample

https://codesandbox.io/s/calcite-radio-button-checked-tostring-console-error-rjifui

### Reproduction Steps

1. Inspect the Codesandbox console after the calcite-radio-button renders

### Reproduction Version

beta.81

**Comment by jgibson02** [comment]
It might be particular to `calcite-components-react`, but I also noticed it with the `active` prop on `calcite-accordion-item`. Maybe an issue with all boolean props? Added an example for the Accordion to the codesandbox.

**Comment by driskull** [comment]
@jcfranco should we create a utility for these boolean props to string? Something that does `(!!this.myProp).toString()`?

Or maybe we can patch the JSX or get JSX to implement the above if the property is boolean?

**Comment by jcfranco** [comment]
> should we create a utility for these boolean props to string? Something that does (!!this.myProp).toString()?

Good idea.

@jgibson02 Just curious, did you recently switch to React 17? The React wrappers were recently updated to support v16+ (not just v16), so I'm wondering if this is something new or we just hadn't noticed. cc @benelan

**Comment by jgibson02** [comment]
> > should we create a utility for these boolean props to string? Something that does (!!this.myProp).toString()?
> 
> Good idea.
> 
> @jgibson02 Just curious, did you recently switch to React 17? The React wrappers were recently updated to support v16+ (not just v16), so I'm wondering if this is something new or we just hadn't noticed. cc @benelan

@jcfranco in our actual project we have not, we're on v16.13.1, but the codesandbox sample is on React 17

**Comment by geospatialem** [comment]
Verified with `0.23.0` ✔️ 

![calcite radio button with aria-checked fix](https://user-images.githubusercontent.com/5023024/167885857-89c8b8bd-efd5-484d-97df-6c7984d28046.png)
