### ISSUE TITLE
Calcite-Input cannot use "up" key to move cursor

### ISSUE THREAD

**Issue by tyanthony** [Esri/calcite-components#4469]
### Actual Behavior

In the `input` component, of type="textarea", using the arrow keys should move the cursor. All keys work correctly except for the "up" key, which currently does not move the cursor.

The same is for a number input - the up key does not increment the number.

### Expected Behavior

- [ ] The Up arrow key should move the cursor up.

This can be seen in the docs site as well.

### Reproduction Sample

https://codepen.io/tyleranthony/pen/MWQgegK?editors=100

### Reproduction Steps

1. Create a new Calcite Input of type="textarea"
2. Type in text so that there are multiple lines
3. Use the arrow keys to move the cursor
4. Notice that the "up" does not move the cursor up

### Reproduction Version

beta.81

**Comment by jcfranco** [comment]
@Elijbet Could you look at this one?

**Comment by geospatialem** [comment]
Verified in next 
⌨️ ⬆️ ✔️
