### ISSUE TITLE
color-picker color thumbs overflowing outside of component bounds

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#4492]
### Actual Behavior

If you have a scrolling container sized to the color-picker's dimension, it will cause scrolling if either the color field or hue slider thumb is on the edge.

### Expected Behavior

The color thumbs should not overflow their container.

### Reproduction Sample

https://codepen.io/jcfranco/pen/yLvNxgO?editors=1000

### Reproduction Steps

1. Open the above codepen
2. Notice the scrollbar

### Reproduction Version

1.0.0-next.456

**Comment by jcfranco** [comment]
FYI, I've got a fix for this in the works.

**Comment by geospatialem** [comment]
Verified on `1.0.0-beta.82`. 👍🏻 

![screenshot of color picker with no scrollbars present](https://user-images.githubusercontent.com/5023024/167875199-8c49aab1-4731-447f-8be0-5014dd0859b7.png)
