### ISSUE TITLE
2709

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#4526]

**Comment by driskull** [comment]
Mysterious issue :)

**Comment by Elijbet** [comment]
> Mysterious issue :)

Oh, sorry for the late notice, we're been gradually rolling out an invisibility cloak feature. :)

**Comment by benelan** [comment]
Not sure what happened here lol. Closing

**Comment by benelan** [comment]
Actually I think I may have accidently done this while messing with some Zenhub features
