### ISSUE TITLE
Alert: Add close button with auto-dismiss

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#4529]
### Description

On the calcite-alert, using the `auto-close` property will remove the close button. It would be nice to have an option to keep the close button when `auto-close` is present. The user may want to close the alert before the auto-dismiss-duration is over.

### Acceptance Criteria

Either keep the close button when `auto-dismiss` is enabled or add it as an option (maybe as another property).

### Which Component

calcite-alert

### Example Use Case

An alert with `auto-dismiss` is prompted saying your download is complete. The user sees the alert and wants to clear it because it is blocking other UI they want to interact with. However, they must wait until the duration completes. Adding a close button will make the experience less clunky.

**Comment by macandcheese** [comment]
@jmanke - This is referenced in this issue - https://github.com/Esri/calcite-components/issues/3338, could you give a plus one in that thread? I am going to close this as a duplicate.
