### ISSUE TITLE
Height of popover heading inconsistent when `dismissible` enabled

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#4537]
### Actual Behavior

For non-dismissible `calcite-popover` elements (`dismissible=false`), the height of its heading content-box is `46px`. For dismissible popovers, the height is `56px`.

### Expected Behavior

For dismissible popovers, the height of the heading content-box remains unchanged.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/popover/

### Reproduction Steps

1. Visit the doc page
2. Configure the example popover with a heading
3. Activate the popover and use dev tools to inspect the height of its heading
4. Configure the example popover as dismissible
5. Reactivate the popover and use dev tools to inspect the height of its heading

### Reproduction Version

1.0.0-beta.82

### Relevant Info

The padding built into the `m` scaled close action is causing it to stretch the height of the heading area. Adjusting to an `s` scaled action appears to correct the immediate issue.

The `calcite-modal` component exhibited a similar behavior which was (mostly?) corrected in https://github.com/Esri/calcite-components/issues/1707.

**Comment by Elijbet** [comment]
@benelan Do we have any new info on what is happening with the height in Windows for https://github.com/Esri/calcite-components/issues/1707 that I could use for this one? I'll assign it to myself since it's related.

**Comment by benelan** [comment]
Unfortunately I haven't had a chance to look into that yet. If you want to take over #1707 I'd be happy to help you with any Windows related testing

**Comment by benelan** [comment]
verified on beta.83
