### ISSUE TITLE
calcite-popopver: popovers open without being set to open

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#4539]
### Actual Behavior

This started with beta.82, beta.81 was fine.

If I don't use popover-manager and create several popovers that I manage myself a seemingly random popover opens automatically when the user clicks on the reference element, which in my case is the calcite-panel.

### Expected Behavior

popover only opens when I tell it to

### Reproduction Sample

https://codepen.io/driskull/pen/WNMGJNO?editors=1010

https://codepen.io/afreitag/pen/ExQgLYO

### Reproduction Steps

use effects, sketch or background color in Map Viewer

### Reproduction Version

beta.82

### Regression?

beta.81

**Comment by driskull** [comment]
The issue is that previously a user could not use the `calcite-popover-manager` and control the popover opening/closing themselves.

When we removed that component, we failed to add a way to opt out of it.

**Comment by driskull** [comment]
@jcfranco can we strategize a release fix plan for this? Likely will be a breaking change.

**Comment by AdelheidF** [comment]
looks good, tested with next.468

**Comment by AdelheidF** [comment]
I would think this is a breaking change for users, not only a feature. Or you could mark the install with beta.82 as a breaking change.

**Comment by driskull** [comment]
I'll defer to @jcfranco here. Thanks Adelheid.

**Comment by jcfranco** [comment]
If standalone popover usage was supported after the manager was introduced then it's a breaking change and we can update the changelog accordingly.

**Comment by benelan** [comment]
If standalone popover usage was supported after the manager was introduced then it's a breaking change and we can update the changelog accordingly.

> Will do

**Comment by driskull** [comment]
> If standalone popover usage was supported after the manager was introduced then it's a breaking change and we can update the changelog accordingly.

I don't think it was supported or advertised so maybe we don't need to mark it as breaking.
