### ISSUE TITLE
Custom Dropdown Width

### ISSUE THREAD

**Issue by tannerjt** [Esri/calcite-components#4549]
### Description

`calcite-dropdown` current [width](https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-width) property accepts `Scale` values (s, m, l).  The component width cannot be overridden without needing to access shadow DOM.  I'd like to request a new property `customWidth` or similar that can allow custom width values.

### Acceptance Criteria

Custom width can be provided as a property that determines width of calcite-dropdown.

### Which Component

calcite-dropdown

### Example Use Case

For reference, this is for a custom search widget using calcite-components.  I'd like the dropdown to match the width of my input:

<img width="484" alt="enhancement" src="https://user-images.githubusercontent.com/3883995/168209225-13f9855d-892f-4d2d-a153-09aa60fe2e0b.png">

**Comment by driskull** [comment]
I think it would be best if we updated the dropdown to take up its full container width by default, that might solve this issue. Maybe we can change scale to be undefined by default and take up full width?

> For reference, this is for a custom search widget using calcite-components. I'd like the dropdown to match the width of my input:

For accessibility, it might be better to use a `calcite-combobox` for this instead of a dropdown since the combobox uses the correct listbox aria role and has the correct keyboard navigation.

**Comment by tannerjt** [comment]
Thanks @driskull - I like the idea of defaulting to full container width if scale undefined.  I agree that `calcite-combobox` is the better option for accessibility.  That would be the preferred component for our needs, but I didn't see how I could manipulate the `calcite-input` inside of `calcite-combobox` to add the `clearable` and `icon` props.  With `calcite-combobox`, what do you think about adding the ability to customize the `calcite-input` or maybe make the `input` a custom slot?

**Comment by driskull** [comment]
@tannerjt you can now define your own width on the dropdown using CSS. Just make sure the `width` property isn't defined.

You can set the trigger to span the full width of the dropdown as well.

**Comment by tannerjt** [comment]
Awesome, thanks @driskull!

**Comment by geospatialem** [comment]
Closing this issue since custom dropdown width now possible via CSS. 👍🏻
