### ISSUE TITLE
Docs: Update old changelog entries.

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#4560]
### Description

*A follow-up to PR: #4496*

Review the revised events for name change and mark the ones below as internal.

```
- `calcite-accordion` - `calciteAccordionItemHasChanged` event has been renamed to `calciteAccordionChange`
- `calcite-accordion-item` - `calciteAccordionItemSelected` event has been renamed to `calciteAccordionItemSelect`
- `calcite-accordion-item` - `closeCalciteAccordionItem` event has been renamed to `calciteAccordionItemClose`
- `calcite-accordion-item` - `registerCalciteAccordionItem` event has been renamed to `calciteAccordionItemRegister`
- `calcite-dropdown-group` - `registerCalciteItemHasChanged` event has been renamed to `calciteDropdownItemChange`
- `calcite-stepper` - `calciteStepperItemHasChanged` event has been renamed to `calciteStepperItemChange`
- `calcite-stepper-item` - `registerCalciteStepperItem` event has been renamed to `calciteStepperItemRegister`
```

### Proposed Advantages

Changelog update.

### Which Component

Listed in the description.

**Comment by benelan** [comment]
Imo we shouldn't change the [`beta.28` changelog](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#v100-beta28---june-11th-2020), because that will imply that version `beta.29` uses these new names. If anything we should add it to the `beta.82` changelog.

**Comment by benelan** [comment]
Also, if none of these were documented, then it probably doesn't need to go into the changelog at all.

**Comment by Elijbet** [comment]
> Also, if none of these were documented, then it probably doesn't need to go into the changelog at all.

Ok, my bad. I misunderstood the requirement.
