### ISSUE TITLE
Regression with Stepper's `prevStep()`

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#4567]
### Actual Behavior

Navigating a stepper via its `prevStep()` method no longer swaps the active item's content into the stepper's body.

### Expected Behavior

Navigating a stepper via its `prevStep()` method should swap the active item's content into the stepper's body.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/gOvmvaw

### Reproduction Steps

1. Visit the code sample and notice the last stepper item is active.
2. Click the **Prev step** button and notice the previous step's header becomes active, but the stepper's body content remains unchanged.

### Reproduction Version

next.469

### Regression?

beta.81

**Comment by benelan** [comment]
Triaging to this sprint cc @jcfranco

**Comment by driskull** [comment]
I'll take this one since I broke it :)

**Comment by geospatialem** [comment]
Verified in `next.478`

![stepper content with prevstep function](https://user-images.githubusercontent.com/5023024/170562579-69c52247-4d6f-4438-b88a-b9c1314a2977.png)
