### ISSUE TITLE
Enhancement: input-date-picker validates & auto-corrects values while typing

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#4570]
### Description

When `min`,`max` are parsed in `calcite-input-date-picker` ,  values are validated & auto-corrected while user is typing if the value is outside of the range. This happen when the user is not yet tabbed out of the `input` element. 
 

### Acceptance Criteria

the validation & auto-correction needs to be disabled when user is typing while `input-date-picker` has the focus.

### Which Component

calcite-input-date-picker

### Example Use Case

Code pen :https://codepen.io/ANVESHMEKALA/pen/qBxrxyO?editors=1000 

Try entering `05/22/2022` in the input field and even before the user completes typing the value will be reseted to `min` value

**Comment by anveshmekala** [comment]
Need to revisit this issues as it effects both date-picker and input-date-picker. Holding off on development .

**Comment by eriklharper** [comment]
@geospatialem this has also been resolved by #5459.

**Comment by geospatialem** [comment]
Verified in `beta.98`.

![verify-validation-input-date-picker](https://user-images.githubusercontent.com/5023024/204912634-cce9d353-4aa6-464c-bd54-9c04836a7767.gif)
