### ISSUE TITLE
Mismatching Buddhist and Gregorian year in the Date picker with Thai language

### ISSUE THREAD

**Issue by Olga8614** [Esri/calcite-components#4571]
### Actual Behavior

When Thai language set, the Calendar picker displays Gregorian year instead of Buddhist

### Expected Behavior

The Buddhist year should be displayed for Thai language, because Thai has default Buddhist calendar

### Reproduction Sample

.

### Reproduction Steps

1. open devext.arcgis.com and sign in
2. change your user language to Thai
3.  go to My Contents, or any other page that is using calcite date picker
4. set some Start date and End date
5. observe that all Start date, End date, filter range and items creation dates are displaying with Buddhist year
6.  click Calendar picker and observe: it displays Gregorian year
![image](https://user-images.githubusercontent.com/29614798/168928958-2212b6a6-d98e-4636-8248-99bdb97610b3.png)

cc @ain

### Reproduction Version

devext.arcgis.com as of 05/17/2022

**Comment by annierm18** [comment]
https://jsbin.com/juceraraga/1/edit?html,output

**Comment by geospatialem** [comment]
Verified in beta.86

![verified-buddhist-calendar-with-thai-lang](https://user-images.githubusercontent.com/5023024/179622135-8ab01912-d3cd-401f-a098-94c4c4937140.png)
