### ISSUE TITLE
Number input incorrect rounding behavior for long decimals

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#4578]
### Actual Behavior

For the number input, there seems to be a maximum allowable number of decimal places, but the behaviour seems inconsistent depending on the starting number and the decimal value. In some cases it actually replaces what the user would have typed or adds an extra number to the end.

You can continuously enter decimal values <6 without any weird rounding occurring.

### Expected Behavior

It should not round decimals unless the developer specifies the behavior. It should additionally not be adding numbers to the end of the decimal or replacing user input with random numbers in long decimals

### Reproduction Sample

https://codepen.io/eborgen/pen/YzeVwdb?editors=1000

### Reproduction Steps

The codepen has 3 examples, they are labeled in the pen:

1. Continuously adding a decimal value of 9 eventually converts the value to the next largest whole number
2. Continuously adding decimal values >5 eventually causes the digit to increase by 1 for a bit, before continuing to allow that number again
3. Setting a value with many decimal values >5 causes an extra digit to be appended

### Reproduction Version

beta.82

### Regression?

unknown

**Comment by benelan** [comment]
Looks like this is happening when we convert the string into a number because 
```js
Number("4.9999999999999999") === 5 // true
````

**Comment by amring1** [comment]
This doesn't just occur with decimal values. Typing 9999999999 eventually turns into 10000000000000000

**Comment by benelan** [comment]
@ethanbdev I have a PR for this, is there a specific decimal precision you need for your use case? I currently have it at 100 decmial places.

**Comment by amring1** [comment]
> @ethanbdev I have a PR for this, is there a specific decimal precision you need for your use case? I currently have it at 100 decmial places.

I think that should be plenty for us.

**Comment by geospatialem** [comment]
Verified on `next` ✔️ 

![verified decimal fix](https://user-images.githubusercontent.com/5023024/173392100-a00e9c32-effb-4987-9d10-5bd2f7003f6f.png)
