### ISSUE TITLE
Popover fails to open on mobile devices

### ISSUE THREAD

**Issue by juliannaeapicella** [Esri/calcite-components#4582]
### Actual Behavior

When I attempt to open a popover while simulating a mobile device in Chrome DevTools, the popover does not open on certain devices, although the button appears to be clicked.

Before:
<img width="194" alt="Screen Shot 2022-05-18 at 4 45 26 PM" src="https://user-images.githubusercontent.com/42875581/169152702-ab67c1cd-6ae9-4440-b494-819ad50cc290.png">

After:
<img width="215" alt="Screen Shot 2022-05-18 at 4 45 01 PM" src="https://user-images.githubusercontent.com/42875581/169152649-126ad9c7-f531-467a-a82f-2fda3807e8c8.png">

### Expected Behavior

The popover should appear regardless of device.

### Reproduction Sample

https://codepen.io/tannerjt/pen/eYVWdQe?editors=100#unsupported-modal

### Reproduction Steps

1. Open DevTools console
2. Click "Toggle device toolbar"
3. Select a device and try to open the popover (iPhone XR, Samsung Galaxy S20 Ultra, iPad Air, iPad Mini, Surface Pro 7, Samsung Galaxy A51/71, Nest Hub, Nest Hub Max)
4. Observe that the popover does not appear

### Reproduction Version

beta.81

### Relevant Info

Observed with the following dimensions:
- iPhone XR
- Samsung Galaxy S20 Ultra
- iPad Air 
- iPad Mini
- Surface Pro 7
- Samsung Galaxy A51/71
- Nest Hub
- Nest Hub Max

Not sure if this is exclusive to Chrome dev tools or an issue on all of the listed physical devices as well.

**Comment by macandcheese** [comment]
Hi @juliannaeapicella - We were only able to replicate this in Chrome DevTools while zoomed to anything less or more than 100%. Also checked on a physical iPhone and was unable to replicate the behavior at a zoom level above 100%. Could you check to see if setting DevTools size to 100% works for you?

**Comment by juliannaeapicella** [comment]
@macandcheese After verifying, the issue does seem to be tied to the zoom level rather than a particular simulated device. Is that a known issue?

**Comment by juliannaeapicella** [comment]
@macandcheese If this is the case, what do you think should be done with this bug?

**Comment by macandcheese** [comment]
@benelan thoughts? Unless we can repro outside dev tools / codepen combo - seems to be outside the scope of what we can control?

**Comment by benelan** [comment]
> Unless we can repro outside dev tools / codepen combo - seems to be outside the scope of what we can control?

Agreed. I'm closing this issue for now; if we do find out that it affects actual mobile devices we can reopen it.
