### ISSUE TITLE
Slotted footer content doesn't align properly in Card

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#4603]
### Actual Behavior

Slotting in various kinds of elements like `button`, `dropdown` and even just plain divs into the `footer-leading` and `footer-trailing` slots with a fixed height to match the other elements results in vertical alignment offsets.

![image](https://user-images.githubusercontent.com/821864/169591866-8e5ec1c0-9e50-4caa-bd2c-86b7a7f786dd.png)

### Expected Behavior

Elements slotted into the footer slots should vertically align, especially if they are all the same dimension in height.

### Reproduction Sample

https://codepen.io/eriklharper/pen/vYdZRYG?editors=1000

### Reproduction Steps

Create a calcite-card component and slot a bunch of different kinds of inline elements with the same height dimension in the `footer-leading` and `footer-trailing` slots.  Notice that some of them don't vertically align with others.

### Reproduction Version

1.0.0.beta.61

### Regression?

beta.61 is the last working version where calcite-* components were aligned properly, but even in that version standard divs are out of alignment when they are equal in height.

**Comment by geospatialem** [comment]
Verified on beta.90
