### ISSUE TITLE
Modal has `firstFocus` property documented but not implemented

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#4613]
### Description

The `firstFocus` property is listed in the [readme docs](https://github.com/Esri/calcite-components/tree/master/src/components/modal#properties) and [as a prop in modal.tsx](https://github.com/Esri/calcite-components/blob/master/src/components/modal/modal.tsx#L88), but it is not used anywhere. Seems like it should either be removed or the functionality should be implemented.

It's also documented in the developers website: https://developers.arcgis.com/calcite-design-system/components/modal/#component-api-properties-firstFocus

### Which Component

calcite-modal

**Comment by jcfranco** [comment]
@noahmulfinger Great catch. 

@benelan @geospatialem @driskull we should probably drop this prop. ✋🎤

**Comment by driskull** [comment]
drop it! Agreeed

**Comment by benelan** [comment]
Verified on `beta.83`
