### ISSUE TITLE
[Combobox] Improve placeholder display / add support for placeholder icon

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4629]
### Description

The current implementation of the placeholder text leads to a weird space when there are icons present in the combobox items.

Current functionality:
<img width="190" alt="Screen Shot 2021-10-27 at 12 19 12 PM" src="https://user-images.githubusercontent.com/4733155/139132557-92d2e131-539b-400f-96f4-40c89504e5f5.png">
<img width="190" alt="Screen Shot 2021-10-27 at 12 19 19 PM" src="https://user-images.githubusercontent.com/4733155/139132554-7d01b133-8664-49f4-9ea2-3c1e8d6b0d65.png">
<img width="190" alt="Screen Shot 2021-10-27 at 12 19 27 PM" src="https://user-images.githubusercontent.com/4733155/139132551-1441f2de-7be6-4582-826a-369131f5eecb.png">

### Acceptance Criteria

We should:
- Accept a new `placeholder-icon` property to set a default icon.
- If `placeholder-icon` is not provided, left-align the placeholder text to remove the awkward space.

### Relevant Info

Breakout from https://github.com/Esri/calcite-components/issues/3074.

### Which Component

Combobox

### Example Use Case

There are often times when having a prompt icon adjacent to the placeholder text could be useful. If a placeholder icon is not desired, the current empty space between the edge of the input and the placeholder text is not desirable.

**Comment by MonikaKanduri4525** [comment]
I would need the icon placeholder for the VTSE product. I'm using Combobox for folders and tags search (this is part of a new screen in VTSE). Could you please prioritize this issue?


<img width="490" alt="Screen Shot 2022-05-26 at 3 29 37 PM" src="https://user-images.githubusercontent.com/79884938/170590042-aa077514-19cf-4625-bcfc-69beb7d11426.png">

**Comment by macandcheese** [comment]
@benelan could we bump priority of this? Should be a reasonably easy add.

**Comment by benelan** [comment]
@macandcheese can you help verify that this is the intended spacing when there is no `placeholder-icon`?
![image](https://user-images.githubusercontent.com/10986395/181658862-d3293118-5b36-4f42-ab4f-bdbef7fc2682.png)
https://codepen.io/benesri/pen/VwXrMwR

**Comment by macandcheese** [comment]
Two pieces of feedback on that: It seems the example shown should use the same spacing as input :
![Screen Shot 2022-07-28 at 5 54 38 PM](https://user-images.githubusercontent.com/4733155/181660854-c7ec6b1d-babd-44d3-8125-940d50140459.png)

It seems like there is extra padding on the left - and you can see there is a cursor change at the left side that coincides with that extra space.

I would also imagine the alignment between the value / placeholder with icon, and the spacing of the combobox items (when not nested), would align:
![Group 23](https://user-images.githubusercontent.com/4733155/181660982-d617917b-0545-476e-8233-dbbad0c1bbe3.png)

cc @ashetland for visibility.

**Comment by benelan** [comment]
Yeah I agree with that feedback. Assigning back to dev for some adjustments. Thanks Adam!

**Comment by benelan** [comment]
@anveshmekala - let me know if you don't have cycles to work on this, I can put it up for grabs in the current milestone. I also updated the codepen with the examples from Adam's feedback - https://codepen.io/benesri/pen/VwXrMwR

**Comment by benelan** [comment]
@macandcheese one more question - when a `combobox` has a `placeholder-icon` and the selected `combobox-item` has an `icon`, which icon should be displayed next to the placeholder text?

 It is currently the item's icon, which is how it behaves when the combobox does not have a `placeholder-icon`. However, should the `placeholder` and `placeholder-icon` props to be "in sync"?
![image](https://user-images.githubusercontent.com/10986395/181664727-edb5161c-61bd-43e7-a299-578df796e53e.png)

**Comment by anveshmekala** [comment]
> @anveshmekala - let me know if you don't have cycles to work on this, I can put it up for grabs in the current milestone. I also updated the codepen with the examples from Adam's feedback - https://codepen.io/benesri/pen/VwXrMwR

I have some bandwidth to fix this.

**Comment by macandcheese** [comment]
I agree with @benelan - persisting the icon when the entered characters (or placeholder text) is there may be confusing - using the placeholder icon (or no icon if there is no placeholder icon), would I think avoid that. cc @ashetland

**Comment by anveshmekala** [comment]
`<input/>` inside combobox is a native one which is why there is a difference in spacing with `calcite-input` even after the fix [5073 ](https://github.com/Esri/calcite-components/pull/5073). 

We can replace `input` in combobox with `calcite-input` unless there is a known limitation that prefers the native one.  OR we can add the missing border to input in Combobox but there could be a chance of misalignment if calcite-input changes.
Thoughts ? @macandcheese 

cc: @benelan

**Comment by macandcheese** [comment]
Ideally the spacing is the same, in that example the bullet dot is visually misaligned. IMO it would make sense to push it out to match the item with icon. When there is an icon and item is selected, I do find it weird the dot isn’t present, even if it pushes the icon over, it could still be aligned to the gutter of icon / bullet.

When selection mode is none (no visual), we don’t need the space.

**Comment by macandcheese** [comment]
Ideally the spacing is the same, in that example the bullet dot is visually misaligned. IMO it would make sense to push it out to match the item with icon. When there is an icon and item is selected, I do find it weird the dot isn’t present, even if it pushes the icon over, it could still be aligned to the gutter of icon / bullet.

**Comment by geospatialem** [comment]
Given the context of alignment to accommodate `combobox` with and without icons (_info below_)... 

@jcfranco **Should we proceed with closing and creating a new issue with this context or re-assigning this issue to the current or next sprint to tackle?** Fairly low in prioritization, but seems pertinent for the 1.0.0 release.

> Ideally the spacing is the same, in that example the bullet dot is visually misaligned. IMO it would make sense to push it out to match the item with icon. When there is an icon and item is selected, I do find it weird the dot isn’t present, even if it pushes the icon over, it could still be aligned to the gutter of icon / bullet. We could also the icon the color of the dot to make it easier to tell when it’s selected.

The recommended fix would include:
- [ ] Spacing the selection indicator in alignment with the icon (when present)
- [ ] Spacing the text in alignment regardless of icon presenc

**Comment by geospatialem** [comment]
Recirculating to a future sprint to meet the additional items in the comment above.

cc @jcfranco

**Comment by anveshmekala** [comment]
> The recommended fix would include:
> 
> * [ ]  Spacing the selection indicator in alignment with the icon (when present)
> * [ ]  Spacing the text in alignment regardless of icon present

Added fix for aligning selector indicator with the icon when present and text aligns regardless of icon.  Do we need to add selector indicator for items with icons or would that be a separate discussion ? 

cc @macandcheese

**Comment by macandcheese** [comment]
I think I'd expect it to also have in indicator, like dropdown, but cc @ashetland @SkyeSeitz for final design. 
<img width="266" alt="Screen Shot 2023-01-12 at 4 57 50 PM" src="https://user-images.githubusercontent.com/4733155/212212702-7649576f-2372-4936-8272-317c4a6e518b.png">

**Comment by SkyeSeitz** [comment]
> I think I'd expect it to also have in indicator, like dropdown, but cc @ashetland @SkyeSeitz for final design. <img alt="Screen Shot 2023-01-12 at 4 57 50 PM" width="266" src="https://user-images.githubusercontent.com/4733155/212212702-7649576f-2372-4936-8272-317c4a6e518b.png">

Yup. 100% agree here.

**Comment by anveshmekala** [comment]
> > I think I'd expect it to also have in indicator, like dropdown, but cc @ashetland @SkyeSeitz for final design. <img alt="Screen Shot 2023-01-12 at 4 57 50 PM" width="266" src="https://user-images.githubusercontent.com/4733155/212212702-7649576f-2372-4936-8272-317c4a6e518b.png">
> 
> Yup. 100% agree here.

Can i get a Figma design for this one as matching with dropdown is bit of an issue with difference in padding for `dropdown-item` compared to `combobox-item` .

**Comment by geospatialem** [comment]
The original issue has been addressed above in the [following Codepen](https://codepen.io/ANVESHMEKALA/pen/NWBgLgv). A new issue, 6287 was created to address the component's indicator icon when children have accompanying icons.

### placeholder image:
![image](https://user-images.githubusercontent.com/5023024/212438776-6974ba24-25b5-435e-86ed-7abe1ef6a0fd.png)


### no placeholder image (left-align):
![image](https://user-images.githubusercontent.com/5023024/212438959-ba4a220d-e38c-4e88-87fe-7f615bc79fee.png)
