### ISSUE TITLE
[1.0 Release Cleanup] Date

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#463]
Breakout issue from https://github.com/Esri/calcite-components/issues/97

#### calcite-date 
- [x] change `showCalendar` to `active`
- [x] add `scale` prop ["s", "ml", "l" values] which sizes input/calendar to match buttons/inputs

#### calcite-date

- [x] Use generics for `calciteDateChange` event, rather than extending `EventEmitter`

#### calcite-date-month

- [x] Use generics for `calciteActiveDateChange`, rather than extending `EventEmitter`
- [x] Use generics for `calciteDateSelect`, rather than extending `EventEmitter`

#### calcite-date-month-header

- [x] Use generics for `calciteActiveDateChange`, rather than extending `EventEmitter`

**Comment by paulcpederson** [comment]
Will be in next release.
