### ISSUE TITLE
calcite-tooltip: line breaks added with bold text

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#4631]
### Actual Behavior

If the tooltip string contains a word with <b> tags it puts that word on its own line

### Expected Behavior

no line breaks for bold word

### Reproduction Sample

https://codepen.io/afreitag/pen/KKQZmXP

### Reproduction Steps

Open and click on link

### Reproduction Version

beta.82

**Comment by driskull** [comment]
Looks like a CSS issue with the popover's internal container. Its displaying as a flex column.

**Comment by driskull** [comment]
@asangma or @macandcheese can you advise on this one. I'm not sure if flex-col is needed here: https://github.com/Esri/calcite-components/blob/master/src/components/tooltip/tooltip.scss#L10

Its making `<span>` inside the tooltip display as block. Do we need the flex-col?

**Comment by benelan** [comment]
verified on next
