### ISSUE TITLE
[1.0 Release Cleanup] Dropdown

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#464]
Breakout issue from https://github.com/Esri/calcite-components/issues/97

#### calcite-dropdown
- [x] add `calciteDropdownSelect` event when the selected item changes
- [ ] ~make the detail the selected item element (or it's value?)~ 👇 
- [ ] ~add type information to detail~ -> https://github.com/Esri/calcite-components/issues/470#issuecomment-638298088

#### calcite-dropdown-group

- [x] `calciteDropdownItemHasChanged` => `calciteDropdownItemChange`
- [x] `registerCalciteDropdownGroup` => `calciteDropdownGroupRegister`
- [ ] ~Type all event details~ -> https://github.com/Esri/calcite-components/issues/470#issuecomment-638298088

#### calcite-dropdown-item
- [x] `calciteDropdownItemSelected` => - `calciteDropdownItemSelect`
- [x] `closeCalciteDropdown` => `calciteDropdownClose`
- [x] `registerCalciteDropdownItem` => - `calciteDropdownItemRegister`

**Comment by jcfranco** [comment]
Addressed by #642 & #643.
