### ISSUE TITLE
[1.0 Release Cleanup] Modal

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#466]
Breakout issue from https://github.com/Esri/calcite-components/issues/97

### Props
- [x] change size to `scale`, this will only update the padding of the chrome around the modal?
- [x] add `width` prop which sets width of modal?
- [x] change `closeLabel` to `intlClose`

### Events

- [x] Ensure events have typed detail

**Comment by paulcpederson** [comment]
part of beta.32
