### ISSUE TITLE
calcite-panel: menus that overflow the panel header are cut off

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#4682]
### Actual Behavior

menus that overflow the panel header are cut off

### Expected Behavior

Menus are displayed below or above the header of the panel component without being cut off.

### Reproduction Sample

https://codepen.io/COV-GIS/pen/VwyGmZb

### Reproduction Steps

1. Hover over a header action and the tooltip is behind the panel's content.

### Reproduction Version

1.0.0-beta.82

### Relevant Info

https://github.com/Esri/calcite-components/pull/4182

**Comment by benelan** [comment]
verified on beta.83
