### ISSUE TITLE
[Pick/Value List] - Remove / Privatize "icon" property

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4695]
### Description

The Pick / Value list item components have an `icon` prop that accepts a set of values : https://github.com/Esri/calcite-components/blob/8a00bbbf0ac700a3fed09b1bd03a41f4f079aba8/src/components/pick-list/resources.ts#L5

However, it doesn't seem like providing this attribute to the component results in any visual change. After chatting with @asangma - it seems like we should audit this property to see if 1) it's needed at all, or 2) if it is needed, if it can be made internal somehow.

This was initially brought up as an implementation note while translating the above components to Figma, but after looking at this it seems like something we should clean up.

### Acceptance Criteria

"icon" property on these components is removed / privatized / documented in a way that makes it understandable.

### Which Component

Pick / Value list item.

**Comment by driskull** [comment]
@macandcheese can we close this one? This is already privatized in `calcite-list`

**Comment by macandcheese** [comment]
Sure as long as issue linked above is not valid anymore either. 👍
