### ISSUE TITLE
Component: Chips

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#47]
It'd be nice to provide what Material Design offers: https://material.io/design/components/chips.html

Optional props for: icon, color, "canClose" / deselect (emit a close event). This would be useful for data table "currently selected", filter dropdowns, etc. 

Consider allowing a Calcite-avatar (when built) / Calcite-icon to the left of text.

**Comment by bstifle** [comment]
![chips examples](https://user-images.githubusercontent.com/14083530/73789322-6aed0f80-4753-11ea-8368-25d305e9d49e.png)
![chip designs](https://user-images.githubusercontent.com/14083530/73789323-6b85a600-4753-11ea-8339-52a56d782077.png)

**Comment by macandcheese** [comment]
Installed
