### ISSUE TITLE
[1.0 Release Cleanup] Radio Group

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#470]
Breakout issue from https://github.com/Esri/calcite-components/issues/97

#### calcite-radio-group

- [x] Add a detail with the value of the selected radio group item

#### calcite-radio-group-item

- [ ] Add a detail with the value of the selected radio group item

**Comment by jcfranco** [comment]
> Add a detail with the value of the selected radio group item

@paulcpederson @macandcheese For individual items, `calciteRadioGroupItemChange` is emitted when the item is checked/unchecked. In that case, would you still expect the value to be emitted or `checked`?

**Comment by paulcpederson** [comment]
@jcfranco good question. I'm not totally sure. Does the event pass through the target? If so, are there `checked` and `value` properties on the target?

**Comment by jcfranco** [comment]
>  Does the event pass through the target?

Could you expand on that? I'm not sure what that means. 😅

**Comment by paulcpederson** [comment]
Sorry I worded that weirdly. I mean if somebody uses:

```js
const item = document.querySelector("calcite-radio-group-item");

item.addEventListener("calciteRadioGroupItemChange", (e) => {
  // can I get checked and value like this?
  console.log(e.target.checked, e.target.value)
});
```

**Comment by jcfranco** [comment]
Got it. Yep, that should work. Although, `currentTarget` would be preferable for IE11 cases.

**Comment by jcfranco** [comment]
Per our discussion, closing this issue since these props can be accessed via the event's `target`/`currentTarget`.
