### ISSUE TITLE
[1.0 Release Cleanup] Slider

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#471]
Breakout issue from https://github.com/Esri/calcite-components/issues/97

### Props
- [ ] `minLabel` => `intlLabelMin`
- [ ] `maxLabel` => `intlLabelMax`

### Events
- [ ] Add useful event detail to `calciteSliderUpdate` event (ie, value for single select or min + max for range slider)

**Comment by paulcpederson** [comment]
These strings don't have defaults, and aren't really generic like "close". As such I don't think this needs to be updated. 
The slider state can be accessed on the event target at `value` or `minValue` and `maxValue` for a range slider.
