### ISSUE TITLE
Slider handle misaligned if browser default font is adjusted

### ISSUE THREAD

**Issue by gsoosalu** [Esri/calcite-components#4721]
### Actual Behavior

Calcite slider's handle appears below or above the slider line: 
![image](https://user-images.githubusercontent.com/85623288/173317041-6b5ddd14-3429-4a8c-af7a-3211c425aa80.png)
![image](https://user-images.githubusercontent.com/85623288/173317270-2f6682ac-8bfe-4b26-9287-977d8a82e314.png)

### Expected Behavior

Slider's handle should be in the middle of the line
![image](https://user-images.githubusercontent.com/85623288/173317382-480081da-2304-4f7b-b52f-8d2c6446296f.png)

### Reproduction Sample

https://developers.arcgis.com/javascript/latest/sample-code/widgets-shadow-cast/live/

### Reproduction Steps

1. Change in browser setting the font size to either small or large. Screenshot from Chrome:
![image](https://user-images.githubusercontent.com/85623288/173316634-74f73bae-4b30-4bbd-9a87-5f082a8817d2.png)

1. Open JS API sample: https://developers.arcgis.com/javascript/latest/sample-code/widgets-shadow-cast/live/
2. Open color-picker
3. The opacity slider's handle is misaligned

This also appears when enabling  in the Calcite storybook: 
https://esri.github.io/calcite-components/?path=/story/components-controls-slider--single-value

### Reproduction Version

beta.82

### Relevant Info

MacOS and Windows
Chrome 102.0.5005.115
Firefox 101.0.1

**Comment by driskull** [comment]
Seems like the current positioning of the handle is based on a fixed offset size. That would need to change to be relative instead of fixed.

**Comment by geospatialem** [comment]
Hi @gsoosalu, thanks for reaching out. We plan to address to our February release.

**Comment by geospatialem** [comment]
Verified on [Storybook](https://esri.github.io/calcite-components/?path=/story/components-controls-slider--simple) and in `1.0.8-next.1`.

![image](https://user-images.githubusercontent.com/5023024/221719945-1e621f51-e162-475a-bbe5-6dfbcab29643.png)
