### ISSUE TITLE
calcite-input overflow text does not re-align left onfocusout (Firefox)

### ISSUE THREAD

**Issue by tannerjt** [Esri/calcite-components#4726]
### Actual Behavior

Text that is longer than the `caclite-input` width will shift to the start of the input when focus is removed in Chrome and Safari.  For example, in the screenshot below, when I click outside of the input in Chrome, I'm able to see the start of my long input string.

<img width="783" alt="chrome" src="https://user-images.githubusercontent.com/3883995/173442783-56256c71-f954-4eb9-bbc5-6c8493dc1534.png">

However, in Firefox, when I click outside of the input, I am not observing the same behavior.

<img width="682" alt="firefox" src="https://user-images.githubusercontent.com/3883995/173443210-892fa21d-10ad-49f9-b9da-8fc2dc431c30.png">

### Expected Behavior

I would expect that when I click outside of the input, the text would be shifted so I could see the beginning of my input string.  For Firefox, I'm seeing the end of my string.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input/

### Reproduction Steps

1. Add input to `calcite-input` that is longer than the input width
2. Click out of the input
3. Observe different functionality in Firefox vs Chome / Safari

### Reproduction Version

v1.0.0-next.490

### Relevant Info

This issue is limited to Firefox.  I can also observe this inconsistency on native `<input />` elements. 

I can resolve the issue for an `<input />` by using `<input selector>.setSelectionRange(0,0)`, however in my component work, I can only affect `calcite-input` by reaching into the ShadowDOM.

**Comment by benelan** [comment]
@tannerjt we discussed this and decided to maintain the native functionality here. I suggest creating a Mozilla issue or bumping an existing one, e.g.
- https://bugzilla.mozilla.org/show_bug.cgi?id=860329
- https://bugzilla.mozilla.org/show_bug.cgi?id=1442956
