### ISSUE TITLE
calcite-input initial value set as 'undefined' without the "value" attr/prop present

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#4762]
### Actual Behavior

If `calcite-input` is added without a `value` attr/prop present the value is listed as `undefined`. The [docs site](https://developers.arcgis.com/calcite-design-system/components/input/#component-api-properties-value) also lists `""` as the default value.

### Expected Behavior

Similar to native HTML behavior. Where with or without the `value` prop/attr present on the component, the `calcite-input` would have a value of `""` unless a value is specified.

### Reproduction Sample

https://codepen.io/geospatialem/pen/gOvEePd?editors=1011

### Reproduction Steps

1. Open the [Codepen](https://codepen.io/geospatialem/pen/gOvEePd?editors=1011)
2. Enable the Console
3. Watch the input values on load for:
    - Native `input` (**result**: `""`)
    - `calcite-input` without a `value` attribute present  (**result**: `undefined`)
    - `calcite-input` with a `value` attribute (**result**: `""`)

### Reproduction Version

beta.83

### Relevant Info

- Windows 10 - Chrome, Firefox
- Mac OS 12 - Chrome, Safari

**Comment by jcfranco** [comment]
I believe this is working as expected. For lazy-loaded components (`dist`), they need to hydrate before their props are properly initialized. Basically, they start as plain HTMLElements and get upgraded as soon as their implementation is loaded and defined in the browser (see  [example](https://codepen.io/jcfranco/pen/jOzwKrp?editors=1011)).

**Comment by jcfranco** [comment]
Wanted to share one more observation, it appears that the loaded component 'shell' has setters wired up based on the type. This would explain why the appropriate value type gets assigned when setting an 'empty attribute' (see [example](https://codepen.io/jcfranco/pen/xxWrzLw?editors=1011)).

**Comment by geospatialem** [comment]
> I believe this is working as expected. For lazy-loaded components (`dist`), they need to hydrate before their props are properly initialized.

Gotcha, thanks for the explanation and resources. 👍🏻 

@jcfranco Is there anything doc-wise we could add in for users, in particular mentioning lazy loading and its benefits? Not sure on placement, but perhaps on the [FAQ](https://developers.arcgis.com/calcite-design-system/faq) page?

Maybe its overkill, but this tripped me up a bit, so wondering if it could impact others as well.

**Comment by jcfranco** [comment]
> Is there anything doc-wise we could add in for users, in particular mentioning lazy loading and its benefits? Not sure on placement, but perhaps on the [FAQ](https://developers.arcgis.com/calcite-design-system/faq) page?

That is an excellent idea! This has come up a few times where users expect 1:1 behavior w/ native elements and even between our lazy-loaded & tree-shakeable components bundle. cc @benelan

**Comment by geospatialem** [comment]
Closing this issue as its not an issue, and will follow up on supporting documentation regarding lazy loading. Thanks again for the background, @jcfranco!
