### ISSUE TITLE
Focus not trapped (et al.) by modal if initially `active`

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#4764]
### Actual Behavior

If a `<calcite-modal>` component is rendered with an `active` attribute, it behaves differently than if `active` is enabled later:
1. Modal appears immediately instead of animating in (possibly expected?)
2. The modal's `calciteModalOpen` event never fires
3. Focus is not trapped by the modal

### Expected Behavior

If a `<calcite-modal>` component is rendered with an `active` attribute, it behaves the same as when `active` is enabled later.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/YzegaoB?editors=1011

### Reproduction Steps

1. Visit the sample and notice:
   1. The modal does not animate in
   2. `calciteModalOpen` is not logged to the console
   3. The **Back** button does not gain focus

### Reproduction Version

beta.83

**Comment by anveshmekala** [comment]
The focus trapping and `calciteModalOpen` event trigger issues are resolved with `beta.93`. Could you please verify @nwhittaker.  Thanks.

**Comment by nwhittaker** [comment]
Verifying the code sample exhibits the expected behavior with `beta.93` -- thanks!
