### ISSUE TITLE
Selector `calcite-input[autofocus]` not matched

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#4765]
### Actual Behavior

Given a `<calcite-input>` element with the `autofocus` attribute enabled, the `calcite-input[autofocus]` selector never matches the element.

### Expected Behavior

Given a `<calcite-input>` element with the `autofocus` attribute enabled, the `calcite-input[autofocus]` selector matches the element.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/dydreNL?editors=1011

### Reproduction Steps

1. Visit the sample
2. Open the **Console** and notice a value of `null` is logged instead of the `calcite-input` element

### Reproduction Version

beta.83

### Relevant Info

It's possible other attributes on this, or other elements, exhibit the same behavior.

**Comment by jcfranco** [comment]
@nwhittaker Can you clarify whether you are using the attribute or the property? Styling should work via the attribute: https://codepen.io/jcfranco/pen/NWYgvdd?editors=1111

Also, could you provide more info on your use case?

**Comment by nwhittaker** [comment]
@jcfranco, I think you're right, this should be working as expected. I think my confusion was compounded by a couple things:
1. A workaround in app code that cleared the `autofocus` attribute. This was working around a now-fixed Safari bug where it ignored the `FocusOptions.preventScroll` option.
2. Autofocusing not working correctly in Codepen (at least for me) due to a security restriction: `Blocked autofocusing on a <calcite-input> element in a cross-origin subframe.`

Thanks for taking a look and verifying the correct behavior.

>Also, could you provide more info on your use case?

When dynamically rendering a layout in Ember that contains an `autofocus` element, we need to manually focus it. Finding the element via an `[autofocus]` selector was handiest.
