### ISSUE TITLE
[Stepper] "Grid" is not valid value for layout property

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4766]
### Actual Behavior

Layout property has a valid value of "grid" - but that is not applicable for Stepper.

I think when the local types were updated to be sourced from the new shared interface, we never excluded "grid". 

We should extract just "horizontal" and "vertical" from https://github.com/Esri/calcite-components/blob/6847f57359897972b002bb5f9377fb4c6c3d5a4f/src/components/interfaces.ts#L6

### Expected Behavior

"grid" is not a valid value of "layout".

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/YzegLQm?editors=100

### Reproduction Steps

Codepen.

### Reproduction Version

83

**Comment by geospatialem** [comment]
Verified on beta.90
