### ISSUE TITLE
[Pick List Group] Incorrect display of `heading` when `heading-level` is set

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4768]
### Actual Behavior

The Pick List Group is not correctly setting styles for header elements:

The Pick List Group heading styles are scoped to `h3` : https://github.com/Esri/calcite-components/blob/6847f57359897972b002bb5f9377fb4c6c3d5a4f/src/components/pick-list-group/pick-list-group.scss#L20

The List Item Group styles apply to any of the conditionally-rendered heading elements: https://github.com/Esri/calcite-components/blob/6847f57359897972b002bb5f9377fb4c6c3d5a4f/src/components/list-item-group/list-item-group.scss#L5 
<img width="730" alt="Screen Shot 2022-06-16 at 3 25 16 PM" src="https://user-images.githubusercontent.com/4733155/174188349-a652fcba-af2c-4bd4-a1b4-45e16c596bf2.png">

### Expected Behavior

The visual styling of the heading text is not changed when `heading-level` value changes.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/XWZGqxy?editors=1000

### Reproduction Steps

View style differences on Codepen.

### Reproduction Version

83

**Comment by macandcheese** [comment]
@mitc7862 @asangma - Aside from the bug above for the changing of sizes, none of the group title styles from the pick list matches that of the regular list.

Can we make these more consistent? I don't have a preference but it seems like these could be more aligned - thoughts?

**Comment by macandcheese** [comment]
It seems the styles for nested items also differ between List and Pick List - it would be great to do a design pass to ensure they are consistent, and see if we need a border at all (or an option to enable / disable).

**Comment by geospatialem** [comment]
cc @jcfranco potential linting rule implementation?

**Comment by driskull** [comment]
https://codepen.io/driskull/pen/XWEedNo?editors=1000

**Comment by geospatialem** [comment]
Verified on next.540 ✔️
