### ISSUE TITLE
Action menu does not close on iOS

### ISSUE THREAD

**Issue by janett-baresel** [Esri/calcite-components#4771]
### Actual Behavior

Using the action bar with an action group and an action menu (popover menu) doesn't close when one of the actions is clicked (touched) in chrome browser on iOS. It works on desktop and chrome on android (samsung device). 

### Expected Behavior

action menu works on all mobile devices.

### Reproduction Sample

https://codepen.io/Programmine/pen/gOvEyKP?editors=1000

### Reproduction Steps

with an ipad and chrome:
1. Open + action in action bar
2. click on either menu entry (a or b) 
3. observe menu not auto-closing

(do the same on laptop or android with chrome and menu auto-closes)

### Reproduction Version

beta.83

### Relevant Info

iPad and chrome

<sub>SVCH</sub>

**Comment by macandcheese** [comment]
Recording of this - it seems to inconsistently focus the action pad items - when it does, it correctly closes: 

iOS / Safari : 

https://user-images.githubusercontent.com/4733155/180497544-0bfea4d5-19d7-4900-b65b-54b33775c416.mp4

**Comment by geospatialem** [comment]
Verified with iOS on Safari and Chrome via next.553

https://user-images.githubusercontent.com/5023024/182423633-50191a66-aca7-4f44-a810-f8d9f96e05d5.mp4
