### ISSUE TITLE
calcite-combobox hangs out of the window when used within a JS API widget

### ISSUE THREAD

**Issue by gavinr** [Esri/calcite-components#4772]
### Actual Behavior

When using the `calcite-combox` in a JS API widget, the dropdown options drop outside of the viewable area of the screen

### Expected Behavior

`calcite-combobox` should properly size the dropdown to allow the user to see the entire dropdown no matter the screen size

### Reproduction Sample

https://jsbin.com/maridel/1/edit?html,output

### Reproduction Steps

1. Open the jsbin example (https://jsbin.com/maridel/1/edit?html,output)
2. Click open the widget (underneath the zoom buttons) and click open the combobox.
    - Note all the options that are in the box:
    ![image](https://user-images.githubusercontent.com/209355/174350333-c6b0571a-609e-49f1-8b48-b9c61c41b3ef.png)
3. Close the combobox dropdown.
4. Resize your browser to be smaller
    - Actual: Notice that you cannot see all the options
    - Expected: You should be able to see all the options
    ![image](https://user-images.githubusercontent.com/209355/174350689-243d37bc-ecab-4585-a560-d912a6b6c909.png)

### Reproduction Version

1.0.0-beta.83

### Relevant Info

Is this related to #3815? I'm not totally sure.

**Comment by gavinr** [comment]
I have created a very rough temporary workaround by dynamically modifying the `max-items` property based on screen calculations https://jsbin.com/cibekek/edit?html,output

**Comment by geospatialem** [comment]
Also pertains to `dropdown` component. Resolution is to set the `max-height` to a percentage of the view height.

**Comment by benelan** [comment]
verified on next
