### ISSUE TITLE
popover: autoClose does not work in Shadow DOM

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#4792]
### Actual Behavior

If created inside Shadow DOM, the popover's `autoClose` prop does nothing. 

### Expected Behavior

auto-close should work regardless of being used in a component with shadow dom or a component in the light dom.

### Reproduction Sample

https://codepen.io/paulcp/pen/QWQbWpY?editors=1010

### Reproduction Steps

1. Click either of the Shadow DOM buttons
2. Click outside the popover 
3. Notice popover is still open

If you update the CC versions in the codepen to 81, you can see that the shadow dom manager version actually works and autocloses properly. (More about that in _Relevant Info_)

### Reproduction Version

1.0.0-beta.83

### Relevant Info

I think this has something to do with the update to not use a manger that happened in beta.82. 

I'm not totally sure what mechanism is doing the body click listener now for auto close, but previously it was done by the popover-manager. When that was deleted here: https://github.com/Esri/calcite-components/commit/04d537441a890dcbd21a7551b488a9f4683e5a3a#diff-a5f059cf3a8145ee504a5ff9f390ae8b147bd5f113f2f7f35df960268e3e8f5fL81-L82 , I think whatever new click handler got used doesn't work with shadow DOM. 

### Regression?

1.0.0-beta.81

**Comment by driskull** [comment]
PR opened!
