### ISSUE TITLE
Enter key does not submit form in Safari

### ISSUE THREAD

**Issue by ReneU** [Esri/calcite-components#4793]
### Actual Behavior

When using a `calcite-input` within a `<form>` element, pressing enter in Safari results in a JS error and the form is not submitted.

![image](https://user-images.githubusercontent.com/5748802/175255376-ecbd8ff2-8f46-4498-8059-2873b4b7aa38.png)

### Expected Behavior

Similar to other browsers, the form should be submitted correctly (i.e. the form's `onsubmit` event should be triggered).

### Reproduction Sample

https://codepen.io/reneu/pen/jOZjXRq?editors=1000

### Reproduction Steps

1. Open linked codepen with Safari browser
2. Focus input element
3. Press enter

### Reproduction Version

v1.0.0-beta.83

### Relevant Info

macOS Menterey Version 12.4
Safari Version 15.5 (17613.2.7.1.8)

It seems like [HTMLFormElement.requestSubmit](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit#browser_compatibility) has only 'preview browser support' in Safari but is being used in: https://github.com/Esri/calcite-components/blob/4bca90679c19a2c7fed7acb8f126bdd223c0e50f/src/utils/form.tsx#L141-L143

**Comment by geospatialem** [comment]
Verified on Safari Version 15.5 (17613.2.7.1.8) on `next`.

**Comment by ReneU** [comment]
@driskull @geospatialem Thank you!
