### ISSUE TITLE
calcite-card selection checkbox can obscure title slot content

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-components#4802]
### Actual Behavior

When I use `calcite-card` with `selectable` _and_ have content in the title slot that sits at the right side of the card, that content is obscured by the selection checkbox.

### Expected Behavior

The selection checkbox will not obscure content.

### Reproduction Sample

https://codepen.io/mjuniper/pen/KKQOeBq?editors=1100

### Reproduction Steps

1. Visit https://codepen.io/mjuniper/pen/KKQOeBq?editors=1100
2. Observe that the selection checkbox partially obscures the "Card Title" text.

### Reproduction Version

beta.83

**Comment by nick-esri** [comment]
Field Maps web is also affected by this bug:
<img src="https://user-images.githubusercontent.com/3908500/185446752-58ae509a-b180-4565-a0a7-cdace68591fa.png" width="300"> 

Ideally the title should wrap before it collides with the checkbox. Possible to prioritize this fix @benelan ? Thanks

**Comment by geospatialem** [comment]
Verified on beta.95
![verified card select padding](https://user-images.githubusercontent.com/5023024/193696560-01bf72d2-48dd-4401-b834-86d457ba8475.png)
