### ISSUE TITLE
2nd Global Nav design proposal for Phase 2

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#4819]
### Description

Phase 2: Create an interactive prototype for Phase 2 (aka Platform NavO).

### User Stories

The navigation component is a responsive header for navigation and brand positioning.

### Acceptance Criteria

- [ ] App switcher
- [ ] User dropdowns
- [ ] Notifications

**Comment by yelenakreyndel** [comment]
@geospatialem there was a deadline for this task in Devtopia. It looks like it did not move. So we need to set a deadline again. @macandcheese Is this task complete?

**Comment by macandcheese** [comment]
Closing as outdated and project tracking is in Confluence / Airtable.
