### ISSUE TITLE
Migrate from Screener to Chromatic

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#4825]
### Summary

Screener was bought by Sauce Labs and they are shifting directions toward Selenium. We want to continue using storybook for our visual regression testing. We found [Chromatic](https://www.chromatic.com/) and [Storyshots](https://github.com/storybookjs/storybook/tree/next/addons/storyshots/storyshots-puppeteer#imagesnapshots) (self-hosted) as alternatives, which are both created by the same people as Storybook. After research and testing Chromatic came out as a winner.

I was able to configure chromatic on a branch, and the CI is working very well. @eriklharper is working on getting [interaction testing](https://www.chromatic.com/docs/interactions) to work, which is the last thing we need to finish before we can migrate. 

This is the baseline branch: https://github.com/Esri/calcite-components/tree/benelan/chromatic

This is the test branch Erik is using for interaction testing setup: https://github.com/Esri/calcite-components/tree/benelan/chromatic-test

### Desired Outcome

The action items are:

1. get the Chromatic interaction testing working and then rewrite the existing ones we have for screener
2. work with our administrators to figure out when we can switch and how to do it smoothly

### Resources

Undocumented questions that chromatic support answered:

1. Is there a schedule to the browser infrastructure upgrades? From [this doc](https:/www.chromatic.com/docs/infrastructure-release-notes) it looks like it happens once a year, are there plans to increase the frequency of upgrades to stay up to date with recent browser versions?
    - There is no set scheduled for the infrastructure upgrades currently. We’ll likely aim to move to quarterly upgrades for Chrome in 2023. 
 
2. Does chromatic need to run on the default branch to update the baseline, or is the baseline automatically updated after merging a PR?
    - You do have to run Chromatic again on the baseline, but you can use [auto-accept-changes](https://www.chromatic.com/docs/cli#chromatic-options) CLI flag to automate that process. 
    - [From the call] This does count as two snapshots for billing. However they offer [options to conditionally take snapshots](https://www.chromatic.com/docs/turbosnap) which look like they can really help in reducing the snapshots taken.
 
3. What is the operating system of the cloud machines that the snapshot tests run on? Are there any plans to provide additional browser options?
    - Linux is the operating system used for Firefox and Chrome. IE currently runs on windows. We are planning to add Safari as our next browser, which will hopefully be this summer.

4. Is there a public roadmap somewhere that we can look at?
    - We do not have a public roadmap currently, but, I’ve attached information on our roadmap (and recent features released) here. [Public Chromatic Roadmap.pdf](https://github.com/Esri/calcite-components/files/9013696/Public.Chromatic.Roadmap.pdf)

They also mentioned an [unofficial resource](https://6262c53f521620003ac2ff49-ukmsdlppcb.chromatic.com/?path=/story/stories-diff-threshold-check--test-yours-out) for understanding the [visual change threshold](https://www.chromatic.com/docs/threshold). I asked because we were getting some false positive from text aliases which I was able to resolve with a higher threshold. However, I was curious about how the 0 through 1 numbers work since I didn't want to set it too high and ignore actual changes.

**Comment by geospatialem** [comment]
@benelan Is Chromatic ready for verification, and/or should we move this into the January release milestone?

**Comment by benelan** [comment]
Yeah Chromatic is ready for verification. We are still getting some unrelated visual changes, but otherwise everything is looking great. I'll continue investigating the diffs described below, which may actually be issues on our end that they're catching.

**Note for viewing the diffs**
The best way to see the changes described below is to select "1 up" in the top middle of the screen. You can then use the "Switch" button to toggle between the current build and baseline snapshots.
![image](https://user-images.githubusercontent.com/10986395/205396955-d2d194a4-15d3-4000-951f-1e44ea2f8e19.png)


## Text shifting
I am seeing some text shifting between snapshots in various components.

### Date Picker and Pagination 
These seem to only be happening with our arabic `numberingSystem` snapshots.
- [Pagination example](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=638a69d8b2c50cac7f3cd3b8)
- [Date Picker example](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=638a48a3214b8e4f8ab2c891)

### Slider
These seem to mostly (or only) happen on the range snapshots with handles that are overlapping and have labels. The handle labels shift horizontally.
- [Slider example 1](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=638a489d230a014441d693b1)
- [Slider example 2](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=638900221cb3699ccbe2cdae)
- [Slider example 3](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=638900221cb3699ccbe2cdab)

### List
This one appears more inconstently, but it looks like the left-margin is wrong for some list items on some builds
- [List example 1](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=6389059369e273a32f2aa04d)
- [List example 2](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=638a64fded1ae180fb89f683)


## Inconsistent floating-ui positioning
Chromatic support thinks this is due to a difference between hard refresh versus a cached refreshes. If that's the case, it should be solvable by manually repositioning the components ourselves once we can use [interaction tests](https://www.chromatic.com/docs/interactions).
- [Alert example](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=6388fa2378a161fa65f4a5b5)
- [Popover example](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=6388f7762e0a55f2ff111735)


## Animation
It seems like snapshots are occasionally taken before animation completes. This should be easy to fix by adding a [delay](https://www.chromatic.com/docs/delay), or by setting `--calcite-duration-factor` to 0
- [Dropdown example](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=6388fa2378a161fa65f4a606)
