### ISSUE TITLE
Components that are closed/dismissed should no longer render any UI

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#4826]
### Description

> I think we should probably update `chip` to no longer render any UI if closed.
> 
> If not part of this PR, a followup issue/pr should be linked

https://github.com/Esri/calcite-components/pull/4789#pullrequestreview-1020883311

### Proposed Advantages

We should be consistent with how we render closed/dismissed components. 

Most of the components will no longer render any UI when closed. However, the `chip` component still renders UI and emits an event.

### Which Component

chip

### Relevant Info

https://github.com/Esri/calcite-components/pull/4789

**Comment by benelan** [comment]
verified on next
