### ISSUE TITLE
calcite-tooltip-manager only working once (when used with Maquette?)

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#483]
http://devext.arcgis.com/apps/mapviewer/index.html?urls=https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/2

Click Styles tool on the right toolbar, second from top.
Click +Field and select POP2000.
Click on tile with orange dots.
Hover over the buttons above the slider and you’ll see tooltips.
Cancel and click again on the tile with orange dots.
Tooltips no longer work.

<img src=https://user-images.githubusercontent.com/44481292/79526502-472f2b00-801a-11ea-9882-ac41bd6a2cdd.png width=200/>

Franco could probably reproduce this outside of the map viewer on this local install of arcgis-components
…/test-apps/smartMapping/Gallery/index.html?url=https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/2

cc @driskull @jcfranco

**Comment by driskull** [comment]
Yeah maybe a maquette thing? I see the issue in the DOM. The `aria-describedby` on the `calcite-action` should match the `id` of the `calcite-tooltip` but it isn't. Somehow they are getting out of sync? Maybe you could add a key to either the tooltip or the action to make sure they are updated together?

**Comment by jcfranco** [comment]
This could be related to the button layout issue we encountered before. Stencil's latest version has a config option that triggers causes components to update later in the lifecycle, it's worth trying out to see if it'll fix it. The commit message certainly sounds related: https://github.com/ionic-team/stencil/commit/cb71057b7fc4123738f83d03713a06d8f0a50d64

**Comment by AdelheidF** [comment]
> Maybe you could add a key to either the tooltip or the action to make sure they are updated together?

I do both.
```
                <calcite-action
                  key="size-slider-invert"
                  id="size-slider-invert"
                  class={CSS.sliderButton}
                  onclick={this.handleInvertSlider.bind(this)}
                >
                  <calcite-icon scale="s" icon="arrowUpDown"></calcite-icon>
                </calcite-action>
                <calcite-tooltip
                  key="size-slider-invert-tooltip"
                  placement="auto"
                  reference-element="size-slider-invert"
                >
                  {i18n.ui.invertSlider}
                </calcite-tooltip>

```

**Comment by driskull** [comment]
@AdelheidF I have a potential fix.

In the meantime, can you try setting an `id` o the `calcite-tooltip` and see if that fixes it?

**Comment by AdelheidF** [comment]
> In the meantime, can you try setting an id o the calcite-tooltip and see if that fixes it?

Yes, this fixes the issues. I installed that for beta 5. Thanks!

**Comment by driskull** [comment]
awesome 🎉

**Comment by driskull** [comment]
Installed! will need a new release to see. @AdelheidF do we need this release soon?

**Comment by AdelheidF** [comment]
> do we need this release soon?

No thanks, I'm using the workaround for beta 5.

**Comment by driskull** [comment]
Ok sounds good :)

**Comment by AdelheidF** [comment]
verified
