### ISSUE TITLE
Enhancement: Calcite chips supporting icon only 

### ISSUE THREAD

**Issue by abigailmbravo-uxuidev** [Esri/calcite-components#4837]
### Description

We are using the Calcite chip component to create the badges in ArcGIS Online. Currently, we are need of an icon only badge for responsive screens. When the string is removed from the icon today the spacing and overall badge has weird padding and is the wrong size. It's also challenging from a development prospective - right now, the icon is being passed in as an SVG to apply the proper badge size.

### Acceptance Criteria

Update chip component to allow for icon only so that badges can work responsively. 

### Relevant Info

We are in the process of updating the badges as we move the item browser into 4x. And this badge update will apply to ArcGIS Online home page and map viewer long term. 

### Which Component

Calcite chip component

### **This is how the chips look today when the string is removed:**
<img width="406" alt="current icon only chip" src="https://user-images.githubusercontent.com/73944682/176778471-e6c208e7-b1c4-4e60-a84d-6e3b2b064783.png">

### **Hoping to get something more like this:**
![icon only chips](https://user-images.githubusercontent.com/73944682/176778611-f55577b4-4398-4416-b39d-c6e0993c481a.png)

cc: @paulcpederson @macandcheese

**Comment by paulcpederson** [comment]
@macandcheese I think we could probably handle this like we do `calcite-button` where if you don't have text it just puts the icon centered. Here's a codepen to show those two components doing icon only https://codepen.io/paulcp/pen/abYzabX

**Comment by macandcheese** [comment]
Yep, that makes sense. The coded version is a worse offender than the Figma version posted above, which is at least centering the icon inside the pill. I do wonder if having pill vs. circle makes some of the icon boundary misalignments a bit less noticeable, but .. I think we can proceed with handling it like the button.

**Comment by macandcheese** [comment]
This was added in https://github.com/Esri/calcite-components/pull/6058 and is slated for inclusion in our upcoming release.

**Comment by geospatialem** [comment]
Verified in `beta.99` with the [following Codepen](https://codepen.io/geospatialem/pen/ExpKgrG).

Sample (default):

```html
<calcite-chip value="chip" icon="3d-glasses"></calcite-chip>
```
