### ISSUE TITLE
[Progress] Displayed `text` color not set / does not swap with theme class

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4840]
### Actual Behavior

It seems we aren't setting a defined text color on Progress `text` string display - which means it doesn't respond to light / dark mode changes and inherits color from a parent.

### Expected Behavior

Explicit text style is set and responds correctly to light / dark mode change.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/KKowxGr?editors=1000

### Reproduction Steps

1 - Go to Codepen
2 - Notice provided `text` string is not swapping with theme
3 - Notice setting color style on parent component incorrectly overrides `text` string

### Reproduction Version

83

### Relevant Info

Longer term we could look at perhaps removing the `text` string altogether if we don't think it has value / gets use, similar to some of @asangma's proposed changes to Loader : https://github.com/Esri/calcite-components/issues/4470.

**Comment by geospatialem** [comment]
Verified in `beta.95`. ✔️
