### ISSUE TITLE
[Filter] Regex error when using special character in search term

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4851]
### Actual Behavior

Saw this while using the filter-enabled pick-list, I'm guessing it's at the filter level. Using special characters - [ ] \ - etc., will product a console error:
![Screen Shot 2022-07-06 at 9 07 02 AM](https://user-images.githubusercontent.com/4733155/177595249-32b9dc20-4b03-4c0e-87e3-aa198f70d73b.png)
 

### Expected Behavior

No errors are shown in console with any string in filter field.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/GRxoMRq?editors=1000

### Reproduction Steps

1 - go to Codepen sample
2 - type any string in filter-enabled pick list and then add `[`  or `]` or `\`
3 - see console log error

### Reproduction Version

83

**Comment by benelan** [comment]
verified on next
