### ISSUE TITLE
New component: menu or nested dropdown

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-components#4858]
### Description

It would be great to have a new Menu or nested dropdown component. This component would displaying multiple levels of items and allow selecting them.

In Angular Material, for example, this capability is present in their `<mat-menu>` component. An example can be seen here: https://material.angular.io/components/menu/examples#menu-nested
![Screen Shot 2022-07-07 at 13 30 38](https://user-images.githubusercontent.com/3759114/177763481-5c8201f0-efdd-491a-b6a4-ec2b3fe19850.jpg)

In Ant Design, the component is also called `Menu` and examples can be seen here: https://ant.design/components/menu/

![Screen Shot 2022-07-07 at 13 32 09](https://user-images.githubusercontent.com/3759114/177763817-eade3e27-00db-400f-96d9-3a47741bacc2.jpg)

### Acceptance Criteria

While some other design systems and frameworks provide a variety of options for creating menus, an MVP could be something like the Angular nested menu example mentioned above: https://material.angular.io/components/menu/examples#menu-nested

In the case of Calcite Components, the code could look similar to `<calcite-dropdown-group>`. Something like this:

```html
<calcite-menu>
  <calcite-button slot="menu-trigger">Animal index</button>
  
  <calcite-menu-item item-title="Vertebrates">
    <calcite-menu-item item-title="Fishes">
      <calcite-menu-item item-title="Baikal oilfish"></calcite-menu-item>
      <calcite-menu-item item-title="Bala shark"></calcite-menu-item>
      <calcite-menu-item item-title="Ballan wrasse"></calcite-menu-item>
      <calcite-menu-item item-title="Bamboo shark"></calcite-menu-item>
      <calcite-menu-item item-title="Banded killifish"></calcite-menu-item>
    </calcite-menu-item>
    <calcite-menu-item item-title="Amphibians">
      <calcite-menu-item item-title="Sonoran desert toad"></calcite-menu-item>
      <calcite-menu-item item-title="Western toad"></calcite-menu-item>
      <calcite-menu-item item-title="Arroyo toad"></calcite-menu-item>
      <calcite-menu-item item-title="Yosemite toad"></calcite-menu-item>
    </calcite-menu-item>
    <calcite-menu-item item-title="Reptiles">
      <calcite-menu-item item-title="Banded Day Gecko"></calcite-menu-item>
      <calcite-menu-item item-title="Banded Gila Monster"></calcite-menu-item>
      <calcite-menu-item item-title="Black Tree Monitor"></calcite-menu-item>
      <calcite-menu-item item-title="Blue Spiny Lizard"></calcite-menu-item>
      <calcite-menu-item item-title="Velociraptor" disabled></calcite-menu-item>
    </calcite-menu-item>
    <calcite-menu-item item-title="Birds"></calcite-menu-item>
    <calcite-menu-item item-title="Mammals"></calcite-menu-item>
  </calcite-menu-item>
  <calcite-menu-item item-title="Invertebrates">
    <calcite-menu-item item-title="Insects"></calcite-menu-item>
    <calcite-menu-item item-title="Molluscs"></calcite-menu-item>
    <calcite-menu-item item-title="Crustaceans"></calcite-menu-item>
    <calcite-menu-item item-title="Corals"></calcite-menu-item>
    <calcite-menu-item item-title="Arachnids"></calcite-menu-item>
  </calcite-menu-item>
</calcite-menu>
```

### Relevant Info

- React Spectrum has a similar issue open: https://github.com/adobe/react-spectrum/issues/1356. But they have some foundations: https://react-spectrum.adobe.com/react-stately/useTreeData.html
- https://blog.logrocket.com/creating-multilevel-dropdown-menu-react/
- https://mdbootstrap.com/docs/standard/extended/dropdown-multilevel/

### Which Component

Probably to be called `<calcite-menu>`, unless we want to extend the `<calcite-dropdown>`

### Example Use Case

Came up While looking at the internal ArcGIS JS API Playground and trying to figure out what it would take to migrate it to Calcite Components. We currently have a dropdown which lets users select the version of the JS API they'd like to run their app/sample in. To keep the dropdown size small-ish, we nest a list of older versions under an "Older versions" option.

**Comment by macandcheese** [comment]
Thanks for adding, I think this would be a great enhancement to Dropdown... I wonder if slotting `dropdown-group` inside a `dropdown-item` could achieve this hierarchy.

Also curious how we can manage selection state across "nests" - and if a mixed state indicator on the parent would be needed for when selection mode is single, or multiple. Selection mode of none wouldn't need that.

**Comment by geospatialem** [comment]
@jcfranco What do you think of the above recommendation for nesting with `dropdown-item` and `dropdown-group` through a new slot?

Perhaps a good candidate for the #5529 epic?

**Comment by macandcheese** [comment]
This will be addressed in the upcoming Nav component, and is listed as a follow up feature for after the initial version. https://github.com/Esri/calcite-components/issues/6606
