### ISSUE TITLE
calcite-tooltips positioning off in FireFox (placement=auto)

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#486]
Found by @zaramatheson

It depends a bit where the button is inside the panel of how far off the tooltip is.

<img src=https://user-images.githubusercontent.com/44481292/79616290-7cd72100-80b9-11ea-8f74-220a7cf3ed5b.png width=200/><img src=https://user-images.githubusercontent.com/44481292/79616014-e0ad1a00-80b8-11ea-90a1-ffd4d7c66180.png width=200/>

in Chrome:
<img src=https://user-images.githubusercontent.com/44481292/79616066-fae6f800-80b8-11ea-85f0-29f23ae89897.png width=200/>

```
              <calcite-action
                key="transparency-slider-zoom"
                id="transparency-slider-zoom"
                class={CSS.sliderButton}
                label={i18n.ui.zoomSlider}
                disabled={disableZoomButton}
                onclick={this.handleZoomSlider.bind(this)}
              >
                <calcite-icon scale="s" icon="magnifyingGlassPlus"></calcite-icon>
              </calcite-action>
              <calcite-tooltip
                key="transparency-slider-zoom-tooltip"
                id="transparency-slider-zoom-tooltip"
                placement="auto"
                reference-element="transparency-slider-zoom"
              >
                {i18n.ui.zoomSlider}
              </calcite-tooltip>
```

**Comment by driskull** [comment]
@AdelheidF do you have a repro case I can see? It would be hard to debug otherwise.

**Comment by driskull** [comment]
@AdelheidF looks like it has something to do with the positioning when the tooltip is inside a scrollable area. Can you try moving it to the document.body?

**Comment by AdelheidF** [comment]
http://devext.arcgis.com/apps/mapviewer/index.html?urls=https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/2

Click Styles tool on the right toolbar, second from top.
Click +Field and select POP2000.
Click on tile with orange dots.
Hover over the buttons above the slider and you’ll see tooltips.
Scroll the panel a bit to see the position change.

<img src=https://user-images.githubusercontent.com/44481292/79617041-6af67d80-80bb-11ea-912e-0304a1a0e070.png width=200/>

**Comment by driskull** [comment]
Thanks. Updating popper.js may fix this. I see a fix related to scrolling. Ill try that first and if it doesn't fix it we can debug further.

**Comment by macandcheese** [comment]
@AdelheidF was this fixed with the version bump for Popper?

**Comment by AdelheidF** [comment]
No.

<img src=https://user-images.githubusercontent.com/44481292/80839807-cee76e80-8bb0-11ea-943d-1e7a881a0821.png width=200/><img src=https://user-images.githubusercontent.com/44481292/80839892-f63e3b80-8bb0-11ea-92cf-e1c51624c97e.png width=200/>

**Comment by driskull** [comment]
> The horizontal scroll bars that only appear while the tooltip is showing are not very nice either.

@AdelheidF you should place the tooltip outside of that panel which should fix that issue and probably the incorrect positioning.

I can work on creating a repro case for Popper but that might take some time. I think it has to do with shadowDom and the overflow:auto here.

**Comment by AdelheidF** [comment]
> you should place the tooltip outside of that panel which should fix that issue and probably the incorrect positioning.

That makes adding many tooltips to a component really complicated because I can't just add them with JSX. I'll will try it and see.

**Comment by driskull** [comment]
That's going to be the only way to prevent getting cut off by the scrollbars though.

**Comment by zaramatheson** [comment]
Original issue exists for me without the scrollbars:
![image](https://user-images.githubusercontent.com/50747646/80842467-80d56980-8bb6-11ea-89de-6899e5fa42c4.png)

**Comment by AdelheidF** [comment]
I tested it on one of my components to add the calcite-tooltip to the body instead of next to my calcite-button. The placement works now in FF, but it is making it way more complicated. Now the component needs to make sure all its tooltips get removed again even if the app removes the component without the user using Apply or Cancel.

Could the tooltip watch its reference-element and remove itself when it disappears?

**Comment by driskull** [comment]
> Could the tooltip watch its reference-element and remove itself when it disappears?

I don't think so. We would want to support a user changing the referenceElement without it getting removed.

**Comment by AdelheidF** [comment]
OK. 
Do you want to add a comment to the doc saying that calcite-tooltip has to be added to the <body> ?

**Comment by driskull** [comment]
> Do you want to add a comment to the doc saying that calcite-tooltip has to be added to the

Maybe its a best practice we do for MapViewer but there may be some use cases where you want the tooltip to scroll with a reference element out of view so you would put it inside a scrolling node.

The issue with Firefox not getting positioned correctly seems like a bug we can bring to Popper.js to get fixed.

**Comment by AdelheidF** [comment]
> where you want the tooltip to scroll with a reference element out of view so you would put it inside a scrolling node.

Because a tooltip only shows while you hover, how would it be possible to scroll and show a tooltip at the same time? 

I would love to no have to add the tooltip to the `<body>`, it's not a MapViewer specific request.

**Comment by driskull** [comment]
Its probably safest to add to body since then you don't have to worry about anything cutting it off with `overflow:auto`. Then it is always on top and can easily get the position.
