### ISSUE TITLE
[Input] disabled spinner buttons on Input type=number should not be interactive

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#4879]
### Actual Behavior

Disabled spinner buttons on the Input (type=number) respond to pointer events, nudge the number, and transition.

### Expected Behavior

Disabled spinner buttons on the Input (type=number) should not be interactive.

### Reproduction Sample

https://codepen.io/elijbet/pen/jOzqZjv

### Reproduction Steps

Click on the up/down spinner buttons to see them highlight and nudge the number.

### Reproduction Version

v1.0.0-beta.83

### Relevant Info

Seems to appear on the new Input-number component PR #[4870](https://github.com/Esri/calcite-components/pull/) as well.

**Comment by geospatialem** [comment]
Verified on `beta.86`

![verify-input-disabled-spinbtns-interaction](https://user-images.githubusercontent.com/5023024/179016973-1d4cb1d8-12ed-4fdb-943a-1345d46cd57a.gif)
