### ISSUE TITLE
<calcite-switch> "change" event conflicts with native DOM event name warning

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#488]
```
[ WARN  ]  Build Warn: ./src/components/calcite-switch/calcite-switch.tsx:42:12
           The event name conflicts with the "change" native DOM event name.
```

**Comment by paulcpederson** [comment]
@eriklharper yeah, it's noted in the switch cleanup issue: #474. So we could probably consider this duplicate, or we could leave it open and close at the same time. But it is annoying, I agree.

**Comment by eriklharper** [comment]
Marking as dupe is fine with me, just wanted to make sure it was recorded somewhere!  I'll close as appropriate.
