### ISSUE TITLE
Cannot set `width` of stepper

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#4883]
### Actual Behavior

Setting a `width` (or `max-width`) style on a `calcite-stepper` element has no effect on the size of the element.

### Expected Behavior

The stepper assumes the specified width.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/qBoZKWg

### Reproduction Steps

1. Visit the sample
2. Notice the stepper should be half the width of the viewport, but is actually the full width

### Reproduction Version

beta.83

### Relevant Info

The stepper has a `min-width: 100%` style that is overriding any attempts to otherwise set the stepper's width. A current workaround is to reset this style on the stepper element.

**Comment by benelan** [comment]
verified on next
