### ISSUE TITLE
add numberingSystem property to components that display numbers

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#4893]
### Description

We added a numberingSystem property to `calcite-input` for localization. We should also add it to all other components that display numbers out of the box.

### Acceptance Criteria

New `numberingSystem` property that behaves like it does for `calcite-input`

### Which Component

- [x] calcite-alert (Dibs'd by Ben)
- [x] calcite-slider
- [x] calcite-stepper (Dibs'd by Ben)
- [x] calcite-date-picker (Dibs'd by Ben)
- [x] calcite-time-picker (Dibs'd by Ben)
- [x] calcite-input-time-picker (Dibs'd by Ben)
- [x] calcite-input  (follow up bug Dibs'd by Ben: #5252)
- [x] calcite-pagination

### Example Use Case

Example use case is in [`calcite-input`](https://github.com/Esri/calcite-components/blob/master/src/components/input/input.tsx). There is also relevant code in the [`locale`](https://github.com/Esri/calcite-components/blob/master/src/utils/locale.ts) util.

**Comment by geospatialem** [comment]
Verified for all components above, with the exception of pagination. ✔️ 

Created #5648 for pagination-specific tracking.

### alert
![image](https://user-images.githubusercontent.com/5023024/198128320-76a981ef-f27e-4b73-9481-6cf3c49b47bd.png)

### slider
![image](https://user-images.githubusercontent.com/5023024/198128549-55ac6f6e-5b69-41f0-9ea3-9cfc71bb767c.png)

### stepper
![image](https://user-images.githubusercontent.com/5023024/198129030-0d2185b0-b983-4ea2-8237-73afac2ae9e1.png)

### date-picker
![image](https://user-images.githubusercontent.com/5023024/198129322-fe5ff777-3e7e-4786-9b30-75a69ebfb71a.png)

### time-picker
![image](https://user-images.githubusercontent.com/5023024/198129696-7b958702-71db-4587-bfb3-eebfc835e110.png)

### input-time-picker
![image](https://user-images.githubusercontent.com/5023024/198129764-d4a6aed6-6718-4e2a-8083-d2eed4fc5ed0.png)

### input
![image](https://user-images.githubusercontent.com/5023024/198129865-f8777469-b3d3-4d88-811d-7dd898fb2aa2.png)
