### ISSUE TITLE
thumbnail overflows calcite-card when it has rounded corners

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-components#4895]
### Actual Behavior

When calcite-card has a thumbnail and `--calcite-border-radius-base` is used to give it rounded corners, the thumbnail overflows the card at the corners.

![image](https://user-images.githubusercontent.com/942837/178314413-be23ffb4-ee1b-462a-8e7b-427c93178d65.png)

### Expected Behavior

calcite-card should respect `--calcite-border-radius-base`.

I think applying `overflow: hidden` to `.calcite-card-container` fixes it. Not sure if that has undesirable side-effects or if there is a better fix.

### Reproduction Sample

https://codepen.io/mjuniper/pen/qBoNJpv?editors=1100

### Reproduction Steps

1. Visit https://codepen.io/mjuniper/pen/qBoNJpv?editors=1100
2. Observe the upper left and upper right corners where the thumbnail overflows the container, making the corners look wonky.

### Reproduction Version

beta.83

**Comment by geospatialem** [comment]
Verified on `next.530`

![verify-card-border-radius](https://user-images.githubusercontent.com/5023024/178844011-d05726be-fc3f-4305-916b-eb8a57a2f9d7.png)
