### ISSUE TITLE
Active tab underline doesn't fill the width if an icon is dynamically added

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#4896]
### Actual Behavior

If an icon is dynamically added to an active tab title, the underline for the title does not fill the width
<img width="218" alt="Screen Shot 2022-07-11 at 2 53 44 PM" src="https://user-images.githubusercontent.com/5892789/178337502-9166c40b-5a13-4265-b9d4-42e8f6a826ce.png">

### Expected Behavior

The underline width matches the width of the title

### Reproduction Sample

https://codepen.io/mpayson/pen/jOzrXaE

### Reproduction Steps

1. Open the code pen
2. Click the button
3. Notice an indicator is added and the underline is short

### Reproduction Version

beta.83

**Comment by geospatialem** [comment]
Verified in `beta.95`.

![verified active tab style for tab with indicator](https://user-images.githubusercontent.com/5023024/193875035-aa88adc2-8d4c-4c48-94e8-ae45cde1606f.png)
