### ISSUE TITLE
<calcite-stepper> should not wrap items

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#4898]
### Actual Behavior

Since Calcite stepper presents a linear UX pattern it should not wrap horizontally.

![Uploading Screen Shot 2022-07-11 at 1.17.43 PM.png…]()

### Expected Behavior

I would expect text to wrap inside `<calcite-stepper>` instead of the entire step to wrap.

### Reproduction Sample

https://esri.github.io/calcite-components/?path=/story/components-stepper--simple

### Reproduction Steps

1. Open https://esri.github.io/calcite-components/?path=/story/components-stepper--simple
2. Shrink screen width.

### Reproduction Version

latest

**Comment by patrickarlt** [comment]
Likely related to https://github.com/Esri/calcite-components/issues/1258

**Comment by jcfranco** [comment]
FYI, it looks like #4367 would fix this

![improved-stepper-layout](https://user-images.githubusercontent.com/197440/178868738-fd8bc72e-1f9c-4f53-96c6-25aadead5a33.gif)
.

**Comment by jcfranco** [comment]
Fixed via #1258. https://codepen.io/jcfranco/pen/rNdWdYQ?editors=1000

**Comment by benelan** [comment]
verified on next
