### ISSUE TITLE
Regression with stepper `cursor` style

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#4954]
### Actual Behavior

Hovering stepper content shows the `pointer` style cursor.

### Expected Behavior

Hovering stepper content shows the `default` style cursor.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/abYJNpp

### Reproduction Steps

1. Visit the sample
2. Mouse over the active stepper item's content

### Reproduction Version

next.533

### Relevant Info

Likely introduced by https://github.com/Esri/calcite-components/pull/4367 which keeps the stepper item's content within the `.container` element which is supplying the `cursor-pointer` style.

### Regression?

beta.86

**Comment by benelan** [comment]
verified on next
