### ISSUE TITLE
Regression with stepper-item bottom margin

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#4956]
### Actual Behavior

In a horizontal layout, the last element of the active stepper-item's content is given a bottom margin.

### Expected Behavior

In a horizontal layout, no margin is applied to the last element.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/JjLWRmX

### Reproduction Steps

1. Visit the sample
2. Inspect the active stepper item's content and notice it has one applied by the stepper-items stylesheet
3. Compare w/ the [doc page][1] where no margin is applied

[1]: https://developers.arcgis.com/calcite-design-system/components/stepper/

### Reproduction Version

next.533

### Relevant Info

It looks like this margin was previously limited to the vertical layout, but changed in https://github.com/Esri/calcite-components/pull/4367.

Considering this a regression since it can have a disruptive impact on the vertical rhythm for pre-existing usages.

### Regression?

beta.86

**Comment by benelan** [comment]
Verified on `next.554`, however the cursor is no longer `pointer` when hovering over the content, is that expected?
