### ISSUE TITLE
calcite-panel:  setting `closed` to false doesnt remove `dismissed`

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#4969]
### Actual Behavior

When setting the `closed` attribute on calcite-panel to false, the deprecated `dismissed` attribute is not also removed

### Expected Behavior

`dismissed` should be removed when setting `closed` to false

### Reproduction Sample

https://codepen.io/kevindoshier/pen/abYJXZZ

### Reproduction Steps

1. Open the sample above
2. Click the "X" and wait for panel to toggle
3. Observe that the calcite-panel dismissed flag is still set

### Reproduction Version

beta.86

**Comment by driskull** [comment]
cc @anveshmekala

**Comment by tannerjt** [comment]
I encountered this same issue.  As a temporary fix, I'm setting both `closed` and `dismissed` props on `calcite-panel`.  It looks like the [draft PR](https://github.com/Esri/calcite-components/pull/4977) will resolve the issue once merged.

**Comment by benelan** [comment]
verified on next
