### ISSUE TITLE
calcite-stepper-item documentation

### ISSUE THREAD

**Issue by gavinr** [Esri/calcite-components#498]
I can't find the documentation that talks about the properties for `calcite-stepper-item`, like:

- `complete`
- `error`
- `active`
- `disabled`
- any others?

I'm looking here: https://esri.github.io/calcite-components/?path=/story/stepper--simple ... am I just missing it?

Also, it seems like the code example does not match the initial state of the example:
![image](https://user-images.githubusercontent.com/209355/80058195-2aae5980-8518-11ea-88cd-73fde10cbf77.png)

**Comment by macandcheese** [comment]
Hi @gavinr - Storybook only displays docs for the top level component (Calcite-stepper here) - docs do get generated for the child component as Readme: 

https://github.com/Esri/calcite-components/blob/master/src/components/calcite-stepper-item/readme.md#properties

As far as code sample, the code used to generate the stories in storybook isn't actually sourced from the example in the Readme, it's sourced from here : https://github.com/Esri/calcite-components/blob/master/src/components/calcite-stepper/calcite-stepper.stories.js

I can definitely update the default storybook story state to match the Readme documentation example, we also have some improvements planned to our demos that will coincide with Storybook's upcoming version 6 release that should clean the demos up  - https://github.com/Esri/calcite-components/issues/358

**Comment by gavinr** [comment]
Thanks! I didn't know about the child component README files - suggestion/ask: link to those from somewhere (either in the Storybook docs or if not there, maybe on the repo homepage?).

**Comment by macandcheese** [comment]
Yep, just ended up tacking the child component readme's onto the main story - we can probably have a more elegant solution in the future with a "Notes" tab per nested child component, but this should display them all for now: https://github.com/Esri/calcite-components/pull/499

Note this won't be visible until we re-deploy the docs to coincide with the next beta release. Thanks!

**Comment by gavinr** [comment]
Thanks! Since that's merged I'll close this for now.
