### ISSUE TITLE
calcite-dropdown in calcite-card will not extend outside card

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-components#4980]
### Actual Behavior

If you use a calcite-dropdown in a calcite-card, the dropdown content is clipped by the card.

### Expected Behavior

calcite-dropdown should work when in a calcite-card.

### Reproduction Sample

https://codepen.io/mjuniper/pen/gOeWRJp?editors=1000

### Reproduction Steps

1. visit https://codepen.io/mjuniper/pen/gOeWRJp?editors=1000
2. click the dropdown trigger
3. observe that the dropdown content is contained by the card.

### Reproduction Version

beta.85

### Relevant Info

I believe this was introduced by https://github.com/Esri/calcite-components/pull/4908 (sorry!)

### Regression?

beta.83

**Comment by jcfranco** [comment]
As a workaround, the dropdown should be able to escape the card by using `overlay-positioning: fixed`. https://codepen.io/jcfranco/pen/eYMWEoo?editors=1000

**Comment by mjuniper** [comment]
Oh, great point, thank you!

**Comment by mjuniper** [comment]
I think that since the [proposed fix](https://github.com/Esri/calcite-components/pull/4981) has [problems](https://github.com/Esri/calcite-components/pull/4981#discussion_r926073889), the workaround is a more than sufficient solution.
