### ISSUE TITLE
Convention: Exposing CSS properties for theming

### ISSUE THREAD

**Issue by patrickarlt** [Esri/calcite-components#50]
Components should provide CSS properties for theming. We need to decide on a pattern for this allow users to customize at least the colors of components.

We need a system in place for this. I think I have an idea based on custom properties and fallback values. https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#Custom_property_fallback_values.

This issue has origins in [this thread](https://teams.microsoft.com/l/message/19:fd15b51dacd24e70895ec1218a54ae06@thread.skype/1559932065529?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1559932065529&teamName=Calcite&channelName=Calcite%20Components&createdTime=1559932065529) on teams.

I'll work on this next week.

**Comment by macandcheese** [comment]
I think we are relatively in sync on how we are using CSS vars throughout components - going to close this. Can open some individual issues if needed.
