### ISSUE TITLE
Create Loaders in Small and Large—Add dark theme

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#500]
![image](https://user-images.githubusercontent.com/14083530/80127031-9b6d6a00-8548-11ea-888f-3fbe0fd41359.png)

![image](https://user-images.githubusercontent.com/14083530/80127416-23ec0a80-8549-11ea-9e64-69e994342ab6.png)

![image](https://user-images.githubusercontent.com/14083530/80127604-69103c80-8549-11ea-9022-88513c3be665.png)

**Comment by macandcheese** [comment]
Added by @asangma in https://github.com/Esri/calcite-components/pull/709 ✅
