### ISSUE TITLE
Default selection behavior differs between a dropdown + grouped items vs dropdown + items 

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#5020]
### Actual Behavior

Default selection behavior differs between a dropdown + grouped items  (selection-mode: single) vs dropdown + items (selection-mode: none or behaves like it): https://codepen.io/jcfranco/pen/PoRKdgz?editors=1000

Seems confusing to have them behave differently.

cc @driskull 

### Expected Behavior

Both dropdown setups should share the same selection mode behavior (single).

### Reproduction Sample

https://codepen.io/jcfranco/pen/PoRKdgz?editors=1000

### Reproduction Steps

1. Open the first dropdown (with groups) and select an item
2. Open it again and notice that the selected item is visually indicated
3. Open the second dropdown (w/o groups) and select an item
4. Open the dropdown and notice that there is no selected item

### Reproduction Version

@esri/calcite-components@1.0.0-beta.89

**Comment by ashetland** [comment]
Adding @KatelynSeitz to this. Our Figma component is still in review, but I believe it has the expected behavior.

**Comment by macandcheese** [comment]
This just recently started occurring when we removed the wrapping group component requirement, should be unrelated to anything in Figma. 

Why did we remove the requirement for the group? Is it now possible to mix grouped and ungrouped within a single dropdown... If there isn't a group - how does a user choose a selection-mode for the ungrouped items?

**Comment by driskull** [comment]
@jcfranco should we still require the group? We can revert that change.

**Comment by driskull** [comment]
@benelan can we use this issue to update the doc to make sure that a group is required? We should make it pretty clear. 

I think hiding the ungrouped items will help with that as well.

**Comment by benelan** [comment]
> @benelan can we use this issue to update the doc to make sure that a group is required? We should make it pretty clear.
> 
> I think hiding the ungrouped items will help with that as well.

I opened doc PRs for this. Unfortunately I am still able to repro on `next` using [Franco's sample](https://codepen.io/jcfranco/pen/PoRKdgz?editors=1000). Maybe the roles were causing the issue somehow? Reassigning back to dev.

**Comment by driskull** [comment]
@benelan franco's second example is invalid. Whats the issue?

**Comment by benelan** [comment]
Woops sorry you're right, I didn't read the code closely enough. Closing as verified on `next`!
