### ISSUE TITLE
Unify the `calciteStepperItemChange` and `goToStep` interfaces

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#5023]
### Description

The number emitted by the `calciteStepperItemChange` event is asymmetrical with the number expected by the stepper's `goToStep()` method.

In the former case, the step's 0-based position is provided, but in the latter case, the step's 1-based step number is expected. This provides for some confusing API ergonomics on the consumer side.

### Acceptance Criteria

The `calciteStepperItemChange` event and `goToStep` interfaces either both supply/expect the step's 0-based position, or the 1-based step number.

If I had a vote, I'd go with the 0-based position because it seems like the source of truth while the step number feels like more of a presentational/formatting concern.

### Which Component

calcite-stepper

### Example Use Case

In Ember, the ergonomics are such that it's easier to externally navigate a stepper via its explicit `goToStep()` method instead of its relative `prevStep()`/`nextStep()` methods:

```hbs
<button {{on 'click' this.decrementStepNumber}}>Prev</button>
<button {{on 'click' this.incrementStepNumber}}>Next</button>

<calcite-stepper
    {{go-to step=this.stepNumber}}
    {{on 'calciteStepperItemChange' this.setStepNumber}}>
  ...
</calcite-stepper>
```

Unifying on a single numeric representation of a step provides a single source-of-truth regardless of the mode of navigation. It also lends confidence to the stepper API and helps keeps this code as simple and readable as possible.

**Comment by macandcheese** [comment]
@driskull @geospatialem - should we look at these events for deprecation of payload? We could also expose public select event on the stepper-item themselves.

This was one of the first components we added, do we need to evaluate the approach we used for public methods here as well?

**Comment by driskull** [comment]
@macandcheese yep. This would be good to do as well. We'd have to introduce a `selectedItem` to the stepper to handle this.

**Comment by geospatialem** [comment]
Per the conversation in https://github.com/Esri/calcite-components/issues/6330#issuecomment-1454842359, also closes this similar issue on an event for `stepper-item`.
