### ISSUE TITLE
modal : no longer close modal on `esc` key when open on page load

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#5036]
### Actual Behavior

When the `active` prop is set on the modal on page load ,  `esc` key isn't closing the modal.

### Expected Behavior

`esc` key press should close the modal

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/vYReQgJ

### Reproduction Steps

1. Open the code pen 
2. Try to press `esc` key and observe modal wont close.

### Reproduction Version

 1.0.0-next.542

### Regression?

beta.89

**Comment by geospatialem** [comment]
Verified on next
