### ISSUE TITLE
popover,notice, chip,panel : setting `closable` prop to false does not remove `dismissible`.

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#5043]
### Actual Behavior

When the `dismissible` prop is set to `true ` and in the script, user sets the `closable` prop to `false`, the `dismissible` prop still stays as an attribute, and the `clear (x)`  icon is still visible in the component.

Note: This behavior is observed when the user uses one prop as an attribute (either deprecated or new one) and uses another to mutate the value. 

### Expected Behavior

Setting the `closable` prop to false should remove the `dismissible `prop in DOM with value as false and vice-versa.

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/RwMjGrB?editors=1010

### Reproduction Steps

1. Open the code pen and observe every component has a `dismissible` set to true
2. In the script we set `closable` to `false`.
3. Observe the clear icon still stays for all the components

### Reproduction Version

beta.86

### Relevant Info

Related to [4789](https://github.com/Esri/calcite-components/pull/4789)

**Comment by benelan** [comment]
@anveshmekala when I change the sample to `next` the close button is still there for all of the components. Am I doing something wrong?

```html
<script
  type="module"
  src="https://unpkg.com/@esri/calcite-components@next/dist/calcite/calcite.esm.js"
></script>
<link
  rel="stylesheet"
  type="text/css"
  href="https://unpkg.com/@esri/calcite-components@next/dist/calcite/calcite.css"
/>
```

**Comment by benelan** [comment]
Assigning this one back to dev for another look as well:
https://codepen.io/benesri/pen/bGvvXYM?editors=1010

**Comment by anveshmekala** [comment]
From the initial debugging, what I observed is `<script/>` is executed even before `connectedCallback`  which means `watchers` are not invoked when `dismissible =false` or `closable=false` in the script.

**Comment by anveshmekala** [comment]
This is a similar [issue](https://github.com/Esri/calcite-components/issues/4996#issuecomment-1210005463) where setting attributes changes props but not the other way around prior to hydration.

**Comment by anveshmekala** [comment]
can we close this one @benelan ?

**Comment by geospatialem** [comment]
Closing, as this has similar behavior as mentioned in https://github.com/Esri/calcite-components/issues/4996#issuecomment-1210005463.
