### ISSUE TITLE
Radio Tiles / Tile Select

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#505]
Updated visuals

![image](https://user-images.githubusercontent.com/14083530/85803890-13990d00-b6fd-11ea-8609-5db8e6bc49a6.png)

![image](https://user-images.githubusercontent.com/14083530/85803911-1dbb0b80-b6fd-11ea-9458-b6a48560c040.png)

![tile-select-text-overflow](https://user-images.githubusercontent.com/821864/86055109-2b7bd400-ba10-11ea-9ce7-27a1307d3db7.png)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/821864/86055244-5108dd80-ba10-11ea-82ac-f236c3633b4f.png)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/821864/86055134-359dd280-ba10-11ea-97da-1b4897916bf0.png)

Responsive:
![responsive](https://user-images.githubusercontent.com/821864/86055420-93cab580-ba10-11ea-8269-fc620aa59011.png)

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/85804025-670b5b00-b6fd-11ea-8cd1-8f23ee7173cd.png)
image area rough

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/85804118-ad60ba00-b6fd-11ea-82f9-9aad4c8bb34a.png)

**Comment by eriklharper** [comment]
- [ ] Whole item is clickable (single action)
- [ ] Separate slots for icon, title and description
- [ ] Text should push down the card (no maximum vertical height)
