### ISSUE TITLE
Changes to `autofocus` property not reflected in `calcite-input` attributes

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#5069]
### Actual Behavior

Given a `<calcite-input>` element, toggling its `autofocus` property does not add/remove its `autofocus` attribute.

### Expected Behavior

Given a `<calcite-input>` element, toggling its `autofocus` property does add/remove its `autofocus` attribute.

### Reproduction Sample

https://ember-twiddle.com/9f794f79e6c1d25b00a276a2ee8524b9

### Reproduction Steps

1. Visit the sample and wait for the `<calcite-input>` to load.
2. Use dev tools to inspect the `<calcite-input>` and the `<input>` within its shadow-dom.
3. Click the **Toggle autofocus** button repeatedly and notice the `autofocus` attribute is added/removed on the `<input>` but not the `<calcite-input>`.

### Reproduction Version

beta.86

### Relevant Info

The above sample is contrived, but it's indicative of how Ember renders templates. Given something like:

```hbs
<calcite-input autofocus={{...}} />
```

Ember ends up setting the `autofocus` property instead of the attribute, and the logic to compute the `autofocus` value could occur after the `<calcite-input>` is hydrated.

The problem with not adding/removing the `autofocus` attribute from the `<calcite-input>` is that it becomes difficult to query for the auto-focused element (i.e. `document.querySelector(['autofocus'])`). It's useful to find this element so we can call `setFocus()` on it for cases where we need to shift the focus relative to an Ember render hook (e.g. after opening a modal, visiting a new step in a stepper, etc...).

This is essentially the same issue as https://github.com/Esri/calcite-components/issues/4765, but with less confusion and a more Ember-focused test case.

**Comment by geospatialem** [comment]
@nwhittaker Would you be able to verify if the above fix works with Ember and `beta.95`? 

Wasn't able to get the [reproduction sample above](https://ember-twiddle.com/9f794f79e6c1d25b00a276a2ee8524b9) to load as a result of a API limit on the gist.
