### ISSUE TITLE
Action Menu: trigger's focus ring is overlapped 

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#5082]
### Actual Behavior

Action Menu's trigger Action needs a bit of tweaking for the focus style.

1. Using the `calcite-action-menu` component:
    https://codepen.io/benesri/pen/GRxxNPb
    ![image](https://user-images.githubusercontent.com/10986395/182709249-0f42278e-92f4-4842-bd99-3adcdf71d79b.png)
    The top of the trigger has a focus ~~ring~~ line, and the first menu action is focused.

2. Using the `menu-actions` slot from the `calcite-action-group` component:
    https://codepen.io/benesri/pen/OJvvWJy
    ![image](https://user-images.githubusercontent.com/10986395/182709603-53a5b1f9-ab7a-41b2-a622-b9f2a34a0ca0.png)
    The top and bottom have focus lines (bottom is slightly clipped) and nothing in the menu is focused

3. The `calcite-action-bar` component's overflow menu:
    https://codepen.io/benesri/pen/OJvvWJy
    ![image](https://user-images.githubusercontent.com/10986395/182710164-e995c9aa-509e-4099-a53a-05e6964a9ab9.png)
    Slight clipping of the of the focus ring and nothing in the menu is selected

### Expected Behavior

- The trigger Action's focus ring is not overlapped by adjecent Actions
- The focus is consistent between examples, either they all focus the trigger or the first menu item
- If we don't want to support Action Group's menu slots then they should be undocumented

### Reproduction Sample

multiple samples provided above

### Reproduction Steps

1. Go to the samples
2. Look at the `calcite-action-menu` trigger action

### Reproduction Version

beta.90

**Comment by benelan** [comment]
Nice! All of the focus ring clipping is resolved. 

When opening the menus, both the trigger and first menu item have focus rings. Is that correct, or should only the first menu item have the focus ring? I updated the samples in the issue body to use `next`

**Comment by driskull** [comment]
> When opening the menus, both the trigger and first menu item have focus rings. Is that correct, or should only the first menu item have the focus ring?

Its by design that it has both rings since only one truly has focus and the other is visual by arrow key.

**Comment by benelan** [comment]
Thanks for the confirming Matt. verified on `next`
