### ISSUE TITLE
Popover enhancement request

### ISSUE THREAD

**Issue by bpatterson88** [Esri/calcite-components#509]
Add setting to dismiss popover when user clicks anywhere outside the popover.

**Comment by bstifle** [comment]
Yes!

**Comment by macandcheese** [comment]
@driskull do you know if this is a config option baked into Popper? If not, we can just do what we do with `calcite-dropdown` and listen for clicks outside the container to close. Thoughts on nomenclature?

**Comment by driskull** [comment]
We don't have this built in.

We could probably add this to the `calcite-popover-manager` so there is only one event delegated to many popovers.

**Comment by driskull** [comment]
@macandcheese I noticed that in some components we are setting up event listeners for clicks to `{ target: "window" }`. For a modal, this might not be too bad since there probably won't be too many modals in an app, but for a dropdown, there could be many. 

Is there any concern with the number of events being setup on the window for the number of dropdowns that exist? Maybe one delegated event to close all dropdowns would be better?

**Comment by macandcheese** [comment]
That would probably be a good improvement - as it is, opening multiple dropdowns does not close existing open dropdowns, which would probably be the preferred UX anyway.

**Comment by macandcheese** [comment]
I think we'd maybe want the option to allow clicking on the modal bg to also allow for dismissing the modal (as an option) - right now using "Esc" key can do that (as an option), but having the ability to allow the modal to be clicked / tapped to dismiss would be nice IMO (especially for bottom-docked modals).

**Comment by driskull** [comment]
I'm not sure what Stencil recommends for reducing the amount of event listeners created by each component.

I've tried to limit the number of event listeners for Tooltips/popovers but I'm seeing that things like dropdown don't do that so I'm not sure if its a concern or not.

For example, each Dropdown instance sets up a `mouseenter` and `mouseleave` event whereas the tooltip just has one in the `calcite-tooltip-manager`

**Comment by driskull** [comment]
With tooltips, only one can be open at a time.

For popovers, I'm not sure if we should allow multiple to be open at the same time. @AdelheidF @asangma  do you know if we should allow multiple popovers open at the same time?

**Comment by AdelheidF** [comment]
> do you know if we should allow multiple popovers open at the same time?

I don't think so but how could this be enforced between component, e.g. with an app having a component in the left panel and another in the right panel that both make use of popovers?

**Comment by AdelheidF** [comment]
> Add setting to dismiss popover when user clicks anywhere outside the popover.

This is optional, correct? And opt-in?

**Comment by driskull** [comment]
> how could this be enforced between components,

The popover would do a `document.querySelectorAll` to get all popovers and close them. I'd have to see if it would work within shadowDom.

> This is optional, correct? And opt-in?

Yeah, probably optional. Currently, I'm leaning toward not doing it and leaving it up to the developer. Clicking on things like a map might not want to close the popover.

**Comment by driskull** [comment]
Installed.

**Comment by bpatterson88** [comment]
Closed via https://github.com/Esri/calcite-components/pull/551
