### ISSUE TITLE
Dropdown item/group enhancement request

### ISSUE THREAD

**Issue by bpatterson88** [Esri/calcite-components#510]
![Screen Shot 2020-04-24 at 3 28 13 PM](https://user-images.githubusercontent.com/15875886/80262127-59741f00-8641-11ea-8b33-2e7a5b46d3eb.png)
![Screen Shot 2020-06-15 at 3 23 53 PM](https://user-images.githubusercontent.com/15875886/84711927-47fe1380-af1c-11ea-89b4-9dfde9a0c612.png)
![Screen Shot 2020-06-15 at 3 24 02 PM](https://user-images.githubusercontent.com/15875886/84711933-49c7d700-af1c-11ea-8e2e-9c2c3bd25b54.png)

Extend `<calcite-dropdown-group>` to be usable outside of a dropdown component. Currently this requires some CSS hackery, and I think you lose some built in a11y features.

**Comment by macandcheese** [comment]
Yeah there are a lot of places the concept of a "selectable" list item could be re-used with similar style and functionality to dropdown (select one, select all, etc.) - tree, combobox, a faceted filter type interface in a sidebar, etc...

**Comment by macandcheese** [comment]
Pick list can be used for this in single / multiple options: https://esri.github.io/calcite-components/?path=/story/app-components-pick-list--basic. Feel free to open another issue if that component needs improvements for a use case @bpatterson88
