### ISSUE TITLE
The year input box of the date picker with Buddhist calendar jumps to wired number when backspace is hit

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-components#5101]
### Actual Behavior

When I hit backspace, the year value changes from 2565 to 830 then to 1003
![calcite year](https://user-images.githubusercontent.com/26078106/183058540-1cbaf010-2417-4146-82da-766a5c670166.gif)

### Expected Behavior

I want to switch the year to 2565, but I am not able to change that using the year input box. When I try delete and add any number, the input box jumps to a wired inrelevant number.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/date-picker/ with th locale

### Reproduction Steps

1. Open the demo website, and change the locale to th
2. Try to change the year using the year input box
3. Observe the value jumps when you try to delete or add a number

### Reproduction Version

beta.86

**Comment by jcfranco** [comment]
Possibly related to https://github.com/Esri/calcite-components/issues/3723

**Comment by eriklharper** [comment]
@geospatialem this one should also be resolved by #5459.  I tested it with the `th` lang locally and it no longer changes the value while the user is typing.

**Comment by geospatialem** [comment]
Verified in `beta.98`

![verify-input-th-locale](https://user-images.githubusercontent.com/5023024/205395135-2ff1fca7-cc8f-4f30-a8ed-38bf1756fd2b.gif)
