### ISSUE TITLE
webpack example  for 1.0.0-beta.91 does not build

### ISSUE THREAD

**Issue by jonas-dp** [Esri/calcite-components#5141]
### Actual Behavior

When running `npm start` after `npm install` on the[ webpack example code](https://github.com/Esri/calcite-components-examples/tree/master/webpack), webpack logs a couple of breaking errors.
The site won't load.

> WARNING in ./src/index.js 7:0-12
> export 'setAssetPath' (imported as 'setAssetPath') was not found in '@esri/calcite-components/dist/components' (module has no exports)
> 
> ERROR in ./node_modules/@esri/calcite-components/dist/components/Heading.js 6:0-50
> Module not found: Error: Can't resolve '@stencil/core/internal/client' in 'C:\Users\EXQ423\Desktop\webpack\node_modules\@esri\calcite-components\dist\components'
> Did you mean 'index.js'?
> BREAKING CHANGE: The request '@stencil/core/internal/client' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' 
> file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
>  @ ./node_modules/@esri/calcite-components/dist/components/date-picker-month-header.js 8:0-44 107:473-480    
>  @ ./node_modules/@esri/calcite-components/dist/components/date-picker.js 11:0-75 549:8-29
>  @ ./node_modules/@esri/calcite-components/dist/components/calcite-date-picker.js 6:0-79 8:26-36 9:28-49     
>  @ ./src/index.js 3:0-70
> 
> ERROR in ./node_modules/@esri/calcite-components/dist/components/button.js 6:0-107
> Module not found: Error: Can't resolve '@stencil/core/internal/client' in 'C:\Users\EXQ423\Desktop\webpack\node_modules\@esri\calcite-components\dist\components'
> Did you mean 'index.js'?
> BREAKING CHANGE: The request '@stencil/core/internal/client' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' 
> file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
>  @ ./node_modules/@esri/calcite-components/dist/components/calcite-button.js 6:0-70 8:22-28 9:28-49
>  @ ./src/index.js 1:0-65
> 
> ERROR in ./node_modules/@esri/calcite-components/dist/components/date-picker-day.js 6:0-102
> Module not found: Error: Can't resolve '@stencil/core/internal/client' in 'C:\Users\EXQ423\Desktop\webpack\node_modules\@esri\calcite-components\dist\components'
> Did you mean 'index.js'?
> BREAKING CHANGE: The request '@stencil/core/internal/client' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' 
> file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
>  @ ./node_modules/@esri/calcite-components/dist/components/date-picker.js 9:0-66 539:8-29
>  @ ./node_modules/@esri/calcite-components/dist/components/calcite-date-picker.js 6:0-79 8:26-36 9:28-49     
>  @ ./src/index.js 3:0-70
> 
> ERROR in ./node_modules/@esri/calcite-components/dist/components/date-picker-month-header.js 6:0-106
> Module not found: Error: Can't resolve '@stencil/core/internal/client' in 'C:\Users\EXQ423\Desktop\webpack\node_modules\@esri\calcite-components\dist\components'
> Did you mean 'index.js'?
> BREAKING CHANGE: The request '@stencil/core/internal/client' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' 
> file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
>  @ ./node_modules/@esri/calcite-components/dist/components/date-picker.js 11:0-75 549:8-29
>  @ ./node_modules/@esri/calcite-components/dist/components/calcite-date-picker.js 6:0-79 8:26-36 9:28-49     
>  @ ./src/index.js 3:0-70
> 
> ERROR in ./node_modules/@esri/calcite-components/dist/components/date-picker-month.js 6:0-102
> Module not found: Error: Can't resolve '@stencil/core/internal/client' in 'C:\Users\EXQ423\Desktop\webpack\node_modules\@esri\calcite-components\dist\components'
> Did you mean 'index.js'?
> BREAKING CHANGE: The request '@stencil/core/internal/client' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' 
> file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
>  @ ./node_modules/@esri/calcite-components/dist/components/date-picker.js 10:0-68 544:8-29
>  @ ./node_modules/@esri/calcite-components/dist/components/calcite-date-picker.js 6:0-79 8:26-36 9:28-49     
>  @ ./src/index.js 3:0-70
> 
> ERROR in ./node_modules/@esri/calcite-components/dist/components/date-picker.js 6:0-123
> Module not found: Error: Can't resolve '@stencil/core/internal/client' in 'C:\Users\EXQ423\Desktop\webpack\node_modules\@esri\calcite-components\dist\components'
> Did you mean 'index.js'?
> BREAKING CHANGE: The request '@stencil/core/internal/client' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' 
> file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
>  @ ./node_modules/@esri/calcite-components/dist/components/calcite-date-picker.js 6:0-79 8:26-36 9:28-49     
>  @ ./src/index.js 3:0-70
> 
> ERROR in ./node_modules/@esri/calcite-components/dist/components/form.js 7:0-50
> Module not found: Error: Can't resolve '@stencil/core/internal/client' in 'C:\Users\EXQ423\Desktop\webpack\node_modules\@esri\calcite-components\dist\components'
> Did you mean 'index.js'?
> BREAKING CHANGE: The request '@stencil/core/internal/client' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' 
> file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
>  @ ./node_modules/@esri/calcite-components/dist/components/button.js 11:0-60 111:8-18 114:8-17
>  @ ./node_modules/@esri/calcite-components/dist/components/calcite-button.js 6:0-70 8:22-28 9:28-49
>  @ ./src/index.js 1:0-65
> 
> ERROR in ./node_modules/@esri/calcite-components/dist/components/icon.js 6:0-110
> Module not found: Error: Can't resolve '@stencil/core/internal/client' in 'C:\Users\EXQ423\Desktop\webpack\node_modules\@esri\calcite-components\dist\components'
> Did you mean 'index.js'?
> BREAKING CHANGE: The request '@stencil/core/internal/client' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' 
> file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
>  @ ./node_modules/@esri/calcite-components/dist/components/calcite-icon.js 6:0-66 8:20-24 9:28-49
>  @ ./src/index.js 2:0-63
> 
> ERROR in ./node_modules/@esri/calcite-components/dist/components/index.js 6:0-81
> Module not found: Error: Can't resolve '@stencil/core/internal/client' in 'C:\Users\EXQ423\Desktop\webpack\node_modules\@esri\calcite-components\dist\components'
> Did you mean 'index.js'?
> BREAKING CHANGE: The request '@stencil/core/internal/client' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' 
> file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.

### Expected Behavior

No webpack errors should occur and the example site should be loaded correctly.

### Reproduction Sample

https://github.com/Esri/calcite-components-examples/tree/master/webpack

### Reproduction Steps

1. Run `npm install`
2. Run `npm start`

### Reproduction Version

1.0.0-beta.91

### Regression?

1.0.0-beta.86

**Comment by benelan** [comment]
Thanks for logging this issue. I was able to repro and I downgraded the webpack sample to `beta.86` while we investigate.

**Comment by geospatialem** [comment]
Verified `beta.86` build for the webpack example in the calcite-components-examples repo.
