### ISSUE TITLE
Popover: popovers don't close when clicking another reference-element

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#5142]
### Actual Behavior

A `calcite-popover` will close when `auto-close` is set to true and the user clicks outside the popover. But, if the user clicks on the reference element of a second popover, the first popover will remain open.

<img width="475" alt="Screen Shot 2022-08-12 at 11 14 14 AM" src="https://user-images.githubusercontent.com/55154968/184410657-5846db1e-4ad0-4c48-9465-d696e1be312a.png">

### Expected Behavior

`calcite-popover` should always close when `auto-close` is set to true.

### Reproduction Sample

https://codepen.io/joeyHarig/pen/GRQwmPa?editors=1000

### Reproduction Steps

1. Open the code pen example
2. Click on each of the popover buttons consecutively

### Reproduction Version

1.0.0-beta.91

### Regression?

Worked before deprecating `calcite-popover-manager`

**Comment by geospatialem** [comment]
Verified popovers close with `auto-close` attribute when clicking another popover, or reference element, via `next`

![verify-popover-autoclose](https://user-images.githubusercontent.com/5023024/185986975-8a334955-4ea2-43cd-b3b2-0677964c7b19.gif)
