### ISSUE TITLE
Accordion's selection mode can become stale

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#5143]
### Actual Behavior

Given a `<calcite-accordion selection-mode="single">`, then dynamically changing its `selection-mode` to `multi`, the user is unable to expand multiple sections.

### Expected Behavior

Given a `<calcite-accordion selection-mode="single">`, then dynamically changing its `selection-mode` to `multi`, the user is able to expand multiple sections.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/JjLaVNB

### Reproduction Steps

1. Visit the sample and note the accordion behaves in accordance with the `"single"` selection mode.
2. Click the **Multi selection** button and use dev tools to inspect the accordion and note it now has `"multi"` selection mode.
3. Attempt to expand more than one accordion section and note that the previously expanded section auto-collapses.

### Reproduction Version

beta.91

### Relevant Info

Toggling the selection-mode is convenient for re-purposing the accordion for different states. Specifically, Field Maps could use an accordion to show different groups of layers one-at-a-time. But, when the user enters some text to filter by, we want to expand all the sections and show the matching layers.

**Comment by geospatialem** [comment]
Verified in `1.0.4-next.3` with the following [Codepen sample](https://codepen.io/geospatialem/pen/jOpvMrw).

![image](https://user-images.githubusercontent.com/5023024/215549174-30ec505a-2114-48f1-9dbf-ee989361d634.png)
