### ISSUE TITLE
calcite-split-button (firefox):  if used as a fab button within a calcite-panel, the dropdown menu is offset in firefox

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#5146]
### Actual Behavior

The dropdown menu for the split button shows up in the wrong place in firefox

### Expected Behavior

The dropdown menu should show up directly below the button

### Reproduction Sample

https://codepen.io/kevindoshier/pen/bGvxXOB

### Reproduction Steps

1, Open the above codepen using firefox, cant repro in chrome
2. Click the dropdown notice that the menu shows up in the wrong place, not directly below the button

### Reproduction Version

beta.86

**Comment by jcfranco** [comment]
Closing as this was fixed by https://github.com/Esri/calcite-components/issues/3815#issuecomment-1209822596 and available in the latest release: https://codepen.io/jcfranco/pen/wvmEVZo?editors=1010. 🎉

**Comment by kevindoshier** [comment]
@jcfranco - this seems to be back again, with beta.95

**Comment by ethanbdev** [comment]
Also seeing this as back with popovers too, I can show in the viewer where

**Comment by jcfranco** [comment]
Thanks for reporting this. I knew it was odd this didn't come up during next testing before beta.95. 

Can you share, even if it's in pseudo code, the general structure of your components? For context, floating-ui added a way for us to add back the fix for this, but we need to define a mechanism of when to do so since it can impact performance.

**Comment by kevindoshier** [comment]
@jcfranco - the codepen in the original issue above will repro it

**Comment by jcfranco** [comment]
Closing in favor of https://github.com/Esri/calcite-components/issues/5429, which has condensed info on this. cc @geospatialem

**Comment by Olga8614** [comment]
We verified this defect on ArcGIS Online 10.3 devext and qaext site (11/3/2022) in ENU language with FF(106.0.3 )/Safari(16.1(17614.2.9.1.13.17614)) browsers. Dropdown menu of "Add" is displayed next to "Add" button on Layers pane and Basemap pane. So this defect is fixed. Thanks!
