### ISSUE TITLE
calcite-panel - calcitePanelDismissedChange is called twice

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#5152]
### Actual Behavior

 `calcitePanelDismissedChange` is called twice when clicking on close once.
 `calcitePanelDismiss` doesn't have this issue.

### Expected Behavior

 `calcitePanelDismissedChange` is called once when clicking on close once.

### Reproduction Sample

https://codepen.io/afreitag/pen/RwMqNzX

### Reproduction Steps

call the codepen and click on panel close button

### Reproduction Version

beta.86

### Regression?

yes, not sure when

**Comment by anveshmekala** [comment]
couldn't reproduce with `beta.91`  https://codepen.io/ANVESHMEKALA/pen/KKordGj?editors=1111
