### ISSUE TITLE
Rounded Focus States

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#516]
![Chip focus](https://user-images.githubusercontent.com/14083530/80429445-f7195980-88a0-11ea-8309-cc8de8112953.png)

![image](https://user-images.githubusercontent.com/14083530/80429470-08626600-88a1-11ea-82aa-81b4a5052d42.png)

Need ability to have rounded focus state @macandcheese

**Comment by macandcheese** [comment]
This will be a general enhancement that will require a mixin to concatenate existing box shadow values, if present, with a box-shadow focus style that allows for rounded borders, including other use cases like button "rounded".
