### ISSUE TITLE
Panel `zIndex` placing component underneath map after load

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#5177]
### Actual Behavior

Previously the `calcite-panel` was placed on top of the map in the tutorial. Once upgraded to beta.91, we're able to see the `calcite-panel` load, but it disappears from the display once the map loads up.

![actual behavior of calcite-panel with map in beta.91](https://user-images.githubusercontent.com/5023024/185241627-4c5bff42-71a3-4160-8889-3b7a356a166e.gif)

### Expected Behavior

The `calcite-panel` should remain placed on top of the map once loading has completed, similar to the experience in beta.86.
![expected behavior of calcite-panel with map](https://user-images.githubusercontent.com/5023024/185238003-b354c90c-1975-40f2-be0e-d1b33e6ba85e.png)

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/tutorials/create-a-mapping-app

### Reproduction Steps

1. Open the [tutorial](https://developers.arcgis.com/calcite-design-system/tutorials/create-a-mapping-app)
2. Observe the content loads, but then is hidden by the map upon load.

### Reproduction Version

beta.91

### Relevant Info

Possibly from #5058 (https://github.com/Esri/calcite-components/pull/5058/files#diff-3c801b4000dd6c6d1d5c20cc9d59a1744677b42d214f7e239d717e1edcc7780a)

### Regression?

beta.86

**Comment by driskull** [comment]
@jcfranco looks like related to this change:

https://github.com/Esri/calcite-components/commit/c01f71e5b840cac0f0b7810f027321711f87a90d#diff-2c3914b1417521aa066e81877b4fbdb75da90feb8e10bc6d0c6282124022d7e0

**Comment by geospatialem** [comment]
Verified on the [SDK site](https://developers.arcgis.com/calcite-design-system/tutorials/create-a-mapping-app).

![verified zindex with map](https://user-images.githubusercontent.com/5023024/188228690-7b92503f-2358-44bd-b90a-c680c9d1920a.png)
