### ISSUE TITLE
Date automatically changes when manually entered on certain timezones

### ISSUE THREAD

**Issue by ek070** [Esri/calcite-components#5196]
### Actual Behavior

The date in the input date picker changes when manually entered on certain timezones. As the user enters the year field, the day decreases on each entry
![input_date_picker](https://user-images.githubusercontent.com/111767399/185976616-66eb5f22-67ef-41d0-b3dd-d0a8f21df701.gif)

### Expected Behavior

Date shouldn't change as user manually enters.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-date-picker/

### Reproduction Steps

1. On windows,  go to settings
2. Select time & language
3. Change time zone to  (UTC +05:30) Chennai, Kolkata, Mumbai, New Delhi
4. Access https://developers.arcgis.com/calcite-design-system/components/input-date-picker/
5. Manually enter a date
![timezone_change](https://user-images.githubusercontent.com/111767399/185978027-69ee03b8-7635-48ee-a1a8-9a8e952e00b7.png)

### Reproduction Version

v1.0.0-beta.91

### Relevant Info

Windows 10

**Comment by jcfranco** [comment]
Possibly related to https://github.com/Esri/calcite-components/issues/3723.

**Comment by geospatialem** [comment]
Will wait for the PR related to the issue above to determine further action.

**Comment by eriklharper** [comment]
@geospatialem the changes in #3723 should resolve this one, but just to be sure if you could try reproing this on your windows machine that would be awesome and then we can close this one as resolved by #5459.  Thanks!

**Comment by geospatialem** [comment]
Verified in `beta.98`.
![verify-input-date-picker-timezone](https://user-images.githubusercontent.com/5023024/206524107-5b49b7dc-96a7-4fda-86b8-7a875ff915bd.gif)
