### ISSUE TITLE
[Card] Remove hover / press effect

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#5204]
### Description

The card has a hover / press effect right now. That doesn’t really make sense, as a card can contain one or many internally rendered hit areas.

We should remove the hover and press effects from the card.

Additionally, like we did for border radius, we should have a component level css variable to override the single (and “empty”) default shadow: https://github.com/Esri/calcite-components/issues/4855

### Acceptance Criteria

The hover and press state of card is removed.

### Relevant Info

Cc @ashetland

### Which Component

Card

**Comment by ashetland** [comment]
I'd like to second this. Can we implement it for 1.0?

**Comment by jcfranco** [comment]
Triaged to this sprint.

**Comment by jcfranco** [comment]
PR is up! 

@macandcheese @ashetland Can you confirm if we need any of these states when the card is selectable? I'm assuming we don't since pressing on the component does nothing for selection.

**Comment by macandcheese** [comment]
Correct

**Comment by geospatialem** [comment]
Verified on next
![verify-card-hover](https://user-images.githubusercontent.com/5023024/188229619-15bd3962-d588-4902-857a-0f3408bc8306.gif)
