### ISSUE TITLE
OpenCloseComponents do not emit when setting `--calcite-duration-factor`

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#5206]
### Actual Behavior

Setting `--calcite-duration-factor` to 0 allows users to skip animations, but prevents (before)open/close events from being emitted.

### Expected Behavior

All (before)open/close events to be emitted regardless of transition duration.

### Reproduction Sample

https://codepen.io/jcfranco/pen/MWVReVQ?editors=1111

### Reproduction Steps

Click on toggle and notice how events are not emitted in the console.

### Reproduction Version

@esri/calcite-components@1.0.0-beta.92

**Comment by geospatialem** [comment]
Verified on `next` 💯 

![image](https://user-images.githubusercontent.com/5023024/206047015-f4657acf-f82e-4e90-85f5-a0d57ab4f610.png)

**Comment by jcfranco** [comment]
https://github.com/Esri/calcite-components/issues/6582 demonstrated that this only addressed the issue with modal. I created a [separate issue](https://github.com/Esri/calcite-components/issues/6604) to address all open/close components.
