### ISSUE TITLE
Tree: active indicators

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#522]
![Tree active indicators](https://user-images.githubusercontent.com/14083530/80430124-97bc4900-88a2-11ea-8c8c-4cbf56f3181b.png)

1. Remove ability to use the active/hover indicator bar PLUS the •. Would be better to have only 1 of those at a time.

2. add the ability to have checkmarks in place of the • if using multi select.

**Comment by cosbyr** [comment]
@macandcheese I second this one. The tree is looking a little cluttered now in our app.

**Comment by macandcheese** [comment]
Suggestion: when lines enabled, keep JUST the bar. When lines is disabled, keep JUST the dot cc @capeoples

**Comment by macandcheese** [comment]
Multi select should also use "check" vs. single dot indicator with no lines.
