### ISSUE TITLE
[Stepper-item] vertical layout bottom padding only applied when there is a slotted element

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-components#5227]
### Actual Behavior

On vertical layout:
- No bottom padding when content is text
- 20px bottom padding when content is slotted element
<img width="339" alt="CleanShot 2022-08-26 at 11 15 47@2x" src="https://user-images.githubusercontent.com/108549080/186967318-e8dc7631-2f44-46d6-a52b-08657956bcb8.png">

### Expected Behavior

Bottom padding should be consistent regardless of content type.

### Reproduction Sample

https://codepen.io/ashetland/pen/WNzBqpv

### Reproduction Steps

1. Insert calcite-stepper
2. Add text to content slot in stepper-item. No bottom padding present.
3. Replace text with calcite-notice. 20px bottom padding is added.

### Reproduction Version

beta.93

### Relevant Info

Mac 12.5.1
Chrome 104

**Comment by geospatialem** [comment]
The Figma UI kit contains the above fix, as such the fix should be included in the January release.

**Comment by benelan** [comment]
Should the bottom padding be 20px or 0?

**Comment by ashetland** [comment]
There should always be 20px bottom padding.

**Comment by ashetland** [comment]
16px on small scale, and 24px on large

**Comment by benelan** [comment]
Seems like the only way to target text nodes via CSS is experimental: [`::target-text`](https://developer.mozilla.org/en-US/docs/Web/CSS/::target-text)

You could wrap the next node in a `span`, is that sufficient or should I try to figure something else out?
https://codepen.io/benesri/pen/poZyGJa

**Comment by benelan** [comment]
The alternative is setting the margin on the container instead of the slotted content, but then the line on the left won't extend the full height of the focus ring

![image](https://user-images.githubusercontent.com/10986395/210118732-f79c4d44-ec3d-4ea5-8b84-1ce3a6246a76.png)

**Comment by benelan** [comment]
Nevermind lol, PR coming up

**Comment by anveshmekala** [comment]
Added a prototype solution in #6385 which leverages `onSlotChange`  event and adds margin if text node with a value is rendered.  @benelan , @jcfranco   WDYT?

**Comment by geospatialem** [comment]
Verified in `1.1.0-next.2`

<img width="754" alt="Screenshot 2023-02-06 at 9 11 27 PM" src="https://user-images.githubusercontent.com/5023024/217139094-402e58b3-d299-484d-9fc6-3c3f444fe720.png">
