### ISSUE TITLE
[Button / FAB] Improve scale of internally rendered icons

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#5245]
### Description

Noted as feedback on Button / FAB - but possibly relevant in other places where icons are rendered internally.

Button / FAB of scale S, M, L all render a `<calcite-icon>` of scale S internally. We should consider bumping the scale of that icon to M when the parent Button / FAB is scale L.

Unfortunately the icons don't scale with the component sizes, but in the case of L Button / FAB - the rendered icon is too small.

### Acceptance Criteria

Button / FAB (and other components if needed) render an M size icon from provided Calcite UI Icon strings instead of S

### Relevant Info
cc @ashetland 

### Which Component

Button / FAB

### Example Use Case

Using a FAB or Button of scale L - the rendered S icon is comically small, and takes away from the intent of using a large button / fab to begin with.

**Comment by ashetland** [comment]
Is this something we want to look at for v1/ui-kit-v2?

**Comment by macandcheese** [comment]
If possible - from a code standpoint its a small change so we'd just need to look at design implications.

**Comment by ashetland** [comment]
On the Design and Figma side, we would be good to include this update to Button and FAB. Padding adjustments would be made to maintain height.

Should we look at applying this approach across Calcite? For example, Chip uses a S icon at the L scale.

**Comment by jcfranco** [comment]
Priority bumped and triaged to this sprint. cc @brittneyzwolfer @benelan @geospatialem

**Comment by adepottey** [comment]
@jcfranco Checking in on this - are we still on track to get a fix for this by mid-November?  I see the milestones have shifted a few times.

**Comment by Elijbet** [comment]
Here is a list of relevant Items with a similar issue.  What do we think about these? @ashetland @macandcheese @jcfranco 
Accordion-Item
Action
Chip
Combobox and Combobox-item
Dropdown
Input and input-date-picker
Link
Notice
Pick-list-item
Radio-group
Tab-title

**Comment by jcfranco** [comment]
@Elijbet Thanks for putting that list together. I'll defer to @ashetland @macandcheese on that.

@adepottey I meant to reply sooner, but yes, this should be available by mid-November.

**Comment by ashetland** [comment]
We discovered an issue with this related merged PR (https://github.com/Esri/calcite-components/pull/5521) that needs a design adjustment. It looks like the height of the component changes when the new 24px icon is present. Our recommendation would be to maintain the 44px height with or without icon.

We're starting to look at the rest of the list and we should have the specs outlined by the end of next week. cc: @SkyeSeitz

**Comment by geospatialem** [comment]
Re-routed to design for review.

**Comment by geospatialem** [comment]
@adepottey Thanks for following up! 

We're still aiming for mid-November, within the next week to finalize the changes. More shortly!

**Comment by geospatialem** [comment]
Verified in `beta.98` with the [following Codepen sample](https://codepen.io/geospatialem/pen/dyKLXrQ).

![image](https://user-images.githubusercontent.com/5023024/206748895-c605341c-80f6-4a45-a5c1-5df76baa844e.png)
