### ISSUE TITLE
Input: typing numbers in a different numberingSystem does not work

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#5252]
### Actual Behavior

When typing numbers while using a different numberingSystem, the previous digits are sanitized because they are not numbers (in the JS sense).

### Expected Behavior

Typing numbers does not sanitize previous characters in the input. The input should allow users to type numbers while using a different `numberingSystem` the same way it works with the default `numberingSystem` (latn).

### Reproduction Sample

https://codepen.io/benesri/pen/BaxBJJy?editors=1010

### Reproduction Steps

1. Open the repro sample above
2. Try to type "123" //-> when you type the previous character will be removed and the value will end up being "3"

For some reason you can type two of the same number before it gets sanitized:

3. Type "111" //-> the value will be "11"
4. then type "1" again //-> the value is sanitized to "1"

### Reproduction Version

beta.93

### Relevant Info

The PR that added `numberingSystem` to `calcite-input` (https://github.com/Esri/calcite-components/pull/4195) was released in `beta.83`.

**Comment by geospatialem** [comment]
Verified on `next.597`

![verified numberingSystem where characters are present in locales](https://user-images.githubusercontent.com/5023024/195703408-417dcbe0-5b19-41ed-a87a-f55e3214a695.png)
