### ISSUE TITLE
Date Picker: missing year and incorrect date order for "zh-CN" locale

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#5258]
### Actual Behavior

An Esri Community user reported that the year is missing in the header of the Date Picker when using the "zh-CN" locale. I confirmed with @annierm18 that the year is missing, and she said the date's order is also incorrect. Additionally, the first day of the week is incorrect, but thats not on us ([CLDR issue](https://unicode-org.atlassian.net/browse/CLDR-11510)).

### Expected Behavior

The year should appear in the date picker header when using the "zh-CN" locale, and the date's order should be fixed (check in with @annierm18 for more info on this part if necessary).

### Reproduction Sample

https://codepen.io/benesri/pen/NWMWqzw?editors=1000

### Reproduction Steps

1. Learn how to read Chinese
2. Go to the repro sample and read the date

### Reproduction Version

beta.93

### Relevant Info

Here is the [Community post](https://community.esri.com/t5/calcite-design-system-questions/date-picker-issue-for-local-language-setting-quot/m-p/1208697#M212).

In version `beta.90` it looks like this:
![image](https://user-images.githubusercontent.com/10986395/188026997-bad100c6-2a2b-47a8-b4ae-b56de76bba7f.png)

#5047 and #5028 both made changes to Date Picker between `beta.90` and `beta.91` but niether PR jump out as the culprit.

### Regression?

beta.90

**Comment by fendiaoxiaoshuazi** [comment]
It also happens on `ko` and `ja`.

**Comment by geospatialem** [comment]
Verified in `next.601` for `zh-CN`, `ja`, and `ko`. 

Keeping the issue open for Figma change confirmation from @ashetland and @SkyeSeitz. 

### zh-CN
![image](https://user-images.githubusercontent.com/5023024/196741243-0e120246-9a49-47e1-9127-8b26ca0ec5d4.png)

**Comment by SkyeSeitz** [comment]
Thanks, @geospatialem. This does not effect the Figma build of Date Picker.

**Comment by geospatialem** [comment]
Thanks @SkyeSeitz, closing this issue. 👍🏻
