### ISSUE TITLE
Add groupSeparator prop to Pagination

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#5259]
### Description

Currently, the `pagination` component automatically adds the language's corresponding number separator to the page value, but not all situations require it displayed as separated. Devs would need the option to toggle it to match the context of where they are used, eg. AGOL does not show separators for the content.

### Acceptance Criteria

`groupSeparator` prop is added to `pagination` which displays numbers as separated and localized when true and does not when false.

### Which Component

pagination

**Comment by geospatialem** [comment]
Verified on `next`.
