### ISSUE TITLE
Switch should not be mirrored in RTL

### ISSUE THREAD

**Issue by BLin2525** [Esri/calcite-components#5260]
### Actual Behavior

Actual result:
Switches are mirrored when in right to left mode

![image](https://user-images.githubusercontent.com/109546792/188202650-40dbd586-bedc-4ef5-9643-906ceb0ef022.png)

Expected:
Toggle buttons should not be mirrored in right to left.

Additional information:
- This behavior also occurs in AR langauge.
- This behavior also occurs on Chrome/Edge (Chromium)/Safari browsers.

### Expected Behavior

Expected:
Toggle buttons should not be mirrored on Create a feature layer dialog.

Additional information:
1. This behavior also occurs in AR langauge.
2. This behavior also occurs when selecting "Select an existing feature layer"/"Use a template" option in step 4.
3. This behavior also occurs on Chrome/Edge (Chromium)/Safari browsers.
4. This is a new feature on 9.4 qaext site.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/switch/

### Reproduction Steps

Steps:
1. Got to https://developers.arcgis.com/calcite-design-system/components/switch/
2. Toggle preview direction
3. Note the switch has flipped

### Reproduction Version

All

### Relevant Info

Additional information:
1. This behavior also occurs in AR langauge.
2. This behavior also occurs when selecting "Select an existing feature layer"/"Use a template" option in step 4.
3. This behavior also occurs on Chrome/Edge (Chromium)/Safari browsers.
4. This is a new feature on 9.4 qaext site.

**Comment by BLin2525** [comment]
[paulcpederson](https://devtopia.esri.com/paulcpederson) commented [21 hours ago](https://devtopia.esri.com/WebGIS/arcgis-portal-app/issues/37307#issuecomment-3650200)
This is something that would need to be addressed in Calcite Components. We can open an issue over there depending on what the desired outcome is.

**Comment by BLin2525** [comment]
@paulcpederson

**Comment by paulcpederson** [comment]
Updated the title and body of the issue to better adhere to the standards set in Calcite's contributing guide.

**Comment by geospatialem** [comment]
@annierm18 Is there an expected behavior with `switch` when in RTL?

We were able to verify in Apple's iOS their switch toggle is flipped, but want to confirm if that's the expected behavior, or if we should pursue disabling mirroring while in RTL.

![screenshot of ios switch toggle in rtl flipped](https://user-images.githubusercontent.com/5023024/190270406-30f98829-8be0-429f-aabf-fcb04ebb80a5.png)

**Comment by annierm18** [comment]
@geospatialem the decision to flip a switch for RTL may vary from company to company. At ESRI, we decided not to mirror switches - we have documentation on this in the "General UI mirroring rules" section of this article: https://i18n.esri.com/website/html/RTL/index.html#general_1. This issue would be considered low priority for us.

**Comment by geospatialem** [comment]
Thank you for your great guidance to help us prioritize, @annierm18!

**Comment by geospatialem** [comment]
There is a workaround where if `rtl` is set to the document **and** to `ltr` on the component the component wouldn't be mirrored.

For instance:

```html
<html dir="rtl">
  <calcite-label layout="inline-space-between">
    <calcite-switch dir="ltr"></calcite-switch>
  </calcite-label>
</body>
```

With the above workaround, and a low priority set for the change, setting to the Freezer milestone for now.

**Comment by jcfranco** [comment]
Wanted to piggy-back the above suggestion and add that updating switches individually can be avoided by using a CSS selector to set the switch direction:

```css
calcite-switch {
  dir: "ltr";
}
```

**Comment by I18nRobo** [comment]
@BLin2525 @geospatialem Is this issue okay to close?

**Comment by annierm18** [comment]
@BLin2525 @geospatialem Is this issue okay to close?

**Comment by geospatialem** [comment]
> @BLin2525 @geospatialem Is this issue okay to close?

I'm okay with closing if Bin agrees, it sounds like we're using the Esri-preferred method of implementation.

**Comment by BLin2525** [comment]
very low priority, agree to close it.
