### ISSUE TITLE
calcite-link: fix underline positioning when used with calcite-fonts v2.x

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#5262]
### Actual Behavior

The updated calcite fonts package includes expanded language support. However, because of this the font metrics have changed, making the height of each artboard taller. So even though an `e` will be the same height, when you select it, the selectable area on 2.0 fonts (which use Avenir World) will be taller. 

![bbc03ad3-ab23-4453-8244-4592f5585cb4](https://user-images.githubusercontent.com/1031758/188238347-fcb46243-6e72-4872-bb3c-e3259ed42c47.jpg)

Any components which use the inherent sizing of the content area of a glyph to place elements or backgrounds will need to be updated so they place correctly again. So far I have only noticed visual changes in `calcite-link`. 

Additionally, some messaging in the release should be included about this as these changes will necessitate a move to calcite-fonts 2.x for any devs using the newer calcite-components version. 

### Expected Behavior

Link underline and icon should align properly when using calcite-fonts 2.x.

### Reproduction Sample

https://codepen.io/paulcp/pen/Poeoeqx

### Reproduction Steps

1. Notice the low underline and high icon of the link in the codepen sample
2. Change the calcite-fonts css link to point to 1.4.0 (instead of 2.1.0)
3. See how the underline moves up and the icon moves down.

### Reproduction Version

n/a

### Relevant Info

It may be possible to do this in a backwards compatible way? I will play around a bit.

**Comment by jcfranco** [comment]
@paulcpederson Have you had any luck in finding a backwards-compatible way to move forward with this?

**Comment by paulcpederson** [comment]
Haven't had the cycles to look into this, will try to carve out some time as the release wraps up.

**Comment by jcfranco** [comment]
@paulcpederson's fix has been installed! Many thanks! 🎉

Since `calcite-link` was the only component affected by this (so far), can we update the title to reflect this? We can address related issues from other components separately. 

@geospatialem I went ahead and merged this w/o screenshot tests as Screener has been acting up recently. I can help with additional manual testing if necessary.

**Comment by paulcpederson** [comment]
updated title, agree any further issues should be their own thing

**Comment by geospatialem** [comment]
Verified in `beta.98` ✔️ 

![image](https://user-images.githubusercontent.com/5023024/202219163-ef932b49-3afb-4706-a675-d077c84c9a29.png)
