### ISSUE TITLE
Modal: Add backgroundColor property

### ISSUE THREAD

**Issue by cosbyr** [Esri/calcite-components#527]
- We would like the ability to conditionally change the background color of the content slot of the Modal
- If it makes sense to have separate properties for the modal footer and header that may be helpful to other users down the line as well but we are primarily concerned with the content div.

While the background-color attribute could be added programmatically to the shadowDom modal__content div I think it would be easier for users as a property of calcite-modal.

**Comment by macandcheese** [comment]
Would having the choice between white and our light grey background value (#f3f3f3) work here (and reciprocal dark theme value)?

**Comment by cosbyr** [comment]
@macandcheese I think that would work, though it might be nice to be able to put in your own hex value. Coincidentally we were going to use (#f4f4f4) :)

**Comment by paulcpederson** [comment]
@cosbyr ok, `background-color="grey"` should give you the official calcite off-white background color as of v1.0.0-beta.33

**Comment by cosbyr** [comment]
@paulcpederson thanks!
