### ISSUE TITLE
Auto focus modal content by default

### ISSUE THREAD

**Issue by janett-baresel** [Esri/calcite-components#5270]
### Summary

When using a modal dialog the content is not auto focused.

### Actual Behavior

Opening a modal from a button will not auto focus the content. The focus stays in the document and continues "behind".

### Desired Behavior

When opening a modal dialog the focus is automatically moved to the content or close button. Basically, call setFocus by default when the modal is opened. I cannot think of any user who wouldn't want this behavior.

### Reproduction Sample

https://codepen.io/Programmine/pen/RwyNpJe

### Reproduction Steps

1. create calcite-button that has an onclick event
2. onclick creates modal dialog and opens it
-> focus remains on button and behind modal

### Reproduction Version

latest

### Relevant Info

reproduced on chrome

<sup>SV-CH</sup>

**Comment by janett-baresel** [comment]
@jcfranco I would like to change this from a bug report to an enhancement suggestion. Would I need to create a new ticket and close this one?

**Comment by benelan** [comment]
Hi Jannet, we can use this issue, I just changed the labels. Thanks!

**Comment by geospatialem** [comment]
Verified the `modal` auto focus  in `beta.98` across Chrome, Firefox, and Edge browsers.
