### ISSUE TITLE
calcite-input: required and type attributes should behave like HTML input

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#5284]
### Actual Behavior

- The `required` attribute does not prevent form submission when the value is empty.
- The `type` attribute does not prevent form submission when value is invalid (ex: email)

### Expected Behavior

- When `required` attribute is present and value is empty (""), form submission should be blocked.
- When `type` attribute is set to "email" and value is not a valid email address, form submission should be blocked.

### Reproduction Sample

https://codesandbox.io/s/calcite-input-required-type-email-nxrvh7?file=/src/App.js

### Reproduction Steps

1. Submit form without entering any values.
2. Form submission is blocked by the HTML input.
3. Enter valid email address into HTML input.
4. Submit form.
5. Form submission is NOT blocked by invalid calcite-input value.

### Reproduction Version

beta.93

### Relevant Info

I'm in the process of upgrading from an old version of calcite-components (43), where this behavior previously worked.

### Regression?

beta.43

**Comment by benelan** [comment]
FWIW its not just Input, the `required` property doesn't work as expected for other form components either, e.g. https://codesandbox.io/s/cc-form-validation-jqqrge

I'm pretty sure it's due to #2777. We are planning to do a big form validation epic after v1 where this will be addressed.

As a workaround, users can do their own form validation, here is a small example: https://codepen.io/benesri/pen/xxzaNKW

**Comment by jcfranco** [comment]
Just checked and there is a bug preventing some form components from providing type info to the form, but the rest should be working as expected. One thing I noticed in the repro cases was the lack of `name`. The `name` attribute is required for our components to participate in form submission. I don't think we doc this at the moment, which can lead to confusion. cc @geospatialem

**Comment by geospatialem** [comment]
Verified with the [Codesandbox sample](https://codesandbox.io/s/calcite-input-required-type-email-nxrvh7?file=/src/App.js) with React `1.0.1` and adding an accompanying `name` attr.
