### ISSUE TITLE
Performance optimization for calcite list and floating UI

### ISSUE THREAD

**Issue by sam11927** [Esri/calcite-components#5286]
### Description

Several things are happening so please feel free to add anything if I missed it.

1. Calcite list is not performative when there are components containing floating UIs nested into the calcite-list-item. We believe this is because `reposition` is being called too many times and likely should be debounced.
2. Though better, similar issues are seen with the `calcite-value-list`. 
3. The primary concern for the floating UI optimization was with the `calcite-dropdown`, but I suspect a similar thing might be the case with other components that use `reposition` in a similar way (potentially like popovers or other floating elements).

### Acceptance Criteria

For this use case, we should be able to have large amounts of items in a calcite list or value list each with a floating ui component nested in it (e.g. a list item with a calcite-action at the end that opens up a dropdown), and not see intense performance hits from this. Currently, we see performance hits after only 5 items for a calcite list with a range of 6-244 seconds for TTI. We see better performance for the value list with that range about halved: 3-122 seconds for TTI. Ideally, with large numbers of items we would have a more reasonable TTI.

### Relevant Info

See the codepens in `Example Use Case` to see what an example would be where we have a list item with a floating UI element attached to it.

### Which Component

`calcite-list`, `calcite-list-item`, `calcite-value-list`, `calcite-value-list-item`, `calcite-dropdown`.

### Example Use Case

https://codepen.io/sam11927/pen/gOzPbPW?editors=1000
and
https://codepen.io/sam11927/pen/xxjZbOx?editors=1010
should both be more performative. In the above codepens, we only use 20 items, but a realistic use case could have over 100 items, so it should be performative in those cases as well.

**Comment by jcfranco** [comment]
Triaged per our convo to focus on a stopgap while we dig into the issue.

**Comment by ethanbdev** [comment]
Adding on that I am seeing poor performance with the `input-time-picker` when it is inside a custom element

**Comment by jcfranco** [comment]
@ethanbdev @sam11927 We picked up the most recent version of `@floating-ui/dom`, which reverted a PR that was causing the performance hit. There was another PR that landed before that fixed additional shadow DOM positioning issues. Local testing looks good, but can you test w/ the latest `next` and check for floating-ui/popper issues you may have encountered before? FWIW, using `overlay-positioning=fixed` helps fix some positioning issues as well.

**Comment by sam11927** [comment]
My testing with `next` last Friday still showed a performance dip with a small-moderate amounts of items, but I will test again and post. I am using 100 items as a benchmark in the codepens, though many users may have more than this.

**Comment by sam11927** [comment]
TTI for 300 items is still around 1 second (maybe a bit more) for value-list, which is way better than it was previously. 

Calcite-list still has a very long TTI but for now in analysis we can just use the value-list

**Comment by jcfranco** [comment]
This should be addressed by #5399.

**Comment by sam11927** [comment]
Thank you for the fixes @jcfranco

**Comment by geospatialem** [comment]
Verified in `beta.96`.

### Before fix
![verify-performance](https://user-images.githubusercontent.com/5023024/198315731-d0996de1-7a7e-467c-b2b8-93e4a9392c6a.gif)

### After fix
![verify-performance-1](https://user-images.githubusercontent.com/5023024/198314879-f6968468-2b51-4492-9ffb-7581a679bfef.gif)
