### ISSUE TITLE
[Rating] Unexpected component behavior after setting value as user

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#5312]
### Actual Behavior

As an end-user, after interacting with the rating, there is unexpected behavior that occurs after setting (or clearing) a user-set value.

https://user-images.githubusercontent.com/4733155/189963194-da8ee607-f4a8-46bf-8e21-9b36d2aeef64.mov

- If I've set, or set and cleared, the component will reset on a subsequent keyboard-invoked focus.
- I cannot immediately use space or enter to set the value again, I need to navigate off and back to the desired rating.

### Expected Behavior

- I would not expect subsequent component focuses to reset the value, once I as a user have set it.
- I would expect to be able to toggle between set / clear value while remaining focused on the same rating. 

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/ZEoBWGj?editors=100

### Reproduction Steps

For clear issue:
- Open codepen
- Set a value on a rating
- Use keyboard to leave / return to component focus
- Rating will be cleared

For not being able to "re select" issue:
- Open codepen
- Set a value on a rating
- Use keyboard to clear value
- Attempt to use same key to set value again
- Value will not set
- Navigate to an adjacent star element, and return
- Value will be set-able with the same key.

### Reproduction Version

91

**Comment by driskull** [comment]
@macandcheese the codepen seems to be incorrect for the issue.

**Comment by macandcheese** [comment]
> @macandcheese the codepen seems to be incorrect for the issue.

Wrong link - updated. It's just a single instance of a rating component, but it illustrates the issue.

**Comment by driskull** [comment]
I'm not sure we should allow toggling between a set value and no value when hitting enter or clicking. Radio buttons don't usually work like that.

If we want, maybe we could support the `escape` or `delete` key to reset to no value?

**Comment by driskull** [comment]
I'm also not quite sure while hitting enter or space needs to emit an event. It seems like a user already clicked or navigated to the value with the arrow keys and the emit has occurred. Any idea on why we need to emit again on enter or space?

**Comment by macandcheese** [comment]
Agree on not needing the extra events while navigating. I do think enter / space / click again could be expected to clear the rating, but will defer to @geospatialem there for a11y.

**Comment by driskull** [comment]
> I do think enter / space / click again could be expected to clear the rating

Can you elaborate on why? These are radio buttons and I don't think there is a way to clear radio buttons

**Comment by macandcheese** [comment]
Because as a user I may want to clear the rating I’ve just set. This was the enhancement issue where it was added: https://github.com/Esri/calcite-components/issues/3043

I know there’s the internal hidden input / analog to the radio control but I’m not sure the UX is 1:1. Without the app building their own reset control, as a user I can’t clear my rating.

**Comment by driskull** [comment]
hmmm because the way its currently set up, it doesn't really clear the value it just sets it to zero. Assuming zero is a valid value to submit.

**Comment by macandcheese** [comment]
Yeah, if we want to remove that current "unset my rating" functionality, an option could be to have "no stars" as a navigable item alongside 1-5,  but to your point there is a difference between 0 and no value. I've seen both in the wild, components that let a user "re-select to clear", and components that have a "0 step".

**Comment by driskull** [comment]
Yeah, not sure how to proceed with this one so putting it back in the box.

Issues to discuss

- Should we allow unsetting value?
- If we allow unsetting value, should it set the value to null instead of 0?
- Currently, all inputs are focusable. Ideally, only one input should be focusable. You can notice this by shift-tab back to a rating.
- Enter/Space always emit event even if the value is already set to 0.
- tabbing out of component always emits value even if no change.

**Comment by geospatialem** [comment]
> I do think enter / space / click again could be expected to clear the rating, but will defer to @geospatialem there for a11y.

For a11y I'd expect clearing of the component from a separate element from the stars. It could make it a bit more clear, both visually and for AT users to distinguish the value and what is set in the component.

Perhaps something similar to [W3C's star rating example](https://www.w3.org/WAI/tutorials/forms/custom-controls/#a-star-rating)?

**Comment by geospatialem** [comment]
Accessibility works incredibly great, nice work! 👍🏻 

@alisonailea Noticed using the `Down arrow` key moves focus to the the next star and `Up arrow` to the previous star when testing via `next.727` with the [following Codepen](https://codepen.io/geospatialem/pen/GRBOZJo), is that the expected behavior? I'd expect the opposite behavior, but can update the docs if that's the expectation. cc @macandcheese

**Comment by geospatialem** [comment]
Opened a new issue to tackle in a future upcoming release, the above issue has been verified.
