### ISSUE TITLE
calcite-input: icon-flip-rtl prop is not working

### ISSUE THREAD

**Issue by svlesiv** [Esri/calcite-components#5316]
### Actual Behavior

 Adding `icon-flip-rtl` property to the `calcite-input` component with an icon will not position the icon to the right.

<img width="927" alt="Screen Shot 2022-09-13 at 1 37 52 PM" src="https://user-images.githubusercontent.com/35533801/190004944-9a824a9b-0371-4ad6-af83-542effea67b8.png">

### Expected Behavior

The icon will be positioned to the right within the input field.

### Reproduction Sample

https://codepen.io/svlesiv/pen/poEjVjR

### Reproduction Steps

Add `icon-flip-rtl` property to the `calcite-input` component with an icon. Adding `icon-flip-rtl` property will not position the icon to the right.

```js
<calcite-input alignment="end" icon-flip-rtl icon="2d-explore" label="text-label" />
``` 

### Reproduction Version

beta.93

**Comment by jcfranco** [comment]
@svlesiv Maybe it's a doc issue, but the prop is working as expected. Setting `icon-flip-rtl` won't flip the icon automatically. The component has to be in an RTL context for the flip to happen: https://codepen.io/jcfranco/pen/ExLNPoL

Sidebar: unlike `input`, you need closing tags for `calcite-input`.

**Comment by svlesiv** [comment]
Great, thank you!
