### ISSUE TITLE
Slider enhancement requests

### ISSUE THREAD

**Issue by bpatterson88** [Esri/calcite-components#532]
Dashboards is requesting the following for the slider:

![Screen Shot 2020-04-29 at 4 33 29 PM](https://user-images.githubusercontent.com/15875886/80656917-2cf04680-8a37-11ea-8cc0-b579e61dc116.png)

- Prevent handle labels from extending past the edge of the slider. This keeps the UI intact when dealing with compact components and longer numbers.
- Concat handle labels into a hyphenated range when they get close together. Readability concern.
- Hide rail labels when handle overlaps. Readability concern.
- Allow slider to have an inactive state. Handle and value is previewed on hover and added to the rail on click.
- (possibly not a direct slider concern) Add support for histogram visualization attached to slider. Histogram should show which portion is active as determined by the slider.

Let me know if these should be broken out into individual tickets

**Comment by macandcheese** [comment]
Thanks for opening, I think these are good additions.

Can you add some screenshots of issue / mockup of solution for the requested items?

Histogram support should be opened as a separate issue IMO, it might be out of scope for this component but we can take a look at what that might take.

The other ones seem like doable improvements!

**Comment by bpatterson88** [comment]
@macandcheese Added screenshots as well as an additional request. Will open another ticket for the histogram.

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/80658606-61660180-8a3b-11ea-95a4-d835207469bc.png)
some other ideas.

**Comment by bpatterson88** [comment]
> @bpatterson88 what font-size are you proposing for the start/end labels? do those disappear if the handles are on top of them?

I'm mocking them with 12px and it seems to work well enough, not stuck on that though. They should disappear smoothly when a handle goes over the top... I'm picturing some kind of gradient washing over them.

**Comment by bstifle** [comment]
hahaha i am so confused

**Comment by bstifle** [comment]
these 2 issues inception

**Comment by macandcheese** [comment]
Thanks for the screenshots and comments, I think the slight overlap of the handles Bryan and Ben showed might work better than stacking - I imagine that transition could be a little jarring and the resulting hitboxes could be tough to manage. The "number-number" approach for handle label seems to always show the points as well which is nice

**Comment by bstifle** [comment]
yeah i really like the number-number thing too

**Comment by eriklharper** [comment]
> Prevent handle labels from extending past the edge of the slider. This keeps the UI intact when dealing with compact components and longer numbers.

Does the `precise` option handle the concern here?  
![image](https://user-images.githubusercontent.com/821864/82268642-61fc0480-9924-11ea-9e0d-209f132595c4.png)

Notice that when the numbers get really close together, because they render on completely separate horizontal planes, it makes them very readable without any additional work.

**Comment by bstifle** [comment]
would be nice to keep them both underneath the bar, some kind of fade out when the numbers get close. prefer the last handle used and show that number

**Comment by eriklharper** [comment]
I see, so should the behavior of the `precise` option simply be updated to display it like this?
![image](https://user-images.githubusercontent.com/821864/82269276-029ef400-9926-11ea-8cdd-352941929e76.png)
Or should the `precise` option still retain its current behavior and we just add the hyphenation for cases when `precise = false`.  Does this also mean that handle labels should move from above the handle to below in all cases as well?

**Comment by bstifle** [comment]
![](https://user-images.githubusercontent.com/821864/82269276-029ef400-9926-11ea-8cdd-352941929e76.png)

**the hyphen and both handles and numbers underneath is a good display**

"I see, so should the behavior of the precise option simply be updated to display it like this?"
- **Only when using a graph.**

"Does this also mean that handle labels should move from above the handle to below in all cases as well?"
- **no only when using graph**

**Comment by patrickarlt** [comment]
It would also be nice if we could use some of these enhancements with just `<calcite-slider>` and not just `<calcite-graph>`. We have a the following UI on an upcoming project:

![2020-05-22_12-32-45](https://user-images.githubusercontent.com/378557/82703233-58c2ae80-9c28-11ea-9488-10b21b3b6f95.png)

So it would be to:

* Specifcy slider position on, over or under the track
* Allow clicking to edit the number in the slider

**Comment by macandcheese** [comment]
Re: @patrickarlt last point - example : https://github.com/Esri/calcite-components/issues/304

**Comment by eriklharper** [comment]
I just noticed that numbers are displayed in the typical English locale with the comma at the thousandth place and I was wondering if we are to support all possible locales when it comes to number formatting via something like `Number.toLocaleString`?  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
