### ISSUE TITLE
calcite-slider throws error

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#5321]
### Actual Behavior

When clicking left of handle on slider an error occurs and no calciteSliderInput event gets called. After that nothing works anymore. This started with beta.91.

![image](https://user-images.githubusercontent.com/44481292/190230955-f1cd3a76-73d0-4f83-a7b6-20eee7de5740.png)

### Expected Behavior

no errors

### Reproduction Sample

https://codepen.io/afreitag/pen/ExLNOeN

### Reproduction Steps

open the codepen and the browser console
click twice on the right side of the handle, all good
click left of the handle and you'll see the error

### Reproduction Version

beta.93 and latest next

### Regression?

beta.90

**Comment by RalucaNicola** [comment]
I ran into the same issue with the calcite react components. I have a repro here: https://codesandbox.io/s/brave-benz-cfi8vg?file=/src/index.js

**Comment by AdelheidF** [comment]
looks good with next.603
