### ISSUE TITLE
Panel: Escape key closes panel even when closable is true

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#5329]
### Actual Behavior

Panel: Escape key closes panel even when closable is true

### Expected Behavior

Panel: Escape key should only close panel if the panel is closable

### Reproduction Sample

https://codepen.io/driskull/pen/MWGJrga?editors=1010

### Reproduction Steps

1. Open codepen
2. Focus on panel
3. Hit esc key

### Reproduction Version

Latest

**Comment by driskull** [comment]
@benelan @jcfranco can we triage this one?

**Comment by jcfranco** [comment]
Triaged! 🚀

**Comment by geospatialem** [comment]
Verified in beta.95
