### ISSUE TITLE
Button neutral and outline uses wrong color for border

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#5331]
### Actual Behavior

When Button is `appearance="outline"` and `color="neutral"`, the border color is set to `foreground-3`.

### Expected Behavior

Border color should be `border-1`.

### Reproduction Sample

https://codepen.io/mtb-alan/pen/vYjgrJE

### Reproduction Steps

Inspect the button in the example.

### Reproduction Version

latest

**Comment by asangma** [comment]
cc @ashetland

**Comment by asangma** [comment]
cc @macandcheese

**Comment by ashetland** [comment]
@asangma Sadly, the codepen is blank, but I agree with this one.

**Comment by asangma** [comment]
LOLz. I pasted the wrong url.

**Comment by macandcheese** [comment]
👍 agreed

**Comment by geospatialem** [comment]
Verified in `next.727` with the following html:

```html
  <calcite-button appearance="outline" kind="neutral">Test</calcite-button>
```

![image](https://user-images.githubusercontent.com/5023024/213256574-be5ca2af-471d-4503-aacf-074937cd19dd.png)
