### ISSUE TITLE
Fix(tabs): bordered and center layout combination does not work

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#5345]
Related Issue: [#3682](https://github.com/Esri/calcite-components/issues/3682)

### Actual Behavior

The component doesn't currently support the `bordered` + `center` combination. I checked back to beta84 and it seems like it never did. `bordered layout="center"` just ignores the `bordered` attribute.

### Expected Behavior

bordered and layout="center" combined props should display the intended design.

### Reproduction Sample

https://codepen.io/elijbet/pen/YzLQPzN?editors=1100

### Reproduction Steps

Observe the displayed difference in the reproduction sample.  

### Reproduction Version

beta.94 back through beta.84

**Comment by geospatialem** [comment]
Possibly conduct a fix in coordination with #5445

**Comment by geospatialem** [comment]
Verified in `beta.98` 👍🏻 

![image](https://user-images.githubusercontent.com/5023024/202220490-c8ba03eb-c1bc-46d9-8295-f37d47317fa9.png)
