### ISSUE TITLE
Slider with histogram

### ISSUE THREAD

**Issue by bpatterson88** [Esri/calcite-components#535]
![Screen Shot 2020-04-29 at 4 38 00 PM](https://user-images.githubusercontent.com/15875886/80657180-cc153e00-8a37-11ea-8c87-45e5d822a33f.png)

Visualize the distribution of data points along a slider with a histogram. This visualization will help users predict how using a slider will effect their Dashboard. This will also help provide feedback when a slider has been filtered by showing the changing data point distribution.

**Comment by bstifle** [comment]
what happens when the handle numbers get close? @bpatterson88

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/80658298-a3db0e80-8a3a-11ea-9910-737c9a73564b.png)
rough idea.... def not sold on this but maybe something to ponder

**Comment by bpatterson88** [comment]
@bstifle Definitely need to account for it. I think probably concat with a hyphen? I opened a ticket for that, and a few other general slider requests: https://github.com/Esri/calcite-components/issues/532

**Comment by bstifle** [comment]
dope! added to that, disregard on this

**Comment by bstifle** [comment]
@bpatterson88 what font-size are you proposing for the start/end labels? do those disappear if the handles are on top of them?

**Comment by macandcheese** [comment]
@bpatterson88 can you post any other requirements you may have for this? do step increment values affect the curved nature of histogram - etc. Thanks!

**Comment by AdelheidF** [comment]
As a FYI, the JS-API has a HistogramRangeSlider:

<img src=https://user-images.githubusercontent.com/44481292/81751864-25806280-9465-11ea-8c6f-fb3aa7de8b7a.png width=250/>

Not much data has a nice curve like you show.

**Comment by macandcheese** [comment]
Added in last release - @AdelheidF example should be an improvement to `calcite-graph` - closing this one.
