### ISSUE TITLE
Color chips

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#536]
lets get all the color chips in there!

(or should we call these labels?)

![image](https://user-images.githubusercontent.com/14083530/80672164-cbdd6880-8a60-11ea-8ae5-0f00ca10cf69.png)

**Comment by macandcheese** [comment]
We already have `calcite-label` - probably using the "non-dismissible" version of `calcite-chip` here makes sense.

**Comment by evanmosby** [comment]
+1 on this one. Monitor could use this as part of facet filtering... especially on a gray background.
