### ISSUE TITLE
[Tree] Content density factor, remove left padding when list is non-nested

### ISSUE THREAD

**Issue by dmartini-zrh** [Esri/calcite-components#5374]
## Description

This ticket concerns 2 enhancement requests to the Tree component.
They both come from specific use cases but might be beneficial for additional ones.

### Actual Behavior
1. When using a Tree component in combination with action buttons for each item of the list, the latter can appear very narrowly spaced.  In particular, this is the case when the `scale` is set to `s`
<img width="2322" alt="Screenshot 2022-09-22 at 11 56 54" src="https://user-images.githubusercontent.com/113533121/191717723-a1d05611-6423-406b-80c7-6bbbd5410f90.png">

2. If the Tree component displays a non-nested list, the left space – where collapse controls (e.g. chevrons) would appear – is of no use.
<img width="1662" alt="Screenshot 2022-09-22 at 11 57 05" src="https://user-images.githubusercontent.com/113533121/191717761-c5cbf605-e29e-4930-85d5-3ce3737ae7ad.png">

###  Desired Behavior
1. The Tree component might have a `density` variable to choose between a `default` or "compact" and a `cozy` or "roomy" layout. In particular use cases, increasing visual separation could also be beneficial to accessibility.
<img width="2087" alt="Screenshot 2022-09-22 at 13 10 53" src="https://user-images.githubusercontent.com/113533121/191732051-25fde892-ce76-4c38-9787-239f5938ab0f.png">

2. When the Tree component presents a non-nested list, the left padding might be hidden, resulting in more space-efficient layouts.
<img width="2825" alt="Screenshot 2022-09-22 at 13 11 28" src="https://user-images.githubusercontent.com/113533121/191732390-de4c2422-faba-4419-83e5-568befb18ece.png">

### Which Component

[Tree](https://developers.arcgis.com/calcite-design-system/components/tree/)

### Esri team

ArcGIS Scene Viewer

**Comment by macandcheese** [comment]
Agreed, this would be great to look at, I think there's a lot of valid changes suggested here.

Removing the padding when there is no nested content makes a lot of sense to me. I struggle a bit with the "cozy / compact" terminology - to me cozy insinuates a density that is higher than default. If possible, finding a good default for s/m/l without the need for a secondary layout property would be ideal. Another option we could look at is a css variable for spacing, but even that feels like a workaround.

cc @ashetland

**Comment by dmartini-zrh** [comment]
@macandcheese thanks for your reply. 
Exact terminologies and defining whether `density` and `size` shall be distinct or a single property are design topics that I wanted to suggest... but go beyond this ticket  😉
My idea of "cozy / compact" refers to other design systems such as SAP's [Fiori](https://experience.sap.com/fiori-design-web/cozy-compact/) (which basically recommends "cozy" for touch devices) and Microsoft's (e.g. Outlook's UI density settings)
<img width="393" alt="Screenshot 2022-09-23 at 14 04 20" src="https://user-images.githubusercontent.com/113533121/191956594-8edc19ec-6106-43e8-b2aa-d6db24722578.png">

**Comment by macandcheese** [comment]
Yep, that context makes sense. Usually that ends up being an app-level or across multiple component type of user selection, so perhaps applicable at some point outside of tree specifically. 

Maybe in this case if scale updates aren’t sufficient a line item space css var could work.

**Comment by geospatialem** [comment]
Related #6632

**Comment by ashetland** [comment]
Padding for a non-nested list is outlined in issue #7100 as part of epic #6632. Tree Items now support an `actions-end` slot (issue #3127) which will cause Tree Items to increase in height, adding more visual separation between items than is outlined above. Spacing is being wrapped into token work for now.
