### ISSUE TITLE
`Action Bar` width changes when an `Action` gets an indicator.

### ISSUE THREAD

**Issue by LanceStasinski** [Esri/calcite-components#5375]
### Actual Behavior

The width of an `Action Bar` component changes when an `Action`'s indicator is toggled which leads to distracting layout changes.
![190012279-aadc3751-c757-4efe-a1dc-4937077d2ca8](https://user-images.githubusercontent.com/57465065/191782499-140232ba-a5df-4073-98e2-76ce6d5515b3.gif)

### Expected Behavior

I expect the width of the `Action Bar` to remain constant when an `Action`'s indicator is toggled.

### Reproduction Sample

https://codesandbox.io/s/proud-meadow-eo44tw?file=/src/styles.css

### Reproduction Steps

1. Create an `Action` component with a toggle-able `indicator`
2. Nest that `Action` component within an `Action Group` that is nested with an `Action Bar`
3. Tie the `toggle indicator` action to an element outside of the `Action Bar` - probably a button.
4. Click the element that triggers the `toggle indicator` action.
5. Notice how the width of the `Action Bar` increases.

### Reproduction Version

1.0.0-next.541

### Relevant Info

MacOS, Chrome version 105.0.5195.102
Calcite Components version 1.0.0-next.541

We solved this issue temporarily by adding a pseudoelement that takes the place of the `indicator` when `indicator=false`. The issue may be fixed by keeping the `indicator` psuedoelement as a permanent fixture within the component by setting `visibility: hidden;`, and only changing the visibility when `indicator=true`.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
@ashetland + @SkyeSeitz: What are your design thoughts of `action-bar` where the indicator is added in particular use cases? 

In the sample above the component is expanded, and the indicator is added to the text line with the most characters.

**Comment by LanceStasinski** [comment]
In case it's of use, we fixed this by modifying the CSS as such: 
```css
calcite-action-bar[expanded] calcite-action:not([indicator])::after
  display: inline-block
  content: ''
  width: 1rem
```

**Comment by driskull** [comment]
What if we changed the indicator to always be in the same place?

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1231455/198148210-7498dad4-eab9-481a-b42a-a5c58de7b4be.png">


cc @asangma

**Comment by ashetland** [comment]
My vote would be to account for the additional space of the indicator rather than keep it attached to the icon. When it's expanded, the indicator feels out-of-place if it's still on the icon.

**Comment by SkyeSeitz** [comment]
I would agree with @ashetland. Also curious if there can be an Action Bar with no icons and just text?

**Comment by jcfranco** [comment]
> Also curious if there can be an Action Bar with no icons and just text?

Technically, yes (except for the expand/collapse action), but I don't think this is a supported configuration. Looks odd to me.

![Screenshot 2023-03-03 at 5 26 33 PM](https://user-images.githubusercontent.com/197440/222868168-9c058cc2-92b8-451b-8e98-ca8753978436.png)

If the actions used in action-bar/pad are meant to always use their icon, we should update the doc to indicate this. cc @geospatialem 

--- 

Seems to me like this is ready for implementation. @SkyeSeitz @ashetland Can you confirm?

**Comment by jcfranco** [comment]
[Took a stab](https://github.com/Esri/calcite-components/pull/6562) with the current information. LMK if this needs further design discussion.

**Comment by geospatialem** [comment]
Verified on `master`

![verify-action-bar-indicator-width](https://user-images.githubusercontent.com/5023024/225363118-10a72648-3d22-4e93-b886-0213309b219c.gif)
