### ISSUE TITLE
Pick list filter is missing icon in Firefox 

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#5381]
### Actual Behavior

The pick list filter icon is not displaying in Firefox but it is visible in other browsers

Firefox
<img width="1000" alt="Screen Shot 2022-09-23 at 7 29 35 PM" src="https://user-images.githubusercontent.com/5892789/192069296-6f256f9f-fa38-448e-8bb5-ced16982a39e.png">

Chrome
<img width="1003" alt="Screen Shot 2022-09-23 at 7 29 52 PM" src="https://user-images.githubusercontent.com/5892789/192069292-57aec884-bec1-4df2-8afb-dec0466ea638.png">

### Expected Behavior

Filter icon displays in all browsers

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/pick-list/

### Reproduction Steps

1. Enable filter in doc demo
2. See there's a missing icon

### Reproduction Version

beta.94

### Relevant Info

Firefox

### Regression?

beta.86

### Esri team

ArcGIS Enterprise

**Comment by jcfranco** [comment]
This should be fixed via https://github.com/Esri/calcite-components/issues/5417.

**Comment by geospatialem** [comment]
Verified on the master branch with Firefox. 👍🏻 

![verified pick list icon in Firefox](https://user-images.githubusercontent.com/5023024/196208588-9ceabdc0-b3e1-4558-8774-e74867657dcf.png)
