### ISSUE TITLE
At min level 0, slider handle appears above scale, and label ticks no longer display 0 value

### ISSUE THREAD

**Issue by capegreg** [Esri/calcite-components#5382]
### Actual Behavior

Issue 1. 
As of 1.0.0-beta.94, the slider handle is positioned above the scale when value is 0.

Issue 2. 
Handle jumps to scale line as slider value increases.

Issue 3.
The minimum tick level 0 no longer displays.

![image](https://user-images.githubusercontent.com/1051118/192314048-3eb7ba7e-f83d-4cf4-b901-29a7054a3706.png)

### Expected Behavior

In previous version 1.0.0-beta.93, handle positioned on same line as scale, and min tick level 0 displayed.

![image](https://user-images.githubusercontent.com/1051118/192314246-89f5ce33-4b63-43cc-bda1-eea9d4572389.png)

### Reproduction Sample

https://codepen.io/capegreg/pen/XWqzvxy?editors=1010

### Reproduction Steps

1. Increase slider value. Handle jumps to scale line.

### Reproduction Version

1.0.0-beta.94

### Regression?

1.0.0-beta.93

### Esri team

N/A

**Comment by geospatialem** [comment]
Looks like a regression from https://github.com/Esri/calcite-components/pull/5138 cc @Elijbet

**Comment by anveshmekala** [comment]
I stumbled up on this one while working on #4721 .

**Comment by geospatialem** [comment]
Verified on `next` ✔️
