### ISSUE TITLE
Tile select: checked state border is hidden by other tiles 

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#5389]
### Actual Behavior

<img width="921" alt="Screen Shot 2022-09-27 at 8 54 17 AM" src="https://user-images.githubusercontent.com/1031758/192575326-752eddd4-fffc-4d05-892a-60914741f728.png">

Blue outline for checked tiles is underneath subsequent tiles.

### Expected Behavior

Should be able to see the full blue outline.

### Reproduction Sample

https://codepen.io/paulcp/pen/poVpxNZ

### Reproduction Steps

1. Select the first tile
2. Notice only two sides have a blue border

### Reproduction Version

1.0.0-beta.94

### Relevant Info

You can just add a z-index: 2 to the selected tile and it will show it correctly, so I think it's just buried.

### Regression?

beta.86? CDN links are down for other versions...

### Esri team

ArcGIS Online

**Comment by macandcheese** [comment]
This has been resolved since this issue was opened - closing: https://codepen.io/mac_and_cheese/pen/QWZaxxN

**Comment by macandcheese** [comment]
This was resolved in https://github.com/Esri/calcite-components/pull/5390 - closing: https://codepen.io/mac_and_cheese/pen/QWZaxxN
