### ISSUE TITLE
modal's open behavior depends on hydrated attribute

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#5396]
### Actual Behavior

Beta 93 introduced a regression (see https://github.com/Esri/calcite-components/commit/f1322c898d6e1a0d400cb5a3d97a08169b71b8f6) where an earlier approach using `calcite-hydrated` was not removed before merging. The bug causes modal's open behavior to be tied to the `calcite-hydrated` attribute, which may not be applied when the component is wrapped by another Stencil component (the hydrated class/attribute can be modified).

cc @mjuniper 

### Expected Behavior

Modal's open behavior to work regardless of the component's hydrated attribute.

### Reproduction Sample

https://codepen.io/mjuniper/pen/oNdGaOp

### Reproduction Steps

1. click on the open button
2. notice how the modal does not open

### Reproduction Version

beta.94

### Regression?

beta.93

### Esri team

ArcGIS Hub

**Comment by geospatialem** [comment]
@mjuniper Could someone on the Hub team verify the fix with `beta.95`, released last week? 

With the `hub-components` script inclusion, unsure which would be the best version to test with this fix to ensure the `modal` opens regardless of hydration. 🛠️

**Comment by geospatialem** [comment]
Thanks for verifying, @mjuniper! 

Closing based on fix. 🔨
