### ISSUE TITLE
Popover reference element position issues

### ISSUE THREAD

**Issue by rslibed** [Esri/calcite-components#5399]
### Actual Behavior

When opening a popover with a trigger element, the popover will be incorrectly positioned for a brief moment, then correct itself. 

### Expected Behavior

When opening a popover with a trigger element, the popover will correctly open next to the reference element

### Reproduction Sample

https://codepen.io/rslibed/pen/bGMvBPL

### Reproduction Steps

1. Open CodePen
2. Click on `i` icons to open popovers. 
3. Notice that the popovers are incorrectly positioned and eventually corrects itself. 

Note: Issue is intermittent, so it may take a few refreshes to repro. 

### Reproduction Version

beta.95

### Relevant Info

Chrome, Mac OS

### Regression?

beta.92

### Esri team

ArcGIS Instant Apps

**Comment by ethanbdev** [comment]
+1 watching this one

**Comment by jmanke** [comment]
Here is another [sample](https://codepen.io/jmanke/pen/LYmMbJb) that is reproducible 100% of the time on my machine (using Chrome).

+1 Dashboards is watching this one as well
