### ISSUE TITLE
Flow documentation page is blank

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#5407]
### Description

Flow documentation page seems to crash and show a blank page. Reproducible on Mac Firefox & Chrome

### Which Component

Flow

### Resources

https://developers.arcgis.com/calcite-design-system/components/flow/

<img width="1680" alt="Screen Shot 2022-10-03 at 9 22 02 PM" src="https://user-images.githubusercontent.com/5892789/193714324-a8129e1b-cce7-464f-a79d-dfe68a142e4a.png">

**Comment by benelan** [comment]
This should now be fixed on [`next.sites.afd`](
https://next.sites.afd.arcgis.com/calcite-design-system/components/flow/) (Esri vpn required). It will be deployed early next week on the public docs.

**Comment by geospatialem** [comment]
[Back in business](https://developers.arcgis.com/calcite-design-system/components/flow)! 🎩 

![image](https://user-images.githubusercontent.com/5023024/194173461-23bd4be6-719a-4617-8148-98968e1f8091.png)
