### ISSUE TITLE
Input - Icon does not appear in Firefox browser

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#5417]
### Actual Behavior

The calcite-input's icon does not appear in Firefox.

![Screen Shot 2022-10-05 at 11 23 36 AM](https://user-images.githubusercontent.com/19629809/194134199-b404896b-53b9-4389-b5f9-fbb931c3334d.png)

### Expected Behavior

The calcite-input's icon should appear in Firefox.

### Reproduction Sample

https://codepen.io/jmanke/pen/bGMjxGL?editors=100

### Reproduction Steps

1. Open provided codepen in Firefox
2. Observe the calcite-input's icon does not appear

### Reproduction Version

beta.95

### Relevant Info

Mac OS, Firefox

### Regression?

beta.86

### Esri team

ArcGIS Dashboard

**Comment by mpayson** [comment]
Related #5381

**Comment by fendiaoxiaoshuazi** [comment]
@jcfranco @benelan @geospatialem 

Hi, we also encountered this issue on the firefox time picker, could you please help check the time picker? (Note: the date picker works as expected, only the time picker misses the icon on firefox)
Firefox:
![image](https://user-images.githubusercontent.com/26078106/195796797-eee6778c-dfb7-4275-a895-1fd92c25f716.png)
Chrome:
![image](https://user-images.githubusercontent.com/26078106/195796903-692dfae8-839a-49e7-ac22-b9c9ea33b6bb.png)

**Comment by geospatialem** [comment]
Verified on the master branch for both the `input` and `input-time-picker` components with Firefox. 👍🏻 

`input`:
![verified icon in input on firefox](https://user-images.githubusercontent.com/5023024/196207531-b1ef13eb-b97d-4b8b-b0c5-902d2625f956.png)

`input-time-picker`:
![verified icon in input-time-picker on firefox](https://user-images.githubusercontent.com/5023024/196207446-2fbcb0ae-2156-4f66-8ecc-825de339853f.png)
