### ISSUE TITLE
add .15 transition to buttons, split-buttons

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#542]
All buttons seemed to have lost the transition. lets get it back in!

![image](https://user-images.githubusercontent.com/14083530/80826673-7eafe280-8b97-11ea-9d88-ddb4035835a0.png)

![image](https://user-images.githubusercontent.com/14083530/80826700-88394a80-8b97-11ea-8eee-619b4886bcbd.png)

**Comment by macandcheese** [comment]
👍

Just to check with @kstinson14 - adding bg-color and border transitions back is fine here, correct? 

We just didn't want to apply it to "all" previously because that caused the weird width transitions you were experiencing?

**Comment by macandcheese** [comment]
Fixed in https://github.com/Esri/calcite-components/pull/587
