### ISSUE TITLE
calcite-slider no longer displays value 0

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#5420]
### Actual Behavior

slider min value is 0 and that value displays with beta.93 and no longer displays with beta.95

beta.93
![image](https://user-images.githubusercontent.com/44481292/194166314-ce4c9b68-187e-4ac5-8ebd-6224ee284ede.png)

beta.95
![image](https://user-images.githubusercontent.com/44481292/194166235-b24d694e-54a2-48a3-b9e4-5fb6367866ec.png)

If I use a min value of 1 it appears, but I need 0.

### Expected Behavior

value 0 displays below slider

### Reproduction Sample

https://codepen.io/afreitag/pen/ExLNOeN

### Reproduction Steps

open codepen and look at slider, now change version to beta.93

### Reproduction Version

beta.95

### Regression?

beta.93

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Thanks for filing, @AdelheidF! We had a fix in via https://github.com/Esri/calcite-components/issues/5382 that just missed the `beta.95` release, but is currently live on `next` and will make next month's release. 

Also verified in your [Codepen](https://codepen.io/afreitag/pen/ExLNOeN) with `next`. ✔️
