### ISSUE TITLE
Unable to constrain block content to height of block

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#5422]
### Actual Behavior

A child element inside `<calcite-block>` with a percentage height hugs its content instead of filling up the block to the percentage specified.

### Expected Behavior

A child element inside `<calcite-block>` with a percentage height fills up the block to the percentage specified.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/WNJgRbx

### Reproduction Steps

1. Visit the sample and see two calcite blocks.
2. The first block contains a child with a `100%` height, but shows the child hugs its content instead of filling the block.
3. The second block contains the same mark-up and styling but, through some possibly hacky shadow DOM manipulation, shows the expected behavior of the child filling the block.

### Reproduction Version

beta.95

### Relevant Info

This is a somewhat reduced test case, but a more real-world scenario is if the calcite block is within a layout where it has a fixed height, but the content of the block is dynamic and may need parts of it to scroll.

I have slightly more complex test case showing this scenario: https://codepen.io/nwhittaker-esri/pen/BaxOQga:
1. The first block shows the current behavior where the user is unable to scroll the contents of the block.
2. The second block is patched to show the expected behavior of being able to scroll the contents of the block.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Verified on `master`.

![verify block content to height of the block](https://user-images.githubusercontent.com/5023024/196210964-240b9290-01f1-44f2-b2d9-81eaa07c5506.png)
