### ISSUE TITLE
Calcite block section's open property doesn't work after one toggle.

### ISSUE THREAD

**Issue by sam11927** [Esri/calcite-components#5424]
### Actual Behavior

https://developers.arcgis.com/calcite-design-system/components/block-section/

Go here, and toggle the open checkbox a few times and see it does not work after one or so toggles.

### Expected Behavior

https://developers.arcgis.com/calcite-design-system/components/block-section/

Open property toggles every time the checkbox changes.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/block-section/

### Reproduction Steps

1. https://developers.arcgis.com/calcite-design-system/components/block-section/
2. navigate to the code example
3. toggle the open property

### Reproduction Version

next

### Esri team

Calcite (dev)

**Comment by sam11927** [comment]
@macandcheese Thanks! Glad to hear it :)

**Comment by geospatialem** [comment]
Closing this since its related to the component sample page, as opposed to the specific component behavior. 

There will also be some enhancements that will fix the sample experience as mentioned by Adam above - as well as a better user experience altogether. 🎉
