### ISSUE TITLE
Calcite-Panel: content is no longer wrapped in a <section> element when panel.hasFab is false

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#5428]
### Actual Behavior

The panel content is no longer wrapped in a `<section>` element when panel.hasFab is false, which refers to a "floating action button". Not totally sure if this was an intended change. (Note: This is also the case when replacing the panel with flow-item.)

It is causing issues with button display in the panel's footer in Map Viewer. 

cc @jcfranco 

![dev screenshot](https://user-images.githubusercontent.com/5023024/194960772-95d5f4bf-a83b-47f4-a88a-679c2bf41b5f.png)

### Expected Behavior

panel content wrapped in a `<section>` element.

More specifically, the panel/flow-item is missing the `display: flex;` from the `.content-container`, which is resulting in an `overflow: auto;` from `.content-wrapper` to display the scrollbar.

The `Editor` widget typically relies on a child of the `<calcite-panel>` to display a scrollbar around its own content (FeatureForm, Attachments) so the main container element inside the panel/flow-item container may need `display: flex;` at the minimum to override the `overflow: auto;`.

![prod screenshot](https://user-images.githubusercontent.com/5023024/194960793-88a046ef-7047-4cef-8497-813018443f92.png)

### Reproduction Sample

https://jsbin.com/jisujuyofu/edit?html,output

Other samples:
- https://codepen.io/banuelosj/pen/poVBZoV
- Also, a [more advanced use case with JSAPI](https://codepen.io/hgonzago/pen/ExLQazO)

### Reproduction Steps

1. Visit the [sample](https://jsbin.com/jisujuyofu/edit?html,output)
2. Observe the scrollbar in panel

### Reproduction Version

beta.95

### Relevant Info

- Issue was first found in version 91
    - Most recent version where this issue was NOT reproducible was version 86.
- If remove the `<calcite-tab>` and `calcite-tabs` components in the example and keep the `calcite-flow` and `calcite-panel`, then it works as-expected.

### Regression?

Potentially related to the https://github.com/Esri/calcite-components/pull/5129 update [[Commit]( https://github.com/Esri/calcite-components/commit/6f6316c8532e1876aadc63f71c3e4095db2af3b6#diff-e58f98beb295fc3692d5fe7bbc2c3d1dc8a0b4379ebacd2de304680f9d7ad7f3L521)]. 

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Seeking completion in the current sprint to release CC prior to the fall product release schedule. 

cc @jcfranco @benelan

**Comment by Apahadi73** [comment]
Also, impacts AC-Charts

**Comment by geospatialem** [comment]
Verified in `next.598`. ✔️ 

![verify-panel-1](https://user-images.githubusercontent.com/5023024/196478988-7e6a2756-f202-4ed8-90d0-838fd73f22d6.png)

![verify-panel-2](https://user-images.githubusercontent.com/5023024/196478878-5ca64128-0cef-48b6-bff2-518c6669060f.gif)
