### ISSUE TITLE
Slider: `onCalciteSliderInput` is not fired when dragging range

### ISSUE THREAD

**Issue by wju** [Esri/calcite-components#5449]
### Actual Behavior

Drag the highlighted rod to move both thumb handles at the same time towards right, `onCalciteSliderInput` is only fired at the very beginning, and not fired while dragging or when dragging is ended.

<img width="101" alt="Screen Shot 2022-10-11 at 12 48 37 PM" src="https://user-images.githubusercontent.com/6289956/195185097-0f0a4b06-324a-4837-976d-9f9b0e03fac7.png">

<img width="1091" alt="Screen Shot 2022-10-11 at 12 45 00 PM" src="https://user-images.githubusercontent.com/6289956/195184469-22cc1e7d-a925-4779-a042-f31dfc860386.png">

### Expected Behavior

`onCalciteSliderInput` is expected while dragging and when dragging is ended. Per doc
> Fires on all updates to the component. **Note:** Will be fired frequently during drag

A side note. `onCalciteSliderChange` is fired when dragging is ended and can be used to mitigate the issue.

### Reproduction Sample

https://codepen.io/wju/pen/poVqREv

### Reproduction Steps

1. Open the code pen sample, open and clear console.
2. Move the mouse to place the cursor on the slider track, between of the two circles, until you see the pointer changes to a horizontal double arrow.
3. Hold down the mouse the start dragging, 
  check console:  `calciteSliderInput` event is fired in the console.
4. Drag rightwards towards the middle or the end of the slider
   check console: `calciteSliderInput` event is not fired in the console.
5. Release the mouse.
   check console: `calciteSliderInput` event is not fired in the console.

### Reproduction Version

beta.95

### Relevant Info

Reproduced on MacOS / Chrome, Windows / Chrome but probably not OS/Browser specific.

### Esri team

N/A

**Comment by AdelheidF** [comment]
tested with next.603 https://codepen.io/afreitag/pen/gOzVoLR

**Comment by AdelheidF** [comment]
tested with next.610, but it doesn't seem to be fixed there
