### ISSUE TITLE
Button - ensure CSS vars are using underlying calcite-colors and are not re-aliased

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#546]
`calcite-button` was built before `calcite-colors` were available as CSS vars and as such has a ton of re-aliased values that cause headaches for theming using our defined set of vars in `calcite-colors`. 

Update the component to use only defined CSS vars, and generally clean up the CSS for how we generate our veritable bevy of appearance and color combinations.

**Comment by paulcpederson** [comment]
@macandcheese I've started this on the theme branch: https://github.com/Esri/calcite-components/commit/a9c70b8f88079207e2aca0306fd9dc10e7088992

**Comment by paulcpederson** [comment]
Not sure how we want to handle dark button color though, we don't have all those values as part of the theme...
