### ISSUE TITLE
[Research] Stencil DS "Sibling" libraries for Angular and React

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#547]
https://github.com/ionic-team/stencil-ds-plugins

**Comment by julio8a** [comment]
some updates about the repository:
https://teams.microsoft.com/l/message/19:fd15b51dacd24e70895ec1218a54ae06@thread.skype/1588723110933?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1588723110933&teamName=Calcite%20Design%20System&channelName=Calcite%20Components&createdTime=1588723110933
