### ISSUE TITLE
tooltip and popover attached to the same button

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/calcite-components#548]
As of `v1.0.0-beta.20` I was able to use both a `<calcite-tooltip>` and a `<calcite-popover>` attached to the same `<calcite-button>` reference element.

When upgrading to `v1.0.0-beta.25` and making the necessary changes to use the `<calcite-popover-manager>` and `<calcite-tooltip-manager>` wrapped around the `<calcite-button>` element, I can only get 1 or the other to work.  Otherwise I get deeper down console errors along the lines of `Uncaught TypeError: o.toggle is not a function`.

The use case was a FAB style round icon button with hover tooltip explanation of the action the user could take, and a click interaction to then show a popover with a form to fill out.

Is this currently supported in some way?  Or is it no longer possible at this version?  Otherwise, can I recommend an enhancement to make this behavior possible?

**Comment by macandcheese** [comment]
Hi @jwasilgeo - apologies for the trouble and the slow response - could you post a code snippet with how this is set up on your end?

**Comment by jwasilgeo** [comment]
Hey there @macandcheese no worries, I appreciate your help regardless.

https://codepen.io/jwasilgeo/pen/KKdoVWg?editors=1000

This debugging codepen sample was wired up with `v1.0.0-beta.20` which is how we currently have it working in our own application.

**Comment by macandcheese** [comment]
@jwasilgeo this seems resolved at the above demo, can you confirm?

**Comment by jwasilgeo** [comment]
What would the HTML generally look like to attach both a popover and tooltip to the same target button in recent versions?

Not really sure if this is headed in the right direction:

```html
<calcite-popover reference-element="target-button">Hello! I am some popover content!</calcite-popover>
<calcite-tooltip placement="bottom" reference-element="target-button">This is the message of the tooltip</calcite-tooltip>

<!-- or vice versa nesting?  -->
<calcite-tooltip-manager>
  <calcite-popover-manager>
    <calcite-button id="target-button">Clickable popover</calcite-button>
  </calcite-popover-manager>
</calcite-tooltip-manager>
```

**Comment by macandcheese** [comment]
@driskull

**Comment by driskull** [comment]
I'm not sure we can support this use case as is. Is this a valid use case?

The issue is that they both use the `aria-describedby` attribute to open. We would have to adjust that logic.

Is it valid to have a FAB open a popover or an element with both a tooltip and popover?

**Comment by driskull** [comment]
I think I can probably change this so that they both work.

**Comment by jcfranco** [comment]
@jwasilgeo Could you help verify this one?

**Comment by jwasilgeo** [comment]
Sure, happy to. What’s the interface look like to make it work?

Is this valid? https://github.com/Esri/calcite-components/issues/548#issuecomment-733428024

**Comment by driskull** [comment]
Yes that is valid

**Comment by jwasilgeo** [comment]
Looks good and works. Thanks!

I changed all of the HTML in the codepen [above](https://github.com/Esri/calcite-components/issues/548#issuecomment-625473860) to the following to test it out like so:

```html
<script type="module" src="https://unpkg.com/@esri/calcite-components@1.0.0-beta.47/dist/calcite/calcite.esm.js"></script>
<script nomodule="" src="https://unpkg.com/@esri/calcite-components@1.0.0-beta.47/dist/calcite/calcite.js"></script>
<link rel="stylesheet" type="text/css" href="https://unpkg.com/@esri/calcite-components@1.0.0-beta.47/dist/calcite/calcite.css" />

<div>
  <p>just some aimless filler content</p>
</div>

<calcite-popover reference-element="target-button">
  <calcite-card>
    <h3 slot="title">Fill out the form</h3>
    <span slot="subtitle">It isn't important enough to be a blocking modal</span>

    <p>a cool form you could fill out one day</p>

    <calcite-button slot="footer-leading" appearance="outline" scale="s">
      Cancel
    </calcite-button>

    <calcite-button slot="footer-trailing" scale="s">
      Submit
    </calcite-button>
  </calcite-card>
</calcite-popover>

<calcite-tooltip reference-element="target-button">This is the message of the tooltip</calcite-tooltip>

<calcite-tooltip-manager>
  <calcite-popover-manager>
    <calcite-button id="target-button">Clickable popover</calcite-button>
  </calcite-popover-manager>
</calcite-tooltip-manager>
```
