### ISSUE TITLE
Calcite dropdown - picklist choices dont always anchor to the input box properly

### ISSUE THREAD

**Issue by CodeBarker** [Esri/calcite-components#5480]
### Actual Behavior

<img width="265" alt="image" src="https://user-images.githubusercontent.com/3944714/195833299-d97c5398-d299-4d66-9edc-9aa3aa1ac8e4.png">

The pick list for Sort Order is no-where near the ui element.  This only occurs in non-chromium browsers from the looks of it

### Expected Behavior

the choices for the picklist should be in the right spot

cc @jcfranco and @asangma  dont have the skills to create a simple repro for this 

also @AdelheidF for awareness

### Reproduction Sample

--

### Reproduction Steps

See screenshot above

### Reproduction Version

beta.95

### Regression?

Unsure as this specific ui element is new in map viewer

### Esri team

ArcGIS Map Viewer

**Comment by AdelheidF** [comment]
overlayPositioning="fixed" fixes it.
