### ISSUE TITLE
Update @esri/calcite-ui-icons to 3.20.4

### ISSUE THREAD

**Issue by yannikmesserli** [Esri/calcite-components#5481]
### Description

Update @esri/calcite-ui-icons to 3.20.4

### Acceptance Criteria

@esri/calcite-ui-icons to be on 3.20.4 and the new icons to be avaialble in calcite

### Which Component

All.

### Esri team

Calcite (dev)

**Comment by macandcheese** [comment]
Doesn't seem like that has made it to npm yet https://www.npmjs.com/package/@esri/calcite-ui-icons - @benelan maybe you could and @SkyeSeitz could figure out an automation to publish the latest releases to npm?

**Comment by SkyeSeitz** [comment]
> Doesn't seem like that has made it to npm yet https://www.npmjs.com/package/@esri/calcite-ui-icons - @benelan maybe you could and @SkyeSeitz could figure out an automation to publish the latest releases to npm?

Thanks, @macandcheese. Catching up on messages after being out. I have now published the latest (3.20.5) to npm, but yes, automation of this task is definitely going to be 🔑 moving forward. @benelan please let me know what you need from me set this up. Thanks!

**Comment by benelan** [comment]
Completely automating prod NPM releases usually isn't the best idea. But if we want to do that I'd have to know more about how the icons team handles branches/PRs. 

Right now there are no branch protections set up in the repo, so automatically releasing NPM on pushes to `master` would be really dangerous. If you want releases automated, we would probably need to protect `master` and create a `dev` or release branch(s) where work would happen, and then only merge to `master` when you want to release to npm. We can discuss on Teams if that's something you're interested in setting up.

In the meantime, I created a PR to bump the icons in CC, which will make it into the upcoming `beta.96` release. #5525

**Comment by geospatialem** [comment]
The icons have been updated to `3.20.5`. ✔️

@benelan + @SkyeSeitz before closing out this issue, is a new related issue needed for the automation of the icons GH repo to the CC repo?

**Comment by SkyeSeitz** [comment]
Thanks for checking @geospatialem. @benelan has already opened a PR on the Calcite UI Icon repo: 
https://github.com/Esri/calcite-ui-icons/pull/243
So I think we are good to close this issue out.

**Comment by geospatialem** [comment]
Awesome news, thank you both. Closing out this issue. 👍🏻
