### ISSUE TITLE
calcite-inline-editable: end with ellipses if string is too long

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#5489]
### Actual Behavior

if the string is too long to fit it should end with ellipses

### Expected Behavior

string ends with ellipses

### Reproduction Sample

https://codepen.io/afreitag/pen/ExLJpRa

### Reproduction Steps

open codepen and see string is just cut off.

### Reproduction Version

beta.95

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
@AdelheidF The request to add an ellipses is out of scope for the component at this time. As such, will be closing the request.

At this time it would be on the developer to implement an ellipse if interested in doing so.

**Comment by ashetland** [comment]
Already built. 🥳
<img width="276" alt="CleanShot 2022-11-16 at 09 31 30@2x" src="https://user-images.githubusercontent.com/108549080/202251887-757f9c45-a9e6-4a44-896a-3a98409a36b1.png">
