### ISSUE TITLE
A closed modal's content elements can be interacted with

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/calcite-components#549]
At version `1.0.0-beta.25` a closed `<calcite-modal>`'s content slot elements may still be interacted with. Specifically I noticed this with a `<textarea>` element in Chrome.

If you were to add a `<textarea></textarea>` to the content slot in the demo here https://esri.github.io/calcite-components/?path=/story/modal--simple, then close the modal, and then move the mouse to the location where the `<textarea>`'s lower-right resize handle was located, the mouse will show the resize cursor and you can resize that element. Open the modal back up to visually verify.

To work around this, is there some CSS I can apply with JS (like `display: none`) after closing the modal?

**Comment by paulcpederson** [comment]
@jwasilgeo I think this may be fixed. Can you try it out on beta.32 and reopen if the problem still exists for you?

**Comment by jwasilgeo** [comment]
@paulcpederson thank you! I'll try to test with beta.32 soon. I'm curious, what was the fix? (couldn't easily find it in the recent changes)

**Comment by paulcpederson** [comment]
Nevermind, I just tested this with other elements and it's still happening, I'll work on this a bit more.

**Comment by paulcpederson** [comment]
@jwasilgeo ok, put a fix for this in beta.33 👍  For real this time!
