### ISSUE TITLE
add iconFlipRtl prop to all components with a convenience icon prop

### ISSUE THREAD

**Issue by omarkawach** [Esri/calcite-components#5496]
### Actual Behavior

Suppose you had a [`calcite-action`](https://developers.arcgis.com/calcite-design-system/components/action/) with a question mark icon. 

The icon is only in LTR direction. If a user speaks Arabic, they would expect the question mark to be the other direction (RTL).

`calcite-icon` has a [`flipRtl`](https://developers.arcgis.com/calcite-design-system/components/icon/#component-api-properties-flipRtl) property, but when you declare an icon on `calcite-action` there is no way use this property.

```
<calcite-action id="developer-website-action" appearance="solid" icon="question" scale="l"></calcite-action>
```

### Expected Behavior

The `flipRtl` property should be exposed to avoid workarounds.

### Reproduction Sample

https://codepen.io/omarkawach/pen/QWrYOaX

### Reproduction Steps

1. Open the Codepen
2. Compare Calcite-action on its own versus the workaround

![Screen Shot 2022-10-17 at 12 52 20](https://user-images.githubusercontent.com/49499098/196270218-df9dfb07-231c-465b-adec-c8876d3062ef.png)

### Reproduction Version

beta.95

### Relevant Info

Mac, Chrome 106

### Esri team

ArcGIS Online

**Comment by macandcheese** [comment]
We have this property on other components that render icons internally, [for example on button](https://developers.arcgis.com/calcite-design-system/components/button/#component-api-properties-iconFlipRtl), [and on chip](https://developers.arcgis.com/calcite-design-system/components/chip/#component-api-properties-iconFlipRtl). Seems reasonable we'd add this to other components.

**Comment by jcfranco** [comment]
Agreed.

**Comment by driskull** [comment]
@jcfranco I think the `icon` prop is a convenience for quickly setting an icon on a component. 

If we add `iconFlipRtl` to every component that has an `icon` prop that might add some bloat. What if `icon` gets more props? Would we add all these props to every component?

IMO we should consider a pattern where if you need to set more properties than just the `icon`, you should slot the `calcite-icon` within the component instead. This is more scalable and won't bloat the API with props from other components on each component (users may ask for `iconScale` next). I think we should consider a best practice to not alias multiple properties from other components.

What do you think?

**Comment by benelan** [comment]
I see both sides of this. I agree that adopting the pattern of passing through icon props would lead to bloat. But to do this with slots, we would need to add more icon slots to components (e.g. for `accordion-item` two icon slots)? I think that could lead to some design fragmentation. For example, users creating a small `accordion-item` with a large icon.

We can say this prop will be an exception, but we need to think of a good alternative for future props before we do that. And I'd prefer there to not be exceptions to rules in our decisions so we can maintain consistency.

@macandcheese suggested [CSS parts](https://developer.mozilla.org/en-US/docs/Web/CSS/::part), which could be worth exploring.

**Comment by benelan** [comment]
@omarkawach This issue was marked as `has workaround`, so in case you aren't aware you can currently slot the icon in Action like this:

https://codepen.io/benesri/pen/ZEodPNm?editors=1000

**Comment by driskull** [comment]
We can definitely make an exception here but we should decide on a rule going forward.

**Comment by benelan** [comment]
Yeah imo we should decide on a rule before we make an exception to it. We may come up with a better solution and then regret the inconsistency of the flipRtl prop. Maybe we need a meeting for this?

**Comment by geospatialem** [comment]
@driskull @benelan Added a discussion to next week's engineering meeting for follow-up. cc: @jcfranco

**Comment by macandcheese** [comment]
Icons may be a good first candidate for research into css parts - to allow for things like individual color override, rotation, etc. Obviously still risky since you cannot restrict which rules consumers can override, but seems like a good use case for part.

**Comment by driskull** [comment]
@jcfranco @macandcheese for components that have `iconStart` and `iconEnd` do we just want one property to flip them both or individual properties for each?

**Comment by driskull** [comment]
I wonder if it would be better if we just automatically flipped icons in RTL if we knew they needed to be flipped and get rid of this `flipRTL` property? cc @benelan @jcfranco @macandcheese.

**Comment by macandcheese** [comment]
> @jcfranco @macandcheese for components that have `iconStart` and `iconEnd` do we just want one property to flip them both or individual properties for each?

I think the existing pattern is "both"/"start"/"end" (or undefined): https://developers.arcgis.com/calcite-design-system/components/button/#component-api-properties-iconFlipRtl

w/r/t automatically flipping, I feel like we considered that when the property was initially added to `calcite-icon`, but decided not to due to maintenance of that "flip list" / perhaps subjectivity?

**Comment by driskull** [comment]
> w/r/t automatically flipping, I feel like we considered that when the property was initially added to calcite-icon, but decided not to due to maintenance of that "flip list" / perhaps subjectivity

I think having this list might be beneficial though. Its like metadata for the icon whether or not it needs to be flipped in RTL.

Some icons like plus, minus, ellipsis don't need to be flipped because mirroring them will not render any differently. However some icons do need to be flipped.

It would be good if the icon library actually included this metadata so we don't have to maintain it.

**Comment by macandcheese** [comment]
I’ll defer to @SkyeSeitz on this one, but yes of course some need to be flipped. If that could be offloaded to icon metadata, great, but there may still be times where an app might want to explicitly opt in or out of flipping the icon.

**Comment by driskull** [comment]
Yeah I get it. I was just thinking that it would be helpful to offload this logic to the icon. Otherwise, every component has to make judgement calls on whether icons its using need to be flipped. In some cases when rendering radio buttons, they don't need to be flipped but if a user opts into checkmarks they do need to be flipped.

It would just be helpful metadata we could key off of in the `<calcite-icon>` itself and not have to worry about each component doing it.

Some property like `symmetric` or `asymmetric` would be helpful on the icon info.

Maybe even if within the `SVG` itself it had a class either `asymmetric` or `symmetric` we could use to determine whether to flip or not.

**Comment by macandcheese** [comment]
Yeah it’s an interesting topic! I’m sure some of it is subjective, but it seems symmetry of glyph is not the only deciding factor, for example many of the examples Google says not to flip/mirror are visually asymmetrical:

https://m2.material.io/design/usability/bidirectionality.html#mirroring-elements

**Comment by driskull** [comment]
Gotcha.

Yeah, all i'm saying is its probably better for the authors of the icons to decide whether or not the icon should be flipped. Otherwise we will get inconsistencies with users flipping and not flipping...

And a design system is supposed to try to minimize those inconsistencies :D

**Comment by macandcheese** [comment]
Agreed 😆 !

**Comment by driskull** [comment]
Another note: It seems we have a few different ways we flip icons currently.

1. We use `getElementDir()` and use different icons (right/left) arrows for example.
2. We use `getElementDir()` and use CSS to flip the icon. `[CSS_UTILITY.rtl]: rtl`
3. We use `flipIconRtl` property.

It would be nice to refactor and clean these up to just use one method in the future.

**Comment by SkyeSeitz** [comment]
> Yeah it’s an interesting topic! I’m sure some of it is subjective, but it seems symmetry of glyph is not the only deciding factor, for example many of the examples Google says not to flip/mirror are visually asymmetrical:
> 
> https://m2.material.io/design/usability/bidirectionality.html#mirroring-elements
> 
> Not that it would prevent icon team from maintaining a list of which ones to mirror, that could still happen but it may need to consider more than symmetry.

I would agree this could be something the Icon designers could maintain in the library’s metadata and would have to be run by Steve Frizzell’s team. Happy to reach out them if that is what we decide. 

One more factor that will contribute to the list that is compiled are icons that require Rtl redesigns (see example below):
![57970E58-3799-407C-A186-4077C59760CD](https://user-images.githubusercontent.com/29716057/205377834-2f2b187d-1fb8-40d5-8375-3635675c8485.jpeg)

**Comment by driskull** [comment]
Good point @SkyeSeitz.

Actually, looking at the `calcite-ui-icons` they provide alternative icons for anything that needs to be flipped. For example, the `list-number` above.

So, why are we providing an option to flip the icon? Shouldn't they just be using the alternative icon from `calcite-ui-icons`? @macandcheese do you know?

If they tried to flip the list-number the numbers wouldn't be correct. The `2` would look like a weird `S` right?

**Comment by driskull** [comment]
IMO I think we should hold off on this issue.

It seems the desired intention for `calcite-ui-icons` is to use the alternative icon and not flip them.

We should probably just request the `calcite-ui-icons` to add a RTL question mark icon and remove these flip props.

**Comment by SkyeSeitz** [comment]
The only Rtl icons in `calcite-ui-icons` are ones that cannot work if flipped and instead require a re-design. `list-numbers` is an example due to the numbers that need to be at the “start” of the list but cannot read as flipped. `calcite-ui-icons` library relies on the ability for either the DS or the users to flip other icons when needed. Otherwise, the library would quickly become extremely bloated.

**Comment by driskull** [comment]
> The only Rtl icons in calcite-ui-icons are ones that cannot work if flipped and instead require a re-design

@SkyeSeitz why is there chevron-left/right, arrow-left/right? There are many icons that are left/right which could just be flipped.

**Comment by driskull** [comment]
Again, I think it goes back to what the `calcite-ui-icons` project desires users to do. 

- If it expects users to flip some icons and not others then it should probably define that somewhere.
- If it expects users to not flip icons and use the provide alternatives then that should be documented and the relationship defined.

Its probably too vague to expect users to know its ok to flip the question mark icon but [not ok to flip the checkmark](https://medium.com/@khalidaljaaidi/rtl-a-story-of-motion-and-direction-part-1-1f411cede765).

**Comment by macandcheese** [comment]
I think this is the thread where it was originally discussed, I think @paulcpederson's comment summed it up best https://github.com/Esri/calcite-components/issues/721#issuecomment-656879206

**Comment by driskull** [comment]
Thanks @macandcheese.

Seems like some documentation could help in the icon project.

1. It would be nice if we knew which icons were "flippable" and which were not. The linked issue doesn't really address that part.
2. Its not clear whether we should bloat the API with `flipIcon` or the icons project with more flipped icons.
  - The icon project already has flipped icons. (arrows, directions, and icons like the list one above). So I'd prefer to just add another flipped question mark icon rather than add a prop to every component that has an icon prop. 

Its up to @jcfranco to make the call. I created the PR to add more `flipIconRtl` properties if we decide to go that route.

**Comment by geospatialem** [comment]
<details>
<summary>Verified components with "icon-flip-rtl"</summary>
<br>

- [ ] accordion-item - follow-up needed, see [Codepen example](https://codepen.io/geospatialem/pen/yLqVMQO)
- [x] action
- [x] alert
- [x] combobox-item
- [x] combobox (`placeholder-icon-flip-rtl` attr)
- [x] fab
- [x] input-message
- [x] notice
- [x] pick-list-item (n/a - deprecated)
- [x] stepper-item
- [x] tile-select
- [x] tile
- [x] value-list-item (n/a deprecated)

</details>

@benelan Can you take a peek at `accordion-item`, in this [Codepen sample](https://codepen.io/geospatialem/pen/yLqVMQO). 

The other components are verified, but the [`accordion-item`](https://github.com/Esri/calcite-components/commit/30a080b81d20163eba7e65e481ba3701b2bd39a1#diff-aaaf14a87a40729c8562ea768864e5aa960fb5719a65ba3eb59aa768ff649d2c) doesn't seem to respect the `icon-flip-rtl` attribute for both `icon-start` and `icon-end`.

```html
<calcite-accordion-item icon-flip-rtl icon-start="activity-monitor" heading="heading"></calcite-accordion-item>
```

**Comment by macandcheese** [comment]
Since Accordion Item has two icons - the values for that are start/end/both - we might want to update docs for that, button, any other place using FlipContext interface.

**Comment by geospatialem** [comment]
Thanks for the tidbit @macandcheese - all the above components are verified. 

Good catch on the docs too - will put in a PR for those components shortly. 👍🏻 

<details>
<summary>Additional components verified with "icon-flip-rtl"</summary>
<br>

### Uses `FlipContext`
- [x] button
- [x] dropdown-item
- [x] link
- [x] split-button
- [x] tab-title

### Others 
- [x] chip
- [x] input
- [x] input-number
- [x] input-text
- [x] segmented-control-item
