### ISSUE TITLE
Bug: Tooltip does not position correctly in Calcite Shell

### ISSUE THREAD

**Issue by samMatenaer** [Esri/calcite-components#5498]
### Actual Behavior

Tooltips with overlayPositioning set to 'absolute' are not being displayed in the expected location when they are the child of a CalciteShell
![image](https://user-images.githubusercontent.com/50883428/196287166-95579a37-8ee5-44aa-b7bb-78d7c272336c.png)

### Expected Behavior

Tooltip should be positioned directly next to hovered component

### Reproduction Sample

https://codesandbox.io/s/gifted-tess-bujev9

### Reproduction Steps

Hover over the items in the shell and see that "absolute" positioning has an offset the height of the header in the calcite shell

### Reproduction Version

beta.95

### Relevant Info

Issue is only present when using Firefox (on Windows and MacOS) and Safari

Works fine on Edge and Chrome (although the fixed tooltips seem to have a separate bug where they visibly reposition themselves)

### Esri team

N/A

**Comment by geospatialem** [comment]
Thank you for submitting! 

@samMatenaer Can you verify which OS and browsers you were testing for us to diagnose? 

Able to reproduce in Firefox, but not other browsers, but hoping to verify what you're experiencing to the summary.

**Comment by samMatenaer** [comment]
@geospatialem updated the pr description

**Comment by geospatialem** [comment]
We've got a few duplicate related issues, so condensed information from this issue into #5429.
