### ISSUE TITLE
`calcite-tooltip` does not work within another stencil component

### ISSUE THREAD

**Issue by vivzhang** [Esri/calcite-components#5499]
### Actual Behavior

When we add `calcite-tooltip` to a stencil component, the tooltip doesn't appear on hover, or rather, pretty inconsistent (works 1 out of 100 times?). We are currently using a temporary solution,  which is using ' scoped: true` instead of `shadow: true` in our consuming component, but it is not ideal and can potentially cause problems. 

### Expected Behavior

The tooltip appears on hover

![image](https://user-images.githubusercontent.com/16672774/196289767-2e8f47e6-3f0c-481e-85a7-c44e50c61abb.png)

### Reproduction Sample

n/a

### Reproduction Steps

1. Render `calcite-tooltip` in a stencil component
2. This is a sample use case we have
``` <calcite-icon icon='information-f' id='collapse-tooltip' scale='s' />
  <calcite-tooltip label='collapse toggle' placement='top' reference-element='collapse-tooltip' >
    <span>Tooltip text here...</span>
  </calcite-tooltip>
```
3. We are currently using beta.86 but have tried beta.95 and the problem still appears

### Reproduction Version

beta.86

### Esri team

ArcGIS Hub

**Comment by geospatialem** [comment]
We've got a few duplicate related issues, so condensed information into https://github.com/Esri/calcite-components/issues/5429.
