### ISSUE TITLE
Tooltip not positioned correctly within Modal

### ISSUE THREAD

**Issue by ReneU** [Esri/calcite-components#5502]
### Actual Behavior

It looks like a `calcite-tooltip` will be positioned far below the expected location if used within a `calcite-modal`.

![image](https://user-images.githubusercontent.com/5748802/196413489-e0c29813-f5d2-4ea9-ad8e-0cf741ae07d9.png)

### Expected Behavior

Tooltip is positioned correctly.

### Reproduction Sample

https://codepen.io/reneu/pen/ExLzVra?editors=100

### Reproduction Steps

1. Configure Modal with tooltip in content
2. Hover over tooltip reference element
3. Observe tooltip position

### Reproduction Version

beta.95

### Relevant Info

I'm seeing this in Chrome `Version 106.0.5249.119 (Official Build) (x86_64)` and Firefox `105.0.3` but I'm pretty sure this was working fine about two weeks ago (so possibly a regression with any of these browsers, I'm seeing the same behavior with some older Calcite versions). Interestingly, I'm not able to repro this in Microsoft Edge `Version 106.0.1370.47 (Official build) (x86_64)`.

Esri Team: ArcGIS Velocity

### Esri team

N/A

**Comment by ReneU** [comment]
I wasn't sure if this might be a duplicate of #5499, please feel free to close this one if it's the same issue. Any help or a workaround for solving this would be much appreciated as it broke a lot of our tooltips over night.

**Comment by geospatialem** [comment]
Also cc: #5498

**Comment by samMatenaer** [comment]
this is the exact same issue as #5498

**Comment by ReneU** [comment]
@geospatialem I updated my codepen in the initial description above to use 'latest' but I'm still seeing this issue with Chrome on a Mac. Should this be fixed by the changes in #5429 or is this a separate issue?

**Comment by geospatialem** [comment]
@ReneU Thanks for reaching back out! Had a colleague test on a Mac (I'm on Windows), but we're unable to reproduce (_screenshot below for the experience on Mac and Chrome_).

![Mac Chrome test](https://user-images.githubusercontent.com/5023024/200855796-13370577-c6e5-4b01-84a6-6ca833a49065.png)

Are you using the same version of Chrome mentioned in the original issue description? 

Want to make sure we're addressing the issue, so any additional context or steps we can take to reproduce the behavior to mitigate.

**Comment by ReneU** [comment]
Sorry about that, yeah, looks like I'm on a different Chrome version by now: `Version 107.0.5304.87 (Official Build) (x86_64)`

**Comment by geospatialem** [comment]
@ReneU We're unable to reproduce on our end - for both Windows (Chrome, FF, Edge) and Mac (Chrome, FF, Safari). 

Was able to successfully verify on Mac with Chrome `Version 107.0.5304.110`.

It looks like you might have a slightly older Chrome version installed, perhaps the older version is causing the issue?
