### ISSUE TITLE
calcite-popover should only display content on left-click

### ISSUE THREAD

**Issue by richiecarmichael** [Esri/calcite-components#5513]
### Actual Behavior

[calcite-popover](https://developers.arcgis.com/calcite-design-system/components/popover/) is displaying content on right click. 

### Expected Behavior

[calcite-popover](https://developers.arcgis.com/calcite-design-system/components/popover/) should ignore right-clicks.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/popover/

### Reproduction Steps

1. Open [sample page](https://developers.arcgis.com/calcite-design-system/components/popover/)
2. Right click on "Activate Popover" button.
  - "Popover content here" is displayed. It should not.

### Reproduction Version

unknown

### Esri team

ArcGIS API for JavaScript

**Comment by geospatialem** [comment]
Verified on `next.608`.

![verify-left-click-only-popover](https://user-images.githubusercontent.com/5023024/197832663-2c2be3f0-ec6c-4463-b378-be7d1d13f50c.gif)
