### ISSUE TITLE
Bug: overlay-positioning fixed tooltip and popover not initially positioned properly

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-components#5515]
### Actual Behavior

Tooltips and popovers with `overlay-positioning="fixed"` are not initially positioned properly. On first target hover the tooltip or popover becomes visible and then moves to correct position. All subsequent openings are fine.

Mentioned in https://github.com/Esri/calcite-components/issues/5498 relevant info.

### Expected Behavior

Tooltips and popovers with `overlay-positioning="fixed"` should be positioned properly before first open.

### Reproduction Sample

https://codepen.io/COV-GIS/pen/vYjwZLN?editors=1000

### Reproduction Steps

1. Hover over target
1. Optionally uncomment js for work around

### Reproduction Version

1.0.0-beta.95

### Relevant Info

Per the sample the work around is to call `reposition()` before first open. Seems like if `fixed` just needs a reposition call somewhere in the lifecycle.

### Esri team

N/A

**Comment by samMatenaer** [comment]
for whatever reason, it seems to be fine in this example (firefox only): https://codesandbox.io/s/gifted-tess-bujev9

however, the issue is present when using firefox in the codepen provided by @COV-GIS

**Comment by geospatialem** [comment]
@jcfranco Good catch!

We've got a few duplicate related issues, so condensed information into https://github.com/Esri/calcite-components/issues/5429.

**Comment by samMatenaer** [comment]
@geospatialem i think this is a duplicate of #5399 instead of the issue you condensed it in to
