### ISSUE TITLE
calcite-tooltip and calcite-popover have both z-index of 999

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#552]
calcite-tooltip and calcite-popover both have a z-index of 999, so the order matters in deciding which one shows on top. Instead tooltips should always be on top.

<img src=https://user-images.githubusercontent.com/44481292/80850616-b63b8080-8bd1-11ea-994a-5d1e255737f0.png width=300/>

<img src=https://user-images.githubusercontent.com/44481292/80850692-10d4dc80-8bd2-11ea-8eed-65423db3f985.png width=100/>

**Comment by AdelheidF** [comment]
This is still an issue

**Comment by AdelheidF** [comment]
Still an issue. I do think that the popup should have a higher z-index than the popover. Otherwise every user will have to overwrite that.

**Comment by macandcheese** [comment]
Agreed, tooltips should sit above popover

**Comment by AdelheidF** [comment]
looks good. Tested with @next.

<img src=https://user-images.githubusercontent.com/44481292/108747718-9ffd0900-74f2-11eb-8e78-86378022458f.png width=250/>
