### ISSUE TITLE
Refactor to drop the optional chaining operator ? from tree within the event handler.

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#5520]
### Description

In the context of events from child items, there is no need for the optional chaining operator as the event is processed after it bubbles, so we can assume there's an ancestor chain.

### Proposed Advantages

Remove redundancy.

### Which Component

`calcite-tree`

### Relevant Info

Stems from changes in #5472

**Comment by geospatialem** [comment]
Verified on `next.608`
