### ISSUE TITLE
Date Picker header displays incorrect date format order for locales where order is not Month then Year

### ISSUE THREAD

**Issue by annierm18** [Esri/calcite-components#5532]
### Actual Behavior

When the lang prop is set to "zh-CN" the date-picker header displays the format in M Y. 

This issue will happen in other locales whose date format order is in reverse of the locales with the M Y format.

### Expected Behavior

When the lang prop is set to "zh-CN", the date-picker header should be displayed as Y M format according to CLDR - see line 3317 here: (https://github.com/unicode-org/cldr/blob/release-41/common/main/zh.xml). Also, see line 2847 for "ko" here: https://github.com/unicode-org/cldr/blob/release-41/common/main/ko.xml

### Reproduction Sample

https://codepen.io/ainermfc/pen/MWGMMZB?editors=100

### Reproduction Steps

1. Set the lang prop to "zh-CN" in the date picker component (or select any locale where the order of the date format is not Month followed by year)
3. View the header

### Reproduction Version

v1.0.0-beta.95 (https://developers.arcgis.com/calcite-design-system/components/date-picker/)

### Relevant Info

@anveshmekala said they "inspected the code and looks like there is a typo in code base for a css class which set's the format in the right order

This was first reported by @BLin2525

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `next.610` for `lang`s `"ko"` and `"zh-CN"`

### `"ko"`:
![ko lang verified](https://user-images.githubusercontent.com/5023024/198083723-02e9285c-30cb-4c15-a992-89230a20de68.png)

### `"zh-CN"`:
![zh-cn lang verified](https://user-images.githubusercontent.com/5023024/198083587-056d76b4-f065-4828-b91d-6105635e717e.png)
