### ISSUE TITLE
calcite-flow-item setFocus not working for close button

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#5535]
### Actual Behavior

I call flowItem.setFocus() and it won't focus the close button of the first flowItem.
If I have a second flowItem and call setFocus it correctly focuses the back button.

It works fine with calcite-panel.

### Expected Behavior

It should set the focus on the close button.

### Reproduction Sample

flow-item: https://codepen.io/afreitag/pen/gOzNVPR  /   panel: https://codepen.io/afreitag/pen/eYMQPpy

### Reproduction Steps

Open codepen
click button
wait
see if focus goes to close button

refresh page and uncomment second flow-item and set the focus on myFlowItem2
click button
wait
see if focus goes to back button

### Reproduction Version

beta.95

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
This could have been related to https://github.com/Esri/calcite-components/issues/5428. It seems to be fixed with `next.602`.

@AdelheidF Can you try [this version with next](https://codepen.io/geospatialem/pen/LYmKwqy) to verify the fix works?

**Comment by AdelheidF** [comment]
yes, that works. Thanks. 
I used the wrong URLs for next when I tried earlier, sorry.
