### ISSUE TITLE
Loader spins faster on some Windows machines

### ISSUE THREAD

**Issue by xlt208** [Esri/calcite-components#5536]
### Actual Behavior

The loader component spins a lot faster than it used to in Chrome, Firefox, and Edge. We have spotted this on some Windows machines but not on Mac. 

https://user-images.githubusercontent.com/52176718/197069388-5ca2a5fe-9556-4db6-84e5-4403363ef02b.MP4

### Expected Behavior

The loader component spins at the same rate of speed in Windows and Mac. 

Both the ArcGIS Enterprise and ArcGIS Online home apps use the loader component in multiple places. We started seeing the loader spinning a lot faster around three weeks ago.

https://user-images.githubusercontent.com/52176718/197071361-bfaf10ba-9843-4272-9440-dc428a20ab58.MP4

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/loader/

### Reproduction Steps

On a Windows machine, open the page above and observe how fast the loader component spins.

### Reproduction Version

v1.0.0-beta.95

### Relevant Info

We were not able to reproduce the behavior on all Windows machines, but here are the specs of the machines where we did constantly reproduce the behavior: 
1. Windows 10 Enterprise, 20H2, OS build 19042.2130. Reproduces on the machine itself, as well as remoting into the machine from a Mac. 
    - Chrome Version 106.0.5249.119 (Official Build) (64-bit)
    - Firefox 102.4.0esr (64-bit)
    - Edge Version 106.0.1370.52 (Official build) (64-bit)
2. Windows 10 Enterprise, 20H2, OS build 19042.2006
3. Windows 11 Enterprise, 21H2, OS build 22000.978
4. Windows Server 2022 Standard, 21H2, OS build 20348.887

Based on the timeline that we started seeing this around three weeks ago, this could be related to the following change mentioned in the v1.0.0-beta.95 release notes: 
> animation: Support reduced motion preference for animations (https://github.com/Esri/calcite-components/issues/5314) ([920f5bd](https://github.com/Esri/calcite-components/commit/920f5bd1aba336f6068354adb1077c223129611f))

### Regression?

v1.0.0-beta.94

### Esri team

ArcGIS Enterprise

**Comment by xlt208** [comment]
cc @rpanichakit9541

**Comment by xlt208** [comment]
This appears to be a duplicate of https://github.com/Esri/calcite-components/issues/3489.

**Comment by benelan** [comment]
closing as a duplicate
