### ISSUE TITLE
calcite-tooltip with close-on-click will show up if clicked quickly

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#5538]
### Actual Behavior

Using `<calcite-tooltip close-on-click>`, the tooltip will open if the reference element is clicked before the tooltip opens.

It's clear when calcite-tooltip and calcite-popover share the same reference element. The tooltip will overlap the popover.

### Expected Behavior

When using `close-on-click` the tooltip should not show up when the reference-element is clicked.

### Reproduction Sample

https://codepen.io/gpbmike/pen/mdLNBMz

### Reproduction Steps

1. Click on reference element before tooltip opens.

### Reproduction Version

beta.95

### Relevant Info

![image](https://user-images.githubusercontent.com/8754/197244352-ea327902-0f9a-4e10-99a0-8f4ca7730d5a.png)

### Esri team

ArcGIS Site Scan

**Comment by gpbmike** [comment]
@geospatialem what are you using to record your clicks in your gif? i've been looking for something like that

**Comment by geospatialem** [comment]
> what are you using to record your clicks in your gif? i've been looking for something like that

@gpbmike [ScreenToGif](https://www.screentogif.com) - it's been a handy tool! 👍🏻
