### ISSUE TITLE
calcite-date issues with Maquette (?)

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#554]
When it first displays the calcite date input all is fine.

<img src=https://user-images.githubusercontent.com/44481292/81093100-7537ba80-8eb6-11ea-8eb5-312b20e83302.png width=200/>

When I then change the operator the date value disappears.

<img src=https://user-images.githubusercontent.com/44481292/81093173-8f719880-8eb6-11ea-8499-84c1a15df122.png width=200/>

But as you can see from this output, the value property is always set correctly.

<img src=https://user-images.githubusercontent.com/44481292/81093487-0eff6780-8eb7-11ea-8044-a1ae754360f0.png width=200/>
Operator input changes at the red line. Then Maquette creates a new calcite-date.

If I play around with the key property and make it unique to the value it just makes it worse. I see the mm/dd/yyyy all the time then.

cc @paulcpederson @jcfranco

**Comment by paulcpederson** [comment]
I'm not sure how to reproduce this in a non-maquette environment? Can you give more details?

**Comment by jcfranco** [comment]
These issues are tricky to repro. Basically, maquette sets up the component before some component lifecycle hooks kick in, so initialization may not be done properly.

I think this issues is more noticeable after the new compiler was set enabled by default. Bumping `stencil@core` to the latest may help here since they changed the default for when components are initialized (https://github.com/ionic-team/stencil/commit/cb71057b7fc4123738f83d03713a06d8f0a50d64).

**Comment by AdelheidF** [comment]
@jcfranco I have a test app for FeatureFilter in arcgis-components repo if you want to use that one. I'll send you instructions if you're interested.

**Comment by macandcheese** [comment]
@AdelheidF is this still occurring in the latest beta?

**Comment by AdelheidF** [comment]
Very cool, it seems to work well now.

There's an issue with z-index with the slider handles. The z-index of the slider handle is 1. I'm not sure how to fix this.
<img src=https://user-images.githubusercontent.com/44481292/88332909-34e11f00-cce4-11ea-8787-a744ec5487b8.png width=200/><img src=https://user-images.githubusercontent.com/44481292/88332959-475b5880-cce4-11ea-98c0-69aa2464d253.png width=200/>

**Comment by macandcheese** [comment]
Glad the first issue is solved, could you open another ticket with this new issue? Thanks as always!

**Comment by AdelheidF** [comment]
https://github.com/Esri/calcite-components/issues/755
