### ISSUE TITLE
Bug: the end date in date picker range is a square

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#5544]
### Actual Behavior

The end date in date-picker range is a square 

![image](https://user-images.githubusercontent.com/10986395/197309240-d2b2fee3-8f03-4497-9c46-9d9bf655439b.png)

### Expected Behavior

The end date to match the nice, smooth start date #dontbeasquare

### Reproduction Sample

https://codepen.io/benesri/pen/NWMQzyQ

### Reproduction Steps

1. Open the sample
2. Look at the shapes

### Reproduction Version

beta.94 through next

### Regression?

beta.93

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Observed on `hover`, or `focus` the end date returns to a filled circle.

![date-picker-range-hover](https://user-images.githubusercontent.com/5023024/197826033-4bd14d0f-5535-4126-919e-138ddaadd125.gif)

**Comment by geospatialem** [comment]
Verified in `next.729` ✨ 

![image](https://user-images.githubusercontent.com/5023024/213800590-61e3b387-90f1-45e2-abec-80d845db7cf3.png)
