### ISSUE TITLE
Combobox: Custom value enhancements

### ISSUE THREAD

**Issue by arjavbadjatiya** [Esri/calcite-components#558]
This enhancement will allow use cases such as tags to utilize the combobox component. 
- Users can type to see the filtered list of values 
- If what they typed doesn't exist in the combobox list, they can hit enter to add the custom value as a chip

Current tag design:
<img width="323" alt="Screen Shot 2020-05-05 at 2 47 31 PM" src="https://user-images.githubusercontent.com/29237960/81119447-a082cf80-8edf-11ea-9aac-e37ec7bb25b5.png">

CC @macandcheese

**Comment by macandcheese** [comment]
Yeah, this is a good addition - we discussed this in the initial component specs but never added it in - basically a configuration to allow this behavior along with an emitted event with the requested string as a detail.

**Comment by bpatterson88** [comment]
Entering custom values in a combo box is a requirement for the Dashboards query builder. In progress UI example: 

![custom-value-combobox](https://user-images.githubusercontent.com/15875886/87593289-1786d200-c6a0-11ea-8b2b-709c51f64b29.png)

**Comment by macandcheese** [comment]
@paulcpederson was this something you were hoping to add in the UX pass? cc @noahmulfinger

**Comment by paulcpederson** [comment]
Yes, definitely a part of the combobox rework as we'll need this in online.

**Comment by jcfranco** [comment]
Closing as it was installed a while back.
