### ISSUE TITLE
DropDown. Alignment in RTL doesn't seem to work

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#562]
It looks like the alignment attribute/prop in DropDown doesn't work in RTL.

`alignment="start"`
![Screen Shot 2020-05-06 at 3 22 57 PM](https://user-images.githubusercontent.com/12503298/81234512-c24a8800-8fad-11ea-9217-105ef15a62df.png)

`alignment="end"`
![Screen Shot 2020-05-06 at 3 22 16 PM](https://user-images.githubusercontent.com/12503298/81234542-d55d5800-8fad-11ea-930a-c56333ffaeb0.png)

From https://github.com/Esri/calcite-app-components/issues/959

cc @AdelheidF

**Comment by macandcheese** [comment]
Will be addressed in https://github.com/Esri/calcite-components/pull/545 - thanks for report.

**Comment by asangma** [comment]
Thanks @macandcheese 🤘🏽

**Comment by macandcheese** [comment]
Even better - an actual fix https://github.com/Esri/calcite-components/pull/566 🤷‍♂️- didn't realize we still had a `:host-context` declaration...
