### ISSUE TITLE
Dropdown: Add ability to control vertical orientation

### ISSUE THREAD

**Issue by evanmosby** [Esri/calcite-components#564]
We're running into a use case where it would be helpful if a dropdown could "drop-up". For instance, as part of a pagination control positioned at the bottom of the display

![dropdown_up](https://user-images.githubusercontent.com/28676725/81243937-f762d480-8fc5-11ea-8928-6ccad2016342.gif)

**Comment by bstifle** [comment]
This sounds good to me. 

question remains for how things scroll. Do we do first result bottom, then scroll up?

**Comment by paulcpederson** [comment]
I was thinking about this problem the other day, I wonder if we could solve this automatically based on the position of the element. You don't really want another prop _per se_, really you want dropdown menus not to cause overflow. There are a lot of instances of this in online, and managing them by hand by setting what side the dropdown opens on is kind of a pain, IMO. It would be ideal if we could figure out how to just make this work...

**Comment by macandcheese** [comment]
Maybe we could use Popper for this? We could restrict accepted props to "top / bottom" but I think the placement against edge of page could be handled for us? I'm not sure about maintaining our animate in/out w Popper to be honest?

**Comment by paulcpederson** [comment]
If we can animate popper, that would be ideal for sure. This does seem like a problem popper has already solved, I agree.

**Comment by driskull** [comment]
Not sure if this issue is still required now

**Comment by paulcpederson** [comment]
@driskull I think we should add a prop on dropdown/combobox to allow setting the popper position. AFter https://github.com/Esri/calcite-components/pull/207 you can disable flip of a popper instance, but there is no way to access that popper instance from the higher order components like dropdown and combobox. Could be nice to have a prop that set's the position and locks it, IMO

**Comment by driskull** [comment]
@paulcpederson Have there been requests to modify it?

I'm just thinking that a native `<select>` doesn't give you this control, it just opens in the best spot. I'd rather not add the prop until there's a good use case for it.

**Comment by paulcpederson** [comment]
OK, I'd buy that. We should close this issue, can always open a new one if we decide it needs to be addressed.
