### ISSUE TITLE
calcite-dropdown nested within a calcite-shell doesn't respect the "max-items" attribute 

### ISSUE THREAD

**Issue by Csmith246** [Esri/calcite-components#565]
This issue is to report a bug with the behavior of the Calcite Dropdown. Specifically, this bug happens in Chrome. When a Calcite Dropdown is nested within a Calcite-App Shell, it causes the Calcite Dropdown to ignore the “max-items” attribute if one is applied. As stated before, this only happens in Chrome. In Firefox, the dropdowns within the Shell always respect the "max-items" attribute. 

Also, in Chrome, if you right click the refresh button, and then choose “Empty Cache and Hard Reload”, the dropdowns inside the Shell work properly. But then, on the next normal refresh they go back to ignoring the max-items attribute.

A sample app demonstrating this behavior is avaliable internally [here](https://teams.microsoft.com/l/message/19:fd15b51dacd24e70895ec1218a54ae06@thread.skype/1588797930870?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1588797930870&teamName=Calcite%20Design%20System&channelName=Calcite%20Components&createdTime=1588797930870)

**Comment by macandcheese** [comment]
Hi @Csmith246 - sorry you are having issues with this! 

I did open the sample project you provided on Teams in Chrome `Version 81.0.4044.92` and I was unable to replicate this - it seemed like both the wrapped and non-wrapped dropdowns adhered to the requested `max-items` value. 

Video here: https://jumpshare.com/v/up78vg7LZk9znM9iisyS

Is there a specific Chrome version this happened in or maybe something the sample app isn't capturing?

**Comment by macandcheese** [comment]
@Csmith246 are you still seeing this behavior? I was unable to replicate...

**Comment by Csmith246** [comment]
@macandcheese  Hey. Sorry about the inactivity. We did get this working properly in the app that we were using the dropdown in. So this issue can be closed. Thanks

**Comment by macandcheese** [comment]
@Csmith246 Roger that, thanks.
