### ISSUE TITLE
Clarify distinction between "theme" and "mode"

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#5657]
### Description

This issue stems from a conversation about how we currently refer to "theme". Currently we have "dark theme" and "light theme" - really these correspond to the dark and light modes set by a user on an application / OS / Browser / preference level etc.

We should evaluate our nomenclature here - really we offer a single Calcite default "theme" that has declarations for both light and dark modes.

### Acceptance Criteria

The story for theme / mode is cleaned up.

### Relevant Info

Feel free to edit with more information.

### Which Component

All

### Esri team

Calcite (design)

**Comment by driskull** [comment]
Agreed. It does make sense to separate mode from theme.

We should discuss if we want to do this for version 1.0 or if we want this to be version 2.0. It would be a breaking change to rename our theme classes and update references where theme should be mode.

**Comment by geospatialem** [comment]
We'll update our CC class name from "theme" to "mode" for next month's release. 

In addition to doc updates, once implemented additional discussion around Tokens, the Color repo, and others should be discussed as part of the change. cc @alisonailea for expertise.

**Comment by geospatialem** [comment]
Verified using our [tutorial](https://developers.arcgis.com/calcite-design-system/tutorials/create-a-theme-switcher/) sample with `next.714` using the `calcite-mode-` naming convention.

![image](https://user-images.githubusercontent.com/5023024/211352644-55770533-4233-4695-ac25-50a21a940be8.png)
