### ISSUE TITLE
Buttons with long text should cut them off

### ISSUE THREAD

**Issue by yannikmesserli** [Esri/calcite-components#5660]
### Actual Behavior

When an unbreakable text is set to a button which is longer that what the button's width is capable of handling, the text overflow and break the button's layout.

### Expected Behavior

The text should be cut-off.

### Reproduction Sample

https://codepen.io/yannikm/pen/xxzGPRE?editors=100

### Reproduction Steps

Check the codepen's sample above.

### Reproduction Version

beta.97

### Esri team

ArcGIS Scene Viewer

**Comment by alisonailea** [comment]
We have had some conflicting requests for the right resolution to text overflows in components. We may need to provide an optional prop or find another solution per designer's recommendations.

**Comment by SkyeSeitz** [comment]
Thanks, @alisonailea. Let's connect on all the text overflow requests as a collection. 

@yannikmesserli do either of these examples below demonstrate the expected behavior you are describing?

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/29716057/199351835-30a786fe-f749-4f0c-8c31-88163c471cb7.png">

**Comment by ashetland** [comment]
The truncated version feels like the best failure state in the case. @alisonailea, we should sync up on other components where this occurs. Hopefully a similar strategy will work kit-wide. 🤞

**Comment by jcfranco** [comment]
Hopefully, we can arrive at a single way of handling this to avoid props if possible. Some additional things to consider:

1. slotted content – depending on the slotted HTML, it won't be possible for us to handle truncation via CSS
2. translations/overrides (near future) – different languages may have strings that impact the original component layout, these can also be overridden by users, which seems closer to this issue
3. a11y – we should be fine here as long as truncation is handled at a visual level and not by manipulating text content

**Comment by yannikmesserli** [comment]
> The truncated version feels like the best failure state in the case. @alisonailea, we should sync up on other components where this occurs. Hopefully a similar strategy will work kit-wide. 🤞

Agreed 🪁 

> We may need to provide an optional prop or find another solution per designer's recommendations. 

It probably makes sense to have an optional prop (`truncated`?). There are probably good uses cases that embed html element that needs to be on the edge, e.g. thumbs, so truncated inline element will break their design.

**Comment by geospatialem** [comment]
cc fix from https://github.com/Esri/calcite-components/issues/5683#issuecomment-1474113754

**Comment by jcfranco** [comment]
@ashetland @SkyeSeitz https://github.com/Esri/calcite-components/issues/5683#issuecomment-1474113754 addressed this problem in a separate component and its wrapping vs what's proposed above. Should this adopt the same approach? If not, can you chime in on guidelines for dealing with long text?

**Comment by SkyeSeitz** [comment]
> @ashetland @SkyeSeitz [#5683 (comment)](https://github.com/Esri/calcite-components/issues/5683#issuecomment-1474113754) addressed this problem in a separate component and its wrapping vs what's proposed above. Should this adopt the same approach? If not, can you chime in on guidelines for dealing with long text?

Thanks, Franco. The guideline here would be to **truncate** long text on fixed width components that should not grow in height, such as the Button discussed above. This is to avoid oversized buttons and/or misalignment as seen below:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/29716057/227027364-10691166-6659-4a4a-a10f-884a6a77b30e.png">
Instead, visually truncated text is the preferred failure state.

For components that are meant to grow in height, such as Accordion, the guideline would be to **wrap** text as seen #5683.

**Comment by ashetland** [comment]
Summary of discussion about the best way to display the full text:

Preference is for truncated buttons to use html label to display the full text. This would leave calcite-tooltip available for additional context and configurations.

**Comment by Elijbet** [comment]
> Summary of discussion about the best way to display the full text:
> 
> Preference is for truncated buttons to use html label to display the full text. This would leave calcite-tooltip available for additional context and configurations.

This comment in a related issue has some details of the implementation https://github.com/Esri/calcite-components/issues/5903#issuecomment-1500570630

**Comment by geospatialem** [comment]
Verified in `1.3.0-next.6`.

![image](https://user-images.githubusercontent.com/5023024/232170773-e22584b5-ef50-47ee-b842-455db60518cd.png)
