### ISSUE TITLE
Dropdown - max-items is not accurate in FF and Safari

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#5663]
### Actual Behavior

The `max-items` prop on the `<calcite-dropdown>` is not being reflected accurately in FF and Safari.

| Chrome  | FF | Safari |
| ------------- | ------------- | ------------- | 
| ![Screen Shot 2022-10-28 at 11 42 05 AM](https://user-images.githubusercontent.com/19629809/198709621-abcc9914-9a84-44a9-ace4-d29ca36eaacb.png) | <img width="340" alt="Screen Shot 2022-10-28 at 11 43 40 AM" src="https://user-images.githubusercontent.com/19629809/198709665-b7a19b88-a25f-4865-858c-5f6e767c8f39.png"> | <img width="340" alt="Screen Shot 2022-10-28 at 11 43 51 AM" src="https://user-images.githubusercontent.com/19629809/198709679-134bbc63-4724-4ae3-a990-db9b9a6b29cd.png"> |

### Expected Behavior

All browsers should behave the same when the `max-items` prop is set on the `calcite-dropdown`. In this case, they should match what chrome looks like.

### Reproduction Sample

https://codepen.io/jmanke/pen/NWzqLKK?editors=1000

### Reproduction Steps

1. Open [codepen](https://codepen.io/jmanke/pen/NWzqLKK?editors=1000)
2. Open dropdown in FF or Safari
3. Notice `max-items` is not behaving correctly

### Reproduction Version

beta.97

### Regression?

beta.96

### Esri team

ArcGIS Dashboard

**Comment by jcfranco** [comment]
Going to nab this for this milestone as it's a regression from https://github.com/Esri/calcite-components/issues/5399. cc @geospatialem @benelan @brittneyzwolfer

**Comment by geospatialem** [comment]
Verified on `next.631`

Firefox:
![image](https://user-images.githubusercontent.com/5023024/202225360-dc782564-9d2f-4f2d-968e-9df208e974c1.png)

Safari:
![image 2](https://user-images.githubusercontent.com/5023024/202226669-3b3414a0-2afa-4fa6-80a4-c89cbf9bd5af.png)
