### ISSUE TITLE
calcite-button: focus box cut off with width=half

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#567]
<img src=https://user-images.githubusercontent.com/44481292/81344460-a3123000-906b-11ea-9fba-3ee82175db3c.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/81344488-b0c7b580-906b-11ea-873a-9a5e38e27318.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/81344542-cdfc8400-906b-11ea-9673-c488a55b296c.png width=600/>

**Comment by macandcheese** [comment]
I think this is probably not specific to `width=half` buttons but to any component with an "outset" focus ring where it's adjacent to either the edge of a window or an element with higher z-index. It looks like maybe we can use "inset" focus rings for `appearance=transparent` buttons, but that only really solves this one use case, not across all buttons... cc @asangma

**Comment by AdelheidF** [comment]
This is still an issue.

**Comment by macandcheese** [comment]
I think the panel should end up with a higher z-index than the toolbar.. I don't think we are planning on changing the focus ring styling to be inset since so many of the button types rely on "outset" focus ring to be visible.

**Comment by AdelheidF** [comment]
OK, z-index doesn't help on the map side or if the panel has scroll bars.

<img src=https://user-images.githubusercontent.com/44481292/101123231-36332a00-35a9-11eb-9a58-dbcc8834d833.png width=200/>

**Comment by macandcheese** [comment]
We can keep this open to track it.

**Comment by Olga8614** [comment]
We verified this defect on ArcGIS Online 10.2 Production site (09/02/2022) and ArcGIS Online 10.3 devext site (09/02/2022) in EUN language with Edge chromium(105.0.1343.25)/Chrome(105.0.5195.54)/FF(104.0.1) browsers. "Fid" and "Expression" buttons are display well on Styles option pan of Map ewer beta. So this defect is fixed. Thanks!
