### ISSUE TITLE
Slider handle is out of alignment in the zero position

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#5678]
### Actual Behavior

Either of the slider's handles becomes misaligned in the `0` position on the slider axis when used in `label-handles` mode.  Both the handle in single mode and both handles in range mode float above the slider bar at the `0` position, which obscures the `0` label text.

![image](https://user-images.githubusercontent.com/821864/199359434-506db6c1-5bea-49ac-9463-5c13c9b83e8d.png)

### Expected Behavior

The slider handles should always be centered along the slider axis.

### Reproduction Sample

https://codepen.io/eriklharper/pen/WNyrPVZ?editors=100

### Reproduction Steps

1. Render a `calcite-slider` with `label-handles` turned on.
2. Observe that the handle in position `0` floats above the axis and obscures the label.

### Reproduction Version

v1.0.0-beta.95

### Esri team

Calcite (dev)

**Comment by jcfranco** [comment]
This is fixed in the latest release (via https://github.com/Esri/calcite-components/issues/5382). Closing!

**Comment by eriklharper** [comment]
> This is fixed in the latest release (via #5382). Closing!

![](https://media.giphy.com/media/PhKhSXofSAm3e/giphy.gif)
