### ISSUE TITLE
Bug: Tooltip arrow issue when the container has text-align: right set

### ISSUE THREAD

**Issue by rpanichakit9541** [Esri/calcite-components#5680]
### Actual Behavior

When the container element has the `text-align: right` style set, the tooltip arrow looks broken.

### Expected Behavior

The tooltip arrow should render correctly regardless of the parent container text-align style

### Reproduction Sample

https://codepen.io/rpanichakit/pen/JjZXOLo?editors=100

### Reproduction Steps

Hover over the link to see the arrow issue.

### Reproduction Version

beta.95

### Relevant Info

Windows 10 Chrome Version 107.0.5304.87 (Official Build) (64-bit)

### Impact

Not currently blocking, was able to override the container to have `text-align: start` to work around it.

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Verified on `next.631` in Firefox and Chrome.

![image](https://user-images.githubusercontent.com/5023024/202229597-eb4c96ed-04f2-440d-8b41-f4c2f4625703.png)
