### ISSUE TITLE
Accordion Item: Longer titles extend outside of the header area

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/calcite-components#5683]
### Actual Behavior

If the accordion item header title is long (simulated this with underscores) the title will extend outside the container instead of wrapping.  
<img width="835" alt="Screen Shot 2022-11-03 at 9 39 25 AM" src="https://user-images.githubusercontent.com/2124187/199781419-2760537e-f712-47cb-8d9c-288c2a0c58cb.png">

![image](https://user-images.githubusercontent.com/5023024/201743676-f52f652c-746f-4d2a-9733-d2c796e46ea8.png)

### Expected Behavior

I expect the title to wrap not to overflow out of the container. 

### Reproduction Sample

https://codepen.io/geospatialem/pen/QWxgzJE

### Reproduction Steps

1. Go to the [code sample](https://codepen.io/geospatialem/pen/QWxgzJE)
2. Observe `accordion-item`s containing long `heading`s with underscores don't wrap, and overflow outside the header area. 

### Reproduction Version

beta.98

### Esri team

ArcGIS Instant Apps

**Comment by ashetland** [comment]
I think this one might just be contained to Accordion Item as it looks like a bug. The presence of underscores shouldn't affect  text wrapping. Underscores should allow for line breaks just like using dashes or spaces currently do.

**Comment by geospatialem** [comment]
@jcfranco Going to assign to the upcoming March milestone per Aaron's note above.

> Underscores should allow for line breaks just like using dashes or spaces currently do.

**Comment by geospatialem** [comment]
Verified with the [following Codepen](https://codepen.io/geospatialem/pen/QWxgzJE) with `1.1.1-next.0`:

![image](https://user-images.githubusercontent.com/5023024/225966404-f77d2593-ecb4-4f2d-8c1b-5b48e0056786.png)
