### ISSUE TITLE
[Tree] Update source of selection-mode values

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#5684]
### Description

The way the values for `selection-mode` are defined prevents the correct values from making into the docs-json file. They are declared in an enum. As a result, the Component Sample doesn't have the underlying values to display. Moving this to a typed interface may solve the problem. To my knowledge, this is the only property where values are defined in this way.

cc @anveshmekala 

### Which Component

Tree

### Resources

https://github.com/Esri/calcite-components/blob/72e25afb0f7e86d4b73cce66c4e5e4663ecc5dde/src/components/tree/interfaces.ts#L5

**Comment by geospatialem** [comment]
Verified on `next.sites`.

![image](https://user-images.githubusercontent.com/5023024/214140583-d1382026-221c-42e2-9f43-3729cddd6643.png)
