### ISSUE TITLE
Many "Add Esri Product Label" workflow failures

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#5687]
### Summary

There are many [**Add Esri Product Label** workflow][1] failures. It appears as though the workflow fails when [creating an issue][2] (with an Esri team selected) because it succeeds upon a [subsequent edit][3] of the issue description.

[1]: https://github.com/Esri/calcite-components/actions/workflows/add-esri-product-label.yml
[2]: https://github.com/Esri/calcite-components/actions/runs/3394795776
[3]: https://github.com/Esri/calcite-components/actions/runs/3394807270

### Desired Outcome

The workflow succeeds when creating an issue, or is canceled for issue templates that don't request an Esri team.

### Resources

I'm submitting issues using Chrome on macOS. I don't know if other browser/platform combos have the same behavior. One thought is the issue is created with different newlines than what the workflow's [regex][1] is expecting:

>`const productRegex = new RegExp("(?<=### Esri team\r\n\r\n).+", "m");`

[1]: https://github.com/Esri/calcite-components/actions/runs/3394795776/workflow#L23

**Comment by benelan** [comment]
Sorry, not sure how I missed this. I have a fix that is working on Ubuntu and Windows, but if you want confirm on Mac you can do so [here](https://github.com/benelan/test/issues/new?assignees=&labels=bug%2C0+-+new%2Cneeds+triage&template=bug.yml) with dummy data.

I was also able to turn on email notifications for failed actions so this kind of thing won't go unnoticed again.

We are also in the process of collecting github usernames from Esri teams so we can use a script to label the issues that were logged before this action was created. Any issues that were affected by this bug will also be labelled at that time.

**Comment by geospatialem** [comment]
Confirmed label assignments with new issue creation over the last two business days. 🙌🏻
