### ISSUE TITLE
calcite-value-list + calcite-dropdown position issue

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#5693]
### Actual Behavior

Dragging the last element from a value list will cause incorrect positioning from slotted dropdown.

cc @rslibed

### Expected Behavior

Dropdown menu positioning takes into consideration latest reference element placement.

### Reproduction Sample

https://codepen.io/rslibed/pen/ZEROGjX

### Reproduction Steps

1. Drag bottom 'calcite-value-list-item' to top
2. Click on '...' action on 'Bottom (Drag to top)' value list item
3. Observe

### Reproduction Version

beta.97

### Regression?

beta.87

### Impact

Affects layout and can prevent interaction with the dropdown menu.

### Esri team

ArcGIS Instant Apps

**Comment by driskull** [comment]
Somewhat related to #5694 as well.

**Comment by geospatialem** [comment]
Verified on `next.631`.

![image](https://user-images.githubusercontent.com/5023024/202232433-289b4806-f35c-430d-a75a-b1f029e4b5dd.png)
