### ISSUE TITLE
floating-ui offscreen placement causes drag-and-drop issues in Chrome and Safari

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#5694]
### Actual Behavior

Chrome's ghost image while dragging appears in an unexpected place and in Safari items cannot be dragged at all.

cc @rslibed

### Expected Behavior

Drag and drop is consistent across browsers.

### Reproduction Sample

https://codepen.io/rslibed/pen/ZEROGjX

### Chrome

1. Drag any 'calcite-value-list-item''s handle and move
2. Notice the ghost image is offset and becomes obscured

### Safari

1. Drag any 'calcite-value-list-item''s handle and try to move
2. Notice that the item cannot be dragged at all

### Reproduction Version

beta.97

### Regression?

beta.97

### Esri team

ArcGIS Instant Apps

**Comment by geospatialem** [comment]
Verified in `next.631`.

![verify-drag-handle](https://user-images.githubusercontent.com/5023024/202233679-f88911eb-e8ab-4e43-9b56-6b48b8205746.gif)
