### ISSUE TITLE
Improve scale of internally rendered icons across relevant components

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#5698]
### Description

Follow-up to [#5245](https://github.com/Esri/calcite-components/issues/5245)

This issue will be rounding up all the components that need an `icon scale` upgrade, where the large-scale component gets a medium-scale icon (24px) instead of a small one, this includes `chevron` icons. Needs to maintain the height with or without an icon, accounting for all the prop variations that can affect height, eg. the default solid appearance with a border and transparent without.

🏗 ⚠️
WIP: Design in Figma is in progress for most of the listed components. Will update by linking Figma for each component as they become available. Please contact @SkyeSeitz if you need permission to access the provided link. 

### Proposed Advantages

This will provide a better visual distinction between scales. 

### Which Component

- [x] Accordion-Item ([Finished in Figma](https://www.figma.com/file/lfeQxz39iCKeKqkwvmFztV/24px-icons-%5Benhancement%5D-%5Bissue-%235698%5D?node-id=0%3A1))
- [x] Action (icon is contained in a button)
- [x] Button: https://github.com/Esri/calcite-components/pull/5659
- [x] FAB: https://github.com/Esri/calcite-components/pull/5659
- [x] Combobox-item
- [x] Dropdown-item
- [x] Input (all types with icons)
- [x] Input-number
- [x] Input-text
- [x] Input-date-picker
- [x] Input-time-picker
- [x] Inline Editable (icon is contained in a button)
- [x] Tab-title
- [x] Chip - https://github.com/Esri/calcite-components/pull/6058
- [x] Select
- [x] Pagination 

### Relevant Info
Follow-up issues:

- List, List-group, and List-item currently do not have any scale at any level and will be considered separately at a later time. 
- Tree-item icon satisfies the requirements but `action-end` needs to be reworked to not have an impact on height. 

_No response_

**Comment by SkyeSeitz** [comment]
**Accordion Item** design updates are completed and available at this [Figma link](url). I will continue to add completed designs that same enhancements file for the list above as they are ready. cc @brittneyzwolfer for visibility 

<img width="894" alt="image" src="https://user-images.githubusercontent.com/29716057/200431039-ff3a44d6-8b4a-4434-9a63-f6fcbcf0d0fc.png">

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/29716057/200431620-5df7499f-5a6d-473e-af7e-adaa23a06a16.png">

**Comment by Elijbet** [comment]
Some items on this list need to be refactored per #6038 to be able to inherit the scale from their parent before we can make sure these adhere to Figma styles.

**Comment by geospatialem** [comment]
Reference the follow-up items for inclusion in the January patch milestone.

**Comment by geospatialem** [comment]
Verified on `1.0.3` for the following components where `scale="l"`.

- [x] Accordion-Item
- [x] Action (icon is contained in a button)
- [x] Button
- [x] FAB
- [x] Combobox-item
- [x] Dropdown-item
- [x] Input
- [x] Input-number
- [x] Input-text
- [x] Input-date-picker
- [x] Input-time-picker
- [x] Inline Editable (icon is contained in a button)
- [x] Tab-title
- [x] Chip
- [x] Select (icon contained in component)
- [x] Pagination (icons contained in component)
