### ISSUE TITLE
Icon property doesn't work on Value List Item

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-components#5699]
### Actual Behavior

icon="circle" doesn't work on Value List Item, even though it's listed in the documentation:

https://developers.arcgis.com/calcite-design-system/components/value-list-item/#component-api-properties-icon

### Expected Behavior

icon="circle" should show a circle, like for Pick List

### Reproduction Sample

https://codepen.io/cont-kolomeets/pen/jOKVaPW?editors=1000

### Reproduction Steps

See the sample

### Reproduction Version

beta.95

### Esri team

ArcGIS Business/Community Analyst

**Comment by jcfranco** [comment]
Closing in favor of ☝️.
