### ISSUE TITLE
assistive-text element doesn't go away after re-ordering value list items

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-components#5700]
### Actual Behavior

After the order is changed, the label on top of the list says where the item went. That’s fine, but how do I make this label go away?
It just stays no matter what.

![image](https://user-images.githubusercontent.com/5318527/200470233-1e867155-b378-4cb5-8f08-db7edb3a0e33.png)

### Expected Behavior

There must be away to make the helper text go away.

### Reproduction Sample

https://codepen.io/cont-kolomeets/pen/gOKLXrN?editors=100

### Reproduction Steps

(1) Use the keyboard to change the items order.
(2) After the order has changed, the helper text on top doesn't go away.

### Reproduction Version

beta.95

### Esri team

ArcGIS Business/Community Analyst

**Comment by driskull** [comment]
I think this is fixed in #5690

**Comment by jcfranco** [comment]
Closing in favor of ☝🏼.
