### ISSUE TITLE
popover slot content doesn't have :root class applied

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-components#5702]
### Actual Behavior

Found a critical popover issue reproducible in a stand-alone sample. For some reason :root is not applied to popover’s default slot.
You can see that root css variables are not available and are colored in gray (see below).
This causes many styling issues in our code when trying to use Calcite. Please take a look asap and advise how to proceed with it.
Please note, this is not reproducible in CodePen because somehow :root makes it inside the popover there, not sure why.

![image](https://user-images.githubusercontent.com/5318527/200471232-ce8d1797-0c67-45d1-b936-60b1bd370098.png)

### Expected Behavior

:root must be available in popover's slot

### Reproduction Steps

**!!!Reproducible in a stand-alone sample only!!!**

[popover_issue.zip](https://github.com/Esri/calcite-components/files/9957470/popover_issue.zip)

In CodePen :root is available, but gets inherited from some outer div outside of the iframe, which is very strange:

https://codepen.io/cont-kolomeets/pen/gOKLXmV?editors=100

![image](https://user-images.githubusercontent.com/5318527/200472025-f47dd84d-d3f4-4358-b315-fcfd6850717d.png)

### Reproduction Version

beta.95

### Impact

Can't really use components inside popover.

### Esri team

ArcGIS Business/Community Analyst

**Comment by jcfranco** [comment]
I'm not sure I follow. `:root` is available. Inspecting the preview content page shows the following:

<img width="813" alt="Screen Shot 2022-11-09 at 5 28 23 PM" src="https://user-images.githubusercontent.com/197440/200978021-0bdd4c33-c4e4-4e40-8cb3-325eb4710cf6.png">

https://codepen.io/jcfranco/pen/wvXgVeo?editors=1000

**Comment by cont-kolomeets** [comment]
@jcfranco Like I mentioned above, in CodePen things look a bit messed up and I'm not sure why :root works there.
Could you try the stand-alone HTML sample I've attached above to have a clean html parent without any iframe?

**Comment by jcfranco** [comment]
@cont-kolomeets Regardless of the `<iframe>`, both cases work the same:

<img width="889" alt="Screen Shot 2022-11-10 at 3 55 16 PM" src="https://user-images.githubusercontent.com/197440/201230582-54d4b8fe-b533-447b-917b-e84bef2e80b6.png">

<details>
  <summary>updated popover_issue.html
  </summary>

  ```html
  <!DOCTYPE html>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
<title>Calcite</title>

<script type="module" src=https://js.arcgis.com/calcite-components/1.0.0-beta.95/calcite.esm.js> </script> <link
  rel="stylesheet" type="text/css" href=https://js.arcgis.com/calcite-components/1.0.0-beta.95/calcite.css />

<style>
  html,
  body {
    height: 100%;
    margin:20px;
  }
  :root {
    --some-color: red;
  }
</style>

</head>

<body>

<div>
  <calcite-popover label="Example label" reference-element="popover-button" overlay-positioning="fixed" open>
    <calcite-action icon="information" id="icon-1"></calcite-action>
    <div style="font-size: var(--calcite-font-size--1); color: var(--some-color);">why hello there 👋</div>
    <div style="font-size: var(--calcite-font-size--2); color: var(--some-color);">why hello there 👋</div>
    <div style="font-size: var(--calcite-font-size--3); color: var(--some-color);">why hello there 👋</div>
  </calcite-popover>
  <calcite-button id="popover-button">Activate Popover</calcite-button>
</div>
</body>

</html>

  ```
</details>

Maybe I'm missing something. Could you share a bit more about your use case? Are you trying to override the font size for components inside popover?

**Comment by cont-kolomeets** [comment]
@jcfranco As mentioned above, the issue is in that there are no `:root` styles in the **content** of the popover. See the `calcite-action` in the image below. It has no `:root` available.


![image](https://user-images.githubusercontent.com/5318527/201249868-c9eba6a5-1b3d-418e-a87e-764b161fdb59.png)

**Comment by jcfranco** [comment]
> As mentioned above...

You've mentioned `:root` not showing up in the styles panel, but you haven't described what is it exactly that you're trying to style or the exact styling issues you're running into.

In any case, I think what you've observing is a Chrome dev tools issue. Firefox shows `:root` in the rules panel.

<img width="944" alt="Screen Shot 2022-11-11 at 1 40 47 PM" src="https://user-images.githubusercontent.com/197440/201435021-c24d8287-1284-4b4e-a2dd-3e425a7eb15f.png">

Ignoring the styles/rules panel for a moment, the CSS properties defined at `:root` _**are indeed available.**_ You can see this in your repro case itself (`calcite-action` is styled accordingly) and in mine (slotted content is styled referencing custom CSS props from `:root`). 

Here's one more example to help illustrate this: https://codepen.io/jcfranco/pen/wvXgVeo.

**Comment by cont-kolomeets** [comment]
@jcfranco You are right! It _is_ a dev tool issue. In Firefox `:root` is available. Also, I've updated my sample to see if it actually works. The text color specified in the `:root` makes it all the way to the popover content. Thank you for your help!

[popover_issue.zip](https://github.com/Esri/calcite-components/files/9994037/popover_issue.zip)

![image](https://user-images.githubusercontent.com/5318527/201456564-f0cd0a85-4952-40c2-a1de-441f7996687e.png)

**Comment by jcfranco** [comment]
Awesome. Closing based on ☝🏼.
