### ISSUE TITLE
Need iconStartScale and iconEndScale for Button

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-components#5706]
### Description

Need more control over icon scale for Buton calcite component. Currently there is no such property available.

### Acceptance Criteria

For Button  `iconStartScale` and `iconEndScale` should be available.

### Which Component

https://developers.arcgis.com/calcite-design-system/components/button

### Example Use Case

    <calcite-button scale="l" icon-start-scale="s" icon-start="plus"/>

### Esri team

ArcGIS Business/Community Analyst

**Comment by jcfranco** [comment]
Closing this one per https://github.com/Esri/calcite-components/issues/5705#issuecomment-1314262433:

> Brought this up with the team and we decided to not proceed with this as the icon scales are controlled internally for visual consistency.
