### ISSUE TITLE
Placeholder string is not centered horizontally in Input search/combobox in Safari/FF

### ISSUE THREAD

**Issue by MonikaKanduri4525** [Esri/calcite-components#5713]
### Actual Behavior

The placeholder string is not aligned correctly in Input search box/combobox in Safari and Firefox 
Please refer to screenshots, pic 1(safari) it's not centered and pic 2(chrome) looks fine
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/79884938/200666861-76460e5a-47b3-4a2c-80a6-3666c3180526.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/79884938/200666869-31081a11-0315-4fdb-9e49-1f6c1b53a26d.png)

### Expected Behavior

The placeholder string should be centered horizontally in Input search box/ combobox in safari and firefox

### Reproduction Sample

https://jsbin.com/gosabugeti/1/edit?html,output

### Reproduction Steps

1. Login https://qaext.arcgis.com with a valid account and set profile language to AR.
2. Click App launcher and choose Vector Tile Style Editor app.
3. Observe the Search box/Combo box in VTSE home page.

### Reproduction Version

1.0.0-beta.74

### Esri team

ArcGIS Online

**Comment by anveshmekala** [comment]
@MonikaKanduri4525  the placeholder text placement is affected by the ArcGIS JSAPI stylesheet. Tried removing the JSAPI css reference [here](https://codepen.io/ANVESHMEKALA/pen/yLxbLPw??editors=1000) and you can see that placeholder is centered in safari.   We also submitted the issue https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/50478 in ArcGIS JSAPI repo. Let us know if you have any other questions.

**Comment by geospatialem** [comment]
Moved to our Stalled milestone to determine next steps.

**Comment by anveshmekala** [comment]
Closing this issue since it is related to ArcGIS JSAPI. Please follow https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/50478 .

**Comment by bsvensson** [comment]
FYI - this has been fixed for version 4.27 (June 2023) of ArcGIS Maps SDK for JavaScript.
