### ISSUE TITLE
Segmented control should not use fractional margin and padding internally

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-components#5721]
### Actual Behavior

The inner label (calcite-radio-group-item > shadow-root > label) has fractional margin and padding.

![image](https://user-images.githubusercontent.com/5318527/200762425-4934a93d-0693-4aa5-8c3a-c0f29f1af092.png)

If the document font size is 13px (we use it in the BA Web app) and the position of the `calcite-radio-group` happens to be fractional (because it depends on the layout and sizes of other elements before it), the result doesn't look good. See below, the blue rectangle is shifted up.

![image](https://user-images.githubusercontent.com/5318527/200762219-bbdbfe8b-3457-40d9-bf72-89bae54b62cd.png)

### Expected Behavior

`calcite-radio-group` must look correctly for all document font-sizes and position. Suggest to use non-fractional margins and padding.

It makes more sense to use the following defaults:

    margin: 2px;
    padding: 5px 10px;

### Reproduction Sample

https://codepen.io/cont-kolomeets/pen/YzvNZYy?editors=100

### Reproduction Steps

See the sample

### Reproduction Version

1.0.7

### Esri team

ArcGIS Business/Community Analyst

**Comment by geospatialem** [comment]
Additional research will be conducted with PR #6505 to determine if a solution mitigates across components, including `segmented-control` padding/margin.

**Comment by jcfranco** [comment]
> Additional research will be conducted with PR https://github.com/Esri/calcite-components/pull/6505 to determine if a solution mitigates across components, including segmented-control padding/margin.

Belated follow-up, tests using build from ☝️ look fine, but after looking at the latest version and original codepen again, I don't see the spacing issue.

@cont-kolomeets Could you provide some additional info regarding your usage of 13px and whether you see the issue with in the latest version? Spacing from your codepen looks fine to me:

<img width="516" alt="Screenshot 2023-03-21 at 11 04 59 PM" src="https://user-images.githubusercontent.com/197440/226816810-310b89b4-e6d0-4ced-9349-257c78c29afb.png">

FWIW, we're using rems as much as possible to help us scale based on the root font size. 

Also, not sure if related to the original issue, but I noticed a margin of 10.5 pixels applied to the segmented-control/radio-button-group. Is there a reason why pixels are used vs rems?

**Comment by cont-kolomeets** [comment]
@jcfranco 

Updated the sample to 1.0.7. The problem didn't go away. https://codepen.io/cont-kolomeets/pen/YzvNZYy?editors=100

It's not about px or rems. The problem is that the control can happen to be in an arbitrary place on the screen and if it happens to be, for example, 10.5px along the Y coordinate, then the rounding of margins made by the browsers produces incorrect visual output.

![image](https://user-images.githubusercontent.com/5318527/226819478-6a0dc30c-a344-45f1-aee9-390950dc9677.png)

Related issue: https://github.com/Esri/calcite-components/issues/5767

**Comment by jcfranco** [comment]
> It's not about px or rems. 

It sort of is, though. We use rems for scaling and spacing consistency (there might be a few exceptions). As you mentioned, due to how rems are calculated from the root font-size, it is expected that some calculated values might be fractional and depending on user's hardware, this might cause some misalignment (FWIW, this doesn't seem to be observable in Retina Display monitors and why I didn't notice it last time I tested). Because of this, using pixels for spacing is not an option for us.

You might be able to mitigate these layout issues by using flex or grid vs using margin. +@macandcheese for additional tips.

I will admit that we need to add some info about changing font-size with a possible gotchas section for users. @macandcheese @geospatialem Could we add this to the doc site at some point?

**Comment by jcfranco** [comment]
> Because of this, using pixels for spacing is not an option for us.

Closing based on ☝️.
