### ISSUE TITLE
Allow popover to be visible even when the reference element is out of view

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#5731]
### Description

In Dashboards, we have a use case where a popover will need to be visible even when the reference element is out of view. Previously, we could easily override the :host element's style; however, it looks like an inline style is being applied to hide the popover #5666. Using an !important css override will still work, but I believe making this an option on the component would be desirable.

### Acceptance Criteria

Allow consumers of the calcite-popover to prevent the popover from hiding when the reference element is out of view. A property on the component would be desirable. Other solutions would also be welcome.

### Which Component

calcite-popover

### Example Use Case

Here's an example where it's desirable to keep the popover visible even when the reference element is out of view. It's not a great experience to scroll down and see the popover disappear.

![chrome-capture-2022-10-9](https://user-images.githubusercontent.com/19629809/200972204-274f5a7a-7e93-4302-b84b-8c4e525d2607.gif)

### Esri team

ArcGIS Dashboard

**Comment by driskull** [comment]
Yeah, this is as expected. We would need to introduce an option to disable it. We will have to discuss because I think its working as expected.

Its notable to say that the native select element doesn't let you scroll when it is open. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by jmanke** [comment]
That makes sense, I suppose the combobox also exhibits this behavior now (as of beta 98). If this ends up being as designed we'll look into other options. Thanks!
