### ISSUE TITLE
Panel element `scrollContentTo` method is not awaiting the `scrollTo` async function

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#5747]
### Actual Behavior

This line is missing an await on the `scrollTo` function it calls, meaning calling this method does not always work properly because the promise is immediately resolved.

https://github.com/Esri/calcite-components/blob/master/src/components/panel/panel.tsx#L424

### Expected Behavior

It should be like the flow-item:
https://github.com/Esri/calcite-components/blob/master/src/components/flow-item/flow-item.tsx#L196

### Reproduction Sample

n/a

### Reproduction Steps

I can't reproduce any issue in a codepen, but have seen some inconsistency elsewhere

### Reproduction Version

beta.98

### Impact

Low impact - but it means the method is unreliable.

### Esri team

ArcGIS Map Viewer

**Comment by driskull** [comment]
@ethanbdev the scrollTo method on that div within the panel isn't async. Its as native element method.

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo

Am I understanding this correctly?

**Comment by driskull** [comment]
Going to close this. Feel free to reopen if incorrect.

**Comment by ethanbdev** [comment]
Ah I misread - sorry, we were having an issue with this method and thought it was related
