### ISSUE TITLE
calcite-input-date-picker: can't do anything in popover

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#5757]
### Actual Behavior

If you click on anything inside the popover nothing happens except popover closes.

### Expected Behavior

popover works, you can click on a different date value

### Reproduction Sample

https://codepen.io/afreitag/pen/yLPOpVY

### Reproduction Steps

open date popover and click on anything

### Reproduction Version

beta.98

### Regression?

beta.97

### Impact

it's showing up in Map Viewer in several places

### Esri team

ArcGIS Map Viewer

**Comment by jcfranco** [comment]
Express-triaged this one since it's a serious one. cc @geospatialem @brittneyzwolfer @benelan

**Comment by eriklharper** [comment]
Here's a workaround:

```
 <script>
    (async () => {
      await customElements.whenDefined("calcite-input-date-picker");
      const inputDatePicker = document.querySelector("calcite-input-date-picker");
      await inputDatePicker.componentOnReady();

      var style = document.createElement("style");
      style.innerHTML = ".menu-container { pointer-events: inherit !important; }";

      inputDatePicker.shadowRoot.appendChild(style);
    })();
  </script>
```

**Comment by geospatialem** [comment]
Verified on `next.634`.

![verify-input-date-picker](https://user-images.githubusercontent.com/5023024/202579031-f98953f8-df8e-4e23-9f38-6f4fbb787586.gif)
