### ISSUE TITLE
calcite-number-input is clearing leading zeros for decimal numbers

### ISSUE THREAD

**Issue by sam11927** [Esri/calcite-components#5763]
### Actual Behavior

All leading zeros for numbers in the calcite-number-input are cleared. This includes integers (which is expected) but problematically it includes decimal numbers. E.g. 0.000013124 becomes 0.13124.

### Expected Behavior

0.000013124 is not converted to 0.13124. Instead, decimal numbers with leading 0's are maintained.

### Reproduction Sample

https://codepen.io/sam11927/pen/mdKMLbx

### Reproduction Steps

1. open my codepen: https://codepen.io/sam11927/pen/mdKMLbx
2. enter 0.000013124
3. notice it converts it to 0.13124

### Reproduction Version

next

### Regression?

Related to the `beta.96` release. Possibly related to https://github.com/Esri/calcite-components/pull/5427?

### Impact

The vast majority of analysis uses number inputs (as well as many other apps) and we are currently not able to support any numbers less with decimals that have leading zeros.

### Esri team

ArcGIS Map Viewer

**Comment by jcfranco** [comment]
> Possibly related to https://github.com/Esri/calcite-components/pull/5427?

Confirmed! https://github.com/Esri/calcite-components/commit/2a15c79ae2f1f21dcca0d16b7b016181c7b7d79c# introduced the regression. @benelan Can you look at this one?

**Comment by benelan** [comment]
I have a PR that is waiting for approval that fixes this #5490

**Comment by benelan** [comment]
This is resolved on `next`:
https://codepen.io/benesri/pen/zYaZaGX

**Comment by geospatialem** [comment]
Verified on `next.633`.

![image](https://user-images.githubusercontent.com/5023024/202284435-f4af593f-08f3-4a5a-a4e4-1d7a2a1d0bc8.png)
