### ISSUE TITLE
Block loading icon spinning too fast

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#5776]
### Actual Behavior

Loading indicator spins way too fast.

### Expected Behavior

Loading icon to spin like it in version 94.

### Reproduction Sample

https://codepen.io/jcfranco/pen/RwJLZQJ

### Reproduction Steps

Observe the spinner! 🏃🔁

### Reproduction Version

beta.98

### Regression?

beta.94

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `next.639`.
