### ISSUE TITLE
calcite-input-number jumps by 2 when clicking arrows with laptop trackpad

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#5785]
### Actual Behavior

When tapping on the trackpad of a laptop (instead of using the button or a  mouse), the numbers seem to go up in increments of 2 instead of 1. Testing with a Dell precision laptop. 
![numbers](https://user-images.githubusercontent.com/50747646/202751782-ce0c1047-5957-4dab-a9c8-e66b2a90c3a5.gif)

### Expected Behavior

Numbers should only go up in increments of 1. 

### Reproduction Sample

https://codepen.io/afreitag/pen/bGKYBeb

### Reproduction Steps

1. Open codepen above
2. tap the up arrow by tapping on a laptop trackpad

### Reproduction Version

beta.98

### Esri team

ArcGIS Map Viewer

**Comment by driskull** [comment]
@eriklharper do you think you could investigate this one when you have some time?

**Comment by eriklharper** [comment]
@zaramatheson are these double jumps caused by taps on the trackpad as opposed to pressing the trackpad down?

**Comment by zaramatheson** [comment]
@eriklharper yes, a single tap on the trackpad

**Comment by eriklharper** [comment]
Curious what happens when you disable tap to click and try pressing the trackpad down and releasing.  Does it still result in a 2-number jump?  Also, have you seen this kind of double submission anywhere else on your computer?

**Comment by eriklharper** [comment]
We should also see if someone else with the same Dell Precision laptop is experiencing this same problem.  That would allow us to know if this is a genuine hardware and/or software issue specific to these kinds of laptops.

**Comment by zaramatheson** [comment]
@eriklharper Nothing happens for me if I disable tap to click. And this is the only place I've seen this issue.

**Comment by eriklharper** [comment]
> @eriklharper Nothing happens for me if I disable tap to click. And this is the only place I've seen this issue.

K.  Do you have a way to plug in an external mouse or bluetooth mouse?  I'm curious if that also happens in that case.

**Comment by zaramatheson** [comment]
Mouse is fine.  I have  a colleague who can repro on a Dell Precision 5560 (Mine is a Dell Precision 7530). Another colleague with  a Dell 5570 can’t repro.

**Comment by eriklharper** [comment]
It sounds like this could be a trackpad driver issue.  I'm wondering if reinstalling the touchpad drivers could remedy it.

**Comment by driskull** [comment]
If it doesn't happen on the native input number type then it shouldn't happen on our component.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

**Comment by zaramatheson** [comment]
> If it doesn't happen on the native input number type then it shouldn't happen on our component.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

I can't repro it using that

**Comment by geospatialem** [comment]
Verified on Windows on `next.714` with both a mouse and using the trackpad. 👍🏻
