### ISSUE TITLE
Cannot select date in the date-picker with input-date-picker 

### ISSUE THREAD

**Issue by arjanvanzutphen** [Esri/calcite-components#5805]
### Actual Behavior

Selecting a date in the date-picker in the input-date-picker does not return feedback when hovering over the dates. 
Also, the user cannot select a date or select another month.
![image](https://user-images.githubusercontent.com/25850072/203549807-56e90748-1114-4135-a256-c8d11179f873.png)
In this case hovering over '25'

The date-picker itself still works in beta.98

### Expected Behavior

Focusing the input-date-picker should allow me to select a date in the appearing date-picker
![image](https://user-images.githubusercontent.com/25850072/203549945-13241a67-83d6-4757-b2e1-5bfdc1f550ae.png)
Also, in this case hovering over '25'

### Reproduction Sample

See reproduction steps

### Reproduction Steps

1. Go to https://developers.arcgis.com/calcite-design-system/components/input-date-picker/
2. Go to the sample and edit the sample in CodePen
3. Change the referring two Calcite files from beta.97 to beta.98
4. Click on the input element and try to select a date
5. The date-picker will not highlight the dates in gray when hovering over them. You cannot select a date or another month 

### Reproduction Version

beta.98

### Regression?

beta.97

### Impact

The user can only type the date, instead of selecting the date in the date-picker

### Esri team

N/A

**Comment by geospatialem** [comment]
@arjanvanzutphen Thanks for opening! 

We were able to address this with a fix to https://github.com/Esri/calcite-components/issues/5757 last week with the change reflected in `next.634` and future next releases. [Codepen examples with next](https://codepen.io/geospatialem/pen/NWzYazo).

Closing with the mitigated fix, but let us know if there's anything missing we can address.
