### ISSUE TITLE
Icon appears blur for some font sizes

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-components#5811]
### Actual Behavior

This problem occurs in all components that use `calcite-icon`. The size of the icon is based on the document font size. E.g. for "s" scale it's 1rem. The problem occurs when we use 13px or 15px and the icon scales down in such a way that it appears blur.

See how blurry the plus is, when the document size is 15px.

![image](https://user-images.githubusercontent.com/5318527/203793348-cccad89a-a42e-4131-9b4e-239b3e203025.png)

### Expected Behavior

The icon size must be cast to the size that would not cause such distortion. E.g. for "s" scale you can always cast it to 14px. For "m" scale it could be 22px, for "l" scale - 28px. That would work for any document font size.

My understanding is that Calcite is mostly designed to work at 14px, so please just hard-code the icon size for this case.

### Reproduction Sample

https://codepen.io/cont-kolomeets/pen/zYajYMp?editors=100

### Reproduction Steps

See the sample above.

### Reproduction Version

beta.98

### Impact

We can't use icons for 13px in our app. We have to hack the shadow root to cast the size to the size that can be divided by 2.

### Esri team

ArcGIS Business/Community Analyst

**Comment by geospatialem** [comment]
Additional research needed, in particular around design tokens. cc @alisonailea

**Comment by alisonailea** [comment]
Calcite design (@SkyeSeitz @ashetland ) and engineering (@alisonailea @jcfranco) have looked into this. Regrettably the only option at this time is the shadowRoot hack you mentioned. 

I'm creating a new label called "scaling" and adding it to this ticket. We'll review this and other scale customization requests in the future but for now I'm going to close this ticket.
