### ISSUE TITLE
The typed-in value on input time picker is not honored by the component

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#5847]
Originally reported by: @fendiaoxiaoshuazi

### Actual Behavior

When I try typing in a value in the input time picker, the typed-in value will be changed while typing or after losing focus.

![time picker](https://user-images.githubusercontent.com/26078106/163307562-3a6ae682-f79e-47f4-b9c8-3a09f3db29ee.gif)

### Expected Behavior

The value that already exists should not be changed while typing or after losing focus.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-time-picker/

### Reproduction Steps

1. Assuming a standard `en-US` locale, type in `12:00` and hit tab or click outside the input with the mouse
2. Refocus the input by clicking or tabbing back.
3. Backspace the `12` and type `1` or `01`.
4. Hit tab or unfocus the input
5. Result: Value doesn't change.  Stays at `12:00 AM`

### Reproduction Version

beta.80

### Relevant Info

This is the same issue as: https://github.com/Esri/calcite-components/issues/4402 just specific to Input Time Picker.

### Esri team

Calcite (dev)

**Comment by eriklharper** [comment]
Duplicate of https://github.com/Esri/calcite-components/issues/6398

**Comment by jcfranco** [comment]
Closing based on ☝️.
