### ISSUE TITLE
Add full localization support for calcite-date component

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#585]
### Current State

Currently, we use the `Intl` library for our strings and formatted inside the calendar component. 

Examples:
- https://github.com/Esri/calcite-components/blob/master/src/utils/locale.ts#L118
- https://github.com/Esri/calcite-components/blob/master/src/utils/locale.ts#L96

We're also parsing user input into the date field ([getLocaleFormatData](https://github.com/Esri/calcite-components/blob/master/src/utils/locale.ts#L28)) in a way that is not very dependable/scalable between browsers. Additionally, I've inlined the start date of the week for our supported calendars [inside the library](https://github.com/Esri/calcite-components/blob/master/src/utils/locale.ts#L140-L233).

### Possible Solution

It would be much easier and less error-prone to have the locale-specific data and translations we need for the calendar component available on request as JSON. We could use a similar approach to what we do for icons. Essentially, we copy over json files into the `caclite-icon/assets` folder, and then have a utility which requests individual icon json from this folder on-demand when the icon is used. Below is a general outline of what it would take to complete this work:

1. Install unicode CLDR from npm as a devDependency in `package.json`
2. Write a node script inside the `support` directory that reads these files and generates the JSON files with data we need (more on that below), saving them to disk inside `calcite-date/assets`.
3. Write a utility for requesting the correct locale based on the `locale` property. See [the icon utility](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-icon/utils.ts) for an example. This module should have a cache for the locale data _and_ the requests so that any particular request for json is only executed once per locale.
4. Use this utility in `calcite-date.tsx` when [calendar is in view](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-icon/calcite-icon.tsx#L86-L102) or the [locale changes](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-icon/calcite-icon.tsx#L158-L168) (use icon component as example).
5. Replace most of the `src/utils/locale.ts` file with the real data, instead of the heuristics we currently use (ie. we now know the order of day, month, year, no need to figure it out). This should greatly simplify this file.
6. Use the new data to:
  - show the correct layout, strings, numerals, etc
  - correctly interpret (and display) text input from the user
6. Write tests for this work, testing different locales in `calcite-date.e2e.ts`, and testing json requests in `calcite-date/utils.e2e.ts` (these can be based on the [icon util tests](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-icon/utils.spec.ts)).

#### JSON Format

Here is a sketch of a possible format for the JSON files:

```js
{
  /** Default calendar for this locale (could be overriden by dev?) **/
  calendar: "gregorian",

  /** The character(s) most commonly used to join units (ex: /, -, .) */
  separator: "/",

  /** The order of day, month, year **/
  unitOrder: ["m", "d", "y"],

  /** Offset of week start (Monday start would be 1, Tuesday 2, etc) **/
  weekStart: 0,

  /** Placeholder string that should show for this locale when no date is provided */
  placeholder: "mm/dd/yyyy",

  /** Translated days of the week **/
  days: {
    short: ["S", "M", "T", "W", "T", "F", "S"],
    medium: ["Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"],
  },

  /** Numerals used by this numer system **/
  numerals: "٠١٢٣٤٥٦٧٨٩",

   /** Translated months of the year **/
  months: ["January", February", ...]
}
```

I think that would cover everything, but we may need more data than this? 

/cc @raje9276 not sure why I can't assign you...

**Comment by bsvensson** [comment]
I'm looking forwards to weeks that start on Mondays.  This how the current date picker in ArcGIS Online works, and we would expect the same when switching to calcite-components.

What's the timeline for implementing this issue?  @raje9276

**Comment by raje9276** [comment]
@paulcpederson can answer the timeline for implementing.

Here is the CLDR data  (version 37)
[CLDR-37-Calicite.zip](https://github.com/Esri/calcite-components/files/5157765/CLDR-37-Calicite.zip)

**Comment by paulcpederson** [comment]
@bsvensson will try to get the new locale data plugged in after 8.3 goes out the door and I get some cycles, will be sure to ping you when it's released.

**Comment by paulcpederson** [comment]
@raje9276 this in is the latest release, assigning to you for verification of all provided languages. Please open new issues with any bugs found.
