### ISSUE TITLE
calcite-tree doesn't initialize properly when options are pre-selected with selection-mode="ancestors"

### ISSUE THREAD

**Issue by sonofflynn89** [Esri/calcite-components#5867]
### Actual Behavior

In a simple tree with one parent node and one child node, the parent node will initialize with an indeterminate state even if both parent and child are marked as selected:

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/30124777/205094629-8a0e2705-4526-48f8-ad9f-6b82a49fc7cc.png)

The same thing happens when only the child is marked as selected (and the option remains unbolded).

### Expected Behavior

If either:
- the parent node and the child node are marked as selected
- the child node is marked as selected

then the parent node's checkbox icon and label should reflect that reality:

![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/30124777/205094957-aba99801-5e6f-454f-ab11-5d1a5b07da00.png)

### Reproduction Sample

https://codepen.io/sonofflynn89/pen/ExRdNwR

### Reproduction Steps

1. Open the code pen. Note that the top example has both parent and child selected, while the bottom example has only the child selected
2. Note that both parent nodes have checkboxes with the `indeterminate` icon, even though they should be checked
3. Uncheck and recheck the parent nodes
4. Note that the parent nodes have checkboxes with the `checked` icon

### Reproduction Version

1.0.0-beta.98

### Impact

minor visual bug

### Esri team

ArcGIS Hub

**Comment by geospatialem** [comment]
Looks to be a regression from `beta.66`, possibly https://github.com/Esri/calcite-components/pull/3111?

## `beta.65`:
![image](https://user-images.githubusercontent.com/5023024/205104696-f45e16d8-bff3-4f29-b1e9-a39fa1e005c0.png)

## `beta.66`:
![image](https://user-images.githubusercontent.com/5023024/205104648-a35bfbc4-46f5-4a2f-bc7c-6a0489f82894.png)

**Comment by sonofflynn89** [comment]
@geospatialem, same thing happens when just the child node is marked as selected. Should I update the description to account for both scenarios?

**Comment by sonofflynn89** [comment]
@geospatialem done! Codepen has been updated with both scenarios as well

**Comment by sonofflynn89** [comment]
@geospatialem any updates on this? I'm wrestling with a lot of other issues trying to programmatically select / unselect tree items and this particular bug is foiling all my workarounds.

**Comment by geospatialem** [comment]
Hi @sonofflynn89 we're working on triaging issues for upcoming releases later this week/early next week. 

Thanks for your patience, and sorry its impacting the workarounds.

Hope to have more information on a timeline soon!

**Comment by geospatialem** [comment]
Additional research, and should also include the use case for the `"ancestors"` `selectionMode`.

**Comment by geospatialem** [comment]
Reallocating to the April milestone.

**Comment by geospatialem** [comment]
Verified in `1.3.0-next.8` with the original [Codepen](https://codepen.io/sonofflynn89/pen/ExRdNwR):

![image](https://user-images.githubusercontent.com/5023024/232632245-7983af94-970a-4dd3-992c-79d41910882a.png)
