### ISSUE TITLE
`calcite-list-item`s are missing focus styling

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#5880]
### Actual Behavior

The list item component seems to be missing the hover styling with the latest version
![D7F0BE04-0240-4703-BDDC-39CBC643F5A2](https://user-images.githubusercontent.com/52869490/205390147-04a49e67-82b6-466a-9814-eaea8400f7a4.GIF)

### Expected Behavior

There should be some indication of hover/focus on the list item
![6517357E-5C95-487B-B079-F38EA2A8D6BB](https://user-images.githubusercontent.com/52869490/205390473-17c51b7a-d4d3-4dc9-8d4d-0d8d182a7afb.GIF)

### Reproduction Sample

https://codepen.io/afreitag/pen/MWXzwvp

### Reproduction Steps

Hover over a list item, and observe there is no styling

### Reproduction Version

next.653

### Regression?

beta.98

### Impact

High!

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Verified on `next.660`

![verify-list-focus](https://user-images.githubusercontent.com/5023024/206225101-5a6bc418-c72c-4911-b5f5-b8c0c8a99b51.gif)

**Comment by AdelheidF** [comment]
@driskull 

It seems like the cursor change is missing too, used to show a pointer.

https://codepen.io/kevindoshier/pen/JjZVXWG
