### ISSUE TITLE
Enhancement: add files property to calcite-input

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#5890]
### Description

We currently support the `file` input type, so we should add the `files` property to provide access to the uploaded content.

### Acceptance Criteria

A new [`files`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#getting_information_on_selected_files) property that aliases the one from the internal input. The property will be type [`FileList`](https://developer.mozilla.org/en-US/docs/Web/API/FileList).

### Relevant Info

Comparison of accessing files in `input` vs `calcite-input`:
https://codepen.io/benesri/pen/MWXZONP?editors=1011

### Which Component

calcite-input

### Example Use Case

Accessing the uploaded files. Related: #5675

### Esri team

Calcite (dev)

**Comment by brittneytewks** [comment]
@benelan just needed to research at this time in order to add estimate and priority for future milestone implementation

**Comment by geospatialem** [comment]
Additional research needed on the `files` property. RE: https://github.com/Esri/calcite-components/pull/6277#issuecomment-1382657593

**Comment by geospatialem** [comment]
Verified on `master`.

![image](https://user-images.githubusercontent.com/5023024/234150418-a3ce2807-7614-473d-99cf-5080bd63f7a8.png)
