### ISSUE TITLE
List: inconsistent focus behavior when when using content slots

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#5899]
### Actual Behavior

Focus is inconsistent when using the `content-end`, `content-start`, and `content` slots

### Expected Behavior

Focus works the same as it does when not using the content slots

### Reproduction Sample

https://esri.github.io/calcite-components/?path=/story/components-list--start-and-end-content-slots

### Reproduction Steps

Click back and forth between the list items a bunch of times. Sometimes the focus ring will display and sometimes it won't

### Reproduction Version

next.633

### Relevant Info

Note: the `content` slot doesn't exist in `next.633`, I found the bug while testing #5876

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified on `next.664` with the [following Codepen](https://codepen.io/geospatialem/pen/eYKodxQ).
