### ISSUE TITLE
`calcite-loader` with the `inline` attribute cannot be hidden

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#5900]
### Actual Behavior

When a calcite loader has the combination of `hidden` and `inline` attributes it will not be hidden.
![image](https://user-images.githubusercontent.com/52869490/205761427-a2066384-233b-4ced-8593-b571f7c39e16.png)

### Expected Behavior

Should be able to hide an inline placed loader with the `hidden` attribute

### Reproduction Sample

https://codepen.io/eborgen/pen/vYrvjjZ

### Reproduction Steps

Open the codepen and observe the loader is not hidden

### Reproduction Version

next.654

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Verified on `next.675` ✔️
