### ISSUE TITLE
[Inputs] Add `inputmode` and `enterKeyHint` property to Input Components

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#5917]
### Description

We currently don't explicitly accept an `inputmode` property, although it is spread to the internally rendered component. As a result, it is not documented. We should add this as a public property.

### Acceptance Criteria

Add `inputmode` and `enterKeyHint` property to appropriate input-* components.

### Which Component

Input-*

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
Might be worth adding `enterKeyHint` as well while we are at is, since that is similarly inferred from `this.el` currently...

**Comment by geospatialem** [comment]
Adding this to the January 2023 release as a low priority issue to tackle. If we're unable to tackle it with other priorities, we will reevaluate the priority after release for the February or March release.

**Comment by geospatialem** [comment]
Related to a [Community Idea](https://community.esri.com/t5/calcite-design-system-ideas/have-calcite-input-type-be-reflected-on-the/idi-p/1232286/jump-to/first-unread-message).

**Comment by geospatialem** [comment]
Verified in [the following Codepen](https://codepen.io/geospatialem/pen/bGKPqLV) on `next.672` using the `input-mode` and `enter-key-hint` attributes.

Mobile verification on iOS `16.1.2`.

![image](https://user-images.githubusercontent.com/5023024/207401415-76762fa4-1bd2-4ac1-965f-870e1bbcbecd.png)
![image](https://user-images.githubusercontent.com/5023024/207401525-de45d4c2-2274-4a0e-9fca-fb3b416fe4ba.png)
