### ISSUE TITLE
Large options in calcite-select crashed the browser with a "DevTools was diconnected..." and snap!

### ISSUE THREAD

**Issue by caronrob2000** [Esri/calcite-components#5919]
### Actual Behavior

Hi,

  I have 2 calcite-select having 4000 options each (business required this way). Creating the DOM is fast but when it gets to the calcite core function to make its thing, it takes a long time. The CPU goes way up, memory goes high and suddenly "snap" the browser.

  The function "populateInternalSelect" that caused it.

  Thanks
 

### Expected Behavior

Should populate the select fast since this is a regular select-option

### Reproduction Sample

Just have 2 large calcite-select

### Reproduction Steps

The code is too large so like I said before, just have 2 large calcite-select options and see.

### Reproduction Version

bete.97

### Esri team

N/A

**Comment by macandcheese** [comment]
Related: https://github.com/Esri/calcite-components/issues/1460

**Comment by geospatialem** [comment]
@caronrob2000 Is there a snippet or code sample you could provide for additional context? 

We'd like to explore a workaround to mitigate prior to a fix.

**Comment by geospatialem** [comment]
> @caronrob2000 Is there a snippet or code sample you could provide for additional context?
> 
> We'd like to explore a workaround to mitigate prior to a fix.

@caronrob2000 Re-pining if there's a snippet or code sample we could add for additional context to troubleshoot. Without the additional context, we will be closing the issue next month.

**Comment by geospatialem** [comment]
Closing out the issue per https://github.com/Esri/calcite-components/issues/5919#issuecomment-1492263991. You can re-open this issue with additional context for Calcite team members to explore a fix.
