### ISSUE TITLE
i18n Numbering Systems Testing: Issue with # of digits using up and down arrows

### ISSUE THREAD

**Issue by annierm18** [Esri/calcite-components#5920]
### Actual Behavior

In the Calcite input component:

- With a greater than a certain number of digits, like >15 digits after the decimal and 2 digits before the decimal, using the up and down arrows rounds the number in an unexpected way.
- Without including a decimal separator: Is it expected that "e" appears? With "e", the decimal separator gets pushed to right after the first digit. When I backspace to make the number smaller, and manually remove the "e", the decimal separator remains in the same place. So my number goes from very large, like "8173847023850385108501835981", to very small, like "13.17384702"

Info from @benelan : "Using the increment buttons is converting it to a number"

### Expected Behavior

With decimal - the number should not round.
Without decimal - I am not sure what the expected behavior should be, but I imagine if I remove the symbol that means "number to the power of x", then decimal separator should move back to the original spot...e.g. my number "8173847023850385108501835981" would not become "13.17384702". 

### Reproduction Sample
https://codepen.io/ainermfc/pen/XWYMqNE

### Reproduction Steps
(With group-separator...the repro steps may involve a different # of digits without group-separator
1. Enter a number with > 17 digits and include a decimal separator somewhere in the number
6. Click the up or down arrows 
7. Enter a number with > 17 digits and no decimal
8. Use arrows and add digits until you see "e" appear in the number
9. Remove digits manually with the back space until e is removed

### Reproduction Version

1.0.0-beta.97

### Regression?

v1.0.0-beta.97

### Esri team

N/A

**Comment by geospatialem** [comment]
Created a new issue to track the first portion of the original issue cc @annierm18 @benelan @jcfranco

**Comment by geospatialem** [comment]
Verified on `master`

![verify-input](https://user-images.githubusercontent.com/5023024/225423325-422cbdc8-2082-4ac7-86f1-c752626691eb.gif)
