### ISSUE TITLE
[Floating UI] Update definition source for `placement` 

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#5923]
### Description

For Floating UI components that use `placement`, there are a few ways these values are defined.

Some of these ways make it into `docs-json` in a digestible format, others are not able to be parsed. As a result the human-readable values don't make it into the documentation.

Instances where these are "correctly" defined in a format that works for docs (as of beta.97):

- Dropdown: https://github.com/Esri/calcite-components/blob/master/src/components/dropdown/dropdown.tsx#L152
- Input Date Picker: https://github.com/Esri/calcite-components/blob/master/src/components/input-date-picker/input-date-picker.tsx#L302

Instances where the format does not work for docs (as of beta.97):
- Input Time Picker: https://github.com/Esri/calcite-components/blob/master/src/components/input-time-picker/input-time-picker.tsx#L202
- Popover: https://github.com/Esri/calcite-components/blob/master/src/components/popover/popover.tsx#L181
- Tooltip: https://github.com/Esri/calcite-components/blob/master/src/components/tooltip/tooltip.tsx#L116

It would be great to get these in a consistent format that can be consumed easily by the docs site, similar to how we updated `selectionMode` for `calcite-tree`: https://github.com/Esri/calcite-components/pull/5801

It would also allow us to remove the “@see” notes currently used, which can quickly fall out of sync with the correct line numbers as referenced file content changes.

Note: Alert also uses "placement" but doesn't use Floating UI, so those are manually defined and not relevant here (although the values are consistent with Floating UI)

### Which Component

Input Time Picker, Popover, Tooltip

**Comment by geospatialem** [comment]
Verified on the internal v1 preview site for Input Time Picker, Popover, Tooltip.
