### ISSUE TITLE
Action: Rename `clear` appearance value to `transparent`

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-components#5929]
### Description

To improve clarity and consistency across `appearance` properties, this would follow the pattern being proposed to Button, Split Button, and FAB. 
<img width="890" alt="image" src="https://user-images.githubusercontent.com/29716057/206322835-a54409f1-732c-4e18-b9a6-7c2abba180ea.png">

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/29716057/206067744-ec07ec49-07f9-4140-9d05-3d2b3b895825.png">

### Acceptance Criteria

appearance values = `solid | transparent`

### Which Component

Action

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
This update has been made in the Figma UI Kit ✅

**Comment by ashetland** [comment]
cc @ashetland

**Comment by ashetland** [comment]
Updated overview sticker sheet.

<img width="1688" alt="appearance proposal" src="https://user-images.githubusercontent.com/108549080/207727195-660c186a-326f-41da-be99-430b9b36169e.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0.

<img width="1323" alt="updated appearacne proposal" src="https://user-images.githubusercontent.com/108549080/207977185-94b56620-e3e6-4a15-b18f-c5062fea77ee.png">

**Comment by geospatialem** [comment]
Verified in `master`.
