### ISSUE TITLE
FAB: Rename `outline` appearance value to `outline-fill`

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-components#5930]
### Description

To improve clarity and consistency across `appearance` properties, this would follow the pattern being proposed to Action, Button, and Split Button.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/29716057/206322736-7cd2fbf2-4de7-4a21-87e3-c71a7cfe608f.png">

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/29716057/206067744-ec07ec49-07f9-4140-9d05-3d2b3b895825.png">

### Acceptance Criteria

appearance values = `outline-fill | solid`

### Which Component

FAB

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
This update has been made in the Figma UI Kit ✅

**Comment by ashetland** [comment]
cc @ashetland

**Comment by ashetland** [comment]
Updated overview sticker sheet.

<img width="1688" alt="appearance proposal" src="https://user-images.githubusercontent.com/108549080/207727904-a877915d-7ef1-41d8-9464-e9436e07aa3f.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0.

<img width="1323" alt="updated appearacne proposal" src="https://user-images.githubusercontent.com/108549080/207977185-94b56620-e3e6-4a15-b18f-c5062fea77ee.png">

**Comment by geospatialem** [comment]
Verified on `next.695`
