### ISSUE TITLE
Button: Rename `clear` appearance value to `outline`

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-components#5931]
### Description

To improve clarity and consistency across `appearance` properties, this would follow the pattern being proposed to Action and FAB.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/29716057/206322700-96d21170-7c51-48a5-9389-f365a226a816.png">

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/29716057/206067744-ec07ec49-07f9-4140-9d05-3d2b3b895825.png">

### Acceptance Criteria

appearance values = `solid (default) | outline | outline-fill | transparent`

### Which Component

Button

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
This update has been made in the Figma UI Kit ✅

**Comment by ashetland** [comment]
Updated overview sticker sheet.

<img width="1688" alt="appearance proposal" src="https://user-images.githubusercontent.com/108549080/207727527-e7a79e2b-3110-44a5-964f-b48d4eaa6f4d.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0.

<img width="1323" alt="updated appearacne proposal" src="https://user-images.githubusercontent.com/108549080/207977185-94b56620-e3e6-4a15-b18f-c5062fea77ee.png">

**Comment by geospatialem** [comment]
Verified on `next.692` with the following html:

```html
<calcite-button appearance="outline">Button</calcite-button>
```
