### ISSUE TITLE
Button: Rename `outline` appearance value to `outline-fill`

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-components#5932]
### Description

To improve clarity and consistency across `appearance` properties, this would follow the pattern being proposed to Action and FAB.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/29716057/206322458-03ecb43a-4416-4e7d-9d38-f8c497fa6e9b.png">

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/29716057/206067744-ec07ec49-07f9-4140-9d05-3d2b3b895825.png">

### Acceptance Criteria

appearance values = `solid (default) | outline | outline-fill | transparent`

### Which Component

Button

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
@SkyeSeitz is it possible to add the current state of these values so @driskull is able to map those values to these proposed ones? Thanks!

**Comment by ashetland** [comment]
Updated overview sticker sheet.

<img width="1688" alt="appearance proposal" src="https://user-images.githubusercontent.com/108549080/207727633-c5c5ab18-8201-4868-9326-2bd3a3aa4be0.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0.

<img width="1323" alt="updated appearacne proposal" src="https://user-images.githubusercontent.com/108549080/207977185-94b56620-e3e6-4a15-b18f-c5062fea77ee.png">

**Comment by geospatialem** [comment]
Verified on `next.692` with the following html:

```html
<calcite-button appearance="outline-fill">Button</calcite-button>
```
