### ISSUE TITLE
Split Button: Rename `clear` appearance value to `outline`

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-components#5933]
### Description

To improve clarity and consistency across `appearance` properties, this would follow the pattern being proposed to Button, Action and FAB.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/29716057/206322670-5b245d59-d546-4f91-b729-3b50e58f90ca.png">

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/29716057/206067744-ec07ec49-07f9-4140-9d05-3d2b3b895825.png">

### Acceptance Criteria

appearance values = `solid (default) | outline | outline-fill | transparent`

### Which Component

Split Button

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
This update has been made in the Figma UI Kit ✅

**Comment by ashetland** [comment]
cc @ashetland

**Comment by SkyeSeitz** [comment]
> I think the issue with this is that we already removed "clear" in favor of "transparent" in a lot of places. So this is going to be a bit more work to refactor that. It will also be more of a breaking change for our users since our previous deprecation message said to use "transparent" instead of "clear". Now we would be saying to use something different. cc @geospatialem

Yup. Totally understand that concern and acknowledge it might be somewhat of a breaking change to anyone who made the update since the PR you are referencing landed. 

To my understanding, the move from `clear` to `transparent` ended up being more of a band-aid to the broader confusion re: the appearance prop. Since more clarity and consistency between the value names are needed, it sounds like now is the time to make that change, even if breaking.

**Comment by ashetland** [comment]
Updated overview sticker sheet.

<img width="1688" alt="appearance proposal" src="https://user-images.githubusercontent.com/108549080/207728327-da09aa83-cdd8-4848-bcaa-31f1be2cae51.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0.

<img width="1323" alt="updated appearacne proposal" src="https://user-images.githubusercontent.com/108549080/207977185-94b56620-e3e6-4a15-b18f-c5062fea77ee.png">

**Comment by geospatialem** [comment]
Verified in `next.695`.
