### ISSUE TITLE
Split Button: Rename `outline` appearance value to `outline-fill`

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-components#5934]
### Description

To improve clarity and consistency across `appearance` properties, this would follow the pattern being proposed to Button, Action and FAB.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/29716057/206322636-07480f9b-a921-4b28-8b67-75718f23b460.png">

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/29716057/206067744-ec07ec49-07f9-4140-9d05-3d2b3b895825.png">

### Acceptance Criteria

appearance values = `solid (default) | outline | outline-fill | transparent`

### Which Component

Split Button

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
Updated overview sticker sheet.

<img width="1688" alt="appearance proposal" src="https://user-images.githubusercontent.com/108549080/207728408-625c4c3c-65e4-487c-8f03-f0825bede865.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0.

<img width="1323" alt="updated appearacne proposal" src="https://user-images.githubusercontent.com/108549080/207977185-94b56620-e3e6-4a15-b18f-c5062fea77ee.png">

**Comment by geospatialem** [comment]
Verified in `next.695`.
