### ISSUE TITLE
[calcite-input] Error is thrown when rendering calcite-input at the root level without wrapping element

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#594]
The following toy snippet demonstrates an issue when there's no immediate wrapping element in a render method:

```tsx
render() {
  return <Host>
    <calcite-input type="text" placeholder="break!" />
  </Host>;
}
```

throws the following error:

```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Object.ael (index-b00ef87e.js:25)
    at index-b00ef87e.js:78
    at Array.map (<anonymous>)
    at addHostEventListeners (index-b00ef87e.js:74)
    at connectedCallback (index-b00ef87e.js:2011)
    at index-b00ef87e.js:2399
    at Object.jmp (index-b00ef87e.js:23)
    at HTMLElement.connectedCallback (index-b00ef87e.js:2399)
    at addVnodes (index-b00ef87e.js:779)
```

Wrapping it in an element works fine:

```tsx
render() {
  return <Host>
    <div>
      <calcite-input type="text" placeholder="break!" />
    </div>
  </Host>;
}
```

cc @macandcheese

**Comment by macandcheese** [comment]
Couple issues here... the attempt to listen for events emitted only by a wrapping label obviously fails if there isn't a parent...

https://github.com/Esri/calcite-components/blob/fb803234a049fbb923816ff1fee8a3b482761559/src/components/calcite-input/calcite-input.tsx#L303-L306

Resolving that reveals more "dependent on a parent that doesn't exist" errors where we try to inherit a scale and status from a parent that... wouldn't exist here: 

https://github.com/Esri/calcite-components/blob/fb803234a049fbb923816ff1fee8a3b482761559/src/components/calcite-input/calcite-input.tsx#L112-L119

I'll fix these up.
