### ISSUE TITLE
Epic: Consistent color/appearance props and values across components

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#5947]
### Purpose
Consistency of color props and values across components.

cc  @driskull @macandcheese @ashetland @SkyeSeitz

### Plan of action
Completion expected for the 1.0 release, includes:

- [x] `alert`:  
  - #5950 
- [x] `action`:
  - #5929 
- [x] `button`:
  - #5954 
  - #5931
  - #5932 
- [x] `chip`:
  - #5953 
- [x] `fab`:
  - #5956
  - #5930 
- [x] `modal`:
  - #5951
- [x] `notice`:
  - #5952 
- [x] `split-button`:
  - #5955 
  - #5933 
  - #5934

### Resources
Reference https://github.com/Esri/calcite-components/issues/1220#issuecomment-890162861 for context. 

### Updated proposal sticker sheets

<img width="1681" alt="kind proposal" src="https://user-images.githubusercontent.com/108549080/207733417-a8808f30-0311-4f86-bc36-5b1e48ad8131.png">
<img width="1685" alt="appearance proposal" src="https://user-images.githubusercontent.com/108549080/207733432-fabbd007-9463-4550-bcb8-94b275f03766.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0. @geospatialem I'll add these to each issue in this epic as well.

<img width="1323" alt="updated appearacne proposal" src="https://user-images.githubusercontent.com/108549080/207977185-94b56620-e3e6-4a15-b18f-c5062fea77ee.png">
<img width="1690" alt="updated kind proposal" src="https://user-images.githubusercontent.com/108549080/207977197-44bac68f-1fe6-46db-87ca-1337ae967bf6.png">

**Comment by macandcheese** [comment]
@geospatialem these have all been installed!

**Comment by geospatialem** [comment]
All issues verified on `next`.
