### ISSUE TITLE
Alert: Rename `color` property to `kind` and rename values

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-components#5950]
### Description

To improve clarity and consistency across the system, the `color` property should be renamed to `kind`. The values should also be renamed to align with this scheme and a brand version added.
<img width="984" alt="CleanShot 2022-12-08 at 11 16 22@2x" src="https://user-images.githubusercontent.com/108549080/206546982-845ae74a-9e05-4f61-8213-d65d2bb73625.png">

### Acceptance Criteria

`kind` = `brand | danger | info | success | warning`

Brand variant added.

### Which Component

Alert

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
cc @SkyeSeitz @geospatialem

**Comment by benelan** [comment]
I thought we were going with `status`, where did `kind` come from?

**Comment by ashetland** [comment]
We went with `kind` to not conflict with input `status`.

**Comment by macandcheese** [comment]
Kind also allows for `neutral`, `inverse` to be siblings of `danger`, `success`, etc, as they aren't `status` based values.

**Comment by ashetland** [comment]
Overview sticker sheet. Note the icon change for `kind`=`info` to use `information`

<img width="1682" alt="kind proposal" src="https://user-images.githubusercontent.com/108549080/207726858-f66832d1-61ad-47a4-9a2f-ec4941a60686.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0.

<img width="1323" alt="updated appearacne proposal" src="https://user-images.githubusercontent.com/108549080/207977185-94b56620-e3e6-4a15-b18f-c5062fea77ee.png">
<img width="1690" alt="updated kind proposal" src="https://user-images.githubusercontent.com/108549080/207977197-44bac68f-1fe6-46db-87ca-1337ae967bf6.png">

**Comment by geospatialem** [comment]
Verified on `next.695`

```html
  <calcite-alert label="Alert kind verification 1" open kind="info"></calcite-alert>
  <calcite-alert label="Alert kind verification 2" open kind="success"></calcite-alert>
  <calcite-alert label="Alert kind verification 3" open kind="warning"></calcite-alert>
  <calcite-alert label="Alert kind verification 4" open kind="danger"></calcite-alert>
  <calcite-alert label="Alert kind verification 5" open kind="brand"></calcite-alert>
```
