### ISSUE TITLE
Modal: Rename `color` property to `kind` and rename values

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-components#5951]
### Description

To improve clarity and consistency across the system, the `color` property should be renamed to `kind`. The values should also be renamed to align with this scheme and `brand | warning | success` versions added.

<img width="1002" alt="CleanShot 2022-12-08 at 11 41 09@2x" src="https://user-images.githubusercontent.com/108549080/206551876-e32ccc18-d4cd-4ead-aeae-7d155e1a55eb.png">

### Acceptance Criteria

`kind` = `brand | danger | info | success | warning`

Brand, warning, and success variants added.

### Which Component

Modal

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
cc @SkyeSeitz @geospatialem @macandcheese

**Comment by ashetland** [comment]
Overview sticker sheet.

<img width="1682" alt="kind proposal" src="https://user-images.githubusercontent.com/108549080/207727993-1c16b121-0170-40cc-8762-4ea3cffb11bb.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0.

<img width="1690" alt="updated kind proposal" src="https://user-images.githubusercontent.com/108549080/207977197-44bac68f-1fe6-46db-87ca-1337ae967bf6.png">

**Comment by geospatialem** [comment]
Verified `kind` prop on `modal` in `next.695`

![image](https://user-images.githubusercontent.com/5023024/208201120-1f78d41c-5e36-45bc-aa44-ba6c46910e9e.png)
