### ISSUE TITLE
Notice: Rename `color` property to `kind` and rename values

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-components#5952]
### Description

To improve clarity and consistency across the system, the `color` property should be renamed to `kind`. The values should also be renamed to align with this scheme and an `info` version added.

<img width="989" alt="CleanShot 2022-12-08 at 11 32 10@2x" src="https://user-images.githubusercontent.com/108549080/206550146-90a406e4-4f5a-4044-a86c-515871623965.png">

### Acceptance Criteria

`kind` = `brand | danger | info | success | warning`

Info variant added.

### Which Component

Notice

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
cc @SkyeSeitz @geospatialem @macandcheese

**Comment by ashetland** [comment]
Overview sticker sheet. Note the icon change for `kind`=`info` to use `information`

<img width="1682" alt="kind proposal" src="https://user-images.githubusercontent.com/108549080/207727043-68f0b18d-a8eb-4fcb-bc09-5fd8286b8b52.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0.

<img width="1690" alt="updated kind proposal" src="https://user-images.githubusercontent.com/108549080/207977197-44bac68f-1fe6-46db-87ca-1337ae967bf6.png">

**Comment by geospatialem** [comment]
Verified `kind` prop and values in `next.695`.
