### ISSUE TITLE
Chip: Rename `color` property to `kind` and rename values

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-components#5953]
### Description

To improve clarity and consistency across the system, the `color` property should be renamed to `kind`. The values should also be renamed to align with this scheme and a `brand` version added.

<img width="878" alt="CleanShot 2022-12-08 at 11 32 37@2x" src="https://user-images.githubusercontent.com/108549080/206550207-5d242512-f042-4907-bb08-7df1c4fd5853.png">

### Acceptance Criteria

`kind` = `brand | danger | info | neutral | success | warning`

Brand variant added.

### Which Component

Chip

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
cc @SkyeSeitz @geospatialem @macandcheese

**Comment by macandcheese** [comment]
A note, these will again change when the chip-group / chip proposed updates are added. The values for `kind` at that time will be brand, neutral, and inverse. The appearance values will match that of button.

We should in the meantime remove the `transparent` appearance type, that was never intended to be used for Chip.

**Comment by ashetland** [comment]
Overview sticker sheet.

<img width="1682" alt="kind proposal" src="https://user-images.githubusercontent.com/108549080/207727693-77ea19bb-4872-47ca-830a-7bf7cd951b7e.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0.

<img width="1690" alt="updated kind proposal" src="https://user-images.githubusercontent.com/108549080/207977197-44bac68f-1fe6-46db-87ca-1337ae967bf6.png">

**Comment by benelan** [comment]
In the future, we can create one issue for doing the same task, even if it is split across multiple components (e.g. renaming a property or two). We can still do separate PRs per component, but having one issue makes it easier to track and manage. For example #5798 and #2925

**Comment by SkyeSeitz** [comment]
> In the future, we can create one issue for doing the same task, even if it is split across multiple components (e.g. renaming a property or two). We can still do separate PRs per component, but having one issue makes it easier to track and manage. For example #5798 and #2925
> 
> We could say "rename `color` and `outline` on components x, y, z"

SO much easier. Thanks, @benelan for the clarification. This is Aaron and my preference as well 😂

**Comment by geospatialem** [comment]
Was able to verify the `kind` values for `"brand"`, `"neutral"` and `"inverse"`. 

Do we need to verify for the remaining values? cc @ashetland @SkyeSeitz 

[Codepen](https://codepen.io/geospatialem/pen/wvxwdrG) for verification for `"danger"`, `"info"`, `"success"`, and `"warning"`?

![image](https://user-images.githubusercontent.com/5023024/208200081-878f1c59-79a9-4698-832a-4ce2a1e12306.png)
