### ISSUE TITLE
Split-Button: Rename `color` property to `kind` and rename values

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-components#5955]
### Description

To improve clarity and consistency across the system, the `color` property should be renamed to `kind`. The values should also be renamed to align with this scheme.

<img width="675" alt="CleanShot 2022-12-08 at 11 32 59@2x" src="https://user-images.githubusercontent.com/108549080/206550286-e59789f8-8d5e-4d08-bb25-5098c747bc20.png">

### Acceptance Criteria

`kind` = `brand | danger | inverse | neutral`

### Which Component

Split-Button

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
cc @SkyeSeitz @geospatialem @macandcheese

**Comment by ashetland** [comment]
Overview sticker sheet.

<img width="1682" alt="kind proposal" src="https://user-images.githubusercontent.com/108549080/207728197-a0358c7a-cdc5-43a8-be40-5cea3dcf2069.png">

**Comment by ashetland** [comment]
Updated sticker sheets that include the new updates to Chip. Accordion was removed from these as those updates will happen post-v1.0.

<img width="1690" alt="updated kind proposal" src="https://user-images.githubusercontent.com/108549080/207977197-44bac68f-1fe6-46db-87ca-1337ae967bf6.png">

**Comment by geospatialem** [comment]
Verified in `next.695`.
