### ISSUE TITLE
[Modal] Add `--calcite-modal-content-padding` CSS Variable

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#5957]
### Description

We recently deprecated the `noPadding` property on Modal: https://developers.arcgis.com/calcite-design-system/components/modal/#component-api-properties-noPadding

The deprecation message states to use `--calcite-modal-padding` - which we also deprecated (correctly, since this affected padding in every element of the Modal).

We need to introduce a `--calcite-modal-content-padding` (or `-spacing`, whatever the pattern is for other instances like this, for instance in `calcite-block`), that lets folks re-create the `noPadding` functionality (or otherwise affect this padding), that is scoped just to the content slot.

### Acceptance Criteria

A `--calcite-modal-content-padding/spacing` CSS Variable is added to `calcite-modal` that correctly lets folks migrate away from the deprecated `noPadding` property.

### Which Component

Modal

### Esri team

Calcite (design)

**Comment by driskull** [comment]
@macandcheese is this one is installed already?

**Comment by macandcheese** [comment]
Yerp #6078

**Comment by geospatialem** [comment]
Verified in `beta.99` with the following css:

```css
calcite-modal {
  --calcite-modal-content-padding: 2rem;
}
```
