### ISSUE TITLE
Audit and document missing css variables

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#5958]
### Description

Audit and determine from the list below which CSS variables need to be exposed to users, and add internal to the rest of them.

- [ ] `--calcite-accordion-item-padding`
- [x] `--calcite-block-padding`
- [x] `--calcite-button-padding-x`
- [x] `--calcite-button-padding-y`
- [ ] `--calcite-loader-padding`
- [x] `--calcite-scrim-background`
- [x] `--calcite-modal-scrim-background`
- [x] `--calcite-modal-padding` (documented as deprecated) - not for inclusion
- [x] `--calcite-modal-padding-large` - not for inclusion, should be deprecated
- [x] `--calcite-tree-padding-y` - not for inclusion

Note: `modal` also has duplicate internal css vars for some reason:
- [x] `--calcite-modal-padding-internal` - not for inclusion, change to `--calcite-internal-modal-padding`
- [x] `--calcite-modal-padding-large-internal` - not for inclusion, change to `--calcite-internal-modal-padding-large`

### Which Component

- accordion
- block
- button
- loader
- modal
- tree

### Resources

Should be set up similar to [notice](https://github.com/Esri/calcite-components/blob/master/src/components/notice/notice.scss#L6) with a `@prop`.

**Comment by macandcheese** [comment]
Block padding should be exposed, it's listed as the migration path from `disablePadding`, but it's not denoted with `@prop` in the .scss file, so it isn't documented.

**Comment by macandcheese** [comment]
We should also expose `--calcite-scrim-background` in scrim: https://github.com/Esri/calcite-components/blob/master/src/components/scrim/scrim.scss

**Comment by macandcheese** [comment]
As discussed, we should expose a `--calcite-modal-scrim-background`, `--calcite-modal-content-background`, and update existing var to `--calcite-modal-content-padding`.

**Comment by driskull** [comment]
The rename would be a breaking change so lets get that one in today 👍

**Comment by macandcheese** [comment]
Added modal scrim: https://github.com/Esri/calcite-components/pull/6093
Added scrim: https://github.com/Esri/calcite-components/pull/6091

**Comment by macandcheese** [comment]
Added `-internal` to non-public button css vars: https://github.com/Esri/calcite-components/pull/6094

**Comment by macandcheese** [comment]
Not sure on accordion or loader. Accordion may see design change after design team audits `appearance` value, and it sounds like loader may see some upcoming design change: https://github.com/Esri/calcite-components/issues/4470.

I'd say we leave those two alone for now and close this out for the 1.0 issues.

**Comment by geospatialem** [comment]
@macandcheese Are the remaining two items non-breaking change? 

Wondering if we should create a new issue to track the remaining two components? We could then associate this issue with the breaking changes above for the January release.

**Comment by geospatialem** [comment]
Verified on `master`.
