### ISSUE TITLE
Alert: demo page for `alert` component appears to be broken and `buttons` no longer trigger the `alert` dialogues to open

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#5975]
### Actual Behavior

`buttons` on the demo pages won't trigger the `alert` dialogues to open any longer

### Expected Behavior

Demo page for `alert` component works as expected, where `buttons` trigger the `alert` dialogues to open. 

### Reproduction Sample

N/A

### Reproduction Steps

N/A

### Reproduction Version

v1.0.0-beta.98

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified on `master`. 💯 🔥
