### ISSUE TITLE
[commonTests] - slots test utility not compatible with getSlotted options.matches argument

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#5984]
### Test type

commonTests

### Which Component(s)

commonTests

### Unstable Tests

Wasn't sure if this is better for `testing` or `tooling` tag, feel free to adjust as needed. 

I discovered a blocking issue in this draft PR: https://github.com/Esri/calcite-components/pull/5983

When using the `slots` test helper from `commonTests`, the test will fail if the component being tested has used `getSlotted` with a passed `matches` configuration option.

Consider this code in `shell.tsx`:

`const hasModal = !!getSlotted(this.el, SLOTS.modal, { matches: "calcite-modal" });`

and this test:

`it("has slots", () => slots("calcite-shell", SLOTS));`

Because the `slots` test helper inserts a `div` element to test the existence of the slot (https://github.com/Esri/calcite-components/blob/master/src/tests/commonTests.ts#L251), the test will always fail since it doesn't match the `options.matches` argument, and as a result isn't rendered.

### Test error, if applicable

```
 ● calcite-shell › has slots

    expect(received).toEqual(expected) // deep equality

    - Expected  - 0
    + Received  + 2

    @@ -2,6 +2,8 @@
        "center-row",
        "panel-start",
        "panel-end",
        "header",
        "footer",
    +   "alerts",
    +   "modal",
      ]

      280 |   );
      281 |
    > 282 |   expect(slotNames).toEqual(slotted);
```

### PR skipped, if applicable

#

### Additional Info

The only other place `getSlotted`'s `options.matches` is declared is in `calcite-inline-editable`, and those tests don't use the `slot` test helper from `commonTests`, so this likely hasn't come up before.

**Comment by driskull** [comment]
It should be noted that `getSlotted()` util is deprecated and has instructions for conversion.

**Comment by macandcheese** [comment]
Whoops, missed that messaging somehow. I did refactor to use the `slotChange-*` helpers - this issue still remains, but I suppose I can just render the slot container and conditionally hide unexpected elements inside that to satisfy this test. Closing seeing how I was using `getSlotted()` is no longer supported.

**Comment by macandcheese** [comment]
Whoops, missed that messaging somehow. I did refactor to use the `slotChange-*` helpers - this issue still remains in this particular use case, but closing seeing how I was using `getSlotted()` is no longer supported.
