### ISSUE TITLE
popover/modal focus trap causes input elements not to get the focus set via mouse click

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#5993]
### Actual Behavior

popover/modal focus trap causes input elements, inside or outside of popovers, not to get the focus when you click on them via mouse click.

E.g. a popover is open (focus trap set by default), now I can no longer edit an input box in a shell panel.

cc @driskull 

### Expected Behavior

A mouse click anywhere in the app should set the focus on that element. Focus trap set for an open popover should not affect this.

### Reproduction Sample

https://codepen.io/afreitag/pen/XWzOjwK

### Reproduction Steps

Try to edit value 0 in the panel

### Reproduction Version

next.665

### Impact

very high

### Esri team

ArcGIS Map Viewer

**Comment by AdelheidF** [comment]
looks good in my various codepens, will test in map viewer later

**Comment by geospatialem** [comment]
Verified in `next.673`.
