### ISSUE TITLE
value-list,pick-list:skip unstable test 

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#6011]
### Test type

unstable test

### Which Component(s)

value-list, pick-list

### Unstable Tests

value-list : Keyboard navigation › single selection › navigating items after filtering
pick-list:  Keyboard navigation › single selection › should honor filterText

### Test error, if applicable

    Expected length: 1
    Received length: 0
    Received array:  []

### PR skipped, if applicable
#6034
#

### Additional Info

The test is passing in local and failing only in remote occasionally.
passed instance : [Merge branch 'master' into anveshmekala/4961-add-built-in-pseudo-translations](https://github.com/Esri/calcite-components/pull/5471/commits/8ecdf67cb764fd2af6c1603dbc8294b02b9e1d99) 

Failed instances:
[Merge branch 'master' into anveshmekala/4961-add-built-in-pseudo-translations](https://github.com/Esri/calcite-components/pull/5471/commits/d3aa2d3ae3b1c92be1ed91ccb6c629e005a3baff)

Ref: https://github.com/Esri/calcite-components/pull/5471/commits

There are a lot of instances where the test has failed and passed.

**Comment by geospatialem** [comment]
Verified in `master`.
