### ISSUE TITLE
Rating: if average is present but no value is set selects the first item

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-components#6021]
### Description

When there is no value set but there is an average set, it seems like it would be better UX to focus on the ~average~ first star rating first. This is discussed in PR #5948

So instead of this...
![rating-average-deselect](https://user-images.githubusercontent.com/3362490/207457819-f2d8d5ba-4e16-4b78-b5de-0cbb5396865b.gif)

It should behave like this...
![rating-acceptance](https://user-images.githubusercontent.com/5023024/213803160-f608fa45-2c38-413b-ac11-af5dcbd02b7b.gif)

### Acceptance Criteria

should focus the first rating in the component when tabbing into a component with an average set but no value.

### Relevant Info

This can be accomplished by updating rating.tsx starting on line :293 as follows.

```javascript
private handleRatingFocusIn = (): void => {
    let selectedInput = this.value > 0 ? this.value - 1 : 0;

    if (selectedInput == 0) {
      const average = this.starsMap.filter((i) => i.average);

      if (average.length > 0) {
        selectedInput = average[average.length - 1].value;
      }
    }

    const focusInput = this.inputRefs[selectedInput];
    const focusValue = Number(focusInput.value);

    focusInput.select();
    this.focusValue = focusValue;
    this.hoverValue = focusValue;
    this.hasFocus = true;
  };
 ```

### Which Component

Rating

### Esri team

Calcite (dev)

**Comment by ashetland** [comment]
Agree with this UX improvement.

**Comment by ashetland** [comment]
Hang on folks

**Comment by benelan** [comment]
cc @geospatialem for a11y considerations

**Comment by ashetland** [comment]
See this comment on PR https://github.com/Esri/calcite-components/pull/5948#issuecomment-1350049013

The above proposed behavior might be construed as leading the user to a particular rating.

**Comment by alisonailea** [comment]
solution implemented in #5948

**Comment by benelan** [comment]
Can you please change the [lifecycle label](https://github.com/Esri/calcite-components/blob/master/CONTRIBUTING.md#lifecycle) to `3 - installed` when the PR is merged instead of closing. It still needs to go through verification

**Comment by geospatialem** [comment]
@alisonailea It looks like the scope of this issue change since creation. Changing the issue name to the following to fit the pattern:

> Rating: if average is present but no value is set selects the first item

**Comment by geospatialem** [comment]
Verified on `master` branch.
