### ISSUE TITLE
Alert: autodismiss direction should go from Left to Right in RTL mode

### ISSUE THREAD

**Issue by cosbyr** [Esri/calcite-components#604]
![6067_8_RTL_bar_HE](https://user-images.githubusercontent.com/11748268/82380422-456fd300-99dd-11ea-951b-9ae399cf3a41.gif)

Reproducible on demo page: https://esri.github.io/calcite-components/?path=/story/alert--alert-rtl

**Comment by macandcheese** [comment]
Good catch, will fix 🔧.
