### ISSUE TITLE
tip,tip-manager,shell-panel: Localize and add support for built-in translation.

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#6066]
### Description

`tip`,`tip-manager` & `shell-panel` components needs to be localized and support for built-in translations needs to be added.
Epic: #4961 
### Acceptance Criteria

Localize the component
Add built-in translation support using the pattern mentioned [here.](https://github.com/Esri/calcite-components/blob/master/conventions/Internationalization.md#translation-t9n) 

### Which Component

- tip
- tip-manager
- shell-panel

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified on `master`.
