### ISSUE TITLE
Breaking Change - Remove `backgroundColor` property on `Modal`

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#6070]
### Description

Breaking Change - Remove `backgroundColor` property on `Modal`

@ashetland @SkyeSeitz @macandcheese 

Do we need the property `backgroundColor` on `Modal`? It seems like this might be better as a CSS variable.

Currently, the value is `white` or `gray`. 

I assume that the light/dark mode already alters the color depending on the mode. Do we know why this property exists and if we can remove it?

### Proposed Advantages

Advantage is that modals would be consistent in background color. Currently, there's no instruction on when to use white vs gray.

### Which Component

Modal

### Relevant Info

What is the purpose of this property? Could it be more semantic like the new "kind" properties if it does have some meaning to it?

**Comment by driskull** [comment]
cc @geospatialem

**Comment by SkyeSeitz** [comment]
I am curious about the history of this property as well. Do we know of use-case for `grey`. I would assume white would be the choice if we were to simplify.

**Comment by macandcheese** [comment]
The use case is seen a lot in Online. Often, the content slot is populated container or other "foreground" content - and this was used to let users set the background color to use the "ui-background" to let content be "ui-foreground-1", while keeping the header and footer white (in light mode) - similar like Panel.

I think the use case is common and valid, but the method of setting it is an outlier. 

Having a `--calcite-modal-content-background` css variable would let users maintain their designs (and actually be more flexible). Another option would be to discontinue entirely and tell users to slot their own div with custom background style inside the slot, but they'd need to set `--calcite-modal-content-padding` to `0` to do this, which is a bit arduous so I lean towards the former css variable option.

Some screenshots from Online (they aren't using Calcite Modal here but the use case is the same) :
<img width="800" alt="Screen Shot 2022-12-15 at 5 39 53 PM" src="https://user-images.githubusercontent.com/4733155/208002315-74516eb1-39eb-4344-b118-4ac2385dcb04.png">
<img width="800" alt="Screen Shot 2022-12-15 at 5 37 41 PM" src="https://user-images.githubusercontent.com/4733155/208002319-8f82151f-a58a-4ea7-900f-78b336ab1566.png">

Some other similar examples of this were from this closed Tile issue: https://github.com/Esri/calcite-components/issues/1021

**Comment by geospatialem** [comment]
Verified on `next.698` with the new CSS variable:

```css
calcite-modal {
  --calcite-modal-content-background: var(--calcite-ui-background);
}
```
