### ISSUE TITLE
[Accordion] Remove extraneous code with home/end/arrow keys

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6081]
### Actual Behavior

I am working on making some of our focus helpers into a general utility : https://github.com/Esri/calcite-components/pull/6075#discussion_r1051100417

While doing so, I discovered our accordion keyboard navigation (besides `tab` / `shift + tab`) stopped working at some point: https://codepen.io/mac_and_cheese/pen/LYBPyPr?editors=1000

### Expected Behavior

After discussion, this is the intentional behavior, the stale code was never removed - this issue has been repurposed to remove that code.

**Comment by macandcheese** [comment]
After discussing with @geospatialem - this may be intentional / expected. But we still have a bunch of code in the components that supposedly is handling this, so we can remove if this is indeed desired behavior.

**Comment by geospatialem** [comment]
We're going to proceed with leaving the `Home` / `End` / arrow keys as-is, instead repurposing this issue to remove the extraneous code to support the pattern.

**Comment by geospatialem** [comment]
Verified on `master` and in the `accordion` component in `beta.99`.

The `dropdown`, `stepper`, and `tabs` components added enhancement utility is also working great in `beta.99`.
