### ISSUE TITLE
[Dropdown] Navigation within Dropdown with Tab is broken

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6083]
### Actual Behavior

I am working on making some of our focus helpers into a general utility : https://github.com/Esri/calcite-components/pull/6075#discussion_r1051100417.

While doing so I found some weird behavior with the Dropdown - using `tab` or `shift/tab` to navigate within the component will move in increments of two items - which I assume is unexpected.

This also means its unreliable to close the dropdown with tab / shift-tab as you can get into a state where tab doesn't reach the first or last item due to this.

Also found another issue - when the `href` property of `dropdown-item` is populated - there is a "double tab" / focus that is unexpected.

https://codepen.io/mac_and_cheese/pen/poZzPRe?editors=100

### Expected Behavior

Tab / Shift Tab should focus the next or previous item, until the first / last item, in which case the dropdown should be closed.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/poZzPRe?editors=100

### Reproduction Steps

1. Navigate to Codepen
2. Open dropdown, use tab to navigate
3. See that items are skipped

### Reproduction Version

98

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified on `next.710`
