### ISSUE TITLE
List - Arrow navigation won't wrap focus

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#6106]
### Actual Behavior

When using arrow keys to switch focus between list-items, pressing 'down arrow' on the last list-item won't focus the first list-item (and vice-versa). Both the `pick-list` and `value-list` will wrap its focus when using arrow key navigation so I'm assuming this is a bug.

### Expected Behavior

Arrow navigation should behave the same as the `pick-list` and `value-list` with focus wrapping.

### Reproduction Sample

https://codepen.io/jmanke/pen/dyjyPYv?editors=1010

### Reproduction Steps

1. Use arrow keys to navigate calcite-list.
2. Notice focus will not wrap (pressing 'down arrow' on the last item won't focus the first element and vice-versa).

### Reproduction Version

next.701

### Impact

Low

### Esri team

ArcGIS Dashboard

**Comment by driskull** [comment]
I think this one is expected.

https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/

> If focus is on a row, moves focus one row down. If focus is on the last row, focus does not move.

**Comment by jmanke** [comment]
Thanks for clarification, closing
