### ISSUE TITLE
Tooltip does not always display on calcite-action button

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#6113]
### Actual Behavior

When hovering over the button, the tooltip does not consistently display. It seems ok the first time you hover, and then it seems to depend on placement. In some cases it will not display at all. 

![hover](https://user-images.githubusercontent.com/50747646/208496106-b21a8548-5579-4778-9dc9-5920293abf9d.gif)

cc @kevindoshier @kitt

### Expected Behavior

Tooltip should consistently display when hovering over the button. 

### Reproduction Sample

https://codepen.io/kevindoshier/pen/WNyBLVO

### Reproduction Steps

1. Open the codepen above
2. Hover mouse over the back button (Try a few times)
![image](https://user-images.githubusercontent.com/50747646/208495674-c8e59852-2f33-4db9-be70-841a049b99ab.png)
3. Sometimes tooltip will display, sometimes it will not

### Reproduction Version

next

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
@kevindoshier Would it be possible to get a more refined/directed Codepen for us to reproduce and diagnose further? cc @zaramatheson 

There might be a workaround if a heading is added the `flow-item` component.

**Comment by kevindoshier** [comment]
@geospatialem - im not sure what you are asking for, that codepen is basically how the app uses the flow-item's, would just the basic flow-item sample work that you can access through the calcite-component flow-item docs?

**Comment by geospatialem** [comment]
> @geospatialem - im not sure what you are asking for, that codepen is basically how the app uses the flow-item's, would just the basic flow-item sample work that you can access through the calcite-component flow-item docs?

@kevindoshier - we're going to continue to troubleshoot and debug on our end to help determine a fix. Stay tuned for updates.

**Comment by geospatialem** [comment]
Verified on `next.705`.
