### ISSUE TITLE
`calcite-list-item` missing pointer cursor style

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#6123]
### Actual Behavior

`calcite-list-item` does not use a pointer style for the cursor. Looks like this was fixed in https://github.com/Esri/calcite-components/issues/5880 but the pointer may have changed again?

cc @ethanbdev @AdelheidF @geospatialem 

### Expected Behavior

`calcite-list-item` uses the pointer style so the items appear clickable, see gif under "Expected behavior" here: https://github.com/Esri/calcite-components/issues/5880

### Reproduction Sample

https://codepen.io/mpayson/pen/mdjdNBq

### Reproduction Steps

1. Open code pen
2. Hover over an item

### Reproduction Version

beta.99

### Regression?

next.660

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
This seems to be a result of the `selection-mode` attribute, which is set to `"none"` by default. If adding `selection-mode="multiple"` or `"single"` the cursor is present. 

```html
<calcite-list selection-mode="single">
...
</calcite-list>
```

This seems to be the expected behavior, but we could add documentation to the component for additional context.

**Comment by mpayson** [comment]
Ah interesting, is there a way to do this without the visual selected state? Our use case is a user selects a processing tool from a list of options and that tool gets added to a processing model, I'm not sure it makes sense to keep the tool highlighted after the user chooses an option

**Comment by geospatialem** [comment]
> Ah interesting, is there a way to do this without the visual selected state?

Not at this time. Prior to the refactor we had a `nonInteractive` property, but [opted to remove it as we couldn't justify a use case compared to a `selectionMode` of `"none"`](https://github.com/Esri/calcite-components/discussions/4356#discussioncomment-2481815). 

The visual feedback is useful for more diverse audiences, so we decided to remove the `nonInteractive` prop. We'd likely need to consider the enhancement after next month's release after some team discussion.

> Our use case is a user selects a processing tool from a list of options and that tool gets added to a processing model, I don't think it makes sense to keep the tool highlighted after the user chooses an option. They can select the same option twice and that tool should get added to the model twice, for example, and they aren't choosing one exclusive option

Good to know, don't believe we knew of a use case so good to get additional context. 

For us to re-evaluate after next month's release, could you or the team add additional visuals for the expected behavior so when we are able to convene we can determine some viable options for consideration in a future release?

**Comment by ethanbdev** [comment]
The use case we have in the map viewer is in the issue linked that was originally open.. basically we use the list item to list tools that the user can select and open. The visual selection indicator does not make a lot of sense in this context as the panel changes when the user selects one of the tools.

We got feedback that not having pointer cursor styling feels a bit off, but is there a different component we could use to get this same effect maybe? The other list components also don't really fit the job it seems like

**Comment by mpayson** [comment]
> could you or the team add additional visuals for the expected behavior

Our use case is similar to Ethan's, and I think the expected behavior is how the list works in beta.98 (hover pointer & background styles, no selection style after the user clicks an option then clicks somewhere else). Here's a codepen using this version: https://codepen.io/mpayson/pen/NWBPMpM

**Comment by ashetland** [comment]
Yep, this makes sense to me as well. If we do it on the selection modes, then we should be consistent and also do it when the mode is set to `none` for the use case outlined above.

**Comment by geospatialem** [comment]
@driskull Going to add this to the January milestone to add the cursor pointer when `selectionMode` is `"none"` (default).

**Comment by geospatialem** [comment]
Verified on `next.710`

![verify-pointer-selection-none](https://user-images.githubusercontent.com/5023024/210890595-94115acb-1b16-441e-8e9d-6a586cca4032.gif)
