### ISSUE TITLE
Refactor radio-button-group `calciteRadioButtonChange` event payload

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6130]
### Description

Deprecate and remove the `calciteRadioButtonChange` event payload to a readonly prop such as `selectedItem`.

Related to  https://github.com/Esri/calcite-components/issues/6007 

cc: @driskull 

### Proposed Advantages

For consistency across components prior to the January release.

### Which Component

`radio-button-group`

### Relevant Info

To be completed ASAP to communicate the breaking change to teams before the January release.

**Comment by geospatialem** [comment]
Verified the `calciteRadioButtonChange` event `next.703` with the following JS:

```js
const radioGrp = document.querySelector("calcite-radio-button-group");

radioGrp.addEventListener("calciteRadioButtonGroupChange", (evt) => {
  console.log(evt.target.selectedItem);
})
```

@driskull Were we planning on deprecating or removing the [`calciteRadioButtonChange` event from `radio-button`](https://github.com/Esri/calcite-components/blob/master/src/components/radio-button/radio-button.tsx#L273-L279) with this refactor?

**Comment by driskull** [comment]
No, we just removed the event.detail. The event can remain.
