### ISSUE TITLE
Update Icon Dependency 

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#6131]
### Description

High Priority

Calcite icons has recently published many new icons for ArcGIS Monitor that aren't available through calcite components. The  `calcite-ui-icons` dependency will need to be updated to [v3.20.7](https://github.com/Esri/calcite-ui-icons/releases/tag/v3.20.7). This should be an easy update, but ArcGIS Monitor will need to this changed released as soon as possible.

Also - could you add ArcGIS Monitor as a 'Esri team' option for submitting issues.

### Acceptance Criteria

Update icon dependency to [v3.20.7](https://github.com/Esri/calcite-ui-icons/releases/tag/v3.20.7)

### Which Component

icons

### Esri team

N/A

**Comment by macandcheese** [comment]
@geospatialem need for 1.0

**Comment by geospatialem** [comment]
@joeyHarig The ArcGIS Monitor team is now an option in our issue templates and a label, thanks for letting us know!

**Comment by benelan** [comment]
>  The ArcGIS Monitor team is now an option in our issue templates and a label, thanks for letting us know!

FWIW, if the team isn't listed they can submit it as "N/A" and then edit the issue after submitting. Whatever they replace "N/A" with will be created as a new label and added to the issue. I think I included that in the issue template instructions but I'll double check
