### ISSUE TITLE
[Alert] Auto-close closes early if hovering over and leaving Alert

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6132]
### Actual Behavior

The auto-close Alert can close unexpectedly if a user were to hover over, and then leave the alert (or tap).

### Expected Behavior

The auto close pause works correctly while hovering, but I'd expect it to re-start the timer and only close at expiration of countdown or explicit "close button" interaction

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/dyjyqqV?editors=1001

### Reproduction Steps

1. Open codepen
2. Hover over alert
3. Move cursor off alert
4. Alert will close before timer ends and without clicking "x"

I tested on a phone and tapping then tapping "off" has the same effect.

### Reproduction Version

99

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
@geospatialem needed for 1.0 :)

**Comment by geospatialem** [comment]
Verified on `next.712`.
