### ISSUE TITLE
[Stepper / StepperItem] Add / update events

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6135]
### Description

As mentioned in this issue: https://github.com/Esri/calcite-components/issues/5023, we deprecate the event payload for `stepper` events and expose a public selected / change event for `stepper-item`

### Acceptance Criteria

The event payload for `stepper` events are deprecated, and the `stepper-item` adds a selected / change event.

### Which Component

Stepper / Stepper Item

### Esri team

Calcite (dev)

**Comment by macandcheese** [comment]
Can we keep open / re-name so we remember to add the event on the stepper-item child when selected

**Comment by geospatialem** [comment]
@macandcheese Maybe we can create a new issue for the `stepper-item` child event, so we can verify the breaking change with the 1.0 release? Or does the `stepper-item` event need to land for the 1.0 release?

**Comment by geospatialem** [comment]
cc: @jcfranco - Should the `stepper-item` selection event be added to the upcoming release? 

We added a property, `selectedItem` and removed the `event.detail` event payload, so adds `event.target.selectedItem` to get at the selected `stepper-item` with #6138

**Comment by geospatialem** [comment]
Added issue 6330 to track the Stepper Item event. The above breaking change was added to 1.0 and is verfied.
