### ISSUE TITLE
[calcite-input] `status` property doesn't have any effect

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#614]
`status` is an available property on calcite-input, but it has no effect on the styling of the input. Additionally, as far as I can tell the property is not used anywhere in the code. Is this intended to have some effect in the future?

**Comment by macandcheese** [comment]
Yeah, currently that prop only affects `calcite-input-message` and `calcite-label` (`calcite-input` and `calcite-input-message` inherit from `calcite-label` if it is present). 

I left it on `calcite-input` in case did want to style anything in the input based on status - a red focus outline for an invalid state for example. So, currently it is indeed unused style-wise.

**Comment by macandcheese** [comment]
Right now all it does is change the color of the icon (if present), and that's actually being inherited from `calcite-label` anyway. I could just move that icon color change from `calcite-label` to `calcite-input` so it actually has an effect within the component rather than cascading down.
