### ISSUE TITLE
[Tooling] Generate translation reference JSON during build

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6143]
### Summary

The documentation site uses the `docs-json.json` file in the `extras` folder of our distributable to format and display docs to users. We would benefit from having a similar output for the updated translation files. 

`docs-json.json` includes each file's `messageOverride` string names, but not the default values, which would be valuable to show in documentation. It would be great if these were included as well.

Alternatively, and maybe easier than fighting jsdoc, we could generate our own `translations-json.json` at build time, since the files seem to be in a predictable location and format: (`/dist/assets/<component>/t9n`).

### Desired Outcome

Something like this, but any format works as long as the default are available somehow.

```
{
    "components": {
        "calcite-action": {
            "loading": {
                "en": "Close",
                "es": "Cerrar"
                ...
            },
            "disabled": {
                "en": "Close",
                "es": "Cerrar"
                ...
            }
        },
        "calcite-alert": {
            "loading": {
                "en": "Close",
                "es": "Cerrar"
                ...
            },
            "disabled": {
                "en": "Close",
                "es": "Cerrar"
                ...
            }
        }
    }
}
```

**Comment by jcfranco** [comment]
@macandcheese I think we could generate something for this quite easily. What's the desired timeline for this?

**Comment by macandcheese** [comment]
As soon as reasonable without a rush - not high priority. 

Whenever it is available I can add it into documentation site. Currently we only show the English string.

**Comment by benelan** [comment]
Yeah I can whip something up after the patch period and other v1 stuff quiets down

**Comment by jcfranco** [comment]
@benelan Were you able to whip something up for this? We modified the milestone, but can move it sooner if it's feasible.

**Comment by benelan** [comment]
I haven't gotten to this yet, there are some higher priority items on my plate

**Comment by geospatialem** [comment]
Verified with `1.4.3` in the calcite-components-examples repo.
