### ISSUE TITLE
calcite-modal: custom sizing no longer working

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#6146]
### Actual Behavior

Before beta.99 we could size a modal by specifying styling for the dimensions

### Expected Behavior

Would like more control on sizing calcite-modal. Full screen can be confusing to the user because they might think they left the app.

### Reproduction Sample

https://codepen.io/kevindoshier/pen/poZvqYm

### Reproduction Steps

1. Open codepen above
2. Observe that the custom styling is applied
3. Uncomment the "next" script tags
4. Observe the custom styling is no longer applied

### Reproduction Version

beta.99

### Regression?

beta.98

### Impact

High. We want to control the size of the modal that we are hosting the arcadeEditor in

### Esri team

ArcGIS Map Viewer

**Comment by macandcheese** [comment]
These rules were moved to an internal container inside the shadow root in a recent update. That seems to align with patterns adopted in other components - but it does seem strange for modal that we also have a `width` property that could be used here...

**Comment by geospatialem** [comment]
Verified using:

1. The `width` property values of `"s"`, `"m"` and `"l"`, for instance:

```html
<calcite-modal width="l" aria-labelledby="modal-title" open>
```

and 

2. `--calcite-modal-width` and `--calcite-modal-height` CSS props.

```css
calcite-modal {
      --calcite-modal-width: 50vw;
      --calcite-modal-height: 45vh;
}
```
