### ISSUE TITLE
calcite-dropdown not displaying in v1.0.0-beta.99

### ISSUE THREAD

**Issue by capegreg** [Esri/calcite-components#6151]
### Actual Behavior

calcite-dropdown with calcite-button and calcite-dropdown-group no longer displaying in beta 99. (See codepen)
Appears to be issue with no width or height.

beta 98
![image](https://user-images.githubusercontent.com/1051118/209007724-517fc124-0051-4048-936b-68d379bf63e7.png)

beta 99
![image](https://user-images.githubusercontent.com/1051118/209007703-3292b61e-dd9a-43f6-b990-7a93cd400850.png)

### Expected Behavior

Visible calcite-dropdown with width > 0 and height > 0

### Reproduction Sample

https://codepen.io/capegreg/pen/oNMgmMd

### Reproduction Steps

Toggle beta version 98 to 99 to see that calcite-dropdown no longer display.

`<script type="module" src="https://unpkg.com/@esri/calcite-components@1.0.0-beta.98/dist/calcite/calcite.esm.js"></script>
<link rel="stylesheet" type="text/css" href="https://unpkg.com/@esri/calcite-components@1.0.0-beta.98/dist/calcite/calcite.css" />

<calcite-dropdown id="pao-buffer-unit" overlay-positioning="fixed" placement="bottom-start" type="click" scale="m" max-items="0" style="white-space: nowrap;" calcite-hydrated="">
  <calcite-button slot="dropdown-trigger" id="pao-buffer-unit-button" scale="m" alignment="center" appearance="solid" color="blue" type="button" width="auto" calcite-hydrated="">Click</calcite-button>
  <calcite-dropdown-group id="pao-buffer-unit-group1" selection-mode="single" role="group" calcite-hydrated="">
    <calcite-dropdown-item id="pao-unit-feet" data-unit-abrv="ft" aria-checked="true" role="menuitemradio" tabindex="0" calcite-hydrated="" active="" selected="">Feet</calcite-dropdown-item>
    <calcite-dropdown-item id="pao-unit-yards" data-unit-abrv="yds" aria-checked="false" role="menuitemradio" tabindex="0" calcite-hydrated="">Yards</calcite-dropdown-item>
  </calcite-dropdown-group>
</calcite-dropdown>

<calcite-dropdown id="pao-buffer-unit" overlay-positioning="fixed" placement="bottom-start" type="click" scale="m" max-items="0" style="white-space: nowrap;" calcite-hydrated="">
  <calcite-button slot="dropdown-trigger" id="pao-buffer-unit-button" scale="m" alignment="center" appearance="solid" kind="brand" type="button" width="auto" calcite-hydrated="">Click</calcite-button>
  <calcite-dropdown-group id="pao-buffer-unit-group1" selection-mode="single" role="group" calcite-hydrated="">
    <calcite-dropdown-item id="pao-unit-feet" selected="" data-unit-abrv="ft" aria-checked="true" role="menuitemradio" tabindex="0" calcite-hydrated="">Feet</calcite-dropdown-item>
    <calcite-dropdown-item id="pao-unit-yards" data-unit-abrv="yds" aria-checked="false" role="menuitemradio" tabindex="0" calcite-hydrated="">Yards</calcite-dropdown-item>
  </calcite-dropdown-group>
</calcite-dropdown>`

### Reproduction Version

1.0.0-beta.99

### Relevant Info

Windows 10,
Chrome 108

### Impact

Cannot move to latest version.

### Esri team

N/A

**Comment by macandcheese** [comment]
Hi @capegreg - the slot name was changed to `trigger` in `beta.99` : 

https://codepen.io/mac_and_cheese/pen/yLqywRK?editors=1010

**Comment by capegreg** [comment]
> Hi @capegreg - the `dropdown-trigger` slot name was changed to `trigger` in `beta.99` :
> 
> https://codepen.io/mac_and_cheese/pen/yLqywRK?editors=1010

Got it. All good now. Thank you very much!
