### ISSUE TITLE
Rename `radio-group` and `radio-group-item` components

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6152]
### Description

Rename the components to eliminate confusion. As an example [Ant Design](https://ant.design/components/segmented) uses the name `segmented`.

### Proposed Advantages

To eliminate the confusing name hopscotch.

### Which Component

`radio-group`, `radio-group-item`

### Relevant Info

Rename should be considered by designers and developers. 

cc @ashetland @SkyeSeitz @driskull @macandcheese

**Comment by geospatialem** [comment]
Stems from #2512

**Comment by macandcheese** [comment]
I like ‘segmented-something’, I think both ‘segmented-toggle’ and ‘segmented-control’ are pretty familiar names for this element.

**Comment by ashetland** [comment]
I like segmented-control. This is a separate issue, but could we allow icon-only as well?

**Comment by SkyeSeitz** [comment]
I agree with `segmented-control` 👍🏽

**Comment by geospatialem** [comment]
@driskull Sounds like `segmented-control` is what we're working towards. Would you or another dev be able to pick up the change this week?

**Comment by driskull** [comment]
@geospatialem I don't have the bandwidth to take this one. 

Do we need the `-control` part? or would `calcite-segmented` and `calcite-segmented-item` be enough?

@benelan @macandcheese @eriklharper @anveshmekala @Elijbet does one of you have the bandwidth to rename these two components as a breaking change?

**Comment by macandcheese** [comment]
I can pick this up. I think it should probably be `calcite-segmented-control` though, "segmented" is just a descriptor. Or we could go with "chunky buttons" like giffgaff system : https://component.gallery/components/segmented-control/

**Comment by driskull** [comment]
I just saw that `ant` doesn't use the `-control` part.

**Comment by ashetland** [comment]
Omg "chunky buttons"! But seriously, unless there's a good reason to omit `-control`, I'm in the camp of `calcite-segmented-control` and `calcite-segmented-control-item`.

**Comment by ethanbdev** [comment]
Should the event be renamed? https://github.com/Esri/calcite-components/blob/master/src/components/segmented-control/segmented-control.tsx#L253

**Comment by macandcheese** [comment]
@ethanbdev - thanks for the catch, pr incoming...

**Comment by geospatialem** [comment]
Verified on `next.714` with `calcite-segmented-control` and `calcite-segmented-control-item`:

```html
<calcite-segmented-control>
    <calcite-segmented-control-item value="layers" checked>Layers
    </calcite-segmented-control-item>
    <calcite-segmented-control-item value="data">Data</calcite-segmented-control-item>
    <calcite-segmented-control-item value="geography">Geography</calcite-segmented-control-item>
    <calcite-segmented-control-item value="maps">Maps</calcite-segmented-control-item>
</calcite-segmented-control>
```

Also, verified on `master` no remaining `radio-group-` or `radioGroup-` instances are presented and have been renamed to the new pattern of `segmented-control-` and `segmentedControl-`. 👍🏻
