### ISSUE TITLE
[Pagination] Undocument `--calcite-pagination-spacing` css var

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6158]
### Actual Behavior

Currently the `--calcite-pagination-spacing` css var is public and setting it results in unwanted changes.
<img width="1027" alt="Screen Shot 2022-12-21 at 3 56 26 PM" src="https://user-images.githubusercontent.com/4733155/209026839-6c5cf5dd-d176-4f3d-86de-46ee8592fdd9.png">

We should remove the documentation for this. Rating has a "space between" public css var that may better serve this use case.

### Expected Behavior

`--calcite-pagination-spacing` is not documented, or if it is, the behavior matches that of rating where the space between items is adjusted, not the spacing of the entire component.

### Reproduction Sample

No

### Reproduction Steps

No

### Reproduction Version

99

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified on `next.710`.
