### ISSUE TITLE
calcite-radio-group-item checked=false looks checked

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#616]
Might have something to do that it's being used with Maquette.

![image](https://user-images.githubusercontent.com/44481292/82697327-8fdf9280-9c1d-11ea-88a8-82a410a29b4f.png)

normally it looks like this
![image](https://user-images.githubusercontent.com/44481292/82697389-b271ab80-9c1d-11ea-83ed-955f3643c00d.png)

**Comment by macandcheese** [comment]
Can you try removing `checked` attribute from DOM rather than using `checked="false"`?

**Comment by AdelheidF** [comment]
before
`checked={isAutomatic ? "true" : "false"}`

now
`checked={isAutomatic ? "true" : null}`

![image](https://user-images.githubusercontent.com/44481292/82701945-e9e45600-9c25-11ea-8321-30b52cf07bc4.png)

doc:
![image](https://user-images.githubusercontent.com/44481292/82702042-126c5000-9c26-11ea-983d-2274da7c1e0f.png)

**Comment by AdelheidF** [comment]
Found a way around the issue by using a new key every time.

**Comment by AdelheidF** [comment]
No, I can't make it work. If I use a new key every time I run into issues with afterCreate.

The problem seems to be that it renders twice in a short time, the second time after an async call for the renderer update returns.

Might have to go back to use calcite-buttons.

**Comment by AdelheidF** [comment]
I don't see the same with calcite-radio-button even with a similar scenario.

**Comment by AdelheidF** [comment]
Found a workaround for just the one button that shows the checked="false" in the dom.

Instead of this:
```
<calcite-radio-group-item
...
checked={!isAutomatic ? "true" : "false"}
...
```

I do this:
```
            {!isAutomatic ? (
              <calcite-radio-group-item
                key="size-range-fixed-button"
                checked="true"
                value="fixed"
              >
                {i18n.ui.custom}
              </calcite-radio-group-item>
            ) : (
              <calcite-radio-group-item
                key="size-range-fixed-button"
                value="fixed"
              >
                {i18n.ui.custom}
              </calcite-radio-group-item>
            )}
```

weird

**Comment by macandcheese** [comment]
That makes sense, `checked="false"` would still be interpreted as `checked` being present in the DOM. Closing for now but feel free to re-open if the above does not work 🎈 .
