### ISSUE TITLE
[Combobox Item] Remove `toggleSelected` method

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6160]
### Description

The Combobox Item component has a `toggleSelected` method - we should evaluate if this can be removed in favor of users setting / unsetting `selected` on the item, and remove it if so.

### Proposed Advantages

Bring up to speed with latest patterns.

### Which Component

Combobox Item (it also exists on soon-to-be-deprecated Pick List / Value List - but can probably leave until their eventual removal)

**Comment by geospatialem** [comment]
Verified the `toggleSelected` method is no longer publicly accessible on `next.711`.
