### ISSUE TITLE
[calcite-input-message] Inactive floating message is still clickable and covers part of input

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#617]
When a calcite-input-message is Inactive and floating. The message is still clickable over the input causing a button-style cursor.

Steps to reproduce:
- Go to https://esri.github.io/calcite-components/?path=/story/input--with-label-and-input-message
- In the Knobs, go to Input Message and uncheck active and set type to `floating`
- Hover over the bottom half of the input and the cursor looks like a button click
- Hover over the top half and the cursor looks like a standard text cursor as expected

This is a pretty minor issue and has no effect on functionality. In both cases it focuses the input as expected. It just looks a little odd.

**Comment by macandcheese** [comment]
Occurs on `type=default` in addition to `floating` too. Will fix.
