### ISSUE TITLE
[tile-select] Can't make selection by clicking tile with dist-custom-elements

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#6185]
### Actual Behavior

It looks like when using `dist-custom-elements`, users can't click a tile to make a selection for tile select components, they have to click the radio button circle. This differs from the `dist` behavior, where the user can click the entire tile to make a selection.

### Expected Behavior

The user can click the tile to make a selection like with the `dist` output.

### Reproduction Sample

https://github.com/mpayson/calcite-components-examples/tree/tile-select-issue

### Reproduction Steps

1. Clone the repository and checkout the `tile-select-issue` branch
2. `cd react && npm install && npm start`
3. Click a tile, see it does not make a selection
5. Go to this codepen: https://codepen.io/mpayson/pen/yLqezWB
6. Click a tile, see it does make a selection

### Reproduction Version

beta.99

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Research will be conducted in March to determine next steps.

**Comment by geospatialem** [comment]
Verified in `1.2.0-next.0`

![verify-select](https://user-images.githubusercontent.com/5023024/228124509-b5c017f0-7d69-4745-a382-0d31370be2ba.gif)
