### ISSUE TITLE
[modal] TypeError when calling `setFocus` with dist-custom-elements

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#6188]
### Actual Behavior

When calling `setFocus` on calcite-modal with dist-custom-elements, the TypeError below gets thrown. The error stems from `focusTrapEl` being undefined when focusFirstTabbable is called [here](https://github.com/Esri/calcite-components/blob/master/src/components/modal/modal.tsx#L387), so maybe the fix from #5749 does not work with the custom-elements output type? Also, it does look like `setFocus` gets called internally [here](https://github.com/Esri/calcite-components/blob/master/src/components/modal/modal.tsx#L463) and focuses the close button as expected, so consuming apps may not need to call it?

```
focusTrapComponent.js:76 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tagName')
    at getCandidatesIteratively (focusTrapComponent.js:76:1)
    at tabbable (focusTrapComponent.js:418:1)
    at focusFirstTabbable (focusTrapComponent.js:1250:1)
    at Modal.open.setFocus (calcite-modal.js:226:1)
```

### Expected Behavior

`setFocus` method waits until the component has loaded and the TypeError is not thrown

### Reproduction Sample

https://github.com/mpayson/calcite-components-examples/tree/set-focus-issue

### Reproduction Steps

1. Clone the repository and checkout the set-focus-issue branch
2. `cd react && npm install && npm start`
3. Open developer console
4. Click button to open the modal, see console error
5. Switch the [loading strategy here](https://github.com/mpayson/calcite-components-examples/blob/set-focus-issue/react/src/App.js#L7) by commenting lines 5-6 and un-commenting lines 7-8
6. Refresh the page
7. Click button to open the modal, don't see console error

### Reproduction Version

beta.99

### Esri team

ArcGIS Online

**Comment by benelan** [comment]
Note: this isn't specific to React, it repro's in the vite sample as well:

<details open>

<summary>index.html</summary>

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<link rel="icon" type="image/svg+xml" href="favicon.svg" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Calcite Vite</title>
	</head>
	<body>
      <calcite-button>Click me!</calcite-button>
        <calcite-modal open>
          <div slot="header">Demo</div>
          <div slot="content">hi!</div>
        </calcite-modal>
		<script type="module" src="/main.js"></script>
	</body>
</html>
```

</details>

<details open>

<summary>main.js</summary>

```js
import { setAssetPath } from "@esri/calcite-components/dist/components";
import "@esri/calcite-components/dist/components/calcite-button";
import "@esri/calcite-components/dist/components/calcite-modal";
import "@esri/calcite-components/dist/calcite/calcite.css";
import "./style.css";

setAssetPath(location.href);
```

</details>

**Comment by jcfranco** [comment]
@mpayson Thanks for the excellent issue description. Installed a workaround to avoid the error, while we look into creating a repro case. Fortunately, as you pointed out, focus works as expected after the open transition.

**Comment by geospatialem** [comment]
Verified with `master`.
