### ISSUE TITLE
Input Date Picker Range: start date's hover style starts at the beginning of the month

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#6194]
### Actual Behavior

Hovering over start date adds hover style starting at the first day of the month, even when the component has no value.

### Expected Behavior

- For the start date, only the day under the cursor has hover style when the component does not have a value. See `next.701` functionality for reference

### Reproduction Sample

https://esri.github.io/calcite-components/?path=/story/components-controls-inputdatepicker--range

### Reproduction Steps

1. Open the start date picker and hover over the days

### Reproduction Version

next.703

### Relevant Info

I'm pretty sure it's a regression due to #6085, @eriklharper can you take a look?

### Regression?

next.701

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified on Storybook and in `1.1.0-next.2`.
