### ISSUE TITLE
Input Date Picker: internal input doesn't display numerals in the numberingSystem

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#6198]
### Actual Behavior

The internal input no longer displays numerals in the specified numbering system

### Expected Behavior

The internal input should display numerals in the specified numbering system

### Reproduction Sample

https://codepen.io/benesri/pen/xxJZvmB

### Reproduction Steps

1. Type numbers into the input and notice they are `latn` numerals, even though the `numberingSystem` property is `arab`
2. Switch the version to `next.621`
3. Repeat step 1 and notice the numbers are `arab` numerals

### Reproduction Version

next.703

### Relevant Info

This is a regression from #5459

Related issue: #5886

@eriklharper do you have bandwidth to help with this one? The component is completely different than the last time I looked at it and most of the i18n code I added is gone. You have a better idea of what's going on in the component right now and it would probably take me a while to get back up to speed. If you're swamped I can take a stab at it though, let me know.

### Regression?

next.621

### Esri team

Calcite (dev)

**Comment by eriklharper** [comment]
> @eriklharper do you have bandwidth to help with this one? The component is completely different than the last time I looked at it and most of the i18n code I added is gone. You have a better idea of what's going on in the component right now and it would probably take me a while to get back up to speed. If you're swamped I can take a stab at it though, let me know.

Yeah, I can assign myself to this, I'm going to be adding numberingSystem support to Input Time anyway, so all the info will be fresh in my head anyway.

**Comment by benelan** [comment]
Awesome, thanks! Let me know if you have any questions about the `numberingSystem` utils I wrote as you work through the issues.

**Comment by eriklharper** [comment]
After some fresh thinking on this, I'm wondering if the computer's Input Source should be the "source of truth" when it comes to what characters display as the result of typing into inputs, regardless of any component-specific settings.  Meaning, if I have a U.S. keyboard layout, I, as a user probably expect to see latin numerals anywhere I type, even on Arabic date picking/text/number inputs.  By Input Source, I'm referring to the setting of the same name in macOS:

![image](https://user-images.githubusercontent.com/821864/214132468-289bcd3b-6b0c-48e0-94e8-e9c3aa0c907d.png)

The logical outcome to a setting like this is that the component would still render read-only and committed content in the specified language/character system, but respect the user's Input Source setting for data entry only.  This could mean that when the user focuses any editable portion of UI, they would see characters native to the Input Source, but after committing the value and blurring the input the component would display those characters in the specified language on the component.

**Comment by jcfranco** [comment]
@eriklharper What you propose is interesting, but it sounds complex and not sure if possible. From what I understand, we would have to parse the input text into a number (1) to then format (2). For 1, I don't believe we have access to the OS to determine the input source, so not sure how we can reliably parse the input.

In any case, can we stick to the original bug for the time being?

**Comment by benelan** [comment]
Yeah I looked into this a bit when implementing NumberingSystem to try to determine a default and it wasn't possible. There are no _public_ APIs that allow us to grab operating system preferences like that. The closest we could do was getting the default numbering system from `NumberFormat.resolvedOptions()`

https://github.com/esri/calcite-components/blob/1e518748527aa8a61854311c783a07d8b3973b8c/src/utils/locale.ts#L136

The other option was using `navigator.language` but I don't remember why the Intl approach was better.

**Comment by geospatialem** [comment]
Verified on `1.0.4-next.2`

<img width="153" alt="Screenshot 2023-01-28 at 9 10 05 PM" src="https://user-images.githubusercontent.com/5023024/215302420-bf3cb345-2cf5-4b42-b5a5-deaf5e626aad.png">
