### ISSUE TITLE
Initials in avatar do not pass color contrast in all combinations

### ISSUE THREAD

**Issue by samanthahunter** [Esri/calcite-components#6203]
### Summary

Various combinations of the background color and initial text do not pass color contrast. ArcGIS Hub uses the avatar component heavily in our discussions UI (this feature is gated to premium users, so can contact Sam Hunter for credentials if needed) which is where we noticed the issue due to problems with custom themes being applied. However, after checking the Design System and Figma examples in a contrast checker, various combinations are not passing even when a custom theme is absent so the issue isn't just in Hub.

### Actual Behavior

Calcite avatar in pink/light mode, and Calcite avatar in green/dark mode - do not pass contrast. We did not check all combinations.

<img width="825" alt="Screenshot 2022-12-29 at 2 40 51 PM" src="https://user-images.githubusercontent.com/33425289/210004283-773a8c0c-5c10-4154-9135-cc920e281df0.png">

Also seeing issues when testing options from Figma combos which are different than the Design System site:
<img width="748" alt="Screenshot 2022-12-29 at 2 40 43 PM" src="https://user-images.githubusercontent.com/33425289/210004336-fac27981-d400-48a4-8650-181891f0f765.png">

### Expected Behavior

All text and color combos pass color contrast when no custom theme is applied (uses Calcite defaults)

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/avatar/

### Reproduction Steps

Looking at combinations from the [Design System site](https://developers.arcgis.com/calcite-design-system/components/avatar/) using dev tools I inspect for the hex colors to put in in [web Aim's contrast checker](https://webaim.org/resources/contrastchecker/)

### Reproduction Version

v1.0.0-beta.98

### Working W3C Example/Tutorial

https://www.w3.org/TR/WCAG21/#contrast-minimum

### Relevant Info

I was testing against AA - where "Large text is defined as 14 point (typically 18.66px) and bold or larger, or 18 point (typically 24px) or larger."

<img width="332" alt="Screenshot 2022-12-29 at 2 49 11 PM" src="https://user-images.githubusercontent.com/33425289/210004984-aaeadf2a-8880-4b01-862d-70a6f2f88b80.png">

Given initials text is not larger than 18px, it does not qualify as 'Large' so it needs to pass on 'Normal' text criteria on [WebAim](https://webaim.org/resources/contrastchecker/) if I am understanding the requirements correctly.

From 2.1 guidelines:
The visual presentation of [text](https://www.w3.org/TR/WCAG21/#dfn-text) and [images of text](https://www.w3.org/TR/WCAG21/#dfn-images-of-text) has a [contrast ratio](https://www.w3.org/TR/WCAG21/#dfn-contrast-ratio) of at least 4.5:1, except for the following:

Large Text
[Large-scale](https://www.w3.org/TR/WCAG21/#dfn-large-scale) text and images of large-scale text have a contrast ratio of at least 3:1;

### Esri team

ArcGIS Hub

**Comment by geospatialem** [comment]
cc @SkyeSeitz @ashetland

**Comment by ashetland** [comment]
Thanks for logging this issue, @samanthahunter! I believe these colors are assigned programmatically. @macandcheese, is that true? Is there a set of color combinations that are chosen? Trying to determine how much control we have on this what it will take to fix.

**Comment by geospatialem** [comment]
Research needed from developers on what is possible to achieve. Once determined, can ping designers for next steps. cc @jcfranco

**Comment by geospatialem** [comment]
Verified on `master` with light and dark modes using the WAVE extension.

![image](https://user-images.githubusercontent.com/5023024/225350874-cd700e7c-db92-44ea-a917-237eef7aa0e9.png)
