### ISSUE TITLE
Input Date Picker: date value does not match its placeholder format for ar lang

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#6209]
### Actual Behavior

The date format for the `ar` lang seems incorrect, although @annierm18 can you confirm? If it is correct, then the placeholder needs to be updated

### Expected Behavior

The value should match the format of the placeholder

### Reproduction Sample

https://codepen.io/benesri/pen/qByZmXd

### Reproduction Steps

1. Open the sample and look at the placeholder vs the format when the component has a value

### Reproduction Version

next.704

### Relevant Info

This first reproduced in `next.591`, the last working version was `next.581`. Unfortuantely there were no next releases between those two due to technical difficulties at the time. So one of these commits caused the issue:

https://github.com/Esri/calcite-components/compare/v1.0.0-next.581...v1.0.0-next.591

Potentially #5216, although I didn't see anything suspicious when skimming through the PR's diff.

### Regression?

beta.581

### Esri team

N/A

**Comment by benelan** [comment]
lol it's actually coming from `Intl`: https://codepen.io/benesri/pen/eYjZEyV

So should we update our placeholder to `DDYYYY/MM` @annierm18? 

https://github.com/Esri/calcite-components/blob/0038162ce593a522f48b985ea290788aa55e257e/src/components/date-picker/assets/date-picker/nls/ar.json#L6

**Comment by benelan** [comment]
Our logic assumes there will be three separators, so we would need to update that as well. Currently typing a date in the input using either `Intl` or the placeholder's format doesn't commit a value. cc @eriklharper

**Comment by annierm18** [comment]
@benelan I checked with my teammates on this and we agreed that the existing behavior, where the placeholder value is "DD/MM/YYYY" when dir is rtl and ltr, is okay to keep as-is.
