### ISSUE TITLE
Long, unbreakable BIDI text flows out of calcite-button in special conditions

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#621]
This is not a calcite-components bug. It seemed like an interesting what-not-to-do from a library client's perspective. There is an easy workaround.

We have an app that combines &lt;input&gt;, &lt;div&gt;, and &lt;calcite-button&gt; on a single line. The &lt;div&gt; and &lt;calcite-button&gt; change size to fit their contents; the &lt;input&gt; uses the rest of the space. The developer chose to use `style="width:100%"` to achieve the &lt;input&gt; size change. With this choice, long, unbreakable BIDI text such as pseudo strings ("כן_Filter_____________ש") can flow out of calcite-button bounds; non-BIDI text is fine:

![image](https://user-images.githubusercontent.com/2125181/82715643-f5954400-9c48-11ea-93fe-6bf27d3b4839.png)

Here is HTML to reproduce the above image:

```html
<!doctype html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link
    rel="stylesheet"
    type="text/css"
    href="https://unpkg.com/@esri/calcite-components@1.0.0-beta.26/dist/calcite/calcite.css"
  />
  <script
    type="module"
    src="https://unpkg.com/@esri/calcite-components@1.0.0-beta.26/dist/calcite/calcite.esm.js"
  ></script>
  <script
    nomodule=""
    src="https://unpkg.com/@esri/calcite-components@1.0.0-beta.26/dist/calcite/calcite.js"
  ></script>
  <style>
  div { border: 1px dotted lightgreen;}
  </style>
</head>
<body>
  <div lang="en" dir="ltr" style="display:flex">
    <input style="width:100%" placeholder="long English ltr OK">
    <div style="display:flex;flex:1 1 auto">en ltr</div>
    <calcite-button appearance="transparent" scale="s">abcdefghijklmnopqrstuvwabcdefghijklmnopqrstuvw</calcite-button>
  </div>
  <br/>
  <div lang="en" dir="rtl" style="display:flex">
    <input style="width:100%" placeholder="long English rtl OK">
    <div style="display:flex;flex:1 1 auto">en rtl</div>
    <calcite-button appearance="transparent" scale="s">abcdefghijklmnopqrstuvwabcdefghijklmnopqrstuvw</calcite-button>
  </div>
  <br/>
  <div lang="he" dir="rtl" style="display:flex">
    <input style="width:100%" placeholder="long Hebrew rtl OK">
    <div style="display:flex;flex:1 1 auto">he rtl</div>
    <calcite-button appearance="transparent" scale="s">וְהָאֲחַשְׁדַּרְפְּנִיםוְהָאֲחַשְׁדַּרְפְּנִיםוְהָאֲחַשְׁדַּרְפְּנִים</calcite-button>
  </div>
  <br/><br/><br/>
  <div lang="he" dir="rtl" style="display:flex">
    <input style="width:100%" placeholder="long bidi rtl not OK">
    <div style="display:flex;flex:1 1 auto">he rtl</div>
    <calcite-button appearance="transparent" scale="s">abcdefghijklmnopqrstuvwוְהָאֲחַשְׁדַּרְפְּנִיםabcdefghijklmnopqrstuvw</calcite-button>
  </div>
  <br/>
  <div lang="en" dir="ltr" style="display:flex">
    <input style="width:100%" placeholder="long bidi ltr not OK">
    <div style="display:flex;flex:1 1 auto">en ltr</div>
    <calcite-button appearance="transparent" scale="s">abcdefghijklmnopqrstuvwוְהָאֲחַשְׁדַּרְפְּנִיםabcdefghijklmnopqrstuvw</calcite-button>
  </div>
</body>
</html>
```

The problem goes away if the &lt;input&gt; and &lt;div&gt; styles are changed:
```html
    <input style="display:flex;flex:auto" placeholder="long English ltr OK">
    <div style="display:flex;flex:none">en ltr</div>
```

**Comment by macandcheese** [comment]
Hey @MikeTschudi - do you have an example of what the `<div>` contains? If it's just text, maybe we can handle this better with our `suffix-text` and slotted `input-action`...

ie (long URL warning): https://esri.github.io/calcite-components/?path=/story/input--with-slotted-action&knob-status=idle&knob-scale=m&knob-label%20text=My%20great%20label&knob-type=text&knob-alignment=start&knob-number-button-type=horizontal&knob-min=&knob-max=&knob-step=&knob-prefix-text=&knob-suffix-text=test%20text&knob-loading=&knob-value=&knob-placeholder=Placeholder%20text&knob-button%20width=auto&knob-action%20button%20text=Go&knob-input-message-active=&knob-input%20message%20type=default&knob-input%20message%20status=idle&knob-input%20message%20text=My%20great%20input%20message

If it's more than just text in the `<div>` maybe we could wrap unbreakable strings at a certain point similar to the recent calcite-tree issue?

**Comment by MikeTschudi** [comment]
@macandcheese, the div contained a &lt;calcite-dropdown&gt;; I omitted it from the example because it had no effect on the display problem.

Here's what the app has:
![image](https://user-images.githubusercontent.com/2125181/83278288-367ce380-a188-11ea-87e0-652bae899a7a.png)

with roughly the html
```html
<div class="grid-container">  <!-- plus width:unset -->
  <div class="input-group">  <!-- plus display:flex -->
    <input class="input-group-input input-search input-minimal" type="text"
      placeholder="כן_Search Solutions_________________ש">
    <calcite-button class="clear-btn hide invisible hydrated" appearance="transparent" color="dark" scale="m" dir="rtl"
      width="auto" icon-position="start">
      <calcite-icon scale="m" icon="x" class="hydrated"></calcite-icon>
    </calcite-button>
    <div style="display:flex;flex:1 1 auto;white-space:nowrap">
      <calcite-dropdown class="sort-control-dropdown hydrated" alignment="end" width="l" dir="rtl" scale="m"
        type="click">
        <calcite-button slot="dropdown-trigger" appearance="transparent"
          icon="sort-descending" icon-position="start" color="blue" hastext="" scale="s" dir="rtl" width="auto">כן_Date
        Modified______________ש</calcite-button>
        <calcite-dropdown-group group-title="כן_Sort by_______________ש" selection-mode="single" class="hydrated">
                   :                   :                   :                   :
        </calcite-dropdown-group>
      </calcite-dropdown>
    </div>
    <calcite-button class="filter-btn sort-control flex visible hydrated" appearance="transparent" icon="sliders"
      icon-position="start" color="blue" active="" hastext="" scale="s" dir="rtl" 
      width="auto">כן_Filter_____________ש</calcite-button>
  </div>
</div>
```

**Comment by paulcpederson** [comment]
I don't think there is much we can do on the library side for this. Devs are free to apply whatever layout they want to to the components. It's impossible for us to know what the layout should be as we only have context at the more granular component level. 

When using flex, devs should be explicit about how the flex is applied. If they want the button to always fit it's content, use `flex: 0`. If you want the input to grow to fill extra space, use `flex: 1 1 auto; min-width: 0;`. You have to tell flex how to apply the space, and when it's ok to break. I updated your example to just use flex to do this layout: https://codepen.io/paulcp/pen/WNwqdwX?editors=1000

I am going to close this, but feel free to reopen (you as well @macandcheese ) if there is something we can address on our side for this!
