### ISSUE TITLE
[Date Picker] Square End Date Bug

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-components#6214]
### Actual Behavior

End date renders as a square upon clicking away. 

[Storybook](https://esri.github.io/calcite-components/?path=/story/components-controls-datepicker--range&knob-checked=true&knob-disabled=true&knob-filterEnabled=true&knob-intl-deselect=Deselect&knob-intl-loading=Loading&knob-intl-select=Select&knob-label=Checkbox&knob-loading=true&knob-scale=m&knob-selectable=true&knob-selected=true&knob-thumbnail-position=block-start)

<img width="317" alt="image" src="https://user-images.githubusercontent.com/29716057/210119589-308aa325-2eee-4205-8509-c41beb8c3d9b.png">

### Expected Behavior

End date should remain a circle upon clicking away 

<img width="309" alt="image" src="https://user-images.githubusercontent.com/29716057/210119611-6e4e1e62-6272-44cf-be07-adccac1bb776.png">

### Reproduction Sample

https://www.figma.com/file/fBkmuAy3R4BfjAWlRi2KjS/Calcite-Web-Components?node-id=8279%3A183723&t=pYFjKgFC7uZTs5lf-1

### Reproduction Steps

Reach out if access to the Figma file is needed.

### Reproduction Version

v1.0.0-beta.99

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
cc @apfister @ashetland

**Comment by macandcheese** [comment]
![pulp-fiction-mia](https://user-images.githubusercontent.com/4733155/210121011-6098f806-c9ed-4c9c-8fe4-4a69974e5390.gif)

**Comment by Elijbet** [comment]
This is a duplicate issue. Also possibly my fault 🙄 https://github.com/Esri/calcite-components/issues/5544. I haven't had a chance to check or address this.

**Comment by geospatialem** [comment]
Closing in favor of issue 5544.
