### ISSUE TITLE
Min & Max values not honored on calcite-input

### ISSUE THREAD

**Issue by pemberdom** [Esri/calcite-components#622]
When using a `calcite-input` from type "number", we can set values for `min` and `max`.

Those values are honored by the step down/up buttons, but not by the input itself. Greater than max and lesser than min values can be entered.

<img width="131" alt="image" src="https://user-images.githubusercontent.com/45367780/82762828-116b2800-9db8-11ea-9ea1-7b9e686915cc.png"> <img width="90" alt="image" src="https://user-images.githubusercontent.com/45367780/82762812-01534880-9db8-11ea-9ea3-67371848dfbc.png">

Is there a way besides adding an extra test in the `onCalciteInputChange` handler function to have those values rejected?

**Comment by pemberdom** [comment]
To add a precision: there's a difference of behavior when incorrect values are entered in the input.
If we consider that same `calcite-input` having min=1 and max=64, when the `onCalciteInputChange` handler function is called we receive in `e.target.value`:
Value entered | Value received by the handler
--- | ---
40 | 40
-5 | -5
99 | 99
"something" | "" (empty string)
55.2 | 55.2
55....2 | "" (empty string)

So in the handler we can ignore easily the empty string values, but for the numeric values out of bounds we need to implement an extra test (unless we're missing an error/valid property)?

**Comment by macandcheese** [comment]
I believe even a native input with set min and max allows any number to be typed. But, I also think it will try to validate on submission if contained in a form so maybe we can do a better job at checking that.

We should make it as close to native behavior as possible here.
