### ISSUE TITLE
calcite-block: handle label not translated

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#6248]
### Actual Behavior
![image](https://user-images.githubusercontent.com/3362490/219098686-86cc7477-43b7-4d5e-b72f-db9812087829.png)

### Expected Behavior
handle should be translated

### Reproduction Sample
https://codepen.io/afreitag/pen/RwBbgxK

### Reproduction Steps
Hover over the drag handle and you'll see the English text "handle". Hover over the expand/collapse icon an you'll see French text.

### Reproduction Version
beta.99

### Relevant Info
No response

### Regression?
don't think so

### Impact
medium/high

### Esri team
ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Verified on `master`.

### `en`:
![image](https://user-images.githubusercontent.com/5023024/225348157-f169f1cf-a3ef-4dd4-948e-2a453c83f9c9.png)

### `ar`:
![image](https://user-images.githubusercontent.com/5023024/225348401-c5ef9252-f298-4031-942e-70d3b035f46a.png)
