### ISSUE TITLE
Min & max properties as numbers on calcite-input?

### ISSUE THREAD

**Issue by pemberdom** [Esri/calcite-components#627]
The min & max properties on a numeric `calcite-input` are typed as string:

![image](https://user-images.githubusercontent.com/45367780/83177650-4e932b00-a0d4-11ea-93c4-7b0d63908ecf.png)

Is it because those properties can also be used on text inputs? If not and if there are only used for the "number" input, would it make sense for you to change their type to `number` as on the native number imput?

Thanks!

**Comment by macandcheese** [comment]
related https://github.com/Esri/calcite-components/issues/593
