### ISSUE TITLE
Tooltip does not open while pointer is moving

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#6278]
### Actual Behavior

An element's tooltip does not start to open until the user stops moving the pointer over the reference element.

### Expected Behavior

An element's tooltip starts to open when the user first moves the pointer onto the reference element.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/YzjVoMK

### Reproduction Steps

1. Visit the code sample
2. Move the continuously mouse within the reference element and note the tooltip does not appear
3. Stop moving the mouse and see the tooltip appear

### Reproduction Version

next.702

### Relevant Info

I suspect the issue was actually introduced in `next.701` (possibly #6119), but that release's build doesn't appear to reflect those changes for some reason.

### Regression?

beta.99

### Impact

Tooltips open at inconsistent points in time.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.6`
