### ISSUE TITLE
[Segmented Control] Duplicate Segmented Control Item value crashes component

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6283]
### Actual Behavior
When two child Segmented Control Item have matching values, and a user tries to interact with the Segmented Control, the component with freeze and crash the tab. Obviously each component should have its own unique value, so this is more of how we handle a case where they match in a better way.

### Expected Behavior
While values should be unique in a real-world situation, the component should fail more gracefully than crashing the entire page.

### Reproduction Sample
https://jsbin.com/bogovenune/edit?html,output

### Reproduction Steps
Go to Jsbin link
Observe two matching values on Segmented Control Item
Select one of the Segmented Control Item
Select the third item
Watch the world burn 🔥
Reproduction Version
next 717

### Relevant Info
No response

### Regression?
No response

### Impact
Each Segmented Control Item should have a unique value in production code, so this shouldn't have a large impact.

### Esri team
Calcite (design)

**Comment by geospatialem** [comment]
Verified with `1.4.0-next.21`.
