### ISSUE TITLE
Expanded Tree Item doesn't render properly under TSX 

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#6284]
### Actual Behavior

![image](https://user-images.githubusercontent.com/3506166/212389816-b3d6061b-7bb3-4cfe-b6fb-7896b7a81465.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/3506166/212389881-04884939-e95f-4dfa-b8e5-d137c98483e2.png)

### Reproduction Sample

Use Arcade Editor on qawebgis

### Reproduction Steps

1. https://qawebgis.esri.com/arcade-editor/main/
2. Click Run in upper left corner
3. Result tab should open
4. A tree is supposed to be expanded and rendered 
5. Inspect tree in debugger and notice that everything is in place
6. search for children-container in the calcite-tree-item shadow dom
7. change the style by adding `transform: none`

### Reproduction Version

next.723

### Regression?

Was working before

### Impact

Confuses users when using Arcade Editor.

### Esri team

ArcGIS Map Viewer

**Comment by CodeBarker** [comment]
This ones a critical issue for the Arcade Editor team and it will impact multiple apps such as Field Maps and potentially Dashboard

**Comment by benelan** [comment]
Removing the `incomplete issue report` label since I was able to reproduce. It appears to only occur in the output dist builds and not the CDN, e.g. [this repros](https://codesandbox.io/s/cc-expanded-not-rendering-7o2fk8), but [this doesn't](https://codepen.io/benesri/pen/MWBOMzY). I'm working on a fix now, but here is a temporary workaround in case this is impacting anyone's CI/testing:

```css
:root {
  --calcite-duration-factor: 0;
}
```

**Comment by geospatialem** [comment]
Verified in `next.736` with Ben's [Code sandbox](https://codesandbox.io/s/cc-expanded-not-rendering-7o2fk8).

**Comment by geospatialem** [comment]
@omarkawach Good catch - can also repo on my end. We do plan to have a patch for 1.0.3 in the next week or so. @jcfranco this could be a good candidate to tackle, WDYT?

**Comment by omarkawach** [comment]
Thanks @geospatialem 

I was also able to reproduce this on the Calcite Design System site

![image](https://user-images.githubusercontent.com/49499098/214966324-c2fd1a78-bbc1-4103-aaa9-cd8840f14058.png)

**Comment by geospatialem** [comment]
Opened a new issue to track the vertical line on `tree` introduced with the above fix.
