### ISSUE TITLE
Combobox - Add indicator icon for combobox-items with icons

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6287]
### Description

Add an `indicator`, similar to what is depicted in the `dropdown` component for `dropdown-item`s with icons.

Related issue: https://github.com/Esri/calcite-components/issues/4629

cc @SkyeSeitz @ashetland

### Acceptance Criteria

Similar to the behavior depicted in `dropdown`:

![image](https://user-images.githubusercontent.com/5023024/212437012-aa0238d2-e3d6-4144-9b15-791e04666f65.png)

### Which Component

Combobox / Combobox-item

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
cc: @ashetland @SkyeSeitz

**Comment by ashetland** [comment]
Figma file with final specs for this enhancement is available. When nesting combobox-items, it is recommended that icons should be present or not present for all items within a group to maintain parent/child relationships. 
<img width="676" alt="CleanShot 2023-01-18 at 08 49 27@2x" src="https://user-images.githubusercontent.com/108549080/213244854-7dd2c65b-fa77-4110-9bac-cd0f7f83b689.png">

**Comment by geospatialem** [comment]
Verified on `next.731`

![image](https://user-images.githubusercontent.com/5023024/214224958-155ad4b8-0fea-46ed-a270-88dc67cea321.png)

![image](https://user-images.githubusercontent.com/5023024/214225225-4f991eff-b7de-4b7a-9942-a66e598eb54c.png)
