### ISSUE TITLE
[calcite-progress] Alignment and size of text

### ISSUE THREAD

**Issue by jgibson02** [Esri/calcite-components#629]
When using the `text` attribute, the label is left-aligned under the track, and also does not have its own specified size.
https://codesandbox.io/s/calcite-components-progress-text-issues-5hunr?file=/index.html

Suggestions:
* Text should be center aligned under the track
* Text should have the basis font size specified (i.e. `@include font-size(0)`), or perhaps something smaller

**Comment by macandcheese** [comment]
Agree, centered text would better match that of 'calcite-loader' - could use same sizing and positioning as that.
