### ISSUE TITLE
Checkbox is not a in Rtl

### ISSUE THREAD

**Issue by yannikmesserli** [Esri/calcite-components#6291]
### Actual Behavior

Checkbox is not a in Rtl

### Expected Behavior

Checkbox to be flipped

### Reproduction Sample

https://codepen.io/yannikm/pen/OJwjoPP?editors=100

### Reproduction Steps

1. Open the example
2. Check the checkbox

### Reproduction Version

beta.97

### Relevant Info

None

### Esri team

ArcGIS Urban

**Comment by geospatialem** [comment]
cc'ing @annierm18 for her expertise regarding the recommended pattern (flipped/unflipped) with i18n and RTL to display a checkbox.

**Comment by ESRIi18n** [comment]
@geospatialem checkmarks should not be flipped, as they don't communicate any direction

**Comment by annierm18** [comment]
@geospatialem checkmarks should not be flipped, as they don't communicate any direction

**Comment by geospatialem** [comment]
@yannikmesserli To align with internationalization and the expected pattern we do not plan to flip the checkbox at this time.

**Comment by geospatialem** [comment]
Closing this issue per the discussions above, but if additional follow-up is needed don't hesitate to reach out @yannikmesserli.

**Comment by yannikmesserli** [comment]
I've verified on my end, you are right. Sorry for the noise.
