### ISSUE TITLE
[Bug] tab-nav: `selectedTitle` property has incorrect value when `calciteTabChange` event is emitted

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#6299]
### Actual Behavior
When the calciteTabChange event is emitted, the selectedTitle property does not correctly reflect the currently selected calcite-tab-title.
![212974955-6dae9978-7f74-42ef-a850-b927965f9707](https://user-images.githubusercontent.com/3362490/218838659-62ece0f2-602e-4a2f-801e-e5fae1fb7c61.png)

### Expected Behavior
When the calciteTabChange event is emitted, the selectedTitle property should reflect the currently selected calcite-tab-title.

### Reproduction Sample
https://codepen.io/jmanke/pen/NWBayKv?editors=1011

### Reproduction Steps
1. Open the console.
2. Click on a `calicte-tab-title`
3. Observe the previous `calcite-tab-title` will be the value of `selectedTitle`. See JS code for more details.
### Reproduction Version
next.726

### Relevant Info
Chrome 108

### Regression?
No response

### Impact
Low
Workaround is to use the calciteTabsActivate event on the calcite-tab-title.

### Esri team
ArcGIS Dashboard

**Comment by geospatialem** [comment]
This also came up with members of the JS team, and adding a higher priority with a few pings on this issue for issue triaging.

Workaround: https://codepen.io/geospatialem/pen/gOdBzXx

**Comment by geospatialem** [comment]
Related:https://github.com/Esri/calcite-components/issues/6362

**Comment by geospatialem** [comment]
Reallocated to the upcoming May milestone.

**Comment by geospatialem** [comment]
Verified on `master`.

![verify-tab-selection](https://github.com/Esri/calcite-components/assets/5023024/87291810-277b-43aa-bcca-62e0a9b40a4f)
