### ISSUE TITLE
Floating UI issues with Tree and Dropdown

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6300]
### Actual Behavior
The first tree-item has the expected floating UI behavior, but subsequent tree-items placement looks off that surfaced while verifying #5168 cc @anveshmekala

![1__212780237-ea5ab162-0128-45cd-bf3b-34c433228b7f](https://user-images.githubusercontent.com/3362490/219099506-370650ec-d5e7-40f7-9cd1-5d601290edf9.gif)

### Expected Behavior
The Dropdown item should be present in line with its parent Dropdown, similar to the first item.

### Reproduction Sample
https://codepen.io/geospatialem/pen/QWBqWeN

### Reproduction Steps
Open the [Codepen sample](https://codepen.io/geospatialem/pen/QWBqWeN)
Select the first dropdown and observe the dropdown-item's placement (as-expected)
Select either the second or third dropdown and observe the behavior of the dropdown-item's placement
![2__213015711-9d144bcd-b15f-4227-83dc-7e7a6a642c3f](https://user-images.githubusercontent.com/3362490/219099546-d1387162-087a-4b03-98e0-01ce58f5cf9f.png)

### Reproduction Version
next.726

### Relevant Info
Applicable to Chrome and Edge browsers in the latest version (Version 109.0.5414.74 (Official Build) (64-bit)).

Firefox is not affected.

### Regression?
beta.94

### Impact
High

### Esri team
Calcite (dev)

**Comment by ethanbdev** [comment]
Oh nice - I noticed this issue and was just about to open one.

If its helpful, I found this issue did _not_ reproduce on chrome v108 🤷 

Here was my codepen anyway: https://codepen.io/eborgen/pen/vYaWgoz?editors=1010

I could message some screenshots of it being bad in the map viewer, but its the same with a dropdown inside an open block

**Comment by jcfranco** [comment]
@ethanbdev Interesting. Thanks for sharing the browser version info. I'm wondering if we should hold off on this to see if it gets fixed in a future Chrome version.

**Comment by geospatialem** [comment]
Moving to the February 2023 milestone per Franco's note above regarding checking for a potential fix in a future Chrome/Edge browser update.

**Comment by atomiks** [comment]
It's not Chrome's bug per se, they're now [adhering to the spec](https://github.com/shoelace-style/shoelace/issues/1135#issuecomment-1387325386). 

From what I remember, @jcfranco patched Safari and Firefox, but not Chrome (or just 109+ now needs to be checked and patched)

**Comment by jcfranco** [comment]
@atomiks Thanks for chiming in! I'll apply the patch to Chrome 109+ as suggested.

On a related note, would you recommend using the [polyfill shared in floating-ui/floating-ui#2160](https://github.com/floating-ui/floating-ui/pull/2160#issuecomment-1433140604)? We'll make sure to test the special cases that have come up, but wanted to get your thoughts on any potential polyfill testing so far.

**Comment by geospatialem** [comment]
Verified in `1.0.8-next.3`


![verify-tree-dropdown-floatingui](https://user-images.githubusercontent.com/5023024/222013593-833aef8a-5207-4e8e-a0e3-c057a5d3ee66.gif)
