### ISSUE TITLE
Inconsistent loading state for calcite-button in React wrapper

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#6304]
### Actual Behavior
The loading property on the CalciteButton React wrapper is not consistent with the [expected behavior for booleans](https://developers.arcgis.com/calcite-design-system/frameworks/#boolean-attributes). When setting loading={false} (which results in loading being true), the button is displaying as disabled, but does not have a loading spinner.

### Expected Behavior
Based on the above linked documentation, when you set loading={false}, it should become true, resulting in the button being disabled AND the loading spinner should appear.

### Reproduction Sample
https://codesandbox.io/s/quirky-vaughan-597ui7?file=/src/App.js

### Reproduction Steps

1. Open codesandbox
2. View first two test cases listed, which are showing as disabled, but no loading spinners.

### Reproduction Version
beta.99

### Relevant Info
No response

### Regression?
No response

### Impact
Fairly minor issue since users shouldn't use loading={false} anyway, but does signal a potential inconsistent handling of properties.

### Esri team
ArcGIS Developer Experience

**Comment by jcfranco** [comment]
I think we need to update the gotchas doc. Stencil components deviate a bit from [HTML boolean props](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) and [do support setting `"false"` on boolean attributes](https://stenciljs.com/docs/properties#boolean-props) (see https://github.com/Esri/calcite-components/pull/1411 for more info). cc @geospatialem @benelan

**Comment by geospatialem** [comment]
Verified doc updated on the test site for release on Wednesday.

![image](https://user-images.githubusercontent.com/5023024/228106706-004998f5-5efd-43d4-b503-fa0b491fb83a.png)
