### ISSUE TITLE
Remove Ratings  and  behavior

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6315]
### Summary
Rating's accessibility functionality should not include the  or  keys.

### Actual Behavior
The  shifts focus to the next rating star, and the  shifts focus to the previous rating star, which is confusing. Since we already use the  and  keys for focusing between stars, we can omit the  and . Functionality was spotted while verifying #5312.

### Expected Behavior
No keyboard change when interacting with Rating when using the Down arrow or Up arrow keys.

### Reproduction Sample
https://codepen.io/geospatialem/pen/GRBOZJo

### Reproduction Steps

1. Open the [sample](https://codepen.io/geospatialem/pen/GRBOZJo)
2. Focus on the Rating component
3. Select the Down arrow key and observe the next star is focused
4. Select the Up arrow key and observe the previous star is focused

### Reproduction Version
next.727

### Working W3C Example/Tutorial
No response

### Relevant Info
No response

### Regression?
No response

### Esri team
Calcite (dev)

**Comment by anveshmekala** [comment]
@geospatialem  the [codepen](https://codepen.io/geospatialem/pen/GRBOZJo)  is working as expected. As mentioned in the spec [here](https://www.w3.org/WAI/ARIA/apg/patterns/radio/examples/radio-rating/#:~:text=the%20default%20value.-,Keyboard%20Support,-Key), Down arrow should shift the focus to the right and Up arrow will shift the focus to left.

**Comment by geospatialem** [comment]
@anveshmekala and I had a great discussion, so wanted to highlight some of the findings below for future reference prior to closing this issue out.

Ultimately there are a few different patterns out in the wild showcasing:
1. up/right arrows [next] and down/left arrows [previous], and
2. down/right arrows [next] and up/left arrows [previous] - **current pattern**

Based on some internal feedback with other teams regarding a11y, we're following one of the expected patterns. We could alter the pattern to the above request, but since we're already following one of the patterns with `type="radio"` will be closing out this issue unless we hear different from users.
