### ISSUE TITLE
Stepper Item - Add a selected / change event

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6330]
### Description
Expose a public selected / change event for Stepper Item.

### Acceptance Criteria
Stepper item adds a selected / change event

### Relevant Info
Related to issues #5023, and stems from #6135

### Which Component
Stepper Item

### Example Use Case
No response

### Esri team
Calcite (dev)

**Comment by jcfranco** [comment]
@geospatialem I synced up w/ @anveshmekala on this and I don't think it's valid anymore. We already have an event on the stepper when items are selected and a `selectedItem` property to retrieve the current item.

**Comment by geospatialem** [comment]
> don't think it's valid anymore. We already have an event on the stepper when items are selected and a `selectedItem` property to retrieve the current item.

Sounds good. Per https://github.com/Esri/calcite-components/issues/6135#issuecomment-1398494748, we should be in alignment. Closing this issue out.
