### ISSUE TITLE
stepper : numbering-system displaying inconsistent results with two stepper components in a page

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#6331]
### Actual Behavior

if two numbered stepper components are rendered in a page with different numbering-system, when user alternate the clicks between stepper components the numbers are showing inconsistent results.

### Expected Behavior

stepper components should follow numbering-system defined on them or should fall back to `latn` numbers.

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/YzjaveB?editors=100

### Reproduction Steps

1. Click on the stepper item with arabic numbers
2. Then, click on the stepper item above with latin numbers
3.  Observe that latin numbers changes to arabic.

### Reproduction Version

next.729

### Regression?

beta.97

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `1.0.4-next.5`
