### ISSUE TITLE
split-button: transparent with kind='inverse' display divider 

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#6332]
### Actual Behavior

split-button with transparent appearance and kind=`inverse` is displaying divider container

### Expected Behavior

Shouldn't display divider container 

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/XWBEYYV?editors=100

### Reproduction Steps

1. Hover the split-button
2. Observe  a small vertical dotted line in black.

### Reproduction Version

next.729

### Regression?

beta.99

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified on `1.0.4-next.2` in `.calcite-mode-dark`.

<img width="195" alt="Screenshot 2023-01-28 at 9 24 04 PM" src="https://user-images.githubusercontent.com/5023024/215302974-5b0f5152-0f5f-4bf9-a960-716d8bf91405.png">
