### ISSUE TITLE
[Notice] spacing to right of slotted end action may seem too narrow

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#6347]
### Actual Behavior

When you have a small, non-closable notice with a small slotted end-action, the right side looks a bit crowded. This also depends on the icon.

This is totally subjective and I understand if it is by design. cc @ashetland @SkyeSeitz @macandcheese 

### Expected Behavior

For the above configuration, the right side could have slightly more padding.

### Reproduction Sample

https://codepen.io/jcfranco/pen/QWBrGdw

### Reproduction Steps

1. Open the repro case and look at the space between the icon and the right edge of the notice

### Reproduction Version

1.0.3

### Esri team

Calcite (dev)

**Comment by ashetland** [comment]
I agree that it fells a bit tight, but this should also be true for any case where a small, icon-only Action is slotted into actions-end (Alert comes to mind, although Alert always has a close button following the action slot). I think the user could use a medium Action on a small Notice to achieve more space if desired.

**Comment by jcfranco** [comment]
Gotcha. In that case, any objections to closing? Doesn't seem like it's actionable from our perspective.

**Comment by ashetland** [comment]
Nope, I think we can close this one.
