### ISSUE TITLE
[Alert] Incorrect border radius when icon is present

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6348]
### Actual Behavior

When an icon is present (default `icon` or supplied as an override - `icon="layers"`) - there is no bottom-left border-radius:
<img width="687" alt="Screen Shot 2023-01-25 at 1 07 09 PM" src="https://user-images.githubusercontent.com/4733155/214691303-a8243e17-796b-4a52-ac54-0dc1d6fa09c9.png">
<img width="687" alt="Screen Shot 2023-01-25 at 1 06 08 PM" src="https://user-images.githubusercontent.com/4733155/214691311-32a2ba03-1d8d-404c-94b0-755e254e1f8c.png">

### Expected Behavior

The alerts with icon have correct border radius.

with icon: https://codepen.io/mac_and_cheese/pen/BaPxpqR?editors=1000
without icon: https://codepen.io/mac_and_cheese/pen/yLqjgjj

### Reproduction Sample

Above

### Reproduction Steps

1. Visit codepen links
2. View difference in styling

### Reproduction Version

1.0.3

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
cc @ashetland @SkyeSeitz - Would this fix require a Figma UI kit change? We're hoping for this to land in the upcoming patch.

**Comment by ashetland** [comment]
Nope, the Figma component has a 4px radius on all corners in all variants. 🚀

**Comment by geospatialem** [comment]
Verified on `1.0.4-next.2`

<img width="1227" alt="Screenshot 2023-01-28 at 8 57 46 PM" src="https://user-images.githubusercontent.com/5023024/215302084-9b6f2eeb-dc82-4173-a9e7-165879f5ff95.png">
