### ISSUE TITLE
[Modal]: "disableCloseButton" modal prop is outdated

### ISSUE THREAD

**Issue by jasdelreyes** [Esri/calcite-components#6349]
### Description

[Calcite modal documentation](https://developers.arcgis.com/calcite-design-system/components/modal/) shows that the `disableCloseButton` prop is still in use. But in development, it seems that the correct updated prop is named `closeButtonDisabled`.

### Which Component

Modal

**Comment by macandcheese** [comment]
Hi @jasdelreyes - apologies for the delay - our documentation was just updated in the last hour, it should reflect the new `closeButtonDisabled` name now: https://developers.arcgis.com/calcite-design-system/components/modal/#api-reference-properties-closeButtonDisabled

**Comment by geospatialem** [comment]
@jasdelreyes Thanks for reaching out! 

Apologies for the confusion - our documentation site was just released for `1.0.3` this afternoon, where the updated props, including [`closeButtonDisabled`](https://developers.arcgis.com/calcite-design-system/components/modal/#api-reference-properties-closeButtonDisabled), are now listed.
