### ISSUE TITLE
calcite-tree aria attribute issues

### ISSUE THREAD

**Issue by cosbyr** [Esri/calcite-components#635]
- aria-multiselectable attribute needs to be set to "true" or "false":
![image](https://user-images.githubusercontent.com/11748268/83302039-7c996d80-a1af-11ea-8a44-57434d497587.png)
-aria-role="tree" should just be role="tree"
![image](https://user-images.githubusercontent.com/11748268/83302196-be2a1880-a1af-11ea-95a9-0dc7f7fb2afb.png)

**Comment by shoe913** [comment]
Re-opening since this still appears to be an issue.

**Comment by MikeTschudi** [comment]
still present @1.0.0-beta.57 with Accessibility Insights for Web (Chrome extension)

**Comment by MikeTschudi** [comment]
verified @1.0.0-beta.62 with Accessibility Insights for Web (Chrome extension) FastPass
