### ISSUE TITLE
Unable to select label text in radio group

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#6357]
### Actual Behavior
Hovering the text label of a <calcite-radio-button> inside a <calcite-radio-button-group> shows a text style cursor. Holding down the mouse button and dragging the label text does not select the text and does check the assoc. radio control when the mouse button is released.

### Expected Behavior
Hovering the text label of a <calcite-radio-button> inside a <calcite-radio-button-group> shows an arrow cursor. Dragging the cursor across the text label does select the text and does not select the assoc. radio control.

### Reproduction Sample
https://developers.arcgis.com/calcite-design-system/components/radio-button-group/

### Reproduction Steps
Visit the radio-button-group doc page and try to perform selections on the radio button labels.
### Reproduction Version
1.0.3

### Relevant Info
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio for an example of the expected behavior.

### Regression?
No response

### Impact
Impact is to users who expect radio button labels to behave in the same way native radio button labels behave. A common use case might be to want to copy label text for some other use.

### Esri team
ArcGIS Field Apps

**Comment by geospatialem** [comment]
Research will be conducted to determine feasibility/next steps in June.

**Comment by anveshmekala** [comment]
Need to determine the focus behavior when the text is selected to solve this issue since focus and selection behavior is different in chrome/edge compared to safari/FF.
