### ISSUE TITLE
Popover : remove or change max-width?

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#636]
Right now Popover has a max-width set.
https://github.com/Esri/calcite-components/blob/master/src/components/calcite-popover/calcite-popover.scss#L11

Would we be able to either remove this limitation or add a property to give users a bit of control here? Open to suggestions.

I know we can use Popper directly, but it would be nice to get the styling etc. that comes with Popover.

@macandcheese

**Comment by macandcheese** [comment]
Sounds good to me... I assume Popper will handle instances of page overflow sure to width?

We could also provide some set widths for consistency sake like we do for dropdown, predefined s/m/l and then an auto/full to allow any width.

**Comment by asangma** [comment]
Sounds good! I can make a PR but could use some suggestions on 

* Do we wanna use pixels or vw or %
* Values for the units per scale
* Should scale include values for height?

**Comment by macandcheese** [comment]
Hm, I guess... do we need to set anything at all? Wouldn't popper just fit to size for both height and width? Aside from constraining for page overflow horizontally and vertically maybe we just need to remove the `max-width`.

**Comment by asangma** [comment]
Sounds good. I won't add a scale prop and will just nix the max-width.

**Comment by macandcheese** [comment]
Sounds good @asangma - just verify that Popper will prevent page overflows so we don't need a `max-width:100%` or anything like that. Thank you!

**Comment by asangma** [comment]
I know. It's weird, but would you mind verifying @macandcheese ?

**Comment by macandcheese** [comment]
LGTM! We can probably address https://popper.js.org/docs/v2/faq/#my-popper-is-bigger-than-the-viewport-what-do-i-do when we look at adding fixed widths that match those of dropdown (when that gets updated to Popper...) mentioned here: https://github.com/Esri/calcite-components/issues/656

**Comment by macandcheese** [comment]
Addressed in https://github.com/Esri/calcite-components/pull/655
