### ISSUE TITLE
fix(tree-item): consistent height with or w/t `action-end`

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#6361]
### Actual Behavior
Expected consistent height with our without action-end as per spec:

Small: 24
Medium: 32
Large: 44

Padding on the action-end slot currently affects the height of the host. For the slot in tree-item to not affect the tree layout, we need to take it outside of the layout, sitting it next to node-container. Similar to notice. This way the padding on the node-container will not affect it. Assuming the user sets a proper action scale it should match the height.

### Expected Behavior
Follows the design spec.

### Reproduction Sample
https://codepen.io/elijbet/pen/YzjvKdR?editors=1010

### Reproduction Steps
Use inspect to explore how bringing in action-end bumps up the height of the tree-item.

### Reproduction Version
1.0.3

### Relevant Info
No response

### Regression?
No response

### Impact
No response

### Esri team
Calcite (dev)

**Comment by geospatialem** [comment]
Migrating to the upcoming February milestone for the fix to land later this month.

**Comment by geospatialem** [comment]
Verified in `1.0.6`. There was a tradeoff with the focus pertaining to `action-end`, and a new issue #6481 was created to track progress.
