### ISSUE TITLE
calcite-list calciteListItemSelect event - selection timing issue

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/calcite-components#6362]
### Actual Behavior
The calcite-list selectedItems property doesn't provide the correctly selected items when the calciteListItemSelect event fires.

### Expected Behavior
I expect the calcite-list selectedItems property to provide the correctly selected items when the calciteListItemSelect event fires.

### Reproduction Sample
https://codepen.io/john-grayson/pen/bGjKGMg

### Reproduction Steps
open the CodePen console
select and unselect various items in the list
Workaround provided by @jcfranco
https://codepen.io/jcfranco/pen/jOpKORY

### Reproduction Version
1.0.3

### Relevant Info
No response

### Regression?
No response

### Impact
No response

### Esri team
N/A

**Comment by apfister** [comment]
+1 for this. thank you!

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.6`

![verify-listitemselect](https://user-images.githubusercontent.com/5023024/235976611-7e5ae380-3df3-47b8-a044-0112050bc2d2.gif)
