### ISSUE TITLE
[pagination]: Uses deprecated props

### ISSUE THREAD

**Issue by jasdelreyes** [Esri/calcite-components#6365]
### Actual Behavior

Calcite pagination is incorrectly showing the numbers provided in the props.

Below you can see screenshots of the pagination component showing "0" instead of, for example, "1 2 3". The header on top is showing the inputs I've added to the `calcite-pagination` props.

_First render_
<img width="718" alt="pagination1" src="https://user-images.githubusercontent.com/107893471/215166664-a6e1047c-5eab-45e3-a8c0-ce766f5c396c.png">
_When "0" is clicked_
<img width="719" alt="pagination2" src="https://user-images.githubusercontent.com/107893471/215166663-790dfc5e-e330-406f-9af4-ce0cbb3040cb.png">

### Expected Behavior

I expect the pagination component to show the correct sections of pages -- which are also clickable to then change the local variables to show different pages in the UI.

### Reproduction Sample

https://codepen.io/jasdelreyes/pen/abjKqPL?editors=100

### Reproduction Steps

1. Use `calcite-pagination` as outlined in https://developers.arcgis.com/calcite-design-system/components/pagination/ with the camelCase props. 
2. Open devTools
3. See that the props include deprecated props.

_Source code_
<img width="281" alt="pagination-source" src="https://user-images.githubusercontent.com/107893471/215167569-b4351cd2-7ff7-495e-b8f2-62c1204be99d.png">

### Reproduction Version

1.0.3

### Relevant Info

Firefox 109.0, Chrome 109.0.5414.119

### Regression?

Yes

### Impact

This is used in the new append experience aimed for R01. This is the prohibiting the ideal behavior of a workflow.

### Esri team

ArcGIS Online

**Comment by jasdelreyes** [comment]
@brittneytewks This is resolved!

**Comment by geospatialem** [comment]
Great news, and thanks for the quick reply, @jasdelreyes! We'll close out the issue.
