### ISSUE TITLE
Alert queue pattern is confusing to users

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6366]
### Description

When using the `alert` component and multiple are open on a page, users start trying to click on the numbers in the component's queue. While it is useful to have messages, ArcGIS Online has received feedback that when alerts are stacked users don't know what to do next. 

For instance:

> I just didn't know what the "+2" tag at the bottom of the `alert` meant. It doesn't seem to be clickable.

![component with multiple message tag](https://user-images.githubusercontent.com/5023024/215194752-667cbd1c-818d-453e-acbc-ddcceed711d7.png)

![user feedback on alert](https://user-images.githubusercontent.com/5023024/215194744-699f65b7-7640-4158-9df8-83a8a61ab15a.png)

![user feedback on alert 2)](https://user-images.githubusercontent.com/5023024/215194977-7249f4fd-f78f-40c5-a5bd-1b3deea7f314.png)

cc @alisonailea

### Acceptance Criteria

Potential solutions include:
- Auto closing
- Display all alerts to give details on messages
- Add a "see more" message and make it clickable (similar to Teams functionality)

<img width="see more example" src="https://user-images.githubusercontent.com/5023024/215193953-e2fa49cd-7ed1-4153-8dfc-f5e6b7f0c751.png">

- When the component appears provide a short description and if set by a dev links to another page to provide more context/info
- Allow multiple groupings where the stacked messages can be drilled into without numbers

### Relevant Info

We've received questions and requests from a number of users across ArcGIS Online products.

### Which Component

`calcite-alert`

### Example Use Case

ArcGIS Online uses `alert` for analysis-related job status messages.

To reproduce:
run create buffers -> create buffer submitted , create buffers executing , create buffers succeeded shown in these calcite alerts run another job - > hotspots, where `alert`s are added to same grouping

### Esri team

ArcGIS Online

**Comment by macandcheese** [comment]
https://github.com/Esri/calcite-components/issues/2835 

This is an issue tracking solutions for this -  has not been prioritized in a bit but I can pick it back up as we had a bit of progress awhile back. Personally I wouldn’t consider it a bug but seems like something we should continue improving. 

Improvements can include “adjacent” UI elements to show more open alerts, the ability to have the chip also expand to show more, and a better visual indication of alert queue by adding a “stack” display when multiple are queued.

**Comment by geospatialem** [comment]
Ah, thanks for the context @macandcheese. Will close out this issue in favor of 2835.

@alisonailea: Can you refer Ganesh to 2835?
