### ISSUE TITLE
[List] Improve border styling

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6373]
### Actual Behavior

There are some cases where the transparent border on the List cause the List to: 
- not extend fully to the width of a container, creating a gap where background can be visible
- when `filter-enabled` - scrolling items will show behind the sticky input bar for 1px

![Group 8](https://user-images.githubusercontent.com/4733155/215292969-06d55fd1-59e2-426f-91d6-ce21873a67a0.jpg)

### Expected Behavior

The list extends to the full width of the parent container with no transparent borders. The list, when `filter-enabled`, does not allow the scrolled items to peek through behind the sticky input bar.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/oNMMjqJ?editors=1000

### Reproduction Steps

1. Open Codepen

### Reproduction Version

1.0.3

### Esri team

Calcite (design)

**Comment by mjuniper** [comment]
Here's another reproduction of the issue where it does not extend to the width of its container: https://codepen.io/mjuniper/pen/VwGOzBB?editors=1100

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.4`.
