### ISSUE TITLE
[calcite-input-date-picker]: should display placeholder text when the value is reset to null

### ISSUE THREAD

**Issue by vannizhang** [Esri/calcite-components#6378]
### Actual Behavior
I have two simple simple components, a `calcite-input-date-picker` and a `calcite-button`:
![cal1](https://user-images.githubusercontent.com/3362490/218831044-a97d2fcd-060f-41eb-811f-c31ce3cad851.png)

I can use the date picker to select a date without any issue:
![cal2](https://user-images.githubusercontent.com/3362490/218831078-0652cb5c-1c12-4118-9719-47f1d638d0d6.png)

The selected date should be reset when I click on the reset button, and I can see selected date become unselected in the calendar component after clicking the button:
![cal3](https://user-images.githubusercontent.com/3362490/218831104-7053b779-ce58-4be9-a7af-dc2e96bd493f.png)

But the input still shows previously selected date even after we reset the selected date:
![cal4](https://user-images.githubusercontent.com/3362490/218831617-c8e6f433-a2b0-47a9-a16a-7490f9356301.png)

### Expected Behavior
the input should show placeholder text (e.g. YYYY/MM/DD) once the selected date is reset to undefined, so that the user knows that they have successfully reset the selected date.

### Reproduction Sample
https://codepen.io/vannizhang/pen/ZEjMLaL?editors=1010

### Reproduction Steps
open the codepen sample,
select a date using the date-picker component and you should see the selected date in input-date-picker
click on reset selected date button
you still see the previously selected date in the input-date-picker, which is incorrect, should see the placeholder text
#### Reproduction Version
1.0.3

### Relevant Info
No response

### Regression?
No response

### Impact
The Living Atlas Curation App (a internal tool to curate all Living Atlas contents) uses the calcite-input-date-picker in a Modal to let the curator to select a auto removal date for any Living Atlas content, we also gives them a button to reset the previously selected auto removal date, when that button is clicked, we want them to see that change in the calcite-input-date-picker:

![cal5](https://user-images.githubusercontent.com/3362490/218831215-5498e826-46b8-4964-871e-5a0b5b616fd2.png)

### Esri team
Calcite (dev)

**Comment by geospatialem** [comment]
Also surfaced in a [Community post](https://community.esri.com/t5/calcite-design-system-questions/reset-input-date-picker-component/m-p/1297746#M423) on June 9.
