### ISSUE TITLE
Combobox Item Groups no longer change indentation levels when nested

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-components#6384]
### Actual Behavior
When nesting Combobox Item Groups, there is no visual indication of nesting.

### Expected Behavior
Nested groups should increase in indentation levels, matching the behavior of Combobox Items.

### Reproduction Sample
https://codepen.io/ashetland/pen/JjBaOga?editors=100

### Reproduction Steps
Open the codepen.
Note that groups are nested in code, but there is no visual representation of the nesting.
See this [beta.97 codepen](https://codepen.io/ashetland/pen/dyjqZLw?editors=1000) for comparison.

### Reproduction Version
1.0.3

### Relevant Info
No response

### Regression?
beta.97

### Impact
No response

### Esri team
Calcite (design)

**Comment by ashetland** [comment]
This change may be an unintended byproduct of a recent update to Combobox Item Groups. It was discovered that groups were unnecessarily increasing the initial indentation level of their children. This was fixed, but the now nesting groups shows no visual change.

**Comment by Anastasiia-Boleiko** [comment]
@ashetland Thank you for filing the issue, will be very helpful for ArcGIS Urban.

**Comment by ashetland** [comment]
cc @geospatialem for triage

**Comment by geospatialem** [comment]
Reallocated to the upcoming April milestone.

**Comment by geospatialem** [comment]
Verified in `1.3.0-next.3`

![image](https://user-images.githubusercontent.com/5023024/231849749-44c1e457-8f57-42c6-b006-4a86d978c9cf.png)
