### ISSUE TITLE
Extra space in front of the `input` in `input-number` and `input-text`

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#6386]
### Actual Behavior

The extra space in front of the input in input-number and input-text is coming from specifying `icon`, but not having a recommended icon for these 2 types. The solution is to not support the boolean type on the icon on them. 

### Expected Behavior

Get rid of the space. 

### Reproduction Sample

https://codepen.io/elijbet/pen/WNKggyE

### Reproduction Steps

See demo.

### Reproduction Version

1.0.3

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified on `master`.

cc: @macandcheese - The change includes the JSDoc tag of `@futureBreaking`, we might need to consider some styling options for the doc site for these use cases.
