### ISSUE TITLE
[Shell Panel] Add Overlay display mode

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6388]
### Description

As proposed, add an "overlay" mode to Shell Panel that allows it to position over any content adjacent to it in the shell.

- Does not extend over header / footer slots (use case for upcoming proposed Sheet)
- Does not have a blocking scrim (use case for upcoming proposed Sheet)
- Action bar remains visible when the child panel is open or closed (same as existing functionality)
- Mutually exclusive from "detached"
- Animation of width, box shadow applied.
- Animation direction, box shadow direction determined by shell panel slotted location within shell.

### Acceptance Criteria

As proposed, this mode will allow users to use a Shell Panel to overlay other content in the main slotted content area of Shell.

### Relevant Info

More information in Confluence proposal

### Which Component

Shell Panel

### Example Use Case

At a smaller viewport size, it may be desirable to use Shell Panel as an "overlay". This will allow consuming apps to change the property and gracefully hide "shown on larger viewport" shell panels.

### Esri team

Calcite (design)

**Comment by driskull** [comment]
@macandcheese how is this different from the `contentBehind` property on the `shell`?

**Comment by macandcheese** [comment]
Much of this functionality does focus on the "without `contentBehind` set on parent shell" use case as that was not intended to be changed:

- default (current behavior): Slotted Shell Panel's action bar and panel push over content slotted in default Shell slot.
- overlay display (proposed additional behavior) Slotted Shell Panel's action bar pushes over content slotted in default Shell slot. Panel is overlaid absolutely on top with animation / transition. start/end slotted shell panel would display on top of top/bottom if multiple were open (but documented against)
- detached mode used with "Default behavior" in this case creates the "swimlanes" where the shell panel appears floating above a plain bg adjacent to the map. 


So, yep, in some ways these proposed changes do create an alternative to using `contentBehind` while leaving that functionality alone to keep those use cases when used with jsapi view padding. I can whip up a demo if needed to demonstrate better, I think the one on Confluence is outdated if still working.

**Comment by driskull** [comment]
> overlay display (proposed additional behavior) Slotted Shell Panel's action bar pushes over content slotted in default Shell slot. Panel is overlaid absolutely on top with animation / transition. start/end slotted shell panel would display on top of top/bottom if multiple were open (but documented against)

Are you proposing that the action bar is on the side of the center content but the panel is on top of it? These are inside a single component (shell-panel) so I'm not sure how we would achieve that.

**Comment by macandcheese** [comment]
Yes - but it could be changed to be a sibling value of "docked" and "overlay" - instead of a separate and mutually exclusive property. So, a Shell Panel could have a `displayMode` with possible values "docked(current default)/overlay/detached"

When slotted within a Shell with `contentBehind` set:
Currently, both `detached` and "default" behave like this:
- The action bar and panel are positioned absolutely on top of the center content.
- The new "overlay" mode here would function similarly.  There is a difference in that it has an animation, and box-shadow, but otherwise it behaves more similarly to "default / docked" than "overlay".

When slotted within a Shell without `contentBehind` set:
- Currently, "default" places both the slotted action bar and the slotted panel adjacent to center content.
- `detached` places the slotted action bar adjacent to content, but absolutely positions and styles the Shell Panel.
- Using "detached" currently places the Shell Panel in its own swimlane adjacent to the content, which isn't desirable. I'd expect it to position absolutely.
- The new "overlay" mode here is where we add support for many use cases - The ability to have the absolute positioning of `detached` with the full-height and not constrained to `detachedHeightScale` property.

The last bullet point is really value add for this feature, if there's a way to do it within our existing structure that would be great. Talking through now - does it seem like "detached" would be better not being mutually exclusive to the newly proposed mode and instead a sibling value?

**Comment by geospatialem** [comment]
Verified with https://codepen.io/geospatialem/pen/QWZJQdE in `1.4.0-next.21`
