### ISSUE TITLE
[Shell] Add "panel-top" slot, rename "center-row" to "panel-bottom"

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6389]
Description

Following up with more issues from proposals...

Acceptance Criteria

Rename "center-row" slot to "panel-bottom" to be more consistent with existing slot names.
Keep the existing "center-row" for a period of deprecation before removal.
Add a reciprocal "panel-top" slot.
Handle collision between these in the same way "panel-start/end" are.
Relevant Info

In future updates, Shell Panel will be the recommended component for use in these two slots (replacing Shell Center Row).

Which Component

Shell

Example Use Case

Slotted content is desired at the top of a shell component.

Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `1.3.0-next.4`.
