### ISSUE TITLE
New radio group styling

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#639]
![image](https://user-images.githubusercontent.com/14083530/83555351-005e9d00-a4c3-11ea-8cfe-8efcbb681415.png)

This is an effort to make radio groups look more distinct from buttons.

**Comment by ffaubry** [comment]
@bstifle So the border around will always be there?

**Comment by macandcheese** [comment]
@ffaubry Yes, we received a lot of feedback that radio group items looked very similar to a row of buttons (especially when it was a choice between 2 radio group items - it looked like a primary / secondary button lockup), so we adjusted the styling a bit to make the two components slightly more distinct:
![Slice](https://user-images.githubusercontent.com/4733155/88423300-6ddec980-cda0-11ea-980f-770efb8e30a7.png)
