### ISSUE TITLE
[Action Group] Infer Action Group `layout` from parent Action Bar or Action Pad

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6390]
### Description

Currently, the Action Group has a `layout` property, as does its containing Action Bar or Action Pad. This can lead to situations where the parent is in one mode, and Action Group in another, creating undesirable layout. 

### Acceptance Criteria

If possible, infer the `layout` of the Action Group from the parent and respond to changes made to the parent. This could be set by the parent. Remove the public property from Action Group as it shouldn't be used on its own (verify this ... maybe it needs to remain but still be set by parent in most cases).

### Which Component

Action Group (Action Pad / Action Bar)

### Esri team

Calcite (design)

**Comment by driskull** [comment]
> This could be set by the parent.

Yes, the parent should manage it and set it. We don't want to look back up the DOM.

**Comment by brittneytewks** [comment]
@driskull as we're working through the milestone, can you add a priority and estimate to this issue?

**Comment by geospatialem** [comment]
Dev work will be initiated once https://github.com/Esri/calcite-components/issues/6389 is complete, and should be coordinated with #6447.

**Comment by geospatialem** [comment]
Verified in `1.3.0-next.4`.

**Comment by geospatialem** [comment]
future breaking change for the `action-group`s `layout` prop
