### ISSUE TITLE
Calcite-Input-Time-Picker resets user typed values on blur

### ISSUE THREAD

**Issue by JonUihlein** [Esri/calcite-components#6398]
### Actual Behavior

`Calcite-Input-Time-Picker` resets any user-entered values when focus is lost.

If the form has a current value of `12:05:10 AM` for example, changing the value to `12:15:10` AM with the keyboard is rejected.

Values must be explicitly chosen via the UI and cannot be manually typed. The only noted exception is when a value is copy+pasted into the input directly. These values seem to be honored in cases when the value lacks any localization context (e.g. `10:15` is accepted but `10:15 AM` is not).

I assume this is because the newly typed value provided to the validator is rejected and the last previous value is set on the input instead.

Being unable to type values into the input and requiring user interaction via the picker/popover seems like an accessibility concern and/or potential bug.

### Expected Behavior

The input should not reset valid user entered values when focus is lost, especially in the case of modifying a single character in the time string via keyboard. Changing `01:01:02 AM` to `01:11:02 AM` should be honored/persisted in the input when focus is lost, and not reset back to`01:01:02 AM`

### Reproduction Sample

https://jsbin.com/yoguxihoze/edit?html,output

### Reproduction Steps

1. Notice value in the input is `10:20 AM`
2. Click on the input, and navigate to the middle of the string with keyboard arrow keys
3. Delete the '2' in `10:20 AM`
4. Type '4' so the value appears as `10:40 AM`
5. Click (or tab) away from the input so focus is lost
6. Notice the value in the input has reset back to `10:20 AM`

### Reproduction Version

1.0

### Relevant Info

Chrome, windows

### Regression?

No response

### Impact

Prevents common workflow of modifying time values by hand without requiring interaction with a picker/popover. Seems like a potential accessibility concern.

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by AdelheidF** [comment]
this might be the same issue as here: https://github.com/Esri/calcite-components/issues/5847

**Comment by geospatialem** [comment]
Reallocating to the April milestone to dive in to `date-fns`, which handles some locales, but not all. Will need further investigation to determine what is needed to contribute to the missing locales.

**Comment by geospatialem** [comment]
Adjusting to the May milestone. Research has been completed for localization tooling. Next steps include mitigating a few locales and tests.

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.21`

![verify issue 6398](https://github.com/Esri/calcite-components/assets/5023024/32a81b29-6d82-470e-8088-c998b52475f4)
