### ISSUE TITLE
Component: Color Picker

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#64]
Specs and designs to follow.

**Comment by macandcheese** [comment]
This should be built independently of an accordion as shown above, but we should doc and show examples of how to combine multiple in collapsible accordions since that will be a super common use case.

**Comment by jcfranco** [comment]
@julio8a I've been making progress on this one and had a few questions.

![401deda1-d695-4134-be32-1bee1d3c4db6](https://user-images.githubusercontent.com/197440/64444688-988d3a00-d089-11e9-829b-7e353b4a937e.jpg)

* (blue) I noticed there's no indicator for the current hue, can you update the mock to include this?
* (purple) is the eye dropper icon decorative or functional? If the latter, I don't think this is possible due to security concerns.

**Comment by julio8a** [comment]
I'll work on item 1. Item two, maybe we need more discussion on this. We can talk about it in our next meeting.

**Comment by julio8a** [comment]
Narrow color picker wrap inputs:

![image](https://user-images.githubusercontent.com/6144462/64448135-d55d2f00-d091-11e9-90fb-f15ff5741191.png)

^ for when the color picker needs to fit inside a panel

**Comment by julio8a** [comment]
Handle, changes color when dragged based on value

![image](https://user-images.githubusercontent.com/6144462/64449201-443b8780-d094-11e9-868d-cacf50949941.png)

**Comment by paulcpederson** [comment]
@jcfranco how's it going, any blockers? Working on a UI right now that needs a nifty little color picker, wondering if I can just hold out until you're done.

**Comment by jcfranco** [comment]
@julio8a @paulcpederson Sorry for not giving any updates. I'm wrapping up some stuff and I'll get back to this. Do you have a timeframe for your UI work or an issue you could link to? Just to keep it on my mind.

**Comment by paulcpederson** [comment]
It's 7.4 timeframe, so no rush, really

**Comment by paulcpederson** [comment]
So I just got some bugs on a different color picker we're using in high contrast mode and thought I'd mention it in this thread. Basically the issue is that the color swatches/color fields are implemented with `background-color`, which gets lost in high-contrast mode:

![Screen Shot 2019-10-28 at 3 41 27 PM](https://user-images.githubusercontent.com/1031758/67723579-b98f4e80-f999-11e9-89fe-3bb8e2c70cb9.png)

I think the safest way to do the swatches, etc is a `<svg>` with a `rect` that has a fill of the color. That way high-contrast will treat it as an image and leave it be.

Thought I'd mention it as sort of a note-to-self.

**Comment by jcfranco** [comment]
@paulcpederson Thanks for sharing. I'll make sure to take this into consideration.

**Comment by julio8a** [comment]
From a conversation with Fred:

It's important that we could pass the color to the component as a string with the following supported formats:
	
#RRGGBB
	#RRGGBBAA
	rgb(....)
	rgba(....)
	hsl(....)
	hsla(....)

And the value returned by the component should be the string type chosen by the user.

**Comment by snoakes** [comment]
Hello,
I don't know if this is the correct place to ask, but I'd love to know a rough date for this.
Thanks for all your hard work,
Sarah

**Comment by jcfranco** [comment]
@snoakes Thanks for showing interest in this component's progress! 😄 I'm guesstimating early January for this.

**Comment by kumarGayu** [comment]
@julio8a is this need to have a transperancy?

**Comment by julio8a** [comment]
Yes, from one of the requirements from the Operations Dashboard, we did need RGBA.

**Comment by kumarGayu** [comment]
@julio8a yes we were also thinking to have the opacity. However, I could not see that in the design. will there be any new design?

**Comment by julio8a** [comment]
I'll work with @jcfranco on it. There shouldn't be any drastic changes. I will post here if they are significant.

**Comment by jcfranco** [comment]
@julio8a I was under the impression that the component should be able to parse CSS colors with alpha, but not allow users to update it (based on the design).

**Comment by macandcheese** [comment]
I think another tab next to "hsb / rgb" with rgba and then a 4th "alpha" field could work.
If it needed to be more apparent - a mutually exclusive slider / input combination could provide that functionality for hsb / rgb.

**Comment by jcfranco** [comment]
I really like how https://github.com/Simonwep/pickr handles this. Among other things, it supports multiple modes and has an opacity slider (all configurable).

**Comment by macandcheese** [comment]
I like that with the feedback: it'd be nice if there were individual fields for each RGBA/HSVA value. I could see that their implementation is easier for pasting in, but seems weird to make a user worry about formatting commas, %, parens, etc.

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/73222090-41126800-4117-11ea-9915-1ecacca26c53.png)

here's a design layout for opacity on the large and small pickers

**Comment by macandcheese** [comment]
Feedback on above: 

I think the "opacity" slider should (IMO) always be visible, if requested by a user via configuration because it can be used in combination with HSB / RGB, so weird to have it on a "sibling" tab.

The "tab list" should (IMO) support any combinations of "HSB / RGB / RGBA / HSLA", and if the latter two are selected, display 4 input fields for each value.

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/73224050-1e834d80-411d-11ea-8045-ded24248ffb9.png)

**Comment by jcfranco** [comment]
@julio8a BTW, the eye dropper won't be possible to implement due to security restrictions.

**Comment by bstifle** [comment]
whoa really?! @jcfranco

**Comment by bstifle** [comment]
Also @jcfranco what is your avatar? asking for a friend.

**Comment by jcfranco** [comment]
> whoa really?!

I'm afraid so. We can only sample pixels from a canvas we draw to.

> what is your avatar? 

It's an illustration I saw on Twitter a looooong time ago. I set it as my avatar because it reminded me of one my puppers. I truly wish I had the source.

**Comment by bstifle** [comment]
sounds good. thanks man.

**Comment by mitc7862** [comment]
For Map Viewer beta, we need a simplified color picker for some workflows. I think it would be nice if the individual piece could be toggles on/off and rearranged. That way we can show it like a dropdown like so.

![image](https://user-images.githubusercontent.com/12564905/73389139-65da1d00-4288-11ea-956e-858348194e50.png)

we should also vet this design with Jennifer Bell from Esri's content team to see if it meets their needs. They use this stuff every day.

**Comment by bstifle** [comment]
- 

1. 

- [ ] 


> e

**Comment by bstifle** [comment]
here are the latest designs


![image](https://user-images.githubusercontent.com/14083530/73414178-db62df00-42c2-11ea-96e2-b73c9a01695f.png)

**Comment by bstifle** [comment]
@jcfranco 

are you building the component in a way that can handle rearrangements like this?:

![image](https://user-images.githubusercontent.com/14083530/73414260-1e24b700-42c3-11ea-9472-35ca353d0a95.png)

**Comment by jcfranco** [comment]
Just synced up w/ @julio8a: For the first iteration, the color picker will follow the designs that @bstifle [shared](https://github.com/Esri/calcite-components/issues/64#issuecomment-580052328) (sans opacity/alpha; that'll come later).

> are you building the component in a way that can handle rearrangements like this?:

This will probably be an update to the component after the first iteration.

@julio8a @mitc7862 @bstifle WRT saved colors: 

1. Should the amount of numbers be capped?
2. How would a user delete a color? Maybe CTRL+clicking (or similar) removes items?

**Comment by macandcheese** [comment]
For saved colors.. IMO seems like we need two modes:

One is "non editable" in that a user can't add or remove them (use case - "recommended colors bases on your theme", like Story maps, or, "recently used colors", etc that an app could provide)

The other would be "editable" with some affordance to enter an "edit" mode where items can be deleted (maybe rearranged down the line as a follow up feature).

Random thoughts... For the editable one, not sure how discoverable ONLY having a keyboard shortcut would be vs. Something more explicit like a "pencil" icon that when clicked places a user in an editing mode where they can be deleted or rearranged like iOS apps on home screen or something). That means there would need to be a way to "save" or edit that state which could be annoying vs. Always allowing editing and rearranging with  "long hover to display an x" or something.

**Comment by bstifle** [comment]
@jcfranco 

> 1. Should the amount of numbers be capped?
2. How would a user delete a color? Maybe CTRL+clicking (or similar) removes items?

1. yes 3
2. my thoughts would be dragging it out to delete, or no deletions. Since we have no "save" save button... i would rather just show the last x-number of colors used

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/74070459-f6fe7180-49b5-11ea-862a-ed3b112f3aaf.png)

@jcfranco @macandcheese @mitc7862 @julio8a @asangma 

design idea for + / - 

Also, idea for stacking instances of "provided" vs "user added" colors

**Comment by jcfranco** [comment]
Nice! 

In your proposed design for the +/-, does it require changing the color to delete it? If so, this may cause unintentional changes.

**Comment by macandcheese** [comment]
How are these swatch lists created? I was under the impression it'd be up to the app to pass an array of color values that render as swatches, with a title="" attribute, and an attribute for "is-editable". 

Assuming the "plus minus" example is the "is-editable" version, coupla q's

- Would "-" be disabled until a swatch is selected to remove?
- Is there a confirmation or "undo" affordance for removed items
- How does "+" work
- Is this idea that any "is-editable" swatch lists support drag and drop for re-ordering?

Use cases in my mind:

Recommended Colors - not editable, app passes an array at initial render

Saved Colors - editable, rearrangeable, app passes an array at initial render, on any update the component emits these changes for the app to... save to a user object ?

Recent Colors - not editable by a user, component updates order as colors are selected? or is this still up to the app to listen for those changes and then provide the updates back to the component?

**Comment by bstifle** [comment]
yeah + should only be there if there is an RGB or hex module associated.

if no association to add colors, then only have -  (if editable prop)

I agree - should appear disabled until a color in that menu is selected.

**Comment by jcfranco** [comment]
> I was under the impression it'd be up to the app to pass an array of color values that render as swatches, with a title="" attribute, and an attribute for "is-editable".

The component will support an array of color values. 

> Saved Colors - editable, rearrangeable, app passes an array at initial render, on any update the component emits these changes for the app to... save to a user object ?

I have saving colors working, but will wait for the final remove color design before adding it. Colors will not be rearrangeable (at least for the first release). When no `storage-id` is provided, users will have full control of these colors; otherwise, it's controlled by the component.

> Recent Colors - not editable by a user, component updates order as colors are selected? or is this still up to the app to listen for those changes and then provide the updates back to the component?

This would be a new requirement since it's not part of the first design. cc @julio8a 

> Note - we'll eventually be able to replace the inputs with calcite-inputs which include an affordance for "prefix" which will be a nice addition.

Awesome! 🎉

**Comment by macandcheese** [comment]
@jcfranco Cool - yes agree on "recent colors" - apps should be able to provide those updates if they want to. Maybe in the future component can handle it but, not for now for sure.

**Comment by bstifle** [comment]
![Example Dark wide](https://user-images.githubusercontent.com/14083530/74075985-46e73380-49ca-11ea-895a-9562e91f3900.png)
![Example Light wide](https://user-images.githubusercontent.com/14083530/74075987-48b0f700-49ca-11ea-94ef-a07744a3a096.png)


@jcfranco  here are the latest. hopefully this doesn't screw things up too bad

also realized how i forgot to include hover states for the color swatches, see new designs

**Comment by rmstinson** [comment]
Any thoughts or ideas on a mixed-state for the color picker input field? The direction the Charts team is taking this is to leave the input field blank, and filled back in once a change has happened on all selected elements, or just a single element is selected to display that color.

Like so:
![multiple_selections](https://user-images.githubusercontent.com/12650705/77374636-7eb2fc00-6d28-11ea-892f-24d21d8b1422.png)

**Comment by bstifle** [comment]
@rmstinson thats one way, but my first hunch is it could look disabled

sketch does this:
![image](https://user-images.githubusercontent.com/14083530/77376351-6abdc900-6d2d-11ea-9d47-2ddbd4d6daf2.png)


illustrator:
![image](https://user-images.githubusercontent.com/14083530/77376428-875a0100-6d2d-11ea-8635-6bcfeed7a125.png)

and photoshop just shows the color of the first thing you select. (not very helpful)

**Comment by macandcheese** [comment]
Hey @jcfranco - is this still in the works, or maybe close to a draft PR for someone else to pick up if need be?

**Comment by jcfranco** [comment]
Sorry for the delay. I've been on and off on this. 😞 I have a branch with a functional version of it with a few things pending. I'll shoot for a PR next week.

**Comment by macandcheese** [comment]
Cool, no rush, just doing some issue 🧹🧹

**Comment by jcfranco** [comment]
New `calcite-color` component installed! 🎉 See [PR](https://github.com/Esri/calcite-components/pull/592) for more info.

**Comment by paulcpederson** [comment]
![Happy-dance-2](https://user-images.githubusercontent.com/1031758/88445646-c29e3680-cdd8-11ea-90d9-ca9caba85cc9.gif)
