### ISSUE TITLE
Double clicking the reference element of an open popover causes unexpected placement

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#6404]
### Actual Behavior

![image](https://user-images.githubusercontent.com/52869490/215910566-f0b92ab9-51fa-4b5c-9b59-0556375af7b5.png)

Double clicking the reference element of an open popover makes it position weird, going to the top left of the screen

### Expected Behavior

I would expect it to not change position at all, possibly close? Not clear

### Reproduction Sample

https://codepen.io/eborgen/pen/OJwBrPK?editors=1000

### Reproduction Steps

1. Click the button to open the popover
2. Double click the button

### Reproduction Version

1.0.3

### Relevant Info

```
Additional information:
1. This behavior also occurs on other tools.
2. This behavior also occurs on FF/Safari/Edge chromium browsers.

Test case:
https://github.com/ArcGIS/I18N-BYS-TestCases/issues/10286

Configuration:
1. Build: AGOL 2023.1 devext site
2. OS: ENU Win 10
3. Browser: Chrome (109.0.5414.120)
4. Found by date: 1/31/2023

Build Number : 1/31/2023
```

### Impact

Its pretty consistent and easy for a user to accidentally do this

### Esri team

ArcGIS Map Viewer

**Comment by ethanbdev** [comment]
Also repro'd in the calcite components public doc site: https://developers.arcgis.com/calcite-design-system/components/popover/

**Comment by macandcheese** [comment]
Adding on, this issue (or an issue somewhat similar to it), is also evident in the component sample app UI itself, but with Tooltip. 

Quickly double clicking the Action Bar Actions can occasionally cause the Tooltip to reposition and in that case, appear cutoff: 
<img width="375" alt="Screen Shot 2023-01-31 at 8 59 39 PM" src="https://user-images.githubusercontent.com/4733155/215927208-db9aa640-3408-453a-85ca-393408f64d19.png">

Not 100% the same but another weird Floating UI thing, might help diagnose.

**Comment by amring1** [comment]
Can we get a timeline on a fix for this? It's frustrating for many of our analysis components.

**Comment by geospatialem** [comment]
Adding priority labels, which weren't available at the time of issue creation.

Priority is mentioned since it was an issue reported by support, and aiming to get a resolution as soon as possible.

**Comment by jcfranco** [comment]
This is scheduled for the April milestone. For now, setting `overlay-positioning="fixed"` can be used as a workaround.

**Comment by geospatialem** [comment]
Verified in `1.3.0-next.4`

![veridy-double-click-popover-fix](https://user-images.githubusercontent.com/5023024/231866499-b136ee1c-1730-46a5-b8fe-4b9a7c7e2093.gif)
