### ISSUE TITLE
Restore `intl-close` attribute to calcite-modal

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#6408]
### Description

The Solutions team uses Calcite both declaratively and programmatically.  Currently, a major section of our software is written in a declarative style, e.g.,
```elm
calciteModal
    [ HA.attribute "intl-close" <| Translations.Cards.close translations
    , HA.attribute "width" "l"
    ]
```
which compiles into HTML such as
```html
<calcite-modal intl-close="Fermer" width="l"></calcite-modal>
```

The lose of `intl-close`​ introduces a lot of work because the declarative part of the app (in Elm) is strongly separated from the programmatic part of the app (in TypeScript) to minimize runtime errors.

### Acceptance Criteria

Ability to include `intl-close` or equivalent to declaratively define the close button's text.

### Which Component

Modal

### Esri team

ArcGIS Solutions

**Comment by jcfranco** [comment]
@MikeTschudi Is it possible for you to leverage the built-in translations or do you need to provide custom strings? Currently, we have no plans to bring back an _attribute equivalent_ for message overrides.

**Comment by MikeTschudi** [comment]
Thank you, @jcfranco!  I'm happy to use the built-in translations; I didn't know that they'd been added to the component.
