### ISSUE TITLE
Sample section available on deprecated components?

### ISSUE THREAD

**Issue by ekim2** [Esri/calcite-components#6409]
### Description

I'm not a calcite expert, but I do find the doc very useful to help understand the components. I noticed recently that the Value List component has been deprecated. The last time I look at the doc for this component (I don't think it was deprecated at that time), there was a Sample section that allowed me to experiment with the component. Now, I no longer see it. Is this because the component has been deprecated? 

If possible, it may be useful to maintain the sample section even though the component is deprecated, or at least until a replacement component supports the full functionality. In the case of this value list, it supports drag to order, that the List component does not seem to support. The List component doc still suggests using the value list in this case.

> Additional functionality, such as sorting or removing items in a list will be added in the near future. In the meantime, use the deprecated [Value List](https://developers.arcgis.com/calcite-design-system/components/value-list/).

In terms of the deprecation notice, it may be useful to include when the component was deprecated (date or version?). Also, will a component ever be completely removed? That may be useful info if necessary.
![image](https://user-images.githubusercontent.com/11168738/216128195-28c00187-6d10-403c-a442-34a904279649.png)

thanks for listening!

### Which Component

Value List

**Comment by macandcheese** [comment]
Thanks for reporting @ekim2, great feedback.

@geospatialem - let's add back the sample for the deprecated components. The idea to add the version in which a component was deprecated to the notice is also something we should follow through with.

To the last point - components that are deprecated will at some point reach the end of their lifecycle and be removed - at this point we don't anticipate that happening for Value List / Pick List for a good while as there still isn't 100% feature parity, but cc @jcfranco on that.

**Comment by geospatialem** [comment]
Thanks @ekim2 - we will be adding back in samples for the `value-list` and `pick-list`, including their child components in next week's doc release.

Additionally, as Adam mentioned above add more context to the deprecations providing the release the deprecation took place.

**Comment by ekim2** [comment]
Thanks all. 
How do people find out about deprecated components? Would it be helpful to list them as part of release notes??
https://developers.arcgis.com/calcite-design-system/latest/release-notes/

**Comment by geospatialem** [comment]
> How do people find out about deprecated components? Would it be helpful to list them as part of release notes?? https://developers.arcgis.com/calcite-design-system/latest/release-notes/

With 1.0.3 being the first production release, we didn't have a comprehensive list of changes and updates since its the first official release out of beta. However, we do plan to add context in upcoming quarterly releases for folks.

> I suppose over time, your release notes could provide a historical perspective of changes to calcite. I always found this interesting. https://developers.arcgis.com/rest/services-reference/enterprise/what-s-new.htm, because it allows you to see when some change happened.

Yes, most definitely. Thanks for the resource! Definitely something we'd love to achieve in upcoming releases.

**Comment by geospatialem** [comment]
Verified in this week's documentation release:

![image](https://user-images.githubusercontent.com/5023024/217625274-90754483-97d7-4018-93d0-5cca95f9da3e.png)

![image](https://user-images.githubusercontent.com/5023024/217625520-57db2974-8854-4b46-b590-fe4038136f45.png)
