### ISSUE TITLE
Distribution (lazy esm) build of Calcite components does not work in Vite 

### ISSUE THREAD

**Issue by omarkawach** [Esri/calcite-components#6419]
### Actual Behavior

When lazy loading, Vite does not recognize the dynamic importing and fails silently. 

Getting the Distribution build to work with Vite requires extra configuration.

### Expected Behavior

Expect both the Distribution build and Custom Elements build of Calcite components to work in Vite.

Users should be able to use whichever build they prefer.

### Reproduction Sample

https://codesandbox.io/p/sandbox/calcite-vite-lazy-loading-bug-09bh7k?file=%2Fsrc%2Fmain.tsx

### Reproduction Steps

1. Open the sandbox
2. See that the `calcite-scrim` is not there in the preview
3. Comment out the Distribution build
4. Uncomment the Custom Elements build
5. See that the scrim now appears

### Reproduction Version

1.0.3

### Relevant Info

To support the Distribution build with Vite, the following extra needs to be turned on in `stencil.config.ts`

```js
extras: {
    experimentalImportInjection: true  
},
```

Relevant links:
[Stackoverflow: Unable to load stencil components lib with Vue3 using Vite](https://stackoverflow.com/questions/72530354/unable-to-load-stencil-components-lib-with-vue3-using-vite)

[Stencil doc: experimentalImportInjection](https://stenciljs.com/docs/config-extras#experimentalimportinjection)

### Esri team

ArcGIS Online

**Comment by Trashami** [comment]
Is there a work around for this? I have a Vite app that worked with calcite-components 1.0.0-beta.98. When I attempt an update to 1.0.3 I get the same results and nothing loads.

**Comment by geospatialem** [comment]
It looks like the above sample encounters an error. 

@omarkawach Would you be able to verify if the fix with our recent patch, `1.0.4` mitigates the build with Vite?

**Comment by omarkawach** [comment]
Strange, I can run the sample fine. I wonder if users encounter an error because it is failing to load the dist build. I updated the sample to start with the custom elements build https://codesandbox.io/p/sandbox/calcite-vite-lazy-loading-bug-09bh7k

I upgrade to 1.0.4 and still have the same issue. 

I think the issue might be that Calcite's stencil config has `experimentalImportInjection` on the outside of `extras`

```js
// https://github.com/Esri/calcite-components/blob/master/stencil.config.ts#L130
experimentalImportInjection: true,
extras: {
    scriptDataOpts: true
  }
```

This is what our stencil config looks like for the arcade editor

```js
extras: {
    experimentalImportInjection: true
  },
```

Once our configs match, the stencil library must be recompiled

**Comment by omarkawach** [comment]
Strange, I can run the sample fine. I wonder if users encounter an error because it is failing to load the dist build. I updated the sample to start with the custom elements build https://codesandbox.io/p/sandbox/calcite-vite-lazy-loading-bug-09bh7k

I upgrade to 1.0.4 and still have the same issue. 

I think the issue might be that Calcite's stencil config has `experimentalImportInjection` on the outside of `extras`

```js
// https://github.com/Esri/calcite-components/blob/master/stencil.config.ts#L130
experimentalImportInjection: true,
extras: {
    scriptDataOpts: true
  }
```

This is what our stencil config looks like for the arcade editor

```js
extras: {
    experimentalImportInjection: true
  },
```

Once our configs match, the stencil library must be recompiled

**Comment by geospatialem** [comment]
Hm, maybe its something with Windows? @omarkawach This is the message I'm seeing when visiting the example:

![image](https://user-images.githubusercontent.com/5023024/217892853-9c389da8-0fc1-4a77-af44-97f8e9a6b908.png)

If the above still holds true, lmk, and we can dive back in to determine what might be causing the issue.

**Comment by omarkawach** [comment]
Not sure what's going on. I don't get that code sandbox error on my iPhone or MacBook when I view the sample anonymously

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/49499098/217895712-1c77d5ba-5b5a-4cb9-af15-e73419494652.png">

The sample mostly follows your vite example https://github.com/Esri/calcite-components-examples/tree/master/vite but with the dist build instead of custom elements build


```js
/**
 * Custom Elements Build
 * https://stenciljs.com/docs/custom-elements
 */

/* Comment this out */
import { setAssetPath } from "@esri/calcite-components/dist/components";
setAssetPath("https://unpkg.com/@esri/calcite-components/dist/calcite/assets");

/**
 * Distribution Build
 * https://stenciljs.com/docs/distribution
 */

/* Ucomment this */
// import { defineCustomElements } from "@esri/calcite-components/dist/loader";
// defineCustomElements(window, {
//  resourcesUrl:
//    "https://unpkg.com/@esri/calcite-components/dist/calcite/assets",
// });
```

**Comment by geospatialem** [comment]
We were able to repro on our end, and will determine next steps for a fix.

**Comment by geospatialem** [comment]
Verified in [Esri/calcite-components-examples/vite](https://github.com/Esri/calcite-components-examples/tree/master/vite) with `1.0.6`.
