### ISSUE TITLE
[Tree] Improve  documentation

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6429]
### Description

Tree has many selection modes and some values are not immediately clear in their function. We should improve our documentation around this component. A good first step would be to improve the  API reference.

### Which Component

Tree

### Resources

Even a short sentence about each one would be helpful. Our current text is pretty meaningless.

<img width="355" alt="Screen Shot 2023-02-06 at 3 58 27 PM" src="https://user-images.githubusercontent.com/4733155/217114415-e60f3216-b9c5-4dad-8e39-15d419827bcb.png">

**Comment by geospatialem** [comment]
Verified on `master.sites` for release tomorrow.

![image](https://user-images.githubusercontent.com/5023024/234388943-6be221d4-1c91-4511-93ba-9736061bd3d6.png)
