### ISSUE TITLE
Value in input-date-picker gets plus sign after every character

### ISSUE THREAD

**Issue by arjanvanzutphen** [Esri/calcite-components#6432]
### Actual Behavior

The date string value presented in the input field gets on unexpected moments reformatted to string with the plus sign after every character. Clicking on the input-date-picker brings the date picker to the year 2 (2021 years ago).

![image](https://user-images.githubusercontent.com/25850072/217285011-29b31720-83bc-44c4-9de7-89386ba4a4ec.png)

### Expected Behavior

The expected values can be seen in the screenshot

![image](https://user-images.githubusercontent.com/25850072/217285193-596429f3-2e9d-4c78-a81b-59b2bdbcb031.png)

### Reproduction Sample

[Not able to reproduce yet]
Here are the settings I've used: (https://codepen.io/arjan_esrinl/pen/BaPEbJL?editors=1000)

### Reproduction Steps

Not able yet

### Reproduction Version

1.0.3

### Relevant Info

Windows 10
Chrome 109

### Regression?

beta.98

### Impact

User needs to write down the current date.

### Esri team

N/A

**Comment by geospatialem** [comment]
> @arjanvanzutphen We're trying to prioritize work on the effort, and wondering if we can get a repro sample or follow-up on what the experience is?

@arjanvanzutphen Re-pinging if there's a snippet or code sample we could add for additional context to troubleshoot. Without the additional context, we will be closing the issue next month.

**Comment by geospatialem** [comment]
Closing per https://github.com/Esri/calcite-components/issues/6432#issuecomment-1503842993 and https://github.com/Esri/calcite-components/issues/6432#issuecomment-1532109975. If additional context is provided, the issue can be reopened for the Calcite team to work through a fix.
