### ISSUE TITLE
[Flow item] Add z-index value to back button tooltip

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6433]
### Description

Leverage existing Tailwind configuration z-index values so Tooltips across Calcite components have similar behavior and expectations.

MapViewer has a header with a z-index value, which if the Flow Item had a value would be displayed on top of the header when activated.

cc @jcfranco 

### Acceptance Criteria

Regardless of the developer environment, the Flow Item's "Back" button tooltip should display using similar z-index values used across Calcite from our [Tailwind config](https://github.com/Esri/calcite-components/blob/master/tailwind.config.ts#L212-L223) where  has a value of .

### Relevant Info

Add a z-index value to the [flow-item](https://github.com/Esri/calcite-components/blob/master/src/components/flow-item/flow-item.scss#L8-L13).

### Which Component

Flow Item

### Example Use Case

Supporting Esri teams that have implemented custom headers in products, which contain  values.

### Esri team

ArcGIS Map Viewer

**Comment by jcfranco** [comment]
> Add a z-index value to the [flow-item](https://github.com/Esri/calcite-components/blob/master/src/components/flow-item/flow-item.scss#L8-L13).

I'm not sure this is the path to go. We only apply z-indices for specific contexts and a back button is not one of them.

@geospatialem Is it possible to get a repro case for this? `z-index` can be tricky, so it'd be good to know we're on the same page before making any adjustments to our layering.

**Comment by geospatialem** [comment]
Unfortunately I was unable to reproduce outside of Map Viewer. This is related to MV's issue 6294 _"Arrow is out of tooltip and does not point to Back icon on Layers/Tables/Basemap panels"_.

@kevindoshier Have you been able to repro outside of MV? All of the cases we've tried to repro are coming up as-expected outside of MV, so wondering if there could be more happening. 

The `tooltip` should have a `z-index` value of `901`, so it should not be conflicting with the header's `z-index`.

![image](https://user-images.githubusercontent.com/5023024/222183210-8f68922b-3133-484f-ba12-6cd337022a16.png)

**Comment by kevindoshier** [comment]
@geospatialem - this issue will only crop up within an app type situation where elements surrounding the   flow item have a higher z-index than the flow-item, for that scenario the tooltip will be beneath the surrounding elements, for instance in MV we have a header that has a menu that drops down, we want that menu to overlap the flow-item, but that leads to this issue since to accomplish that the header must have a higher z-index than the flow-item resulting in the back button tooltip going beneath the header effectively making it invisible.  I added notes here

https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/6294#issuecomment-3938231

**Comment by kevindoshier** [comment]
Here is a repro case that has a similiar structure being used in MV, it seems like its the way the header elements are setup, which is in a different globalNav component

https://codepen.io/kevindoshier/pen/VwGpmrY

**Comment by geospatialem** [comment]
> We can make this change on calcite-flow-item component but it comes with some major refactoring and could be a possible breaking change. We'll keep you posted . Let us know if you have any questions.

WRT Anvesh's note above, if we were to incorporate a change, we're not sure if it would solve the above issue as floating-ui doesn't currently impact z-indices.

We are working towards exposing design tokens via https://github.com/Esri/calcite-components/issues/6558 in the near future, which could help solve the above use case as we work towards exposing z-index tokens to developers. We'll be closing out this issue in favor of 6558 tracking.
