### ISSUE TITLE
Support overriding the line height in `calcite-block` with a css variable 

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#6443]
### Description

For some use cases, have received feedback that the line height in the calcite block description text is a bit much:
![image](https://user-images.githubusercontent.com/52869490/217648578-fdb04f8f-2ffe-445f-9503-aefedc53f929.png)
vs
![image](https://user-images.githubusercontent.com/52869490/217648954-240dbb45-0bb6-4443-9451-c96ad9580e6e.png)

It would be nice to customize this via a css variable to give some extra flexibility to fit different amounts of text.

Alternatively, the prop `description` could accept a `<div>` or `<p>` tag

It seems like there might also be some interference with the `collabsible` property

### Acceptance Criteria

Provide a way to override the default line height for the calcite block description text

### Which Component

calcite-block

### Esri team

ArcGIS Web Analysis

**Comment by macandcheese** [comment]
Hi @ethanbdev - is it possible you have conflicting styles or another version CC in play? This is what I'm seeing with various combinations of collapsible and slotted actions in 1.0.3 : https://codepen.io/mac_and_cheese/pen/NWBVmRw?editors=100

![Screen Shot 2023-02-08 at 3 45 58 PM](https://user-images.githubusercontent.com/4733155/217677519-dc4a784b-18ee-46b9-bbb9-2815964a2acb.png)

This seems like a place we'd like to standardize on an appropriate line height. cc @ashetland / @SkyeSeitz for design input.

**Comment by SkyeSeitz** [comment]
Second that from the Figma side as well. We are already using a 16px line height defined in `var(--calcite-font-size--2)`

<img width="803" alt="image" src="https://user-images.githubusercontent.com/29716057/217678221-c5f50db4-3a91-42c7-9725-c33d8c66825e.png">

So hopefully that is good news, @ethanbdev :)

**Comment by ethanbdev** [comment]
Okay, thanks for the input! Yeah I am seeing some inconsistency trying to apply the line height in different deployments of the components we are building.

Does it seem like then that the second screen shot has too much line height and I need to investigate something?

**Comment by macandcheese** [comment]
It seems like when `collapsible` is not present - the component becomes susceptible to line-height declarations on parent components: 
![Screen Shot 2023-02-08 at 3 58 56 PM](https://user-images.githubusercontent.com/4733155/217679142-5b322dba-c32f-43f0-8fc6-5556cb515cf2.png)

**Comment by macandcheese** [comment]
@geospatialem - for triage - issue could be scoped to fixing above. @ethanbdev - is that an ok resolution? I know you mentioned making the `description` prop a slot for rich content as well.

**Comment by ethanbdev** [comment]
I think if it looks like the screenshot from @SkyeSeitz thats perfect, and I think I was just confused about the collabsible / non-collabsible difference.

As an aside, this looks like NOT the default right? This is what I am trying to fix:
![image](https://user-images.githubusercontent.com/52869490/217683112-08bcbf5b-2136-4351-984d-e2afafc996fa.png)

**Comment by ashetland** [comment]
Correct, the line height in that screenshot doesn't match the default for the component.

**Comment by ethanbdev** [comment]
Add a p- tag to this.. would be great to standardize the line height getting applied inside the block

**Comment by geospatialem** [comment]
Verified for non-collapsable `block`s where the parent has a defined `line-height` with `1.3.0-next.9` via https://codepen.io/geospatialem/pen/BaqQVpM
