### ISSUE TITLE
Tree component parents will not open or close when user clicks on parent name

### ISSUE THREAD

**Issue by ddred11** [Esri/calcite-components#6444]
### Actual Behavior
Tree component only opens and close when user clicks on carat to the left of a parent's name in selection mode: single

Additionally, there are similar hit area issues across the other modes.

This is a usability issue in that the click target is too small and will cause frustration.

### Expected Behavior
User will expect to be able to click on parents' names in addition to carat to open and close content. This is especially the case since the component currently shows a cursor change (suggesting clickability) during hover over the parent.

### Reproduction Sample
https://developers.arcgis.com/calcite-design-system/components/tree/

### Reproduction Steps
This can be reproduced directly from the Developers site
https://developers.arcgis.com/calcite-design-system/components/tree/

Click on Mid West or Westcoast and nothing happens

Note that cursor changes when hovering over these parents leading user to believe they are clickable

### Reproduction Version
1.04

### Relevant Info
All

### Regression?
No response

### Impact
Currently we have had to add wrappers to the tree instances in BA WEB app after adoption to remedy this behavior.

In the BA widget for Experience Builder, there is not time for a solution and usability for this release will be affected.

### Esri team
ArcGIS Business/Community Analyst

**Comment by macandcheese** [comment]
Our visual treatments are pretty inconsistent across modes… @ashetland @SkyeSeitz we should look to improve hit area distinction between expand / collapse and selection state where applicable across these.

**Comment by ftiru** [comment]
Currently, the calcite tree does not allow clicking on the body (in red) to expand/collapse the tree. You have to specifically click on the chevron icon (in green). This is not a good experience and we wanted to know when this can be fixed/implemented.

![image](https://user-images.githubusercontent.com/16827336/225700125-5981ba3b-434c-4802-ad24-02ad47bc98ef.png)

**Comment by subgan82** [comment]
We would benefit on this improvement as well for analysis-spatial-reference component , where we do this on our side today to allow expand/collapse on the tree item name

http://arcgiswebanalysis.esri.com:7080/analysis-components/storybook/?path=/story/components-analysis-spatial-reference-input--basic

**Comment by geospatialem** [comment]
Reallocating to the May release for design considerations.

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.10`

![verify-tree-parent-click-open-close](https://user-images.githubusercontent.com/5023024/236598235-5492e124-52f2-48f0-a01e-ac9c82067d00.gif)
