### ISSUE TITLE
Error when not setting the asset path

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#6445]
### Actual Behavior

There is an error when not setting the asset path in the `custom-elements` or `dist` builds.  The error is coming from `getMessageBundle`, and it seems like components with translations won't render.

```
TypeError
Failed to construct 'URL': Invalid base URL
    at getAssetPath (https://m2io2x.csb.app/node_modules/
stencil/core/internal/client/index.js:456:20
    at getMessageBundle (https://m2io2x.csb.app/node_modules/
esri/calcite-components/dist/components/t9n.js:42:110
    at fetchMessages (https://m2io2x.csb.app/node_modules/
esri/calcite-components/dist/components/t9n.js:67:10
    at setUpMessages (https://m2io2x.csb.app/node_modules/
```

### Expected Behavior

There shouldn't be any errors when an asset path isn't provided. I'd expect icons/translations/etc not to load, but components should still be usable in english.

### Reproduction Sample

https://codesandbox.io/s/ccr-assets-error-m2io2x

### Reproduction Steps

1. Open the repro sample

### Reproduction Version

1.0.4

### Relevant Info

cc @anveshmekala @jcfranco 

### Esri team

Calcite (dev)

**Comment by dasa** [comment]
Can `getAssetPath` be exported at `@esri/calcite-components/dist/components/index`? I'd like to be able to call it to see if it throws an error. Even better would be a better way to see if the assets path has been set, but I don't see one.

**Comment by jcfranco** [comment]
@benelan Local assets need to go through `setAssetPath` and `getAssetPath`, so I don't think we can do anything related to the original issue. 

@dasa Can you create a separate issue for that? I'll get working on a PR in the meantime.

**Comment by jcfranco** [comment]
Closing per ☝️.

**Comment by dasa** [comment]
> Can you create a separate issue for that? I'll get working on a PR in the meantime.

Issue #6696
