### ISSUE TITLE
[Shell Panel] Place Action Bar in correct location when used in top / bottom Shell slots

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6447]
Description

To continue support of new patterns afforded by: https://github.com/Esri/calcite-components/issues/6389, the Shell Panel should place Action Bar at the extent of the Shell (top / bottom) when used in relevant slots. We may be able to infer this from the slotted Shell Panel location and set the "placement" of the Action Bar as a result.

Acceptance Criteria

When used in (upcoming) panel-bottom, and panel-top slots, the Shell Panel action bar is positioned at the extent of the shell. The Panel should be placed above / below following the pattern of the panel-start and panel-end experience.

Relevant Info

Additional issues from design requirements.

Which Component

Shell, Shell Panel, Action Bar

Example Use Case

No response

Esri team

Calcite (design)

**Comment by driskull** [comment]
@macandcheese do you have more information for this issue? Maybe a design link and requirements?

**Comment by macandcheese** [comment]
Sorry, fixed the description, some got overwritten by a GitHub action. Yeah, there is a corresponding set of presentation / demo for these on Confluence. Where shell panel is to be used in the top / bottom slots within Shell; the action bars should be slotted beneath / above - at the extent of the page frame. Can follow up on Teams, I think a lot of these were opened while you were OOO!

**Comment by geospatialem** [comment]
Dev work will be initiated once https://github.com/Esri/calcite-components/issues/6389 is complete.

**Comment by macandcheese** [comment]
I have a pretty good jump on this from #6389.

**Comment by driskull** [comment]
@macandcheese let me know if you want me to take this one.

**Comment by macandcheese** [comment]
Hey - sure thing @driskull, feel free to grab if you have bandwidth. 

Separately, I mention in the epic but there is no explicit issue yet - Shell Panel will need to have resizable relocated when in these slots, and likely a set of height css var to accompany that.

**Comment by driskull** [comment]
@macandcheese we might need to discuss this strategy. I don't think we currently do anything like this where the element would adjust itself depending on where its slotted.

Currently, we have the `position` property on the `shell-panel` which allows the action-bar to be placed at the start or end. We would probably need a `layout` property added to `shell-panel` for `vertical` or `horizontal`.

**Comment by driskull** [comment]
@macandcheese assigned back to you for testing and finishing styling touches.

**Comment by geospatialem** [comment]
Verified the following in `master` with Shell panel:
- [x] `resizable` prop to `panel-top` and `panel-bottom` slots
- [x] new CSS vars in `layout="horizontal"` or `panel-top` / `panel-bottom` slots
    - `--calcite-shell-panel-height`
    - `--calcite-shell-panel-max-height`
    -  `--calcite-shell-panel-min-height`
 
Verified code:
```html
<calcite-shell>
  <calcite-shell-panel layout="horizontal" resizable slot="panel-top" position="start" style="--calcite-shell-panel-height:60vh;--calcite-shell-panel-max-height:75vh;--calcite-shell-panel-min-height:50vh;">
    <calcite-action-bar slot="action-bar" class="calcite-mode-dark">
      <calcite-action-group>
        <calcite-action text="Save" icon="save" indicator> </calcite-action>
        <calcite-action text-enabled icon="map" text="New" slot="menu-actions"> </calcite-action>
        <calcite-action text-enabled icon="collection" text="Open" slot="menu-actions"> </calcite-action>
      </calcite-action-group>
  </calcite-shell-panel>
</calcite-shell>
```
