### ISSUE TITLE
[Panel] Add Action Bar slot

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6448]
### Description

As proposed, the Panel gains an "action bar slot" beneath the rendered header to provide familiar and consistent placement of actions in a workflow setting. This will enable the migration path forward from using Shell Center Row to using Shell Panel in the "panel-bottom" and "panel-top" (upcoming) shell slots.

### Acceptance Criteria

The Panel has a positioned action bar that is located beneath the rendered header / slotted header content. Action bar within this slot is set to horizontal.

### Which Component

Panel, Action Bar

### Example Use Case

cc @asangma, @mitc7862

MV - Analysis, etc. 

### Esri team

Calcite (design)

**Comment by brittneytewks** [comment]
@driskull can you please add an estimate to this issue? thank you!

**Comment by ethanbdev** [comment]
Watching 👀

**Comment by geospatialem** [comment]
Verified on `1.3.0-next.4`.

![image](https://user-images.githubusercontent.com/5023024/231895474-ad7b2ffb-b377-4a76-9674-eca8580c5af1.png)

**Comment by driskull** [comment]
@geospatialem @macandcheese can you create a new issue for adding an action bar slot to the flow item?

**Comment by driskull** [comment]
nevermind. created https://github.com/Esri/calcite-components/issues/6886
