### ISSUE TITLE
Popover inside modal is not positioned next to reference element in some browsers

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#6450]
### Actual Behavior
Chrome (Win & MacOS), Edge:
![1 Chrome (Win   MacOS), Edge-](https://user-images.githubusercontent.com/3362490/218832422-89d7ff0f-da55-4cba-93b4-8e536d075537.png)

### Expected Behavior
Firefox, Safari:
![2 Firefox, Safari-](https://user-images.githubusercontent.com/3362490/218832466-d93688b0-83da-427a-8d3d-e2df0df95582.png)

### Reproduction Sample
https://codepen.io/miketschudi/pen/WNKqZPV?editors=1000

### Reproduction Steps
Open the codepen in a wide and high browser window
Click on the "Layer information" reference element button

### Reproduction Version
1.0.5

### Relevant Info

- Problem browsers:
  - Windows 10
    - Chrome 109 & 110
    - Edge 109
  - MacOS Monterey 12.6.2
    - Chrome 109 & 110
- OK browsers:
  - Windows 10
    - Firefox 109
  - MacOS Monterey 12.6.2
    - Safari 16.3

### Regression?
No response

### Impact
Low impact

### Esri team
ArcGIS Solutions

**Comment by geospatialem** [comment]
This has been mitigated across OS and browsers in `1.2.0`.
