### ISSUE TITLE
Inputs not always focusable in Modal

### ISSUE THREAD

**Issue by ellenupp** [Esri/calcite-components#6454]
### Actual Behavior
Inputs used inside calcite-modal are not always focusable, making them non-functional. Might be related to when they are not initially visible, like when used in a tab.

### Expected Behavior
Inputs should always be focusable when not disabled.

### Reproduction Sample
https://codepen.io/ellupp/pen/BaPgVQV?editors=1000

### Reproduction Steps
click button to open the modal
click on 'tab 2'
try to click on the input. you cannot focus on the input.
Reproduction Version
1.0.5

### Relevant Info
No response

### Regression?
1.0.31.0.4

### Impact
This is a blocking issue as it prohibits many editing workflows

### Esri team
ArcGIS Dashboards

**Comment by mpayson** [comment]
We're seeing this too with the item properties modal in our app and the inputs are all initially visible

https://user-images.githubusercontent.com/5892789/218186663-77457b0a-067c-4df0-8841-d1512bb61bf0.mov

**Comment by ellenupp** [comment]
cc @vijayendranj

**Comment by ellenupp** [comment]
Hi @alisonailea, why did you edit this issue to remove all the details?

**Comment by paulcpederson** [comment]
Impacts many teams. As a workaround we've found we can call `updateFocusTrapElements` on the modal after the new content is available, but hard to know when to time this. 

Very much seems to be related to https://github.com/Esri/calcite-components/issues/6281

**Comment by geospatialem** [comment]
> Hi @alisonailea, why did you edit this issue to remove all the details?

@ellenupp Thanks for pinging us, there were some errors in automation. Added in the Dashboards label, so should be set now. cc @alisonailea

**Comment by jcfranco** [comment]
@mpayson @paulcpederson Can you confirm if the original repro case represents your use cases? If not, could you share a repro case? 

@geospatialem We should look into this for an upcoming patch because of its impact.

**Comment by jcfranco** [comment]
@paulcpederson That'd be very helpful. Thanks!

**Comment by jcfranco** [comment]
Quick update: I've got a fix in the works. PR coming up!

**Comment by jcfranco** [comment]
@geospatialem @benelan and myself are stepping in to help verify this one.

**Comment by jcfranco** [comment]
Verified locally by testing original repro case in:

* OSX: Chrome (110.0.5481.100), Firefox (109, 110), Edge (110.0.1587.41), Safari (Version 16.2)
* Windows: Chrome (110.0.5481.100), Firefox (109, 110), Edge (110.0.1587.46)

**Comment by jmanke** [comment]
@jcfranco I can still repro the issue in the [updated repro case](https://codepen.io/jcfranco/pen/NWLWoxp?editors=1000) with the repro steps in the description.

OSX: Chrome (109.0.5414.119)

**Comment by jcfranco** [comment]
@jmanke Thanks for testing. For the time being, we'll revert this along with https://github.com/Esri/calcite-components/pull/6434 for another patch release today.
