### ISSUE TITLE
Popover will not receive focus when animation is disabled

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#6457]
### Actual Behavior
Popovers will not receive focus when the user's computer is configured to disable animation. This does not work either with the default popover focus behavior, or by explicitly calling popoverElement.setFocus()

### Expected Behavior
Popovers can always receive focus

### Reproduction Sample
https://codepen.io/mpayson/pen/mdjNdbG

### Reproduction Steps
Disable animation on your computer
Open code pen
Click "i" action in the top right
Verify popover opens but does not receive focus
Repeat with animation enabled, verify the popover does receive focus
Reproduction Version
1.0.4

### Relevant Info
No response

### Regression?
No response

### Impact
No response

### Esri team
ArcGIS Online

**Comment by jcfranco** [comment]
This should be addressed by https://github.com/Esri/calcite-components/pull/6605.

**Comment by geospatialem** [comment]
> This should be addressed by #6605.

Verified as mitigated in `1.1.1-next.2` with animations not shown on Windows:

![verify-popover-focus-animations-disabled](https://user-images.githubusercontent.com/5023024/227549023-c71d487f-eee2-467c-9f1b-9a39aed13768.gif)
