### ISSUE TITLE
tooltip closeOnClick not working

### ISSUE THREAD

**Issue by stefanobettinelli** [Esri/calcite-components#6459]
### Actual Behavior

calcite-tooltip accepts a prop called closeOnClick, if true and on click on the reference element it should close the tooltip
the tooltip should be closed/hidden

### Expected Behavior

When passing the closeOnClick the tooltip should get closed on click on the reference element

### Reproduction Sample

https://codepen.io/stefanobettinelli/pen/BaOBZrE?editors=1000

### Reproduction Steps

Hover the link and click 

### Reproduction Version

1.0.5

### Esri team

ArcGIS Scene Viewer

**Comment by macandcheese** [comment]
Hi @stefanobettinelli - in a non-TSX environment you should use the "dash-case" attribute - `close-on-click`: https://codepen.io/mac_and_cheese/pen/BaOaYBL?editors=1010. 

[Stencil docs](https://stenciljs.com/docs/properties#variable-casing)

**Comment by stefanobettinelli** [comment]
@macandcheese thanks, in SV we're using it correctly with camelCase since we have a TSX environment, but there's a specific case were it's no being closed. Let me investigate some more, but I will close this one.
Thanks

**Comment by macandcheese** [comment]
Feel free to re-open if there is a case we can take a look at :)
