### ISSUE TITLE
calcite-time-picker: popover at wrong location

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#6460]
### Actual Behavior

![image](https://user-images.githubusercontent.com/44481292/218533268-42fc4e7d-4640-420c-8dd5-4b17c9de1215.png)

### Expected Behavior

popover stays near the time input box

### Reproduction Sample

https://codepen.io/afreitag/pen/abaoQRy

### Reproduction Steps

1. open codepen
2. click on time input box, notice popover opens near the input (still a bit far away!)
3. next click on the label 'Time', notice the popover moves to the top left

### Reproduction Version

1.0.5

### Regression?

don't think so

### Impact

medium

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Research will determine a time estimate for implementation for a fix in an upcoming milestone.

**Comment by jcfranco** [comment]
This should be fixed in `next` via https://github.com/Esri/calcite-components/issues/6404.

**Comment by geospatialem** [comment]
Verified in `1.3.0-next.8`.

![image](https://user-images.githubusercontent.com/5023024/233099455-4f97e2b0-a233-4e9e-9cf4-41ef27c82c88.png)
