### ISSUE TITLE
Date picker is fixed on screen when scrolling

### ISSUE THREAD

**Issue by jlias-devtester** [Esri/calcite-components#6463]
### Actual Behavior

The calendar of start date is fixed on screen while scrolling up or down on 'Create report' dialog with resolution 1440 x 900 or below.

### Expected Behavior

Calendar should be moved along with the scroll bar after clicked calendar icon of start date and then scroll on 'Create report' dialog when resolution is set to 1440 x 900 or below.

### Reproduction Sample

https://codepen.io/rpanichakit/pen/WNgePqY?editors=100

### Reproduction Steps

Steps:
1. Prepare a clean EN browser on machine with resolution is set to 1440 x 900.
2. Login https://qaext.arcgis.com with a valid account.
3. Go to Organization->Status->Reports tab.
4. Click 'Create report' dropdown and select 'Single report'.
5. Click 'Report type' dropdown and select "Item view report", make sure scroll bar is appeared. (key step)
6. Click calendar icon of start date Under 'Timeframe'. (key step)
7. Scroll the mouse or drag the scroll bar.
8. Observe that the calendar of start date is fixed on screen while scrolling up or down on 'Create report' dialog with resolution 1440 x 900 or below.

### Reproduction Version

1.0.3

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Research to be conducted in June for a priority and estimate for an upcoming milestone.

**Comment by geospatialem** [comment]
Verified on `master`.
