### ISSUE TITLE
Latest version availability and issues with unpkg.com

### ISSUE THREAD

**Issue by capegreg** [Esri/calcite-components#6492]
### Background

As of 2/16/2023, we are no longer able to use unpkg.com. I'm not sure if the issue is on the unpkg.com side or ours. We use several other CDNs without issues. We had to switch CDN from unpkg.com to js.arcgis.com and everything is working much better. We plan on staying here! 

I have some concerns with the Calcite devops and API documentation.  Why is 1.0.7 available on unpkg.com but not on js.arcgis.com? Why isn't the Esri Calcite API documentation getting updated? It's still on beta 99. This is very concerning.

Latest version available on unpkg.com
https://unpkg.com/@esri/calcite-components@1.0.7/

Latest version available on js.arcgis.com
https://js.arcgis.com/calcite-components/1.0.6/

### Desired Outcome

Latest version should be up-to-date on js.arcgis.com.
API documentation should be updated to latest version.

**Comment by geospatialem** [comment]
Closing out this issue per the discussion above, and resources posted to Community.
