### ISSUE TITLE
Input date picker - calendar doesn't adjust to programmatically specified date

### ISSUE THREAD

**Issue by jlias-devtester** [Esri/calcite-components#6495]
### Actual Behavior

In ArcGIS Online, it is possible to get the date picker in a state where you cannot select the start and end dates you need

### Expected Behavior

Regardless of how you select a start and end date, the calendar picker should update to show the correct month that you're trying to select.

### Reproduction Sample

https://codepen.io/rpanichakit/pen/RwYPYvq

### Reproduction Steps

1. Prepare a clean ENU browser.
2. ArcGIS online
3. Switch to Organization page and click Status tab.
4. Navigation to Reports and click Create Single report.
5. Expand Report type and select Activity.
Scenario 1:
6. Navigation to Month and expand end date calendar.
7. Select the previous month of current month. (e.g. Select January in 2023 since current month is February) -key step
8. Navigation to Quarter and expand end date calendar.
9. Click > Next icon on calendar and observe the result.
10. Expand start date calendar.
11. Click < Previous icon on calendar and observe the result.
Scenario 2:
12. Navigate to Week and expand start date calendar after step 5.
13. Select certain date which is in current quarter. (e.g. Select 1/1/2023 date since current quarter is from January to March)-key step
14. Navigation to Quarter and expand end date calendar.
15. Click > Next icon on calendar and observe the result.
16. Expand start date calendar.
17. Click < Previous icon on calendar and observe the result.

Actual Result:
1. It is skipped from January 2023 to December 2022 after clicking > Next icon on calendar in step 9 and step 15.
2. It is skipped from December 2022 to September 2022 after clicking < Previous icon on calendar in step 11 and step 17.

### Reproduction Version

not sure

### Regression?

I do not believe so as this is reproducible in production, so it's been a bug since at least November 2022.

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Related https://github.com/Esri/calcite-components/issues/6469

**Comment by geospatialem** [comment]
Verified on `1.5.0-next.8`

![verify-list-filter](https://github.com/Esri/calcite-components/assets/5023024/07fe3334-3ed4-418d-98a1-6febc6561b42)
