### ISSUE TITLE
Tree items with icons appear misaligned

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#6508]
### Actual Behavior

The leading edges of the tree-items' icons are not aligned with the leading edges of their siblings:

<img width="204" alt="Screenshot 2023-02-23 at 11 25 35 AM" src="https://user-images.githubusercontent.com/421496/220969944-aff9bb4b-1ced-41f6-8657-7e7805df1b50.png">

### Expected Behavior

The leading edges of the tree-items' icons are aligned with the leading edges of their siblings:

<img width="204" alt="Screenshot 2023-02-23 at 11 34 13 AM" src="https://user-images.githubusercontent.com/421496/220970857-b9d4442c-a345-468c-9835-625130b0f34a.png">

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/VwGjyvZ

### Reproduction Steps

1. Visit repro sample and expand tree items

### Reproduction Version

1.0.7

### Relevant Info

The `.icon-start` element is applying a `margin-inline` style, but it should probably be a `margin-inline-end` style instead.

### Impact

The misalignment doesn't look great, plus the Field Maps web app has a tree in a resizable panel -- so the extra space further constrains the usable width.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Consideration for enhancement should be routed through designers for next steps.

**Comment by geospatialem** [comment]
Closing in favor of https://github.com/Esri/calcite-components/issues/7096
