### ISSUE TITLE
Clicking tree item action also selects it

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#6509]
### Actual Behavior

Clicking a tree item's slotted `actions-end` action(s) also selects the tree-item.

### Expected Behavior

Clicking a tree item's slotted `actions-end` action(s) does not selects the tree-item.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/poObpdK

### Reproduction Steps

1. Visit sample
2. Click the tree item's trash icon (all the way on the right side of the viewport)
3. The tree item becomes selected

### Reproduction Version

1.0.7

### Impact

On a technical level, in the Field Maps web app, selecting a tree item can be costly since it loads a layer and form. We want to be able to perform actions on other layers (e.g. remove them) without deselecting the current layer.

On a usability level, it can be surprising that the tree-item becomes selected here since the user can only anticipate with certainty that the clicked action will be performed.

One workaround is to manually stop event propagation of `click` and `keydown` events on tree-item actions.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.10` via mouse and keyboard selection of the slotted `action`, where the `tree-item` selection does not occur.

![verify-tree-slotted-action-unrelated-to-select](https://user-images.githubusercontent.com/5023024/236598412-d6249eab-60da-42e6-8351-2fa68be5e76f.gif)
