### ISSUE TITLE
Update calcite-dropdown to use Popper.js

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#651]
Use Popper for positioning to allow for vertical positioning (related) https://github.com/Esri/calcite-components/issues/564

- Need to make sure current animations are used in Popper
- Potentially restrict props-passed-to-Popper to "top" and "bottom" (??) 

It may also be a good time to update the Combobox dropdown...

**Comment by driskull** [comment]
Installed.

**Comment by driskull** [comment]
> It may also be a good time to update the Combobox dropdown...

@macandcheese do we want another issue for this one?

**Comment by driskull** [comment]
Installed for combobox too.
