### ISSUE TITLE
fix(tree-item): regression with content getting clipped

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#6516]
### Actual Behavior

Regression with calcite-tree clipping its content (not only actions). This line is causing the clipping: https://github.com/Esri/calcite-components/blob/728f42b4ad219f5c947cfd5226db7959c3cfd9c1/src/components/tree-item/tree-item.scss#L71 

### Expected Behavior

https://codepen.io/jcfranco/pen/ZEMOMVw

### Reproduction Sample

https://codepen.io/jcfranco/pen/GRXqGxG

### Reproduction Steps

See codepen

### Reproduction Version

V1.0.7

### Relevant Info

Workaround is provided: https://codepen.io/jcfranco/pen/ZEMOMVw

### Regression?

yes

### Impact

Impacts Arcade team. 

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Appears to be similar to #6514, which will be addressed in the upcoming `1.0.8` patch.
