### ISSUE TITLE
Split Button Enhancements

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#652]
1. Appearance for entire button: clear|transparent|...
2. Separate `appearance` attribute for primary
2. Separate `disabled` attribute for primary 

Simulation of what we would like to be able to achieve:
- Primary disabled but dropdown still active
![image](https://user-images.githubusercontent.com/3506166/84091418-2e534e00-a9a9-11ea-9df7-1e36189ecd6e.png)

- User made changes, primary is enabled
![image](https://user-images.githubusercontent.com/3506166/84091457-488d2c00-a9a9-11ea-88f7-2d61b8ee9226.png)

- User clicked primary, we replace the icon
![image](https://user-images.githubusercontent.com/3506166/84091624-dc5ef800-a9a9-11ea-9eef-dc98cbb07db5.png)

- At the end of the process we briefly show the check, we replace temporary the icon
![image](https://user-images.githubusercontent.com/3506166/84091718-192aef00-a9aa-11ea-8c17-9a72fce2d9ed.png)

/cc @bpatterson88

**Comment by macandcheese** [comment]
Yep - these are good enhancements.

> * User clicked primary, we replace the icon
>   ![image](https://user-images.githubusercontent.com/3506166/84091624-dc5ef800-a9a9-

For this one, you use the `loading` prop correct, and then replace the `primary-icon` with the "success check" before reverting back to the initial save icon?

**Comment by bstifle** [comment]
would like to get the outline version to look more like this

@macandcheese 

![image](https://user-images.githubusercontent.com/14083530/84198364-46ce7180-aa58-11ea-9519-fa6601b85da6.png)


i know we tried to avoid using non-buttons, but... the triple border is odd. can we achieve this with the button component?

**Comment by ffaubry** [comment]
@macandcheese My mistake. 
For:
![image](https://user-images.githubusercontent.com/3506166/84199136-7cc02580-aa59-11ea-8993-8f8244eb794a.png)
You are correct I meant to say 'set loading to true'

**Comment by macandcheese** [comment]
@bstifle likely not with just the components but we can probably fudge it in some way.

**Comment by bstifle** [comment]
awesome, thanks adam

**Comment by ffaubry** [comment]
@macandcheese additional thing about loading... 
I did not test but I would expect that the button is from an event standpoint of view disabled.
Not visually thou. 
I think that the disable visual state is not helping during these transitions.
Hopefully I'm making sense.
