### ISSUE TITLE
calcite-label enhancements

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#653]
When layout="inline":
- we need some padding/margin
- the label text should align with the other parts

Example of the issue:
![image](https://user-images.githubusercontent.com/3506166/84097337-23081e80-a9b9-11ea-9a5d-fdc7bea4d4e5.png)

I tried to wrap the label text in a <span> with no success.
/cc @bpatterson88

**Comment by macandcheese** [comment]
Hi @ffaubry - what does the markup look like for this? You should be seeing something like:

<img width="238" alt="Screen Shot 2020-06-08 at 11 00 33 PM" src="https://user-images.githubusercontent.com/4733155/84111491-e6015380-a9db-11ea-9b15-b0768adbb036.png">

There is also `inline-space-between` as an option for `layout` which should push the label and the control to opposite edges of the container.

**Comment by ffaubry** [comment]
You can reproduce by simply going there:
https://esri.github.io/calcite-components/?path=/story/radio-group--wrapping-calcite-label
Edit the html directly:
![image](https://user-images.githubusercontent.com/3506166/84161066-b83ffd00-aa23-11ea-8b5d-2102cecb7bb3.png)
Set the layout to 'inline'
You will get this:
![image](https://user-images.githubusercontent.com/3506166/84161125-cbeb6380-aa23-11ea-8b74-c9d34d7d972a.png)
Same issue.

**Comment by macandcheese** [comment]
Ah got it, yeah the padding only seems to be applying if there is "room to spare" horizontally in the container. Will 👀

**Comment by macandcheese** [comment]
@ffaubry - the label spacing was resolved : https://github.com/Esri/calcite-components/pull/876, I am submitting a PR for the alignment issue ( in this case the radio-group had margin-top which is no longer needed since the label includes it)
