### ISSUE TITLE
Navigation Component

### ISSUE THREAD

**Issue by yelenakreyndel** [Esri/calcite-components#6531]
### Description

Implement Navigation component per design prototype: http://calcite-dev.esri.com:3001/demos/nav.html  and spec: https://www.figma.com/file/6GrtrMONiH13kk9DeJtIMd/Design-Specs?node-id=157%3A2032&t=nLLbnXFvznVkZnqR-1 

### User Stories

High priority for March

### Acceptance Criteria

Design specifications and interaction behavior demonstrated in a prototype are followed

### Relevant Info

For questions about Navigation component interaction behavior, contact @macandcheese. For Figma spec questions, please contact @ashetland. 

### Esri team

Calcite (dev)

**Comment by yelenakreyndel** [comment]
New issue is created and assigned to @anveshmekala. Cc'ing @jcfranco, @geospatialem, @macandcheese

**Comment by yelenakreyndel** [comment]
@anveshmekala I invited you to the file. Try accessing from email link if this one doesn't work: https://www.figma.com/file/6GrtrMONiH13kk9DeJtIMd/Design-Specs?node-id=157%3A2032&t=nLLbnXFvznVkZnqR-1 (I updated the url in the description as well).

**Comment by geospatialem** [comment]
Reallocated to the April milestone.

**Comment by geospatialem** [comment]
Migrating to the May milestone for additional testing.

**Comment by geospatialem** [comment]
Verified on `master` with `nav-logo`, `nav-user`, `menu` and `menu-item`.

cc @ashetland @SkyeSeitz for Figma changes.
