### ISSUE TITLE
Transition to a monorepo

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#6532]
### Background

Several initiatives would benefit from being a monorepo and would also allow the component environment to be updated much more easily than if dependent packages were kept separately.

### Related issues

* https://github.com/Esri/calcite-components/issues/6305
* https://github.com/Esri/calcite-components/issues/6117

### Desired Outcome

To convert this repo into a monorepo and host the following packages (subject to change):

* React wrappers
* Framework examples
* Custom ESLint plugin
* Design tokens
* Icons (potentially)
* Component utils (future)
* Test utils (future)
* Demos (future)

**Comment by benelan** [comment]
## Status update

- I have been setting up the monorepo in [a fork](https://github.com/benelan/calcite-monorepo)
- We are using [turbo repo](https://turbo.build/) to manage our pipelines
- Added CCR to the monorepo and the turbo `build` pipeline is complete (running `turbo build` builds CC and then CCR using the locally built CC)
- We use the deprecated `standard-version` package for versioning and changelog generation and they recommend switching to `release-please`, which creates PRs for releases and [supports monorepos using manifests](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md).
  - Unfortunately, release-please doesn't work well with pre-releases and monorepos, see: 
    - <https://github.com/googleapis/release-please/issues/510>
    - <https://github.com/googleapis/release-please/issues/1355>
  - I will probably continue using standard-version for our pre-releases until release-please resolves those issues.
  - [`release-please-action` is setup](https://github.com/benelan/calcite-monorepo/blob/release-please/.github/workflows/release-please.yml) and partially working for non-pre-releases - [generating prs](https://github.com/benelan/calcite-monorepo/pull/2) and [creating GH releases](https://github.com/benelan/calcite-monorepo/releases/tag/calcite-components-v1.3.1) after merging the PR.

## Next steps

My tasks

- Make sure CCR releases with the bumped CC version even if there are no changes to the CCR code. 
  - The [`node-worskpace` plugin](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#node-workspace) is setup and should be doing this, but it uses lerna so it may not understand how turbo does things. 
  - The [`linked-versions`](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#linked-versions) plugin may be a potential backup option, although I'm not sure if it works on local packages.
- Bump the CDN version in the CC readme using the [generic updater](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files).
- Test and internally document the workflow for [updating changelog entries post-merge](https://github.com/googleapis/release-please#how-can-i-fix-release-notes).
- Modify our existing `next` release CI to also release CCR
- Split out storybook into a separate package
- Split out the demos into a separate package

@alisonailea's tasks (let me know if I missed anything)

- Add the design-tokens as a package
- Split out eslint into a separate package
- Split out tsconfig into a separate package

**Comment by geospatialem** [comment]
Reallocating to the upcoming May release.

**Comment by geospatialem** [comment]
Once the May release is stabilized, the monorepo transition work will be installed.

**Comment by geospatialem** [comment]
Verified in `master`. 🙌🏻 🏆
