### ISSUE TITLE
Empty Set Placeholder Component 

### ISSUE THREAD

**Issue by yelenakreyndel** [Esri/calcite-components#6535]
### Description

@mitc7862 , please provide a description. 

### User Stories

@mitc7862 - please provide user stories

### Acceptance Criteria

@mitc7862 - please provide info

### Relevant Info

Initial for MV, should incorporate / migrate from Hub Components

### Esri team

Calcite (design)

**Comment by yelenakreyndel** [comment]
Design work is assigned to @mitc7862 and @asangma. Design needs to be complete by May for implementation to be complete in September.

**Comment by geospatialem** [comment]
Closing in favor of #6133
