### ISSUE TITLE
List: allow clicking on group names to expand/collapse 

### ISSUE THREAD

**Issue by ade10176** [Esri/calcite-components#6546]
### Description

Currently users have to click on the caret to expand/collapse the group name and see the nested items https://codepen.io/nwhittaker-esri/pen/bGxeMVq

### Acceptance Criteria

Allow users to click on the group name in addition to clicking on the caret to expand/collapse and see the nested items

### Relevant Info

Similar to https://github.com/Esri/calcite-components/issues/6444 for trees.

### Which Component

List

### Esri team

ArcGIS Field Apps

**Comment by macandcheese** [comment]
@geospatialem this could probably be closed and combined with https://github.com/Esri/calcite-components/issues/6444

**Comment by brittneytewks** [comment]
Research needed prior to list slotted for July

**Comment by geospatialem** [comment]
> I don't think we can do this one since we need to follow rules for the aria tree-grid role. The group name is reserved for selection.

The `list` component's recent refactor to support accessibility doesn't support allowing the `list-item` component to be expanded/collapsed.

If the request is vital to a workflow, perhaps we can schedule a separate meeting to discuss alternatives, or a future new component which could support a workflow.

Closing out the original issue as its not feasible with the `list` or `list-item` component as they are built and supported currently.
