### ISSUE TITLE
[List and List Item] Support List Item closed functionality

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6555]
### Description

Add full parity to the `list` component, which is provided in the `value-list` and `pick-list` components.

Children should not be destroyed, or removed as part of the effort.

### Acceptance Criteria

- [x] Closed functionality of `list-item`s
   - [x] Mouse and keyboard support
   - [x] Keyboard support when screen readers are active for both Windows (NVDA, JAWS) and Mac (VoiceOver) users

### Relevant Info

Part of the https://github.com/Esri/calcite-components/issues/6430 epic

### Which Component

- List
- List Item

### Example Use Case

Depicted with `value-list` and `value-list-item`: 
https://codepen.io/geospatialem/pen/abjxWwL

### Esri team

Calcite (dev)

**Comment by driskull** [comment]
@jcfranco It seems like a user would be best to specify the action for removal and handle removing the element. Otherwise, we may need to get into creating a `beforeRemoval` callback incase some async thing needs to happen. Even an undo UI.

With the list, the user manages the DOM elements. It might not be best for us to be removing DOM elements.

We might want to discuss a pattern for when removing DOM elements that are not in a shadowRoot is okay.

**Comment by geospatialem** [comment]
Will be consulting the team on a pattern prior to any work to determine next steps.

**Comment by geospatialem** [comment]
@jcfranco We're exploring closed functionality based on group discussions on 4/11, rather than removable/destroyed children in the DOM. WDYT about the proposed functionality and approach?

cc @driskull

**Comment by geospatialem** [comment]
Verified in `1.3.0-next.7` with the following example:

```html
<calcite-list selection-mode="single" label="test" filter-enabled>
    <calcite-list-item closable label="test1" value="test1" description="hello world 1">
      <calcite-icon icon="banana" slot="content-start" style="color: var(--calcite-ui-success)"></calcite-icon>
      <calcite-action appearance="transparent" icon="ellipsis" text="menu" label="menu" slot="actions-end"></calcite-action>
    </calcite-list-item>
    <calcite-list-item closable label="test2" value="test2" description="hello world 2">
      <calcite-icon icon="compass" slot="content-start" style="color: var(--calcite-ui-success)"></calcite-icon>
    </calcite-list-item>
    <calcite-list-item closable label="test3" value="test3" description="hello world 3">
      <calcite-icon icon="compass" slot="content-start" style="color: var(--calcite-ui-success)"></calcite-icon>
    </calcite-list-item>
    <calcite-list-item closable disabled label="test4" value="test4" description="hello world 4">
      <calcite-icon icon="compass" slot="content-start" style="color: var(--calcite-ui-success)"></calcite-icon>
    </calcite-list-item>
    <calcite-list-item closed closable disabled label="test5" value="test5" description="hello world 5">
      <calcite-icon icon="compass" slot="content-start" style="color: var(--calcite-ui-success)"></calcite-icon>
    </calcite-list-item>
  </calcite-list>
```
