### ISSUE TITLE
Design token integration

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6558]
### Description

Integrate design tokens into the CC repo. ✨ 

cc: @jcfranco 

### Acceptance Criteria

- [x] Expose CSS props and z-index tokens to developers.
- [x] Ensure research from #2972 is upheld through the [Scale spacing table wiki page](https://github.com/Esri/calcite-components/wiki/Scale-Spacing-Table)

### Relevant Info

Once completed, documentation pages should follow.

### Which Component

All components

### Esri team

Calcite (dev)

**Comment by alisonailea** [comment]
reopening until release

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.21` with https://codepen.io/geospatialem/pen/eYPPoBJ.
