### ISSUE TITLE
Dropdown for more advance UI enhancements

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#656]
First requirement is to be able to control when a dropdown should close. Two known use cases:
- a group with single or multi select and the user would like to click and see the effects on the application for apply one option or another. The user then close the dropdown by hitting escape or clicking outside the dropdown UI
- the dropdown doesn't show items in a group but rather a more advance UI (inputs, switchers, etc.) used for filtering data. Same scenario, the user would like to use different options and close the dropdown only with escape or click outside. In addition, the dropdown group could display a close button. In this use case, it is also possible that some UI may request to close the dropdown as well

Philosophically, we could use the Popover components but in many ways it's not really a dropdown and when we compose our UI, different buttons side by side some will behave as dropdown and some will behave as popover... We don't think this is an ideal UX/I and users will immediately notice differences. 

Related to #651 
/cc @bpatterson88

**Comment by macandcheese** [comment]
@ffaubry - can you post a screenshot of the "dropdown that's a little bit of a popover" - with the controls in it?

Ideally we can make them look visually the same, because what you mention is valid when a popover is invoked next to a dropdown, but keep the dropdown for "dropdown item / group" use cases.

We are planning on updating dropdown to use Popper so that may be an opportunity to make sure all styling is consistent. Thanks!

**Comment by bpatterson88** [comment]
I think @ffaubry has this UI in mind.
![Screen Shot 2020-06-09 at 4 28 52 PM](https://user-images.githubusercontent.com/15875886/84210897-d121d000-aa6e-11ea-90c9-4af1fee9b3e7.png)

Agree that it would be nice to have parameters for close, maybe something like this:
- Press `Esc` to close (true/false)
- Click outside to close (true/false) (implemented by https://github.com/Esri/calcite-components/issues/509?)
- Block close event if {{conditions}} aren't met (i.e validation)

The only visual discrepancy I see between dropdown/popover is the animation on the dropdown, which is pretty slick. It'd be nice to have on the popover.

**Comment by macandcheese** [comment]
Cool, thanks. Currently both esc and click outside close. Not sure if there are accessibility issues with not letting esc always close?

Re: design, yeah I think a good solution is to add our animation etc to the popover with the same fixed widths we provide with s/m/l for dropdown. The design above definitely seems like more of something to place in a popover vs. a dropdown item in a dropdown menu, IMO
