### ISSUE TITLE
[accordion-item] Doc actions-start/end slots

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#6561]
### Description

Stems from https://github.com/Esri/calcite-components/issues/2884#issuecomment-1454349330.

Both `actions-start` and `actions-end` slots are missing from [`accordion-item`'s doc](https://github.com/Esri/calcite-components/pull/4958).

### Which Component

`accordion-item`

### Resources

https://github.com/Esri/calcite-components/pull/4958

**Comment by macandcheese** [comment]
We could add an additional sample to show recommended pattern / expected use case for these slots as well cc @geospatialem
