### ISSUE TITLE
Action: icon aligned at end overlaps with indicator .

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#6568]
### Actual Behavior

When the icon is aligned to the end of the action with text-enabled turned off, it overlaps with the indicator icon. 

![C446887F-B595-4369-8401-08A7C0D42533_4_5005_c](https://user-images.githubusercontent.com/88453586/223192847-c07a722e-b28a-4896-a3c2-dc35c115bee0.jpeg)

### Expected Behavior

The icon shouldn't be overlapping with indicator icon.

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/JjayyWX?editors=100

### Reproduction Steps

1. Observe the first calcite-action in the codepen with no text overlaps with indicator icon.
2. The second calcite-action with text-enabled with indicator icon has no overlap.

### Reproduction Version

1.0.7

### Relevant Info

This issue could be related to #5860

### Priority impact

p3 - not time sensitive

### Esri team

N/A

**Comment by ashetland** [comment]
I think this is a byproduct of a funky/invalid configuration. If we look at it in the context of an Action Bar, when collapsed, the indicator placement is correct. 
<img width="304" alt="CleanShot 2023-05-02 at 10 31 09@2x" src="https://user-images.githubusercontent.com/108549080/235740917-6af09b85-6112-4f8a-9f3a-51e9bb10f7d7.png">
<img width="304" alt="CleanShot 2023-05-02 at 10 30 57@2x" src="https://user-images.githubusercontent.com/108549080/235740936-37499627-a8be-4755-98f4-a9d765e1894c.png">

**Comment by geospatialem** [comment]
Awesome, thank you both. Will close this issue out per [Aaron](https://github.com/Esri/calcite-components/issues/6568#issuecomment-1531873597) and [Skye](https://github.com/Esri/calcite-components/issues/6568#issuecomment-1532025967)'s notes above.
