### ISSUE TITLE
Child list-items do not appear in filter results

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#6574]
### Actual Behavior

Matching children are absent from a `<calcite-list>` element's filtered results.

### Expected Behavior

Matching children are present in a `<calcite-list>` element's filtered results.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/bGxeMVq

### Reproduction Steps

1. Visit the sample
2. Expand the **Rivers** list-item to see its child list-item named **Estuaries**
3. Type "Estuaries" into the list's filter input

### Reproduction Version

1.0.8

### Priority impact

p2 - want for current milestone

### Impact

A blocker for migrating the Field Map web app to use a `<calcite-list>` element for managing lists of nested layers.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
Verified in `1.4.1-next.2`

![image](https://github.com/Esri/calcite-components/assets/5023024/0c8cb69c-5161-4288-aaee-8a5fd301d474)
