### ISSUE TITLE
calcite-label + calcite-button focus issue

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#6576]
### Actual Behavior

If a calcite-label contains 2 calcite-buttons and I click on the second button the first one gets the focus.

### Expected Behavior

Focus stays on second button.

### Reproduction Sample

https://codepen.io/afreitag/pen/yLxPBPy

### Reproduction Steps

1. open codepen
2. click on second button with the code icon
Notice that if you do this inside a calcite-label the focus jumps to the first button.

### Reproduction Version

1.0.8

### Regression?

don't think so

### Priority impact

p3 - want for upcoming milestone

### Impact

medium

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Possible duplicate: https://github.com/Esri/calcite-components/issues/5070 to address with research.

**Comment by jcfranco** [comment]
@geospatialem Can confirm, this is a duplicate of #5070.

**Comment by geospatialem** [comment]
Closing in favor of #5070
