### ISSUE TITLE
TriStateCheckbox

### ISSUE THREAD

**Issue by Elhazard** [Esri/calcite-components#6584]
### Description

I want a checkbox that can display 3 types of state when click on the component.

You can see the example from this url

https://www.primefaces.org/showcase/ui/input/triStateCheckbox.xhtml?jfwid=0916f

### User Stories

Sometimes , we have to create custom treecheckbox that parent checkbox can display 3 types of state (Checked - When child checkbox are all checked, Half-Checked - When some child checkbox are checked , Unchecked - When child checkbox are all unchecked)

### Acceptance Criteria

Just like the example from Prime NG 

### Esri team

N/A

**Comment by ashetland** [comment]
The current Checkbox component includes unchecked, checked, and intermediate states. https://developers.arcgis.com/calcite-design-system/components/checkbox/

**Comment by geospatialem** [comment]
This came up at DevSummit, where the requestor is seeking different checkbox states when selecting the component. 

Should we consider as an enhancement to `checkbox`?

For instance:
![tristatecheckbox-example](https://user-images.githubusercontent.com/5023024/224505549-bdd639ab-1975-4514-a12b-cdfc64f5e719.gif)

**Comment by macandcheese** [comment]
You can currently set `indeterminate` programmatically but a user cannot reach that state themselves. Seems like a valid enhancement to have an opt-in for that behavior.

**Comment by macandcheese** [comment]
Checkbox already supports setting ‘indeterminate’ programmatically, is this proposing allowing a user to enter that state themselves?

**Comment by ashetland** [comment]
> Checkbox already supports setting ‘indeterminate’ programmatically, is this proposing allowing a user to enter that state themselves?

Suggest we close this issue unless we get an answer to this question.

**Comment by geospatialem** [comment]
@Elhazard for context, would this fit the need, where the `indeterminate` prop could be set in the HTML, or be programmatically added to the component?

```html
<calcite-checkbox indeterminate></calcite-checkbox>
```

```js
document.querySelector("calcite-checkbox").toggleAttribute("indeterminate");
```

**Comment by geospatialem** [comment]
@Elhazard Wondering if the [above workflow](https://github.com/Esri/calcite-components/issues/6584#issuecomment-1568672466) would fit the need? 

Calcite doesn't plan to integrate as part of the design system, and will be closing out this issue at the end of the month.

**Comment by geospatialem** [comment]
Closing out this issue per the comments on [May 30](https://github.com/Esri/calcite-components/issues/6584#issuecomment-1568672466) and [June 15](https://github.com/Esri/calcite-components/issues/6584#issuecomment-1593638258). The issue can be reopened if the workflow above doesn't fit the need and additional context is provided to the issue.
