### ISSUE TITLE
Dropdown Item have a too restrictive algo for parsing href

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#659]
We are generating href like `//foo.com`.
Dropdown item doesn't recognize the href as a valid URL and doesn't behave as a link.
Note that the `//` is a totally valid way of letting the scheme be determined by the scheme of app.

The reason why we don't enforce a scheme is because despite Online going full https, it is still possible to install an enterprise portal under http only. 
We need to account for the app running under http only versus https.

**Comment by macandcheese** [comment]
Hey @ffaubry - we don't actually parse the href in any way, we spread it directly to the rendered child `a`. Both of the following result in links for me: 
```
<calcite-dropdown>
  <calcite-button slot="dropdown-trigger">Open a dropdown full of links</calcite-button>
  <calcite-dropdown-group selection-mode="none" group-title="These are links">
    <calcite-dropdown-item href="//foo.com">Go to Foo</calcite-dropdown-item>
    <calcite-dropdown-item href="//foo.com" target="_blank">Go to Foo</calcite-dropdown-item>
  </calcite-button-group>
</calcite-dropdown>
```

(Note, it will render as `a` with any `selection-mode` value)

**Comment by ffaubry** [comment]
This is what I'm getting:
![image](https://user-images.githubusercontent.com/3506166/84675251-d5237700-aee0-11ea-9525-009c45c9ced1.png)

This is my template:
```
      <calcite-dropdown-group selection-mode="none">
        <calcite-dropdown-item href={{this.homeLink}}>{{t "home"}}</calcite-dropdown-item>
        <calcite-dropdown-item href={{this.contentLink}}>{{t "content"}}</calcite-dropdown-item>
        <calcite-dropdown-item href={{this.organizationLink}}>{{t "organization"}}</calcite-dropdown-item>
      </calcite-dropdown-group>
```

???

**Comment by macandcheese** [comment]
Note - based on chat with @ffaubry we may need to `@Listen()` for href attribute updates and then re-spread attributes to the rendered. Ember / Glimmer do not populate attributes on first paint.
