### ISSUE TITLE
calcite-list missing slot for menu-action like calcite-pick-list

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#6600]
### Actual Behavior

In order to move from pick-list to list we need a way to add a menu-action like shown below.

![image](https://user-images.githubusercontent.com/44481292/225129562-cd7c2ea2-1801-4a08-859c-5422a4d41299.png)![image](https://user-images.githubusercontent.com/44481292/225129638-9651b83b-2951-4b4d-a0e0-74a6c10ac737.png)

### Expected Behavior

menu-action slot like pick-list

### Reproduction Sample

https://codepen.io/afreitag/pen/WNgzWee

### Reproduction Steps

Open codepen and compare the 2 lists.

### Reproduction Version

1.0.8

### Priority impact

p3 - want for upcoming milstone

### Impact

Needs to happen before pick-list gets removed.

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Will consider a `filter-menu-options` slot for the `list` component when a filter is present on the component.

**Comment by driskull** [comment]
@jcfranco should this slot be built into the filter component? The current slot name "menu-actions" doesn't really work in the context of the list but could work in the context of the filter. We would need a better slot name for the list.

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.9` with the following [Codepen](https://codepen.io/geospatialem/pen/oNQWEWE).

![image](https://github.com/Esri/calcite-components/assets/5023024/0d840ee1-21bd-4ff5-a568-99f6f935b1ab)
