### ISSUE TITLE
i18n Numbering Systems Testing: Issue with group separator

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6607]
### Actual Behavior

In the Calcite input component:

With the locale `"ar-SA"` and the `numberingSystem` `"arab"`, the numbers change from `arab` to `latn` after typing 5 numbers consecutively, like `"12345"`.

via Ben:
> "It looks like it is because of the group separator"

### Expected Behavior

The numbers in the input to remain in the `arab` numbering system.

### Reproduction Sample

https://codepen.io/ainermfc/pen/KKeWoOg

### Reproduction Steps

1. Set the locale to `"ar-SA"`
2. Set the `numberingSystem` to `"arab"`
3. Set `dir` to `"rtl"`
4. Add `groupSeparator`
5. Type more than 5 digits into the input

### Reproduction Version

1.0.0-beta.97

### Relevant Info

Spurred from #5920, which had two distinct issues. cc @annierm18 @benelan 

### Regression?

v1.0.0-beta.97

### Priority impact

p3 - not time sensitive

### Esri team

N/A

**Comment by benelan** [comment]
Looks like @anveshmekala fixed this issue in #7173 :trophy: 

Verified in `next` using the repro sample above.

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.4`.
