### ISSUE TITLE
calcite-tooltip: tooltip lingers after mouse leaves the window

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#6615]
### Actual Behavior

If the user moves their mouse out of the window with the tooltip open, the tooltip will stay open until the user stops moving their mouse in the window, even if the mouse is no longer over the reference element

### Expected Behavior

The tooltip closes immediately, either when the user's mouse leaves the window, or when it is back in the window but not hovering over the tooltip reference element

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/tooltip/

### Reproduction Steps

1. Open sample in codepen
2. Shrink window so there's space to move the mouse outside of it
3. Hover mouse over the reference element
4. Move mouse out of the window quickly, see tooltip stays open
5. Move mouse back into the window, see tooltip stays open until the mouse stops moving

### Reproduction Version

1.10

### Relevant Info

Reproducible on both Mac & Windows

https://user-images.githubusercontent.com/5892789/226350483-e6d0df02-7bc8-4dad-bace-238258df4b38.mov

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Online

**Comment by jcfranco** [comment]
@geospatialem I can repro with your codepen on Chrome. 

This could be related to https://github.com/Esri/calcite-components/issues/6278.

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.6` in Chrome and Firefox browsers.

![verify-tooltip-close-leave-window](https://user-images.githubusercontent.com/5023024/235985231-8c0f9a2d-7e55-4677-8ad5-d186be033bdd.gif)
