### ISSUE TITLE
form validation not honored in Safari

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#6626]
### Actual Behavior

Safari submits forms via `submit` instead of `requestSubmit`, [skipping browser validation](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit#usage_notes).

### Expected Behavior

All form submitting uses `requestSubmit` for consistency.

### Reproduction Sample

https://codepen.io/jcfranco/pen/oNPaezj?editors=1001

### Reproduction Steps

1. click on the input
2. hit enter
3. notice form submits even though the input is required

### Reproduction Version

1.0.8

### Relevant Info

This was introduced by https://github.com/Esri/calcite-components/pull/4815.

### Regression?

1.0.0-beta.83

### Priority impact

p1 - need for current milestone

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `1.1.1-next.1`

![verify-input-required](https://user-images.githubusercontent.com/5023024/227050027-16c8965a-b82b-487e-9069-76b6fa78ed13.gif)
