### ISSUE TITLE
[Block] Icon in slot="icon" vertically misaligned

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6627]
### Actual Behavior

There is a misalignment in Block when icon is slotted into the "icon" slot. This isn't the case in Figma so opening as bug. Happens with or without other slotted content, open / not open, and with / without description.

![Capture-2023-03-21-165533](https://user-images.githubusercontent.com/4733155/226768824-abe98b5a-79d9-4ade-8d1b-7769e95f495b.png)

![Capture-2023-03-21-165552](https://user-images.githubusercontent.com/4733155/226768817-700de746-9888-4fc8-9f58-63efe0c44989.png)

![Capture-2023-03-21-170557](https://user-images.githubusercontent.com/4733155/226768929-2930af28-5606-4122-a7eb-d2841f3f67fb.png)

### Expected Behavior

I'd expect the icon to be vertically centered in the block header component.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/block/

### Reproduction Steps

1. Open doc site link
2. See visual misalignment
3. Panic

### Reproduction Version

1.1.0

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified on `1.4.0-next.7`
