### ISSUE TITLE
Slider Inactive State

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#663]
![image](https://user-images.githubusercontent.com/821864/84693470-6227f980-aefc-11ea-8396-5aade6a391b5.png)

Allow slider to have an inactive state. Handle and value is previewed on hover and added to the rail on click.

**Comment by eriklharper** [comment]
Bryan's proposed solution to address this issue without adding new slider code:
![image](https://user-images.githubusercontent.com/821864/85798235-fad72a00-b6f1-11ea-9a03-fe486bb94696.png)

**Comment by macandcheese** [comment]
This was addresed in #680 ✨
