### ISSUE TITLE
DatePicker , TH locale , when select the year is always incremented by 543

### ISSUE THREAD

**Issue by Elhazard** [Esri/calcite-components#6636]
### Actual Behavior

Get the example from this https://github.com/Esri/calcite-components/issues/6585

When using TH locale in which year will be Buddhist era (A.D. + 543),  try selecting some date in the calendar, the year is always incremented by 543.

![image](https://user-images.githubusercontent.com/8869519/227135530-4a8af38e-626e-426b-8b43-729aa3fd8ab1.png)
![image](https://user-images.githubusercontent.com/8869519/227136365-19781bcf-16bb-4495-b7ab-76b082fe7152.png)

### Expected Behavior

Year should not be incremented by 543 every time users select new date. 

### Reproduction Sample

https://codepen.io/geospatialem/pen/GRXyLJK

### Reproduction Steps

1. Click on the date picker to open calendar
2. Click any date on the calendar
3. The year will be incremented by 543.

### Reproduction Version

1.0.7

### Relevant Info

Occured in all browser such as Firefox, Edge, Chrome

### Priority impact

p3 - want for upcoming milestone

### Impact

Really buggy so we cannot use datetime picker in our application. Need to find another component

### Esri team

N/A

**Comment by benelan** [comment]
@annierm18 can we have i18n guidance on this issue?

**Comment by annierm18** [comment]
@benelan The Thai Buddhist calendar is 543 years ahead of CE, so the year 2023 CE corresponds to 2566 in the Thai Buddhist calendar. That said, the difference of 543 should just be applied once in the code in order to display the calendar correctly and should not be applied every time the user selects a year. Please let me know if you have follow-up questions on this

cc: @spuckdee @babakbolour

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.18` with the [original Codepen](https://codepen.io/geospatialem/pen/GRXyLJK).

**Comment by Elhazard** [comment]
Thank you very much for resolving this problem.
