### ISSUE TITLE
DataGrid-Toolbar

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-components#6647]
### Description

The Data Grid component needs a common UI pattern for toolbar actions around a data grid. This can be provided in the form on a `<calcite-datagrid-toolbar></calcite-datagrid-toolbar>`. This component should have slots for "start", "end", and "center". And use the flexbox spec to lay out its children.

### User Stories

Most table patterns at Esri include related elements like buttons and a search bar which update the related table. A custom component will allow for normalization of common patterns and accessibility best practices while still allowing for customization based on the needs of a specific app team.

### Acceptance Criteria

Component has the name "calcite-datagrid-toolbar"
Component as three slots
- start
- end
- center
Component can be dropped into the "toolbar" slot of a "calcite-datagrid"
component is keyboard accessible

### Relevant Info

Epic: #1574

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (dev)

**Comment by macandcheese** [comment]
Why does this need to be a separate component and not just slots available on the table component itself?

**Comment by macandcheese** [comment]
cc @mitc7862  - We'll need to evaluate this during design as additionally there is the "selected items" display UI and associated slotted content which will need to work in tandem with any content slotted in this way.

**Comment by alisonailea** [comment]
> Why does this need to be a separate component and not just slots available on the table component itself?

Because the HTML table should be related to but can not contain the toolbar elements as they are not tabular data. This is a special header component that relates to the table but is a sibling element.

**Comment by alisonailea** [comment]
> We'll need to evaluate this during design as additionally there is the "selected items" display UI and associated slotted content which will need to work in tandem with any content slotted in this way.

selected attributes should be set on the parent component. I'm assuming these will eventually include 
- selectedRows
- selectedColumns
- selectedCells

**Comment by macandcheese** [comment]
> > Why does this need to be a separate component and not just slots available on the table component itself?
> 
> Because the HTML table should be related to but can not contain the toolbar elements as they are not tabular data. This is a special header component that relates to the table but is a sibling element.

Sure, but we could render the slotted content adjacent to the table element internally, which seems to align with existing components:  we offer `slot="footer"` on Panel, not expose `<panel-footer>` components. For example, having a "footer-actions-start", "footer-actions-end", "header-actions-start", "header-actions-end". 

> selected attributes should be set on the parent component. I'm assuming these will eventually include...

Yep, totally. I'm referring to the UI provided around the table that enables a set of actions / slotted controls. Carbon example:
<img width="599" alt="Screen Shot 2023-03-23 at 10 07 11 AM" src="https://user-images.githubusercontent.com/4733155/227595397-0dbc63b4-75cf-4a68-a4b7-f0d386f42e97.png">

This could be accomplished a few ways but I was thinking more along the lines of "selection-actions-start / end" as we will need to position whatever actions are slotted amongst our own UI

**Comment by alisonailea** [comment]
Requires design input @macandcheese @mitc7862

**Comment by alisonailea** [comment]
Closing in favor of using just the "toolbar" slot as discussed with @macandcheese .
See #6648 for more information.
