### ISSUE TITLE
[Input Date Picker] Add keyboard trap to Date Picker component

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6668]
### Description

Add in keyboard trapping so assistive technology (AT) users can cycle through the different options, ensuring they know the full extent of the dialog and what's available to them.

Spurred from https://github.com/Esri/calcite-components/issues/5582

### Acceptance Criteria

Add keyboard trapping to `date-picker`, where users can close the dialog using the `Esc` key.

### Relevant Info

https://github.com/Esri/calcite-components/issues/5582

### Which Component

`input-date-picker` and `date-picker`

### Priority impact

p2 - want for current milestone

### Esri team

Calcite (dev)

**Comment by jcfranco** [comment]
Waiting on #6773 to address some concerns mentioned ☝️.

**Comment by geospatialem** [comment]
Verified in `1.3.0-next.13` on Mac and Windows.
