### ISSUE TITLE
[calcite-input] Add prop to disable component

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#667]
Currently, there is no way to disable inputs without custom code. 

cc @macandcheese

**Comment by macandcheese** [comment]
Roger 🤙

**Comment by macandcheese** [comment]
Thoughts on having a disabled prop on `calcite-label` in addition to one on `calcite-input` that could be inherited by `calcite-input` but also by any wrapped controls?

If so should there by a styling adjustment for disabled items (would need to be distinct from readOnly)

**Comment by jcfranco** [comment]
My 2 cents: I wouldn't expect label to have a disabled prop.
