### ISSUE TITLE
[Flow] Responsive layout

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6676]
### Description

Mobile responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

### Acceptance Criteria

- [ ] 1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
- [ ] 2. Components need to be designed for the following breakpoints:
    - [ ] Small (s), `476px`
    - [ ] Medium (m), `768px`
    - [ ] Large (l), `1152px`
    - [ ] Extra larger (xl), `1440px`

### Relevant Info

Part of epic https://github.com/Esri/calcite-components/issues/6670

### Which Component

`flow`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
Update from team discussion today:
We determined that Flow does not need enhancements under the responsive layout initiative as its footer contents have enough room at all breakpoints and its header already includes an action-slot for overflow action items. 

@geospatialem Can we close this issue out for the reasons above? Thanks!

**Comment by geospatialem** [comment]
Closing this out per the note above ☝🏻
