### ISSUE TITLE
Clicking a radio button label flashes focus on the group's first radio button

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#6698]
### Actual Behavior

Given a radio button group with no descendants in focus, mouse down on any of the group's radio button labels except the first. While the mouse button is down, focus is given to the group's first radio button.

<img width="168" alt="Screenshot 2023-03-29 at 12 12 15 PM" src="https://user-images.githubusercontent.com/421496/228603443-3a5c6477-dead-450f-8ea3-142571279a4a.png">

### Expected Behavior

Given a radio button group with no descendants in focus, mouse down on any of the group's radio button labels except the first. While the mouse button is down, focus is given to the radio button associated with the label that the mouse is on top of.

<img width="168" alt="Screenshot 2023-03-29 at 12 22 05 PM" src="https://user-images.githubusercontent.com/421496/228604930-48ebd19d-2d66-4a46-af05-8de3e325fb6d.png">

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/radio-button-group/

### Reproduction Steps

1. Visit the doc site and scroll to the **Sample** section.
2. Mouse down on the _Bushes_ label and see focus is given to the _Trees_ radio button instead of the _Bushes_ radio button.

### Reproduction Version

1.2.0-next.0

### Relevant Info

macOS 13, Chrome 111.

### Priority impact

p4 - not time sensitive

### Impact

Could lead to brief user confusion about what radio button they're actually clicking.

### Esri team

ArcGIS Field Apps

**Comment by geospatialem** [comment]
@anveshmekala What would you estimate the time needed to accomplish a fix for the above issue?

**Comment by geospatialem** [comment]
Verified with `1.5.0-next.4`.
