### ISSUE TITLE
`calciteRadioButtonGroupChange` event not appearing on doc site

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#6699]
### Description

The `calcite-radio-button-group` component has a `calciteRadioButtonGroupChange` event but it doesn't appear on https://developers.arcgis.com/calcite-design-system/components/radio-button-group/.

### Which Component

calcite-radio-button-group

### Resources

It is mentioned in the `calcite-radio-button` documentation for the `calciteRadioButtonChange` event:

>Fires only when the radio button is checked. This behavior is identical to the native HTML input element. Since this event does not fire when the radio button is unchecked, it's not recommended to attach a listener for this event directly on the element, but instead either attach it to a node that contains all of the radio buttons in the group or use the `calciteRadioButtonGroupChange` event if using this with `calcite-radio-button-group`.[^1]

[^1]: https://developers.arcgis.com/calcite-design-system/components/radio-button/#api-reference-events-calciteRadioButtonChange

**Comment by macandcheese** [comment]
@nwhittaker this is now available on the Developer site - thanks for reporting! - https://developers.arcgis.com/calcite-design-system/components/radio-button-group/#api-reference-events-calciteRadioButtonGroupChange
