### ISSUE TITLE
[slider] focus outline easily overlaps surrounding elements

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#673]
Is it by design that the slider's thumb outline extends way beyond  size? It's very noticeable when placed on a panel or has sibling elements:

<img width="297" alt="Screen Shot 2020-06-18 at 5 26 37 PM" src="https://user-images.githubusercontent.com/197440/85084307-42f1cc00-b189-11ea-8d2f-c64ecd215430.png">

<img width="281" alt="Screen Shot 2020-06-18 at 5 26 31 PM" src="https://user-images.githubusercontent.com/197440/85084305-42593580-b189-11ea-824d-94e654b0e508.png">

Related a11y question, is the outline necessary if the thumb has a focus state?

cc @paulcpederson @macandcheese @eriklharper

**Comment by macandcheese** [comment]
I believe in @eriklharper 's latest PR the size was reduced a good amount while still giving a little extra hitbox area to prevent misclicks / larger tap area for touch screens.

**Comment by eriklharper** [comment]
Correct.  It looks like this now 
![image](https://user-images.githubusercontent.com/821864/85147144-45910780-b203-11ea-9a2f-c2559c4fa012.png)

**Comment by jcfranco** [comment]
Excellent. I can close this once it's installed. Thanks!
