### ISSUE TITLE
Panel: remove `min-block-size:3rem` on the footer

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#6733]
### Description

It makes the small pagination not fit vertically centered.

### Acceptance Criteria

Panel: remove `min-block-size:3rem` on the footer

### Which Component

Panel

### Example Use Case

https://codepen.io/driskull/pen/dygbLqO?editors=100

### Priority impact

p3 - want for upcoming milestone

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.8`
