### ISSUE TITLE
Localization support for `de-AT`

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6737]
### Description

Provide support to the language, `German - Austria (de-AT)`, in particular with the `date-picker` component.

### Acceptance Criteria

- [ ] The `date-picker` component's month should be  set to `Jänner` (currently set to German value of `Januar`) for  `German - Austria (de-AT)` languages. - @annierm18
- [ ] Update [supported languages](https://developers.arcgis.com/calcite-design-system/resources/localization/#calcite-supported-languages) to include `German - Austria (de-AT)*` - @geospatialem 

### Relevant Info

Enhancement request

### Which Component

[`date-picker`](https://github.com/Esri/calcite-components/tree/master/src/components/date-picker/assets/date-picker/nls)

### Priority impact

p3 - want for upcoming milestone

### Esri team

N/A

**Comment by annierm18** [comment]
@geospatialem for this change, we can make a copy of this [de.json](https://github.com/Esri/calcite-components/blob/master/src/components/date-picker/assets/date-picker/nls/de.json) file, rename the copy to "de-AT", and then update the following two values:

1. In months.abbreviated: change "Jan" to "Jän"
2. In months.wide: change "Januar" to "Jänner"

**Comment by geospatialem** [comment]
Verified in `1.3.0-next.5` with the [following Codepen](https://codepen.io/geospatialem/pen/PoyNzgB).

**Comment by annierm18** [comment]
@geospatialem the distributor that requested this change tested it on the Codepen that you shared; he said the change looks good.
