### ISSUE TITLE
Panel - close button should always be in the corner and not before the menu actions.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#6742]
### Actual Behavior

A closable panel has the close button left of the actions menu.

https://developers.arcgis.com/calcite-design-system/components/panel/

### Expected Behavior

The close button is all the way to the corner.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/panel/

### Reproduction Steps

1. Go to https://developers.arcgis.com/calcite-design-system/components/panel/
2. Set the panel to closable
3. view

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1231455/230456453-dee77240-993a-42e1-892b-ef2e83d9d94c.png">

### Reproduction Version

1.2.x

### Priority impact

p2 - want for current milestone

### Esri team

N/A

**Comment by driskull** [comment]
@geospatialem can we get this triaged? I can take it.

**Comment by asangma** [comment]
➕
