### ISSUE TITLE
Create generic item layout component

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#6743]
### Description

Create generic item layout component

This component would have the following slots to allow users to layout content better...

- actions-start
- content-start
- DEFAULT content slot
- content-end
- actions-end

### User Stories

This will help users be able to layout content that is slotted within a panel footer for example. It will also allow a use to disable specific parts within the component if necessary since some parent components don't allow disabling partial UI.

### Acceptance Criteria

Name of component can be decided later.

### Relevant Info

- actions-start
- content-start
-(default slot) for cotent
- content-end
- actions-end

related to #5664

### Helpful Details

This would be able to emulate the layout of a calcite-panel header or a calcite-list-item 

```tsx
<calcite-layout-item>
<calcite-action text="select" icon="checkmark" slot="actions-start" />
<calcite-avatar slot="content-start" / >
My Content
<calcite-action text="delete" icon="trash" slot="actions-end" />
</calcite-layout-item>
```

### Priority impact

p2 - want for current milestone

### Esri team

N/A

**Comment by driskull** [comment]
cc @geospatialem @jcfranco can we get this triaged?

**Comment by macandcheese** [comment]
Does it complicate this unnecessarily to have a `layout-group` or parent by another name to wrap these `layout-item` component? That could control spacing / margin around the children, any potential alignment or orientation options, etc.

**Comment by driskull** [comment]
I'm not sure it needs a parent since this layout component since wherever its slotted should handle that.

**Comment by geospatialem** [comment]
> cc @geospatialem @jcfranco can we get this triaged?

@driskull You thinking for the May release?

**Comment by driskull** [comment]
yeah that sounds good

**Comment by geospatialem** [comment]
Verified on `master` with the demo pages, including use of the two CSS props: 
- `--calcite-stack-padding-inline` and
- `--calcite-stack-padding-block`

Example use:
```html
<calcite-panel>
  <div slot="header-content">Panel</div>
  <p>Content</p>
  <calcite-stack slot="footer">
    <calcite-action text="select" icon="check" slot="actions-start"></calcite-action>
    <calcite-input disabled></calcite-input>
    <calcite-avatar slot="content-start" thumbnail="http://placekitten.com/105/105" scale="s"> </calcite-avatar>
    <calcite-chip slot="content-end" value="chip" scale="s" appearance="outline">A chip</calcite-chip>
    <calcite-action text="delete" icon="trash" slot="actions-end"></calcite-action>
  </calcite-stack>
</calcite-panel>
```

**Comment by geospatialem** [comment]
cc @SkyeSeitz @ashetland for Figma changes.
