### ISSUE TITLE
[Shell Panel] Update `bottom-actions` slot name to more generic name

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6757]
### Description

The Action Bar has a `bottom-actions` slot for adding actions. This makes sense in `vertical` layout, but less so in `horizontal`. 

### Acceptance Criteria

Use a more generic slot name for this to better represent the placement in all layout types of Action Bar.

### Relevant Info

As mentioned in #6738.

### Which Component

Action Bar

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Closing in favor of https://github.com/Esri/calcite-components/issues/6517
