### ISSUE TITLE
[Action Bar] Improve border display when slotted in Panel's `action-bar` slot

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6758]
### Description

Brought up in https://github.com/Esri/calcite-components/pull/6738, when `bottom-actions` is populated and the Action Bar is in a Panel's `action-bar` slot, an undesired border is visible at the right extent of the Action Bar. Might be being set by the Shell Panel?

https://user-images.githubusercontent.com/4733155/230954220-b41f6e5d-4290-495f-b8a8-e9c4ef32fa78.mov

### Acceptance Criteria

There is no visible border at either edge of the Action Bar when slotted.

### Which Component

Shell Panel / Action Bar / Panel

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.7`
