### ISSUE TITLE
Lower opacity on Disabled Slider

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#676]
It is difficult to tell visually that the slider component is disabled. 
https://github.com/Esri/calcite-components/tree/master/src/components/calcite-slider

![image](https://user-images.githubusercontent.com/50747646/85183248-eb626780-b23f-11ea-864d-3edf990acc78.png)

@asangma suggested considering dropping the opacity  from 50% to 33%

**Comment by asangma** [comment]
@macandcheese @bstifle @paulcpederson Any issues with this?

**Comment by paulcpederson** [comment]
Fine by me, I think we can get away with this because of [Section 1.4.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html)'s "Incidental" section (emphasis mine):

> Text or images of text that are part of an **inactive user interface component**, that are pure decoration, that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement.

However, I would go a step further, and say that disabled sliders should also be gray, not blue for the active parts. We should also ensure we're setting the `disabled` prop and `cursor: not-allowed` in this state.

**Comment by macandcheese** [comment]
Agree we can make it Grey as well as lower opacity and change cursor. Currently every other disabled element gets a 0.4 opacity value. Would that work in conjunction with changing from blue to grey?

**Comment by asangma** [comment]
I'll make a draft PR, cool?

**Comment by bstifle** [comment]
Recommend making anything that is ui-blue to use blk-140  #6A6A6A for disabled.

**Comment by asangma** [comment]
@bstifle copy that.

**Comment by bstifle** [comment]
plus the 0.4 opacity like adam said!

**Comment by asangma** [comment]
`--calcite-ui-text-3` yeah

**Comment by asangma** [comment]
@paulcpederson re: `cursor: not-allowed`

This cursor change will only show if I remove `pointer-events: none` from `:host([disabled])`.
I can do that, but setting `pointer-events: none` on children, e.g. `*` seems ineffective.

**Comment by asangma** [comment]
@zaramatheson Lemme know if you need anything re: verifying.

**Comment by zaramatheson** [comment]
@asangma Looks good to me! Much clearer that it's disabled now.

**Comment by asangma** [comment]
@macandcheese Zara and Russ are cool with visual updates. Would you mind verfeeing?

**Comment by macandcheese** [comment]
LGTM ✅
