### ISSUE TITLE
Closed date picker popup requires tabbing out and back in to be reopened

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#6773]
### Actual Behavior

Closing a date picker via Escape force a user to tab outside and back into the component to display again.

### Expected Behavior

An affordance in the picker to toggle the popup (akin to combobox) and adding support to reopen on ⬇️ key press.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-date-picker/

### Reproduction Steps

1. Click sandbox above input
2. Press Tab
3. Picker popup opens
4. Press Escape
5. Picker closes

Once closed, the picker can no longer be opened unless users tab outside and back in

### Reproduction Version

1.2.0

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Design implementation will follow `combobox`. Routing to development. cc @ashetland @jcfranco

**Comment by ashetland** [comment]
cc @SkyeSeitz for Figma updates

**Comment by geospatialem** [comment]
Verified on `master` via mouse, keyboard and AT - Windows JAWS and NVDA. 

cc @SkyeSeitz @ashetland - once we're good on Figma changes, can close out the issue.

**Comment by ashetland** [comment]
Did the PR add anything to Input Time Picker or just Input Date Picker? This issue implies both, but I think the work I reviewed only included Input Date Picker.

**Comment by geospatialem** [comment]
> Did the PR add anything to Input Time Picker or just Input Date Picker? This issue title implies both, but I think the work I reviewed only included Input Date Picker.

@ashetland - Good catch. Refactored this issue to date-picker, and opened #6830 to tackle the time picker effort. The design should be the same for both components.

**Comment by geospatialem** [comment]
Figma changes are noted - closing out this issue.
