### ISSUE TITLE
Accessibility: change to aria-label in button used to trigger dropdown partially applied

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#678]
For a no-text calcite-button inside and used to trigger a calcite-dropdown, the aria-label appears in the button and the shadow-root. The NVDA screen-reader reads the shadow-root copy. If the aria-label is changed on the button, the button is updated but not the shadow-root copy. (This does not matter with a text calcite-button because the screen-reader reads the visible text.)

E.g., in the sample below, the dropdown has a radio group of three elements with the first element selected. When an element is selected, it becomes the active one and the aria-label for the calcite-button is changed to represent the current selection. Because the change is not percolated into the shadow-root, however, the screen-reader continues to read the original setting.

Elements at app startup; "Relevance" is selected:
![image](https://user-images.githubusercontent.com/2125181/85185846-a7289480-b24a-11ea-86e7-bbc946a49f98.png)

Elements after the "Title" item is selected:
![image](https://user-images.githubusercontent.com/2125181/85185861-c1fb0900-b24a-11ea-87ee-8a96405b1e59.png)

```html
<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" href="./css/calcite-web.min.css">
  <link rel="stylesheet" href="./css/calcite.css" type="text/css" />
  <script type="module" src="src/lib/calcite-components/calcite.esm.js" crossorigin="use-credentials"></script>
  <script nomodule src="src/lib/calcite-components/calcite.js"></script>
  <script>
    function handleClick(event) {
      var button = document.getElementById("dropdownBtn")
      button.setAttribute("aria-label", event.innerText);
    }
  </script>
</head>
<body style="padding:16px">
  <calcite-dropdown>
    <calcite-button id="dropdownBtn" slot="dropdown-trigger" appearance="transparent"
      icon="sort-descending" icon-position="start" color="blue" nohastext="" scale="m"
      aria-live="polite" aria-atomic="true" aria-label="Relevance"></calcite-button>
    <calcite-dropdown-group group-title="Sort by" selection-mode="single">
      <calcite-dropdown-item value="relevance" tabindex="0" role="menuitemradio" onclick="handleClick(this);"
        active aria-checked="true">Relevance</calcite-dropdown-item>
      <calcite-dropdown-item value="modified" tabindex="0" role="menuitemradio" onclick="handleClick(this);"
        notActive aria-checked="false">Date Modified</calcite-dropdown-item>
      <calcite-dropdown-item value="title" tabindex="0" role="menuitemradio" onclick="handleClick(this);"
        notActive aria-checked="false">Title</calcite-dropdown-item></calcite-dropdown-group>
  </calcite-dropdown>
</body>
</html>
```

**Comment by macandcheese** [comment]
Ah I think this is a case of us not updating the attributes on the rendered child element of `calcite-button` when they are changed on the `Host`... I don't think this is unique to the use case as the trigger for `calcite-dropdown`.

**Comment by MikeTschudi** [comment]
At calcite-components version 1.0.0-beta.46, the latest on [unpkg.com](https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.esm.js), continues to be an issue.

```html
<!doctype html>
<html lang="en" dir="ltr">
<head>
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.css" />
  <style>
  calcite-dropdown { outline: 1px solid blue; }
  </style>
  <script type="module" src="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.esm.js"></script>
  <script nomodule="" src="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.js"></script>
  <script>
    function handleClick(event) {
      var button = document.getElementById("dropdownBtn")
      button.setAttribute("aria-label", event.innerText);
    }
  </script>
</head>
<body style="padding:16px">
  <calcite-dropdown>
    <calcite-button id="dropdownBtn" slot="dropdown-trigger" appearance="transparent"
      icon="sort-descending" icon-position="start" color="blue" nohastext="" scale="m"
      aria-live="polite" aria-atomic="true" aria-label="Relevance"></calcite-button>
    <calcite-dropdown-group group-title="Sort by" selection-mode="single">
      <calcite-dropdown-item value="relevance" tabindex="0" role="menuitemradio" onclick="handleClick(this);"
        active aria-checked="true">Relevance</calcite-dropdown-item>
      <calcite-dropdown-item value="modified" tabindex="0" role="menuitemradio" onclick="handleClick(this);"
        notActive aria-checked="false">Date Modified</calcite-dropdown-item>
      <calcite-dropdown-item value="title" tabindex="0" role="menuitemradio" onclick="handleClick(this);"
        notActive aria-checked="false">Title</calcite-dropdown-item></calcite-dropdown-group>
  </calcite-dropdown>
</body>
</html>
```

**Comment by shoe913** [comment]
Still valid, @cosbyr, can we re-open?

**Comment by MikeTschudi** [comment]
still present @1.0.0-beta.57 with NVDA 2020.4

**Comment by driskull** [comment]
@eriklharper I think your changes should fix this issue right?

**Comment by eriklharper** [comment]
I believe so, yes, the change we made recently to `calcite-button` removes attribute spreading, so setting `aria-label` on the shadowRoot `<button>` will be accomplished by sending in a `label` to `calcite-button` like `<calcite-button label="foo">`

**Comment by MikeTschudi** [comment]
At calcite-components version 1.0.0-beta.59, the latest on unpkg.com, the element is updated:
![image](https://user-images.githubusercontent.com/2125181/125649501-ba7d18d3-216c-4a88-9bb3-a3e68258ce0d.png)
to
![image](https://user-images.githubusercontent.com/2125181/125649597-19d984b5-e43e-4c44-b668-f4c670a27987.png)
when the menu selection is changed.

But the screen reader no longer says the name of the button that opens the menu.  For the example above
![image](https://user-images.githubusercontent.com/2125181/125650591-c7e2052e-bc1c-4fa7-aaaf-0952bf4f87c3.png)

At 1.0.0-beta.46, the reader (NVDA) said,
```
click button to open dropdown: 
clickable  Relevance  button  
menu
menu item  1 of 3
menu item  2 of 3
Relevance  button
```

At 1.0.0-beta.59, the reader says,
```
click button to open dropdown: 
clickable  button  
radio menu item  checked  1 of 1
radio menu item  not checked  2 of 2
clickable  button  
```

**Comment by driskull** [comment]
@MikeTschudi you would need to set the 'label' property on the 'calcite-button' and not set the 'aria-label' there.

**Comment by MikeTschudi** [comment]
@driskull, thank you--that does speak the button name. But then it doesn't get updated when I choose a new menu option:
```
clickable  Relevance  button  
678
button    Relevance

radio menu item  checked  1 of 1
radio menu item  not checked  2 of 2
clickable  Relevance  button  
```
after change to "Date Modified":
![image](https://user-images.githubusercontent.com/2125181/125665257-07bdfab2-6f99-442d-97e9-24304780dce8.png)

**Comment by driskull** [comment]
> it doesn't get updated when I choose a new menu option:

I don't think it is supposed to get updated. It's not a select listbox.

It's this role:

https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html
https://www.digitala11y.com/menuitemradio-role/

**Comment by driskull** [comment]
Those menu items shouldn't need an aria-label since they have text inside them.

**Comment by jcfranco** [comment]
Closing as verified based on https://github.com/Esri/calcite-components/issues/678#issuecomment-880073652 and ☝🏼 . Please create a new issue if anything further is needed.
