### ISSUE TITLE
Dropdown events not triggering in JSX environment

### ISSUE THREAD

**Issue by nathan-barrett** [Esri/calcite-components#682]
I'm having trouble getting events for `calcite-dropdown` and `calcite-dropdown-group` to fire in particular `onCalciteDropdownItemSelect` and `onCalciteDropwnClose`.  I provided a codepen below in a react environment with an example. 

[Link to codepen](https://codesandbox.io/s/preact-calcite-dropdown-v3gxm?fontsize=14&hidenavigation=1&theme=dark)

if I removed the arrow function for the console.logs, the function will fire on first render. 

Thanks for your help!

**UPDATE**

Looks like the types for different components are using camelcase like `onCalciteDropdownSelect` which i had trouble with earlier. If i change the event to: `oncalciteDropdownSelect` it works. So the types in the repo will need to be updated to reflect that.

**Comment by nathan-barrett** [comment]
Also, was able to get the event to trigger within the `ComponentDidMount` function by using the `addEventListener` method.

**Comment by macandcheese** [comment]
@nathan-barrett this was resolved here right? https://github.com/Esri/calcite-components/pull/693

**Comment by nathan-barrett** [comment]
yeah, it was. We can close this.
