### ISSUE TITLE
Stepper inside Modal: focus trap prevent from setting focus

### ISSUE THREAD

**Issue by olga-knyazeva** [Esri/calcite-components#6822]
### Actual Behavior

We have a Stepper inside a Modal. The next steps are disabled until a user clicks the button in the footer, which changes the active step to the next one and we want to set the focus to the new active step. Please see the example here - https://codepen.io/olga-knyazeva/pen/ExdNJEx. 

It works with `focus-trap-disabled` on the modal:

https://user-images.githubusercontent.com/61228868/233629311-9c43ced7-51af-4b4b-b8cb-e5b9d4310498.mov

But if you remove it, which is desired, the focus is not set to the next step:

https://user-images.githubusercontent.com/61228868/233629421-56ffbfc0-80a1-466c-a6cd-7ef8d4e4178a.mov

### Expected Behavior

The `.setFocus()` function sets the focus on the step without `focus-trap-disabled` attribute on the modal.

### Reproduction Sample

https://codepen.io/olga-knyazeva/pen/ExdNJEx

### Reproduction Steps

1. Remove `focus-trap-disabled` attribute from the modal
2. Click "Open modal" button
3. Tab through the modal until "Next" button, click it.

--- Expected: step 2 "Add data" becomes enabled and focused
--- Actual: step 2 "Add data" becomes enabled and but didn't get focused

### Reproduction Version

1.0.8

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Urban

**Comment by driskull** [comment]
This one might be fixed in latest version

**Comment by geospatialem** [comment]
The experience seems to be similar in `1.4.0-next.6` when `focus-trap-disabled` is removed.

![modal-stepper-focus-trap-disabled](https://user-images.githubusercontent.com/5023024/235949596-9fe44d24-e18d-482a-b6a5-62f89636cb8c.gif)

**Comment by driskull** [comment]
This seems to be fixed with the focus-trap update. Here is a codepen: https://codepen.io/driskull/pen/MWPPpaw

I did need to change the setTimeout to requestAnimationFrame.

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.21` with `requestAnimationFrame`:

```js
const nextButton = document.getElementById("next-button");
const step2 = document.getElementById("step-2");

 nextButton.addEventListener("click", function() {
      step2.disabled = false;
      requestAnimationFrame(() => step2.setFocus());
  });
```
