### ISSUE TITLE
Accessibility: calcite-tree traps focus, preventing backwards navigation out of it

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/calcite-components#683]
The following function in calcite-tree.tsx prevents the focus from navigating backwards out of the tree:
```tsx
  @Listen("focus") onFocus() {
    if (this.root) {
      const selectedNode = this.el.querySelector(
        "calcite-tree-item[selected]"
      ) as HTMLCalciteTreeItemElement;
      const firstNode = this.el.querySelector(
        "calcite-tree-item"
      ) as HTMLCalciteTreeItemElement;

      (selectedNode || firstNode).focus();
    }
  }
```

Without the ability to go backwards, a user has to go forwards through many elements to cycle around back to the beginning of the page.

Can this function be removed?

[shift + tab](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility)

**Comment by MikeTschudi** [comment]
Removing the function is not appropriate by itself because there are bigger accessibility problems.

Our version traps the backwards focus and causes the screen reader to say more than is needed. E.g., after clicking on the first tree item ("Child 1") in the [tree example](https://esri.github.io/calcite-components/?path=/story/tree--simple) and tabbing through the list, one hears NVDA say
```
Child 1
clickable  •  clickable  Child 1  clickable   
clickable     clickable  Child 2  clickable  •  clickable  Grandchild 1  clickable     clickable     clickable  Grandchild 2  clickable      
clickable  •  clickable  Grandchild 1  clickable   
clickable     clickable  Grandchild 2  clickable   
clickable     clickable  Child 3  clickable  
```
The arrow keys work, but don't seem to because they stop on each of the extra, hidden "clickables"--items with focus. It's awkward, and doesn't seem to meet the [WAI-ARIA Authoring Practices 1.1 for a TreeView](https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView).

http://www.oaa-accessibility.org/examplep/treeview1/ handles it the way that the Practices recommends. Running this example in a screen reader makes sense, and it doesn't trap the focus. E.g., stepping to the first tree item ("Fruits"), one hears
```
Foods  tree view
Group collapsed Fruits  collapsed  1 of 2  level 1
expanded
level 2  Oranges  1 of 5
Pineapples  2 of 5  level 2
Group expanded Apples  expanded  3 of 5  level 2
Pineapples  2 of 5  level 2
Oranges  1 of 5  level 2
level 1  Group expanded Fruits  expanded  1 of 2
```

The example is licensed under Apache 2; perhaps it can be adapted?

**Comment by MikeTschudi** [comment]
At calcite-components version 1.0.0-beta.46, the latest on [unpkg.com](https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.esm.js), continues to be an issue.

```html
<html>
<head>
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.css" />
  <script type="module" src="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.esm.js"></script>
  <script nomodule="" src="https://unpkg.com/@esri/calcite-components/dist/calcite/calcite.js"></script>
</head>
<body>
  <!-- https://esri.github.io/calcite-components/?path=/docs/components-tree--simple -->
  <a href="#">Uncle</a>
  <calcite-tree>
    <calcite-tree-item>
      <a href="#">Child 1</a>
      <calcite-tree slot="children">
        <calcite-tree-item>
          <a href="#">Grandchild 1</a>
        </calcite-tree-item>
        <calcite-tree-item>
          <a href="#">Grandchild 2</a>
        </calcite-tree-item>
      </calcite-tree>
    </calcite-tree-item>
  </calcite-tree>
  <a href="#">Aunt</a>
</body>
</html>
```

**Comment by macandcheese** [comment]
Thanks for reopening, our stale bot was a bit overeager to get started 😅.

This might be a good one for @caripizza to take a look at to get familiar with 🌲  component.

**Comment by macandcheese** [comment]
Open

**Comment by MikeTschudi** [comment]
Please keep open; still present at latest from unpkg (1.0.0-beta.54)
```html
<script type="module" src="https://unpkg.com/@esri/calcite-components@1.0.0-beta.54/dist/calcite/calcite.js"></script>
<link rel="stylesheet" type="text/css" href="https://unpkg.com/@esri/calcite-components@1.0.0-beta.54/dist/calcite/calcite.css" />
```

**Comment by MikeTschudi** [comment]
still present @1.0.0-beta.57 with NVDA 2020.4

**Comment by jcfranco** [comment]
Installed. 

@MikeTschudi Can you help verify this one? I created a codepen with your snippet https://codepen.io/jcfranco/pen/OJmPXvv?editors=1001

**Comment by MikeTschudi** [comment]
Thank you, @jcfranco!  I added relatives to the codepen and I can tab into and out of the top of the tree.

![image](https://user-images.githubusercontent.com/2125181/124311366-78fab780-db22-11eb-895a-719607fa0a32.png)

@cosbyr

**Comment by jcfranco** [comment]
Awesome, thanks for verifying!
