### ISSUE TITLE
[Input-Time-Picker] Support keyboard a11y improvements

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#6835]
### Description

Related Issue: https://github.com/Esri/calcite-components/issues/6680, #6830 

Summary
Updates `input-time-picker` to support keyboard a11y improvements for its time-picker container along with descriptive text.

### Acceptance Criteria

N/A

### Which Component

input-time-picker

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified on `master`.
