### ISSUE TITLE
Popover structure is may be too opinionated

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#685]
When using popover for any other dropdown UX beside calcite-dropdown, we found that the structure is the following:
- container: flex/column
  - content: flex/row

We are actually trying to compose a column content. It forces us to use yet another div to break the previous structure.
Would it be possible to have a less opinionated structure? Or to have attributes to control the type of popover we want 'mainly column' or 'mainly row'.

**Comment by macandcheese** [comment]
I suppose we could just remove the flex-direction on the content altogether but it would likely break some existing uses - having a prop to set a css property seems a little weird IMO.

We recently removed max-width property on popover with the assumption that a "wrapper div" would be placed there by a user. 

@Esri/calcite-components anyone else have thoughts?

**Comment by driskull** [comment]
I'll defer to @asangma for his wisdom :)
