### ISSUE TITLE
Color Picker allowEmpty description is backwards

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-components#6864]
### Description

**Current Description:**
When `false`, an empty color (`null`) will be allowed as a `value`. Otherwise, a color value is enforced on the component. When `true`, a color value is enforced, and clearing the input or blurring will restore the last valid `value`. When `false`, an empty color (`null`) will be allowed as a `value`.

**Actual behaviors imply the opposite.** 
https://developers.arcgis.com/calcite-design-system/components/color-picker/

### Which Component

Color Picker

**Comment by geospatialem** [comment]
Verified in the 5/24 doc release.
