### ISSUE TITLE
[Panel] `action-bar` slot should have the same background color as header

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6865]
### Description

Since Action Bar are not full width - they can show the Panel background behind, leading to undesired appearance:

![Screen Shot 2023-04-26 at 12 11 47 PM](https://user-images.githubusercontent.com/4733155/234678911-98cf7a0f-5069-456d-b811-d58b5b347046.png)

### Acceptance Criteria

I'd expect the slot to have a container with background that matched that of header, to better match the default color of action bg: 

![Screen Shot 2023-04-26 at 12 11 14 PM](https://user-images.githubusercontent.com/4733155/234678886-8851beb6-c7b8-4b75-9d51-ff4c14d55869.png)

### Which Component

Panel

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by driskull** [comment]
Seems like the action bar should always be full width when slotted here right?

**Comment by macandcheese** [comment]
Yeah, that would also solve 👍

**Comment by driskull** [comment]
@macandcheese do you have a codepen for this one? I think it could be fixed?

**Comment by geospatialem** [comment]
@driskull I observed it when `expand-disabled` is `true` and few `action`s are added: https://codepen.io/geospatialem/pen/LYgOOPK. 

Possibly associated with the container?

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.8` with `panel` and `flow`.

![image](https://user-images.githubusercontent.com/5023024/236329948-a58a8e5a-ae6c-4805-87ed-2869d4fc7ba6.png)

![image](https://user-images.githubusercontent.com/5023024/236330306-6b275be1-8a2f-41a9-a1e2-7af633a156bf.png)
