### ISSUE TITLE
Port over calcite-app-components

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#687]
As we continue to shape Calcite and it's messaging, we will be merging the calcite-app-components into calcite-components.  It'll be best to keep this in a separate branch for the adjustment period and transition to using one repository no avoid user disruption.

**Comment by driskull** [comment]
assigning @asangma for the styles

**Comment by julio8a** [comment]
^ @mitc7862, @macandcheese, and @bstifle can help with styling.

**Comment by driskull** [comment]
For the styling, it's mostly refactoring...

- App Component styles and mixins live under `/src/scss/` whereas Component styles live under `/src/assets/styles`.
- Both sets should use same CSS variable names for components to inherit
- Components `global.scss` is importing the Calcite Components `global.scss`. These should be combined. `globalStyle: "src/assets/styles/global.scss"`
- There are two sets of `includes.scss` files being imported into all components. These should be combined. `injectGlobalPaths: ["src/assets/styles/includes.scss", "src/scss/injected.scss"]`
- Components should be tested against their production version to make sure they are looking correct.

**Comment by driskull** [comment]
Installed.

**Comment by julio8a** [comment]
Can I close this out?

**Comment by jcfranco** [comment]
Not until we're shipping them. 😄
