### ISSUE TITLE
Allow custom labels on slider

### ISSUE THREAD

**Issue by nid13240** [Esri/calcite-components#6877]
### Description

It would be really helpful to add custom labels at the ends of the slider instead of using the min and max numeric values. This is an example picture using the js api slider
<img width="279" alt="image" src="https://user-images.githubusercontent.com/123668462/234934263-a8feb953-7c9c-45ff-b6c1-5ed426726f3d.png">

### Acceptance Criteria

New properties on the calcite-slider component for setting custom text to display under both ends of the slider

### Which Component

slider

### Example Use Case

Sliders on heatmap renderer for softening edges and adjusting area of influence
<img width="281" alt="image" src="https://user-images.githubusercontent.com/123668462/234934378-ae83f1f4-7598-49e2-96c0-94d31bf9d30d.png"> 

### Priority impact

p3 - want for upcoming milestone

### Esri team

ArcGIS Map Viewer

**Comment by jcfranco** [comment]
Thanks for reporting this. We have a few issues related to custom slider labels: 

* https://github.com/Esri/calcite-components/issues/2584
* https://github.com/Esri/calcite-components/issues/4004
* https://github.com/Esri/calcite-components/issues/5827

@geospatialem could consolidate or we create an epic to keep track of slider label enhancements?

Closing as duplicate per ☝.

**Comment by nid13240** [comment]
oh thank you!! sorry about that, didn't realize it was a duplicate

**Comment by geospatialem** [comment]
> @geospatialem could consolidate or we create an epic to keep track of slider label enhancements?

Good idea, @jcfranco! Added all the above issues to reflect the [`c-slider`](https://github.com/Esri/calcite-components/labels/c-slider) label for tracking with the differing milestones.
