### ISSUE TITLE
Refactor ported components to use shared style assets

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#689]
~Since we're merging the calcite-app-components into calcite-components we need to make sure we have clear UI consistency with foundations usage (colors, type-scale, spacing, etc) and overall components UI. Dependant on #687~

---

Moved this over to #902.

This ended up being more about the asset refactor. See @driskull comment [below](https://github.com/Esri/calcite-components/issues/689#issuecomment-670213763).

**Comment by macandcheese** [comment]
I think a large portion of this will be standardization around hitboxes for controls that would be adjacent to the edge of a container, ie: 

<img width="569" alt="Screen Shot 2020-07-06 at 12 12 42 PM" src="https://user-images.githubusercontent.com/4733155/86630863-3d1a2a00-bf82-11ea-9779-f4b08723a41a.png">
<img width="160" alt="Screen Shot 2020-07-06 at 12 12 22 PM" src="https://user-images.githubusercontent.com/4733155/86630867-3db2c080-bf82-11ea-88c6-161f1497cc3c.png">

vs. 


<img width="514" alt="Screen Shot 2020-07-06 at 12 13 36 PM" src="https://user-images.githubusercontent.com/4733155/86630856-3be8fd00-bf82-11ea-8544-c289ef72b0be.png">
<img width="569" alt="Screen Shot 2020-07-06 at 12 13 00 PM" src="https://user-images.githubusercontent.com/4733155/86630859-3c819380-bf82-11ea-84e3-e040ea22d08d.png">

**Comment by asangma** [comment]
@macandcheese We should be able to do that wherever the component is adding those buttons. When it's a slot (usually named), there will likely need to be some flexibility there.

**Comment by asangma** [comment]
Also, in some cases like the pick-list-item, the height of the component is affected by the content, so we'll probz need some flexibility there too.

**Comment by macandcheese** [comment]
Makes sense - we can do a more in depth design review on a per-component basis when they are ready to be updated 🤙

**Comment by asangma** [comment]
Cool.

**Comment by asangma** [comment]
Project here: https://github.com/Esri/calcite-components/projects/7

**Comment by driskull** [comment]
Refactoring todo:

- App Component styles and mixins live under `/src/scss/` whereas Component styles live under `/src/assets/styles`.
- Both sets should use same CSS variable names for components to inherit. Theme styling should propagate down to child components.
- Components `global.scss` is importing the Calcite Components `global.scss`. These should be combined. `globalStyle: "src/assets/styles/global.scss"`
- There are two sets of `includes.scss` files being imported into all components. These should be combined. `injectGlobalPaths: ["src/assets/styles/includes.scss", "src/scss/injected.scss"]`
- Components should be tested against their production version to make sure they are looking correct.
