### ISSUE TITLE
Remove padding from footer slot.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#6892]
### Description

The Panel and FlowItem apply padding to content that is placed inside the `footer` slot.
Because this slot allows users to overwrite the footer while still benefiting from its positioning, it would be good to remove any padding from the container and let users define that.

Doing so will also make it more straightforward to retain the Calcite pattern of full-height buttons.
It will also work nicely in Panel and FlowItem when the updated "compact" pagination gets installed.

### Acceptance Criteria

* Remove padding from `footer` slot of both Panel and FlowItem.
* retain sticky position and scrolling behavior.

### Which Component

Panel & FlowItem

### Example Use Case

When you need the Calcite pattern of full-height actions/buttons in the footer.

### Priority impact

p4 - not time sensitive

### Esri team

N/A

**Comment by macandcheese** [comment]
Full height content in the footer slot may not always be desirable. What about a css variable like we have for Modal's content slot that would easily allow this to be set to 0. It also creates a situation where some of our "footer" elements have padding by default (Card, Modal), and some wouldn't.


Defaulting to no space means folks will need to set their own padding when needed, IMO defaulting to a recommended padding and allowing it to be overridden is more consistent.


![Screen Shot 2023-05-01 at 10 18 53 AM](https://user-images.githubusercontent.com/4733155/235495754-ddefdb6f-73e3-4f8d-b908-227c70957f56.png)
![Screen Shot 2023-05-01 at 10 18 25 AM](https://user-images.githubusercontent.com/4733155/235495758-dea1d32c-cf28-42ff-a0f8-8a0d7e0ad160.png)
![Screen Shot 2023-05-01 at 10 18 07 AM](https://user-images.githubusercontent.com/4733155/235495760-0f662d94-121e-40b6-9d51-c93d7ac5074e.png)

cc @ashetland @SkyeSeitz

**Comment by driskull** [comment]
I think a variable would be ok. Or adding another slot that has no padding but is equivalent.

**Comment by macandcheese** [comment]
If we could combine `footer` and `footer-actions` into a single slot that could have its default padding overridden, I think that would be the simplest story. Right now we have two separate ones that function ... very similarly.

**Comment by ashetland** [comment]
Agree that combining the two slots would simplify things and adding a padding variable would also be consistent with what we've done elsewhere.

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.6` with `selection-mode="single-persist"`.

**Comment by geospatialem** [comment]
Verified in `master` with the `--calcite-flow-item-footer-padding` and `--calcite-panel-footer-padding` variables:

```css
calcite-flow-item {
  --calcite-flow-item-footer-padding: 0;
}
```
and 

```css
calcite-panel {
  --calcite-panel-footer-padding: 0;
}
```

**Comment by asangma** [comment]
Yew!
