### ISSUE TITLE
Calcite tree - allow selection of parent category w/out selecting children

### ISSUE THREAD

**Issue by capeoples** [Esri/calcite-components#6912]
### Description

We would like to have a property on the calcite tree that just allows for selecting the parent, without selecting children. We also want to make sure that this enhancement is accessible. 

_____

Currently in the calcite tree, when a parent is expanded / selected, it automatically selects all of the children. 
<img width="609" alt="Screen Shot 2023-05-03 at 11 40 02 AM" src="https://user-images.githubusercontent.com/30473086/236012618-b50e3da3-d635-440e-be06-6039cf778325.png">

When applied to filters in ArcGIS Online, this creates a scenario that is confusing / overwhelming for users, as there could be many nested filters under a parent. There is also a need to select just the parent in many filter use cases. Current example:
<img width="316" alt="Screen Shot 2023-05-03 at 11 45 52 AM" src="https://user-images.githubusercontent.com/30473086/236013962-12bf786d-ea38-404a-b2c8-aa253dc8f093.png">

### Acceptance Criteria

Allow for a selecting just the parent in a tree without selecting children.

### Relevant Info

[This example from w3.org of a File Directory for a Treeview](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-1a/) illustrates the behaviour we are looking for. Here's a link directly to the [codepen example](https://codepen.io/pen). 

### Which Component

Calcite tree

### Priority impact

p1 - need for current milestone

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
@SkyeSeitz @ashetland Could you take a peek at this one? The solution will likely be a new prop on `tree`, which would only select the parent item and not the child(ren). This pattern would differ from what is currently offered when a parent item is expanded and selected.

**Comment by geospatialem** [comment]
Possible related issue: https://github.com/Esri/calcite-components/issues/6509, which is a bug request on `tree-item` related to child `action` and selection - also targeted for the May release.

**Comment by SkyeSeitz** [comment]
Some thinky thoughts and notes on interaction behavior so we can align and discuss any open ended questions :)
Documented at [this file](https://www.figma.com/file/R0B6ljDBIyKPtEa5GXjSjx/Tree-%5Bparent%2Fchildren-selection%5D-%5B6912%5D?node-id=1%3A77844&t=AtfixlXqewQTJzV0-1).

**Comment by paulcpederson** [comment]
@SkyeSeitz that design covers our workflow really well. This is a change to how the children mode operates, but I think it's a good change and much more intuitive.

**Comment by ashetland** [comment]
Agreed. Nice work Skye. Do we think we can clean up hover states on this as well to make things more clear or does that need to wait to get this implemented faster?

**Comment by paulcpederson** [comment]
I can add hover changes as part of this pr if the designs are done in the very near future

**Comment by SkyeSeitz** [comment]
Thank you, @paulcpederson! Hover states are ready for review [here](https://www.figma.com/file/R0B6ljDBIyKPtEa5GXjSjx/Tree-%5Bparent%2Fchildren-selection%5D-%5B6912%5D?node-id=9%3A19911&t=2wSDwf4UXQEg1qnp-1). 
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/29716057/236301223-f2066f1c-7055-487a-9340-12ea16f657c0.png">

**Comment by SkyeSeitz** [comment]
[Link to prototype ](https://www.figma.com/proto/R0B6ljDBIyKPtEa5GXjSjx/Tree-%5Bparent%2Fchildren-selection%5D-%5B6912%5D?page-id=0%3A1&node-id=32-19135&viewport=-3811%2C-1397%2C1.19&scaling=min-zoom)with different hove state options. I am favoring the second in this list labeled "Background hovers without action" as it provides distinct hover states between the following selecting & expanded a parent item, just expanding, and just the action. The background also consistently extends to the left when hovering over the icon + text container, whether it is a parent item with decedents, item without decedents, or child item.

https://user-images.githubusercontent.com/29716057/236344447-3a812c11-e0bf-4188-9d25-210ef4bceba9.mov

**Comment by geospatialem** [comment]
Verified in `1.4.0-next.10` with `selection-mode="children"`.

_Note: To ensure the [PR](https://github.com/Esri/calcite-components/pull/6926#issue-1698010202) made the upcoming release the [hover states above](https://github.com/Esri/calcite-components/issues/6912#issuecomment-1535251908) were not part of the effort, but will be added to a future upcoming milestone._

![verify-tree-parent-selection-does-not-select-children](https://user-images.githubusercontent.com/5023024/236598997-8d42eaa2-f642-4c9f-baeb-c3dac0da6264.gif)
