### ISSUE TITLE
calcite-popover-manager is not opening the popover if the button contains a structure

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#692]
See: https://jsbin.com/rimabiw/edit?html,css,js,output

You will notice that the calcite-button used for triggering the popover contains a `<span>`.

This seems to mess up the popover-manager. Either it doesn't get the click or it thinks that it's not coming from the button.

Note that the same composition in the calcite-button used inside a calcite-dropdown doesn't have this issue.

/cc @bpatterson88

**Comment by ffaubry** [comment]
I'm working on a fix

**Comment by macandcheese** [comment]
Sounds good, I think generally we wouldn't want to add structural divs inside of buttons, just keeping them to icons and text. In this case you could add "pointer-events:none" to the added markup however.
