### ISSUE TITLE
[Flow Item] `footer` slot content should be centered

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6923]
### Description

It makes the small pagination not fit vertically centered. 

cc: https://github.com/Esri/calcite-components/issues/6733 - Panel footer content

### Acceptance Criteria

Content should be vertically centered on Flow Item, similar to Panel's footer content.

### Which Component

flow-item

### Example Use Case

https://codepen.io/geospatialem/pen/OJBzNvJ

### Priority impact

p3 - want for upcoming milestone

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
![complete design](https://user-images.githubusercontent.com/5023024/236521237-537d73f2-b7ad-468b-b79b-c174ebcf2ac1.png)

**Comment by ashetland** [comment]
Yep, that looks correct.

**Comment by geospatialem** [comment]
Closing out per https://github.com/Esri/calcite-components/issues/6923#issuecomment-1538761630.

**Comment by geospatialem** [comment]
Performing QA/QC on the new GitHub action for when the `design-complete` label is added. Apologies for the noise in advance.
