### ISSUE TITLE
TileSelect. Add icon slot for custom icons.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#6925]
### Description

Add an icon slot to TileSelect to allow users to place custom icons in the space used by the `icon` property.

cc @codebarker

### Acceptance Criteria

Retain existing behavior, e.g. when there is no description.

### Which Component

TileSelect

### Example Use Case

When a product has Meridian icons specific to the workflow but not general enough to be addd to the Calcite UI set.

### Priority impact

p2 - want for current milestone

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment]
Closing out per the group Teams discussion - the request above will be mitigated with additional icon support in Calcite UI icons.
