### ISSUE TITLE
[dropdown] add disabled property

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#694]
This is needed to prevent user interaction.

**Comment by macandcheese** [comment]
Sounds good - for the trigger or individual items? If its for the trigger, should we just apply our 0.4 opacity to whatever the slotted element is?

**Comment by jcfranco** [comment]
I was thinking about the trigger, but it might be useful for individual items although I'm not sure how common that would be. Maybe we can tackle that when there's a few use cases?

>  If its for the trigger, should we just apply our 0.4 opacity to whatever the slotted element is?

I think so. 👻
