### ISSUE TITLE
[Modal / Popover] In Safari, unable to tab through content

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6943]
### Actual Behavior

Follow up from Teams thread:

In Safari, unable to use Modal and keyboard - cannot advance past the close button or first slotted content item with Tab. In Popover, focus visually is added to the close button but unable to navigate with keyboard Tab / shift tab.

### Expected Behavior

I would expect the focus trap to work as expected / as in other browser.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/VwEXGya?editors=100

### Reproduction Steps

1. Open Codepen in Safari
2. Open modal and Try and tab through content
3. Notice that after the Tile Select group gains focus, the next focused element is the Browser's search / url bar.
4. Remove slotted content from Modal - note this still happens, so not specific to any inclusion of particular slotted elements it seems.
5. Close Modal, Open Popover, note that you can tab through the Focus Trap, but unable to Shift tab (focus lost on page)

### Reproduction Version

1.3.1

### Relevant Info

Seems to only occur in Safari but worth double checking other browsers.

### Priority impact

p1 - need for current milestone

### Impact

Depends on browser use per product, but potentially high impact. Feel free to re-prioritize.

### Esri team

Calcite (design)

**Comment by driskull** [comment]
Possibly related to https://github.com/focus-trap/focus-trap/issues/959

**Comment by geospatialem** [comment]
Research being conducted to determine next steps needed, or if it is blocked by the [focus-trap issue Matt mentioned above](https://github.com/Esri/calcite-components/issues/6943#issuecomment-1550227046).

**Comment by driskull** [comment]
I think this is fixed now from focus-trap update. Can you verify?
