### ISSUE TITLE
[Chip Group] Improve `scale` documentation

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6945]
### Description

Currently, the Chip Group `scale` documentation reads:
`Specifies the size of the component.`

We should update this to indicate that it also sets the scale on any Chip rendered inside, in addition to controlling the spacing between the Chips. Users need not set scale on the Chip themselves within a Chip Group.

cc @geospatialem 

### Which Component

Chip Group, Chip

### Resources

https://developers.arcgis.com/calcite-design-system/components/chip-group/

**Comment by geospatialem** [comment]
Verified in the 5/24 doc release.
