### ISSUE TITLE
Incompatible type error when with strict TS

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#7000]
### Actual Behavior

The following error is emitted when compiling with TypeScript configured w/ `strict: true` and `calcite-components@1.4.0`:

``` 
node_modules/@esri/calcite-components/dist/types/components.d.ts:5077:15 - error TS2320: Interface 'HTMLCalciteMenuElement' cannot simultaneously extend types 'CalciteMenu' and 'HTMLStencilElement'.
  Named property 'role' of types 'CalciteMenu' and 'HTMLStencilElement' are not identical.

 

5077     interface HTMLCalciteMenuElement extends Components.CalciteMenu, HTMLStencilElement {
                   ~~~~~~~~~~~~~~~~~~~~~~

 


Found 1 error in node_modules/@esri/calcite-components/dist/types/components.d.ts:5077
```

cc @dasa @bsvensson 

### Expected Behavior

No error is emitted. 🎉

### Reproduction Sample

https://github.com/jcfranco/cc-repro-error-with-strict-ts-and-cc1.4.0

### Reproduction Steps

1. clone the repo
2. run `npm i && npm start`
3. observe the compilation error

### Reproduction Version

1.4.0

### Priority impact

p1 - need for current milestone

### Impact

This will impact developers using strict flags in `tsconfig.json`.

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified with `1.4.1-next.2`
