### ISSUE TITLE
[Navigation User / Navigation Logo] Incorrectly inheriting line-height when JSAPI css present

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#7010]
### Actual Behavior

As reported by @mpayson, these components can be subject to inheriting style from JSAPI css when present on page. This issue was present in `4.26` or before, but `4.27` and later exhibit the issue to a worse extent due to line-height change in the additional css. Not sure what changed on their end, but we can limit any inheritance by adding a couple of line height declarations in our components.

No JSAPI css:  https://codepen.io/mac_and_cheese/pen/oNamozV?editors=1000
JSAPI 4.27 css: https://codepen.io/mac_and_cheese/pen/NWOoXVo
JSAPI 4.26 css: https://codepen.io/mac_and_cheese/pen/ZEqwvdY

### Expected Behavior

The spacing of the components should not look as it does with no JSAPI css on page

### Reproduction Sample

Above

### Reproduction Steps

View the various Codepen links, notice that the one without the JSAPI CSS is the correct spacing.

### Reproduction Version

1.4.0

### Priority impact

p1 - need for current milestone

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `1.4.1-next.2`
