### ISSUE TITLE
calcite-combobox: (x) close button is showing up

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#7015]
### Actual Behavior

For some reason recently in a combobox we use there is an (X) appearing that has not been there before, nothing has changed on our side, but we did update to 1.4.0

![image](https://github.com/Esri/calcite-components/assets/11093161/c5ab2eb3-1630-4647-9c47-6bfeb76c9ac7)

### Expected Behavior

There shouldnt be an (x) there

### Reproduction Sample

https://codepen.io/kevindoshier/pen/ExdrqyB

### Reproduction Steps

Im not able to repro in a codepen for some reason, so have no idea why all of the sudden this has started appearing.  The (x) is in the shadow dom of the component, so I dont think the app is somehow adding it there

### Reproduction Version

1.4.0

### Regression?

1.3.1

### Priority impact

p1 - need for current milestone

### Esri team

ArcGIS Map Viewer

**Comment by ethanbdev** [comment]
You can use `clearDisabled` to opt out of the `x`

**Comment by kevindoshier** [comment]
Thanks!  Yeah that works
