### ISSUE TITLE
Calcite input not allowing space character when used in "content" slot

### ISSUE THREAD

**Issue by nid13240** [Esri/calcite-components#7017]
### Actual Behavior

I am using the "content" slot on the calcite-list-item to insert a calcite text input. When I use this slot, I am not able to type the space character in the input box - other characters work fine but space does not register.

### Expected Behavior

I expect the space to registered as normal while typing.

### Reproduction Sample

https://codepen.io/nid13240/pen/KKGJOjY

### Reproduction Steps

in this codepen https://codepen.io/nid13240/pen/KKGJOjY

1. click the list item input box to edit
2. try to type a space 

### Reproduction Version

1.4.0

### Priority impact

p3 - want for upcoming milestone

### Esri team

ArcGIS Map Viewer

**Comment by nid13240** [comment]
cc @AdelheidF

**Comment by paulcpederson** [comment]
The way around this would be to stop propagation of that keydown event. 

https://codepen.io/paulcp/pen/GRYegPO?editors=1011

**Comment by geospatialem** [comment]
Verified in `1.4.1`.

**Comment by ethanbdev** [comment]
This broke the calcite list item select event. In this codepen, change the version between `v1.4.0` and `v1.4.1` to see the difference in behavior. This logic should not be changing in a patch release - let me know if you want a new issue

https://codepen.io/eborgen/pen/QWZRGKB?editors=1000

@driskull @geospatialem
