### ISSUE TITLE
[Tab-Title]: tabs no longer center with `layout="center"` 

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-components#7025]
### Actual Behavior

<img width="894" alt="Screenshot 2023-05-24 at 2 37 23 PM" src="https://github.com/Esri/calcite-components/assets/19231036/f0fcc075-9101-4898-98cb-33589e7f8244">

### Reproduction Sample

https://codepen.io/nsulzberger_esri/pen/MWPLRgB

### Reproduction Version

1.4.0

### Relevant Info

Possible fix: `:host([centered]) .content { @apply mi-auto; }` on or around https://github.com/Esri/calcite-components/blame/master/src/components/tab-title/tab-title.scss#L95

Possible workaround: https://codepen.io/mpriour/pen/bGmzJZm

### Regression?

Regression caused by https://github.com/Esri/calcite-components/issues/2620

### Priority impact

p1 - need for current milestone

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified in `master`.

**Comment by nsulzberger** [comment]
thanks a lot for fixing this, it looks fine now in Scene Viewer with 1.4.1 :)
