### ISSUE TITLE
[Menu Item] Items in certain configuration not displaying "href icon"

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#7027]
### Actual Behavior

Menu Items, when in a parent Menu of layout "vertical" or a submenu within a child Menu Item of Menu layout "horizontal", should show an icon affordance on hover or focus to indicate there is a href.
<img width="352" alt="Screen Shot 2023-05-24 at 10 27 05 PM" src="https://github.com/Esri/calcite-components/assets/4733155/a31721b3-aa3f-4b4a-8d5e-785829806c99">
<img width="352" alt="Screen Shot 2023-05-24 at 10 26 37 PM" src="https://github.com/Esri/calcite-components/assets/4733155/7e73c5ae-8ce8-4f54-a5e9-cb1efac30d1d">

<img width="236" alt="Screen Shot 2023-05-24 at 10 30 32 PM" src="https://github.com/Esri/calcite-components/assets/4733155/a8de0d2f-6167-45f9-946e-45e08f741bab">

### Expected Behavior

<img width="236" alt="Screen Shot 2023-05-24 at 10 30 19 PM" src="https://github.com/Esri/calcite-components/assets/4733155/7e3cc591-4164-4978-9625-36187e824a95">

<img width="352" alt="Screen Shot 2023-05-24 at 10 26 31 PM" src="https://github.com/Esri/calcite-components/assets/4733155/4610913d-4e44-4bc3-a835-7810a4afda5c">

<img width="350" alt="Screen Shot 2023-05-24 at 10 26 23 PM" src="https://github.com/Esri/calcite-components/assets/4733155/c9a6941c-bd4c-462e-9374-04d87ce35531">

### Reproduction Sample

Local

### Reproduction Steps

Open the local Menu demo and see behavior.

### Reproduction Version

1.4.0

### Priority impact

p4 - not time sensitive

### Impact

Missed this in the last pass - it's already there and just needs a small adjustment to work.

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified on `master`.
