### ISSUE TITLE
input-time-picker doesn't support sending in a lowercase locale code as lang

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#7036]
### Actual Behavior

Input Time Picker throws a console error and fails to render when sending in certain lang codes in lowercase that are typically spelled with uppercase geographical regions, like `en-us` (which is typically typed as `en-US`.  

![image](https://github.com/Esri/calcite-components/assets/821864/d691a846-d687-467a-9f09-c83cd43bbf06)

### Expected Behavior

Input Time Picker should support sending in any valid locale code with all lowercase letters.

### Reproduction Sample

https://codepen.io/eriklharper/pen/ZEqPMYR?editors=1111

### Reproduction Steps

1.  Render  `<calcite-input-time-picker lang="en-us"></calcite-input-time-picker>`
2. Result: nothing renders

### Reproduction Version

1.4.0

### Priority impact

p1 - need for current milestone

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Verified in `master`.
