### ISSUE TITLE
Calcite numeric input deleting decimal point

### ISSUE THREAD

**Issue by nid13240** [Esri/calcite-components#7039]
### Actual Behavior

When I am editing a decimal value on the calcite input component, the decimal point itself gets deleted when I delete the number in the tenths position. For example, if I have 1.5 and want to change it to 1.8, on trying to delete 5, it would also remove the "." and I would end up typing 18. 

### Expected Behavior

I expect the decimal position to stay in the input box like it does in the native input element.

### Reproduction Sample

https://codepen.io/geospatialem/pen/poxYOdO

### Reproduction Steps

Using the codepen above, try to use backspace on the three different input boxes and observe the difference in behavior between calcite-input and native input.

### Reproduction Version

1.4.0

### Priority impact

p3 - want for upcoming milestone

### Esri team

ArcGIS Map Viewer

**Comment by geospatialem** [comment]
Verified on `master`
