### ISSUE TITLE
Input-time-picker does not accept normal locale (nl-nl) code anymore 

### ISSUE THREAD

**Issue by arjanvanzutphen** [Esri/calcite-components#7040]
### Actual Behavior

The input time picker does not get rendered with the same lang property value as in 1.3.0.
The behavior looks this bug: https://github.com/Esri/calcite-components/issues/7036

Changing the locale value from 'nl-nl' to 'nl' works.

### Expected Behavior

Expecting to see a input time picker with the lang property set to 'nl-nl'

### Reproduction Sample

Codepen of the input-time-picker sample from https://developers.arcgis.com/calcite-design-system/components/input-time-picker/

### Reproduction Steps

1. Go to the input time picker page: https://developers.arcgis.com/calcite-design-system/components/input-time-picker/
2. Go to it's codepen sample
3. Add lang='nl-nl' property to the input-time-picker web component
4. The input-time-picker does not get rendered
5. Console errors a missing file. nl-nl.js is missing in dayjs, because it's now nl.js
6. Changing the lang property to 'nl' makes the input-time-picker appear again

### Reproduction Version

1.4.0

### Relevant Info

Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://js.arcgis.com/calcite-components/1.4.0/assets/input-time-picker/nls/dayjs/locale/nl-nl.js

### Regression?

1.3.0

### Priority impact

p3 - want for upcoming milestone

### Esri team

Professional Services - Services Delivery

**Comment by geospatialem** [comment]
Verified in `master`.
