### ISSUE TITLE
Disabled buttons are clickable in Firefox

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#7043]
### Actual Behavior

Clicking a disabled button fires the `onClick` event

### Expected Behavior

Clicking a disabled button does not fire the `onClick` event

### Reproduction Sample

https://codepen.io/mpayson/pen/VwENeyv

### Reproduction Steps

1. Open sample & developer console
2. Click button
3. See logged message

### Reproduction Version

1.4.0

### Priority impact

p2 - want for current milestone

### Impact

Maybe this could be lower priority, we can work around it by ignoring the click even when the button is disabled

### Esri team

N/A

**Comment by geospatialem** [comment]
Was able to repro in FF, even with last night's `1.4.1` release, which included https://github.com/Esri/calcite-components/pull/7031.

**Comment by tristan-morrison** [comment]
If it matters for prioritization purposes, this impacts the Editor widget in the JS SDK.

**Comment by geospatialem** [comment]
There are two workarounds available, however it will prevent providing a `tooltip` to a disabled `button`:

```html
<calcite-button style="pointer-events:none" disabled id="example-button">Open modal</calcite-button>
```

or checking if the button is disabled in the event listener:

```js
button.addEventListener("click", (evt) => {
  if (evt.target.disabled) {
    return;
  } else {
   modal.open = true;
  }
});
```

**Comment by jcfranco** [comment]
@geospatialem [Here's a codepen](https://codepen.io/jcfranco/pen/zYMqBQR?editors=1000) I used to look for regressions related to #5318. Sharing in case it helps.

**Comment by geospatialem** [comment]
Verified with [Franco's codepen above](https://github.com/Esri/calcite-components/issues/7043#issuecomment-1595276148) and https://codepen.io/geospatialem/pen/rNQMPXg in `1.5.0-next.4`.
