### ISSUE TITLE
[List Item] Always emit `calciteListItemSelect` on activation

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#7059]
### Actual Behavior

Where `list-items` have no selection with `selection-mode="none"` the `calciteListItemSelect` event is no longer available.

### Expected Behavior

All `list-items` of all selections should be able to receive context via the `calciteListItemSelect` event.

### Reproduction Sample

https://codepen.io/eborgen/pen/QWZRGKB

### Reproduction Steps

1. Open the [sample](https://codepen.io/eborgen/pen/QWZRGKB)
2. Open the console
3. Select the "Hiking trails" list item
4. Observe the event is fired
5. Change the CC version to `1.4.1`
6. Select the "Hiking trails" list item
7. Observe the event is not fired

### Reproduction Version

1.4.1

### Relevant Info

Originated from https://github.com/Esri/calcite-components/issues/7017#issuecomment-1567314905

In the future, we should also research active events to adopt dropping events from `selection-mode="none"` across our components, breaking current behavior (other components include `tree` and `dropdown`). cc @driskull @jcfranco 

### Regression?

1.4.0

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Map Viewer

**Comment by driskull** [comment]
> All list-items of all selections should be able to receive context via the calciteListItemSelect event.

There is no selection/deselection happening. We may want a different event like `calciteListItemActive` event.

> In the future, we should also research active events to adopt dropping events from selection-mode="none" across our components, breaking current behavior (other components include tree and dropdown).

I'm not sure if this would be considered breaking since the events themselves say they should emit when an item is selected and no selection is happening.
