### ISSUE TITLE
[Menu Item] - When in parent `vertical` menu, `icon-end` is in the wrong position

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#7097]
### Actual Behavior

Currently, if a Menu Item within a parent menu in "vertical" layout has slotted children, and an icon-end, the position of the icons will be incorrect:

<img width="302" alt="Screen Shot 2023-06-02 at 9 52 47 AM" src="https://github.com/Esri/calcite-components/assets/4733155/bb584b0c-4510-463f-8080-4c9a77519173">

### Expected Behavior

The icon-end should be in the correct position:

<img width="302" alt="Screen Shot 2023-06-02 at 9 51 47 AM" src="https://github.com/Esri/calcite-components/assets/4733155/db193453-c293-4b51-a225-149f24377d42">

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/oNaKoOo?editors=1000

### Reproduction Steps

1. Visit sample
2. Notice the "trucks" menu item has the incorrect order

### Reproduction Version

1.4.2

### Priority impact

p2 - want for current milestone

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
Verified in `1.4.3-next.1`

![image](https://github.com/Esri/calcite-components/assets/5023024/1c2c6b18-9bb3-45f0-a4ed-b471f7f10dea)
