### ISSUE TITLE
tab-title focus style issue

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-components#712]
Currently focused tab-title looks like this:
![image](https://user-images.githubusercontent.com/3506166/87093013-51b02980-c1f1-11ea-9202-aacdcd0866e5.png)

This is definitely not looking good IMO.
I'm proposing to add some left/right padding:
![image](https://user-images.githubusercontent.com/3506166/87093112-815f3180-c1f1-11ea-9ca2-a9984c79916b.png)

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/87097843-e79c8200-c1fa-11ea-9f89-c1d34cacf0fa.png)
this looks much better @ffaubry

**Comment by ffaubry** [comment]
@bstifle Could you look at the PR, Adam has questions for you.
