### ISSUE TITLE
Tile Select: Border Configuration

### ISSUE THREAD

**Issue by FelFly** [Esri/calcite-components#7126]
### Description

Hub needs a list component that indicates active selection to assistive technologies and we'd like to rely on a component that uses checkboxes and/or radios, since they clearly communicate state. I had previously identified an issue with the list component not indicating active selection. However, in a follow-up discussion with Kitty, she determined that the list component has some limitations around indicating active selection due to its gridcell structure and inconsistent screen-reader support around the aria-selected attribute. All of this to say, we'd really appreciate being able to use the tile select instead, but the borders on it make vertical lists feel very boxy when it's placed inside of panel editors.

This request would be a request to support a configuration that could disable outside borders.

### Acceptance Criteria

GIVEN I am viewing a vertical tile select group, 
AND inputs are enabled,

IF I am viewing an unselected tile,
THEN the gray border would not be seen,
AND my indicator of unselected would be an empty checkbox or radio.

IF I am viewing a selected tile,
THEN the blue border would not be seen,
AND my indicator of active would be a selected checkbox or radio.

IF I am navigating by keyboard,
THEN my focus state is the same as exists on the tile select today.

### Which Component

https://developers.arcgis.com/calcite-design-system/components/tile-select-group/

### Example Use Case

Here's a mockup of how we'd be likely to use a borderless tile select: https://www.evernote.com/shard/s157/sh/b6faabdb-05c0-46b0-9e28-6b72ba488c3e/be3vMnlv52gfTiEdwwBMo23CSkBqHxOrqDdxuNZi5DFwYTgooCwBixuHFg

Hub has a composite component that looks similar, but still has some idiosyncrasies in how assistive technologies handle the nested elements: https://esri.github.io/hub-components/storybook/?path=/story/editing-arcgis-configuration-editor--composite-fields

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Hub

**Comment by SkyeSeitz** [comment]
Hello @FelFly! Thanks for the info above. Got confirmation from @geospatialem on the [limitation of AT and browsers](https://github.com/Esri/calcite-design-system/issues/6711#issuecomment-1494787199) when using `List`. 

I believe the use-cases you provided can be handled in `Radio Group`, though. @macandcheese put together [this quick codepen](https://codepen.io/mac_and_cheese/pen/qBLdNvj?editors=1000) demonstrating additional content that can live in a Radio Button. Let us know if this serves as a good solution for Hub.
