### ISSUE TITLE
Cannot type a decimal in a number input when the locale is arabic - Firefox only

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#7130]
### Actual Behavior

If I try to type a number such as "5.5: into a `calcite-input` with type `number`, it does not enter the decimal and just types "55"

### Expected Behavior

It should type "5.5" like it does in Chrome

### Reproduction Sample

https://codepen.io/eborgen/pen/PoxYxdR?editors=1010

### Reproduction Steps

1. Open the codepen
2. Try to type "5.5"
3. Observe "55" is displayed

You can also,
1. Type "5.5" somewhere else and copy/paste, it will change it to `5,5`
2. This is not correct per https://i18n.esri.com/website/i18ntools (Use Arabic - Saudi Arabia for testing)

### Reproduction Version

1.4.1

### Relevant Info

I don't think this has worked for a while

### Priority impact

p3 - want for upcoming milestone

### Esri team

ArcGIS Web Analysis

**Comment by geospatialem** [comment]
Perhaps could be tackled with https://github.com/Esri/calcite-components/issues/7039?

**Comment by anveshmekala** [comment]
From the initial debugging , it is identified that `Intl.NumberFormat` API is returning `latn` numbers with `.` as decimal separator  in chrome where as in FireFox the decimal separator is `,` with `arab` numbers though the numbering-system is set to `latn` in both instances.

**Comment by geospatialem** [comment]
Verified in `1.4.3-next.5` with Firefox v`102.12.0esr`.
