### ISSUE TITLE
Modal: setting focus on modal open doesn't work

### ISSUE THREAD

**Issue by olga-knyazeva** [Esri/calcite-components#7135]
### Actual Behavior

It's not possible to set focus on any element as soon as the modal is open, setting it in onCalciteModalOpen doesn't seem to work - https://codesandbox.io/s/modal-focus-ypge83?file=/src/App.js

### Expected Behavior

We want to set focus on the first interactive element in the content when the modal is opened rather than having it on a close button. I expected that setting it in onCalciteModalOpen should do that, but it doesn't, even with e.preventDefault()

### Reproduction Sample

https://codesandbox.io/s/modal-focus-ypge83?file=/src/App.js

### Reproduction Steps

1. Click Open
2. Observe the modal

Expected - the focus is on the text input
Actual - the focus stays on the close button

### Reproduction Version

1.4.2

### Priority impact

p2 - want for current milestone

### Esri team

ArcGIS Urban

**Comment by geospatialem** [comment]
@olga-knyazeva This is the intended sequence to maintain accessibility with focus order per [Success Criterion 2.4.3: Focus Order](https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html), where content is navigated sequentially to preserve meaning and operability. Closing out this issue as not planned to follow accessibility standards and guidelines.
