### ISSUE TITLE
`calcite-popover` does not open in a specific case with `calcite-tooltip`

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#7158]
### Actual Behavior

When a `calcite-action` (element type may not be important) is the target of both a `calcite-popover` and `calcite-tooltip`, the `calcite-popover` will not open if the `calcite-tooltip` is in the process of appearing. For example, the user hovers over the `calcite-action` and the tooltip starts to appear - at this exact time, clicking on the action will not open the `calcite-popover`. The user will need to click the `calcite-action` two more times for the `calcite-popover` to appear.

### Expected Behavior

The `calcite-popover` should appear when the user clicks its target.

### Reproduction Sample

https://codepen.io/jmanke/pen/ExOabVd?editors=1011

### Reproduction Steps

The following repro steps are for this [codepen](https://codepen.io/jmanke/pen/ExOabVd?editors=1011):

  1. Ensure page is refreshed
  2. Hover over action with mouse. Right as the tooltip appears, click on the action. This step is difficult to time just right.
  3. Observe that the popover does not open. It requires clicking on the action two more time to open it.

### Reproduction Version

v1.4.2

### Relevant Info

Tested on Chrome v114 on MacOS Ventura 13.4

### Priority impact

p3 - want for upcoming milestone

### Impact

Medium - it feels like the popover is broken for some users in this particular workflow.

### Esri team

ArcGIS Dashboards

**Comment by driskull** [comment]
It seems to have to do with debouncing the reposition() method internally. If you resize the page when it gets into one of those bad states it seems to bring the component up to date because it calls reposition again.

@jmanke does this only happen when there is both a tooltip and popover or can you reproduce with just a popover?

**Comment by jmanke** [comment]
@driskull I can't seem to repro the issue when I remove the tooltip. It may be a timing issue on my end, but I've tried ~50 times and couldn't repro the bug. The only way I've been able to repro is with the steps above.

**Comment by geospatialem** [comment]
Verified in `1.5.0-next.4`.
