### ISSUE TITLE
Expose maxItems as a constructor argument on ComboBoxInput

### ISSUE THREAD

**Issue by dndhm** [Esri/calcite-components#7244]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-components/issues) to avoid duplicates

### Description

ComboBoxInputs can vertically overflow their containers if they have enough items. The underlying calcite ComboBox component includes a [maxItems](https://developers.arcgis.com/calcite-design-system/components/combobox/#api-reference-properties-maxItems) property, but this is not available to consumers via the `@arcgis/core` ComboBoxInput class.

Exposing `maxItems` as a constructor argument would allow consumers to avoid this behaviour without resorting messy hacks.

### Acceptance Criteria

Passing `maxItems` as a constructor argument should set `max-items` on the rendered `<calcite-combobox>` component.

```
new ComboBoxInput({
  maxItems: 5,
})
```

```
<calcite-combobox max-items="5" ...>
```

### Which Component

@arcgis/core/form/elements/inputs/ComboBoxInput

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by jcfranco** [comment]
Thanks for creating this issue.

`@arcgis/core/form/elements/inputs/ComboBoxInput` belongs to the [ArcGIS Maps SDK](https://developers.arcgis.com/javascript/latest/api-reference/esri-form-elements-inputs-ComboBoxInput.html), so you'll have to contact [Esri Technical support](https://support.esri.com/en-us/overview) for this request.

**Comment by dndhm** [comment]
Thanks, I will reach out there, although it seems to be more of a venue for workarounds and hacks, rather than actual feature requests and bug reports.

**Comment by geospatialem** [comment]
Closing this issue out as it pertains to the ArcGIS Maps SDK per https://github.com/Esri/calcite-components/issues/7244#issuecomment-1613962339.
