### ISSUE TITLE
calcite-shell-panel breaking style changes

### ISSUE THREAD

**Issue by capegreg** [Esri/calcite-components#7246]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-components/issues) to avoid duplicates

### Actual Behavior

Calcite shell panel style computed widths break panel.

--calcite-shell-panel-min-width-internal

![image](https://github.com/Esri/calcite-components/assets/1051118/60ffaadb-c58d-4103-8c52-f10cc7644480)

### Expected Behavior

![image](https://github.com/Esri/calcite-components/assets/1051118/1d23298c-1749-4b48-a1af-b60ceda9030c)

### Reproduction Sample

https://www.manateepao.gov/parcel/?display=fullaerial&referer=search

### Reproduction Steps

Differences between classes 

1.3.0

:host([detached-height-scale="l"]) .content--detached {
    --calcite-shell-panel-detached-max-height-internal: var(--calcite-shell-panel-detached-max-height, 80vh);
}

![image](https://github.com/Esri/calcite-components/assets/1051118/4d087ef8-5bbf-41af-a7c0-3ae1ec81683c)

1.4.0

:host([layout="vertical"][width-scale="m"]) .content {
    --calcite-shell-panel-width-internal: var(--calcite-shell-panel-width, 20vw);
    --calcite-shell-panel-max-width-internal: var(--calcite-shell-panel-max-width, 420px);
    --calcite-shell-panel-min-width-internal: var(--calcite-shell-panel-min-width, 240px);
}

![image](https://github.com/Esri/calcite-components/assets/1051118/8032a28f-e12f-4748-9923-5fad902a90a4)

### Reproduction Version

1.4.0

### Regression?

1.3.0

### Priority impact

p3 - want for upcoming milestone

### Impact

Map appears broken.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

N/A

**Comment by capegreg** [comment]
Try this

broken
[https://calcite-demo2.capegreg.repl.co/index.html](https://calcite-demo2.capegreg.repl.co/index.html)

works
[https://calcite-demo2.capegreg.repl.co/index2.html](https://calcite-demo2.capegreg.repl.co/index2.html)

**Comment by macandcheese** [comment]
Thanks for the additional links - I can see the difference now. 

What's happening is expected as the Shell Panel in the "broken" example is using `displayMode="dock"` - which will always display the container except when `collapsed`. 

The older example is using `detached` which would map to "display-mode="float"` - if you use that, it should work as it previously did.

Alternatively, if you do want to use `display-mode="dock"`, you could hide / show the Shell Panel using the `collapsed` property, or conditionally setting the css vars to manage width.

**Comment by capegreg** [comment]
Ok. I am creating the panel on the DOM and that content class is in the shadow. 

let panel = document.createElement('calcite-shell-panel');
panel.setAttribute('id', 'pao-shell-panel-start');
panel.setAttribute('slot', 'panel-start');
panel.setAttribute('position', 'start');		
panel.setAttribute('detached', '');
panel.style.zIndex = '9999';


![image](https://github.com/Esri/calcite-components/assets/1051118/7e7a4b2e-6b68-438a-a420-277f0b299e6c)


I will have to resort to customElements whenDefined.

    const fixShellContainer = async () => {
      await customElements.whenDefined('calcite-shell-panel');
      await delay(200);
        let node = document.querySelector('.content'); // not quite there
        // or let node = document.querySelectorAll(#pao-shell-panel-start); // not quite there
        // get the container and add the class.

        if(node)
          node.classList.add('detached');
    };

**Comment by macandcheese** [comment]
If you set `display-mode` to `float` instead of adding the `detached` attribute, does it work as intended. You shouldn't need to set `detached` anymore as `display-mode="float"` would work.

**Comment by capegreg** [comment]
display-mode float works perfect. Thank you.
