### ISSUE TITLE
Enhancement request: Custom value in select menu

### ISSUE THREAD

**Issue by bpatterson88** [Esri/calcite-components#733]
Requirements for Dashboards query builder:
- Allow user to select a value
- Allow user to filter existing values
- Allow user to select a new/custom value 

In progress UI:
![custom-value-select-menu](https://user-images.githubusercontent.com/15875886/87594856-777e7800-c6a2-11ea-96ad-ec5905c7c059.png)

cc @ffaubry @Esri/calcite-components

**Comment by macandcheese** [comment]
Valid

**Comment by macandcheese** [comment]
@bpatterson88 - this functionality should be available in the Combobox component - can you check to see if that satisfies this issue?

**Comment by bpatterson88** [comment]
Looks like it does. Closing.
