### ISSUE TITLE
[calcite-modal Enhancement] Add explicit slot for calcite-stepper

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#734]
A common use case for a stepper is inside of a modal. We should have a named slot for `calcite-stepper` that provides a place for a stepper to reside within the modal. If the slotted element is not a `calcite-stepper`, don't render the content.

If the stepper is in `alignment="horizontal"`, it the slot could be wrapped in a container that gives it a border top but places it inside the header. If the stepper is in `alignment="vertical"`, we could somehow position it within the modal. 

We would need to document the pattern in Storybook with examples of both, but currently you need to place it inside the modal content which is less ideal.

**Comment by macandcheese** [comment]
Valid

**Comment by jcfranco** [comment]
@macandcheese Is this still valid with the latest implementation? If so, can it be done via a prop or CSS var instead of having modal 'know about' stepper?

**Comment by macandcheese** [comment]
I’m not sure how we could style this with css to achieve the desired layout, since we’d need to position the stepper inside or adjacent to the header div based on the type of alignment.

It’s been requested a few times but we can close it until a team comes back with another ask.
