### ISSUE TITLE
CalciteRadioGroup#focus() should focus first applicable item

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#74]
As noted in https://github.com/ArcGIS/calcite-components/pull/72#issue-299425059.

**Comment by macandcheese** [comment]
@jcfranco is this still an issue?

**Comment by jcfranco** [comment]
Yes, but IMO this is low priority. There are other component's with similar behavior (e.g., `calcite-tabs` and `calcite-button`).

**Comment by jcfranco** [comment]
Fixed via #364.
