### ISSUE TITLE
calcite-checkbox: displaying undefined when un-checking

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#747]
I started seeing this when switching from beta31 to beta33. beta32 gives me a build error.

If I check and then un-check the checkbox I get undefined in the UI.
Reproducible with Map Viewer Beta on devext.

<img src=https://user-images.githubusercontent.com/44481292/88122246-ebc28b00-cb7c-11ea-8a0d-8c013b5a948f.png width=100/>
<img src=https://user-images.githubusercontent.com/44481292/88122261-f3822f80-cb7c-11ea-9926-c238124170de.png width=100/>
<img src=https://user-images.githubusercontent.com/44481292/88122231-e1a08c80-cb7c-11ea-833d-bcc10a1b2e6f.png width=100/>

<img src=https://user-images.githubusercontent.com/44481292/88122285-085ec300-cb7d-11ea-8b58-934564e8b1b6.png width=400/>

<img src=https://user-images.githubusercontent.com/44481292/88122209-d188ad00-cb7c-11ea-85d2-e0a2f88e2126.png width=300/>

Seems to point here
`{role:"checkbox","aria-checked":this.checked.toString(),tabindex:this.disabled?"-1":"0"}`

**Comment by macandcheese** [comment]
@AdelheidF are these wrapped with a calcite-label?

**Comment by AdelheidF** [comment]
no

<img src=https://user-images.githubusercontent.com/44481292/88201225-0ee04f80-cbfc-11ea-8565-5171aff15a8a.png width=400/>

**Comment by macandcheese** [comment]
They don't need to be wrapped in `calcite-label`  to work,  I was just wondering if there was some interaction at play there.(the label font-sizes are still 12/16/20)

Are you saying this only occurs in `beta.32` and not `beta.33` ? I can't reproduce this, is it possible to get a JSbin / Codepen? Thanks!

**Comment by AdelheidF** [comment]
I'm saying it worked in beta.31 and does not work in beta.33. beta.32 was a bad build, so I can't say if it broke before or after beta.32.
I (locally) change not a single thing beside switching from beta31 to beta33.

Here is a test case
http://devext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0
click layer name on left to make it active, click Styles tool on right to open panel, click +Field and choose Work Zone, click on Types tile, check and un-check the Other checkbox.

**Comment by AdelheidF** [comment]
I can work around the issue by re-creating the calcite-checkbox after every click, but now I see the expected flickering.

**Comment by AdelheidF** [comment]
I think I figured it out. It's related to the changes for those boolean properties `checked` and `selected`. They work differently now with beta33.
