### ISSUE TITLE
[color-picker] add property to disable outline for embedded use cases

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#750]
Color picker may be used in panels and it would be useful to add a property similar to `<calcite-button>`'s `appearance` to fit better in embedded scenarios.

**Comment by macandcheese** [comment]
Makes sense. Calcite-date has a similar style for "always open" but it's tied to "noCalendarInput". It removes the shadow associated with the date container but keeps the border. 

Would be good to make those two behave similarly?

**Comment by jcfranco** [comment]
@macandcheese I was mistaken, only the outline would be affected by appearance here. Not sure if that answers your date question. 😅

**Comment by jcfranco** [comment]
Closing as self-verified.
