### ISSUE TITLE
calcite-popover disappears when moving mouse over other elements

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#751]
Popover disappears and reappears when moving mouse over other elements.

Using beta33, I can't reproduce it with beta31. In both cases I use calcite-app-components 6.1.1 and 4master.

http://devext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0

Click on the layer name on the left to make it active, open smartMapping by clicking Styles on the right, click on Location tile, open transparency block and enable it (you need stuff in the UI to see it), click on the orange dot symbol to open the symbol styler. Now move your mouse slowly down the side panel (not over the styler).

cc @jcfranco

**Comment by zaramatheson** [comment]
![symbolstyler](https://user-images.githubusercontent.com/50747646/88207037-0a1f9980-cc04-11ea-8e29-64ae41e98fc9.gif)

**Comment by driskull** [comment]
Seems like an app issue. Only happens when the vertical slider is showing and when I move the mouse it seems to remove the popover being `open`.

**Comment by driskull** [comment]
@AdelheidF let me know if I can close this. Otherwise, we would need some kind of repro case using just components.

**Comment by driskull** [comment]
Neither the `popover` or `popover-manager` have any mouse events so this must be something in the app messing with it.

**Comment by driskull** [comment]
choosing an attribute also does a pretty crazy popover flicker. 

![Jul-24-2020 15-06-20](https://user-images.githubusercontent.com/1231455/88439188-5c58ea00-cdbf-11ea-89a9-c00953b139e0.gif)


Lets try to open issues in the MapViewer before opening them here until we know it's an issue with the component itself.

**Comment by AdelheidF** [comment]
It worked fine with beta 31. And if I only change to beta 33 and leave everything else as is I see the issue. Something must have changed there. Do those `data-popper-*` properties tell you anything? 

hidden state:
<img src=https://user-images.githubusercontent.com/44481292/88439047-f2d8db80-cdbe-11ea-9084-96e732e80fac.png width=400/>

showing state:
<img src=https://user-images.githubusercontent.com/44481292/88439145-40eddf00-cdbf-11ea-84d1-25b8dc6aff77.png width=400/>

I also see this issue on a panel without a slider.
<img src=https://user-images.githubusercontent.com/44481292/88439617-86f77280-cdc0-11ea-8256-b88883e2b8f9.png width=300/>

**Comment by driskull** [comment]
I would check what mouse events you have on those items and see why they might be causing a rerender

**Comment by AdelheidF** [comment]
OK, seems to happen only if I'm using `<calcite-tooltip-manager>` inside the panel. If I comment that out it works fine. Does this help?

**Comment by driskull** [comment]
yep! that helps. I see the bug.

**Comment by driskull** [comment]
Installed

**Comment by AdelheidF** [comment]
looks good, tested locally with beta.35
