### ISSUE TITLE
calcite-date: z-index issue

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#755]
There's an issue with z-index with the JS-API histogram slider handles. The z-index of the slider handle is 1. I'm not sure how to fix this.
<img src=https://user-images.githubusercontent.com/44481292/88332909-34e11f00-cce4-11ea-8787-a744ec5487b8.png width=200/><img src=https://user-images.githubusercontent.com/44481292/88332959-475b5880-cce4-11ea-98c0-69aa2464d253.png width=200/>

**Comment by AdelheidF** [comment]
I just noticed that this does not happen if the slider has only one handle.

<img src=https://user-images.githubusercontent.com/44481292/88336218-77f1c100-cce9-11ea-8cbe-2ea8a9fc2cc4.png width=200/><img src=https://user-images.githubusercontent.com/44481292/88336259-86d87380-cce9-11ea-9e80-e3faf9eb47bc.png width=200/>

Does this mean it's an issue for the histogram slider then? @JonUihlein

**Comment by AdelheidF** [comment]
From @JonUihlein

in the single handle case, we don't apply a z-index because there's no other handles to overlap
so the handle itself does not have any z-index value
in the multiple handle case, z-index is used when hovering, interacting, etc, it would be weird for the handle you are dragging to be behind other handles

**Comment by macandcheese** [comment]
Hm, the calendar wrapper has a z-index of 3... I was able to reproduce this with a `calcite-slider` by setting the z-index to 3 or higher, which is expected, but if I set the z-index of `calcite-slider` to 2 or lower it works as expected. Can you link to a repro case with the JSAPI slider?

**Comment by AdelheidF** [comment]
Here is a test case (will be on devext by tomorrow)
http://devext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0
click layer name on left to make it active, click Filter tool on right to open panel, click Add Expression, change field to 'Date of Crash', change operator to 'is between', now open calendar.

**Comment by AdelheidF** [comment]
Any updates on this one? Our release is in one week.

**Comment by macandcheese** [comment]
I was able to solve it at the above by setting the z-index to 2 on the histogram slider container (the fab seems like it should be beneath the calendar as well or at least positioned below it vertically?): 

<img width="932" alt="Screen Shot 2020-08-18 at 3 07 32 PM" src="https://user-images.githubusercontent.com/4733155/90570518-b487cf80-e164-11ea-8bb1-372665a32a10.png">

The calcite wrapper div has a z-index of 3... not sure if we just want to infinitely bump that up unless needed?

**Comment by AdelheidF** [comment]
The slider handles not longer appear above the calendar with `1.0.0-beta.41`.
The fab button has its own issue https://github.com/Esri/calcite-components/issues/989.
