### ISSUE TITLE
[calcite-input] missing maxLength/minLength properties

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#757]
Adding these properties will bring this component closer to `HTMLInputElement`.

**Comment by kat10140** [comment]
@jcfranco can this be closed?

**Comment by julio8a** [comment]
Closing, please re-open is still valid.

**Comment by COV-GIS** [comment]
FWIW...setting min/max string length on an `calcite-input` still isn't possible. Adding `maxLength` would be useful when setting up feature attributes for editing with field attributes. As opposed to manual length validation or setting `maxlength` on the input thru the vnode.
