### ISSUE TITLE
[calcite-input] value should also allow string and number

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#758]
`value` is currently typed [as string](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-input/calcite-input.tsx#L49), but should allow other types (similar to [`<input>`](https://github.com/ionic-team/stencil/blob/master/src/declarations/stencil-public-runtime.ts#L953)). 

The current type forces casting as string:

```tsx
render() {
    // 👇 from incoming color component

    // update rgb/hsv channel
    <calcite-input
      // ... 
      scale="s"
      type="number"
      value={channels[0].toString()}
    />

  // ...
}
```

**Comment by driskull** [comment]
This issue getting a bit stale. Do we want to increase priority?

**Comment by jcfranco** [comment]
@driskull Yeah, I think it should be bumped. I guess it would be tackled by https://github.com/Esri/calcite-components/issues/1145.

I'll close this in favor of the umbrella issue and reference this one.

**Comment by jcfranco** [comment]
Reviving this one for the remaining item of #1145 (wherever applicable, update value prop types to accept the most flexible type allowed) and adding it to the 5/10 - 5/21 milestone.
