### ISSUE TITLE
[calcite-label] disabled property

### ISSUE THREAD

**Issue by joeyHarig** [Esri/calcite-components#760]
Issue:
Labels above disabled inputs and above enabled inputs appear the same, making it difficult for the user to quickly distinguish between disabled and enabled fields.

Solution:
Ability to give the calcite-input a disabled prop that would change the text color to a lighter grey. The disabled prop could also be passed to any children (input or button), making them disabled as well.

**Comment by macandcheese** [comment]
Makes sense, we can have any control that we'd expect to be wrapped in a label (calcite-switch, calcite-slider, calcite-radio-group, calcite-checkbox, calcite-input, etc.) look up for a disabled prop on the wrapping label and apply to itself.
