### ISSUE TITLE
[calcite-color] allow toggling of sections

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#763]
Some use cases may require a simpler version of the UX, so having properties to toggle sections off will be needed.

**Comment by macandcheese** [comment]
Maybe use the `disable-*` API I kind of started to use in `calcite-video`? I think the only components that would be usable on their own outside of `calcite-color` would be the hex input and the swatch sets correct?

**Comment by jcfranco** [comment]
Would the `disable-x` pattern also hide the section or only prevent interaction?

>  I think the only components that would be usable on their own outside of calcite-color would be the hex input and the swatch sets correct?

Correct.

**Comment by macandcheese** [comment]
In `calcite-video` (still in PR so not set in 🗿 obviously) - it disables that UI element from appearing. 

If there's value in disabling sections from interaction but keeping them visible maybe having a `disable-x` and `hide-x` would make sense - but that seems like it may be asking for confusion.

**Comment by jcfranco** [comment]
> but that seems like it may be asking for confusion.

Agreed. I like the behavior, but I'd suggest `hide-x` (or similar) to avoid any confusion with native `disable` attribute behavior.

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
Closing as self-verified.
