### ISSUE TITLE
Checkbox style fixes

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#767]
![image](https://user-images.githubusercontent.com/14083530/88598009-52342700-d01d-11ea-89a3-3db3010573c1.png)
1. focus state transition too slow. needs to be sped up, thing looks jumpy

![image](https://user-images.githubusercontent.com/14083530/88598229-afc87380-d01d-11ea-8060-c2df9c2a0a10.png)
2. light theme fill is using ui-background, should use ui-foreground-1
3. dark theme fill, use ui-foreground-1-dark

![image](https://user-images.githubusercontent.com/14083530/88598359-fd44e080-d01d-11ea-9144-d42398ea0b50.png)
3. to meet 3:1 contrast, Light theme borders should be using blk-100 or #949494.
4. dark theme borders use blk-130, or #757575 or border-4-dark

![image](https://user-images.githubusercontent.com/14083530/88598533-51e85b80-d01e-11ea-9d9c-677dc2c50e68.png)
5. Disabled states should just be 40% opacity of whatever the visible state is. No color changes.

![Screen Shot 2020-07-27 at 3 33 38 PM](https://user-images.githubusercontent.com/14083530/88598688-abe92100-d01e-11ea-8856-fd4151a8949a.png)
6. S, M, L sizes should be 14, 16, and 18 px paired with font-size--1, font-size-0, and font-size-1 respectively.

**Comment by macandcheese** [comment]
@bstifle - this uses the same focus mixin as all other components, we'd need to change the animation for everything (which, might be worth speeding up since quick keyboard navigation often can't keep up with the animation delay).
