### ISSUE TITLE
Enhancement: Get color picker scales up to par with new scale system

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#771]
Ensure all elements in the calcite-color component are up to scale-snuff

#### Depends on

https://github.com/Esri/calcite-components/issues/1500
https://github.com/Esri/calcite-components/issues/1610

**Comment by julio8a** [comment]
Is this still valid?

**Comment by jcfranco** [comment]
@bstifle If this is still valid, could you add more info on what needs to be done?

**Comment by bstifle** [comment]
i think this wont be doable until tabs, input, and slider are up to date.

**Comment by julio8a** [comment]
This one should be addressed with the refactor of the color picker, closing
https://github.com/Esri/calcite-components/issues/2462
