### ISSUE TITLE
Enhancement: calcite-input type:number, holding arrow should speed up the counter

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#782]
### Description
If I use the HTML input element and hold down the mouse on one of the arrow keys the number keeps changing faster and faster. With calcite-input I have to click for every step increase.

In my test case I have values 0 to 100 for a percentage value and it's annoying to have to keep clicking.

<img src=https://user-images.githubusercontent.com/44481292/88857316-e8e21e80-d1aa-11ea-8f04-c13bce3cc84f.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/88857454-28a90600-d1ab-11ea-9812-fa082bf6b695.png width=200/>

**Comment by macandcheese** [comment]
This should also occur when holding down arrow up / down keys, in addition to holding down mouse on the increment / decrement ui buttons.

**Comment by driskull** [comment]
This issue getting stale. Who can we assign it to?

**Comment by benelan** [comment]
In beta.69 the number increases but at a slow rate. Should we increase it? The native input's rate of increase is much faster.
https://codepen.io/benesri/pen/ExvRoYJ?editors=1000

cc @macandcheese

**Comment by macandcheese** [comment]
@benelan Agreed - the speed of incrementing / decrementing with the arrow keys or the buttons should match a native input element where incrementing / decrementing "accelerates". 

The codepen above also has a strange interaction where the cursor occasionally flips to the start of the input.

**Comment by benelan** [comment]
@Elijbet I'm assigning the issue back to you, can you try to get the rate of increase/decrease to match the [native input element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number). Thanks!

**Comment by Elijbet** [comment]
Cool, I'll work on the cursor and speed issue next.

**Comment by Elijbet** [comment]
> @Elijbet I'm assigning the issue back to you, can you try to get the rate of increase/decrease to match the [native input element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number). Thanks!

I researched and didn't see an easy way of finding out the exact rate of change, but I took a video and tracked the time to be about 100ms. Would an estimate like that work?

**Comment by AdelheidF** [comment]
Looks good to me now.

**Comment by benelan** [comment]
verified on `next`
