### ISSUE TITLE
Upgrade Stencil to version 4

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#7861]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Upgrade Stencil from v2 to v4, which include the following breaking changes:
- [Version 3](https://github.com/ionic-team/stencil/blob/main/BREAKING_CHANGES.md#stencil-v300)
- [Version 4](https://stenciljs.com/docs/introduction/upgrading-to-stencil-four)

A more comprehensive list can be found on [GitHub](https://github.com/ionic-team/stencil/blob/v4.0.0/BREAKING_CHANGES.md).

### Acceptance Criteria

Upgrade to the latest version of Stencil to support users and teams also using Stencil in their projects.

### Relevant Info

- Since Calcite has come out of beta, Stencil has already bumped 2 versions (they are on version 4, Calcite is on version 2)
- This means that any projects building on top of the Calcite Components are using version 2 and that puts us at in a little bit of a bind because Stencil is focusing all their efforts on the latest release, so if we want to pick up any of the most recent fixes or features, we need to be on version 4
- To be cautious, Calcite is treating the update as a breaking change because with all the the projects building on top of Calcite Components and Stencil. As a result there might be some things that we're not considering that might pop up once we make the change.

### Which Component

All components

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-components-react
- [X] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by omarkawach** [comment]
Watching
