### ISSUE TITLE
Enhancement: Split Button support for Appearance

### ISSUE THREAD

**Issue by TheBlueDog** [Esri/calcite-components#796]
### Description

Update the Split Button component to support the `appearance` property for `solid, clear, outline, and transparent` for parity with other button components.

#### Which Component
Split Button: https://esri.github.io/calcite-components/?path=/story/split-button--simple

#### Example Use Case
This is currently needed for use in Field Maps (Acadia)

**Comment by julio8a** [comment]
I verified this on the storybook, closing.
