### ISSUE TITLE
[calcite-app-components] migration plan

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#801]
Original items moved over to [`calcite-app-components`](https://github.com/Esri/calcite-app-components/issues/1052). 

Leaving this open for any follow-up work after ☝️ is done.

cc @driskull @asangma @kat10140

**Comment by driskull** [comment]
<img src="https://media.giphy.com/media/l3q2Kgm3KOBUE6wF2/giphy-downsized-large.gif" />

**Comment by jcfranco** [comment]
Components were fully migrated in beta.42.
