### ISSUE TITLE
Enhancement: Add S M L Tabs and add new prop

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#803]
1. Add SML sizes for tabs
2. ~Add `default` prop~ (update: this is not needed - Cari)
3. 2. ~Add `default-top` prop~ (update: this is not needed - Cari)
4. 2. Add `bordered` prop

![image](https://user-images.githubusercontent.com/14083530/89087390-f6cda600-d348-11ea-8b81-add4557c6a69.png)

**Comment by macandcheese** [comment]
Related https://github.com/Esri/calcite-components/issues/186 cc @patrickarlt

**Comment by macandcheese** [comment]
cc @rmstinson

**Comment by capeoples** [comment]
+1 for this. I'm working on a project now with @joshtaylor0404 that could benefit from the medium scale size.

**Comment by macandcheese** [comment]
Suggestion: change "minimal" to default, and choose a new name for what's shown as "default" above. Because that would be a breaking change, we should keep what's currently the design as default. Maybe "bordered" for the new style cc @bstifle

**Comment by bstifle** [comment]
@macandcheese Agreed!! bordered makes sense

**Comment by macandcheese** [comment]
Valid

**Comment by julio8a** [comment]
This issue says in development, who is working on it?

**Comment by macandcheese** [comment]
Not being worked on right now.

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/109027371-52190a00-7686-11eb-8192-37c3ce493627.png)

most recent designs and prop names

**Comment by julio8a** [comment]
This is still needed

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/116442532-36fa8000-a818-11eb-9415-ac6c3e2daff1.png)
specs

**Comment by bstifle** [comment]
![image](https://user-images.githubusercontent.com/14083530/116614544-ac8d4b80-a8ff-11eb-86a1-743078879ab2.png)

**Comment by TheBlueDog** [comment]
Is there an update on this? Field Maps is in need of the sizes of tab to fix a UI defect.

**Comment by caripizza** [comment]
Adding the latest mockups from Bryan:
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/42423180/121594684-431a5580-c9f2-11eb-8372-f68813795363.png)
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/42423180/121594786-63e2ab00-c9f2-11eb-8ebd-9a70309a2dc1.png)

**Comment by TheBlueDog** [comment]
@bstifle Are these in component or experimental figma?

**Comment by julio8a** [comment]
verified on master.
