### ISSUE TITLE
Enhancement: Update focus handling in calcite-checkbox and calcite-radio-button

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#808]
### Description
Breakout issue from https://github.com/Esri/calcite-components/pull/807#discussion_r464594337 cc @driskull 
- Look at adding a `setFocus` method to handle focus requests instead of the `focused` prop

#### Which Component
Checkbox

**Comment by julio8a** [comment]
Still valid?

**Comment by driskull** [comment]
I think we need to increase priority on this one and fix it before release.

**Comment by julio8a** [comment]
@Esri/calcite-components can someone take this one?

**Comment by jcfranco** [comment]
![tenor-1](https://user-images.githubusercontent.com/197440/108574463-58953380-72cc-11eb-9d3d-f19b5a5678c8.gif)

**Comment by driskull** [comment]
@julio8a @macandcheese besides checkbox, it seems like calcite-radio-button needs this change too.

https://github.com/Esri/calcite-components/blob/master/src/components/calcite-radio-button/calcite-radio-button.tsx#L63-L71

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
@macandcheese Can you help verify this one? 🙇‍♂️

**Comment by macandcheese** [comment]
Works locally on master, thanks!
