### ISSUE TITLE
Enhancement: ShellPanel. Add a property to make it wide

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#815]
### Description
Add a property to enable users to set a wider dynamic width for the ShellPanel. This would be similar to the height-scale. I am guessing we could call it sideways-height-scale...

...or maybe width-scale.

### Acceptance Criteria 
* not break stuff
* not cause issues with Panel in center-row

### Relevant Info 
Some tools/workflows/ocelots benefit from a v-scroll layout but can use a bit more elbow room.

#### Which Component
* ShellPanel
* Possibly Flow, FlowItem
* Possibly CenterRow

#### Example Use Case
Updated UX/UI for analysis tools.

**Comment by asangma** [comment]
This might mean that we would need to update the `detached-scale` property to be like `detached-height-scale`.

**Comment by julio8a** [comment]
Any updates on this one @asangma ?

**Comment by jcfranco** [comment]
@asangma Is this still valid? If so, can you provide an estimate to help triage?
