### ISSUE TITLE
Enhancement: Color contrast accessibility compliance for inputs, combobox, search etc.

### ISSUE THREAD

**Issue by arjavbadjatiya** [Esri/calcite-components#816]
### Description
Input borders currently do not comply with 1.4.11: Non-text Contrast. The requirement is that the input's indicator (border) must meet 3:1 contrast ratio with the background. The background in our case would be either white or light gray.

### Acceptance Criteria 
Border's contrast ratio with the background must be above 3:1

### Relevant Info 
This will affect previous implementations (like the map viewer beta) and future projects (such as save and create dialogs in ArcGIS Online). Having the component meet accessibility requirements will help chip away at the accessibility debt around inputs.

#### Which Component
- All inputs
- Combobox
- Search boxes/text inputs (unless a different indicator in that component complies with 3:1 contrast)
- Any other components where only a border can indicate that they are "inputs" 

CC @macandcheese @bstifle

**Comment by julio8a** [comment]
@bstifle, can you check this is compliant now? if so, please close this issue.

**Comment by bstifle** [comment]
it wont be compliant until the color changes are in master

**Comment by driskull** [comment]
Can we close or assign this issue?

**Comment by bstifle** [comment]
assign it, this is still relevant

**Comment by bstifle** [comment]
#1247 is related

**Comment by julio8a** [comment]
I'm wondering if this can be taken care of during the refactor of those components

**Comment by macandcheese** [comment]
Unassigning - I’m super busy with AFD site stuff so leaving open if someone else can grab.

**Comment by driskull** [comment]
@julio8a can you assign someone

**Comment by julio8a** [comment]
@caripizza, if you have any questions on which vars to use, reach out to @bstifle.

**Comment by bstifle** [comment]
@caripizza vars are here: #1247

**Comment by bstifle** [comment]
@caripizza https://github.com/Esri/calcite-components/issues/1274 vars are here

**Comment by bstifle** [comment]
bring addressed in #1274
