### ISSUE TITLE
Enhancement: Input should support inline editing / click-to-edit

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#819]
### Description
Inputs should support inline / click-to-edit, where they can render as an input that is styled as text, with an affordance for edit (probably a pencil icon) - that then turns the input into a "regular" input with a save button as a slotted action.

### Acceptance Criteria 
Open to discussion / ideas.

**Comment by bstifle** [comment]
here's a design for this

![image](https://user-images.githubusercontent.com/14083530/89463206-7087da00-d723-11ea-9c27-e8e825577064.png)

**Comment by ade10176** [comment]
Adding clarification from offline chat with Adam, the `x` in the input is currently used for:
- Clearing the input in production since we don't have an editable state. 
- For "while editing" it actually closes the edit state and reverts to the previous value. 

I'm concerned about having an `x` that does two different actions (Clear and Cancel) in the input. Any issues with cancelling by clicking outside of the input? 

Also what other sizes will this input be supported in?

**Comment by macandcheese** [comment]
Hey @ade10176 - it would be supported in S/M/L along with other inputs. 

Re: clicking outside - that could also cancel / discard edits but I don't think it should be the only way to do so. We initially had a "garbage can" instead of an "x" which could be reverted to in the comps if needed.

**Comment by capeoples** [comment]
Per our sync on 8.3.2020, I'm posting some popover examples we currently have in Online > Organization > Settings. It would be great to leverage this component, but we'd like to have single-line and multi-line edit areas to have the same save/cancel affordances.

**Inactive state:**

- Empty state <img width="534" alt="Screen Shot 2020-08-10 at 3 29 49 PM" src="https://user-images.githubusercontent.com/30473086/89838194-7dd80680-db1f-11ea-9b76-bc3e3b75d863.png">

- With content <img width="680" alt="Screen Shot 2020-08-10 at 3 39 04 PM" src="https://user-images.githubusercontent.com/30473086/89838261-a3651000-db1f-11ea-815e-5af0195b29ec.png">


**Active state:**
<img width="587" alt="Screen Shot 2020-08-10 at 3 29 17 PM" src="https://user-images.githubusercontent.com/30473086/89838299-bed01b00-db1f-11ea-97c8-907b8ebd8830.png">

**Comment by ade10176** [comment]
- Does the hover state in idle only show up for the edit/pencil icon vs the entire input bg?

- Here's what we're thinking for the character counter placement. These examples are set in 2XL as they're used in our Form title:
![Inline Editing](https://user-images.githubusercontent.com/49533268/89839680-38b5d380-db23-11ea-9ee8-fddfb946974f.png)
