### ISSUE TITLE
[Conventions] Custom vs native events

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#82]
It'd be useful to enhance the [event namespacing section](https://github.com/Esri/calcite-components/tree/master/conventions#event-namespacing) with info on when to add a custom event vs relying on native browser ones.

**Comment by julio8a** [comment]
What's the status of this issue? can we close or does it still need work?

**Comment by jcfranco** [comment]
I think we still need to add a note about leveraging existing DOM events whenever possible and to create custom ones when we need a specialized event.

**Comment by paulcpederson** [comment]
Added note to conventions doc
