### ISSUE TITLE
Bug: CalciteInputInput event is giving previous value as a result on event listeners.

### ISSUE THREAD

**Issue by kumarGayu** [Esri/calcite-components#829]
### Summary

CalciteInputInput event is giving previous value of state on an event listeners.
 
### Actual Behavior
CalciteInputInput event is giving previous value of state on an event listeners.
Due to an event emission on componentWillUpdate

```tsx 
componentWillUpdate() {
    this.calciteInputInput.emit({
      element: this.childEl,
      value: this.value
    });

 

    this.determineClearable();
  }
```

### Expected Behavior
calciteInputInput event should always have current value.

### Reproduction Steps

1. consume the application with `calcite-input` component through tsx
2. listen to `onCalciteInputInput`
3. change the property of value
4. Observer in the listener youwould receive the old value. 

### Relevant Info 
Observed on stencil component consuming calcite-input component.

**Comment by macandcheese** [comment]
Verified.
