### ISSUE TITLE
Bug: Unexpected behavior in Pagination Component

### ISSUE THREAD

**Issue by joshtaylor0404** [Esri/calcite-components#833]
### Summary
There is some unexpected behavior when using the pagination component when it comes to the requested page size and total records.

### Actual Behavior
1. When using the pagination component, if the total records is less than the expected page size the component will display an unexpected result that shows two "1" elements:

![image](https://user-images.githubusercontent.com/3470614/89796613-b60b2500-dade-11ea-8e77-20f988a473e4.png)

2. Similarly, if the total number of records is 1 record over the page size multiple, the page will show up in the pagination area but you can not page to the last page:

![image](https://user-images.githubusercontent.com/3470614/89796319-59a80580-dade-11ea-8e38-c41dcc198320.png)

### Expected Behavior
1. We should only see 1 pagination number element at the bottom.
2. We should be able to page to the last page if the remaining total is under the requested page size.

### Reproduction Steps

See screenshots above.

**Comment by crowjonah** [comment]
Found another one! When `num` is `1`, no button is made for page 1 and page 2 appears initially selected:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/1634397/91904666-4f0f0500-ec73-11ea-98d6-75d90aa81b28.png">

**Comment by paulcpederson** [comment]
I think this is out now, feel free to reopen if need be
