### ISSUE TITLE
Enhancement: Slider Histogram Color Stops

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#834]
### Description

Site Scan is replacing in house UI components with Calcite where possible. The slider with histogram is one we would like to use, but our implementation allows for adding color stops (see example use case).

### Acceptance Criteria 

See example use case.

### Relevant Info 

Currently we use the `<AreaChart>` component from Recharts to provide this visualization and sync it to our slider. We can continue to do that with the Calcite slider, but thought it would look better if provided by calcite.

#### Which Component

Slider with histogram

#### Example Use Case

Elevation data using the "turbo" palette.

![image](https://user-images.githubusercontent.com/8754/89807659-ce367080-daed-11ea-958f-697d93eb86b6.png)

Thermal data using the "inferno" palette. 

![image](https://user-images.githubusercontent.com/8754/89807697-ddb5b980-daed-11ea-8561-ec6dae63d186.png)

Color stops update to reflect changes in slider positions.

![image](https://user-images.githubusercontent.com/8754/89807737-ef975c80-daed-11ea-85e3-cc2e90e0bd8b.png)

**Comment by julio8a** [comment]
@gpbmike, do you think this is something you can help us implement?

**Comment by gpbmike** [comment]
> @gpbmike, do you think this is something you can help us implement?

Sure I can give it a go.

**Comment by julio8a** [comment]
I'll add it to the coming sprint and assign to you.

**Comment by gpbmike** [comment]
This work is ready for review across two PRs (#2562, #2568). I'm blocked by lack of permissions in the calcite-components repository. If someone with permission would like to use my work, that's A-OK with me.

**Comment by julio8a** [comment]
@gpbmike, you should be good on the permissions now, can you check?

**Comment by jcfranco** [comment]
Installed!

**Comment by julio8a** [comment]
verified on master
