### ISSUE TITLE
Enhancement: Slider - display min-label and max-label attribute text

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#837]
### Summary

Using calcite-slider with min-label, and max-label and nothing shows up, Ive tried using them as attributes and as props after the element is created, neither result in the labels showing up

![image](https://user-images.githubusercontent.com/11093161/89817175-9125aa80-dafc-11ea-9abe-526f496f741a.png)

### Reproduction Steps

1.

**Comment by julio8a** [comment]
@kevindoshier is this issue still valid?

**Comment by kevd** [comment]
Yep, not seeing labels here

https://esri.github.io/calcite-components/?path=/story/components-slider--range

**Comment by caripizza** [comment]
@kevindoshier can you clarify this one for me with a code snippet example? When I select the `label-handles` checkbox knob on the story link you provided, the min and max value labels appear.

Are you instead asking for the "Temperature, upper/lower bound" text labels to appear?

**Comment by caripizza** [comment]
chatted with @kevindoshier in Teams, he's looking for the max/min-labels to appear like so:
![image](https://user-images.githubusercontent.com/42423180/106646413-93fcd780-6542-11eb-87f4-6d7bde274ebe.png)

**Comment by jcfranco** [comment]
Based on https://github.com/Esri/calcite-components/issues/837#issuecomment-771876212, I'm closing in favor of https://github.com/Esri/calcite-components/issues/4004.
