### ISSUE TITLE
New Component: Query Builder

### ISSUE THREAD

**Issue by bpatterson88** [Esri/calcite-components#840]
### Description

A query builder allows a user to define a logical expression based on an underlying data set. The query builder returns a set of records that match the expression.

#### User Stories

- As a Dashboard Publisher, I want to be able to apply a filter to a data visualization so that only relevant data points are shown.
- As a Map author, I want to be able to apply a filter to a feature layer so that only relevant data points are shown
- ?

### Acceptance Criteria 

- String based queries
- Numeric queries
- Date based queries
  - Relative dates
  - Specific dates
- Query against feature subtypes
- Use fields from record as a value in a expression
- 1 level of nesting
  - i.e. `(rule-1 AND rule-2) OR (rule-3 AND rule-4)`
- Horizontal and vertical layouts

#### Out of Scope 

tbd

**Comment by macandcheese** [comment]
Would be good to handle nested`WHERE` clauses as well in addition to `AND` / `OR` between parent arguments...
... [rule-1 WHERE rule-1a and rule-1b] OR [rule-2 WHERE rule-2a and rule-2b]

**Comment by bpatterson88** [comment]
First draft. Will be shopping this around to see if it needs to hit additional requirements.

[**Prototype**](https://www.sketch.com/s/eeb38ba1-5b80-4172-9b9b-14b05a6feabb/a/wEl0Lp/play) 

![20 0819 Query Builder](https://user-images.githubusercontent.com/15875886/90446538-686e5980-e096-11ea-98d2-b77b7f330991.png)

**Comment by macandcheese** [comment]
Looks awesome! 

Some quick feedback: 
The "on-gray" nesting with the slight border breaks down a bit when deeply nested, maybe there's another treatment for that?

For the horizontal alignment, could the number of matching records and delete be placed inline with the rest of the options somehow? Lots of vertical space per rule for that bit of info. 

Also for horizontal, the "And v" kind of reads like a potential caret for collapsing the section vs. a dropdown for selection between and / or. These also take up a bit of vertical space, perhaps they could be placed inline as well (as radio-group or as dropdown still?)

Overall super good stuff @bpatterson88 !

**Comment by bstifle** [comment]
@bpatterson88 loving this!!small nitpick, are you using #949494 on the borders on the inputs?

also, just curious what these little guys are for: 
![image](https://user-images.githubusercontent.com/14083530/90447183-9c964a00-e097-11ea-8a6d-b3089b9962e5.png)

**Comment by AdelheidF** [comment]
A few notes:

- This is how much width space you have on a small screen, e.g. a Microsoft Surface, for the panel containing the filter in Map Viewer Beta.

<img src=https://user-images.githubusercontent.com/44481292/90556609-0ffa9300-e14e-11ea-9553-ee2fd03ed27a.png width=200/><img src=https://user-images.githubusercontent.com/44481292/90556722-38828d00-e14e-11ea-877d-e356ef639b77.png width=200/>

- When asking for the unique values of a string field you might get too many to display.

- Sentence layout is different between languages and might need additional strings, if you're going for a sentence...

![image](https://user-images.githubusercontent.com/44481292/90557142-e3934680-e14e-11ea-9cc9-7fc09f9165a3.png)
<img src=https://user-images.githubusercontent.com/44481292/90558838-95337700-e151-11ea-8a68-1d38a79a06f7.png width=200/>

from the Classic Map Viewer
<img src=https://user-images.githubusercontent.com/44481292/90557509-716f3180-e14f-11ea-9ac7-864db62fa35f.png width=400/>
<img src=https://user-images.githubusercontent.com/44481292/90557437-543a6300-e14f-11ea-9578-77cddb6ac006.png width=400/>

- Date period

<img src=https://user-images.githubusercontent.com/44481292/90558466-ff97e780-e150-11ea-94a5-090ba8900ae0.png width=100/>

How would a user specify something like 'in the last 5 months' or in the 'last 2 years'?

**Comment by AdelheidF** [comment]
- (6) 
<img src=https://user-images.githubusercontent.com/44481292/91336180-6424f900-e786-11ea-8162-62f23d39d390.png width=200/>
If the user chooses a number field you'll show a histogram slider and then it will most likely have a default value (avg) show up in the number input. I wonder how useful the 'Number' string will be then.
<br/><br/>
Also, if the number field has domains, the UI will only show strings as options, so saying 'Number' next the the field name might get confusing. E.g. this is a number field and it displays the domain names to select from:
<img src=https://user-images.githubusercontent.com/44481292/91336471-cda50780-e786-11ea-954f-4f1256a4079c.png width=200/>

**Comment by macandcheese** [comment]
@TheBlueDog Can you and Ade go over the comps above and see if they would support your use case, maybe have the devs chime in there as well?

**Comment by bpatterson88** [comment]
v2 Notes:
- Removed count of records per condition and condition group. Feedback indicated this could be expensive and confusing. Now only showing count of records for entire expression.
- Removed group delete and overall expression delete. Deleting the last condition in a group will delete the group. Condition delete has been moved to the field select.
- Moved value source select to ellipsis button inside value select. This is a rarely used feature. Previous UI gave this option too much prominence and would likely lead to confusion.
- String conditions now use chips instead of plain strings. Related, removed "badge" showing how many values had been selected.
- Added additional detail around querying with feature subtypes.
- Additional nesting (2+ levels) seems out-of-scope / not yet required so those comps have been removed.
- Added specs and details for a 'freeform' mode, where users can set And/Or within groups and between groups.

![query-builder-v2](https://user-images.githubusercontent.com/15875886/92638199-c7d31a00-f28e-11ea-9e35-d12f4700e584.png)

**Comment by bpatterson88** [comment]
> small nitpick, are you using #949494 on the borders on the inputs?

@bstifle I'm using #2b2b2b on the text/spinner inputs and #eaeaea on the borders within the conditions.

**Comment by julio8a** [comment]
This looks really good @bpatterson88, nice work!

**Comment by bstifle** [comment]
@bpatterson88 i recommend working with Arjav on accessibility regarding the borders.

We use ui-text-3 (#6A6A6A) on all the icons like spinners on idle, then ui-text-1 (#2b2b2b) on focused/filled inputs and icons

**Comment by macandcheese** [comment]
This looks awesome - Re: inputs border color, these will just consume our input component I'd imagine, so that should get sorted out.

**Comment by driskull** [comment]
Whats the status on this component? 

IMO, it seems like it would be too tied to a specific query language so maybe belongs in arcgis components?

**Comment by julio8a** [comment]
Want to follow up on this one ^

**Comment by driskull** [comment]
I think we should close this or move it to arcgis components. query builder isn't a generic UI that belongs in calcite components.

**Comment by julio8a** [comment]
Let's move it to ArcGIS components. @bpatterson88, do you need help moving it over?

**Comment by alexabreu** [comment]
> Let's move it to ArcGIS components. @bpatterson88, do you need help moving it over?

@julio8a @driskull Field Maps is exploring building something similar to this to handle building **simple** Arcade expressions.  To clarify, did you you guys mean `arcgis-components` or `arcgis-app-components`? I ask because we were hoping to build a shareable web component, and my understanding is that that arcgis-components utilize Maquette rather than Stencil.

**Comment by driskull** [comment]
arcgis-app-components

**Comment by bpatterson88** [comment]
Feel free to move this issue to the appropriate repo. Looks like I am not a member or don't have the right permissions to move to either `arcgis-app-components` or `arcgis-components` so someone else will need to do that.

**Comment by driskull** [comment]
I don't think we can transfer to devtopia. It needs to be copy/pasted.

**Comment by bpatterson88** [comment]
Moved it over here: https://devtopia.esri.com/WebGIS/arcgis-app-components/issues/1020

**Comment by yelenakreyndel** [comment]
@mitc7862 can design work for this component be complete in May? Please update description of a task along with acceptance criteria.
