### ISSUE TITLE
Docs: Icon: missing example of "mirrored" property

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#846]
### Description 

I can't seem to figure out how to use the `mirrored` property for `<calcite-icon>`. An example would be helpful.

### Which Component

Icon 

### Resources 

https://esri.github.io/calcite-components/?path=/story/icon--simple

**Comment by macandcheese** [comment]
Hey @gpbmike - currently it needs to be in `dir=rtl` for `mirrored` to work, I have an update planned that allows it to work outside of that `rtl` context, along with some parent-level component props to mirror icons contained within them.

**Comment by gpbmike** [comment]
Thanks @macandcheese! That works for me.

I assumed `direction` in the docs referred to [CSS direction](https://developer.mozilla.org/en-US/docs/Web/CSS/direction). Feel free to close this if you think the documentation is fine as is.

**Comment by macandcheese** [comment]
@gpbmike I'll leave open until the PR is up and you can confirm it makes sense 😆

**Comment by gpbmike** [comment]
I think including something like the following in the "notes" section would help clarify.

```html
<div dir="rtl">
  <calcite-icon icon="carrot-left"></calcite-icon>
</div>
```

**Comment by macandcheese** [comment]
You will be able to explicitly request an icon to be `mirrored` with or without the icon being within a `dir=rtl` container. Currently, it has to be, which is a little weird, and to your point, undocumented.

**Comment by driskull** [comment]
still valid?

**Comment by gpbmike** [comment]
> still valid?

It looks like there is [no longer a `mirrored` property](https://esri.github.io/calcite-components/?path=/docs/components-icon--simple) and there's an example of `flipRtl`, so I'm going to say "no". Thanks! 😄
