### ISSUE TITLE
Enhancement: Disabling calcite-switch

### ISSUE THREAD

**Issue by rslibed** [Esri/calcite-components#851]
### Description
Disabling calcite switch.

### Acceptance Criteria 
Need `disabled` property to gray out the switch, preventing toggle.

#### Which Component
Calcite Switch

#### Example Use Case
Configuration app still needs to display options that are dependent on a conditional setting. But need to disable the switch if conditional setting is toggled off. 

Sample: 
https://codepen.io/rslibed/pen/KKzVVdX

**Comment by macandcheese** [comment]
Will go out next release @rslibed
