### ISSUE TITLE
Enhancement: CalciteStepper

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#862]
### Description
Enhance CalciteStepper 

- [ ] Ability to have no icon
- [ ] Ability to have no "complete" on any steps
- [ ] Allow vertical layout

### Acceptance Criteria 
Don't break stuff.

### Relevant Info 
https://github.com/Esri/calcite-components/issues/743

#### Which Component
CalciteStepper

#### Example Use Case
Stuff.

**Comment by macandcheese** [comment]
It does these things already 😄 

`icon` is opt-in along with `numbered`, so you can leave that off. Step status (`active`, `complete`, `error`) is set via prop,  so you can just not put `complete` on the steps. And `layout="vertical"` should give you a vertical layout :)

```
<calcite-stepper layout="vertical" numbered>
    <calcite-stepper-item item-title="Choose method" item-subtitle="Some subtext">
        <calcite-notice active width="full">
            <div slot="notice-message">Step 1 Content Goes Here</div>
        </calcite-notice>
    </calcite-stepper-item>
    <calcite-stepper-item item-title="Compile member list" item-subtitle="Some subtext">
        <calcite-notice active width="full">
            <div slot="notice-message">Step 2 Content Goes Here</div>
        </calcite-notice>
    </calcite-stepper-item>
    <calcite-stepper-item item-title="Set member properties" item-subtitle="Some subtext">
        <calcite-notice active width="full">
            <div slot="notice-message">Step 3 Content Goes Here</div>
        </calcite-notice>
    </calcite-stepper-item>
    <calcite-stepper-item item-title="Confirm and complete" item-subtitle="Some subtext">
        <calcite-notice active width="full">
            <div slot="notice-message">Step 4 Content Goes Here</div>
        </calcite-notice>
    </calcite-stepper-item>
</calcite-stepper>
```

**Comment by macandcheese** [comment]
@asangma does the above config work for that example?

**Comment by julio8a** [comment]
Seems like this one is good to close? 

Please re-open if necessary.

**Comment by macandcheese** [comment]
Yeah it already did all the requested items, safe to close.
