### ISSUE TITLE
Enhancement: Default icon for input type="email" should be "email-address"

### ISSUE THREAD

**Issue by gpbmike** [Esri/calcite-components#864]
Can I petition to have the default icon for input type email changed from 'send' to 'email-address'? "Send" is an action, probably more fitting on a button.

# Suggested new icon

https://esri.github.io/calcite-ui-icons/#email-address

# Location of code

https://github.com/Esri/calcite-components/blob/947b8cade8cee5ccd6629daaabffb5db11c2e89d/src/components/calcite-input/calcite-input.tsx#L413-L421

# Current icon top, suggested icon bottom

![image](https://user-images.githubusercontent.com/8754/90171529-7e0e1700-dd56-11ea-847d-7b888d3eaab4.png)

**Comment by macandcheese** [comment]
I think this would be a good improvement!

Just as an FYI, even with the input types that have default icons, it's still possible to override by passing an icon name string to the `icon` attribute, ie `<calcite-input icon="banana" type="email" placeholder="john@doe.com"></calcite-input>`

**Comment by gpbmike** [comment]
Thanks for the tip. We are using the override but thought I would make the suggestion as well.

**Comment by macandcheese** [comment]
@gpbmike - Yep, it's a good update - that icon was added pretty recently to the Calcite UI Icon set, I wasn't even aware it was there 😆 . Installed via #865 - will go out next release as the default!
