### ISSUE TITLE
Enhancement: Color - Supercharge color input functionality ⚡⚡⚡

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#866]
### Description
Add some spice 🌶️ to how we handle keyboard interactions with inputs:

#### Which Component
Color

#### Example Use Case

**HSV / RGB**
- Holding `shift + arrow up / arrow down` should increment / decrement the value by 10. If the value is within 10 of the upper / lower bound - set to that.

| Sketch | Figma |
| --- | --- |
|![Screencast 2020-08-13 at 12 53 10 PM (1)](https://user-images.githubusercontent.com/4733155/90180923-84a38b00-dd64-11ea-8c62-d03b038cb392.gif) | ![Screencast 2020-08-13 at 12 53 45 PM](https://user-images.githubusercontent.com/4733155/90180900-7c4b5000-dd64-11ea-8100-ee4fc7329aea.gif) |

**HEX**
This is only something I've seen from Figma, but it's pretty cool. Arrow Up / Down will increment / decrement the HEX Value, doing it in combination with Shift will increase the step.
![Screencast 2020-08-13 at 12 54 16 PM](https://user-images.githubusercontent.com/4733155/90180878-72c1e800-dd64-11ea-955d-8468083302b9.gif)

Related : This should help number inputs generally (accelerate speed when keys are held down) : https://github.com/Esri/calcite-components/issues/782

**Comment by bstifle** [comment]
woot!

**Comment by jcfranco** [comment]
@macandcheese Nice. Shouldn't this be labeled as a `calcite-input` enhancement?

**Comment by macandcheese** [comment]
> @macandcheese Nice. Shouldn't this be labeled as a `calcite-input` enhancement?

Hm.. I was thinking it was only really applicable to the color picking workflow and would just handle it in that component and not change anything with underlying input. 

Similarly the "shift key and arrows" in HEX input I would feel could be handled in the color-hex-input component (and also maybe as a follow up issue)?

The issue I linked above though certainly is input although only... somewhat related to this: https://github.com/Esri/calcite-components/issues/782.

**Comment by jcfranco** [comment]
Fair enough. 😄 I'll tackle both in the same since they're similar.

**Comment by jcfranco** [comment]
Installed! 

@macandcheese If you have some time, can you verify this one?

**Comment by macandcheese** [comment]
Verified on master. Looks good @jcfranco !

**Comment by jcfranco** [comment]
@macandcheese Thanks!
