### ISSUE TITLE
Enhancement: Modal — Add progress indicator prop to header section

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#868]
Design:

![image](https://user-images.githubusercontent.com/14083530/90199762-82542780-dd8a-11ea-8032-31e014d79cd2.png)
![image](https://user-images.githubusercontent.com/14083530/90199777-897b3580-dd8a-11ea-943e-8dd07d42e03d.png)
![image](https://user-images.githubusercontent.com/14083530/90199938-f8f12500-dd8a-11ea-97d5-447a70920c97.png)

**Comment by macandcheese** [comment]
This will cause long modal header text to wrap at small modal sizes and in mobile. Can you add comps of that?

**Comment by macandcheese** [comment]
We will also need to make sure this can be translated / localized. I know @mitc7862 / @asangma might have some considerations from experience with "this of that" values in Online.

**Comment by benelan** [comment]
Closing this issue. If this comes up again in a different issue we can take a closer look
