### ISSUE TITLE
Enhancement: Label - update margin-bottom based on scale prop

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#872]
### Description
Consider making the `margin-bottom` relative to the `scale` prop, i.e. `scale="s"` would be smaller.

#### Which Component
CalciteLabel

**Comment by asangma** [comment]
cc @bstifle what you think about making a stack of small inputs be a bit tighter and visa versa?

**Comment by macandcheese** [comment]
Agreed!

Should probably have margin values that correspond to all three scales. Since these will hopefully be used to wrap all kinds of controls this will help the spacing of all form control groups

**Comment by bstifle** [comment]
100%

**Comment by macandcheese** [comment]
@asangma @bstifle what values do we want for each of these? We might want to have the margin-bottom by default as it currently is to enforce good spacing, but also have a prop for `no-margin` to allow label / input lockups to be used without the spacing if needed, like at the bottom of a panel or something where spacing exists outside of the component.

**Comment by bstifle** [comment]
Ive been using 4px underneath all the labels. the line-height makes up for increase in scale

**Comment by macandcheese** [comment]
I think this is referring to spacing applied to the bottom of the label's container, ie what is the spacing underneath an input wrapped with the label (applies to inline and inline-space-between as well).

**Comment by bstifle** [comment]
oh...

8, 12, 16 then
