### ISSUE TITLE
Bug: Tabs registryHandler is throwing error when tabs are removed from DOM

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-components#873]
### Summary

Bug: Tabs registryHandler is throwing error when tabs are removed from DOM

### Expected Behavior

Should not error when an id of a  tab can't be found.

### Reproduction Steps

1. Go to storybook for tabs: https://esri.github.io/calcite-components/?path=/story/tabs--simple
2. Navigate to the dark theme tabs story
3. Notice error in console:

> p-9363d789.entry.js:1 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined

> (anonymous) | @ | p-9363d789.entry.js:1
> -- | -- | --
> | registryHandler | @ | p-9363d789.entry.js:1

### Relevant Info 

Any browser

**Comment by caripizza** [comment]
@driskull is this still an issue?

**Comment by driskull** [comment]
This has been fixed
