### ISSUE TITLE
Checkbox input field event handler is not being called

### ISSUE THREAD

**Issue by svlesiv** [Esri/calcite-components#874]
### Summary
According to the [documentation](https://esri.github.io/calcite-components/?path=/docs/checkbox--dark-mode), an input field with a type of checkbox can be added as a child of `<calcite-checkbox>` component, and onChange event should work for the input field. However, it seems that the onChange event handler is not being called. Is it the expected behavior?

### Reproduction Steps
1. In React framework, add an input field with a type checkbox as a child of `<calcite-checkbox>` component.
2. Add onChange event for the input field.
3. The input field handler will not be called when clicking on the checkbox.

### Relevant Info 
https://codepen.io/svlesiv/pen/Rwarrpr

**Comment by eriklharper** [comment]
Passing an input is no longer supported, so the documentation will reflect that once this pr is merged: #1247
