### ISSUE TITLE
Enhancement: ValueListItem & maybe also ValueList

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#885]
### Description
Add prop to disable selection: `disableSelect`
Should ValueList also get this prop and children items receive the value?

The ValueList is used to show the selected or active items (often fields from a data set). And in many of those cases, this list of selected fields does not benefit from a selected state.

### Acceptance Criteria 
* don't break stuff

#### Which Component
* ValueListItem
* ValueList maybe too?

#### Example Use Case
User clicking on one of these will result in an unnecessary selected state.
![Screen Shot 2020-08-19 at 9 03 35 AM](https://user-images.githubusercontent.com/12503298/90660845-4b9f6680-e1fb-11ea-9d8e-5fec35583ba8.png)

**Comment by julio8a** [comment]
@asangma, this is still something to work on?

**Comment by macandcheese** [comment]
@asangma is this still valid?
