### ISSUE TITLE
Bug: Steppers not working on numeric calcite-input

### ISSUE THREAD

**Issue by pemberdom** [Esri/calcite-components#886]
### Summary
The steppers are not working anymore on a numeric calcite-input.

### Actual Behavior
Since Calcite Components beta 37, the steppers up/down don't trigger anymore the `calciteInputInput` event handler.
The value changes in the input when we use them, but the event handler is never called.
Changing the value directly in the input works well though.

![image](https://user-images.githubusercontent.com/45367780/90671234-434e2800-e209-11ea-8769-3f5e11e5f4cd.png)

### Expected Behavior
Clicking on the up/down buttons triggers the `calciteInputInput` change and the associated handler is called.

### Relevant Info 
Since Beta 37. Tested on Firefox and Chrome

**Comment by macandcheese** [comment]
Addressed in https://github.com/Esri/calcite-components/pull/888

**Comment by macandcheese** [comment]
Verified.
