### ISSUE TITLE
Enhancement: Add focus utility - ShellPanel, Panel

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#890]
### Description
Developers are manually setting focus to the X close button on panels being opened in ShellPanel.
This is a standard a11y pattern that we should encourage and enable.

I propose a utility that assists this kind of pattern

1. user create a ShellPanel with an ActionBar
1. user relates an Action (from ActionBar) to a Panel that will appear in ShellPanel's content area
1. user does something like `setFocusOn(emitter, selector)`...probs something better than that.
1. when Panel is "loaded" 🍺 , it emits
1. a handler sets focus to the element*

*For good a11y usability, it'd be awesome if the ShellPanel and Panel and stuff could play nice together and out-of-the-box set focus on the close button of Panel.

Note: I know this is all probably 35% wrongly stated.

A related enhancement would be to make Panel not so generic and to push a lot of the styling and work that FlowItem is doing in its header into Panel's header. #891

**Comment by driskull** [comment]
Seems to me like this should just be a utility within the app. Whenever a panel is created, it also sets focus to that panel's close button.

The only way I can think of handling this would be adding a prop `autoFocus` that automatically sets focus to a component when it is connected to the DOM. like `autoFocus="dismiss-button"`

**Comment by asangma** [comment]
At the moment, a version of this is being done in MVB. 
I think this is a basic a11y pattern, and any app using the ShellPanel (ActionBar + Panel) pattern should get that out-of-the-box.

As it is now, each user has to a) know that this is the suggested a11y pattern and b) implement it.
We already see inconsistency in MVB and are having to QA for it.

Note: I had a quick chat with Kevin about this, and he said he'd love to see it be built in.

**Comment by julio8a** [comment]
Is this issue still valid?
