### ISSUE TITLE
Enhancement: Make Panel less generic

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#891]
### Description
Make Panel not so generic.
Push a lot of the styling and work that FlowItem is doing in its header into Panel's header.

At the moment, we rarely if ever need a generic "panel". As such users are often using FlowItem when there is no Flow because it comes with all the styles and things like a heading and subheading.

Users should still be able to override the header slot with their own content.

Should probably also make `dismissible` true by default.

### Acceptance Criteria 
* don't break stuff
* maybe add `dismissible` prop

#### Which Component
* Panel
* FlowItem

#### Example Use Case
Most panels in Map Viewer Beta.

**Comment by asangma** [comment]
@driskull @jcfranco The proposal here is to move some of the props like the heading, summary, leadingActions, and trailingActions into Panel. FlowItem would hydrate those slots. 

I think we could still keep a `header` and `footer` slot in Panel that would still override the default structure. That would keep any existing uses of Panel from breaking and keep it flexible.

**Comment by driskull** [comment]
Sounds good. If We could just remove FlowItem and enhance Panel to do all the stuff it does if that makes more sense.

**Comment by asangma** [comment]
@driskull I was thinking something similar. What do you think about making the transition easier for users by doing this?
 
* enhancing the Panel
* keeping the FlowItem as a wrapper
* deprecating FlowItem

Ideally after the enhancement, users should be able to use either Panel or FlowItem in a Flow.

**Comment by driskull** [comment]
That sounds like a good plan
