### ISSUE TITLE
Bug: calcite-date - constantly updating the min/max attributes on native input

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#896]
### Summary

https://esri.github.io/calcite-components/?path=/story/components-date--simple

Using the storybook sample for calcite-date, if you inspect the  native input element you will see that the min/max attributes are constantly being updated, you can debug by right clicking on the native input, selecting break on attribute modifications and you will notice it just contantly calls `this.syncProxyInputToThis`, 

![image](https://user-images.githubusercontent.com/11093161/90784974-b2ce2100-e2b6-11ea-9599-97e9f125183f.png)

### Expected Behavior
I think it should only update when necessary

### Reproduction Steps

1.

**Comment by paulcpederson** [comment]
@kevindoshier I think my latest bug fixes on the date component fixed this as well, let me know if you're still seeing it with the latest release.

**Comment by kevindoshier** [comment]
Thanks Ill take a look
