### ISSUE TITLE
[Panel & Flow Item]: Refactor `"footer"` slot to account for `modal`

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#8981]
### Description
Currently the `panel` and `flow-item` have a `"footer"` slot, however to accommodate the Dialog + Modal component effort in https://github.com/Esri/calcite-design-system/issues/7886, we may need to account of additional footer slots, such as `"footer-start"` and `"footer-end"` to match the "back / secondary / start" currently offered in the `modal` component.

### Acceptance Criteria

Refactor `panel` and `flow-item` footer to include `footer-end` & `footer-start` slots with no built in spacing between or within slots

### Which Component
- `panel`
- `flow-item`

### Relevant Info
A dependency needed for the Dialog + Modal component effort in https://github.com/Esri/calcite-design-system/issues/7886

See [Figma file](https://www.figma.com/file/wVqftT1aZDjwYVkDZ2V5fC/Dialog?type=design&node-id=621-5496&mode=design&t=9PfAlfhXFoN5YOXS-11) for specs
<img width="1620" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/61eca8fc-4e0a-463e-a032-e4094402d4f8">

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by macandcheese** [comment]
Not sure if this applies to Card cc @ashetland @SkyeSeitz - I think it may have just been mentioned as a component that has footer-start/end slots.

**Comment by SkyeSeitz** [comment]
Agreed. I believe the idea was to confirm if we wanted more consistency between footers across components or if Card should be unique.

**Comment by Elijbet** [comment]
Can we determine the best approach for the footer slots? In most use cases do we want the footer as is without the need for start/end slots or is it the other way around? I'm wondering if the footer needs to be deprecated.

@ashetland @SkyeSeitz @macandcheese

**Comment by Elijbet** [comment]
From what I gather so far after speaking with @macandcheese and @geospatialem , `footer-start/end` will live alongside `footer`:
 
- `footer` - for non modal/dialog scenarios
- `footer-start` - to support modal/dialog components (future)
- `footer-end` - to support modal/dialog components (future)

The question there is what happens when the footer and one or both of the new footer-start/end are populated? Do the new slots take precedence? 

In the case of the `panel`, there is a `header-content` in addition to `header-actions-start/end` and they display next to each other. Would it make sense for the `footer-start/end` to just appear "around" the `footer` slot?

**Comment by ashetland** [comment]
Added `visual changes` due to default padding changes in the footer.

**Comment by geospatialem** [comment]
The `panel` is good to go in `2.10.0-next.10` via https://codepen.io/geospatialem/pen/PovBzKM 👍🏻 , but it looks like the `flow-item`'s slots are reversed as depicted in https://codepen.io/geospatialem/pen/pomZbwE. 

![image](https://github.com/Esri/calcite-design-system/assets/5023024/35f280be-451b-4fd5-8e98-b1b97c9ff147)


Sending back to development for follow-up prior to release.

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`. 

`flow-item` slots are ordered correctly now 👌![image](https://github.com/Esri/calcite-design-system/assets/60022782/5527ee9d-e5e0-4eba-ba18-a5f4b19a5fb6)

**Comment by driskull** [comment]
@DitwanP @geospatialem this introduced a regression. The following CSS prop isn't being honored anymore: https://github.com/Esri/calcite-design-system/commit/3def3ea51bc69dfd1ebefc6a1ef2bcfe0bdc943c#r144045487

`--calcite-panel-footer-padding`
