### ISSUE TITLE
calcite-components and calcite-app-components UI consistency

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#902]
### Description
Since we're merging the calcite-app-components into calcite-components we need to make sure we have clear UI consistency with foundations usage (colors, type-scale, spacing, etc) and overall components UI. Dependant on #687

---

Moved from #689 

I think a large portion of this will be standardization around hitboxes for controls that would be adjacent to the edge of a container, ie: 

<img width="569" alt="Screen Shot 2020-07-06 at 12 12 42 PM" src="https://user-images.githubusercontent.com/4733155/86630863-3d1a2a00-bf82-11ea-9779-f4b08723a41a.png">
<img width="160" alt="Screen Shot 2020-07-06 at 12 12 22 PM" src="https://user-images.githubusercontent.com/4733155/86630867-3db2c080-bf82-11ea-88c6-161f1497cc3c.png">

vs. 

<img width="514" alt="Screen Shot 2020-07-06 at 12 13 36 PM" src="https://user-images.githubusercontent.com/4733155/86630856-3be8fd00-bf82-11ea-8544-c289ef72b0be.png">
<img width="569" alt="Screen Shot 2020-07-06 at 12 13 00 PM" src="https://user-images.githubusercontent.com/4733155/86630859-3c819380-bf82-11ea-84e3-e040ea22d08d.png">

**Comment by asangma** [comment]
@macandcheese @julio8a @bstifle @mitc7862 

I've done a basic UI alignment on all the newly ported components.
note: This does not include dealing with the zoology of our component, i.e. what components can be merged, which should stay separate, etc.

Please review.

If you see particular UI issues feel free to create new issues.

**Comment by macandcheese** [comment]
Safe to close @asangma ?
