### ISSUE TITLE
Bug: date -- input field doesn't support years before 1000

### ISSUE THREAD

**Issue by bsvensson** [Esri/calcite-components#905]
### Summary

The data picker doesn't seem to like years before year 1000.

### Actual Behavior

* Typing in year 999 doesn't "do" anything.

### Expected Behavior

* That year 999 works the same way as any other 1000 and onward year.

### Reproduction Steps

1. Go to https://esri.github.io/calcite-components/?path=/story/components-date--simple
2. Under **Knobs**, remove the min and max
3. Try to use the input field to navigate to year 999. It doesn't work, but year 1000 works fine.  It also works fine if you use the back arrows.

Same problem if you try to type it into the smaller year field next to the spelled out month.

![image](https://user-images.githubusercontent.com/808357/91228703-90386f80-e6dd-11ea-8dc7-63d2f6d4ff2b.png)

### Relevant Info 

Chrome `Version 84.0.4147.135 (Official Build) (64-bit)` on Windows 10.

**Comment by paulcpederson** [comment]
This should be in the latest release.
