### ISSUE TITLE
Bug: date -- for Japanese, only 3 digits of the year shows in the calendar picker

### ISSUE THREAD

**Issue by bsvensson** [Esri/calcite-components#907]
### Actual Behavior

Shows "020" instead of "2020". 
![image](https://user-images.githubusercontent.com/808357/91236338-85390b80-e6ec-11ea-879e-a0b606578890.png)

### Expected Behavior

Showing 4 digits of the year.

### Reproduction Steps

1. Go to https://esri.github.io/calcite-components/?path=/story/components-date--simple
2. Under **knobs**, set the **locale** to **ja** for Japanese

### Relevant Info 

Tested on Chrome and Firefox, both on Windows 10.

**Comment by paulcpederson** [comment]
This should be in the latest release.
