### ISSUE TITLE
Bug: [calcite-label] does not adjust spacing in RTL context

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#912]
### Summary

Margin of label content is not applied correctly in RTL.

### Actual Behavior

The label content has a left margin when `dir=rtl`.

### Expected Behavior

The label content has no left margin and right margin applied when `dir=rtl`.

### Reproduction Steps

[This codepen](https://codepen.io/jcfranco-the-scripter/pen/eYZRNwW?editors=1000) demonstrates the issue.

**Comment by macandcheese** [comment]
Whoops, must have happened in the last updates to how label was structured. I'll get this out with a few other items I'm working on re: label.

**Comment by jcfranco** [comment]
Awesome, thanks!
