### ISSUE TITLE
Enhancement: Slider: Align with edge of container

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#913]
### Description
Currently a slider at min / max extends past the edge of the container, which causes some misalignment when presented in a form. 

### Acceptance Criteria 
Compensate for the extra widht of the slider handle and make it align with the edge of container.

|   |   |
|---|---|
|  Current | Desired  |
| <img width="512" alt="Screen Shot 2020-08-28 at 10 54 31 AM" src="https://user-images.githubusercontent.com/4733155/91600619-1db5d280-e91d-11ea-89e9-e212f5d985a8.png">  |  <img width="512" alt="Screen Shot 2020-08-28 at 10 54 20 AM" src="https://user-images.githubusercontent.com/4733155/91600625-23131d00-e91d-11ea-853c-41932e2174e2.png"> |

#### Which Component
Slider

**Comment by julio8a** [comment]
Is this one still valid? If so, what's the status? Maybe this is something I can work on or @bstifle 

Seems like a low priority one though and might get fixed with the spacing scale that gets implemented to all the compnents?

**Comment by macandcheese** [comment]
Wouldn't get fixed with spacing, it's about where the slider rests at the high / low bounds. You can see here: https://esri.github.io/calcite-components/?path=/story/components-label--wrapping-components-other-than-input

Low priority but should keep open so we can address it at some point.

**Comment by julio8a** [comment]
Thanks @macandcheese

**Comment by jcfranco** [comment]
Verified w/ latest storybook: https://esri.github.io/calcite-components/?path=/story/components-label--wrapping-components-other-than-input

![Screen Shot 2021-09-09 at 1 27 05 PM](https://user-images.githubusercontent.com/197440/132757918-1f2ffde5-c72a-4a45-8782-732c02e4b14b.png)
