### ISSUE TITLE
Bug: calcite-label - Add no-margin prop

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#916]
### Summary
I'm using `calcite-label` in the 2 marked cases (one time with `calcite-action`, the other with `calcite-button`, and one empty). The bottom margin that is automatically applied is too big, how can I remove it?
<img src=https://user-images.githubusercontent.com/44481292/91616430-85c6e180-e93a-11ea-934e-45e2f8138597.png width=200/><img src=https://user-images.githubusercontent.com/44481292/91616228-236de100-e93a-11ea-93f6-77a2c5ac62b4.png width=200/><img src=https://user-images.githubusercontent.com/44481292/91622232-f70e9080-e94a-11ea-8e31-6e71b3d20b07.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/91616285-3ed8ec00-e93a-11ea-9add-cca3336301a2.png width=300/>

I would like to have a look similar to this.
<img src=https://user-images.githubusercontent.com/44481292/91616559-c6bef600-e93a-11ea-89b2-1e807f816d6b.png width=200/><img src=https://user-images.githubusercontent.com/44481292/91617444-ef47ef80-e93c-11ea-8772-af1d036248e8.png width=200/>

### Reproduction Steps

1.

**Comment by macandcheese** [comment]
Hey @AdelheidF - we did just adjust the values for margin-bottom on labels in https://github.com/Esri/calcite-components/pull/914 (12/16/20px for s/m/l), which should be a bit smaller than we have now, but it seems like a "noMargin" prop would be useful for cases like you show above.

There is precedent in both `calcite-loader` and `calcite-modal` (`noPadding`) for a prop like that - although this will be the first with `noMargin` I think it's justified here.

**Comment by AdelheidF** [comment]
`disable-spacing` works fine now, but I get a weird look if I apply padding to the `calcite-label` directly. I have to apply it to the surrounding `div`.

**Comment by macandcheese** [comment]
Can you share an example of what it looks like / should look like? Padding to left / right should be handled by "inline" / "inline-space-between" layout prop values, if possible. If not we can look for another fix.

**Comment by AdelheidF** [comment]
> Can you share an example

<img src=https://user-images.githubusercontent.com/44481292/92537713-ad972e80-f1f1-11ea-9564-fec60bee9e4a.png width=200/>

<img src=https://user-images.githubusercontent.com/44481292/92537630-7759af00-f1f1-11ea-84c4-ccc43286533e.png width=400/>
<img src=https://user-images.githubusercontent.com/44481292/92537649-82acda80-f1f1-11ea-8948-b7c25b949fc6.png width=200/>

setting padding on the surrounding div instead

<img src=https://user-images.githubusercontent.com/44481292/92537795-e8996200-f1f1-11ea-830e-922171d7cdbd.png width=200/>

**Comment by AdelheidF** [comment]
this is good now

<img src=https://user-images.githubusercontent.com/44481292/99992440-30e50c80-2d6b-11eb-8d2c-6d2ca542aabf.png width=200/>
