### ISSUE TITLE
Enhancement: calcite-color, what about a placeholder color?

### ISSUE THREAD

**Issue by pemberdom** [Esri/calcite-components#917]
### Description
In some situations we might want to display a placeholder on a color picker.
If a user selects multiple elements all handled by a unique color picker, we'd like to have a mixed or placeholder color displayed.
The idea would be to have a property, to either switch the picker in placeholder mode, or being able to choose an `undefined` default color, which would display the placeholder (dashed symbol, empty square...).

#### Which Component

calcite-color

#### Example Use Case

- element 1 is red
- element 2 is red
- element 3 is green

- the user selects element 1 => color picker displays red
- the user selects elements 1+2 => color picker displays red
- the user selects elements 1+2+3 => color picker displays placeholder color

**Comment by pemberdom** [comment]
Completing the issue: an alternative for our need would be to open the color picker without defining any color.
Right now if the `value` property is not defined, the default `#007AC2` will kick in.
It could be interesting to not default that value (through a parameter?), in order to get an empty color picker: all the inputs would be empty, no color selected on the slider and the canvas.

**Comment by jcfranco** [comment]
@bstifle WDYT? IMO, displaying all supporting input components as empty isn't ideal, but I can't think of another way to convey a no-color state for them.

Going back to the example use case, could you try using a color object + `https://github.com/Qix-/color/`'s `mix()` to update the 3rd color picker's value? It _should_ handle the mixed color properly.

**Comment by bstifle** [comment]
im fine with nothing in the inputs for that case.

i think generally, a good default would be 255,255,255 or 0,0,0

**Comment by jcfranco** [comment]
> im fine with nothing in the inputs for that case.

A-🆗 

> i think generally, a good default would be 255,255,255 or 0,0,0

I think it'll be odd to not have a color selection while showing the values for white or black.

---

@pemberdom do you also need a way to unset a color once selected? If so, we may need an empty color option to the UI (🚫).

**Comment by pemberdom** [comment]
> I think it'll be odd to not have a color selection while showing the values for white or black.

Yeah, in our use case 255,255,25 or 0,0,0 are valid values the user could choose by themselves, so it wouldn't convey the proper information in our scenario.

> @pemberdom do you also need a way to unset a color once selected? If so, we may need an empty color option to the UI (🚫).

Nope, I can't think of a scenario where we'd allow our users to unset a color.
If the point was to reset the color to its default, we'd need the color picker to display that default color.
It the point was to hide the element by unsetting its color, we prefer provide explicit switches in the UI to do so.

That said, having an empty color option sounds nice :), it would likely answer our need.

**Comment by pemberdom** [comment]
To provide more information about the use case: we are working on an UI to author charts.
By default a chart has 1 unique color per series, hence 1 color picker per series.

Now, there's a special mode where the user can ask the chart to match the Feature Layer renderer, which can lead to a series using multiple colors (I spare some details).
In that case we have to deal with our unique color picker, and provide a visual information to say "Hey, we can't pick one color for that series because it's using multiple ones".
If the user opens the color picker for that multi color series, and then choose a specific color, it would apply that unique color to all the series, and we'd get back to normal.

**Comment by jcfranco** [comment]
Installed!

@pemberdom Could you help verify this one?

**Comment by pemberdom** [comment]
> Installed!
> 
> @pemberdom Could you help verify this one?

Sure. Is there a way to import the `@next` version through a script tag?

**Comment by jcfranco** [comment]
You could point it to "http://unpkg.com/browse/@esri/calcite-components@next/".

**Comment by pemberdom** [comment]
First tests look good, I'll do some more.
One thing though, about the doc mentioning `value: the type will be preserved as the color is updated`:
When the color picker is initialized with `null`, the following `onCalciteColorChange` payload carries colors using the hex format. 
In our code when we initialize it with a proper color, we use the RGB format, which is more convenient to deal with.
Ideally an extra parameter allowing us to set the desired format would be nice, but for now we'll to add some conversion lines to deal with both RGB and hex.

**Comment by jcfranco** [comment]
Yeah, being able to set the format would be a good enhancement. As a workaround, I think you could initialize with a color object before `value` gets set to null.

**Comment by pemberdom** [comment]
> As a workaround, I think you could initialize with a color object before value gets set to null.

Yeah I though about that but I feel it will fire an extra `onCalciteColorChange` which will trigger our listener, so I wanted to avoid it.
For now it's all good though. I can open an enhancement request for the format, as enforcing the format can be useful in different situations.

**Comment by jcfranco** [comment]
> I can open an enhancement request for the format, as enforcing the format can be useful in different situations.

👍
