### ISSUE TITLE
Bug: calcite-modal - Inconsistent close behavior

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#918]
### Summary
The Escape key and close button operate differently when closing a modal.

### Actual Behavior

These two snippets show the differences in code between hitting Escape and clicking the close button. As a result, there's a bug where if you click the close button, you can't reopen the modal.

```
// Inside close function
return this.beforeClose(this.el).then(() => {
  this.isActive = false;
  this.previousActiveElement?.focus();
  document.documentElement.classList.remove("overflow-hidden");
  setTimeout(() => this.calciteModalClose.emit(), 300);
});
```

```
// Inside Escape key handler
this.beforeClose(this.el).then(() => {
  this.active = false;
});
```

### Expected Behavior

The behavior should be consistent and you should be able to open and reopen the modal repeatedly.

### Reproduction Steps

1. Set the modal `active` prop to true to open the modal
2. Click the close button to close the modal.
3. Now, set the `active` prop to true again. Nothing will happen.
4. Reset the page and repeat step 1.
5. This time, hit Escape to close the modal.
6. Now, set `active` to true again. It will open as expected.

**Comment by macandcheese** [comment]
Should be resolved in https://github.com/Esri/calcite-components/pull/1139#event-3901313088
