### ISSUE TITLE
Enhancement: calcite-button with text align options

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#922]
### Description
For Map Viewer Beta 9 (September)

<img src=https://user-images.githubusercontent.com/44481292/91760942-febb7880-eb88-11ea-8b31-dba4d46e1b54.png width=200/>

The yellow marked components are `calcite-dropdown` with a `calcite-button`. The red marked component is just a `calcite-button`. I would like to have all text left (leading) aligned and if there is an icon, the icon to be on the very end of the button (trailing).

This is how it looks with HTML `<select>` 
<img src=https://user-images.githubusercontent.com/44481292/91760470-47befd00-eb88-11ea-8033-649f65c75346.png width=200/>

cc @asangma

**Comment by macandcheese** [comment]
I think we may need to just bite the bullet on this one : https://github.com/Esri/calcite-components/issues/302

**Comment by AdelheidF** [comment]
Note: I'm running into issues with the dropdown width if I use `calcite-dropdown/calcite-button`. `width=s` doesn't solve it.

<img src=https://user-images.githubusercontent.com/44481292/91781102-528c8880-ebae-11ea-9cd9-305b12701b8f.png width=200/>

**Comment by macandcheese** [comment]
Looks like https://github.com/Esri/calcite-components/issues/404 would have taken care of that. That's a place where a select would probably work as well. You could do alignment=end on dropdown but that's just a stopgap until the "width as narrow as trigger" is done.

**Comment by asangma** [comment]
Thanks @macandcheese.

I do think it's still valid to get the Button to have a `space-between` layout so that in either LTR or RTL

* the text is aligned start
* end icon is aligned end
* start icon is aligned start

**Comment by asangma** [comment]
Alternatively, we could enhance and use Action for these use cases.
Keep Button for the higher level functions like Save, Cancel, Done, etc.

**Comment by macandcheese** [comment]
OK, I do think calcite-select will solve for the presented use case, but I could see wanting to launch a dropdown / popover / kitten image from a button that had the styles as described.

A consideration is that we'd need a good bit of spacing from the "space-betweened" icon and text so that if this wasn't in a full-width button situation, there would be enough space so that it didn't look like a regular button. Would a "layout" prop that defaulted to current, and accepted a "space-between" value work?

**Comment by asangma** [comment]
> Would a "layout" prop that defaulted to current centered ("default"), and accepted a "space-between", "start", and "end" value work

Probably. But the more I think of it, the centered text works really nicely for things like Cancel, Save, Submit, OK, etc.

I think we should start looking at enhancing Action for these inline use cases.

**Comment by macandcheese** [comment]
I really think that will just add confusion for users. When do I use an action vs. button? A button is a more standard UI element.

I wasn't suggesting changing the default behavior of buttons at all - that would remain centered as folks might expect a button to be - just adding an optional prop to address this issue's use case.

**Comment by asangma** [comment]
I think we can learn if it'd cause confusion.
We've seen use from distinguishing things like value-list and pick-list. And if there are distinct UI differences between say a button and an input, that's cool and makes sense. But we have use cases where we need a control that is inline with inputs, switches, etc. in a panel and shouldn't be too distinct.

The Button on the other benefits from being distinct.

I think it's not a difficult thing to make it easy to distinguish the two components. Buttons would generally be primary actions and live at the bottom of interfaces. Actions are non-primary and inline.

**Comment by macandcheese** [comment]
I don't know... an actionable element inline with an input is a button. I think that's a way more common nomenclature that requires no learning curve or documentation. I'm up for enhancing the button to satisfy more use cases outside the default, but I'm not sure fragmenting "things that look and feel like buttons to users" is necessary. Of course just IMHO :)

**Comment by AdelheidF** [comment]
> [calcite-button] the text is aligned start

Could we get this enhancement for map viewer beta 10 (end of October)?

**Comment by macandcheese** [comment]
Alignment would only work on `width="full"` due to how buttons are spaced... is this a stop gap until `calcite-input` is here?

**Comment by asangma** [comment]
@kat10140 Mind helping verfee?

**Comment by AdelheidF** [comment]
Great, could you let me know once it's part of a next or full release?

**Comment by asangma** [comment]
@AdelheidF 
Next builds are being done manually right now.
There are some tests that need to get fixed before the next `@next` release.

**Comment by AdelheidF** [comment]
Cool, `alignment=start` works well.

<img src=https://user-images.githubusercontent.com/44481292/100040627-7b42a980-2dbc-11eb-849a-50f92090c7a6.png width=200/>

RTL
<img src=https://user-images.githubusercontent.com/44481292/100040685-9b726880-2dbc-11eb-9533-3b3d85195d5e.png width=200/>
