### ISSUE TITLE
Enhancement: Reduce all "highlight bar" indicators to 2px to fit within new scale

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#924]
![image](https://user-images.githubusercontent.com/14083530/91777274-44d20580-eba4-11ea-92ff-75b9476c536d.png)

- [x] Alert
- [x] Modal
- [x] Notice
- [x] Pagination
- [x] Stepper
- [x] Tab
- [ ] Tree
- [ ] etc?

**Comment by julio8a** [comment]
This one is tied to the refactor

**Comment by caripizza** [comment]
Looks to me like the only ones left to address adjust here are in Tree and Modal, does that sound correct?

**Comment by bstifle** [comment]
@caripizza i think this is done. Modal, we decided to keep 4px. Tree should no longer have the highlight bar as a selected state, so that will go away, i gonna call this one donezo!
