### ISSUE TITLE
Enhancement: Button

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#926]
### Description
Add or update a color to match the input border color.

**Comment by asangma** [comment]
cc @AdelheidF

**Comment by macandcheese** [comment]
Could you add a screenshot of this / use case? Thanks.

**Comment by asangma** [comment]
It looks like Button in light mode is using vars for foreground instead of border vars.
It would be an easy update, but @bstifle should chime in.

**Comment by asangma** [comment]
Alternatively (like with #922), we could enhance and use Action for these use cases.
Keep Button for the higher level functions like Save, Cancel, Done, etc.

**Comment by macandcheese** [comment]
I don't think we should add any extra functionality or styles to action that would conflate with button. I think the input borders will become much darker due to Arjav's accessibility findings - I'll let cc @bstifle figure out the border / button color nuances :)

**Comment by AdelheidF** [comment]
This is my use case. Two `calcite-button`s and one `calcite-input` (this has darker borders). 

<img src=https://user-images.githubusercontent.com/44481292/91877013-4944ff80-ec32-11ea-80b8-71d05f31e34c.png width=200/>

**Comment by bstifle** [comment]
I dont think it's a great idea to make buttons look like inputs. 

Additionally, inputs will be using #949494 (blk-100) based on accessibility fixes. 

suggest just using this button
![image](https://user-images.githubusercontent.com/14083530/91881947-223cfc80-ec37-11ea-9247-f0b7eb8ac4a6.png)

**Comment by bstifle** [comment]
here's why i wouldnt want to do that.
![image](https://user-images.githubusercontent.com/14083530/91882277-937caf80-ec37-11ea-8474-833c70ef3919.png)


Perhaps we make the "Dark" buttons match inputs instead? maybe? still a little hesitant to make them look like"centered" inputs

**Comment by bstifle** [comment]
another reason i am hesitant to do this, is that we wanted to have buttons that shared the same border+text color.

e.g. Dark-button on light theme = #ui-text-1
e.g. Light-button on dark theme = #ui-text-1-dark

so we'd be losing that if we change the border color. 

things to ponder.

**Comment by asangma** [comment]
I'm cool with that.
It sounds like we should look at enhancing Action to take on some of these use cases.

**Comment by bstifle** [comment]
ALSO.....

![image](https://user-images.githubusercontent.com/14083530/91883233-00dd1000-ec39-11ea-81ba-c69289e3b2c4.png)

these types of lockups would be nice to maintain. e.g. same color #151515 or ui-text-1

the more i think about this, the more i do not want to match the borders on existing buttons to match inputs.





maybe we just need a new one called input-button haha

**Comment by julio8a** [comment]
From the conversation, I'm closing this one. Please reopen if needed.
