### ISSUE TITLE
Bug: Input. input-action slot not getting focus

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#927]
### Summary
Looks like any Action or Button in Input's `input-action` slot isn't getting keyboard focus.
Can someone else see if they can repro?

### Reproduction Steps

1.

**Comment by macandcheese** [comment]
Could you post a codepen? 

Not reproducible on the demo: https://esri.github.io/calcite-components/?path=/story/components-input--with-slotted-action

**Comment by asangma** [comment]
Hmmm...weirdly it seems to be happening when it's inside a Block.
I may have to demonstrate on a local build.

**Comment by macandcheese** [comment]
Is this still an issue?

**Comment by macandcheese** [comment]
@asangma validity check ✅

**Comment by julio8a** [comment]
Checking back in on this one
