### ISSUE TITLE
Bug: Dropdown appears to trap focus.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#930]
### Summary
It seems like Dropdown traps focus.

See codepen: https://codepen.io/asangma/pen/poyWJEq

It also appears to be happening in the Storybook.

### Reproduction Steps

1. View codepen or storybook
1. tab into Dropdown
1. notice that focus disappears 
1. keep tabbing and notice that focus reappears on dropdown trigger

**Comment by asangma** [comment]
cc @AdelheidF

**Comment by macandcheese** [comment]
Resolved in https://github.com/Esri/calcite-components/pull/880

**Comment by asangma** [comment]
Sorry for the redundancy.

**Comment by macandcheese** [comment]
No prob, feel free to keep this open until it can be verified if need be ✅
