### ISSUE TITLE
Enhancement: Add Arrows / or other visual cue so users know how to edit time values

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#932]
In the Time Picker, it is not clear that you can scroll through the numbers using arrow keys or type in new values. It would be nice if there was a visual indicator about how to to edit the time values:

![image](https://user-images.githubusercontent.com/50747646/91915892-947e0300-ec70-11ea-9a1b-d0525e3a64b7.png)

@jcfranco

**Comment by jcfranco** [comment]
The time picker input component has visual cues for updating time values: https://esri.github.io/calcite-components/?path=/story/components-controls-time-input-time-picker--light-theme. 

Closing.
