### ISSUE TITLE
Bug: Date Calendar can appear too narrow 

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#934]
Noticed in Map Viewer Beta Time Configuration, the calendar can often appear too narrow, especially on smaller screens. 
It was suggested that it might be better if the calendar could be added as a pop-over. https://github.com/Esri/calcite-components/issues/188#issuecomment-567674950

![image](https://user-images.githubusercontent.com/50747646/91916630-71545300-ec72-11ea-842f-326d58a3a9ed.png)

cc @AdelheidF @jcfranco

**Comment by AdelheidF** [comment]
Still a valid request...
