### ISSUE TITLE
Bug: calcite-input type=number / up/down arrows create rounding issues

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#936]
### Summary

```
        <calcite-input
          type="number"
          value={`${value}`}
          scale="s"
          onCalciteInputInput={this.handleValueChange}
        ></calcite-input>
```

If I start e.g. with value 10.123 and click the up arrow a few times the number displays with too many decimals. Adding `step=1` doesn't change that.

<img src=https://user-images.githubusercontent.com/44481292/92045735-200d9780-ed36-11ea-81e4-01d18cae4a36.png width=200/>
<img src=https://user-images.githubusercontent.com/44481292/92045747-2865d280-ed36-11ea-904a-b26b939dfdd1.png width=200/>
<img src=https://user-images.githubusercontent.com/44481292/92045759-31ef3a80-ed36-11ea-89ce-68c7428772d3.png width=200/>

### Reproduction Steps

1.

**Comment by AdelheidF** [comment]
I still see this happening...

**Comment by AdelheidF** [comment]
This is still happening.

**Comment by AdelheidF** [comment]
This is still happening.

**Comment by paulcpederson** [comment]
@AdelheidF I've opened a pr to fix this because I can't stand to watch you battle the github bot any longer

**Comment by paulcpederson** [comment]
@AdelheidF I think this made it into beta.52

**Comment by AdelheidF** [comment]
yes, this is good now.
