### ISSUE TITLE
Enhancement: Refactor value-list and value-list-item to use sortable-list

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#940]
### Description
Might be nice if value-list could utilize calcite-sortable-list and calcite-handle.

### Acceptance Criteria 
Consistent api and UI.

#### Which Component

- value-list
- value-list-item

#### Comment from Alan:
@jcfranco Do you think we could also add a disableSelect property? (I know the name is all verb-y but we currently have disableDeselect.

We have cases where a value-list is mostly for displaying what items have been chosen and for allowing dnd reordering. And showing a selected state is non-relevant.

https://github.com/Esri/calcite-app-components/issues/889

**Comment by julio8a** [comment]
Is this one still valid?

**Comment by julio8a** [comment]
This one still valid?
