### ISSUE TITLE
Enhancement: being able to collapse the color picker

### ISSUE THREAD

**Issue by pemberdom** [Esri/calcite-components#950]
#### Which Component
`calcite-color`

### Description
It could be useful for some users to display the color picker in a collapsed state.

From the current fully component (size "m"):

![image](https://user-images.githubusercontent.com/45367780/92526623-aa447880-f1da-11ea-8cd1-7478b4fe52cb.png)

We could have a caret to collapse the component, that would be then displayed in a single line.
The single line would display either the Hex input, or the RGB/HSV inputs, and an icon showing the selected color:

![image](https://user-images.githubusercontent.com/45367780/92526803-e8da3300-f1da-11ea-864e-af0a4605a0b6.png)

Clicking again on the caret would expand the component to its original state.

We could imagine an attribute to initialize the component in the desired state (ie `collapsed` = `true` | `false`), and another attribute to choose what to display when collapsed (ie `single-line-display-type` = `hex` | `rgb` | `hsv`).

**Comment by bstifle** [comment]
heyo, we have something like this in the works, and i think it would be cool if we had a way to make the full color picker pop up after clicking the swatch. heres the comp

![image](https://user-images.githubusercontent.com/14083530/92537587-4d07f180-f1f1-11ea-8b6c-37818f70e9f5.png)

**Comment by pemberdom** [comment]
> heyo, we have something like this in the works, and i think it would be cool if we had a way to make the full color picker pop up after clicking the swatch. heres the comp
> 
> ![image](https://user-images.githubusercontent.com/14083530/92537587-4d07f180-f1f1-11ea-8b6c-37818f70e9f5.png)

That looks good 👍!

**Comment by jcfranco** [comment]
Closing in favor of #1616.
