### ISSUE TITLE
Bug: disabled state of calcite-button inside calcite-input in v1.0.0-beta.38 version

### ISSUE THREAD

**Issue by svlesiv** [Esri/calcite-components#951]
### Summary
Calcite-button as Calcite-input action is getting the disabled state in the newer version of Calcite (v1.0.0-beta.38).

### Reproduction Steps

1. Create calcite-input with calcite-button as its action using Calcite v1.0.0-beta.37 and v1.0.0-beta.38 versions.
2. Calcite-button in v1.0.0-beta.38 version will be disabled.

### Relevant Info 
Calcite v1.0.0-beta.37: https://codepen.io/svlesiv/pen/yLOvqoZ
Calcite v1.0.0-beta.38: https://codepen.io/svlesiv/pen/xxVYJpw

**Comment by macandcheese** [comment]
Should be fixed in https://github.com/Esri/calcite-components/pull/952 - sorry about that!

**Comment by svlesiv** [comment]
Awesome. Thank you!
