### ISSUE TITLE
Bug: [date + label] native calendar shows up in Firefox for a label-wrapped date

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#953]
### Summary

Wrapping `calcite-date` with `calcite-label` will cause the native calendar to show up after making a selection in Firefox.

![54bf9a00-f1e1-11ea-928a-892ff6e1010a](https://user-images.githubusercontent.com/197440/92613412-ce9e6480-f26f-11ea-9080-99e1ab070882.png)

### Actual Behavior

See image.

### Expected Behavior

Native calendar picker not displayed.

### Reproduction Steps

Open the following pen in FF to see the issue: https://codepen.io/jcfranco-the-scripter/pen/LYNdpqR

### Relevant Info 

Firefox! 🔥

**Comment by jcfranco** [comment]
Upon further investigation this issue is unrelated to positioning (updated title/description). I'll move up the Popper improvement to a separate issue.

**Comment by macandcheese** [comment]
Related: https://github.com/Esri/calcite-components/issues/931#issuecomment-689197320

**Comment by macandcheese** [comment]
Closing this @jcfranco - Codepen out of date with latest markup, feel free to re-open if this still happens but I think it's solved?

**Comment by jcfranco** [comment]
Updated codepen. Verified this is fixed, thanks!
