### ISSUE TITLE
Enhancement: Dropdown - use an icon instead of HTML char for selected item

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#957]
### Description

Different fonts render the HTML char differently.. Avenir looks great but, for instance Roboto, doesn't really work:

<img width="376" alt="Screen Shot 2020-09-09 at 2 00 14 PM" src="https://user-images.githubusercontent.com/4733155/92654539-cdd3f580-f2a4-11ea-93c4-c71e90a7aaed.png">

<img width="376" alt="Screen Shot 2020-09-09 at 1 48 22 PM" src="https://user-images.githubusercontent.com/4733155/92653502-4d60c500-f2a3-11ea-9b75-4eb48ac124ee.png">

We also use an icon for multiple selection (checkmark), so this would be consistent with that.

### Acceptance Criteria 
Use an icon in some form to make the selection indicator consistent no matter what font is used. There isn't a "bullet" icon, but maybe we could shrink another down.

#### Which Component

Calcite-dropdown.

**Comment by bstifle** [comment]
yes icon nice!

**Comment by macandcheese** [comment]
@kat10140 no has not been fixed yet just low-ish priority 😬

**Comment by driskull** [comment]
Do we have an icon for this? a dot?

**Comment by driskull** [comment]
@julio8a I think we need a bullet icon to do this.

**Comment by julio8a** [comment]
we need an icon, I'll create an issue/request in the calcite-ui-icons repository.

**Comment by driskull** [comment]
Should we move this issue to next sprint then since it is blocked?

**Comment by julio8a** [comment]
verified on storybook
