### ISSUE TITLE
Enhancement: ActionBar & ActionPad. Add scale property that its Actions inherit.

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#962]
### Description
Add a `scale` property to ActionBar and ActionPad.
The main issue is that we set the scale on the expand action inside ActionBar, so if a user wants to set all their Actions to `scale="s"`, the expand Action is still `scale="m"`.

### Acceptance Criteria 
* Actions inherit the scale property (including expand Action)

#### Which Component
* Action
* ActionBar
* ActionPad

#### Example Use Case
Setting all Actions in an ActionBar to `scale="s"`.

CAC Issue: https://github.com/Esri/calcite-app-components/issues/1033

**Comment by julio8a** [comment]
- action already has scales.
- action bar has a refactoring issue for scales
- I'll add an action pad refactor issue for scales as well. 

Closing this one.
