### ISSUE TITLE
Enhancement: Block - add a header-menu-actions slot like Panel

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#963]
### Description
Wiring up the same UX in Block is hard and often sees devs using calcite-dropdown and looks like this.
<img width="322" alt="Screen Shot 2020-03-25 at 2 22 01 PM" src="https://user-images.githubusercontent.com/12503298/77587035-6536bf00-6ea4-11ea-9e06-5ea101c7e07e.png">

Would be nice if Block could do what ~FlowItem~ Panel does using the same pattern.
<img width="286" alt="Screen Shot 2020-03-25 at 2 23 26 PM" src="https://user-images.githubusercontent.com/12503298/77587091-7da6d980-6ea4-11ea-802b-8475acae3ef3.png">

### Acceptance Criteria 

- don't break the control slot?
- use same pattern as ~FlowItem's~ Panel's `header-menu-actions`

#### Which Component
Block

#### Example Use Case
Any time we need actions coming out of a `...` menu.

**Comment by kat10140** [comment]
https://github.com/Esri/calcite-app-components/issues/894

**Comment by macandcheese** [comment]
Can we just use dropdown with `selection-mode:none` - so there isn't the indication of selection there?

<img width="270" alt="Screen Shot 2020-09-10 at 11 04 24 AM" src="https://user-images.githubusercontent.com/4733155/92777829-704bb180-f355-11ea-9961-9e38192b3f3c.png">

**Comment by asangma** [comment]
@jcfranco @caripizza Bringing this one back up. Seems like often when someone uses Block, they need to hand-roll a popover for menu actions.

**Comment by jcfranco** [comment]
@asangma Couple of questions for you:

1. When the user slots in actions, should the toggle icon still be displayed or is it dropped in favor of the menu? If we do need to show it do we place it before the toggle icon?

    ![Screen Shot 2021-06-22 at 3 12 50 PM](https://user-images.githubusercontent.com/197440/123006406-7357e180-d36c-11eb-8340-ffd7ff7f625f.png)

2. (Revisiting https://github.com/Esri/calcite-app-components/issues/894#issuecomment-636106949) Can users still slot a control along with menu actions? Or does one supersede the other?

**Comment by macandcheese** [comment]
This change has created a weird moment in our icon search. We currently slot an action when chips are selected beneath (ignore the incorrect color overrides, this is just a local build). 

This causes the caret affordance to disappear (blinking is just video recording):


https://user-images.githubusercontent.com/4733155/123008033-07c34380-d36f-11eb-97c3-a58d3d2ce792.mp4

**Comment by jcfranco** [comment]
@macandcheese Can you share a snippet? I think it may be unrelated. As far as I can tell, there haven't been any installs related to this issue yet.

**Comment by jcfranco** [comment]
@asangma 🔊  https://github.com/Esri/calcite-components/issues/963#issuecomment-866379004

**Comment by asangma** [comment]
We may also want to retain the ability to "overload" the `control` slot.
That is to say, if Actions are added to `header-menu-actions`, we'd treat them like Panel does but use the Block's `control` slot.

And if Actions (or whatever) are also added directly to the `control` slot, we'd honor that. The `...` Action to open the menu would just always stay at the end of the header (right in LTR and left in RTL).

**Comment by jcfranco** [comment]
Installed.

**Comment by jcfranco** [comment]
@kat10140 Can you help verify this one? If not, let us know if you want us to reassign it. Thanks!

**Comment by julio8a** [comment]
Verified on master
