### ISSUE TITLE
New Component: new generic list component for pick and value lists

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#965]
### Description
A new generic list component to be used between `calcite-pick-list` and `calcite-value-list`

### Acceptance Criteria 
More generic and reusable! 

### Helpful Details
A good start would be extracting from `calcite-pick-list` as it is now

CAC issue: https://github.com/Esri/calcite-app-components/issues/1006

**Comment by jcfranco** [comment]
This was superseded by https://github.com/Esri/calcite-components/issues/2117.
