### ISSUE TITLE
Docs: Add overview page for web component resources

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#966]
Adding a page with web component resources could help users start out with our components.

cac issue: https://github.com/Esri/calcite-app-components/issues/827

**Comment by caripizza** [comment]
Hi @kat10140 - what exactly (and where) are you hoping to have this new documentation added? Are you thinking of different resources other than what we have on the main readme here?
https://github.com/Esri/calcite-components/blob/master/conventions/README.md#general-guidelines
