### ISSUE TITLE
Bug: calcite-action - label property seems to have no purpose

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#967]
### Summary
calcite-action - label property seems to have no purpose.

<img src=https://user-images.githubusercontent.com/44481292/81992266-f1897680-95f7-11ea-852c-bdb9cbaf8303.png width=350/>

It doesn't appear on hover and it's not populated automatically from text. It's not creating an arial-label either.

(1)
<img src=https://user-images.githubusercontent.com/44481292/81992463-56dd6780-95f8-11ea-9dce-253de4dad3ee.png width=350/>

<img src=https://user-images.githubusercontent.com/44481292/81992091-9a83a180-95f7-11ea-9d9c-fe3f7103b653.png width=350/>

(2)
<img src=https://user-images.githubusercontent.com/44481292/81992673-e256f880-95f8-11ea-9db5-7a26f77827b7.png width=350/>

<img src=https://user-images.githubusercontent.com/44481292/81992692-f1d64180-95f8-11ea-8e4a-7290ecbfa603.png width=350/>

### Reproduction Steps

1.

### Relevant Info 

cac issue: https://github.com/Esri/calcite-app-components/issues/981

**Comment by bstifle** [comment]
@kat10140 Is this issue still valid?

**Comment by kat10140** [comment]
@bstifle yes i'll take care of it tomorrow

**Comment by jcfranco** [comment]
Closing based on #1518. Verified that label does set shadow DOM button's `aria-label` attribute.
