### ISSUE TITLE
Enhancement: PickList & PickListItem. Add "appearance" prop with "clear" as available option.

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#970]
### Description
Update PickList and PickListItem to have a transparent bg-color.
<img width="240" alt="Screen Shot 2020-05-12 at 2 24 28 PM" src="https://user-images.githubusercontent.com/12503298/81747146-70e24300-945c-11ea-9d42-2bb6748fa116.png">

#### User Stories
User wants to create a PickList that is visually distinct from other PickLists such as for a list of options that will trigger a drill in using something like FlowItems.

### Acceptance Criteria 
* It should work with flow & flow-items.
* don't break stuff
* ~Clicking/tapping a FlowMenuItem would trigger a Flow animation into a new FlowItem~

### Helpful Details

CAC ISSUE https://github.com/Esri/calcite-app-components/issues/978

**Comment by jcfranco** [comment]
@asangma @kat10140 Is this still valid?

**Comment by julio8a** [comment]
Closing this one, please reopen if still valid.
