### ISSUE TITLE
Enhancement: Reusable border style

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#971]
**[calcite-app-border]**- let's make reusable standard border style

Should we make css or sass var?
or a mixin?

Related PR: https://github.com/Esri/calcite-app-components/pull/1015

Let's discuss @jcfranco @asangma 

CAC ISSUE https://github.com/Esri/calcite-app-components/issues/1017

**Comment by julio8a** [comment]
Is this still valid?
