### ISSUE TITLE
Bug: calcite-block-section toggle button spacing

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#972]
### Summary
if enabled spacing looks good
<img src=https://user-images.githubusercontent.com/44481292/86072684-f8990680-ba36-11ea-8ba9-47915ba639ab.png width=200/>

if disabled spacing is not good
<img src=https://user-images.githubusercontent.com/44481292/86072695-051d5f00-ba37-11ea-8eee-11e0aee95175.png width=200/>

CAC ISSUE https://github.com/Esri/calcite-app-components/issues/1027

**Comment by bstifle** [comment]
@asangma me again, do you have an eta on this issue?

**Comment by AdelheidF** [comment]
doesn't seem to happen anymore

<img src=https://user-images.githubusercontent.com/44481292/108145279-06f86900-7080-11eb-9d7a-a51bffaba8fb.png width=200/>
