### ISSUE TITLE
Enhancement: Add tooling to test onscroll event for FlowItem and Panel #842

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#973]
### Description

Enhancement: Add tooling to test onscroll event for FlowItem and Panel #842

https://github.com/Esri/calcite-app-components/pull/842#pullrequestreview-366032621

CAC ISSUE: https://github.com/Esri/calcite-app-components/issues/859

**Comment by jcfranco** [comment]
Fixed via https://github.com/Esri/calcite-components/pull/812
