### ISSUE TITLE
Enhancement: Add Expand/Collapse Calcite Action to setFocus method

### ISSUE THREAD

**Issue by rslibed** [Esri/calcite-components#974]
### Description
Add Expand/Collapse Calcite Action to setFocus method

### Relevant Info 
In order to handle focus management, app must be able to programmatically focus the Expand/Collapse calcite action button in calcite-action-bar. 

#### Which Component
calcite-action

**Comment by driskull** [comment]
Installed

**Comment by rslibed** [comment]
Verified. Fix looks good!

**Comment by jcfranco** [comment]
Closing as verified based on ☝️ .
