### ISSUE TITLE
feat(pick-list-group, pick-list-item, tip-group, tip-manager, value-list-item): add replacement text props

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-components#976]
## Summary

Deprecates `text<Name>` props in favor of `<name>` for consistency. 

The only remaining one is `textFilterPlaceholder`. Not sure if this should be `filterPlaceholder` or `intlFilterPlaceholder` instead.

CAC ISSUE: https://github.com/Esri/calcite-app-components/pull/1060

**Comment by jcfranco** [comment]
Fixed via 0b198c53
