### ISSUE TITLE
Bug: I18N-FORM: Date-Calendar picker is not localized

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#979]
Related Map Viewer Beta issue:
https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/1913

Steps:

- Prepare a clean zh-CN Win10 64bit OS.
- Login in to devext.arcgis.com with admin account.
- Launch Map Viewer beta and click "+ Add layer".
- Add time layer and click Map properties.
- Click Time slider options.
- Click box under Start date.
- Observe.

Actual Result:

The calendar is not localized in Start date/End date/Date option on Time slider options pane.

Please see the attachment "zhcn_calendar.jpg" for details.
![image](https://user-images.githubusercontent.com/50747646/92982048-65764700-f451-11ea-80e4-29c574001f20.png)

cc @jcfranco

**Comment by paulcpederson** [comment]
This should be in the latest release.

**Comment by Olga8614** [comment]
We verified this defect on AGOL 8.3 Production site(10/12/2020) in zh-CN/AR/RO languages on FF/Chrome/Edge(chromium)/Safari browsers. The calendar still not localized in Start date/End date/Date option on Time slider options pane. So this defect still occurs. Thanks!

**Comment by Olga8614** [comment]
@paulcpederson

**Comment by paulcpederson** [comment]
@Olga8614 they aren't using this version of calcite components yet, so it won't be fixed until they use the right one...
