### ISSUE TITLE
Provide short medium and long INTL format for date picker

### ISSUE THREAD

**Issue by kumarGayu** [Esri/calcite-components#98]
One requirement for DatePicker is to support the INTL format this has been an issue with Datepickers in the past as we support 30+ languages
Support for short, medium and long formats as mentioned INTL format

https://github.com/Esri/calcite-components/pull/92

**Comment by macandcheese** [comment]
I believe @paulcpederson added locale support in his latest refactor of `calcite-date`

**Comment by paulcpederson** [comment]
I addressed formatting the text in the input properly based on locale, but didn't add the ability to display the date with `"full", "long", "medium", "short"` for `dateStyle`:

| style | result |
| ---- | ------ |
| short | 4/1/20 |
| long | April 1, 2020 |
| full | Wednesday, April 1, 2020 |
| medium | Apr 1, 2020 |

**Comment by paulcpederson** [comment]
Right now we are always using short, but it is localized. IMO, the date length is low-priority but I'm not sure where the original requirement came from.

**Comment by julio8a** [comment]
Following up on this issue.
