### ISSUE TITLE
Refactor: getElementProp needs to be revisited

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#981]
### Summary

`getElementProp` is misleading from a naming and implementation perspective and needs to be revisited.

**Current implementation**

```ts
export function getElementProp(el: HTMLElement, prop: string, value: any): any {
  const closestWithProp = el.closest(`[${prop}]`);
  return closestWithProp ? closestWithProp.getAttribute(prop) : value;
}
```

1. `getElementProp` reads as a helper to get a prop, but it will actually get an attribute (string) OR whatever fallback value is provided.
2. The `prop` argument is used to build the selector for searching. This will only work for single-word props, e.g., will always fail for `someName` (prop), where the attribute  is `some-name`.
3. Some usages of the fallback `value` argument have non-string types. This will lead to a mismatch or confusion on the expected value:

```ts
this.aBooleanProp = getElementProp(el, "a-boolean", false); // if a match is found it will return a string (getAttribute)
```

### Proposal

Refactor `getElementProp` to:

`export function getElementProp(el: HTMLElement, prop: string, value: T): T ;`

1. convert the prop name to an attribute when building the selector
1. look at an element's property 
1. update the type so that the fallback matches the expected return value

Introduce `getElementAttr`, which would be based on ☝

`export function getElementAttr(el: HTMLElement, attr: string, value: string): string ;`

1. use `attr` arg to build selector
1. look at an element's attribute 
1. update the return type and fallback value type to be string (matching what `getAttribute` returns)

**Comment by jcfranco** [comment]
Thoughts on this, @Esri/calcite-components devs?

**Comment by macandcheese** [comment]
![](https://thumbs.gfycat.com/MeagerCreepyFoal-size_restricted.gif)

**Comment by julio8a** [comment]
This one still valid @jcfranco ?

**Comment by geospatialem** [comment]
Closing this issue in favor of #3757. Content has been placed in the epic.
