### ISSUE TITLE
Bug: fab button overlaps open calendar

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#989]
### Summary
`calcite-date` with `calcite-fab`

<img src=https://user-images.githubusercontent.com/44481292/93235966-1c651200-f733-11ea-830f-92f8e4670cd9.png width=200/>

Maybe it's related to this issue https://github.com/Esri/calcite-components/issues/755

### Reproduction Steps

1.

**Comment by Olga8614** [comment]
https://github.com/ArcGIS/I18N-BYS-Bugs/issues/5116

**Comment by AdelheidF** [comment]
That seems to be fixed now. Thanks.
