### ISSUE TITLE
Bug:  FAB padding doesnt always give enough room for whats underneath at the bottom of a panel in firefox

### ISSUE THREAD

**Issue by CodeBarker** [Esri/calcite-components#993]
### Summary
On firefox the FAB button isnt getting the padding that is should... best place to see this is the MVB popup config
### Actual Behavior
here it is on firefox
![image](https://user-images.githubusercontent.com/3944714/93257103-5f8ea780-f76a-11ea-936c-4f7740dfe52e.png)

### Expected Behavior
here it is in chrome/edge
![image](https://user-images.githubusercontent.com/3944714/93257121-65848880-f76a-11ea-8526-1587300b5fc9.png)

### Reproduction Steps
1. Launch Map Viewer beta and add a layer. 
2. Click the layer and click Configure pop-ups tab. 
3 Turn on Enable pop-ups button and click +Add content button. 
4. Add three or more Charts or Image contents on Pop-ups panel. (key step) 
5. Observe 'Add media' and '+ Add content' buttons at the bottom in Pop-ups panel.

**Comment by macandcheese** [comment]
@CodeBarker is this still a valid issue?

**Comment by CodeBarker** [comment]
yup 
![image](https://user-images.githubusercontent.com/3944714/130503255-a8a1786e-8f12-48d1-b819-6d60dece1966.png)
