### ISSUE TITLE
Enhancement: Improve alignment of Panel Header and Action Bar Items

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#997]
### Description
It would be nice for the min-height of a header within a panel would align with the selected action item's height. Obviously the header could increase in height past that with more text, but it would help with alignment if the min-height / padding would line up.

### Acceptance Criteria 
Probably decreasing the padding would help vs. increasing action-item size, would also create more space overall within the pane for content.

### Relevant Info 
![Group](https://user-images.githubusercontent.com/4733155/93373774-a8963880-f80a-11ea-9e24-380e4bd13790.png)

**Comment by bstifle** [comment]
@macandcheese is this still necessary? panels heights can vary based on the props used
