### ISSUE TITLE
Enhancement: [Card] Card should support strings for select / unselect tooltips

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#998]
### Description

We should accept string-attributes for dev users to pass translatable strings that we display in tooltips to indicate the state of the checkbox.

### Related
#2426 #1316 

### Acceptance Criteria 
From AGOL:

<img width="292" alt="Screen Shot 2020-09-16 at 10 59 06 AM" src="https://user-images.githubusercontent.com/4733155/93374601-c7e19580-f80b-11ea-843a-70e32a95a522.png">

#### Which Component
Card

**Comment by julio8a** [comment]
is this one related?
https://github.com/Esri/calcite-components/issues/1316

**Comment by macandcheese** [comment]
Can we prioritize #1316 and this one @julio8a ?

**Comment by julio8a** [comment]
Is this one a duplicate?
https://github.com/Esri/calcite-components/issues/2426

**Comment by macandcheese** [comment]
Related, could use that one to track. The tooltip issue linked above should also solve for that.
